### ISSUE TITLE
Database tools should be indistinguishable from magic

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#1000]
Surprise and amaze people with developer tools for building real-time, data-driven web applications they could only dream of building, and bring sheer joy and simplicity to the process of building great software.

**Comment by danielmewes** [comment]
Almost forgot about this. We should ship it with 2.0.

**Comment by coffeemug** [comment]
I think we might want to punt it the raft milestone, but I'm not sure :smile:

**Comment by Tryneus** [comment]
I'll get to this when I'm back from vacation (should be around August).

**Comment by danielmewes** [comment]
@coffeemug Yes I was considering that too. I think we might have to split this issue up. I'm pretty sure we should be shipping at least some of the magic with 2.0.

**Comment by gchpaco** [comment]
That's no good, some of it might escape.  You can only enclose it safely if all of the magic is there.

**Comment by danielmewes** [comment]
Rethinking this I'm not sure how useful a database tool indistinguishable from magic would actually be.

There already is an implementation, and I'm unsure how we could maintain the database aspect of it.
We could maybe just fork http://www.opencircuitdesign.com/magic/ and relabel it as a database tool?

**Comment by deontologician** [comment]
Database tool that's indistinguishable from magic is one that isn't real, so the solution is to fork an empty git repo

**Comment by danielmewes** [comment]
I feel like it isn't entirely clear what we should actually do here for some reason.

I was originally going by @coffeemug 's original description
> Surprise and amaze people with developer tools for building real-time, data-driven web applications they could only dream of building, and bring sheer joy and simplicity to the process of building great software.

This I think we will get done for 2.0.

However it's also clear that there's more to this.
I think in the long term we'll have to do all of these things:
* Having nothing to do with magic
* Hire some wicca
* Ship it with 2.0
* Put it in the raft milestone
* Split it up
* Enclose it safely by having all the magic there
* Fork an empty git repo

I'll probably open separate issues for these items at some point.

**Comment by deontologician** [comment]
![dead horse](http://i3.kym-cdn.com/photos/images/newsfeed/000/540/662/748.gif)

**Comment by v3ss0n** [comment]
Magic Shrooms are Strong with this team...

**Comment by danielmewes** [comment]
RethinkDB 2.0 ships with a good amount of magic out of the box. We'll add some more in the upcoming releases to fully achieve this goal.

**Comment by v3ss0n** [comment]
How about hiring David Copperfield , or Dynamo :P

**Comment by danielmewes** [comment]
@v3ss0n will keep that option in mind. :)

**Comment by danielmewes** [comment]
I think this deserves some serious consideration for 2.1.

**Comment by v3ss0n** [comment]
Yes Please!! And please live stream it for those who can't come to States :D

**Comment by danielmewes** [comment]
The magic is being packed up right now.

**Comment by v3ss0n** [comment]
This bag of magic shouldn't be closed! keep it open!!

**Comment by danielmewes** [comment]
@v3ss0n don't worry, this is just for transfer. It's easy to unpack again once we've distributed the packages.
