### ISSUE TITLE
Add exclusive or (xor) to RQL

### ISSUE THREAD

**Issue by skizzerz** [rethinkdb/rethinkdb#1018]
Currently we have and() and or() inside of RQL, but no xor(), so this enhancement request is meant to correct that.

For python and ruby, the operator symbol could be ^, which is already in use as the bitwise xor operator in C, C++, etc. and would match the current convention with & and | being used for logical and and logical or, respectively (for clarification this request is for logical xor, e.g. returns true if both sides are either both true or both false, and false if one side is true and the other is false).

**Comment by srh** [comment]
Closing because it's old.  You can use `!=` or `.ne` depending on driver language to get logical xor behavior.

(Note that the OP got the return values backwards.)
