### ISSUE TITLE
RQL Proposal: Make Between not use `null` to denote unboundedness

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#1023]
See issue #1001.

**Comment by timmaxw** [comment]
Extending `datum_t` to support `r.minval` and `r.maxval`, but not letting them be serialized or returned, seems like a major hack. But I don't have a better idea.

**Comment by coffeemug** [comment]
We could let them be serialized if we wanted to. JavaScript supports `Infinity`, Python supports `float("inf")`, and Ruby probably has a similar concept.

I note `r.maxval` and `Infinity` aren't exactly the same thing, but that's one way the drivers could treat the serialized value that doesn't seem insane to me.

**Comment by timmaxw** [comment]
Another option would be to introduce a new pseudo-type for `r.minval` and `r.maxval`.

**Comment by deontologician** [comment]
I think that would be confusing because `inf` doesn't have the same semantics as `r.maxval` across types. And I don't think they're worth introducing a new pseudotype for just so they could be returned.

**Comment by deontologician** [comment]
Sorry, to clarify, I think it should be ok to be able to return them from a reql function that uses them in some way, just not serialized

**Comment by mlucy** [comment]
@coffeemug -- `r.maxval` isn't just an infinitely large number, it's larger than everything else (including all strings and all pseudotypes).  I don't think there's a good equivalent of that in our client languages.

@timmaxw -- I think we should implement it as a pseudotype internally just because it's easier (that's also how we do `r.literal`), but I still think we shouldn't send it to the user or write it to disk because that probably has the potential to be really really confusing.

**Comment by gchpaco** [comment]
> Another option would be to introduce a new pseudo-type for `r.minval` and `r.maxval`.

I'm down with this idea.  @mlucy, I don't think we can get away with not having them serializable *to the cluster*.  Not serializable *to the disk* is a different issue.  It would be ... difficult to forcibly prevent it from leaking to users, as I understand the driver end.  How do you propose doing it?

I too had the "well but +INF and -INF" idea, but as @mlucy points out the fact that these terms have to have special casing with our other ordering constraints means they have a legitimate reason to exist.

**Comment by mlucy** [comment]
Sorry for the imprecision, they definitely have to be cluster-serializable.

We already have a bunch of code to make sure `r.literal` pseudotypes can't get written to disk or sent to the user; I hope to just re-use all of that.

**Comment by coffeemug** [comment]
I retract the whole `inf` thing. That was a dumb idea.

**Comment by danielmewes** [comment]
I think it's fine to not allow serializing (except cluster-serialiazation) or returning `r.minval` and `r.maxval`.
We can also add that option later if users ask for it.

**Comment by Tryneus** [comment]
I could see it being useful storing `r.minval` or `r.maxval` in a row, especially if users have a table they use to parameterize queries, or perhaps once we make custom resharding schemes possible.  As for returning it to clients, we could have the pseudotype convert back to the original term (seeing as they are constants).

**Comment by mlucy** [comment]
This was apparently settled back in 2014, but fortunately we seem to still agree with the old decision.  Planning to leave this settled on Monday.

**Comment by danielmewes** [comment]
@VeXocide or @Tryneus please pick this up when you are done with other 2.0 issues (whoever comes first).

**Comment by Tryneus** [comment]
Working on this.

**Comment by Tryneus** [comment]
This has been implemented and merged to `next` in commits 701b2cf, 9692c8c, and 96400b5.  Will be in release 2.0.

**Comment by AtnNn** [comment]
@tryneus: in the Data Explorer I get

```
>>> r.minval()
RqlDriverError: Expected 1 argument but found 0.
```

**Comment by AtnNn** [comment]
My bad. It should be `r.minval` not `r.minval()`.

**Comment by gchpaco** [comment]
Derp, I should have chimed in earlier.  These terms did not get added to the pretty printer's list of non-stringable terms, so they'll come out all stupid.  Reopening and assigning to myself.

**Comment by gchpaco** [comment]
CR 2693.
