### ISSUE TITLE
Use new node streams interface

### ISSUE THREAD

**Issue by wmrowan** [rethinkdb/rethinkdb#1037]
Once #1022 is resolved and we do drop support for node versions prior to 0.10, we should replace the networking code in the driver with a simpler version that leverages the new node streams interface. Though the existing code has worked so far, this change will greatly reduce our code complexity.

**Comment by thelinuxlich** [comment]
@srh maybe this is obsolete?

**Comment by srh** [comment]
Will close.  If any node users want the driver API to change or be extended, be sure to bring up that issue.
