### ISSUE TITLE
Confusing behavior with multiple comparison syntax in python

### ISSUE THREAD

**Issue by jdoliner** [rethinkdb/rethinkdb#1040]
We currently have a very confusing behavior if people try to use mutliple comparison syntax in python. Observe:

``` Python
>>> r.expr(1).do(lambda x: 0 < x < 2)
<RqlQuery instance: r.expr(1).do(lambda var_3: (var_3 < 2)) >
```

basically we just drop the first comparison. This is because `0 < x < 2` is desgured to `0 < x and x < 2` by python and python then python evaluates `a and b` to `b` if it considers both `a` and `b` to be true.

I'm actually not sure we can do anything here. But I'm curious to see if anyone else has an idea. At the very least we should document this.

**Comment by srh** [comment]
Can't do anything about it.
