### ISSUE TITLE
Expose and document exprJSON

### ISSUE THREAD

**Issue by wmrowan** [rethinkdb/rethinkdb#1090]
There are currently three ways to serialize an object in the drivers.

1. `r.expr(obj)` converts it to a tree of datums and uses protobuf serialization, this is slow
2. `r.json(JSON.stringify(obj))` uses native JSON serialization, this is pretty fast
3. `r.exprJSON(obj)` is used by `insert` to convert the parts of the object which can be to JSON. For a large pure JSON object this imposes a penalty over option 2 but is still faster than option 1 for mixed objects (those that have a little bit of ReQL code burried somewhere) that can't be handled by option 2.

Currently, option 3 is an internal helper used to implement `insert`. We should probably expose this to users and document it so they can use it elsewhere they want to.

N.B. While `insert` uses method 3 by default and all other uses method 1 by default, any of the three behaviors can be forced by manually wrapping the object before passing it into a ReQL api function.

**Comment by Tryneus** [comment]
Closing this as obsolete - the Python driver no longer uses protobufs, and so exprJSON no longer exists.
