### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by GammaNu** [rethinkdb/rethinkdb#1100]
Windows compatibility could be a good thing for wamp-like dev environnement. be able to test a project with a dummy local db is easyer than binding in dev config file to use a distant one (for windows developer of course)

**Comment by githubUser919** [comment]
:+1:

**Comment by vilic** [comment]
looking forward to it.

**Comment by evmek** [comment]
+1

**Comment by lekojson** [comment]
+1

**Comment by jasonhansel** [comment]
It would be nice if RethinkDB (or someone else) provided a pre-made Vagrantfile to make running RethinkDB on Windows easier.

**Comment by danielmewes** [comment]
@jasonhansel have you checked out https://github.com/zoontek/vagrant-rethinkdb by @zoontek? I haven't tried it myself yet, but it looks interesting.

**Comment by jasonhansel** [comment]
Unfortunately, both of them use the `ubuntu/trusty64` box, which doesn't work on my Windows machine due to its lack of Hyper-V support. I tried to use a different box without success.

**Comment by zoontek** [comment]
@jasonhansel Hyper-V is highly available on Windows (actually, it's a Microsoft technology).
Try to check in your BIOS, i'ts deactivated by default.

**Comment by jhermsmeier** [comment]
@jasonhansel You should be able to enable Hyper-V through the Control Panel, it's in the Programs and Features dialog; and says "Turn Windows Features on or off".
@zoontek the BIOS should have nothing to do with Hyper-V directly, those are just options regarding hardware processor virtualization (by the CPU), which of course, as you said, should be enabled as well for everything to run nicely (it's not necessary though, afaik).

**Comment by luisrudge** [comment]
:+1:

**Comment by RaitoBezarius** [comment]
:+1:

**Comment by explorer2309** [comment]
+1

**Comment by graphnode** [comment]
:+1:

**Comment by andreikun** [comment]
It would be very helpful if you can provide us a vagrant box, already configured Ubuntu with RethinkDB :)

**Comment by chrisvariety** [comment]
@andreikun this might work! https://github.com/kwcto/rethinkdb-vagrant/blob/parallels/Vagrantfile no promises :ok_hand:

**Comment by danielmewes** [comment]
@andreikun have you tried https://github.com/zoontek/vagrant-rethinkdb ?

I think we should document this more dominantly on our website.

**Comment by coffeemug** [comment]
Great news everyone, this has been scheduled and development will start in a couple of days!

No ETA yet, we first have to see how quickly development progresses, but we expect to ship this in RethinkDB 2.3. Really excited about porting to Windows!

**Comment by luisrudge** [comment]
awesome work, guys!

**Comment by hsdk123** [comment]
This is really great news!!

**Comment by egeozcan** [comment]
I'm psyched, thank you! I think listening to community is one of the two things you're really good at. The second is shipping great databases^^

**Comment by coffeemug** [comment]
@egeozcan -- assuming one could only be really good at three things, this opens up a very important questions. What is the third thing we should get really good at? :smile:

**Comment by oliverjanik** [comment]
Marketing?  ;-) 

Seriously, Windows support would rock. I hope it'll run as a windows service, not just console app.

**Comment by kdnmih** [comment]
:+1:

**Comment by Krishna-teja** [comment]
This is awesome news... Thanks guys!..

**Comment by AtnNn** [comment]
This is going to take a while.
![ss](https://cloud.githubusercontent.com/assets/706854/7381578/97f1f610-edb9-11e4-8586-6065861e4931.png)

**Comment by bobiblazeski** [comment]
:+1:

**Comment by Dashue** [comment]
Any estimate on this? Thanks

**Comment by coffeemug** [comment]
It's still early in development -- sorry, no ETA yet.

**Comment by vansteki** [comment]
:+1:

**Comment by joaojeronimo** [comment]
awesome!

**Comment by dkleehammer** [comment]
:+1:

**Comment by andreasbhansen** [comment]
:+1:

**Comment by jjlegendre** [comment]
Great news!

**Comment by arlair** [comment]
:+1:

**Comment by sceee** [comment]
This is really great news! Thank you very much!

**Comment by jonywtf** [comment]
+1

**Comment by bubnenkoff** [comment]
+1

**Comment by deontologician** [comment]
Misclick on mobile

**Comment by JAertgeerts** [comment]
+1

**Comment by dzolnjan** [comment]
+1

**Comment by daviddiasfront** [comment]
+1

**Comment by mesosteros** [comment]
:+1:

**Comment by azukaar** [comment]
+1

**Comment by deontologician** [comment]
For future +1-ers, could you also note what language you would ideally use to connect to RethinkDB with?

**Comment by jamescostian** [comment]
:+1: and I use PHP and Node

**Comment by pascalberger** [comment]
+1. Use from C#/.NET

**Comment by herby** [comment]
Node.js, Python, Pharo Smalltalk ;-)

**Comment by futurechan** [comment]
Node.js and C#/.Net

**Comment by mesosteros** [comment]
Elixir.

**Comment by bobiblazeski** [comment]
Node.js

**Comment by JAertgeerts** [comment]
C# / .NET / JavaScript 

    _____________________________

**Comment by sceee** [comment]
C#/ASP.NET using the rethinkdb-net driver by mfennia and my own aspnet-identity-rethinkdb project for using ASP.NET Identity with RethinkDB.

**Comment by egeozcan** [comment]
For me the most important is .NET then go, node.js and Java.

**Comment by hsdk123** [comment]
For me, golang, node.js, then .NET

**Comment by danielmewes** [comment]
@egeozcan In general it has issues that we are considering for the release after the one we are currently working on, where release means something like going from 2.0.x to 2.1.x. It doesn't necessarily mean that all issues in `subsequent` will make it into it.
In this specific case, we think that it will be around RethinkDB 2.3, though this isn't absolutely fixed yet.

**Comment by xmachine** [comment]
May be u guys can consider C# for windows... but it is  good to see at-least it is under development :)

**Comment by jamescostian** [comment]
@xmachine rewriting all of the code in C# would take ages

**Comment by EugeneHlushko** [comment]
+1... node

**Comment by danielmewes** [comment]
@xmachine Do you mean a C# driver?

**Comment by SatheesA** [comment]
+1 node and c#

**Comment by PaulBGD** [comment]
+1, although running in Vagrant works really well

**Comment by STALKER2010** [comment]
+1 for Java, C# and Python3. Nice DB, well done, devs!

**Comment by buzinas** [comment]
+1 .NET

**Comment by andokai** [comment]
+1 node

**Comment by adamjcooper** [comment]
+1 node and C#

**Comment by lekojson** [comment]
+1 node

**Comment by GeARCraft1** [comment]
+1 Java and *GROOVY*

**Comment by lucasjans** [comment]
+1 C#, Golang and Node.

**Comment by balupton** [comment]
As https://github.com/rethinkdb/rethinkdb/issues/1100#issuecomment-123806213 requests

+1 node.js (latest stable version)

We are looking at using rethinkdb for the next version of a node.js developer facing content management system, that has about 500 companies/freelancers a day using it.

**Comment by tbertenshaw** [comment]
+1 C#

**Comment by tbertenshaw** [comment]
Is there a branch somewhere where this work can be seen? A recent podcast (https://devchat.tv/js-jabber/176-jsj-rethinkdb-with-slava-akhmechet) implied this release was imminent?  Would be interested in beta testing.

**Comment by danielmewes** [comment]
@tbertenshaw it's still a bit too early for beta testing, as some last pieces are not quite working yet.

You can check out the `windows` branch https://github.com/rethinkdb/rethinkdb/tree/windows , but I would recommend waiting until it actually runs. We'll keep you updated in this thread.

**Comment by peisenmann** [comment]
@deontologician +1 node.js driver

**Comment by OlegZee** [comment]
+1 .NET C#/F#, Go

**Comment by GregoryHlavac** [comment]
+1 Good to hear there's some progress on this @danielmewes I've wanted to experiment with rethinkdb on my machine.

**Comment by Wargog** [comment]
+1 (100,000,000 really), Node.JS, PHP, C#

**Comment by dougestey** [comment]
+1

**Comment by medokin** [comment]
+1

**Comment by AtnNn** [comment]
The windows port is slowly taking shape:

```
$ x64/Debug/RethinkDB.exe --bind all
Running rethinkdb 2.2.0-dev-windows (debug) (MSC 190023026)...
Running on Some Windows version
Loading data from directory C:\Users\atnnn\Documents\Visual~1\Projects\rethinkdb\rethinkdb_data
Our server ID is fbc43a33-79e8-4306-bfb5-be085e38e451
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on addresses: 127.0.0.1, 192.168.0.173
Server ready, "OKHO_tgu" fbc43a33-79e8-4306-bfb5-be085e38e451
```

![windows-query](https://cloud.githubusercontent.com/assets/706854/10554010/4bcab9e8-742d-11e5-9f5b-4c12b5da30a0.png)

**Comment by hsdk123** [comment]
@AtnNn This looks mighty good-!

**Comment by coffeemug** [comment]
@AtnNn -- that's awesome!! Hopefully I'll see you in NC next week to pass preliminary congrats in person!

> `Running on Some Windows version`

Is there actually an API call that returns a string `Some Windows` on Windows? :grimacing:

**Comment by NicolasParada** [comment]
Great :D

**Comment by GeARCraft1** [comment]
In What language are you building the Some Windows version??

**Comment by AtnNn** [comment]
"Some Windows " is actually 8.1. The server is written in C++, it is the same codebase as on linux and OSX.

**Comment by GeARCraft1** [comment]
Oh, Nice! If you need help, I think I can help with C# (.NET) integrating it on the code.
+1 for C#

Thank you,
Gabriel

**Comment by danielmewes** [comment]
@GeARCraft1 If you want to help with a C# driver, you might want to look at these projects:
https://github.com/mfenniak/rethinkdb-net
https://github.com/bchavez/RethinkDb.Driver

**Comment by howdoicomputer** [comment]
Honestly, I would be less interested in a Windows port and more interested in the Docker project taking off for Windows. Right now there is already so much momentum with developers and projects building their software using a UNIX tool chain that the only hope I have for ever using Windows for development is Docker from within a Linux guest.

**Comment by Wargog** [comment]
Well, for those of us who using a Linux guest doesn't ever want to connect to anything on that guest no matter what they do *cough* me, we would like a Windows port :)

**Comment by srsgores** [comment]
+ 1

**Comment by winnerf** [comment]
+1

**Comment by AtnNn** [comment]
Here's a preview of RethinkDB for Windows. Only tested on Windows 8 so far:

https://ipfs.io/ipfs/QmUyxHeRXHeXBNp8bfTH5JJYJjKXQgH3JR2kGcVnnoGmKu/RethinkDB-windows-alpha1.zip

**Comment by danielmewes** [comment]
@AtnNn That's so awesome! I'll try it once I get my hand on a Windows PC.

**Comment by ha1331** [comment]
tried. Had chrome complain something about malware. 
![rethinkmalware](https://cloud.githubusercontent.com/assets/8921895/11202993/65dcf688-8cf7-11e5-837b-bf2070afd7d4.PNG)

Just double clicked the .exe and it runs on command prompt. Complains about errno -1 
![malwareerrors](https://cloud.githubusercontent.com/assets/8921895/11203008/9cc2144e-8cf7-11e5-804a-d89bad37226a.PNG)

After some time, I get this in the admin console:

Error

The request to retrieve data failed. You can try to refresh.

Error:

Problem with reading log file on server `ha_workstation_s8x`: file IO error: could not open 'C:\Users\ha1331\AppData\Local\Temp\Rar$EXa0.579\rethinkdb_data\log_file' for reading. (errno = No error) in:
r.db("rethinkdb").table("logs", {identifierFormat: "uuid"}).orderBy({index: r.desc("id")}).limit(5).map(function(var_14) { return var_14.merge({server: r.db("rethinkdb").table("server_config").get(var_14("server"))("name"), server_id: var_14("server")}); })
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 

Still pretty cool thing... to be running rethinkdb on windows.

**Comment by AtnNn** [comment]
Thanks for testing @ha1331. I will try to fix the logs and the graph.

It should not contain any malware. It was built from the `windows` branch in this repo.

```
$ md5sum RethinkDB-windows-alpha1.*
491ff82d649475c9529f4dea440e5ebe  RethinkDB-windows-alpha1.exe
6a3b2b6dc7493145548e35cd5b10063b  RethinkDB-windows-alpha1.zip
```

**Comment by ha1331** [comment]
Oh, I didn't think it actually contains malware, just included that there in case somebody else tries it and gets the same. I haven't seen chrome do that before, so it was kind of interesting.

**Comment by srsgores** [comment]
It doesn't contain any malware.  I was able to run on Windows 8 x64.  But not sure, what's supposed to happen when I navigate to localhost?  Currently, I get nothing.

**Comment by AtnNn** [comment]
@srsgores While rethinkdb is running, the web ui should be accessible on port 8080 by default. When you say you get nothing, what does that mean? Is there an error, in that case which one? Is there an html document that seems empty? If so, does the JavaScript console report any errors? Have you tried with a different browser? Does the log contain any errors?

**Comment by srsgores** [comment]
@AtnNn, just nothing.  Seems like nothing's serving to that port...

**Comment by ha1331** [comment]
also running Windows 8 x64, but I get admin interface when I navigate to http://localhost:8080/ 

@srsgores did it say "listening for administrative HTTP connections on port 8080" when you started it?

**Comment by srsgores** [comment]
@ha1331, it worked when I navigated to ``localhost:8080``.  And I get this message on the dashboard:

> Error:

Problem with reading log file on server `DESKTOP_IEOITEF_dkv`: file IO error: could not open 'C:\Users\seang\Downloads\Compressed\RethinkDB-windows-alpha1\rethinkdb_data\log_file' for reading. (errno = No error) in:
r.db("rethinkdb").table("logs", {identifierFormat: "uuid"}).orderBy({index: r.desc("id")}).limit(5).map(function(var_30) { return var_30.merge({server: r.db("rethinkdb").table("server_config").get(var_30("server"))("name"), server_id: var_30("server")}); })

**Comment by ha1331** [comment]
@srsgores Glad you got that figured out. That logging problem is being handled by @AtnNn. I mentioned the same thing and he responded: "Thanks for testing @ha1331. I will try to fix the logs and the graph." 

It's still Alpha after all :)

**Comment by winnerf** [comment]
Whata fuck is this on 5 am you fucktards

**Comment by jamescostian** [comment]
@winnerf feel free to unsubscribe from this issue, set up do not disturb on your phone or other device, and move on

**Comment by ha1331** [comment]
@winnerf No need to be rude. We fucktards are fragile tards. :(

**Comment by winnerf** [comment]
So sorry for my comment… :(

**Comment by tgienger** [comment]
@AtnNn Just downloaded alpha onto Windows 10 x64 (latest release). Running and browser points to the admin panel. I shall commence testing! What, if anything, can I *not* do on this alpha release?

**Comment by AtnNn** [comment]
@tgienger you might notice a few weird things in the UI as pointed out above. I don't know exactly what was in that build. I believe `r.js` was broken.

**Comment by eliashdezr** [comment]
Is there a nightly builds for the Windows alpha?

**Comment by danielmewes** [comment]
> Is there a nightly builds for the Windows alpha?

Not at the moment.

@AtnNn if it's not too much work, could you upload a new binary some time soon? Maybe after you've fixed the log file issue?

**Comment by fdcastel** [comment]
Great work, guys!

Just for the sake of curiosity: what's the difference between "windows" and "windows2" branches in this repo? Which one should a dilettante developer look at? :)

**Comment by maboiteaspam** [comment]
fyi,
![image](https://cloud.githubusercontent.com/assets/530732/11712131/0cc833d8-9f66-11e5-8456-bfef4ea5a56d.png)

windows7@chinese edition with the build provided by AtnNn.

**Comment by coffeemug** [comment]
This function is only available on Windows 8 and above -- the current port doesn't work on Windows 7. We might want to make it work on Windows 7, but I'm not sure it's worth it -- I haven't looked at the percentage of users still on it.

**Comment by bchavez** [comment]
+1 for windows 7 =_)

**Comment by AtnNn** [comment]
@fdcastel The `windows` branch contains the latest changes.

**Comment by herby** [comment]
+1 win7. I would say lots of people still use Windows 7, it's similarly "too good to upgrade" as XP was in its days. I also do, for example (I tried the W10, but it have buggy drivers, hw working on w7 just fails on w10).

**Comment by danielmewes** [comment]
I opened https://github.com/rethinkdb/rethinkdb/issues/5194 for Windows 7 compatibility.
I agree that it's important. Many Windows users I know are running Windows 7.

**Comment by bmrpatel** [comment]
:+1:  Great work guys

**Comment by AtnNn** [comment]
Here's a new build of the windows branch. Sorry, we don't have nightlies.

[/ipfs/QmeaNpgJd2Uwharad1o1dcDx9K1m3i93vx7BUkiEcCJqi5/RethinkDB-windows-alpha2.zip](https://ipfs.io/ipfs/QmeaNpgJd2Uwharad1o1dcDx9K1m3i93vx7BUkiEcCJqi5/RethinkDB-windows-alpha2.zip)

Most of the issues mentioned above have been fixed, including support for `r.js`. It might also now work on Windows 7 or Vista, but I haven't been able to test that yet (my development machine is a Chromebook).

**Comment by maboiteaspam** [comment]
![image](https://cloud.githubusercontent.com/assets/530732/11829906/36a74544-a3db-11e5-81de-e652122ae048.png)

Not sure what this is related with. Maybe this is about the chinese edition i m running here.

**Comment by AtnNn** [comment]
@maboîteàspam That looks like #5194.

**Comment by maboiteaspam** [comment]
ok, i ll follow there if you publish another build.

**Comment by datamats** [comment]
```
C:\rethinkdb>RethinkDB-windows-alpha2.exe
Running rethinkdb 2.2-windows-alpha2 (debug) (MSC 190023506)...
Running on 6.2.9200 (Windows 8, Server 2012)
Loading data from directory C:\rethinkdb\rethinkdb_data
Our server ID is 9379c8c6-d707-4198-91fa-231a7dc89401
Listening for intracluster connections on port 29015
```
And then it just stops without any error or crash.

**Comment by STALKER2010** [comment]
Facing the same failure to start RethinkDB after shutdown by Ctrl+C.

**Comment by AtnNn** [comment]
@datamats @STALKER2010 I was unable to reproduce that issue on my own. If your `rethinkdb_data/` folder is not too big and you don't mind sharing it, could you please zip it up and send it to atnnn@rethinkdb.com?

**Comment by Jonnyfromnothing** [comment]
I'm getting the same issue as @Datamats & @STALKER2010. 
If it's useful I'm using windows 10 on a surface pro 4.

**Comment by fractalawareness** [comment]
The same issue here, Win10 x64 Surface Pro 3

**Comment by tychota** [comment]
@AtnNn 

# Context
not on windows but sometimes having to work on windows or deploy on windows

# Proposal

https://www.appveyor.com/ (free for open source) can build (a la travis) some nightly for windows. I can actualy fork this repo and do it myself, but I think it would be better if it is done here.

Is it possible for you guys to configure it ? If not, would you find helpful that I fork and build it myself ?

**Comment by AtnNn** [comment]
@tychota Building RethinkDB on Windows is a fragile operation with lots of parts, I don't think it will be straightforward to get it to run on AppVeyor. It also takes a very long time. We used to let Travis build RethinkDB, but it instead it timed out or ran out of memory.

**Comment by tychota** [comment]
Mmh oki :) Sorry for noise, in this case.

--------

As other, when I restart server, it crashes. Else evrything working fine.

**Comment by AtnNn** [comment]
Here's another alpha build that fixes the issue mentioned above and should work on Windows 7.

http://circus.atnnn.com/ipfs/QmbF14Tn4HLkRtRFgz64JiunEHE6DaGPaLf15Mrz8ugHzL/rethinkdb-windows-alpha3.zip

**Comment by Jonnyfromnothing** [comment]
@AtnNn Just tested the latest alpha on windows 10 seems to be working fine there too

**Comment by STALKER2010** [comment]
@AtnNn Works ok, no more crashes on startup with Windows 10. Thanks, looking forward to the release version!

**Comment by wannado** [comment]
:100:

**Comment by bmrpatel** [comment]
:+1:

**Comment by luisrudge** [comment]
I love you all! :tada:

**Comment by danielmewes** [comment]
We have just released an official developer preview of RethinkDB for Windows: http://rethinkdb.com/blog/rethinkdb-windows-preview/

This build is fully functional, but not recommended for production use yet.
It will also run more slowly since it's compiled with additional debugging code for better testing.

2.3.0 is going to be the first release with a full Windows build available at launch.

**Comment by herby** [comment]
Nice. ;-)

Daniel Mewes wrote:

**Comment by howdoicomputer** [comment]
Wooooah, niiiiiice. I plan on testing this out later tonight for my side project. Will we see a Chocolatey package?

**Comment by danielmewes** [comment]
> Will we see a Chocolatey package?

Not sure yet. Maybe later once we have the stable release. It looks pretty neat though.

**Comment by jamescostian** [comment]
Congrats! This is awesome!

**Comment by andokai** [comment]
Kudos!

**Comment by unclepaul84** [comment]
Is installing as windows service supported?

**Comment by danielmewes** [comment]
@unclepaul84 Not yet, but we're working on it.

**Comment by danielmewes** [comment]
We're going to release a beta version of RethinkDB 2.3.0 for Windows soon.
