### ISSUE TITLE
Authentication for web admin

### ISSUE THREAD

**Issue by HorizonNet** [rethinkdb/rethinkdb#1163]
It would be helpful to add an authentication mechanism to the web admin. That would make remote administration more secure.

**Comment by somenxavier** [comment]
[This](http://www.reitermayer.org/nginx-rethinkdb/) is the only way it works for me.

**Comment by uchuugaka** [comment]
Is it still accurate that there is no built-in web (http/https) log in, just automatically the admin user?
Yikes. That's a real gotcha.
