### ISSUE TITLE
Enforce UTF-8 encoding of strings

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#1181]
There are many inconsistencies in the treatment of strings. It should probably be standardised across drivers and reql functions, and documented.

The python driver refuses non-ascii strings unless they are unicode:

```
python> r.expr('\xc1').run()
  File "/Library/Python/2.7/site-packages/google/protobuf/internal/type_checkers.py", line 128, in CheckValue
    (proposed_value))
ValueError: '\xc1' has type str, but isn't in 7-bit ASCII encoding. Non-ASCII strings must be converted to unicode objects before being added.
```

The ruby driver lets you use strings that are not utf8:

```
ruby> r.expr("\xc1").run
=> "\301"
```

The python drivers fails badly when receiving a non-utf8 string:

```
ruby> r.table('foo').insert({:a=>"\xc1"}).run

python> r.table('foo').run()
  File "/Library/Python/2.7/site-packages/google/protobuf/internal/decoder.py", line 410, in DecodeField
    field_dict[key] = local_unicode(buffer[pos:new_pos], 'utf-8')
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc1 in position 0: invalid start byte
```

`r.js` expects strings to be utf-8, and gets confused when they are not:

```
ruby> r.expr("\xc1").do(r.js('(function(x){ return x; })')).run
=> "\357\277\275"
```

`r.match` also expects utf-8:

```
ruby> r.expr("a").match(".").run
=> {"groups"=>[], "end"=>1, "str"=>"a", "start"=>0}

ruby> r.expr("\xc1").match(".").run
=> nil
```

Other reql functions that use operations from C++'s `std::string` (such as comparison operators) simply treat strings as arrays of bytes.

The JSON spec says that

> A string is a sequence of zero or more Unicode characters, wrapped in double quotes

This affects issues such as #264, #874, #1099 and #1147.

Issue #137 complements this issue by proposing a separate binary data type.

**Comment by gchpaco** [comment]
In `next` now, we enforce UTF-8 on input strings.  When I get some other stuff done, I will be able to fix `split` to be safe, at which point it should not be easy to insert invalid UTF-8 strings into the database.  Not included here is any form of locale support, which is the `toupper`/`tolower` stuff as well as collation; I feel that's grist for a different mill.

@danielmewes Do you want me to close this now, or wait until we get `split` in?

**Comment by gchpaco** [comment]
Per private discussion, there's a followup ticket for that in #3531.
