### ISSUE TITLE
Allow for curried functions.

### ISSUE THREAD

**Issue by jdoliner** [rethinkdb/rethinkdb#1190]
I think we could make a number of awesome additions to our syntax by adding curried functions to our language. Passing functions is an integral part of our language at this point but it can get verbose quickly. It's important to keep in mind throughout this issue that there are drivers written in languages besides Ruby. @mlucy you use the argument "this is only marginally better than the alternative in Ruby" far too often and it leads to a protocol designed around Ruby.

The basic idea of a curried function is that you can construct a new function by passing an existing function fewer arguments than it normally takes. For example `r.add` is a function which normally takes 2 arguments (actually it's variadic right now but we'll talk about that later). If we allow for curried functions then `r.add` could be passed wherever we accept a 2 argument function, in particular it can be passed to reduce like so:

``` Javascript
// old version
r.table("foo").reduce(function (left, right) { return left.add(right); })
// with currying
r.table("foo").reduce(r.add)
```

Currying also allows you to pass a single argument to a binary function to create a unary function. Suppose you have a stream of numbers and want to add one to them:

``` Javascript
stream.map(r.add(1))
```

this also gets really nice if you add a pattern matching version of update. Consider the use case of incrementing a field:

``` Javascript
// old version
r.table("foo").update(function (doc) { return {"counter" : doc("counter").add(1)}; })

// can be made shorter with r.row but that doesn't work in nested cases
r.table("foo").update({"counter" : r.row("counter").add(1))

// curried version, works everywhere
r.table("foo").update({"counter" : r.add(1)})
```

Curried functions are also absolutely awesome if you combine them with pattern matching `filter` syntax. For example consider the case of wanting to check if a user wrote a particular article:

``` Javascript
// old version
r.table("foo").filter(function (doc) {return  doc("articles").contains(id);})

// curried version
r.table("foo").filter({"articles" : r.contains(id)})
```

I'm sure there are a bunch of other places we can find where curried functions are awesome.

---

It was pointed out by @mlucy that currying doesn't play nicely with variadic functions. I'm not 100% sure that it's impossible to have both although it seems like it might be. However I think that the syntax here is nice enough that it would be worth sacrificing variadic functions. I really don't think they're that useful to be honest. Basically all code I've seen written in Ruby and Python use infix `+` rather than variadic `r.add` and in Javascript people mostly do `foo.add(1)` rather than `r.add(foo, 1).

**Comment by avimar** [comment]
Just to throw in an example: I'm using lodash-fp in my node.js projects for the auto-currying to make the code cleaner than using lodash.

**Comment by srh** [comment]
I think Clojure's syntax `#(+ %1 %2)` is the thing to emulate here, it avoids ambiguity.

`r.fn(r._.add(r._2))`
`r.fn.add(r._, r._2)`
`function(x, y) { return x.add(y); }`

For what it's worth this could already be implemented in any driver.

**Comment by thelinuxlich** [comment]
@srh if it belongs to userland and there are many terms which lose context if trying to use partially, shouldn't this be closed?
