### ISSUE TITLE
configure script autocompletes to "--without-<module>" and "--with-<module>"

### ISSUE THREAD

**Issue by srh** [rethinkdb/rethinkdb#1202]
Type the argument `--with` and press TAB.  You'll get this:

```
[16:03:38] sam@newton:~/rethinkdb$ ./configure CXX=clang++ --with
--with-<module>     --without-<module>  
```

Type any further and you'll get `--without-<module>` or `--with-<module>` autocompleted onto the command line.

**Comment by AtnNn** [comment]
I am unsable to reproduce. Closing as outdated.
