### ISSUE TITLE
Chaining dbList and tableList

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#1221]
```
r.dbList().forEach(function(db) {
  return r.expr({
    name: db,
    tables: r.db(db).tableList()
  })
})
```

This query doesn't work with map instead of forEach

And it returns one database with all the tables (including those in other databases)  instead of all databases with its own tables.

**Comment by danielmewes** [comment]
Something similar just came up on Google groups and this now works (based on @coffeemug's response):
`r.dbList().map(function(db) { return {db: db, tables: r.db(db).tableList()}; })`

I'm not sure I fully understand what the original problem was, but it seems to be fixed.
