### ISSUE TITLE
re errors are printed on the terminal

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#1236]
If I make a mistake and write a bad regex, I get errors in the terminal where I started RethinkDB

Something like that
```
re2/re2.cc:196: Error parsing '/^([0-9]_/': missing ): /^([0-9]_/
```

I guess it's not that bad, but it would be nice to not fill the logs with `re` errors.

**Comment by danielmewes** [comment]
I can no longer reproduce this. Looks like it has been fixed.
