### ISSUE TITLE
Clearer documentation/notation on performing legacy/non-eventfd builds

### ISSUE THREAD

**Issue by t3hmrman** [rethinkdb/rethinkdb#1247]
So I am using a kernel that is so old that sys/eventfd.h is not available (and I do not have the freedom to update the kernel) -- I wanted to ask that the configure help be updated to clearly show these option:

LEGACY_LINUX=1 
NO_EVENTFD=1

I know it's a small case, but in my case they are necessary options and every time I reinstall I have to remember to add them (amongst other things) to make the install go smoothly.

**Comment by AtnNn** [comment]
These options are mentioned in `mk/README.md`.

**Comment by t3hmrman** [comment]
Thanks! :D
