### ISSUE TITLE
Update with https

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#1251]
We should:
- Have the interface be able to get the last version with the https protocol (it now only uses http regardless of the current protocol used)
- Have the update server works with https (with a valid certificate).

**Comment by danielmewes** [comment]
Related to https://github.com/rethinkdb/rethinkdb/issues/3489
Once we have https on our web server we should just switch it over.

**Comment by srh** [comment]
It seems we use https now.
