### ISSUE TITLE
Count Queries Painfully Slow

### ISSUE THREAD

**Issue by dbettin** [rethinkdb/rethinkdb#1271]
I talked to @jdoliner about this issue on IRC yesterday. But, I thought it would be worth my time to create an issue regarding the problem.

I have a large table ~30,000 documents, each document is ~150K and when I run a straightforward count query 

`r.table('mytable').count().run(conn)`

it either takes a long time to complete or errors out.

Evidence:

http://snapnote.io/0o4zZT
http://snapnote.io/dw3pRh

In my mind this a major issue and should be addressed before RethinkDB is production ready. Thoughts?

**Comment by PrakashThapa** [comment]
RethinkDB `count()` function is always slow.I testing it since 1.12 till the latest stable. the table count might be fine but once there are intermediate opetation it simple cannot be use. very slow.

**Comment by danielmewes** [comment]
@PrakashThapa This is probably because the intermediate operations cause RethinkDB to compute every result item before counting it. For certain types of operations (specifically `getAll` and `between` operations), we will make counts very fast with https://github.com/rethinkdb/rethinkdb/issues/3949. This is still a few releases away though unfortunately.

**Comment by lucasjans** [comment]
@danielmewes is this getting any closer? we need to be able to do `.count` against indexes (getall or between). our data set has 7mb records and it is far too slow. engineering our own solution outside Rethink is complexity I would prefer to avoid.

**Comment by danielmewes** [comment]
@lucasjans The solution outlined in https://github.com/rethinkdb/rethinkdb/issues/3949#issuecomment-84143955 is going to solve your use case. However I can't tell for sure yet when we will ship this, as it's only one among a bunch of other features we are working on.
