### ISSUE TITLE
Measure write performance in cluster settings

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#1277]
The user has a cluster of seven EC2 nodes, configured to have seven shards and two replicas.

He has two clients connecting to random rethinkdb nodes, running an insert workload (on EC2/EBS, though I'm not sure that's relevant). On his setup, the sharded setup results in a smaller write throughput than a single node setup.

We need to test this scenario and find out what's going on.

Assigning to @Tryneus.

**Comment by danielmewes** [comment]
We had tested this for the 2.0 performance report and it appeared to scale fine (after some further optimizations).
