### ISSUE TITLE
Improve message error on non valid timezone

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#1280]
```
r.now().inTimezone('-4')
```

Returns

```
RqlRuntimeError: Truncated date string `-4`. in:
r.now().inTimezone("-4")
^^^^^^^^^^^^^^^^^^^^^^^^
```

It would be nice to tell them the valid timezone.
Assigning to @mlucy

**Comment by dineyw23** [comment]
Hi, 
I thought I could try working on this, [here](https://github.com/rethinkdb/rethinkdb/blob/0ec7cc90061bb7cd4f38b52cfea9bc9767a78d5f/src/rdb_protocol/pseudo_time.cc). I believe the valid timezone are:

`±hh:mm, ±hhmm, ±hh and Z`

Right?

**Comment by danielmewes** [comment]
> I believe the valid timezone are:

I'm not 100% sure. @mlucy do you know?

**Comment by mlucy** [comment]
Yes, that's right.

**Comment by dineyw23** [comment]
Thanks.
Based on the other errors. How about something like thing?

![sample](https://cloud.githubusercontent.com/assets/10092343/14100762/a6096650-f544-11e5-9bfe-b68849067dfc.png)

**Comment by danielmewes** [comment]
@dineyw23 Thanks for working on this first of all.

I think the message is almost good, but I would set the backticks around each alternative rather than around the whole list:
> Invalid time zone string `-1`. Valid time zone formats are `+-hh:mm`, `+-hhmm` `+-hh` and `z`.

(except with the single +/- character that you're using)

**Comment by mlucy** [comment]
I would personally vote for `+hh:mm, -hh:mm` instead of `±hh:mm` just to avoid having unusual characters in an error message.

**Comment by danielmewes** [comment]
:+1: on whatever @mlucy says :)
