### ISSUE TITLE
Make r.now evaluate once per query.

### ISSUE THREAD

**Issue by jdoliner** [rethinkdb/rethinkdb#1282]
Currently if someone does the following:

```Python
r.table("foo").index_create(r.now())
```

They'll get a constant index for the creation time which is pretty useless.

Instead we should record the time each query is received in the global optargs and have `r.now()` evaluate to that value. This way that query does what users expect.

**Comment by danielmewes** [comment]
I think we'll disallow `r.now` in secondary index functions as per https://github.com/rethinkdb/rethinkdb/issues/5472 , and then think about a way for getting something closer to the behavior described here for TTL and changefeeds (there already is some discussion in other issues, which numbers I don't have at hand right now).
