### ISSUE TITLE
ReQL proposal: Passing ReQL api functions as well as lambdas

### ISSUE THREAD

**Issue by wmrowan** [rethinkdb/rethinkdb#1320]
Currently we officially support and recommend the following syntax:

``` python
r.expr([1,2]).reduce(lambda x,y: x + y)
```

It just so happens though that our current implementation (at least in the Python driver) is agnostic to the type and origin of the passed function. The following also works (though currently blocked by an unrelated bug in next):

``` python
r.expr([1,2]).reduce(r.add)
```

This proposal is to standardize this form, make sure it is available in all drivers, and document it as a real feature.

**Comment by thelinuxlich** [comment]
@srh I think #1312 already covers this
