### ISSUE TITLE
Bootstrap v3

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/rethinkdb#1342]
Bootstrap upgraded to v3 and has deprecated v2. We use a number of JS libraries and features of Bootstrap to provide the skeleton for the web UI.

We should decide on one of the following:
- Upgrade to v3
- Decide that we're going to continue patching problems with browser bugs, etc. as they come up
- Analyze how we use Bootstrap and remove as many components as we can to move away from it.

Moving to backlog-- this issue is to prompt a discussion with @neumino and @coffeemug.

**Comment by danielmewes** [comment]
@mglukhovsky Is this still up to date?

**Comment by mglukhovsky** [comment]
@danielmewes: I'd like to remove our use of Bootstrap altogether, and move from using LESS to using SASS with Bourbon + Neat. This isn't an urgent project, however.

**Comment by danielmewes** [comment]
Got it, thanks for the update.
What do you think are the main benefits of that transition?

**Comment by thelinuxlich** [comment]
@srh since this issue was opened, Bootstrap V4 was released and many JS frameworks rose to power. If we do a UI overhaul on the data explorer, I don't think we will even use bootstrap .
