### ISSUE TITLE
Soft-durability writes are disk-bound on rotational drives

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#1357]
We cap out at about 13k writes/sec with 64-byte values.  That's something like a megabyte/sec in disk throughput, which seems pretty bad.

(This number is for a two-node cluster using one disk, but goes up for a two-node cluster using two disks or if you use an SSD.  The number is a little lower for a one-node cluster using one disk.)

**Comment by danielmewes** [comment]
This has improved a lot since then.
