### ISSUE TITLE
failed index creation in python driver fails slowly

### ISSUE THREAD

**Issue by underrun** [rethinkdb/rethinkdb#1370]
i tried to create an index a table using the data explorer and it "failed" - meaning the web interface said their was a timeout, but apparently the index was actually being created.

following that i tried to create the index using the python driver, but it took 10 minutes to fail with the error: Index `somefield` already exists.

My table is 7M+ docs of ~2k each (+/- 1k).

I ran it again and it failed faster this time (maybe because the index is already finished being created and previously it was still not finished?) and here's what I got:

```
$ time python -c "import rethinkdb as r; r.connect().repl(); r.db('test').table('sometable').index_create('somefield').run()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/rethinkdb/ast.py", line 106, in run
    return c._start(self, **global_opt_args)
  File "/usr/lib64/python2.7/site-packages/rethinkdb/net.py", line 159, in _start
    return self._send_query(query, term, global_opt_args)
  File "/usr/lib64/python2.7/site-packages/rethinkdb/net.py", line 229, in _send_query
    raise RqlRuntimeError(message, term, frames)
rethinkdb.errors.RqlRuntimeError: Index `somefield` already exists. in:
r.db('test').table('sometable').index_create('somefield')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

real	0m26.455s
user	0m0.056s
sys	0m0.008s
```

**Comment by danielmewes** [comment]
Pretty sure this has been fixed a while ago.
