### ISSUE TITLE
ReQL proposal: `r.fromXML`

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#1393]
``` javascript
r.fromXML('<hello>world</hello>')
// => { hello: 'world' }
```

Backlog, for obvious reasons.

**Comment by lonnietc** [comment]
Greetings All,

I have been wondering  about the use of XML from within RethinkDB and it occurred to me that perhaps it would be possible to take advantage of the built-in V8 Javascript engine to allow for the storage and use of user extensible procedures and methods to enhance RethinkDB.

Actually, I was looking over the RethinkDB documents and C/C++ on github as well and noticed in the documentation that the ReQL has a r.js() method which allows for Javascript which is then run on the embedded V8 Javascript engine. It seems that the r.js() implementation is reall just for small Javascript functions and the like, but a quick thought occurred to me that perhaps if there was a way to t.js("load somefile.js") then it would be very easy to load in a Javascript function or library ( i.e. a vanilla Javascript XML library perhaps like https://github.com/abdmob/x2js) that could be called from within the ReQL in which the V8 engine could run as part of stored ReQL procedures and extensible ReQL methods.

Just a thought that I had and it might allow for xml and other Javascript based methods to be used from within ReQL.

Cheers and have a good day,
Lonnie

**Comment by srh** [comment]
Moving to super-backlog.
