### ISSUE TITLE
Promises/A+ for JS driver

### ISSUE THREAD

**Issue by jamescostian** [rethinkdb/rethinkdb#1395]
I would like to suggest that the JS driver use the [Promises/A+ spec](http://promises-aplus.github.io/promises-spec/). Callbacks are very important to support because they are the de-facto style, but that doesn't mean that promises should be unsupported. Modules _can_ return a promise and still call a callback, allowing both to work. If you're on the fence with regards to promises, just consider that the following 2 examples do the same thing:

``` js
r.connect({ host: 'localhost', port: 28015 }, function(err, conn) {
  if(err) throw err;
  r.db('test').tableCreate('tv_shows').run(conn, function(err, res) {
    if(err) throw err;
    console.log(res);
    r.table('tv_shows').insert({ name: 'Star Trek TNG' }).run(conn, function(err, res)
    {
      if(err) throw err;
      console.log(res);
    });
  });
});
```

NB: the following uses [gen-run](https://github.com/creationix/gen-run) and JS ES6

``` js
var run = require('gen-run');
run(function* () {
  var conn = yield r.connect({ host: 'localhost', port: 28015 });
  console.log(yield r.db('test').tableCreate('tv_shows').run(conn));
  console.log(yield r.table('tv_shows').insert({ name: 'Star Trek TNG' }).run(conn));
});
```

**Comment by lolwhoami** [comment]
How about promises with `update()` (and probably all other `writing` functions)?

**Comment by deontologician** [comment]
@lolwhoami this is a pretty old issue. Would you mind opening a new issue if you have a feature request?

**Comment by goatic** [comment]
Is there full fletched promise support in the Node driver as of now? Looking over the docs, there's plenty of asynchronous commands that document supporting callbacks, but not promises (thenable/awaitables). For example `dbDrop`,`dbList` etc.

btw, am loving what you're doing with Rethink!

**Comment by marshall007** [comment]
@goatic I don't think the promise variants are documented, but for (almost) any method that takes a callback, the callback is optional and a promise is returned.

**Comment by goatic** [comment]
excellent, was kind of expecting it to just not be documented :+1:

**Comment by danielmewes** [comment]
@goatic Note that all ReQL terms such as `dbDrop`, `dbList` etc. are non-blocking functions in JavaScript that only build up a "query object". The command that actually executes the query and that is blocking is `run`, which has both a promise- and a callback-style interface (which is documented). The examples in the individual commands are often using the callback-style I think.

**Comment by goatic** [comment]
haha - I guess I should move past the docs and get some actual work done :stuck_out_tongue_winking_eye:
