### ISSUE TITLE
indexdb and sync

### ISSUE THREAD

**Issue by ghost** [rethinkdb/rethinkdb#14]
ability to do synchronisation with client woudl be compelling.

i have been looking at pouchDB, but i find your RethinkDB compelling

Integrating client / server syc into your architecture woudl be amazing and solve many many problems as so many applications move to html5 and offline client.

**Comment by josiahsavary** [comment]
Hey @coffeemug, I've been using Rethink for the past month, and it's really great. I'm wondering has there been any more traction on synchronization features or integrations with PouchDB you're aware of?

**Comment by coffeemug** [comment]
@josiahsavary -- not that I know of yet, sorry!

**Comment by nono** [comment]
I'm also interested by rethinkdb implementing [the couchdb replication protocol](http://www.replication.io/spec), so it can be synchronized with pouchdb.

**Comment by coffeemug** [comment]
FYI, for anyone watching this -- we're on it! It won't be exactly like Pouch, but we'll allow accessing RethinkDB from the browser in a way that will make building apps that have intermittent network connections dramatically easier.

**Comment by arlair** [comment]
@coffeemug Sounds very interesting. Is there somewhere to find out more information about this? Thanks.

**Comment by coffeemug** [comment]
@arlair -- yes, I just invited you to the private repo.

**Comment by gedw99** [comment]
can i also get an invite ?

**Comment by gedw99** [comment]
I am using rethinkdb for a project where this would be very useful. so i can also feedback on typical use cases, and stability

**Comment by coffeemug** [comment]
@gedw99 -- just invited you to the project, sorry for the delay, this slipped through the cracks. /cc @mglukhovsky

**Comment by gedw99** [comment]
Awesome thanks @coffeemug
I just got the invite and added myself

**Comment by skoni** [comment]
We are using couch/pouch for online/offline sync. I would love to try RethinkDB in our case.

**Comment by danielmewes** [comment]
I'd like to note that the project we're working on is not primarily targeting offline syncing.
It's a functionality that would fit in nicely though, so we might be able to add it eventually.

**Comment by jacwright** [comment]
@coffeemug could I get access to this project?

**Comment by joeblew99** [comment]
Me too please. It's exactly what I am interested in doing also

**Comment by mglukhovsky** [comment]
@jacwright, @joeblew99: you can sign up for the developer preview of Horizon, our upcoming open-source realtime backend, by going to [horizon.io](https://horizon.io).

**Comment by joeblew99** [comment]
@mglukhovsky Thanks. wil do.

**Comment by v3ss0n** [comment]
there are already pouch based addons for local storages so how about local storage adapter that sync with rethinkdb , may be we can just use PouchDB and then develop a protocol adapter for sync.
