### ISSUE TITLE
bitwise operations

### ISSUE THREAD

**Issue by est** [rethinkdb/rethinkdb#1401]
Hello,

Could RethinkDB allow 
1. bitwise operations like AND, OR and NOT, aggregation functions like POPCOUNT
2. Apply to both Integer **and Binary data types**.

So we could make something cool like this?

http://highscalability.com/blog/2012/4/5/big-data-counting-how-to-count-a-billion-distinct-objects-us.html

MongoDB support simple bitwise operations (only to integers)

http://docs.mongodb.org/manual/reference/operator/bit/

**Comment by andrewmunsell** [comment]
Just curious, has this been considered at all recently?

**Comment by danielmewes** [comment]
@andrewmunsell It's still not scheduled, sorry.
At the moment a work-around is using `r.js` with appropriate JavaScript code ( http://rethinkdb.com/api/javascript/js/ ).

**Comment by thelinuxlich** [comment]
This could allow us some fast analytics tricks https://tech.bellycard.com/blog/light-speed-analytics-with-redis-bitmaps-and-lua/

**Comment by danielmewes** [comment]
@thelinuxlich Some interesting tricks in there. That use of bitwise operations is also somewhat related to https://github.com/rethinkdb/rethinkdb/issues/4928 .

**Comment by thelinuxlich** [comment]
Another inspiration, antirez is adding BITFIELD to Redis 3.2: http://antirez.com/news/103

**Comment by ouroboroscoding** [comment]
It's been five and a half years, is this ever going to be implemented?

**Comment by srh** [comment]
This was implemented and merged into the next branch.

**Comment by srh** [comment]
@ouroboroscoding  I'm going to reopen.  We could get this in v2.4.x.  Because why not?

Stay tuned for a 2.4 release candidate, and if it doesn't have bitwise operations, please bother me until I get it in.

**Comment by gabor-boros** [comment]
Since 2.4.0 is released with bitwise operations support, closing this issue
