### ISSUE TITLE
Fix error reporting in python driver

### ISSUE THREAD

**Issue by jdoliner** [rethinkdb/rethinkdb#1409]
Most of the exceptions in the python driver don't overload their `__repr__` method. This leads to exceptions being thrown with informative error messages but those error messages not making it to the user. One example of this I know of is that if you nest `r.row`s you won't get any indication of what went wrong.

**Comment by yograterol** [comment]
+1

**Comment by danielmewes** [comment]
@larkost Do you know if this is still true?

**Comment by larkost** [comment]
I did not immediately come up with queries to test this, but we don't have a `__repr__` on our error base-class. So I have added it on `next` with 84f49f5c and `v2.3.x` with ae93e08c.

@jdoliner: can you supply a query that triggers this?

**Comment by danielmewes** [comment]
I'm assuming this was fixed by @larkost's changes.
