### ISSUE TITLE
`get_field` errors are not caught by `default`

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#1423]
I would expect this query to return 0 but I get a RqlRuntimeError

```
r.expr(3)("value").default(0)
```

Is it an expected behavior? Why default doesn't catch the error?

**Comment by danielmewes** [comment]
I think this is outside the scope of `default` as it is now.

We should discuss a general term for catching arbitrary errors at some point (something similar was discussed in https://github.com/rethinkdb/rethinkdb/issues/2269 ).
