### ISSUE TITLE
Build counter increments by 2 instead of 1

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#1428]
On gentoo with emerge:

> zamabe> Hello. Compiling now and the counter is moving in 2 at a time instead of +1. I take it this isn't normal :p
> zamabe>    [499/293] CC src/clustering/administration/http/stat_app.cc -o build/release/obj/clustering/administration/http/stat_app.o
> 
> zamabe> Even in the install phase, [22/13] GZIP build/release/assets/rethinkdb.1.gz
> 
> zamabe> AtnNn, fun amendment to my report. Building by hand results in normal counters. Building in portage it gives +2 counters. Here's what I'm using http://bpaste.net/raw/131847/ (rethinkdb-1.9.0.ebuild)

**Comment by thelinuxlich** [comment]
@srh I believe there was a guy mantaining RethinkDB for Gentoo and this issue doesn't matter anymore
