### ISSUE TITLE
Debian Packaging

### ISSUE THREAD

**Issue by mafrosis** [rethinkdb/rethinkdb#1486]
Hey dudes, apologies if you have Debian packaging covered - I couldn't find what the current plan was for that.

Anyway, running a fresh install of 7.1 wheezy, I can install the `lucid` package and get a working rethinkdb, but if I install the `precise` version I receive this error:

    /usr/bin/rethinkdb: error while loading shared libraries: libv8.so.3.7.12.22: cannot open shared object file: No such file or directory

(I was installing `precise` as my configuration management setup normally targets Ubuntu precise; I switched to `lucid` as that's referenced in the script on anantshri.info)

Finally I'd like to add that `add-apt-repository` is provided by `python-software-properties`, so that hacky script isn't actually necessary. Edit: [see below](https://github.com/rethinkdb/rethinkdb/issues/1486#issuecomment-25220401).

Let me know if that's anything I can test for you.

**Comment by AtnNn** [comment]
Closing as outdated. We have packages for wheezy and jessie. See http://rethinkdb.com/docs/install/debian/
