### ISSUE TITLE
Write Jepsen tests for RethinkDB

### ISSUE THREAD

**Issue by novabyte** [rethinkdb/rethinkdb#1493]
[Jepsen](https://github.com/aphyr/jepsen) is a tool for simulating network partitions in databases. It's written in Clojure.

You can find out more about how to write Jensen tests here:

http://aphyr.com/posts/289-automating-jepsen

These tests would be __very__ useful in determining how RethinkDB behaves during certain kinds of network failures.

**Comment by jdunck** [comment]
When I hear about a new distribute datastore, I google "$DBNAME jepsen", and this is what got me here.

RethinkDB, if you agree that good Jepsen results would be good marketing (as I do), I think you should see if you can contract @aphyr (or a colleague) and, if not, you do it yourself, preferably with community input that You're Doing It Right.

**Comment by danielmewes** [comment]
@jdunck We definitely agree that Jepsen results are extremely useful.
We are currently in the process of re-designing a lot of our clustering logic for one of the upcoming releases, so we would however like to wait until then before putting resources into this.

**Comment by donspaulding** [comment]
@danielmewes Is 1.16 the release you were talking about?  If so, does that mean a discussion of how RethinkDB holds up against Jepsen is forthcoming?

If so... yay!

**Comment by deontologician** [comment]
@donspaulding We're moving to raft for automatic failover, that's the change he was talking about. We'll probably have a milestone for it soon, but #223 is an issue you can follow if you're interested

**Comment by timmaxw** [comment]
To be completely clear: RethinkDB 1.16 does not have automatic failover. RethinkDB 2.0 will not have automatic failover. We're actively working on automatic failover, but it requires some big changes under the hood, and we're expecting to ship sometime around April or May. We're planning to test RethinkDB against Jepsen once we've implemented automatic failover.

**Comment by wamatt** [comment]
@timmaxw thats fantastic. good luck! :)

**Comment by timmaxw** [comment]
The new [raft milestone](https://github.com/rethinkdb/rethinkdb/milestones/raft) tracks issues that need to be fixed before we can ship auto-failover.

I'm moving this issue to the raft-polish milestone; it would be nice to do it before we ship Raft, but it's not necessary.

**Comment by jwr** [comment]
I'll pitch in with a non-technical comment. I'm looking for a DB for a new project. RethinkDB looks tempting, but there is the trust issue: databases are hard, distributed databases way more so. Jepsen has become the reference: a reality check for various claims being made. After reading a Jepsen article carefully, I know whether I can trust a distributed DB to get things relatively right.

I'm writing this to suggest that once you do get auto-failover working, you should ensure that Jepsen results are published.

**Comment by danielmewes** [comment]
@mlucy is going to work on this.

**Comment by danielmewes** [comment]
@mlucy has implemented a few test scenarios with Jepsen and they're passing on the development branch.

The remaining item in this issue I think is to prepare a pull requests for the Clojure driver, and if possible one for our Jepsen adaptation as well.

The code is currently in https://github.com/rethinkdb/jepsen in the branches rdb and rdb_mongo.

**Comment by danielmewes** [comment]
@mlucy Anything else you wanted to do for this?

**Comment by danielcompton** [comment]
Happy to help with the Clojure driver, I'm a maintainer of it.

**Comment by wamatt** [comment]
@danielmewes this is great news

**Comment by aphyr** [comment]
In an attempt to make Jepsen tests more modular and less prone to breaking as core changes, I've made Jepsen into a library and split out the tests into their own projects. Take a look at, say, https://github.com/aphyr/jepsen/tree/master/disque for an example of how to structure your tests. :)

**Comment by aphyr** [comment]
Also I'm a little confused by some of the commit messages--for instance, https://github.com/rethinkdb/jepsen/commit/c0062c347523dbdff17aba6c7300e9b888ae6428 says "etcd tests" but seems mostly related to rethinkdb, not etcd...

**Comment by danielmewes** [comment]
Hi @aphyr , great news about the modularization. Assuming we can find the time, we'll try to bring the RethinkDB tests over to the new structure.
The explanation for the commit messages is that we weren't completely sure how things were working and which tests were possible when we started out, so we went to your blog and started by implementing tests from specific articles of yours. So the "etcd tests" are similar to the tests that you describe in https://aphyr.com/posts/316-call-me-maybe-etcd-and-consul , but ported to RethinkDB. Those were the first we tried, and I'm not sure if their currently committed configuration is actually very useful for testing RethinkDB at this point. The `rdb_mongo` branch has the `mongo` in it for the same reason. They try to mirror your tests from https://aphyr.com/posts/322-call-me-maybe-mongodb-stale-reads .

**Comment by danielmewes** [comment]
@mlucy will know better which commit is the most recent one and if there's anything else to keep in mind.

**Comment by mlucy** [comment]
@aphyr -- I opened a pull request with what I have at https://github.com/aphyr/jepsen/pull/70 .  It pulls the current 2.1 beta release (which is known to have bugs) from the Internet, and requires a slightly-patched version of `clj-rethinkdb` to run (I link to it in the description of the merge).  If you want to wait until the actual release to merge it I can update it to pull the right version and use the mainline `clj-rethinkdb` (which will probably support error types by then).

@danielcompton -- my changes to the clojure driver are at https://github.com/mlucy/clj-rethinkdb/tree/mlucy_error_types .  Basically we added fine-grained error types in 2.1.  The error hierarchy is changing a little before the final release (see https://github.com/rethinkdb/rethinkdb/issues/4559), but once that's in I'll update the branch and open a pull request.

**Comment by mlucy** [comment]
Marking as closed since the main task associated with this issue (running the Jepsen tests against RethinkDB 2.1 prior to release) is done.  If anyone has questions about anything in this thread, though, feel free to continue commenting here.

**Comment by lamielle** [comment]
@mlucy one small question that we could take somewhere else if necessary: what were the results of the testing?  I'm really curious to see how the tests worked, what (if anything) was found, and if anything was learned from the process.  Maybe a blog post is more appropriate?

**Comment by mlucy** [comment]
@lamielle -- they were definitely helpful to run.  I'd have to go back and look at the issue history to remember what they actually found, but I remember them being useful.  They also spurred progress on a new feature (typed errors) since the Jepsen tests distinguish between failed and indeterminate operations, and previously the only way to tell those apart was to look at the error messages.  Writing up a blog post on the process and what we found would probably be a good project.

**Comment by pmbauer** [comment]
+1; we are evaluating RethinkDB at Udacity and need a full understanding of the write guarantees and failure modes; looking forward to your Jepsen blog.

**Comment by danielmewes** [comment]
@pmbauer In case you haven't seen it yet, this page might be useful for you: http://rethinkdb.com/docs/consistency/

**Comment by coffeemug** [comment]
@pmbauer -- shoot me an email at slava@rethinkdb.com. I'd love to learn more about your use case, answer any questions, and help with the evaluation in any way I can.

**Comment by pmbauer** [comment]
@danielmewes @coffeemug thank you! We are just starting out but like what we see so far ... will reach out later this week.

**Comment by RVN-BR** [comment]
Sorry if I miss a point, but are there published results/interpretation? thks!

**Comment by coffeemug** [comment]
@RVN-BR -- not at the moment, but they should be available in a month or two.

**Comment by RVN-BR** [comment]
Great, I'll wait for that :)  I assume itl be posted here so ill keep watching the issue

thanks

**Comment by mafrosis** [comment]
https://aphyr.com/posts/329-jepsen-rethinkdb-2-1-5

**Comment by mglukhovsky** [comment]
Hey guys, as @mafrosis pointed out, the [Jepsen analysis](https://aphyr.com/posts/329-jepsen-rethinkdb-2-1-5) went live today.

From the article:
> As far as I can ascertain, RethinkDB’s safety claims are accurate. You can lose updates if you write with anything less than majority, and see assorted read anomalies with single or outdated reads, but majority/majority appears linearizable.
