### ISSUE TITLE
Rename Database and Tables.

### ISSUE THREAD

**Issue by paulmars** [rethinkdb/rethinkdb#151]
A lot of systems match the Classes to the db name and table names. Renaming them allows the data to match the code when a class is renamed.

**Comment by ravi** [comment]
The DB link and therefore the ability to rename a database seem to have disappeared in the web UI after I updated from 1.11 to 2.0. This can't be, can it?

**Comment by timmaxw** [comment]
You can rename a database via ReQL with `r.db("old_name").config().update({name: "new_name"})`. I'm not sure if it's possible via the web UI in 2.0.

**Comment by ravi** [comment]
Okay thank you, that's a decent substitute, will give it a go.

**Comment by Extarys** [comment]
Even for a 2012 question it still helps! viva rethinkDB! <3

**Comment by MrBoombastic** [comment]
Helpful even in 2020!
