### ISSUE TITLE
r.table('foo').count() should be constant time

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#152]

**Comment by malthe** [comment]
Isn't ``size`` a better term for the number of items in a table and/or index?

It makes sense that ``size`` could be trivially (cheaply) available where a ``count`` normally costs the same as a query minus the fetching of data (and probably should be avoided).

**Comment by danielmewes** [comment]
@malthe That's a decent point. On the other hand `count` as a term has the advantage that it makes clear that the number of entries is returned (and not for example their size in bytes). It probably makes more sense to think about naming when we actually have a constant-time count/size operation...

**Comment by coffeemug** [comment]
Also, SQL uses `count`, which is why we appropriated the name.

**Comment by malthe** [comment]
@coffeemug right, but count is basically ``sum(select 1 from ...)`` while the index size is not a query as such (it's a kind of metadata). I mean obviously you know this, but I think it's an important difference to communicate.

**Comment by danielmewes** [comment]
Closing in favor of https://github.com/rethinkdb/rethinkdb/issues/3949
