### ISSUE TITLE
Compound Secondary Index Speed

### ISSUE THREAD

**Issue by linuxdynasty** [rethinkdb/rethinkdb#1526]
I noticed when I was testing the speed of the queries that I have in my product, there was a significant decreases in certain queries that involved Compound Indexes.

For instance this query took Total time: 0:00:03.790848
eq_join with a compound index without a filter and using distinct()

```
r.table('apps_per_agent').get_all(['installed', 'default'], index='status_and_customer').eq_join(lambda x: [x['app_id'], 'no'], r.table('unique_applications'), index='appid_and_hidden').pluck({'right': 'app_id'}).distinct().run(conn)
```

Now this query is eq_join with an index with a filter took Total time: 0:00:01.156872
```
r.table('apps_per_agent').get_all(['installed', 'default'], index='status_and_customer').eq_join('app_id', r.table('unique_applications')).filter({'right': {'hidden': 'no'}}).pluck({'right': 'app_id'}).distinct().run(conn)
```

@jdoliner Can add more details to this, since he was working with me on this issue.

I expected the compound index to be faster than the filter when it came to the eq_join, but not in this case.

**Comment by StyxOfDynamite** [comment]
hi

**Comment by danielmewes** [comment]
Working on this.

**Comment by danielmewes** [comment]
An optimization for caching secondary index functions is in CR 3171.
I'm going to look into batching multi-key gets next, because it has showed up as a bottleneck in context of plain `getAll` as well.

**Comment by danielmewes** [comment]
After taking a brief look, I think I might need @mlucy's help on this one...

**Comment by danielmewes** [comment]
Assigning @mlucy for the multi-key `get_all` optimization.

**Comment by VeXocide** [comment]
I'll be taking over the multi-key `get_all` optimisation.

**Comment by mlucy** [comment]
The `get_all` optimization is in CR 3240 by @danielmewes .

**Comment by mlucy** [comment]
(It turned out that what we were doing in @VeXocide's branch wasn't actually sufficient for a few edge cases (truncated keys and multiple copies of the same datum in the `get_all`), and the changes were significant enough I think they warrant a new review.)

**Comment by mlucy** [comment]
It turns out this was branched off of `next`, so once the review's complete there's still a merge step, but it should be pretty trivial.

**Comment by mlucy** [comment]
This is in next and 2.1.x, will ship with RethinkDB 2.1.5.
