### ISSUE TITLE
RethinkDB shuts down slowly on rotational drive

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#1547]
Just something I've noticed which might be worth investigating:

After inserting a lot of data (~100 GB) into a single RethinkDB instance on rotational drives, I shut down the server. There was only one table, with a cache size of just 1 GB. After about 15 minutes, it is still shutting down.

What's weird is the output of `iostat -m`:
```
Device:            tps    MB_read/s    MB_wrtn/s    MB_read    MB_wrtn
sda             305.50         2.86         0.75          5          1
dm-0            201.50         0.74         0.75          1          1
dm-1            542.00         2.12         0.00          4          0
```
First of all the write throughput is extremely low at less than a MB per second. Interestingly, RethinkDB is reading more data than writing. I assume this is the garbage collector at work.
At the same time, the relatively high number of transactions (305 on sda) could indicate that it is bound by disk seeks but that's just speculation. 

The server uses only very little CPU at this point.

**Comment by danielmewes** [comment]
Closing as outdated.

**Comment by wojons** [comment]
@danielmewes do we want to test this before closing it.

**Comment by Tryneus** [comment]
If this was happening in debug mode, it may have been due to some debug checks that were performed.  I ran into that a couple months ago and removed the check as it was rather antiquated.  If this was happening in release mode, nevermind.

**Comment by wojons** [comment]
@Tryneus i can find sometime this weekened to load 2M real records into a spinning disk db and then delete it and then shutdown and see if its still happending if @danielmewes  he can assign it to me.

**Comment by danielmewes** [comment]
Yeah I closed this because the last instance I'm aware of at least was quite a while ago and we changed and fixed a lot of things since.

Please just re-open this if you see it again.
