### ISSUE TITLE
Standardize `any`, `or`, `|` situation

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#1581]
Even people who work here are confused by this.

I think the names `any` and `all` are confusing.  IMO we should use `and` and `or` in every language that allows it, and use something similar (like `and_` or something) in languages that don't.  We should also support the shortcuts `&` and `|` in languages that allow it.

Scheduling for backlog; let's try to avoid discussing this until we schedule it for a sprint.

**Comment by danielmewes** [comment]
We should remove `any` and `all` and only keep `and`/`or`.

**Comment by marshall007** [comment]
#3511 can probably be closed as a duplicate of this issue.

**Comment by danielmewes** [comment]
Thanks for noting @marshall007 . Going to close the other one as suggested.

**Comment by gchpaco** [comment]
> We should remove any and all and only keep and/or.

:+1:

**Comment by VeXocide** [comment]
:+1:

**Comment by mlucy** [comment]
Everyone seems on board with this; planning to mark it as settled on Monday.

**Comment by VeXocide** [comment]
This is in CR 2610 by @Tryneus

**Comment by VeXocide** [comment]
Merged into `next` via commit c4c6b0a
