### ISSUE TITLE
RethinkDB 1.10.1 Package won't install on OSX 10.7.5

### ISSUE THREAD

**Issue by jongirard** [rethinkdb/rethinkdb#1595]
Can't get Rethink DB (latest version from http://www.rethinkdb.com/docs/install/osx/) to install on OSX 10.7.5 using the "rethinkdb.pkg" installer.

After opening the package, the install window appears but immediately a popup appears with an error stating "Alert: x86_64 system required" only that single message, and the only option available is to click "close".

My system is indeed 64bit architecture.

**Comment by AtnNn** [comment]
@larkost Since you know OS X better than any of us, do you have any suggestions on how to best fix this?

**Comment by danielmewes** [comment]
It seems that every version starting with OS X 10.8 Mountain Lion always uses a 64 bit kernel, at least according to http://support.apple.com/en-us/HT4287 "Can I switch between the 64-bit kernel and 32-bit kernel?"

There probably aren't many people out there who still run 10.7, so I think we should just close this unless @larkost knows a better flag to test the architecture out of his head.

**Comment by larkost** [comment]
At this point we require 10.7, which in turn requires 64-bit CPUs. So we can just drop that portion of the `Distribution.xml` and still have what we need.

I have a version that does this up for review in CR 2657 from branch `larkost/1595-osx-install-requirements`

**Comment by larkost** [comment]
This has been merged into `next` with dc9c5d5
