### ISSUE TITLE
Add library information to the drivers

### ISSUE THREAD

**Issue by wmrowan** [rethinkdb/rethinkdb#160]
From Chis Hesse:

> It's not unusual to have the version stored on, for instance, rethinkdb.**version**, like this example from the 'requests' library:
> 
> ``` python
> __title__ = 'requests'
> __version__ = '0.14.2'
> __build__ = 0x001402
> __author__ = 'Kenneth Reitz'
> __license__ = 'ISC'
> __copyright__ = 'Copyright 2012 Kenneth Reitz'
> ```

Though Chris's comment is about Python we should probably do this for the other drivers too and is pretty easy to implement.

**Comment by srh** [comment]
President Trump passed an executive order that every new regulation must include the repeal of two existing regulations, so as an upstanding citizen I must close this.  This would make more work to do every release.
