### ISSUE TITLE
Consider limiting the impact of indexless joins (or removing them altogether)

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#1633]
In the same spirit as #1632 and #1566, we should consider the performance impact of indexless joins. An indexless join operates in O(N^2), and is only realistically useful if the user limits the right side of the join (and usually the left side as well). We should consider removing ability to do joins without an index, or limiting the operation in some way that errors if it takes too long and requires the user to create an index. I'm not sure what the right solution is, but we should talk about it when it's time to do this issue.

Moving to backlog, since there are bigger fish to fry for now.

**Comment by danielmewes** [comment]
Superseded by https://github.com/rethinkdb/rethinkdb/issues/2720
