### ISSUE TITLE
copy/paste doesn't work correctly in the data explorer in firefox on linux

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#1647]
These standard actions work in chrome, but not in firefox:
- Middle click -> paste from the primary selection
- Shift+Insert -> paste from the primary selection
- Select some text -> copy to the primary selection
- Control+C -> copy to the primary selection and also to the clipboard selection

**Comment by gabor-boros** [comment]
This is not an issue anymore
