### ISSUE TITLE
Web UI: add a progress bar when loading the admin app

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/rethinkdb#1651]
Roughly 2MB+ of assets need to be downloaded to make the admin app load. 

If you're not running RethinkDB locally, this takes time, and the user has to sit and wait for assets to download without feedback.

Adding a simple progress or loading page with minimal style would help mitigate this.

**Comment by lsabi** [comment]
Moved the issue into the newly created Web app repository
