### ISSUE TITLE
Test how a cluster responds to partial node failures

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#1654]
We should test how a cluster of RethinkDB nodes behaves in different local failure cases.

Here are three examples:
1. A single node becomes very slow.
2. The i/o subsystem stops responding (e.g. a disk in a server becomes defective). 
3. A node loses connectivity to a part of the remaining cluster, but not to all of it

Note that neither 1 nor 2 will (likely) cause a heartbeat timeout, so the defect is not going to be detected by the rest of the cluster.

What impact do those scenarios have on the overall cluster? More specifically on:
1. The performance and availability of unrelated tables
2. The performance and availability of tables that have shards on the failing node.
3. Whether the cluster can still be administered with respect to meta operations (e.g. reassigning shards to a different node, creating a table)

I don't know if we will be able to do this for subsequent, but I feel like it would be a good idea to at least know about possible issues before the LTS release.

**Comment by thelinuxlich** [comment]
@srh isn't this already covered by the Jepsen test?

**Comment by srh** [comment]
Number 3 is, presumably.  The first two we don't need to test because we know a bad outcome will happen.
