### ISSUE TITLE
Remove (ms) from the duration(ms) field in the profiler

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#1693]
If no one has an objection, I would like to rename field `duration(ms)` to be just `duration`.

I cannot access things with `data.duration` because of the parentheses.
And it's not pretty (that's the main reason -- it's not pretty to print the raw profile)

**Comment by danielmewes** [comment]
Let's not change this. It doesn't matter.
Eventually we'll overhaul the profiler completely and then we can consider changing the field named.
