### ISSUE TITLE
Perfomance suffers near 2.8 million docs

### ISSUE THREAD

**Issue by wojons** [rethinkdb/rethinkdb#1696]
I have a table with about 2.8 million docs according to the approxmation system. everytime i get near this number if is a cluster of machines or a single machine i start getting werid issues. For example when trying to write 200 docs i will get socket timeout errors. This insert is the only operation going on.

**Comment by danielmewes** [comment]
A lot has been improved since this issue was observed. I suspect this might have been fixed.
