### ISSUE TITLE
`r.between` returns the wrong type (table)

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#1728]
```python
> r.table('foo').between('a', 'z').typeOf()
"TABLE"
```

I believe the type should be `SELECTION<STREAM>`. We had a similar issue before (#317) -- could we add a polyglot test for this?

**Comment by danielmewes** [comment]
The query now returns `"TABLE_SLICE"`. @coffeemug do you think we should do more about this?

**Comment by coffeemug** [comment]
I'm ok with that.

**Comment by coffeemug** [comment]
Meaning, I don't think there is more to do.
