### ISSUE TITLE
Add a progress bar while flushing writes to disk on shutdown

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/rethinkdb#1735]
If a large number of documents are being inserted via soft durability, and the server receives a shutdown signal, RethinkDB will attempt to flush all dirty data absorbed by RAM to disk.

The user receives no indication that this is happening, beyond using tools like `iostat` or `iotop` to observe a high volume of disk writes.

It would be useful to add a message stating "Flushing data to disk" and a progress bar indicating how many docs / blocks remain to be flushed.

**Comment by danielmewes** [comment]
Our unwritten data limit is relatively small nowadays and we're not super slow in flushing them anymore.
I don't think this is an issue anymore.
