### ISSUE TITLE
Move drivers out of the main tree

### ISSUE THREAD

**Issue by mmalecki** [rethinkdb/rethinkdb#1740]
I noticed that all the drivers are kept in the main tree. This is problematic for developers who want to contribute to them or even just check out the source code locally.

I'd be happy to help with moving the node driver out of the tree.

**Comment by knownasilya** [comment]
Would love them moved out as well, makes it that much easier to contribute, and find the code. This has a lot to do with productivity, commit history, issues, PRs, etc. It's all merged together and that's a HUGE pain! Like I was just looking through the commit history, trying to find where Promise support was added to the Javascript driver, and I couldn't find anything.. almost 30k commits.

**Comment by deontologician** [comment]
@knownasilya If you're looking for changes that only affect a single directory, you can specify it to git log:

```
$ git log --name-status --no-merges drivers/javascript
```

**Comment by AtnNn** [comment]
For the specific problem of finding commits and tracking changes, you can use the following `git` commands:

`git blame` to find the commit that introduced a change:

```
$ git blame -- drivers/javascript/net.coffee | grep -i bluebird
02b70c7f drivers/javascript/net.coffee     (neumino       2014-03-31 17:18:38 -0700  15) Promise = require('bluebird')
```

02b70c7f (Add promises to the JS driver) is the commit you are looking for.

`git log` to show all changes in a specific subfolder:

```
$ git log --graph --oneline --decorate -- drivers/javascript/
* 4d2fd72 (tag: v1.15.0) Bump driver version numbers to 1.15.0.0
|  drivers/javascript/package.json |    2 +-
|  1 file changed, 1 insertion(+), 1 deletion(-)
* 29ab2e5 (origin/michel_3087_stack_traces_2) Create a stack trace only if Error.captureStackTrace is available
|  drivers/javascript/errors.coffee |    6 ++++--
|  1 file changed, 4 insertions(+), 2 deletions(-)
*   dc0cff0 Merge branch 'michel_3054_backtraces' into v1.15.x
|\  
| * 1b48d71 Backtrace should prefix geo terms
| |  drivers/javascript/ast.coffee |   10 +++++-----
| |  1 file changed, 5 insertions(+), 5 deletions(-)
* | 4fb062f Capture stack trace
| |  drivers/javascript/errors.coffee |    2 ++
| |  1 file changed, 2 insertions(+)
* | 23c52ce (origin/gchpaco_2185) Fix ReQL tests to reflect new style for batch operations.
|/  
|    drivers/javascript/net.coffee |   16 ++++++++++++++--
|    1 file changed, 14 insertions(+), 2 deletions(-)
* b3ca440 (origin/daniel_3011) Introduced polygon_sub term to replace sub() on polygons.
|  drivers/javascript/ast.coffee |    5 +++++
|  1 file changed, 5 insertions(+)
```

`git shortlog` to find contributors to the driver:

```
$ git shortlog -sen drivers/javascript/ | head -n 5
   149  Bill Rowan <bill@rethinkdb.com>
   112  Bill <bill@rethinkdb.com>
    81  neumino <michel@rethinkdb.com>
    63  Etienne Laurin <atnnn@rethinkdb.com>
    50  Marc Hesse <marc@rethinkdb.com>
```

**Comment by knownasilya** [comment]
Those are some nice commands, didn't know you could use `git log` on a directory. 
I've never had a chance to try out `git blame`.
`git shortlog` looks nice.

Now this is all nice and well, but once again not everyone knows how to do this, and not everyone has cloned the repo first. Really it comes down to how much you guys want to get others involved, and make on-boarding for contributors easy, which says a lot about a project.

**Comment by deontologician** [comment]
Maybe we could add some useful commands like this to the READMEs for the drivers. From past experience I can say that splitting up projects that are actually developed in lockstep into multiple repositories and using submodules or subtree merges to keep them in sync is a huge pain.

**Comment by AtnNn** [comment]
@knownasilya, I agree with you. I also believe that splitting out the drivers would encourage making the driver protocol more version-agnostic.

However https://github.com/rethinkdb/rethinkdb/issues/1740#issuecomment-29938887 above explains why this hasn't been done yet.

**Comment by knownasilya** [comment]
Is the main reason that ReQL is still changing too fast? Or is it that the web app is also bundled in this repo (should be in it's own repo as well..)?

**Comment by knownasilya** [comment]
> Maybe we could add some useful commands like this to the READMEs for the drivers.

Added #3523

**Comment by danielmewes** [comment]
@knownasilya Sorry for the late response: It's a combination of both. At the moment it makes our lives a bit easier because it's easier to keep the server and drivers in sync and to run tests at a given (even non-release) version without having to deal with separate repositories.

**Comment by joaojeronimo** [comment]
(at least for javascript (actually coffeescript in this case))

Have you guys heard about `npm link` ? I think it solves all those problems.

You can npm link a specific version, the latest version, an older version, whatever, while allowing everyone the privileges of having the driver on it's own directory.

**Comment by AtnNn** [comment]
This issue has come up again. As RethinkDB moves to being a more community-driven project, we want to make it easier to contribute to the drivers, and perhaps have separate maintainers for them.

I think those considerations outweigh the advantages of a monorepo with tight coupling.

This process would also blur the line between community drivers and official drivers. Previously, no feature was allowed to be merged unless it was supported in at least one driver, and no release was made until all four official drivers had feature parity.

The testsuite is also important to consider. Currently, tests for RethinkDB itself and for each official driver are mixed up together in an efficient but monolithic testsuite.

**Comment by kofalt** [comment]
Driver consistency is a huge plus to using RethinkDB. It would be great if that quality remained, whether via keeping it in a single repository, or some other process (merge criteria? clever CI? etc).

**Comment by knownasilya** [comment]
Or just a unified test suite that can handle all of the drivers, e.g. handle input and output but don't worry about the implementation, by running against each, so once all pass the suite you do a release.

**Comment by AtnNn** [comment]
We already have such tests, called the [polyglot tests](https://github.com/rethinkdb/rethinkdb/tree/next/test/rql_test). They have built-in support for the Ruby, JavaScript and Python drivers. Using conversion scripts, those same tests are also used to test the Java driver and [a few other drivers](https://groups.google.com/forum/#!topic/rethinkdb-dev/CxFVwbA9yNs)

**Comment by marshall007** [comment]
@AtnNn we should also consider tackling #3771 (i.e. adopting `rethinkdbdash` as the official JS driver) at the same time. I would imagine a trivial amount of work would need to go into updating the polyglot tests to run against `rethinkdbdash`. Once we start splitting out the repos, that would be an opportune time to do it.
