### ISSUE TITLE
Large delete fails, causes further operations to fail.

### ISSUE THREAD

**Issue by nergdron** [rethinkdb/rethinkdb#1761]
Per conversation on IRC with @atnnn:

I've just set up a 3 node cluster with the latest release on CentOS 6 (rethinkdb-1.11.2-1.11.2.x86_64). I pushed about 6.5M records into test.test doing some insert benchmarking, and though I'd test delete performance by timing the following:

r.db('test').table('test').delete()

I left it running last night, and when I came it, the query was still just sitting in the web UI, never completed. Now, other queries through the web UI are failing that should complete almost instantly, such as the following:

r.db('test').table('test').limit(10)

Note that all 3 systems are responsive, and the web UI still loads new pages and graph data, so the server processes don't appear to be completely dead. I'm sure if I restart the daemons, that'll clear this issue, but I thought since it's a test cluster it'd be worth investigating the problem further before I do so.

Let me know what I can do or run to get you guys further information on this problem. Log file under /var/lib/rethinkdb/default/data/log_file on each node doesn't appear to have any useful information in it.

**Comment by danielmewes** [comment]
We've done loads of improvements since. Closing the issue since it's unlikely the same problem is still around (and we have no clear way to check).
