### ISSUE TITLE
Investigate batched delete performance

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#1762]
``` python
r.table('foo').filter(lambda x: x['age']>1).delete()
r.table('foo').delete()
```

Queries of this type seem to subjectively run very slowly.

**Comment by danielmewes** [comment]
@mlucy has implemented the improvement where we only send the primary key and not the whole document to the parser. That should make these queries more efficient.

**Comment by wojons** [comment]
Wanted to let you know that in 2.0 i have a large delete 5 nodes all spinning disk shared table across allow nodes just doing a delete all rows from the database and capping out 100 records a seocnd and the cluster is idle outside of that also it has 4 or 5 indexes.

**Comment by wojons** [comment]
something that i am also noticing is i can get between 700-1.5k updates per second on the same cluster same config. Same documents. And from what i remember an update rewrites the whole document so finding it weird it takes more time to delete then to update.

**Comment by thelinuxlich** [comment]
@srh maybe close this in favor of #134 ?
