### ISSUE TITLE
Read Only mode

### ISSUE THREAD

**Issue by wojons** [rethinkdb/rethinkdb#1773]
An instresting use case i have had with mongodb when neededing to transfer data to a new node by dumping the data dir is wanting to keep the current node serving read data but not handing writes. If there was a start up flag that this node will only do read data would be AMAZING

**Comment by mike-marcacci** [comment]
This is related to https://github.com/rethinkdb/rethinkdb/issues/1805

**Comment by danielmewes** [comment]
Actually this will just become a special case of https://github.com/rethinkdb/rethinkdb/issues/4519 . You will be able to simply remove write permissions from the accounts.
