### ISSUE TITLE
Every time RethinkDB deletes a file, we should add a log entry

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#1780]
Every time RethinkDB deletes a file, we should add a log entry (preferably with information regarding what operation caused the delete). This would help us with a paper trail for issues like #1339.

**Comment by danielmewes** [comment]
There has been another issue where this information would have been helpful https://github.com/rethinkdb/rethinkdb/issues/3717 .
We should do this asap, possibly in a 1.16 point release.

@gchpaco , @Tryneus any takers?

**Comment by gchpaco** [comment]
Sure, I can work on that.

**Comment by gchpaco** [comment]
CR 2562.
