### ISSUE TITLE
Consider relaxing the definition of a node being part of a cluster

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#1790]
Just spent a lot of time with a user on IRC. Here is the flow they went through:

* Start node A on EC2, make sure it starts
* Start node B on EC2 joining node A, make sure it starts
* Ok, everything's cool. Shut down node B because they wanted to get a different EC2 instances and this was just a test.
* Start node C on EC2 joining node A, make sure it starts
* Server unavailable issue (node B missing). What's going on? Go on IRC, spend an hour trying to figure it out

There are a couple of options I can think of:

* Leave things as is. May be document the issue that pops up a bit better.
* Allow servers to go away without issues as long as they don't have any responsibilities. This would actually be kind of nice. Seeing an issue for servers that don't have responsibilities might be excessive.
* Some variation of the above. For example, allow servers to go away without issues if they currently don't have any responsibilities and never had them before. (I'm not sure why we'd want this, but it's an option to consider)

Not super high priority, so putting in backlog for now, but I think we discuss this to improve first time devops experience.

**Comment by danielmewes** [comment]
This will be fixed by the Raft release

**Comment by danielmewes** [comment]
This has been done.
