### ISSUE TITLE
admin UI not reporting "Machine UID is inaccessiable"

### ISSUE THREAD

**Issue by wojons** [rethinkdb/rethinkdb#1809]
I am finding times where the admin ui says all nodes are up. If i check the aviaable tables i can see some are missing. If i go to the admin cli i then ls issues and then i can see machines are down. The rethinkdb process is up but i guess its locked takes forever to stop or has to be killed 9. This is painful because meta data and replication breaks

**Comment by danielmewes** [comment]
The issue detection logic in the web UI has been rewritten completely for 1.16. Closing this.
