### ISSUE TITLE
More on insert performance

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#1825]
@neumino has run some insert benchmarks against Postgres which give us a good set of latency expectations to work off of.

* The detailed benchmark results are here: https://docs.google.com/spreadsheet/ccc?key=0Ah6XjNY9qZqNdHY4Y0sxV3VZTGZ5elJuUWVOZUE5RGc&usp=sharing.
* The script that generates them is on newton (/home/michel/rethinkdb/benchmark/vsPg.js).

Here are some points of interest:

* For big documents, we are as fast as PostGres (sometime faster), but for small documents, we are up to 10 times slower.
* The cost of the first 10 fields (beside the primary key) seems to be huge -- That may be just an accident though, I could try to run the test more than once and do an average.

We should look into what's going on here when we get the chance.

**Comment by danielmewes** [comment]
These numbers are fairly old. We should still *generally* improve insert performance, but this issue doesn't help much with that.
