### ISSUE TITLE
Rename upsert to replace

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#1838]
Opening this issue for discussion

`upsert` behaves like a `replace` if the document exists. It's confusing because `upsert` is a mix between `update` and `insert`.
It would probably better to rename the flag `replace`.

While we are at it, we may want to provide a flag `update` that would let people insert or update (instead of inserting or replacing).

Any thought?
Putting in backlog.

**Comment by tomasvts** [comment]
update this documentation please 
https://www.rethinkdb.com/blog/answers-to-common-questions/

**Comment by larkost** [comment]
@tomasvts: I don't think that we should try to keep old blog entries up-to-date. The first sentence on that page does stress that it is mostly outdated information. The actual documentation on this is up-to-date.

**Comment by patrickleet** [comment]
maybe a link then - googling still brings up previous article years later.
