### ISSUE TITLE
Promise/Futures and noreply_wait Proposal

### ISSUE THREAD

**Issue by nviennot** [rethinkdb/rethinkdb#1850]
I want an API that allows me to do writes in bulk for performance.
See for example https://github.com/redis/redis-rb#futures

There is some potential with http://stackoverflow.com/questions/20294097/rethinkdb-multiple-queries-in-a-single-request
But that's less ideal because I would need to buffer my writes in the applications, and during that time, the server is idle. Also, the semantics of such replies can be weird (esp. with the return_vals feature).

Here is how I think it should work for ruby (I'm not saying javascript, because things are asynchronous by nature):

```ruby
# Current behavior, not great for parallelization: maybe the two queries would hit different shards.
result1 = rql_query1.run(c) # waits for the result
result2 = rql_query2.run(c) # waits for the result

# With futures
future_result1 = rql_query1.run(c, :async => true) # we send the write to the server and we dont wait for the reply
future_result2 = rql_query2.run(c, :async => true) # we send the write to the server and we dont wait for the reply

future_result1.value # waits for the query to complete and returns the result
future_result2.value # waits for the query to complete and returns the result.

# To wait for all pending queries to complete
# Calling c.wait would wait for all the pending futures to complete.
c.wait

# Note that if some query errored (bad syntax or whatever),
# retrieving the future's value is where the exception will be raised, not on c.wait.
```

This would be trivial to implement due to how the rql protocol works with query tokens. Would this feature also make the noreply feature useless? (unless I don't understand the usecase for noreply).

**Comment by danielmewes** [comment]
Our protocol is now natively asynchronous, and many drivers support a syntax similar to what @nviennot proposed here, or can easily emulate this syntax (through EventMachine in case of Ruby). Closing as outdated.
