### ISSUE TITLE
The clustering megathread

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#1911]
Our clustering implementation has a lot of limitations, both in performance/scalability, and operations. We have lots of open issues about various problems. Many of them are related on the product level, many are related on the code/architecture level, many are unrelated. We'll have to do significant reworking and I'd like to start a discussion about the overall refactor/rearchitecture here.

Here are the issues we'll need to fix:

* #1900 -- improve blueprint suggester to make sure automatic node allocations are (more) balanced in various scenarios.
* #1876, #223 -- automatic failover.
* #1774 -- sharding without losing availability.
* #1861 -- directory scalability.
* #364, #1679 -- consistent hash sharding.
* #1862 -- custom sharding functions. That is, I want primaries for my US users to be in datacenter A, and primaries for my EU users to be in datacenter B.
* #1858, #1859 -- more flexible outdated reads routing. E.g. "run outdated, but make sure it's not older than token X", "run outdated and route to datacenter A", "run outdated if there is no primary in the DC I'm connected to, otherwise run up-to-date".
* #1792, #1392 -- programmatic access to cluster/statistics via ReQL.
* #1906 -- make networking more datacenter-aware (e.g. can servers within one datacenter communicate only through private IPs/internal network interfaces?)
* #83, #301, #1905 -- cluster setup flow. Specifically duplicate database "test" issues, and connecting two disjoint clusters by accident.

EDIT:

* Better issue resolution. A problem with one table shouldn't make administration of the whole cluster impossible until the issue is resolved. A machine down that doesn't result in unsatisfiable goals shouldn't be treated as an emergency. A netsplit between datacenters shouldn't inundate the web ui in a hundred issues. We need to treat machine failure and nesplits like regular events rather than something out of the ordinary.

EDIT2:

* #2119 -- better/different presentation of acks/replicas, and possibly some latency minimization query routing strategies.

We could make this a bazaar or a cathedral or anything in between. Pinging @Tryneus and @timmaxw. I'd like your thoughts and proposal on how to go about this.

EDIT3:

* #2083 -- our query routing algorithm (basically we pick a random node) is too simple and causes latency issues.

**Comment by danielmewes** [comment]
The ideas in here have pretty much been translated into the ReQL admin interface that we shipped with 1.16 and the Raft rework that @timmaxw has been working on for the past months.

There are some separate issues (query routing, hash sharding etc.) that are already tracked elsewhere.

I think this thread has outlived its usefulness.
