### ISSUE TITLE
Proposal: allow external programs to bypass/replace cluster administration code

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#1913]
Here's a wild suggestion: make it possible for external programs to bypass/replace the C++ cluster administration code.

By "C++ cluster administration code" I mean the goals, the suggester, the automatic failover code (that doesn't exist yet), and the entire notion of declaring a machine dead, among other things. The boundary between cluster administration code and the rest is just above `reactor_t`; external programs should be able to feed blueprints directly to the `reactor_t` of a specific machine.

If such an interface existed, a lot of the issues in #1911 could be addressed by an external program. In particular: #1900, #1876, #223 (except lossless rebalance), #1792, and #1905. So, if the normal RethinkDB high-level clustering code didn't handle a particular use case properly, then third parties could write an external program to replace it. Exposing this interface would be a fairly easy feature to implement, and it would allow RethinkDB to be greatly extensible. The official RethinkDB cluster administration code probably won't "get right" clustering administration once and for all; there are too many corner cases, unusual use cases, and potential trade-offs. By decoupling the cluster administration from the core engine, we can allow third parties to fill in the gaps or integrate RethinkDB with their favorite tool like Zookeeper or etcd.

This idea could also be taken a lot further by moving the existing cluster administration code, including the web UI, out of the C++ executable and into an official external program written and maintained by the RethinkDB team. The external program would probably be written in Python. If we did this, the Python program would "wrap" the C++ engine, so users would run the Python program which would in turn run the C++ program. (Perhaps they would talk over stdin/stdout.) Then we could move the porcelain command-line argument parsing from C++ to Python.

The advantages of having a separate Python component are:

* Python is nicer than C++ for high-level code that doesn't need to run fast. Right now the C++ code isn't too bad, but we're likely to want to add a lot more features as we go along. For example, suppose that we want to email a sysadmin when there's a problem. That's much easier in Python than in C++.

* It's easier for third parties to write plug-ins for a Python program than for a C++ program. If people want just one feature that the existing code doesn't offer, but they don't want to write their own full-featured cluster administration logic from scratch, then such a plug-in interface would be very valuable.

* If the engine crashes, the Python component will stay up, because they aren't in the same process. This gives us more crash recovery options. (We could potentially take this even further by having e.g. one RethinkDB process per namespace. But then there are issues with setting up network connections, so that's probably a bad idea.)

* Decoupling the engine from the administration code is elegant.

Of course, the problem is that we would have to actually port the C++ logic to Python; this would take time and introduce bugs.

**Comment by danielmewes** [comment]
This is not going to happen in the described form for at least a while.

ReQL admin now provides decent access to the internal cluster configuration.
We also made most of the changes and improvements we were planning to the clustering control logic as part of the Raft rewrite in the server.
