### ISSUE TITLE
Add functionality for message queuing

### ISSUE THREAD

**Issue by pixelspark** [rethinkdb/rethinkdb#195]
It would be really nice if RethinkDB could be used to pass messages between servers. My guess is that even though this feature is somewhat different than the others, a lot of the required infrastructure is already in place. Much of the query processing already happens in 'streams' anyway. On the receiver side, this could look like this:

``` javascript
r.db().table().filter({topic:"christmas"}).listen(function(msg) {  /* message about christmas received */ });
```

On the sender side, it is simply an insert() to a particular table. To prevent the table from filling up, messages should periodically be removed (either by the database or by the user) based on some sort of TTL value. Another option is implementing a message channel without any backing store:

``` javascript
// sender
r.db().channel("someChannel").insert({topic:"christmas", message:"hello world"});

// receiver
r.db().channel("someChannel").filter({topic:"christmas"}).listen(function(msg) { console.log(msg.message): });
```

For some use cases, it should be possible to guarantee that a message was delivered to exactly one listener.

**Comment by grantcarthew** [comment]
@dminkovsky Hi Josh,

Any news on this?
> I'm working on a recipe/pseudo-library now that implements message queueing as a pattern on top of RethinkDB. This would alleviate the extra point of failure (the daemon pushing changes from rethink to rabbit). It wouldn't have as fully-featured routing capabilities as something like RabbitMQ, but it might be useful in a lot of cases where an industrial strength message queue isn't needed.

My project currently only has two storage service dependencies being RethinkDB and the File System. I need a job queue and the options on NPM seem to all require Redis or RabbitMQ etc. For a simple job/task list (in this case sending emails) I was hoping to avoid adding a new dependency to the project. I had a look at the [repubsub](https://rethinkdb.com/docs/publish-subscribe/javascript/) on the RethinkDB site, however this is not persistent. I was thinking about rolling my own and found this issue after a general search.

Regards.

**Comment by deontologician** [comment]
@grantcarthew Repubsub is the library referred to above. Unfortunately, as you said, it isn't persistent.

You might be able to jury-rig a job queue by inserting jobs into a table, having a changefeed on the table to listen for updates, and then atomically updating the record when a worker starts working on a task. Updates can use a function to decide whether to perform the update or not, so you can have a field like "being_worked_by" which is initially null. On update, check if some other worker has already picked up the task by the time you get to it. Something like:

```js
r.table('jobs').get(jobId).update(function(job){
  return r.branch(job('being_worked_by'),
    r.error('Job already being worked'),
   { being_worked_by: workerId } ));
})
```

That being said, there are lots of edge cases to consider like workers dying etc, so you may want to check whether not adding dependencies is worth the extra time and maintenance of a from-scratch solution. There are lots of job queue libraries with the necessary guarantees out there that run on RabbitMQ or Kafka etc

**Comment by grantcarthew** [comment]
Great information, thanks @deontologician.
