### ISSUE TITLE
Standardize the errors we throw and give an easy way for people to distinguish them

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#2106]
See https://github.com/rethinkdb/rethinkdb/issues/468#issuecomment-37351085 .

**Comment by larkost** [comment]
When we do get around to doing this I would like us to consider changing the name prefix from 'Rql' to 'Reql'. In playing with the error hierarchy we are already going to mess up people's code, so it would be a good time to make the change.

**Comment by danielmewes** [comment]
This was superseded by https://github.com/rethinkdb/rethinkdb/issues/4544 and shipped with 2.1.
