### ISSUE TITLE
Include data structure overhead when tracking cache memory usage.

### ISSUE THREAD

**Issue by srh** [rethinkdb/rethinkdb#2129]
Instead of tracking just page sizes, we could track data structure overhead when tracking cache memory usage.  We could even benefit from changes that make this information *more accurate* but not precise.

**Comment by danielmewes** [comment]
We're including more of the metadata overhead now (I think since RethinkDB 2.2.0). I think it's probably good enough. We can reopen if this becomes a problem again. Closing.
