### ISSUE TITLE
User Accounts

### ISSUE THREAD

**Issue by emilbayes** [rethinkdb/rethinkdb#218]
I'm extemely excited about rethinkdb and have been playing around with it for a while. Are user accounts on the road map any time soon?

I'm thinking accounts restricting access to specific databases and read/write restrictions.

**Comment by dmpayton** [comment]
I wanted to add my own +1 to this; user accounts are important for our use case. My wish list is pretty much exactly what @tobymarsden posted.

**Comment by blazedd** [comment]
+1

**Comment by jampekka** [comment]
+1 Although I'd like to see a rethought approach to this too. A good approach would be to think how PostgreSQL does it as a example not to do user handling.

I've been fantasizing about something like having just secret keys (what's the point of having both user name and password anyway?) and definitely no messing about with ident authentication or filtering hosts etc (these are all easier and better done on OS level if needed).

Also no ACL's or per table permissions etc everybody has hated for decades. I think a lot more elegant approach would be that for each key, a separate "view" of the database could be created (using ReQL of course), where the views would have to be explicitly declared. I think this could be surprisingly simple if the current architecture is flexible enough.

Write access with such thing could get a bit tricky if the views are very flexible, but an easy approach would be to allow writing only to very simply filtered views.

On top of my head this could look something like:

```python
r.table("restricted_namespaces").insert({
    "access_keys": ["somestringthatmayormaynotbesecret", "anotherkeyusingthesameview"],
    "view_name": "public_pages",
    "view": r.table("pages").filter({"public": True}).without("secret", "fields"),
    "writable": False
})
```

The views in themselves would be a very powerful thing, especially if they could be stored and used in queries.

**Comment by jampekka** [comment]
Oh, and at least memory and CPU quotas could be better done just running different processes for the different keys, so OS level controls (eg RLIMIT_* stuff on linux) could be used quite elegantly to prevent DOSs.

**Comment by danielmewes** [comment]
Thank you for your input @jampekka . Using general views for access control is an interesting idea.

I don't think we can easily spawn separate processes for each view with our current architecture, so we'll have to do CPU and memory quotas ourselves unfortunately.

**Comment by jampekka** [comment]
In the current architecture this could probably be worked around by setting other replica for access, which could use OS level limits, if there would be option for per-replica key views.

Although in the longer term I'd wager that refactoring the architecture to allow multiple processes would pay off in the long run. It could allow also using RethinkDB as an process-embedded "serverless" database. But this probably should have an another ticket for better discussion.

**Comment by albsala** [comment]
+1

**Comment by hsen-dev** [comment]
+1

**Comment by nchiring** [comment]
+1

**Comment by ryankrabath-ws** [comment]
+1

**Comment by ekingery** [comment]
+1, we want to use this for a multi-tenant app and having no logical separation between dbs is a big concern for us.

**Comment by rookus** [comment]
+1 for the secret token and views approach described by @jampekka, this is exactly the approach I'm looking for.

**Comment by samuelgoldenbaum** [comment]
+10 for tokens

**Comment by alex-dixon** [comment]
+2

**Comment by RubenKelevra** [comment]
+10

**Comment by NeonMonk** [comment]
+100

**Comment by coffeemug** [comment]
All -- good news, this project is now on the way. We have a basic design in mind, and are starting full design/development today (@VeXocide is the engineer on this). We're shooting to get this out in the next release or two (so realistically, we should be able to get it done and released before end of year).

**Comment by danielmewes** [comment]
We're going to discuss the actual API / implementation for this in https://github.com/rethinkdb/rethinkdb/issues/4519 . There should be an updated proposal in there soon.

I'm going to close this in favor of the other issue, so we don't have two different ones around.

**Comment by GeoffreyPlitt** [comment]
@coffeemug Is there any progress on this?

**Comment by VeXocide** [comment]
@GeoffreyPlitt Yes, it's there! User accounts and permissions for tables has been added to 2.3 along with a new authentication protocol, see #4519 and #5406 for more information. Support for permissions on system tables is currently in code review and will be added to 2.4, see #5692. Adding security features to an existing product is always a rather intrusive process thus we're taking this one step at a time, but this should cover most uses.

**Comment by coffeemug** [comment]
:bow: @VeXocide
