### ISSUE TITLE
Error while compiling on raspberry pi

### ISSUE THREAD

**Issue by Yoeori** [rethinkdb/rethinkdb#2193]
Hello Rethinkers,

I tried finding a package for arm but sadly that seems to be unavailable.. so I compiled it myself! on step 304 of 340 I got the error "Error: selected processor does not support ARM mode 'dmb'"

Full log: http://yoeori.nl/log.txt

This could also be an error of gperftools but I couldnt find anything on there bug forums except one from 3 years ago..

Using raspbian on the Raspberry Pi model B

**Comment by danielmewes** [comment]
We now have tested build instructions at http://rethinkdb.com/docs/install/raspbian/ .
