### ISSUE TITLE
Avoid "No master available errors"

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#2226]
The first few queries sent to an instance after it has restarted or after the cluster configuration has changed often fail with a `No master available` error. This happens even in a single-instance cluster.

It would be very useful if the server made an effort to find the master, or at least polled the status of the master for a while instead of immediately failing with an error.

Related to #1811.

**Comment by danielmewes** [comment]
Superseded by https://github.com/rethinkdb/rethinkdb/issues/4331
