### ISSUE TITLE
Support decommissioning of machines

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#2252]
Every once in a while admins know that they want to take a machine down, but don't have to do it immediately. Currently there is no easy way to tell RethinkDB "divest this machine of all responsibilities and tell me when you're done." There needs to be.

**Comment by danielmewes** [comment]
I'd like to close this in favor of https://github.com/rethinkdb/rethinkdb/issues/2941 which has a bit more technical detail, but is otherwise about the same thing.
