### ISSUE TITLE
Improve error message in case of wrong magic number

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#2302]
The current error is

```
Fail to create a new connection for the connection pool The error returned was:
Server dropped connection with message: "ERROR: this is the rdb protocol port (bad magic number)"
```

I got this error when using the new driver for 1.13 with RethinkDB 1.12.

We should give the user a hint like `"Are you running a version of the driver that does not match the server?"` (with a better wording).
The main reason is that no one probably knows what the magic number is, except drivers developers.

Putting in 1.13 since we changed the magic number.

**Comment by sinderrellar** [comment]
is this means that i should update my rethinkdb??

**Comment by coffeemug** [comment]
You should update RethinkDB server and the client drivers.
