### ISSUE TITLE
Polyglot tests take too long to run

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#2305]
This actually slows down development time a lot -- it's more of an issue than building when working on most ReQL issues.  (I just timed it, and `make rb_polyglot` alone takes ~2 minutes on Newton.)

There are several things we should do to fix this:
* Separate the slow-running tests from the long-running tests.  The slow-running tests can still be run before every release.  (Most of the slow-running tests test things that are unlikely to break from 99% of changes, like waiting on sindexes.)
* Stop creating and dropping tables for every test.  We should re-use tables (and maybe even indexes) between tests, and delete everything from the tables at the end.
* Consider running the tests in parallel.

**Comment by larkost** [comment]
With #2672 `./test-runner` now can run in parallel. It does `-j 2` by default (we have some old testers), but on newton `-j 10` completes all tests in about 2 minutes which I consider acceptable. So I am going to mark this as completed.
