### ISSUE TITLE
super slow backfill

### ISSUE THREAD

**Issue by wojons** [rethinkdb/rethinkdb#2311]
Sometimes i run into a case of a super slow backfill. Both nodes are SSD table sze is 700k docs. the host node is 18 cores and 18gb of ram the client node is 4 cores and 1gb of ram. the backfill rate is about 50-60 records a second. and both have a load of less then 1.

I am not sure if backfill speed is depenant on the client speed or the host machine what i mean is i sometimes see the read spike high that the host has grabed lots of docs the write speed stays about constant but then the read speed goes to 0 while the write speeed does its thing and then the read will come back. 

if i tell it to replicate to a different node this time the client is spinning disk the speed jumps to about 1k and holds strong there. So my guess is an issue with the node getting the data.

**Comment by danielmewes** [comment]
I don't think there's anything we can do here.
We've done a couple of improvements since than, and it might have been because of low cache.
