### ISSUE TITLE
Optimizing insert performance

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#2336]
@nviennot kindly produced two graphs that compare RethinkDB insert performance on a single node to other products. In particular, he's replicating from MongoDB to RethinkDB, and RethinkDB is the bottleneck (https://github.com/rethinkdb/rethinkdb/issues/2335#issuecomment-41751921).

Hard durability:

![benchmark-rethinkdb-hard](https://cloud.githubusercontent.com/assets/48436/2836881/e09bd202-d008-11e3-9fd1-e3c674bee645.png)

Soft durability:

![benchmark-rethinkdb-soft](https://cloud.githubusercontent.com/assets/48436/2836884/f2ecc8a8-d008-11e3-960c-4d58f2243d1b.png)

It's surprising that our performance doesn't significantly improve with soft durability. We haven't optimized for throughput like this for a while, and I think that we should. I suspect that we throttle too quickly and other systems don't -- if you run the workload longer, other systems should either have lower performance, or have too many dirty blocks in memory. However, people still run into this in benchmarks, and it'd be great to either have comparable performance, or better documentation, or a way for users to tune this.

Putting in subsequent.

**Comment by danielmewes** [comment]
A lot has happened since then and this issue doesn't have any details on how to reproduce this benchmark.
While there's little value in keeping this specific issue open, we'll do more benchmarks of insert and other performance soon.
