### ISSUE TITLE
Support objects in primary keys (or fix error message)

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#2352]
It is currently possible to insert arrays as primary keys. However, if I insert an object I get the following error message:

``` javascript
r.table('foo').insert({id: {a: 1, b: 2}, name: 'slava'})

// Primary keys must be either a number, bool, pseudotype or string (got type OBJECT)
```

We should:
- Fix the error message. It should mention arrays (and objects, if we add that).
- Add support for objects in the primary key.

**Comment by thelinuxlich** [comment]
@srh maybe close it?
