### ISSUE TITLE
in in opensuse 13.1, build/external/protobuf_2.5.0/lib/libprotobuf.a is in .../lib64/ instead

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#2363]
Reported [on twitter](https://twitter.com/GrzegorzNosek/status/463732276514525184).

Building should be possible with the system protobuf library and without `--fetch protobuf`. Another workaround is to copy `libprotobuf.a` to `lib/` where the rethinkdb makefile expects it to be.

This bug can likely be fixed by adding a configure flag to `mk/support/pkg/protobuf.sh` or just symlinking `lib` to `lib64/`

**Comment by mbains** [comment]
This is also an issue for libjemalloc if you choose to fetch it. 

I created a symbolic link to fix the issue. 

linked
`rethinkdb-2.1.5-2/build/external/jemalloc_3.6.0/lib64/`
to
`rethinkdb-2.1.5-2/build/external/jemalloc_3.6.0/lib/`

**Comment by AtnNn** [comment]
@mbains thanks for reporting. Are you also using opensuse 13.1?

**Comment by mbains** [comment]
@AtnNn I'm using 13.2

I'm new to this distro but it's becoming a pattern. Whenever I build from source, autotools on this distribution likes to link everything in lib64. 

http://www.pathname.com/fhs/pub/fhs-2.3.html#LIBESSENTIALSHAREDLIBRARIESANDKERN

**Comment by AtnNn** [comment]
I wonder if there is a way to detect what the lib directory is, or if passing `--libdir=$prefix/lib` would fix the problem.

**Comment by mbains** [comment]
@AtnNn 
I pinged the opensuse IRC and they recommend that I look at /etc/ld.so.conf.

Here are the contents:

```
/usr/local/lib64
/usr/local/lib
include /etc/ld.so.conf.d/*.conf
# /lib64, /lib, /usr/lib64 and /usr/lib gets added
# automatically by ldconfig after parsing this file.
# So, they do not need to be listed.
```


Stackoverflow thread: http://stackoverflow.com/questions/9922949/how-to-print-the-ldlinker-search-path

Performing one of the recommendations on my machine:

```
gcc -print-search-dirs | sed '/^lib/b 1;d;:1;s,/[^/.][^/]*/\.\./,/,;t 1;s,:[^=]*=,:;,;s,;,;  ,g' | tr \; \\012
libraries:
  /usr/lib64/gcc/x86_64-suse-linux/4.8/:/usr/x86_64-suse-linux/lib/x86_64-suse-linux/4.8/:/usr/x86_64-suse-linux/lib64/:/usr/lib64/x86_64-suse-linux/4.8/:/usr/lib64/:/lib/x86_64-suse-linux/4.8/:/lib64/:/usr/lib/x86_64-suse-linux/4.8/:/usr/lib64/:/usr/x86_64-suse-linux/lib/:/usr/lib64/:/lib/:/usr/lib/
```

*Another solution*:  the rethinkdb scripts could add something to jemalloc's configure to set libdir to /lib explicitly

**Comment by danielmewes** [comment]
Should be fixed via https://github.com/rethinkdb/rethinkdb/pull/5360 , I think.
