### ISSUE TITLE
Bad server performance when given concurrent CONTINUE queries

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#2374]
Previously discussed in #2364.

When exporting 5600 rows of 1MiB each:

* Python driver 1.12.0-2 (single CONTINUE queries): 122 seconds. The graph has no gaps.
* Python driver 1.12.0-1 (double CONTINUE queries): 152 seconds and the read graph has many gaps:

![graph](https://cloud.githubusercontent.com/assets/706854/2923286/38c56956-d712-11e3-9a71-08a58817a875.png)

**Comment by danielmewes** [comment]
We should retest this sometime.

**Comment by danielmewes** [comment]
I don't think we're realistically going to retest this. It's likely the problem no longer exists because the handling of multiple requests is very different now.
