### ISSUE TITLE
.getAll() queries do not show in performance graphs

### ISSUE THREAD

**Issue by NerdYouDontKnow** [rethinkdb/rethinkdb#2379]
Using RethinkDB 1.12.4 on Mac OSX 10.9.2.

To reproduce:

1. Open two web browser windows and pull up the Data Explorer in one window, and the table page in the other window. (I used google chrome).
2. Run the query `r.db("your_db").table("your_table").getAll(value, {index: "secondaryIndex"})` on a table with the secondary index `secondaryIndex`, and matching data entered in the table.
3. Watch in your other browser window as the graph stays zeroed out.

When I use `.get("value")` to retrieve an entry, the graph shows those reads correctly.

Is this intended behavior? If so, why?

**Comment by danielmewes** [comment]
This works in `next`.
