### ISSUE TITLE
Test and support connecting nodes with different architecture bitsizes

### ISSUE THREAD

**Issue by Tryneus** [rethinkdb/rethinkdb#239]
As a result of #169, cluster nodes of e.g. 32bit and 64bit will not be allowed to connect to each other.  There is no technical reason that this cannot be done, but it is untested and therefore prohibited at the moment.

Remove the code from `rpc/connectivity/cluster.cc` that prevents this from happening and thoroughly test this situation.

**Comment by jrote1** [comment]
Is there any update on this?

**Comment by danielmewes** [comment]
@jrote1 No, this is pretty low priority.
Do you need this for your setup?

**Comment by jrote1** [comment]
Yes this is a key part of how I was going to use this, is there a workaround?

**Comment by danielmewes** [comment]
@jrote1 The work-around is to check out v2.3.0 (or v2.3.x if you want the latest bug fixes), remove the check in https://github.com/rethinkdb/rethinkdb/blob/next/src/rpc/connectivity/cluster.cc#L985 , compiling from source, and hoping that it works.

As the issue says, we aren't testing this. It might still work in practice, or it might not (you might get server crashes when running certain queries etc).

**Comment by thelinuxlich** [comment]
@srh is this still desirable? Can't we enforce homogeneous cluster architectures and move on?

**Comment by utzb** [comment]
As the submitter of issue #6500, I agree with @thelinuxlich . The use case doesn't seem strong enough.

**Comment by srh** [comment]
Agreed, there is no capacity for supporting this.
