### ISSUE TITLE
Test and support connecting nodes of debug and release build modes

### ISSUE THREAD

**Issue by Tryneus** [rethinkdb/rethinkdb#240]
As a result of #169, debug and release builds will not be allowed to connect to each other.  There is no technical reason that this cannot be done, but it is currently broken and therefore prohibited at the moment.

Remove the code from `rpc/connectivity/cluster.cc` that prevents this from happening and fix the existing problems with this clustering scenario.

**Comment by thelinuxlich** [comment]
@srh is this really necessary?
