### ISSUE TITLE
Make sure the split points match the inserted ids in all tests

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#2436]
I fixed a few tests that would create shards, but all the inserts would go to the same shard. I think there are some remaining tests that do this.

If a tests wants to test empty shards, it should be done explicitly.

**Comment by larkost** [comment]
I have policed all of the tests other than the polyglot tests that would be implicitly covered by using `-s/--shards`. All of them either do not care about the data in ranges, or handle that themselves. I will be handling this question for the polyglot tests with #3519, so this is completed.

**Comment by larkost** [comment]
I am re-opening, as there are a couple of small cleanups that I want to make, an they fall under this banner.

**Comment by larkost** [comment]
The two small cleanups are up for review with CR 2442, and are in branch larkost/2436-shard-cleanup

**Comment by larkost** [comment]
These have passed review, and are in `next` with 5111ff2
