### ISSUE TITLE
Move node to different DC with responablities

### ISSUE THREAD

**Issue by wojons** [rethinkdb/rethinkdb#2492]
If a node is in a dc and and has replicas and write acks could be master all that sort of stuff users should still be able to create a new dc move the node and move its responablies with it. It should be a questions box ore set of questions for each table.

**Comment by danielmewes** [comment]
In ReQL admin, table responsibilities are bound to individual servers.
We don't have data centers anymore, but if you change the "tags" of a server (a more flexible replacement for DCs), this does no longer affect the server assignments of existing tables.

To reassign servers in ReQL admin, you'd need to run an explicit `reconfigure` specifying the desired tags to use for replicas.

So I think this issue has gone away.
