### ISSUE TITLE
Table creation time (and disk space)

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#2498]
The execution time of the `tableCreate` command hovers around 1s in SSDs, and creates a 3MB file. There are two pieces of weirdness here:

- It shouldn't take anywhere near 1s to write 1MB on a modern SSD -- we're about an order of magnitude off. So there is something else going on performance-wise that we should fix.
- We should cut down from 1MB to something smaller. There is no reason for an empty table to take up that much. (I know there is a big constant factor because of the serializer, but we should get that factor down).

Edit: thought empty table size is 3MB, but it's actually 1MB.

**Comment by danielmewes** [comment]
Closing in favor of https://github.com/rethinkdb/rethinkdb/issues/4251 and https://github.com/rethinkdb/rethinkdb/issues/4746 .
The performance numbers in here are now pretty much all outdated, because table creation uses very different code paths since the Raft switch.
