### ISSUE TITLE
Avoid incompletely erase shard data; outdated data could re-appear

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#2557]
This is a theoretic race condition in the clustering layer, and I'm not sure if there already is something in the code to prevent this or not. @timmaxw do you remember anything about this?

Suppose we have two nodes A and B and get the following sequence of events:
- A and B are replicas for table T
- The admin removes A as a replica
- A goes through the "reactor be nothing" procedure. While in the "nothing_when_done_erasing" stage, it first sets the metainfo/version range for the shards corresponding to A to zero, and then starts erasing the data from the btree.
- Before A is done erasing, it is shut down
- The admin adds A back as a replica
- A is started up again
- I *think* A would now directly go through the reactor_be_primary / reactor_be_secondary procedure, starting by backfilling all data from B. (if it is somehow guaranteed that A first goes through be_nothing again, everything should be fine)

The problem is that A hasn't finished deleting all old data at the time it begins backfilling new data.

**Comment by danielmewes** [comment]
I think @timmaxw implemented the mentioned changes to `store_t::reset_data()` a while ago.
@timmaxw do you know if this problem is fixed?

**Comment by timmaxw** [comment]
Yes, I think this issue is a duplicate of #3480, which was fixed.

**Comment by danielmewes** [comment]
Thanks for looking up the other issue. Closing.
