### ISSUE TITLE
JavaScript driver: enhance .run()

### ISSUE THREAD

**Issue by vvo** [rethinkdb/rethinkdb#2570]
Hi right now we are trying to:

``` js
var conn = r.connect({ db: 'marvel' });
r.table('marvel').run(con, fn);
```

Problem is that to use `.run`, `con` has to be ready, which makes sense of course.

I thought that while you use promises everywhere, you could just handle this use case
by using `con.then` in the `.run` so that once the promise is resolved you can just use it.

This use case is important otherwise you need to do a complex wrapper when your application is starting and the rethinkdb connection is not yet ready.

What do you think? @neumino

**Comment by stuartpb** [comment]
Using a different method for construction (such as the root `return('rethinkdb')` value, as described in https://github.com/rethinkdb/rethinkdb/issues/3771#issuecomment-107127070) would sidestep this issue cleanly (keeping `r.connect()` as the asynchronous connection constructor, and the new method as the synchronous connection constructor).
