### ISSUE TITLE
Low cache size even if there is available memory

### ISSUE THREAD

**Issue by janih** [rethinkdb/rethinkdb#2580]
There is 18G cached by the OS and 582M free:

```
jani@jani-desktop:~/temp$ free -mh
             total       used       free     shared    buffers     cached
Mem:           31G        30G       582M       128M       515M        18G
-/+ buffers/cache:        12G        19G
Swap:          15G        21M        15G
```

When I start RethinkDB, It doesn't reserve a lot of cache and warns about it:

```
jani@jani-desktop:~/temp$ rethinkdb --http-port 7001
info: Running rethinkdb 1.13.0-0ubuntu1~trusty (GCC 4.8.2)...
info: Running on Linux 3.13.0-24-generic x86_64
info: Using cache size of 100 MB
warn: Cache size does not leave much memory for server and query overhead (available memory: 577 MB).
warn: Cache size is very low and may impact performance.
info: Loading data from directory /home/jani/temp/rethinkdb_data
info: Listening for intracluster connections on port 29015
info: Listening for client driver connections on port 28015
info: Listening for administrative HTTP connections on port 7001
info: Listening on addresses: 127.0.0.1, 127.0.1.1, ::1
info: To fully expose RethinkDB on the network, bind to all addresses
info: by running rethinkdb with the `--bind all` command line option.
info: Server read
```

Should RethinkDB be able to take a chunk of that disk cached memory (18G) or is the operating system holding on to it too tight? :)

**Comment by lciummo** [comment]
RethinkDB’s page cache keeps recently used data in memory to minimize disk access. By default, RethinkDB automatically configures the cache size limit according to the formula (available_mem - 1024 MB) / 2. available_mem is the amount of available memory at the time RethinkDB starts, including memory that can be freed up by the operating system if needed (such as the operating system’s disk cache). If there is less than 1224 MB of memory available on the system, a minimum cache size limit of 100 MB is used. You can find the actual size limit used by an instance of RethinkDB in its log.
