### ISSUE TITLE
Build RethinkDB with bundled v8 on OS X without XCode

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#2581]
The version of v8 that RethinkDB is bundled with (using `--fetch v8`) fails to build when the full XCode is not installed. Reported here: https://github.com/Homebrew/homebrew/pull/30249

```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

Patching v8 with the suggested patch or bumping the fetched version could fix this problem.

**Comment by larkost** [comment]
Relating this to:
- Drop support for older versions of v8 #3423
- Make v8 static-only to allow using the included ICU headers #3472

**Comment by AtnNn** [comment]
Moving out of 1.16, adapting the code to work on newer versions of v8 is going to take more time.

**Comment by AtnNn** [comment]
Closed. See #3423 and #3472
