### ISSUE TITLE
ReQL proposal: allow zero keys in `get_all`

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#2588]
```python
r.table('foo').get_all()
// returns []
```

The rationale for this is user reported here: #2586. Any time the function is variadic, it becomes possible for people to pass no values, and that in turn becomes probable now that we've introduced `r.args`. So allowing no keys here seems much more convenient and sensible than throwing.

**Comment by chrisvariety** [comment]
Currently staring at a lot of queries like this to avoid this problem: `r.table('lessons').getAll(r.args(ids.append('prevent-empty-error')))`

Would love to see this in a future version of RethinkDB, though I understand the potential confusion.

**Comment by mlucy** [comment]
I'm still not sure whether or not we should do this; what do other people think?

**Comment by danielmewes** [comment]
I'm not sure how clean or hacky this would be to implement on the server, but we could also suppress the error only if `r.args` is used as an argument to `getAll`.

If that's too tricky or breaks any significant abstractions in the server code, I think we should allow `get_all` with zero arguments.
If a user finds that there's a getAll term, they have probably found it through some type of documentation (either the Data Explorer auto suggestion, or out API docs). Chances are that they don't fully read the documentation, but once they notice that they always get an empty result from the term they will already know where to find the docs, at which point it will hopefully become obvious pretty quickly.

**Comment by deontologician** [comment]
+1 for this, I think it makes sense.

**Comment by coffeemug** [comment]
Having thought about it, I think allowing no arguments to `get_all` would be too confusing. One way to get around it is to rename the method to `get_keys`, which probably wouldn't be the worst of ideas.

**Comment by danielmewes** [comment]
`get_keys` could be confusing as well, since it doesn't get the keys but the documents under the keys.
Maybe it's just me, but if I didn't know how the ReQL naming scheme works I could see myself thinking of `get_keys` as doing the same as `keys` (i.e. get the keys of an object).
Maybe `fetch_keys` would be clearer? In that case we should probably also rename `get` to `fetch`?

I'm generally not too fond of changing the name of `getAll` as a solution to this to be honest. But I could be convinced otherwise.

I still prefer doing either the `r.args` special casing or generally allowing zero arguments to `get_all` without renaming the term.

**Comment by coffeemug** [comment]
Yeah, perhaps renaming `get_all` was a crazy 3am idea :smile: 

I wouldn't be opposed to allowing zero arguments. We'll make everything clear in the docs, and if it still confuses people we'll add a troubleshooting entry we can easily link them to.

**Comment by mlucy** [comment]
OK, it sounds like we should make `get_all` with 0 arguments work.  That sounds cleaner to me than special-casing it for `r.args`.

**Comment by danielmewes** [comment]
:+1:

**Comment by danielmewes** [comment]
Marking settled as making `get_all` with 0 arguments work.

**Comment by nighelles** [comment]
This is in review 3425
Implemented in branch nighelles_2588
https://github.com/rethinkdb/rethinkdb/tree/nighelles_2588

**Comment by chrisvariety** [comment]
@nighelles my hero! You have no idea how much my code will be cleaned up by this. :sparkling_heart:

**Comment by nighelles** [comment]
This is in next.
