### ISSUE TITLE
`has_fields` should return a selection when called on a table

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#2609]

**Comment by danielmewes** [comment]
I don't think we should do this. It will clash with https://github.com/rethinkdb/rethinkdb/issues/2692 and can be very confusing if users think that the update applies only to the selected field, not to the whole document.

**Comment by mlucy** [comment]
@danielmewes -- I disagree pretty strongly, I think this is a straight-up bug.  `r.table('test').has_fields('foo')` should be identical to `r.table('test').filter{|row| row.has_fields('foo')}`.  The latter returns a selection, so the former should as well; it's literally an implementation bug that `obj_or_seq_op_term_t` discards the selection property after it applies the filter.

(Resetting the state since there's disagreement and I don't want us to forget to talk about it because the issue is buried.)

**Comment by danielmewes** [comment]
Arr you are absolutely right. For some reason I had read this as `get_fields`. Totally misunderstood. Sorry.

**Comment by chrisvariety** [comment]
:+1: on this, current behavior is straight up broken (but it is easy enough to work around)

**Comment by mlucy** [comment]
This is in CR 3117 by @Tryneus .

**Comment by mlucy** [comment]
This is in next.
