### ISSUE TITLE
Have a datum size limit instead of an array size limit

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#2614]
The size limit could be based on the size of the JSON representation, in bytes.

RethinkDB currently lets you manipulate very large documents as long as there is no single array with over 100000 elements. When working with large documents, this seems very arbitrary. It can also confuse users such as in #2596.

**Comment by danielmewes** [comment]
I think this will no longer be necessary once we get https://github.com/rethinkdb/rethinkdb/issues/1375 in. It does the same just with a size limit applied globally to the query and not to individual datums.
