### ISSUE TITLE
Consider adding more stats to the dashboard and table view

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#262]
@lawrencenull on twitter was very interested in seeing disk space usage on the dashboard (and on a table view for a given table). It sounds like a good idea to reevaluate which other stats we can present once we get a bit more info to users. Moving to backlog for the time being, let's revisit this after a few point releases.

**Comment by deontologician** [comment]
We now show disk usage on the dashboard after #4461, and had a discussion on what stats to show overall. I am going to close this as obsolete
