### ISSUE TITLE
Cannot compute blueprint because a machine is offline.

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#2620]
On branch `michel_2606_test` (commit ec0d96de64bf64094fe73a31a6a201f907c70979), the test for the JavaScript driver can throw an error if I immediately start the test once the server is ready.

Replace the line 134 in `test/rql_test/connections/connection.js` with `done()` instead of `setTimeout(done, 500)`.

The error sent back by the server when trying to create a table is:
```
Cannot compute blueprint because a machine is offline.
```

The flow is this one

- Start RethinkDB
- Read stderr and wait until "Server ready" is printed
- Open a connection with the JS driver
- Try to create a table with `r.tableCreate`

Then I get the error.
It happens something like once every 5 runs.

**Comment by danielmewes** [comment]
This seems to be a relatively rare problem. In any case it will go away with the Raft rewrite.
