### ISSUE TITLE
`r.js` reported to be unacceptably slow

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#2642]
See https://github.com/rethinkdb/rethinkdb/issues/2435#issuecomment-47670984.

> It takes over 20 seconds to filter through 100 documents when `r.js` is used in a filter on Ubuntu 13.1 and OSX 10.9.3. Documents look like this:

> ```
{
"categories": [
{
"prop":  "$HY%Tn4Ap4V8" ,
"prop2":  "QG&RzjkS0vNI!eWG#"
} ,
{
"prop":  "JzV^SCIDkH" ,
"prop2":  "]t5aVRzJJfPmg"
}
] ,
"id": 123012409982976 ,
"prop":  "O@hH)kG4vww"
"prop2":  "0jZ@ZbTJD"
"prop3":  "e5PP7mH5c^T["
} 
```

> Query looks like this:

> ```js
r.table('marvel').filter(
    r.js('(function (row) { return row.magazines > 5; })')
)
```

/cc @Tryneus

**Comment by danielmewes** [comment]
We also fixed some serious issues with `r.js` performance that depended on compilation order in https://github.com/rethinkdb/rethinkdb/issues/3757.

I'll open an issue on the docs tracker to add a warning about `r.js` being slower than native ReQL.

Is there anything actionable left in here? Closing, but feel free to re-open if there are issues left.
