### ISSUE TITLE
Support changefeeds in the web UI

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#2643]
There are a few reasons to do it:

- We really should support all features in the web ui. It's a bad idea to lock some queries out.
- It's really, really, really useful for demos.

We should figure out how to do this effectively before we ship 1.14.

/cc @neumino @mglukhovsky

**Comment by AtnNn** [comment]
Merged into next and v1.16.x as 752c755.

**Comment by danielmewes** [comment]
Super awesome :clap:
