### ISSUE TITLE
Consider a design for access control

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#266]
If RethinkDB supported access control, we could allow people to hit the database via the http API straight from the browser and bypass servers. For a lot of people this would be really, really nice.

I'm slating for 1.5 for now, but we should brainstorm what we can do here once 1.4 is out.

**Comment by fasiha** [comment]
When this was closed in 2013, was it closed in reference to @coffeemug's initial thought of HTTP API for browser-only apps (‘if you expose the http api to people, they could write apps entirely in the browser without servers (which is really nice)’), or with reference to client driver access, which this issue morphed into?

I would love to see an HTTP API, or anything that allowed me to write a purely client-side app, without anything server-side beyond RethinkDB—but I fully appreciate that this is likely beyond the scope of this project.

**Comment by coffeemug** [comment]
@fasiha -- we've been thinking about it a lot (and still are). This is definitely tricky -- we don't have a plan for it yet, and don't yet know if it will ever become a core part of RethinkDB. It will take more time to figure it out, but it's definitely on our minds.
