### ISSUE TITLE
/etc/init.d/rethinkdb and /etc/rethinkdb don't exist after installation on mac os x mavericks

### ISSUE THREAD

**Issue by zooshme** [rethinkdb/rethinkdb#2717]
I've installed 13.3 and followed the tutorial for starting rethinkdb on startup but the folders /etc/init.d/rethinkdb and /etc/rethinkdb do not exist. Any ideas what I might be doing wrong?

**Comment by thelinuxlich** [comment]
@srh is this still a valid issue?
