### ISSUE TITLE
Indexing time periods and ranges

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#2722]
Querying for overlapping ranges is a common operation. There is currently no good way to optimize it using an index.

Here is a sample query:

```
r.table('events')
 .filter(lambda event:
   (event['start'] < end) & (event['end'] > start))
```

If we had `r.range` (#875) it might be possible to create a multi-index like this:

```
hour = 86400
def hour_blocks(start, end):
  n = r.floor((end - start) / hour)
  offset = r.floor(start / hour)
  return r.expr(offset).do(lambda offset: r.range(n).map(lambda i: i + offset))

r.table('events')
 .index_create('hours', lambda ev: hour_blocks(ev['start'], ev['end']), multi=True)
```

And query it like this:

```
r.table('events')
 .getAll(r.args(hour_blocks(start, end)), index='hours')
 .filter(lambda event:
   (event['start'] < end) & (event['end'] > start))
```

But it is still a lot of work. There must be some easier way to work with ranges and time periods. Perhaps something like `getIntersecting` (#2571)

**Comment by thelinuxlich** [comment]
@srh we already have r.range

**Comment by srh** [comment]
Gonna say adding interval querying is out of scope for now.
