### ISSUE TITLE
Meteor feedback on changes

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#2727]
From @coffeemug :

Some feedback on this command from the Meteor team:
- `r.table('users').orderBy(r.desc('age')).limit(2).changes()` is really important to support and comes up in almost every app, including hello world. @mlucy tells me this is easy to do as long as we require an index in `orderBy`. There is a question of how to return data here (i.e. how do we indicate that an item has moved in the list, for example).
- Atomically getting the current resultset + changes is very important.
- Documenting guarantees is important. For example, if the object's value changes and then changes back to the original value, is the user guaranteed to see the change? We should document guarantees clearly.
- It's important to clearly specify the relationship between when acks to writes occur and when changes are pushed onto a feed. It's also important to see the ack before the change on a given connection (or to be able to correlate them between different connections).
- How do I easily and efficiently subscribe to changes of multiple objects or multiple different changes? What happens when I call `t.getAll(x, y, z).changes()`?

We don't have to solve all these problems right away, but I wanted to document this so we can make incremental improvements over time.

**Comment by danielmewes** [comment]
We got `r.table('users').orderBy(r.desc('age')).limit(2).changes()` in 1.16,
will have "Atomically getting the current resultset + changes is very important." in 2.1
and got "easily and efficiently subscribe to changes of multiple objects or multiple different changes" through `r.union(....).changes()` in 2.0.

So that leaves documenting the guarantees and detailed semantics.

**Comment by Slava** [comment]
Commenting to express my interest in this issue and subscribe to updates.

**Comment by thelinuxlich** [comment]
@srh is this still a reality? I don't think Meteor has interest anymore on this

**Comment by srh** [comment]
I think we've got documentation of detailed semantics, see the "squash" option for example.  Changefeed consistency guarantees are documented at https://rethinkdb.com/docs/consistency/ .  So I think this issue is completed.
