### ISSUE TITLE
Nodes Wont reconnect.

### ISSUE THREAD

**Issue by wojons** [rethinkdb/rethinkdb#2755]
I had an issue where i had 4 nodes. node 1 and 2 could not see node 3 but they could both see node 4. node 3 could not see node 1 or 2. but node 4 could see all other nodes. I was working with @danielmewes we checked for cpu spikes and other things and there was nothing.

There was an interesting log line:
warn: Received invalid clustering header from 123.123.123.123, closing connection -- something might be connecting to the wrong port.

otherwise there was a lot of connect and disconnects and then at some point it looks like it simply gave up trying to reconnect again.

**Comment by danielmewes** [comment]
This could be related to https://github.com/rethinkdb/rethinkdb/issues/2841.

Unfortunately we don't have any ideas right now what might have caused these issues.
We should keep our eyes open in case we can observe this again.

**Comment by danielmewes** [comment]
This used to be rare, but issues with servers stopping to reconnect have surfaced more frequently lately. It seems like some other changes might have made some existing bug more prominent.

We're looking into this now.

**Comment by danielmewes** [comment]
A handful of fixes and improvements to the connection handling logic are in code review 3464, branch daniel_no_stuck_connections

**Comment by danielmewes** [comment]
The race conditions we're aware of are fixed in v2.2.x by 97d9cb4 , and in next by defa1fc.
