### ISSUE TITLE
Changefeeds proably don't behave correctly when someone changes which replica is the master

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#2757]
After talking with @timmaxw, it sounds like right now if you change which replica is the master, existing changefeeds on the old master won't be disconnected, so we'll have changefeeds on a replica, which we haven't thought about.

We probably want to support this at some point, for live resharding if nothing else.  After a brief talk with @timmaxw it sounds like it might be sufficient to just guarantee that changefeeds are disconnected if the replica and the master can't reach each other.

**Comment by larkost** [comment]
The test that shows that this is the case is up for review with CR 2757, and is in branch `larkost/2757-changfeeds-change_master`

**Comment by larkost** [comment]
This test is in `next` with 17ea5a9. The implied changes to behavior to keep changefeeds intact are in separate bugs:

- don't disconnect changefeeds during resharding #3549
- Keep point and range changefeeds intact when `table.reconfigure` does not alter their shards #3547

**Comment by danielmewes** [comment]
@larkost What is the current behavior? @mlucy's original post talks about the potential issues of ending up with changefeeds on a non-primary replica as far as I understand.
Is that what's happening or are the changefeeds terminated properly on changing the primary?

**Comment by larkost** [comment]
The current behavior is that all changefeeds are ended on a table when the shards change on that table. There does not seem to be any regard to whether it needs to end or not. So there is no problem there (but not great behavior from a user perspective).

**Comment by danielmewes** [comment]
@larkost Just to double-check: So that's still true if the shard boundaries remain the same and the replicas stay on the same servers, but the primary replica is switched to a different server (which used to be a secondary replica before)?

**Comment by larkost** [comment]
Yes, we have a couple of items in the test to make sure of exactly that. The only thing we are not checking is when the boundaries move... at some point I will go back and make sure of that.

**Comment by danielmewes** [comment]
Ok, thanks for the clarification.
