### ISSUE TITLE
Between ordering - string < date

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#2774]
This return `true`

```
r.expr("foo").lt(r.now())
```

This return the states I expect (basically all of them) - `state` is a simple index on the field `state` and states are all strings.

```
r.db('test').table('test').between(0, 'z', {index: "state"})
```

However this return nothing:

```
r.db('test').table('test').between(0, r.now(), {index: "state"})
```

Ping @mlucy

**Comment by aleclarson** [comment]
> We generally have the rule that types sort according to the output of typeof.

Sorry for the necropost. But this should be somewhere in the docs, if it's not already. 😄

**Comment by marshall007** [comment]
@aleclarson thanks, I created an issue in the docs repo: https://github.com/rethinkdb/docs/issues/1210
