### ISSUE TITLE
Add a repository and packages for CentOS 7

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/rethinkdb#2778]
CentOS 7 was [released](http://lists.centos.org/pipermail/centos-announce/2014-July/020393.html) earlier this month.

We should add packages and a yum repo that explicitly supports CentOS 7 (although the CentOS 6 packages will likely work as they stand currently.)

Assigning to @AtnNn.

**Comment by ShahriyarR** [comment]
Still there is no Centos 7 repo:

http://download.rethinkdb.com/centos/

**Comment by lamielle** [comment]
Bump: I just discovered there is no official CentOS 7 package.  It appears that the CentOS 6 RPMs will work, but it is concerning that I have to use those.

**Comment by mlucy** [comment]
@danielmewes -- who should be pinged on these while @AtnNn is gone?

**Comment by danielmewes** [comment]
Indeed the CentOS 6 packages are fully compatible. We still need to add a separate repository to make that more obvious though. Sorry this has been taking a while.
I hope we'll be able to get to this for 2.2. I think it's not hard, we just need to do it.

**Comment by lamielle** [comment]
Thanks Daniel.  Actually, just hearing word in this issue that they are expected to work makes me feel better.  : )  Obviously a 7-specific repo would be nice, but it's good to hear from you that they work and are expected to work.

**Comment by AtnNn** [comment]
I'm preparing the Centos 7 repo:

* created a `centos7-64` schroot on `newton` and installed the build dependencies
* updated the `build-rpm.sh` script
* updated the buildbot config
* updated the upload script for download.rethinkdb.com
* updating the docs

**Comment by AtnNn** [comment]
The preparations are complete. The next release will have a centos7 package.

- https://github.com/rethinkdb/rethinkdb/commit/d1af8116fef710851dafb0a81a74cf9969f09741
- https://github.com/rethinkdb/buildbot/commit/091eddb306fbd99bec5ae17d52b5e14f71bd62c0
- https://github.com/rethinkdb/rethinkdb-download/commit/7f18b9b1ffb0f7822271cbfb5047e2917b52e499
- https://github.com/rethinkdb/docs/pull/941
