### ISSUE TITLE
 error: Ran out of disk space.

### ISSUE THREAD

**Issue by philips** [rethinkdb/rethinkdb#2781]
We have machines that keep crashing with " error: Ran out of disk space. (offset = 104857600, count = 258048)" even though there is more than sufficient disk space available: 20GB+.

**Comment by internalfx** [comment]
This is late, but may be useful to others looking for answers....

Try running a Balance operation.

How to do it: https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-balance
Why: https://btrfs.wiki.kernel.org/index.php/FAQ#What_does_.22balance.22_do.3F

**Comment by philips** [comment]
@internalfx Yes, we ended up writing a full btrfs tuning and debugging guide: https://coreos.com/docs/cluster-management/debugging/btrfs-troubleshooting/

**Comment by RubenKelevra** [comment]
Well the Btrfs-team does recommend always using the latest kernel, for latest bug-fixes. So @philips did you tried Linux 4.1 on this machine? 3.15 is over 1 year old.

**Comment by philips** [comment]
This was filed a year ago, thus the old Kernel. We ended up moving off of
RethinkDB so we never tested this again.

**Comment by RubenKelevra** [comment]
Sad to hear this, but I still expect this issue in the not-production-stable btrfs-codebase, not rethinkdb.

**Comment by philips** [comment]
@RubenKelevra If you wish to close the issue you may, for whatever reason I cannot close it myself.

**Comment by RubenKelevra** [comment]
I'm not the part of the team here, so I can't too.

@danielmewes would you? :)

**Comment by danielmewes** [comment]
The issue seems to be closed already. Does it show as open for you?

**Comment by RubenKelevra** [comment]
Nope, sorry :)

**Comment by danielmewes** [comment]
Must be a problem with GitHub. It's definitely closed here.

![screenshot from 2015-08-19 23 51 44](https://cloud.githubusercontent.com/assets/505365/9377375/46b92c74-46cd-11e5-9036-c1fb1f6c10c9.png)

**Comment by RubenKelevra** [comment]
I meant, it's closed, I'm just blind. :)

**Comment by danielmewes** [comment]
Ah :-)
