### ISSUE TITLE
Better error message when a binary is more than 64MiB

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#2808]
I currently get `EPIPE` errors if I try to send a query with a binary bigger than 64MiB (using Node).

Is there a reason the server has to close the connection in this case?

We should try to provide a better error message at least.
We could have the driver check the size of a binary and throw if they are too big. That should catch the most common cases I guess?

Putting in subsequent.

**Comment by danielmewes** [comment]
I think our error reporting on queries that are too large has gotten a lot better and is probably sufficient by now. Closing.
