### ISSUE TITLE
Rethinkdb UI grays out when stats timeout

### ISSUE THREAD

**Issue by wojons** [rethinkdb/rethinkdb#2813]
@neumino could not recall if there was a ticket for this or not but I would like to open one. I find this to be very annoying sometimes you have to work over a slow connection (mobile or a vpn), sometimes you have one node that is really slow and times out. I would like that the gear near the top of the screen had an option to disable the grayout it can put some flashing bar at the top or bottom of the screen to let the user know they are not connected but I find my self writing a query and the screen grays and i have to rewrite it. Or trying to edit some db replication settings and the same thing happens.

**Comment by deontologician** [comment]
This may have been solved/traded for new issues after 1.16

**Comment by danielmewes** [comment]
We're still graying out the UI if we lose the connection.
@wojons suggested in his original post that the graying out could be disabled.

**Comment by danielmewes** [comment]
Superseded by https://github.com/rethinkdb/rethinkdb/issues/3638
