### ISSUE TITLE
Heartbeat timeout message should be more explicit about the connection

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#2891]
When the communications fail between two servers the current message looks like:
```error: Heartbeat timeout, killing connection to peer 127.0.0.1```

The problem is that in this case (testing) all of the servers are on `127.0.0.1`, so that does not actually designate a server. We should probably include the port information as well.

**Comment by eliangidoni** [comment]
Hey , I think there's a bug in peerstr, the function getpeername() returns true on success, see https://github.com/rethinkdb/rethinkdb/pull/3814

**Comment by danielmewes** [comment]
Just merged @eliangidoni 's patch. In `next` the message now includes the port.
