### ISSUE TITLE
Oversharding may cause spurious failures in `index_create`, `index_rename`, and `index_drop`

### ISSUE THREAD

**Issue by Tryneus** [rethinkdb/rethinkdb#2904]
While testing the script for secondary index rebuilding in #2799, I ran across the case that an oversharded table will randomly have errors for creating and renaming (and presumably dropping) indexes.  This is because the secondary indexes are stored on the same btree, so whichever request gets to the store_t second will fail.  We return only the first result (which may be effectively random), so the probability that the index call fails is directly based on how oversharded the table is.

Marking this for 1.14 because it would be really nice to have a reliable script, even if users are oversharding.

**Comment by timmaxw** [comment]
The proper solution will soon be in the `raft` branch. It's currently in CR 2712.

**Comment by timmaxw** [comment]
Proper solution was merged into `raft` branch by d1110bf445a7bb205e551662326f19c5a4c04e80.
