### ISSUE TITLE
Unlikely clustering race condition

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#2933]
Consider the following scenario:

The user has a server `a` with some data on it. Two servers `x` and `y` connect to `a` simultaneously, so they exchange semilattice metadata with `a`; but the exchange between the two is delayed. So `a` sees all three servers in the semilattices, but `x` and `y` each only see themself and `a`. A user issues a configuration change on each one that causes a new blueprint to be issued with `x` or `y` as the sole data host. Because `x` and `y` don't see each others' entries in the semilattices, `x`'s blueprint contains only `x` and `a`, and `y`'s blueprint contains only `y` and `a`. `x`'s blueprints propagates to `a`, so `a` goes into `nothing_when_safe` state; and `x` and `y` backfill from it. But `x`'s blueprint doesn't propagate to `y` and `y`'s blueprint doesn't propagate to either of the other machines. When the backfills finish, `x` and `y` still ignore each other because neither's blueprint mentions the other, so they both think it's safe to become primary. Now we have two primaries. Both of them will accept writes, so data can diverge.

This sequence of events is technically possible because the RPC layer provides no guarantees about how fast the semilattices will propagate between machines. However, I don't think we should fix this bug. It's incredibly unlikely in practice--I would guess that we couldn't reproduce it if we tried--and nobody seems to have run into it so far. It seems like a lot of work to fix. And the code that contains this bug is likely to be rewritten within the coming year when we modify the clustering layer to work even when some machines are missing, so the bug will be fixed then.

**Comment by danielmewes** [comment]
I believe Raft is going to fix this.
Let's not bother with it before then.
