### ISSUE TITLE
.values() method

### ISSUE THREAD

**Issue by merrihew** [rethinkdb/rethinkdb#2945]
I'd like to suggest implementing the reverse of the ````.keys()```` method for retrieving an array of the values from an object.  I have not been able to find an easier method then ````.coerceTo().map()```` and its functionality I use often.  Thanks!

**Comment by mlucy** [comment]
This sounds good to me as described.

**Comment by danielmewes** [comment]
Sounds good. We should guarantee that the ordering of values in the result array corresponds to the ordering in the result of `keys`.
I don't think we need to make any more specific guarantees about it.

**Comment by danielmewes** [comment]
Marking settled as described.

**Comment by marshall007** [comment]
> We should guarantee that the ordering of values in the result array corresponds to the ordering in the result of `keys`.

@danielmewes does `.keys()` give you the keys sorted lexicographically right now? I think it does but it's important for [#3761 (comment)](https://github.com/rethinkdb/rethinkdb/issues/3761#issuecomment-95033615) that `r.object('0', 1, '1', 2).values()` returns `[1, 2]`.

**Comment by danielmewes** [comment]
@marshall007 Yes it does, though we don't really guarantee it.
Actually I didn't think about that properly when I suggested using `values` in #3761. If you have more than 10 groups in a `match` the ordering of `values` will be off.

**Comment by encryptio** [comment]
Working on this, code review 3196 on my `ckastorff_2945_values branch` is out.

**Comment by coffeemug** [comment]
Whoo, first commit! :cake: :fireworks: :clap:

**Comment by encryptio** [comment]
Fixed in 69461f6
