### ISSUE TITLE
Changefeed redundancy

### ISSUE THREAD

**Issue by dminkovsky** [rethinkdb/rethinkdb#2953]
I'm in the process of using `r.changes()` to implement some important functionality in my app. My problem is that I'm seeing a single point of failure here. If the process that's reading a changefeed fails and disconnects from Rethink, further changes will be discarded until the process comes back up (it is my understanding the Rethink only buffers changes internally while a process is connected and tailing that buffer).

Are there plans to address this issue in the design of changefeeds? Am I looking at something incorrectly?

Thank you.

**Comment by danielmewes** [comment]
Discussion about this feature has moved to https://github.com/rethinkdb/rethinkdb/issues/3471.
