### ISSUE TITLE
Should I use a loadbalancer with a rethinkdb cluster?

### ISSUE THREAD

**Issue by timjrobinson** [rethinkdb/rethinkdb#2956]
I can't find any documentation on how to properly run a cluster of 2+ nodes with rethinkdb. Should I just set them up and make clients connect to the first server? Or should I use a loadbalancer such as HAProxy or nginx in front of the cluster and go through that? If I should be using a loadbalancer what settings should I be specifying for maximum performance? 

It would be good to have a doc that explains even the basics of how this should be setup. If you could point me to any docs related to this it would be much appreciated.

**Comment by hellodk** [comment]
we have two client machines, how do we connect both of them using proxy server? As you said earlier:
"To start a RethinkDB proxy on the client:
rethinkdb proxy -j <server1host> -j <server2host> ..."
only of the clients can connect in this way, since the ports will already be in use.

**Comment by danielmewes** [comment]
Try passing‎ '-o 1' to rethinkdb proxy. That will shift the ports that it's using by an offset of 1.

**Comment by larkost** [comment]
Alternately you can pass `0` to all of: `--cluster-port`, `--driver-port`, and `--http-port`. This will get random open ports from the OS, but does mean you need to read the ports out of the log file. We effectively have some sample code on doing this in [`test/common/driver.py`](https://github.com/rethinkdb/rethinkdb/blob/next/test/common/driver.py#L517) that watches the log file for this output. Depending on your goals this might be overkill. In case that has moved in the mean time, the function is named `read_ports_from_log`.
