### ISSUE TITLE
Make dbCreate/tableCreate return more information

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#3001]
Now we return `{created: 1}`.

If we could return what I get in the `db_config` table, it would make a more reactive interface.

If we don't, I'll fire an extra query to immediately fetch data, but it would be better to minimize the number of HTTP queries.

Same thing for `tableCreate`. It would be nice to return what is in `table_status`

**Comment by timmaxw** [comment]
Merged into `next` in 7cbfc7066908f13c2106b548ba46565cf225df4d.
