### ISSUE TITLE
Array over size limit should provide more guidance

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#3061]
If the table `test` has more than 100k documents, this will return an error:

```
r.db('test').table('test').orderBy('id')
```

The error being:
```
RqlRuntimeError: Array over size limit `100000` in:
r.db("test").table("test").orderBy("id")
```

We should mention the `arrayLimit` option or the fact that they can use an index.

**Comment by llambda** [comment]
Yes e.g. orderBy({index: r.desc('id')}) would be helpful to know from the error message; this caught me up.

**Comment by gyelwande** [comment]
The issue is fixed.

**Comment by danielmewes** [comment]
@gyelwande I might have missed this. Which change fixed this?
