### ISSUE TITLE
MacOS installer .pkg should check if binary is running before allowing an upgrade install

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3072]
Currently our installer will happily replace the rethinkdb binary even if it is in active use. We should use `lsof` to check if it is open, and refuse to install if it is. The same should also take place for un-installs.

**Comment by danielmewes** [comment]
What is the behavior of HFS+ in this case?

On Linux it is standard practice to replace binaries while the program is running. `dpkg` for example makes use of that to reduce the downtime of server processes.

**Comment by larkost** [comment]
The issue is not with HFS+, everything we run on has to conform to POSIX (more or less), and that is what defines the behavior on open files. This was a technical issue when the web interface used a lot of external files, since those could then get out-of-sync with the web ui. Now that those are embedded in the binary there is no real technical issue.

There is still an expectation issue, in that someone who is installing an upgrade might expect that we would relaunch the server. But I am ok with no trying to go down that road.

ping @danielmewes

**Comment by danielmewes** [comment]
I see, that makes sense.
I don't think we should do anything here. We can reconsider if we end up installing a launchd script with the package (https://github.com/rethinkdb/rethinkdb/issues/2717).
