### ISSUE TITLE
Rethinkdb & newrelic

### ISSUE THREAD

**Issue by listepo** [rethinkdb/rethinkdb#3076]
Please create rethinkdb plugin for newrelic https://docs.newrelic.com/docs/plugins/developing-plugins

**Comment by murphyrandle** [comment]
Is this on anyone's radar currently?

**Comment by danielmewes** [comment]
@murphyrandle None of us is currently working on this.

**Comment by murphyrandle** [comment]
K, thanks @danielmewes

**Comment by modosc** [comment]
I started working on new relic instrumentation in ruby and js - is this the right issue to ask questions related to this or should I open a new one?

**Comment by coffeemug** [comment]
@modosc -- that's awesome! Feel free to ask questions here.

**Comment by builtinnya** [comment]
+1

**Comment by baradas** [comment]
+1

**Comment by goldendase** [comment]
+1

**Comment by StephenWeber** [comment]
There's a PR in the MeetMe plugin's repo for RethinkDB support: https://github.com/MeetMe/newrelic-plugin-agent/pull/392

It's a year old and hasn't been merged, I'm not sure it's compatible with current releases of RethinkDB but perhaps someone could pull down that fork and try it out?

**Comment by zedtux** [comment]
This issue has been closed without any comment on the reason.
