### ISSUE TITLE
Add a __version__ variable to the Python driver

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3100]
For remote troubleshooting it would be very helpful for the Python driver to have a `__version__` variable, making it easy to figure out. This would probably require having the makefile insert this into at least `__init__.py` based on the output of `scripts/gen-version.sh`. It is probably overkill to put it into each file. The only issue there is that we have driver versions separate from the server version, so that will need to be resolved.

The same thing should also be done for the Ruby, and the JavaScript driver if it supports it.

**Comment by danielmewes** [comment]
Closed by https://github.com/rethinkdb/rethinkdb/pull/3971 thanks to @yograterol
