### ISSUE TITLE
Job control API

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#3115]
I discussed this in person with @timmaxw and @Tryneus -- this would be a spectacular addition to the reql admin release, and would take care of a number of related issues:

- long running query log (and ability to kill)
- much needed visibility into internal system processes

I propose to create a system table `jobs`, and include any tasks that might make significant impact on the performance of the system. Off the top of my head:

- user queries
- any time GC spins up
- secondary index post-construction
- replication

The user ought to be able to delete documents from the table to kill jobs (we may not let them delete everything; but certainly user queries and index post-construction).

I'm purposely omitting the structure of the document from the spec. I think the implementer should take a pass at it first and let us play with a prototype. Once we do, we can tune the API to make it more user-friendly (like we did with other parts of the reql admin).

**Comment by VeXocide** [comment]
Adding `"backfill"` jobs to the `rethinkdb.jobs` table is in CR 2423 by @timmaxw

**Comment by danielmewes** [comment]
:clap: :-)

**Comment by VeXocide** [comment]
The `"backfill"` jobs are merged into `next` via commit 0fc416b0121f8e645a5eeda6cb9e660537cbba87.

**Comment by VeXocide** [comment]
Adding progress tracking to `"index_construction"` jobs is in CR 2482 by @timmaxw

**Comment by VeXocide** [comment]
Adding progress tracking to `"index_construction"` jobs is merged into `next` via f2ee92543d53a6103c021c4be4fd94df7b45a681

**Comment by VeXocide** [comment]
Tests for the `rethinkdb.jobs` table are in CR 2498 by @larkost

**Comment by VeXocide** [comment]
Tests for the `rethinkdb.jobs` table are merged into `next` via dd756f9ba9f442fdf260ac50e22b3dc1cba2d0c8.

**Comment by danielmewes** [comment]
@VeXocide Can you merge the tests into v1.16.x as well?

**Comment by danielmewes** [comment]
I opened https://github.com/rethinkdb/rethinkdb/issues/3647 to track post-1.16 improvements to the jobs table. Closing this. Great work!
