### ISSUE TITLE
Fulltext Search

### ISSUE THREAD

**Issue by 3goats** [rethinkdb/rethinkdb#3140]
Are there any plans to implement a full text search capability with RethinkDB along the lines of RIAK and the SOLR integration? 

Carl

**Comment by cserb** [comment]
@deontologician Is there any plan to add full text search like ArangoDB or PostgreSQL? Installing and dealing with Elasticsearch just to perform very simple full text queries seems like overkill.

**Comment by deontologician** [comment]
@cserb fulltext search is encompasses a lot of different kinds of indexes and use-cases. What kind of queries were you thinking of?

**Comment by cserb** [comment]
@deontologician With PostgreSQL I usually create a tsvector[1] column and feed it with different fields (while assigning a weight) I want to include whenever I do an INSERT or UPDATE. Then when I want to search I perform a search only on the tsvector column. This approach has it's obvious drawbacks, but I would argue that it's enough for 80% of smaller projects or projects where search is not the main feature.

[1]http://www.postgresql.org/docs/9.1/static/textsearch-controls.html

**Comment by deontologician** [comment]
So, it looks like for that use case, we'd need the lexing function (with a labelled dictionary for each language) and a ranking function for weighting search terms vs. results. Maybe multi-indexes could be used for this, but I don't know if they are capable of taking into account ordering. 

ping @danielmewes for what we should open an issue for

**Comment by danielmewes** [comment]
You can achieve some parts of the `tsvector` functionality by using multi indexes and `split`. For example:
```
table.indexCreate("text", function(x) { return x('text').split(" "); }, {multi: true})
```

However that doesn't take care of removing words like "a" or converting plural into singular nouns.

**Comment by danielmewes** [comment]
There's an open issue about adding native fulltext indexes, but it's not on the roadmap yet: https://github.com/rethinkdb/rethinkdb/issues/2601

**Comment by deontologician** [comment]
Ah, I missed it. I searched for `fulltext`

**Comment by danielmewes** [comment]
GitHub's issue search is a bit ... picky.

**Comment by cserb** [comment]
thanks @danielmewes
