### ISSUE TITLE
Update docs for 1.16

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#3141]
Beside generating the docs from the docs repo, the data explorer need a little tweak to properly handle "toJSON, toJsonStringify".

**Comment by danielmewes** [comment]
Looks like we'll have to apply this commit specifically https://github.com/rethinkdb/rethinkdb/commit/747add43dad509036b7eabebad3eaf37d6445313

**Comment by danielmewes** [comment]
The mentioned commit seems to assume that we want to handle `toJsonString` in the Data Explorer as an alias to `toJSON` if I understand it correctly.
I can't find any mention of `toJsonString` (or `toJsonStringify`) in any other issue, so I assume the patch is probably not necessary?

**Comment by danielmewes** [comment]
Talked to @neumino and it turns out we renamed `toJSON` to `toJsonString()` as part of https://github.com/rethinkdb/rethinkdb/issues/3123.

**Comment by danielmewes** [comment]
An updated version of the suggestions handling for `toJSON`/`toJsonString` is now in CR 2524 by @AtnNn .

**Comment by danielmewes** [comment]
Fix merged into v1.16.x and next https://github.com/rethinkdb/rethinkdb/commit/82f6aa469970c158477a5be3aace3a93f5b4123d
