### ISSUE TITLE
Only bind ports on 127.0.0.1 by default

### ISSUE THREAD

**Issue by mrkurt** [rethinkdb/rethinkdb#3154]
We tend to use 127.0.0.2 - 127.0.0.254 for binding various, often conflicting ports. After I've added some of these as aliases in OSX, RethinkDB binds to all of them at start time — consuming my precious ports.

**Comment by Tryneus** [comment]
Changes are up in review 2425.  I went with the `--no-default-bind` option.

**Comment by Tryneus** [comment]
This has been approved and merged into `next` in commits 0116bb7 and 47943e0.  Will be in release 1.16.
