### ISSUE TITLE
Test point change feeds

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3157]
We are going to ship point change feeds in 1.16.
This feature is implemented in next, but needs some testing.

@larkost said he would write those tests. Please coordinate with @mlucy about which corner cases need to be tested, and how (/if) this is different from table change feeds.

**Comment by danielmewes** [comment]
I believe this is done.

**Comment by larkost** [comment]
We don't have tests for this really at this point. Some are underway.

**Comment by danielmewes** [comment]
@larkost what is missing for this?

**Comment by larkost** [comment]
I thought that this still needs to be merged in, but it seems that it already got merged in along with #3876. There was one minor change from the review that is in `next` with 401ff2d.
