### ISSUE TITLE
Print new version notifications in the server logs

### ISSUE THREAD

**Issue by drakester1** [rethinkdb/rethinkdb#3170]
We use a custom build of rethinkdb pretty heavily and love it, but it would be really nice to see new version notifications in the server log. The browser-based administration console is great for our developers, but as an ops person, I hooked a few custom monitoring tools into `/ajax` to view server logs, historical performance, etc. It would be great to know when new versions are available, particularly for point releases that fix critical bugs, and it's a pain to do it by following the blog/opening the web console/going to rethinkdb.com. Having a message in the server log would be really helpful.

**Comment by danielmewes** [comment]
https://github.com/rethinkdb/rethinkdb/issues/3475 and https://github.com/rethinkdb/rethinkdb/issues/3666 have the remaining bits for the future.
@gchpaco implemented the parts we need for 1.16. Closing.
