### ISSUE TITLE
show the list of bound interfaces in `server_status`

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3179]
From a admin perspective it would be nice to have the list of bound interfaces in `server_status`, e.g.: `'interfaces' : ['127.0.0.1']`

**Comment by danielmewes** [comment]
We have the `canonical_addresses` field now with a list of all addresses a server is bound to.

**Comment by Tryneus** [comment]
Technically 'bound' and 'canonical' addresses are not the same.

**Comment by danielmewes** [comment]
Ah my mistake. It's probably still sufficient in 95% of the cases.
For the other 5% the bound interfaces can be parsed out from the logs.
