### ISSUE TITLE
Empty "Connected to" field in web UI of proxy nodes

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3182]
@AtnNn noticed that connecting to the web UI on a proxy node, the "Connected to" field at the top of the page is empty.

Since proxy nodes don't have a name, I think we should change the web UI to display `Connected to <proxy node>` or something along those lines.

**Comment by deontologician** [comment]
How do we know if it's a proxy node? I'm not familiar with how they work

**Comment by danielmewes** [comment]
Hmm we might have to determine that on the server and then return some special value in `ajax/me`.
The current state is that "<Unknown>" is shown under "Connected to", but the rest of the status bar (at least Servers */* connected and Tables */* ready) are broken (= remain empty) when opening the web UI on a proxy.
I think this is going to be a relatively rare use case, so I wouldn't worry about this for 1.16.0.

**Comment by deontologician** [comment]
@danielmewes Can someone add the special value in `ajax/me` ? This should be easy to fix then. Currently `ajax/me` is just the unquoted name of the server, but if we make it a json value, it's a small change to update the logic

**Comment by danielmewes** [comment]
@VeXocide or @Tryneus can probably do this.
It's low priority though.

**Comment by encryptio** [comment]
`/ajax/me` was removed in 22b9e92. The web UI was switched to use `conn.server()` instead (which is broken on proxy servers; see #5485.)

Since this is related to #5485 which I'm working on, I'll fix up the web UI to use the new `isProxy` value in the same branch.
