### ISSUE TITLE
Distribute ChangeFeed

### ISSUE THREAD

**Issue by wojons** [rethinkdb/rethinkdb#3184]
#2953 which has redundancy.

I sugguesed that there were names to change feeds so that you can reconnect and get changes that were not processed another useful think would be that you would be able to use the same name system and connect many server to the same change feed system. This way you are now able have many processes look at the same feed and negiocate who gets what. lets call it roundrobin. 

Lets say i have 3 processes connected to the same chagne feed with the same name. All processes connect and start to wait. when a change comes in a random changefeed process is selfect and then is unable to get a change. if another change comes in before the first busy one acklaoges its finshed then another process will get the feed. if no process is avaialable then it will buffer until a process is able to process it. this way 100s of processes can work together on a single change feed. There may need to be sytems in place so that if its never acklaged after timeout it goes back into change feed.

**Comment by danielmewes** [comment]
https://github.com/rethinkdb/rethinkdb/issues/5038 has an API proposal for this. Closing this in favor of the #5038.
