### ISSUE TITLE
Resolving a conflicting auth key in the web UI shows an incomplete message

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/rethinkdb#3189]
This is what you see when you resolve a conflicting auth key when joining two nodes that each had auth keys set:

![screen shot 2014-10-13 at 6 42 11 pm](https://cloud.githubusercontent.com/assets/91193/4622934/5c3e5ca0-5343-11e4-951b-9a683d56c2fc.png)

Note the message:
> You successfully resolved the configuration value to .

It's missing the actual auth key that was chosen.

**Comment by danielmewes** [comment]
@timmaxw changed conflict resolution, and conflicting auth values are now resolved automatically (based on timestamp). There is no such message in the web UI anymore as far as I know.
