### ISSUE TITLE
Integrate cursors with json libraries on client side

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#319]
Currently in order to convert the result of a query to JSON (discovered in Python, but should apply to other clients as well), the user has to do the following: `json.dumps(list(cursor))`. At least in Python, if we provide the right method, the user will be able to say `json.dumps(cursor)`. This is both nicer, and less confusing.

**Comment by srh** [comment]
Closing.  Yet another piece of code to maintain, and quite specific to JSON serialization libraries.  But if you still want this feature, by all means complain.
