### ISSUE TITLE
object internal order preservation

### ISSUE THREAD

**Issue by techdragon** [rethinkdb/rethinkdb#3194]
I have a small dance I perform in order to get from the query result to a python ordered dict without letting the query logic 'corrupt' the ordered JSON object I'm querying. So firstly, somewhere in the query semantics it would be nice to be able to specify order is important, in python there is a dead simple tool for this 'ordereddict' which functions exactly like a dictionary, it just won't screw up the order of its internal parts. I dug in, having a look with an eye towards making a PR, but wasn't sure quite where to place the logic yet. Ideally the final result would be either an ordered dict for individual object queries, or a list of ordereddict objects for queries that return a list. 

Secondly... and more importantly, can we get documentation or an answer, on if the underlying rethinkdb engine, preserves the order of the document. Since theres no point in me working on an ordereddict enabling argument/option for the python driver, if rethinkdb itself doesn't store the internal order of the json object.

**Comment by danielmewes** [comment]
We can add a new ReQL type at some point which is an ordered map.
You could generate one by something like
`object.fixOrder('attr1', 'attr2', 'attr3')`
to make the keys be ordered as `attr1`, `attr2`, `attr3`

**Comment by srh** [comment]
Adding a new ReQL type for this would be a ton of work just in the specification.  I recommend making a client side function used like `obj2 = reorder(obj1, ['attr1', 'attr2', 'attr3'])` and using that to get your object's keys in order.
