### ISSUE TITLE
switch / if-elseif-elseif-else term

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3199]
Currently the `r.branch()` term isn't that great to use if you have more complex case distinctions.

Proposed by @wojons: Add a variadic term taking 2N+1 arguments
```
r.switch(cond1, val1, cond2, val2, ..., condN, valN, default_val)
```

Its semantics are those of the following code block in C:
```C++
if (cond1) return val1;
else if (cond2) return val2;
...
else if (condN) return valN;
else return default_val;
```

We could also make `r.branch()` variadic, instead of introducing a new term.

**Comment by coffeemug** [comment]
:+1: for extending `r.branch` and not introducing a new term.

**Comment by deontologician** [comment]
extending `r.branch` seems obviously good.

**Comment by wojons** [comment]
I think r.branch sounds more like its forking something but fair enough for extending it as long as i dont have to use 10 of them.

**Comment by VeXocide** [comment]
Extending `r.branch` seems obvious, are we considering renaming it as well?

**Comment by danielmewes** [comment]
I'd like to keep the renaming discussion separate and for later.

**Comment by danielmewes** [comment]
Marking as settled for making `branch` variadic to support multiple branches.

**Comment by pilwon** [comment]
:+1: fantastic idea to make `r.branch` more powerful!

**Comment by encryptio** [comment]
Done in `next` as of `bf5b28b`, CR 3201

**Comment by mlucy** [comment]
@encryptio -- is there a docs issue?

**Comment by encryptio** [comment]
@mlucy Writing an issue out now.
