### ISSUE TITLE
Web UI: Change way table reconfiguration is presented

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3229]
Suppose someone manually configures a table using tags or other advanced features.

If a user later wants to increase for example the replica count, they might be tempted to go to the table's page in the web UI and increase the replica count there. This however will overwrite the original configuration, ignoring any tags.

Since we are not storing the fact that the table was originally configured in a more advanced way, we have no way to warn the user about the loss of their original configuration.

We should probably change the workflow in the web UI as follows (suggested by @coffeemug):
- Reconfiguring a table calls `table.reconfigure` with the `dry_run` flag set. This gives us a new configuration for the table. The web UI pops up some kind of dialog displaying the new configuration in a nice format. It should explain that the new configuration is going to overwrite any previous configuration (probably it should also display the old configuration).
- If the user confirms the change, we will write the generated config to the `table_config` table to commit the change.

**Comment by deontologician** [comment]
This is merged into next with 2a9c8b7

**Comment by mglukhovsky** [comment]
@deontologician: congrats, so much work went into this! :clap:
