### ISSUE TITLE
configure (and possibly others) assume python executable is Python 2

### ISSUE THREAD

**Issue by goodgerster** [rethinkdb/rethinkdb#3244]
The `configure` script attempts to detect Python (presumably by querying the `python` executable in `$PATH`) and will fail if it finds Python 3, as is the case by default under Arch Linux:

> Error: python 3.4.2 is too recent. At most python 2.9.99 is required.

Workaround: [the ArchWiki article on Python](https://wiki.archlinux.org/index.php/Python#Dealing_with_version_problem_in_build_scripts) suggests installing some bash voodoo in `$PATH` in order to redirect specific scripts to `python2`. (I have not tested this).

Possible resolution: `configure` should instead look for an executable named `python2`.

Probable further bug: whatever `configure` wants Python 2 for may also be labouring under the assumption that `python` means Python 2.

**Comment by AtnNn** [comment]
The configure script currently checks that `python` is Python 2.

Python 3 may be supported soon, see #3731.

**Comment by deontologician** [comment]
Would it be possible to change the hashbang line to just be "#!/bin/bash python2" ?

**Comment by deontologician** [comment]
updated my previous comment

**Comment by AtnNn** [comment]
Using `python2` would break in some environments where RethinkDB gets built that have `python` but not `python2`. It would also force users to use Python 2.

All our Python scripts that run during the build are compatible with Python 3. This is however not the case for the bundled version of v8. After upgrading v8 (see the `atnnn/v8` branch, currently in review), I'll revisit #3731.

See also https://www.python.org/dev/peps/pep-0394/ and the linked threads
