### ISSUE TITLE
Very slow test results

### ISSUE THREAD

**Issue by gotlium** [rethinkdb/rethinkdb#3245]
Today I test RethinkDB vs MySQL, and what I see?

RethinkDB is very slow when I using Limit or Group with Sum, Insert and Read.
This is a results for 2 million records on last MB Pro:

```
SELECT SQL_NO_CACHE * FROM table limit 1000000, 10; -- MySQL==5.6.21, InnoDB
319ms

r.table("table").skip(1000000).limit(10) // RethinkDB==1.15.1
7.84s
```

Simple select:

```
SELECT * FROM table WHERE slug = 'd4436de862fbc706d76608a8818a1158';
2,5ms

table("table").filter(r.row('slug').eq('d4436de862fbc706d76608a8818a1158'))
5.28s.
```

Insert 2 million records:

```
MySQL: 25 sec. all in one + Index for 2 fields, . CPU < 84%
RethinkDB: 17m by 50k rows + Indexing 2 fields. If > 50k, I get socket error. . CPU > 400%, Mem: 1k+
```

For read & aggregate I get equal results above.
I think, it's a very-very bad results.

I can say, MongoDB showed worse results.
You can test all by your self. All my interest for RethinkDB this is a GUI and sharding. Results is sad but true ...
You can close or remove this issue, but I believe you can do it better!

**Comment by tabvn** [comment]
so ? i 'm a fan of Mongodb ? anyone had test with Rethinkdb vs Mongodb ?

**Comment by bruce327** [comment]
@larkost https://lnkr.fun/813dc87
