### ISSUE TITLE
On rethinkdb reboot table not in sync

### ISSUE THREAD

**Issue by wojons** [rethinkdb/rethinkdb#3246]
This has been an issue i have been facing.

I have tables that are weekly at the end of a week that table will not get any writes any more i have tables many weeks old that when the replicas are restarted or the primary is restarted the replicas then claim that they are no longer up to date and start syncing data And then will say they are up to date and if I restart them again they will say they are not up todate but there are no new writes to the table.

**Comment by danielmewes** [comment]
This was probably resolved with 2.1, since we rewrote most of the backfilling logic.
