### ISSUE TITLE
ql2.proto TIME term documentation incorrect

### ISSUE THREAD

**Issue by mfenniak** [rethinkdb/rethinkdb#3248]
ql2.proto's documentation for the TIME term shows two formats that don't seem to actually be supported.

```
// Construct a time from a date and optional timezone or a
// date+time and optional timezone.
TIME = 136; // NUMBER, NUMBER, NUMBER -> PSEUDOTYPE(TIME) |
            // NUMBER, NUMBER, NUMBER, STRING -> PSEUDOTYPE(TIME) |
            // NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, NUMBER -> PSEUDOTYPE(TIME) |
            // NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, NUMBER, STRING -> PSEUDOTYPE(TIME) |
```

The three-arg and six-arg options don't seem to be supported.  Sending a term with only three arguments (year/month/day values) results in an error, "Expected between 4 and 7 arguments by found 3."  Sending a term with six arguments (year/month/day/hour/minute/second values) results in an error, "Got 6 arguments to TIME (expected 4 or 7)".

**Comment by Tryneus** [comment]
This has been fixed and merged to `next` in commit f7d90b8.  Review was 2461.  Will be in release 1.16.

Thanks for reporting this, @mfenniak!
