### ISSUE TITLE
Rename and generalize `zip`

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#325]
Currently our `zip` operator has two flaws:
1. It's different from what one would expect `zip` to be (which is described in #324)
2. It's very oddly specific in that it hardcodes `left` and `right`.

Here's what I think we should do:
1. Rename `zip` to `flatten`
2. Generalize it so that it can do more arbitrary object flattening:

```
r.expr({ left: {a : 1}, right: { b: 2}}).flatten('left', 'right') ==> { a: 1, b: 2 }
```

The generalization should also account for nested objects, so we should probably wait until we work out `pluck` before we do this.

**Comment by sunjay** [comment]
Note that this is still referenced in the docs here: https://rethinkdb.com/docs/table-joins/

Given that this has been superseded by a new issue and given that the new issue is on the backlog that should probably be updated.
