### ISSUE TITLE
`rethinkdb import` attempts to import system tables

### ISSUE THREAD

**Issue by Tryneus** [rethinkdb/rethinkdb#3261]
If you run `rethinkdb export` in `reql_admin`, it will export `r.db('rethinkdb')`, which I think is fine.  It's actually kind of cool to be able to make a backup of your cluster configuration.

The problem, however, is that running `rethinkdb import -d` will automatically try to import these tables.  I think the script should skip system tables when importing a directory.  A user could still import a system table explicitly using `rethinkdb import -f`.

**Comment by bussiere** [comment]
same here : 

Importing from directory...
Error: Cannot import tables into the system database: 'rethinkdb'
Error: rethinkdb-import failed

**Comment by mglukhovsky** [comment]
@bussiere: have you checked the version of your RethinkDB Python driver with `pip freeze`?

The import / export script relies on the Python driver installed. If you're running an older version of the driver (< 1.16.0-2), you should upgrade the driver:

```
sudo pip install -U rethinkdb
```
