### ISSUE TITLE
rename indexesOf

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3265]
Theres a bit of a confusing name clash between array indexes (which indexesOf refers to), and table indexes.

```javascript
r.table('foo').indexesOf('foo')
```

You might expect this to return something about secondary indexes that involve the 'foo' field or something.

Possible suggestions:

* position_of
* get_position

**Comment by deontologician** [comment]
I like `offset_of`

**Comment by mlucy** [comment]
Democracy time, maybe?  Here are the candidates:
* `positions_of`
* `offsets_of`
* `indexes_of`

**Comment by mlucy** [comment]
+1 for `offsets_of` myself.

**Comment by danielmewes** [comment]
`offsets_of` or `positions_of` are both fine with me, and definitely better than `indexes_of`.

**Comment by gchpaco** [comment]
:+1: for `offsets_of`.  I could live with `positions_of`.

**Comment by VeXocide** [comment]
:+1: for `offsets_of`, but likewise I could live with `positions_of`.

**Comment by mlucy** [comment]
Planning to mark this as settled for `offsets_of` on Monday unless anyone objects strongly.

**Comment by VeXocide** [comment]
This is in CR 2608 by @Tryneus

**Comment by VeXocide** [comment]
Merged into `next` via commit 0d0c2c4fecf7f0d85a7190081dac299077e58b3e

**Comment by mlucy** [comment]
@VeXocide -- Is there a docs issue open for this?

**Comment by VeXocide** [comment]
There we go
