### ISSUE TITLE
Standardize terminology for a server missing/dead/down/unavailable/unreachable

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#3280]
See discussion in #3258. The problem with "dead" and "down" is that we can't tell the difference between a server that's actually dead and one that's alive but we can't talk to. @mglukhovsky prefers "unreachable". I like "unavailable" because it's clearly the opposite of "available".

Once we settle on a term, we should try to use it consistently in the admin interfaces. In particular, this affects the `table_status`, `server_status`, and `issues` system tables, and the web UI.

**Comment by Tryneus** [comment]
The fix has been approved by @mglukhovsky and merged to `next` in commits e08c1dc and 399432a.  Will be in release 1.16.
