### ISSUE TITLE
Introduce ReQL logging facility

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#329]
One of the big problems in building up and debugging large ReQL queries is that it's often difficult to determine what things look like in intermediary steps. It feels like if only we could say `r.log(...)`, things would be so much easier, but rethink doesn't allow that.

I don't have good ideas for _how_ to introduce logging, but we should think about what we can do to make people's lives easier. One idea I had is to allow wrapping any ReQL command in an `r.log` command, which would print all input to the command (on the parser server console, or return it back to the client). E.g.:

```
table.log(filter(...))
```

Would print all inputs to `filter`.

This is a precursor to a reql debugger, but that's a whole other conversation.

**Comment by thelinuxlich** [comment]
@srh is this yet valid since we have a query profiler?

**Comment by srh** [comment]
I don't know anything about the query profiler, but presumably, maybe, it removes some of the need for this.  Will close.
