### ISSUE TITLE
Execute queries in parallel on a single connection

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#3296]
Not to be confused with #2156, which is about evaluating parts of a single query simultaneously.

The JavaScript driver and many community drivers are asynchronous, but they don't get the full benefit of it because the server will only evaluate one query at a time on a single connection.

This also causes pathological behaviour when using changefeeds. Each changefeed adds a possible latency of 500ms to all other queries on the same connection. The only sane way to use changefeeds is to open a new connection for each changefeed. I believe this problem would be better solved by allowing parallel execution of queries on a single connection and not by adding server pools.

Another disadvantage of the current situation is that listening on an empty changefeed will cause an empty response to be sent every 500ms. This causes useless wake-ups and network traffic.

With this proposal, if a user waits for the result of a query before sending the next query to the server, queries would still be executed sequentially.

When this is implemented, we should include a backwards-compatible mode. Some drivers rely on the fact that responses are in the same order as their respective requests.

To avoid complications in the web UI, it may be easier to not make this change for HTTP connections.

This proposal is based on my understanding of the current behaviour, please correct me if I am wrong.

@mlucy @danielmewes Any thoughts?

**Comment by danielmewes** [comment]
Despite a certain potential to expose new bugs, I'm scheduling this for 2.0.

The reason is that having multiple changefeeds open on the same connection (as discussed in https://github.com/rethinkdb/rethinkdb/issues/3298 and https://github.com/rethinkdb/rethinkdb/issues/3678 ) isn't practicable without this change.

We should be conservative about when to enable this feature. I suggest two restrictions to this on the server side:
- only ever process one request at a time per request token. Make sure that per token, we send back responses in the same order in which the requests arrived. This avoids a whole bunch of potential race conditions (e.g. what if some cursor implementation sends two `CONTINUE` requests? what if it sends a `CONTINUE` and then a `STOP` before receiving the response to the `CONTINUE`?).
- Increase the protocol version magic. Only enable concurrent query execution for drivers that send the new magic. That way we can be sure not to break any existing (third party) drivers that are not prepared to handle parallel query execution.

**Comment by danielmewes** [comment]
To be clear regarding "Make sure that per token, we send back responses in the same order in which the requests arrived.":
I think it's enough to just keep the lock on the token until we've completely sent the response. I would avoid doing anything more complex (like pipelining) for 2.0.

**Comment by gchpaco** [comment]
I've complained in person that we shouldn't re-use tokens, like, at all; it just invites bugs.  If we're bumping the protocol magic *anyway* we could put something else in like "when you send a `CONTINUE` request, you supply in addition the token you're going to query next" or alternatively the server sends back a different token, or something similar.  The idea being that it should be impossible to send two `CONTINUE`s to the server before getting a response back from either one, and then trying to make sense of the resulting situation.  My intent here is that the server will send back information from one and then go "we already did this" with the other.  If the server sends back the token to use for the next request, it's actually impossible to submit two valid read requests on the wire before a response is gotten back from either one.

That said I do agree that we should worry about how much of it should be automatically parallelizable.  Changefeeds seem like an obvious instance where the default should be YES, parallelize.  Presumably if we made an option to `.run` that said "please run me in parallel" that would work too.  Are there any other default-YES situations we should worry about?

**Comment by mlucy** [comment]
I think we should default to parallelization for all queries (with some cap on the number of coroutines we spawn).  For asynchronous drivers like JS it makes more sense, because it's entirely plausible people will just be firing off queries while other queries are queued up.

**Comment by danielmewes** [comment]
> I think we should default to parallelization for all queries

:+1:

**Comment by internalfx** [comment]
:+1:

**Comment by VeXocide** [comment]
:+1:

**Comment by mlucy** [comment]
There seems to be general consensus on this; planning to mark it as settled on Monday.

**Comment by danielmewes** [comment]
@mlucy this is done except for https://github.com/rethinkdb/rethinkdb/issues/3754 isn't it?

**Comment by mlucy** [comment]
Yes.

**Comment by neumino** [comment]
If I open a feed, and send a `CONTINUE` query, I won't get any response until the server sees a change with (`v0_4`).
So if no change happens and if I want to close the feed, I have to send the `STOP` query.

My question is:
- What happens in this case? I seem to be stuck (no response is returned) for the `CONTINUE` or `STOP` query.
- Is the `CONTINUE` query supposed to return nothing? An error?

**Comment by neumino** [comment]
One more thing: If I force the `STOP` query, and trigger a change after that, the `CONTINUE` query returns an empty `SUCCESS_SEQUENCE`, but the `STOP` query will throw with something like `Token X not in cache`.

**Comment by mlucy** [comment]
@neumino -- that sounds like a bug to me; the `STOP` query should be interrupting the `CONTINUE` query.  Good catch!
