### ISSUE TITLE
Huge Performance Degradation During Rebalance

### ISSUE THREAD

**Issue by kmcgrady** [rethinkdb/rethinkdb#3303]
We initiated a rebalance after re-pinning a shard to a new host, the replication was very speedy in the beginning, but now it's a magnitude slower. It seems to be due to a ton of very small writes on a single host. The two other hosts are relatively idle. This has made the host under high load and unresponsive to other requests, which does not seem right. We have upgraded our servers and SSDs to be dedicated to the databases. Here's the hardware and software configuration below:

Server Info:
Intel Xeon E5-2660 4 cores
60GB of RAM (50GB configured as cache for RethinkDB) 256G DD3-1600
200GB SSD drive partition - Raid 1 - Samsung

![image](https://cloud.githubusercontent.com/assets/69432/4942627/881a15aa-65ed-11e4-8586-10ba72c7a699.png)

Here is what iostat is saying about the one host.
![image](https://cloud.githubusercontent.com/assets/69432/4942628/8dfbd328-65ed-11e4-9c94-2464528e5c9c.png)

**Comment by danielmewes** [comment]
@kmcgrady Did you ever see this again and get a chance at dumping out `/ajax/progress`?
Note that starting with RethinkDB 1.16, we removed `/ajax/progress` and part of that information is now available in `r.db('rethinkdb').table('jobs')`.

**Comment by kmcgrady** [comment]
@danielmewes I have not seen this again thankfully. I will make note of that in future versions and let you know if anything pops up. Thanks!

**Comment by danielmewes** [comment]
Closing for now. We can re-open it if it pops up again.
