### ISSUE TITLE
Remove support for broken 1.13 datum comparisons and deprecate unmigrated indexes

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3311]
It's been a few versions; we should remove support for the broken `datum_t` comparison behavior from 1.13, rip out all the extra code to support it, and prevent people from using unmigrated 1.13 indexes.

**Comment by danielmewes** [comment]
We should start by changing the issue and log message for people who are using unmigrated indexes with 2.0. The message should warn people that their indexes are going to stop working in the next release of RethinkDB.

**Comment by mlucy** [comment]
This is in next, although we didn't manage to warn people in a previous release.
