### ISSUE TITLE
Cross compiling for ARM

### ISSUE THREAD

**Issue by kingkorf** [rethinkdb/rethinkdb#3312]
Hi all,

I'm trying to cross compile RethinkDB for a BeagleBone Black. I'm following [these](http://stackoverflow.com/questions/23172020/cross-compiling-rethinkdb-for-raspberry-pi) instructions on a 32 bit Ubuntu 14.04.1. I fixed some issues myself (--host=arm for curl) but can't fix the following OpenSSL build error:

```
vagrant@vagrant-ubuntu-trusty-32:~/tmp/rethinkdb-1.15.1$ make -j3
    [1/362] INSTALL-INCLUDE protobuf_2.5.0
    [2/362] INSTALL-INCLUDE gtest_1.6.0
    [3/362] INSTALL-INCLUDE re2_20140111
    [4/362] INSTALL-INCLUDE v8_3.22.24.17
    [5/362] INSTALL-INCLUDE boost_1.55.0
    [6/362] INSTALL-INCLUDE zlib_1.2.8
    [7/362] INSTALL-INCLUDE curl_7.36.0
    [8/362] INSTALL-INCLUDE openssl_1.0.1i
    [9/362] BUILD v8_3.22.24.17
    [10/362] BUILD protobuf_2.5.0
    [11/362] BUILD re2_20140111
    [12/362] BUILD zlib_1.2.8
    [13/362] FETCH libidn_1.28
    [14/362] BUILD openssl_1.0.1i
x86cpuid.s:321: Error: bad instruction `leal -4(%ecx),%ecx'
x86cpuid.s:322: Error: bad instruction `testl $-4,%ecx'
x86cpuid.s:323: Error: bad instruction `leal 4(%edx),%edx'
x86cpuid.s:324: Error: bad instruction `jnz .L021aligned'
x86cpuid.s:325: Error: bad instruction `cmpl $0,%ecx'
x86cpuid.s:326: Error: bad instruction `jne .L020little'
x86cpuid.s:327: Error: bad instruction `ret'
x86cpuid.s:330: Error: unrecognized symbol type ""
x86cpuid.s:331: Error: alignment too large: 15 assumed
x86cpuid.s:334: Error: bad instruction `movl $8,%ecx'
x86cpuid.s:337: Error: bad instruction `jc .L023break'
x86cpuid.s:338: Error: bad instruction `loop .L022loop'
x86cpuid.s:340: Error: bad instruction `cmpl $0,%eax'
x86cpuid.s:341: Error: bad instruction `cmovel %ecx,%eax'
x86cpuid.s:342: Error: bad instruction `ret'
x86cpuid.s:346: Error: bad instruction `call OPENSSL_cpuid_setup'
make[3]: *** [x86cpuid.o] Error 1
make[3]: Leaving directory `/home/vagrant/tmp/rethinkdb-1.15.1/build/external/openssl_1.0.1i/build/crypto'
make[2]: *** [build_crypto] Error 1
make[2]: Leaving directory `/home/vagrant/tmp/rethinkdb-1.15.1/build/external/openssl_1.0.1i/build'

Full error log: ./build/external/openssl_1.0.1i_install.log
make[1]: *** [build/external/openssl_1.0.1i/install.witness] Error 1
make[1]: *** Waiting for unfinished jobs....
^Cmake[1]: *** [build/external/protobuf_2.5.0/lib/libprotobuf.a] Interrupt
make[1]: *** wait: No child processes.  Stop.
make: *** [make] Error 2
```

Can anyone help me with this or does someone have another way of building for an ARM system. I looked at the [openSUSE build factory](https://build.opensuse.org) but could not figure out how to get that system building an ARM package of RethinkDB.

I hope you guys can help!

**Comment by AtnNn** [comment]
@kingkorf I have updated the build script to be able to cross-compile. I have only tested it on a Raspberry Pi:

http://www.atnnn.com/p/cross-compile-rethinkdb/

Does that work for you when compiling for your BeagleBoard?

**Comment by kingkorf** [comment]
@AtnNn I'll try it coming week :+1:

**Comment by oliver006** [comment]
https://github.com/rethinkdb/rethinkdb/issues/5094#issuecomment-172246699

Sorry, I think this should go here instead. Tried cross-compiling for ARM and got an error when trying to build icu for v8.
Any idea on how to address that?

**Comment by AtnNn** [comment]
@oliver006 Those instructions were written for RethinkDB 2.0, but RethinkDB has changed a lot since then.

Your log seems to indicate that `build/external/v8_3.30.33.16/build/third_party/icu/configure` might be missing. Are you building from a fresh source tree? You could try doing `rm -rf external/v8*; make clean` then test if it builds with `make install-include-v8`.

Related to #5137

**Comment by oliver006** [comment]
Yeah, fresh install. Tried you suggestion but it fails right away with the same error (`./configure: No such file or directory`)

**Comment by mbroadst** [comment]
@AtnNn yeah this is wierd. I'm trying to build this in yocto and getting to the same error. `build/external/v8_3.30.33.16/build/third_party/icu/configure` is definitely missing, but is instead located at `build/external/v8_3.30.33.16/build/third_party/icu/source/configure` not sure what's going on here

**Comment by mbroadst** [comment]
@AtnNn looks like the bug is in this line: https://github.com/rethinkdb/rethinkdb/blob/next/mk/support/pkg/v8.sh#L17

**Comment by jdmichaud** [comment]
Thanks for that oliver006, the next failure follows:
```
/usr/bin/install -c -m 644 ./unicode/vtzone.h /home/jedi/rethinkdb-2.3.5/build/packages/dsc/build/external/v8_3.30.33.16/include/unicode
make[6]: Leaving directory '/home/jedi/rethinkdb-2.3.5/build/packages/dsc/build/external/v8_3.30.33.16/build/third_party/icu/source/i18n'
make[5]: Making `install-headers' in `layout'
/bin/bash: line 10: cd: layout: No such file or directory
Makefile:141: recipe for target 'install-headers-recursive' failed
make[5]: *** [install-headers-recursive] Error 1
```
