### ISSUE TITLE
Null pointer passed to zero-length memcpy

### ISSUE THREAD

**Issue by srh** [rethinkdb/rethinkdb#3317]
Some null pointers are getting passed to zero-length memcpy calls.

This happens in the datum_string_t() constructor, and in store_key_t::min().

According to the internet, some systems, including relatively recent ones, choke on this.

Fixed in sam_0_null_undefined, awaiting review 2302.

**Comment by AtnNn** [comment]
That commit isn't on the server. The fix from review 2302 seems to be in 8fa0271 and 5b115e2.

**Comment by danielmewes** [comment]
There must be another commit to it. The CR also has a fix in src/btree/keys.hpp http://newton:8080/ui#file:review=2302/version=91564

**Comment by danielmewes** [comment]
(in any case it looks like the fixes are in v1.15.x)

**Comment by srh** [comment]
That commit hash had a capital N in it.
