### ISSUE TITLE
Joins should probably be prefix

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#332]
After actually writing real queries, I think `r.join(a, b)` is orders of magnitude nicer than `a.join(b)`. I think that in general we should adopt the following philosophy for the infix/prefix business:

1. Operations that accept multiple sequences should be prefix
2. Math and logic should be accessible via infix, prefix, and overloaded ops if the language allows it
3. Beyond that (with stuff like `[]` for `nth` and `[:]` for `slice`, we probably shouldn't use operator overloading because it tends to be annoying and confusing in practice)

**Comment by danielmewes** [comment]
Superseded by https://github.com/rethinkdb/rethinkdb/issues/2720
