### ISSUE TITLE
Reconsider the AGPL license

### ISSUE THREAD

**Issue by dandv** [rethinkdb/rethinkdb#3347]
I would like to use RethinkDB in an open-source project at Google, but [Google cannot use AGPL code](http://www.theregister.co.uk/2011/03/31/google_on_open_source_licenses/), and [does not even allow installing AGPL software on Google machines](https://www.quora.com/Do-internet-companies-such-as-Facebook-or-Google-use-MongoDB-despite-the-AGPL-license/answer/Dan-Dascalescu).

Would it be possible to use a different license?

**Comment by AtnNn** [comment]
This topic was brought up recently on the mailing list: https://groups.google.com/forum/#!topic/rethinkdb/g5UEck3sqMs

**Comment by williamstein** [comment]
> ...unless there are additional reason to do so.

There are additional reasons to do so.

**Comment by omeid** [comment]
So, considering the recent changes and developments, is it likely for this issue to be reconsidered?

I understand that the client drivers are licensed under Apache License v2.0, but anything AGPL is no go for a lot of companies.

**Comment by ivanov** [comment]
A recent issue, #6221, has an update and is still open. Thought I'd cross-link these two. I came here from [William's post](https://sagemath.blogspot.com/2016/10/rethinkdb-must-relicense-now-what-is.html).
