### ISSUE TITLE
Data Explorer: Make number of documents per page depend on size

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3350]
This is a follow-up to https://github.com/rethinkdb/rethinkdb/issues/1540 .

If you have a table with very big documents and query it in the Data Explorer, you
a) lose syntax highlighting in the results (for performance reason)
b) still can get slow performance

According to @neumino 's comment in the other issue, we currently show 40 documents per page in the Data Explorer. I think it would make sense to have the number of documents depend on the size of the documents (e.g. show no more than 40 or 16 KB of data, whichever comes first).

**Comment by danielmewes** [comment]
This would be confusing now that we have #1540. Closing.

**Comment by danielmewes** [comment]
While #1540 points to this issue as a successor, it ended up being addressed directly by https://github.com/rethinkdb/rethinkdb/pull/3910

**Comment by deontologician** [comment]
Even though a page size option was implemented, we could easily pull it out
and implement this issue if this results in a better experience. I don't
know that it is necessarily worth it, but I wanted to point out the option

**Comment by danielmewes** [comment]
I think it's not worth it for now to have two different limits, now that we expose one of them explicitly.
