### ISSUE TITLE
Rename table_config() to table().config()?

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3365]
@larkost suggested renaming `table_config()` and `db_config()` to `config()` (or `configuration()`), and have them become methods on table and database objects respectively.

So `r.db('db').table_config('table')` would become `r.db('db').table('table').config()`
and `r.db_config('db')` would become `r.db('db').config()`.

I like this syntax quite a bit more than the current one to be honest, and find it more intuitive.

There are a few disadvantages:
- You lose the ability to run `table_config('table1', 'table2', ...)` on multiple tables at once (same for `db_config()`)
- You lose the ability to run `r.db('db').table_config()` without arguments on a database. Right now this would return a selection on the configurations of all tables in 'db'.

@coffeemug @mlucy @timmaxw What are your thoughts on this?

(related to https://github.com/rethinkdb/rethinkdb/issues/3315 )

**Comment by timmaxw** [comment]
Merged into `next` in 7cbfc7066908f13c2106b548ba46565cf225df4d.
