### ISSUE TITLE
triggers - attempt 2

### ISSUE THREAD

**Issue by wojons** [rethinkdb/rethinkdb#3367]
I have been thinking that I still do not use change feeds because they do not give me enough promise that the function is going to run for many reasons. after speaking with @timmaxw  for a few minutes there looks like there is an easy way to give users the options for triggers.
- use most of the code that runs for when an index starts
- before the corutine launches check to see if node is primary of the shard o the document
- allow for non determanisc queries
- allow for a timeout if the user wants to allow for a timeout
- #997 allow users to make mistakes. Lots of the issues with dealing with trigger development is making sure the users dont mess up. Let the users mess up and fix the bugs from there. users that are using trigger to update tables will have to be responsible for not ending up in a never ending loop.

**Comment by RubenKelevra** [comment]
Well it's might be nice to combine both features. Something which works like:

When there are changes on X do notify me.

And then, connect and let the database push me changes.

Else let me fetch the pushes at once, without any push.

When reconnecting via push-request to a trigger, you'll receive everything which hasn't been pushed.

This would meet my requirements :)

**Comment by danielmewes** [comment]
@RubenKelevra That sounds like it will be covered by https://github.com/rethinkdb/rethinkdb/issues/3471 eventually. The first implementation will be relatively basic, but in the longer term we are planning to implement changefeeds that you can resume after any kind of disconnect or server failure.

**Comment by RubenKelevra** [comment]
Nice! :+1:

**Comment by thelinuxlich** [comment]
@srh shouldn't this be closed in favor of write hooks?
