### ISSUE TITLE
Servers not re-syncing data

### ISSUE THREAD

**Issue by timjrobinson** [rethinkdb/rethinkdb#3382]
Over the past few days I had a few servers die due to what I think was running out of memory and the process being killed. Since that was all fixed they haven't resynced their data for over 24 hours. My dashboard currently looks like this: (and has been like this for the past 24 hours)

http://i.imgur.com/0CW1DSH.png

Is there anything I can do to fix this up?

**Comment by danielmewes** [comment]
This issue is stale.
We'll do more testing and optimization of backfilling performance as part of our auto-failover implementation.
