### ISSUE TITLE
Consider using no-direct-io by default

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3391]
Our assumption has always been that this is slower because of the added overhead of going through the OS' block cache.
We should re-evaluate this, and actually benchmark whether the overhead is significant.

Here are three arguments in favor of making buffered I/O the default:
- On rotational drives, I get an ~3x improvement in soft-durability write throughput with buffered I/O, since the operating system can apparently combine write operations better than we are currently doing. This is pretty huge (an alternative would be to investigate why we are so inefficient without it, but that's more work).
- There have been bugs in combination with BTRFS and other file systems, that lead to data corruption and other issues when using direct I/O. Using buffered I/O frequently avoided those.
- If the cache size is mis-configured or set smaller than necessary out of reliability concerns, the performance drop becomes less severe if there's the OS' buffer as a fallback.

It seems possible that making buffered I/O the default is going to improve the out-of-the-box experience for a huge majority of our users.
I propose we still provide a `--direct-io` flag to enable direct I/O, so users can enable it in specialized cases where it makes sense (e.g. on high-speed SSDs, possibly).

**Comment by Xrave** [comment]
Just curious - is it better to do direct-io on a SSD with only a small amount of RAM (200MB) or use default no-direct-io?

Thanks.

**Comment by danielmewes** [comment]
@Xrave You can try it out, though I'd probably stick with the default. It's going to give you better utilization of the little available RAM since you probably have to set RethinkDB's own cache size to a really small value to avoid it running out of memory during normal operation.
The efficiency loss from the indirect / buffered i/o also hasn't been very large in our tests.

**Comment by analytik** [comment]
What is the easiest way to test if `--direct-io` works reliably, and makes a difference? It would be nice if there was a simple (python?) script to run. The servers have 64GB RAM, and SSD with ~140k IOPS.

**Comment by danielmewes** [comment]
@analytic To give you a data point, I've not personally seen a single system + workload combination for which `--direct-io` was faster, including some with NVMe storage. There normally isn't much reason to turning it on.

I think a generic testing script wouldn't be much good, because it would likely not reflect the same load pattern that your actual workload will put on the I/o subsystem.
