### ISSUE TITLE
Update interface.log test for ReQL admin.

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3397]
In `reql_admin` our logs test is broken because there is no current method of accessing the logs through http or ReQL. This is slated to be fixed in #2884, and this is a follow-on to that to correct the test.

**Comment by timmaxw** [comment]
When I merged the `rethinkdb.logs` implementation into `next` in 9bb17a21559ec72e3d07c6a8014336644a775c43, I also merged a new version of the `interface.log` test.

**Comment by larkost** [comment]
I merged a corrected version into `next` with 3f8bbd2, after code review with CR 2468.
