### ISSUE TITLE
Update interface.progress and regression.659 tests for ReQL admin

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3398]
With the changes in `req_admin` there is currently no way of tracking progress on shading, backfills, index creation. This is slated to be fixed as part of #3115, and this issue is to track the follow-on work on the tests once enough of the jobs table is completed to make them possible.

**Comment by VeXocide** [comment]
As mentioned in #3115 the `interface.progress` test is merged into `next` via dd756f9 after a CR by @larkost. I'll take care of `regression-659` as well.

**Comment by VeXocide** [comment]
Merged the `regression-659` fix to `next` via 82d1455816a13c524d06fc188e6c00aebd936ddc and `v1.16.x` via 303d9228820006e871d6516250e1e13354bca0aa, over the shoulder by @larkost
