### ISSUE TITLE
Allow chaining of r.object

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3402]
I would love to be able to do this:

```javascript
r.expr(['a', 1, 'b', 2, 'c', 3]).object()
```
There are a lot of times when I've constructed some complicated list of pairs, then I have to go back to the beginning and wrap the entire thing in a `r.object(r.args(`, and find the right place to put the closing braces etc.

**Comment by coffeemug** [comment]
FYI, I think you can do `.coerceTo('object')`. I think `.object()` would be a shortcut for that.

**Comment by coffeemug** [comment]
However, I think it's a bad idea. Generally in ReQL `x.y()` is equivalent to `r.y(x)`. I think it would be a bad idea to break this convention is specific cases. I'd prefer `toArray()`/`toObject()` -- I think it's a better solution.

**Comment by deontologician** [comment]
Yeah, I wasn't aware of `coerce_to('object')` when I wrote this. That solves my use case and I think it's better than adding new functionality or being inconsistent. if no one else has any strong opinions, I'll close this.
