### ISSUE TITLE
Big integer data type

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3407]
We should consider supporting big integers, or maybe infinite precision floats in general at some point.

Related to https://github.com/rethinkdb/rethinkdb/issues/3405
and https://github.com/rethinkdb/rethinkdb/issues/3009

Pretty low priority at the moment, putting into backlog.

**Comment by or-else** [comment]
I think this issue should be mentioned in http://www.rethinkdb.com/limitations/
It's quite common to try to store 64 bit integers in databases in 2015. The fact that RethinkDB does not support 64-bit integers above a certain size seems like a significant limitation of the system worth mentioning.

**Comment by danielmewes** [comment]
@or-else Thanks, I agree. Just opened https://github.com/rethinkdb/docs/issues/859 on our docs issue tracker.

**Comment by danielmewes** [comment]
Merging into https://github.com/rethinkdb/rethinkdb/issues/1639
