### ISSUE TITLE
Spurious "More data is available" in Data Explorer (regression)

### ISSUE THREAD

**Issue by brwnll** [rethinkdb/rethinkdb#3432]
Attempting to use getNearest(), and it's not returning any results, except if I run a different query first, kinda.

Setup: Table that is structured like so (subset)
```json
{
    "name" : "a business location",
    "address" : {
        "location": {
             "$reql_type$":  "GEOMETRY" ,
             "coordinates": [
                 -122.730209 ,
                 48.990702
              ] ,
            "type":  "Point"
        }
     }
}
```
As a test, I attempted to run `getNearest()`, taking the location of one of the businesses directly.
```js 
r.table('locations').getNearest(r.point(-122.730209, 48.990702), { index: 'address.location' })
```

And I get an empty array as a result.

The other oddity is, if I run this in the query explorer, but run a different query first such as 
```js
r.table('locations')
```
_then_ run the previous query, the results show "[]" but _also_ "More data is available. Load the next batch ->".

Clicking that WILL display my 1 returned location which corresponds with the above point.

But if I run the query again, everything is gone, with no "More data" link.

**Comment by AtnNn** [comment]
I was not able to reproduce in `next`. I believe it was fixed but some of the improvements described in #2643.
