### ISSUE TITLE
Improve "80 rows returned , 40 displayed, 40 skipped, more available" message

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#3454]
In the web ui.

**Comment by danielmewes** [comment]
Related to https://github.com/rethinkdb/rethinkdb/issues/3927#issuecomment-83162858

**Comment by danielmewes** [comment]
Updated suggestion combining both issues: "<rows> rows returned in <time>. Displaying rows 41-80, more available"

**Comment by AtnNn** [comment]
Improved the message in 96b59f5
