### ISSUE TITLE
Server stuck in `looking_for_director` state

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#3456]
Reported by @deontologician.

Output of `rethinkdb._debug_table_status` is [here](http://pastebin.com/tyfK6uQA).

For 5/8 hash shards on one of the range shards, all three secondaries failed to find the primary. But the directory dump seems to indicate that the primary is up.

**Comment by danielmewes** [comment]
@timmaxw did you ever get a chance to look into this? Do we have any idea what was going on?

**Comment by deontologician** [comment]
As I don't have the cluster data still, I think it wasn't possible to reproduce. I was shutting down servers and removing them though, so if I had to guess, it might have been fixed by #3627

**Comment by timmaxw** [comment]
No, I don't have any more information about this.

**Comment by danielmewes** [comment]
Let's close it for now then.
