### ISSUE TITLE
We should remove support for older `reql_version_t`s at some point

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3457]
Otherwise we're just going to accumulate cruft indefinitely.

@danielmewes, @coffeemug, do you have an opinion on how often we should do this?

**Comment by danielmewes** [comment]
@Tryneus made another suggestion in https://github.com/rethinkdb/rethinkdb/issues/4148 : 
> I think we should offer 'milestone' releases for well-defined upgrade paths - these should probably coincide with the LTS releases.  Then, it would be very easy to support upgrades from all versions since the previous milestone up until the next milestone.

I think that sounds reasonable, though I'd like to wait until we understand things better and not do this immediately for 2.1.

**Comment by mlucy** [comment]
For what it's worth, there's a lot of very ugly and fragile code to support pre-1.16 secondary indexes that it would be really nice to be able to drop.

**Comment by danielmewes** [comment]
We've done this in 2.1. I think we should just decide this on a case by case basis in the future.

**Comment by danielmewes** [comment]
(Also I might be over-eager in closing this since I'm trying to clean up our issues a bit. Please let me know if anyone things this needs more discussion)
