### ISSUE TITLE
r.http is not passing back cookies sent during digest authentication

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3469]
There has been some back-and-forth in the tests about whether cookies are required during digest authentication. Put simply here is what is happening:

1. `r.http` connects to the server
2. the server responds with a 401 response with the auth-request headers, adding in a cookie header
3. `r.http` follows through on the auth-request properly, but does not send back the cookie from step 2
4. `httpbin` checks for the cookie, and sends back a 401 code.

Part of the lack of clarity has been both that `httpbin` is currently indiscriminate when it checks for cookies that it set, so we have been working around this by always sending cookies (both steps 1 and 3), and so there is some cookie on step 3, making `httpbin` happy. The issue in for `httpbin` is Runscope/httpbin#124

My guess is that we are not specifically turning on `libcurl`'s cookie jar for the session, and so it is not doing this correctly. This might be as easy as just enabling that if we already have the concept of a session, although it might get more complicated if `r.http` sessions can bounce around among the worker processes.

Note that I am keeping the work-around in the tests for the moment.

**Comment by Tryneus** [comment]
This has been fixed and merged into `next` in commits daa6031 (cookies in a single `r.http` session) and 4621c45 (saving and restoring cookies across multiple workers for multiple-request `r.http`).   Review was 2419.  Will be in release 1.16.
