### ISSUE TITLE
Make v8 static-only to allow using the included ICU headers

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3472]
@gchpaco needs to use the ICU library for some work he is doing, but v8 also is using this library and to avoid nasty possible mis-matches we are going to need to match the versions exactly. The easiest route to this is probably to make v8 an always-static resource, so that we always have the source code (headers) of the version of v8 we are using. Otherwise we are going to have to do a lot of complicated detection to figure out what the system version of v8 is linked against, which might not have headers available on the system.

Pinging @AtnNn for comment on this.

**Comment by AtnNn** [comment]
My favourite solution is to build V8 without a bundled ICU. This will allow linking ICU like any other library, It might cause problems if v8 requires specific versions of ICU.

Another less elegant solution, which is what I think you describe, is to use V8's bundled ICU and copy the include files where RethinkDB can find them. This might be a lot easier to do.

Either way, it will make it harder to use a custom `libv8`.

**Comment by danielmewes** [comment]
@gchpaco had some concerns about ending up with two different versions of ICU in our binary.
@AtnNn is this proposal safe in that respect?
> My favourite solution is to build V8 without a bundled ICU. This will allow linking ICU like any other library, It might cause problems if v8 requires specific versions of ICU.

> Either way, it will make it harder to use a custom `libv8`.

Do we know whether that is important for our users?

**Comment by AtnNn** [comment]
Yes, RethinkDB will only ever link to one instance of ICU.

I believe linking to a custom `libv8` is not important.

**Comment by danielmewes** [comment]
I think either of the solutions you propose is ok.
The first indeed feels a lot cleaner, but if you think it's difficult to get it working reliably we should go for the second one of making the V8 ICU includes accessible to RethinkDB code.

**Comment by gchpaco** [comment]
Concur with @danielmewes.  Do we know *why* v8 embeds a specific version?

**Comment by gchpaco** [comment]
https://code.google.com/p/v8-wiki/wiki/I18NSupport appears to indicate it.  They don't seem to require any specific version, so we should be okay.  @AtnNn that should tell you how to do it to boot.

**Comment by AtnNn** [comment]
ICU has been added as an explicit dependency, and V8 no longer builds its own ICU. Implemented in cda0835.

@gchpaco it's all yours now.
