### ISSUE TITLE
Export/import secondary indexes

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#3484]
It would be nice if `rethinkdb export` and `rethinkdb import` had the ability to dump and re-create secondary indexes, instead of making the user re-create their indexes manually.

Is there a reason we decided not to implement this?

**Comment by kofalt** [comment]
+1

**Comment by danielmewes** [comment]
> Is there a reason we decided not to implement this?

The reason was that we didn't have a stable way to represent the index function.

We now provide an interface for getting a binary representation of the function through `index_status(...)['function']`. I'm not sure how many guarantees we can give about its stability across versions.

I think we should extend the format a little such that it contains the ReQL version of the index (if it doesn't already). That way we can detect index functions that are too old and reject them on import.
Once we have that this should be pretty straight-forward.

**Comment by danielmewes** [comment]
(this could be a worthwhile project for 2.0)

**Comment by Tryneus** [comment]
For the record, the binary object you get for `index_status(...)['function']` includes the version of reql that was used to create the index.  We currently ignore that field, but that doesn't mean we need to.

See the definition for `struct sindex_disk_info_t` if you're curious.

**Comment by danielmewes** [comment]
Oh cool, I didn't know that. So we just have to add some sanity check that makes a `indexCreate` fail if the version is too old (I think currently we still support all versions)...

**Comment by internalfx** [comment]
You can clone secondary indexes with external [tools](https://github.com/internalfx/thinker). It currently doesn't write to a file, but maybe I should add that.

I can't really help with building the database, but perhaps the RethinkDB community can further the project by building its own tools for devops. This frees time for the main developers to focus on the core product.

After reading this, I think I will focus on making [thinker](https://github.com/internalfx/thinker) have the ability to dump to a file (with secondary indexes, of course :wink: ).

**Comment by Tryneus** [comment]
Import/export of secondary indexes added to `next` in fe8b35f, ecd5a4c, and  (reviews were 2428 and 2430).  Will be in release 1.16.

For reference:
 * `rethinkdb export` (and thus `rethinkdb dump`) now includes the secondary index information from `index_status` in the `table.info` file.
 * `rethinkdb import` and `rethinkdb restore` will create the indexes for the tables being imported if they are available in the data files, unless `--no-secondary-indexes` is specified.
