### ISSUE TITLE
serve debian key over https

### ISSUE THREAD

**Issue by nairboon** [rethinkdb/rethinkdb#3489]
According to the docs: http://rethinkdb.com/docs/install/debian/ the key for the repo is only available over http and not https thus the chain of trust for the debian packages are broken.

**Comment by danielmewes** [comment]
That's an excellent point @nairboon .

@mglukhovsky Do we have any current plans for getting a certificate and setting up HTTPS for our web server? It sounds to be worth doing.

**Comment by mglukhovsky** [comment]
@danielmewes, it's on the backlog, as we don't have an immediate application for SSL certificates, but it might be worth bumping for this issue.

**Comment by kofalt** [comment]
Pretty easy workaround until that happens; I assert that as of the time of this post the URL http://download.rethinkdb.com/apt/pubkey.gpg contains the content

```text
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.11 (GNU/Linux)

mQENBFCS5MMBCACVLxpeBSXS7/rbfb3vMWHucU2S5dQZ3w2aS8kf31s/Sh0fhvSr
WUGtUDeA1ks8Y1BDFtjT9Ui6uzo1BYT4QsUo3XEkvFD1wg5K6JP6TDpGv6qtak2T
GO9JeZG8xumNIPA67/i1B1jHHdoghieegMBHMxN78HqPFyce5h1MZaEY2uJuhaGx
4ZQZxCCb4njek10iUEG9w1Z1bHpkaz6uJCMqZE9lmkZnUa84soqTfk/b/iflGoNM
uTklDt8ZJ7pr4UoXm/v9DKp3IiRW0/kQZYLWCvmeyTmPqCU8NolmmspgDQMZXvE2
3Vq+ROeNcr1rxNry0KN119BlQ0bz2PFEzJ7ZABEBAAG0LVJldGhpbmtEQiBQYWNr
YWdpbmcgPHBhY2thZ2luZ0ByZXRoaW5rZGIuY29tPokBOAQTAQIAIgUCUJLkwwIb
AwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQp+AO8zqPI5lIUwf/SVCckUIF
YNgR8jPeEXE9RdZHliqllSD+fxMWqk0e5kwIo1P6MJ5A52AAmx5Qe7ifPE7jcX+P
hKEG9vFCk3/TOOYTn7JWMwC+eF+gwB/ueu9cspARi2hIbLPaG0uyrDVznfDbUpbT
cqKTvP7a5Xjyl4LllHMdAb0+jrqJorZwSPo0a3shXGjMKCJXNJYXtIfTjuJglwGH
S19n5O4+lm3TMakvZ+ZhP633muu0cPB2rM+8aiLZKkQfCd1H+HveczDxjx3kIeXc
4cV7yARCwqSAH1HJmvk2zUjd+ihDSwKsBS04TzFza91I8nmVF2OnqKAN0cdrZAif
JMV5hdAKxGgJR7kBDQRQkuTDAQgA8yJRhWpIg6FoeVOejKx1EYbsKELZP/PiIxi1
iP2lyeu5ZWMGMDGNDcYQANpOKPbGMAfNqdJuQuPY0UeD1AllFWo+/pj6mxmfI97l
ioEwxT0FpmRvu59kLaS3xa4ioQ/0RMt+WTSGKDxicjSHCl55NSRfPDi8r5MaFJzs
Mdg0FXUWmGwB41Vk957XavsMCZXzGFz+zUesJZOmi1DodI7Dsgjg7EVwRCMpirxH
GkMcE9TDghC8rGaBETsowUCpYAPkJ3OeDVileNjtGZ3drtWLWG3vfxU0WOlQMvdT
xBu7jTDmDS8seze3pKS6fBM6AM90U5k0zeqEKBvW+AzUdEkGFQARAQABiQEfBBgB
AgAJBQJQkuTDAhsMAAoJEKfgDvM6jyOZWlUH/126sLjFpSJrDR12jIyDIIjXglj0
Z9BYgRQZLPkxISSRswtJzqC0mlFNLDi8Y3tbbgb8p8rgBChW4HNSvIM2qvRj0r8m
icep9xvw+1OwxHpJkdb7BeeR6nsCW4oFSNbqaShdL42l2f9vfRbrcVVnSkDemCPF
/jtM0fALlV5U5nA70aLIYjY21E0LA++UUmI/cDHEeKemeh988DKQ7w9Pj2dJa6CJ
5wk5o++nhdqnJU7m61mFkbIFRd0LEnWBVislW6UnHyo733atS25b33iwOx34r/PP
arkg8eY8sdtL0o/Sx8nIAMVQrwOGGmlTPpF66IVl9Yon/pSHQ3d3tLJbskY=
=kCCH
-----END PGP PUBLIC KEY BLOCK-----
``` 

If your findings do not align, one or more of [ myself, github, an ISP, ... ] are full of lies!

**Comment by d-snp** [comment]
:+1: pretty important point

@kofalt 's workaround is not really a work around as the page recommends executing a snippet that automatically wgets the gpg. A better workaround is to check the gpg into github, and updating the manual to wget the key from there instead.

**Comment by kofalt** [comment]
Yeah, to clarify my implicit proposal was that you download, compare with my paste, THEN continue.
Which requires slightly modifying the installation instructions.

Ya'll should go chuck a few bucks at StartSSL please ;)
Or just wait for... summer-ish, when Mozilla rolls out that free CA!

**Comment by danielmewes** [comment]
A fix for this is in pull request https://github.com/rethinkdb/docs/pull/871

**Comment by danielmewes** [comment]
This was fixed a few months ago.
