### ISSUE TITLE
Remove links to database page, add rename database functionality to tables page

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3491]
The database page is currently a hidden easter egg (there is one link to it), and after reql_admin it's also broken. The only unique functionality from the page was the ability to rename a database. That should be moved elsewhere and the remaining link to the database page should be removed. We may add it back in at a later point if necessary

**Comment by mike-marcacci** [comment]
Hey there, did the rename database functionality make it into 1.16? I can't seem to find it anywhere. (Sorry if I'm just missing, it, which is entirely possible... it is quite late here.)

**Comment by timmaxw** [comment]
In 1.16 you can rename a database through ReQL by writing `r.db("foo").config().update({"name": "bar"})`. I don't think it's possible to rename a database through the web UI.

**Comment by deontologician** [comment]
Ah, sorry no we didn't add it. We're going to make some modifications to the table listing page, so it will show up there. As tim mentioned, you can do it though the system tables for now

**Comment by mike-marcacci** [comment]
Gotcha – I actually just figured that out about an hour ago. I have to say I love having access to the rethinkdb table. Thanks for the clarification!
