### ISSUE TITLE
Issues panel gets collapsed even if it's open when the status bar refetches.

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3492]
This is a jarring annoyance that should be fixed.

**Comment by danielmewes** [comment]
I cannot reproduce this with the current v1.16.x. Could you have fixed this?

**Comment by deontologician** [comment]
To reproduce: 
1. bring down two servers in the cluster
2. wait for "2 issues" to be shown in the issue banner.
3. click "resolve issues" expanding the issue banner
4. bring one of the servers back up
5. the issues banner will close up and disappear.

I think this is because the banner is in an if/else in the templates, rather than being updated though jquery. Ultimately, it'd be nice to just show "all issues resolved" and only make the issues banner disappear once you click "hide issues" again. This will probably also fix #3521

**Comment by danielmewes** [comment]
This appears to be working fine in 2.1.
