### ISSUE TITLE
Add secondary index monitor to dashboard

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3493]
Since consistency monitor was moot (the issue can no longer happen) we're adding a secondary index monitor to take its place in the dashboard.

Per @danielmewes:

Here's a suggestion:
```
  o Indexes
  <n> issues detected
  <n> indexes under construction
```

Or alternatively:
```
  o Indexes
  <n> issues detected
  <N-n>/<N> indexes up to date
```

The second variant is definitely better, but requires running `indexStatus()` on each table to collect the total number of indexes (N) that exist. This could become expensive, but we have to test it.
For the first variant it's sufficient to filter index post construction jobs from the `jobs` table, which should be faster.

**Comment by deontologician** [comment]
@danielmewes @mglukhovsky Should the box be red if indexes are currently building? Also, I'm going to populate "issues" with the number of outdated index issues.

**Comment by danielmewes** [comment]
@deontologician I say yes, it should be red.

**Comment by deontologician** [comment]
![selection_020](https://cloud.githubusercontent.com/assets/1366/5868260/d5e9057a-a25b-11e4-8e76-a7c7df90f5d1.png)

**Comment by danielmewes** [comment]
Looks really good! :+1:

**Comment by mglukhovsky** [comment]
Very pretty!

**Comment by deontologician** [comment]
Fixed by 955170
