### ISSUE TITLE
Get rid of "Please wait" from webui

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3494]
This was added in as part of the reql_admin transition, but it needs to be removed before shipping 1.16. This probably involves maintaining models from the tables -> table page transition. We should also render the page with an empty model and re-render when the data comes in a moment later. This will avoid flasing loading screens etc

**Comment by danielmewes** [comment]
Fixed in next as of https://github.com/rethinkdb/rethinkdb/commit/051c54e7b9bc62cb31f9d5280ee24b6c3e1268c8 , was in CR 2481.
