### ISSUE TITLE
Quick ui fixes for 1.16

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3496]
This issue collects "dust" problems that are a line or two fix, and don't warrant their own issues.

- [x] Remove slideDown animation on secondary index panel
- [x] The "Loading table" headline at the top of the table view should use the Copse font, so it's not too visually distracting.
- [x] `this.progress_bar` being `undefined`, see https://github.com/rethinkdb/rethinkdb/issues/3496#issuecomment-69266506
- [x] Remove checkbox next to reconfigure progress bar
- [x] "Permanently remove server" modal has "remove undefined" on the remove button

**Comment by VeXocide** [comment]
`this.progress_bar` was `undefined` in

```
    SecondaryIndexView.prototype.cancel_delete = function() {
      return this.$('.alert_confirm_delete').slideUp('fast');
    };

    SecondaryIndexView.prototype.remove = function() {
      if (this.progress_bar != null) {
        this.progress_bar.destroy();
      }
      return SecondaryIndexView.__super__.remove.call(this);
    };

    return SecondaryIndexView;
```

**Comment by danielmewes** [comment]
@deontologician Is there anything left here?

**Comment by deontologician** [comment]
Nope, we can re-open if more one-liners come up
