### ISSUE TITLE
Loading fixes for table page

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3497]
Related to #3494, there are numerous "Loading" alert infoboxes in bright yellow that flash when the table page is loading. These should be removed in most cases, and where loading notification is unavoidable, the effect and colors should be less jarring.

- [x] When you first load the table view (clicking the table view from the table list), a yellow popup appears above the shard distribution graph, that says "Loading..." and slides up. This is visually distracting, especially because it's yellow. Could we:
    - [x] just show an empty graph until the shard distribution is loaded (show the axes but no bars)
    - [ ] put the words "Loading..." in the center of the graph, with no colors, just the text
- [x] Choose a more subtle way to show that the secondary indexes and server lists are loading. (similar to the suggestion for the shard distribution graph) -- currently the yellow popups are very distracting.
- [x]  Secondary indexes on table page is always "Loading..." for a table that is unavailable
- [x] Data distribution graph disappears entirely when distribution is unavailable, it should show an error

Some of the checkboxes above are overlapping problems. These were collected from #2878

**Comment by danielmewes** [comment]
Moving the remaining parts of this to 1.16-polish, since they're not blocking the release.
