### ISSUE TITLE
Icon next to table status is always green, even if the table is unavailable

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3500]
We should have the colors match, at least in some way, the text that is next to it

ping @mglukhovsky for ideas

**Comment by mglukhovsky** [comment]
If the table is unavailable, it should be red. Is this currently broken, or a corner case we haven't considered?

**Comment by deontologician** [comment]
I believe, last time I looked at it, the icon is hardcoded and not parameterized in the template. So it's always a green shining broadcast icon

**Comment by mglukhovsky** [comment]
That sounds like a regression. There's a bit of a complex mechanism at work here (it could probably be simpler):

  - There's a helper for returning the status of a table (`humanize_table_readiness`): https://github.com/rethinkdb/rethinkdb/blob/next/admin/static/coffee/util.coffee#L109
  - That helper is used in the Handlebars template, which is re-rendered on a regular basis: https://github.com/rethinkdb/rethinkdb/blob/next/admin/static/handlebars/tables/table-template.handlebars#L10
  - The LESS file has specific classes for the red and green lights: https://github.com/rethinkdb/rethinkdb/blob/next/admin/static/less/styles.less#L1370
  - Here's the view generating the template and passing the current status: https://github.com/rethinkdb/rethinkdb/blob/next/admin/static/coffee/tables/index.coffee#L307

**Comment by danielmewes** [comment]
You mean this icon right?

![table status](https://cloud.githubusercontent.com/assets/505365/5620915/47f55c1a-94e5-11e4-8492-512e484a1b59.png)

This is not a regression but has unfortunately has never worked (as far as I know). The screenshot is from RethinkDB 1.15.2.

We should still fix it of course.

**Comment by mglukhovsky** [comment]
Ah, I thought this referred to the green icon on the table list, not the table view.

That's always been hardcoded, we should definitely fix it.

**Comment by deontologician** [comment]
in CR 2567
