### ISSUE TITLE
Update document ID

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#3502]
Since the only way to guarantee uniqueness is to put all related fields inside the ID, but there are many cases where you want to update these unique values, I think this should be possible somehow

**Comment by danielmewes** [comment]
Hi @thelinuxlich,
the difficulty with that is that it can't (easily) be done atomically. If you shard your table for example, it can happen that the document has to be moved over to a different server by changing the ID. You would basically have to insert a new document on the destination server, and then delete the old document on the source server after the destination servers has acknowledged the write.

Without a distributed commit protocol (such as 2PC), this can easily go wrong. For example if the network connection is interrupted in the middle, both servers might now have a copy of the document. One under the old and one under the new ID.

I suppose this might be acceptable in some scenarios, so it's worth considering.

**Comment by kofalt** [comment]
Oh! So a constraint. Carry on.

**Comment by thelinuxlich** [comment]
Exactly, and since most of my unique values are big, I need to hash them(sha256) into the ID

**Comment by thelinuxlich** [comment]
Now that I noticed the huge performance difference between querying by primary key and by secondary index, this becomes much more valuable for tables with millions of documents.
When modelling a time-series database, you will desire something like [id, created_at] or [id, updated_at], but the date part can change

**Comment by danielmewes** [comment]
Quick question @thelinuxlich :
> Now that I noticed the huge performance difference between querying by primary key and by secondary index

I think that's only the case if there's a `.count()` behind the `between` right? Or could you see the same effect in other queries as well?
`count()` is special because it doesn't require loading the actual document data if the `between` is based on the primary key. We could optimize this for secondary indexes as well. It shouldn't require any deeper architectural change I think.

**Comment by thelinuxlich** [comment]
You're right, I've created a test table with 100k documents now and the difference is negligible when not using count
