### ISSUE TITLE
Web UI regression: server list lost borders + drop shadow

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/rethinkdb#3504]
![screen shot 2015-01-05 at 5 51 39 pm](https://cloud.githubusercontent.com/assets/91193/5623265/59020c2c-9505-11e4-8e67-313cf5f0c924.png)

This looks like a regression after removing datacenters -- we need to add back the borders and drop shadows (as used in the table view).

**Comment by deontologician** [comment]
Needed to add the `section` class to the server list. @mglukhovsky it currently doesn't have a header. Does it need one?

**Comment by deontologician** [comment]
![server listing](https://cloud.githubusercontent.com/assets/1366/5673636/e49bca2a-9753-11e4-830a-277359138a5d.png)

**Comment by mglukhovsky** [comment]
I think it looks great!

**Comment by deontologician** [comment]
Going to also remove the checkboxes since they're useless on the server page currently. We can add them back in if we need functionality later

**Comment by mglukhovsky** [comment]
Makes sense.
