### ISSUE TITLE
List tags in the server list view + server view

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/rethinkdb#3505]
Given that we're moving from datacenters to tags, we should present tags in the UI (read-only for now) -- users who have preconfigured datacenters shouldn't be surprised by seeing their datacenters not listed (in some form).

_Server list view_: show a comma-separated list of tags with ellipses.

_Server view_: show a list of tags and a hint on how to use tags (linking to the documentation).

**Comment by danielmewes** [comment]
Linking to the docs depends on parts of https://github.com/rethinkdb/docs/issues/464

**Comment by deontologician** [comment]
@mglukhovsky list of tags with ellipses, meaning if it's too long?
