### ISSUE TITLE
Allow specifying a custom JSONDecoder class in the python driver

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3506]
[Currently](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/python/rethinkdb/net.py#L61) we just use `json.loads` to deserialize json in the python driver. But it would be nice to allow some way for users to provide a custom [JSONDecoder](https://docs.python.org/2/library/json.html#json.JSONDecoder) subclass that allows customizing the deserialized result.  This would be useful, for example, for ORM writers who would like to instrument the objects coming out of the DB without having to reconvert or wrap them in a second step

**Comment by deontologician** [comment]
I'm leaving open what the api for this should be, since it isn't obvious to me right now what's the best way

**Comment by grandquista** [comment]
I have implemented an `r.json_parser` property that can be reassigned to override all serialization in the Lua driver. It seems like this would be useful to customize in any driver, not just Python.

**Comment by deontologician** [comment]
Having a global like that seems the simplest way, but I think it might be better to specify it at the connection level

**Comment by danielmewes** [comment]
We have to keep in mind though that the driver itself has to understand parts of the decoded JSON. Most importantly it has to be able to check the response type (error, cursor, single document).

**Comment by deontologician** [comment]
That's why I think this should be more of a thing that's possible, vs. something exposed to regular users. ORM creators would be testing that it doesn't break the driver.

**Comment by danielmewes** [comment]
I see, that makes sense. I imagine we could just make it an opt arg to `r.connect`?

**Comment by danielmewes** [comment]
Actually that might be a bad idea because it would expose it a bit too prominantly.

One option might be to make the connection class such that an ORM developer can easily derive their own custom version of it, with some json decoding method overwritten.

**Comment by deontologician** [comment]
that sounds like it might work

**Comment by brianjpetersen** [comment]
@danielmewes

> One option might be to make the connection class such that an ORM developer can easily derive their own custom version of it, with some json decoding method overwritten.

If done thoughtfully, +1.  This would also address #4503.

**Comment by danielmewes** [comment]
This is now possible with https://github.com/rethinkdb/rethinkdb/pull/4585
