### ISSUE TITLE
Web UI: Missing error message on reconfiguration when server is down

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3507]
Saw this on your test server newton:11222. One server in the cluster was down. The reconfiguration modal shows an error "The server returned the following error:", but nothing comes after that.

![server down error](https://cloud.githubusercontent.com/assets/505365/5639228/4fc76d1a-95c7-11e4-80c7-43dae692a015.png)

**Comment by deontologician** [comment]
This is a valid issue on next, but in general I'd not report bugs directly off newton:11222, since I use that for development and it's often broken

**Comment by danielmewes** [comment]
Fix in CR 2513

**Comment by danielmewes** [comment]
Closed in v1.16.x and next https://github.com/rethinkdb/rethinkdb/commit/0986c3de9d7fa472c4fb1586cf32fabbc7e46f59
