### ISSUE TITLE
Add a "work with this table in the data explorer" button to table pages

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3509]
The idea being that it loads the data explorer tab immediately with `r.db(appropriate_db).table(current_table)` so the user can mess with it

**Comment by mglukhovsky** [comment]
:+1:, good idea.

**Comment by danielmewes** [comment]
Sounds good (assuming we can find a good place to put it).

**Comment by danielmewes** [comment]
Adding suggestion from #3856: 
> If I were to make this change myself, I would probably put a button on each table row that shows just on hover. When clicked, it would set the localStorage value current_query to the prefillled in query (just r.db().table()) and then navigate to the data explorer view.

**Comment by srh** [comment]
Fixed by #3857.
