### ISSUE TITLE
Ensuring table and db exists

### ISSUE THREAD

**Issue by YChebotaev** [rethinkdb/rethinkdb#3512]
In my practice, there are often need to be sure about existence needed dbs, tables and indexes.

I think following syntax will be o'k:

```javascript
r.ensureDb('db_name')
```

As equivalent to:

```javascript
r.dbList().contains('db_name').do(r.branch(r.row, r.db('db_name'), r.do(function(){
  return r.dbCreate('db_name').do(function(){
    return r.db('db_name');
  });
}));
```

And ensuring for table exists:

```javascript
var tableOptions = {
  primaryKey:'id',
  durability:'hard'
};
r.db('db_name').ensureTable('table_name', tableOptions);
```

As equivalent to:

```javascript
var table = r.db('db_name').table('table_name');
r.db('db_name').tableList().contains('table_name').do(r.brach(r.row, table, r.do(function(){
  return r.db('db_name').tableCreate('table_name', tableOptions).do(function(){
    return table;
  });
})));
```

And ensuring index existence:

```javascript
var indexOptions = {};
r.db('db_name').table('table_name').ensureIndex('index_name', indexFunction, indexOptions);
```

As equivalent to:

```javascript
var table = r.db('db_name').table('table_name');
table.indexList().contains('index_name').do(r.branch(r.row, table, r.do(function(){
  return table.indexCreate('index_name', indexOptions).do(function(){
    return table;
  }));
})));
```

I think following approach should be implemented at core level, not in drivers, to achieve fast performance in cases where inserts are often occurs in unexistent databases or tables.

**Comment by danielmewes** [comment]
Hi @YChebotaev, thank you for the detailed proposal!

We were already discussing a similar idea in https://github.com/rethinkdb/rethinkdb/issues/2975 .
A big problem with `ensureTable` is that table creation in RethinkDB is not an atomic operation, and as a consequence you can end up with multiple tables of the same name if the term is used on multiple servers in the cluster at the same time.

I'm closing this as a duplicate, but please feel free to comment more about this in https://github.com/rethinkdb/rethinkdb/issues/2975

**Comment by macdja38** [comment]
Just commenting here because this shows up on the first page of google for how to create a table if one does not exist. branch is spelt wrong in the ensuring table exists example.

**Comment by disarticulate** [comment]
Commenting cause this seems like a basic design decision

**Comment by macdja38** [comment]
```js
var table = r.db('db_name').table('table_name');
r.db('db_name').tableList().contains('table_name').do(r.branch(r.row, table, r.do(function(){
  return r.db('db_name').tableCreate('table_name', tableOptions).do(function(){
    return table;
  });
})));
```
Just another warning for those that stumble across this and decide to use it. The above code returns the table, meaning that when you run it the entire table contents are loaded into memory. If you have a multi GB table this will cause node.js to run out of memory...

**Comment by douira** [comment]
I use this to ensure database existence:
```
r
  .dbList()
  .contains(db.databaseName)
  .do(databaseExists =>
    r.branch(databaseExists, { dbs_created: 0 }, r.dbCreate(db.databaseName))
  )
  .run(connection)
```
which doesn't load the whole database into memory as far as I can tell. Does anyone have an idea of how to transfer this approach to tables?

**Comment by srh** [comment]
Use `tableCreate` and handle the error if it already exists.

**Comment by douira** [comment]
I ended up doing a fancy thing that checks what tables are missing and then creates just those combined with the specified primary keys and secondary indexes. Thanks for the info though.

**Comment by wtfp2p** [comment]
NOTES: try-catch for tableCreate is somehow better when dbList is too big

**Comment by cat-dealer** [comment]
When trying to ensure a table exists, the table does exist in most cases; running elaborate queries for a 1/100 issue negatively impacts starting time of the application. The most performant solution I have found so far is to check if the table exists with a lightweight query like r.db("test").tableList().contains("sample") which returns only true/false and execute a second query to create the table in case it is missing.
