### ISSUE TITLE
`./test-runner polyglot/regression/665` looks fragile

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3515]
My reading (and @timmaxw seems to agree) of `./test-runner polyglot/regression/665` is that it is highly dependent on exactly how the sub-shard hashing of keys works, and this is not bound up with that code at all (so might already be an invalid test).

This regression test should probably re-worked as a unit test that mocks the hashing code with something that it can predict/synced with.

This is low priority.

**Comment by gabor-boros** [comment]
I've tried to run the tests more than 100 times and it did not fail so I'm closing this issue.
