### ISSUE TITLE
"<jemalloc>: Error in munmap(): Cannot allocate memory"

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3516]
I have a cluster of four servers based on `next`.
I created 400 tables in the `test` database, and then ran
`r.db('test').reconfigure({shards: 8, replicas: 4})`

Two things happened:
* One of the servers started using a lot of memory. According to `htop`, it used in the range of 20 GB, with >40 GB virtual memory allocated to that process. I think this part is ok, though at some point we might want to look into it (and maybe throttle the query or something).
* The server started printing lots of these messages: `<jemalloc>: Error in munmap(): Cannot allocate memory`. It kept running though and everything still seems to be fine after the reconfiguration has finished.

Three questions:
* What does this message mean exactly?
* If an allocation failed, why is the server not crashing? Is jemalloc internally recovering from it somehow?
* If this is just a sort of warning without any consequences, can we suppress it?

**Comment by danielmewes** [comment]
Upon shutting the server down, I got this:
`error: Failed to shutdown worker process: 'failed to send job function to worker'.  Killing it.`

Seems like the failed allocation did have some effect after all, though I would expect it to show up differently.

**Comment by danielmewes** [comment]
After compiling with TCMalloc instead of Jemalloc for testing, I got this a while after restarting the servers:
```
warn: Received invalid clustering header from (unknown), closing connection -- something might be connecting to the wrong port.
error: Error in src/rpc/connectivity/cluster.cc at line 117:
error: Guarantee failed: [!is_loopback()] Attempted to kill connection to myself.
error: Backtrace:
error: Wed Jan  7 15:38:39 2015
       
       1: backtrace_t::backtrace_t() at backtrace.cc:203
       2: lazy_backtrace_formatter_t::lazy_backtrace_formatter_t() at basic_string.h:269
       3: format_backtrace(bool) at backtrace.cc:197
       4: report_fatal_error(char const*, int, char const*, ...) at basic_string.h:287
       5: connectivity_cluster_t::connection_t::kill_connection() at cluster.cc:117
       6: mailbox_manager_t::mailbox_read_coroutine(connectivity_cluster_t::connection_t*, auto_drainer_t::lock_t, threadnum_t, unsigned long, std::vector<char, std::allocator<char> >*, long, mailbox_manager_t::force_yield_t) at mailbox.cc:286
       7: ./rethinkdb() [0x75d748] at 0x75d748 ()
       8: coro_t::run() at coroutines.cc:206
error: Exiting.
```

In my experience this guarantee gets triggered if the server sends itself a (local) cluster message that fails to deserialize.

**Comment by danielmewes** [comment]
I think the guarantee failure is unrelated. Will move it to a separate issue.

**Comment by danielmewes** [comment]
I can only reproduce this with the jemalloc installed on newton (version 2.2.5).
If I configure with `--fetch jemalloc` it disappears. We seem to be fetching version 3.6.0.

**Comment by danielmewes** [comment]
I think the problem is that Linux has a limit on the number of contiguous mmapped areas (or something like that). Jemalloc prior to version 3.0.0 appears to use `munmap` to return pages to the OS, which fragments the mapped memory space into a lot of discontiguous areas.

I was able to avoid the issue on newton by setting `echo 131060 > /proc/sys/vm/max_map_count` (the default is 65530).

The Jemalloc developers have disabled the use of `munmap` on Linux by default starting with Jemalloc 3.0.0 (https://github.com/jemalloc/jemalloc/commit/59ae2766af88bad07ac721c4ee427b171e897bcb). Even if I explicitly enable `munmap` use at Jemalloc compile time, I'm not getting the error with Jemalloc 3.6.0 anymore though, so there must have been some additional changes as well.

The reason we don't get a crash from this is that the error happens in `free()` rather than during an allocation.

Generally this appears to be a problem with Jemalloc and not in RethinkDB.
We should avoid linking with old versions of Jemalloc for our official packages though. @AtnNn can we do that?

**Comment by AtnNn** [comment]
I have opened #3541

**Comment by danielmewes** [comment]
Ok let's close this one then, thanks @AtnNn .
