### ISSUE TITLE
clean `test/old_regression`

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3517]
We should go through `test/old_regression` and see if there are any tests there worth updating, and remove the rest.

**Comment by larkost** [comment]
I looked through this folder and there is nothing worth saving at this point. Here are my notes:

- gc_verification.py - specific to an older serializer, was a performance characterization tool
- issue_133.py - memcache protocol, looks like a specific bug
- issue_153.py - specific to memcache protocol
- issue_197.py - just used `stress`, we do that
- issue_283.py - open and closes 100 connections
- issue_327.py - specific to memcache protocol
- issue_69.py - specific to memcache protocol, was sending 1024 as a "large=" value
- issue_90.py specific to memcache protocol, looksed at values with \r\n
- issue_95.py specicic to memcache protocol, noreply test

@danielmewes any objection to me deleting all of these files?

**Comment by danielmewes** [comment]
I think these can all go.

**Comment by larkost** [comment]
I am going to take that as an ersatz over-the-shoulder and have wiped them in f4d52bf8.

**Comment by danielmewes** [comment]
:+1:
