### ISSUE TITLE
A restarted primary replica gets stuck in the `backfilling_data` state

### ISSUE THREAD

**Issue by Tryneus** [rethinkdb/rethinkdb#3520]
Scenario:

* Start a cluster with two nodes
* Create a table with `replicas=2`
* Shut down both nodes
* Restart the node hosting the primary replica of the table

The restarted node should be able to serve outdated reads.  Instead, it is stuck in the `backfilling_data` state indefinitely and outdated reads are rejected with `Cannot perform read: No direct reader available`.

**Comment by timmaxw** [comment]
The solution is to split the `primary_when_safe_t` reactor state into `primary_waiting_for_peers_t` and `primary_backfilling_t`. In the former state, we would serve outdated reads.

**Comment by danielmewes** [comment]
Assuming that this is because of how the reactors work, it sounds like this has already been a problem in 1.15?
Moving to polish then.

**Comment by timmaxw** [comment]
Yes, this is a `reactor_t` issue, and it's probably been around since 1.2.

**Comment by danielmewes** [comment]
This was rewritten.
