### ISSUE TITLE
"Resolve Issues" button state incorrect in some cases

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3521]
Steps to repeat:

1. Cause an issue (take a server down)
2. Click "Resolve issues" button in the issue banner that pops up in red at the top
3. Resolve the issue (bring the server back up)
4. The issue banner will disappear as expected
5. Cause another issue

The button text will still be "Hide issues" rather than "Resolve issues" as expected.

@danielmewes polish?

**Comment by danielmewes** [comment]
Yeah wouldn't hold the release for this.

What is the incorrectly labelled "Hide issues" button doing if you click it?

**Comment by deontologician** [comment]
It switches to the "resolve issues" button. the second time you click it will be back to normal

**Comment by deontologician** [comment]
Fix is up in CR 2976
