### ISSUE TITLE
difference between get_intersecting() and get_nearest()

### ISSUE THREAD

**Issue by nviennot** [rethinkdb/rethinkdb#3526]
What's the differences between `get_intersecting(r.circle(point, radius))` and `get_nearest(point, :max_dist => radius)` ?

I see two:
* get_nearest() needs a `max_results` argument (which seems fairly artificial), while get_intersecting does not.
* get_nearest() returns a computed distance, while get_intersecting does not.

Is that it? I feel like I'm missing something.

**Comment by danielmewes** [comment]
Hi @nviennot,
these two queries are indeed very similar.
One more thing that `get_nearest()` does in this case is that it sorts the result by increasing distance from `point` in an efficient way.

They key use case for `get_nearest()` is a different one from what your example does though: Getting a certain number of nearest neighbors around a point, without knowing their maximal distance.
If you are interested in all points within a certain radius, `get_intersecting` indeed does the job and is usually even faster than `get_nearest()`.
However if you are interested in the k nearest neighbors, `get_nearest` with the `max_results` option is always efficient, while for `get_intersecting` you will have to traverse a radius that is often much bigger than necessary.

**Comment by nviennot** [comment]
thx @danielmewes
