### ISSUE TITLE
Server page fails to load sometimes if the server is down

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3530]
Reported by @VeXocide:

Bring a server down, click on the server in the server listing page. The page will fail to lose and will give an exception along the lines of `$(...).get() cannot be undefined`

The extracted stack trace
```
.datetime@http://newton:8408/js/jquery.timeago.js?v=1.15.2-1618-g5facb1-dirty:99:20
$.timeago@http://newton:8408/js/jquery.timeago.js?v=1.15.2-1618-g5facb1-dirty:23:22
this.Profile</Profile.prototype.render@http://newton:8408/cluster-min.js?v=1.15.2-1618-g5facb1-dirty:4310:21
__bind/<@http://newton:8408/cluster-min.js?v=1.15.2-1618-g5facb1-dirty:12890:58
this.ServerMainView</ServerMainView.prototype.render@http://newton:8408/cluster-min.js?v=1.15.2-1618-g5facb1-dirty:4235:31
__bind/<@http://newton:8408/cluster-min.js?v=1.15.2-1618-g5facb1-dirty:12890:58
this.ServerContainer</ServerContainer.prototype.render@http://newton:8408/cluster-min.js?v=1.15.2-1618-g5facb1-dirty:4143:25
__bind/<@http://newton:8408/cluster-min.js?v=1.15.2-1618-g5facb1-dirty:12890:58
this.ServerContainer</ServerContainer.prototype.fetch_server/this.timer</<@http://newton:8408/cluster-min.js?v=1.15.2-1618-g5facb1-dirty:4120:24
this.Driver</Driver.prototype.run/</</</fn/<@http://newton:8408/cluster-min.js?v=1.15.2-1618-g5facb1-dirty:13030:25
tryCatch2@http://newton:8408/js/rethinkdb.js?v=1.15.2-1618-g5facb1-dirty:11178:18
Promise$_successAdapter@http://newton:8408/js/rethinkdb.js?v=1.15.2-1618-g5facb1-dirty:7930:11
tryCatch1@http://newton:8408/js/rethinkdb.js?v=1.15.2-1618-g5facb1-dirty:11170:18
Promise$_callHandler@http://newton:8408/js/rethinkdb.js?v=1.15.2-1618-g5facb1-dirty:8725:13
Promise$_settlePromiseFromHandler@http://newton:8408/js/rethinkdb.js?v=1.15.2-1618-g5facb1-dirty:8739:13
Promise$_settlePromiseAt@http://newton:8408/js/rethinkdb.js?v=1.15.2-1618-g5facb1-dirty:8902:9
Promise$_settlePromises@http://newton:8408/js/rethinkdb.js?v=1.15.2-1618-g5facb1-dirty:9045:9
Async$_consumeFunctionBuffer@http://newton:8408/js/rethinkdb.js?v=1.15.2-1618-g5facb1-dirty:6311:9
Async$consumeFunctionBuffer@http://newton:8408/js/rethinkdb.js?v=1.15.2-1618-g5facb1-dirty:6274:9
Promise$_Scheduler@http://newton:8408/js/rethinkdb.js?v=1.15.2-1618-g5facb1-dirty:10375:17
```

Issue seems to be in `this.ServerContainer>ServerContainer.prototype.fetch_server>this.timer`

**Comment by deontologician** [comment]
This was on `next`, it may have been fixed already in my local branch as I wasn't able to reproduce it (though that would be strange)

**Comment by VeXocide** [comment]
This can be reproduced as follows:

1. Create a cluster of two instances, `X` and `Y`
2. Shut down both instances
3. Bring instances `X` back up
4. Visit `/#servers` and click on the disconnected instance

Contrary to starting with two instances and bringing one down, this way the other instance doesn't have any outdated information stored.

**Comment by deontologician** [comment]
@timmaxw is this reasonable behavior for there to be a difference between X not having seen Y since X came up, and X losing contact with Y while X is up the entire time?

**Comment by deontologician** [comment]
At the very least, this means I need to split the `.info()` calls into a separate query from the main query, like I did on the table page.

**Comment by danielmewes** [comment]
Fixed in next https://github.com/rethinkdb/rethinkdb/commit/e2561a86eb30ea68cff1b6053271c33b674720ad . We now show the "last seen" duration if a server is disconnected, and show "unkown time ago" as its value if the server has never been seen. Was in CR 2475.
