### ISSUE TITLE
Thinker watermark image

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3534]
Add the thinker watermark image.

Currently looks like:

![thinker_watermark_1](https://cloud.githubusercontent.com/assets/1366/5673811/148df602-9756-11e4-9fe5-2eb3152e7ef5.png)

Once the position and opacity are decided, I'll bake it into a final image and remove the ability to position him dynamically

**Comment by VeXocide** [comment]
:+1:

**Comment by mglukhovsky** [comment]
Awesome, looks great. :clap:
