### ISSUE TITLE
ParseError in admin/static/less/_ionicons-icons.less

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3539]
On my PC with Ubuntu 12.04 using lessc 1.3.1 I'm getting
```
[25/621] LESSC build/web_assets/cluster.css
ParseError: Syntax Error on line 739 in /home/daniel/rethinkdb/admin/static/less/_ionicons-icons.less:739:2
738 {
739   &:extend(.ion);
740 }
```

**Comment by danielmewes** [comment]
Using `./configure --fetch lessc` so it uses less 1.6.2 avoids the issue.

Looks like we might have to bump up the required version?

**Comment by AtnNn** [comment]
@deontologician, @mglukhovsky:
 
* Do you know what version of lessc introduced whatever feature is causing lessc 1.3.1 to fail? We could update the lower bound.
* Have you tried to build RethinkDB with a more recent version of lessc? We could update the higher bound.

**Comment by danielmewes** [comment]
Cannot reproduce this anymore.
