### ISSUE TITLE
Bump Curl version to 7.40.0

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3540]
When fetching libcurl while building we currently fetch 7.36.0.
We need to use Curl 7.40.0 because of (at least) http://curl.haxx.se/docs/adv_20150108A.html .

Since we could never reproduce the issue in our officially built OS X packages, I don't think we need another 1.15 point release for this. I still suggest merging this into 1.15.x for users who want to build that branch from source.

**Comment by AtnNn** [comment]
Bumped in 6d13fa5

Follow up issue #3685
