### ISSUE TITLE
Build failed: Cannot find module 'deep-equal'

### ISSUE THREAD

**Issue by kofalt** [rethinkdb/rethinkdb#3544]
On rethink release `v1.15.0`, commit 4d2fd72, on Ubuntu 14.04 x64, the `BROWSERIFY build/drivers/javascript/rethinkdb.js` step fails with `Cannot find module 'deep-equal'`.

This is potentially part of a pattern of bit-rot that I've seen before (such as #3109) when trying to reproduce non-latest binaries, which might warrant a meta-ticket about being able to reliably build non-latest server versions.

Alternatively, additional `./configure` flag advise welcome. I'm more concerned about reliably building than I am about using system libraries, so it might be a good idea in my case to switch from `./configure --allow-fetch` to `./configure --allow-fetch --fetch all`. The downside being that implies a lot more redundancy (building node, etc) which would be unfortunate.

Relevant build log except:

```
HEAD is now at 4d2fd72... Bump driver version numbers to 1.15.0.0

$ ./configure --allow-fetch
* Detecting system configuration
Bash:                           4.3.11(1)-release
Use ccache:                     no
C++ Compiler:                   GCC 4.8.2 (/usr/bin/c++)
Host System:                    x86_64-linux-gnu
Build System:                   Linux 3.13.0-24-generic x86_64
Cross-compiling:                no
Host Operating System:          Linux
Without tcmalloc:               no
Build Architecture:             x86_64
C++11:                          ok
Precompiled web assets:         no
Protobuf compiler:              /usr/bin/protoc
python:                         python 2.7.6
Node.js package manager:        /usr/bin/npm
LESS css:                       external/less_1.6.2
CoffeeScript:                   external/coffee-script_1.7.1
Handlebars:                     external/handlebars_1.3.0
Browserify:                     external/browserify_3.24.13
bluebird:                       external/bluebird_1.2.1
wget:                           /usr/bin/wget
curl:                           /usr/bin/curl
Google Test:                    external/gtest_1.6.0
termcap:                        -ltermcap
boost_system:                   -lboost_system
ssl:                            -lssl
protobuf:                       -lprotobuf
v8:                             -lv8
RE2:                            external/re2_20140111
z:                              -lz
crypto:                         -lcrypto
curl:                           -lcurl
Use pre-3.19 v8 API:            yes
tcmalloc_minimal (static):      /usr/lib/libtcmalloc_minimal.a
Test protobuf:                  ok
Test boost:                     ok
Installation prefix:            /usr/local
Configuration prefix:           /usr/local/etc
Runtime data prefix:            /usr/local/var
* Wrote configuration to config.mk

$ time nice make -j 8
...

    [374/377] LD build/release/rethinkdb
    [375/377] LESSC build/release/rethinkdb_web_assets/cluster.css
    [376/377] BROWSERIFY build/drivers/javascript/rethinkdb.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'deep-equal'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (..../build/external/browserify_3.24.13/node_modules/packed-browserify/node_modules/browserify/index.js:7:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
make[1]: *** [build/drivers/javascript/rethinkdb.js] Error 8
make: *** [make] Error 2
```

This problem does not occur on tag `v1.15.3-1` commit 37e491c7a9.

**Comment by danielmewes** [comment]
Hi @kofalt, thank you for the issue report.

So does the build work when you're using `./configure --allow-fetch --fetch all`?

We generally don't maintain old point releases in this way.
1.15.3 is already a conservative bugfix-only update to 1.15.0, so it wouldn't make much sense to have a second updated 1.15.0-updated as well.
Is there a special reason for why you need to build 1.15.0 rather than 1.15.3?

**Comment by kofalt** [comment]
The reason we're doing this is we operate with managed updates - an entire environment (dev, prod, etc) will always use the same byte-identical source of truth until we explicitly make the choice to upgrade. This precludes "whatever is on someone else's HTTP server today" methods like apt-get.

In practice, this has meant just building on each machine we use, which is the only reason I found out about this problem. I have been considering just hosting alternate tarball downloads, which would be a "cool to have" for the main site. On the other hand, RDB builds fast enough to not really mind.

If the current policy is to support the latest bugfix release (such as `1.14.x`, `1.15.x`), we shouldn't have any problems bumping the version to follow along. We just haven't happened to need an infrastructure upgrade in the last few months.

I'll likely close this ticket tomorrow, pending internal discussion about changing our update policy.

**Comment by AtnNn** [comment]
@kofalt: You may want to use the tarballs in http://download.rethinkdb.com/dist/ instead of git sources. They contain pre-compiled platform-independent assets and pre-fetched dependencies. They should allow you to have more reproducible builds.

**Comment by kofalt** [comment]
I was not aware of that until now! 

![iron man jericho](https://cloud.githubusercontent.com/assets/265071/5715514/a57ec85c-9a9f-11e4-9187-569e84dad202.gif)

I'll report back when I've adapted our solution to use those instead.

**Comment by mglukhovsky** [comment]
@danielmewes: I think we should promote that URL more prominently on the install pages. :smile:

**Comment by kofalt** [comment]
Agreed. When I went to go check how blind I was, the link is mainly talking about older versions (and does not talk specifically about the dist tarball folder).

Maybe linking to that on the 'building from source' pages would be useful.

**Comment by kofalt** [comment]
Specifically mentioning

> They contain pre-compiled platform-independent assets and pre-fetched dependencies.

As that's excessively relevant.

**Comment by mglukhovsky** [comment]
Agreed, opened rethinkdb/docs#619 to do this.

**Comment by danielmewes** [comment]
@kofalt any update on this? Can we close the issue?

**Comment by kofalt** [comment]
I think so. I just switched my script over to using the distribution tarball.

I will follow rethinkdb/docs#325 for instructions on which dependant packages no longer need to be installed (presumably node, among others).

**Comment by PrajapatiAnkit** [comment]
sdfghjkl
