### ISSUE TITLE
Refactor job_report_t

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3545]
@VeXocide said it would be good to split the `job_report_t` data structure up into individual types for the different job types.

Just opening an issue so it's easier to keep track of things.

**Comment by VeXocide** [comment]
In CR 2571 by @timmaxw.

**Comment by VeXocide** [comment]
Merged into `next` via commit 4dac90218ef72f25922b7e2183577c6b945be0c7.
