### ISSUE TITLE
r/rethinkdb sidebar version out of date

### ISSUE THREAD

**Issue by chrisvariety** [rethinkdb/rethinkdb#3559]
https://www.reddit.com/r/rethinkdb/

Just noticed it says "Latest RethinkDB version: 1.13.1" in the sidebar, thought y'all might want to know.

Looks like @AtnNn is the mod over there.

**Comment by danielmewes** [comment]
Good catch, thanks @chrisvariety !

**Comment by danielmewes** [comment]
Looks like @AtnNn or achille has updated it.
