### ISSUE TITLE
Add backward compatibility for #3550

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3561]
In https://github.com/rethinkdb/rethinkdb/issues/3550 we changed the format for sindex key serialization.  We probably need to add code to correctly handle old keys as well, even though we're going to require people to migrate.

A list of things off the top of my head:
* [ ] Check that range operations on sindexes are still correct (they might be correct without any changes because of the way we changed the serialization, or they might require branching based on the ReQL version).
* [ ] Make sure that functions which parse the primary key out of the secondary key branch based on the ReQL version.
* [ ] Make sure that we use the old serialization when writing a key to an outdated index.

**Comment by mlucy** [comment]
Been working on this.  It's actually something of a pain in the ass because we seem to generate sindex keyranges on the machine hosting the query, where we don't have any information on the sindex's ReQL version.  I think we have to change what we send over the wire for this to actually work.

Alternatively, how attached are we to letting people use their old sindexes when they upgrade to 1.16?  Would it be possible to just force them to update the sindexes before they can use them?  (@danielmewes)

**Comment by danielmewes** [comment]
Arr that's annoying. Let's talk about it later today.

**Comment by mlucy** [comment]
This is CR 3561, but there's at least one bug in it still, and more testing to do.

**Comment by mlucy** [comment]
In next and 1.16.x.

**Comment by AtnNn** [comment]
> but there's at least one bug in it still

@mlucy Was the bug been fixed?

**Comment by mlucy** [comment]
Yes, the bug (and several others) was fixed during testing.
