### ISSUE TITLE
Error reporting of missing functions in the Data Explorer

### ISSUE THREAD

**Issue by VeXocide** [rethinkdb/rethinkdb#3566]
Current in the Data Explorer `r.db("rethinkdb").table("jobs").filter({"type": "index_construction"}).coerce_to("ARRAY")` leads to an error `TypeError: undefined is not a function` which is uninformative, and should be improved if JavaScript allows it. Note that `coerceTo` should've been used here instead of `coerce_to`.

**Comment by deontologician** [comment]
Might be able to give a slight remedy (at least on driver objects) by using ES6 proxies: https://github.com/lukehoban/es6features#proxies

**Comment by deontologician** [comment]
I haven't looked at the dataexplorer code too in depth. It's possible the exception being thrown has more info we could show in the error message. pinging @AtnNn who's looked at that code more recently

**Comment by AtnNn** [comment]
It's the exception raised by JavaScript's eval. On Firefox 31, the error is a little more useful:

```
TypeError: r.db(...).table(...).filter(...).coerce_to is not a function
```

The exception may have a stack trace that we could sanitize and print.

**Comment by deontologician** [comment]
Recently, this was fixed in Chrome: https://plus.google.com/+AddyOsmani/posts/DdWkiKsvbA2

Since this would be a significant workaround that is fixed by the browser vendors, I'm closing this @danielmewes @VeXocide let me know if you think differently

**Comment by danielmewes** [comment]
Sounds good enough.

**Comment by VeXocide** [comment]
Works for me.
