### ISSUE TITLE
Test what happens if a point changefeed with squash disabled gets backed up by more than 100k elements

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3570]

**Comment by mlucy** [comment]
It looks like we insert a document `{'error': "..."}` into the stream, which is bad because it's indistinguishable from a document in a table with primary key "error" being updated accordingly.

**Comment by danielmewes** [comment]
What should we return in that case? Can we return an error?

**Comment by mlucy** [comment]
We could error and abort the feed, we could ignore it and silently squash, we could decline to support non-squashing point changefeeds, or we could change the format like we're talking about in #3564.

**Comment by mlucy** [comment]
This will fix itself as part of #3564, since the error object will now make sense.
