### ISSUE TITLE
What changefeeds should squash by default?

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3578]
Currently all changefeeds (even point and limit changefeeds) have `squash: false` as the default.  We could change some or all of these to `squash: true` or `squash: 0.1` (or something) before release.  I think we should put a little bit of thought into this because changing feeds from non-squashing to squashing in a future release might break someone's app.

@coffeemug, I remember you had opinions on this, but I don't remember what they were.

Personally I think `squash: true` or `squash: 0.1` should be the default for all changefeeds and people should have to ask for non-squashing behavior.

**Comment by timmaxw** [comment]
I agree that the default should not be `squash: false`. I suspect we'll want to forbid `squash: false` entirely for some types of changefeeds; for example, system table changefeeds always do at least some squashing, even though they ignore the `squash` optarg. There might be other types of changefeeds in the future for which it's impractical to never squash.

**Comment by danielmewes** [comment]
`squash: true` by default sounds fine to me.

**Comment by danielmewes** [comment]
(we just have to mention the change in the release notes)

**Comment by mlucy** [comment]
I think we should seriously consider `squash: .1` or `squash: .05`.  It won't hurt latency much in 99% of cases, but it will drastically reduce network traffic in the case where the client is processing faster than the server, the server is producing a lot of changes, and there's negligible network latency.

**Comment by mlucy** [comment]
But no strong objections to `squash: true` on my part.

**Comment by danielmewes** [comment]
I'd prefer `true` so we don't have to pick an arbitrary value :)

**Comment by mlucy** [comment]
Alright, since we're up against the deadline let's just default to `true`.

**Comment by mlucy** [comment]
This is fixed in `mlucy_cfeed_changes`, CR OTS by @danielmewes.

**Comment by coffeemug** [comment]
I'm late to the party, but :+1: on `squash: true` by default.
