### ISSUE TITLE
Pluck (maybe other things) ignored with artificial tables + changefeeds

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3584]
Currently

```
r.db('rethinkdb').table('jobs').pluck('id').changes()
```
completely ignores the pluck, I get the full result as if the pluck were not there.
It looks like this also happens with `.getField` and `.merge`

**Comment by coffeemug** [comment]
Just independently ran into this. Can confirm it's very annoying :)

**Comment by coffeemug** [comment]
So, actually, the issue I ran into is this:

```js
r.db('rethinkdb').table('jobs')('new_val').changes()
```

In this case the feed returns all the values (i.e. `new_val` and `old_val`), but it isn't immediately clear what should happen here. Do we treat these fields as something that exists before the `.changes()` command is introduced? (that feels wrong to me, but is one possible option) If we don't treat them as existing before `.changes()`, what should we return to the user? An empty feed?

/cc @mlucy

**Comment by danielmewes** [comment]
@coffeemug I think your query should never generate any changes.

**Comment by mlucy** [comment]
The current behavior is that `r.table('test').map(func).changes()` is identical to `r.table('test').changes().map{|row| row.keys.map{|key| [key, func(row[key])]}.coerce_to('object')}`.  That would be hard to change before the release.

**Comment by danielmewes** [comment]
@mlucy that doesn't seem right. If the result of the map doesn't change, I'm not getting an update on the changefeed. So the map is indeed processed before generating the change event.

**Comment by danielmewes** [comment]
(@mlucy: If you're reading via email: I've edited my response)

**Comment by mlucy** [comment]
Ah, yeah.  The deduplication and "don't send trivial changes" logic applies as normal (I think).  So "identical" was a bad way to put it.  I just meant that we apply the map to both `new_val` and `old_val`, so `r.db('rethinkdb').table('jobs')('new_val').changes()` doesn't do what Slava seemed to be expecting.

**Comment by mlucy** [comment]
This is in CR 2510 by @danielmewes .

**Comment by mlucy** [comment]
This is in next and v1.16.x.
