### ISSUE TITLE
Double-check that artificial table changefeeds never generate trivial changefeeds

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3585]
There are asserts to the effect that we never send `{old_val: x, new_val: x}` changes to the client (except for initial values prior to https://github.com/rethinkdb/rethinkdb/issues/3443, but even those are going away now).  I just realized that I never actually checked with @timmaxw that there aren't situations where artificial tables will generate these and thus trip a guarantee.

**Comment by timmaxw** [comment]
I just reviewed the artificial table changefeed logic and confirmed that it should never call `ql::changefeed::artificial_t::send_all()` with a change where `change.old_val == change.new_val`. If it does, there's a bug, and tripping a guarantee is appropriate. Do you think that's adequate, or do you have an idea for how to write a test for this?

**Comment by mlucy** [comment]
Good enough for me.
