### ISSUE TITLE
[next][web ui]Error header does not appear

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#3588]
Following https://github.com/rethinkdb/rethinkdb/issues/3586, I didn't see a red header with an issue.
I had to open a new web interface to see the red header (with the error "Server disconnected").

**Comment by danielmewes** [comment]
Thanks for reporting.
I've definitely seen this working before, but either we broke it gets stuck under some conditions or something.

**Comment by danielmewes** [comment]
Just tested and it worked fine for me, so the failure seems to be intermittent.

**Comment by danielmewes** [comment]
Maybe a consequence of https://github.com/rethinkdb/rethinkdb/issues/3593

**Comment by danielmewes** [comment]
Closed #3593 , so we have to see if this happens again.

**Comment by deontologician** [comment]
@neumino have you seen this again with the released version of 1.16?

**Comment by neumino** [comment]
@deontologician -- nop, it just happened once for me.

**Comment by deontologician** [comment]
OK cool, closing for now then
