### ISSUE TITLE
Webui should attempt to reconnect if an http connection is closed

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3593]
Currently, there are several ways the ui can stop updating because the webui doesn't try to automatically reobtain a connection when the connection is closed.

This will (among other things) remove the need to refresh the page if the server you're connected to goes down and comes back up

**Comment by danielmewes** [comment]
It looks like the error message that the driver generates has changed and we do string comparison on the message. Going to fix this for now, but that's another good reason for getting https://github.com/rethinkdb/rethinkdb/pull/2103 in.

**Comment by danielmewes** [comment]
Fix in CR 2499

**Comment by danielmewes** [comment]
Fixed in next https://github.com/rethinkdb/rethinkdb/commit/33e0f2d62fa5ececb7b2c62a951b43234e15f534
