### ISSUE TITLE
Inconsistent table availability in `next`

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3595]
I am seeing occasional table availability problems in `next` while running `./test-runner`. The problem has been showing up in every run of the entire suite (of 343 tests), but is hopping around on every run, so affects a handful of them with every test. It is a little hard to describe because it shows up a little differently every time, so I will give a few examples:

Example 1:
```python
r.db('test').table_create('test').run(conn)
r.db('test').table('test').wait().run(conn)
# RqlRuntimeError(u'Table `test.test` does not exist.')
```

Example 2:
```python
# previous test drops table test.t665

# test harness
r.db('test').table_list().for_each(lambda tableName: r.db('test').table_drop(tableName)).run(conn)

# new test using same server
r.db('test').tableCreate('t665').run(conn)
# RqlRuntimeError(u'Table `test.t665` already exists.')
```

Example 3:
```python
r.db('test').table_create('t665').run(conn)
r.db('test').table('t665').insert([{'id':1}, {'id':4}]).run(conn)
# RqlRuntimeError(u'Table `test.t665` does not exist.')
```

I have cleaned up the examples a little, but mostly this is copy-paste from what the tests are doing. I have also only been running these tests locally. There have also been a number of other versions of the error, but these are three that were in one run.

**Comment by danielmewes** [comment]
FYI: I've been running this small test case for ~1000 cycles so far and haven't gotten any errors
```php
while (true) {
        r\tableCreate('t0')->run($conn);
        r\table('t0')->wait()->run($conn);
        r\tableDrop('t0')->run($conn);
}
```

I'll keep it running for somewhat longer to see if anything eventually happens.
If not, we should double-check that we didn't somehow had two tests running against the same server at the same time.
Alternatively, there might be something crucial to reproducing the bug which I'm not replicating in my minimal test.

@larkost also mentioned to me that this was working until at least about a week ago, so we could theoretically try bisecting git history (though it might take a while).

**Comment by mlucy** [comment]
I seem to encounter these errors in `test-runner` only when I run with `-j12`.  Is it possible it's related to the fact that the test suite was recently parallelized?

**Comment by danielmewes** [comment]
(Still no errors after 62,400 cycles in my test.)

**Comment by larkost** [comment]
The problem turned out to be in `test-runner` specifically in the line:

```python
self.envVariables = copy.copy(os.environ)
```

That looks like it does the right thing, but `os.environ` is actually an interface, so what it is actually copying is the function pointer. So there was a space between that and when it was used by `subprocess.Popen` (some 10 lines later) that the multiple threads could interrupt each other and get the wrong env variables. including the server connection information.

This caused one test to get a connection to the server of another, and from there anything was possible. The fix was simple:

```python
self.envVariables = os.environ.copy()
```

This was review in CR 2496, from branch `larkost/3595-inconsitent-table-availability`, and went into `next` with 031c172.
