### ISSUE TITLE
Creation and deletion of tables slows down over time

### ISSUE THREAD

**Issue by christopherhesse** [rethinkdb/rethinkdb#360]
This seems unlikely to occur in practice, but I noticed it slowing down my tests.  Running rethinkdb 1.3.2-fallback (CLANG 4.1 ((tags/Apple/clang-421.11.65))) on Mac OS X, when you create and delete tables over and over, the creation/deletion queries slow down over time.  Non-meta queries appear to be unaffected.

I mentioned this to Joe D, and while he thinks it is an unlikely thing for a customer to run across, it may still be an issue worth tracking.

Here's a script to reproduce it:

    import time

    import rethinkdb as r

    r.connect()

    i = 0
    while True:
        start_time = time.time()
        r.db("test").table_create("example").run()
        r.db("test").table_drop("example").run()
        end_time = time.time()
        print i, "elapsed:", end_time - start_time
        i += 1

The first loop takes ~30ms, the 2000th loop,  ~140ms.  The 'metadata' file goes from 2MB to 8MB in the same time.  My tests drop and create tables frequently, so they would tend to slow down from 20 seconds to 100 seconds over the course of a number of runs.

**Comment by danielmewes** [comment]
This was fixed in RethinkDB 2.1.
