### ISSUE TITLE
Unit test failures on OS X

### ISSUE THREAD

**Issue by gchpaco** [rethinkdb/rethinkdb#3610]
Running `rethinkdb-unittest` I get some failures on OS X.  It has persisted through multiple `make clean; make` rebuilds, so I suspect it is fundamental.

```
$ build/debug_clang/rethinkdb-unittest
( successes omitted )
[ RUN      ] JSProc.EvalTimeout
src/unittest/jsproc.cc:23: Failure
Expected: js_runner.eval(loop_source, config) throws an exception of type interrupted_exc_t.
  Actual: it throws nothing.
[  FAILED  ] JSProc.EvalTimeout (20 ms)
[ RUN      ] JSProc.CallTimeout
src/unittest/jsproc.cc:48: Failure
Expected: js_runner.call(loop_source, std::vector<ql::datum_t>(), config) throws an exception of type interrupted_exc_t.
  Actual: it throws nothing.
[  FAILED  ] JSProc.CallTimeout (84 ms)
( more successes omitted )
[ RUN      ] RDBProtocol.OverSizedKeys
src/unittest/rdb_protocol.cc:653: Failure
Value of: id.length() >= rdb_protocol::MAX_PRIMARY_KEY_SIZE
  Actual: false
Expected: true
[  FAILED  ] RDBProtocol.OverSizedKeys (772 ms)
[ RUN      ] RDBProtocol.OvershardedOverSizedKeys
src/unittest/rdb_protocol.cc:653: Failure
Value of: id.length() >= rdb_protocol::MAX_PRIMARY_KEY_SIZE
  Actual: false
Expected: true
[  FAILED  ] RDBProtocol.OvershardedOverSizedKeys (441 ms)
( more successes omitted )
[ RUN      ] TimerTest.TestApproximateWaitTimes
src/unittest/timer_test.cc:21: Failure
Expected: (llabs(diff - wait_array[i][j] * (1000LL * 1000LL))) < (2 * (1000LL * 1000LL)), actual: 4470710 vs 2000000
src/unittest/timer_test.cc:21: Failure
Expected: (llabs(diff - wait_array[i][j] * (1000LL * 1000LL))) < (2 * (1000LL * 1000LL)), actual: 5219998 vs 2000000
[  FAILED  ] TimerTest.TestApproximateWaitTimes (86 ms)
 ( more omissions )
[----------] Global test environment tear-down
[==========] 272 tests from 61 test cases ran. (672699 ms total)
[  PASSED  ] 267 tests.
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] JSProc.EvalTimeout
[  FAILED  ] JSProc.CallTimeout
[  FAILED  ] RDBProtocol.OverSizedKeys
[  FAILED  ] RDBProtocol.OvershardedOverSizedKeys
[  FAILED  ] TimerTest.TestApproximateWaitTimes

 5 FAILED TESTS
```

**Comment by danielmewes** [comment]
We've had the timeout failures on OS X for a while.
The OverSizedKeys failures are reason for concern though.

**Comment by danielmewes** [comment]
I can reproduce all of these failures on newton.

**Comment by gchpaco** [comment]
Interesting, here I assumed it was just my machine.

**Comment by gchpaco** [comment]
The overlong key problems are due to this:
```c++
            std::string id(i + rdb_protocol::MAX_PRIMARY_KEY_SIZE - 10,
                           static_cast<char>(j));
```
which defies belief in how idiotic it is, so I shall have to come up with some better way to do that.

**Comment by gchpaco** [comment]
TestApproximateWaitTimes appears to be because our nap function is only accurate to within about 25% on short wait times like this; for very small wait times (1 ms) it can be as much as 50%.  I have corrected it to pick 25% or 2 ms, whichever is larger, but I don't know for certain this will address the issue.

Table of %s on my OS X box follows:

Wait time (in ms) | Percentage deviation
-------------------- | ---------------------------
1 | 18.6483
1 | 2.78776
2 | 2.07043
5 | 2.88007
3 | 2.30791
3 | 5.80863
2 | 19.1259
5 | 0.567125
13 | 14.992
20 | 2.92692
40 | 0.120976
30 | 10.3766
30 | 3.06756
20 | 0.291125
8 | 0.632363
40 | 0.245048
13 | 2.25883
1 | 17.6654
1 | 3.12237
8 | 12.0125

**Comment by gchpaco** [comment]
The JS timeouts are because the API for `js_runner.eval` changed to return a string in case of timeout.

**Comment by gchpaco** [comment]
CR 2502, for posterity.
