### ISSUE TITLE
Web UI: Getting stuck on Data Explorer

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3616]
With Firefox 34.0:
Once I go to the Data Explorer, I cannot switch to any of the other pages. On the console I see this error:
`TypeError: this.query_result is undefined`

The error happens in this piece of code:
```
ResultViewWrapper.prototype.remove = function() {
      var _ref;
      if ((_ref = this.view_object) != null) {
        _ref.remove();
      }
      if (this.query_result.is_feed) {
        this.query_result.force_end_gracefully();
      }
      if (this.set_scrollbar_scroll_handler != null) {
        $(window).unbind('scroll', this.set_scrollbar_scroll_handler);
      }
      $(window).unbind('resize');
      $(window).off('scroll', this.scroll_handler);
      return ResultViewWrapper.__super__.remove.call(this);
    };
```

Specifically on the line
```
if (this.query_result.is_feed)
```

**Comment by danielmewes** [comment]
Once I run a query, I can switch to other pages again. Looks like this just needs a `?` in the Coffeescript code.

**Comment by AtnNn** [comment]
You've accurately pinpointed the problem.

**Comment by deontologician** [comment]
I happened to independently fix this on my branch as well. in CR 2509
