### ISSUE TITLE
Changefeed implementation in the web UI blinks the run/abort button

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#3618]
Go to the data explorer in the web UI, setup a changefeed query, and hit run (or cmd-enter). I used the following query:

```js
r.db('rethinkdb').table('stats').changes()
```

You can see the run button blink into "abort" then blink into "run" again, and finally settle on "abort". It shouldn't have the transition "abort/run" state, and go into "abort" state right away.

/cc @AtnNn

**Comment by AtnNn** [comment]
Fixed in `atnnn/3618` (437f121)
