### ISSUE TITLE
Minor stylistic issues for the changefeed implementation in the web ui

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#3619]
I have two minor pet-peeves with the changefeed implementation in the web UI:

- [ ] The pause (and to a lesser degree the play) buttons don't feel like buttons. I think a small change would make them more compelling. For example, we could draw a circle around them, or make the play button green (or possibly make the pause button red).
- [ ] The flash color (the light blue) is too subtle, it feels barely perceptible on my Air. I think we should make it a tad darker.

/cc @mglukhovsky @AtnNn

**Comment by mglukhovsky** [comment]
Agreed!
