### ISSUE TITLE
server_ghost issue doesn't respect the identifierFormat flag passed to table

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3624]
Currently, the issue `server_ghost` has the following format:
```
   {
      "critical": false,
      "description": "The server process with hostname `newton` and PID 10892 was deleted from the `rethinkdb.server_config` table, but the process is still running. Once a server has been deleted from `rethinkdb.server_config`, the data files for that RethinkDB instance cannot be used any more; you must start a new RethinkDB instance with an empty data directory.",
      "id": "0a321521-0722-532f-92ad-973cf92b7cc3",
      "info": {
         "hostname": "newton",
         "pid": 10892,
         "server_id": "88a37e2e-ccf7-49b3-a84a-9c34f4eb0163"
      },
      "type": "server_ghost"
   },
```

Passing the `identifierFormat` argument to table doesn't affect whether the server name or id is returned in the info subdocument. This makes some sense because it's server_id, not "server" like other issues. But it should be consistent.

**Comment by Tryneus** [comment]
The `server_ghost` issue actually can't provide a name for the server since it was deleted.  The name is gone.

**Comment by Tryneus** [comment]
That said, we could possibly have a server remember its name from when it was deleted, but I'm not sure if that would be much help.

**Comment by deontologician** [comment]
Yeah, I just realized this as I was mucking with it more. If there's an easy solution like using the server name the server was started with, then it might be worth it. If it requires keeping old server data around forever we should just close this

**Comment by Tryneus** [comment]
The data isn't persisted now, we would have to add handling for that.  But we could recognize `identifier_format` and show '__deleted_server__', which is what we show in other parts of code referring to the name of a deleted server (mostly just issues and log statements regarding intra-cluster connections).  That wouldn't be much use to users, though.

**Comment by deontologician** [comment]
Well, I mean the dead server has some default server name or maybe one set from the command line. Is that immediately discarded if the server is identified as a ghost?

**Comment by Tryneus** [comment]
That is actually immediately discarded if the data directory already exists.

**Comment by deontologician** [comment]
OK, then it probably isn't worth a major re-engineering just to have a server name in the issue. closing

**Comment by Tryneus** [comment]
For posterity, here is a more detailed explanation of what happens with the name:

* A server is started
* The server checks if it needs to initialize its data directory
  * If the data directory doesn't exist:
    * The server creates a default data directory
    * The server constructs its metadata, using parameters passed at startup, including `--server-name`
    * If no `--server-name` was specified, a random string based on the hostname is used
    * The server writes this metadata to its `metadata` file
  * If the data directory does exist, its `metadata` file is loaded, this overrides what was passed in `--server-name`
* The server may or may not connect to other servers in the cluster
* Metadata is exchanged with other servers, and will be merged using timestamps to resolve conflicts
* Now, we delete the server
* The server is erased from the metadata on all servers in the cluster, this includes its server name
* Even if removed from the cluster, the server will recognize itself as a ghost, but it does not know its true name
* I cry every time.
