### ISSUE TITLE
Reconfigure modal doesn't show anything if a shard primary is unavailable

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3625]
The code that talks to table.info should be completely removed for the modal, since no counts are used anyway. This is causing it to fail when server_config is perfectly fine and available to use.

We should probably also give some indication of servers that are disconnected/removed

**Comment by danielmewes** [comment]
I actually cannot find any `info()` in the query. After fixing https://github.com/rethinkdb/rethinkdb/issues/3507 and seeing the actual error returned, I think `reconfigure` just generally fails if a server is down (which won't change until we get Raft-based clustering probably).

**Comment by deontologician** [comment]
Ah, I probably should have checked if a bare reconfigure works

**Comment by danielmewes** [comment]
@deontologician Do you think we should still implement a custom error message for this case?

Currently (with the #3507 fix) it looks like this, which might be good enough:
![screenshot from 2015-01-21 12 54 24](https://cloud.githubusercontent.com/assets/505365/5844925/b3363c5e-a16c-11e4-8aa6-a639fad45120.png)

**Comment by deontologician** [comment]
That actually looks decent to me, especially since it's a weird corner case. I kind of separate the errors conceptually into "we can predict the server giving us this error" and "we need the server to tell us", and this seems fine in the latter

**Comment by deontologician** [comment]
Closing since the #3507 is in now
