### ISSUE TITLE
Investigate whether ghost servers can prevent backfilling

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3627]
@danielmewes and I observed some combination of circumstances on my cluster that prevented a backfill from occurring.

We're guessing that the relevant pieces are:
- shut down and permanently remove a shard primary, (with or without total data loss for the shard, not sure)
- bring the server back up, causing a ghost_server issue
- attempt to reconfigure the table

**Comment by danielmewes** [comment]
Assigning myself, will see if I can reproduce this.

**Comment by danielmewes** [comment]
Answer: Yes, it does. As long as a ghost server is connected, backfilling doesn't finish. Once I terminate it the tables become available.

Exact steps to reproduce:
* Start a two-server cluster, let's say the servers are called A and B
* Create a table, reconfigure to `{shards: 2, replicas: 1}`
* Remove one of the servers from the cluster, for example server B:
`r.db('rethinkdb').table('server_config').filter({name: "B"}).delete()`
* Reconfigure the table to `{shards: 2, replicas: 1}`
* The table never becomes available, the replicas are stuck in state "backfilling_data".
* Shut down the ghost server (server B)
* The table becomes available

**Comment by danielmewes** [comment]
@timmaxw When you come back on Friday, can you take a look at this?

**Comment by timmaxw** [comment]
Fix is in CR 2525.
