### ISSUE TITLE
"Permanently remove" button can become inactive in issues list

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3628]
To reproduce:

- disconnect two servers
- in the issues banner in the webui, click "Permanently remove" and complete the instructions in the modal
- The server should be removed correctly
- Click on "Permanently remove" on the second issue that's still in the issues banner
- Nothing should happen, the button is stuck

Refreshing solves the problem, I don't have a guess currently as to the cause

**Comment by danielmewes** [comment]
Just tested with the latest v1.16.x (including your fixes to the issue messages) and this appears to be working now.
Closing. We can re-open the issue if we see it again.

**Comment by deontologician** [comment]
This is funky, it sometimes works and sometimes doesn't. I'll try to replicate one more time, but in general I agree with closing
