### ISSUE TITLE
Oversharding a table, then reconfiguring in web UI doesn't display error message

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3651]
* Create a table
* Overshard it through ReQL admin (i.e. make it have more shards than there are servers)
* Use the reconfigure function in the web UI
* No error message is visible, but no configuration is shown either and the modal cannot be confirmed.
* Editing the number of shards field once makes the error message appear

**Comment by deontologician** [comment]
This is probably because oversharding is an error state in the reconfigure modal

**Comment by nighelles** [comment]
Did this get fixed? I'm not seeing the issue.

**Comment by nighelles** [comment]
This seems fixed.
