### ISSUE TITLE
"Permanently remove" modal doesn't show server name correctly

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#3655]
Wherever the server name was supposed to be, it shows an empty string or `undefined`.

![permanently remove](https://cloud.githubusercontent.com/assets/316661/5885620/f53a04ee-a326-11e4-854a-5e28fddeb3ca.png)

**Comment by deontologician** [comment]
This should be fixed on v1.16.x

**Comment by timmaxw** [comment]
Oops, I didn't realize that v1.16.x had been branched off.
