### ISSUE TITLE
Change some guarantees in changefeed code to rasserts

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3656]
There are a couple of expensive guarantees in the changefeed code right now.  I'd like to leave them in for 1.16 because I'm worried about the code being wrong, but we should change them to rasserts for 2.0.  (cc @danielmewes)

**Comment by mlucy** [comment]
@danielmewes, do you remember any of these which were particularly egregious off the top of your head?

**Comment by danielmewes** [comment]
@mlucy the ones where we guarantee that old_val is different from new_val. Those perform datum comparisons, which are not for free.

**Comment by mlucy** [comment]
In next.
