### ISSUE TITLE
Error in dump command

### ISSUE THREAD

**Issue by YChebotaev** [rethinkdb/rethinkdb#3658]
I'm trying to dump my database with `rethinkdb dumb` cli command, and get an error:
```
rethinkdb dump
NOTE: 'rethinkdb-dump' only dumps data and does *not* dump secondary indexes or
 cluster metadata.  You will need to recreate your secondary indexes and cluster
 setup yourself after you run 'rethinkdb-restore'.
Exporting to directory...
[==                                      ]   5% 
129 rows exported from 4 tables
ReQL error during 'table scan': Unknown pseudo-type BINARY
Errors occurred during export
Error: rethinkdb-export failed
```

I am on osx 10.7.

```
rethinkdb -v
rethinkdb 1.15.1 (CLANG 4.2 (clang-425.0.28))_
```

**Comment by danielmewes** [comment]
Hi @YChebotaev, if you haven't done so yet, can you try updating the Python driver and see if that solves the problem?
```
sudo pip install --upgrade rethinkdb
```

The `rethinkdb dump` command is actually implemented as a part of the Python driver, so if you're using an older version it might not suppport the binary data type yet.

**Comment by danielmewes** [comment]
Closing since we haven't heard back from @YChebotaev .
@YChebotaev if the problem still persists after upgrading the driver, please let us know and we will re-open the issue.
