### ISSUE TITLE
Add back `durability` opt arg to tableCreate

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3659]
We should add back the `durability` opt arg to `tableCreate`. There's no real reason to remove it, and it's strictly better to keep it in terms of backwards compatiblity and convenience I think.

It was previously removed as part of https://github.com/rethinkdb/rethinkdb/issues/2876 , but without any special reason as far as I can see. Note that `table_config` still has the durability field (https://github.com/rethinkdb/rethinkdb/issues/3066#issuecomment-62468938), so it should be consistent to allow it for `tableCreate` as well.

I know this is super last-minute, and I apologize for not noticing this earlier.

**Comment by Tryneus** [comment]
Fix has been approved and merged into `next` in commit 28f3c07, and cherry-picked into `v1.16.x` in commit 0c9b2a2.  Review was 2533.  Will be in release 1.16.0.
