### ISSUE TITLE
Use real dependency management for the webui code like browserify/require.js

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3660]
Right now the order of our js files loading is done in mk/webui.mk. All the web ui coffee files must be explicitly mentioned there in the correct order so their dependencies are concatenated earlier in the file.

This is pretty brittle, annoying and unnecessary because there are tools like browserify and require.js

**Comment by danielmewes** [comment]
@deontologician is this getting addressed by the changes you're currently having in CR 2715?

**Comment by deontologician** [comment]
Yes, that's the one
