### ISSUE TITLE
Jobs table: Report open cursors as single entry

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3662]
Currently the jobs table gets a new entry whenever we request a new batch from a cursor.
This is especially weird in combination with changefeeds.

**Comment by Tryneus** [comment]
This is up in review 2593, containing a complete refactor of the `stream_cache_t`, which is now the `query_cache_t`.  Regarding the jobs table, this also includes the ability to see and interrupt queries/streams even when they are not actively running.

**Comment by Tryneus** [comment]
This has been fixed and merged to `next` in commit 4cdb9ba.  Will be in release 2.0.
