### ISSUE TITLE
Deprecate protobuf wire protocol

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3664]
We could print a warning to the log the first time someone is connecting with a protocol buffer client.
We should mention that support for this driver is going to be removed in the next version of RethinkDB.

**Comment by danielmewes** [comment]
This didn't make it into 2.0.

I think instead we'll just remove the protocol buffer interface and put a list of now unsupported drivers in the release notes for the next version.

Users who rely on old drivers will have to stick with 2.0 for a while, but that's probably ok (the old drivers are unlikely to benefit from most of the new features anyway).

**Comment by danielmewes** [comment]
Since we changed our release plans for 2.1 and 2.2, this is now again something we should try to do.

The minimal solution is to add a message to our 2.1 release notes stating that the protocol buffer protocol is now deprecated and will be removed in the next release.

The more polished solution is also printing a log message on the server the first time it detects a protocol buffer client.

**Comment by mlucy** [comment]
@danielmewes -- this isn't assigned to anyone, what's going on with it?

**Comment by danielmewes** [comment]
I'll just include a note in the release notes.

**Comment by larkost** [comment]
Are we going to have a second issue to do the actual removal, or continue on this one? If we are going to have a new one we need to remove the protobuf test as well.

**Comment by danielmewes** [comment]
@larkost Separate issue: https://github.com/rethinkdb/rethinkdb/issues/4601 (just opened)

**Comment by danielmewes** [comment]
This is noted in the 2.1.0 release note draft.
