### ISSUE TITLE
Buildbot should run the ReQL tests

### ISSUE THREAD

**Issue by gchpaco** [rethinkdb/rethinkdb#3669]
I noticed that buildbot does not run the ReQL tests; this should be fixed.  Running them is theoretically as simple as `test/rql_test/test_runner`.

**Comment by deontologician** [comment]
This would be awesome. Also, I've seen things in other CI systems that will keep track of "newly failing tests" etc. Not sure how difficult that would be with buildbot (in other words, how much buildbot would have to know about the format of the test output)

**Comment by larkost** [comment]
The premise of this is incorrect, we have long had the `ql` test that runs all of the `test-runner` tests. Additionally `interface.artificial_table` runs a subset with specific options. Finally this is eventually going to go away with #3442.

Tracking test failures is much more complicated, and sadly `buildbot` does not (currently) do anything to help us in this. Long term it is on my list of problems to solve, but that is some ways out both in terms of time and work.
