### ISSUE TITLE
Web dashboard doesn't load most of the time

### ISSUE THREAD

**Issue by elifarley** [rethinkdb/rethinkdb#3673]
I have a 1GB RAM OpenVZ VPS running RethinkDB 1.15.3 under Fedora 20.

I run Putty Release 0.60 to establish an SSH tunnel (9090:localhost:8080) from my Windows box and try to load the dashboard page at http:localhost:9090/

I can only use it after refreshing the page many many times. I get a blank page and Javascript errors on the browser console almost every time I open that page (using Chrome and IE8).

The SSH connection looks good, as I can type shell commands without any problems.
I can browse other web sites without any problems.

Here are some errors I get on the browser console (they can be different every time I reload the page):

Uncaught SyntaxError: Unexpected end of input - backbone.js:1
Uncaught SyntaxError: Unexpected token ILLEGAL - jquery.form.js:798

**Comment by danielmewes** [comment]
Hi @elifarley , sorry you are running into this issue.

If I had to guess, I'd say that this is probably some timeout or other connectivity issue.
@mglukhovsky @deontologician have you seen this / heard of this before?

@elifarley How fast is your network/Internet connection?

You might also want to make sure that the server has enough free memory and isn't going into swap or anything like that.

**Comment by danielmewes** [comment]
@elifarley I can reproduce seemingly random failures when using Putty on a Windows box to SSH-tunnel the web UI.
Which SSH client are you using? It's possible that http://sshwindows.sourceforge.net/ works better than Putty for this.

**Comment by danielmewes** [comment]
@gchpaco you mentioned today that Putty had some bugs with respect to multiplexing, which might be relevant here. Do you have more details on that and know whether that's still the case?

**Comment by gchpaco** [comment]
The flaws I knew about have been patched for a while, but it would not surprise me to know that they were occasionally present.  Checking...

There do appear to be some issues involving IPv6 noted at http://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/ but I don't see any known bugs involving tunneling.  It would help, @danielmewes, if you could turn logging on in Putty and I could see them.

**Comment by danielmewes** [comment]
Actually I just updated Putty on my machine and now I cannot reproduce the issue anymore (was using a version that was a couple years old before, which matches what @gchpaco said).

@elifarley if you're not already running the latest version, that's probably worth a try. If the problem persists, please let us know so we can investigate if anything else is wrong.

**Comment by mglukhovsky** [comment]
@danielmewes, very lucky that you managed to reproduce it with an older version (that you happened to have installed!)

@elifarley, what version of Putty are you running?

**Comment by elifarley** [comment]
I'm using Putty Release 0.60 (original post updated to reflect that).
I've updated to Release 0.63, but it looks like the problem persists...

I then tried the BitVise SSH client (downloaded from http://www.putty.org/), and it seems to solve the problem :)

**Comment by danielmewes** [comment]
Thanks for your tests and feedback @elifarley . We'll investigate this more.
How fast is your Internet connection?

**Comment by elifarley** [comment]
I've set up a SOCKS5 proxy via SSH so that I could perform a speed test using my local browser.
According to www.speedtest.net:
Ping: 240ms; Download: 15.54 Mbps; Upload: 0.75 Mbps

**Comment by elifarley** [comment]
After rebooting my machine, I was unable to reproduce the problem, so I'll close it.

**Comment by mglukhovsky** [comment]
@elifarley, glad things worked out for you (and in case others run into this issue, now we have a few suggestions to share on how to fix it!)
