### ISSUE TITLE
IE11: Table / server list loads slowly on first visit

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3674]
I was testing our new 1.16 web UI on IE 11 and ran into this odd behavior:

The first time I went to the web UI, the tables as well as the servers list were stuck in the loading state for several seconds before anything appeared.

Since then it has been working fine (i.e. results appear almost immediately) everytime I go to the web UI, even after restarting the browser.

I've once been able to get the slow loading again by cleaning the browser cache and using private mode, but it's not consistent.

Unfortunately this is pretty tricky to reproduce.
It's also not very severe since the data eventually appears and from then on everything seems to be working fine.
It might hint towards some race condition while loading though.

**Comment by mglukhovsky** [comment]
@danielmewes: does IE11 have decent debugging tools that we can use to profile what's happening?

**Comment by danielmewes** [comment]
@mglukhovsky Yes they didn't show anything. I might have opened them too late though.
Will try to reproduce this again later.

**Comment by danielmewes** [comment]
Will re-open if I see this again (maybe it was broken because we used HTTP get for opening ReQL connections);
