### ISSUE TITLE
Reading from multiple changefeeds in Ruby

### ISSUE THREAD

**Issue by gchpaco** [rethinkdb/rethinkdb#3678]
This is intended as an analog for #3298 in the context of Ruby.

We don't presently have a good story for reading from multiple changefeeds concurrently in Ruby, as in the Python case; this should get fixed before 2.0.

Like in the Python case (prior to 3.4) and unlike in the JavaScript driver, Ruby does not bundle a way of doing nonblocking IO in the base language.  Unlike in the Python case, Ruby does offer [Fibers](http://www.ruby-doc.org/core-2.2.0/Fiber.html) starting in 1.9.  Fibers are cooperatively scheduled coroutines, more or less; they have small stacks reserved for them but the differences are very technical and they can be thought of as coroutines.  So we might be able to do this without using an additional library.

Another alternative is using something like [EventMachine](http://rubyeventmachine.com).  I have used EM before and it's rather scary, not the least of which because it uses its own I/O routines, entirely sidestepping Ruby; it also has the worst implementation of `popen` I have ever seen, which I swear I fixed years ago but which does not appear to have ever been accepted by upstream.  So I would prefer to use Fibers here.

**Comment by danielmewes** [comment]
I think it's a good idea to provide a consistent basic interface across all drivers where it makes sense, such as this one https://github.com/rethinkdb/rethinkdb/issues/3298#issuecomment-62483313 .

In addition, making sure that our driver works with Ruby Fibers sounds like a great idea to make changefeeds easy to use in Ruby.

**Comment by mlucy** [comment]
I think we should consider doing both (i.e. offering an EventMachine integration even if we go with fibers for the main driver).  A lot of other libraries people want to use (e.g. Websocket libraries) already use EventMachine, so it would be nice if people could just hook changefeeds up to those).

**Comment by gchpaco** [comment]
Using Fiber libraries from EM appears to be fairly easy; https://www.igvita.com/2010/03/22/untangling-evented-code-with-ruby-fibers/

**Comment by thelinuxlich** [comment]
I thought rubyists were moving to https://celluloid.io/ where async is concerned

**Comment by gchpaco** [comment]
I have not been a bleeding edge Ruby developer for several years, so it doesn't surprise me that people are moving away from EM given its deficiencies.  I've never heard of Celluloid, though, so I'll have to look into that.

Hopefully if we support Fibers, then EM/Celluloid/InsertFrameworkDuJourHere will all be compatible.

**Comment by gchpaco** [comment]
Possible implementation: assume we have @coffeemug's `.on` proposal from https://github.com/rethinkdb/rethinkdb/issues/3298#issuecomment-62483313 .  If we pass that a `Fiber` object, then we could call `Fiber.resume(cursorargs)`.  This would look like this from the client's POV:
```ruby
feed1 = r.table('foo').changes().run(conn).on(Fiber.new do |change|
  until change.nil?
    # ... do something ...
    change = Fiber.yield
  end
end)
feed2 = r.table('bar').changes().run(conn).on(Fiber.new do |change|
  until change.nil?
    # ... do something ...
    change = Fiber.yield
  end
end)
# in base Ruby case
conn.poll(wait=True)
```
We can also invert it, with a new method, maybe `.fiber(identifier)`, that returns a `Fiber` which gives us a new value every time we call `yield` on it.  This doesn't really support readiness, tho.  Also, there's probably a better name, but that'll do for the moment.  We can add readiness by adding a new type that amounts to a union of the streams; so it would look like this:
```ruby
feed1 = r.table('foo').changes().run(conn).fiber(:foo)
feed2 = r.table('bar').changes().run(conn).fiber(:bar)
union = feed1 + feed2
# in base Ruby case
for feed, change in union do
    case feed
    when :foo
        # do something with change from feed1
    when :bar
        # do something with change from feed2
    end
end
```

With EventMachine and this `.fiber` thing, this would look like this:
```ruby
EventMachine.run do
  Fiber.new {
    for change in r.table('foo').changes().run(conn).fiber
        # ... do something
    end
  }.resume
  Fiber.new {
    for change in r.table('bar').changes().run(conn).fiber
        # ... do something
    end
  }.resume
end
```

**Comment by gchpaco** [comment]
I could also imagine `.on` taking an object and a symbol suitable for `.send`; so that would make this look something like this.
```ruby
class Klass
   def bar(change)
      ...
   end
   def foo(change)
      ...
   end
   ...
end
k = Klass.new
feed1 = r.table('foo').changes().run(conn).on(k, :foo)
feed2 = r.table('bar').changes().run(conn).on(k, :bar)
# in base Ruby case
conn.poll(wait=True)
```

**Comment by gchpaco** [comment]
Upon further reflection the EM examples will probably require us, on some level at least, to hitch the Ruby driver's wagon to EM's horse.  I don't like this, but I don't think it's avoidable and there are EM-aware versions of several other protocols that we would need to copy.

**Comment by coffeemug** [comment]
For reference -- see https://github.com/rethinkdb/rethinkdb/issues/3298#issuecomment-73011053. It specs a simpler API in Python that could be trivially adapted to Ruby.

**Comment by mlucy** [comment]
I've been thinking about this, and I think we should:
1. Provide our own API that's as easy as possible to implement and reason about.
2. Integrate with EventMachine for people who want event-style programming.

It's obvious how to do (2); it's just a pain.  For (1) I think we should do something like @coffeemug mentioned in #3298 -- we should offer a way to merge multiple lazy streams into a single lazy stream, and offer a way to figure out which .  To use @coffeemug's `r.join` syntax:

```rb
c1 = r.table('test').changes.run
c2 = r.table('test2').changes.run
both = c1.join(c2) # also legal: `r.join(c1, c2)`
both.each {|change|
  # do something with change
}
both.each {|change, cursor|
  if cursor == c1 # also legal: cursor.query == q1
    # do something with changes from q1
  else if cursor == c2
    # do something with changes from q2
  end
}
```
```

**Comment by mlucy** [comment]
(I think we should extend discussion on this and #3298 since it's important and we don't yet seem to know what we want to do.)

**Comment by danielmewes** [comment]
In an offline discussion with @larkost , @coffeemug , @timmaxw and @mlucy , we decided to provide an event-loop integration in 2.0.

Since EventMachine is the most common one, we should implement support for that first.

@gchpaco described in https://github.com/rethinkdb/rethinkdb/issues/3678#issuecomment-72129095 that we could implement a fiber-based interface and then very easily put an EventMachine API on top of that. If we can re-use the fiber implementation for EventMachine I have no objections to that.

So now we just have to come up with the details of our EventMachine (and possibly fiber) API.

@mlucy since you had recently used some EventMachine framework, maybe you can describe what you think a natural EventMachine API for cursors would look like?

**Comment by danielmewes** [comment]
We should get this going.

@mlucy can you comment on the interface? You had mentioned something about named events in the context of your Slack ReQL bot development. Which interface would seem natural to you given the other EventMachine interfaces that you have encountered?

So far @gchpaco has suggested this interface:
```
EventMachine.run do
  Fiber.new {
    for change in r.table('foo').changes().run(conn).fiber
        # ... do something
    end
  }.resume
  Fiber.new {
    for change in r.table('bar').changes().run(conn).fiber
        # ... do something
    end
  }.resume
end
```

or alternatively one that uses `on` with a callback, possibly also supporting an object/method name pair:
```
class Klass
   def bar(change)
      ...
   end
   def foo(change)
      ...
   end
   ...
end
k = Klass.new
feed1 = r.table('foo').changes().run(conn).on(k, :foo)
feed2 = r.table('bar').changes().run(conn).on(k, :bar)
```
(not sure what this would look like exactly with EventMachine. @gchpaco can you clarify?)

**Comment by gchpaco** [comment]
The intention there, @danielmewes, was that in the context of EM (perhaps with a method with a different name; there's prior art for appending a- for the async version in the other EM drivers, so perhaps `aon`) would register callbacks within the EM runtime and return a future; if our connection is EM enabled, `on` would probably Just Work.  Upon hitting the end of the block handed to `EventMachine.run` it would loop until it saw `EventMachine.stop`; so as stuff comes in from the database, the callbacks would be run.  The "magic" as it were would be setting up `conn` in our example so that it's using EM.

So for the user it would look something like this:
```ruby
class Klass
   def bar(change)
      ...
   end
   def foo(change)
      ...
   end
   ...
end
k = Klass.new
EventMachine.run do
  conn = r.aconnect(...)
  r.table('foo').changes().run(conn).on(k, :foo)
  r.table('foo').changes().run(conn).on(k, :bar)
end
```
To make this work, we would need to define this new `aconnect` method (which would override all of the network I/O with EM's versions), and `on` and/or `aon` would need to be altered slightly.

**Comment by danielmewes** [comment]
@gchpaco Ok that interface looks reasonable to me.
I have no experience with EventMachine at all, so I trust you and @mlucy to pick an interface that feels natural in this context.

**Comment by mlucy** [comment]
Sorry I didn't get to this until today.

I haven't used EM much, but here's roughly what I would expect:

```rb
require 'rethinkdb'
require 'em-rethinkdb'

# A simple interface for the common case
EventMachine.run {
  r.table('foo').changes().run(conn) {|change|
    # do something with `change`
  }
}

# A complicated interface for people who want more control
class StreamHandler < EventMachine::RethinkDB::StreamHandler
  def on_open
  end
  def on_close
  end
  def on_error(err)
  end
  def on_val(val)
  end
end

class ChangeHandler < EventMachine::RethinkDB::ChangeHandler
  def on_open
  end
  def on_close
  end
  def on_error(err)
  end
  def on_initial_val(val) # runs on every initial val
  end
  def on_change(change) # runs on every change
  end
  def on_ready # runs when all initial vals have been received
  end
end

EventMachine.run {
  conn = r.aconnect(...)
  r.table('foo').changes().run(conn, StreamHandler)
  r.table('foo').changes().run(conn, ChangeHandler)
}
```

**Comment by mlucy** [comment]
I'm basing the second one on https://github.com/eventmachine/eventmachine/wiki/Code-Snippets .  https://github.com/igrigorik/em-websocket is the only EM interface I've actually used.

**Comment by danielmewes** [comment]
Oh I was about to write how I preferred
```
r.table('foo').changes().run(conn).on(k, :foo)
```
over
```
r.table('foo').changes().run(conn, StreamHandler)
```
, but actually the `on` syntax might be bad because it requires that we get some return value from `run` even before we've received the first batch.

This will also affect https://github.com/rethinkdb/rethinkdb/issues/2622 and https://github.com/rethinkdb/rethinkdb/issues/3785 (the current proposal relies on `on` as well). We could make `run` return a promise that you can call `on` on, but that sounds unnecessarily complicated. We might still want to support that eventually, but I don't think we should do it now.

In the Ruby case, we could call that variant of `run` `arun` to make the distinction clear and to make it more discoverable than just having an overloaded variant of `run` that takes a second argument. What do you think?


...Also this looks great
```
# A simple interface for the common case
EventMachine.run {
  r.table('foo').changes().run(conn) {|change|
    # do something with `change`
  }
}
```

@gchpaco comments?

**Comment by gchpaco** [comment]
I don't *love* the `StreamHandler` et al interfaces, but I can see the value.

The main issue I have with the enum interface is I'm not sure how it plays with more involved coroutines.  But it's possible to support it in Ruby pretty easily (methods can have an optional "block"), so I don't feel strongly against it.  Numerous standard library methods do this, so I presume Rubyists are accustomed to it.  The main issue with the block case is that you cannot perform `yield` statements in the block; it's very much like a callback in that way.  If you want or need to do something more sophisticated, it's a bit awkward.

**Comment by danielmewes** [comment]
My comment was mainly about `run(conn).on(cb)` vs. `run(conn, cb)`.

I guess the benefit of
```
r.table('foo').changes().run(conn, StreamHandler)
```
over
```
r.table('foo').changes().run(conn, k, :foo)
```
is that we get specific callbacks for errors, initial values, closing the cursor etc. which is really nice.

If we want to reduce complexity a little I think we can get away with only implementing `StreamHandler` for now, but not `ChangeHandler` (all changefeed events would just be passed into `on_val` the way we get them from the server).

What should we do if you pass a `StreamHandler` to `run` for a query that returns an `atom`? Just perform a sequence of `on_open`, `on_val`, `on_close` calls with the single returned value?


Regarding the block interface: For cases where users need to do more sophisticated things, wouldn't the `StreamHandler` interface allow for it?
How would @mlucy 's block interface compare to the fiber-based on @gchpaco has proposed earlier?

**Comment by coffeemug** [comment]
> ```rb
# A simple interface for the common case
EventMachine.run {
  r.table('foo').changes().run(conn) {|change|
    # do something with `change`
  }
}
```

This is lovely!

> ```rb
# A complicated interface for people who want more control
class StreamHandler < EventMachine::RethinkDB::StreamHandler
  def on_open
  end
  def on_close
  end
  def on_error(err)
  end
  def on_val(val)
  end
end
```

This is also very nice!

> ```rb
class ChangeHandler < EventMachine::RethinkDB::ChangeHandler
  def on_open
  end
  def on_close
  end
  def on_error(err)
  end
  def on_initial_val(val) # runs on every initial val
  end
  def on_change(change) # runs on every change
  end
  def on_ready # runs when all initial vals have been received
  end
end
```

I'm not sure we need a special `ChangeHandler` -- I think we could get away with asking people to always use a `StreamHandler`. The `ChangeHandler` is a nice abstraction, though, so I'm not sure. If we do decide to add both, I'd suggest always allowing the user to pass `StreamHandler`, even on feeds. They can choose to use `ChangeHandler` on feeds if they want to, but shouldn't have to.

**Comment by gchpaco** [comment]
Derp re: close & reopen.  Anyway.



> is that we get specific callbacks for errors, initial values, closing the cursor etc. which is really nice.

My intention with the `.on` interface was that you were only interested in changes.  If you want to handle closes, errors, or what have you, you should use something more sophisticated; this was the simple version.  As such the `.run(conn, foo, :k)` is probably okay, although I would want to call it `.arun`.  This isn't as important in the block case because it's fairly obvious to a Rubyist what you want to do there, whereas this callback thing is a bit subtle.



> What should we do if you pass a StreamHandler to run for a query that returns an atom? Just perform a sequence of on_open, on_val, on_close calls with the single returned value?

That would make sense to me.

> Regarding the block interface: For cases where users need to do more sophisticated things, wouldn't the StreamHandler interface allow for it?
> How would @mlucy 's block interface compare to the fiber-based on @gchpaco has proposed earlier?

Yes, the `StreamHandler` is intended as a "I'm doing something sophisticated I'm willing to put up with some additional complexity" thing.  The block interface is more attractive, if slightly less flexible.  We might be able to get away with both; if it's a `Fiber` it won't support `.call` or `[]` the way that `Proc`s do, but it will support `.resume`, which is used exactly the same way, which is also the same way that you would do it if you had passed a block (viz. `yield *args` <=> `p.call(*args)` <=> `f.resume(*args)`).

**Comment by danielmewes** [comment]
Sounds like we're converging towards an API here.

1. For simple use cases:
```rb
EventMachine.run {
  r.table('foo').changes().run(conn) {|change|
    # do something with `change`
  }
}
```

2. For more sophisticated cases:
```rb
r.table('foo').changes().run(conn, StreamHandler)
```

with the `StreamHandler` interface as described above, and working for all of atoms, normal cursors and feeds.

**Comment by mlucy** [comment]
I think `StreamHandler` should definitely work for both streams and cursors.  Let's call `ChangeHandler` polish; I think it's really useful but we can always add it later, and it depends on the `note_state` proposal getting done first.

If we make `StreamHandler` work for atoms, we have to decide what to do if the atom is an array.  I think most people would expect `r.table('test').order_by(index: 'id')` and `r.table('test').order_by('id')` to be treated the same way even though one returns a stream and one returns an array.  I would be OK with making `StreamHandler` iterate over arrays but evaluate only once on all other atoms.

**Comment by coffeemug** [comment]
> I think `StreamHandler` should definitely work for both streams and cursors.

:+1: 

> I would be OK with making `StreamHandler` iterate over arrays but evaluate only once on all other atoms.

:+1: People definitely don't want to write different code to deal with arrays and streams, so I think the StreamHandler should iterate over arrays in the same way as it iterates over streams. I might consider calling it `SequenceHandler` to avoid confusion.

**Comment by danielmewes** [comment]
>  People definitely don't want to write different code to deal with arrays and streams, so I think the StreamHandler should iterate over arrays in the same way as it iterates over streams. I might consider calling it `SequenceHandler` to avoid confusion.

That sounds good to me.

**Comment by mlucy** [comment]
`SequenceHandler` sounds good to me too.

**Comment by danielmewes** [comment]
Marking settled with the interface like here https://github.com/rethinkdb/rethinkdb/issues/3678#issuecomment-75350275
and the following additions/changes:
- `SequenceHandler` instead of `StreamHandler`
- For an atom that's an array, call the `SequenceHandler` `on_val` callback for each element in the array

**Comment by mlucy** [comment]
@gchpaco -- how far into this are you?  The only thing I have left for the release is writing the driver developer notes, so I could maybe do the EM integration if you're pressed for time.

**Comment by gchpaco** [comment]
I have not begun to work on the Ruby side; the Python keeps eating me.  If you want to do it, that would be really, really helpful.

**Comment by gchpaco** [comment]
Note that EM is an old framework and in particular is very callback based; the easiest way to translate that to permit the sort of logic our drivers do is to add the driver logic to a `Fiber` and the callbacks would call `Fiber.resume`.

**Comment by mlucy** [comment]
Alright, I'll take this.  Re-assigning to myself.

**Comment by mlucy** [comment]
Been working on this.  There's good news and bad news.

The most unambiguous piece of good news is that EventMachine is kind enough to yield to other threads between ticks.  This means that we can keep most of the driver logic (where it spawns a listener in a separate thread), and that we don't have to have separate code paths where we sometimes use blocking IO and sometimes use EM-friendly IO.  This is maybe slightly sub-optimal, but I've been experimenting with it and it doesn't seem to hurt performance much or have large latency spikes or anything.

There's also a pice of hypothetically-good news coupled with a piece of bad news.  EventMachine has built-in support for integrating with libraries that block the thread using `EM.defer`, which made me think that maybe we could get away with barely touching the driver's internals.  Unfortunately if you use `EM.defer`, you're limited by the size of EM's threadpool, which defaults to size 20.  (The user can reconfigure this, but it has to happen before `EM.run`.)  If we used `EM.defer` and users tried to listen on more than 20 changefeeds, and the first 20 they listened on never returned results, they'd never return results from anything after those 20.

I have a prototype working with `EM.defer`, but as-is I don't think it's usable because of the 20-feed problem.  There are two possibilities:
* Keep track of how many feeds are spawned, warn the user if they've spawned more than 20 and recommend they increase the threadpool size.
* Rework the internals of the driver to support either blocking on condition variables *or* calling a callback through EM.

The first is easy, and if we did that then we could ship this tomorrow (I even have moderately good tests).  The second is a little harder, but I think it's perfectly doable.  I'm probably going to go with the second option unless it turns out to be really hard for some reason and I'm holding up the release.  It will make the driver internals more complicated (and they're already a little too complicated IMO), but it will be a lot better, and it will be more performant than using `EM.defer` anyway.

**Comment by mlucy** [comment]
Also, while I was working on this I discovered a few problems with the interface we talked about earlier (no way to get errors with the simple interface, the difference between `StreamHandler` and `ChangeHandler` stopped making since once changes worked on both, etc.).  I'm making a few small changes (supporting both arity-1 and arity-2 callbacks so that you can receive an error like in JS for the simple case, have `StreamHandler` and `ChangeHandler` be just `Handler` where the behavior is determined by what functions you define in the subclass, etc.).

I'm going to write up a short tutorial/guide when I'm done; if after reading it people don't like the changes I'm making to the interface I'd be happy to roll them back (they aren't really the hard part at all).

**Comment by gchpaco** [comment]
How charming.  Well, that happens, thank you for taking it on.

**Comment by coffeemug** [comment]
I'd go with the second option because the user is always right, (unless they're not, but in this case I think they are).

**Comment by mlucy** [comment]
This is in CR 2716.  The brief tutorial I promised is below.

**Comment by mlucy** [comment]
# Accessing RethinkDB with EventMachine

## Basic Usage

The simplest way to access RethinkDB with EventMachine is to call
`em_run` with a block.  If RethinkDB returns a sequence (an array or a
stream), the block will be called with each element of that sequence.
If RethinkDB returns anything else, the block will be called once with
that value.

#### Example 1: iterating over a stream

```rb
# Insert some data.
r.table('test').insert([{id: 0}, {id: 1}, {id: 2}]).run($conn)
EM.run {
  # Print every row in the table.
  r.table('test').order_by(index: 'id').em_run($conn) {|row|
    p row
  }
}
```

Will print this:

```rb
{"id"=>0}
{"id"=>1}
{"id"=>2}
```

#### Example 2: iterating over an array

```rb
EM.run {
  # Print an array.
  r.expr([1, 2, 3]).em_run($conn) {|n|
    p n
  }
}
``

Will print this:

```rb
1
2
3
```

#### Example 3: accessing a single row

```rb
# Insert some data.
r.table('test').insert([{id: 0}, {id: 1}, {id: 2}]).run($conn)
EM.run {
  # Print a single row.
  r.table('test').get(0).em_run($conn) {|row|
    p row
  }
}
```

Will print this:

```rb
{"id"=>0}
```

## Basic Error Handling

If you pass `em_run` a block that only accepts a single argument,
RethinkDB's EM adapter will handle errors by re-throwing them.  You
can also handle errors in the block by passing `em_run` a block that
accepts two arguments.  If you do so, then the block will either be
called with `nil` as its first argument and data as its second
argument, or with an error as its first argument and `nil` as its
second argument.

Note that it's possible for the block to be passed data many times,
and then be passed an error.  For example, this can happen if you lose
availability in the middle of a long read.

#### Example 1: re-thrown errors

```rb
EM.run {
  r.table('non_existent').em_run($conn) {|row|
    p row
  }
}
```

Will produce an error:

```rb
RethinkDB::RqlRuntimeError: Table `test.non_existent` does not exist.
Backtrace:
r.table("non_existent")
^^^^^^^^^^^^^^^^^^^^^^^
```

#### Example 2: handling errors in the block

```rb
EM.run {
  r.table('non_existent').em_run($conn) {|err, row|
    if err
      p [:err, err.to_s]
    else
      p [:row, row]
    end
  }
}
```

Will print:

```rb
[:err, "Table `test.non_existent` does not exist.\nBacktrace:\nr.table(\"non_existent\")\n^^^^^^^^^^^^^^^^^^^^^^^"]
```

And

```rb
# Insert some data.
r.table('test').insert([{id: 0}, {id: 1}, {id: 2}]).run($conn)
EM.run {
  # Print every row in the table.
  r.table('test').order_by(index: 'id').em_run($conn) {|err, row|
    if err
      p [:err, err.to_s]
    else
      p [:row, row]
    end
  }
}
```

Will print:

```rb
[:row, {"id"=>0}]
[:row, {"id"=>1}]
[:row, {"id"=>2}]
```

## Advanced Usage

More precise control is provided by a superclass `RethinkDB::Handler`.
You can write a class that inherits from `RethinkDB::Handler` and
overrides certain methods, then pass an instance of that class to
`em_run`.  (If you instead pass the name of the class, the RethinkDB
event machine adapter will instantiatie it for you with no arguments
and use that.)

Here's a simple example of a handler that prints things:

```rb
class Printer < RethinkDB::Handler
  def on_open
    p :open
  end
  def on_close
    p :closed
  end
  def on_error(err)
    p [:err, err.to_s]
  end
  def on_val(val)
    p [:val, val]
  end
end
```

#### Example 1: handling a stream


```rb
# Insert some data.
r.table('test').insert([{id: 0}, {id: 1}, {id: 2}]).run($conn)
EM.run {
  # Print every row in the table.
  r.table('test').order_by(index: 'id').em_run($conn, Printer)
}
```

Will print this:

```rb
:open
[:val, {"id"=>0}]
[:val, {"id"=>1}]
[:val, {"id"=>2}]
:closed
```

## Granular Advanced Usage

Sometimes you want to treat atoms differently from sequences, or to
distinguish streams from arrays.  You can do that by defining
`on_array`, `on_atom`, and `on_stream_val`.  (If `on_array` isn't
defined, arrays will be treated the same as streams and
`on_stream_val` or `on_val` will be called for every element of the
array.)

```rb
class Printer < RethinkDB::Handler
  def on_open
    p :open
  end
  def on_close
    p :closed
  end
  def on_error(err)
    p [:err, err.to_s]
  end
  def on_atom(atom)
    p [:atom, atom]
  end
  def on_array(array)
    p [:array, array]
  end
  def on_stream_val(val)
    p [:stream_val, val]
  end
end
```

#### Example 1: handling granular results

```
# Insert some data.
r.table('test').insert([{id: 0}, {id: 1}, {id: 2}]).run($conn)
EM.run {
  # Print every row in the table.
  r.table('test').order_by(index: 'id').em_run($conn, Printer)
  # Print an array.
  r.expr([1, 2, 3]).em_run($conn, Printer)
  # Print a single row.
  r.table('test').get(0).em_run($conn, Printer)
}
```

Will print this:

```
:open
[:stream_val, {"id"=>0}]
[:stream_val, {"id"=>1}]
[:stream_val, {"id"=>2}]
:closed
:open
[:array, [1, 2, 3]]
:closed
:open
[:atom, {"id"=>0}]
:closed
```

(Note that when you register multiple callbacks, the order they're
called in isn't guaranteed -- it would be perfectly legal for this to
have printed the result of `r.expr([1, 2, 3])` first.)

## Changefeeds

Changefeeds can be treated like normal streams.  If you pass a block
to `em_run`, that block will be called with each document in the
change stream.  If you pass a `Handler` that defines `on_val` or
`on_stream_val`, that function will be called with each document in
the change stream.

If you want more granular control, there are also several changefeed
specific functions that can be defined:

* `on_initial_val` -- if you're subscribed to a changefeed that
  returns initial values (`.get.changes` and `.order_by.limit.changes`
  right now), those initial values will be passed to this function.
* `on_change` -- changes will be passed to this function.
* `on_change_error` -- sometimes the change stream includes documents
  specifying errors that don't abort the feed (e.g. if the client is
  reading too slowly and the server was forced to discard changes).
  Those will be passed to this function if it's defined.
* `on_state` -- sometimes the change stream includes documents
  specifying the state of the stream.  Those will be passed to this
  function if it's defined.

Here's our printer class with these functions defined:

```rb
class Printer < RethinkDB::Handler
  def on_open
    p :open
  end
  def on_close
    p :closed
  end
  def on_error(err)
    p [:err, err.to_s]
  end

  def on_change_error(err_str)
    p [:change_error, err_str]
  end
  def on_initial_val(val)
    p [:initial_val, val]
  end
  def on_state(state)
    p [:state, state]
  end
  def on_change(old_val, new_val)
    p [:change, old_val, new_val]
  end
end
```

#### Example 1: `.order_by.limit.changes`

```rb
# Insert some data.
r.table('test').insert([{id: 0}, {id: 1}, {id: 2}]).run($conn)
EM.run {
  # Subscribe to changes on the two smallest elements.
  r.table('test').order_by(index: 'id').limit(2).changes.em_run($conn, Printer)
}
```

Will print this:

```rb
:open
[:state, "initializing"]
[:initial_val, {"id"=>1}]
[:initial_val, {"id"=>0}]
[:state, "ready"]
```

If you then insert a new row with an `id` of 0.5:

```rb
r.table('test').insert({id: 0.5}).run($conn)
```

It will replace `{id: 1}` in the set with `{id: 0.5}`:

```rb
[:change, {"id"=>1}, {"id"=>0.5}]
```

If the table is then dropped:

```rb
r.table_drop('test').run($conn)
```

The changefeed will receive an error and be closed:
```rb
[:err, "Changefeed aborted (table unavailable).\nBacktrace:\nr.table(\"test\").changes\n^^^^^^^^^^^^^^^^^^^^^^^"]
:closed
```

**Comment by deontologician** [comment]
Is this review still going on? I would like to use this in the logstash plugins if possible

**Comment by mlucy** [comment]
The review is still going on, but you can develop off of `mlucy_em_integration` until it's done.

**Comment by mlucy** [comment]
(Er, to be clearer, `mlucy_em_integration` is a branch.)

**Comment by deontologician** [comment]
cool, thanks

**Comment by danielmewes** [comment]
I'm excited about this :clap: .

@gchpaco you mentioned earlier that it's customary in the EM world to prefix asynchronous functions with an `a`. Do you think `em_run` is fine or do you think we should rename it to `arun`?

As an outsider, I'd prefer `em_run` because it's more explicit about which framework is being used, but for users already familiar with EM things could be different.

**Comment by mlucy** [comment]
This is in next and 2.0.x .  @chipotle -- I updated the documentation comment above, it should be complete now.

**Comment by gchpaco** [comment]
EM tends to be of the `EM::Protocols::BlahBlahBlah.connect` mold, which doesn't fit the structure here (It's more like the Tornado driver with a special `.connect` and an otherwise ordinary `.run`).  Celluloid is entirely different and appears to use `.async.whatever`.

Basically, it's Ruby.  No two groups or projects can agree on any one style ;)

**Comment by danielmewes** [comment]
Fair enough. I think our current interface is fine then.
