### ISSUE TITLE
Don't error on `table.rebalance` with insufficient data

### ISSUE THREAD

**Issue by Tryneus** [rethinkdb/rethinkdb#3679]
`r.table('foo').reconfigure(shards=n, replicas=m)` will never fail due to insufficient data, but `r.table('foo').rebalance()`, which appears to perform a subset of `reconfigure`'s tasks, will error with:
 'There isn't enough data in the table to create _n_ balanced shards.'

I think this error would be better if replaced with a no-op.  It is just another error that users need to know about and handle, without much difference to the user.

**Comment by coffeemug** [comment]
:+1: for a noop (though I don't think it's urgent)

**Comment by timmaxw** [comment]
:+1: I think making this a no-op is a no-brainer.

(I guess that implies I had no brain before...)

**Comment by danielmewes** [comment]
I'm ok with that.

**Comment by mlucy** [comment]
There doesn't seem to be any contention here; planning to mark this as settled (with the interpretation that rebalancing with too little data is a noop) on Monday.

**Comment by Tryneus** [comment]
This change has been approved and merged to `next` in commit dd5fe9d, review was 2598.  Will be in release 2.0.
