### ISSUE TITLE
Offline caching, sync when connected?

### ISSUE THREAD

**Issue by kevinSuttle** [rethinkdb/rethinkdb#3680]
Is this a scenario rethinkdb supports?
http://offlinefirst.org/

**Comment by danielmewes** [comment]
Hi @kevinSuttle ,
such functionality is not currently built into RethinkDB. You'd have to implement the syncing in your application (or use a separate library/service).

We'll definitely consider adding such a feature at some point, but at the moment it's not in our main focus.

**Comment by kevinSuttle** [comment]
Good to know. Thanks.

**Comment by alimoeeny** [comment]
Just wanted to add a vote for syncing of **offline clients** which may be related to what @kevinSuttle asked for.

**Comment by kevinSuttle** [comment]
Wonder if this is like the same type of problem @rauchg was trying to solve with https://github.com/cloudup/mydb https://cloudup.com/blog/introducing-mydb

**Comment by alimoeeny** [comment]
To be clear, what I need is a way to every now and then, get an offline copy of the database (image of the database) to my clients. basically one large json blob (or a bunch of json blobs). 
Going back is (for me) just nice to have, but couchdb is more like what I need (of course I really like to use rethinkdb instead and eat my cake too).

**Comment by alimoeeny** [comment]
Thanks @spiffytech , yeah, that is exactly what I need. I am new, didn't know about it. appreciate your comment very much.

**Comment by cometta** [comment]
any plan to support client side offline sync?

**Comment by HighOnDrive** [comment]
"We'll definitely consider adding such a feature at some point", looking forward to it then :+1:
