### ISSUE TITLE
Ruby changefeeds can only be used once

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3682]
I am trying to use a `changefeed` in Ruby to get single items from it one at a time, but am getting and error:
```ruby
# table `foo` exists, but is empty
alpha = r.table('foo').get(1).changes().run()
alpha.take(1) #  [{"new_val"=>nil}]
r.table('foo').insert({'id'=>1}).run()
alpha.take(1) # RethinkDB::RqlRuntimeError: Can only iterate over a cursor once.
```

For comparison, the same thing using `.next()` in the Python driver works. And the same idea using `.each` and bailing with `break` also has the same issue.

**Comment by danielmewes** [comment]
@mlucy is this expected? Is there another way to do this that works?

**Comment by mlucy** [comment]
Our cursor class inherits from Enumerable, which doesn't implement `next`, but you can turn it into an Enumerator by calling either `cursor.to_enum` or `cursor.each` (with no arguments), and that should support `next`.  I talked about this with @larkost, and I wouldn't be opposed to making cursors support `next` by default either by returning an enumerator or implementing it ourselves.

**Comment by danielmewes** [comment]
@Tryneus has added a `next` method to Ruby cursors.
