### ISSUE TITLE
Periodic update ping sends number of machines as `char(num_machines)` binary, not as ascii

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#3691]
Noticed that in the update logs, just talked to @gchpaco about it.

We should fix that, but not worth holding the 1.16 release for it IMO.

**Comment by timmaxw** [comment]
In case anyone else is curious how this happened by accident, the culprit is the `string::string(initializer_list<char>)` constructor.

**Comment by coffeemug** [comment]
It's going to be fun writing scripts to parse out one binary character out of an ascii string :)

**Comment by gchpaco** [comment]
Herpdy derp.  Fixed in next and cherry picked into 394dcf1 for v1.16.x.

**Comment by gchpaco** [comment]
I should say, over-the-shoulder review.

**Comment by gchpaco** [comment]
> In case anyone else is curious how this happened by accident, the culprit is the string::string(initializer_list<char>) constructor.

That's C++ for you, I suppose.
