### ISSUE TITLE
Version check counts deleted servers and tables

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#3692]
In `do_check()`, `snapshot.servers` and `snapshot.rdb_namespaces` may contain entries corresponding to things that have been deleted. So instead of saying `snapshot.servers.servers.count()` we have to loop over it and count the non-deleted entries.

**Comment by gchpaco** [comment]
yeah, not for 1.6.

**Comment by VeXocide** [comment]
In CR 2612 by @gchpaco

**Comment by VeXocide** [comment]
Merged into `next` via commit 44e3cc6
