### ISSUE TITLE
[next]dryRun doesn't impact the behavior of reconfigure

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#3693]
I can set `dryRun: true`, but it will still reconfigured my table.
I get `reconfigured: 1` in the results, and one more/less shard in my case.

**Comment by timmaxw** [comment]
As of 6d13fa56d84022c7c918b81c4520a3f77404c747 `dryRun` works as expected. I created a table in the Data Explorer on a 2-node cluster and then ran `reconfigure({shards:2, replicas:1, dryRun:true})` and it returned `reconfigured:0`. How did you get your result?

**Comment by neumino** [comment]
Arg sorry, I misread the new docs :(
I was running `r.table('foo').reconfigure({shards: 2, replicas: 1}, {dryRun: true})`.

It works fine when `dryRun` is part of the first argument.
