### ISSUE TITLE
javascript API for async cursor.each

### ISSUE THREAD

**Issue by yaru22** [rethinkdb/rethinkdb#3702]
Currently, `cursor.each` has the following signature:
```js
cursor.each(function(err, row) {
  if (err) throw err;
  processRow(row);
});
```
I've encountered situations where `processRow(row)` had to run asynchronously in series, but I don't think it's possible to do that with `cursor.each()` if I'm not mistaken. Correct me if I'm wrong.
I could do what I wanted with `cursor.next()` as follows:
```js
var fetchRow = function fetchRow(err, row) {
  if (err) throw err;
  asyncFunc(function (err, result) {
    if (err) throw err;
    cursor.next(fetchRow);
  });
};
cursor.next(fetchRow);
```
However, the above feels cumbersome and I'd like if `cursor.each` accepts `done` parameter so I can do something like this:
```js
cursor.each(function (err, row, done) {
  if (err) throw err;
  asyncFunc(done);
});
```
So if `done` parameter is provided, it runs asynchronously and otherwise, it runs synchronously. Similar to how [Mocha is doing](http://mochajs.org/#asynchronous-code).

**Comment by mlucy** [comment]
That seems like a reasonable addition.  Changing the behavior based on whether the callback takes 2 or 3 arguments seems a little subtle to me, but I'm also not a JS person.

@danielmewes, is there a single person in charge of the JS driver right now?

**Comment by danielmewes** [comment]
Thank you for your suggestion @yaru22 .
@deontologician does this look reasonable to you?

**Comment by deontologician** [comment]
I'll say it doesn't look *unreasonable*, but I would want @neumino 's opinion on reasonableness

**Comment by neumino** [comment]
That seems a good idea to me, especially since I think that `next` is a low level thing that shouldn't be used if possible.

One thing you may want to add to @yaru22 suggestion, is the ability to stop the iteration by calling `done(false)`.

**Comment by ember-max** [comment]
+1 for `done`, and specifically the ability to call `done(false)` to stop `cursor.each()` iteration via an async func. however, what if you want to cancel the `cursor.each()` iteration before your callback has even been invoked (i.e., a table changefeed where nothing has changed yet) and you haven't received `done`?

out of curiosity, what is the impact of calling `cursor.close()` while an outstanding `cursor.each()` is in progress? i.e., some external event has caused you to stop wanting to listen to a particular changefeed - without any other updates, `cursor.each()` won't fire again to give you a chance to return false...

**Comment by marshall007** [comment]
> +1 for `done`, and specifically the ability to call `done(false)` to stop `cursor.each()` iteration via an async func.

@ember-max I implemented support for this in a promise-based API. See #4784. See [#4784 (comment)](https://github.com/rethinkdb/rethinkdb/pull/4784#issuecomment-142113485) for my proposal on how we could unify this functionality and support the callback-style as well.

You should be fine closing a `cursor` mid-stream. It cleans up all pending callbacks for you and (I think) ignores any further responses received for that feed until the connection is finally closed.

**Comment by ember-max** [comment]
@marshall007 Great, yeah I've been utilizing my own promise-wrapper around `cursor.each`, so seeing something formalized would be great. The issue I'm encountering is that when I invoke `cursor.close`, there's no way for me to listen for this event and terminate my promise (either with a resolve or reject).

**Comment by danielmewes** [comment]
I believe `each_async` accomplishes this now? http://rethinkdb.com/api/javascript/each_async/
