### ISSUE TITLE
Query using a simple r.js expression is more than 10x  slower than an equivalent ReQL-only query

### ISSUE THREAD

**Issue by elifarley** [rethinkdb/rethinkdb#3704]
RethinkDB 1.16.0-1
VPS with 1 GB RAM
cache size of 100 MB
~5400 documents ( loaded from a 2 MB CSV file )

r.table('en').hasFields('file_name').pluck('file_name','title','mime').merge( r.js("(function(row) {return {mime2: row.mime}; })") ) 
46 seconds

r.table('en').hasFields('file_name').pluck('file_name','title','mime').merge( function(row) {return {mime2: row('mime')}; } )
2.4 seconds

Typical document:

{
"date_created":  "735.207,84829861" ,
"date_created_1":  "735.207,84829861" ,
"file_name":  "Simple.pdf" ,
"hash":  "d61ab208f44c2b10da392cb54cafaadf4" ,
"id":  "00fa00b1-2a2c-4c86-f845-374964c01678" ,
"mime":  "application/pdf" ,
"note":  "7329,000000" ,
"notebook":  "My notes" ,
"notebook_uid":  "220,000000" ,
"size":  "8791127,000000" ,
"size_1":  "8791127,000000" ,
"source_url": "file://C:\home\file.pdf" ,
"title":  "Simple" ,
"uid":  "08f4,000000" ,
"uid_1":  "08f4,000000"
}

**Comment by mlucy** [comment]
Hi @elifarley,

I think this is expected unfortunately.  We have to communicate back and forth with v8 for JS snippets, so they're much slower than native ReQL code, especially for simple queries.

**Comment by danielmewes** [comment]
We will eventually do more profiling of the `r.js` code, though in the end it will always be slower than native ReQL for small functions.

**Comment by danielmewes** [comment]
@elifarley Now that I could test this myself with your data, there is a chance that the bad performance you've been seeing is due to https://github.com/rethinkdb/rethinkdb/issues/3757 .

Already asked this in the other thread, but how did you install RethinkDB? Did you compile from source or use a package?

**Comment by danielmewes** [comment]
... that being said the performance difference between `r.js` and the native query even when building RethinkDB from source is still roughly a factor of 10x on my system, so it might be unrelated.

**Comment by elifarley** [comment]
I've installed it from your repo.

**Comment by danielmewes** [comment]
@elifarley Ok sounds like you would be affected by #3757 then. The good news is that @AtnNn has implemented a fix for that problem and we're going to release new RethinkDB 1.16.2 binaries soon (likely some time next week). That should speed up `r.js` quite a bit, though it still won't be as fast as a native ReQL query.

**Comment by AtnNn** [comment]
#3757 was fixed in the 1.16.2 release. @elifarley have your `r.js` queries gotten any faster?

**Comment by elifarley** [comment]
Quite a bit faster indeed! Thanks!
