### ISSUE TITLE
RethinkDB make_timezone from timestamp off by an hour

### ISSUE THREAD

**Issue by Grazfather** [rethinkdb/rethinkdb#3705]
I'm trying to serialize and deserialize datetimes that come from rethink so that I can send them over rabbitmq. I noticed the following behaviour in python3:

```python
$ python3
Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 00:54:21)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> import rethinkdb as r
>>> a = datetime.datetime.now().replace(tzinfo=r.make_timezone('-07:00'))
>>> a
datetime.datetime(2015, 1, 30, 13, 12, 0, 339408, tzinfo=<rethinkdb.ast.RqlTzinfo object at 0x10073e518>)
>>> datetime.datetime.fromtimestamp(a.timestamp()).replace(tzinfo=r.make_timezone('-07:00'))
datetime.datetime(2015, 1, 30, 12, 12, 0, 339407, tzinfo=<rethinkdb.ast.RqlTzinfo object at 0x10073e5f8>)
```

Note that the time is off by an hour (and microseconds, but I think this is allowed)

**Comment by svisser** [comment]
What timezone are you in (as `.now()` depends on your local settings)?

**Comment by Grazfather** [comment]
Yes, I think the problem is that I am using `fromtimestamp` incorrectly. I am in -8, so I would expect the time, if anything, to be off by an hour in the _other_ direction.

`timestamp()` takes the tz into accounts, so when I use `fromtimestamp` I need to specify which timezone it came from.

**Comment by svisser** [comment]
Also checks the docs for `pytz` (often you can't use `replace(tzinfo=...)` to get a correct datetime): http://pytz.sourceforge.net.

**Comment by Grazfather** [comment]
Thank you!
