### ISSUE TITLE
Latest python driver thinks v1.16.0 is too low?

### ISSUE THREAD

**Issue by keighl** [rethinkdb/rethinkdb#3706]
Getting a error using trying to use the dump tool on Ubuntu 14.04 LTS. The python driver is complaining that the rethink version is too low? I installed rethink via apt-get.

```
$ rethinkdb -v
rethinkdb 1.16.0+1~0trusty (GCC 4.8.2)

$ pip list | grep rethink
rethinkdb (1.16.0.post0)

$ rethinkdb dump
Exporting to directory...
Error: Incompatible server version found, expected >= 1.16.0
Error: rethinkdb-export failed
```

Something obvious I did wrong?

**Comment by AtnNn** [comment]
I can reproduce this. I'm going to try to fix it. Thanks for the report

**Comment by svisser** [comment]
What versions of `pip` do you have? It could be that `1.16.0+1~0trusty` doesn't match the new version schema introduced in PEP 440.

**Comment by AtnNn** [comment]
The regexp that tests the version number in `_backup.py` doesn't correctly detect the version of the Ubuntu packages. I've got a possible fix that I'll try to push to pypi soon.

**Comment by keighl** [comment]
That's awesome. Thanks, @AtnNn

**Comment by AtnNn** [comment]
A new version of the driver is now available, it should fix this bug.

**Comment by keighl** [comment]
@AtnNn yep working now!
