### ISSUE TITLE
rethinkdb.stats.written_docs_total is broken

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#3713]
The `written_docs_total` field in `rethinkdb.stats` incorrectly displays 0 in the stat dumps posted in #3712. I think this is because of a perfmon name mismatch; `btree/slice.hpp` publishes a perfmon called `total_keys_set`, but `clustering/administration/stats/request.cc` looks for a perfmon called `total_keys_written`.

**Comment by Tryneus** [comment]
Fix up in review 2561.

**Comment by Tryneus** [comment]
The fix has been approved and merged to `next` in commits ff8c26b and 05d9ea5, and cherry-picked into `v1.16.x in commits 28d4870 and cdde59f.  Will be in release 1.16.1.
