### ISSUE TITLE
Web UI: Switching from Tables to Data Explorer hangs UI

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3718]
I only got this once. Switching from a table page to the Data Explorer by clicking on the Data Explorer link caused the web UI to hang, becoming unresponsive for further input.

This is the JS error:
`TypeError: _ref.destroy is not a function`

In this code:
```js
SecondaryIndexView.prototype.remove = function() {
      var _ref;
      if ((_ref = this.progress_bar) != null) {
        _ref.destroy();
      }
      return SecondaryIndexView.__super__.remove.call(this);
    };
```

**Comment by danielmewes** [comment]
I had secondary index post constructions going on

**Comment by danielmewes** [comment]
Just got this again. I think it might be a general problem whenever there are index constructions.

**Comment by danielmewes** [comment]
Assigning @deontologician

**Comment by deontologician** [comment]
In CR 2564
