### ISSUE TITLE
Approx. documents should round more aggressively

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3722]
I'm currently seeing "About 9080708" on a table in the web UI, which is not only difficult to read but also looks like a very precise number which it is not.
I think "About 9M" would be enough.
I suggest we make it round to the nearest power of thousand, that is 1-3 significant digits.

**Comment by mglukhovsky** [comment]
Rounding should work -- is this a regression?

**Comment by danielmewes** [comment]
I'm not sure. I thought we were still rounding. It might just be a setting to make it round earlier.

**Comment by deontologician** [comment]
We currently have nothing in the template or the view doing any kind of
rounding. I don't see any helpers in utils.coffee for rounding, though I'm
sure I've seen the "9M" behavior before. Will have to investigate in git to
see what it used to do

**Comment by deontologician** [comment]
OK, yeah, on
https://github.com/rethinkdb/rethinkdb/blob/v1.15.3-1/admin/static/coffee/namespaces/namespace.coffee#L186
you can see we used to round the value in the model directly. I'll add that
back in

**Comment by deontologician** [comment]
This is a pretty simple fix, I'll put it on the 1.16.x branch and backport it to next

**Comment by deontologician** [comment]
Up in CR 2563, branch is josh/3722
