### ISSUE TITLE
virtual tables do not give an initial value to a point changefeed

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3723]
The following never returns for me, implying that point changefeeds do not get an initial value:
```python
feed = r.db('rethinkdb').table('table_status').get(1).changes().run()
next(feed)
```

A disabled sub-test will shortly be available in `./test_runner polyglot/changefeeds/point`.

**Comment by larkost** [comment]
Update: It appears that this is only a problem when there is no initial value. When there is an initial value it works as expected.

**Comment by mlucy** [comment]
This is in CR 2678 by @timmaxw .

**Comment by mlucy** [comment]
This is in next.
