### ISSUE TITLE
Rethinkdb adapter for Waterline/Sails.js

### ISSUE THREAD

**Issue by listepo** [rethinkdb/rethinkdb#3727]
Please add the rethinkdb adapter for sails.js/waterline :) https://github.com/jmdobry/waterline-rethinkdb has not supported

**Comment by danielmewes** [comment]
Pinging @deontologician .
I'm not sure if we have the capacity to maintain this adapter at the moment, but it's worth considering.

@listepo Have you checked out http://thinky.io/ and http://reheat.pseudobry.com/ ? They are not written specifically for sails.js, so I'm not sure how easy they're to use with it.

**Comment by listepo** [comment]
will be difficult but thanks :) I think of something

**Comment by danielmewes** [comment]
Re-opening. @deontologician mentioned that this would be interesting to support.

**Comment by deontologician** [comment]
Or possibly https://github.com/dsincl12/sails-rethinkdb

**Comment by mwielbut** [comment]
Created a rough hook for loading [Thinky](http://thinky.io) ORM for RethinkDB into sails so you can use it instead of or in addition to Waterline.

https://www.npmjs.com/package/sails-hook-thinky

**Comment by deontologician** [comment]
@mwielbut nice!

**Comment by gutenye** [comment]
Created a simple sails-rethinkdb adapter, Sails Query Syntax is only [20% compilation](https://github.com/gutenye/sails-rethinkdb/blob/master/lib/query.js), otherwise it's good to use. 

https://github.com/gutenye/sails-rethinkdb

**Comment by danielmewes** [comment]
Cool, thanks for sharing @gutenye

**Comment by thelinuxlich** [comment]
@srh I think this framework and ORM is kinda dead and not worth the effort anymore
