### ISSUE TITLE
virtual tables giving odd result for initial value on point changefeeds

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3732]
When a record is deleted, and then another record created with the same id any point changefeeds created immediacy after will give a bad answer for the initial record in that changefeed. This is related to issue #3723, and might well be another result of the same cause.

```python
r.table('bob').insert({'id':1, 'version':1}).run(conn)
r.table('bob').get(1).delete().run(conn)

r.table.insert({'id':1, 'version':2}).run(conn)
feed = self.table.get(1).changes().run(conn2)

feed.next() # gets {'new_val': None} rather than  {'new_val': {'version': 2, 'id': 1}}
```

**Comment by larkost** [comment]
I have added a test for this in CR 2568 from branch `larkost/3732-virtual-tables-point-changefeeds`.

**Comment by mlucy** [comment]
What does "virtual tables" mean here?

**Comment by danielmewes** [comment]
I believe @larkost was using `r.db('rethinkdb').table('_debug_scratch')`

**Comment by mlucy** [comment]
@timmaxw -- do you have any insight into this?  Is there a chance that the changefeed is reading an old value out of the `_debug_scratch` table?

**Comment by timmaxw** [comment]
@larkost, I think there's a bug in `regression/issue_3732.test`. You have this line:
```python
feed = utils.NextWithTimeout(self.table.get(1).​changes().run(feedConn), timeout=0.1)
```
I think it should be `table` instead of `self.table`. As far as I can tell, it's opening the changefeed on the real table after writing to the artificial table. So this explains why the changefeed returns `{'new_val': None}`.

However, when I fix this, I get a different error:
```
.E
======================================================================
ERROR: test_virtual (__main__.Issue3732)
Inital value should always exist, even if preceded by a delete on virutal tables
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../regression/issue_3732.test", line 47, in test_virtual
    self.helper(table=self.r.db('rethinkdb').table('_debug_scratch'))
  File "../regression/issue_3732.test", line 40, in helper
    self.assertEqual(next(feed), {'new_val':{'id':1, 'version':2}})
  File "/home/tim/rethinkdb/test/regression/../common/utils.py", line 599, in next
    raise Exception('Timed out waiting %d seconds for next item' % self.timeout)
Exception: Timed out waiting 0 seconds for next item

----------------------------------------------------------------------
Ran 2 tests in 4.831s

FAILED (errors=1)
```
This is clearly caused by #3723. So I think this issue can be closed.

**Comment by larkost** [comment]
I committed this before seeing @timmaxw's comment. He is correct, so I have removed it with 011ee9a
