### ISSUE TITLE
Will changefeeds eventually support `.count()` queries?

### ISSUE THREAD

**Issue by marshall007** [rethinkdb/rethinkdb#3735]
I understand the existing limitations of changefeeds in regards to commands that consume the entire stream, but is support for such queries on the roadmap?

In one of our applications we have long-running jobs that are started in a separate process and insert documents as they go. After starting one of these jobs, I need to notify clients of its progress (from the main process) by monitoring the number of documents that have been inserted thus far.

```js
r.table('job_results').getAll(job_id, { index: 'job_id' }).count().changes()
```

I currently handle this by polling and was looking forward to not having to do that anymore after 1.16. As a workaround I will probably watch for changes on the `.getAll(...)` and manually increment a counter when I see new values.

**Comment by mlucy** [comment]
> is support for such queries on the roadmap?

Yes, it is!  It isn't scheduled for a release yet, but long-term you should be able to call `changes` on any reduction (so `.count.changes`, `.sum.changes`, `.avg.changes`, and reversible instances of `.reduce.changes`).

**Comment by danielmewes** [comment]
This is part of https://github.com/rethinkdb/rethinkdb/issues/1118
