### ISSUE TITLE
We send responses in three individual serialized writes

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3744]
From `json_protocol_t::send_response()`:
```
conn->write(&token, sizeof(token), interruptor);
conn->write(&size, sizeof(size), interruptor);
conn->write(str.data(), size, interruptor);
```

As far as I can see each call to `conn->write()` waits until that piece of data has actually been transmitted over the network. So this is pretty horrible in terms of latency and overhead.

We should try to merge all three writes together.

**Comment by danielmewes** [comment]
On YCSB's read-only workload with 64 concurrent clients, fixing this for the protobuf protocol gives us 10% more throughput (on localhost, probably more if the server was on an actual network).

The protocol buffer protocol only uses two writes, not three like the JSON protocol so I expect the difference to be even higher there.

**Comment by danielmewes** [comment]
A fix is in CR 2578

**Comment by danielmewes** [comment]
Merged into `next` bb0fd8a89eb8b5b2635607ed85a1d0371e1d45f6

**Comment by neumino** [comment]
@danielmewes -- I think one of the reason the messages were split is that if you pack everything in one protocol buffer message, and fails to parse it, you don't know which query is failing as you do not have the token.

That may not apply in the server though, but it may be worth checking (sorry for bumping in late).

**Comment by danielmewes** [comment]
@neumino I don't think that has anything to do with this. This shouldn't have any impact on how things are parsed.

In the protocol buffer implementation we had the problem that the token was part of the message itself, which would lead to what you describe. This is unrelated to how many TCP frames we use to send the message though.
