### ISSUE TITLE
On startup: Cannot write directory removal messages to log

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3746]
Every time I start a server from the current v1.16.x I'm getting these two messages:
```
Recursively removing directory rethinkdb_data/tmp
Previous message may not have been written to the log file (cannot open or find log file).
In recursion: removing file rethinkdb_data/tmp
Previous message may not have been written to the log file (cannot open or find log file).
```

This is of course a consequence of https://github.com/rethinkdb/rethinkdb/issues/1780 .
The log is actually working fine, but maybe these messages get printed before it's ready?

Usually the `tmp` directory should be empty, and I'm not sure why we're recreating it on every startup. We could change the startup code so that it checks if the `tmp` directory exists *and is empty* (we already have a method `check_dir_emptiness(base_path)` in directory_lock.cc). If the directory exists but is not empty, it recreates it just like it does now. If it exists and is empty, it does nothing, hence avoiding the warning message in the usual case.

Marking as `pr:high` because it's a regression in v1.16.x.

**Comment by gchpaco** [comment]
Problem appears to be that we do `recreate_temporary_directory` before `initialize_logfile`.  Checking to see if there's any good reason for that.

**Comment by danielmewes** [comment]
I think it would be better to not have that message at all by changing the code as I had suggested above.

**Comment by gchpaco** [comment]
There are two issues.
1. We should not be logging before we initialize logging.  Logging should happen as soon as possible.  So I want to move the ordering regardless.
2. We should probably not do the dumb thing with `/tmp`, which I'll do separately.

**Comment by gchpaco** [comment]
CR 2586.
