### ISSUE TITLE
Make `.orderby.limit` changefeed tests into real tests.

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3749]
I have a script that tests `.orderby.limit` changefeeds; I should sit down with Karl and make it into a test that gets run by our test system.

**Comment by VeXocide** [comment]
In CR 2737 by @larkost

**Comment by VeXocide** [comment]
Merged into `next` via commit 3a67d57f734b155e5800d0fad23685790ae570d0a and 2e5eeaab0fa9a43c39a74d2535d3054a88c11481, and into `v2.0.x` via commit 58f98f39a04defed064e73d9bd8c2321ebf0333c and 8f6644441808c07f55d34a6a27727b843ae93c72
