### ISSUE TITLE
Add default dicts.

### ISSUE THREAD

**Issue by jdoliner** [rethinkdb/rethinkdb#375]
Along with dealing with missing attributes when the arise it would be very useful to specify ahead of time what the default value of a dictionary is. This is particularly useful in examples where there is a sensible default value for all the entries in it. For example suppose you had a schema where users made posts and these posts could have various tags on them. You want to store on each user the number of posts made with each tag on them. There could be a huge (and always growing) number of tags with each users posts only representing a small subset of them. Having a default dict lets your syntax look like this:

```
users.insert({"name" : "foo", "tag_counts": default_dict(0)})
```

And now you never need to worry about writing default again. When you want to get the users with fewer than 10 posts with a certain tag you just do:

```
users.filter(lambda x: x["tag_counts"][tag] < 10)
```

In speaking with @mlucy about this he had some worries about how this would be represented in languages that don't have a default dict type built in (Python and Ruby do, JS I believe doesn't). He was pretty happy with the solution of adding in a special purpose field on dicts: "**default**" is used as the default for the dictionary. If I recall correctly he seemed to really like this and I'm pretty okay with it myself.

**Comment by elifarley** [comment]
Looks like this bears some resemblance to #3963

**Comment by srh** [comment]
Obviously we're not going to do this.  Certainly we're not going to specify how all the functions operating on dicts behave, argue about it, implement it, and then put that in the documentation.  And it's probably a bad idea in general.  Closing.
