### ISSUE TITLE
UI bug on Dashboard

### ISSUE THREAD

**Issue by joaojeronimo** [rethinkdb/rethinkdb#3751]
Hey guys, I'm running `1.16.0-1` and noticed the Y axis got weird this time, as you can see in the picture it went from 20k to 20k, passing through 00k, I think it is in fact 100k and 120k over there but there's not enough space to display the first character, `1`.

![possible ui bug](https://dl.dropboxusercontent.com/u/463581/possiblebug.png)

**Comment by coffeemug** [comment]
Ouch, we should fix that margin. Evidently the server's performance improved faster than the quality of CSS :smile:

**Comment by deontologician** [comment]
OK, @coffeemug, I've tracked this down to something called "Slava's sensible chart version"...

**Comment by coffeemug** [comment]
oh-oh :smile: 

There are *much* better chart projects these days for what we need done (the one @segphault used for his demo seems really good). I think we should drop my fork of cubism at some point and use that instead.

**Comment by mglukhovsky** [comment]
@coffeemug: that's planned in #3720. Epoch seems like a good alternative.

**Comment by deontologician** [comment]
Up in CR 2644 by @danielmewes
