### ISSUE TITLE
Determine conflict strategy for inserts with a function

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#3753]
I'm inserting in batches with conflict: replace, but I stumbled upon a case where I'd need to change the strategy to error if the field status of my data is false. Without the possibility to do this dynamically I will have to avoid batch inserting for this specific table.

**Comment by danielmewes** [comment]
Good idea. We should support it in the same way as https://github.com/rethinkdb/rethinkdb/issues/873 .

**Comment by marshall007** [comment]
Just ran into this as well. I'm basically looking to do a `replace` while preserving a couple fields if they don't exist in the document being inserted. For example:

```js
table.insert(values, {
  conflict: function (old_val, new_val) {
    return old_val.pluck('foo', 'bar').merge(new_val);
  }
})
```

**Comment by mlucy** [comment]
I like the idea of passing the conflict resolution function as a `conflict` optarg.

**Comment by mlucy** [comment]
We should also consider making the format be `function (id, old_val, new_val)` for consistency with #873.

**Comment by danielmewes** [comment]
@mlucy Would the `id` be the primary key of the document? This seems somewhat different from #873 where the first argument would be the field name. I don't think it makes sense to add the `id` here.

**Comment by mlucy** [comment]
Bumping to subsequent; we #873 got bumped and we should settle this at the same time (hopefully for 2.2).

**Comment by thelinuxlich** [comment]
Is this happening on 2.1 or 2.2? Now I need to insert in batches with conflict = update and there is a field that could be missing when updating that I would like to add(but only if it doesn't exist). Are there any alternatives?

**Comment by danielmewes** [comment]
@thelinuxlich This is not happening for 2.1, hopefully for 2.2. Sorry.

Assuming that you need this to be atomic, I'm not sure if there's a work-around at the moment.
@mlucy do you have any idea for @thelinuxlich 's use case?

**Comment by mlucy** [comment]
I don't think there's any way to do this while preserving the performance benefits of batched inserts in 2.0 or 2.1.  Hopefully we can get this in for 2.2.

**Comment by mlucy** [comment]
Bumping to 2.2 polish.

**Comment by thelinuxlich** [comment]
Ok, thanks!

**Comment by danielmewes** [comment]
http://stackoverflow.com/questions/31634640/rethinkdb-atomic-operations/31640295 would have benefited from this as well.

I think the function we use here should be different from what we would use for `merge` (#873). In case of `insert`, the function shouldn't be called for individual fields, but on the whole document I think. The signature that @mlucy suggested here https://github.com/rethinkdb/rethinkdb/issues/3753#issuecomment-95019001 looks reasonable to me (that is `function (id, old_val, new_val)`).

**Comment by danielmewes** [comment]
We should also think about the question of atomicity. I can think of two options:
1. Require the conflict function to be atomic, fail if it's not
2. Add a `non_atomic` optarg to `insert`, similar to the one for `update` and `replace`. Require it to be set to `true` if the conflict function is not atomic.

I feel like a non-atomic upsert is kind of pointless, so option 1 might be more reasonable (and easier).

**Comment by danielmewes** [comment]
Ok, so what about this syntax?
```
.insert(documents, {conflict: function(id, old_val, new_val) { ... } })
```

The conflict resolution function must be atomic.

If the function returns `old_val`, the document will not be changed. If the function returns `null`, the document will be deleted (this is consistent with `replace`). Otherwise, the document will be updated to whatever value the function returns.

**Comment by marshall007** [comment]
:+1:

The option to return `null` also solves my use-case for #4410, but in a much more elegant way.

**Comment by thelinuxlich** [comment]
Nice!

**Comment by mlucy** [comment]
That looks good to me, except I think we shouldn't pass `id` to the function since you can get that out of `old_val` or `new_val` pretty easily.

**Comment by danielmewes** [comment]
@mlucy I added the ID argument because of your comment here https://github.com/rethinkdb/rethinkdb/issues/3753#issuecomment-95019001 .
I don't feel strongly about it. You are probably right that it's rarely useful and when it is, it's easy to come by. So :+1: for just `function(old_val, new_val)`.

@marshall007 I'm not sure if this actually solves #4410. The way I imagined the conflict function to work is that it would only be called when there is a conflict. For #4410, you would probably need the conflict function to be called for *every* insert, even if no previous document exists, don't you?

Theoretically we could make it work like that I suppose. That is if no previous document exists, the function `function(old_val, new_val)` is called with `old_val = null`. If there is a conflict, the function is called with both `old_val` and `new_val` set. In the first case you could then return `null` to make the insert a no-op, which would address your use case from #4410.
However I think that this is less convenient to use in many other cases, since you now explicitly have to distinguish between an actual conflict and a non-conflicting insert inside of the function.

**Comment by thelinuxlich** [comment]
In my opinion the function should run only when conflicting, if you need to transform the data for every insert you can already do it before inserting with ReQL existing features

**Comment by mlucy** [comment]
Oh, that @mlucy actually makes a pretty good point.  I retract my objection; I think `id, new_val, old_val` is probably better.

**Comment by marshall007** [comment]
@danielmewes oops, sorry. At first glance I was thinking (as you just said) that the callback would be fired for every document with `old_val = null` in the case of new documents. It's definitely the cleanest solution to #4410 we've considered, but I think I agree. It's not worth making the more typical cases less convenient.

**Comment by danielmewes** [comment]
Looks like we agree on
```js
.insert(documents, {conflict: function(id, old_val, new_val) { ... } })
```

where the conflict function is only called when there actually is a conflict.
Marking settled.

**Comment by thelinuxlich** [comment]
Another very good use case for this feature would be when you save timestamps for document creation and when replacing in batches, you want to drop documents which have a older timestamp than the document to be replaced, thus guaranteeing some kind of ordering.

**Comment by danielmewes** [comment]
@thelinuxlich Very interesting use case!

**Comment by thelinuxlich** [comment]
I found another use case, when you want to limit the key quantity of a embedded object, very useful.

**Comment by marshall007** [comment]
@thelinuxlich what do you mean? Can you give an example where that's useful?

**Comment by thelinuxlich** [comment]
@marshall007 when you let the user save N fields inside a embedded object but you want to limit the max quantity of fields. An example from my code(limiiting to 30 fields):

```
r.table("attributes").get(item.id).replace(row => {
    return r.branch(row.eq(null),
        item, {
            id: item.id,
            client_id: item.client_id,
            visitor_id: item.visitor_id,
            fields: r.branch(row("fields").keys().setUnion(r(item.fields)).count().gt(30),
                row("fields").merge(r(item.fields).pluck(row("fields").keys().setIntersection(r(item.fields).keys()))),
                row("fields").merge(item.fields)
            )
        }
    );
}, {
    durability: "soft"
})
```

**Comment by nighelles** [comment]
This was in review #2523.

**Comment by nighelles** [comment]
This is in next.
