### ISSUE TITLE
Add support for parallel query execution in Python and JS

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3754]
This requires bumping the protocol version to `V0_4` and then testing that the driver can actually handle queries being executed in parallel.  (This has already been done in Ruby.)

A few good things to test:
* Test that you can run queries while waiting on the result of a changefeed (e.g. during prefetching).
* Test that you can run queries while a big noreply write is happening.
* Check that you can close a cursor while a request for a batch is outstanding.

**Comment by danielmewes** [comment]
There could be a bit of overlap with what @gchpaco is doing for https://github.com/rethinkdb/rethinkdb/issues/2622 and https://github.com/rethinkdb/rethinkdb/issues/3678.

That being said this one should be much simpler and we shouldn't wait for those to be complete before making this change in the synchronous connection classes.

**Comment by danielmewes** [comment]
I might take a shot at this later. It's hopefully as simple as bumping the version number.

**Comment by danielmewes** [comment]
In CR 2667
Seems to be working fine without further driver changes.

**Comment by danielmewes** [comment]
This is in `next` as of https://github.com/rethinkdb/rethinkdb/commit/a9459831e6ad33ca491cff5c64d642786a471ad6
