### ISSUE TITLE
More statistics functions

### ISSUE THREAD

**Issue by elifarley** [rethinkdb/rethinkdb#3769]
I hope this doesn't constitute feature bloat, but I think adding the functions below would make things easier for developers:

pvariance           Population variance of data.
variance            Sample variance of data.
pstdev              Population standard deviation of data.
stdev               Sample standard deviation of data.

**Comment by danielmewes** [comment]
Hi @elifarley , thank you for your suggestion.
Generally I think this would be a useful feature, but probably not at the top of our priority list at the moment.

Does anyone know if there's a single-pass algorithm for computing the variance without knowing the mean ahead of time, and which doesn't require O(n) space?

That would make it much easier to fit into our existing query language.
A two-pass algorithm would be more difficult to apply, since data might change underneath.

**Comment by timmaxw** [comment]
Yes, variance can be computed in one pass:
```python
sum_vals = 0
sum_squares = 0
count = 0
for value in stream:
    sum_vals += value
    sum_squares += value**2
    count += 1
variance = (sum_squares - sum_vals**2) / count
```

**Comment by danielmewes** [comment]
@timmaxw maybe I'm wrong, but that doesn't seem right.

Assume m is the mean, and n the number of samples (assuming population variance):
```
v = 1/n sum (x_i - m)^2
  = 1/n sum [(x_i)^2 - 2mx_i + m^2]
  = 1/n sum [(x_i)^2 - 2mx_i] + m^2
```

While if I'm not mistaken, your algorithm comes down to
```
v = 1/n [sum (x_i)^2] - m^2
```
which is looks different.

**Comment by danielmewes** [comment]
Wikipedia has a section on it though, so it's definitely possible:
http://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Online_algorithm

**Comment by danielmewes** [comment]
@timmaxw Oh never mind, your algorithm is correct. The derivation of your formula is shown here http://www.strchr.com/standard_deviation_in_one_pass

**Comment by timmaxw** [comment]
Apparently the algorithm I proposed is numerically unstable, so we should use the one on Wikipedia instead.

**Comment by elifarley** [comment]
Here's a ReQL to compute the sample standard deviation, adapted from https://gist.github.com/Pyrolistical/8139958

```
r.table('t').group(r.row['G']).map(r.row['value']).map(lambda x: {
  'count': 1,
  'sum': x,
  'min': x,
  'max': x,
  'diff': 0 # M2,n:  sum((val-mean)^2)
}) \
.reduce(lambda a, b: {
  'count': r.add(a['count'], b['count']),
  'sum': r.add(a['sum'], b['sum']),
  'min': r.branch(a['min'].lt(b['min']), a['min'], b['min']),
  'max': r.branch(a['max'].gt(b['max']), a['max'], b['max']),

  # See https://gist.github.com/Pyrolistical/8139958
  # temp helpers
  # delta: a.sum/a.count - b.sum/b.count; // a.mean - b.mean
  # weight: a.count * b.count / (a.count + b.count)

  # diff: a.diff + b.diff + delta * delta * weight
  'diff': r.add(
    a['diff'],
	b['diff'],
	r.mul(
	  r.sub(a['sum'].div(a['count']), b['sum'].div(b['count'])),
	  r.sub(a['sum'].div(a['count']), b['sum'].div(b['count'])),
	  r.div(a['count'].mul(b['count']), a['count'].add(b['count']))
	  )
	)
}) \
.ungroup().map(lambda g: {
  'G': g['group'],
  'count': g['reduction']['count'],
  'sum': g['reduction']['sum'],
  'min': g['reduction']['min'],
  'max': g['reduction']['max'],
  's2': r.branch(g['reduction']['count'].gt(1), r.div(g['reduction']['diff'], g['reduction']['count'].sub(1)), 0)
}).merge(r.js('(function(x){ \
  return { s2: Math.sqrt(x.s2) } \
})')).merge(lambda d: {
  'avg': r.div(d['sum'], d['count'])
})
```

**Comment by danielmewes** [comment]
Very cool query @elifarley !

As mentioned on IRC, you can use `r.do` for introducing variables. See http://rethinkdb.com/api/javascript/do/

**Comment by elifarley** [comment]
Here's an updated version, using r.do:

```
r.table('t').group(r.row['G']).map(r.row['value']).map(lambda x: {
  'count': 1,
  'sum': x,
  'min': x,
  'max': x,
  'diff': 0 # M2,n:  sum((val-mean)^2)
}) \
.reduce(lambda a, b: {
  'count': r.add(a['count'], b['count']),
  'sum': r.add(a['sum'], b['sum']),
  'min': r.branch(a['min'].lt(b['min']), a['min'], b['min']),
  'max': r.branch(a['max'].gt(b['max']), a['max'], b['max']),

  # See https://gist.github.com/Pyrolistical/8139958
  # diff: a.diff + b.diff + delta * delta * weight
  'diff': r.add(
    a['diff'],
	b['diff'],
	r.do(
      # temp helpers
      # delta: a.sum/a.count - b.sum/b.count; // a.mean - b.mean
      # weight: a.count * b.count / (a.count + b.count)
	  r.sub(a['sum'].div(a['count']), b['sum'].div(b['count'])),
	  r.div(a['count'].mul(b['count']), a['count'].add(b['count'])),
	  lambda avgdelta, weight: r.mul(avgdelta, avgdelta, weight)
	)
  )
}) \
.ungroup().map(lambda g: {
  'G': g['group'],
  'count': g['reduction']['count'],
  'sum': g['reduction']['sum'],
  'min': g['reduction']['min'],
  'max': g['reduction']['max'],
  's2': r.do(
    r.branch(g['reduction']['count'].gt(1), r.div(g['reduction']['diff'], g['reduction']['count'].sub(1)), 0),
    r.js('(function(x){ return Math.sqrt(x) })')
  )
}).merge(lambda d: {
  'avg': r.div(d['sum'], d['count'])
})
```

**Comment by untra** [comment]
I hate to necropost, but I was told to suggest my statistics feature here. :smile: 
A convenient statistics feature to have would be something like an arithmetic mode.

`r.expr([1,2,2,2,3,3]).mode()`

`mode()` would be invoked similar to how `avg()` is currently invoked, and have additional options for dealing with funky, bi-modal datasets. At the moment, If I want to take an arithmetic mode of a dataset, the following query gets the job done:
`r.expr([1,2,2,2,3,3]).group(r.row).count().ungroup().orderBy('reduction').nth(-1)('group')`

This is fine at the moment, but as an aggregation call I think `mode()` would be a lot terser.

Cheers!
