### ISSUE TITLE
OS X "Uninstall RethinkDB" script is out of date

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#3773]
It complains that

```
rmdir: usr/local/share/rethinkdb/web: No such file or directory
```

It looks like I forgot to update it with #1093.

It also suspiciously acts as if it was trying to delete `usr`:

```
rmdir: usr: Directory not empty
```

**Comment by AtnNn** [comment]
This seems to happen when some of the files from an older install of RethinkDB have already been deleted but are still listed by `pkgutil --files rethinkdb`.

**Comment by larkost** [comment]
We don't generally have to keep the uninstall script up-to-date. Using `pkgutil` generally gets us around that. The only place where this would be an issue is in things like #4507 where we might have script-installed files (symlinks).

The reason that it tries (always unsuccessfully) to delete the given folder is that we actually have `/usr`, `/usr/local`, and `/usr/local/bin` in our package. In most cases we don't create them, but they do remain in our pkg receipt. This is fairly easy to correct by using `pkgbuild --install-location`, and I will be submitting a change for that.

However, we have to make the uninstall script work with existing installed packages, and doing so without trying to remove those folders is going to be a little trickier. We should still use an AppleScript, as that makes authentication really easy, but it will probably involve adding a Python script that that calls to do the heavier lifting.

**Comment by larkost** [comment]
I have a solution to this in branch `larkost/#3773-mac-uninstall-script`. I managed to avoid going to Python and it does everything in a mixture of AppleScript and bash. I will test that I have not broken anything on the-shadow and then put this up for review on Monday.

**Comment by larkost** [comment]
Up for review with CR 3086.

**Comment by larkost** [comment]
This has been committed to `next` with ffd7d8b.
