### ISSUE TITLE
Bundle import-export dep with distributable

### ISSUE THREAD

**Issue by kofalt** [rethinkdb/rethinkdb#3784]
While running `rethinkdb restore example.tar.gz`:

```text
Error: Incompatible server version found, expected >= 1.16.0
Error: rethinkdb-import failed
```

In this case, the failure occured because one particular developer trying to use our data set happened to run `sudo pip install rethinkdb` a few days later than her colleagues :( 

I can sympathize with not wanting to support multiple major versions in an import script, but it would be really nice to be able to import & export data from a ~17 day old version of the software, even if there's a few bugs in the script :D

Would it be possible to have `rethinkdb dump` & `rethinkdb restore` rely on a bundled version of the python library, so as to avoid the "suddenly-I-can't" problem? 

I can also sympathize with possibly wanting to patch an import/export script separately from the main database product itself. How about a non-default option flag to use the vendored python lib?

**Comment by danielmewes** [comment]
Hi @kofalt, sorry for the inconvenience. This is indeed annoying.

We already have an issue for this https://github.com/rethinkdb/rethinkdb/issues/2080, so I'm going to close this one but will bump the other one.
