### ISSUE TITLE
Rethinkdb connection is not independent of library location

### ISSUE THREAD

**Issue by kmcgrady** [rethinkdb/rethinkdb#3796]
We have encountered a situation where we have the following structure.
* We have multiple web services that touch rethinkdb
* We wanted to create a universal middleware that ensures a connection to the database. We created a library which given the configuration, makes the connection and ensures it's provided in the request.
* Each web service, loads this library and uses it to ensure the connection. It then loads rethinkdb to run queries on the given connection.

This caused an error where the connection was not open, though it clearly was. I realized this is because the connection was created by our library's rethinkdb library, where our web services makes query on the connection using their own rethinkdb library. They both use the same version of rethinkdb. It seems that the connection object should be independent and run on any rethinkdb library (assuming they are the same version at least). We were able to create a workaround, but I figured I would mention it here. Thanks!

**Comment by danielmewes** [comment]
Hi @kmcgrady ,
which driver are you using for this? The node driver, Python, Ruby?

Could you post a code snippet to make it clearer what's happening? I'm not entirely sure I understand what's going on yet. So the middleware opens the connection through `r.connect` right? 
When you say that the web service "loads rethinkdb", you mean that it loads the rethinkdb driver?

What's the exact error message you're getting when the connection is claimed to not be open? Do you get a backtrace with the error?

**Comment by kmcgrady** [comment]
Sure, We use the node driver. We load using `r.connect`. And yes I mean the rethinkdb driver.

In our library:
```coffeescript
r = require 'rethinkdb'

module.exports = class RethinkDb
  constructor: (@host, @port) ->
    @connection = null

  @r: r

  getRethinkConnection: (callback) ->
    return callback null, @connection if @connection

    r.connect {@host, @port}, (err, conn) =>
      return callback err if err

      conn.on 'close', =>
        @connection = null

      @connection = conn
      callback null, conn

  ensureConnectionMiddleware: ->
    (req, res, next) =>
      @getRethinkConnection (err, conn) ->
        return next err if err

        req.rethinkConnection = conn
        next()
```

In our webservice (the host, port, and query is irrelevant):
```coffeescript
RethinkDb = require 'library/rethinkdb'
r = require 'rethinkdb'

db = new RethinkDb host, port
ensureRethink = db.ensureRethinkConnection()

exports.routes = (app) ->
  app.get '/foo', ensureRethink, (req, res, next) ->
    r.db('foo').query().run(req.rethinkConnection, next)
```

I can tell you, that `req.rethinkConnection` is valid AND open, but we get this error

```
Possibly unhandled RqlDriverError: First argument to `run` must be an open connection.
  at new RqlDriverError (/home/vagrant/deploy/webservice/node_modules/rethinkdb/errors.js:14:13)
  at Get.TermBase.run (/home/vagrant/deploy/webservice/node_modules/rethinkdb/ast.js:135:15)
From previous event:
  at Get.TermBase.run (/home/vagrant/deploy/webservice/node_modules/rethinkdb/ast.js:142:16)
  at /home/vagrant/deploy/webservice/lib/controllers/push_failures.coffee:21:20, <js>:26:80
  at callbacks (/home/vagrant/deploy/webservice/node_modules/express/lib/router/index.js:160:37)
  at /home/vagrant/deploy/webservice/node_modules/library/rethinkdb.coffee:27:9, <js>:43:18
  at /home/vagrant/deploy/webservice/node_modules/library/rethinkdb.coffee:19:7, <js>:31:16
  at TcpConnection.<anonymous> (/home/vagrant/deploy/webservice/node_modules/library/node_modules/rethinkdb/net.js:86:16)
  at TcpConnection.g (events.js:180:16)
  at TcpConnection.emit (events.js:92:17)
  at Socket.handshake_callback (/home/vagrant/deploy/webservice/node_modules/library/node_modules/rethinkdb/net.js:525:23)
  at Socket.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:764:14)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:426:10)
  at emitReadable (_stream_readable.js:422:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:528:21)
```

Instead, we need to do the following:

```coffeescript
exports.routes = (app) ->
  app.get '/foo', ensureRethink, (req, res, next) ->
    RethinkDb.r.db('foo').query().run(req.rethinkConnection, next)
```
where we refer to the rethinkdb driver loaded in our library.

**Comment by danielmewes** [comment]
Thanks for the code and example @kmcgrady .

This is probably because we check `net.isConnection` on the connection parameter which checks that the connection argument is an instance of a specific `Connection` class.
So if the driver is imported twice, the classes won't match and the `instanceof` will fail.

@deontologician do you know if there's a standard way to avoid such issues?

An easy (but slightly hacky) work-around would be to not use `instanceof` but instead have a special magic value field in the `Connection` that we can test for.

**Comment by AtnNn** [comment]
This looks related to #3263.

The RethinkDB driver checks that the connection it is given is an instance of `Connection`. If you've loaded two different drivers, the `Connection` class will not be the same in both, and the check will fail with the error `RqlDriverError: First argument to `run` must be an open connection`.

If you have multiple instances instance of the rethinkdb driver in your `node_modules` tree, you can perhaps use [peer dependencies](http://blog.nodejs.org/2013/02/07/peer-dependencies/) to solve the issue.

**Comment by marshall007** [comment]
You could try [`npm dedupe`](https://docs.npmjs.com/cli/dedupe) to flatten out the dependency tree so that each web service references the same package.

This will become the default behavior in `npm@3.0` as mentioned in [this blog post](http://blog.npmjs.org/post/110924823920/npm-weekly-5), so it shouldn't be an issue too much longer!

**Comment by deontologician** [comment]
You could do a string comparison, but in this case, I think it's a legit error. You wouldn't want to accidentally use two different versions of the driver and not realize it.

**Comment by danielmewes** [comment]
@marshall007 Thanks for chiming in!
@kmcgrady Can you try if `npm dedupe` solves the issue for you?

**Comment by kmcgrady** [comment]
@danielmewes Yes. It looks like `npm dedupe` works for me. Thanks for looking into it.

**Comment by danielmewes** [comment]
Ok, glad @marshall007's tip solved the issue. I'm going to close this as a dup then, since we already have #3263 open.

**Comment by eeerrrttty** [comment]
Here, i still get the error even after dedupe.

My node_modules have two directories:

bluebird and rethinkDB

My system is debian 9, got many problems to install.
