### ISSUE TITLE
Shouldn't r.expr() supersede r.literal()?

### ISSUE THREAD

**Issue by stuartpb** [rethinkdb/rethinkdb#3797]
In the context of a `merge`, when encountering a `r.expr` value, it would seem like that value should be treated literally. So why the extra `r.literal`?

**Comment by AtnNn** [comment]
@stuartpb `r.expr

**Comment by AtnNn** [comment]
@stuartpb `r.expr` is not a ReQL term, it is a client-side operation that turns a value into a ReQL expression. The server sees no difference between queries with `r.expr` and queries without. For example, these three expressions generate identical ReQL queries: `r.expr(1).add(2)`, `r.expr(1).add(r.expr(2))` and `r.add(1,2)`.

However `r.literal` is a ReQL term that is sent to the server and used by `merge`.

**Comment by stuartpb** [comment]
What reason does `r.expr` exist for? Is it just to wrap native objects for chaining `r` methods from them?

**Comment by timmaxw** [comment]
@stuartpb: Yes, that's the main reason for it.

**Comment by stuartpb** [comment]
What are the others?

**Comment by timmaxw** [comment]
I don't know of any other reasons; it's possible that's the only reason. But there might be something I'm not thinking of.

**Comment by mlucy** [comment]
The only two reasons I can think of are to allow chaining and to make operator overloading work in some languages.
