### ISSUE TITLE
When using .add() with a string and a number, automatically coerce the number to string

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#3800]
r(1).add("1") // "11", like JS behavior

or have a special method .concat()?

**Comment by danielmewes** [comment]
This sounds very reasonable to me. We will include this in the next RQL_proposal discussion period.

**Comment by coffeemug** [comment]
I personally don't think it's a good idea. For example, should the value here be `2` or `11`? What about `r('1').add(1)`?

I think people should coerce types explicitly.

**Comment by deontologician** [comment]
I think coercion of numbers to strings in javascript is a huge mis-feature that we shouldn't replicate. Having a string formatting term would be better in my opinion

**Comment by mlucy** [comment]
I don't think we should do this, personally.  I second what @deontologician said about adding a string formatting command.

**Comment by danielmewes** [comment]
Ok I can see that supporting this can be dangerous.
I think having a special `concat` term would be reasonable generally, but on the other hand the difference between that term and `add` would be difficult to explain since it's so small. So in the end I think that would be a bad idea as well.

I don't understand how a string formatting term is related to this though? You can already coerce the number to a string.

**Comment by deontologician** [comment]
Because usually the reason you'd want to take advantage of auto-coercion is in code like:

```
r.expr("I have").add(x).add(" cookies and ").add(y).add(" brownies")
```

where coercions would be really verbose.

**Comment by deontologician** [comment]
something like:

```
r.format("I have {} cookies and {} brownies", x, y)
```

would be much nicer

**Comment by danielmewes** [comment]
I see, thanks for explaining.
@thelinuxlich is the use case you had for this originally something that would be addressed by a `format` term?

**Comment by deontologician** [comment]
For posterity, #3353 is the string formatting issue

**Comment by thelinuxlich** [comment]
Yes, r.format would be nice!

**Comment by mlucy** [comment]
@danielmewes, could we close this in favor of #3353?

**Comment by danielmewes** [comment]
I'd like to wait until the end of the ReQL discussion period on Monday. I'll close it then.

**Comment by danielmewes** [comment]
Closing. We'll later implement a formatting term instead.
