### ISSUE TITLE
Batch size too large for batched writes

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3806]
1. Run a write such as `r.table(...).update({a: "A"})` on a sufficiently large table, ideally with somewhat large documents and small primary keys.
2. Watch the QPS plot in the web UI to wait until the write has read the first batch and started writing things
3. Run any read query that needs to touch the table (even `r.db('rethinkdb').table('jobs')` works since it has to check the sindex status).
4. The read can easily stall for minutes before it actually gets run.

The likely reason is that the default batchspec has a limit on the batch size (of 1 MB), but no limit on the number of elements. @mlucy has recently changed batched updates to only transfer the primary key and not the whole document, meaning that the max size allows for pretty huge batches in terms of number of documents (10s of thousands).

We should use a special default batchspec for writes that limits the number of documents. I think ~100 is a reasonable size.

This is pretty much a show-stopper for 2.0 so we need to fix that.

@VeXocide want to grab this?

**Comment by danielmewes** [comment]
I can confirm that reducing the max_els to 100 avoids the issue.

**Comment by danielmewes** [comment]
Talked to @mlucy and assigning to him.

**Comment by mlucy** [comment]
In next.
