### ISSUE TITLE
Very slow inserts when listening on changes() in the same Node.js process

### ISSUE THREAD

**Issue by kacperzuk** [rethinkdb/rethinkdb#3819]
I'm using this code. It attaches to the changefeed several times and tries to insert at the same time:
```javascript
var r = require('rethinkdb');
var insert_time = null;
var listeners_count = 0;

var db = 'databasename';
var table = 'tablename';

r.connect({
    host: 'localhost',
    port: 28015,
    db: db
}).then(function(conn) {
    var attach_changes_handler = function() {
        r.table(table).changes().run(conn).then(function(cursor) {
            listeners_count += 1;
            cursor.each(function() {});
        });
    }

    var test = function() {
        insert_time = Date.now();
        r.table(table).insert({}).run(conn).then(function() {
            console.log('Changefeed listeners: '+listeners_count+'; Insert time: '+(Date.now()-insert_time)+'ms');
            setTimeout(test, 500);
        });
    }

    test();
    setInterval(attach_changes_handler, 1000);
});
```

And here's the result:
```
Changefeed listeners: 0; Insert time: 13ms
Changefeed listeners: 0; Insert time: 11ms
Changefeed listeners: 1; Insert time: 115ms
Changefeed listeners: 1; Insert time: 10ms
Changefeed listeners: 2; Insert time: 632ms
Changefeed listeners: 3; Insert time: 632ms
Changefeed listeners: 4; Insert time: 1134ms
Changefeed listeners: 6; Insert time: 2257ms
Changefeed listeners: 8; Insert time: 3755ms
Changefeed listeners: 13; Insert time: 4626ms
```

Things I observed:
1. it doesn't happen when I do the inserts in one process and attach to the changefeed in another
2. if I start another process that does inserts every 500ms, it speeds up inserts in the first process (they take about 500ms then).

I'm using default config and rotational disk, it's not a virtual machine.

**Comment by danielmewes** [comment]
Hi @kacperzuk. Sorry you're running into this. This is a known limitation of the current protocol.

We're fixing this in RethinkDB 2.0 (the next release).
Until then, you can open a separate connection for each changefeed to work around the limitation.

**Comment by coffeemug** [comment]
@danielmewes -- could you link to the dup?

**Comment by danielmewes** [comment]
Sorry, it's this one https://github.com/rethinkdb/rethinkdb/issues/3296
