### ISSUE TITLE
Unable to create new rethinkdb

### ISSUE THREAD

**Issue by kamilion** [rethinkdb/rethinkdb#3828]
Getting this odd traceback when I try to create a new database instance.

    root@cloudmaster:/mnt/btrfs/cloudmaster/rethinkdb# service rethinkdb restart
    rethinkdb: cloudmaster: The instance is not running (there is no pid file)
    rethinkdb: cloudmaster: Starting instance. (logging to '/mnt/btrfs/cloudmaster/rethinkdb/log_file')
    Version: rethinkdb 1.16.2+1~0trusty (GCC 4.8.2)
    error: Error in src/utils.cc at line 546:
    Previous message may not have been written to the log file (cannot open or find log file).
    error: Guarantee failed: [res != __null]  (errno 13 - Permission denied) Failed to determine absolute path for '/mnt/btrfs/cloudmaster/rethinkdb'
    Previous message may not have been written to the log file (cannot open or find log file).
    error: Backtrace:
    Previous message may not have been written to the log file (cannot open or find log file).
    error: Mon Feb 23 16:51:07 2015
           
           1: backtrace_t::backtrace_t() at ??:?
           2: format_backtrace(bool) at ??:?
           3: report_fatal_error(char const*, int, char const*, ...) at ??:?
           4: base_path_t::make_absolute() at ??:?
           5: main_rethinkdb_porcelain(int, char**) at ??:?
           6: main+0x1f4 at ??:?
           7: __libc_start_main+0xf5 at 0x7f9fd4fc4ec5 (/lib/x86_64-linux-gnu/libc.so.6)
           8: /usr/bin/rethinkdb() [0x8b93d9] at 0x8b93d9 ()
    Previous message may not have been written to the log file (cannot open or find log file).
    error: Exiting.
    Previous message may not have been written to the log file (cannot open or find log file).
    Trace/breakpoint trap

Here's a screenshot of the issue.

![](http://files.sllabs.com/files/long-term/screenshots/rethinkdb/rethinkbacktrace-1.16-2.png)

The btrfs is clean, rw, no subvolumes, the folder is owned by the rethinkdb user, the permissions seem correct.

The oddest thing about the traceback is
    Failed to determine absolute path for '/mnt/btrfs/cloudmaster/rethinkdb'

**Comment by danielmewes** [comment]
Thanks for opening the issue @kamilion .

@VeXocide can you check under which circumstances we would get a
"(errno 13 - Permission denied) Failed to determine absolute path for '/mnt/btrfs/cloudmaster/rethinkdb'"?

I wonder if we're doing something stupid.

@kamilion could you also post the config files in /etc/rethinkdb/instances.d that you're using as well as the output of `ls -l /mnt/btrfs/cloudmaster`?

**Comment by kamilion** [comment]
https://github.com/kamilion/kamikazi-deploy/blob/master/resources/config/rethink/cloudmaster.conf

    root@cloudmaster:/mnt/btrfs/cloudmaster# ls -al
    total 16
    drwx------ 1 ubuntu    ubuntu     52 Feb 24 01:16 .
    drwxr-xr-x 3 root      root       60 Feb 23 23:44 ..
    drwxrwxr-x 1 ubuntu    ubuntu     44 Feb  8 13:29 active
    drwxrwxr-x 1 ubuntu    ubuntu    792 Nov 27 11:58 bin
    drwxr-xr-x 1 rethinkdb rethinkdb   0 Feb 24 01:16 rethinkdb
    drwxrwxr-x 1 ubuntu    ubuntu    542 Nov 27 11:54 stacklet
    root@cloudmaster:/mnt/btrfs/cloudmaster# stat rethinkdb/
      File: ‘rethinkdb/’
      Size: 0         	Blocks: 0          IO Block: 4096   directory
    Device: 2eh/46d	Inode: 335         Links: 1
    Access: (0755/drwxr-xr-x)  Uid: (  107/rethinkdb)   Gid: (  119/rethinkdb)
    Access: 2015-02-24 01:16:17.020337892 +0000
    Modify: 2015-02-24 01:16:02.464337892 +0000
    Change: 2015-02-24 01:16:17.020337892 +0000
    Birth: -

**Comment by kamilion** [comment]
Seems to be reproducible on different hardware; grab the kamikazi64 ISO from
https://github.com/kamilion/kamikazi-deploy
and make a *LABELED* btrfs partition (bonus points if you choose the label "cloudmaster" to coincide with my configuration) and kamikazi will find it and mount it under /mnt/btrfs/<label>/ for you.

I was able to reproduce it with just a 32GB USB stick with a 4GB fat32 boot containing the ISO and a fresh 28GB btrfs following it.

**Comment by eliangidoni** [comment]
@danielmewes  @kamilion The bug is not in rethinkdb, the problem is with file permissions. You should set execution permissions (711) to the whole path ``/mnt/btrfs/cloudmaster``.

**Comment by danielmewes** [comment]
Uhh good catch @eliangidoni . I totally missed the 'drwx------ 1 ubuntu    ubuntu     52 Feb 24 01:16 .'

@kamilion can you try that and let us know if it solves the problem?

**Comment by kamilion** [comment]
Ah, yeah, that got it.  Guess it couldn't traverse into the directory. Firing up fine now. Thanks much!

**Comment by bwesen** [comment]
FWIW I got this just now 2023 when installing a replica rethinkdb instance using 2.4.3. The same error, permission problem, but this time the folder has the right permissions and ownership. The bug only appears if the folder is on a separate hd partition though. There are no funny symlinks or abs links though, so shouldn't be any different from any other hd mount...

I.e., it works if the directory is placed default, in /var/lib/rethinkdb/<conf name> but it doesn't work if I explicitly place it in say /mnt/something/something/<conf name>. I even tested starting it in the former, stopping, then mv'ing the folder into /mnt/something/something and it would then not start even though the folder is the same and has the exact same permissions.

Something in make_absolute() is checking other things I guess and finds something magical to complain about.. :/

```
       1 [0x562bf5f95d06]: backtrace_t::backtrace_t() at 0x562bf5f95d06 (/usr/bin/rethinkdb)
       2 [0x562bf5f96376]: lazy_backtrace_formatter_t::lazy_backtrace_formatter_t() at 0x562bf5f96376 (/usr/bin/rethinkdb)
       3 [0x562bf5f964b2]: format_backtrace[abi:cxx11](bool) at 0x562bf5f964b2 (/usr/bin/rethinkdb)
       4 [0x562bf5c98bbd]: report_fatal_error(char const*, int, char const*, ...) at 0x562bf5c98bbd (/usr/bin/rethinkdb)
       5 [0x562bf600cb0b]: base_path_t::make_absolute() at 0x562bf600cb0b (/usr/bin/rethinkdb)
       6 [0x562bf5c04fea]: main_rethinkdb_porcelain(int, char**) at 0x562bf5c04fea (/usr/bin/rethinkdb)
       7 [0x562bf59303e0]: main+0x2d0 at 0x562bf59303e0 (/usr/bin/rethinkdb)
       8 [0x7ff1b98e0083]: __libc_start_main+0xf3 at 0x7ff1b98e0083 (/lib/x86_64-linux-gnu/libc.so.6)
       9 [0x562bf593090e]: _start+0x2e at 0x562bf593090e (/usr/bin/rethinkdb)
```
