### ISSUE TITLE
Support for the Intel C++ compiler has bitrotted

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#3829]
Is there any interest in reviving support for building with icc?

**Comment by danielmewes** [comment]
I don't think it's worth investing development time into this at the moment.

**Comment by Tryneus** [comment]
I wouldn't mind taking a look.  If it means we'd be more portable and can reduce bad assumptions in our code, great.  If we have to work around compiler limitations in `icc` that we don't have to deal with for `clang` or `gcc`, probably not worth it.

**Comment by srh** [comment]
Nobody cares.
