### ISSUE TITLE
Getting 1 item found: `null` back for all `get` calls with arbitrary indexes

### ISSUE THREAD

**Issue by alimoeeny** [rethinkdb/rethinkdb#3830]
I inserted a row/object into my local rethinkdb. I am using the `go` driver. 
When I try to get the thing back using the `id` that I provided, if I use the driver (the go driver) I cannot get it back. 
If I use the Data Explorer web UI, I get one row back, but it is "null".
After this, any `get` call, with ANY id, even random ids, results a "1 row returned".
This row is null, not that it contains a field that is null. The whole object is null.
I understand that this most likely comes from something that the go driver does incorrectly, but the fact that you can even get into this situation I guess, needs investigation.

**Comment by mlucy** [comment]
@alimoeeny -- getting back `null` is normal; the server sends back `null` whenever you do a point get for a key that doesn't exist.  If you start up a fresh RethinkDB server, create a table, go to the web UI, and write `r.table('test').get(0)`, you should get back `null`.

As for why you can't retrieve your original object -- what did it look like when you inserted it?  If you just write `r.table('whatever')` and read everything from the stream, does it show up?

**Comment by alimoeeny** [comment]
Thanks @mlucy , I was a bit thrown off by the "1 row returned" .
OK, so let me investigate it more and I'll open another issue if I needed to, 
Thanks again,
