### ISSUE TITLE
Issues with large intergers

### ISSUE THREAD

**Issue by alimoeeny** [rethinkdb/rethinkdb#3834]
There is this issue with large ints (`int64` in go) being cut off or overflown or something. Here is a link to to the issue https://github.com/dancannon/gorethink/issues/156 
We appreciate it if you guys can comment. 
We know that the web UI, because of the limitations of Javascript cannot show the very large ints properly, but this issue is beyond that, it looks.

**Comment by mlucy** [comment]
Hi @alimoeeny,

This is more than a problem with JS, unfortunately, it's a problem with JSON.  JSON only has one numeric type, and for compatibility reasons we basically had to choose double-precision floating point numbers to be that numeric type, which means that RethinkDB stores all numbers as double-precision floats internally.

There's been talk of supporting other numeric types as pseudotypes (e.g. https://github.com/rethinkdb/rethinkdb/issues/3407), but that isn't currently scheduled.

**Comment by alimoeeny** [comment]
Thanks @mlucy , so from your standpoint drivers (at least for the time being) should not support `int64` since there is no way for the users of the driver to tell if what they are saving will be the same thing as what is being stored, right?

**Comment by mlucy** [comment]
Well, I could see three possible interpretations:
* Drivers shouldn't support `int64`.
* Drivers should support `int64` but should refuse to serialize values that the database won't be able to losslessly deserialize.
* Drivers should serialize whatever they want as long as they do it losslessly, and the server should be responsible for erroring if it can't preserve the full precision.

We're currently in the process of changing the JSON parser on the server for performance reasons, and we could look into the third option as part of that, but for now I think it would be best for drivers not to serialize unsafe values.

**Comment by danielmewes** [comment]
I opened https://github.com/rethinkdb/rethinkdb/issues/3835 to discuss option 3.
