### ISSUE TITLE
Suggestion: allow importing data from stdin

### ISSUE THREAD

**Issue by elifarley** [rethinkdb/rethinkdb#3838]
Sometimes I wish I could pipe data to rethinkdb like this:

```
bzip2 -dc my-file.log.bz2 | rethinkdb import --table test.mytable
```

If this is implemented, the help file could read like this:

```
Import file:
  -f [ --file ] FILE               the file to import data from. If absent, data is read from stdin
```

**Comment by danielmewes** [comment]
This would have been useful for https://github.com/rethinkdb/rethinkdb/issues/3832#issuecomment-76118001 as well.

**Comment by timmaxw** [comment]
I propose that we interpret `-f -` as an order to read from stdin. This is consistent with the behavior of `tar`.

**Comment by danielmewes** [comment]
> I propose that we interpret `-f -` as an order to read from stdin. This is consistent with the behavior of `tar`.

:+1:

**Comment by elifarley** [comment]
That was on my mind too :)

However, the idea of defaulting to stdin when no file is specified is consistent with the way **mysql** and **mongodb** work:

>  If you do not specify a file with the “--file” option, mongoimport accepts input over standard input (e.g. “stdin.”)

So it could feel more natural to those coming from mysql and mongodb worlds if stdin is the default choice for data input.

But that's just my 2c...

**Comment by nlevitt** [comment]
Without making any changes to the code, `rethinkdb import -f /dev/fd/0` seems to work for me (though progress bar is wrong of course)
