### ISSUE TITLE
ERROR: Unrecognized subcommand 'admin'. Try 'rethinkdb help'.

### ISSUE THREAD

**Issue by mjhea0** [rethinkdb/rethinkdb#3840]
I am using version - 

```sh
$ rethinkdb -v
rethinkdb 1.16.2-1 (CLANG 6.0 (clang-600.0.56))
```
Is the `admin` command gone? If so, how do I set an auth key? Thanks!

**Comment by mglukhovsky** [comment]
@mjhea0, the `admin` command has been replaced by a set of system tables used for cluster administration. To set an auth key, run the following query from any of the client drivers, or directly from the Data Explorer:

```
r.db('rethinkdb').table('cluster_config').get('auth').update({auth_key: 'newkey'})
```

For more information on setting auth keys, check out the section titled 'Securing the driver port' of this document: http://rethinkdb.com/docs/security/

Hope that helps!

**Comment by mjhea0** [comment]
So you set the auth keys on the table? How do you set it at the db-level? If I can't set it at the db-level, this will error out -

```python
conn = r.connect(
            host=config['rethink_host'], port=config['rethink_port'],
            auth_key=config['rethink_authkey'], db=config['rethink_db']).repl()
```

With:

```sh
raise RqlDriverError("Server dropped connection with message: \"%s\"" % response.strip())
rethinkdb.errors.RqlDriverError: Server dropped connection with message: "ERROR: Incorrect authorization key."
```

**Comment by mglukhovsky** [comment]
You can configure one auth key to access the cluster -- there is no way to set an auth key to be specific to a database or table.

The auth key is stored in a system table called `cluster_config`, in the system `rethinkdb` database. You can read more about how system tables are used for cluster administration tasks here: http://rethinkdb.com/docs/system-tables/

Supposing no auth key has been set, if I run this query to see the contents of the `cluster_config` table:

```js
r.db('rethinkdb').table('cluster_config')
```

...then I can see no auth key has been set.

```json
{
    "auth_key": null ,
    "id":  "auth"
}
```

Once I've set the auth key (by updating the `auth_key` document):

```js
r.db('rethinkdb').table('cluster_config').update({'auth_key': 'hunter22'})
```

...the `cluster_config` table will show that a key has been set (but will hide the actual auth key for security purposes):

```json
{
    "auth_key": {
        "hidden": true
    } ,
    "id":  "auth"
}
```

If I try to connect to the cluster now (using the default values), I should get an error:

```py
>>> import rethinkdb as r
>>> r.connect()
Traceback (most recent call last):
...
RqlDriverError: Server dropped connection with message: "ERROR: Incorrect author
ization key."
```

Using the new auth key, I can connect successfully:

```py
>>> r.connect(auth_key='hunter22')
<rethinkdb.net.Connection object at 0x10f333fd0>
```

**Comment by mglukhovsky** [comment]
If you're still running into issues connecting to the cluster with an auth key:

- check the contents of the `cluster_config` system table to make sure the auth key has been set
- double-check that you're using the same auth key in your connection details.

**Comment by mjhea0** [comment]
Strange. It works when I'm logged into the portal. Just not with a script. Is that the case?

**Comment by mglukhovsky** [comment]
Sorry, by "portal" do you mean the web UI? The cluster auth key should only be used when you're opening a connection to the database (e.g. `r.connect()`)

Can you include the script you're using, and the output of `r.db('rethinkdb').table('cluster_config')`?
 What happens when you try to connect via a REPL like `python` or `bpython`?
```python
>>> import rethinkdb as r
>>> r.connect(auth_key='hunter22')
```

**Comment by samyoungnyc** [comment]
Hi you might want to replace 'rethinkdb admin' command shown on this page - http://rethinkdb.com/docs/paas/

**Comment by timmaxw** [comment]
Good point. I've filed an issue in the docs repository: https://github.com/rethinkdb/docs/issues/790
