### ISSUE TITLE
set auth at db level?

### ISSUE THREAD

**Issue by mjhea0** [rethinkdb/rethinkdb#3841]
So you set the auth keys on the table? How do you set it at the db-level? If I can't set it at the db-level, this will error out -

```python
conn = r.connect(
            host=config['rethink_host'], port=config['rethink_port'],
            auth_key=config['rethink_authkey'], db=config['rethink_db']).repl()
```

With:

```sh
raise RqlDriverError("Server dropped connection with message: \"%s\"" % response.strip())
rethinkdb.errors.RqlDriverError: Server dropped connection with message: "ERROR: Incorrect authorization key."
```

**Comment by danielmewes** [comment]
Hi @mjhea0 , this was probably a misunderstanding. Like @mglukhovsky explained here https://github.com/rethinkdb/rethinkdb/issues/3840#issuecomment-76207845 the auth key is actually set for the whole cluster.
