### ISSUE TITLE
Rethinkdb internal tables already exist when running `rethinkdb dump`

### ISSUE THREAD

**Issue by chrisvariety** [rethinkdb/rethinkdb#3842]
This is new with the 1.16 release.

With a fresh rethinkdb instance (e.g. `rm -r rethinkdb_data` then starting up rethinkdb with just `rethinkdb`), running `rethinkdb restore rethinkdb_dump_2015-02-26T05\:17\:02.tar.gz` gives me this:

```
Unzipping archive file...
  Done (1 seconds)
Importing from directory...
Error: The following tables already exist, run with --force to import into the existing tables:
  rethinkdb.cluster_config
  rethinkdb.current_issues
  rethinkdb.db_config
  rethinkdb.jobs
  rethinkdb.logs
  rethinkdb.server_config
  rethinkdb.server_status
  rethinkdb.stats
  rethinkdb.table_config
  rethinkdb.table_status
Error: rethinkdb-import failed
```

The server was dumped with `rethinkdb dump` on the same version of rethinkdb. Is this expected behavior? How do I restore into an "empty" rethinkdb instance, since those tables are created automatically? I know I can `--force` like the message says, but that is kind of scary to do on rethinkdb internal tables.

Log output from the server:

```
Initializing directory /Users/chrismcc/workspace/ti-node/rethinkdb_data
Running rethinkdb 1.16.0-1 (CLANG 4.2 (clang-425.0.28))...
Running on Darwin 14.1.0 x86_64
Loading data from directory /Users/chrismcc/workspace/ti-node/rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on addresses: 127.0.0.1, ::1
To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.
Server ready, "goldie_local_yck" fc44f620-0dda-4a48-9ca9-fb8c1882eeb0
```

Happy to send the dump along, just let me know.

**Comment by chrisvariety** [comment]
Yeah, seems like `--force` doesn't work either, so dump/restore is totally busted?

```
Error when importing into table 'rethinkdb.logs': It's illegal to write to the `rethinkdb.logs` system table.
Error when importing into table 'rethinkdb.db_config': If you want to create a new table by inserting into `rethinkdb.db_config`, you must use an auto-generated primary key.
Error when importing into table 'rethinkdb.table_config': The change you're trying to make to `rethinkdb.table_config` has the wrong format. In `shards`: In `replicas`: Server `goldie_local_oms` does not exist.
Error when importing into table 'rethinkdb.server_status': It's illegal to write to the `rethinkdb.server_status` table.
Error when importing into table 'rethinkdb.server_config': It's illegal to insert new rows into the `rethinkdb.server_config` artificial table.
Error when importing into table 'rethinkdb.table_status': It's illegal to write to the `rethinkdb.table_status` table.
Error when importing into table 'rethinkdb.jobs': The `rethinkdb.jobs` system table only allows deletions, not inserts or updates.
Error when importing into table 'rethinkdb.stats': It's illegal to write to the `rethinkdb.stats` table.
Errors occurred during import
Error: rethinkdb-import failed
```

**Comment by mglukhovsky** [comment]
@chrisvariety, have you checked the version of your RethinkDB Python driver with `pip freeze`?

If you're running an older version of the driver (< `1.16.0-2`), you should upgrade the driver:

```
sudo pip install -U rethinkdb
```


The import/export script relies on the Python driver installed. If that doesn't help, it I suspect you're running into #3261, but @Tryneus will know more. Sorry you ran into this!

**Comment by Tryneus** [comment]
Yep, this looks like it's due to an old driver.  The import script from before `1.16` doesn't know about the admin tables and will try to export/import them.  With the 1.16 backup scripts, we changed it to refuse to export/import those tables (this is also why the 1.16 backup scripts won't connect to older instances of rethinkdb).

This is just another reason we should package the backup scripts with the server.

**Comment by chrisvariety** [comment]
@mglukhovsky d'oh! `rethinkdb==1.14.0-0` :frowning: 

got it! thanks all.
