### ISSUE TITLE
Replace cJSON by rapidjson

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3844]
https://github.com/miloyip/rapidjson is usually faster than cJSON. 

I've already started a branch with a partial port in `daniel_rapidjson`.

**Comment by danielmewes** [comment]
Implemented in branch `daniel_rapidjson`, in CR 2801 by @Tryneus.

**Comment by mlucy** [comment]
@danielmewes -- it might be worth auditing the rapidjson code to see whether they parse and print doubles in a way that doesn't discard information.  I don't think we have a test for that right now.

**Comment by danielmewes** [comment]
@mlucy Good point. It does round differently from cJSON (this shows up in the geospatial tests). I haven't investigated that yet, but it might indeed discard some information on the way. I'll add a separate test and investigate.

**Comment by danielmewes** [comment]
Merged into `next` 9504c0d5f96560693e6ff53fbb6ffc9a3fba6f1b .

The output of JSON-related commands such as `coerce_to('string')` and `to_json_string()` as well as some error messages that include user data will change slightly in format due to this.

Old secondary indexes keep using cJSON for these operations for the time being to maintain compatibility.
