### ISSUE TITLE
Suggestion: running a query from the command line and piping the results

### ISSUE THREAD

**Issue by elifarley** [rethinkdb/rethinkdb#3849]
How about having something siimlar to this?

```
mysql database --batch --execute "\
  SELECT a, sum(b) FROM mytable GROUP BY a ORDER BY 2;\
" > results.csv
```

In rethinkdb it could be like this:
```
rethinkdb --format csv --reql-flavor python --execute "\
r.table('mytable').group('a').sum('b').ungroup().orderBy('reduction') \
" > results.csv
```

In the future, it could be
```
rethinkdb --format csv --reql-flavor pure-reql --execute "\
r.table('mytable').group('a').sum('b').ungroup().orderBy('reduction') \
" > results.csv
```

Of course the 'pure-reql' flavor would be the default.

**Comment by danielmewes** [comment]
There actually already are two tools available for doing this:
https://github.com/stiang/recli
https://github.com/deontologician/reql_cli

Please let me know if that works for you.

**Comment by elifarley** [comment]
They look great, thank you!

**Comment by danielmewes** [comment]
Glad they're working for you.
We might integrate something into RethinkDB itself later, but I'm going to close this for now.
