### ISSUE TITLE
Keep "SELECTION" on "SELECTION<STREAM>"s queried through hasFields

### ISSUE THREAD

**Issue by thejsj** [rethinkdb/rethinkdb#3851]
The [`.hasFields`](http://rethinkdb.com/api/javascript/has_fields/) method converts a "SELECTION<STREAM>" into a "STREAM". `.filter`, on the other hand, keeps the original reference to the selection. The functionality between these seems similar enough that I would have expected `.hasFields` to keep the reference to the source rows through the "SELECTION". 

Is it possible for `.hasFields` to return a "SELECTION<STREAM>" when provided a "SELECTION<STREAM>", instead of returning a "STREAM"? All this is also true for "SELECTION<ARRAY>".

Example Queries:

```
r.db('caltrain').table('trains')
 .between(300, 400, {'index': 'number'})
 .orderBy({'index': 'number'})
 .filter({'direction': 'north'})
 .typeOf() // "SELECTION<STREAM>"
```

```
r.db('caltrain').table('trains')
 .between(300, 400, {'index': 'number'})
 .orderBy({'index': 'number'})
 .filter({'direction': 'north'})
 .hasFields({'stations': true})
 .typeOf() // "STREAM"
```

**Comment by chrisvariety** [comment]
Note that this doesn't work with `.hasFIelds('id').nth(0)` either, it returns a `OBJECT` instead of a `SELECTION<OBJECT>`

**Comment by coffeemug** [comment]
Is this a dup of #2609?

**Comment by danielmewes** [comment]
Yes, looks like one.
Closing as dup of https://github.com/rethinkdb/rethinkdb/issues/2609
