### ISSUE TITLE
Launch Data Explorer directly to table

### ISSUE THREAD

**Issue by joshhunt** [rethinkdb/rethinkdb#3856]
Just a small suggestion to make the Admin Console a little bit easier to use - It would be really handy if in the Tables view, there was a button next to each table that would launch the Dataexplorer, prefilled in with a query for that table, like `r.db('myApi').table('users')`

**Comment by joshhunt** [comment]
If I were to make this change myself, I would probably put a button on each table row that shows just on hover. When clicked, it would set the localStorage value `current_query` to the prefillled in query (just `r.db().table()`) and then navigate to the data explorer view.

Thoughts? If I were to approach it this way, would the PR be accepted?

**Comment by deontologician** [comment]
Very similar to #3509. It's not scheduled immediately, so pull requests are definitely welcome!

**Comment by danielmewes** [comment]
Let me actually merge this with #3509 since they are really similar.
