### ISSUE TITLE
Server suddenly crash after upgrading to 1.16.2

### ISSUE THREAD

**Issue by jilen** [rethinkdb/rethinkdb#3863]
I upgrade my rethinkdb from 1.15 to 1.16 and everything seems ok, but after a while, the server went south,  and I found following logs 
```
2015-03-03T09:37:51.251008986 57609.441698s error: Error in src/arch/address.cc at line 317:
2015-03-03T09:37:51.251058765 57609.441747s error: to_string called on an uninitialized ip_address_t, addr_type: 0
2015-03-03T09:37:51.251074933 57609.441764s error: Backtrace:
2015-03-03T09:37:51.446894516 57609.637586s error: Tue Mar  3 09:37:51 2015\n\n1: backtrace_t::backtrace_t() at 0xc287c0 (/usr/bin/rethinkdb)\n2: format_backtrace(bool) at 0xc28b20 (/usr/bin/rethinkdb)\n3: repo\
rt_fatal_error(char const*, int, char const*, ...) at 0xdaed00 (/usr/bin/rethinkdb)\n4: ip_and_port_t::to_string() const at 0xb56c69 (/usr/bin/rethinkdb)\n5: connectivity_cluster_t::run_t::handle(keepalive_tcp_\
conn_stream_t*, boost::optional<peer_id_t>, boost::optional<peer_address_t>, auto_drainer_t::lock_t, bool*) at 0xb65d2e (/usr/bin/rethinkdb)\n6: connectivity_cluster_t::run_t::on_new_connection(scoped_ptr_t<lin\
ux_tcp_conn_descriptor_t> const&, auto_drainer_t::lock_t) at 0xb67630 (/usr/bin/rethinkdb)\n7: std::_Function_handler<void ()(scoped_ptr_t<linux_tcp_conn_descriptor_t>&), std::_Bind<std::_Mem_fn<void (connectiv\
ity_cluster_t::run_t::*)(scoped_ptr_t<linux_tcp_conn_descriptor_t> const&, auto_drainer_t::lock_t)> ()(connectivity_cluster_t::run_t*, std::_Placeholder<1>, auto_drainer_t::lock_t)> >::_M_invoke(std::_Any_data \
const&, scoped_ptr_t<linux_tcp_conn_descriptor_t>&) at 0xb68255 (/usr/bin/rethinkdb)\n8: linux_nonthrowing_tcp_listener_t::handle(int) at 0xb4788c (/usr/bin/rethinkdb)\n9: coro_t::run() at 0xb5eca8 (/usr/bin/re\
thinkdb)
```

**Comment by danielmewes** [comment]
Sorry you had to run into this @jilen , and thanks for reporting the issue.

My guess is that this got fixed by https://github.com/rethinkdb/rethinkdb/pull/3814 but we didn't backport it to 1.16.x.

Does this happen repeatedly if you restart the server(s)?

**Comment by danielmewes** [comment]
@VeXocide also suggested that we could make `ip_address_t::to_string()` not crash on an uninitialized `ip_address_t` but to return some default string instead to make the code more robust.

**Comment by jilen** [comment]
@danielmewes  No, after restarting server it is ok, but I worrying about whether  it will happen again sometime later.

**Comment by danielmewes** [comment]
So we believe that this only happens if another server disconnects in a very narrow time frame after establishing the connection. The error should not happen once the cluster is up and running.

I'm going to backport https://github.com/rethinkdb/rethinkdb/pull/3814 to our v1.16.x branch. However unless it turns out that this happens more often than we believe, we will probably wait for the next release (2.0) to ship the fix. The release should be out ~2 weeks from now.

@jilen if this is critical for you, I can also send you a custom binary with the fix.

**Comment by jilen** [comment]
@danielmewes  Thanks,  send me an `rpm`  if convenient.

**Comment by danielmewes** [comment]
@jilen Sent you an email with a binary.
