### ISSUE TITLE
python driver dict subclass problem

### ISSUE THREAD

**Issue by ftKnox** [rethinkdb/rethinkdb#3871]
I am subclassing dict that contains a `__call__` function and then passing that as an object to insert. The insert fails due to it matching collections.Callable. In ast.py function expr() simply moving the collections.Callable check after the collections.Mapping check fixes the issue for me. I don't know how common this use case is but it's an issue none the less. Below is a test case.

```python
    class u(dict):
      model = {
        'id':'test'
      }
      def __init__(self,*args,**kwargs):
        for k,v in self.model.iteritems():
          self[k] = v

      def __call__(self):
        return self

    user = u()
    print 'Result: %s' % r.table("users").insert(user).run(dbh)
```

**Comment by danielmewes** [comment]
Thanks for opening an issue report @ftKnox.

The general problem is that this sort of conversion is ambiguous without having additional information. If we swap the Callable and Mapping checks in our implementation of `r.expr` you can theoretically run into the same problem where you expect something to behave like a function, but it also implements `Mappable` and hence is treated like a dictionary.
I imagine that would be even more rare than your use case though.

The problem would get solved by something like https://github.com/rethinkdb/rethinkdb/issues/1016, which would allow you to register your subclass explicitly with the driver and tell it how to convert instances of it into a ReQL object.

Here's a work-around you can do:
subclass you class from `r.RqlQuery`. Then overwrite the `tt` attribute and the `build(self)` method by something like
```py
tt = pTerm.MAKE_OBJ
def build(self):
        res = {}
        for k, v in self:
            k = k.build() if isinstance(k, RqlQuery) else k
            res[k] = v.build() if isinstance(v, RqlQuery) else v
        return res
```

You can look at the `MakeObj` type for a reference.

**Comment by danielmewes** [comment]
Please let me know if that works for you for the time being until we get to #1016.

**Comment by ftKnox** [comment]
Good point @danielmewes. One downside, off the top of my head, to subclassing r.RqlQuery is that it pulls all of the namespace over with it. I will just maintain a driver fork until you get to #1016. Thanks.

**Comment by danielmewes** [comment]
Sorry for the inconvenience. #1016 is not super high on our list of priorities at the moment, but we'll get to it eventually.
