### ISSUE TITLE
Hitting escape on any web UI modal breaks web UI entirely

### ISSUE THREAD

**Issue by chrisvariety** [rethinkdb/rethinkdb#3872]
Hi all,

So, if you open any modal in the web UI (e.g. "Delete Database", "Delete Selected Tables", etc.), and close the modal by hitting ESC (_instead_ of clicking the little **x**), the page becomes unresponsive -- you cannot click or hover on anything and have to refresh the page. This is because the `modal-dialog` retains a class of `visible` even though its content is emptied correctly.

Here's a GIF demonstrating the issue:

![rethinkdb-bug](https://cloud.githubusercontent.com/assets/44855/6476009/99bc1e00-c1c5-11e4-939f-653df7d5ecbc.gif)

Reproduced on latest RethinkDB.

**Comment by chrisvariety** [comment]
I think you'll want to call `@hide_modal()` on this line: https://github.com/rethinkdb/rethinkdb/blob/next/admin/static/coffee/ui_components/modals.coffee#L48

... or something similar to that.
... or disable ESC entirely :wink:

**Comment by danielmewes** [comment]
Thank you for the great issue report, even with an animation :)
Also thanks for looking into a possible fix for this.

I think we should fix this soon, as I can see it being very irritating. Scheduling for 2.0.

(@deontologician)

**Comment by deontologician** [comment]
I think we fixed a similar issue that occurred when the user clicked on the background. In any case, should be a quick fix.

**Comment by deontologician** [comment]
Up in CR #2676 by @danielmewes

**Comment by chrisvariety** [comment]
quick work y'all!!!

**Comment by deontologician** [comment]
Ok, fixed on next. Thanks again @chrisvariety. @danielmewes I assume this isn't backport worthy? Or do we have another point release before 2.0?

**Comment by danielmewes** [comment]
Feel free to merge it into v1.16.x, but it's unlikely that we'll do another point release before 2.0.

**Comment by mglukhovsky** [comment]
@chrisvariety, thanks for the GIF, great bug report!
