### ISSUE TITLE
Loading a large table in the data explorer leads to InternalError

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3873]
I've just observed this in firefox. Chromium doesn't seem to have the issue. It also doesn't trigger when a smaller table is loaded. Trying to load a table with 1.4M docs causes this

![selection_023](https://cloud.githubusercontent.com/assets/1366/6476825/a2285676-c1cf-11e4-9d81-343a0fd1269d.png)

I'm still investigating whether this is a regression and which part of the code is causing it. I believe it's happening in loading the results. It also only happens sporadically.

**Comment by deontologician** [comment]
Well, it's at least in 1.16 as well.

**Comment by deontologician** [comment]
Determined the part that's overflowing is this sequence:

firefox lets it go 20 times and then cuts it off

```
__bind/cluster-min.js:11999:58
ResultView</ResultView.prototype.fetch_batch_rows@/cluster-min.js:7960:16
__bind/cluster-min.js:11999:58
QueryResult</QueryResult.prototype.fetch_next@/cluster-min.js:4598:18
__bind/cluster-min.js:11999:58
DriverHandler</DriverHandler.prototype.cursor_next@/cluster-min.js:9353:1
require<[43]</</module.exports.varar/js/rethinkdb.js:11695:12
require<[2]</IterableResult</IterableResult.prototype._nextjs/rethinkdb.js:4828:14
require<[2]</IterableResult</IterableResult.prototype._next</fn</js/rethinkdb.js:4824:16
require<[2]</IterableResult</IterableResult.prototype._promptNext@/js/rethinkdb.js:4768:13
require<[2]</IterableResult</IterableResult.prototype._handleRow@/js/rethinkdb.js:4743:12
DriverHandler</DriverHandler.prototype.cursor_next/</cluster-min.js:9363:20
QueryResult</QueryResult.prototype.fetch_next/<.row</cluster-min.js:4618:24
Backbone.Events.trigger@/js/backbone.js:148:19
triggerEvents@/js/backbone.js:208:32
h.before/js/underscore-min.js:5:9072
Backbone.Events.once/oncejs/backbone.js:100:9
ResultView</ResultView.prototype.fetch_batch_rows/</cluster-min.js:7957:20
```

These line numbers refer to the compiled coffeescript in g7d65146

**Comment by neumino** [comment]
I'm not sure where the problem is exactly, but we break the recursion by using setImmediate here:
https://github.com/rethinkdb/rethinkdb/blob/next/drivers/javascript/cursor.coffee#L78

Firefox doesn't setImmediate so we replace it with `setTimeout(..., 0)`. Maybe that isn't enough to break the recursion? Or there's a path that avoid setImmediate?

**Comment by deontologician** [comment]
That's what I ended up doing. I used requestAnimationFrame, but I need to tweak where I break the stack because its delaying showing the first batch until the second one comes in, which makes it seem really slow. Anyways, probably a bit more hacking tomorrow and it'll be nice.

**Comment by deontologician** [comment]
@neumino you were right, looks like I just need to reduce the `@stackSize` value on firefox, all that work has been done in the driver already.

**Comment by deontologician** [comment]
This is up in CR 2682 by @AtnNn . It looks like this may be peculiar to Firefox 35. This recursion error is reported as popping up for other applications with that version.
