### ISSUE TITLE
Garbage-collect branch history

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#3879]
Currently the branch history is append-only, so it grows without bound. We should garbage-collect it by deleting branches that all replicas are known to be descended from.

Probably the right way to do this is to have the `contract_coordinator_t` garbage collect its own branch history and have the `contract_executor_t`s copy those changes. We'll have to rewrite all the branch-history manipulation functions so that they don't crash when the history is incomplete.

**Comment by danielmewes** [comment]
@timmaxw noticed that this can become important very quickly, so we'll have to do it for 2.1.

**Comment by timmaxw** [comment]
In CR 3007.

**Comment by timmaxw** [comment]
Fixed in 6e45d1569305c96136135ff19e47bda67c378617.
