### ISSUE TITLE
Migrate metadata and B-tree metainfo to new Raft format

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#3881]
Both the metadata and the B-tree metainfo have changed format with the Raft changes. We need to write code to migrate existing data files in-place to the new format. There are several parts to this:

* Metadata migration: When a post-Raft server opens a pre-Raft metadata file, it should create a Raft cluster for each table that it was a replica for before. This means that every replica will create its own Raft cluster; but the epoch system will pick a winner. We should think more about this and make sure it actually gives reasonable behavior.

* Metainfo migration: The metainfo now stores `version_t` instead of `version_range_t`. Normally the old `version_range_t`s corresponded to a single `version_t`, so they're easy to translate. If the start and end points of the range are different, we need to create a fake branch and insert it into the local branch history.

* Sindex metadata migration: If we decide to put secondary indexes in the Raft metadata, we need a way to put them there. We might be able to insert them as we create the new Raft cluster when migrating the metadata.

**Comment by timmaxw** [comment]
Some complications (relevant for @Tryneus):

* In RethinkDB 2.0, if a server is permanently removed, we'll leave its server ID in the configs. All of the functions for displaying servers in 2.0 will check each server ID in the config, and ignore the ones that have been permanently removed. So the migration routine needs to do the same thing.

* The primary for a shard in 2.0 can also be set to the server ID of a permanently removed server, or it can be set to a nil UUID. But in 2.1 the primary must be a valid server ID. So the migration process should detect the case where the primary server ID is a permanently removed server or nil, and pick an arbitrary secondary to become primary.

**Comment by AtnNn** [comment]
In #3311 support for old 1.13 indexes was removed. Automatic migration may need to explicitly support or reject them. (@tryneus @mlucy)

**Comment by danielmewes** [comment]
@Tryneus merged this in a series of commits.
@Tryneus could you please add code review numbers here later?

**Comment by Tryneus** [comment]
The related commits in `next` and their reviews are below.  These were also cherry-picked into `v2.1.x`, but `next` was merged into `v2.1.x` anyway, so it doesn't matter.

e750a98 (review 3122): Initial migration commit
e8c475a (review 3133): Fixing unittests following that
66ff2c8 (review 3139): Automatically handle incoherent versions without an explicit command-line flag
a381f54 (review 3139): Handle corner cases in table metadata
85e5ec2 (review 3140): Error properly when encountering a v1.13 secondary index
