### ISSUE TITLE
Fix table status

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#3882]
The `rethinkdb.table_status` system table and the `table.status()` command are currently disabled in `raft`. These should be fixed. Also, we'll need to change the format of the status documents somewhat.

**Comment by danielmewes** [comment]
@VeXocide mentioned he wanted to do this one.

**Comment by timmaxw** [comment]
#3922 might be part of the same project.

**Comment by timmaxw** [comment]
We have to decide how to summarize and present table status. The biggest issue is how to combine information across different "sub-shards" of the same user-visible shard. These "sub-shards" could be hash shards, or they could be smaller range shards within the user-visible range shard.

For each sub-shard, we have the following information:
* The server ID that's supposed to be acting as primary; this is normally the user's designated primary, but might be different during auto-failover.
* A set of "voting" server IDs; we need a quorum of them to perform writes.
* For each server, one of the following states:
    * `primary` - The server is accepting queries as primary for the table.
    * `secondary` - The server is acting as secondary for the table and streaming up-to-date queries from the primary.
    * `backfilling` - The server is backfilling data from the primary, but not ready for queries.
    * `looking_for_primary` - The server would like to be a secondary, but it can't find the primary
    * `disconnected` - the server cannot be reached.
    * `nothing` - the server has no data or is erasing its data.
    * `transitioning` - a temporary state indicating that the server is unavailable for some other reason
The sub-shard is ready for outdated reads if any server is `primary`, `secondary`, `backfilling`, or `looking_for_primary`. It's ready for regular reads if any server is `primary`. It's ready for writes if the server that's "supposed to be acting as primary" is `primary`, and a quorum of the "voting" servers are `secondary`. (Calculating if the sub-shard is fully ready is straightforward but would take more space to describe, so I'll leave it out here.)

The hard part is combining sub-shard readinesses and sub-shard server states in a way that's consistent. Presumably the user-shard readiness should be the minimum of its sub-shards' readinesses. Suppose we make the user-shard state for a given server be the minimum of the sub-shard states for a given server. Then we could end up with a paradoxical situation where each server is apparently a secondary, but the table as a whole is ready for writes.

**Comment by danielmewes** [comment]
I like the idea of displaying the status of a user-visible shard*server with inconsistent subshard states as `mixed`.
The readyness values for the whole table should in that case still reflect the actual readyness I think, even if some shards are in the `mixed` state.

We could also set the primary and set of voting servers to a special `"$mixed"` value whenever they are inconsistent among sub-shards. However that would break the schema, and hence is probably a bad idea.
Instead we could make both the primary server and the voting servers field an array of primary servers / voting server lists. 

It might look weird to have two or more primaries for a shard. But we can explain that they are in a phase of "hand over" and both are serving a separate subset of the shard while doing that. I think that's easy enough to understand.

**Comment by timmaxw** [comment]
I think `mixed` doesn't give users enough information, and they'll just be confused.

(Sorry for the tersse comment. I have some more ideas, but they're still half-formed.)

**Comment by VeXocide** [comment]
In CR 2833 by @timmaxw

**Comment by VeXocide** [comment]
Merged into `raft` via commit 27c3c372ddca5d2f12bc1ea108576c770cf0c078.
