### ISSUE TITLE
Fix jobs

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#3884]
The `rethinkdb.jobs` system table is currently broken in `raft`:

* The `jobs_manager_t` currently cannot find the `store_t`s, because the method through which it was finding them was changed in Raft.

* Backfill jobs need to be reimplemented.

**Comment by VeXocide** [comment]
This is next.

**Comment by VeXocide** [comment]
The fix for `"disk_compaction"` and `"index_construction"` jobs is in CR 2918 by @timmaxw, and I'm holding off on the `"backfill"` jobs until either @danielmewes or @timmaxw is here to give me a rundown of the code.

**Comment by VeXocide** [comment]
Fix merged into `raft` via commit c4e45484d9b9c2e830198d936edc7c7a6bb33c99.

**Comment by danielmewes** [comment]
FYI: The `regression.659` test is failing because of missing backfill jobs.

**Comment by VeXocide** [comment]
Fixing backfill jobs is next

**Comment by VeXocide** [comment]
In CR 3012 by @timmaxw.

**Comment by VeXocide** [comment]
Merged into `next` via commit 5a2e9b25d108eeb2c114aa92f07d8518721b28f1.
