### ISSUE TITLE
Let user specify some replicas as voters and some as non-voters

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#3891]
In `raft` right now, consensus is defined as a majority of all replicas. We should let the user specify replicas that aren't used for consensus. This could take the form of another field in `table_config` called `non_voting_replicas`, or something.

**Comment by danielmewes** [comment]
What's an example use case of this?

**Comment by timmaxw** [comment]
Suppose the user has three replicas in a datacenter in Boston and one replica in each of three "satellite" datacenters in San Francisco, Hong Kong, and Paris. The primaries are all in the Boston datacenter, and the user wants writes to be acknowledged without doing a complete network round-trip to one of the remote datacenters. So they set the satellite replicas as non-voting.

**Comment by danielmewes** [comment]
Got it, thanks

**Comment by VeXocide** [comment]
Moving to the `raft` milestone due to #3894.

**Comment by danielmewes** [comment]
I think it's actually not critical that we support this for https://github.com/rethinkdb/rethinkdb/issues/3894 . Just `single` and `majority` acks should be enough for the first release.

We might get this as a side effect of implementing hard override, but in itself I think it's not release critical.

**Comment by VeXocide** [comment]
:+1:

**Comment by deontologician** [comment]
This is just a reminder to do the webui portion whenever this is completed

**Comment by timmaxw** [comment]
In CR 2925.

**Comment by deontologician** [comment]
@timmaxw so do we need new webui functionality for this in your opinion?

**Comment by timmaxw** [comment]
The web UI should visually indicate which replicas are nonvoting, but other than that I don't think we need anything.

**Comment by danielmewes** [comment]
> The web UI should visually indicate which replicas are nonvoting, but other than that I don't think we need anything.

:+1:

**Comment by timmaxw** [comment]
Fixed in f706b90e991021f45881fa6512498126476c4d7d.
