### ISSUE TITLE
Fix write_acks and durability

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#3894]
Right now in `raft` we ignore the `write_acks` and `durability` fields of the table. We should stop ignoring them. Also, we should think about whether we want to change the format of the `write_acks` field now that we have auto-failover.

**Comment by VeXocide** [comment]
For the `write_acks` we're going to keep the options `"single"` and `"majority"`, and removing the `"complex"` option which allowed users to specify which servers were considered to be part of the majority. Instead we're going to implement #3891 adding non-voting replicas which will never be considered part of the majority.

**Comment by danielmewes** [comment]
> For the `write_acks` we're going to keep the options `"single"` and `"majority"`, and removing the `"complex"` option

:+1:

**Comment by VeXocide** [comment]
In CR 2867 by @timmaxw.

**Comment by VeXocide** [comment]
Merged into `raft` via commit d64210a28332d4fd736f90b08b9e981b87cfeb8d.
