### ISSUE TITLE
Suggestion: square root function

### ISSUE THREAD

**Issue by elifarley** [rethinkdb/rethinkdb#3898]
A square root function (perhaps sqrt) could help use cases similar to this, by avoiding the call to r.js:

https://github.com/rethinkdb/rethinkdb/issues/3769#issuecomment-77229538

**Comment by elifarley** [comment]
I've asked @AtnNn for some tips on implementing this.

He suggested me to take a look at [how the UUID term was added] (https://github.com/rethinkdb/rethinkdb/commit/1412cc3a).

The **sqrt** term should probably be added to [src/rdb_protocol/terms/arith.cc] (https://github.com/rethinkdb/rethinkdb/blob/next/src/rdb_protocol/terms/arith.cc)

**Comment by danielmewes** [comment]
@elifarley Oh awesome.
Another good starting point is adding the term to ql2.proto.
Once you do that, compiling RethinkDB should get you lots of compiler errors because of the new value not being handled in enums. This should point you to the places where you need to add code for chaining the new term through.

**Comment by Tryneus** [comment]
I think it would be preferable to add a generic `pow` function, so `val.sqrt()` would be equivalent to `val.pow(0.5)`.  Is there a strong preference for a literal `sqrt` term?

**Comment by elifarley** [comment]
I prefer **val.pow(0.5)**, as it packs more versatility than **sqrt**.

**Comment by grahamjenson** [comment]
I would very much like this as well, as there are so many more possible math applications with data with a power and a sqrt functions.

**Comment by thelinuxlich** [comment]
@srh this should be merged into #1410
