### ISSUE TITLE
`squashing_queue_t` ordering/starvation issue

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3903]
`squashing_queue_t` (which we use to implement `squash: true`) doesn't preserve ordering of changes.  (It just stores them in a big map to squash them together.)  This has two problems:

* It's unintuitive in the simple case where no changes are squashed (how to order changes to different keys when squashing occurs is sort of non-obvious, but if no squashing occurs then the results are very confusing).
* There are starvation problems -- if someone is reading keys almost exactly as fast as the server is generating them, they will never get to the end of the queue, so changes that happen to large `store_key_t`s will basically never be sent.

We should also consider adding a `{state: consistent}` message when `include_states: true` is used that will let you know when you've emptied the squashing queue.  This is important to know because if there are still entries in the squashing queue, then after applying all the changes you've gotten you'll be in a state that might never have existed, but if the queue is empty then you're in a state that the database was in at some point in time.  For example:

```rb
r.table('test').insert({id: 0, a: 0})
r.table('test').insert({id: 1, a: 0})

changes = r.table('test').changes.run

r.table('test').get(0).update({a: 1})
r.table('test').get(1).update({a: 1})
r.table('test').get(0).update({a: 2})
```

If we squash the first and third change together, and you've only received that change, then you'll see a state `[{id: 0, a: 2}, {id: 1, a: 0}]` which never existed in the history of the database, and might be confusing because it violates some constraints you've put on your writes.  (If we put the squashed write after the unsquashed write instead of before the same problem exists in reverse.)  `{state: 'consistent'}` would only be sent after you'd received both the squashed and unsquashed change (because the queue would be empty), and would let you know that you're seeing a state that actually existed at some point.

**Comment by mlucy** [comment]
(Tagged as `RQL_proposal` for the `{state: consistent}` proposal.  I think the first thing is just a bug because of the starvation aspect.)

**Comment by mlucy** [comment]
Any objections to this?  I still think it's a good idea to fix the starvation issue and add a `{state: consistent}` message when `include_states` is `true`.

**Comment by danielmewes** [comment]
It would be nice if we could do without the `{state: consistent}`, but I can see that it's hard to combine with the goals of `squash`.
Hence :+1: for the `{state: consistent}` proposal.

**Comment by VeXocide** [comment]
I agree we should fix the order / starvation issue but have people actually complained about the inconsistent states.? Adding `{state: consistent}` seems to add even more complexity and I'm not convinced it's necessary.

**Comment by danielmewes** [comment]
I think `{state: consistent}` is useful, but it's certainly not a priority for 2.1.
As far as I know nobody has complained about it, but I think it's relevant because it makes squashing changefeeds useful for a set of additional use cases.

**Comment by mlucy** [comment]
It's complexity, but it's the sort of complexity that makes useful things possible, and it isn't on by default.

**Comment by danielmewes** [comment]
Marking as settled for adding a `{state: consistent}` state.

(@VeXocide let me know if you still feel strongly that this isn't a good idea)

**Comment by coffeemug** [comment]
> It's complexity, but it's the sort of complexity that makes useful things possible, and it isn't on by default.

:+1: 

(I hear @VeXocide's argument, though. We had a bit of the discussion on this last night that the `changes` API is getting quite complex. But I think that's ok -- we're *doing* something complex, and still the feature is extremely easy to use, even with all the optargs and different output types)

**Comment by VeXocide** [comment]
@danielmewes I don't feel that this isn't a good idea, mostly wanted to make sure enough thought had been put into whether adding it was necessary and that's certainly the case now.

**Comment by mlucy** [comment]
This turned out to be really easy to fix actually.  In CR 3701 by @Tryneus .

**Comment by Tryneus** [comment]
I'm not sure how useful this would be in practice.  Because of how changefeeds work, this can only guarantee that the client's up-to-date view of a particular shard is consistent, but not for the table as a whole.  Because clients don't (and probably shouldn't) know which shards individual rows are hosted on, `{ state: 'consistent' }` loses a lot of its meaning.

I am not sure, but this may even extend down into hash shards.  If not, users could get some useful guarantees by having an unsharded table, but I think it's unrealistic to expect this feature to be used in such a manner.  Do we have a valid use case for a consistent view in a changefeed where the consistency guarantee only extends to rows in the shard's key space (and maybe even just a hash-shard's hash space)?

**Comment by danielmewes** [comment]
Oh. That's a problem. In that case I really think that we should not expose the `'consistent'` state unless we get concrete requests for it at some point. It would leak a lot of internals if we had to send key ranges with it, and I think we should avoid that.

**Comment by mlucy** [comment]
The 'consistent' state really just means 'there are now no inconsistencies that were introduced by squashing' (i.e. that it's no worse than a nonsquashing changefeed).  That's currently an extremely weak guarantee (although it might theoretically get stronger if we improved the guarantees for nonsquashing changefeeds in the future, which we probably won't).  I would be OK with omitting it if people think it's confusing, though.

**Comment by danielmewes** [comment]
@mlucy So is all squashing performed on the parsing node for the changefeed or does some of it happen on the individual shards?

Assuming that it does work as @mlucy described over all shards, I don't feel strongly about whether we should have that state or not. Though I guess there is a chance for it to be misunderstood, so maybe we should leave it out of 2.1 and think about it more later (or maybe just leave it alone until someone asks for it).

**Comment by mlucy** [comment]
@danielmewes -- all squashing is performed on the parsing node.

@coffeemug, do you have an opinion on whether it should be in or out?  (It's already implemented and trivial to remove, so it's literally just a question of what's best.)

**Comment by coffeemug** [comment]
I think it's valuable to include this state, but I can see how `consistent` can be very confusing. What if we renamed it to communicate more precisely what's going on? For example `squashing_queue_empty`? (@mlucy -- do you have an idea for a better name?)

**Comment by mlucy** [comment]
I talked about this a bit with Daniel, I've changed my mind and I think we should just cut the state.  It provides so few additional guarantees that it's not worth the potential confusion (and in general I think having fewer state documents is probably better).

**Comment by coffeemug** [comment]
I'm ok with that too.

**Comment by mlucy** [comment]
This is in `next`.
