### ISSUE TITLE
Consider making changefeeds not squash by default

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3904]
I was just talking about this with @VeXocide .  Squashing by default only noticeably improves performance in the relatively uncommon case where you have a lot of changes to the same documents within our default window of 100ms.  In exchange for that improvement, we get higher latency and some very confusing behavior vis-a-vis ordering (see e.g. https://github.com/rethinkdb/rethinkdb/issues/3903).

@VeXocide told me that he was confused by the behavior of squashing changefeeds several times while testing, and I think it's probably confusing for normal users too.

@danielmewes -- I realize we're really close to the release, but this is like a 1-line fix and I think it will make changefeeds a lot less confusing for people in 2.0, do you might if we slip it in at the last minute here?

(Also, @coffeemug, any objections?)

**Comment by VeXocide** [comment]
As @mlucy mentions I've been confused by the ordering of the output in writing tests. In my opinion it's better to disable squashing my default now, fix #3903, and then consider enabling it.

**Comment by coffeemug** [comment]
Assuming I understand the issue correctly (switching the default `squash` optarg from `true` to `false`), I have no objections.

**Comment by danielmewes** [comment]
No objections.

**Comment by mlucy** [comment]
This is in next (CR by Jeroen).
