### ISSUE TITLE
Web UI: Modify query return limit in Web UI Settings

### ISSUE THREAD

**Issue by justinmealey** [rethinkdb/rethinkdb#3908]
I'd like to change the (query) `limit` constant in `dataexplorer.coffee` to be a user-configurable variable stored in local storage, similar to `check_update`.  This would be added to the Web UI settings next to automatically looking for new updates, and would just be a simple user input taking an integer.

**Comment by deontologician** [comment]
I think this is a good idea. It's not a super high priority right now, but if you submit a PR we could probably get it into the 2.1 release

**Comment by justinmealey** [comment]
Awesome, will start working on it.
