### ISSUE TITLE
Expose csv module's "delimiter" param for the export command

### ISSUE THREAD

**Issue by elifarley** [rethinkdb/rethinkdb#3916]
Sometimes it's convenient to specify a custom field delimiter when exporting to CSV format.

**Comment by danielmewes** [comment]
That makes total sense.

(@Tryneus)

**Comment by danielmewes** [comment]
Closed by https://github.com/rethinkdb/rethinkdb/pull/3925#issuecomment-83158998 , thank you @elifarley !
Unfortunately it didn't make it into RethinkDB 2.0, but will ship with RethinkDB 2.1.
