### ISSUE TITLE
Fix `table.wait()` and `db.wait()`

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#3922]
In `raft` right now, the implementations of `table.wait()` and `db.wait()` are commented out. They need to be fixed.

**Comment by VeXocide** [comment]
This is being done as part of #3882, and in the same CR 2833 by @timmaxw.

**Comment by VeXocide** [comment]
Merged into `raft` via commit 27c3c372ddca5d2f12bc1ea108576c770cf0c078.
