### ISSUE TITLE
IPv6's zone index in rethinkdb_status

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#3923]
I have this IP reported in `rethinkdb_status`: `fe80::8e70:5aff:feff:a408%2`

I don't know much about IPv6 (or close to nothing), but it looks like the `%2` is the way Windows report the index (see http://en.wikipedia.org/wiki/IPv6_address). Linux uses the name of the interface.

In my case I had to use `fe80::8e70:5aff:feff:a408%wlp3s0` to RethinkDB.

```
michel@xone:~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 8c:70:5a:ff:a4:08 brd ff:ff:ff:ff:ff:ff
    inet 192.168.42.168/24 brd 192.168.42.255 scope global dynamic wlp3s0
       valid_lft 82970sec preferred_lft 82970sec
    inet6 fe80::8e70:5aff:feff:a408/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by neumino** [comment]
Side note: The node driver needs to provide the `family` field (with IPv6) in `net.connect` for this to work (with `%wlp3s0`).

**Comment by Tryneus** [comment]
For the record, link-local addresses are really weird, and you probably shouldn't be connecting to anything besides 'localhost' through them (unless you have a very carefully provisioned network).  I'm not very familiar with them, but from what I can find, routers do not forward packets destined for link-local addresses.

I tested this in python, and connecting to a link-local address on localhost works fine with either `%2` or `%eth0` (e.g.).  Is there a problem in node that keeps this from working?

I'm not sure if there is an easy way to convert from the scope ID to the interface name - I vaguely remember looking into this before and giving up.  Perhaps we should just not report link-local addresses in `rethinkdb_status`, but that may be overkill.

**Comment by neumino** [comment]
So the reason why I found out what these indices was because I'm trying to implement a connection pool that automatically connect to RethinkDB instances.
And because of a bug in the way I was picking the "main" address, I ended trying at some point to connect using this IPv6.

So in node from what I could find, you need to pass the name of the interface
https://github.com/joyent/node/issues/7395
It may just be a limitation of node though.

I'll just try to avoid IPv6 for now in the connection pool, so feel free to close or put in backlog, especially since like you said, these link-local addresses are weird :)

**Comment by danielmewes** [comment]
What does that interface after the address mean when connecting?
For a link-local address I would expect it to specify the interface on the *client* to use for reaching that link-local address. So the server's interface wouldn't help you anyway. I might be completely wrong about this.

@neumino You could filter link-local addresses by removing those starting with `fe80::` (source http://en.wikipedia.org/wiki/Link-local_address#IPv6 )

**Comment by danielmewes** [comment]
@neumino @Tryneus Can I close this?

In my understanding of what the interface of a link-local address means, it wouldn't make much sense to change the format on the server. I think on the client you need to replace the interface by the client's interface name in any case, since the server cannot know how the corresponding interface on the client is called or which number it has (how would the server know which interfaces the client has in the first place?).
I might be misunderstanding how link-local addresses work though.

**Comment by Tryneus** [comment]
@danielmewes, I think so, I suspect this issue was due to misuse of link-local addresses.
