### ISSUE TITLE
r.whoami()

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#3934]
It's similar to what was mentioned in https://github.com/rethinkdb/rethinkdb/issues/2979 but my use case is a bit different. I'm trying to have the connection pool in rethinkdbdash automatically populates connections to all the servers listed in the table `server_status`.

And one problem that surfaces is that people may try to populate the pool from `localhost`. I have one pool per server (and a "master" that manage all these pools). Since `localhost` will match all the servers, I can't know exactly in which pool I should put these connections.

I'm working around this by opening new connection to not localhost (by picking up the "wider" address and closing the one to localhost, but being able to run `r.whoami()` and get a server id would make the code way more simple.
If the server id can be returned at the end of the handshake, that would also work for me.

**Comment by deontologician** [comment]
+1 this is the last special /ajax functionality the webui is using (beyond the http reql connections)

**Comment by mlucy** [comment]
@danielmewes -- putting this in 2.1 so it's in a milestone and we don't forget about it, but feel free to move it out if there isn't room.

**Comment by danielmewes** [comment]
There was some relevant discussion about this in https://github.com/rethinkdb/rethinkdb/issues/2979

We should consider exposing this functionality as a function on the connection object instead of a ReQL term I think, like discussed over there.

**Comment by timmaxw** [comment]
Yeah, I definitely think this should be a method or variable on the connection rather than a ReQL term.

**Comment by danielmewes** [comment]
To bring something else over from the other thread: I really prefer the name `conn.server_uuid()` over `conn.whoami()`.

**Comment by timmaxw** [comment]
I think `server_id` is better, for consistency with the system tables.

**Comment by danielmewes** [comment]
Sure, `server_id` sounds good.

**Comment by coffeemug** [comment]
:+1: for `conn.server_id()`

**Comment by deontologician** [comment]
to clarify, will this return the uuid of the server, the server name, or the hostname of the server?

**Comment by timmaxw** [comment]
This will return the UUID of the server as a string.

**Comment by timmaxw** [comment]
Also, it's not a query. So if you run `>>> conn.server_id()` in the Python console, it just returns the UUID as a string. You don't write `conn.server_id().run(conn)` or anything like that.

**Comment by deontologician** [comment]
It'd be super super nice if I could get the server name as well without having to query server_config

**Comment by mlucy** [comment]
What if we had `conn.server()` and it returned `{name: X, id: Y}`?

**Comment by timmaxw** [comment]
If `conn.server()` internally compiles to `r.secret_magic_whoami().run(conn)`, then that's easy. If `conn.server()` returns the value of a local variable that was transmitted during the handshake, then that's difficult.

**Comment by Tryneus** [comment]
It doesn't *have* to be a term, we have NOREPLY_WAIT as a query-type rather than a term-type, we could add another query-type SERVER_INFO or something.

**Comment by coffeemug** [comment]
> What if we had `conn.server()` and it returned `{name: X, id: Y}`?

:+1: (assuming implementing this isn't too painful).

**Comment by danielmewes** [comment]
I think either `conn.server_id()` or `conn.server()` would be sufficient.
I think we should implement the latter with `{name: X, id: Y}` if it's about the same amount of work, and the former returning only the ID if it's easier.

**Comment by VeXocide** [comment]
A `conn.server_id()` sounds good.

**Comment by danielmewes** [comment]
Marking settled with `conn.server_id()`, or `conn.server()` if it's similarly easy to implement.

**Comment by mglukhovsky** [comment]
This would be really useful for the web UI, and for `rethinkdb import` (see #4617).

**Comment by dancannon** [comment]
Would also be really useful for gorethink, currently the way I am checking host status is a bit hacky.

**Comment by encryptio** [comment]
in review with @VeXocide, CR 3317

**Comment by dancannon** [comment]
This is great, Thanks for the work guys!

**Comment by encryptio** [comment]
Done in `next`, will be in 2.2.
