### ISSUE TITLE
Data Explorer not showing any results

### ISSUE THREAD

**Issue by VeXocide** [rethinkdb/rethinkdb#3935]
When an old set of `options` is set in Local Storage such as
```
{"suggestions":true,"electric_punctuation":false,"profiler":false,"undefined":false}
```
the Data Explorer will not show any results until you've manually set it in the options, changing the key to
```
{"suggestions":true,"electric_punctuation":false,"profiler":false,"undefined":false,"query_limit":40}
```
. Instead it will show an empty Tree view and show "Waiting for more results" in Table view.

**Comment by deontologician** [comment]
talking about it, I think a good solution that will stave off this kind of bug in the future is to do an _.extend() on localStorage with the defaults whenever starting up.

**Comment by deontologician** [comment]
up in CR 2717 by @VeXocide . I'll have to port it to the v2.0.x branch and to the josh/3660 branch since it will be a merge conflict.
