### ISSUE TITLE
STOP queries not properly interrupting changefeeds

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3938]
See https://github.com/rethinkdb/rethinkdb/issues/3296#issuecomment-79960767

**Comment by mlucy** [comment]
Also, we shouldn't consider it an error when we get a `STOP` query for a token not in the cache, since when the user sends the `STOP` query they don't know whether the token will still be in the cache or not by the time it arrives.

**Comment by mlucy** [comment]
Actually, @Tryneus, is there any chance you'd be willing to take this?  I forgot when I originally assigned this to myself that you'd rewritten this part of the code last.

**Comment by Tryneus** [comment]
@mlucy - I can take this.  I think the best solution would be for STOP queries to inherently be noreply, but seeing as it's a little late for that, we should just always have them succeed (barring malformed queries or protocol errors).

**Comment by Tryneus** [comment]
The fix has been merged to `next` in commit 041838a, and cherry-picked into `v2.0.x` in commit 5c82f5c.  Review was 2734.  Will be in release 2.0.
