### ISSUE TITLE
Point changefeeds on `r.db('rethinkdb').table('_debug_scratch')` behaving oddly

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3944]
This is causing `point.yaml` to fail in a lot of interesting ways in next.

**Comment by mlucy** [comment]
If I do the following:
```rb
dtbl = r.db('rethinkdb').table('_debug_scratch')
dtbl.insert({id: 5, red: 1, green: 1}, conflict: 'replace').run
dtblPluck = dtbl.get(5).changes().run
it = dtblPluck.each
PP.pp it.next
dtbl.get(5).update({blue: 2, green: 3}).run
PP.pp it.next
```

Then I sometimes see this:
```rb
{"new_val"=>{"green"=>1, "id"=>5, "red"=>1}}
{"new_val"=>{"blue"=>2, "green"=>3, "id"=>5, "red"=>1},
 "old_val"=>{"green"=>1, "id"=>5, "red"=>1}}
```

Sometimes this:
```rb
{"new_val"=>{"green"=>1, "id"=>5, "red"=>1}}
{"new_val"=>{"green"=>1, "id"=>5, "red"=>1},
 "old_val"=>{"blue"=>2, "green"=>3, "id"=>5, "red"=>1}}
```

And sometimes this:
```rb
{"new_val"=>{"green"=>1, "id"=>5, "red"=>1}}
# HANGS FOREVER
```

If I put `sleep 0.2` after each `run` I only ever see the first result (which is also the result I'd obviously expect).

@timmaxw -- my current guess is that this is a bug in the `debug_scratch` table, would you be willing to take this issue?

**Comment by timmaxw** [comment]
Yes, I'll look into it.

**Comment by timmaxw** [comment]
In CR 2725.

**Comment by timmaxw** [comment]
Merged into `next` in 5b61836ea72f80f6b26029d1b5e75cd4f5bd2f1a.

**Comment by mlucy** [comment]
@timmaxw -- is it in `next` as well?

**Comment by timmaxw** [comment]
Yes, it's in `next` too.
