### ISSUE TITLE
ql2.proto: 0-arity r.literal

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3947]
The type signature in ql2.proto is omitting the fact that `LITERAL` can be used with zero arguments
https://github.com/rethinkdb/rethinkdb/blob/next/src/rdb_protocol/ql2.proto#L699

Related to https://github.com/rethinkdb/docs/issues/681

**Comment by VeXocide** [comment]
In CR 2744 by @danielmewes

**Comment by VeXocide** [comment]
Merged into `next` via commit a26e46e9c2d5be1e7665c2e8f6d28d1484801437 and into `v2.0.x` via commit  19174be22c72fe5c678cb6f0bf70f294ea4769df
