### ISSUE TITLE
error: use of deleted function 'http_opts_t::http_opts_t(http_opts_t&&)'

### ISSUE THREAD

**Issue by orthecreedence** [rethinkdb/rethinkdb#3956]
Hey everyone, I'm seeing this while compiling branch `v1.16.x`:
```
    [219/373] CC build/release/obj/rdb_protocol/terms/http.o
src/rdb_protocol/terms/http.cc: In constructor 'ql::http_datum_stream_t::http_datum_stream_t(http_opts_t&&, counted_t<const ql::func_t>&&, int64_t, const ql::protob_t<const Backtrace>&)':
src/rdb_protocol/terms/http.cc:146:35: error: use of deleted function 'http_opts_t::http_opts_t(http_opts_t&&)'
In file included from src/rdb_protocol/terms/http.cc:12:0:
./src/extproc/http_runner.hpp:76:5: note: 'http_opts_t::http_opts_t(http_opts_t&&)' is implicitly deleted because the default definition would be ill-formed:
./src/extproc/http_runner.hpp:76:5: error: non-static data member 'http_opts_t::url_params' does not have a move constructor or trivial copy constructor
make[1]: *** [build/release/obj/rdb_protocol/terms/http.o] Error 1
make: *** [make] Error 2
```

I'm on Slackware 14.0 (3.2.29) x86_64 GCC 4.7.1. Any ideas? Thanks!

**Comment by mlucy** [comment]
@VeXocide -- I remember you mentioned to me the other day that you were deleting some unused code, is it possible this is a result of that?

**Comment by Tryneus** [comment]
I really doubt that was merged to the `v1.16.x` branch.

**Comment by VeXocide** [comment]
@mlucy -- those changes weren't merged to the `v1.16.x` branch.

Here's my suspicion, currently `ql::datum_t` doesn't have a move constructor, but does have a user-defined destructor which means a move constructor won't be automatically added. There's a `ql::datum_t http_opts_t::url_params` which probably means that `http_opts_t` isn't movable either.

However, I wasn't able to reproduce this error using GCC 4.9.

**Comment by VeXocide** [comment]
@AtnNn just installed GCC 4.7.4 for me on one of the development servers and it compiled `v1.16.2` fine, thus I'm leaning towards this being a GCC 4.7.1 bug.

**Comment by AtnNn** [comment]
It could be [this one](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53733) which was fixed in gcc 4.7.2

**Comment by VeXocide** [comment]
That looks quite plausible.

**Comment by orthecreedence** [comment]
Guess it's time to upgrade GCC =]. Thanks for the quick response, everyone.

**Comment by danielmewes** [comment]
@orthecreedence we saw Slackware 14.1 had a much newer version of GCC, which will likely work fine. Not sure if upgrading is an option for you?

We could theoretically work around this issue in our code, but it would require some testing and wouldn't make it into 2.0. I think it's not worth doing at the moment.

**Comment by orthecreedence** [comment]
I'd rather not force you to code in a style that works around my old gcc...let's keep things on your side as clean as possible =]. I'm working on upgrading to 14.1 (not a problem).
