### ISSUE TITLE
Python driver should print first few results of cursor if they aren't too large.

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3965]
When the Ruby driver prints a cursor, it shows the first few elements of the cursor.  This is extremely useful for interactive use.  I think the Python driver should do the same thing.

**Comment by mglukhovsky** [comment]
Agreed, this would be amazing!

**Comment by Tryneus** [comment]
This has been implemented, reviewed, and merged to `next` in commit 039c896.  Review was 2739.  Will be in release 2.1.

```
> cursor = r.range(1000).run(conn)
> print(cursor)
<rethinkdb.net.DefaultCursor object at 0x10b0910> (streaming):
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, ...]
> cursor.next()
0
> conn.close()
> print(cursor)
<rethinkdb.net.DefaultCursor object at 0x10b0910> (error: RqlRuntimeError('Connection is closed.')):
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ...]
```

**Comment by mlucy** [comment]
@Tryneus -- is this a 2.1 thing or a 2.0 thing?

**Comment by Tryneus** [comment]
@mlucy, this issue is in the 2.1 milestone and didn't seem necessary for the release branch, so I didn't merge it to `v2.0.x`.  If you need it for testing on 2.0, feel free to merge it, it's a very localized diff.

**Comment by mlucy** [comment]
OK, cool.  This is in 2.0.x now too.  Moving the milestone to indicate that.  (Thanks for implementing this so quickly!)
