### ISSUE TITLE
[2.0RC]Js driver - feed.close() should send the STOP query without waiting

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#3967]
It's the second part of https://github.com/rethinkdb/rethinkdb/issues/3938
IIn the JS driver, `feed.close()` does not immediately send the `STOP` query, see
https://github.com/rethinkdb/rethinkdb/blob/next/drivers/javascript/cursor.coffee#L190

Typically this will hang (assuming no operation is happening on the table `test`).
```js
r = require('./rethinkdb.js'); // 2.0RC driver

r.connect().bind({}).then(function(connection) {
  this.connection = connection;
  return r.db('test').table('test').changes().run(this.connection);
}).then(function(feed) {
  feed.each(function(err, change) {
    if (err) {
      console.log('ERROR');
      console.log(err);
    }
    else {
      console.log(change);
    }
  });
  return feed.close();
}).then(function() { // never called here.
  console.log('Feed was successfully closed.');
  return this.connection.close();
}).then(function() {
  console.log('Connection was successfully closed.');
}).error(function(err) {
  console.log('ERROR');
  console.log(err);
});
```

The logic related to `closeAsap` should be removed, and the driver should accept to send a `STOP` query even if a `CONTINUE` query is going on. It requires a bit of refactoring since the driver currently assumes one query per token.

I don't know if there's the same problem in the python and ruby driver, but someone should probably take a look.

**Comment by danielmewes** [comment]
Good catch.

Just to clarify: This used to work well enough since every request to a feed would time out after 0.5s (though it was still not great). With 2.0 changefeeds don't time out quickly anymore, so this script can lock for a long time.

@Tryneus I think you had changed the server such that STOP queries are always processed hadn't you? Do you know if the Python and Ruby drivers handle this correctly?

Assigning @deontologician for the JS driver fix.

**Comment by Tryneus** [comment]
@danielmewes, the Ruby and Python drivers will send a STOP query immediately.  The Ruby driver ignores unknown tokens (since there may be both a CONTINUE and a STOP pending for the cursor's token), and the Python driver keeps track of how many outstanding queries there are, and waits until all responses have been collected before unregistering the Cursor object.

**Comment by danielmewes** [comment]
@Tryneus ah great, thanks for the info. So we only need to fix the JS driver...

**Comment by deontologician** [comment]
Alright, after looking at this today, as far as I can tell the @_closeAsap stuff isn't hurting anything. If we just launch a `STOP` immediately upon `cursor.close()`, we should be ok. Any outstanding `CONTINUE` queries will get their callbacks run, and everything should be ok. From what I can tell, the `@_cbQueue` is specifically for this issue where multiple queries are out at once for the same token.

@neumino thoughts?

**Comment by neumino** [comment]
@deontologician -- It's slightly a bit more tricky.

You can have the cursor with a pending `CONTINUE` query meaning that the object `outstandingCallbacks[token]` will have a `cb` field mapping to a function.

If you directly send `STOP`, you need to save the callback somewhere (you can't just overwrite `cb`, so you probably want to add a new field like `endCb`).
Then you will get twice `SUCCESS_SEQUENCE` (for the same token) with an empty response, so you have to make sure that it doesn't break the driver.

**Comment by deontologician** [comment]
The `cb` field for queries that return `SUCCESS_PARTIAL` is only called when the cursor is first created. After that, the connection only calls _addResponse when a new response comes in for the token.

Internally, the cursor keeps track of how many queries are outstanding for that token and increments or decrements `_outstandingRequests` as necessary. The connection only deletes the cursor if `_endFlag` is set and `cursor._outstandingRequests` is 0.

I need to make sure tokens coming in after the cursor is removed from the cache won't disrupt anything, but in my ad-hoc tests this seems to be working

**Comment by deontologician** [comment]
Up in CR 2753 by @Tryneus

**Comment by danielmewes** [comment]
@AtnNn this is the one that got fixed in the JS driver post RC1.
