### ISSUE TITLE
Change Ruby driver to check `arity < X` rather than `arity == -1`

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#3968]
Apparently you can sometimes have an arity of `-2`.

**Comment by danielmewes** [comment]
What's the context of this?

**Comment by mlucy** [comment]
There are a two places where we have predicates like `x.arity == 2 || x.arity ==-1`; they should probably be of the form `x.arity == 2 || (x.arity < 0 && x.arity > -3)`.  `lambda{|*a|}.arity` returns `-1`, and I just learned that `lambda{|a,b,*c|}.arity` returns `-3`.

(I think the only place we do this is in the new EM integration, so the only noticeable impact is that if someone overloaded a `RethinkDB::Handler` function with a function that accepts both a normal and a rest argument we'd erroneously refuse to call it.)

**Comment by danielmewes** [comment]
Ah I see, thanks.

**Comment by mlucy** [comment]
In CR 2777 by @Tryneus .

**Comment by mlucy** [comment]
This is in next and 2.0.x.
