### ISSUE TITLE
r.row behavior changes on next

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#3970]
Not sure if this is a bug or intended, but it seems this behavior has changed in next vs. 1.16 at least (and probably vs. 2.0.x)

```js
r.expr({}).merge(r.row)
```

In 1.16 this returns `{}`, on next it returns the error:

```
t: r.row is not defined in this context in:
r({}).merge(r.row)
            ^^^^^ 
```

**Comment by mlucy** [comment]
That seems like a bug to me.

**Comment by deontologician** [comment]
I should clarify, @atnnn said this bug was not on 2.0, but I haven't checked myself

**Comment by danielmewes** [comment]
We should double-check that it's working in 2.0. On a quick pass over a diff between `v2.0.x` and `next` I didn't spot anything suspicious.

**Comment by deontologician** [comment]
Ok, after doing a full clean and build on both next and v2.0.x I can't replicate this. I'm going to chalk this up to some artifact in my build directory
