### ISSUE TITLE
Minor doc issue: Document that nth accepts negative indexes

### ISSUE THREAD

**Issue by mkleehammer** [rethinkdb/rethinkdb#3973]
Through trial and error I see that `nth(-1)` returns the last item in a sequence.  (That is intended, right?)  That would be useful to add to the API and Cookbook.

Thanks.

**Comment by danielmewes** [comment]
Good catch @mkleehammer. I moved your issue to our "docs" repository https://github.com/rethinkdb/docs/issues/690
