### ISSUE TITLE
Preparing RethinkDB 1.16.3

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#3979]
Will contain fixes for the issues in the [1.16.3 milestone](https://github.com/rethinkdb/rethinkdb/issues?q=milestone:1.16.3), most notably #3969 and #3976

**Comment by danielmewes** [comment]
I'd also like to include https://github.com/rethinkdb/rethinkdb/issues/3954.
I'm going to re-run the tests on gantz.

**Comment by danielmewes** [comment]
The tests are fine.
I had some new timeouts at first, but it looks like they were because of stray processes on gantz using up all memory.

**Comment by AtnNn** [comment]
The packages for 1.16.3 are now available
