### ISSUE TITLE
Admin console page reload in Safari

### ISSUE THREAD

**Issue by ftKnox** [rethinkdb/rethinkdb#3983]
Seems there is a infinite page reloading issue with at least version 8.x of safari and the web admin console. (I could not get this to happen with firefox or opera.) It seems to happen randomly while navigating through the admin console. One way to trigger it is to open the main page, stop the rethinkdb server and wait untill the disconnected message appears in the browser. Once you see that, start rethink back up and it should trigger the issue. If necessary, I can provide a screen capture.

```javascript
Javascript Console repeats the following output:
[Error] Failed to load resource: The network connection was lost. (open-new-connection, line 0)
[Log] Connection lost. Retrying. (cluster-min.js, line 12205)
[Error] Failed to load resource: The network connection was lost. (reql, line 0)
[Log] Connection lost. Retrying. (cluster-min.js, line 12205)
[Error] Failed to load resource: The network connection was lost. (reql, line 0)
[Error] Failed to load resource: The network connection was lost. (open-new-connection, line 0)
```

**Comment by deontologician** [comment]
Hi @ftKnox, thanks for the bug report.

What is version of RethinkDB are you running, and what version of safari?

**Comment by ftKnox** [comment]
rethink: 1.16.2
safari: 8.0.4

**Comment by deontologician** [comment]
OK, working on this now

**Comment by deontologician** [comment]
@ftKnox I can't seem to replicate this. Could you try to replicate it on your system in Chrome or Firefox?

**Comment by ftKnox** [comment]
i have two separate OS X machines that exhibit the issue. I cannot replicate in firefox or chrome on either machine. I also had a colleague check on his macbook and it exhibits the same issue in safari 8.0.4.

**Comment by ftKnox** [comment]
i also tried the latest 1.16.3 rpms on a centos 7 vm to make sure it wasn't just my install.

**Comment by deontologician** [comment]
OK cool, thanks a lot for checking in to it. I'm going to try again tomorrow to replicate it. Since it doesn't seem you're having a problem replicating the problem in other machines, is the procedure you outlined above (shutting down and restarting the server) what triggers it for you?

**Comment by ftKnox** [comment]
@deontologician Its doesn't happen 100% of the time, but its greater than 50%. Just clicking around in the interface (typically on tables is where I notice it most) also triggers this behavior. Also note, that I access my admin panel by ip AND or a hostname aliased in my /etc/hosts file. Maybe something in the way the url router parses?

**Comment by ftKnox** [comment]
@deontologician Here is a sweet gif of the issue. You can see in the video how annoying it is to have to click into the url bar between reloads and click stop. I then typically have to add an "/" to the url to get it to reload correctly.
 
![safarireloadissue](https://cloud.githubusercontent.com/assets/11303823/6922819/20326e6e-d78b-11e4-8af4-223c3ef6c7e9.gif)

**Comment by mglukhovsky** [comment]
@ftKnox: just to be clear, how are you running RethinkDB? (e.g. from your local machine, via a Docker instance, on a VPS, or over an SSH tunnel)

**Comment by ftKnox** [comment]
@mglukhovsky rethinkdb is running in a standard lxc container (not created via docker) on a separate host.

**Comment by ftKnox** [comment]
@mglukhovsky i just tried the 1.15.3 rpms and i can't seem to trigger this in that version.

**Comment by ftKnox** [comment]
@mglukhovsky 1.16.0-1 rpms seem to be fine as well, 1.16.1 seems to be where the issue starts

**Comment by mglukhovsky** [comment]
@ftKnox: thanks for narrowing it down! @deontologician, let me know if you're having trouble reproducing this given the new information.

**Comment by deontologician** [comment]
Yeah, this is great stuff. I found the commit that's the likely cause. It was actually intended to fix another Safari issue with stale http connections

**Comment by deontologician** [comment]
Hey @ftKnox would it be possible for you to share your exact lxc configuration, along with how the computer with the issue is connected to the computer hosting the container? Is it on the same subnet, or is it external etc.

**Comment by ftKnox** [comment]
@deontologician Sorry for the delay, did some testing.

Same subnet:
container: no issue
bare metal: no issue

Different Internal Subnet:
container: triggers issue
bare metal: triggers issue

Public Ip:
container: triggers issue
bare metal: triggers issue

**Comment by deontologician** [comment]
I've tried through a public ip now, but I still can't replicate it. So what I'm going to do is make a couple of zip files with the web assets compiled into them, with different possible solutions in each one. You can specify the web assets directory with a command line flag. Would you be willing to try that @ftKnox ?

**Comment by deontologician** [comment]
Ok, I decided to go back to the drawing board and to look at the facts again from scratch. I noticed something very interesting, which was that the error I was getting in Safari 8 when I shut down the server was not the same as the error you were getting.

```
[Error] Failed to load resource: The network connection was lost.
```

Apparently, this is triggered in safari when a response with a Content-Length header longer than the content body is received. Safari assumes it is just missing the rest of the data and errors out. Other browsers will render the content, but may or may not put an error into the console.

@ftKnox could you try to replicate it again in Chrome, but check the console? Chrome shouldn't fail if this is the issue, but will output an error to the console.

**Comment by ftKnox** [comment]
@deontologician sure I can do that, and to clarify, restarting of rethinkdb was just an easy way to trigger the issue. It also happens randomly when utilizing the web admin in safari.

Below is the only error I see in the chrome console.

```javascript
Connection lost. Retrying.               cluster-min.js?v=1.16.3:12205
```

**Comment by ftKnox** [comment]
@deontologician here is another gif demonstrating the random issue when clicking through the interface. (the click speed is exaggerated, but the issue happens no matter the click speed). 

![safarireloadissue2](https://cloud.githubusercontent.com/assets/11303823/7076166/b83ba1d6-dec4-11e4-97b0-5ebbdd75802a.gif)

**Comment by deontologician** [comment]
So, I was able to replicate this by randomly modifying the `Content-Length` header, so that every 10 requests or so it will be too long.  Then when the ui reconnects, it loads everything and this triggers another disconnect since so many requests are happening at once.

This might happen if you have a firewall or other network equipment that is maybe mucking with http headers. Since the web ui doesn't use https, it's vulnerable to this kind of thing.

@danielmewes suggested since we have a custom http server, it's possible something we are doing is triggering the firewall and that's what's causing the response to fail. @ftKnox would it be possible for you to do a [wireshark](www.wireshark.org) capture of your network traffic while you're interacting with the webui, until a failure happens? [Instructions are here](https://www.wireshark.org/docs/wsug_html_chunked/ChapterCapture.html). We could analyze the results of that and see if anything about the individual requests is special

**Comment by ftKnox** [comment]
@danielmewes I just tested the latest 2.1.0 and this issue is no longer occurring. So either a newer version of safari fixed this or the latest release did. In either case, thanks for the work on this!

**Comment by danielmewes** [comment]
Thanks for the update @ftKnox ! Let us know if you observe anything like this again.

Closing as outdated.

**Comment by Geocloud** [comment]
I have this error with Safari and the last version of RethinkDB
QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.

**Comment by danielmewes** [comment]
Re-opening. @definitelycarter ran into this with a 2.2.5 server hosted on Azure.
It happens reliably on his server with Safari (including the version on the iPhone), but not with Firefox or Chrome.

**Comment by danielmewes** [comment]
I've been able to even reproduce this with a server running locally (on newton). It doesn't happen as quickly, but if I click around in the web UI a little it eventually gets into the state.

**Comment by danielmewes** [comment]
A work-around on the server side seems to be disabling HTTP connection re-using (keepalive). I'd prefer to find out what our webserver does wrong that breaks this with Safari, but in the worst case we could disable it depending on the browser.

**Comment by DefinitelyCarter** [comment]
Just wanted to note that the web ui works in safari when using the official rethinkdb docker image.  
Maybe the keep alive setting is disabled by default in the rethinkdb docker image?

**Comment by danielmewes** [comment]
@DefinitelyCarter Thanks for the note. It's not generally disabled on Docker. I think whether this issue occurs or not depends on the network conditions and on the server load, though we don't understand what's causing it exactly yet.

**Comment by nighelles** [comment]
A fix to disable keepalive on Safari is in next and v2.3.x, in 1cddc64 and a03c94b.
