### ISSUE TITLE
MacOS X launchd script set to incorrect permission in documentation

### ISSUE THREAD

**Issue by leibowitz** [rethinkdb/rethinkdb#3984]
The section `Startup with launchd (OS X)` on the [start-on-startup documentation page](http://rethinkdb.com/docs/start-on-startup/) mentions these instructions:
```
sudo chown root:wheel /Library/LaunchDaemons/com.rethinkdb.server.plist
sudo chmod 622 /Library/LaunchDaemons/com.rethinkdb.server.plist
```

When trying to load this plist file using 
```
launchctl load /Library/LaunchDaemons/com.rethinkdb.server.plist
```
it is complaining with 
```
launchctl: Dubious permissions on file (skipping): /Library/LaunchDaemons/com.rethinkdb.server.plist
```

Replace the 622 with 644, and problem solved.

Wasn't sure where to report this so thought the github issues would be a good place to start - please let me know if there is a better place to report documentation issues

**Comment by danielmewes** [comment]
Thanks @leibowitz for the report! I'm going to move this over to our separate issue tracker for documentation. We'll take care of it asap.

**Comment by danielmewes** [comment]
-> https://github.com/rethinkdb/docs/issues/693
