### ISSUE TITLE
Creating multiple tables at once

### ISSUE THREAD

**Issue by knownasilya** [rethinkdb/rethinkdb#3985]
Is there a way to do that?

**Comment by Tryneus** [comment]
This should work (in Python):

```py
r.expr(['foo', 'bar']).for_each(r.table_create(r.row)).run(c)
```

If you wanted to create them in separate databases:

```py
r.expr([['db_1', 'foo'], ['db_2', 'bar']]).for_each(r.db(r.row[0]).table_create(r.row[1])).run(c)
```

This assumes that the databases already exist beforehand - it gets a little more complicated if you're also creating the databases in the same query.

**Comment by danielmewes** [comment]
@knownasilya does @Tryneus response answer your question?

We could make `tableCreate` variadic, but I think it's not very important at the moment.

**Comment by knownasilya** [comment]
@danielmewes it worked for me, hopefully it'll be more straight forward in the future.
