### ISSUE TITLE
Admin console: update checking does not support HTTPS

### ISSUE THREAD

**Issue by stuartpb** [rethinkdb/rethinkdb#3988]
Accessing my RethinkDB admin console through an HTTPS proxy:

> Mixed Content: The page at 'https://admin.example.com/' was loaded over HTTPS, but requested an insecure script 'http://update.rethinkdb.com/update_for/1.16.0-1?callback=jQuery1720892887496156618_1427682104192&_=1427682110244'. This request has been blocked; the content must be served over HTTPS.

It's a little weird that this is being loaded via PJSON (can't update.rethinkdb.com support CORS?), but if anything is getting requested from update.rethinkdb.com, it should be via HTTPS. (I just checked, and apparently update.rethinkdb.com doesn't support HTTPS.)

**Comment by mlucy** [comment]
@mglukhovsky

**Comment by danielmewes** [comment]
@stuartpb Does the warning go away if you disable update checking in the web UI?
(click on the gear icon between "Logs" and the "Search" box)

In the long term we should get rid of the update check in the UI and instead use the information from the server's update checking mechanism.

That being said, I don't know anything about CORS. Is that easy to use? Would it avoid the issue for now?

This is also related to https://github.com/rethinkdb/rethinkdb/issues/3489

**Comment by mglukhovsky** [comment]
@stuartpb: adding CORS might make sense, but since it's just a basic GET request, we used JSONP. We'll also be deploying HTTPS on the update server in the near future.

**Comment by stuartpb** [comment]
@danielmewes CORS is pretty easy (it's pretty much just an extra `Access-Control-Allow-Origin: *` header, which allows you to read the response with an XMLHttpRequest, even if it's cross-origin). If your server is written with Express, you can enable it by using the [ach](https://github.com/stuartpb/ach) middleware.

**Comment by danielmewes** [comment]
Fixed by 6a06e7fb4d2a8ad7d2237957011620882634091f in v2.1.x and c237672e238f437b44e1008da2b2ae1b9f1df9fa in next. The check now uses `https`.
