### ISSUE TITLE
Array append is much slower for primitive values than objects

### ISSUE THREAD

**Issue by Zolmeister** [rethinkdb/rethinkdb#3991]
There is a `4x` performance difference between appending an object vs a primitive
(object is faster than primitive)

```js
// 12ms
r.table('table').get(id).update({
  array1: r.row('array1').default([]).append(
   {id: '123'} //object
  )
}).run();

// 48ms
r.table('table').get(id).update({
  array2: r.row('array2').default([]).append(
    '123' // string
  )
}).run();
```

**Comment by danielmewes** [comment]
Thanks for reporting this @Zolmeister .
How consistent is this if you run the query multiple times? Do you get the same difference in runtime if `array1` and `array2` are empty?
How many entries did they previously have?

I find it pretty hard do imagine that the append operation itself could make a difference of 36ms. So I wonder if one of them just happened to go over some size boundary (e.g. the btree inline value size) making the disk write slower.

**Comment by Zolmeister** [comment]
This was done with a clean database (multiple times (>10), in our test-suite)
The timings are the average of ~50 calls, but the standard deviation is small

**Comment by danielmewes** [comment]
@Zolmeister I'm unable to reproduce any difference in performance between those queries so far.
Are the documents otherwise empty in these cases? Do you get the same results if you run these two tests in the opposite order?

**Comment by Zolmeister** [comment]
I should also clarify a few points:
  - I am using rethinkdbdash (https://github.com/neumino/rethinkdbdash)
  - I am using version 1.16.2-1

I verified that the order of the tests did not matter.

Sorry, I won't be able to get back to this for a few days, but when I do I'll try and set up a clean environment and let you know

**Comment by danielmewes** [comment]
Thanks for the info @Zolmeister . Looking forward to your update in a few days.

I had tested with 1.16.3 and a different driver, but I would be very surprised if that made such a big difference.

**Comment by Zolmeister** [comment]
My apologies,
After further isolation the results indicate no slowdown due to primitives

Thanks for taking the time

**Comment by danielmewes** [comment]
Thanks for looking into it again @Zolmeister and letting us know.
Did you find out what caused these differences? I'm just curious.

**Comment by Zolmeister** [comment]
No, unfortunately I lost the test case that produced the results, and upon re-writing the tests could not reproduce.
