### ISSUE TITLE
order_by changes uses reversed order

### ISSUE THREAD

**Issue by jkarneges** [rethinkdb/rethinkdb#3993]
Using 2.0.0-0RC1 and Python driver 1.16.0-0.

I have a table of objects with name and score fields. Here's code to print a normal query and then a changes query:

```python
results = r.table('test').order_by(index=r.desc('score')).limit(3).run(conn)
for row in results:
        print row

results = r.table('test').order_by(index=r.desc('score')).limit(3).changes().run(conn)
for row in results:
        print row
```

And here's the output:

```
{u'score': 12, u'id': u'08790f3b-b18f-4afd-9197-72992d506546', u'name': u'henry'}
{u'score': 11, u'id': u'bb7e37c2-ecc4-4be8-9584-7901bf488007', u'name': u'george'}
{u'score': 10, u'id': u'ac534e45-f6c8-4415-9d60-94dbff6ee5d1', u'name': u'alice'}
{u'new_val': {u'score': 10, u'id': u'ac534e45-f6c8-4415-9d60-94dbff6ee5d1', u'name': u'alice'}}
{u'new_val': {u'score': 11, u'id': u'bb7e37c2-ecc4-4be8-9584-7901bf488007', u'name': u'george'}}
{u'new_val': {u'score': 12, u'id': u'08790f3b-b18f-4afd-9197-72992d506546', u'name': u'henry'}}
```

I would have expected the ordering to be the same in both cases.

**Comment by danielmewes** [comment]
Thank you for reporting this @jkarneges .
I'd expect the ordering to be the same as well.

@mlucy is this a bug?

**Comment by mlucy** [comment]
We currently offer no guarantees about what order changes that occur at the same time will be sent in (the initial values of the changefeed are considered to be "changes" that occur at the same time).  But this would be pretty easy to fix for the initial-value case (we just have to iterate over the initial set in reverse order in this case) and it would probably be more intuitive for people.

**Comment by danielmewes** [comment]
I see. I think we should change it, if possible for 2.0. It's kind of confusing.

**Comment by mlucy** [comment]
This is in CR 2779 by @danielmewes .

**Comment by mlucy** [comment]
This is in next.

**Comment by mlucy** [comment]
(And v2.0.x.)
