### ISSUE TITLE
Set TCP_NODELAY in all drivers

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3998]
At least in the Python driver we're not currently setting this.
This can cause Nagle's algorithm to kick in and make certain sequences of noreply and regular queries *very very* slow.

I'm working on a fix.
I think we should include it for 2.0.

(this showed up while experimenting with @peterbe's benchmark)

**Comment by danielmewes** [comment]
We did already disable it in the JS driver, but not in Python nor Ruby.

**Comment by danielmewes** [comment]
In CR 2759 by @Tryneus

**Comment by mlucy** [comment]
@danielmewes -- this issue says "all drivers", what's the state of Ruby?

**Comment by danielmewes** [comment]
@mlucy That's also fixed by the commit. Sorry, should have added you as an observer or 2nd reviewer. Does it look reasonable?

**Comment by mlucy** [comment]
@danielmewes -- yeah, looks good to me.

**Comment by peterbe** [comment]
As a noob to this community, when will I see this in a pypi release? I'm eager to re-attempt above-mentioned benchmarks.

**Comment by danielmewes** [comment]
@peterbe It will ship with RethinkDB 2.0 in about two weeks.
Whether it makes a difference or not will depend on the exact timing of the tests. On my machine it improved things with `noreply=True` very very considerably, but that might not always be the case.
