### ISSUE TITLE
cursor.close: TypeError: this._cbQueue is undefined

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#4002]
When the data explorer calls `cursor.close`, this error shows up in the console:

```
TypeError: this._cbQueue is undefined
```

Ping @deontologician. It might be caused by some changes in 67f7f0cc

**Comment by deontologician** [comment]
There is a test failure also related to this, looking into it

**Comment by deontologician** [comment]
Good old dynamically scoped `this`. I love that little guy

**Comment by deontologician** [comment]
Fixed in 5b73db6dd975b2d1994834fe6d30e838dd4dc53b5b73db6dd975b2d1994834fe6d30e838dd4dc53b
