### ISSUE TITLE
The server replies "SUCCESS" and immediately fails with an error

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#4011]
After a handshake with a wrong protocol version, the server sends back:

```
SUCCESS\0Unrecognized protocol specified: '1074539808'
```

I think it shouldn't send back "SUCCESS" if the magic number is wrong.

**Comment by danielmewes** [comment]
@grandquista fixed this through https://github.com/rethinkdb/rethinkdb/pull/4012. Also backported to v2.0.x.
