### ISSUE TITLE
Cache query results for other queries

### ISSUE THREAD

**Issue by cadina** [rethinkdb/rethinkdb#4016]
If we have follow query:
```
r.table('table1').filter(lambda t1: r.table('table2').get_field('id').contains(t1.t2_id))
```
Can we assert that RethinkDB will repeat the query of `table2` for every `table1` rows scanned?
If so, is there a recommended way to avoid that?

**Comment by thelinuxlich** [comment]
This looks similar to #3318

**Comment by mlucy** [comment]
@cadina -- you can't avoid querying table2 for every row of table1, but you can avoid scanning all of table2 by writing `r.table('table1').filter(lambda row: r.table('table2').get(row['t2_id']))`.

**Comment by danielmewes** [comment]
Closing since it's not really a feature request or bug, but @cadina please let us know if you have further questions.
