### ISSUE TITLE
JavaScript driver appears to hang if cursor is closed twice

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4017]
In branch `larkost/2649-connection.js-failures-v2` (#2649) the two "close twice" tests have been made deterministic and this has exposed that the second `close` command is never returning . Since most uses of `close` are nearly throw-away this is not going to be a big deal for most uses. But since the JavaScript model is so intertwined it would be easy for people to accidentally be caught in this.

Note: until CR 2773 is merged this will only be clearly visible in the branch listed above.

**Comment by danielmewes** [comment]
@deontologician

**Comment by deontologician** [comment]
@larkost this is on 2.0.x and next right?

**Comment by larkost** [comment]
I am branched off next, but I presume that this is in both.

**Comment by deontologician** [comment]
So, interestingly, this test is failing not because of the double close, but something else. Making it close only once still causes a timeout.

**Comment by deontologician** [comment]
fix is up in CR 2782 by @Tryneus

**Comment by deontologician** [comment]
This was the result of not only close not expecting to be called twice, but also reconnect not expecting to be called on a closed connection (it relied on the socket close event being fired, which it never would be on an already closed socket)

**Comment by deontologician** [comment]
merged to next, cherry-picked onto v2.0.x
