### ISSUE TITLE
Insert/Replace/Update optarg to automatically coerce ISO8601 valid strings to date

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#4023]
During operation, if the user trusts its data, it would be much better if some field didn't need special treatment with r.ISO8601()

**Comment by deontologician** [comment]
Wouldn't this mean it would have to scan every string on the off chance it's iso8601?

**Comment by thelinuxlich** [comment]
you're right, the optarg should mention the key(s)

**Comment by danielmewes** [comment]
I'm not sure if it's a good idea to implement this in the server, as it seems to be rather specific.

@thelinuxlich Could you use a helper function in your application that you pass arguments to insert/replace/update through to perform the conversion client-side?

Related to https://github.com/rethinkdb/rethinkdb/issues/3085
