### ISSUE TITLE
JavaScript connection tests not handling promise errors correctly

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4027]
Both @Tryneus and I separately noticed that there are some cases where failures in the JavaScript connection tests are not reported correctly. In his case he noticed that running `./test/rql_test/test-runner connections/feeds.js -v` was passing, but if you look that output you will see `Possibly unhandled Error` showing where the test is actually failing. I am seeing a similar case in `connections/connection.js`.

A little investigation shows that this is actually the BlueBird module's way of reporting promise errors. Since we are not chaining `.catch` after them we are losing these errors. And unfortunately since we switched to promises anything that does not explicitly have a callback is returning a promise.

I am going to have investigate every line of our JavaScript tests to make sure we are always catching things.

**Comment by deontologician** [comment]
You should be able to do what I did in 4017 and finish the promise chain by passing `done` to `.nodeify`. That should handle successes and failures in the chain

**Comment by larkost** [comment]
The fixes for connection.js are up for review in CR2784.

**Comment by neumino** [comment]
@larkost -- You can bind a listener on process for `unhandledRejection` and have it call `process.exit(1)` to avoid false positives.

See https://github.com/petkaantonov/bluebird/blob/master/API.md#global-rejection-events

**Comment by larkost** [comment]
The changes for `connection.js` have been merged into `next` () and `v2.0.x` (). The rest of the audit is still outstanding.

**Comment by benjamingr** [comment]
> You should be able to do what I did in 4017 and finish the promise chain by passing done to .nodeify. That should handle successes and failures in the chain

Unless you're using an odd test runner - you can just return promises.

> See https://github.com/petkaantonov/bluebird/blob/master/API.md#global-rejection-events

This is the correct approach generally, yeah.

**Comment by larkost** [comment]
The rest of the tests are updated, and in review with CR 2856. This introduces a few changes to what we have had before:
- `test-runner` now looks for files with the extension `.mocha` and runs them with the [Mocha](http://mochajs.org) test framework with no intermediate `.test` file needed.
- all of the `connections` JavaScript tests except `http.js` now use Mocha.
- There are a number of additional tests mixed in, especially in testing changefeed EventEmitters.

**Comment by danielmewes** [comment]
Merged into `next` as of 6921a35015f7c1929eb243ec5e9ff41f3a0df6d2
