### ISSUE TITLE
utf-8 orderBy collate support

### ISSUE THREAD

**Issue by derkan** [rethinkdb/rethinkdb#4028]
Dear All,

Although [docs say](http://rethinkdb.com/api/javascript/order_by/):

>Note: RethinkDB uses byte-wise ordering for orderBy and does not support Unicode collations; non-ASCII characters will be sorted by UTF-8 codepoint.

Is it possible to define collate like [ Postgresql's`COLLATE 'tr_TR.UTF-8' ` ](http://www.postgresql.org/docs/9.1/static/collation.html ) so that sorting will be done correctly for languages like Turkish? ( COLLATE can be defined for a column, for a table or for DB)

Regards
Erkan D.

**Comment by danielmewes** [comment]
Hi @derkan. Sorry, this isn't supported yet. We're planning to add that in the future though. See https://github.com/rethinkdb/rethinkdb/issues/2040

**Comment by derkan** [comment]
Thanks @danielmewes, I'll watching for that. 
Best regards, Erkan.
