### ISSUE TITLE
Allow r.union as top-level term

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4030]
At least in the JavaScript driver, `union` currently cannot be used as a top-level term:
```
> r.union([1,2,4], [1,2,3])
TypeError: r.union is not a function
```

I haven't tested the other drivers.

We should allow this (marking as ReQL_proposal for formal reasons).

**Comment by mlucy** [comment]
That's currently the behavior in Ruby.  Not sure about the other ones.

**Comment by coffeemug** [comment]
That sounds like an oversight, we always intended this to work. We should definitely support this IMO.

**Comment by danielmewes** [comment]
Marking settled.

**Comment by larkost** [comment]
I have confirmed that this is also a problem in Python.

**Comment by larkost** [comment]
I have added a regression test (taking the term loosely) to show when this issue is fixed. The test has the beginnings of a more comprehensive `unions` test that should be filled in when this is solved.

**Comment by danielmewes** [comment]
I ended up just implementing this since disabling the test for 2.1 seemed about as much hassle as just adding the term to the global namespace.

In CR 2978

**Comment by danielmewes** [comment]
I didn't turn the regression test into a full blown `union` test. Leaving that for @larkost .

**Comment by danielmewes** [comment]
This is now in `raft` 58583b1b1f464e424120d4ac11db4a5adc477c82 .
Opening a follow-up issue for extending the test.
