### ISSUE TITLE
Dropping a replicated table crashes

### ISSUE THREAD

**Issue by VeXocide** [rethinkdb/rethinkdb#4033]
On a cluster of two machines the following can be used to reproduce the issue

```
r.tableCreate("test")
r.table("test").reconfigure({replicas: 2, shards: 1})
r.table("test").insert({"x": 1})
r.tableDrop("test")
```

A copy of the executable and core file is in `newton:/home/vexocide/tim/4033`.

**Comment by timmaxw** [comment]
This will probably be fixed with https://github.com/rethinkdb/rethinkdb/issues/3594.

**Comment by timmaxw** [comment]
I can't reproduce this and it's probably been fixed. I'm closing this for now, but feel free to reopen.
