### ISSUE TITLE
Make get_all of lots of keys work and not be slow

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4035]
User hubz on IRC was testing a scenario with a `get_all` that was fetching 1 million different keys at once. Something similar to
```
r.table("t").get_all(key1, key2, ..., key1000000)
```

While this is a little extreme, wanting to fetch something like a few thousand keys at once is certainly not unreasonable.

We should test that this works and doesn't run out of memory or anything like that.

I also suspect that this will be very slow at the moment, since as far as I know `get_all` is going to fetch one key at a time. We should consider parallelizing it (I vaguely remember that it's using `union` underneath?).

**Comment by coffeemug** [comment]
Note, this is related to what @VeXocide was doing (and what @mlucy) is finishing up.

**Comment by danielmewes** [comment]
The description of this issue is pretty outdated. `get_all` has parallelized lookups for a while, and we're making it more performant in https://github.com/rethinkdb/rethinkdb/issues/1526 .

The way those changes are implemented, I think memory consumption will be about what one would expect, i.e. all keys obviously have to fit in memory, but the results itself will be streamed.

I'm going to close this, since I don't think there's much left to do here.
