### ISSUE TITLE
Filter deep hash

### ISSUE THREAD

**Issue by forrestgrant** [rethinkdb/rethinkdb#4044]
I have documents that look like this:
```ruby
{
  first: {
    second: [
      { foo: 'foo', bar: 'bar' },
      { foo: 'another foo', bar: 'another bar' },
    ],
  },
}
```

I'd like to filter by `foo`. With mongo syntax, I think it would look something like this:
```ruby
r.table('table').filter { |doc| doc['first']['second.foo'].match('(?i)another') }
```
Anything?

**Comment by mlucy** [comment]
@forrestgrant -- does this do what you want?  If not, could you elaborate a bit on what behavior you're looking for?

```rb
r.table('table').filter{|doc| doc['first']['second']['foo'].contains{|foo| foo.match(whatever)}}
```

**Comment by forrestgrant** [comment]
That works. Thanks for the speedy reply, @mlucy!
