### ISSUE TITLE
In tornado , .repl() do not work 

### ISSUE THREAD

**Issue by v3ss0n** [rethinkdb/rethinkdb#4046]
```python
db = (yield r.connect("localhost", db=db_name)).repl() 
class EventsUpdateHander(EventBaseHandler):

    @gen.coroutine
    def get(self):
        curs = yield db.table('evt').changes()

        while (yield curs.fetch_next()):
            feed = yield curs.next()
            message = {
                'id': feed['new_val']['id'], 'html': tornado.escape.to_basestring(
                    self.render_string("message.html", message=feed['new_val']))}
            self.write_events(name="message", evt_id=feed['new_val']['id'],msg=[message])
```

``` python
Traceback (most recent call last):
  File "/home/v3ss/pypy/site-packages/tornado-4.1-py2.7.egg/tornado/web.py", line 1348, in _execute
    result = yield result
  File "/home/v3ss/pypy/site-packages/tornado-4.1-py2.7.egg/tornado/gen.py", line 807, in run
    value = future.result()
  File "/home/v3ss/pypy/site-packages/tornado-4.1-py2.7.egg/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/home/v3ss/pypy/site-packages/tornado-4.1-py2.7.egg/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "event_rechat.py", line 146, in get
    curs = yield self.evt.changes()
  File "/home/v3ss/pypy/site-packages/tornado-4.1-py2.7.egg/tornado/gen.py", line 807, in run
    value = future.result()
  File "/home/v3ss/pypy/site-packages/tornado-4.1-py2.7.egg/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/home/v3ss/pypy/site-packages/tornado-4.1-py2.7.egg/tornado/gen.py", line 886, in handle_yield
    self.future = convert_yielded(yielded)
  File "/home/v3ss/pypy/site-packages/tornado-4.1-py2.7.egg/tornado/gen.py", line 956, in convert_yielded
    raise BadYieldError("yielded unknown object %r" % (yielded,))
BadYieldError: yielded unknown object <RqlQuery instance: r.table('events').changes() >
```

**Comment by v3ss0n** [comment]
I see now .run is still necessary.

```        curs = yield db.table('evt').changes().run() ```

Can we get rid of  .run() , when repl() is called at db connection ?

**Comment by danielmewes** [comment]
I'm not sure if that's possible. Maybe we could hack something in such that the first time you yield a query object back to the Tornado loop, it somehow triggers `run()`. Were you thinking of something like that?
So
```py
x = r.table("t").get(0)
```
would not run (`x` would be a query object), but
```py
x = yield r.table("t").get(0)
```
would run and `x` would be the query result.

Even if this is possible, I personally don't think that's a good idea. ReQL has the nice property that you can store queries in variables (or return them from functions) and compose them further into your final query. For example:
```py
x1 = r.table("t").get(1)
x2 = r.table("t").get(2)
res = yield x1.union(x2).run()
```
In cases like this you want to make it very clear at what point the query is actually executed. You don't want to execute `x1` or `x2` individually. Piggy-backing on yielding to the event loop for triggering query execution sounds fragile and might trigger unwanted execution.

**Comment by AtnNn** [comment]
@v3ss0n You could write your own decorator, something like:

```
def autorun_coroutine(f):
    @gen.coroutine
    def wrap(*args, **kwargs):
        coroutine = f(*args, **kwargs)
        query = coroutine.next()
        while True:
            try:
                query = coroutine.next(yield query.run())
            except StopIteration:
                return
            except Exception as e:
                coroutine.throw(e)
    return wrap
```

**Comment by v3ss0n** [comment]
@AtnNn  I will try it.
@danielmewes  
> Piggy-backing on yielding to the event loop for triggering query  execution sounds fragile and might trigger unwanted execution.

Its true , just unexpected , coz i was expecting to run like python's RePL enviorments. @AtnNn 's wrapper will work fine i guess. i will give a try.

**Comment by danielmewes** [comment]
That makes sense, I understand.

I think we will keep the current behavior for now, but we can re-evaluate it at some point later when we have more experience with how our Tornado driver is typically being used.

**Comment by v3ss0n** [comment]
Thanks , yes i will keep updated.
