### ISSUE TITLE
Client Niceties

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#405]
Here are some thing we do in the ruby client to make things nicer for people:
- If people are in IRB and hit C-c C-c, we reset the connection for them automatically.
- If someone writes `r(1) < r(2) | r(3) < r(4)`, we give them a nice warning message about the fact that they probably messed up the precedence.
- We keep track of where subqueries were constructed using `caller` and use that to give people a more useful backtrace.

Do we do these in the Python client?  Should we?

**Comment by srh** [comment]
We at least do the order of precedence thing.  Closing.
