### ISSUE TITLE
Python driver changefeeds hangs on `list`

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4053]
The following code will hang forever waiting for a `StopIteration` that the driver is never going to produce:
```python
import rethinkdb as r
r.connect().repl()
r.table_create('bob').run()
feed = r.table('bob').changes().run()
list(feed)
```
The underlying problem is that `list` is using `next`, and by default we have no timeout on `next`. So regardless of how many items `list` winds up pulling out of the changefeed, it will always try for one more. I see four options of how we could go on this:

1. Leave it alone. This actually works as expected for unbounded generators. For example the following code will also hang:
```python
def endless():
    while True:
            yield 1
list(endless())
```
2. Mention this in the documentation. While most people would probably miss this until it bit them, we would at least have made the token gesture.
3. Inspect the call stack every time `next` is called and bail out if our caller is `list`. This feels hackey to me, and is probably going to impact performance.
4. Have a timeout by default on `next`, and make that timeout inherit from `StopIteration`. This has a few downsides: it would break existing code that depends on `next` waiting forever for the next change, it would break the Python guidance that generators/iterator never return data after a `StopIteration`, and it would be difficult to choose a timeout.

While I like #4, I think we should just do #2.

**Comment by danielmewes** [comment]
I feel like this is expected and we should just do [2] - mention it in the documentation.

Does anyone else have any objections?

**Comment by danielmewes** [comment]
http://rethinkdb.com/api/python/to_array/ actually already mentions this:
```
Note: Because a feed is a cursor that never terminates, using list with a feed will never return. Use for or next instead. See the changes command for more information on feeds.
```

Closing.
