### ISSUE TITLE
Deadlock in eventmachine ruby driver

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#4055]
While doing something like:

```rb
class MyHandler < RethinkDB::Handler
   def on_close
      some_query_handle.close
   end
end
```

Basically, closing within a close deadlocks. @mlucy thoughts? I can get around this by using `EM.next_tick` to defer the inner close operation, but since I'm only on one thread, it seems like it shouldn't be necessary.

**Comment by danielmewes** [comment]
@mlucy if you get a chance to work on this today, we can still get this into 2.0. Otherwise we'll do a driver point release later.

**Comment by mlucy** [comment]
This is in CR 2806 by @Tryneus .

**Comment by mlucy** [comment]
The fix is in next and v2.0.x.

**Comment by danielmewes** [comment]
@AtnNn could you repackage the Ruby driver for 2.0 please?

**Comment by AtnNn** [comment]
Consider it done.

**Comment by danielmewes** [comment]
Excellent :)
