### ISSUE TITLE
Make datum_t movable

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4056]
We currently have a non-default destructor in datum_t which makes it non-movable. The destructor is empty, so it looks like we could safely remove it.

However we should audit code that might move datums and make sure that we're not introducing any new bugs by doing so. As a second step we should see if we can move datums more often to avoid some of the atomic reference counting calls that occur when copying a datum.

**Comment by mlucy** [comment]
I think we should bump this up; I think a lot of code is attempting to move datums because moving worked back when they were `counted_t<datum_t>`s, and it's confusing to be doing that if the type isn't actually movable.

**Comment by danielmewes** [comment]
We could just do it and see if it causes crashes in our 2.1 tests.

I didn't consider the fact that it used to be movable before. Since that's the case, it actually makes me less concerned about unwanted side-effects.

**Comment by danielmewes** [comment]
It's in `next`. All tests are passing on `newton`.
