### ISSUE TITLE
cfeed_union test timing out on MacOS

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4057]
The `cfeed_union.rb` test is timing out after 300 seconds. I put some print lines and found that the timeout is happening at the following line (line 91):
```ruby
$cp2 = nested_union($change_pop).run.each
```
The timeout is happening in the `run` command, so it looks like this is a server issue. I have attempted to reproduce this outside of the test, but one-line nested queries are not reproducing the issue. So it looks like this is something more complicated going on in the server.

This particular sub-test is testing deeply nested unions on changefeeds so it is unlikely that a customer would run into this, but we do need to investigate it.

**Comment by mlucy** [comment]
As far as I can tell this is a legitimate server bug that only shows up on OS X for some reason.  @VeXocide -- you've expressed interest in learning the changefeed code, this would be a pretty good starter bug if you want to take it.  (If not, that's fine too, I'd be happy to take care of it.)

**Comment by mlucy** [comment]
@larkost -- the cfeed_union test turned out to have some other problems, right?  Does this bug still occur?

**Comment by larkost** [comment]
Yes, this is still a problem. I will probably re-write the test into JavaScript in order to improve its reliability at some point (one that is clearer about where the issue is), but this is probably still an issue.

**Comment by larkost** [comment]
We actually have two issues on this (not counting duplicates), so I am going to leave this one with @mlucy to try and find the server bug portion that we presume is there, and I will take #4314 myself to re-write the test for reliability/completeness.

**Comment by mlucy** [comment]
A fix is in CR 3105 by @larkost .

**Comment by mlucy** [comment]
The fix is in next.
