### ISSUE TITLE
homebrew install rethinkdb still in version rethinkdb-1.16.3

### ISSUE THREAD

**Issue by John-Lin** [rethinkdb/rethinkdb#4058]
https://github.com/Homebrew/homebrew/blob/06397cc0c82b15d2435dc9ae73470286ee9145ee/Library/Formula/rethinkdb.rb

Does anyone can help update it.
Thanks :+1:

**Comment by danielmewes** [comment]
Hi @John-Lin, @AtnNn is working on it. We'll submit the pull request to Homebrew today.

**Comment by John-Lin** [comment]
Thank you @AtnNn @danielmewes  :smile:
