### ISSUE TITLE
Can't connect to RethinkDB

### ISSUE THREAD

**Issue by Ch4s3** [rethinkdb/rethinkdb#4060]
when I run ````r.connect(:host => 'localhost', :port => 28015).repl````, I get the following error:
````
RethinkDB::RqlRuntimeError: Server dropped connection with message: "ERROR: Received an unsupported protocol version. This port is for RethinkDB queries. Does your client driver version not match the server?
"
````

I installed RethinkDB with brew, and ran ````rethinkdb``` and Ic an run queries from the web ui. I just can't connect from the ruby library.

**Comment by mglukhovsky** [comment]
Could you please include the output of `rethinkdb --version` and `gem list`?

Based on the error message, it may be possible that you're running an outdated version of the driver -- if you're using RethinkDB 2.0, you'll need to use the [matching 2.0 version](https://rubygems.org/gems/rethinkdb/versions/2.0.0.1) of the `rethinkdb` gem.

**Comment by Ch4s3** [comment]
So it turns out that I had ````rethinkdb-2.0.0.1```` installed and 2.0 isn't available on Brew yet... so I had a version mismatch. I solved it by installing the ````1.16.0.1```` gem.

**Comment by Ch4s3** [comment]
Oh, @mglukhovsky thanks. I reread the error and thought to check the version. The error message seems a bit fuzzy, but maybe that's just me. ¯\_(ツ)_/¯

**Comment by ramesh-pmap** [comment]
Hi,

When I run rethinkdb in localhost:28015/,
giving error like "ERROR: Received an unsupported protocol version. This port is for RethinkDB queries. Does your client driver version not match the server?".

with this if I run

r.connect( {host: 'localhost', port: 8080, db: 'test'}, function abc(err, conn) {
      console.log('error', err);
      console.log('success', conn);
   }); 
this getting error. Please find the attached file

can you please suggest.

<img width="550" alt="screen shot 2016-01-20 at 2 41 13 pm" src="https://cloud.githubusercontent.com/assets/15626909/12444269/02e481b2-bf84-11e5-87e2-36e4ee2eb6b5.png">

**Comment by mglukhovsky** [comment]
@ramesh-pmap: how are you starting RethinkDB? 

The default port for the web UI is port 8080 (so you can access the admin UI via http://localhost:8080), and the default port for queries is 28015.

This means your connection code should start with `r.connect( {host: 'localhost', port: 28015, db: 'test'}, ...`.

Does that work for you?

**Comment by ramesh-pmap** [comment]
Thanks for reply @mglukhovsky 

Still not working even I mentioned port with 28015.
same error getting. I think the problem with "ReqlDriverError" error.

I installed client drivers as below
$ npm install rethinkdb

how to resolve this?


please suggest.

**Comment by ramesh-pmap** [comment]
i am using es06 and react js

**Comment by danielmewes** [comment]
@ramesh-pmap RethinkDB doesn't currently support connecting to your server directly from the browser-side code. You'll need to put the `r.connect` etc. in the backend code, that runs in node.js (and for that use port 28015, not 8080).
The RethinkDB API isn't suitable for direct connections from the browser, since it doesn't have a security model.

The good news is that we're working on a separate product that will allow exactly this type of use case. It's still in the planning phase, but we'll hopefully have a first alpha out very soon. (some details about it here: https://github.com/rethinkdb/rethinkdb/issues/3711#issuecomment-151639571)

**Comment by ramesh-pmap** [comment]
Thanks for reply.
