### ISSUE TITLE
Parse error for server version

### ISSUE THREAD

**Issue by damonmcminn** [rethinkdb/rethinkdb#4061]
Running `rethinkdb import` with `rethinkdb 2.0.0+1~0trusty (GCC 4.8.2)` I receive the error:

`Error: Incompatible server version found, expected >= 1.16.0`

https://github.com/rethinkdb/rethinkdb/blob/next/drivers/python/rethinkdb/_backup.py#L82
has a regex that matches incorrectly

**Comment by danielmewes** [comment]
Thanks for the report and for investigating the issue @damonmcminn ! Sorry you had to run into this.
We'll release a Python driver update with the `rethinkdb import` patch as soon as possible.

**Comment by danielmewes** [comment]
Linking @damonmcminn pull request https://github.com/rethinkdb/rethinkdb/issues/4061

**Comment by damonmcminn** [comment]
Not a problem @danielmewes! Glad I can be of help.

**Comment by danielmewes** [comment]
@Tryneus has merged the fix into v2.0.x (and next).
@AtnNn can you get a new python driver package on the way?

**Comment by Tryneus** [comment]
Ok, #4062 has been merged to `next` in commit 4226183 and cherry-picked into `v2.0.x` in commit 95d8188.  Thanks again, @damonmcminn!

**Comment by AtnNn** [comment]
This fix has been published to PyPI in version 2.0.0-1 of the Python driver.
