### ISSUE TITLE
Force `changes` to be populated

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#4068]
`returnChanges: true` used to return all the documents that the user is trying to update. With 2.0, RethinkDB returns only the documents that are actually updated. 

Thinky was relying on the behavior pre-2.0 to let people do an update and get the new document, and this was really nice to build REST API (it makes things easier - you don't have to look for special values, empty arrays, weird ordering).

Any chance to revert to the old behavior? Or add a new flag to force `changes` to be populated?

**Comment by mlucy** [comment]
We changed it for consistency with how `table.changes` works (it discards trivial changes), but I think it would be fine to add another optarg `include_trivial_changes` to support this.  Does anyone else object?

**Comment by mlucy** [comment]
(It might also be the case that we made the wrong decision and `return_changes` should default to including trivial changes.)

**Comment by danielmewes** [comment]
I still think our decision makes sense, but I don't object to an additional option.
I think it should be a special value for `return_changes` though, not a second optarg.

What about `return_changes="include_unchanged"`?

We should also consider adding this to a 2.0.x point release, to make thinky work again.

**Comment by mlucy** [comment]
Yeah, another value for `return_changes` is probably the way to go.  How about `return_changes='always'`?

**Comment by mlucy** [comment]
Or `return_changes='all'`?

**Comment by danielmewes** [comment]
`return_changes='all'` sounds good.

@mlucy unless it requires bigger changes, can you try to implement this for a point release?

@neumino You've probably worked around this in Thinky for now haven't you?
I imagine some other ORMs might be affected though (@nviennot does nobrainer make use of this aspect of `return_changes`?)

**Comment by neumino** [comment]
@danielmewes -- Well it doesn't crash now, but people still can't make an update and retrieve the document without firing a second query.
It also makes things a bit complicated to track in case of batch update.

**Comment by nviennot** [comment]
`return_changes` is an important feature that I should be using for atomic updates.
But I don't mind not returning anything if the update didn't change anything. I can deal with this very easily.
In short, I don't care so what semantics `return_changes` gives when the document has not changed.

**Comment by danielmewes** [comment]
Thanks @neumino and @nviennot for the feedback.
Let's still put it into a point release.

**Comment by linkyndy** [comment]
I also support the old behavior. Remodel too has problems. I can workaround this issue, but I prefer the old behavior.

**Comment by mlucy** [comment]
We never actually settled this.  My personal favorite is `return_changes: 'always'` (I like this a little bit better than `all` because I feel like it better conveys that we're retuning changes even when they're trivial).  Does that sound fine?

Sorry I haven't gotten to this yet, it's next on my list once my current code review is done.

**Comment by VeXocide** [comment]
I dislike the combination of `'always'`, '`true`', and `'false`' since it mixes strings and booleans in a non-obvious way. However, changing that in a point release is a bad idea as well.

**Comment by danielmewes** [comment]
> I dislike the combination of 'always', true, and false since it mixes strings and booleans

That's true, but I think we shouldn't change it now for the reason you mention. Also most people will only ever use `true` and `false`, while `"always"` is a much more specialized option.

I'm down with `return_changes: 'always'`.

**Comment by mlucy** [comment]
Alright, marking this as settled and working on it now.

**Comment by mlucy** [comment]
This is in CR 2847 by @danielmewes .

**Comment by linkyndy** [comment]
From my point of view, `True` means that changes will be returned, meaning that `changes` must be present there either way. `False` means that changes will not be returned, so `changes` must not be there either way. I would add an option for the current behavior, which is neither `True`, nor `False`. Because with boolean values, you expect something to be there or not, you expect something certain, while the current behavior is not something certain.

Just my thoughts on this :)

**Comment by danielmewes** [comment]
@linkyndy The original reason we started discarding "changes" that didn't change anything was for consistency with changefeeds and other places. This is probably a question of interpretation. If nothing changes, I wouldn't necessarily expect `return_changes = True` to return anything.

I can see that it might be annoying having to deal with the absence of the `changes` field in some cases.

@mlucy @VeXocide What would you think about always including the `changes` field in the result if `return_changes = True`, but leaving it as an empty array if there are no proper changes?

**Comment by simonratner** [comment]
@danielmewes, the main problem isn't in dealing with the missing field - that part is easy - it is the fact that the client doesn't get the updated state of the document if no changes were made. See my scenario in #4179.

**Comment by linkyndy** [comment]
@danielmewes I understand your reasoning too. I believe your last solution would work for both parts: an empty array for `changes` if nothing changed.

**Comment by danielmewes** [comment]
@simonratner Makes sense. Well we agree that there should be an option for doing that. :-)
The only remaining question was how to name the arguments. I still think that setting `return_changes` to `true` not returning non-changes is the right behavior, with the `"always"` value to indicate that the document value should always be returned.

Unless there are objections, I think we should have the empty `changes` array for trivial changes with `return_changes=True` then.
Sorry for the late addition to an already settled and implemented proposal...

**Comment by VeXocide** [comment]
@danielmewes -- that'd work as I'd prefer sticking to just `true` and `false` for `return_changes`, the actual behaviour is less important to me.

**Comment by danielmewes** [comment]
@VeXocide Sorry for being unclear. We still need the `always` option for `return_changes`.

**Comment by mlucy** [comment]
This is in `next` along with @danielmewes's change where `return_changes: true` always at least puts an  empty array in the object.

**Comment by mlucy** [comment]
@danielmewes -- this is going in a point release too, right?

**Comment by danielmewes** [comment]
@mlucy Yes please.
Will be in 2.0.2.

**Comment by mlucy** [comment]
Alright, this is now in 2.0.x as well.

**Comment by linkyndy** [comment]
This is great, guys! Appreciate your fast reaction :+1:

**Comment by neumino** [comment]
In 2.0.4 this doesn't work anymore (and in `next` too - for `update` or `replace`). One use case beside the one already mentioned is https://github.com/neumino/thinky/issues/288: 
```
r.db('test').table('test').get(1).replace({id: 1, foo: 'bar'}, {returnChanges: true})
```

**Comment by danielmewes** [comment]
@neumino Can you make sure that you're setting `returnChanges: "always"`? With that option it seems to work as expected on 2.0.4.
```
r.db('test').table('test').get(1).replace({id: 1, foo: 'bar'}, {returnChanges: "always"})
```

**Comment by neumino** [comment]
Arg I missed that change. Thanks @danielmewes, it works like a charm now :)
