### ISSUE TITLE
Preparing for RethinkDB 2.0.1

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#4069]
Motivated by #4066.

Milestone: https://github.com/rethinkdb/rethinkdb/milestones/2.0.1

Is there anything else we want to include in this release?

**Comment by danielmewes** [comment]
I think we're good. Let's tag and build it tomorrow.

**Comment by AtnNn** [comment]
We should also test first.

**Comment by rclai** [comment]
Change feeds for joins? Hehe.

**Comment by danielmewes** [comment]
@rclai not in this bug fix release, but some time later. :) See https://github.com/rethinkdb/rethinkdb/issues/3997

**Comment by rclai** [comment]
I was just kidding.
