### ISSUE TITLE
snappy on rethinkdb [feature]

### ISSUE THREAD

**Issue by hsen-dev** [rethinkdb/rethinkdb#4070]
How can I use google snappy compression for my data to to save more storage, and are you have any planning to add this feature to rethinkdb.
In my issue this feature can be a option for some special tables.

**Comment by mlucy** [comment]
@hsen-dev -- if you compress your data in the client, you can use `r.binary` to store arbitrary binary blobs on the server (and then uncompress them again in the client).

As for adding compression to the database, there's an issue for this at https://github.com/rethinkdb/rethinkdb/issues/1396 (closing this one as a duplicate).  We've looked at a few compression algorithms so far including snappy (you can find more details on how they performed in that issue).

Thanks for the suggestion!
