### ISSUE TITLE
Suggestion: Pluggable indexes

### ISSUE THREAD

**Issue by sreejaThummala** [rethinkdb/rethinkdb#4078]
The present rethinkdb has indexes hard coded into it.  It would be really easy to develop new indexes if there is a pluggable api for indexing with the backend engine. This type of pluggable indexes are present in Neo4j, Nutch.

**Comment by deontologician** [comment]
Are you suggesting being able to write index functions in a language other than reql? Could you give an example of what this might look like?

**Comment by danielmewes** [comment]
@sreejaThummala ... or do you mean something like GiST (http://en.wikipedia.org/wiki/GiST) so you can implement custom index tree structures?

**Comment by sreejaThummala** [comment]
Yes . I mean to build custom index tree structures. Neo4j has custom index providers and they are a great help.

**Comment by sreejaThummala** [comment]
yes. I am thinking of an interface to the storage engine to help people implement their own underlying index structure. This would be great as different applications have different priorities.

**Comment by danielmewes** [comment]
I see, thanks for the suggestion @sreejaThummala!

I don't think we'll get to this in the next couple releases, but we'll keep it in mind.

There's also the question of how different index data structures will integrate into the ReQL query layer. Currently ReQL terms assume a certain type of index where keys are ordered sequentially. It might need a pretty major rewrite to take advantage of other index types (say a multi-dimensional index for example).

**Comment by thelinuxlich** [comment]
@srh  without a proposal, I think this should be closed
