### ISSUE TITLE
Can't connect locally when using --bind all

### ISSUE THREAD

**Issue by freak4pc** [rethinkdb/rethinkdb#4082]
Hey All,
I'm using thinky on node.js , 
When trying to connect to 127.0.0.1 after running "rethinkdb" it works fine, but if i ran "rethinkdb --bind all" , it wouldnt let me connect with the following errors:

```
Failed to connect to fe80::4fb:81e2:d4f9:a4a1%10:28015
Full error:
{
  "code": "EHOSTUNREACH",
  "errno": "EHOSTUNREACH",
  "syscall": "connect"
}.
ReqlDriverError: Failed to connect to fe80::4fb:81e2:d4f9:a4a1%10:28015
Full error:
{
  "code": "EHOSTUNREACH",
  "errno": "EHOSTUNREACH",
  "syscall": "connect"
}.
    at Socket.<anonymous> (/Users/freak4pc/Work/DreamDate/DreamDate-API/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:83:16)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
Fail to create a new connection for the connection pool The error returned was:
Failed to connect to fe80::4fb:81e2:d4f9:a4a1%10:28015
Full error:
{
  "code": "EHOSTUNREACH",
  "errno": "EHOSTUNREACH",
  "syscall": "connect"
}.
ReqlDriverError: Failed to connect to fe80::4fb:81e2:d4f9:a4a1%10:28015
Full error:
{
  "code": "EHOSTUNREACH",
  "errno": "EHOSTUNREACH",
  "syscall": "connect"
}.
    at Socket.<anonymous> (/Users/freak4pc/Work/DreamDate/DreamDate-API/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:83:16)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)
```

Am I doing anything wrong?

**Comment by Tryneus** [comment]
It looks like the host in the error message is a link-local IPv6 address, which I wouldn't recommend using unless you know exactly what you're doing.  Are you providing a hostname to connect, or that link-local address?

**Comment by neumino** [comment]
@freak4pc -- you can just pass `discovery: false` to thinky's option and it will work fine.

`fe80:...` is a link local address, and will be picked only if no private  or public network is found -- though it seems that I forgot to check for `169.254.x.x` which is probably why the ipv6 ip is picked and not the ipv4.
I'll probably switch the default flag for discovery to false as it seems to raise a few issues with containers and ipv6.

**Comment by freak4pc** [comment]
Hey @neumino, thanks for replying here on behalf of Thinky ;) 

I'm aware of the fact it's trying to connect to the IPv6 address, but I'm supplying either 127.0.0.1 or localhost, so I'm not sure why it would try those addresses instead. How can I pass discovery false? Just in the options dictionary for the connection object? 

Thank you very much.

**Comment by neumino** [comment]
@freak4pc -- yes, passing it as any other option will work:
```
var thinky = require('thinky')({
  discovery: false
})
```

It's related to https://github.com/rethinkdb/rethinkdb/issues/3923 too.

**Comment by freak4pc** [comment]
Thanks @neumino . 
Shouldn't discovery be false by default? 

It seems like someone would want an auto connection-pool only in very specific cases ... most systems would prefer to configure their own connection.

**Comment by danielmewes** [comment]
I'm going to close this since I think it's not a RethinkDB bug (or is it?).
Feel free to keep discussing in this thread of course.
