### ISSUE TITLE
Update documentation for writing drivers to include ResponseNotes

### ISSUE THREAD

**Issue by hamiltop** [rethinkdb/rethinkdb#4093]
See 62bbf33bed1950103df43ed272458f93f60b7221 

The documentation on writing drivers still has `SUCCESS_FEED` which no longer exists in master. Ran me around in circles trying to figure out what why `changes()` wasn't returning a `SUCCESS_FEED`.

**Comment by danielmewes** [comment]
Sorry for the confusion! We will try to update the document soon.
I moved the issue over to our separate tracker for documentation issues: https://github.com/rethinkdb/docs/issues/729
