### ISSUE TITLE
make rethinkdb met an error, when i update protoc to the 2.5.0 and is not work, is there some way to solve???

### ISSUE THREAD

**Issue by sinderrellar** [rethinkdb/rethinkdb#4094]
```
   [1/288] CC build/release/obj/protob/json_shim.o
src/protob/json_shim.cc: In function ‘bool json_shim::parse_json_pb(Query*, int64_t, const char*)’:
src/protob/json_shim.cc:190:53: error: expected unqualified-id before ‘&’ token
     } catch (const google::protobuf::FatalException &) {
                                                     ^
src/protob/json_shim.cc:190:53: error: expected ‘)’ before ‘&’ token
src/protob/json_shim.cc:190:53: error: expected ‘{’ before ‘&’ token
src/protob/json_shim.cc:190:54: error: expected primary-expression before ‘)’ token
     } catch (const google::protobuf::FatalException &) {
                                                      ^
src/protob/json_shim.cc:190:54: error: expected ‘;’ before ‘)’ token
src/protob/json_shim.cc:192:7: error: expected primary-expression before ‘catch’
     } catch (...) {
       ^
src/protob/json_shim.cc:192:7: error: expected ‘;’ before ‘catch’
make[1]: *** [build/release/obj/protob/json_shim.o] Error 1
make: *** [make] Error 2
```

**Comment by AtnNn** [comment]
If you change the version of `protoc` you may have to `make clean` and re-run `./configure` to build RethinkDB.

Then try to `make build/release/obj/protob/json_shim.o`. If it still fails with the same error, could you copy the full output of the `./configure` script?

**Comment by danielmewes** [comment]
@sinderrellar did @AtnNn suggestion work?

**Comment by danielmewes** [comment]
No response from @sinderrellar for a while. Closing since we don't have enough information at the moment.

**Comment by nda888** [comment]
Hello everyone,

I follow the guid but it still be error:

src/protob/json_shim.cc: In function ‘bool json_shim::parse_json_pb(Query*, int64_t, const char*)’:
src/protob/json_shim.cc:190:53: error: expected unqualified-id before ‘&’ token
     } catch (const google::protobuf::FatalException &) {
                                                     ^
src/protob/json_shim.cc:190:53: error: expected ‘)’ before ‘&’ token
src/protob/json_shim.cc:190:53: error: expected ‘{’ before ‘&’ token
src/protob/json_shim.cc:190:54: error: expected primary-expression before ‘)’ token
     } catch (const google::protobuf::FatalException &) {
                                                      ^
src/protob/json_shim.cc:190:54: error: expected ‘;’ before ‘)’ token
src/protob/json_shim.cc:192:7: error: expected primary-expression before ‘catch’
     } catch (...) {
       ^
src/protob/json_shim.cc:192:7: error: expected ‘;’ before ‘catch’
make[1]: *** [build/release/obj/protob/json_shim.o] Error 1
make: *** [make] Error 2

Could you help me please,
Thanks so much
An,

**Comment by AtnNn** [comment]
@nda888 have you tried re-running `./configure` and `make clean`?

**Comment by nda888** [comment]
yes i did, but still fail AtnNn

I install rethinkdb v2.0.3 lastest version

**Comment by nda888** [comment]
yes i did, but still fail

I install rethinkdb v2.0.3 lastest version

I think this file *build/release/obj/protob/json_shim.o* got some problems

I try research on Google but no more info to resolve

Please help,
Thanks

**Comment by nda888** [comment]
I use centos 6.5

Compile from source rethinkdb v2.0.3
  wget http://download.rethinkdb.com/dist/rethinkdb-2.0.3.tgz

I follow as your guide and excuted these step below but not working , still got issue:
  ./configure --dynamic jemalloc --allow-fetch 
  make clean 
  make

One more thing I followed setup guide from Rethinkdb site too:
http://rethinkdb.com/docs/install/centos/

Please help me

**Comment by AtnNn** [comment]
@nda888 I may be able to help, but I first need to know:

 * What is the output of the configure script?
 * What version of protobuf do you have installed?
 * Are you using devtoolset-2 as described in http://rethinkdb.com/docs/install/centos/ ?

**Comment by nda888** [comment]
1. What is the output of the configure script?
== The output is : 
* Error: libicui18n not found. Try running ./configure with the --fetch icui18n or --allow-fetch flags.
/opt/rh/devtoolset-2/root/usr/libexec/gcc/i686-redhat-linux/4.8.2/ld: cannot find -licui18n
collect2: error: ld returned 1 exit status

'Try running ./configure with the --fetch icui18n or --allow-fetch flags' --->>>> i tried this but failed while make:
src/protob/json_shim.cc: In function ‘bool json_shim::parse_json_pb(Query*, int64_t, const char*)’:
src/protob/json_shim.cc:190:53: error: expected unqualified-id before ‘&’ token
     } catch (const google::protobuf::FatalException &) {
                                                     ^
src/protob/json_shim.cc:190:53: error: expected ‘)’ before ‘&’ token
src/protob/json_shim.cc:190:53: error: expected ‘{’ before ‘&’ token
src/protob/json_shim.cc:190:54: error: expected primary-expression before ‘)’ token
     } catch (const google::protobuf::FatalException &) {
                                                      ^
src/protob/json_shim.cc:190:54: error: expected ‘;’ before ‘)’ token
src/protob/json_shim.cc:192:7: error: expected primary-expression before ‘catch’
     } catch (...) {
       ^
src/protob/json_shim.cc:192:7: error: expected ‘;’ before ‘catch’

2. What version of protobuf do you have installed?
protobuf-2.3.0-9.el6.i686
protobuf-devel-2.3.0-9.el6.i686
protobuf-compiler-2.3.0-9.el6.i686

3. Are you using devtoolset-2 as described in http://rethinkdb.com/docs/install/centos/ ?
Yes , i am
scl enable devtoolset-2 bash
gcc -v: 
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-2/root/usr/libexec/gcc/i686-redhat-linux/4.8.2/lto-wrapper
Target: i686-redhat-linux
Configured with: ../configure --prefix=/opt/rh/devtoolset-2/root/usr --mandir=/opt/rh/devtoolset-2/root/usr/share/man --infodir=/opt/rh/devtoolset-2/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-languages=c,c++,fortran,lto --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.2-20140120/obj-i686-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.2-20140120/obj-i686-redhat-linux/cloog-install --with-mpc=/builddir/build/BUILD/gcc-4.8.2-20140120/obj-i686-redhat-linux/mpc-install --with-tune=generic --with-arch=i686 --build=i686-redhat-linux
Thread model: posix
gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC)

I answered all of your question, please help, i don't know what happend may i wrong or missing something
