### ISSUE TITLE
Data Explorer: Increase History count

### ISSUE THREAD

**Issue by paulm17** [rethinkdb/rethinkdb#4097]
I didnt see this already raised.

It would be nice if in the .ini file there is a section to specify how many lines of history the Data Explorer remembers.

Thanks

**Comment by danielmewes** [comment]
Thanks for your suggestion @no1youknowz .
I'm not sure how important this is, but we will keep it in mind.

I think in terms of the actual implementation, we would probably have this configurable directly in the web UI and store the value in a cookie, similar to where the history itself is stored. Having a server command line argument (and configuration file option, those are the same) for this sounds like overkill.
