### ISSUE TITLE
Official blog feed is down

### ISSUE THREAD

**Issue by pilwon** [rethinkdb/rethinkdb#4098]
http://rethinkdb.com/blog/feed is down.

**Comment by mlucy** [comment]
Ping @mglukhovsky .

**Comment by mglukhovsky** [comment]
@pilwon, thanks for the heads up. The RSS feed was broken in the transition to the new site: I intend to get it up and running shortly (but don't have an ETA for you). I'll update this issue when it's been resolved.

**Comment by thelinuxlich** [comment]
@srh this should probably be closed
