### ISSUE TITLE
Implement bug-report command

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#41]
I propose implementing the following command

```
$ rethinkdb bug-report
```

The command should open people's favorite editor, let them write up a bug report, and automatically submit it to github with all the relevant version information. It would then print the url of the github issue for the user.

**Comment by srh** [comment]
Closing, we want Github issues to be tied to a specific user so that we can ask follow-up questions, and (a wild guess appears!) nobody wants to develop or host this open proxy for posting to Github.
