### ISSUE TITLE
Web UI: Reconfigure should block the UI while adding/removing shards/replicas

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#4107]
If I go too fast I end up with the UI showing the new number of replicas but seconds after it returns to the old state.

**Comment by danielmewes** [comment]
@thelinuxlich can you explain a bit more which steps you take and where in the web UI you first see the new and then again the old number of replicas? Are you doing the reconfiguration over the web UI or through a `reconfigure` query?

**Comment by thelinuxlich** [comment]
I'm doing it over the web UI, when I add more replicas and click "Apply configuration" it closes the modal, updates the number of replicas, but sometimes after a few seconds it returns to the old number of replicas.

**Comment by thelinuxlich** [comment]
I've noticed that it won't happen if I expand the "where's my data going?" panel and wait for it to show the new results and only after it click on "Apply configuration"

**Comment by danielmewes** [comment]
Thanks for the clarification @thelinuxlich 

@deontologician you remember when we had the number of replicas on the tables page flicker between including the offloading data replicas and the actual correct number? Maybe this is the same issue.

**Comment by danielmewes** [comment]
I don't think we should block the UI by the way, we should just try to figure out what's going on with the number of replica calculation/display.

**Comment by deontologician** [comment]
Yeah, I remember this. I agree, we need to nail down the core issue

**Comment by danielmewes** [comment]
Just realized that this is the same issue as #4858. The good news is that we mostly understand what's happening.

**Comment by danielmewes** [comment]
Merging with #4858.
