### ISSUE TITLE
Web UI: Don't cache table information on "Tables" page(or expire the cache on a reconfigure)

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#4108]
As of the current version I need to hit F5 on the tables page if I want to see the correct number of shards and replicas for each table after a reconfigure(on the UI or using ReQL)

**Comment by danielmewes** [comment]
That's weird. It should refresh periodically, and also when you switch back to the tab.

The next time this happens, can you check if there is any error in the JavaScript debugging console of your browser?

**Comment by danielmewes** [comment]
Going to close this since it's a pretty old issue and as far as I know we haven't seen it again. Or have you run into this again recently @thelinuxlich ?

**Comment by thelinuxlich** [comment]
No, i guess it is fixed
