### ISSUE TITLE
WebUI: bad interaction when the resultset is empty

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#4110]
1. Start RethinkDB
2. Connect your browser to the web UI, go to the Data Explorer
3. Create an empty table (say, `users`)
4. Run the query `r.table('users')`

The output will look like this:

![screen shot 2015-04-23 at 6 00 21 pm](https://cloud.githubusercontent.com/assets/48436/7310540/b18a5a48-e9e2-11e4-8011-ed7dda35fbed.png)

This is super-confusing because the string "No results returned" isn't noticeable, so it looks like there is a bug. I believe the tree view used to show an empty array in these cases (`[]`), which makes a lot of sense.

Also, if I switch to the table view, it will say the following:

![screen shot 2015-04-23 at 6 02 59 pm](https://cloud.githubusercontent.com/assets/48436/7310558/0557f50e-e9e3-11e4-88e0-4ea03fe0c9eb.png)

This error message is confusing -- it should say "No results were returned for this query" (without the "more"). This error message probably comes from the fact that if I get a result set and keep clicking "next", eventually saying "no more results were returned" makes sense, but it doesn't make sense for the first message.

Alternatively, we can show an empty array in the table view too, and it will probably be ok.

/cc @deontologician, @mglukhovsky 

I think it's worth fixing sooner rather than later, as empty resultsets come up pretty often.

**Comment by danielmewes** [comment]
Pinging @AtnNn for this as well, since he might have additional insights.

**Comment by AtnNn** [comment]
In review 2977 by @deontologician

**Comment by AtnNn** [comment]
Fixed in cdd96f5
