### ISSUE TITLE
Unable to update document key with a new nested object

### ISSUE THREAD

**Issue by suparngp** [rethinkdb/rethinkdb#4113]
Its a straightforward use case:
Current version of document in the rethink db is 
<pre>
<code>
    {
        content: 'Hello! How are you.',
        id: '17a1c401-3a40-4378-ad25-889ba8fb4a16',
        title: 'John Doe' 
    }
</code>
</pre>

Lets say you want to add a new key address which has two nested fields, city and zip. 
<pre>
<code>
r.table("blogs").get(the_id).update({address: {zip: "94894", city: "MV"}}).run()

Results in:

{
        address: {},
        content: 'Hello! How are you.',
        id: '17a1c401-3a40-4378-ad25-889ba8fb4a16',
        title: 'John Doe' 
    }
</code>
</pre>

**Comment by coffeemug** [comment]
@suparngp -- something strange is going on -- when I run your query I get the result you'd expect (the address in the document, not an empty address field).

How are you running the query? Via the Data Explorer, or via a driver (and if so, which driver?) How are you checking the result? What's the output of `r.table("blogs").get(the_id)`?

**Comment by suparngp** [comment]
I am using the rethink client for node JS. I will give it a shot again in a couple of hours. If it still doesn't work, I will post the further details. 

Thanks @coffeemug

**Comment by suparngp** [comment]
There was a bug in my code. The field was getting overridden by a middleware.

Sorry for the trouble.

**Comment by danielmewes** [comment]
@suparngp Glad to hear it's now working.
