### ISSUE TITLE
changefeeds and sub-queries

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#4117]
Some non-constant sub-queries are currently treated as constant when calling `changes`. Perhaps they should instead error out or, even better, recursively listen for changes.

```
>>> c = r.table('a').get(r.table('b').get(1)('a')).changes().run()
>>> c.next()
{"new_val":{"id":0}}
>>> r.table('b').get(1).update({a:1}).run()
>>> c.next()
```

```
r.table('a').get(r.random()).changes()
```

**Comment by mlucy** [comment]
Not sure whether to mark this as a feature request or a bug.  I think long-term we should try to recursively listen for changes.

**Comment by danielmewes** [comment]
Marking as ReQL_proposal, since it doesn't seem obvious if we should error on these queries or keep allowing them.

**Comment by timmaxw** [comment]
I think we should error on these queries in the short term, and do what @mlucy suggested in the long term. If users want the current behavior they should run `r.table('b').get(1)('a').do(lambda a: r.table('a').get(a).changes())`.

**Comment by danielmewes** [comment]
Superseded https://github.com/rethinkdb/rethinkdb/issues/5212
