### ISSUE TITLE
ssl suport patch breaks in stock MacOS on Python

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4119]
When the ssl support was added to the Python driver (in #4076) the `backports.ssl_match_hostname` module was not added, so Python versions prior to 2.7.9 don't have what they need. This includes all current versions of MacOS through 10.10.3.

The fix for this is to include that module in the Python driver.

**Comment by larkost** [comment]
The review for this is up with `CR 2827`, from branch `larkost/4119-ssl_match_hostname-backport`

**Comment by larkost** [comment]
This has been merged into `next` with b0f23dc.

**Comment by sebastianneubauer** [comment]
this commit breaks version 2.1.0. see #4683 
> ImportError: No module named backports.ssl_match_hostname

backports folder does not end up in package!!

Consider adding tests for correct installation and packaging, e.g. with tox...

Why not just adding 'backports.ssl_match_hostname' to requirements? It's on pypi...

**Comment by larkost** [comment]
This is all covered in #4683, including a fix that is in code review at the moment.
