### ISSUE TITLE
Add Ubuntu 15.04 packages

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4123]
@AtnNn

**Comment by danielmewes** [comment]
As a work-around, it appears that the utopic package works fine:
http://download.rethinkdb.com/apt/pool/utopic/main/r/rethinkdb/rethinkdb_2.0.1~0utopic_amd64.deb

**Comment by kamilion** [comment]
Just a note, this won't work on new installs of vivid (15.04). You'll need to grab one additional package first.
http://packages.ubuntu.com/utopic/main/libprotobuf8
Click on your architecture and download the deb.
Here's the 64-bit version:
http://packages.ubuntu.com/utopic/amd64/libprotobuf8/download

Vivid has changed to:
http://packages.ubuntu.com/vivid/main/libprotobuf9

Shouldn't be too long until a 2.0.2 or 2.1 appears, built against libprotobuf9.

**Comment by AtnNn** [comment]
Packages for Ubuntu 15.04 (Vivid) are now available on `download.rethinkdb.com`.

http://www.rethinkdb.com/docs/install/ubuntu/

**Comment by danielmewes** [comment]
:clap:
