### ISSUE TITLE
[JS driver]contains doesn't accept r.row

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#4125]
It does accept an anonymous function though. There may be something similar in the Python driver.

```
// Doesn't work
r.expr([1,2,3]).contains(r.row.eq(2))

// Works
r.expr([1,2,3]).contains(function(doc) { return doc.eq(2)})
```

**Comment by danielmewes** [comment]
Good catch. It seems to be missing a `funcWrap`.

**Comment by danielmewes** [comment]
Adding the Python tag because we have to check if the issue exists there.

**Comment by danielmewes** [comment]
Assigning @deontologician .

**Comment by deontologician** [comment]
in review 2829 by @Tryneus

**Comment by deontologician** [comment]
merged into v2.0.x and cherry-picked onto next.

**Comment by mlucy** [comment]
Re-opening because Daniel extended the scope above; we still need to check whether the bug is present in Python.

**Comment by Tryneus** [comment]
Python funcwraps the arguments to `contains`.

**Comment by deontologician** [comment]
Thanks, sorry about that, forgot to check
