### ISSUE TITLE
null && false !== false && null

### ISSUE THREAD

**Issue by thenightwassave** [rethinkdb/rethinkdb#4131]
In the Data Explorer the following commands result in the comment after the line. Notice lines 3 and 4 where the ordering gives a different result (null && false !== false && null).

````javascript
r.expr(true).and(null); // null
r.expr(null).and(true); // null
r.expr(false).and(null); // false
r.expr(null).and(false); // null

r.expr(true).or(null); // true
r.expr(null).or(true); // true
r.expr(false).or(null) // false
r.expr(null).or(false); // false
````

I don't know if it actually makes a difference anywhere as, for example, branch is defined as: "If the test expression **returns false or null**, the false_branch will be evaluated. Otherwise, the true_branch wlill be evaluated." but wanted to report it just in case. I would think line 4 should return false like 3 is doing.

**Comment by thenightwassave** [comment]
I made an important edit so email summary will be incorrect.

**Comment by mlucy** [comment]
I think this is the behavior I'd expect (it's also the behavior I see in Ruby):

```rb
irb(main):3850:0> false && nil
false
irb(main):3851:0> nil && false
nil
```

**Comment by mlucy** [comment]
It's also the behavior in JS apparently; I think we should keep it.

**Comment by danielmewes** [comment]
Hi @thenightwassave. This is by design. `and` always returns the first argument that is falsy.
We considered changing that at some point, but decided against it. See https://github.com/rethinkdb/rethinkdb/issues/3562 for the discussion.

As for `or`: It should always return the first truthy argument, or the last argument if there is none. It seems like there's a bug actually:
```
r.expr(false).or(null) // false
```

I would expect this to return `null`. @mlucy ?

**Comment by danielmewes** [comment]
Note that JS also does this "right":
```
false || null  // null
null || false  // false
```

**Comment by mlucy** [comment]
I agree; the behavior of `or` there is a bug.  I opened https://github.com/rethinkdb/rethinkdb/issues/4132 for it.

**Comment by thenightwassave** [comment]
I understand the reasoning but I must disagree with the semantics of ````and````. null && false is not undefined - no matter what null could have been the result is always false. 

This is how C# handles it.

**Comment by danielmewes** [comment]
@thenightwassave 
We've had some lengthy discussion about these semantics in https://github.com/rethinkdb/rethinkdb/issues/1721 if you're interested. I think my opinions are pretty similar to yours, but in the end we decided to go with JavaScript semantics.

**Comment by thenightwassave** [comment]
Thanks, I think I read through that issue awhile ago but didn't connect it to this issue until you linked it. Thanks again and glad I could still help find a similar bug.
