### ISSUE TITLE
Fix behavior of `or`

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#4132]
`r(false).or(nil)` should return `nil` (but `r(nil).or(false)` should continue to return `false`).

**Comment by danielmewes** [comment]
Actually even `r.(nil).or(nil)` returns `false` at the moment.

**Comment by thenightwassave** [comment]
@danielmewes 
Just interesting, but reading the thread you linked me to in the other issue shows mlucy noticed that variation when you were discussing it over there (last line in comment): https://github.com/rethinkdb/rethinkdb/issues/3562#issuecomment-69827122

**Comment by mlucy** [comment]
This is in next (the review was completed a while ago and I had just forgotten to merge it in).
