### ISSUE TITLE
r.expr(true).and('foo') returns 'foo'

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#4135]
Is that expected?

`r.expr(true).and('foo').and(true)` returns `true`
`r.expr(true).and(null).and(true)` returns `null`

**Comment by danielmewes** [comment]
That seems right to me.
Compare JS:
```js
< true && 'foo' && true
> true
< true && null && true
> null
```

**Comment by neumino** [comment]
I'm amazed. Sorry for the wrong bug :)
