### ISSUE TITLE
Use an HVM image as the base for the RethinkDB AMI

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#4141]
Users have been asking for it on twitter and the documentation suggests it:

> For the best performance, we recommend that you use current generation instance types and HVM AMIs when you launch new instances

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html

I've made the change, I'll put it up for CR after I've tested it.

**Comment by AtnNn** [comment]
Support for this in 850805b, but there seems to be another difficulty in supporting HVM:

> Unfortunately, due to service limitations, when changing your virtualization type, your product would have to appear as a brand new listing on the AWS Marketplace.
>
> In these cases, your product will lose its reviews, as we’ll need to remove the previous (PV version) from the Marketplace.

**Comment by danielmewes** [comment]
> In these cases, your product will lose its reviews, as we’ll need to remove the previous (PV version) from the Marketplace.

That sounds ok. It's not like we have much choice.

**Comment by danielmewes** [comment]
Our new listing is finally up :-) https://aws.amazon.com/marketplace/pp/B013R60Q8Y
It's currently at 2.0.4. Will update to 2.1.2 once we have that out.

**Comment by danielcompton** [comment]
It could be good to link to the new AMI https://aws.amazon.com/marketplace/pp/B013R60Q8Y/ref=sp_mpg_product_title?ie=UTF8&sr=0-2 from the old one: https://aws.amazon.com/marketplace/pp/B00E9EZ5DK in the marketplace description.

**Comment by danielmewes** [comment]
The old listing was meant to be taken down, but it looks like that hasn't happened yet. I'll ask Amazon about it.
