### ISSUE TITLE
STATUS throws exception if table does not exist

### ISSUE THREAD

**Issue by wereHamster** [rethinkdb/rethinkdb#4142]
In ql2.proto the STATUS term is described as having the type `Table -> SingleSelection`. I was told that SingleSelection is (OBJECT or NULL), ie. if the object is not found then NULL is returned. However, when I run STATUS on a non-existing table then the server thows an exception. Contrast that to GET which returns NULL if the entry doesn't exist.

Also, why should I use STATUS over `r.db('rethinkdb').table('table_status').get('table_name')`? Ignoring the difference in handling non-existing entries, those two seem equivalent.

**Comment by danielmewes** [comment]
The reason this is happening is that one of the arguments to STATUS is the TABLE, and TABLE fails if you evaluate it on a non-existing table name. It's not STATUS that's failing, but its argument.

STATUS is simply a short cut for the system table read. The only reason for using it is that it's shorter to write.

Does that make sense?

**Comment by wereHamster** [comment]
I see. Wouldn't it make sense though to change its type to `Table -> Object` since it can't fail in a graceful way and always returns an `Object`?

**Comment by timmaxw** [comment]
The reason it's `SingleSelection` instead of `Object` is that `.changes()` works on `SingleSelection` but not on `Object`.

**Comment by mlucy** [comment]
Also updates work on selections.

**Comment by danielmewes** [comment]
> Also updates work on selections.

... though not on `status`
