### ISSUE TITLE
deleting multiple indexes stops any writes and they don't resume afterwards

### ISSUE THREAD

**Issue by digi604** [rethinkdb/rethinkdb#4144]
i needed to restart the processes

**Comment by danielmewes** [comment]
Did the whole rethinkdb process become unresponsive or "just" a certain set of write queries?

I think it's likely that this has the same underlying cause as https://github.com/rethinkdb/rethinkdb/issues/4137 ...

**Comment by danielmewes** [comment]
Insufficient information at the moment to reproduce (I had tested this briefly and appeared to work). Closing for now.
