### ISSUE TITLE
inserts into db with indexes completely destroys performance.

### ISSUE THREAD

**Issue by digi604** [rethinkdb/rethinkdb#4145]
db with 10 indexes. writes are at around 300/s. If i remove the indexes i get 2k/s

**Comment by danielmewes** [comment]
Ignoring the question of whether your system is going into swap or not (https://github.com/rethinkdb/rethinkdb/issues/4137), a reduction in write performance of 10x is actually quite reasonable for 10 indexes.

Writing 10 indexes is roughly 10 times the work of writing a single one.

Are you specifying soft durability for the writes or using the default of hard durability?

**Comment by digi604** [comment]
it's soft and noreply on the connection

**Comment by digi604** [comment]
anyway 300w/s is not even remotely acceptable for me for 4cores.

**Comment by danielmewes** [comment]
@digi604 How much CPU utilization and disk (SSD) throughput (reads and writes) are you seeing while running the inserts?

I assume these are the same types of batched inserts that you described in the other issue (https://github.com/rethinkdb/rethinkdb/issues/4137)?

**Comment by danielmewes** [comment]
Closing because we don't have enough details to investigate this further at the moment.
