### ISSUE TITLE
timeOfDate() and date() ignore timezone

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4149]
Noticed by @neumino in https://github.com/rethinkdb/docs/issues/744 : 
```js
r.time(1986, 11, 3, "+00:00").date()
Mon Nov 03 1986 00:00:00 GMT+00:00

r.time(1986, 11, 3, "+02:00").date()
Mon Nov 03 1986 02:00:00 GMT+02:00
```

I feel like this might be a bug, since it behaves *really* badly in some cases:
```js
r.time(1986, 11, 3, 23, 0, 0, "-02:00").inTimezone("+00:00")
Tue Nov 04 1986 01:00:00 GMT+00:00
// So this time is on the 4th in UTC, and on the 3rd in -02:00. But let's see what date makes of it:

r.time(1986, 11, 3, 23, 0, 0, "-02:00").date()
Sun Nov 02 1986 22:00:00 GMT-02:00
// It's saying that this is on the 2nd! This doesn't seem to make any sense to me.
```

`timeOfDate` has a similar problem, and I think this is almost certainly a bug:
```js
r.time(1986, 11, 3, "+02:00").timeOfDay()
-7200
```

Note that it returns a negative number.

mentioning (@neumino , @mlucy)

**Comment by mlucy** [comment]
OK, let's change this.

**Comment by mlucy** [comment]
Note to self: when you change this, make sure that `t1.date().eq(t2.date())` returns true if `t1` and `t2` are on the same date in different timezones.

**Comment by thelinuxlich** [comment]
Workaround for date() until this bug is solved:

```
// supposing your date field is called "created_at"
row("created_at").sub(row("created_at").hours().mul(3600)).sub(row("created_at").minutes().mul(60)).sub(row("created_at").seconds())
```

**Comment by mlucy** [comment]
I thought a little bit more about the correct behavior for this, and I think my note to myself above is incorrect.  (Or, rather, it's impossible to satisfy that constraint without things behaving really weirdly.)

I think the most intuitive behavior is this:
```
irb(main):107:0> tm = Time.now
2015-07-09 00:14:29 -0700
irb(main):108:0> r(tm).run
2015-07-09 00:14:29 -0700
irb(main):109:0> r(tm).date.run
2015-07-09 00:00:00 -0700
irb(main):110:0> r(tm).in_timezone('-08:00').run
2015-07-08 23:14:29 -0800
irb(main):111:0> r(tm).in_timezone('-08:00').date.run
2015-07-08 00:00:00 -0800
```

This makes comparing dates in different time zones not work, but it's the only way of doing things (short of introducing a separate date type) that actually makes times that occur on the same day in a particular time zone produce the same output from `date`.  (It also makes `time_of_day` accurate.)

**Comment by mlucy** [comment]
In CR 3057 by @Tryneus .

**Comment by danielmewes** [comment]
@mlucy that behavior looks good to me.

**Comment by mlucy** [comment]
@danielmewes -- this change should only be for 2.1, right?

**Comment by danielmewes** [comment]
Yes 2.1 only.

**Comment by mlucy** [comment]
This is in next.
