### ISSUE TITLE
Mention index optarg for order_by in ql2.proto

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4151]
Pointed out by @hamiltop in https://github.com/rethinkdb/docs/issues/730#issuecomment-97660113

> I'll also add that it isn't clear you can provide options for order_by. Correct me if I'm wrong but:
> 
> ```
> ORDER_BY   = 41; // Sequence, (!STRING | Ordering)... -> Sequence
> ```
> 
> should read:
> 
> ```
> ORDER_BY   = 41; // Sequence, (!STRING | Ordering)..., {index: !STRING} -> Sequence
> ```

**Comment by hamiltop** [comment]
I'll submit a PR :smile:

**Comment by danielmewes** [comment]
Closed by https://github.com/rethinkdb/rethinkdb/pull/4152
