### ISSUE TITLE
OS X dmg: ugly hidden files

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#4153]
This article has a screenshot of the OS X package that shows some hidden files, .background.tiff, .DS_Store, .Volume.ico and .Trashes. Those files clash with the design:

https://strongloop.com/strongblog/rethinkdb-connector-loopback-node-js-framework/

**Comment by larkost** [comment]
This means that the person has done `defaults write com.apple.finder AppleShowAllFiles YES`. I consider that a very uncommon setting. Other than trying to work them into the design (which will do nothing for 99% of people), there is really nothing we can do.

I don't consider this a bug on us, but rather a really bad decision on the writer's part to give a very non-standard screenshot.

**Comment by larkost** [comment]
It occurred to me that an alternate route would be to contact them and ask if they would mind replacing the image with one created without the setting. Any objections to me doing so @mglukhovsky? I would use the following image:

![out](https://cloud.githubusercontent.com/assets/7431361/7418479/0646984a-ef23-11e4-9396-9c7b19ce7495.png)

**Comment by mglukhovsky** [comment]
@larkost no objections, thanks!

**Comment by danielmewes** [comment]
@larkost Could we override the AppleShowAllFiles attribute in the folder?

**Comment by FLIR31207** [comment]
I have AppleShowAllFiles set to YES and would find it rather irritating if files like .DS_Store - which I fully expect to see - were not there.

People who go to the extend of setting this on the command line usually know what / why they're doing and won't be confused if the installer looks slightly different than the screenshot, in my opinion.

**Comment by larkost** [comment]
No, this is either a user or system-wide setting. It even overrides `SetFile -a V` (make invisible). It exposes all normally hidden files and there is no way of overriding it that I am aware of.

**Comment by danielmewes** [comment]
I see. Looks like there's indeed nothing we can do then.

**Comment by larkost** [comment]
For the record, I did email callback@strongloop.com with the improved image. I will update this if/when they get back tome.

**Comment by larkost** [comment]
They got back to me to say that they are updating the blog now.
