### ISSUE TITLE
Support MSBuild

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#4155]
MSBuild is the build system used by Visual Studio.

**Comment by danielmewes** [comment]
@AtnNn Can we close this? Or do you think we should get rid of the GNU make dependency alltogether?

**Comment by AtnNn** [comment]
If you use visual studio to work with the rethinkdb source, the current workflow is not ideal. Cygwin needs to be installed, and `make` needs to be run to build the project file and when non-c++ files change.

I think we can close this until it becomes painful for someone.
