### ISSUE TITLE
Bring python driver up to python standards

### ISSUE THREAD

**Issue by jdoliner** [rethinkdb/rethinkdb#416]
The new python driver has several things that look very strange to me as a python programmer. The following things in particular:

- There's no documentation, this means that the standard python methods of calling `help(...)` don't work at all and repl's such as BPython don't offer any help.

- it leaks a lot of its internal structures on import. We have a pretty common pattern in it that we have a class to represent an AST node and then a function which instantiates that class. It's very confusing to see both `r.db` and `r.DB` especially since neither has any documentation. This is also bad because it doubles the number of things in the module which gives you more to scan through. It also shows a number of things that have no meaning to a user such as `p` and `T`.

- Operators `all` and `any` are only present as the classes `Any` and `All` this is inconsistent because you call `branch` as `r.branch` but `any` as `r.Any`. I also suspect this isn't reflected in our docs and is incongruous with the other drivers.

- Many of the objects aren't Thread safe. I'm not 100% sure what python programmer expectations are on this but the way we break when connections and functions are passed between threads is going to be very confusing. 

@timmaxw would you mind also taking a look at this code. It's in the branch ql-refactor in drivers/python2.

**Comment by larkost** [comment]
This is an old issue, with a lot of conversation. We actually have everything but one done:

- [x] `help()` does not work - done in 2013 or before
- [x] leaks internal structures on import - done in #2343
- [x] `r.any` and `r.all` were removed at some point
- [ ] Python driver does not support multiple threads - covered in #2427 and #4448
- [x] `Cursor` and `Connection` should inherit from `object`
- [x] `RDBBase`, `RDBOp`, `RDBValue`, `RDBMethod`, `RDBTopFun`, and `RDBBiOper` could be subclasses of `RDBValue` - all replaced at some point
- [x] `Connection` should be publicly available
- [x] `Cursor` should discard old results
- [x] `Connection` should throw RethinkDB specific errors
- [x] `Cursor.__del__` should close the connection with a `Cursor.close()`
- [x] Use `None` (as opposed to `()`) to denote empty keyword arguments
- [x] In expr(): Consider replacing isinstance(val, types.LambdaType) with callable(val) - uses `isinstance(val, collections.Callable)` which is the same thing.
- [x] renaming `build()`, `compose()`, `deconstruct()`, and so on to `_build()`, `_compose()`, `_deconstruct()`, etc. so it's obvious that users shouldn't call them - these are now all hidden within the package
- [x] The class `MakeArray` overrides `do()` with something identical to its parent definition - done in 153a96ab

So the only issue left is the threading one, and that is well covered in the referenced issues.
