### ISSUE TITLE
Generated web assets in Visual C++

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#4162]
Visual C++ seems to have a 65535 character limit for string literals that the generated web-assets `cc` file does not respect.

**Comment by danielmewes** [comment]
@AtnNn This is fixed in atnnn/windows3 with your switch to using a resource file, right?

**Comment by AtnNn** [comment]
Yes. On windows I now use an RC file to bundle the web assets (currently in review). This avoids the issues that MSC had with the huge `web_assets.cc` file.
