### ISSUE TITLE
Build and run the unit tests on Windows

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#4164]
There are 64 test groups to build and run.

I'm going to find a way to easily build and run each unit test individually, even if there are files that don't build or link. I should be able to use that as a rough guideline for the Windows port.

**Comment by AtnNn** [comment]
1 of 64 done. 63 to go.

![first unit test](https://cloud.githubusercontent.com/assets/706854/7578754/70e7cfcc-f80e-11e4-8627-9f3d1e46ef25.PNG)

**Comment by AtnNn** [comment]
I got some more tests to pass, including the `ContextSwitchingTest` which now uses Fibers.

![4](https://cloud.githubusercontent.com/assets/706854/7855928/18acde64-04da-11e5-88de-834b15daf0f0.PNG)

**Comment by AtnNn** [comment]
All tests now pass except for

* `ClusteringRaft.Fuzzer` occasionally hangs for a very long time
* `ExtProc` and `JSProc` tests fail because extprocs are not implemented on windows

**Comment by AtnNn** [comment]
`ExtProc` tests now all pass in the windows branch.

Fixing a bug in my implementation of `get_monotonic` improved the performance of `ClusteringRaft.Fuzzer`.

`JSProc` are still broken, I'm hitting this bug https://code.google.com/p/v8/issues/detail?id=4192. There is an easy workaround I have yet to try.

**Comment by danielmewes** [comment]
> `ExtProc` tests now all pass in the windows branch.

:clap: Great progress!

**Comment by danielmewes** [comment]
Regarding the `JSProc` issue: Have you tried building V8 without snapshots? It will be very slow, but I think it would be ok for a beta release.

**Comment by AtnNn** [comment]
No, that is the easy workaround I have yet to try.

**Comment by AtnNn** [comment]
Solved by building v8 with `-Dv8_use_external_startup_data=0`.
