### ISSUE TITLE
Web UI: Server times

### ISSUE THREAD

**Issue by aranw** [rethinkdb/rethinkdb#4173]
I just came across an issue during development due to Timezones being out across machine.

When I was debugging it I wanted to see what timezones my database was operating in but couldn't figure it out without looking at the graph and checking on the server via SSH. 

I thought it would be useful for the time of the servers be visible in the Web interface, with current timezones.

**Comment by AtnNn** [comment]
@aranw What was the issue you came across that was due to Timezones being different?

I believe the result of all queries is independent of the local time of the servers.

**Comment by aranw** [comment]
Looking at the control panel the cluster performance graph is showing the time based on my local machine which is in BST at the moment. 

I've had to alter one of my queries to include the timezone to prevent queries failing.

**Comment by danielmewes** [comment]
@aranw 
> I've had to alter one of my queries to include the timezone to prevent queries failing. 

Which query or command was that?
Like @AtnNn said, all ReQL queries should be independent of the timezone that the server is using. If that is not the case, that's very likely a bug which we should fix.

**Comment by danielmewes** [comment]
We don't have enough information to investigate this at the moment.
@aranw . Please feel free to re-open the issue.
