### ISSUE TITLE
ENOENT, open 'tls' while resolving "tls"

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4175]
On `next` as of 04c4af6073eec2dac1512ba0f5f488edab07256f while compiling on arclight:
```
    [1/7] BROWSERIFY build/drivers/javascript/rethinkdb.js
Error: ENOENT, open 'tls' while resolving "tls" from file /home/daniel/rethinkdb/build/packages/js/net.js
make[1]: *** [build/drivers/javascript/rethinkdb.js] Error 1
```

I had to do `npm install tls` manually to get it working.

Is this a missing dependency we need to declare something?
Or should we modify the JS driver to work in the absence of the `tls` module?

@deontologician @AtnNn any ideas?

**Comment by AtnNn** [comment]
We should probably change the way the tls module is imported so that browserify doesn't try to package it with the web ui where it is not needed.

**Comment by deontologician** [comment]
Yeah it should be a core nodejs module, but as @atnnn said, we don't need it on the frontend, so we can probably fiddle with it to avoid the import in the browser

**Comment by AtnNn** [comment]
Fixed by adding `--ignore tls` to the browserify command line. In 1b24006
