### ISSUE TITLE
update bluebird version

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4178]
In updating the JavaScript connection tests for #4027 I added `BLUEBIRD_DEBUG = 1` to the env variables to prompt bluebird to give better stack traces. Unfortunately a bug in the version of the library that we include (2.3.2) that makes it very slow when we have a lot of items to process and this env variable when is set. I replaced that with 2.9.25, and that fixes the problem. Obviously we would need to throughly test a new version, but we should look at updating bluebird.

In a related area, we are currently including all of the bluebird files in our repository rather than downloading them like we do for some other libraries. There well may be a reason for this, but we should at least evaluate it when replacing all of the files.

In the mean time I am going to not enable the debug output generally, but would like to have this generally as it sometimes makes the output better (but generally the JavaScript stack traces are near worthless).

**Comment by AtnNn** [comment]
:+1: for updating bluebird.

The reason we keep a copy of bluebird in the repo is because we bundle it with the driver into the web ui. Otherwise we would run into issues like #4175.

**Comment by larkost** [comment]
Note: `test/rql_test/connections.mocha.runner` should have the `BLUEBIRD_DEBUG` line re-enabled once this is done.

**Comment by deontologician** [comment]
I think I ran into this problem too and just gave up trying to get stack traces that made sense. +1 for updating bluebird from me too

**Comment by AtnNn** [comment]
Bluebird version bumped to 2.9.25 in 1b24006
