### ISSUE TITLE
JS driver: r.row doesn't work in group

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4180]
Something like `r.expr([{a: 1}, {a: 2}]).group(r.row('a'))` doesn't work in the Data Explorer:
`t: r.row is not defined in this context in: [...]`

`r.expr([{a: 1}, {a: 2}]).group(function(x) { return x('a'); } )` works fine.

**Comment by deontologician** [comment]
This is working fine in 2.0.x, it's broken on next

I tried doing a bisect, but there were a number of non-compiling builds that made it hard to do it right. I'll try it with a stricter criterion for success tomorrow.

**Comment by deontologician** [comment]
This seems to be working again on next.

**Comment by deontologician** [comment]
To clarify, I was able to replicate it on next in May, but not any longer.
