### ISSUE TITLE
Update web UI code for ReQL admin changes

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4181]
There will be a few changes in the ReQL admin interface that we need to update the web UI logic for.

**Comment by timmaxw** [comment]
This issue isn't terribly useful on its own; the server side isn't finished yet and it will be finished bit by bit. As we finalize each piece of the server side we should open separate web UI issues. This issue can server as a reminder to make sure the web UI gets done eventually, though.

**Comment by timmaxw** [comment]
Here's a tentative list of things that will need to be changed:
* Web UI issues display will need to be updated when issue formats change. Some of the changes are covered in #4182. Also, we'll need to make some changes to the server issues as part of #3897.
* The `table_status` format has changed, and the web UI will need to be updated. This is blocking on #4196.
* If #3891 makes it in, we'll need to update the web UI for that.

**Comment by danielmewes** [comment]
* On a table's page under "Servers used by this table", we show which server is the Primary replica based on the table config. If the configured primary is currently disconnected and the table has switched over to a different primary, we should show that somehow.

**Comment by deontologician** [comment]
Closing in favor of #4283, #4284, and #4288
