### ISSUE TITLE
Fix table name conflict issue detection

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#4183]
Right now in `raft` we don't detect name conflicts on tables. We should fix this. It should be fairly easy to fix; we just need to thread the `table_meta_client_t *` into the `name_collision_issue_tracker_t` and make it fetch the list of table names/DBs that way.

**Comment by VeXocide** [comment]
In CR 2870 by @timmaxw.

**Comment by VeXocide** [comment]
Merged into `raft` via commit 0f4c32594b8075eac8a73e0a5ec106ebfd99d821.
