### ISSUE TITLE
Ruby driver does not appear to correctly handle nested field notation as an argument

### ISSUE THREAD

**Issue by eliaslevy** [rethinkdb/rethinkdb#4184]
A query like `t.with_fields( fp: :fn).group { |r| r['fp']['fn'] }.run` returns the expected results.  But `t.with_fields( fp: :fn).group( fp: :fn).run` returns an error:

```
RethinkDB::RqlCompileError: Unrecognized optional argument `fp`.
Backtrace:
r.db("test").table("queries").with_fields({"fp" => :fn}).group({"fp" => :fn})
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by danielmewes** [comment]
Hi @eliaslevy , this is a limitation of `group` itself, see https://github.com/rethinkdb/rethinkdb/issues/2206 .

We plan to add this functionality, but decided to work on some other features first. We'll hopefully be able to schedule it for one of the upcoming releases.
