### ISSUE TITLE
Tutorial for subscribing to changes

### ISSUE THREAD

**Issue by MrDunne** [rethinkdb/rethinkdb#4191]
Any good tutorials for using RethinKDB in C#? The main one I'm interested in is subscribing to new inserts in a table, sort of like the example on the RethinkDB website.

**Comment by danielmewes** [comment]
I'm not aware of a tutorial that uses changefeeds with C#, but I imagine it will be similar to other languages.

The current version of rethinkdb-net https://github.com/mfenniak/rethinkdb-net has support for the `Changes` command.

I don't know much C#, but I imagine that something if you take the example that they have in their README and add a line like this to `Main` it should work:
```
[...]
    // Print all changes that arrive for the table
    foreach (var change in conn.Run(Person.Table.Changes())
        Console.WriteLine("Change: {0}", change);
[...]
```

**Comment by danielmewes** [comment]
@mfenniak can probably help you better with this.

**Comment by mfenniak** [comment]
@McDunne -- there's an example of a C# program using the Changes query here: https://github.com/mfenniak/rethinkdb-net/blob/master/Examples/RethinkDb.Examples.ConsoleApp/Program.cs.  If you have any issues with this, or need any help, please open an issue at the [rethinkdb-net repository](https://github.com/mfenniak/rethinkdb-net), and I'll help you out.
