### ISSUE TITLE
Change `table_meta_client::list_configs` behaviour

### ISSUE THREAD

**Issue by VeXocide** [rethinkdb/rethinkdb#4193]
As discussed in #3883 we do not want `table_meta_client::list_configs` to throw when it fails to contact any server for a particular table.

**Comment by timmaxw** [comment]
Related changes:
* `rethinkdb.stats` should produce error documents for tables it couldn't fetch the config for.
* `rethinkdb.table_config` should also produce error documents. If the user tries to write back an error document we should produce an actual error.

**Comment by timmaxw** [comment]
Fixed in df0dcf13968553737f3049729c1aa84d45022c8f. I decided to make `rethinkdb.stats` silently drop inaccessible tables instead of erroring.
