### ISSUE TITLE
Explicit "action" field in changefeed documents

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4194]
Suggested by Steven Perez.

In changefeed documents, we currently implicitly encode whether they are a deletion, and insertion, an update/replace or an initial result by setting some of `old_val` and `new_val` to `null` or by omitting `old_val` entirely.

The proposal is to encode this information explicitly by adding an additional field. For example
`action: 'delete'`
`action: 'insert'`
`action: 'replace'`
`action: 'initial'`

Incidentally, our current system also breaks if you have a changefeed like this:
`r.table('t1')('a').changes()`

and you set the value of `a` to `null` for a document. The generated change event will be indistinguishable from a deletion. Additionally, when deleting a document that currently has `a: null`, no change event is generated.

**Comment by marshall007** [comment]
I like this a lot! It would allow you to easily filter by the "type" of change being emitted, which is what I was getting at in [#3719 (comment)](https://github.com/rethinkdb/rethinkdb/issues/3719#issuecomment-95760238).

**Comment by StevenPerez** [comment]
Excellent 👍🏻

Thanks for listen Wise Rethinkdb Partners

**Comment by mglukhovsky** [comment]
@danielmewes: I'm a fan of this, usually I check for the values of `old_val` + `new_val` to infer what happened, but the case you stated is definitely ambiguous!

**Comment by StevenPerez** [comment]
Mike - I think you are right in terms that it is ambiguous, in the other hand, it is more syntax clear to have the action, for example:

```javascript
// Current
r.table('t1').changes().run(conn, function(err, cursor) {
   cursor.each(function(n, el){
      if (el.old_val == null && el.new_val != null) // Do something if Inserted
         // Do something
      else if (el.old_val != null && el.new_val != null) // Do something if Updated
         // Do something
      else if (el.old_val != null && el.new_val == null) // Do something if Deleted
         // Do something
   });
});

// If action
r.table('t1').changes().run(conn, function(err, cursor) {
   cursor.each(function(n, el){
      if (el.action == 'Inserted')
         // Do something
      else if (el.action == 'Updated')
         // Do something
      else if (el.action == 'Deleted')
         // Do something
   });
});
```

Maybe there are more critical features :), so this issue can be made in the future.

**Comment by mglukhovsky** [comment]
@StevenPerez: actually, I was saying that the case @danielmewes stated is ambiguous and is a good reason for adding an `action` to the changefeed, so we're in agreement:

> Incidentally, our current system also breaks if you have a changefeed like this:
> `r.table('t1')('a').changes()`
> and you set the value of a to null for a document. The generated change event will be indistinguishable from a deletion. Additionally, when deleting a document that currently has a: null, no change event is generated.

**Comment by StevenPerez** [comment]
Mike - Got it :+1: ,  sorry It was my bad :) , I'm glad to know you are agree =)

**Comment by danielmewes** [comment]
Merging with https://github.com/rethinkdb/rethinkdb/issues/5188
