### ISSUE TITLE
Benchmark backfilling and determine if we need to change the algorithm

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#4195]
The current backfilling algorithm has the potential to spend O(N^2) time updating metainfo. There's an alternative algorithm that doesn't have this limitation. We should benchmark backfilling and possibly change the algorithm. The change would be ~1 week of work.

**Comment by danielmewes** [comment]
Self-assigning.

**Comment by danielmewes** [comment]
I've done a couple of benchmarks of backfilling under heavy writes to the table and backfilling performance as well as the throughput and latency of other writes while backfilling seem to be ok in practice.
