### ISSUE TITLE
Server gets stuck

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4202]
I was playing with backfills on `raft` with a 3-server cluster.

I had servers get stuck twice. They would not accept connections anymore and were not CTRL+C-able. At least in one case I saw 100% CPU usage on one core.
Have to investigate more.

This was in release mode.

**Comment by danielmewes** [comment]
Just had this happen again. The moment I shut down one server in a two server cluster, the remaining server froze with 100% CPU on one core.

**Comment by timmaxw** [comment]
Fixed in cb29cbcb12f8e29bc2289eb01000369ad340f832.
