### ISSUE TITLE
table_status incorrectly reports disconnected

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#4209]
Steps to reproduce:
1. Create a table with 1 replica
2. Reconfigure it to have 2 replicas
3. Observe that in the new status field of the response, the new replica is marked as disconnected

**Comment by VeXocide** [comment]
https://github.com/rethinkdb/rethinkdb/blob/raft/src/clustering/administration/tables/calculate_status.cc#L141 currently checks whether there's a reply from the server to determine whether it's connected. It might be better to handle the servers listed in the config and contract differently.

**Comment by VeXocide** [comment]
In CR 2941 by @timmaxw.

**Comment by VeXocide** [comment]
In CR 2949.

**Comment by VeXocide** [comment]
Merged into `raft` via commit b09683f13163f474ae0bfacdd5b299fbb13f5cd2.
