### ISSUE TITLE
Sort dates and times with millisecond precision.

### ISSUE THREAD

**Issue by pgrm** [rethinkdb/rethinkdb#4217]
Hi, sometimes I'm inserting several data sets within the same second. I'd afterwards again like to get them in the same order as they've been inserted, is that planned, or is it not really possible to implement?

In any case, is there a best-practice workaround for that for now? Out of the top of my head, I could think of just storing the raw `Time.now.to_f` and handling all date/time conversions in the applications which would access the db. But this seems like a bit of overhead on the application development part, and if somewhere someone in some library forgets to convert it to UTC, it will be screwed up. So maybe someone had figured it out already?

Thx, Peter

**Comment by danielmewes** [comment]
Hi @pgrm, RethinkDB times already have millisecond precision. So the easiest way of doing this is to add a `insertion_time` field to each document and setting it to `r.now()` on insert.

Then you can create an index on the field and sort by insertion time like this:
```js
r.table(...).orderBy({index: "insertion_time"})
```

Alternatively you can save the additional index and use a combination of time and UUID for your primary index. For example:
```js
r.table(...).insert({...., id: [r.now(), r.uuid()]}, {returnChanges: true})
```

Your primary IDs will thus be an array consisting of both the timestamp in its first component and a random UUID as its second component, just in case two inserts happen at exactly the same time.
The `{returnChanges: true}` makes sure that you can get the generated key back after the insert (see http://rethinkdb.com/api/javascript/insert/ for more information).

To get the documents in insertion time order then:
```js
r.table(...).orderBy({index: "id"})
```

Note that `r.now()` will be evaluated on whichever RethinkDB server you are connected to, so if you're using a RethinkDB cluster you should probably make sure that the server clocks are well synchronized.

Does this solve your use case?

**Comment by pgrm** [comment]
Hi @danielmewes sorry for the confusion. I guess I misunderstood the sentence in the [documentation](http://rethinkdb.com/docs/dates-and-times/):

> Times are considered equal if their seconds since epoch (UTC) are equal, ...

in a way, that milliseconds don't matter for it to be equal. This together with choosing some wrong sample data, which had only second precision made me think RethinkDB isn't considering it for sorting. 

Sorry for the confusion and thx for the kind answer.

**Comment by danielmewes** [comment]
Ah the "seconds since epoch" in that case is a floating point number, and the milliseconds are in fact considered for the equality comparison.
I opened https://github.com/rethinkdb/docs/issues/762 to make the documentation clearer. Thanks for bringing it up.
