### ISSUE TITLE
Allow more values in multi-indexes.

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#4222]
We currently limit multi-indexes to 256 values per row.  This is a limit that can be hit pretty easily in the real world.  I think we should change our key format in the near(ish) future to use 2 or 4 bytes to store the multi-index tag rather than 1.

This would also give us a good answer to questions like http://stackoverflow.com/questions/30184818/rethinkdb-text-search .

@danielmewes, any thoughts?

**Comment by danielmewes** [comment]
The problem with many key values is that writes to that every write to that document can become extremely slow.
That being said I'm not a big fan of artificial limits, so I wouldn't be opposed to increasing it to 2 bytes or so.

**Comment by danielmewes** [comment]
Putting into backlog for now though. Even with this we won't be very good at text search.

**Comment by mlucy** [comment]
@danielmewes -- I was reading about mongo text indexes, and as far as I can tell they just do this and people are OK with the significant performance consequences (http://docs.mongodb.org/manual/core/index-text/).

I don't think that's the biggest problem, though; I think even if you're using multi-key indexes for other things it's easy to hit this limit in production (restaurants can have more than 256 locations, etc. etc.).  This is a pretty easy fix aside from the migration issue, I think we should consider doing it sooner rather than later.

**Comment by danielmewes** [comment]
Fair enough.

**Comment by marshall007** [comment]
It might be cool to compliment this with a `string.ngram(<min_gram>, <max_gram>)` which could basically just be a rewrite to:

```js
r.range(<min_gram>, <max_gram>).map(function (i) {
  return string.split('').limit(i);
})
```

```js
r.expr('foobar').ngram(1, 3) // -> [ 'f', 'fo', 'foo' ]
table.indexCreate('autocomplete', r.row('term').ngram(2, 5), { multi: true })
```

Having some basic tokenizers like this as part of the ReQL API would make it more obvious that multi-indices can be used to solve use-cases like autocomplete and basic text-search.

**Comment by danielmewes** [comment]
@marshall007 I copied your `ngram` proposal to https://github.com/rethinkdb/rethinkdb/issues/4226

**Comment by mlucy** [comment]
@danielmewes -- would it be alright if we bumped this to 2.2-polish?  It's come up multiple times in the last few months.

**Comment by danielmewes** [comment]
:+1:

**Comment by mlucy** [comment]
I think we should bump this to 4 bytes.  People haven't really been complaining about prefix collisions in their keys, so I don't think saving the extra 2 bytes is a worry, and it will be nice to have the headroom.

**Comment by danielmewes** [comment]
Sounds good. Can we make it backwards compatible easily?

**Comment by danielmewes** [comment]
Also do we currently store the tag for non-multi indexes?
If yes, we might want to change that to avoid the overhead in that case (assuming it's not too hard).

**Comment by mlucy** [comment]
On storing the tag for non-multi indexes: the code is doing something pretty weird, it looks like it isn't including the tag in the non-multi-index case, but it's still using the length of the tag to calculate how much of the sindex key it needs to truncate.  I think that's just a mistake, but the key printing code is absurdly complicated and has a history of breaking in subtle ways, so I'd want to think about it a little more before changing it.  (So, yeah, as of right now I don't see any reason why we can't stop storing the tag for non-multi indexes.)

On backwards compatibility: I think we can make this backwards-compatible without too much work.  We already store the tag offset in the sindex, and we have a fixed 2-byte chunk after the tag, so we can determine the length of the tag easily whenever we have a key.  Our range get logic is already designed to work if you truncate an sindex key too far (since we don't know how long the primary key is and we truncate less for short primary keys), so I think it should just continue working even if the entries in an index have a mix of sindex keys truncated to different lengths.

**Comment by danielmewes** [comment]
Actually it might be better to only support 4 byte tags in indexes with the right (new) reql version.
Imagine you delete a document from a table with an existing index. Currently we compute all the sindex keys based on the value of the document you delete. Then we look up those exact keys in the secondary index tree, and delete them. If we could have both 1 byte and 4 bytes tags in a secondary index, this wouldn't work anymore since we wouldn't know whether the given document had been indexed using the short or the long tags.

**Comment by mlucy** [comment]
That's true, we'd have to do two gets to be backward-compatible.  It's probably less error-prone in general to have it be a separate version and require people to upgrade their indexes.

**Comment by danielmewes** [comment]
Marking settled for using 4 byte tags, only for newly created indexes (which includes migrated indexes). At the same time we should change the code to not reserve space for the tag in the case of non-multi indexes.

**Comment by danielmewes** [comment]
It turned out that we have been using 64 bit tags all along and more than 256 values in a multi index are already working. :-)
