### ISSUE TITLE
`slice` on strings an binary

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4227]
Follow up from https://github.com/rethinkdb/rethinkdb/issues/264 and a question on the mailing list.

The proposal is to make `slice` work on strings and binary data in addition to arrays.
On binary data it would operate on a byte level, and on string data it would operate on UTF-8 code points.

Scheduling for 2.2 since it has come up repeatedly.

**Comment by coffeemug** [comment]
`slice` already works on binary data.

```js
> r.http('https://2.gravatar.com/avatar/767fc9c115a1b989744c755db47feb60?s=132&d=wavatar').slice(10, 20)
<binary, 10 bytes, "00 01 01 00 00 01...">
```

**Comment by danielmewes** [comment]
Oh I didn't realize that. Thanks @coffeemug .
So that just leaves strings.

**Comment by mlucy** [comment]
+1, defining `slice` on strings seems good.

**Comment by coffeemug** [comment]
:+1:

**Comment by VeXocide** [comment]
+1

**Comment by danielmewes** [comment]
Marking as settled (extending `slice` to work on strings, where the indexes should be based on code points).

**Comment by encryptio** [comment]
In CR 3397 with @Tryneus

**Comment by encryptio** [comment]
In `next` as of 85a9f88, will be in 2.3.
