### ISSUE TITLE
`count` on strings and binary

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4228]
Follow up from https://github.com/rethinkdb/rethinkdb/issues/264 and https://github.com/rethinkdb/rethinkdb/issues/1146

The proposal is to make `count` work on strings and binary data in addition to arrays.
On binary data it would count the number of bytes, and on string data I propose it would count the number of UTF-8 code points.

Scheduling for 2.2.

**Comment by danielmewes** [comment]
An alternative is to introduce another term `length` for strings. I would prefer re-using `count`.

**Comment by coffeemug** [comment]
Obligatory reminder that `count` already works on binary blobs:

```js
> r.http('https://2.gravatar.com/avatar/767fc9c115a1b989744c755db47feb60?s=132&d=wavatar').count()
7223
```

**Comment by carbureted** [comment]
Would be awesome to see this!

**Comment by andreis** [comment]
I need to measure the byte size of documents, currently I'm doing

```
.coerceTo('string').coerceTo('binary').count()
```

Is that good enough?

**Comment by mlucy** [comment]
@andreis -- yeah, that should get you the size of the JSON representation of the document.

**Comment by marshall007** [comment]
Not sure if this belongs in a separate issue, but I also think `<object>.count()` should return the number of keys. Basically a shortcut to `<object>.keys().count()` or `<object>.coerceTo('array').count()`.

**Comment by danielmewes** [comment]
@marshall007 Ah that's an interesting idea. I quite like that (though I haven't thought about it too deeply yet).

**Comment by mlucy** [comment]
So the current proposal is just to define `count` on strings?  That seems obviously good to me, so +1.

**Comment by mlucy** [comment]
I would like to propose that we also define `count` on objects and have it count the number of fields.  I think most languages that have a common function that works on arrays and strings also define that function on objects.

**Comment by VeXocide** [comment]
+1 for extending it to support both strings and objects

**Comment by deontologician** [comment]
+1 for objects as well

**Comment by danielmewes** [comment]
Sounds reasonable. :+1: for:
`object.count()` to count the number of fields and
`string.count()` to count Unicode code points

**Comment by coffeemug** [comment]
:+1:

**Comment by danielmewes** [comment]
Marking as settled as described (`object.count()` and `string.count()`).

**Comment by encryptio** [comment]
In CR 3389
