### ISSUE TITLE
Local variable returned by reference

### ISSUE THREAD

**Issue by srh** [rethinkdb/rethinkdb#4241]
In https://github.com/rethinkdb/rethinkdb/blob/next/src/parsing/utf8.hpp#L80 we can see that the local variable "it" is returned by reference.

Don't ask me why I was even looking at this code... 

Also, `saw_error()` would dereference an uninitialized pointer if you call it too soon, which is just nuts.

**Comment by mlucy** [comment]
It sort of looks like this code was produced by a misunderstanding of how `std::move` should be used, so we should double-check to make sure there isn't similar code elsewhere.

**Comment by mlucy** [comment]
This is in CR 2897 by @danielmewes .  I double-checked all the places we were calling `move` in a return, and we had another copy of this bug in `rdb_protocol/terms/string.cc` which I also fixed.

It looks like the buggy code hasn't been released yet, so moving to the 2.1 milestone.

**Comment by mlucy** [comment]
This is in next.
