### ISSUE TITLE
Figure out how to warn the user about non-transitive connectivity

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#4253]
Prior to #3897 we would show an issue if a server was partially or completely disconnected. We decided to get rid of the server issues and instead only show table issues. We should figure out if and how to warn the user about non-transitive connectivity.

**Comment by coffeemug** [comment]
I think we should move this to 2.1-polish, and discuss it if we have time.

**Comment by danielmewes** [comment]
This was resolved by https://github.com/rethinkdb/rethinkdb/issues/4936 in RethinkDB 2.3.0.
