### ISSUE TITLE
Fix blocks_processed/blocks_total in index_status

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#4259]
Somehow these got removed in `raft` branch.

**Comment by larkost** [comment]
The `polyglot/sindex/status` tests are failing at the moment over this. Once a decision is made we should remove that part of the test if appropriate.

**Comment by danielmewes** [comment]
Assigning @Tryneus . (you might want to check with @VeXocide how he implemented it for the jobs table).

**Comment by VeXocide** [comment]
Would it be an option to add a progress field instead, similar to `rethinkdb.jobs`?

**Comment by danielmewes** [comment]
I think a progress field would be good enough. It will need small modifications to the web UI (@deontologician) and the API docs (@chipotle).

**Comment by deontologician** [comment]
ok, just ping me when this is done

**Comment by Tryneus** [comment]
Fix is up in review 2966.  Everything was working for the most part, except in the time between when an index was created in the metadata and when it hit the btree shards.  Didn't make any changes to the `index_status` format, though if we're going to change the format now would be a good time.

**Comment by danielmewes** [comment]
Let's keep the format as it is for now.

**Comment by Tryneus** [comment]
The fix has been approved and merged to `raft` in commit c2f1010.
