### ISSUE TITLE
Update test-runner README.md

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4270]
The `README.md` file for `test-runner` has gotten a bit out-of-date. I have made a basic pass at fixing the biggest problems and will be putting it up for review momentarily.

**Comment by marshall007** [comment]
It might be worthwhile to add a brief description and the purpose for each of the three test types. Also, I think it's worth mentioning how the `polyglot` tests are dynamically generated from the YAML files. At first glance I thought they were used for documentation generation or something.

**Comment by larkost** [comment]
In the not-too-distant future I will be doing a re-org of the tests (for #3442) so I don't want to put too much effort into explaining groupings that are not going to last long.

**Comment by larkost** [comment]
This has been merged into `next` with 79a58a2 after CR 2916.
