### ISSUE TITLE
orm for koa?

### ISSUE THREAD

**Issue by chovy** [rethinkdb/rethinkdb#4275]
Is there any way to manage/define models for rethinkdb using koajs?

I'm just doing raw queries now but that seems very ugly to me. I used mongoose/mongodb before and it was pretty good.

**Comment by deontologician** [comment]
@chovy have you tried [thinky](https://github.com/neumino/thinky)? It isn't koa specific, but it is a nice Node ORM.

**Comment by chovy** [comment]
I just found thinky, giving it a look through. I'm curious what features of rethinkdb I would be missing out on that aren't supported in thinky.

**Comment by deontologician** [comment]
Thinky proxies all query options from the underlying rethinkdb driver, so anything you can do in the driver you can do with Thinky. It's well maintained and is up to date with rethinkdb 2.0

**Comment by chovy** [comment]
Awesome.

**Comment by tundrax** [comment]
Besides object oriented benefits, big reason for using koa-compatible ORM with rethinkdb were pre/post filters. But soon it turned out, that using plain JS object as "model" and generator/iterators as filter chains (just like koa middlewares) was more comfortable.

**Comment by chovy** [comment]
Do you have an example?

**Comment by tundrax** [comment]
Something like this:

```es6
var co = require('co');

function *noop() {}

// taken from koa-compose
function compose(filters){
  return function *(next){
    if (!next) next = noop();

    var i = filters.length;

    while (i--) {
      next = filters[i].call(this, next);
    }

    yield *next;
  }
}

// you can create any group of filters,
// not just limit to rethinkdb api
var filters = [

  function *(next) {
    console.log(this); // see this is 'article' passed below
    console.log('pre-1');
    yield next;
    console.log('post-1');
  },

  function *(next) {
    console.log('pre-2');
    yield next;
    console.log('post-2');
  },

  function *(next) {
    console.log('pre-3');
    yield next;
    console.log('post-3');
  }
];

// assume this is your 'article'
var article = {
  title: 'filters with genertors'
}

var it = co.wrap(compose(filters));
it.call(article);
```
https://github.com/tundrax/filter-generator

**Comment by tundrax** [comment]
@chovy so the actual rethinkdb api call could be the last generator in the filters array.

```es6
var r = require('rethinkdb');
// ...
var filters = [
// ...
  function *(next) {
    r.table('articles').insert(this).run(conn).then(function () {
      yield next;
    });
  }
]
```
