### ISSUE TITLE
Short unique IDs

### ISSUE THREAD

**Issue by xpepermint** [rethinkdb/rethinkdb#4276]
Hey. I just wanted to ask you if this https://github.com/dylang/shortid/issues/36 would really generate a unique IDs in clustered environment? If not, is there an alternative solution? Thanks!

**Comment by mlucy** [comment]
It looks like they're adding `process.env.NODE_UNIQUE_ID` to their generated IDs, so as long as that's different on all your nodes you should be fine.  We offer our own UUID generator `r.uuid()` as well if you'd prefer to use that: http://rethinkdb.com/api/javascript/uuid/ .

Closing this issue, but feel free to ask more questions here.

**Comment by xpepermint** [comment]
@mlucy Thanks!
