### ISSUE TITLE
Accommodate new replica states from raft in Webui

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#4284]
Another change from #4196 is that there are new states for replicas.

New state: `waiting_for_quorum`

Renamed states:
* `backfilling_data` -> `backfilling`
* `looking_for_primary_replica` -> `waiting_for_primary_replica`

@timmaxw in #4196 you mention `disconnected` "can never occur in conjunction with any other state". Does that mean it can't show up in the `primary_replicas` array, or just that it doesn't have an ordering with the other states?

**Comment by deontologician** [comment]
Fixed typo in the title

**Comment by timmaxw** [comment]
I meant that it's never possible for a single server to be `disconnected` with respect to one subshard but not `disconnected` with respect to some other subshard.

**Comment by deontologician** [comment]
ok, thanks that makes sense

**Comment by deontologician** [comment]
I need to double check this, it may already be fixed

**Comment by deontologician** [comment]
This has already been fixed as part of other issues
