### ISSUE TITLE
raft branch: changefeeds are not disconnected after shard changes

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4286]
The `changefeeds.change_master` test is currently failing on the `raft` branch as the `changefeeds` that are connected to shads as the shards are reconfigured are not disconnected.

I have tested with a strategically placed `time.sleep(2)` to confirm that this is not #4265 tricking us into firing before the `reconfigure` starts.

**Comment by timmaxw** [comment]
In CR 2959.

**Comment by timmaxw** [comment]
Merged in 0fc878a8e7e3cf60d04313d3d67947dfcacef92e.
