### ISSUE TITLE
Handle raft issue changes in WebUI

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#4288]
Following from #4182 (and maybe something else?), the webui needs to be updated to handle new raft issues, and remove some issues which can't happen any more.

Issues removed: `table_needs_primary`, `data_lost`, `write_acks`, `server_ghost`, `server_disconnected`
Issues added: `table_availability`

**Comment by timmaxw** [comment]
`server_ghost` and `server_disconnected` are removed in CR 2912, which hasn't been merged yet. But we might put them back following discussion of #4253. I can't think of any other new issue types off the top of my head.

**Comment by deontologician** [comment]
Ok, updated the issue to reflect that.

**Comment by deontologician** [comment]
Fix is up in CR 2976 by @AtnNn
