### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [rethinkdb/rethinkdb#4298]
The function "[crash](https://github.com/rethinkdb/rethinkdb/blob/15eb5db9689e810c5484ed72ebd9f73b7cc43d1a/src/errors.hpp#L95 "Error reporting")" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function "[generic_crash_handler](https://github.com/rethinkdb/rethinkdb/blob/27180d45218c71f280493f7f1bf4f80c1b5acf96/src/errors.cc#L100 "Reconsider signal handling implementation.")".

**Comment by AtnNn** [comment]
Thanks for investigating and suggesting possible improvements. However your suggestion doesn't apply in this case:

* `crash` is a macro, not a function. Any signal handler could safely call it if it was reentrant and thread-safe.
* The linux man page lists a lot more async-signal-safe functions than the CERT style guide: http://man7.org/linux/man-pages/man7/signal.7.html
* `crash` never returns, it should be safe to call some non-reentrant functions.

**Comment by elfring** [comment]
Will the crash functionality be executed within the context of a signal handler?

Would you like to improve the portability of your software a bit more here?

**Comment by AtnNn** [comment]
@elfring How would you improving the code in this situation?

**Comment by elfring** [comment]
Would you like to consider other software design options?
* [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "wait for queued signals")
* [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html "Use case description by Daniel J. Bernstein")
* [Signal-safe locks](http://locklessinc.com/articles/signalsafe_locks/ "lock-free algorithms")

**Comment by AtnNn** [comment]
@elfring None of those can handle SIGSEGV.

**Comment by elfring** [comment]
How do you come to such a conclusion?

**Comment by AtnNn** [comment]
[signal(7)](http://man7.org/linux/man-pages/man7/signal.7.html) says:
> certain signals, such as SIGSEGV and SIGFPE, generated as a consequence of executing a specific machine-language instruction are thread directed

[sigprocmask(2)](http://man7.org/linux/man-pages/man2/sigprocmask.2.html) says:
> If SIGBUS, SIGFPE, SIGILL, or SIGSEGV are generated while they are blocked, the result is undefined

I put together a reading list for signals a few weeks ago that you might be interested in: https://gist.github.com/AtnNn/b91e7c63fba215091f6b

If you are looking for issues to fix or want to contribute to RethinkDB, perhaps you could start with one of the issues tagged *good_for_contributors* https://github.com/rethinkdb/rethinkdb/issues?q=is:open+is:issue+label:good_for_contributors

**Comment by elfring** [comment]
Thanks for your clarification.
