### ISSUE TITLE
Save tags from js

### ISSUE THREAD

**Issue by flashfoxter** [rethinkdb/rethinkdb#4301]
when i save array to json properties (example: {name: "test", tags:"["tag1","tag2"]"})
 - its automatically adds quotes to array "[]"

And if i try to get query with:
r.table('media').getAll('tag1', {index: 'tags'}) - result 0

But, if i remove quotes from array with data explorer (example: {name: "test", tags:["tag1","tag2"]})
its works good - resut 1

Error with get query with quotes, or need save array in props without quotes.

Sorry for bad english.

**Comment by danielmewes** [comment]
Looks like you've resolved this already, but in general you must not use quotes for storing arrays. Only for string values.
