### ISSUE TITLE
Visually indicate nonvoting replicas in webui

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#4303]
Once #3891 is merged, it'll be possible to show which replicas are non-voting. It should be shown somehow in the web ui

**Comment by danielmewes** [comment]
I think this is fairly important since I imagine things might become confusing if using non-voting replicas but not seeing that info in the web UI.
Moving to 2.1 for now, though we can push it back if we end up not having enough time for this.

**Comment by deontologician** [comment]
in CR 2984 by @Tryneus (I am on the spread-the-webui-reviews-around kick again)
