### ISSUE TITLE
Meteor & RethinkDB

### ISSUE THREAD

**Issue by babakness** [rethinkdb/rethinkdb#4307]
I recently saw a talk by Slava of MDG (Meteor) and his points on latency compensation. It'd be great to have the meta data available to enable latency compensation (Optimistic UI). I don't completely appreciate the depths of the problem but I figured I'd voice my vote for enabling this functionality.

All the best.

**Comment by danielmewes** [comment]
Hi @babakness , are there slides or a video of Slava's talk available somewhere?
I'm not familiar with what latency compensation entails with respect to a database.

**Comment by mglukhovsky** [comment]
@danielmewes: check out the talk here: https://www.youtube.com/watch?v=xQJ-QGYrpRc&feature=youtu.be&t=23m27

**Comment by danielmewes** [comment]
Ah is this about providing version metadata with changes?

**Comment by danielmewes** [comment]
Thanks for opening the issue @babakness . I'll check back with Slava to see what he needs exactly.

**Comment by danielmewes** [comment]
@Slava Would you mind clarifying again which metadata you need? I think you mentioned a need for an automatic document "version" field. Was that it, or is there something else?

**Comment by Slava** [comment]
@danielmewes 

I think there are a couple of things needed for a quality integration with Meteor's optimistic UI system (or for that matter, any correct ad-hoc system implementing the same feature):

- Either version numbers or some-kind of unique identifiers for the changes.
- Make it possible to figure out when a write to DB appears in the change-feeds:
  * One of the ways to achieve this: make unique identifiers for the changes ordered, also make every query to return the identifier for the write, so the clients can look for it (or any changes after it, in case of `squash: 1`) in the change-feeds

**Comment by dkran** [comment]
Thanks for addressing this so proactively in many places. I just want to voice a vote as being 100% for the meteor-rethink integration :)

**Comment by TwinTales** [comment]
Also very much looking forward to Meteor & RethinkDB integration :+1:

**Comment by neumino** [comment]
Doesn't having a field that get populated with a random id by the client solve the problem for tracking changes in the feed?

**Comment by Slava** [comment]
@neumino no.

Let me clarify. If I understand you correctly, you propose clients set a special field (like '_change') to a random identifier on every write? Here is a list of reasons why it doesn't satisfy the requirements outlined in my comment above:

- Having a special field set randomly doesn't make it ordered. Sure, you can set it to something like `r.now()` to get a server-generated date, this still doesn't reserve the ordering on operations happening at the same second.
- Unclear how to track this special field in removed documents. We are still interested in the id of a removal, if you don't remove the document, you would need to somehow encode this.
- [?] possible race-conditions if the field is updated too naively: as far as I understand, invoking two operations in one ReQL query doesn't guarantee atomicity. So a query like `r.get(id).update(...) AND r.get(id).update(...update the special field...)` is risking to be racy.
- client code inconvenience: maintaining a special field in the client-code is inconvenient and error-prone. Also requires every query to RethinkDB to be accompanied with an extra field set.

I thought of multiple ways of implementing such functionality in application layer and couldn't come up with any ideas that would work w/o races or w/o hitting limitations of change-feeds.

**Comment by danielmewes** [comment]
Superseded by https://github.com/rethinkdb/rethinkdb/issues/4629 which has a discussion of specific solutions to this.
