### ISSUE TITLE
Should default cache size by explicitly (or by default) set to auto? 

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/rethinkdb#4310]
https://github.com/Homebrew/homebrew/pull/39450#issuecomment-102564245

I would guess that without setting the `--cache-size` flag  the minimum cache-size of 100MB is set, which on my MBA was less performant and had log messages suggesting to increase the size. Compared to better performance when setting the cache-size to auto which set it at 1GB. 

I ask whether this should be done in the default brew formula?

**Comment by AtnNn** [comment]
As documented in the [memory-usage](http://rethinkdb.com/docs/memory-usage/) page, the `auto` setting is already be the default.

The *auto* cache size depends on the amount of free memory, not the total memory. Perhaps you had other memory hungry apps running intermittently when you tested the different options?

**Comment by dalanmiller** [comment]
That must have been it, some more thorough scouring of my logs found this
to be true. Thank you sir :+1:
