### ISSUE TITLE
Fuzzer for Raft core logic

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#4322]
The current `ClusteringRaft` unit tests check a few specific scenarios, but that's not enough. We should add a unit test that's a general-purpose fuzzer that does random operations on a `dummy_raft_cluster_t`.

**Comment by Tryneus** [comment]
Working on this.

**Comment by Tryneus** [comment]
This is up in review 3009, but the test is currently failing.  It looks like there is some situation that the raft cluster isn't recovering after fuzzing even though it has a quorum, although there is a chance the test is incorrect.

**Comment by Tryneus** [comment]
The fuzzer has been approved and merged to `next` as of commit 2bc7d0f.  Will open a new issue for the failing test.
