### ISSUE TITLE
Data Explorer query editor does completion for many fewer things than it used to

### ISSUE THREAD

**Issue by ccheever** [rethinkdb/rethinkdb#4326]
Starting with 2.0.2, most things are not competable in the composer. The UI thinks .table() should only be .do() for example, which doesn't make much sense.

**Comment by danielmewes** [comment]
Hi @ccheever, thanks for reporting this. We indeed accidentally broke the auto completion functionality in 2.0.2. We'll ship another point release soon which is going to fix this.
Sorry for the inconvenience.

Duplicate of https://github.com/rethinkdb/rethinkdb/issues/4261
