### ISSUE TITLE
Shards are not properly merged when down-sharding

### ISSUE THREAD

**Issue by VeXocide** [rethinkdb/rethinkdb#4328]
When down-sharding, reconfiguring from ten to two shards for example, the shards are not properly merged which is demonstrated by `test/interface/shard_balancing.py` hanging.

This seems to be a consequence of `src/clustering/table_contract/coordinator.cc:496` which merges identical contracts, but the different `branch_id_t`'s prevent the otherwise equal contracts from being merged here.

**Comment by danielmewes** [comment]
A fix for this is in CR 2963 by @timmaxw

**Comment by danielmewes** [comment]
Fixed in `raft` as of 0bfc5aa317705d2f19fb00a691f2a7cfd30ddc4f
