### ISSUE TITLE
raft branch: changefeeds not closed when table reconfigured

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4329]
As is demonstrated in the `./test/run changefeeds.change_master` test, changefeeds are not being closed when the underlying table is reconfigured. While this is the behavior that I would eventually want (#3549), I don't believe that this is correct/safe behavior. I tried putting a `time.sleep()` in at the  appropriate point to make sure that this is not a timing issue, and it does not appear to be.

**Comment by timmaxw** [comment]
Is this a duplicate of https://github.com/rethinkdb/rethinkdb/issues/4286?

**Comment by larkost** [comment]
Yes, I remembered filing that one, and even looked for it, but for some reason did not find it so assumed I just talked about creating it.
