### ISSUE TITLE
Standardize raft-era terminology for primary replicas

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#4330]
Specifically, we need to distinguish between primary replicas that were configured by the user (in table_config) and those that were elected by raft (unless they're the same).

Currently, I'm using this terminology:

   | primary in table_config | primary in table_status | what it's called in webui
--- | ----------------------- | ----------------------- | -------------------------
1  | true                    | true                    | Primary replica
2  | true                    | false                   | Configured primary replica
3  | false                   | true                    | Elected primary replica
4  | false                   | false                   | Secondary replica

@danielmewes has suggested "Acting primary replica" for row 3.
@timmaxw suggested "Future primary replica" for 2 and "Temporary primary replica" for 3 in #engineering 

ping @coffeemug @mglukhovsky, but whoever wants to comment feel free. I don't have a strong opinion about it, other than it should be something we're happy with since it'll show up several times in the webui

**Comment by coffeemug** [comment]
I think the current terminology is a bit confusing because I can't quite tell from it what's going on. I presume "configured" means the user configured a server to be a primary replica but the election process hasn't started yet or is in progress, is that right? And "elected primary replica" is when the election process has ended but the replica hasn't transitioned into primary yet (but is in the process of doing so)?

(I need to understand what's happening a bit better before I can propose better terms)

**Comment by deontologician** [comment]
This can be a permanent state. if the server the user specifies as primary never reconnects to the cluster, the primary elected by raft will stay the primary indefinitely

**Comment by deontologician** [comment]
A key ppoint is that when raft elects a server as the primary, it doesn't ever change the table config

**Comment by coffeemug** [comment]
Ah, got it. In that case, what's the difference between "configured primary replica" and "primary replica"?

**Comment by deontologician** [comment]
Just that in 99% of cases, the primary you configured is the current primary, so there's no reason to make it more confusing (i.e. we only need to distinguish when the primary situation is complicated due to failover).

**Comment by deontologician** [comment]
To clarify, states 2 and 3 will only occur during failover

**Comment by larkost** [comment]
I think that is pretty clear, but agree with @danielmewes's suggestion to change 3 to "Acting primary replica".

**Comment by coffeemug** [comment]
Ah I see, that makes sense. Could we add a column/icon to show if the server is disconnected? That would make it much more clear why a replica might be configured as primary, but isn't one.

**Comment by deontologician** [comment]
I am adding a status icon to the table/server page. I definitely think that will help, but hopefully we can get a terminology that makes sense in isolation as well, in case there are places where it's inconvenient to show the status

**Comment by danielmewes** [comment]
I think I'd slightly prefer "Goal primary replica" over "Configured primary replica".

I like either "Acting primary replica" or "Temporary primary replica" for case 3, with a slight preference for "Temporary primary replica".

**Comment by deontologician** [comment]
I think I like "Acting primary replica" better since it's not two "-ary" words in a row

**Comment by deontologician** [comment]
Went with "Acting/Goal"
