### ISSUE TITLE
"ordered union" term to merge ordered streams

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4338]
There are situations where you have multiple streams that are all sorted according to the same order function, and you want to efficiently merge them into a single stream that's still sorted accordingly.

This came up in https://github.com/rethinkdb/rethinkdb/issues/4325

Right now `r.union` doesn't make any guarantees about the ordering of its result. So the only work around is `r.union(orderedStream1, orderedStream2).orderBy(...)` which is inefficient because the fact that the individual substreams are already sorted isn't utilized.

The proposal is to have something like an "ordered union" that takes an attribute or a function to sort by, and merges the substreams in the correct order, assuming that each of them has already been ordered by the same attribute.

I haven't thought about a concrete interface yet.

**Comment by marshall007** [comment]
This would be really useful! I think it would be slightly annoying if the sorting function had to be specified on each stream and then again in the "ordered union" term. Instead of a new term, perhaps we could just have a boolean optarg to `r.union` for whether or not it should attempt to preserve sorting if all its arguments are ordered streams.

**Comment by deontologician** [comment]
Do we keep track of whether a stream is ordered currently?

**Comment by danielmewes** [comment]
I believe for lazy streams we do, but not for arrays. (@mlucy?)
If we have information about the ordering we could probably use that for the ordered union and avoid having to specify it again (also we could verify then that the same ordering is used on each substream).

**Comment by mlucy** [comment]
> I believe for lazy streams we do, but not for arrays.

That's right, although I think there might be some terms that drop that information.
