### ISSUE TITLE
raft branch: shard not failing over when server is killed

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4339]
The `./test/run -v changefeeds.basic` test is showing a case where failover is not happening when a primary goes down. The failure is in the `test_primary_falure` subtest and the steps that it goes through:

1. spin up 3 server instances, joined as a cluster
2. create a single table with 3 replicas, filled with a 10 records of sample data (like: `{'id':1}`)
3. figure out the primary for the first/single shard and get the id of a record in that range
4. create a table changefeed using a replica other than the primary as the server
5. confirm that the changefeed works (update the record, read the change out)
6. kill the primary server
7. try step 5 again, expecting an error when we change from the feed

But instead we are getting a failure in step 7 when we try to update the record. Specifically the error is:
```
RqlRuntimeError: Cannot perform write: primary replica for shard ["", +inf) not available in:
r.db('test').table('basic_py2_7_6').get(1).update(r.expr({'update': 1}))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by timmaxw** [comment]
Fixed in 939ee74db7ea197e93535ab7ab238d99e2e72388.
