### ISSUE TITLE
Preparing RethinkDB 2.0.3

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4345]
I created a 2.0.3 milestone with issues that should go into 2.0.3.

All of the open issues already have patches either in code review or at least in a commit (https://github.com/rethinkdb/rethinkdb/issues/4264).

Other remaining items:
* Write release notes
* Bump driver version of the JS driver
* Tag, build etc.

**Comment by danielmewes** [comment]
Is there anything important I forgot that should also go into this release?

(also mentioning @AtnNn )

**Comment by deontologician** [comment]
There are a couple of open CRs @AtnNn is reviewing that should probably go out with this

**Comment by deontologician** [comment]
OK, nevermind, I just noticed you already moved them into the milestone
