### ISSUE TITLE
Implement CT_ASSERT using static_assert

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#4346]
C++11's `static_assert` gives much nicer compile errors.

**Comment by mlucy** [comment]
+1, it would be even nicer if we just dropped `CT_ASSERT` entirely.

**Comment by AtnNn** [comment]
I accidentally fixed this along with #4264, as

```
#define CT_ASSERT(e) static_assert(e, #e)
```

**Comment by danielmewes** [comment]
Oh no, these accidents... :-)
