### ISSUE TITLE
JavaScript driver overwrites 'db' optarg passed to 'run' if connection default is set

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4347]
Both the Ruby and Python drivers use a 'db' optarg passed into 'run' over the default DB set on the connection using 'use'. However the JavaScript driver overwrites the 'db' optarg if there is a connection default without checking if it had already been set.

I think we should change the JS driver to make this consistent and behave more like expected.

**Comment by marshall007** [comment]
To clarify, passing `.run({ db: '...' })` should **not** set the default `db` for the connection even if it's not already set, correct?

**Comment by danielmewes** [comment]
Closed by @marshall007 's pull request https://github.com/rethinkdb/rethinkdb/pull/4349 .

Also yes, the optarg passed to `run` should not change the default `db` state of the connection (if that's what you meant).

**Comment by marshall007** [comment]
Yep, that's what I meant. Thanks!
