### ISSUE TITLE
Docs mistake

### ISSUE THREAD

**Issue by alehano** [rethinkdb/rethinkdb#4350]
On the page 
http://www.rethinkdb.com/api/python/insert/ 
(and http://www.rethinkdb.com/api/ruby/insert/)
there is a mistake.

Example: Insert a document into the table users, replacing the document if the document already exists.
```
r.table("users").insert(
    {"id": "william", "email": "william@rethinkdb.com"},
    conflict="error"
).run(conn)
```

To replace should be conflict="replace"

**Comment by danielmewes** [comment]
Thanks for reporting this. I'm going to move your issue over to our separate documentation issue tracker...

**Comment by danielmewes** [comment]
Now tracked in https://github.com/rethinkdb/docs/issues/786
