### ISSUE TITLE
audit `test/scenarios` for raft

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4352]
After converting `failover_to_secondary.py` in #4340 I think that the whole `test/scenarios` folder will need to be audited, and in many cases revamped. Rather than creating separate issues for each I will do them under this issue. So the checklist (email users: this will be updated):

 - [x] change_primary.py
 - [x] failover_to_secondary.py - separate issue: #4340
 - [x] kill_access_point.py
 - [x] kill_secondary.py
 - [x] more_or_less_secondaries.py
 - [x] ~~proxy_cluster.py~~ (removed, static_cluster handles this with an option)
 - [x] rebalance.py
 - [x] restart.py
 - [x] static_cluster.py
 - [x] transfer.py

**Comment by larkost** [comment]
The fix for `kill_secondary.py` is in change review with CR 2960.

**Comment by danielmewes** [comment]
The `kill_secondary.py` fixes are merged into `raft` as of  e40213b7afa826da66fbbebac57958f17f64804

**Comment by danielmewes** [comment]
`transfer.py` also needs fixes. Currently working on that.

**Comment by danielmewes** [comment]
`transfer.py` adaptations are in CR 2969

**Comment by danielmewes** [comment]
The `transfer.py` fix is in `raft` https://github.com/rethinkdb/rethinkdb/commit/b1280546746f05bbf10fd570c71f8cee81023d35

**Comment by larkost** [comment]
`change_primary.py` has been changed in `next` with 46ee97f0 after CR 3155. The test had not been accurately reporting when the workloads failed, but that has not turned up any new actual failures.

**Comment by larkost** [comment]
`kill_acces_point.py` is up for review in CR 3160 from branch `larkost/4352-audit-kill_access_point`

**Comment by larkost** [comment]
`static_cluster.py` and `proxy_cluster.py` (deleted in favor of `static_cluster.py` with an option) are up for review in CR 3168 from branch `larkost/4352-audit-static_cluster`

**Comment by larkost** [comment]
Merged changes for `kill_acces_point.py`, `static_cluster.py`, and `proxy_cluster.py` into `next` with 74cc1d9d

**Comment by larkost** [comment]
`rebalance.py` review is up in CR 3174 off branch `larkost/4352-audit-rebalance.py`

**Comment by larkost** [comment]
the modified `rebalance.py` is in `next` with 393f4e9

**Comment by larkost** [comment]
The review for the last two files is up as CR 3224 from branch larkost/4352-audit-rebalance.py

**Comment by larkost** [comment]
The review is back, and the last two have been merged into `next` with 7431b7e4
