### ISSUE TITLE
Feature Request: r.mq

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#4354]
We have r.http and changefeeds for delegating jobs to microservices, but it would be amazing if RethinkDB supported something like the Scalability Protocols(SP) of 0MQ/nanomsg/mangos:

```
r.mq("PUSH", "message");
r.mq("REQ", "message"); // would return the reply
r.mq("SURVEY", "message"); // would return answers array from respondents
```

Any client SP-compatible(so far I know that mangos can interact with nanomsg) could receive and reply messages

**Comment by danielmewes** [comment]
I can see that being useful.
@thelinuxlich do you have a good overview of how commonly nanomsg is used?

Putting into backlog for now, but we'll come back to it when we are done with some of the more pressing features and improvements.

**Comment by thelinuxlich** [comment]
There are many people using but it's a shy community compared to 0MQ. Although there are benefits to nanomsg as it is a specification, it's trying to be sane, simple and modular.

I hope that @gdamore, the actual mantainer, can give us a few words about this proposal :)

**Comment by deontologician** [comment]
This might be a better fit for an adapter of some kind, vs. being baked into the db itself

**Comment by gdamore** [comment]
Agreed.  I don't have any experience with thinkDB, but unless you want to use nanomsg/SP as a transport for your own application traffic, it would seem instead that you could (or someone could) offer up an interface (say query over REQ/REP or perhaps subscribe to values in the DB over PUB/SUB) using the nanomsg protocols.  This has some advantages over HTTP/REST, but I'm not convinced that they are compelling enough in the general case; definitely probably a lower priority item for this project unless there are some specific consumers needing it.
