### ISSUE TITLE
question: max length of string values ?

### ISSUE THREAD

**Issue by silver83** [rethinkdb/rethinkdb#4360]
Hi guys I couldn't find an answer for this in http://rethinkdb.com/docs/data-types/ or http://rethinkdb.com/limitations/

Is there a known limit for string value sizes ? other data types as well could be useful for future reference...

**Comment by jsarenik** [comment]
Does following answer your queston?

http://rethinkdb.com/limitations/

**Comment by ha1331** [comment]
@jsarenik  silver83 listed that same link on his question, so I suspect the answer would be no.

**Comment by jsarenik** [comment]
OK, sorry. I tried to insert into RethinkDB a record with `name` (which I suppose is kind of `string`) 1024*8 bytes long and it works with no problem.

**Comment by jsarenik** [comment]
And even longer works:

```
var a = (new Array(10*1024*1024)).join("x");
r.table('tv_shows').insert([{ name: a, episodes: 178 }])
```

But sorry, I do not have a straight answer to your question yet.

**Comment by ha1331** [comment]
I think this "While there is no hard limit on the size of a single document, there is a recommended limit of 16MB for memory performance reasons." is the best lead. RethinkDB stores documents to the disk in chunks of 512B, so it might be possible there is no set max length for strings. I base this only on the fact that no such max length has been defined/documented.

**Comment by danielmewes** [comment]
Hi Ján,

as Henrik suggested there is indeed no limit on the length of a string,
apart from the size of memory on your server.

Note that there is however a limit of 64 MB on the size of a single query,
so you cannot actually transfer a string larger than that to the server in
one piece. Retrieving strings larger than 64 MB should work fine though.

Note that large documents above 16 MB haven't been tested very thoroughly
and while there shouldn't be any crashes, there might be performance and/or
resource consumption issues.

Hope this helps.

Best,
  Daniel

**Comment by jsarenik** [comment]
@danielmewes Thanks much! @silver83 ^^^
