### ISSUE TITLE
Feature request: ES2015(ES6) in ReQL.

### ISSUE THREAD

**Issue by xbenjii** [rethinkdb/rethinkdb#4361]
Would it be possible to use ES2015 in the web administration console? Namely arrow functions.

Essentially turning this:
```JavaScript
r.table("posts")
    .map(function(doc) {
        return 1
    }).reduce(function(left, right) {
        return left.add(right)
    });
```
Into this:
``` JavaScript
r.table("posts")
    .map(doc => 1)
    .reduce((left, right) => left.add(right));
```

**Comment by joaojeronimo** [comment]
That's a feature that your javascript VM must have, not RethinkDB. If you're running iojs or node with --harmony (I tested the following code on the latest stable with --harmony) you already get working arrow functions :)

```js
var r = require('rethinkdb');
var conn = undefined;

r.connect(onConnect);
function onConnect (err, connection) {
    if (err) {
        throw new Error(err);
    }
    conn = connection;
    r.table('test').insert({}).run(conn, onInsert);
}

function onInsert (err) {
    if (err) {
        throw new Error(err);
    }

    // ARROW FUNCTION YAY
    r.table('test').filter(doc => true).run(conn, onFilter);
}

function onFilter (err, cursor) {
    if (err) {
        throw new Error(err);
    }
    cursor.toArray(onResults);
}

function onResults(err, results) {
    if (err) {
        throw new Error(err);
    }

    console.log(results);
    conn.close();
}
```

**Comment by xbenjii** [comment]
@joaojeronimo Whups, sorry. Should've been more specific. I meant for the web admin console. I've updated the OP.

**Comment by joaojeronimo** [comment]
Ohh got it. Well, same theory. I was able to run `r.db('test').table('test').filter(doc => true)` from the data explorer in the latest Firefox, although in Chrome I can't do it even after enabling harmony in chrome://flags/#enable-javascript-harmony, guess they don't have arrow functions yet ?

**Comment by xbenjii** [comment]
Ah okay. For some reason I thought it was lower level than the browser. Thanks for the help.

**Comment by joaojeronimo** [comment]
Only if it was for `r.js` calls, which is pretty much a valid feature request worth opening an issue ;)
