### ISSUE TITLE
Remove server status from the server listing page

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#4367]
Since disconnected servers won't show up in the server listing page, there's no reason to show a status

![selection_039](https://cloud.githubusercontent.com/assets/1366/8072829/e03e67cc-0ed0-11e5-8a56-aef699d09d33.png)

@timmaxw @danielmewes would you say removing status is the correct behavior here?

**Comment by timmaxw** [comment]
Sounds right to me.

**Comment by danielmewes** [comment]
Do disconnected servers actually disappear from `server_status` if they are part of a table? I thought those were still there.

**Comment by deontologician** [comment]
Yeah, they disappear from `server_config` and `server_status`

**Comment by danielmewes** [comment]
Oh ok I misremembered that then.
Yeah we should remove the status.

**Comment by deontologician** [comment]
in CR 3011
