### ISSUE TITLE
table_status should return something more reasonable if a table is completely unavailable

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#4374]
Right now it returns a document with `error: ...`. Instead it should return the regular status fields and such, which should all be set to `false`.

**Comment by danielmewes** [comment]
:+1:

**Comment by timmaxw** [comment]
In CR 3006 and https://github.com/rethinkdb/rethinkdb/tree/tim/overhaul-status-and-wait.

**Comment by timmaxw** [comment]
Fixed in eb2ca72467b8543cf196ccfb4c7f2c2cc56b9415.
