### ISSUE TITLE
Rework table_acks_durability.py test

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4381]
It currently tries to declare servers dead and doesn't take auto-failover into account. I suspect that we have to rewrite larger parts of it.

(mentioning @larkost)

**Comment by timmaxw** [comment]
In CR 3011. The test turned out to be obsolete; the `table_readiness.py` test was testing almost all of the same things. So I removed most of it and moved the parts that were still relevant into `table_config.py`.

**Comment by timmaxw** [comment]
Merged in 3f9ce0c2816464b152b927783bc785f3ae8179e7.
