### ISSUE TITLE
r.wait without arguments depends on test database existing.

### ISSUE THREAD

**Issue by grandquista** [rethinkdb/rethinkdb#4382]
I am running this query to clean up at the end of a test suite.

```js
r.wait().do( function (wait_res) { return r.db('rethinkdb').table('db_config').delete(); })
```

It returns this error even if a database exists. I replicated this in the data explorer by deleting all databases and then creating a database named `foo`. Both `next` and `2.0.2` have the issue.

```
t: Database `test` does not exist in:
undefined.wait().do(function(var_120) { return r.db("rethinkdb").table("db_config").delete(); })
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

When the default database is left in place the query runs successfully.

**Comment by danielmewes** [comment]
Sorry you ran into this. This is actually just a case of pretty confusing syntax on our end.

`r.wait()` doesn't wait for all tables, but it waits for all tables in the default database. It works analogous to other operations such as `r.tableCreate()` or `r.table()`, all of which use the default database if no `r.db(...)` is prefixed.

So you'll probably need to run `wait()` on the specific database that you're using, or do something like
```js
r.dbList().filter(r.row.ne('rethinkdb')).forEach(r.db(r.row).wait().do(...))
```
to wait (and run your deletion function) on all tables in all databases.

**Comment by danielmewes** [comment]
I suggest that we disallow `r.wait()` without an explicit database, because it's obviously confusing.
Marking as ReQL_proposal and putting into 2.2-polish.

**Comment by grandquista** [comment]
I understand now. I will make the changes to my clean up.

**Comment by deontologician** [comment]
+1 for removing one more place where "test" database is implicitly used

**Comment by VeXocide** [comment]
+1

**Comment by danielmewes** [comment]
Marking settled for disallowing `r.wait` on databases without an explicit database argument.

**Comment by nighelles** [comment]
In review 3430
Implemented in branch nighelles_4382_good.
https://github.com/rethinkdb/rethinkdb/tree/nighelles_4382_good

**Comment by nighelles** [comment]
This is in next.
