### ISSUE TITLE
Emergency read mode to read directly from replica

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4388]
For emergency situations we should add a special read mode which allows extracting a table's data directly from a given server, ignoring shard and replica constraints. This will often allow recovering data under unrecoverable failures of the clustering / metadata logic.

It could even be a command line argument that dumps the content of a given table file into a local JSON file. Something like
`rethinkdb emergency-extract --table <table UUID> --out table.json`

**Comment by timmaxw** [comment]
For ease of implementation, I think this should be a special value of `read_mode`. I suggest `read_mode="_debug_direct"``.

**Comment by danielmewes** [comment]
I actually think the command line argument might be easier.

We just have to open the specified file with a serializer and cache, and spawn a parallel (or concurrent or whatever) traversal on it with a JSON write as the callback.

For a special read mode I think we will have to create a completely new path through the query execution and routing code that does sharding differently, and accesses the server in some direct way, don't we?

Maybe I'm under and/or over-estimating the complexity of these things though.

**Comment by timmaxw** [comment]
For a special read mode we would give the `table_query_client_t` a pointer to the `multi_table_manager_t`. Through that pointer it can easily get direct access to the `multistore_ptr_t`. It could be done in <100 lines of code, I think.

**Comment by timmaxw** [comment]
Another advantage of a special read mode is that it gives access without shutting down the server. This is useful for testing as well.

**Comment by timmaxw** [comment]
To clarify, under my proposal it would always extract from the server that the query was sent to.

**Comment by danielmewes** [comment]
The testing aspect is a good point. I think we should pick whichever option is easier.

If they are similar in difficulty (which I now think they are), the command line option seems to be slightly more low level and able to recover in more cases, since it doesn't require even the table metadata to work. With the read option, we still rely on the server having knowledge of which tables exist. The command line option would work in cases where the metadata is corrupted or missing, or where we trigger some guarantee in some of the clustering or query code that makes the server terminate before the user can even issue the emergency read query.

Because of this I have a slight preference for the command line option, but not a strong one.

**Comment by timmaxw** [comment]
In CR 3014.

**Comment by timmaxw** [comment]
Fixed in e139d144ebd1645b55c06a297c8b1155099570d3.
