### ISSUE TITLE
Think about specifying which browsers we want to support for the webui

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#4398]
Some options for a policy:
1. Pick some minimum versions of major browsers, things may work in other browsers but no guarantees.
   - pros: simple to decide whether to use a feature. Simple to explain the policy to users
   - cons: May be too coarse-grained, d
2. Polyfill and css-prefix where necessary, and avoid features that can't be polyfilled/prefixed
   - pros: some more support than a pure browser version floor
   - cons: this policy has no real hard definition, it's a best-effort kind of thing. Any feature may become a problem and there's nothing to point to to say "We don't intend to support this". So it's hard to explain to users.
3. Specify a minimum "global support" percentage from caniuse.com for features
   - pros: sort-of empirical, provides a better measurement of impact than browser version
   - cons: Some things have a lot of support on caniuse, but are still in experimental phase and may change
4. Rely on jQuery/less and coffeescript for cross-browser compatibility, and don't use browser features that these tools don't handle themselves.
   - pros: takes some of the burden off of us to think about incompatibilities
   - cons: takes some tools out of our toolbox even if they're eminently reasonable
5. "Squeaky wheel gets the grease". This is our default policy at the moment.
   - pros: Doesn't spend time fixing issues no one has complained about yet
   - cons: If the user base ramps up very quickly, we may end up with a large population of of enterprise users locked to older browsers, and have a very large backlog of compatibility issues all at once.

Honestly, I'm guessing we'll go with 5. It might be nice to have a general rule for new features along the lines of 3, so we know we aren't going completely off the rails. I've been roughly going with >90% support on caniuse.com, but it's probably good to have a discussion on it.

ping @mglukhovsky @AtnNn @danielmewes

**Comment by danielmewes** [comment]
Talked with this with @deontologician and we decided that we shouldn't officially support specific browser versions at the moment, because we don't have the resources to actually test for them.

I think going with >90% support on caniuse.com in combination with option 5 is good enough for the moment. In addition we should make sure that at least the latest versions of Chrome, Firefox and Internet Explorer support the features.
Once we have more resources for testing, we will make the supported browser versions more specific.

**Comment by srh** [comment]
Going with option 5 :)
