### ISSUE TITLE
Website makes it seem as if new primaries are automatically elected after permanently removing a server

### ISSUE THREAD

**Issue by bigtree3131** [rethinkdb/rethinkdb#4406]
From the website:  If the server is permanently removed, it is absolved of all responsibilities, and one of the secondary replicas is automatically elected to act as a new primary

**Comment by timmaxw** [comment]
Oops. Thanks for the report. The website is describing the pre-1.16 behavior.

Problems with the website are tracked in the RethinkDB docs repository, not here. I've created an issue over there: https://github.com/rethinkdb/docs/issues/792
