### ISSUE TITLE
Add a package to protobuf definition

### ISSUE THREAD

**Issue by danielcompton** [rethinkdb/rethinkdb#4411]
I looked for previous issues about this but couldn't see anything. Sorry if it's a duplicate. The current QL2.proto file doesn't specify a package.

This is generally good to have to avoid naming collisions with other protocol buffers in general usage in all languages. It's also essential for Java, as all Classes need to have a (Java) package to be used. See https://developers.google.com/protocol-buffers/docs/proto#packages for more details.

What are your thoughts about adding this? I'm not 100% sure what the downstream effect of this would be. 

Relates to apa512/rethinkdb-protobuf#1

**Comment by mlucy** [comment]
I don't know much about Java, but this seems reasonable.  @deontologician, any thoughts?

**Comment by danielcompton** [comment]
It will change the generated Class that people get compiling it in Java, and probably have similar effects in C++ and Python. It might pay to put this in a 2.1 rather than a patch release.

**Comment by deontologician** [comment]
This is a hygiene thing and we're dropping support for protobufs soon. I don't think we should worry about it.

**Comment by deontologician** [comment]
The existing Java drivers just copy the protobuf file and add the package declaration, so we won't gain any immediate benefit

**Comment by danielmewes** [comment]
Thanks for bringing the question up for discussion @danielcompton .

I don't think we will remove protocol buffer definitions for generating protocol constants really soon.
In the longer run it should make sense for us to replace the proto file by for example a JSON file that contains all of the protocol constants though.

I think we should not add the package at this point. While it might be cleaner, it will also affect a lot of third party driver developers who might then have to work around it or adapt their code.
