### ISSUE TITLE
Filter with groupBy - AttributeError: 'Filter' object has no attribute 'group_by' -  [Python]

### ISSUE THREAD

**Issue by aj07mm** [rethinkdb/rethinkdb#4414]
Hello guys!
im having trouble with this query:
```
r.table(collection).filter(_filter).group_by(conditions.get('group_by')).count().run(self.rdb_conn)
```

i can't seem to find a way to group_by the filtered results, it throws this:

```
AttributeError: 'Filter' object has no attribute 'group_by'
```

PS:
nice job with the rethinkdb, thanks for the such a great database

**Comment by aj07mm** [comment]
forget it, found out: its "group" not "group_by".

**Comment by danielmewes** [comment]
Happy you found it. Let us know if you run into any other issues.
