### ISSUE TITLE
creating a table causes a temporary issue

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#4417]
When running `createTable` or `reconfigure` in the data explorer, an issue sometimes pops up for a second or two.

**Comment by danielmewes** [comment]
I'm moving this to polish. I think it's ok to ship with this.
We should think about how we can solve it in the long term though. Maybe we generally shouldn't generate issues for tables that are let's say less than 5 seconds old?

**Comment by AtnNn** [comment]
I think it's important to fix because it pops up a big red issue in the web ui, but doesn't give you any time to read it or any indication why. It is especially confusing when the table is being created or reconfigured by another user or by a script.

**Comment by mlucy** [comment]
That does sound like it would freak people out.

**Comment by timmaxw** [comment]
Maybe we should only report an issue for a table if the table is not fully available *and* at least one server for the table is disconnected?

**Comment by danielmewes** [comment]
Hmm that might work. My concern is that if something goes wrong in our clustering logic and things get stuck making a table unavailable, we won't get an issue.
Thinking about it, I think that's acceptable though. Let's do what @timmaxw said.

**Comment by AtnNn** [comment]
It might also help to have a notification in the web UI for automatically resolves issues, something like

> The issue "Table *test.foo* not available" was resolved. [`Dismiss`]
> [`Dismiss all`]

**Comment by deontologician** [comment]
@AtnNn that should be handled by #4375

**Comment by timmaxw** [comment]
In CR 3006 and https://github.com/rethinkdb/rethinkdb/tree/tim/overhaul-status-and-wait.

**Comment by timmaxw** [comment]
Fixed in eb2ca72467b8543cf196ccfb4c7f2c2cc56b9415.
