### ISSUE TITLE
Ruby driver: cursor.next()  - undefined method next

### ISSUE THREAD

**Issue by pedram-tiv** [rethinkdb/rethinkdb#4420]
Ruby driver: cursor.next() 
http://rethinkdb.com/api/ruby/next/

cursor = r.table('[table_name]').run(conn)
cursor.next()

error: undefined method `next' for #<RethinkDB::Cursor:0x007ffadf01b788> (NoMethodError)

rethinkdb 2.0.3 (CLANG 4.2 (clang-425.0.28))
Running on Darwin 14.3.0 x86_64

thanks.

**Comment by Tryneus** [comment]
@pedram-tiv, you may have an older version of the ruby driver.  `next` was added with the 2.0 release.  Can you check the version of the ruby driver that you're using?

**Comment by pedram-tiv** [comment]
@Tryneus that solved the issue: updated to rethinkdb 2.0.0.1 (was 1.16.0.1)
it would be helpful to have driver versions in the doc pages.

thanks.
