### ISSUE TITLE
Data Explorer Feature request: A shortcut for r.db(<database>).table(<table>) for each table

### ISSUE THREAD

**Issue by ccheever** [rethinkdb/rethinkdb#4423]
Especially at the beginning of a project, I find myself using queries like

```
r.db('exp_host').table('users')
```

over and over again.

I'm not sure what the interface looks like but it would be kind of nice to have a bunch of buttons, one for each table in a database, and be able to click on them and see just everything in that table, maybe with click-to-sort-by column headers (though maybe that's a whole separate feature that would need to be thought through).

Many other db admin tools have functionality like this and it seems to be pretty popular and work pretty well, especially if you can live edit data within the tables. 

I don't think it would be too hard to map sorting and/or editing of cells into ReQL queries.

**Comment by danielmewes** [comment]
Hi @ccheever, thank you for the suggestion.

I think in its basic version this will be covered by https://github.com/rethinkdb/rethinkdb/issues/3509 .
More sophisticated features (like adapting the sorting etc.) will be covered by https://github.com/rethinkdb/rethinkdb/issues/1592 .
Does that sound right @ccheever ?

Closing as a duplicate.

**Comment by ccheever** [comment]
Sounds great. I glanced through the issues quickly before adding this new one but just missed #3509.
Sorry for the dupe.
