### ISSUE TITLE
interface.table_wait test stalls

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4424]
With https://github.com/rethinkdb/rethinkdb/issues/4422 fixed, `interface.table_wait` is now stalling with a table remaining unavailable.

**Comment by timmaxw** [comment]
In CR 3002 by @danielmewes.

**Comment by timmaxw** [comment]
Fixed in 7680ebce15adef8e56b0ddaa50f69e6491134750.
