### ISSUE TITLE
Better tests for table_raft_storage_interface_t

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#4425]
`table_raft_storage_interface_t` is lightly tested because most of our tests don't restart the server; so if it writes corrupted data, we might never find out. We should write a test that specifically puts it through its paces, and periodically tries to reload from the serialized file and confirms that the results match.

**Comment by VeXocide** [comment]
In CR 3104 by @danielmewes.

**Comment by VeXocide** [comment]
Merged into `next` via commit ba0ac15fa9043bbe398ab1f270c52deb16fa9198.
