### ISSUE TITLE
Consider providing binary for Debian Stretch?

### ISSUE THREAD

**Issue by fasiha** [rethinkdb/rethinkdb#4426]
I wouldn't ask if my VPS wasn't so feeble and building from source wasn't a fearsome endeavor. But I'll understand if you decline, no hard feelings!

Edit: I installed the jessie binary on stretch and it seems to be working well so far.

**Comment by AtnNn** [comment]
Thanks for the reminder.

This shouldn't be too hard, I'll try to do this before the upcoming 2.1 release.

**Comment by danielmewes** [comment]
@AtnNn Can you do this remotely?

**Comment by AtnNn** [comment]
Yes

**Comment by AtnNn** [comment]
I've added stretch-i386 and stretch-amd64 to the buildbot.

**Comment by danielmewes** [comment]
Debian stretch packages have been released with RethinkDB 2.2.0.
