### ISSUE TITLE
Ability to make read-only slaves in cluster

### ISSUE THREAD

**Issue by frankleng** [rethinkdb/rethinkdb#4427]
We have a use case where clients have an on-premise read-only slave to act as failover.

Is it possible to create a replica without write permissions right now?

**Comment by danielmewes** [comment]
Hi @frankleng, this isn't supported at the moment. Every member of a RethinkDB cluster has the same permissions.
We're planning to add read-only connections with a separate auth key https://github.com/rethinkdb/rethinkdb/issues/1805 , but that is for client connections and not cluster connections.
We don't have any plans to add a permissions system between cluster members.

Once we have read-only client connections, you might be able to perform data replication by running a local separated RethinkDB instance and using changefeeds to apply changes to the main cluster to it asynchronously. Would such a solution work for you?

**Comment by frankleng** [comment]
@danielmewes that will make the ability to resume changefeeds even more important. and that feature is coming out in 2.2 right?

**Comment by danielmewes** [comment]
Resumability for some cases is coming in 2.2, correct. There will still be some cases that will require a restart of the synchronization. We might be able to ship an improved version that covers those with 2.3.
