### ISSUE TITLE
Table page of unavailable tables loads slowly

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4432]
If I go to the table page for a table that has no replicas available, I'm getting this at first:
![unavailable table 1](https://cloud.githubusercontent.com/assets/505365/8262781/c9e17896-1689-11e5-80c6-875563585a23.png)

It takes almost 20 seconds and then it changes to this which looks correct:
![unavailable table2](https://cloud.githubusercontent.com/assets/505365/8262788/de24733a-1689-11e5-8e7f-fbec12875564.png)

**Comment by danielmewes** [comment]
On `next` commit 79fb0e3e7ef85addccaacc64128303a77ac9861d

**Comment by timmaxw** [comment]
I'm pretty sure this is server-side. I'm working on some related code anyway, so I'll take this issue.

**Comment by deontologician** [comment]
I owe you a donut or something

**Comment by timmaxw** [comment]
In CR 3006 and https://github.com/rethinkdb/rethinkdb/tree/tim/overhaul-status-and-wait.

**Comment by timmaxw** [comment]
Fixed in eb2ca72467b8543cf196ccfb4c7f2c2cc56b9415.
