### ISSUE TITLE
Add gevent support to the python driver

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#4433]
Aside from tornado/twisted/asyncio etc, a lot of people use flask and django and things, and their standard advice is to use gevent to gain access to features like websockets and long-polling.

I *think* as long as we have one connection per green-thread we get basic gevent support (the stdlib's socket implementation is monkey-patched with a cooperative version), but it would be nice to be able to use the same connection across green threads as well.

**Comment by danielmewes** [comment]
@Tryneus was working on one.

**Comment by Tryneus** [comment]
Yep, this is in the branch `grey_python_gevent` - the implementation for the python driver is done, but it needs testing.

**Comment by bigblind** [comment]
I'd really love to see this getting done. Is there anything I can help out with? (I don't know much about low-level networking, but I'd love to learn about it.)

**Comment by danielmewes** [comment]
@Tryneus Could @bigblind help by writing tests for your implementation maybe?

(it also needs a fresh merge from `next`, since we've changed some logic in the Python driver to improve performance in the meantime)

**Comment by thedrow** [comment]
This is my effort in helping making this happen: https://github.com/rethinkdb/rethinkdb/pull/5126
Not a very good one but I can't do anything about it. Rebasing doesn't solve the merge conflicts.

**Comment by danielmewes** [comment]
@thedrow Thanks for your help! I left a suggestion for how to get a cleaner diff in the PR.

**Comment by gvidon** [comment]
Have recently tried changefeed with gevent-socketio and it didn't work — ```self.emit()``` doesn't work when ```r.table(...).changes().run()``` called in the same method of namespace class. No error messages. 

Tried patching everything with ```gevent.monkey.patch_all()```, but it didn't help. Is it going to be fixed soon or I missed something and do it wrong?

**Comment by larkost** [comment]
@gvidon: for clarity, were you trying the currently shipping Python driver, the one from the PR #5126, or the one from the branch @Tryneus is working on (`grey_python_gevent`)? I would not expect it to work on the currently shipping one, and would need to do some testing specifically to make sure even the in-development version works specifically with `gevent-socketio`.

**Comment by gvidon** [comment]
@larkost thank you. I used the package from pypi, not sure which exactly branch is it from. Will try ```grey_python_gevent``` and let you know.

**Comment by Tryneus** [comment]
The `grey_python_gevent` branch has been reviewed and merged to `next` in commit da66a3a.  Will be in release 2.3.

**Comment by nickmishustin** [comment]
How install python-driver from grey_python_gevent or from next by pip? 
When I try  
pip install -e git+https://github.com/rethinkdb/rethinkdb.git@grey_python_gevent 
or  
pip install -e git+https://github.com/rethinkdb/rethinkdb.git@next 
I get error.

**Comment by renstrom** [comment]
@nickmishustin, that doesn't work since the Python driver is in a subfolder. You have to clone the repo locally. Something like this:

```bash
$ git clone git@github.com:rethinkdb/rethinkdb.git
$ pip install ./rethinkdb/drivers/python
```

**Comment by nickmishustin** [comment]
@renstrom, it works. Thanks for your help!

**Comment by larkost** [comment]
I don't know if `pip` knows about `make`files, so I am worried that @renstrom's instructions are missing one step before the last:
```make --directory ./rethinkdb/drivers/python```
This runs `make` in that directory, which will make sure that the driver is complete. Technically this creates the finished version in `./rethinkdb/build/drivers/python`, but for ease of development it also copies the one file that needs to be created into ` ./rethinkdb/drivers/python` as well. So for this purpose they are equivalent.

**Comment by nickmishustin** [comment]
I have trouble with @renstrom's instructions now. When I try 
`import rethinkdb as r`
I get the error :
`ImportError: cannot import name ql2_pb2`
and I get the error after `make --directory ./rethinkdb/drivers/python`
`../../mk/configure.mk:23: Configure error: Missing or invalid config file.
../../mk/configure.mk:24: *** Run ./configure or edit ../../config.mk`

**Comment by larkost** [comment]
Ya.. @nickmishustin is right... in my one more line there should have been two:
```
./configure
make --directory ./rethinkdb/drivers/python
```

The `configure` script does check for a lot of things that are not necessary to only build this one part. I am going to file a separate issue (#5329) to think about that. I am also going to ping @danielmewes to see if we should sync all of the driver changes from `next` to `v2.2.x` and put out a release?

**Comment by renstrom** [comment]
I've updated my example with the `configure` and `make` step.

**Comment by danielmewes** [comment]
I'd prefer to wait for 2.3 before releasing this with the official driver. Though if there's a lot of demand, we can surely backport it.

**Comment by thedrow** [comment]
Please backport.

**Comment by nickmishustin** [comment]
It works with the `./configure` and `make`. Thank you all!

Backport would be more convenient way :)

**Comment by nickmishustin** [comment]
Changefeed with gevent-socketio problem continue in python driver from `next`. 
I have the same problem as that of @gvidon - `self.emit() ` doesn't work when `r.table(...).changes().run() `called.

**Comment by renstrom** [comment]
@nickmishustin @gvidon perhaps create a separate issue for that now that gevent support has been merged into `next`? Just to prevent this from becoming a kitchen sink for gevent related bugs/issues.

**Comment by AlexzAK** [comment]
When release 2.3 with gevent support will became available?

**Comment by larkost** [comment]
@AlexzAK: We are planning on releasing 2.3 sometime around the end of the month. That timing is chained to a major feature (user-level security), so is more of a guideline than a promise.
