### ISSUE TITLE
Wrong issue description in web UI

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4434]
"
Table test.t1 is available for all operations, but some replicas are not ready.

None of the replicas for this table are reachable (the servers for these replicas may be down or disconnected).
No operations can be performed on this table until at least one replica is reachable.
"

The first line was correct, the rest of the message was not.

**Comment by WuLex** [comment]
呵呵！

**Comment by deontologician** [comment]
这不好笑！

**Comment by deontologician** [comment]
@danielmewes turns out I was not able to replicate this. The only reason I thought I could was because I reversed the logic in one commit, and reversed it back in another.

What did you do to get this error message?

**Comment by danielmewes** [comment]
I don't remember exactly, but looking at the conditions in admin/static/coffee/issues.coffee `render_table_availability` I think I have an explanation:
```
[...]
        h "p", [
            "The following servers are disconnected:"
            h "ul", info.missing_servers.map((servername) ->
                h "li",
                    h "code", servername
            )
        ] if info.missing_servers.length > 0
        h "p", [
            "None of the replicas for this table are reachable "
            "(the servers for these replicas may be down or disconnected). "
            h "br"
            "No operations can be performed on this table until at least "
            "one replica is reachable."
        ] if info.missing_servers.length == 0
```

Note that it shows the observed message if no servers are reported missing.
However a table can be not fully ready for reasons other than a missing server, so I believe this check is wrong.

I was probably reconfiguring a larger table, so it took a while for it to bring all replicas up to date.

**Comment by deontologician** [comment]
According to @timmaxw (via slack)
> there will never be a table availability issue if all servers are connected. We show an issue if table has reduced availability AND at least one server is disconnected 

So I think the logic is correct, and if we see an issue like this and the servers are not disconnected, then it's a bug in the issue code. I think we should verify what conditions this can occur in, and then close this (possibly opening a server issue if we find something buggy in the issue code)

**Comment by danielmewes** [comment]
Can't reproduce it anymore.
