### ISSUE TITLE
Dash.app docset for RethinkDB

### ISSUE THREAD

**Issue by jwr** [rethinkdb/rethinkdb#4435]
I would like to kindly request a Dash (https://kapeli.com/dash) docset for RethinkDB. Dash is used by many programmers as a quick reference tool, on Macs and on iOS devices. It is spectacularly useful — documentation is just a single keystroke away.

I think building and maintaining an official RethinkDB Dash docset would go a long way towards making RethinkDB easier and more convenient to use for programmers.

**Comment by VeXocide** [comment]
Hi @jwr, we keep our documentation in a separate repository where we have an open issue to create a docset for Dash, see https://github.com/rethinkdb/docs/issues/541. I'm closing this as a duplicate, but please feel free to leave a comment there.
