### ISSUE TITLE
JS driver releases are using bad semvers

### ISSUE THREAD

**Issue by stuartpb** [rethinkdb/rethinkdb#4436]
The latest release of `rethinkdb` on npmjs.com is `2.0.0-2`. Version `2.0.0` has already been released. Versions that are followed by a hyphen and additional text are *prerelease* versions which [*can not match* a dependency range that does not specify prerelease tags](https://docs.npmjs.com/misc/semver#prerelease-tags). This means that a library with a `peerDependencies` entry for a range of `rethinkdb` versions will **fail** on installing if the latest version of `rethinkdb` was added with `npm install --save rethinkdb`.

Releases to the driver *need* to be specified as patch version bumps, if not minor or major ones.

**Comment by AtnNn** [comment]
That was my mistake. I'll change it to 2.0.2.

**Comment by stuartpb** [comment]
How soon until this is published?

**Comment by AtnNn** [comment]
I already published it. It hasn't shown up on https://www.npmjs.com/package/rethinkdb yet, I don't know how long that will take.

**Comment by AtnNn** [comment]
That page hasn't updated yet. However, it looks like the `2.0.2` version is now available:

```
$ npm install rethinkdb
rethinkdb@2.0.2 node_modules/rethinkdb
└── bluebird@2.9.30
```

It should be identical to `2.0.0-2`.
