### ISSUE TITLE
Make `<boolean>.branch(<b1>, <b2>)` work

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4438]
In the JavaScript driver at least, we currently support
`r.branch(<boolean>, <b1>, <b2>)` but not `<boolean>.branch(<b1>, <b2>)`

I think we should support both syntaxes.

(checking Python and Ruby as well, even though I suspect that it might already be working in Ruby)

**Comment by marshall007** [comment]
@danielmewes just submitted a PR. You were right, this already worked in the Ruby driver, but not JS or Python.
