### ISSUE TITLE
Failing to remove file after removing a replica

### ISSUE THREAD

**Issue by VeXocide** [rethinkdb/rethinkdb#4440]
Given a table `"test"` with 10k records, when reconfigured to two replicas 

`r.table("test").reconfigure({shards: 1, replicas: 2})`,

and after the backfill back to a single replica 

`r.table("test").reconfigure({shards: 1, replicas: 1})`

the data file is not removed. After restarting this replica it recognises the file isn't needed and removed.

**Comment by timmaxw** [comment]
In CR 3008.
