### ISSUE TITLE
Improve unsaved data limit throttling

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4441]
Under heavy soft durability write workload, our current unsaved data limit throttling leads to uneven utilization of the storage system as well as to abrupt stalls in writes and up to date reads to the affected tables.

I think we can improve our write throughput significantly by improving it. I have some ideas on what we can do, but have to give it a bit more thought.

**Comment by samuelgoldenbaum** [comment]
Would have expected to see a fairly consistent rate of writes, but actually see quite a lof dips and spikes for both hard and soft writes:

![rethink-hard](https://cloud.githubusercontent.com/assets/278570/8302365/3265f914-1996-11e5-9bb6-b813dd9f7e23.png)

![__r2](https://cloud.githubusercontent.com/assets/278570/8302367/32b31726-1996-11e5-9f2d-7804b7bafa27.png)

**Comment by danielmewes** [comment]
Fixed in 1fc0c5152a774dd2e2aa4917f78c681271e8779c, was in CR 3019. Will ship with RethinkDB 2.1.

**Comment by danielmewes** [comment]
In the `node insert.js --dbpackage rethinkdb --nb 200000 --threads 5` test of https://github.com/chussenet/db-perf-test, this changed RethinkDB's performance on our benchmark server (pretty chunky machine) as follows:

On a rotational disk:
  Before: ~6,500 inserts/s  | After: ~14,000 inserts/s
On an SSD:
  Before: ~24,000 inserts/s | After: ~37,000

**Comment by danielmewes** [comment]
Unfortunately the change introduced a new problem: While transactions are throttled if they exceed the unsaved data limit, some of their metadata can linger around for a while and those transactions can accumulate over time. This can lead to growing memory consumption over time under heavy write workload.
Re-opening.

**Comment by danielmewes** [comment]
The fix for the run-away memory consumption is now in code review 3047.

**Comment by danielmewes** [comment]
The fix for the memory consumption issue that was created by the previous fix is now merged into `next` as of https://github.com/rethinkdb/rethinkdb/commit/3a347e161551702dd2aa08624556fb04d5217f19 .
This unfortunately makes write query throughput somewhat spiky again on rotational disks, but the overall throughput is still essentially what I had measured after the first improvement.

**Comment by v3ss0n** [comment]
So this will be added in coming 2.1 version? The problem of spiky throughput is tracked ?

**Comment by danielmewes** [comment]
@v3ss0n Yes, the fix for the problem where throttling reduced the overall write throughput is going to ship with 2.1.

We don't currently have a dedicated issue for spiky write throughput, but I don't think it's a big problem in practice.
Benchmarks are special because they intentionally try to reach the limits of the system. In practice if you have an application that continuously generates write queries at a higher rate than what the storage system (HDDs or SSDs) can absorb, spiky throughput is going to be the least of your problems I think.
One exception I can see is the case where you have batch write jobs running in the background, and you don't want them to make foreground queries go into high latencies. In that case there is the easy work-around of making the background / batch writes run with hard durability though, which should make sure that they get slowed down before they can push the amount of unsaved data into critical regions.
Please let me know if you think there are other important cases that I forgot.

Btw: The improvements in 2.1 already make writes on SSDs very smooth on my system with the benchmark I tried. It's only on rotational disks where writes were still stalling for a moment if too much unsaved data accumulates.

**Comment by v3ss0n** [comment]
@danielmewes  thanks! Does this have in rethinkdb 2.1-beta ?

**Comment by danielmewes** [comment]
@v3ss0n Yep, shipped today in the beta https://github.com/rethinkdb/rethinkdb/releases/tag/v2.1.0-0BETA1
