### ISSUE TITLE
Support simple `.do` manipulations on point changefeeds

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#4443]
Right now we can do:

```python
r.db('rethinkdb').table('table_config')['shards'].changes()
r.db('rethinkdb').table('table_config').map(r.row['shards'].count()).changes()
```
but not:

```python
r.table('foo').config()['shards'].changes()
r.table('foo').config().do(r.row['shards'].count()).changes()
```

It seems, intuitively, any manipulation you can map over and changefeed, you should be able to `.do` over and changefeed on a single document.

**Comment by danielmewes** [comment]
I think we already have an issue for this, but I can't find it at the moment. @mlucy do you remember which one it was?

**Comment by mlucy** [comment]
Closing as a dup of https://github.com/rethinkdb/rethinkdb/issues/3623 .
