### ISSUE TITLE
yum not showing the 2.0.3 update

### ISSUE THREAD

**Issue by nodesocket** [rethinkdb/rethinkdb#4444]
Not sure if this is the right place for this, but I noticed an alert that RethinkDB version `2.0.3` was released in my web admin. However, when I SSH into a RethinkDB server and run:

    yum clean all
    yum update

I don't see the `2.0.3` update available. I am using the official yum repository.

````
[rethinkdb]
name=RethinkDB
baseurl=http://download.rethinkdb.com/centos/6/x86_64/
gpgcheck=0
enabled=1
````

**Comment by AtnNn** [comment]
Your repo file looks good. 

I was not able to reproduce your issue.

What is the output of `yum update`? Does it work if you `yum install rethinkdb` or `yum install rethinkdb-2.0.3`?

**Comment by nodesocket** [comment]
Nevermind, apparently the `yum update` already ran, but rethink was not restarted.

A simple `sudo service rethinkdb restart` fixed it.
