### ISSUE TITLE
Server result json returning hexvalues

### ISSUE THREAD

**Issue by Gesias** [rethinkdb/rethinkdb#4446]
Hello!

Just wondering if someone else has come across this issue. I am running rethinkdb 2.0.2 with pythonclient and using Celery to handle some parsing of documents. Everything is running on OSX yosemite. 

I am also investigating Celery for this, since it works if I have only one worker thread per process. I can have multiple processes running in parallell as long as each process only has one worker. If I have two workers attached to the same process, this behavior appears. So, this most likely is not rethinkdb:s fault, rather a behavior maybe someone with more core rethinkdb knowledge may be able to help me solving or give me some ideas.

When I get the Response from the rethinkdb server it sometimes adds hexcodes in front of or after the string which ruins the decoding.  

Heres an example of the response, I´ve digested the last document to make it less verbose.
```
{"deleted":0,"errors":0,"inserted":0,"replaced":1,"skipped":0,"unchanged":0}],"n":[]}\t\x00\x00\x00\x00\x00\x00\x00\x81\t\x00\x00

\x03\x00\x00\x00\x00\x00\x00\x00\xf0\t\x00\x00{"t":2,"r":[{"brand_id":"5dffbcfe-9cf7-444b-8f00-daf42d502335","category_id":"5986cb82-b9c4-4afe-aab8-fcf300bda7e5"}]
````
This obviously gives me issues like this
```
File "/Users/someuser/PycharmProjects/gambit/lib/python2.7/site-packages/rethinkdb/net.py", 
line 84, in __init__ 
json_str = json_str.decode('utf-8')
File "/Users/someuser/PycharmProjects/gambit/lib/python2.7/encodings/utf_8.py", 
line 16, in decode return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf0 in position 8: 
invalid continuation byte
```
or this
````
  File "/Users/someuser/PycharmProjects/gambit/lib/python2.7/site-packages/rethinkdb/net.py", line 88, in __init__
    full_response = json.loads(json_str)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 368, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 2513 - line 1 column 2534 (char 2512 - 2533)
````

Very grateful for any theories or ideas about this!

**Comment by Tryneus** [comment]
@Gesias, the python driver connections are not thread-safe, you should either protect them with a mutex or use one connection per thread.  It looks like the connection code is desyncing with the server and reading out the wrong number of bytes - this could certainly happen due to multiple threads accessing the connection at once.

Note that this also extends to Cursors - reading from a cursor can cause reads to happen on the Cursor's connection, so it should only be done from same thread.

**Comment by mlucy** [comment]
@Tryneus -- would it be feasible to detect when a Python connection is being used on multiple threads and produce an error?  People seem to run into that quite frequently.

**Comment by Tryneus** [comment]
@mlucy, @larkost had some ideas for that, but I don't think we ever scheduled anything.

**Comment by Gesias** [comment]
Great, thanks! Was thinking about the thread thing but thought the errors would be worse than just failing to decode json. Throwing an error would be nice for sure.

Will most probably just run different processes to begin with and leave it like that. Cheers!
