### ISSUE TITLE
Open file limit...

### ISSUE THREAD

**Issue by graycatfromspace** [rethinkdb/rethinkdb#4447]
I looked into my other processes using "/proc/xxxx/limits" and they all have the correct limit but rethink db has its limit set to 4k, im needing to handle way more than 4k connections. I have been trying to fix this issue for weeks and cannot seem to find a solution!

I am using connection pooling, all my file limits are set to over a million every process on my system is using the new limits besides rethinkdb.

http://i.imgur.com/hMEup6m.png 
http://i.imgur.com/5QUoYXE.png 
http://i.imgur.com/dIQRTEu.png 
http://i.imgur.com/D9t2Blq.png

As you see i even tried to enforce the limit specifically on rethinkdb with nothing working. (commented added after ofc)

**Comment by deontologician** [comment]
How are you running rethinkdb?

**Comment by graycatfromspace** [comment]
service rethinkdb start

**Comment by deontologician** [comment]
is this on ubuntu?

**Comment by graycatfromspace** [comment]
no debian 8

**Comment by danielmewes** [comment]
Thanks for opening an issue about this @graycatfromspace .

We will see if we can reproduce this, though I still think that it might be an issue with the configuration and not with RethinkDB. Maybe something about how Debian sets the user limits?

**Comment by graycatfromspace** [comment]
could you please look at my screenshot they clearly show my limits are set way high enough. Also, as I said its only this process redis, nginx, ect do not have this 4000 limitation.

**Comment by deontologician** [comment]
@graycatfromspace Could you try adding ulimit -n 1000000 to the beginning of the /etc/init.d/rethinkdb script and restart the service?

**Comment by danielmewes** [comment]
@graycatfromspace I've looked at the configuration, the limits you've configured are obviously high enough.

I haven't tried on Debian 8 yet. Maybe we have an incompatibility there. On Ubuntu 12.04 I can easily open 10000+ connections to a single server.

I'm not sure how limits.conf is parsed exactly. Have you tried replacing the `-` in your entries by `hard`? Just a guess, I suspect that's not it but maybe worth a try?

**Comment by danielmewes** [comment]
@graycatfromspace could you also check if there's a message "The call to set the open file descriptor limit failed" in the server log (it should appear very early during server startup)?

**Comment by danielmewes** [comment]
(for anyone looking into this: if this is an incompatiblity with Debian 8, the place to look at is the function `run_generic_global_startup_behavior()` in `utils.cc`. That's where we set the soft file descriptor limit to be equal to the hard limit. If somehow reading the hard limit was giving us a wrong value, then that could cause us to set a wrong soft limit as well.)

**Comment by danielmewes** [comment]
Finally one more thing that might be worth trying: What do you get when running rethinkdb as root manually (I don't recommend that for production obviously, but it might help isolating the issue)?

**Comment by graycatfromspace** [comment]
@deontologician thanks for the solution that did the trick!

**Comment by deontologician** [comment]
solution obtained from a few SO answers like this one: http://superuser.com/a/459183/353286
