### ISSUE TITLE
Make the heartbeat timeout configurable

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#4449]
We should add a field `heartbeat_timeout_secs` to the `cluster_config` table to let the user modify the timeout (in case, for example, they want the system not to failover if there are short blips in network connectivity).

**Comment by danielmewes** [comment]
To clarify: If we make the heartbeat timeout configurable, we can have cluster connections survive longer network blips as long as the TCP connection remains alive. I think this will usually be the case if for example someone briefly unplugs a network cable, at least if it's not the one connected directly to the server (so the OS cannot know that the cable has been unplugges).

Thinking about this again, I'm now wondering if this is enough. If for example a router fails somewhere in the network, the TCP connection itself might get terminated. If we want to sustain TCP connection loss, we would need to implement a different timeout parameter (like an actual "wait this long after losing connectivity before initiating a failover"). @timmaxw how difficult would it be to have that parameter configurable? Are there any corner cases you can think of that we need to be aware of if this parameter is freely configurable?

**Comment by timmaxw** [comment]
At one point we had a hard-coded timeout between when the table detected connection loss and when it began failover. The implementation was a bit of a mess and also buggy, so I took it out and made the system just use connection loss for failover purposes. So the thing you're proposing would be kind of a pain to implement, although possible.

The way we were doing it before was that when the executor sent a `secondary_need_primary` contract ack to the coordinator, it would include a flag indicating whether it had been looking for the primary for longer than the failover timeout. The advantage of this scheme is that it doesn't rely on clock synchronization over the network and it isn't affected by the coordinator moving to a different server. But the logic we had for updating the flag was kind of annoying and bug-prone. If we wanted to implement a configurable post-connection-loss failover timeout, I think we'd want to keep that same implementation strategy.

**Comment by danielmewes** [comment]
Yeah I remember that. I'd prefer not to bring that logic back if possible. Was hoping that there might be an easier way to implement this specific parameter with our current implementation, but maybe not?

Maybe having the heartbeat timeout configurable is actually enough. Unfortunately I don't really know how common the different types of network blips are. @coffeemug do you have any insights about what sort of brief network failures people are concerned about?

**Comment by coffeemug** [comment]
I don't think we should complicate it by attempting to repair the TCP connection loss within a time window, or anything like that. The issue is mostly psychological, I don't think people will change the value most of the time, but it's important for them to know they have ability to.

**Comment by VeXocide** [comment]
In CR 3060 by @danielmewes.

**Comment by VeXocide** [comment]
Merged into `next` via commit 705b238802984ca6cc630866cced1e5c305412a4.
