### ISSUE TITLE
Figure out what the dashboard needs to show after raft

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#4461]
Currently, I have it looking like this:
![selection_061](https://cloud.githubusercontent.com/assets/1366/8368487/ef99a1b4-1b5f-11e5-8a76-d5d9481764ea.png)

The problem is that if all of the servers for a table go down, we no longer have any way of telling how many shards/replicas it should have. So the denominators of the availability and redundancy panels will be useless.

@danielmewes @timmaxw @mglukhovsky any thoughts on what to do here?

This is blocking #4395 and #4391

**Comment by deontologician** [comment]
One solution is to get rid of the bottom numbers, since we can't always calculate it, and just keep the "x tables are affected" part, since we can always determine that

**Comment by deontologician** [comment]
Another issue is this panel at the top:
![selection_062](https://cloud.githubusercontent.com/assets/1366/8368833/9260ca22-1b64-11e5-9f9b-9b85ef7b3b97.png)

The best I can do right now for the denominator is "max of servers connected or servers assigned to tables" This still fails in the case where servers are assigned to tables, but those tables are completely down and so don't have non-authoritative server lists. In this case it will seem "everything is a-ok" because the denominator is servers connected.

The more I'm thinking about this, the more I think we just need to eliminate denominators that represent servers

**Comment by danielmewes** [comment]
This is a little tricky. I have to think about it for a bit. Removing denominators for servers sounds reasonable, but I'm not sure yet what we can do for the replicas (at least not if we want to maintain the current two-row layout in the dashboard).

**Comment by deontologician** [comment]
Yeah, I am thinking the two row thing might just need to go maybe. Index issues doesn't make sense anyway, so it could just be indexes constructing

**Comment by deontologician** [comment]
After thinking a bit about this, here's my proposal for the new panels. Each would have 3 numbers:

- Servers panel
  - # of servers connected (server_status.count())
  - # of servers unassigned (servers_connected set_diff table_config.replicas.distinct)
  - # of servers missing (table_config.replicas.distinct set_diff servers_connected)
    - Add a '+' to the number if any tables in table_stats has no connected replicas
    - servers assigned and missing has a minimum of 1 if any table
      is down because all of its replicas are gone
- Tables panel
  - # of tables "ready"
  - # of tables "reduced" (write_only, read_only, outdated_read_only)
  - # of tables "unavailable" (outdated_read_only == false)
- Indexes panel
  - total # of secondary indexes
  - # of secondary indexes rebuilding
  - # of outdated indexes
- Connections panel
  - # of client connections
  - # of active connections
  - # of queries per second

This invents two new terms "servers assigned" for servers that have tables assigned to them, and "servers missing" which are assigned servers that are not currently connected.

**Comment by deontologician** [comment]
For reference, the dashboard panels look like this now
![selection_071](https://cloud.githubusercontent.com/assets/1366/8534052/e627d4e8-23ed-11e5-864c-a2ddc9cbf573.png)
