### ISSUE TITLE
DB name conflict issue rendered incorrectly in web UI

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4463]
![db name issue](https://cloud.githubusercontent.com/assets/505365/8388574/91243ee6-1c18-11e5-9876-e4bc53ea2a9c.png)

`current_issues` looks like this:
```js
{
    "critical": true ,
    "description": "There are multiple databases named `test`. RethinkDB requires that every database have a unique name. Please update the `name` field of the conflicting databases' documents in the `rethinkdb.db_config` system table.

    The UUIDs of the conflicting databases are as follows: 36567b7c-38d5-4a25-91f8-911d9ddd41f5, 71a29864-05f0-4c5e-85e5-f1764f6c5c2b, d0da5912-34c0-42d4-bfe0-ca2e3bdb0ca7" ,
    "id": "a60c9c46-8671-5c75-8ca0-2ae1e3e68143" ,
    "info": {
        "ids": [
            "36567b7c-38d5-4a25-91f8-911d9ddd41f5" ,
            "71a29864-05f0-4c5e-85e5-f1764f6c5c2b" ,
            "d0da5912-34c0-42d4-bfe0-ca2e3bdb0ca7"
        ] ,
        "name": "test"
    } ,
    "type": "db_name_collision"
}
```

**Comment by danielmewes** [comment]
On a side note: The table listing doesn't appear to distinguish databases by UUID, but only by name:
![db conflict tables](https://cloud.githubusercontent.com/assets/505365/8388603/dec344c6-1c18-11e5-884f-6771a420dbf0.png)

(there actually is only one table `t1` in one of the `test` databases)

**Comment by danielmewes** [comment]
For "We should probably also change the "Delete Database" " we need to fix https://github.com/rethinkdb/rethinkdb/issues/4465 first, so let's wait with that.

**Comment by danielmewes** [comment]
To clarify: I think fixing the issue and having a working "rename" link in there is enough for 2.1. The other things about the table list aren't as critical I think.

**Comment by mlucy** [comment]
@danielmewes -- yes, they both affected both versions.  I'll get them merged into both branches today.

**Comment by deontologician** [comment]
Sounds good. This fix is mostly done, though it revealed there are a bunch more links to the defunct databases page that I need to remove
