### ISSUE TITLE
Deleting a database (sometimes?) doesn't delete all its tables

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4465]
I created a single table on a single server in the `test` database, then joined two other servers into the cluster that also already had a `test` database. Then I deleted all databases through
`r.db('rethinkdb').table('db_config').delete()`

Now `r.db('rethinkdb').table('table_status')` looks like this:
```
 {
    "db": "__deleted_database__" ,
    "id": "23125856-6a20-439c-8e9a-454d998de631" ,
    "name": "t1" ,
    "shards": [
        {
            "primary_replicas": [
                "newton_tbe"
            ] ,
            "replicas": [
                {
                    "server": "newton_tbe" ,
                    "state": "ready"
                }
            ]
        }
    ] ,
    "status": {
        "all_replicas_ready": true ,
        "ready_for_outdated_reads": true ,
        "ready_for_reads": true ,
        "ready_for_writes": true
    }
} 
```

**Comment by danielmewes** [comment]
In fact I can reproduce this on a single server by doing the following:
```
r.tableCreate('t1')
r.db('rethinkdb').table('db_config').delete()
```

This also appears to be causing a lot of test failures, since the left over tables are generating spurious entries in the `current_issues` table for some of the tests. It must be a recent regression.

**Comment by danielmewes** [comment]
This seems to be specific to deleting from db_config. Using `dbDrop` appears to work as expected.

**Comment by danielmewes** [comment]
The test failures were actually for a different reason, and it seems like this has never worked. Moving to polish.

**Comment by nighelles** [comment]
This is in review 3455.
Implemented in nighelles/4465
https://github.com/rethinkdb/rethinkdb/tree/nighelles/4465

**Comment by nighelles** [comment]
This is in next.
