### ISSUE TITLE
Updates for ARM architecture

### ISSUE THREAD

**Issue by atomgomba** [rethinkdb/rethinkdb#4468]
I successfully compiled and installed RethinkDB 1.16.3 experimental ARM version on my Banana Pi, and recently notification on the admin UI popped up that there's a new version. Can the new version also be compiled for ARM? Are there any updates?

**Comment by danielmewes** [comment]
Hi @atomgomba. Since ARM is still not an officially supported architecture of RethinkDB, there are no binaries to download. You should be able to compile RethinkDB 2.0.3 for ARM mostly the same way you did for 1.16.3.
