### ISSUE TITLE
Limit backfill memory usage when loading large values

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#4474]
The new backfilling algorithm loads up to 16 leaf nodes at a time from disk. With 16MB values, that would be multiple tens of gigabytes of RAM usage per backfill. The solution is twofold:

1. Apply the item chunk size limit as we load values from disk. That probably means that `backfill_item_consumer_t` should have a separate method like `acquire_semaphore()` that gets called before `on_item()`. Before loading each value, the B-tree traversal code would try `acquire_semaphore()`.

2. If `acquire_semaphore()` returns `false` while we're loading a multi-key backfill item, then we should stop loading the item at that point and set its right bound to just before the key we were about to load, then pass on the incomplete item normally. This allows us to break large items into smaller chunks.

If this is done right, the memory usage per-backfill should be limited to approximately the value of `item_queue_mem_size` plus the size of the largest value in the B-tree.

**Comment by danielmewes** [comment]
In CR 3108 by @timmaxw

**Comment by danielmewes** [comment]
Merged into `next` as of 78553c70e72c35ac6ba3aaae30d1df73ca1642b2 . (Sorry, I forgot to use `--squash`. Will try to remember it next time.)
