### ISSUE TITLE
secondary stuck in waiting_for_primary even after primary is back up

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#4477]
![selection_063](https://cloud.githubusercontent.com/assets/1366/8441159/63fa2a32-1f2b-11e5-8a0f-6178b08062a8.png)

output of `r.db("rethinkdb").table("_debug_table_status").filter({name: 'bar'})` is here: https://gist.github.com/19ae2fd3c7c0a6b679fc

**Comment by deontologician** [comment]
table_status for the above:

```json
{

    "db": "test" ,
    "id": "fe5f47c1-7811-4542-a90a-134f94e2aeae" ,
    "name": "bar" ,
    "shards": [
        {
            "primary_replicas": [
                "eos_3146"
            ] ,
            "replicas": [
                {
                    "server": "eos_3146" ,
                    "state": "ready"
                } ,
                {
                    "server": "eos_3148" ,
                    "state": "ready"
                } ,
                {
                    "server": "eos_3145" ,
                    "state": "ready"
                }
            ]
        } ,
        {
            "primary_replicas": [
                "frampton"
            ] ,
            "replicas": [
                {
                    "server": "eos_3147" ,
                    "state": "ready"
                } ,
                {
                    "server": "frampton" ,
                    "state": "ready"
                } ,
                {
                    "server": "eos_3144" ,
                    "state": "ready"
                }
            ]
        } ,
        {
            "primary_replicas": [
                "eos_3149"
            ] ,
            "replicas": [
                {
                    "server": "eos_3143" ,
                    "state": "waiting_for_primary"
                } ,
                {
                    "server": "eos_3149" ,
                    "state": "ready"
                } ,
                {
                    "server": "eos_3144" ,
                    "state": "ready"
                }
            ]
        }
    ] ,
    "status": {
        "all_replicas_ready": false ,
        "ready_for_outdated_reads": true ,
        "ready_for_reads": true ,
        "ready_for_writes": true
    }

}
```

**Comment by deontologician** [comment]
Contrary to my guess, bouncing the cluster didn't help:

![selection_064](https://cloud.githubusercontent.com/assets/1366/8441757/28f32944-1f2f-11e5-87ec-2a56102b7d0d.png)

**Comment by deontologician** [comment]
It is just this one table though, the other two tables in the cluster havent changed

**Comment by deontologician** [comment]
debug tables status after bouncing: https://gist.github.com/deontologician/0516040242d6cc134a15

**Comment by timmaxw** [comment]
We also determined that Raft transactions aren't going through. It looks like the cluster is failing to elect a Raft leader. This might be one of the same bugs that was uncovered by the Raft fuzzer, in which case it's already fixed in `next`. @deontologician is checking.

**Comment by deontologician** [comment]
Ok, the corrupted data folder is in ~josh/borked_server.tar.gz on newton

**Comment by danielmewes** [comment]
If I remember correctly, this is hard to verify because we can't load the old data.
Since we haven't seen it again as far as I know, and there's a chance that it has been fixed.
Closing until we see it again (hopefully never).
