### ISSUE TITLE
Missing documents with using slice or skip on an orderBy index term

### ISSUE THREAD

**Issue by wfairclough** [rethinkdb/rethinkdb#4479]
Running the following slice on a large table I can see 1 result returned.
```
r.db('mydb').table('largeTable').slice(110290, 110300)

Result:
Executed in 1.76s. 1 row returned
```

When I try ordering the table by a secondary index and use the same values for the slice I see 0 values return.
```
r.db('mydb').table('largeTable').orderBy({index: r.desc('modified_at')}).slice(110290, 110300)

Result:
Executed in 11.65s. No results returned.
```

I would have expected to see 1 result returned in the second expression like the first.

**Comment by danielmewes** [comment]
Hi @wfairclough, thank you for the report.
Are there any values that don't have a `modified_at` field or where this field is `null` in your table?

**Comment by wfairclough** [comment]
@danielmewes Thanks for the tip that must have been the issue. After running the following command I see the expect behaviour. 
```
r.db('mydb').table('largeTable').update({modified_at: r.now()})
```

**Comment by danielmewes** [comment]
@wfairclough Happy to hear it's now working. For your information: we are considering changing the behavior of secondary indexes with respect to `null` in https://github.com/rethinkdb/rethinkdb/issues/1032 . If the field is missing though I believe it would still be absent from the secondary index.
