### ISSUE TITLE
Discrepancy in driver and server version throws unhelpful error message

### ISSUE THREAD

**Issue by thejsj** [rethinkdb/rethinkdb#4481]
When there's a discrepancy between the server version and the client driver version, RethinkDB throws an error, but the error messages is not helpful. Here's the message:

```
Error creating database { [RqlDriverError: Server dropped connection with message: "ERROR: this is the rdb protocol port (bad magic number)"]
  name: 'RqlDriverError',
  msg: 'Server dropped connection with message: "ERROR: this is the rdb protocol port (bad magic number)"',
  message: 'Server dropped connection with message: "ERROR: this is the rdb protocol port (bad magic number)"' }
```

I'd be better if it explicitly stated that there's a difference between the client driver version and the server version.

**Comment by danielmewes** [comment]
To solve this problem properly, we will need to change how the driver handshake works, and exchange versions explicitly. Currently the magic we send at the beginning of a connection is used both for detecting things connecting to the wrong port, as well as to detect the protocol version being used. This will probably happen as part of https://github.com/rethinkdb/rethinkdb/issues/3134.

As an immediate improvement, just changing the error message sounds ok.
Maybe something like "ERROR: Bad magic number. Are you connecting to the wrong port (this is the RethinkDB client protocol port)? Are you using a driver that is too new for the server?"

**Comment by thejsj** [comment]
> As an immediate improvement, just changing the error message sounds ok.
Maybe something like "ERROR: Bad magic number. Are you connecting to the wrong port (this is the RethinkDB client protocol port)? Are you using a driver that is too new for the server?"

I think this would be a good simple improvement for the near future.

**Comment by thejsj** [comment]
Just found this issue which supposedly fixed it: https://github.com/rethinkdb/rethinkdb/issues/2302

**Comment by thejsj** [comment]
This error came up from testing it with an older version. Should be fixed.
