### ISSUE TITLE
Double-check error types

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#4484]
Known problems from #4483:

* `r.minval` produces `InternalError`
* `array_limit: -1` produces `InternalError`

**Comment by marshall007** [comment]
Another one to consider is `r.error()` producing `RqlUserError: Empty ERROR term outside a default block`. In this particular case it may make more sense for this to be `RqlLogicError` due to incorrect usage of `r.error`.

**Comment by mlucy** [comment]
It turns out several of these were actually caused by us handling `datum_exc_t`s incorrectly in `query_cache.cc` (we were just overwriting the error type with an internal error).  I have a fix for that, but I'm waiting on #4590 since a lot of the error type tests are failing in `next` anyway.

**Comment by mlucy** [comment]
This is in CR 3124 by @danielmewes .

**Comment by mlucy** [comment]
This is in next.
