### ISSUE TITLE
Testing: do not depend on globally installed npm modules

### ISSUE THREAD

**Issue by marshall007** [rethinkdb/rethinkdb#4487]
Building the JS driver and web UI currently requires specific (old) versions of `coffee-script` and `browserify` to be installed globally. They should instead be installed locally and referenced as `./node_modules/.bin/coffee-script` for example. That way the tests will run regardless of what your environment looks like.

**Comment by larkost** [comment]
You can already do this by using the `--fetch` options to `configure` from the top-level directory:

```
./configure --fetch coffee --fetch browserify --allow-fetch
make js-dist
```

The `--allow-fetch` is to let our `make` system configure everything in case you wanted to use a larger `make`.

But you do make a decent argument for us to make `coffee` and `browserify` non-optional fetches, since we are not validating other versions (and the implication is that newer versions don't work).

**Comment by marshall007** [comment]
I've seen the output from `./configure` but assumed `--fetch` would blow away my existing global installations. Are you saying that using this option actually installs and references them locally? If so, I agree that shouldn't be optional and should just happen by default.

**Comment by larkost** [comment]
Yes `--fetch` and `--allow-fetch` download/install into an `external` folder inside the RethinkDB source folder. They do not mess with your global installs at all.

We usually make things use system versions by default and only grab remote items with explicit user say-so. This is both more efficient and removes the requirement of downloading things outside people's control (and issue both for some security policies as well as machines with internet connections).

**Comment by larkost** [comment]
@marshall007 I assume that things did not work with the versions of `browserify ` and `coffeescript` you have installed. Could you give us the versions and the error message you got? Having a specific problem in front of us might help our conversation.

**Comment by marshall007** [comment]
@larkost I never actually tried running the tests with the newer versions. I've just been installing the required versions globally (since I assumed they had to be) and then reverting back to the newer versions after running the tests. This was getting annoying which is why I opened the issue. It's less important now that I understand how `--fetch` and `--allow-fetch` work.

**Comment by marshall007** [comment]
Update: the tests actually appear to run fine under `coffee-script@1.9.3` (latest). Haven't tried building the web UI under the newer versions though.

**Comment by danielmewes** [comment]
It seems like this was just a misunderstanding about what `--fetch` does. Closing.
