### ISSUE TITLE
[next]indexWait doesn't throw on missing indexes

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#4501]
It used to. I couldn't find any issue about that. Is it on purpose?
`indexStatus` still throws on missing indexes.

**Comment by danielmewes** [comment]
Thanks, I think that's a regression and not intentional.

**Comment by VeXocide** [comment]
This is in CR 3065 by @danielmewes.

**Comment by VeXocide** [comment]
Merged into `next` via commit 9874bacf8007b6d7431fdc09186eeae933ba112b.
