### ISSUE TITLE
rendering bug on Safari for new tables

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4513]
![screen shot 2015-07-07 at 3 53 54 pm](https://cloud.githubusercontent.com/assets/7431361/8559311/6ec35430-24c0-11e5-8d81-a87a5fff8628.png)
As can be seen in the screenshot above, there is a rendering issue on Safari when adding a new database. It looks like the box is not being expanded properly for the new table.

If desired I grabbed both the html and webarchive versions of this page, but can't include them in GitHub.

**Comment by deontologician** [comment]
Ok, looks like this and a few other rendering bugs are due to unprefixed flexbox. Just need to go through a couple places and add -webkit- prefixes

**Comment by deontologician** [comment]
![screen shot 2015-07-08 at 2 21 25 pm](https://cloud.githubusercontent.com/assets/1366/8582689/4748fb5e-257d-11e5-949a-4a60c2674db3.png)
