### ISSUE TITLE
webui causing nonwhitelisted messages about "/ionicons.*"

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4514]
On `next` I am getting a lot of messages like this one:
```
Someone asked for the nonwhitelisted file "/ionicons.ttf". If this should be accessible, add it to the static web assets.
```
It appears that Safari is unsuccessfully looking three variants: `/ionicons.svg`, `/ionicons.woff`, `/ionicons.ttf`

**Comment by mglukhovsky** [comment]
@deontologician: did we remove ionicons?

**Comment by deontologician** [comment]
No, we just don't use the svg font apparently. It has a woff version too which works. This is sloppy though and I need to clean it up

**Comment by deontologician** [comment]
Oh actually I just noticed it was failing on the woff file too. Not sure what's going on here since the icons work

**Comment by deontologician** [comment]
It looks like the eot file is being picked up, so that's how the icons are working.
