### ISSUE TITLE
Building packages fails: "Missing source packages in external. Please configure with '--fetch handlebars'."

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4520]
See for example this build http://dr-doom:8010/builders/package-dist/builds/156
```
mk/packaging.mk:163: *** Missing source packages in external. Please configure with '--fetch handlebars'.  Stop.
```

Looking into it.

**Comment by deontologician** [comment]
On 2.1 we should get handlebars through npm now, so it may be a left-over check for the --fetch option

**Comment by danielmewes** [comment]
@deontologician was right. Fix in CR 3066.

**Comment by danielmewes** [comment]
Fixed in `next` as of https://github.com/rethinkdb/rethinkdb/commit/310771c235f956a3e9f34d301983a3ccc90e0333
