### ISSUE TITLE
JavaScript `noReplyWait` connection test timing out on select computers

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4526]
On two computers, on current `next` I am getting a failure one two of the subtests in `connections/connection.js`, specifically:
- `connection close does not wait if we want it not to`
- `connection reconnect does not wait if we want it not to`

The subtests time out, indicating that the post-call function is not being called. I disabled the setting of `BLUEBIRD_DEBUG` so this is probably not a repeat of #4496, but it could well be related to the recent update to `bluebird`.

I have a [smaller test](https://gist.github.com/larkost/99c526c1d171caa4096e) that demonstrates this, as well as an improved version of the test that adds more stable versions of these tests as well as new versions that demonstrate this:
- `connection close noreplyWait works even with outstanding noreplyWait calls`
- `connection reconnect noreplyWait works even with outstanding noreplyWait calls`

So far this only reproduces on my two computers (home and work), and only on `next` (so not `2.0.4`). Isolating the problem I found that it only occurs in `mocha` tests where the tests is inside (at least) two levels of `describe`. This leads me to believe that this is a very narrow timing issue, and is probably going to be really nasty to debug. I do think that this is a valid problem and could reach out and bite someone.

**Comment by danielmewes** [comment]
I suspect that this might be a race condition in the driver. The test submits a query but doesn't wait until it has been sent over the wire. Then it tries to close the connection, but the `close` callback never gets called.

@deontologician could you double-check please that the logic in the driver for closing connections looks sane given these circumstances?

**Comment by deontologician** [comment]
There is a change I can make to how callbacks are added to the existing promise. I'll make the change and maybe once Karl is back he can replicate it. I was unable to replicate (as expected) on newton, even with the improved tests.

**Comment by deontologician** [comment]
Review is available in #4535

**Comment by deontologician** [comment]
Previous PR didn't fix the issue. I'll try something else in a bit.

**Comment by larkost** [comment]
A slightly improved test is in `next` with 1f07837. It separates the simultaneous `noreply` queries case from the outstanding one. However, this still only demos on my computers.

**Comment by deontologician** [comment]
Ok, I'm going to try to replicate this on the MacInShelf, hopefully I can narrow it down

**Comment by deontologician** [comment]
I narrowed down the issue, it seems that the socket is never emitting the "close" event, so the final callback is never being invoked. I've tried setting the timeout to 30s 60s, whatever and it never emits the event. Strangely, even without the previous 3 noreply queries, this will still fail on my (OS X) machine. I'm tempted to remove those from the test since they aren't necessary to surface the error.

I'm also getting some other errors in the tests, but I'm not sure which ones you expect. @larkost would you mind running the tests on your machine from branch josh/4526 ? I have a hack in there that seems to fix the issue, but I want to make sure it isn't causing other unexpected test failures.

**Comment by larkost** [comment]
I am not seeing any new errors in the JavaScrip polyglot tests from that branch on my machine.

**Comment by deontologician** [comment]
awesome, so now I just need to find out why these sockets aren't closing and whether my hack will leak file descriptors or not

**Comment by deontologician** [comment]
In CR 3114 by @larkost. It was a race-ish condition. I did not clean up the tests to be a minimal implementation exposing this issue however. I'll open a new issue to write a test to expose this bug directly, instead of indirectly as they are now.
