### ISSUE TITLE
Show per-replica disk stats in the stats table

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#4532]
Currently, in the stats table we show disk usage for every table on a server, but it's the sum for all replicas. It's reasonable to have a table be a replica for more than one shard of a table, so we should split them out if it's easy to do so.

**Comment by danielmewes** [comment]
‎That would be difficult because all replicas for a given table on a server are stored in the same file.

**Comment by deontologician** [comment]
I was worried that might be the case :/
