### ISSUE TITLE
yum install 2.1.0 beta?

### ISSUE THREAD

**Issue by nodesocket** [rethinkdb/rethinkdb#4551]
I'd love to try the **2.1.0 beta** on **CentOS 7**, is there a way to use the official yum repo to install 2.1.0 beta or do I have to use the .rpm listed at https://github.com/rethinkdb/rethinkdb/releases?

Prefer yum so I can run `yum update rethinkdb` to apply updates.

**Comment by danielmewes** [comment]
The beta packages are only available as direct downloads. We don't have a beta repository for yum at the moment.
