### ISSUE TITLE
Date/Time in Node.js

### ISSUE THREAD

**Issue by nodesocket** [rethinkdb/rethinkdb#4552]
When storing dates in RethinkDB via Node.js is using epoch milliseconds best practice if I want millisecond precision?

    obj.date = Date.now()

**Comment by chrisvariety** [comment]
I use `r.now()` which has millisecond precision: `{"$reql_type$":"TIME","epoch_time":1437323792.848,"timezone":"+00:00"}`

http://rethinkdb.com/api/javascript/now/

**Comment by danielmewes** [comment]
I think what @chrisvariety suggested is the easiest option.

**Comment by nodesocket** [comment]
Following up on this, if you want to generate timestamps in JavaScript is:

`Date.now()` the preferred method?

**Comment by nodesocket** [comment]
Do be aware, when using the http control panel and viewing with data explorer, rows using `r.now()` will show formatted like `Mon Aug 15 2016 23:35:48 GMT+00:00`

**Comment by nodesocket** [comment]
Arggg never mind, if I change from treeview to raw, it shows the correct storage type `{"$reql_type$":"TIME","epoch_time":1471304380.916,"timezone":"+00:00"}`.
