### ISSUE TITLE
redo MacOS installer art

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4555]
The behavior of the MacOS Installer.app has changed subtly and the text box is no longer translucent, but is now a solid white. This can best be seen in these two images:

**New behavior** with 10.10.4
![screen shot 2015-07-17 at 5 02 41 pm](https://cloud.githubusercontent.com/assets/7431361/8789989/4c68eda4-2efd-11e5-915c-51757846d85d.png)

**Old behavior** with 10.7
![screen shot 2015-07-20 at 12 25 35 pm](https://cloud.githubusercontent.com/assets/7431361/8790006/7ee21760-2efd-11e5-87c4-2f5fcaab9e63.png)

I don't know exactly where the behavior changed, but we should probably update our image to account for the new behavior since that is where most of our customers are going to be.

Pinging @ahruygt and @mglukhovsky.

**Comment by mglukhovsky** [comment]
@ahruygt: think we can choose a new composition that would work without the transparency?

**Comment by larkost** [comment]
Just remember that we will need to do both Retina and non-retina versions. So any artwork produced should be big enough to handle either. I can do the work of producing the combined asset (and resizing if you want).

**Comment by ahruygt** [comment]
Thanks, @larkost, I'll try a new image.  I think the old one won't work with the updated composition.

**Comment by ahruygt** [comment]
@larkost  I'd like to change it to this:
![screen shot 2015-10-26 at 2 14 45 pm](https://cloud.githubusercontent.com/assets/7118680/10742747/f42922d0-7beb-11e5-88b2-60e3d9d5783c.png)

Here's the png: https://www.dropbox.com/s/xua2v5a09931jeo/Thinker-standing-computer2.png?dl=0

**Comment by mglukhovsky** [comment]
Much better!

**Comment by larkost** [comment]
Right now I am blocked by #5017. Once that is resolved I will produce an example .pkg for that.

**Comment by larkost** [comment]
I hacked up a branch to avoid the compile error, and made a sample for @ahruygt and that got approved. Additionally the code all was approved as part of #5016, so this has been merged with `next` in 0f59e55.
