### ISSUE TITLE
Send out driver developer notes for 2.1

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4557]
Since we've already released the 2.1 beta server and drivers, we should send out the driver developer notes for 2.1 to the rethinkdb-dev group once we've decided on https://github.com/rethinkdb/rethinkdb/issues/4544.

@mlucy could you take care of this please post https://github.com/rethinkdb/rethinkdb/issues/4544 ?

**Comment by mlucy** [comment]
Will do.  Should we wait for the non-beta release or just send it out as soon as it's done?

**Comment by danielmewes** [comment]
As soon as it's done, so driver developers get a head start before the final release.

**Comment by danielmewes** [comment]
We should also mention that we now recommend turning on TCP keepalive for the client connections (https://github.com/rethinkdb/rethinkdb/issues/4572).

**Comment by danielmewes** [comment]
Just sent @mlucy's notes over the mailing list. Closing this.
