### ISSUE TITLE
Separate out drivers into their own repos

### ISSUE THREAD

**Issue by sontek** [rethinkdb/rethinkdb#4567]
I want to contribute to the Python driver but it seems very difficult to contribute since I have to clone a repo with the database itself and other drivers in it and then I can't easily find issues that are related to the driver because they are all together in one ticket tracker.

**Comment by chrisvariety** [comment]
See #1740 for some backstory on this subject.

**Comment by larkost** [comment]
And we try to label all issues for the Python driver with the [`Python` label](https://github.com/rethinkdb/rethinkdb/issues?q=is%3Aopen+is%3Aissue+label%3APython). Personally  keeping the first-party drivers in sync with the database makes my job testing a lot easier.

I am going to mark this issue as duplicate to #1740. Further conversation on this should probably go there.
