### ISSUE TITLE
[2.1-beta] Unable to view Dashboard during secondary index creation.

### ISSUE THREAD

**Issue by marshall007** [rethinkdb/rethinkdb#4568]
![screen shot 2015-07-23 at 2 37 18 pm](https://cloud.githubusercontent.com/assets/877936/8860733/5f16699a-314b-11e5-98f1-7ab6f330f246.png)

The error is not displayed, but if I open up the console I see queries failing with:

```
No attribute `index_name` in object:
{
  "db":	"data_pipeline",
  "index":	"diff_id",
  "progress":	0.15607202439164703,
  "table":	"diff_results"
}
```

**Comment by deontologician** [comment]
This is probably just adding a `.default` in this transitional case.
