### ISSUE TITLE
Add editing feature to data explorer

### ISSUE THREAD

**Issue by palango** [rethinkdb/rethinkdb#4574]
A lot of times it would be nice if I could do simple editing in the data explorer. Something like changing strings in results from queries.

Also a simple delete button would come handy from time to time.

**Comment by danielmewes** [comment]
@palango we have been thinking about that as part of https://github.com/rethinkdb/rethinkdb/issues/1592 . It's not scheduled for a specific release yet, but the feature is definitely on our list.

I'm going to close this as a duplicate, but please feel free to join the conversation in the other issue.
