### ISSUE TITLE
Confusing `rethinkdb create` behavior when specifying directory

### ISSUE THREAD

**Issue by wmrowan** [rethinkdb/rethinkdb#458]
We error if the directory we wish to create already exists and error if the directory's parent doesn't exist. Therefore both of the following fail:

```
rethinkdb create --directory servers/server_1
=> Error directory servers/ doesn't exist
mkdir -p servers/server_1
rethinkdb create --directory servers/server_1
=> Error directory server_1 already exists
```

This is confusing. I feel like I should be able to do both and not be forced to create just the parent directories.

**Comment by danielmewes** [comment]
Few people seem to care about this. Also the second command (using an existing empty directory) now works.
