### ISSUE TITLE
Can we detect non-atomic non-function arguments to update/replace?

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4582]
In http://stackoverflow.com/a/31634756/2413884 , a user suggested the following query to emulate `r.row` in an `insert:
```js
r.table('FruitStore')
.insert({
  id : 1, 
  count : r.table('FruitStore').get(1)('count').default(0).add(1) 
}, { 
  conflict : 'update'
})
```

He was probably mislead by a bad sentence in our FAQ (https://github.com/rethinkdb/docs/issues/834), but there is also another problem here:
In `update` and `replace`, we try to detect non-atomic operations by inspecting the function passed into them. However as this demonstrates, there are ways of doing a single-document update without involving a function, e.g.:
```js
// Increment a counter. This is non-atomic, but there's no error:
table.get(1).update({counter: table.get(1)('counter').add(1)})
```

The problem is that what we pass to `update` in this case is not a function.

We should try to detect such cases I think. @mlucy is this possible?
If performing the check directly is difficult, maybe we could always wrap the argument to `update` or `replace` into a function first before we evaluate it?

(This is also slightly related to https://github.com/rethinkdb/rethinkdb/issues/3700 , though the situation there is a bit different)

**Comment by danielmewes** [comment]
@mlucy A related question: In case of `update` with `non_atomic=true`, is the implicit `merge` still performed atomically? If that's not the case, could we change that easily?

**Comment by mlucy** [comment]
Checking this is easy (there's already a function for it).

How certain are we that we want to change the current behavior?  (i.e. should this be a ReQL discussion or should we just change it?)

---

The implicit `merge` is always atomic, but I'm not really sure that gives any useful guarantees.

**Comment by danielmewes** [comment]
The implicit `merge` being atomic gives guarantees like this one:
Assume a document with two fields `a` and `b`. If I run a non-atomic `update` on field `a`, then concurrent updates to field `b` can still be atomic and form a linearizable history (the update on `a` never "undoes" a change on `b`).
I think this is very useful.

Given this behavior for the `merge`, I believe
`update(some_object)` with `some_object` not being a function is equivalent to `update(some_object, non_atomic=true)`, right?

So adding this check shouldn't have any disadvantages as far as I can tell, except that a few people will have to add a `non_atomic=true` to their `update`s / `replace`s.
At the same time we have evidence that this can lead to confusion about the atomicity of operations, because (mostly due to `r.row`) we don't make it obvious when something is a function and when it is not.

I really think we should just do this. Unless you have concerns that this could have other side effects that I didn't consider, I don't think this needs a ReQL discussion. It would bring our implementation in line with what the documentation already says, and it would make it much easier to explain when an update is atomic ("everything inside the `update` command is executed atomically, unless `non_atomic=true` is given").

**Comment by danielmewes** [comment]
For e-mail readers: I edited "evidence that this can lead to confusion" -> "evidence that the current behavior can lead to confusion"

**Comment by mlucy** [comment]
This is in CR 3106 by @danielmewes .

**Comment by mlucy** [comment]
This is in next.
