### ISSUE TITLE
Many tests failing in next

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#4590]
Pinging @larkost .

The errors I saw all looked like cases where the test system was no longer matching an error message correctly for some reason.

These are the tests that are failing for me:
```
        connections/twisted_connection.py2.6
        cfeed_union.rb1.9
        polyglot/arity.rb1.9
        polyglot/changefeeds/edge.js
        polyglot/changefeeds/edge.rb1.9
        polyglot/datum/object.rb1.9
        polyglot/geo/geojson.rb1.9
        polyglot/default.rb1.9
        polyglot/control.rb1.9
        polyglot/geo/indexing.rb1.9
        polyglot/math_logic/logic.rb1.9
        polyglot/mutation/delete.rb1.9
        polyglot/mutation/sync.rb1.9
        polyglot/range.rb1.9
        polyglot/regression/4501.rb1.9
        polyglot/regression/453.rb1.9
        polyglot/regression/632.rb1.9
        polyglot/regression/578.rb1.9
        polyglot/regression/730.rb1.9
        polyglot/selection.rb1.9
        polyglot/sindex/api.rb1.9
        polyglot/transformation.rb1.9
```

**Comment by danielmewes** [comment]
@larkost looks like these are related to the message you mentioned yesterday?
```
TEST FAILURE: polyglot/default.rb1.9/17
	BODY: r.expr({})['b'].default(r.error())
	VALUE: <RqlNonExistenceError "No attribute `b` in object:">
	EXPECTED: <RqlNonExistenceError "No attribute `b` in object.">
```

**Comment by larkost** [comment]
I am already working on this, and found a whole series of problems with the test "driver"s handling of error cases (and a couple of other issues). I have Python done, and am working on JavaScript now. Ruby will be after that.

I suspect that some changes recently make us catch these cases, whereas before we were incorrectly dropping them. So far I am not finding real issues (so outside of testing issues).

**Comment by larkost** [comment]
This is now checked into `next` (41c1690) and `v2.1.x` (601c92d) after change review CR 3118.

**Comment by mlucy** [comment]
@larkost -- awesome, thanks!
