### ISSUE TITLE
Get rid of protocol buffer data structures in query processing

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4601]
@Tryneus had already started on this one.
I couldn't find an issue for this, so opening this for tracking purposes.

As a side-effect, we will discontinue support for the protocol buffer client protocol.

@larkost mentioned in https://github.com/rethinkdb/rethinkdb/issues/3664#issuecomment-126507462 that we also need to remove some protobuf tests for this.

**Comment by Tryneus** [comment]
This is up in review 3219.

**Comment by danielmewes** [comment]
:clap: :tada:

**Comment by danielcompton** [comment]
@Tryneus where are the reviews? Is that in a private review tool?

**Comment by Tryneus** [comment]
@danielcompton, yeah, it's just an internal review, and once it gets approved we'll merge it to `next`.  If you're really curious, you can check out the branch in `grey_no_term_storage` (ignore the name, it was an iterative process).

**Comment by danielcompton** [comment]
@Tryneus thanks, I was just curious what the review numbers meant.

**Comment by Tryneus** [comment]
The changes have been merged to `next` in commit 1cd2122.  Will be in release 2.2.

**Comment by danielmewes** [comment]
:clap: :tada: :-)
