### ISSUE TITLE
test that closed connections give up their file socket

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4606]
A user reported a possible problem in our JavaScript driver where connection might not be disposing of their file sockets when closed. We don't have a resolution on that yet, but regardless of how that conversation comes out we should have a test for each driver that attempts to hit the open file limit by looping over:
- open connection
- simple query (to make sure it is open)
- close connection

If we set a low resource limit on the test, then loop a few thousand times that should be enough to prove that we don't have an issue.

**Comment by haggy** [comment]
@larkost I'm the one that reported this originally. I sent more information to Jorge via email (he sent me a modified version of the JS driver). I'll ask him if he wants me to paste that into a comment here.

**Comment by haggy** [comment]
@larkost On a side note, one of the modifications to the driver was to add logging to the `rawSocket.on('close')` event in `net.js`. The interesting this is I barely see these console.log lines being executed during normal operation of our application. When I do get logs, `port` is always undefined. The rest of the time we never reach the __on close__ handler. Any thoughts?

Here is the modified code:

```
this.rawSocket.on('close', (function(_this) {
        return function() {
          var port = _this.rawSocket.localPort;
          console.log('Close connection');
          console.log(port);
          if (connections[port] !== undefined) {
            delete connections[port];
          }
          console.log('^^ Close connection');
          if (_this.isOpen()) {
            _this.close({
              noreplyWait: false
            });
          }
          return _this.emit('close');
        };
      })(this));
```

**Comment by danielmewes** [comment]
@deontologician do you have any thoughts on the behavior @haggy describes?

**Comment by larkost** [comment]
As it happens we may have just fixed this on Friday with #4526. One of our tests had been showing an issue (only on my machine) and it looked like a timing issue where `close` would not finish. @deontologician isolated it and fixed it, and it sounds very like what you are describing.

Would you mind trying out the JavaScript driver from our latest version? I can send you it in email if you can't/don't want to build it yourself (@thejsj has your email address).

**Comment by haggy** [comment]
@larkost It would be great if you could send me the driver via email. I can plug that into the app and let you know the result.

**Comment by deontologician** [comment]
It's possible this is the same bug as @larkost mentions. The end result was that sometimes a close callback wouldn't be invoked because the socket was already closed, so it was listening for an event that had already happened.

**Comment by larkost** [comment]
I forgot to comment on this, but right after this last round of comments @thejsj said he would send the driver version. @haggy did this work? The changes made have since gone out in the regular drivers.

(taking this to make sure we get resolution on it).

**Comment by larkost** [comment]
Since we don't have anything back in nearly a week I am going to assume that this is resolved. If someone finds it is still an issue please chime in and I will re-open.
