### ISSUE TITLE
How to create index for pair of every value in an array? [Question]

### ISSUE THREAD

**Issue by kureikain** [rethinkdb/rethinkdb#4610]
Let's say I have this table to represent user with a list of their favourie foods

```
{
"favfoods": [
"Edible shell" ,
"Clupeinae (Herring, Sardine, Sprat)" ,
"Deer" ,
"Perciformes (Perch-like fishes)" ,
"Bivalvia (Clam, Mussel, Oyster)"
] ,
"gender":  "m" ,
"id":  "1dd8059c-82ca-4345-9d75-eaa0f8edbf48" ,
"name":  "Arthur Hegmann"
} {
"favfoods": [
"Port wine" ,
"Crisp bread" ,
"Chewing gum" ,
"Salad dressing" ,
"Other meat product"
] ,
"gender":  "f" ,
"id":  "1f8aadbc-0569-4d0d-9561-55d655d8e9a1" ,
"name":  "Ricky Quigley Sr."
} {
"favfoods": [
"Common sage" ,
"Rye" ,
"Sesame" ,
"Broad bean" ,
"Gram bean"
] ,
"gender":  "m" ,
"id":  "3619ce33-6eb6-4bb8-9199-8a79f960e7c8" ,
"name":  "Jazmyne Brakus"
}
```

I wants to answer the question: who liked both of `Kiwi` and `Banana`. I'm thinking of create an multi index, with each of value is an pair of two elements of array. Take this

```
"favfoods": [
"Common sage" ,
"Rye" ,
"Sesame" ,
"Broad bean" ,
"Gram bean"
] 
```

I will try to create index with: [["Commont sage", "Rye"], ["Sesame", "Broad bean",], ["Rye", "Seesame"]....] 

(via using `map` function)

But I think it's very stupid. How do you guys do it ?

**Comment by danielmewes** [comment]
I'm not sure if there's a better way of doing this.
The only alternative I can think of is using a multi index on only one value and then using a `filter` to post-filter the terms. This will be faster to write, but slower to lookup obviously.

Keep in mind that there's currently a limit of 256 values per document in multi indexes. In your case it sounds like you could reach that limit quickly if someone likes more than 16 foods.
See https://github.com/rethinkdb/rethinkdb/issues/4222 for that one.

**Comment by kureikain** [comment]
Thanks @danielmewes 

I think your approach will scale better. Closing this issue out.
