### ISSUE TITLE
r.literal can be used in update but not in a branch update

### ISSUE THREAD

**Issue by gjuchault** [rethinkdb/rethinkdb#4613]
Hi,

This sample works :
```js
r.db('db').table('test').get('id').update(function (item) {
    return { foo : r.literal({}) };
});
```

Not that one :
```js
r.db('db').table('test').get('id').update(function (item) {
  return r.branch(
    true,
    { foo: r.literal({}) },
    { foo: r.literal({}) }
});
```

Error : `Stray literal keyword found: literal is only legal inside of the object passed to merge or update and cannot nest inside other literals.`
I think as literal parent node is branch; the error is thrown.
Can be done with nested branch too :
```js
r.db('db').table('test').get('id').update(function (item) {
  return r.branch(
    true,
    r.branch(
        true,
        { foo: r.literal({}) },
        { foo: r.literal({}) }
    ),
    { foo: r.literal({}) }
});
```

Which mean a recursive parent node check should be done to ensure the update function is called; before throwing because of a branch.

**Comment by danielmewes** [comment]
Thanks for opening this issue @gjuchault . I'm going to merge this into https://github.com/rethinkdb/rethinkdb/issues/4428 , which is closely related.

**Comment by danielmewes** [comment]
Also see https://github.com/rethinkdb/rethinkdb/issues/4604#issuecomment-127362173 for a work-around for your case.
