### ISSUE TITLE
Cluster with missing servers fails on import

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/rethinkdb#4617]
Details below.

**Comment by mglukhovsky** [comment]
Changed title to "Cluster with missing servers fails on import" (for email readers).

**Comment by mglukhovsky** [comment]
I was trying to import data into my RethinkDB cluster, and got an error:

```
$ rethinkdb import -d git/rethinker-dashboard/rethinkdb_export_2015-08-02T23\:18\:30/
Error: Incompatible server version found, expected >= 1.16.0
```

After checking that my server and Python driver versions were up to date, I started investigating with @AtnNn. I checked the version with Python reported in the `server_status` system table:

```python
>>> list(r.db('rethinkdb').table('server_status').run())
[{u'status': u'disconnected', u'network': {u'canonical_addresses': None, u'http_admin_port': None, u'hostname': None, u'cluster_port': None, u'reql_port': None}, u'process': {u'version': None, u'pid': None, u'cache_size_mb': None, u'argv': None, u'time_started': None}, u'connection': {u'time_connected': None, u'time_disconnected': None}, u'id': u'4ba38031-5fa8-4233-85fd-23016ea0effd', u'name': u'orpheus_local_2ky'}, {u'status': u'connected', u'network': {u'canonical_addresses': [{u'host': u'127.0.0.1', u'port': 29015}, {u'host': u'::1', u'port': 29015}], u'http_admin_port': 8080, u'hostname': u'orpheus.local', u'cluster_port': 29015, u'reql_port': 28015}, u'process': {u'version': u'rethinkdb 2.0.1 (CLANG 6.1.0 (clang-602.0.49))', u'pid': 28239, u'cache_size_mb': 369.3125, u'argv': [u'rethinkdb'], u'time_started': datetime.datetime(2015, 8, 3, 14, 37, 41, 150000, tzinfo=<rethinkdb.ast.RqlTzinfo object at 0x10813d250>)}, u'connection': {u'time_connected': datetime.datetime(2015, 8, 3, 14, 37, 41, 153000, tzinfo=<rethinkdb.ast.RqlTzinfo object at 0x10813df50>), u'time_disconnected': None}, u'id': u'e1e5b00e-88cb-42fd-a816-1c6f34dc8fda', u'name': u'orpheus_local_f3l'}]
```

After being very confused as to why my server version was being reported as `None`, I realized that I'd left a demo cluster in a bad state. One of my servers had been disconnected, and I hadn't permanently removed it. The import script was looking for the first server in the system table, which happened to be the missing server, so the import script failed the version check (since it was `None`).

Permanently removing the server fixed the issue. My thoughts:

- The import script should either refuse to import data if the cluster is in a bad state, return an error if there is a missing server, or keep looking for servers in the list until it finds one that reports a version other than `None`.
- It would be supremely useful if there was a ReQL command for finding the specific server the driver is connected to via ReQL (which we had at one point with `ajax/me`, some discussion in #4617). I'll open an issue for this separately.

**Comment by danielmewes** [comment]
I think we should fix this in 2.1 by adding a filter to the `server_status` query.
Then later when we have #3934 we can do a second pass on this.

**Comment by danielmewes** [comment]
Actually never mind. This can't happen in 2.1 anymore.
Putting this into `backlog`. We should change the code eventually when we have #3934, in case we want to support mixed-version clusters in the future.

**Comment by gabor-boros** [comment]
@srh as far as I remember mixed clusters are not supported. Can we close this issue? (If this is not supported for more than 5 years I believe it will be not introduced in the near future)

**Comment by srh** [comment]
Yeah, you'll want to keep mixed-version clusters out of scope.
