### ISSUE TITLE
Proposal: ReQL command to find which server the driver connected to

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/rethinkdb#4618]
As mentioned in #4617, there isn't a way for the driver to find out which server it's connected to. This would be most useful for the `rethinkdb import` command, and for the web UI (which used to rely on `ajax/me`.

**Comment by VeXocide** [comment]
This is probably a duplicate of #3934.

**Comment by mglukhovsky** [comment]
Agreed, closing.
