### ISSUE TITLE
High memory consumption on OS X

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4619]
@indiedotkim ran into this:
https://groups.google.com/forum/#!topic/rethinkdb/-wl6i00XuDA

I could reproduce this with our RethinkDB 2.0.4 DMG . Importing about a GB of data easily brought the server's memory consumption above 1.3 GB, despite me setting the cache size to just 100 MB.

However, strangely, `v2.0.4` compiled from source on `gantz` does *not* exhibit this behavior and memory usage is as expected (below 600 MB).

**Comment by danielmewes** [comment]
The manual compile was on gantz. I will try this on the shadow next, which we also use to create the dmg file.

**Comment by mlucy** [comment]
Are we using the same malloc building from source and in the release build?

**Comment by danielmewes** [comment]
Theoretically yes. On Mac we always use the default allocator that comes with the system.

**Comment by danielmewes** [comment]
I could reproduce this with `v2.0.4` compiled on `the-shadow` (an older Mac with OS X 10.4).
However I was not able to reproduce it with `next` compiled on `the-shadow`.

I'm not aware of any significant change between those versions that would affect this. Wonder if it might be a compiler error in the older compiler. Needs more investigation...

**Comment by larkost** [comment]
Minro correction: `the-shadow` is running MacOS X 10.7.5, which is our minimum requirement on MacOS. I wouldn't bet that we would work with 10.4.

**Comment by danielmewes** [comment]
Oops I was mixing that with the Darwin version (11.4). Thanks for the correction @larkost .

**Comment by danielmewes** [comment]
Instruments' allocation profiler doesn't show anything that's using the memory. It shows the amount of allocated memory at a reasonable level, while at the same time the rethinkdb process is using much more memory in reality. This looks to be something on the system / allocator level, but I'm not sure what it is.
I also have no theory yet as to why it looks to be working ok with RethinkDB 2.1 / `next`.

**Comment by danielmewes** [comment]
Moving to `2.0.x`. This isn't critical for 2.1 because for some odd reason `next` doesn't appear to be affected by this.

It is kind of scary though that this can happen, and I think we should do https://github.com/rethinkdb/rethinkdb/issues/2230 soon to avoid potential bugs in the older compiler (if this is indeed a compiler bug).

**Comment by danielmewes** [comment]
This has disappeared in 2.1. The mid-term solution is probably #2230. Closing as outdated.
