### ISSUE TITLE
In admin CLI allow pinning when table's primary datacenter is universe

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#462]
1. Create a cluster of multiple machines (no datacenters, or add datacenters, should be irrelevant)
2. Create a table. Don't set a primary datacenter
3. Set multiple replicas in universe
4. Access admin cli and try to pin one of the shard's masters

Current behavior: the system says you can't pin masters because it's not in the table's primary datacenter

Expected behavior: allow pinning because when the table is in universe the user should be able to pin anywhere.

This is low priority, so leaving in backlog until this matters to someone.

**Comment by Tryneus** [comment]
Closing this - the admin CLI is going away with 1.16, as well as datacenters.
