### ISSUE TITLE
Add a function to driver to get outgoing port

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4620]
See the comment here https://github.com/rethinkdb/rethinkdb/issues/544#issuecomment-127435975

It might be useful to add a method to the connection objects that returns the outgoing IP port. This is probably a pretty simple client-side addition.

**Comment by danielmewes** [comment]
We should probably expose the client's IP address as well, so that the client can be uniquely identified in the `jobs` table without additional information.

**Comment by marshall007** [comment]
Long-term (possibly as part of #4519) I think it would be simpler to receive a `client_id` generated by the server and use that to filter the `jobs` table, but filtering by `client_port`/`client_address` will work for now.

**Comment by danielmewes** [comment]
@marshall007 That makes sense. I agree that that would be better long-term.

**Comment by marshall007** [comment]
@danielmewes does this information already come back as part of the response in the initial handshake or will it require server-side changes? I didn't see any existing reference to a `port` or `host` in the drivers other than the ones used to initially connect to RethinkDB.

**Comment by danielmewes** [comment]
@marshall007 the outgoing port shouldn't require any server changes. What I meant was just the TCP port that the operating system on the client picks randomly when it opens the connection to the server.
It's usually possible to get this from the socket object.

In node.js I think the `localPort()` method should return it: https://nodejs.org/api/net.html#net_socket_localport

**Comment by marshall007** [comment]
@danielmewes ah, thanks. Got a PR up!

**Comment by marshall007** [comment]
I opened #4820 to track the simplified `client_id` proposal and the possibility of exposing client info as a ReQL term `r.client`.

**Comment by danielmewes** [comment]
This was merged via https://github.com/rethinkdb/rethinkdb/pull/4796
