### ISSUE TITLE
Rethinkdb starts sending responses to queries in an async for loop only after all the queries have finished executing on server side

### ISSUE THREAD

**Issue by kulbirsaini** [rethinkdb/rethinkdb#4623]
I have the following code which uses JavaScript driver for Rethinkdb.

```javascript
var r = require('rethinkdb');

function printCount(i, connection) {
  r.db('pytwitter').table('tweets').count().run(connection, function(error, data){
    console.log(new Date(), i, 'Error:', error, 'Data:', data);
    connection.close();
  });
}

function connectAndPrint(i) {
  r.connect({ host: 'localhost', port: 28015 }, function(error, conn) {
    printCount(i, conn, true);
  });
}

console.log(new Date(), "Started");
for (var i = 0; i < 10; i++) {
  connectAndPrint(i);
}
```

Results when running only for one iteration
```bash
Tue Aug 04 2015 20:53:43 GMT+0530 (IST) 'Started'
Tue Aug 04 2015 20:53:44 GMT+0530 (IST) 0 'Error:' null 'Data:' 1432098
```
Time taken is roughly one second for executing and returning the data.

Now, results with 10 iterations.
```bash
Tue Aug 04 2015 20:53:49 GMT+0530 (IST) 'Started'
Tue Aug 04 2015 20:53:56 GMT+0530 (IST) 0 'Error:' null 'Data:' 1432098
Tue Aug 04 2015 20:53:56 GMT+0530 (IST) 4 'Error:' null 'Data:' 1432098
Tue Aug 04 2015 20:53:56 GMT+0530 (IST) 3 'Error:' null 'Data:' 1432098
Tue Aug 04 2015 20:53:56 GMT+0530 (IST) 8 'Error:' null 'Data:' 1432098
Tue Aug 04 2015 20:53:56 GMT+0530 (IST) 7 'Error:' null 'Data:' 1432098
Tue Aug 04 2015 20:53:56 GMT+0530 (IST) 2 'Error:' null 'Data:' 1432098
Tue Aug 04 2015 20:53:56 GMT+0530 (IST) 1 'Error:' null 'Data:' 1432098
Tue Aug 04 2015 20:53:56 GMT+0530 (IST) 6 'Error:' null 'Data:' 1432098
Tue Aug 04 2015 20:53:56 GMT+0530 (IST) 5 'Error:' null 'Data:' 1432098
Tue Aug 04 2015 20:53:56 GMT+0530 (IST) 9 'Error:' null 'Data:' 1432098
```
Note the 7 seconds delay in returning the first result. And then all the results are with us within the same second.

![Cluster Performance Graph](https://cloud.githubusercontent.com/assets/127315/9064742/8bdb3d62-3aeb-11e5-964f-f8d9781dae7e.png)

I am running `rethinkdb 2.0.4~0trusty` (GCC 4.8.2) on `Linux 3.13.0-37-generic x86_64` (Linux Mint 17). Table tweets has 1.4M documents (tweets fetched from twitter but no nested entities/users. Only top level fields within an object).

Also, I am running two instances of Rethinkdb on the same machine and table has 2 shards and two replicas (I know it doesn't make sense to run two instances on same machine but that's unrelated to the issue at hand).

Also note that I am new to `node.js` and it's pretty possible that I have written bad code but googling for the same/related issue left me wondering why no one wrote a similar bad example ever.

**Comment by danielmewes** [comment]
Hi @kulbirsaini, there might still be something wrong wrong here, but this isn't necessarily unexpected.

If you start 10 equivalent queries all at exactly the same time, I would expect them to finish at close to the same time as well. All of the queries have the same priority to the server, so it doesn't have any reason to favor one over the other.

Since the server is under higher load, the individual queries also take longer. I think that's also expected.

Does that make sense?

I think if you use more different queries, you'll find that they do return at different times as well.

**Comment by kulbirsaini** [comment]
@danielmewes makes perfect sense to me now. I was thinking that the first query will get the count real quick since the reads were around 2M/sec but I overlooked the part that the graph is showing total reads/sec which is a sum of reads performed via all the connections. 

I introduced another count and it does return them quicker.

```bash
Wed Aug 05 2015 01:06:19 GMT+0530 (IST) 'Started'
Wed Aug 05 2015 01:06:21 GMT+0530 (IST) 0 'Table:' 'users' 'Error:' null 'Data:' 297821
Wed Aug 05 2015 01:06:21 GMT+0530 (IST) 4 'Table:' 'users' 'Error:' null 'Data:' 297821
Wed Aug 05 2015 01:06:21 GMT+0530 (IST) 2 'Table:' 'users' 'Error:' null 'Data:' 297821
Wed Aug 05 2015 01:06:21 GMT+0530 (IST) 8 'Table:' 'users' 'Error:' null 'Data:' 297821
Wed Aug 05 2015 01:06:21 GMT+0530 (IST) 6 'Table:' 'users' 'Error:' null 'Data:' 297821
Wed Aug 05 2015 01:06:23 GMT+0530 (IST) 3 'Table:' 'tweets' 'Error:' null 'Data:' 1432098
Wed Aug 05 2015 01:06:23 GMT+0530 (IST) 1 'Table:' 'tweets' 'Error:' null 'Data:' 1432098
Wed Aug 05 2015 01:06:23 GMT+0530 (IST) 5 'Table:' 'tweets' 'Error:' null 'Data:' 1432098
Wed Aug 05 2015 01:06:23 GMT+0530 (IST) 7 'Table:' 'tweets' 'Error:' null 'Data:' 1432098
Wed Aug 05 2015 01:06:23 GMT+0530 (IST) 9 'Table:' 'tweets' 'Error:' null 'Data:' 1432098
```

Thanks for your time. Closing this.
