### ISSUE TITLE
JS driver doesn't always appear to attach error types to exceptions correctly

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#4631]
See @larkost's comment in https://github.com/rethinkdb/rethinkdb/issues/4559#issuecomment-127772888 .  The `polyglot/changefeeds/edge.js` test is failing in `next`, and from looking at it quickly it seems like a bug in the JS driver.

@deontologician, any idea what might be causing this?

**Comment by deontologician** [comment]
I don't know, but I'll take a look at it, it's probably something simple

**Comment by deontologician** [comment]
up in CR 3123 by @larkost
