### ISSUE TITLE
Converting date string to date object and updating the document

### ISSUE THREAD

**Issue by jamhall** [rethinkdb/rethinkdb#4632]
Hello,

I've gone through all of the docs, but I can't seem to find an easy way to do what I want to do. I have imported a CSV into a table.

An example of a record:

```
{
"humidity":  "75.1" ,
"id":  "000362a9-0812-4a03-98ce-c46f84aa8da2" ,
"temperature":  "2.604" ,
"time":  "2014-02-11 06:23" ,
"windspeed":  "3.646"
}
```

Converting the numbers(temperature, windspeed, humidity) is easy:
```
r.table('weather').update(function(doc) {
    return doc.merge({
        temperature: doc('temperature').coerceTo('number'),
        windspeed: doc('windspeed').coerceTo('number'),
        humidity: doc('humidity').coerceTo('number')
    })
});
```
However, converting the date is the dfficult part...

I've tried doing (in the web interface):

```
r.table('weather').update(r.js('(function (point)  { var  t = point("time").split(/[- :]/); return point.merge({ time: new Date(t[0], t[1]-1, t[2], t[3], t[4]); }) })') , { nonAtomic: true});

```
That throws an error:

``` 
"first_error":  "TypeError: object is not a function" 
```

I've also tried:

```
r.table('weather').update({ time: r.js('(function (point)  { var  t = point("time").split(/[- :]/); return new Date(t[0], t[1]-1, t[2], t[3], t[4]) })') }, { nonAtomic: true});
```

That also throws an error:

```
"Expected type DATUM but found FUNCTION:
VALUE FUNCTION
```

Surely there must be another way to easily convert typical (YYYY-MM-DD H:I) date strings into date objects?

Perhaps it's trivial...

Thank you!

Great database btw!

**Comment by danielmewes** [comment]
Hi @jamhall, for creating a ReQL time object, you cannot use `new Date` inside of an `r.js` function unfortunately.

Here's a (unfortunately somewhat lengthy) alternative that relies on `r.js` only for the string splitting:

```js
r.table('weather')
 .update(function (oldRow) {
   return { time: oldRow.do(r.js('(function (point) { return point.time.split(/[- :]/); })'))
                        .do(function (splits) {
                          return r.time(splits(0).coerceTo('number'),
                                        splits(1).coerceTo('number'),
                                        splits(2).coerceTo('number'),
                                        splits(3).coerceTo('number'),
                                        splits(4).coerceTo('number'),
                                        0,
                                        "Z");
                        })
     };
 }, { nonAtomic: true })
```

If you want to, you could do the splitting in ReQL without `r.js` as well. using the http://rethinkdb.com/api/javascript/match/ `match` command (ReQL's `split` doesn't support a regex yet).

**Comment by danielmewes** [comment]
If you want to subtract 1 from the month, simply replace
`splits(1).coerceTo('number')` by `splits(1).coerceTo('number').sub(1)`.

**Comment by mlucy** [comment]
Here's another way you could do it:
```js
r.table('weather').update(function(row) {
  return {time: row('time').split().do(function(arr) {
    return r.ISO8601(r.add(arr[0], 'T', arr[1]), {defaultTimezone: '+00:00'});
  });
});
```

**Comment by jamhall** [comment]
Hello @danielmewes, @mlucy. Thank you for your answers. Much appreciated! Are there any plans to make this simpler? I would image it's quite a common problem for a lot of people. 

When I say simpler, in Mongo, I would just do: 
```
db.datapoints.find().forEach(function(doc){
    doc.time = new ISODate(doc.time);
    db.datapoints.save(doc)});
})
```

It would be awesome if you had something like this:
```
doc('time').coerceTo('date').fromFormat('YYYY/MM/DD HH:mm:ss')
```

Anyway, just my two cents...

Thanks!

**Comment by danielmewes** [comment]
Yes, https://github.com/rethinkdb/rethinkdb/issues/3387. It's not scheduled yet, but it's on our list.
