### ISSUE TITLE
improve changefeed docs to have examples/info about errors

### ISSUE THREAD

**Issue by ha1331** [rethinkdb/rethinkdb#4637]
I didn't find too much about error handling with changes() from the documentation. Also it might be good idea to explain what conditions should be met for the feeds to keep working and how to handle errors. by conditions I mean you can loose feed if any of the primaries go down or the server you connected goes down.

**Comment by ha1331** [comment]
this post is from the user who I talked with at #rethinkdb before I filed this issue and it contains more information/ideas for improvements : https://groups.google.com/forum/#!topic/rethinkdb/7n_lBN6CKoM

**Comment by danielmewes** [comment]
Sounds like a good idea. Pinging @chipotle 
We currently lose a changefeed in the scenarios you mention and also if a tables is rebalanced / reconfigured, if the network connection between two relevant servers in the cluster is lost, or if the network connection between the client and the server is lost.

**Comment by danielmewes** [comment]
Sorry I forgot about this. Moved to https://github.com/rethinkdb/docs/issues/1009
