### ISSUE TITLE
Discuss name-based UUID proposal from #4636

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4639]
Making this an issue because Github by default doesn't show PRs when looking for ReQL_proposal issues.

Please discuss in: https://github.com/rethinkdb/rethinkdb/pull/4636

**Comment by deontologician** [comment]
:+1: It's backwards compatible and is straightforward and easy to understand and use

**Comment by danielmewes** [comment]
I like it too. :+1:

**Comment by coffeemug** [comment]
:+1:

**Comment by coffeemug** [comment]
Deleted my upvote, as I have a slightly more nuanced opinion. Will post in the PR.

**Comment by mlucy** [comment]
I like it as well.

**Comment by danielmewes** [comment]
Settled as implemented in the PR. Since we're out of the discussion period, I'm going to close this issue in favor of https://github.com/rethinkdb/rethinkdb/pull/4636 .
