### ISSUE TITLE
Calling filter/map after changes causes connection to timeout

### ISSUE THREAD

**Issue by let4be** [rethinkdb/rethinkdb#4642]
I'd like to filter and map changes to a more simplified structures to reduce network loading and increase efficiency

but as soon as I chain `.filter()` / `.map()` after `.changes()` my connection starts to timeout(10 second as I specified during creating a connection)

Sorry if this is duplicate, but I found only this:
https://github.com/rethinkdb/rethinkdb/issues/2485

I also saw this one for the .NET driver so gorethink might have a similar issue
https://github.com/mfenniak/rethinkdb-net/issues/193
If this is the case, sorry for disturbing

Thanks!

**Comment by let4be** [comment]
I can't reproduce the same inside data explorer but on the other hand it has no timeout setting or it's hidden somewhere

`r.table('batches').changes().filter(r.row.hasFields('new_val'))`

the following works perfectly fine in data explorer but timeouts in gorethink if connection timeout is specified...

**Comment by danielmewes** [comment]
Hi @let4be. The timeout behavior seems to be specific to the Go driver. Our official drivers don't have any timeout like that, except for the first handshake during connection setup.

I suspect that the solution for this is simply to disable the timeout.

@dancannon do you have any additional insights on this?

**Comment by dancannon** [comment]
Hi, currently the driver has a global timeout setting which is used for both connecting and queries. I think that having timeouts on queries makes sense but clearly it needs to be possible to ignore this for changefeeds. I will look into adding this soon.

For now I think @danielmewes is correct in saying that removing the timeout for now is the best solution.
