### ISSUE TITLE
Unit tests with temporary files

### ISSUE THREAD

**Issue by jdoliner** [rethinkdb/rethinkdb#466]
Right now we have several unittests that need to have the temporary directory created but don't actually create it. The temporary directory is needed primarily for disk backed queues which are used for backfilling (among) other things. These unittests would be fail except for the fact that our disk backed queues buffer a small amount of data in memory before going to disk and our unittests are small enough that they never actually go to disk.

Before closing this issue make sure that:
- unittests that use disk backed queues actually write to them enough that they go to disk
- The unittests create their directories and thus pass.

**Comment by srh** [comment]
I believe they do go to disk.  Closing.
