### ISSUE TITLE
OS X installer release notes URL is wrong for 2.1.0

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4662]
It links to https://github.com/rethinkdb/rethinkdb/releases/tag/v2.1.0 , but the right URL is https://github.com/rethinkdb/rethinkdb/releases/tag/v2.1.0-1 (note the -1)

**Comment by danielmewes** [comment]
This is no longer a problem with the 2.1.1 release, but we should still fix the installer for the future.

**Comment by larkost** [comment]
This has been fixed in `next` with 46ef6512 and `v2.1.x` in 9a9d9938
