### ISSUE TITLE
--migrate-inconsistent-data option still appears in --help output

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4665]
This option doesn't do anything, but we still print it in 2.1.0.

**Comment by Tryneus** [comment]
Fix is up in review 3142.

**Comment by Tryneus** [comment]
Fix has been approved and merged into `next` in commit a0b3e02, and cherry-picked into `v2.1.x` in commit 8c702d2.  Will be in release 2.1.1.
