### ISSUE TITLE
Celluloid::IO Support

### ISSUE THREAD

**Issue by digitalextremist** [rethinkdb/rethinkdb#4666]
As asked on Twitter: https://twitter.com/_de/status/631172559300485120

Was there any energy put into a `Celluloid::IO` based driver?

If not, what about collaborating on such a driver? There is `celluloid-redis` for example:
- https://github.com/celluloid/celluloid-redis

This adds "evented" IO to that highly-popular database. That's much more powerful than just adding `async` capabilities to the underlying database.

People using `0MQ` benefit from using `celluloid-zmq`, which also uses `Celluloid::IO` ... making those sockets "evented" also. Same for people using `Reel` or `sidekiq` ... `Celluloid` is available to the application already. Adding `Celluloid::IO` and engaging it for RethinkDB makes sense.

It would be cool to have [`celluloid-rethinkdb`](https://github.com/celluloid/celluloid-zmq) and have the underlying Ruby driver not use `EventMachine` by default... but only if alternative concurrency management frameworks are not already in use. As I reconsider MongoDB for my own systems, I could see collaborating on a RethinkDB driver if someone is interested in co-developing this in `Celluloid::IO`, but the `EventMachine` focused pieces of the existing Ruby driver would need to be spun off to another gem that is only installed if another concurrency management framework driver like it, is not there.

I've created a repository to start doing this, if someone from here would like to cooperate in developing it, as I am not familiar with RethinkDB:

https://github.com/celluloid/celluloid-rethinkdb

**Comment by nviennot** [comment]
All we need is to use a celluloid compatible blocking primitive like `Celluloid::Condition` when waiting for results. This would be easy to do if the blocking logic was abstracted away (see  https://github.com/rethinkdb/rethinkdb/issues/4630#issuecomment-128055788 for more info).

**Comment by danielmewes** [comment]
We haven't put any energy into one yet. Thanks for bringing it onto our radar.
@nviennot's suggestion might be the best way to abstract our driver for different backend, though I don't understand the details of this very well. @mlucy probably has a better idea of this.

If you want to develop your own driver port, we're happy to help if you run into any questions or issues.

**Comment by digitalextremist** [comment]
Right on, thanks to you both.

There is interest in trying `RethinkDB` around some of the people I know, and I intend to try it also. When I do, I will expect to write a driver port at `celluloid-rethinkdb` unless one is already done.

**Comment by nviennot** [comment]
@danielmewes The high level idea is:

1) The regular `run()` method would be a wrapper for `async_run().wait()`. (it's easy to make something async synchronous, but the opposite is not true). This way the driver does not carry both an async and sync implementations.

2) To implement the asynchronous part, have backend-defined callbacks. They can call whatever is appropriate. (e.g. on_stream_val() would call an EventMachine callback, or would signal a cursor to  wakeup any callers).

3) Synchronous blocking can happen at two levels: i) getting the initial response from the server by calling `wait()` on the result of `async_run()`. ii) getting the next batch of items when iterating on a cursor. How blocking should be done is left to the backend implementation. To simplify backend implementations, we can require the primitive of a blocking queue (that implements push and pop). This way we can implement both i) and ii) with it. For the Regular backend, we can use a regular ruby Queue. For eventmachine + fibers, we can use EventMachine::Queue. For Celluloid, we might want to use a regular actor and use its mailbox as a queue.

I hope this clarifies.

**Comment by digitalextremist** [comment]
@danielmewes having read your comment on the other issue you linked, I see the change you would like to make, and completely agree with your proposal. I deal with asynchronous operations all the time maintaining `Celluloid`, and your handling of that mode is appropriate to the domain.

I would need to try some things however, to see if a `Condition` is the best way, or if it is not instead better for `Future` to be used. But either one would be supported by the upcoming `Multiplexer` feature set ( https://github.com/celluloid/celluloid/issues/632 )

**Comment by jf** [comment]
+1!!! Really looking forward to being able to handle rethinkdb using Celluloid!

**Comment by digitalextremist** [comment]
This might not be the most awesome idea to pure `RethinkDB` enthusiasts, but I decided to do an abstraction layer instead, and provide 'evented' I/O to several NoSQL database drivers by adding `Celluloid::IO` support to the abstraction layer itself, starting with `RethinkDB`:

https://github.com/abstractive/nada

**Comment by thelinuxlich** [comment]
@srh the latest Celluloid stable release is from 2016...I don't think this is a valid issue anymore

**Comment by srh** [comment]
The latest Rethinkdb stable release is from 2017...

Anyway, if somebody wants this, nothing's stopping them from working on the driver or forking it.
