### ISSUE TITLE
Incorrect error for `db.table()`

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4667]
The Python and Ruby drivers are reporting a `ReqlQueryLogicError` error for `r.db('test').table().run(conn)` rather than the more expected `RqlCompileError`. Other, similar, problems return the expected error (e.g.: `r.db('test').table('test').insert()`).

This can be seen in `./test/rql_test/test-runner polyglot/arity`

JavaScript is reporting a `ReqlDriverError` which will be the subject of another bug.

**Comment by mlucy** [comment]
I think that this is intended (if slightly confusing) behavior.  From the server's perspective, `r.db('test').table()` is indistinguishable from `r.table(r.db('test'))`.  It produces a logic error because it thinks you tried to write `r.table('test')` or something but accidentally provided a database instead of a string.

**Comment by larkost** [comment]
I don't think that this should make it to the server, since we always need a table. And I suspect that it is not reaching there as the error message is `Expected 2 arguments but found 1.`, and I am not finding the constant part of that string in `src/`

**Comment by mlucy** [comment]
Ah, probably differs by driver.  Here's the error I see in Ruby:
```rb
irb(main):008:0> r.db('test').table().run
RethinkDB::RqlLogicError: Expected type DATUM but found DATABASE:
```

**Comment by danielmewes** [comment]
Even though it would make the error clearer in this particular case, I think we should be careful about adding more knowledge about the number of allowed arguments to the drivers than absolutely necessary. It increases the maintenance burden whenever we change the signature of a term, and makes it harder for users running older drivers to make access new server features.

**Comment by danielmewes** [comment]
In the case of `r.table` the likelihood of the term changing is probably really small. So I would be ok with making an exception for this. It's probably not worth adding special code to the Ruby driver if this isn't already possible though. @mlucy Is it easy to specify the expected number of arguments in the Ruby driver?

**Comment by mlucy** [comment]
@danielmewes -- it's not that hard, but it isn't done for any other terms (except maybe one or two that are weird enough they're just done totally custom).

I think @larkost was saying that the error was different in one of the other drivers though, in a way that was more confusing.  (Unless I misunderstood.)

**Comment by danielmewes** [comment]
I think this isn't worth changing. I'm going to change the `arity` test to differentiate the different drivers' behaviors as part of #4669.
