### ISSUE TITLE
Migration generates timestamps that are too high for inactive tables

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4668]
The timestamp is set to `9223372036854775808`. 
The effect this has is that if you add a new replica to a table after migration, that replica will never come up because its timestamp is always going to be higher than any other timestamp.

There might be a second problem here that inactive tables do not synchronize their states correctly.

Once this is fixed, we're going to ship a 2.1.1 point release asap.

**Comment by Tryneus** [comment]
Workaround for the invalid timestamp is up in review 3146.  We still need to handle the case of an inactive replica having a higher timestamp than all active replicas in the cluster.  Also, we should create an issue to remove the workaround (and rewrite all invalid timestamps in the metadata) in v2.2.x.

**Comment by Tryneus** [comment]
The workaround for the invalid timestamp has been approved and merged into `next` in commit 1b1efa9, and cherry-picked into `v2.1.x` in commit bd785e8.  Will be in release 2.1.1.

**Comment by danielmewes** [comment]
A second work-around to handle the case of an inactive server having a higher timestamp is now in `next` 678f8801f565f06d3e3a9947b052f6d465564705 and in `v2.1.x` df27878967e70a4c30ff040ef63c7deddf68f949. The code review for this was 3148.

This solution is temporary as well, but a cleaner solution is considerably more work and needs additional though. We will probably replace that code by a different logic in 2.2.
