### ISSUE TITLE
Javascript driver error after upgrading

### ISSUE THREAD

**Issue by Timer** [rethinkdb/rethinkdb#4676]
```
  SyntaxError: Unexpected token   
      at Object.parse (native) 
      at TcpConnection.Connection._data (/app/node_modules/rethinkdb/net.js:117:23) 
      at Socket.<anonymous> (/app/node_modules/rethinkdb/net.js:509:32) 
      at emitOne (events.js:77:13) 
      at Socket.emit (events.js:169:7) 
      at readableAddChunk (_stream_readable.js:146:16) 
      at Socket.Readable.push (_stream_readable.js:110:10) 
      at TCP.onread (net.js:521:20) 
```

**Comment by Timer** [comment]
Server(s) are RethinkDB 2.1.0-1, driver version 
```
├─┬ rethinkdb@2.1.0
│ └── bluebird@2.9.34
```

**Comment by danielmewes** [comment]
Thanks for the report @Timer .

I recommend downgrading to the 2.0 driver until we've figured this out.
```
npm install rethinkdb@2.0.2
```

@deontologician any ideas?

**Comment by Timer** [comment]
I've already started using the new table functionality and floor functions, I think I'll try to ride it out.

**Comment by danielmewes** [comment]
@Timer Oh so this doesn't happen all the time? Does it always happen for a specific query?

Is there a way you could get the result of that query by using some other client? I wonder if the server is sending the driver illegal JSON or something like that.

**Comment by Timer** [comment]
@danielmewes Not sure really, it's on my production servers so I'm trying to debug it...

**Comment by Timer** [comment]
The response looks something like ...
```
{"t":1,"r":[23818],"n":[]}{"t":1,"r":[false],"n":[]}{"t":1,"r":[0],"n":[]}�{"t":1,"r":[[{"buy_in":68,"id":"4ad69f24-f9cf-4271-a692-29824f24e12e","players":["e78861f8-693f-42f2-abe3-ef80554421be"],"seats":2,"state":"seating"}]],"n":[]}{"t":1,"r":[{}],"n":[]}�{"t":1,"r":[[{"action_timeout":15,"id":"7a4f7520-48fb-4d83-87aa-73e55c7fbb32","players":[],"seats":6,"start_after":10,"state":"seating"},{"action_timeout":30,"buy_ins":{"f4f182ec-b121-4dbd-8c5e-f91685e40912":"5"},"id":"1bf6edd8-a876-4f89-932b-ffbb327975a1","players":[],"seats":2,"start_after":10,"state":"seating"},{"action_timeout":120,"id":"41d17d93-2252-4206-acbc-f31f6eef8949","players":[],"seats":1,"start_after":0,"state":"seating"},{"action_timeout":120,"id":"2bbe4a54-9618-44c8-9583-d73606b42588","players":[],"seats":1,"start_after":0,"state":"seating"},{"action_timeout":120,"id":"5fb9cd6c-19e9-4307-a7db-2f90fe7514f8","players":[],"seats":1,"start_after":0,"state":"seating"}]],"n":[]�{"t":1,"r":[[{"buy_in":68,"id":"4ad69f24-f9cf-4271-a692-29824f24e12e","players":["e78861f8-693f-42f2-abe3-ef80554421be"],"seats":2,"state":"seating"}]],"n":[]}{"t":1,"r":[true],"n":[]}�{"t":1,"r":[[{"action_timeout":15,"id":"7a4f7520-48fb-4d83-87aa-73e55c7fbb32","players":[],"seats":6,"start_after":10,"state":"seating"},{"action_timeout":30,"buy_ins":{"f4f182ec-b121-4dbd-8c5e-f91685e40912":"5"},"id":"1bf6edd8-a876-4f89-932b-ffbb327975a1","players":[],"seats":2,"start_after":10,"state":"seating"},{"action_timeout":120,"id":"41d17d93-2252-4206-acbc-f31f6eef8949","players":[],"seats":1,"start_after":0,"state":"seating"},{"action_timeout":120,"id":"2bbe4a54-9618-44c8-9583-d73606b42588","players":[],"seats":1,"start_after":0,"state":"seating"},{"action_timeout":120,"id":"5fb9cd6c-19e9-4307-a7db-2f90fe7514f8","players":[],"seats":1,"start_after":0,"state":"seating"}]],"n":[]}{"t":1,"r":[{}],"n":[]}�{"t":1,"r":[[{"buy_in":68,"id":"4ad69f24-f9cf-4271-a692-29824f24e12e","players":["e78861f8-693f-42f2-abe3-ef80554421be"],"seats":2,"state":"seating"}]],"n":[]}�{"t":1,"r":[[{"buy_in":68,"id":"4ad69f24-f9cf-4271-a692-29824f24e12e","players":["e78861f8-693f-42f2-abe3-ef80554421be"],"seats":2,"state":"seating"}]],"n":[]}{"t":1,"r":[{}],"n":[]}�{"t":1,"r":[[{"buy_in":68,"id":"4ad69f24-f9cf-4271-a692-29824f24e12e","players":["e78861f8-693f-42f2-abe3-ef80554421be"],"seats":2,"state":"seating"}]],"n":[]}�{"t":1,"r":[[{"action_timeout":15,"id":"7a4f7520-48fb-4d83-87aa-73e55c7fbb32","players":[],"seats":6,"start_after":10,"state":"seating"},{"action_timeout":30,"buy_ins":{"f4f182ec-b121-4dbd-8c5e-f91685e40912":"5"},"id":"1bf6edd8-a876-4f89-932b-ffbb327975a1","players":[],"seats":2,"start_after":10,"state":"seating"},{"action_timeout":120,"id":"41d17d93-2252-4206-acbc-f31f6eef8949","players":[],"seats":1,"start_after":0,"state":"seating"},{"action_timeout":120,"id":"2bbe4a54-9618-44c8-9583-d73606b42588","players":[],"seats":1,"start_after":0,"state":"seating"},{"action_timeout":120,"id":"5fb9cd6c-19e9-4307-a7db-2f90fe7514f8","players":[],"seats":1,"start_after":0,"state":"seating"}]],"n":[]}{"t":1,"r":[{}],"n":[]}{"t":1,"r":[{}],"n":[]}{"t":1,"r":[{}],"n":[]}{"t":1,"r":[{}],"n":[]}{"t":1,"r":[{}],"n":[]}�{"t":1,"r":[[{"buy_in":68,"id":"4ad69f24-f9cf-4271-a692-29824f24e12e","players":["e78861f8-693f-42f2-abe3-ef80554421be"],"seats":2,"state":"seating"}]],"n":[]}�{"t":1,"r":[[{"action_timeout":15,"id":"7a4f7520-48fb-4d83-87aa-73e55c7fbb32","players":[],"seats":6,"start_after":10,"state":"seating"},{"action_timeout":30,"buy_ins":{"f4f182ec-b121-4dbd-8c5e-f91685e40912":"5"},"id":"1bf6edd8-a876-4f89-932b-ffbb327975a1","players":[],"seats":2,"start_after":10,"state":"seating"},{"action_timeout":120,"id":"41d17d93-2252-4206-acbc-f31f6eef8949","players":[],"seats":1,"start_after":0,"state":"seating"},{"action_timeout":120,"id":"2bbe4a54-9618-44c8-9583-d73606b42588","players":[],"seats":1,"start_after":0,"state":"seating"},{"action_timeout":120,"id":"5fb9cd6c-19e9-4307-a7db-2f90fe7514f8","players":[],"seats":1,"start_after":0,"state":"seating"}]],"n":[]}{"t":1,"r":[{}],"n":[]}{"t":1,"r":[true],"n":[]}{"t":1,"r":[true],"n":[]}{"t":1,"r":[true],"n":[]}{"t":1,"r":[{}],"n":[]}{"t":1,"r":[{}],"n":[]}{"t":2,"r":[],"n":[]}{"t":1,"r":[{}],"n":[]}{"t":1,"r":[{}],"n":[]}{"t":2,"r":[],"n":[]}"t":1,"r":[406424],"n":[]}{"t":1,"r":[{}],"n":[]}{"t":1,"r":[{}],"n":[]}{"t":1,"r":[{}],"n":[]}{"t":1,"r":[true],"n":[]}{"t":1,"r":[{}],"n":[]}{"t":2,"r":[],"n":[]}{"t":1,"r":[{}],"n":[]}{"t":2,"r":[],"n":[]}{"t":1,"r":[{}],"n":[]}{"t":1,"r":[{}],"n":[]}{"t":2,"r":[],"n":[]}{"t":1,"r":[{}],"n":[]}a{"t":1,"r":[{"deleted":0,"errors":0,"inserted":0,"replaced":1,"skipped":0,"unchanged":0}],"n":[]}{"t":1,"r":[true],"n":[]}{"t":1,"r":[{}],"n":[]}{"t":1,"r":[true],"n":[]}{"t":1,"r":[true],"n":[]}	{"t":2,"r":[],"n":[]}	{"t":1,"r":[{}],"n":[]}	{"t":1,"r":[true],"n":[]}	"t":1,"r":[406424],"n":[]}	{"t":1,"r":[{}],"n":[]}	{"t":2,"r":[],"n":[]}	{"t":1,"r":[false],"n":[]}	{"t":1,"r":[{}],"n":[]}{"t":1,"r":[{}],"n":[]}		{"t":2,"r":[],"n":[]}
```

**Comment by deontologician** [comment]
looks like this is happening in JSON.parse, which would only occur if the client receives malformed input

Ok, just saw @Timer 's response comment. That appears like the receiving buffer isn't being cleared out between responses, or the responseLength isn't being set correctly

**Comment by deontologician** [comment]
Looking at the affected lines, it seems like this could happen if the server sends a responseLength that's too long, or the responseLength bytes are being corrupted in some way (which is really unlikely).

**Comment by deontologician** [comment]
@Timer can you modify the affected line to do a console.log of the responseLength variable in the _data function in net.js ?

**Comment by deontologician** [comment]
ping @mlucy in case he might have any ideas

**Comment by Timer** [comment]
Sorry I'm away right now, I can mess with it tonight @deontologician.

**Comment by Timer** [comment]
I couldn't get this to reproduce now. But perhaps that's because adding the debugging slowed everything down to a crawl for some reason.

**Comment by deontologician** [comment]
Doh! I might need to write a fuzzer or something and see if I can expose a race condition. Could you share some sample code of the kinds of queries you're running?

**Comment by merrihew** [comment]
We were experiencing the same issue after moving to v2, and in our case the issue was linked to merges (joining data from another table) and not calling 'coerceTo(array)' after a 'getAll' request. Generally, we've needed to be more deliberate with places where previous versions of Rethink would handle cursors/arrays interchangeably, now using a lot more 'coerceTo' calls.

**Comment by danielmewes** [comment]
@merrihew which version exactly are you running now, and which were you running before? By v2, do you mean 2.0.x or 2.1.x?

**Comment by merrihew** [comment]
@danielmewes We were running RethinkDB v1.16.3 and `npm/rethinkdb@1.16.2`. We upgraded to RethinkDB v2.0.4 and `npm/rethinkdb@2.0.2`.

Side note, is there a reason that [`npm/rethinkdb`](https://www.npmjs.com/package/rethinkdb) is not always consistent with the [RethinkDB release](https://github.com/rethinkdb/rethinkdb/releases) version numbers?

**Comment by deontologician** [comment]
@merrihew the driver package numbers match the major and minor versions of RethinkDB, but the patch number only increments if we release a fix for the driver itself, rather than any time we have a patch release for the server

**Comment by danielmewes** [comment]
@merrihew Are you still running into this?

**Comment by jazoom** [comment]
I get this all the time when iterating through my database's objects from Node running on Windows (development). Luckily, it doesn't do this on my production Ubuntu servers (running the same code).

Still, it's very annoying when I'm doing stuff in my test database.

**Comment by danielmewes** [comment]
@jazoom That's quite weird.

@Timer Do you still have the code that prints out the response messages? Maybe @jazoom could use that to get us some insights into why this is failing on Windows.

**Comment by jazoom** [comment]
This is the meat of the code:

`var lastId = r.minval;
var LIMIT = 500;

function doBatch() {
 r.db(database).table(objects).between(lastId, r.maxval, { leftBound: 'open', index: 'id' }).orderBy({ index: 'id' }).limit(LIMIT).run(connection, function(error, cursor) {

    if (error) {
      // be sad
      return;
    }

    cursor.toArray(function(error, objects) {
      if (error) {
        // be sad
        return;
      }

      // check if some objects were returned, because an empty array is returned if the total number of objects is a multiple of LIMIT
      if (objects.length > 0) {
        lastId = objects[objects.length- 1].id;
        doSomethingWithObjects(objects);
      }

      if (objects.length < LIMIT) {
        // we're all done
        return;
      }

      doBatch(); // go on to next iteration
    });
  });
}`

**Comment by Timer** [comment]
@danielmewes iirc I was simply printing out this line https://github.com/rethinkdb/rethinkdb/blob/next/drivers/javascript/net.coffee#L300

**Comment by jazoom** [comment]
It seems this has accidentally been fixed in one of the recent releases since it didn't happen just now when I iterated through all my database items. :-)

**Comment by danielmewes** [comment]
Hmm, wonder what could have changed this.
I'm going to close the issue for now. @jazoom Please re-open if this pops up again at any point.
