### ISSUE TITLE
Ruby connection error not raised as RqlDriverError

### ISSUE THREAD

**Issue by al3xandru** [rethinkdb/rethinkdb#468]
When failing to connect the backtrace is:

```
Errno::ECONNREFUSED - Connection refused - connect(2):
    /lib/net.rb:172:in `initialize'
    /lib/net.rb:172:in `open'
    /lib/net.rb:172:in `reconnect'
    /lib/net.rb:90:in `initialize'
    /lib/func.rb:87:in `new'
    /lib/func.rb:87:in `connect'
```

Shouldn't it raise the `RethinkDB::RqlDriverError`?

**Comment by danielmewes** [comment]
Do we know if this is still true in 2.1?

**Comment by srh** [comment]
Still true in 2.3.5, despite the error hierarchy.  At this point changing this might break some libraries?  I'm closing this, but the only reason is to clean up the issues and avoid interface churn for stuff using RethinkDB.  If you implemented a ReqlConnectionError wrapping I'd merge it.
