### ISSUE TITLE
Do you think RethinkDB is a good fit for a CRM?

### ISSUE THREAD

**Issue by andrerpena** [rethinkdb/rethinkdb#4687]
First, I love RethinkDB, and these are my compelling reasons:

 - Easy to scale... I mean.. I don't know if it can get any easier.
 - Beautiful query language, to the point that an ORM becomes useless.
 - Server joins.
 - Change feeds.

I'm looking for an answer, even if it's a biased one, just as a confirmation, so I feel like I'm not investing in the wrong tool for my problem. Regardless of the answers here, RethinkDB has a place in my heart :)

My goal:
---

I'm investing plenty of time building a platform for developing data-centric business apps called [Gearz](https://github.com/gearz-lab/gearz). When it hits the first alpha, I'm going to release a CRM on top of it. I have 8+ years of experience building ERPs. I know the problems I need to tackle, this is my take to make something new.

My focus:
---

To create a platform/CRM focused on **flexibility** and **configuration-over-code**. It's completely declarative. It's possible to declare entities and properties, as well as how these properties interact with each other. For instance, it's possible to declare that a property is invisible when another property has a value that is less than 1000. I'm building an infrastructure based on React to automatically render views based on metadata. It's beautiful.

Here are my points of interest:

 - I don't know beforehand the entities the user is going to create. When the CRM is released, there's going to be Contacts, Sales, Leads... But the user will have total freedom to declare whatever entities they want, as well as their properties and layouts.

My problem:
---

Normally CRMs adopt a relational database because entities relate to each other. Yes, not necessarily a Contact will have the Sales embedded. It's possible that the Contacts and the Sales will be separate entities that will have to be associated somehow. The standard approach is to have foreign-keys, I know that.

Now there's a dilemma, because normally the app schema would be fixed, and that's exactly what I don't want. I want a free schema, I want the user to declaratively state that entities, properties, actions, layouts and relationships exist and I want to build everything automatically. This doesn't fix in a fixed SQL schema.

My dilemma:
---

I know that RethinkDB has two characteristics that may be roadblocks:

 - The absense of foreign keys.
 - The absense of transactions.

Yet it gives me the freedom I want, like a SQL environment would never give me.

Conclusion:
---

I have faith, and it's not more than faith, that I can handle the absense of foreign keys and the absense of transactions in the application, without that being enforced by the DB.

I have faith that, if you delete a Sale but the reference in the Contact somehow wasn't updated because of the lack of transactions, I can just show the Contact as inconsistent and provide a tool to fix inconsistences automatically.

I think that this will work.

Can you please provide me with feedback on that architecture, on the RethinkDB side? Even if it's biased, and even if it's just a "I think it will work" or "I think it will not work"?

Thank you very much in advance.

**Comment by ha1331** [comment]
Here are couple of issues that you might be interested in following:

https://github.com/rethinkdb/rethinkdb/issues/4598
https://github.com/rethinkdb/rethinkdb/issues/3367

**Comment by danielmewes** [comment]
Hi @andrerpena, that sounds like a really cool project.
From what I can tell, RethinkDB would be a great fit for this, apart from the two restrictions that you already mentioned (transactions, foreign keys). I can't think of anything that would stop this from working really well.

**Comment by andrerpena** [comment]
@ha1331 , thanks. It seems, at least, that transactions should come down the road. Transactions seem to be more important for me because it makes it easier to "enforce" foreign-key consistency on the client.

**Comment by andrerpena** [comment]
@danielmewes , thank you for the reply. Great. I feel better now :)
