### ISSUE TITLE
Connect to MQTT?

### ISSUE THREAD

**Issue by jcw** [rethinkdb/rethinkdb#4689]
For applications where more and more of the code is moving into the browser (SPA's, React, etc), and given that they can connect via http and websockets, would it be an idea to have RethinkDB talk to an MQTT pub-sub broker such as Mosquitto?

The scenario being: `server = rethinkdb + mqtt + static-assets-http-server`, with browsers connecting through a websocket to MQTT to deal with real-time feeds (using various QoS modes), and going _through_ MQTT for database CRUD + query operations.

It may sound like an odd mix, but for a low-power server such as a Raspberry Pi, the combination of rethinkdb/pub-sub/httpd could be all that's needed, and each of these can be _very_ efficient and low on resource requirements.

It's quite easy to turn a C/C++ app into an MQTT client through the libmosquitto packet. Another option would be to run a separate app sitting between db and pub-sub, but that involves more moving parts. Then again, such a bridge could include httpd functionality, and store all assets in the db as well.

Any thoughts on this? Has this been done before? I'd be grateful for any pointers/tips...

**Comment by danielmewes** [comment]
I haven't looked into Mosquitto yet, so I'm not sure about the details of this.
Which role exactly would Mosquitto play in this scenario? Would its main purpose be to provide an access point to the browser? You also mention having it handle real-time feeds. Is that for efficiency / simplicity or is there something you think it does better than RethinkDB changefeeds?

We're working on some ideas to move things closer to the browser. You might be interested in taking a look at https://github.com/rethinkdb/rethinkdb/issues/3711 , which is what we're currently looking into.

**Comment by jcw** [comment]
Moving things closer to the browser. I'm not sure my comments were that coherent, in hindsight. For an [IoT](https://en.wikipedia.org/wiki/Internet_of_Things)-type app, MQTT is in widespread use as standard message interchange. What it offers is pubsub for general use, and a websocket to the browser. What it's missing, is large-scale storage, and the ability to handle HTTP requests.

With MQTT + RethinkDB, I would have the messaging + storage side of things covered. Assuming all assets get stored inside ReDB (even an index.html home page), this really is very close to covering the main server-side needs. The missing links would be: ReDB serving httpd (as it does for the admin interface) and ReDB talking to MQTT in some way.

As I said, I'm not sure it makes sense, but if the app logic is entirely browser-side (JavaScript, and React or Angular), then the server really only needs to handle general app-agnostic tasks, i.e. comms & db.

**Comment by danielmewes** [comment]
Thanks for clarifying.

As part of #3711, we're considering adding a plugin infrastructure to RethinkDB. Different integrations can live in plugins that you can launch together with the RethinkDB server (we're going to put up a comprehensive proposal soon). I think that would be a great place for integrating with an MQTT server as well, and we could also put the HTTP endpoint in there. We'll see how these ideas work out with GraphQL. Once we have the infrastructure for that, I think this might be a relatively simple extension on a technical level.

**Comment by jcw** [comment]
Sounds good. Thx.

**Comment by jcw** [comment]
[This blog post](http://tonsky.me/blog/the-web-after-tomorrow/) more or less summarises what I'm after. I think :)

**Comment by danielmewes** [comment]
@jcw thanks for the link, that's a nice article.
We're definitely aiming at solving the problems mentioned there. There are still a few components missing right now, but hopefully we can add those in the next months (most importantly the option of getting rid of an application-specific backend layer).

**Comment by Grovkillen** [comment]
Update on this?

**Comment by v3ss0n** [comment]
Nobody is working on this , check with @srh  if you plan to contribute.

**Comment by thelinuxlich** [comment]
@srh I think this belongs in userland, it would be viable once we have reliable changefeeds.

**Comment by srh** [comment]
Being kind of lazy thinking about "wontfix" so don't take it completely literally.
