### ISSUE TITLE
Keep durability and acks over `reconfigure`

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4690]
This applies primarily to v2.0.x.

I'm not sure how we handle the acks setting in 2.1 over a `reconfigure`.

**Comment by coffeemug** [comment]
I don't think we should worry about it. I'd check for regression in 2.1 branch, but I don't think it's worth fixing in 2.0.

**Comment by VeXocide** [comment]
It's fixed in 2.1.0, we were considering backporting it.

**Comment by coffeemug** [comment]
Cool. I'm ok with closing this issue and advising users to migrate to 2.1.

**Comment by danielmewes** [comment]
Fair enough.
