### ISSUE TITLE
`table.wait()` not always waiting for `table.config().update()`

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4691]
In working on a test I found that there appears to be a race condition between a `table.config().update()` and a `table.wait()` immediacy following it on the same connection. This is happening regardless of what `wait_for` mode I am using, but a 1 second `time.sleep()` does fix it. @VeXocide thought that the `all_replicas_ready` option should fix this, but it does not in my case.

This bug is to make sure we understand this behavior and that it is not unexpected.

**Comment by danielmewes** [comment]
That's interesting (as in weird).

**Comment by larkost** [comment]
It looks like this was only a case of a missing `.run(conn)`. So... my bad.
