### ISSUE TITLE
Query Stats for Munin-Plugin

### ISSUE THREAD

**Issue by RubenKelevra** [rethinkdb/rethinkdb#4693]
Hey there,

I'm thinking of a plugin to query the stats of a rethinkdb-cluster via Munin-plugin. What is the easiest method of getting the stats of the dashboard?

Best regards

Ruben

**Comment by deontologician** [comment]
The best way is to use the rethinkdb stats table. Check out `r.db('rethinkdb').table('stats')`, which is documented [here](http://www.rethinkdb.com/docs/system-stats/)

**Comment by deontologician** [comment]
I'm closing this since it isn't a bug, but feel free to ask more questions here

**Comment by RubenKelevra** [comment]
Thank you! :)

**Comment by RubenKelevra** [comment]
How do I get the Hostname for a Server? Like in the Server-Tab in Details?

**Comment by deontologician** [comment]
That would be in `rethinkdb.server_config`

**Comment by VeXocide** [comment]
A complete overview of the system tables is available at http://www.rethinkdb.com/docs/system-tables/

**Comment by RubenKelevra** [comment]
Thanks :)

**Comment by VeXocide** [comment]
@RubenKelevra -- once #3934, which proposes a `conn.server_id()`, is implemented it should be significantly easier to find which server you're connected to.

**Comment by deontologician** [comment]
Whoops, was thinking status and wrote config. Glad you got it working

**Comment by RubenKelevra** [comment]
@VeXocide well, thanks. :)

**Comment by RubenKelevra** [comment]
So, I was thinking of the following plugins:

rethinkdb_cluster_status
rethinkdb_memory_usage
rethinkdb_cache_usage_per_x (don't know if this should be table or database)
rethinkdb_node_status
rethinkdb_dbsize_ondisk
rethinkdb_node_io

**Comment by deontologician** [comment]
@RubenKelevra anything else I could think of is probably in the webui somewhere :P

**Comment by RubenKelevra** [comment]
Well sure, but with munin you can monitor the whole system-status along with rethinkdb. Else munin can push me or send me a mail if something goes wrong. :)

**Comment by RubenKelevra** [comment]
I've just added the first one :)

https://github.com/munin-monitoring/contrib/pull/722

**Comment by RubenKelevra** [comment]
Graphs of this plugin looks like this:

![rethinkdb_node_io-day 1](https://cloud.githubusercontent.com/assets/614929/16246603/314b823a-3806-11e6-8c04-986f96877db1.png)

**Comment by danielmewes** [comment]
Nice @RubenKelevra !
