### ISSUE TITLE
Make `and` and `or` work with 0 arguments.

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#4696]
Now that we have `r.args` it's extremely annoying that they don't with with no arguments.  (Also, other languages like Common Lisp with arbitrary-arity `and` and `or` operators have 0-argument version.)

There's another issue for this somewhere but I couldn't find it searching.

**Comment by mlucy** [comment]
Bumping this to 2.2 not because it's particularly important but because I have a fix for #4132 that also changes this, so it would be nice to squeeze it into the discussion period.

**Comment by danielmewes** [comment]
What are the results of these terms when called with zero arguments?

**Comment by mlucy** [comment]
In SBCL (and this makes sense to me intuitively):
```
* (and)
T
* (or)
NIL
```

The reason this makes sense intuitively to me is that variadic `and` works if you define `(and a b) <=> (and a b true)` and `or` works if you define `(or a b) <=> (or a b false)`.

**Comment by deontologician** [comment]
Just one minor data point, we default to `true` with 0-arg `.contains`, which could be seen as an `or`-ish operation

**Comment by deontologician** [comment]
also, I personally think 0-arg `or` returning null is yucky, but I don't have a strong opinion

**Comment by mlucy** [comment]
@deontologician --I think in ReQL 0-arg `or` should return `false`.  It returns `NIL` in CL because that's the only false value.

**Comment by danielmewes** [comment]
I think `contains` is actually more similar to `and`, assuming the documentation is correct: "When called with values, returns `true` if a sequence contains all the specified values."

Allowing 0-argument `or` with `r.or() -> false` and 0-argument `and` with `r.and() -> true` sounds good to me.

**Comment by danielmewes** [comment]
Marking as settled with
` r.or() -> false` and `r.and() -> true`

**Comment by mlucy** [comment]
This is in next (the review was completed a while ago and I had just forgotten to merge it in).
