### ISSUE TITLE
Adding a `count()` on an `eqJoin` stream makes it very slow

### ISSUE THREAD

**Issue by kureikain** [rethinkdb/rethinkdb#4697]
Assume I have this schema:

```
compounds_foods: compound_id (~662,448 documents)
compounds_flavors: compound_id, flavor_id(~11,136 documents)
```

This query run very fast and return `STREAM` what explains why it is fast, I think

```
r.db("foodb").table("compounds_foods")
  .eqJoin('compound_id', r.db('foodb').table('compounds_flavors'), {index: 'compound_id'})
```

Then out of curiousity, I tried to add  a `count` on it to count how many result I have:
 
```
r.db("foodb").table("compounds_foods")
  .eqJoin('compound_id', r.db('foodb').table('compounds_flavors'), {index: 'compound_id'})
 .count()
```

And it never finish on my machine Macbook Pro 2014, core i5 16GB RAM.

```
RqlRuntimeError: HTTP ReQL query timed out after 300 seconds in:
r.db("foodb").table("compounds_foods").eqJoin("compound_id", r.db("foodb").table("compounds_flavors"), {index: "compound_id"}).count()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Is this some kind of bug or I'm doing it wrong?

Eventually, I think it has better way to do this kind of thing. However, this example is trivial and I think counting a stream should be possible?

**Comment by danielmewes** [comment]
I think the discrepancy in performance comes from the fact that if you don't attach the `count()`, only the first few results of the `eq_join` will be computed until your client requests more. For computing the `count()`, the whole result must be generated before the query can return something.

I can see from the HTTP query timeout error, that you're running these queries in the Data Explorer. If you run them in another client, that should both avoid the timeout, and you can load the full result by iterating over the cursor in the first query to get more comparable timings.

In general `eq_join` for large numbers of documents can be a bit slow right now. This is a known issue which we will get to once we get the chance.

**Comment by kureikain** [comment]
Thanks for your explanation @danielmewes Gonna close this out.
