### ISSUE TITLE
Transducers support

### ISSUE THREAD

**Issue by fckt** [rethinkdb/rethinkdb#4700]
Is there any plans to use transducers in order to generate queries? Transducers are awesome, it separates query (manipulation) from the source of data (array, eventstreams ect.). It could be considered as a way to reuse your queries in different contexts. So if I'm developing service which will allow user to filter over things, at some point I must decide, either I want to filter data on client (from cache) or on the server (or both). Or I have another datasource and I wish to filter data as it comes.

**Comment by danielmewes** [comment]
@AlexeyFrolov do you have some links to introductory reads on the topic? I'm not too familiar with the transducer concept.

**Comment by AlexeyFrolov** [comment]
Sry for late answer.
Initially transducers were proposed and implemented for Clojure language. Some links:
http://blog.cognitect.com/blog/2014/8/6/transducers-are-coming
https://www.youtube.com/watch?v=6mTbuzafcII

Also there are 2 implementations in JS: 
https://github.com/jlongster/transducers.js
https://github.com/cognitect-labs/transducers-js

**Comment by danielmewes** [comment]
Thanks for the links @AlexeyFrolov 
I think this needs some thought.

In a way, I think https://github.com/neumino/reqlite provides a comparable functionality for ReQL queries, in that you can run the same code to transform data in your client, and on your database.

**Comment by AlexeyFrolov** [comment]
Thank you @danielmewes . reqlite looks like a solution for my use case. 
I would add that transducers are supported also in the most reactive libraries (although at the same time every one provides its own data transformation "primitives"). People use transducers with Node Streams https://github.com/transduce/transduce-stream . Also I found this https://github.com/kevinbeaty/underarm .
This wonderful idea spread quickly on different languages/platforms:
https://github.com/cognitect-labs/transducers-python
https://github.com/mtdowling/transducers.php
https://github.com/cognitect-labs/transducers-ruby
https://github.com/sdboyer/transducers-go
https://github.com/cognitect-labs/transducers-java
https://github.com/knutwalker/transducers-scala

**Comment by srh** [comment]
In any case I'm all for advancement of ReQL and will leave this in closed-backlog.
