### ISSUE TITLE
Syntax error in Python driver

### ISSUE THREAD

**Issue by indiedotkim** [rethinkdb/rethinkdb#4702]
Hi!

I just installed RethinkDB on a Google Cloud instance (Debian, jessie), and got this message:

~~~
$ sudo pip install rethinkdb
Downloading/unpacking rethinkdb
  Downloading rethinkdb-2.1.0.tar.gz (99kB): 99kB downloaded
  Running setup.py (path:/tmp/pip-build-rElEXC/rethinkdb/setup.py) egg_info for package rethinkdb
    
Installing collected packages: rethinkdb
  Running setup.py install for rethinkdb
      File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net_asyncio.py", line 23
        c = yield from streamreader.read(1)
                     ^
    SyntaxError: invalid syntax
    
    
    Installing rethinkdb-dump script to /usr/local/bin
    Installing rethinkdb-import script to /usr/local/bin
    Installing rethinkdb-index-rebuild script to /usr/local/bin
    Installing rethinkdb-export script to /usr/local/bin
    Installing rethinkdb-restore script to /usr/local/bin
Successfully installed rethinkdb
Cleaning up...
~~~

I only use the Python driver for `rethinkdb import`, which seems to work, but this might affect other folks.

Kim

**Comment by larkost** [comment]
This is very likely `pip` running `compile` on all of the files (very good thing), but we do have one file that is only really valid for Python3.4 (and above) since it uses `asyncio`. We do the right things at runtime so that this is not generally a problem outside of the `compile` phase. But we should attempt to somehow avoid this warning during install.

**Comment by indiedotkim** [comment]
@larkost Thanks for the explanation!

**Comment by larkost** [comment]
A bit of research this morning and the looks like it id going to be really annoying to solve. Unless some questions I asked of others comes back with a better solution it looks like our avenues are:
1. Live with the warning. I have to confirm that all of the other files are getting compiled fine, but we are probably good.
2. Submit 2 versions of the driver to PyPi for every release, one that is marked for Python3.4 and above (i.e.: for every major new version) and includes all files, and the other marked for Python2.6-Python3.3 that excludes this one file. This is going to cause some confusion as I am not sure that `pip` will automatically handle this for us, and I also think that we would have to go into the admin interface every time we release to re-enable the other "older" release.
3. Use a script to manipulate this file while installing. This feels like a bad idea, but would probably work.

**Comment by indiedotkim** [comment]
@larkost My two cents: Having two versions is probably the best solution. I have never met anyone who actually uses Python 3.4, yet. The vast majority of folks appears to use 2.7 at the moment. Those who do use Python 3.4 (like myself) are usually aware of compatibility issues and would not be surprised if there is a separate "rethinkdb3.4" driver.

**Comment by deontologician** [comment]
I'd vote for 2. I am pretty sure pip will select the right version for you, so it'll only be annoying for us

**Comment by danielmewes** [comment]
If we can make sure `pip` can pick the right package automatically, option 2 would be a good solution I think.

I don't particularly like the idea of having a separate `rethinkdb3.4` driver that one has to explicitly select. At the moment few people might be using Python 3.4, but it wouldn't work well in the long term.

**Comment by westermarck** [comment]
I get the same error when trying to install the Python driver today. The package seems to have been updated to ```2.1.0.post2```.

```
Downloading rethinkdb-2.1.0.post2.tar.gz (103kB): 103kB downloaded
  Running setup.py (path:/tmp/pip_build_root/rethinkdb/setup.py) egg_info for package rethinkdb
    
Installing collected packages: rethinkdb
  Running setup.py install for rethinkdb
      File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net_asyncio.py", line 24
        c = yield from streamreader.read(1)
                     ^
    SyntaxError: invalid syntax
    
    Installing rethinkdb-dump script to /usr/local/bin
    Installing rethinkdb-import script to /usr/local/bin
    Installing rethinkdb-export script to /usr/local/bin
    Installing rethinkdb-restore script to /usr/local/bin
    Installing rethinkdb-index-rebuild script to /usr/local/bin
Successfully installed rethinkdb
Cleaning up...
```

The package seems to get installed but upon using it in a Python script the module doesn't load properly.

```
Traceback (most recent call last):
  File "importdb.py", line 3, in <module>
    import rethinkdb
  File "$PATH/rethinkdb.py", line 5, in <module>
    rethinkdb.connect('localhost', 28015).repl()
AttributeError: 'module' object has no attribute 'connect'
```

**Comment by larkost** [comment]
The error should not be getting in the way of installing or using the `rethinkdb` Python driver, and I have just manually verified that `sudo pip install rethinkdb` works for both Python2.7 and Python3.4 (so presumably 2.6-3.4).

@westermarck my guess is that there is something else going on here. Can you tell me what version of Python and what OS you are on? Also, are you doing something specific to get `$PATH/rethinkdb.py` in there? Unless you edited the error message that looks suspicious to me.

**Comment by sontek** [comment]
@westermarck Looks like you have a local file called rethinkdb.py that is being imported instead of the pip installed rethinkdb.

**Comment by westermarck** [comment]
@larkost Python 2.7.6 on Linux fredrik 3.16.0-50-generic #66~14.04.1-Ubuntu SMP Thu Sep 10 17:05:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux.

I removed the full path that's the reason for the $PATH in the error message.

@sontek Yes, I did have a local file named ```rethinkdb.py``` in my local directory. I renamed the file, uninstalled the driver and reinstalled the driver again.

The error message from the ```pip install rethinkdb``` persists. However the Python script now executes as expected. So this resolved my issue, thanks!

**Comment by larkost** [comment]
To reiterate what I said above, the message printed during `pip install rethinkdb` should be considered a warning only.

I do absolutely want to remove it, but it is unimportant since that particular file is not usable unless you are on Python3.4, and in that case it would not generate an error. There are a few ideas for suppressing the error, but I have to do some testing to see which one would work. This has taken a back-seat to other issues.

**Comment by larkost** [comment]
This is now up for review with CR 3286 from branch `larkost/4702-hide-net_asyncio.py`.

My solution actually winds up being the best-of-all-worlds: we only upload a single version to `pypi`, but `pip`/`easy_install` wind up installing only the parts of the driver that are relevant for the version of Python it is being installed for. I have put the specialized `net.py` subclasses inter own sub-modules, and play with the `packages` setting we are sending to `setuptools.setup` to only include the relevant ones.

**Comment by larkost** [comment]
This has been merged into `next` with 5e434b8c. To sum up what has already been said: this solution just works for all versions by excluding the `asyncio` code when the is not available. Unless there are some very odd backports (or a really inconveniently named module) this should always cover us.

@danielmewes do you want this cherry picked into `v2.2.x`?

**Comment by danielmewes** [comment]
For anyone following this: The latest Python driver 2.2.0.post2 no longer has this issue.

**Comment by tonystevens** [comment]
I'm using python 3.6.4, and I cannot even connect to a local rethinkdb. It keep saying "module 'rethinkdb' has no attribute 'connect'"
