### ISSUE TITLE
Need tester for my php-rql package for arch

### ISSUE THREAD

**Issue by RubenKelevra** [rethinkdb/rethinkdb#4708]
Hi! 

I just created a package for arch-linux for the php driver. Since I'm not using it currently and php is not a language which I'm able to write I need somebody which is willing to test the package. :)

https://aur.archlinux.org/packages/php-rql/

Best regards

Ruben

**Comment by danielmewes** [comment]
That's really cool! Unfortunately I'm not running arch Linux, so I can't test it.

A small thing I noticed: The version of `pb4php` that's included in the source is not actually complete, and it has been patched specifically for php-rql. I actually recommend taking the whole `pb4php` directory out of the package / source path. It is not needed for using the driver, only for generating the `pb4php_pb_proto_ql2.php` file during development.

**Comment by RubenKelevra** [comment]
Thanks for the hint, very important detail. It's done.
