### ISSUE TITLE
Should `contains` and `merge` really support 0 arguments?

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#4715]
They do currently, but there isn't a good reason beyond a general one about r.args (I would argue that if you use r.args, you probably don't want it to silently succeed on an empty array, so this isn't really a good argument)

In light of #4696 , it's probably a good time to discuss this.

If I find other surprising 0-arg terms I'll edit this and add them

**Comment by mlucy** [comment]
I would definitely expect 0-argument `merge` to work.  I could easily imagine a query like `r.table('original_documents').get(whatever).merge(r.args(r.table('patches').get(whatever)['patches']))`.

`contains` is more borderline, but in general I expect arbitrary-arity functions to have well-defined 0-arity cases (and languages like the various lisps that have lots of arbitrary-arity predicates almost always define the 0-arity case).  The case here is something like `array_of_words.contains(r.args(array_of_banned_words))` or something -- you want that to work for an empty array of banned words.

**Comment by danielmewes** [comment]
It seems like there's no obvious consent on this, and I think it's not as important as many of the other discussions. Moving to backlog.

**Comment by deontologician** [comment]
I'm less "behind this" and more "we should be consistent". Since it seems #4696 is full steam ahead, I'll just close this one
