### ISSUE TITLE
"outdated indexes" warning persists after rebuilding indexes

### ISSUE THREAD

**Issue by mike-marcacci** [rethinkdb/rethinkdb#4717]
Hi there!

Just updated to version 2.1.1 from 2.0.4, updated the python driver via pip, and ran `rethinkdb index-rebuild`.

![image](https://cloud.githubusercontent.com/assets/690517/9341893/8929c6d4-45ad-11e5-97ee-267f3a117b0d.png)

Strangely, though, I continue to get the outdated index warning from the web UI:

![image](https://cloud.githubusercontent.com/assets/690517/9341885/6eeaec1c-45ad-11e5-8dc1-b87304f0da4c.png)

I've attempted to rebuild again, and from other nodes, but it completes instantly, rebuilding 0 indexes. This doesn't appear to be effecting our application at all, so I suspect it's an incorrect warning?

**Comment by danielmewes** [comment]
Hi @mike-marcacci, yep, this is just an incorrect warning. Sorry for the confusion. 
We're already working on a fix for this, see https://github.com/rethinkdb/rethinkdb/issues/4664

The work-around is to restart your servers. After the restart, the warning should disappear.

**Comment by mike-marcacci** [comment]
Ah awesome – didn't see that other issue (sorry). Thanks for the quick reply!
