### ISSUE TITLE
Very slow query performance using orderBy

### ISSUE THREAD

**Issue by nodesocket** [rethinkdb/rethinkdb#4722]
Running `RethinkDB 2.1.1` on 3 servers *(each with 2 cores and 13GB of memory)*. The table `daily_quotes` has 3 shards and 3 replicas. Each shard has around 22,000 documents. There is a secondary index on `date`.

Running a simple query:

    r.db('macd').table('daily_quotes').orderBy('date')

Takes over 23 seconds. I ran a query profile and see:

    23.32s round-trip time
    10.87s server time
    312 shard accesses

And here is the raw query profile json:

**REMOVED JSON BECAUSE IT WAS HUGE**

**Comment by JohnyDays** [comment]
Hey, you need to use ```.orderBy({index: 'date'})``` or it will not use the index.

**Comment by nodesocket** [comment]
Hi Johny.

Even using the index `date` the query takes about a second each time, which seems very slow seeing as I only have about 64,000 documents, spread across three servers. Is that expected performance?

**Comment by JohnyDays** [comment]
That's still way below expected performance I'd venture a guess, something must be off here. Someone from the core team will surely try to help soon.

**Comment by nodesocket** [comment]
Yeah, something it wrong for sure. I am using Google Compute, with 3 servers *(each with 2 cores and 13GB of memory)*.

**Comment by danielmewes** [comment]
I think 1 second for reading 64,000 documents isn't totally unreasonable, depending on the CPU performance of the servers (2 cores isn't that much), the network bandwidth, and the performance of the client used.

@nodesocket could you check CPU usage on both the servers (ideally on the one that the client is connecting to), and on the client as well?

What do the documents in the table look like? In particular, what's their average size and how many fields do they have?
Which client are you using?

**Comment by nodesocket** [comment]
1 second for 64,000 documents seems unreasonable to me. We plan on storing millions of documents. I am doing this query right from the web interface in query explorer. Could that be the bottleneck?

In terms of documents, they look like:

````
{
    "id": "e9261514-b509-41fd-96dd-c6aa261d2c4e",
    "date": 1440101659948,
    "quote": {
        "id": "22144",
        "t": "AAPL",
        "e": "NASDAQ",
        "l": "112.65",
        "l_fix": "112.65",
        "l_cur": "112.65",
        "s": "2",
        "ltt": "4:03PM EDT",
        "lt": "Aug 20, 4:03PM EDT",
        "lt_dts": "2015-08-20T16:03:45Z",
        "c": "-2.36",
        "c_fix": "-2.36",
        "cp": "-2.05",
        "cp_fix": "-2.05",
        "ccol": "chr",
        "pcls_fix": "115.01",
        "el": "112.60",
        "el_fix": "112.60",
        "el_cur": "112.60",
        "elt": "Aug 20, 4:11PM EDT",
        "ec": "-0.05",
        "ec_fix": "-0.05",
        "ecp": "-0.04",
        "ecp_fix": "-0.04",
        "eccol": "chr",
        "div": "0.52",
        "yld": "1.85"
    }
}
````

With secondary indexes on the following:

````
date
quote.t
quote.l
quote.e
quote.lt_dts
quote.c
````

**Comment by danielmewes** [comment]
The Data Explorer is really really slow when it comes to retrieving data compared to other clients.

Also keep in mind that since the query uses streaming, only the first batch of results will be computed and sent to the client, until more results are requested.
Overall, the timings from the Data Explorer aren't super useful for assessing query performance unfortunately.

You mention that you're going to store millions of documents. Are you also going to retrieve that many documents in queries regularly? In that case, the client having to decode the data might become a bottleneck.
Overall I think 1 second (or even a bit more) for retrieving 64,000 rows with this many fields from a single client is about expected. You can probably get more total throughput by using multiple concurrent clients.

To get an impression on the raw read speed of the cluster ignoring any transfers to a client, you could try a query like this:
```js
r.db('macd').table('daily_quotes').orderBy({ index: r.desc('date') }).map(r.row).count()
```

**Comment by nodesocket** [comment]
@danielmewes running:

````
r.db('macd').table('daily_quotes').orderBy({ index: r.desc('date') }).map(r.row).count()
```

in the web interface *(data explorer)*, resulted in:

416ms round-trip time
302ms server time
24 shard accesses

**Comment by thelinuxlich** [comment]
Hey @nodesocket, I'm running a similar setup to yours, except that my instances are 4-cores. My queries are huuuuuge(complex segmentation joining at least four tables with quantity and size of documents similar to yours) and the performance has been acceptable. I'm using some unoptimized things, like ungroup(), distinct() and group() without index, lots of chained filters, etc

**Comment by thelinuxlich** [comment]
Are you using SSD? That could provide a huge boost. Also, you should pay attention to the region where your instances are located because there are CPU generation differences. Mine is us-central1-c and it is using Intel Haswell

**Comment by thelinuxlich** [comment]
Also I remember @danielmewes saying on the Google Group that a proxy can help too

**Comment by nodesocket** [comment]
The instances are:

|      Zone     | Machine Type                         | Disk   | SSD | IOPS (R/W)    | CPU PLATFORM     |
|:-------------:|--------------------------------------|--------|-----|---------------|------------------|
| us-central1-f | n1-highmem-2 (2 vCPUs, 13 GB memory) | 500 GB | YES | 10,000/15,000 | Intel Ivy Bridge |
| us-central1-c | n1-highmem-2 (2 vCPUs, 13 GB memory) | 500 GB | YES | 10,000/15,000 | Intel Haswell    |
| us-central1-b | n1-highmem-2 (2 vCPUs, 13 GB memory) | 500 GB | YES | 10,000/15,000 | Intel Haswell                  |

**Comment by thelinuxlich** [comment]
they should all be on the same zone to avoid latency issues between them

**Comment by nodesocket** [comment]
I just checked, all RethinkDB machines communicate over the local interface, and pings times are all less than 1ms between each machine. That should be fine.

What do you mean by a proxy?

**Comment by thelinuxlich** [comment]
http://rethinkdb.com/docs/sharding-and-replication/#running-a-proxy-node

**Comment by danielmewes** [comment]
I'm not sure how much a proxy would help here, if the bottleneck is actually on the client. @nodesocket did you get around to trying this with a non web UI client and checking the CPU usage on the server vs. client when running the query?

**Comment by nodesocket** [comment]
@danielmewes related https://github.com/rethinkdb/rethinkdb/issues/4748#event-391161094. Apparently my secondary indexes were not even working because they were created via the webUI.

**Comment by danielmewes** [comment]
@nodesocket Is this still an issue? Have you had a chance to run this with a different client? (as mentioned above, Data Explorer timings are not useful for benchmarking).
