### ISSUE TITLE
After upgrading to 2.1.1 all tables are reported "not available"

### ISSUE THREAD

**Issue by veigarfreyr** [rethinkdb/rethinkdb#4723]
After upgrading to 2.1.1 the Dashboard reports all tables like:
"Table xxx.yyy is not available.
None of the replicas for this table are reachable (the servers for these replicas may be down or disconnected). 
No operations can be performed on this table until at least one replica is reachable."

When trying to dump a backup it returns:
"ReQL error during 'count': The server(s) hosting table `xxx.yyy` are currently unreachable."

All data is available and the server seems to run normally though..

I found one report of the same here: http://stackoverflow.com/questions/32049780/why-are-my-tables-unavailable-in-rethinkdb

**Comment by cd34** [comment]
Also have the same issue.

Had to downgrade to 2.1.0 (using the packaged version for Debian/Jessie)

Tables were accessible, but, trying to reindex failed:

$ rethinkdb index-rebuild -r isoup.coords -n 2
ReQL error during 'get outdated indexes': The server(s) hosting table `isoup.coords` are currently unreachable.

When downgrading to 2.10

$ rethinkdb index-rebuild -r isoup.coords -n 2
Rebuilding 2 indexes: `isoup.coords:location`, `isoup.coords:refid`
[=====                                   ]  13%

**Comment by danielmewes** [comment]
@veigarfreyr, @cd34 Thanks for the report, and sorry you're running into this. We'll look into this and try to provide a fix asap.

@veigarfreyr Could you email me the output of `r.db('rethinkdb').table('_debug_table_status')` (this can be pretty large), as well as the output of `r.db('rethinkdb').table('table_status')` and `r.db('rethinkdb').table('table_config')`? My email is daniel@rethinkdb.com . This data would help a lot in figuring out what's going on.

Is there a chance you could provide us with a copy of the data directories as well? We can sign an NDA if necessary. If yes, please let me know and we will send you instructions for the data upload.

**Comment by danielmewes** [comment]
@veigarfreyr Another question: Was this working with 2.1.0 like in @cd34 's case? Or did you upgrade directly from 2.0.x or earlier? How many servers are there in your cluster?

(also pinging @VeXocide, @Tryneus in case they have any ideas)

**Comment by cd34** [comment]
@danielmewes sent you email. Can upgrade back to 2.1.1 if you would like to debug. data set is ~1tb so I could send you a physical disk with the data if needed.

**Comment by danielmewes** [comment]
Thanks a lot @cd34 . We took a look at your server configuration and think that we understand how this happened.
We're going to include a fix for this in 2.1.2.

It looks like this is basically a side-effect of a migration bug that existed in 2.1.0, but was fixed in 2.1.1. However it seems like the new code in 2.1.1 that works around tables that were already affected by the bug has the side-effect of never making the tables appear as ready. There are still some open questions and we're still investigating the details of this.

**Comment by Tryneus** [comment]
Fix is up in review 3177.

**Comment by Tryneus** [comment]
The fix has been approved and merged to `next` in commit 184c68c, and cherry-picked into `v2.1.x` in commit d4149a2.  Will be in release 2.1.2.

Thanks for your patience, @veigarfreyr and @cd34, and for all your help.

**Comment by danielmewes** [comment]
RethinkDB 2.1.2 with the fix for this is now available. (@veigarfreyr , @cd34)
