### ISSUE TITLE
[Feature request/bug] Arbitrary expression compound indexes do not support lines/polygons

### ISSUE THREAD

**Issue by JohnyDays** [rethinkdb/rethinkdb#4724]
Both of these fail with the error  
```Could not prove function deterministic.  Index functions must be deterministic```

```javascript
r.table('any').indexCreate('line', function() {
  return r.line([-122.423246,37.779388], [-121.886420,37.329898])
}, {geo: true})
```
```javascript
r.table('any').indexCreate('line', function() {
  return r.polygon(
    [-122.423246,37.779388],
    [-122.423246,37.329898],
    [-121.886420,37.329898],
    [-121.886420,37.779388]
  )
}, {geo: true})
```

Even though they are deterministic (?). Do line/polygon somehow use a sub-query to a system table?

**Comment by larkost** [comment]
We have had a number of discussions on this: #3009, #3011, and #3287 are a good overview.

The short of it is that geo calculations use floating point math, and sadly there can be generally non-meaningful differences in those calculations depending on the hardware and software that they are run on. Those slight differences force us to mark anything using floating point as non-deterministic to force all of the calculations to happen on one machine.

There are ways around this, but we have not yet figured one that does not have performance and complexity challenges that we are willing to take yet.

**Comment by JohnyDays** [comment]
It can be worked around, I don't know how efficient it will get with more entries, but my use case for this is for a very limited dataset. Thanks for the explanation
