### ISSUE TITLE
Film updated version of "What is RethinkDB?" video

### ISSUE THREAD

**Issue by ahruygt** [rethinkdb/rethinkdb#4725]
We need to update the "What is RethinkDB?" video on youtube.  @KittyBot and @dalanmiller perhaps you should decide who does the video, though I think Daniel Miller is a good fit.

Ideas for the updated version:

- A "face to face" introduction.
- Screencast
- Outro, with footage of our community and office culture.

**Comment by danielmewes** [comment]
Did you put this here intentionally? Shouldn't it go in the company tracker?
