### ISSUE TITLE
inconsistent results for orderBy query (js driver)

### ISSUE THREAD

**Issue by mbroadst** [rethinkdb/rethinkdb#4728]
if you run the following code multiple times, you'll see that the results returned vary between the top returned document being: `{ username: 'arthur', email: 'arthur@gmail.com' }` or `{ username: 'arthur', email: 'aaaaarthur@gmail.com' }`. With the Data Explorer the top result is consistently `{ username: 'arthur', email: 'arthur@gmail.com' }`

```
'use strict';
var Promise = require('bluebird'),
    r = require('rethinkdb');

r.connect({host: 'localhost', port: 28015}, function(err, connection) {
  if (err) throw err;

  r.db('test').tableDrop('user').run(connection, function(err, result) {
    r.db('test').tableCreate('user').run(connection, function(err, result) {
        if (err) throw err;

        var data = [
          { username: 'arthur', email: 'arthur@gmail.com' },
          { username: 'james', email: 'james@gmail.com' },
          { username: 'henry', email: 'henry@gmail.com' },
          { username: 'william', email: 'william@gmail.com' },
          { username: 'edward', email: 'edward@gmail.com' },
          { username: 'arthur', email: 'aaaaarthur@gmail.com' }
        ];

        r.db('test').table('user').insert(data).run(connection, function(err, result) {
          if (err) throw err;

          r.db('test').table('user').orderBy('username').run(connection, function(err, result) {
            if (err) throw err;
            console.log(result);

            r.db('test').tableDrop('user').run(connection, function(err, result) {
              if (err) throw err;
            });
          });
        });
    });
  });
});
```

**Comment by Tryneus** [comment]
@mbroadst, I believe this is expected behavior.  The field you told the query to order by is identical for those two rows, so their order does not matter.  If you want another field to be a tie-breaker, you can specify multiple fields to `orderBy`:

```js
r.db('test').table('user').orderBy('username', 'email').run(connection, cb);
```

**Comment by mbroadst** [comment]
@Tryneus but running the same operations in the Data Explorer yields consistent results? strange

**Comment by Tryneus** [comment]
The Data Explorer shouldn't be doing anything different with the query or the results, the ordering of ties in the results should be a race condition based on which hash shard replies to the query first.

**Comment by mbroadst** [comment]
@Tryneus yeah I see in the source that the expected behavior should be a toss up between the two results returned but it's definitely weird that the Data Explorer returns a consistent set at least in a quick test of now ~100 executions. @AtnNn suggested perhaps there is something related to batch size with the explorer. Okay, guess we can close this :smile:

**Comment by danielmewes** [comment]
Thanks for opening an issue @mbroadst . I agree with @Tryneus that it's probably just timing related. The Data Explorer can be a lot slower than other clients, which might have an impact on how the results are batched up, which in turn might impact the ordering.

**Comment by Tryneus** [comment]
It's possible that the timing of the race condition is dependent on which thread the query originated on, and HTTP ReQL queries (i.e. from the Data Explorer) are always on the same thread.  Client connections are round-robined across the available threads, so they could be less reliable.
