### ISSUE TITLE
"NaN% cache used" on Dashboard

### ISSUE THREAD

**Issue by aranw** [rethinkdb/rethinkdb#4738]
While doing a restore I've noticed the "Resources" reads "NaN% cache used" 

https://www.dropbox.com/s/vqymbkkh27h3320/Screenshot%202015-08-21%2014.18.38.png?dl=0

I believe its possibly due to the server being busy processing the restore that it does not have the ability to respond to the requests that get the server/table/index/resource data?

Edit: After leaving it for awhile the data updates

**Comment by deontologician** [comment]
Hey @aranw, thanks for reporting this. The webui uses some of the admin tables under the hood, so its possible these tables give weird numbers resulting in a zero division or something . I'll check it out

**Comment by danielmewes** [comment]
I usually see that while the web UI is still loading the data. It's possible that this takes a moment when the database is under high load.

**Comment by aranw** [comment]
@danielmewes I think that is the case, I believe the server is under high load and that query then fails. I've also noticed not sure if related but sometimes while doing a restore the tables and database list fails to update straight away.

**Comment by danielmewes** [comment]
I think the reason this is so slow to load when the server is busy might be #4773.

**Comment by danielmewes** [comment]
Hmm actually it's still slow with #4773 fixed.
@deontologician is the query that retrieves the cache usage the same that fetches the index status? If yes, we might want to split the index status out because it can become pretty slow at the moment. Ideally we would make sure it doesn't get that slow in the first place on the server of course. I'm still looking into that.

**Comment by deontologician** [comment]
@danielmewes yes, everything for the panels on the dashboard goes in one
big query

**Comment by danielmewes** [comment]
Making `indexStatus()` always be fast on the server is probably not so easy. So I think we should split that out in the web UI (also queries that use the `jobs` table if there's anything like that in there as well).
