### ISSUE TITLE
Hang in `multi_table_manager_t` during table fuzzing

### ISSUE THREAD

**Issue by Tryneus** [rethinkdb/rethinkdb#4743]
I ran a 15 minute test of the table fuzzer (1 server, 1 client thread, changefeeds enabled, v2.1.x with fixes for #4734 #4735 and #4736), and after about 10 minutes, the fuzzer was hanging on a query.  Trying queries in the web UI with gdb attached to the process showed that while queries could run, most queries that would touch a table would hang.

The hang was observed to happen on waiting for the `new_mutex_in_line_t` acquisition of a table's `mutex` in `multi_table_manager_t::on_get_status`.  Restarting the server clears up the hang (although it did not respond to a SIGINT and had to be SIGKILLed).  There may be a deadlock in handling table mutexes in `multi_table_manager_t`.

Further runs of the fuzzer have not reproduced the bug, so it may be that it is very rare given these conditions.

**Comment by danielmewes** [comment]
We haven't seen this again afaik and don't know how to reproduce this. I'm going to close the bug until we see another instance of this.
