### ISSUE TITLE
Pid-File containing non-running pid, blocking start

### ISSUE THREAD

**Issue by RubenKelevra** [rethinkdb/rethinkdb#4745]
Sometimes the pid-file is still on disk, when rethinkdb is not running, containing a not-running pid:

`$ cat /var/run/rethinkdb/default.pid` 
`253`

`$ ps aux | grep 253` 
`ruben     1208  0.0  0.1  11260  2312 pts/0    S+   07:39   0:00 grep 253`

But still rethinkdb doesn't want to start up:

`[ruben@fulla ~]$ sudo systemctl start rethinkdb@freifunk` 
`[ruben@fulla ~]$ sudo systemctl status rethinkdb@freifunk` 
`● rethinkdb@freifunk.service - RethinkDB database server for instance 'freifunk'` 
`Loaded: loaded (/usr/lib/systemd/system/rethinkdb@.service; enabled; vendor preset: disabled)` 
`Active: failed (Result: exit-code) since Sa 2015-08-22 07:38:29 CEST; 4s ago` 
`Process: 1174 ExecStart=/usr/bin/rethinkdb serve --config-file /etc/rethinkdb/instances.d/%i.conf (code=exited, status=1/FAILURE)` 
`Main PID: 1174 (code=exited, status=1/FAILURE)`  
`Aug 22 07:38:27 fulla systemd[1]: Started RethinkDB database server for instance 'freifunk'.` 
`Aug 22 07:38:29 fulla rethinkdb[1174]: Warning: The following options are not used by this invocation of rethinkdb and will be ignored: server-name` 
`Aug 22 07:38:29 fulla rethinkdb[1174]: error: The pid-file specified already exists. This might mean that an instance is already running.` 
`Aug 22 07:38:29 fulla systemd[1]: rethinkdb@freifunk.service: Main process exited, code=exited, status=1/FAILURE` 
`Aug 22 07:38:29 fulla systemd[1]: rethinkdb@freifunk.service: Unit entered failed state.`

Rethinkdb should check, if the pid is running, else it should remove the file and start.

**Comment by danielmewes** [comment]
@AtnNn I think you have last looked into the PID file management. How is this currently working?

**Comment by RubenKelevra** [comment]
Well, actually I can't stop RethinkDB with systemd and start it again, because the pid block the start ... I know the .service file of arch is not maintained by you, but maybe you can give the maintainer of the arch-package any hint what's going wrong here...

https://projects.archlinux.org/svntogit/community.git/tree/trunk/rethinkdb.service?h=packages/rethinkdb

Best regards

Ruben

**Comment by danielmewes** [comment]
Ah that doesn't appear to actually be using our `--pid-file` option. Might be that systemd is checking the PID file before it even starts `rethinkdb`.

**Comment by danielmewes** [comment]
@anatol do you know anything about how this works with systemd? I'm not too familiar with it unfortunately.

**Comment by anatol** [comment]
@RubenKelevra please post your systemd unit file.

**Comment by danielmewes** [comment]
Hmm I think I might be wrong.
Judging from the log output it does seem to use RethinkDB's `--pid-file`.
@RubenKelevra could you post your config file from /etc/rethinkdb/instances.d/ ? Maybe that's where it's getting the `--pid-file` from.

This is also related to https://github.com/rethinkdb/rethinkdb/issues/85 btw.

**Comment by anatol** [comment]
@RubenKelevra Do you use Arch with its systemd unit file?

I believe just manually removing the pid file should fix the problem.

But it is a good idea if this file got removed automatically in case of rethinkdb process crash. See if adding `PIDFile=/var/run/rethinkdb/%i.pid` to the unit file helps with it.

**Comment by RubenKelevra** [comment]
@anatol yes I use the package from arch-repo.

[ruben@fulla ~]$ cat /etc/rethinkdb/instances.d/freifunk.conf | grep -v ^# | grep -v '^$'
pid-file=/var/run/rethinkdb/default.pid
directory=/var/lib/rethinkdb/default
bind=all
canonical-address=10.206.0.3
join=10.206.0.2:29015
join=10.206.0.5:29015
join=10.206.0.6:29015
join=10.206.0.7:29015
server-name=fulla

**Comment by danielmewes** [comment]
Ok after looking at our code it seems like - as far as the server itself is concerned - we indeed just check if the pid file exists and fail if it does.

In our init script we verify if the process ID from the pid file still exists, and if not we delete the file. We should probably move that logic into the server itself, so it can work with other startup scripts.

@AtnNn have you done any work in that direction as part of https://github.com/rethinkdb/rethinkdb/issues/3450 ?

**Comment by AtnNn** [comment]
Yes, there are some related changes that are incomplete in `atnnn/3450`.

**Comment by anatol** [comment]
BTW systemd does not need pid at all. Is there an option that disables pid files creation?

**Comment by danielmewes** [comment]
@anatol yes. @RubenKelevra you can simply remove the line `pid-file=/var/run/rethinkdb/default.pid` from your config file. Looks like it's not needed.
Note that RethinkDB uses `flock` on the data directory anyway to make sure no two instances are using the same data. This works independently of the pid file.

**Comment by RubenKelevra** [comment]
@danielmewes without this parameter it works like expected, thanks.

I've added an hint on the default config:

https://github.com/rethinkdb/rethinkdb/pull/4834

**Comment by RubenKelevra** [comment]
I think this one can be closed. :)
