### ISSUE TITLE
Out of memory when starting the server

### ISSUE THREAD

**Issue by Kamugo** [rethinkdb/rethinkdb#4750]
Rethinkdb has been running fine for months on a VPS with 4GB of RAM. Now, when I try to start the server, I get the following error:

Running rethinkdb 2.0.4~0trusty (GCC 4.8.2)...
Running on Linux 2.6.32-042stab108.2 x86_64
Loading data from directory /root/rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on addresses: 127.0.0.1, 127.0.0.2, ::1
rethinkdb: Memory allocation failed. This usually means that we have run out of RAM. Aborting.
fish: Job 1, 'rethinkdb' terminated by signal SIGABRT (Abort)

I've tried to start it using different cache sizes, but I get the same error. It works when I try to start it using another directory, so I suppose the problem is the size of my data, but I cannot start the server to remove some of it or try something different. The biggest table is about 500k documents.

**Comment by danielmewes** [comment]
Hi @Kamugo, the first thing I'd try if possible is adding a swap file (http://www.cyberciti.biz/faq/linux-add-a-swap-file-howto/). Depending on the virtualization stack used this might or might not work.

Assuming the data is somewhat distributed across tables, another way you might be able to retrieve your data is by doing the following:
1. Make a copy of your data directory (important!)
2. For each table, there is a file named after a UUID in the data directory. Delete some of them *from the copy*
3. Start rethinkdb on the copy by running `rethinkdb -d <copy dir> --cache-size 10` (note that this will recreate the deleted table files, but they'll now be empty)
4. Export your data using e.g. `rethinkdb export`
5. Repeat all steps, this time deleting another subset of the tables

**Comment by Kamugo** [comment]
I use OpenVZ so I can't create SWAP files. Rethinkdb is only starting if I delete a lot of the table files. Even starting it using three of the smallest tables (12 MB) does not work with a cache size of 2000 MB. It cannot start only with the biggest table (500MB). After removing all the tables but one, the server starts, and the web UI gives this message on the log:

Problem with reading log file on server `Tiny`: cannot parse log message (9) in:
r.db("rethinkdb").table("logs", {identifierFormat: "uuid"}).orderBy({index: r.desc("id")}).limit(20).map(function(var_74) { return var_74.merge({server: r.db("rethinkdb").table("server_config").get(var_74("server"))("name"), server_id: var_74("server")}); })

**Comment by danielmewes** [comment]
That sounds like it might be a bug. Is there a chance you can send us the data directory with only the three small tables? We can sign an NDA if necessary.
If you gzip it, it might become small enough for email (daniel@rethinkdb.com). If it's too large, please let me know and I can send you an upload link.

**Comment by Kamugo** [comment]
I've sent you the data. After downloading the data from the VPS to my laptop, I still get the same error. However, the error is a bit more specific:

rethinkdb(95834,0x700000081000) malloc: *** mach_vm_map(size=1127654424940544) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
rethinkdb: Memory allocation failed. This usually means that we have run out of RAM. Aborting.

**Comment by danielmewes** [comment]
@Kamugo Thank you for the data. It looks like there's a data corruption in the table with ID `d33563f8-342d-40cc-9644-b207a7017f3a`, that's indirectly triggering the out of memory error. We have to look into it more to find out what kind of corruption this is and where it might have come from.

**Comment by Kamugo** [comment]
Thanks Daniel. I've tried to delete the table file, but I still get the same error. Can it be possible that other tables have been corrupted?

**Comment by danielmewes** [comment]
Looks like it. :-(
I'm also seeing the problem in 11a7aad6-8b1a-449a-a7ac-69a3d3ad1ef6. I haven't checked all of the other ones.

Do you have backups? From the looks of it, those data files will be extremely hard to recover, so I recommend restoring the affected tables from the backup if possible.

I've talked with @Tryneus about this and we're currently thinking through different paths due to which this could have happen.

One scenario is that the virtualization layer doesn't pass through disk syncs properly. A few questions about that:
- What was the reason for restarting the server? Did you do a regular reboot or did it crash / was there a power outage etc?
- Are you hosting the OpenVZ setup yourself? If yes, what are the exact versions you're using (OpenVZ version, host OS, kernel version on the host)? I'm not too familiar with OpenVZ, but are there any configuration files for it that you can share? We might want to replicate your setup locally to test some things, so this would be very helpful.
- What file system(s) are you using? What are the mount options (output of `mount` on the host and/or guest)?

**Comment by danielmewes** [comment]
Also what is the underlying storage? If this is on SSDs, what model are you using?

**Comment by Kamugo** [comment]
I have a backup of about 20 days ago. I do the backups manually and I've been outside the last 2 weeks. Now, the first app has been running properly with a new rethink_data directory for some hours. I will merge the backup with the new data and write a script to generate daily backups.

It it stored in a cheap VPS because it is a personal app, so I can't get a lot of info about the virtualization layer. I'm using Ubuntu 14.04 LTS with the kernel version 2.6.32-042stab108.2 and rethinkdb 2.0.4~0trusty (GCC 4.8.2). It seems to be working over HHD.

The server was working from Aug  6 00:02 to Aug 24 14:22 (local time). That is the first time I tried to restart the server trying to startup rethink. So, it did not restart automatically. The first rethinkdb log line before this is about 15 hours before, a "Someone asked for the nonwhitelisted file".

I use two tmux sessions to start rethink and the app on rc.local. When I saw the app was not responding, the rethinkdb session was closed. This usually happens when trying to start the session and it crashes. It seems the server was restarted but it does not appear on "last reboot" command.

It seems a hardware or virtualization problem while rethinkdb was writing some table files. I'll merge the new data with the backup, write the backup script and inform you if this happens again.

**Comment by danielmewes** [comment]
Thanks @Kamugo! Definitely let us know in case you see anything like this again.

An issue with the virtualization stack not passing through disk flushes correctly seems plausible (some virtualization solutions definitely have these issues). However if this happens again, we will definitely need look into this more because it's a pretty serious issue.

**Comment by Kamugo** [comment]
Thank you @danielmewes. The day after the problem, the VPS was running very slowly and had some crashes, so I suppose it was a hardware failure. When the VPS was running well again, I imported the backup and got some problems with the indexes, but a rebuild solved the problem. Now I do a backup every day in case the problem happens again.

**Comment by danielmewes** [comment]
We just got a similar report of file corruption on OpenVZ in https://github.com/rethinkdb/rethinkdb/issues/5259 . I'm going to close this issue in favor of the newer one.
