### ISSUE TITLE
Improve query time reporting in web UI

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4752]
We should display server time by default, and only show the round-trip time on the profile tab.

**Comment by VeXocide** [comment]
How does `X-RETHINKDB-QUERY-TIME` sound as the header?

**Comment by deontologician** [comment]
looks good, I'll use that

**Comment by danielmewes** [comment]
While thinking about how to best report the query times, we also decided to no longer show query times for batched queries. The reason is that those times could only account for the first batch, and hence can be very misleading.

The timings for the first batch are still available in the profiler output if wanted.

**Comment by VeXocide** [comment]
In CR 3185 by @danielmewes.

**Comment by deontologician** [comment]
webui portion in CR 3186 by @danielmewes
