### ISSUE TITLE
Cannot set max results per query in Data Explorer

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4759]
For some reason it jumps back to the default of 40 as soon as I leave the edit field (in Firefox).

**Comment by deontologician** [comment]
Apparently this is set to a minimum of 40. In the original PR that added this (#3908) it was this way. Not sure why. I assume we should be able to set it to anything > 1?

**Comment by danielmewes** [comment]
Ah I see. Yeah, I don't see a particular reason for the minimum of 40.
