### ISSUE TITLE
Do not apply max results limit to arrays in Data Explorer

### ISSUE THREAD

**Issue by marshall007** [rethinkdb/rethinkdb#4760]
Currently, even if you chain `.coerceTo('array')` on the end of your query, the Data Explorer will limit the number of results displayed at once. It should be possible to force the Data Explorer to render all results by coercing the stream to an array.

This is necessary for doing one-off exports of data. I believe there's an issue somewhere for downloading Data Explorer results as JSON, which would be an even better solution, but I can't find it.

**Comment by marshall007** [comment]
Another solution would be to allow setting the max results limit to `0` or `-1` to indicate "unlimited". I would still prefer the solution that only applies the limit to streamed results so that you can keep the sane default set for most queries.

**Comment by danielmewes** [comment]
Do you see all results if you look at the "Raw view"?
You could also add a `.toJsonString()` to your query to get the full result as a string.

I'm actually surprised that this is working. I was under the impression that it was not, see https://github.com/rethinkdb/rethinkdb/issues/3912 .
It's currently useful to enforce the limit even for arrays, because rendering too many results disables syntax highlighting and makes the Data Explorer generally slow.

**Comment by danielmewes** [comment]
An "unlimited" setting for the limit would make sense though.

**Comment by marshall007** [comment]
@danielmewes you're right, the limits aren't being applied to arrays in 2.x at all. I was working with 1.15.x when I ran into this.

The only problems with the "unlimited" setting are 1) as mentioned above, that's not reasonable for most queries so you might have to change it frequently and 2) you have to remember to set it *before* executing the query, which is annoying if you already kicked off a long-running operation and just wanna copy the results out afterwards.

In the case of arrays, if (like you said) "Raw view" included the full results and the "Tree view" were still paged, I'd also be happy with that.

**Comment by danielmewes** [comment]
Ok that sounds reasonable. If you don't mind, I'm going to put a note in https://github.com/rethinkdb/rethinkdb/issues/3912 that we make sure to keep the raw view complete, and close this issue instead.

**Comment by marshall007** [comment]
Sounds good, thanks @danielmewes!
