### ISSUE TITLE
unable to download openssl on 10.7

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4765]
It looks like openssl.org have upgrades their SSL certificate to something that `curl` on 10.7 does not understand. So we are not unable to download the openssl library on that platform. We will have find a workaround to continue using it.

Downloading elsewhere and moving the files over is an intermediate work-around (hint: translate the dash in the name to an underscore)

**Comment by VeXocide** [comment]
It might be an option to download it from OpenSSL's FTP mirror, then check the SHA256 checksum and optionally the PGP signature.

**Comment by larkost** [comment]
A fix for this is up in the branch `larkost/4765-download-openssl`. @danielmewes will be reviewing and probably including it tonight.

**Comment by danielmewes** [comment]
Merged into `next` cf8af7c96715130271120e7d58df7e363d4c574b, `v2.1.x` efb6373e8aa062d6cc22d16563d3510de2b973d0 and `v2.0.x` 85ba8f2ac392cb960ddd7ef7d263620ff2031f09
