### ISSUE TITLE
Short-circuit chained filters?

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#4768]
When I write something like this:

```
r.table("users").filter({age: 10}).filter({foo: "bar"});
```

And the first filter doesn't return anything, I expected RethinkDB would skip altogether all the logic after, but if I run the query profile I see something like this:

```
{
"description":  "Evaluating filter." ,
"duration(ms)": 0.081655 ,
"sub_tasks": [
{
"description":  "Evaluating filter." ,
"duration(ms)": 0.060813 ,
"sub_tasks": [
{
"description":  "Evaluating table." ,
"duration(ms)": 0.028789 ,
"sub_tasks": [
{
"description":  "Evaluating db." ,
"duration(ms)": 0.009399 ,
"sub_tasks": [
{
"description":  "Evaluating datum." ,
"duration(ms)": 0.000855 ,
"sub_tasks": [ ]
}
]
} ,
{
"description":  "Evaluating datum." ,
"duration(ms)": 0.000314 ,
"sub_tasks": [ ]
}
]
} ,
{
"description":  "Evaluating make_obj." ,
"duration(ms)": 0.008454 ,
"sub_tasks": [
{
"description":  "Evaluating elements in make_obj." ,
"mean_duration(ms)": 0.000657 ,
"n_samples": 1
}
]
}
]
} ,
{
"description":  "Evaluating make_obj." ,
"duration(ms)": 0.00234 ,
"sub_tasks": [
{
"description":  "Evaluating elements in make_obj." ,
"mean_duration(ms)": 0.000366 ,
"n_samples": 1
}
]
}
]
}
```
Am I right to assume that the second filter is still taken into consideration?

**Comment by mlucy** [comment]
There may be some small constant overhead for the second filter, but if you're filtering a large table and the first filter discards all the elements then the second filter should add very little to total execution time, and that amount shouldn't change as the table gets larger.

**Comment by danielmewes** [comment]
@thelinuxlich Can you actually see performance degradation by adding more filters after a filter that let's nothing through?

**Comment by marshall007** [comment]
I hardly notice any difference in performance by chaining arbitrarily many filters after the first one produces no results. I run into `Insufficient stack space available to compile query.` long before it would become nested enough to have a noticeable performance impact.

```js
var query = r.table('test');
for (var i = 0; i <= 30; i++) {
  query = query.filter(r.row(i.toString()).eq(false))
}
query.coerceTo('array');
```

**Comment by marshall007** [comment]
The query profile doesn't make a whole lot of sense in this case, though and that's probably the confusing part. As you increase the number of chained `filter`s it makes it appear as though all of them are taking longer to execute when in reality the total round-trip time remains the same.

**Comment by thelinuxlich** [comment]
Great, I'm gonna close this
