### ISSUE TITLE
Change default db on Data Explorer

### ISSUE THREAD

**Issue by shader** [rethinkdb/rethinkdb#4770]
Maybe I just don't know how to use it properly, but when I was using the Data Explorer it assumed the database I was using (for r.table) was 'test.' This made it much more cumbersome to run queries against other dbs.

How can I change the default database for the Data Explorer queries?

**Comment by deontologician** [comment]
Hi @shader, currently you can't change the default database in the data explorer. There is another issue talking about the default database for `r.table` is "test" (#301) but I couldn't find an issue that mentions adding an option to change it in the webui.

I think this would be a relatively simple and obviously good option to have

**Comment by danielmewes** [comment]
There was a previous issue here: https://github.com/rethinkdb/rethinkdb/issues/2948. I'm going to close this one as a duplicate.
