### ISSUE TITLE
No error message when query size is over limit

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4771]
When sending a query that's larger than 64 MB, we generate an error.
It seems like this error is sometimes displayed (https://github.com/rethinkdb/rethinkdb/issues/4529#issue-94200712) , but in other cases not (https://github.com/rethinkdb/rethinkdb/issues/4529#issuecomment-130731908). Both users were using the JavaScript driver.

We should find out why @Morgul wasn't seeing the error.

**Comment by nighelles** [comment]
I think I figured this out while I was looking at raising the limit to 128.

**Comment by nighelles** [comment]
Python and Ruby were handing a broken pipe in a way that never printed the server error. I am seeing the proper error in javascript.

**Comment by nighelles** [comment]
This is in review 3463,
implemented in nighelles/4529.

**Comment by nighelles** [comment]
Fix for this is in next.
