### ISSUE TITLE
(Javascript) Make `each()` return a Promise

### ISSUE THREAD

**Issue by jorrit** [rethinkdb/rethinkdb#4780]
Each iteration of `each()` is done asynchronously. In the following code, close would be called before the second iteration of each:

```javascript
cursor.each(async (err, data) => {
  if(err) throw err;
  await dosomethingasynchronouslywithdata();
});
await conn.close();
```

Almost all methods offer the choice between a callback and a Promise. `each` is an exception: it only offers an `onFinished` callback, but it doesn't return a `Promise`. If this were done, the code would look like:

```javascript
await cursor.each(async (err, data) => {
  if(err) throw err;
  await dosomethingasynchronouslywithdata();
});
await conn.close();
```

**Comment by deontologician** [comment]
If I remember correctly, this used to be true, but it caused an issue (#3826) so we reverted it. I don't remember the specifics of why it was a problem though, it's very likely it was just an implementation bug and this could be done. I agree it looks nice

**Comment by marshall007** [comment]
I agree, basically `cursor.each(...)` should behave the same as `bluebird`'s [`Promise.each(...)`](https://github.com/petkaantonov/bluebird/blob/master/API.md#eachfunction-iterator---promise). In addition to what @jorrit mentioned, if you return a promise from the `each` callback, that promise should be resolved before continuing iteration.

**Comment by deontologician** [comment]
I'm definitely open to PRs on this, it will be a little while before I could get to it

**Comment by jorrit** [comment]
@marshall007  is right, the onFinished callback will be executed when the last iteration is started, not when it ends. Unfortunately, I never used coffeescript, but maybe I'll attempt a try. If someone else could create a PR that is even better.

**Comment by marshall007** [comment]
@jorrit I'd be happy to work on this if you haven't already started.

**Comment by marshall007** [comment]
See PR #4784. I had to implement it as a separate method, which is annoying. We could have a single method again if we changed the existing `cursor.each()` to work like this:

```js
cursor.each(function (row) {
  // existing `callback` argument
}, function (err) {
  // existing `onFinishedCallback` argument
  // `err == null` if all rows were read from the cursor
});
```
