### ISSUE TITLE
Get rid of the YAML dependency in `test-runner`

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4787]
Currently we use `PyYAML` to read the Polyglot tests, and it is a good format for simple tests. However we have quite a number of places where we actively working around it because it is trying too hard to help us (e.g.: finding dicts in the middle of our queries and blowing up when they don't make sense as that). The basic format of YAML is pretty good, but I don't think we need all of it.

So my proposal is to create our own YAML-like parser, one that is capable of parsing our current tests and allowing people to stop working around YAML. The basic requirements:
1. Allow all of the current nesting and the `key->value` nature that we use
2. Don't translate anything of the `value`s. We can do `dict` translation much better in our testing code.
3. Keep the original line numbers so we can point out the raw text for debugging (#4490)

**Comment by larkost** [comment]
This is up for internal review with CR 4784 from branch `larkost/4787-yaml-parser`.

This completely does away with the `PyYAML` dependency, but there are some things to know about the "new" format:
- For the vast majority of cases there is nothing to change.
- The main change is that the new parser is does not try to interpret the "value" section of a line. Mostly this means we don't have to work so hard to work around the format. For instance:
  - Don't double-quote string values: `'"STRING"'` -> `"STRING"
  - No need to put parenthesis around values to prevent Yaml from trying to translate them: `([])` -> `[]`
  - Dictionaries are now only translated by our string-manipulation code, so you don't have to worry about spaces after colons.
- in-line comments should be avoided since they will not be stripped or translated. For Python and Ruby this is probably not an issue, but for JavaScript it will cause errors (different in-line comment marker). Full-line comments work as expected: they are stripped out in processing.
- Having multiple tests on one line using an array no longer works, this is now interpreted as one test with an array (probably will not do the right thing). You can still have multiple commands inside a single test (i.e.: sharing the same output goal), but now have to list each one on a separate line.
- Line numbers from the Yaml file are now used as the sub-test "names". This makes it much easier to find problems.
- Yaml allows for an `array` inside a `dict` item to be at the same indent level. That over-complicated the code and looked wrong to me so I removed it. We only had one instance of this in the whole codebase.

I have also filed #4874 to document the Polyglot format.

**Comment by marshall007** [comment]
> Line numbers from the Yaml file are now used as the sub-test "names".

:+1: to this and nice cleanup all around!

**Comment by larkost** [comment]
This has been merged into `next` with c88aeabe
