### ISSUE TITLE
uninstall rethinkdb

### ISSUE THREAD

**Issue by Xbot3maSter** [rethinkdb/rethinkdb#4789]
HI,how to completely  uninstall  rethinkdb  in linux system?
i was installed it via source code make install 
but now there was no  make uninstall command 
here my problem  i want point it to other database name  but it always keep in test there that not what i want it to be 
i 'm just deleted the urs/local/bin/rethinkdb and the folder all files but  the problem still same ...
Data Explorer
i inserted this code 
r.table("documents_ops").indexCreate('v')
and then run it 
e: Table `test.documents_ops` does not exist in:
r.table("documents_ops").indexCreate("v")
^^^^^^^^^^^^^^^^^^^^^^^^                 

so now i think reinstall can be a good solution for this ....

**Comment by deontologician** [comment]
Hi @Xbot3maSter !

This just means you haven't created the `documents_ops` table. To do that just run:

```js
r.db("test").tableCreate("documents_ops")
```

in the dataexplorer. Then you can create indexes on it

**Comment by deontologician** [comment]
Closing this issue since this doesn't look like a bug, but feel free to ask more questions here :)

**Comment by Xbot3maSter** [comment]
yes i know the problem bui dont want  create in test db name...

**Comment by danielmewes** [comment]
@Xbot3maSter If you want to start with a fresh database, all you have to do is delete the RethinkDB data folder.

If you start `rethinkdb` from the command line, it will create one in the current directory.
So you just need to do `rm -R rethinkdb_data` and then restart rethinkdb.

If you use the init script to start RethinkDB, the data folder will be in `/var/lib/rethinkdb` unless you've set a different path in the instance configuration.

To use a different database than `test`, you have to create it first:
```js
r.dbCreate('my_db')
```

Then you can create a table in that database as follows:
```js
r.db('my_db').tableCreate('documents_ops')
```
... and access it like so:
```js
r.db('my_db').table('documents_ops')
```

**Comment by Xbot3maSter** [comment]
it does not work the problem still there..
i was compilng codefriends project but  face some issue in rethinkdb 

    Uploading .zips in POST /api/project
Unhandled rejection ReqlRuntimeError: Index `v` was not found on table `code_friends_test.documents_ops` in:
r.table("documents_ops").orderBy({
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    index: "v"
    ^^^^^^^^^^
}).filter({
^^^^^^^^^^^
    name: "a4a7b92dd21e41a7c70d213d725c89ec088d7294274610fd681a43d12f417188"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
}).filter(function(var_1) {
^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return var_1("v").ge(0).and(var_1("v").lt(1))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
})

so i inserted this code line in data explorer

r.table("documents_ops").indexCreate('v')


Error

Server error:

e: Database `test` does not exist in:
r.table("documents_ops").indexCreate("v")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The query that returned an error is:

r.table("documents_ops").indexCreate('v')


it suppose in code_friends_test.documents_ops  database that i created

not  in test db

**Comment by deontologician** [comment]
@Xbot3maSter can you try doing:

```js
r.db("code_friends_test").table("documents_ops").indexCreate("v")
```

**Comment by Xbot3maSter** [comment]
i had tried this command
but it came up other problems

Uploading .zips in POST /api/project
Unhandled rejection ReqlRuntimeError: Index v on table code_friends_test.documents_ops was accessed before its construction was finished in:
r.table("documents_ops").orderBy({
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
index: "v"
^^^^^^^^^^
}).filter({
^^^^^^^^^^^
name: "a4a7b92dd21e41a7c70d213d725c89ec088d7294274610fd681a43d12f417188"
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
}).filter(function(var_1) {
^^^^^^^^^^^^^^^^^^^^^^^^^^^
return var_1("v").ge(0).and(var_1("v").lt(1))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
})
how can i resolve this.?

**Comment by deontologician** [comment]
Ah, you can do this before you try to use the index:

```js
r.db("code_friends_test").table("documents_ops").indexWait("v")
```

This will ensure your index is totally done being constructed so you won't get that error. If you have a lot of data it may take a minute or two to finish building the index.

**Comment by deontologician** [comment]
You should only have to do that right after you create the index. Once it's built, you don't need to do `indexWait` every time you want to use the index

**Comment by Xbot3maSter** [comment]
yes if i do this before try to use the index:
it also ll throw  me an error;

Could Not Get getSpecificProject [Error: Error Connecting to RethindDBDatabase `code_friends_test` already exists in:
r.dbCreate("code_friends_test")

**Comment by Xbot3maSter** [comment]
just tested this command 
r.db("code_friends_test").table("documents_ops").indexWait("v")
i was wait the index building it as run the code same time

npm test

> CodeFriends@1.0.0 test /root/Downloads/CodeFriends-master
> export NODE_ENV='test'; ./node_modules/mocha/bin/mocha -t 15000 server/tests/index

config: { mysql: 
   { host: 'localhost',
     user: 'root',
     password: '',
     database: 'code_friends_test' },
  mongo: 'mongodb://localhost:27017/codeFriendsTest?auto_reconnect',
  rethinkdb: { host: 'localhost', port: 28015, db: 'code_friends_test' },
  ports: { http: 8000, editor: 9000, chat: 9001, video: 8005 },
  url: '127.0.0.1',
  github: 
   { clientID: '364ea3bc2b086177fd27',
     clientSecret: '2dce4e81ad618474f5c822b4567200b941a6c1b1' },
  timeFormat: 'YYYY-MM-DDTHH:MM:SSZ',
  tmpDirectory: '../data/tmp',
  gitRepositoriesDirectory: '../data/git-repositories' }
Chat listening on port: 9001
Editor listening on port: 9000


  Code Friends
created table: users
created table: projects
created table: templates
created table: projects_users
    Database
      User
        ✓ should create a new user (851ms)
      Project
        ✓ should create a new project (154ms)
      Template
        ✓ should create a new template (135ms)
      User/Project
        ✓ should attach user to a project (364ms)
    Auth
      - should sign up the user
      - should authenticate the user
      - should logout the user
    API
      User
        ✓ should get all of the users and their projects on GET /user (54ms)
        ✓ should get a specific user on GET /user/:username
        ✓ should create a new user on POST /user (827ms)
      Project
        ✓ should create a new project on POST /project (341ms)
        ✓ should add a user to a project on PUT /project/addUser (180ms)
        ✓ should get all of the user's projects on GET /project (68ms)
        ✓ should get a specific project on GET /project/:projectName (167ms)
        ✓ should get a specific project on GET /project/:id (225ms)
        ✓ should delete a project on DELETE /project/projectId (61ms)
        Uploading .zips in POST /api/project
Unhandled rejection ReqlRuntimeError: Index `v` was not found on table `code_friends_test.documents_ops` in:
r.table("documents_ops").orderBy({
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    index: "v"
    ^^^^^^^^^^
}).filter({
^^^^^^^^^^^
    name: "a4a7b92dd21e41a7c70d213d725c89ec088d7294274610fd681a43d12f417188"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
}).filter(function(var_1) {
^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return var_1("v").ge(0).and(var_1("v").lt(1))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
})
^^

    at Connection._processResponse (/root/Downloads/CodeFriends-master/node_modules/livedb-rethinkdb/node_modules/rethinkdbdash/lib/connection.js:184:35)
    at Socket.<anonymous> (/root/Downloads/CodeFriends-master/node_modules/livedb-rethinkdb/node_modules/rethinkdbdash/lib/connection.js:117:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
          1) should add all files in the main folder from a .zip with a parent directory
          ✓ should add all files in the main folder when uploading from .zip with no parent directory (1479ms)
        Cloning git repos through POST /api/project
          ✓ should add all files into a project when a git url (https) is passed to it (14222ms)
          - should add all files into a project when a git (git) url is passed to it
          - should add all files into a project when a larger git repo url is passed to it
      File
        ✓ should get the file structure for a project (198ms)
        ✓ should add a new file when POSTed (116ms)
Error creating new file or folder [Error: Path is Invalid or File Already Exists]
Error Creating File or Folder: [TypeError: Cannot read property 'id' of undefined]
        ✓ should throw a 400 error when a file has already been created
        ✓ should add a new folder when POSTed (116ms)
        ✓ should add a new file to a folder that was already added (170ms)
        ✓ should add a new folder to a folder that was already added (143ms)
        ✓ should add a new file to a second-level folder (114ms)
        ✓ should get the file structure when requesting a project through GET
        ✓ should upload a new file to the database (440ms)
        ✓ should upload a new file to a folder in the database (385ms)
        ✓ should download a file in the database (41ms)
        ✓ should download a file in the database that is not in the root folder (39ms)
        ✓ should download a project on GET /api/project/download/:projectNameOrId (614ms)
        Moving Files
Error creating new file or folder [Error: Path is Invalid or File Already Exists]
          ✓ should move a file from a folder to root on PUT /api/file/move (959ms)
Error creating new file or folder [Error: Path is Invalid or File Already Exists]
          ✓ should move a file from root to a folder on PUT /api/file/move (628ms)
Error creating new file or folder [Error: Path is Invalid or File Already Exists]
          ✓ should move a file from root to a folder that is within a folder on PUT /api/file/move (745ms)
Error creating new file or folder [Error: Path is Invalid or File Already Exists]
          ✓ should move a file from a folder that is within a folder to the root on PUT /api/file/move (653ms)
      Template
        ✓ should add a new template on POST api/template (160ms)
        ✓ should add a update a template name on PUT api/template/newName (118ms)
        ✓ should update a gitRepoUrl on PUT api/template/newGitRepoUrl (76ms)
        ✓ should get all templates on GET api/template/
        ✓ should delete a template on DELETE api/template/ (109ms)
Deleting All MySQL Tables
Deleting All RethinkDB Tables
Deleting Database Done


  37 passing (53s)
  5 pending
  1 failing

  1) Code Friends API Project Uploading .zips in POST /api/project should add all files in the main folder from a .zip with a parent directory:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
  
npm ERR! Test failed.  See above for more details.
