### ISSUE TITLE
Golang Client Driver Timeout not working

### ISSUE THREAD

**Issue by mdmdmdmd** [rethinkdb/rethinkdb#4800]
Trying to use the GoLang Client driver against RethinkDB 2.1.2 and Golang 1.5 x64 on linux.

The following code does not work:

gsess, gerr := r.Connect(r.ConnectOpts { 
		Address: "localhost:28105",
		Database: "nowdev",
		Timeout: time.Minute,
		})

And gives this error:

time="2015-09-05T14:58:25-06:00" level=warning msg="Error fetching cluster status gorethink: gorethink: write tcp 127.0.0.1:36174->127.0.0.1:28015: i/o timeout" 
RethinkDB test connection error: no connections were made when creating the session

The following code does work:

gsess, gerr := r.Connect(r.ConnectOpts { 
		Address: "localhost:28105",
		Database: "nowdev",
		})

**Comment by mlucy** [comment]
Hi @mdmdmdmd,

The Go driver is a community driver with a separate repository.  You'll probably get better help opening this issue there (https://github.com/dancannon/gorethink if that's the one you're using).
