### ISSUE TITLE
Show the raw Protocol Buffer query in the Data Explorer

### ISSUE THREAD

**Issue by danielcompton** [rethinkdb/rethinkdb#4801]
As a third party driver writer, it is often handy to look at the raw queries generated by the official drivers. To do that in the Data Explorer, you need to open up the browser Devtools to look at XHR requests. It would be really handy if the protocol buffer query was shown. Perhaps this could be added as part of the Raw View tab?

**Comment by danielmewes** [comment]
Hi @danielcompton , there used to be a tool to accomplish this based on the Python driver, https://github.com/neumino/rethinkdb-driver-development . It's not up to date, but I suspect it would be pretty easy to update to the latest upstream Python driver.

I'm not sure if the Data Explorer is the right place for this functionality, as it would add additional UI clutter (even if we just make it an option in the settings) for a feature that few users need.

@deontologician do you have any thoughts on this?

**Comment by deontologician** [comment]
I think a tool like that one is useful (especially in light of the minimal documentation we have now for writing drivers), but I agree it's special purpose enough that it wouldn't be good in the webui. Generally, we'd only put things there that we expect a large number of users to get a benefit from, and this will only benefit driver writers.

I opened issue #4812 to add protocol logging to the python driver, I think that would probably handle this need, and would be easy to maintain

**Comment by danielcompton** [comment]
Cool, that would also work well. Thanks!
