### ISSUE TITLE
suggestion:Using netty for the java driver's io layer or abstract it.

### ISSUE THREAD

**Issue by hepin1989** [rethinkdb/rethinkdb#4802]
Hi,I just noticed that the inprogress java driver is java8 only and using NIO directly,I have a suggestion for it.
- At least support java7(I am on java8,but not all of us I think)
- Using Netty for the I/O or making I/O layer abstract for extension.

I suggest using Netty for the I/O layer cause both grpc,redission ,mongo-java-driver and others postgres-async etc is using it,so It seems like a right way,it plus some other feature:
- Could using epoll for the linux
- Pooling support,both the Channel and the ByteBuf
- Abstract away the I/O
- Better thread model
- Back-pressure supported
- Zero copy supported for both composited ByteBuf and file transport

I think that by making use of Netty,the java driver could achieve more and have more time to optimize the user API and leveraging the Netty's optimization. 

I still suggest that first we go a simple way,later we change the I/O layer with fully async by netty,then we could just adding pooling and RS support etc.

Thanks for finally put this on table and make it come true. 
@deontologician

**Comment by kofalt** [comment]
FWIW, my understanding is that Java 7 EOL [was April 2015](http://www.oracle.com/technetwork/java/eol-135779.html):

> Developers and end-users are encouraged to update to more recent Java SE versions

Major Release | GA Date  | End of Public Updates Notification | End of Public Updates
--------------|----------|------------------------------------|----------------------
6             | Dec 2006 | Feb 2011                           | Feb 2013
7             | Jul 2011 | Mar 2014                           | Apr 2015
8             | Mar 2014 | TBD                                | Sep 2017*

Doesn't necessarily affect the decision to use netty, which sounds like a good idea; just wanted to provide some context for any RDB decision regarding support of software officially declared obsolete.

**Comment by danielmewes** [comment]
I think supporting Java 7 might be tricky, because the driver makes use of Java 8 lambdas.

I haven't looked into Netty much, but it sounds interesting.

**Comment by deontologician** [comment]
Netty looks really awesome from what I've read. Will have to do more digging.

Java 7 ReQL will be necessarily verbose, with lambdas translating to anonymous classes like this:

```java
// Java 8
foo.reduce((a,b) -> a.add(b)).run(conn);

// Java 7
foo.reduce(new ReqlFunction2(){
    public ReqlExpr apply(ReqlExpr a, ReqlExpr b) {
        return a.add(b);
    }).run(conn);
```

So a lack of lambda syntax isn't a show-stopper per-se. Internally, the driver uses the stream api (from Java 8) in a few places, but it's nothing complicated and could be replaced if necessary. In addition, while Java 7 isn't officially supported by Oracle, there are still a lot of people using it from what I have been able to tell, so official support isn't the final word (much as I wish it was since it would simplify things).

That being said, I would like to get the Java driver rock solid in Java 8 before spending time on backwards compatibility.

**Comment by hepin1989** [comment]
@deontologician In fact both ```akka``` and ```play``` now dropped java7 supported and ```scala 2.12``` is target java 8 too,and we are using Java8 in fact.So support java7 or not is your business decision,but I can see that write code java 7 is really verbos:).And code write via lambda will be a faster too:).

**Comment by hepin1989** [comment]
And maybe for the open source support ,could be Java 7 only,and for the commercial support ,maybe Java 6 +?I don't know.I really looking into the ```changes()```,which may be implemented via ```Publisher<R>```?I means will you implement the Reactive-Stream support too?

**Comment by hepin1989** [comment]
@deontologician another thing you need to think about is the ```Promise/Future```things in netty,cause it have it own and if you target java 8,would you choose the netty's or the CompletableFuture/Stage one?I will try rethinkdb asap:).

**Comment by danielcompton** [comment]
I totally get that some people have chosen to stay on Java 7 past it's EOL date, but I don't think it's reasonable to *expect* RethinkDB to write their driver for it. If it's not a lot of work then perhaps it could be worth it, but I think they'll need to make that call.

Going for Java 8 will mean that you could support the new Java Time API which would be nice.

**Comment by deontologician** [comment]
It's less that people are just expecting RethinkDB to support Java 7, and more that often it's beyond their control to change versions. In the Java thread, it's mentioned that Google app engine supports Java 7 only and doesn't seem to have any plans to upgrade. A lot of enterprise users also have restrictions on how/when they can upgrade that they aren't in control of, but would still like to use RethinkDB.

As I said, it's not my top priority, but I would like to support Java 7 eventually. There is every reason in the world for users to upgrade to Java 8 if they want to, so I'm assuming it's not a matter of will, rather circumstances preventing the upgrade.

**Comment by foliot** [comment]
Just curious, what are the expected benefits of Netty over regular Java NIO? Since both ends of the network connection are well-understood (since they're open-source and written by the same people), it seems like there wouldn't be many edge-cases to account for. On the other hand, Netty is another source of complexity and performance overhead.

**Comment by foliot** [comment]
Traditional blocking IO with one thread per connection may also be a reasonable choice, assuming there will only be a few dozen connections and they are not opened and closed frequently, though pooling would help with the latter part. This could make the driver less complex and easier to reason about.

**Comment by danielmewes** [comment]
@foliot The first post lists the motivation for using Netty. That being said we have not at all decided on Netty.

Our current plan is to support Reactive Streams in our API, which I think should work with our current I/O model and doesn't require Netty. See https://github.com/rethinkdb/rethinkdb/issues/5345 .
If we can get away with fewer library dependencies and less complexity that's certainly preferable.

**Comment by foliot** [comment]
That sounds sensible. I'll stay tuned.

**Comment by adriantodt** [comment]
The Java driver is now on a separate repo (https://github.com/rethinkdb/rethinkdb-java) and has a PR (https://github.com/rethinkdb/rethinkdb-java/pull/12) which proposes detached Socket support, so you will be implement Netty as a library or do a PR to the Java driver. Contributions are welcome! (This issue can be closed, open a new issue on the driver repository if this still is relevant)
