### ISSUE TITLE
Limit number of subprocesses for `rethinkdb export` (or use threads)

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4809]
This was brought up by @s3tqr2w in https://github.com/rethinkdb/rethinkdb/issues/2371#issuecomment-138647915 .
Apparently we currently fork one subprocess for each table in `rethinkdb export`, even if the number of clients is set to a lower number.

**Comment by s3tqr2w** [comment]
Thanks guys.  If you need any help I can assist.  I think the simplest approach would be to have a -safe option or some such that tells it not to fork off for each table.  More complex would be to manage and throttle the sub-processes somehow.

**Comment by encryptio** [comment]
In review with Marc Hesse, CR 3343.

As measured in my Ubuntu 15.04 64-bit VM, memory usage is around `15 + (17+27)*clients` megabytes across `1 + 2*clients` processes, regardless of number of tables with my change. Before, it was around `15 + 17*table_count + 27*clients` megabytes of ram across `1 + table_count + clients` processes.

In my specific test case, that meant several gigabytes of ram down to a hundred megs.

**Comment by danielmewes** [comment]
The fix shipped as part of the updated Python driver 2.2.0.post1 today.
We've also notified Compose about the update.
