### ISSUE TITLE
Config file docs use wrong config option name

### ISSUE THREAD

**Issue by rundowncreator** [rethinkdb/rethinkdb#4813]
The [config file doc page](http://www.rethinkdb.com/docs/config-file/) says "server_tag" when it should say "server-tag" in the "Supported options" section (at very bottom of the page).

**Comment by danielmewes** [comment]
Thanks for reporting this @rundowncreator .

Ping @chipotle

**Comment by danielmewes** [comment]
Moved to https://github.com/rethinkdb/docs/issues/892 . We have a separate issue tracker for documentation issues.
