### ISSUE TITLE
Execute only highlighted portion of query in data explorer

### ISSUE THREAD

**Issue by sjmueller** [rethinkdb/rethinkdb#4814]
A very useful feature is to be able to highlight a selected portion of the query, and execute only what is highlighted by the cursor:

![highlight-execute-rethinkdb](https://cloud.githubusercontent.com/assets/29085/9749096/afccba84-563e-11e5-9584-0aa2eed10066.gif)

This is pretty common in other db tools (e.g. mysql and sql server), and it would be immensely useful in data explorer.  Right now I almost always have two browser tabs open.

**Comment by deontologician** [comment]
:+1: this would be nice
