### ISSUE TITLE
getAll("", {index : "entryID"}) causes massive number of reads

### ISSUE THREAD

**Issue by zeyangl** [rethinkdb/rethinkdb#4822]
I have a table with about 5k entries.  Query with  getAll("", {index : "entryID"}) causes a massive number of reads/sec, about 4.5k seeing from rethinkdb dashboard. Is it traversing every entry in the table? Why is this happening? entryID is a secondary index.

**Comment by mlucy** [comment]
An indexed `getAll` shouldn't traverse the whole table unless every entry in your table has `""` as its value for that secondary index.  Maybe it's reading a small number of rows in a small fraction of a second and reporting that as a large number of reads per second?  If you run the query in a loop once per second, what does the graph look like?

**Comment by danielmewes** [comment]
I think the dashboard already aggregates the stats over a full second without extrapolating, so it shouldn't cause any amplification.

@zeyangl How many results does that query return?

**Comment by danielmewes** [comment]
Haven't heard back from @zeyangl in a few months and we can't reproduce. Closing.
