### ISSUE TITLE
Not a TIME pseudotype when using `during` operator

### ISSUE THREAD

**Issue by knownasilya** [rethinkdb/rethinkdb#4827]
Have something like (using version 1.13.1):

```js
r.table('dailys').filter(function (daily) {
  var timezone = '-04:00';
  var previous = r.time(previousWeek.getFullYear(), previousWeek.getMonth(), previousWeek.getDate(), timezone);
  var next = r.time(nextWeek.getFullYear(), nextWeek.getMonth(), nextWeek.getDate(), timezone);

  return daily('started').during(previous, next);
}).run(conn)
```

And get the following error:

> < { [RqlRuntimeError: Not a TIME pseudotype: `"2015-09-11T02:04:05.472Z"` in:
< r.table("dailys").filter(function(var_0) { return var_0("started").during(r.time(2015, 9, 3, "-04:00"), r.time(2015, 9, 17, "-04:00")); })
<                                                   ^^^^^^^^^^^^^^^^                                                                        ]
<   name: 'RqlRuntimeError',
<   msg: 'Not a TIME pseudotype: `"2015-09-11T02:04:05.472Z"`.',
<   frames: [ 1, 1, 0 ],
<   message: 'Not a TIME pseudotype: `"2015-09-11T02:04:05.472Z"` in:\nr.table("dailys").filter(function(var_0) { return var_0("started").during(r.time(2015, 9, 3, "-04:00"), r.time(2015, 9, 17, "-04:00")); })\n                                                  ^^^^^^^^^^^^^^^^                                                                        ' }

Have tried many alternatives, but nothing so far..

**Comment by knownasilya** [comment]
Also tried sending the data as `new Date(data.started)` to the insert/update.

**Comment by danielmewes** [comment]
That sounds like the "started" field in the "dailys" table is stored as a string. ReQL has a special data/time type that's required in order to perform time operations (such as `during`) on the data.

You can probably convert the string into a ReQL time object through the `r.ISO8601` command ( http://rethinkdb.com/api/javascript/iso8601/ ):
```js
r.table('dailys').filter(function (daily) {
  var timezone = '-04:00';
  var previous = r.time(previousWeek.getFullYear(), previousWeek.getMonth(), previousWeek.getDate(), timezone);
  var next = r.time(nextWeek.getFullYear(), nextWeek.getMonth(), nextWeek.getDate(), timezone);

  return r.ISO8601(daily('started')).during(previous, next);
}).run(conn)
```

**Comment by knownasilya** [comment]
How do I store it in that format?

**Comment by danielmewes** [comment]
@knownasilya If you put a `Date` object into a field, that should get converted during insertion:
```js
r.table('dailys').insert({..., started: new Date(...), ...}).run(...)
```

Or alternatively, to make it more explicit:
```js
r.table('dailys').insert({..., started: r.ISO8601(...), ...}).run(...)
```

**Comment by danielmewes** [comment]
I assume this wasn't a bug. @knownasilya let us know if there's still an issue.

**Comment by knownasilya** [comment]
No it wasn't thanks for following up.

**Comment by iedmrc** [comment]
> That sounds like the "started" field in the "dailys" table is stored as a string. ReQL has a special data/time type that's required in order to perform time operations (such as `during`) on the data.
> 
> You can probably convert the string into a ReQL time object through the `r.ISO8601` command ( http://rethinkdb.com/api/javascript/iso8601/ ):
> 
> ```js
> r.table('dailys').filter(function (daily) {
>   var timezone = '-04:00';
>   var previous = r.time(previousWeek.getFullYear(), previousWeek.getMonth(), previousWeek.getDate(), timezone);
>   var next = r.time(nextWeek.getFullYear(), nextWeek.getMonth(), nextWeek.getDate(), timezone);
> 
>   return r.ISO8601(daily('started')).during(previous, next);
> }).run(conn)
> ```

That answer solved my problem that I didn't realize that I caused mistakenly. I've been storing dates in a proper way but they got broken (cast string) when I did update them.
