### ISSUE TITLE
Please add the maven archetype information to the java driver "build.gradle"

### ISSUE THREAD

**Issue by eric-poitras** [rethinkdb/rethinkdb#4844]
Please add the maven archetype infos in the build.gradle so we can deploy it locally while it is being developped without having to "hack" the gradle file. (By Hack, I mead I add the group and archivesBaseName variables and I add the maven plugin)

Thanks !

**Comment by danielmewes** [comment]
@deontologician

**Comment by deontologician** [comment]
I have a pretty shallow grasp on gradle's capabilities currently, could you give me an example of what you have to change to get it to compile?

**Comment by eric-poitras** [comment]
Sure !
Here what I added so I can install it to my local repo:
```groovy
apply plugin: 'java'
apply plugin: 'maven'

version = '0.5-b1'
group = "rethinkdb"
archivesBaseName = "java-driver"


sourceCompatibility = 1.8
targetCompatibility = 1.8

//create a single Jar with all dependencies baked in
task fatJar(type: Jar) {
    archiveName = "rethinkdb-"+version+".jar"
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
    with jar
}

repositories {
    mavenCentral()
}

dependencies {
    testCompile "junit:junit:4.12"
    compile 'org.slf4j:slf4j-api:1.7.2'
    compile group: 'com.googlecode.json-simple', name: 'json-simple', version: '1.1.1'
}

buildDir = '../../build/drivers/java/gradle'
```

**Comment by deontologician** [comment]
OK, I've added this to the java-driver branch. Thanks for reporting this @eric-poitras
