### ISSUE TITLE
Changefeed results not correct on `.order_by` query (2.1.4, OS X)

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/rethinkdb#4851]
Maybe related to #4850 

Have a table full of players and I'm grabbing a random sample of them, modifying their scores and updating them. Then going and inserting new players with scores set to 0. 

[Here is a quick video of the changefeed output.](https://www.dropbox.com/s/2tue7u5z2f7sg2j/changefeed_results_not_ordered.mov?dl=0)

Notice at 0:13 that the `new_val` top document has a lower score than the `new_val` second place document and during the inserts phase the top results are the documents with `score: 0`.

**Comment by mlucy** [comment]
@dalanmiller -- do you have the script that you used to produce this?

**Comment by danielmewes** [comment]
I'm not sure if this is a bug. Note that the order in which change events are displayed in the web UI (and elsewhere) is the order in which the changes happened, not the order of the `orderBy`.

We don't currently report the "place" of a change.

**Comment by dalanmiller** [comment]
But if the results are `.ordered_by` shouldn't the documents with `score: 0` not appear in the changefeed?

**Comment by dalanmiller** [comment]
Hurr you go @mlucy. I just vomited this out to get some activity going on the Web UI for a new video. 

(Sidenote: Is this the proper way to use `.wait(...)`? )  

```python

import rethinkdb as r
import random
import time
import datetime
from pprint import pprint

conn = r.connect()

test = r.db("test").table("players")

docs_to_insert = []

for name in r.db("test").table("names").sample(250).run(conn):
    pprint(name)
    docs_to_insert.append(dict(
        name = "{} {}".format(name['first_name'], name['last_name']),
        last_updated = r.now(),
        score = random.randint(-10,10),
    ))

pprint(docs_to_insert[:5])

test.insert(docs_to_insert).run(conn)

pprint(test.count().run(conn))

while True:

    while test.wait(wait_for="all_replicas_ready", timeout=60).run(conn)['ready'] != 1:

        time.sleep(1)

    print "LOOPING OVER MODIFICATIONS"
    for player in test.sample(100).run(conn):
        test.get(player['id']).update({
            "score": player['score'] + random.randint(-10,50)
        }).run(conn)

    time.sleep(2)

    while test.wait(wait_for="ready_for_writes", timeout=60).run(conn)['ready'] != 1:
        time.sleep(1)

    docs_to_insert = []

    for name in r.db("test").table("names").sample(10).run(conn):
        docs_to_insert.append(dict(
            name = "{} {}".format(name['first_name'], name['last_name']),
            last_updated = r.now(),
            score = 0,
        ))

    print "INSERTING NEW DUDES"
    test.insert(docs_to_insert).run(conn)

    time.sleep(random.randint(2,5))

    print "READING ALL"

    for x in test.run(conn):
        pass

    time.sleep(random.randint(2,3))

```

**Comment by danielmewes** [comment]
@dalanmiller It looks like there isn't any `limit` in this query, so all changes will and should show up.

**Comment by mlucy** [comment]
Theoretically `r.table('test').orderBy(index: 'foo').changes()` should return identical results to `r.table('test').changes()` (although arguably we should instead produce an error to avoid confusing people).  Why would documents with `score: 0` not appear in the changefeed?

**Comment by dalanmiller** [comment]
@mlucy Because with using `order_by` I expect that the results are always in `score` descending order. New documents should only appear at the top of they change the ordering?

**Comment by dalanmiller** [comment]
Spoke with @mlucy, since using `.order_by( "field" ).changes() ` returns the "Cannot do changes on eager stream...etc" error also `.order_by({"index": "field"}).changes()` should (in my expectations) return the same since it cannot guarantee order in the changefeed result since it would involve loading the entire table into memory. 

If there's an efficient way to make this possible using a secondary index, then that'd be cool :+1:

**Comment by danielmewes** [comment]
@dalanmiller Would this work for you? https://github.com/rethinkdb/rethinkdb/issues/3714

**Comment by dalanmiller** [comment]
@danielmewes Yes I'd like that and think that should be implemented. But I don't think that's what I was initially trying to do here since I wasn't using `.limit( ... )`

I think though that `.order_by( ... ).changes( ... )` should be possible even if my table is large for use cases where I want to know about changes in ordering for the entire table.

**Comment by danielmewes** [comment]
@dalanmiller: You mean getting position data like described in #3714 but for the case where you don't specify a `limit`?

**Comment by dalanmiller** [comment]
@danielmewes Exactly. I mean, I could do this right now if I just specify the limit, correct? Why stop me without the limit? 

```
r.db("test").table("test").ordery_by( { index: "field" } ).limit( r.db("test").table("test").count() ).changes()
```

**Comment by danielmewes** [comment]
@dalanmiller The implementation is very different. With the limit, we keep a copy of the results within the limit in memory on the server. If you do something like this for a huge table, you'll get a lot of memory overhead. It's possible that we're also enforcing the array size limit (default: 100,000 elements) for these queries, but I'm not sure.

**Comment by danielmewes** [comment]
I'm going to close this, since it isn't actually a bug.

**Comment by dalanmiller** [comment]
If the whole table `.order_by` is infeasible then I think that it should return a similar error to when you call `.changes()` on a `.order_by` without a specified index.

```
e: Cannot call `changes` on an eager stream in:
r.db("test").table("players").orderBy("score").changes()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
```

**Comment by danielmewes** [comment]
@dalanmiller Well without the positions in each change notification, you can still maintain an ordered list of results on your client relatively easily. I'm not sure if there are actually many use cases for this, but I don't think we should disallow it in general. Once we add an option to add position data in #3714, using that flag in combination with a non-limited `order_by().changes()` would definitely return an error.
