### ISSUE TITLE
Make `table.orderby(index: ...).changes` produce an error

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#4859]

**Comment by danielmewes** [comment]
I don't think we should do this

**Comment by danielmewes** [comment]
To explain: Our ultimate goal should be that you can call `changes()` on just any query I think. Disallowing this for no particular reason would conflict with that goal.

**Comment by danielmewes** [comment]
(...that's unless there is a strong reason for doing this obviously.)

**Comment by mlucy** [comment]
The reason for doing this is that people expect `table.order_by(index: ...).changes` to behave like `table.order_by(index: ...).limit(INFINITY).changes`, but instead it behaves like `table.changes`.  This is extremely confusing -- why would ordering the table not accomplish anything?  So I think the current behavior is definitely bad.

There's an argument to be made that we should change the behavior or `table.order_by(index: ...).changes` if we found a way to make the behavior people expect efficient.  I still think we should produce an error until we can do that, though.

**Comment by mlucy** [comment]
I talked with Daniel and he made the excellent point that even though we keep around an ordering in memory on the server for `.order_by.limit` changefeeds, we don't actually expose that ordering except by having things enter and leave the set, so we actually don't have to worry about this at all unless we implement something like #3714.  Closing since this isn't actually a problem right now.
