### ISSUE TITLE
High intra-cluster network activity

### ISSUE THREAD

**Issue by nodesocket** [rethinkdb/rethinkdb#4863]
I have three servers each running RethinkDB latest `2.1.4` in a cluster. I was surprised to see so much intra-cluster network activity when I ran `nload` on the primary server *(no reads or writes happening)*.

Is it expected to burst up to `2.6 Mbit/s` with just cluster health and pings? Perhaps there is room for optimization here? Mainly just curious if this is considered normal.

![screen shot 2015-09-18 at 6 45 14 pm](https://cloud.githubusercontent.com/assets/523312/9974072/eaa24bb6-5e35-11e5-83cd-2d117fe12e3a.png)

**Comment by danielmewes** [comment]
Hi Justin,

do you have the web UI open? Sometimes the dashboard can generate quite a
bit of network traffic between the servers, especially when there are a lot
of tables.
Does the server log show any activity?

- Daniel

**Comment by nodesocket** [comment]
@danielmewes thanks for the reply. You are absolutely right, it was the web UI causing the traffic. I feel :sheep:
