### ISSUE TITLE
Write a better fuzzer for btree node code

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4870]
We've had a bunch of bugs (some of them severe) in the leaf node code (#4769, #4867) lately.

We have a fuzzer in the leaf node unit test, but it only tests insertions and deletions, and doesn't test splitting and merging.

We should write a more sophisticated fuzzer for both the leaf node as well as the internal nodes soon.

**Comment by danielmewes** [comment]
@encryptio mentioned he would like to work on this after his current project.

**Comment by encryptio** [comment]
First step (leaf node randomized tests) in review with @mlucy in CR 3278

**Comment by danielmewes** [comment]
I'd also be happy to do the code review for this one (I think @mlucy is quite busy with other things for the 2.2 release).

**Comment by mlucy** [comment]
Happy to hand it over to @danielmewes if he has the time.

**Comment by encryptio** [comment]
Leaf node tests committed to `next` in 3ea74b7

**Comment by coffeemug** [comment]
:+1:

**Comment by encryptio** [comment]
Second (and final) part, whole btree randomized tests, in review with @danielmewes in CR 3303

**Comment by encryptio** [comment]
Done, in `next` as of e9025ef.
