### ISSUE TITLE
.reconfigure will allow you to create more shards than servers where the Web UI will not

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/rethinkdb#4882]
Just got this question at the workshop, @coffeemug was able to increase the # of shards to 9 on three instances of RethinkDB via `.reconfigure ( ... )` but then went back to the Web UI and was informed that this was impossible (although already done).

**Comment by deontologician** [comment]
The reasoning was that oversharding is not useful in practice (just for trying stuff out with sharing maybe). We could change it to a warning, but the idea was to have the ui keep you from doing a bad configuration

**Comment by danielmewes** [comment]
We intentionally made this decision, like @deontologician said.

I think it's ok to allow additional things using ReQL commands that are not possible through the web UI. The main scenario for which more shards than servers are useful is for testing purposes on our end. In practice is almost never makes sense to do this, and will likely result in reduced performance.

I'm going to close this, but let me know if you think there's a better way in which we should handle this @dalanmiller .
