### ISSUE TITLE
ReqlRuntimeError

### ISSUE THREAD

**Issue by stellanhaglund** [rethinkdb/rethinkdb#4886]
by running this.

    r.db('test').table('test').filter({}).changes()

I get this error in console after some time

    { [ReqlRuntimeError: Connection is closed in:
    r.table("ledgerAccounts").filter({}).changes()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^]
      name: 'ReqlRuntimeError',
      msg: 'Connection is closed.',
      frames: [],
      message: 'Connection is closed in:\nr.table("ledgerAccounts").filter({}).changes()\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^' }

**Comment by danielmewes** [comment]
Hi @stellanhaglund, which client is this with? Is anything else going on in the application that might cause the connection to be closed?
Could you check if there are any messages in the RethinkDB server_log? The log file is usually located inside the rethinkdb_data directory, unless configured differently. You can also access the log through the web UI or by reading from the `r.db('rethinkdb').table('logs')` table.

**Comment by stellanhaglund** [comment]
Im running on node, i will check the logs and get back to you, thanks!

fredag 25 september 2015 skrev Daniel Mewes <notifications@github.com>:

**Comment by thinklinux** [comment]
I had the same problem and it turned out that I'm closing the connection because I did't check if it is a feed or a ordinary query. So my code was the reason for the problem not rethinkdb.

**Comment by danielmewes** [comment]
@stellanhaglund Any news on the logs? Is there a chance that it's related to closing connections like in @thinklinux's case?

**Comment by stellanhaglund** [comment]
Could be possible that it's the same issue but I don't see how to solve it by reading about his problem?

I mostly use change feeds, I'm  thinking that maybe my application calls the query before the connection is resolved, could this cause an error like this?

**Comment by stellanhaglund** [comment]
oops

**Comment by thinklinux** [comment]
@stellanhaglund My problem was that I have a code that connects to the database, execute some query and then when I have results or error I close the connection - `conn.close()`. When you have changefeeds you want to keep the connection open. Do you close the connection manually somewhere in you code? If you don't it's probably another issue.

**Comment by danielmewes** [comment]
@stellanhaglund Are you still seeing this?

**Comment by stellanhaglund** [comment]
So sorry i havent been more active here.

I actually found it was something so stupid as that my router was
closing the connection after 10 minutes idle :/

Sorry for the trouble!

fredag 5 februari 2016 skrev Daniel Mewes <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:

**Comment by danielmewes** [comment]
No worries @stellanhaglund, happy to hear you found the issue.

**Comment by joakimbeng** [comment]
In my case this happened even when I had a new connection open, because I forgot to also close the cursor from a changefeed query when the old connection was closed.

**Comment by GuilhermeAbacherli** [comment]
I had this error when executing a test as following:
My nodejs is listening for changes in a table (realtime),
then I simulate a connection interruption by turning off the rethinkdb docker container
and the error breaks the whole application.

I'm looking for how to handle this kind of error, so the application knows the connection was lost,
but, in some way, after a period of X minutes, try to reconnect, I don't know...

How can I proceed with this? Any thoughts? Sorry if this is not the right place to post this kind of question, but it is related.
Thanks in advance.
