### ISSUE TITLE
socket.io reference not working inside cursor.each

### ISSUE THREAD

**Issue by chris9753** [rethinkdb/rethinkdb#4887]
**Summarized Issue: Basically socket.emit() only works once or -sometimes never- inside of cursor.each.(Javascript Driver)**
I am inside an `io.on('connection',(socket)=>{ var externalSocketReference = socket; [rest of my code]}` and I have made a local reference to the socket object. Now somewhere in my code i have this 

```js
db_realtime.tableWithUserFeed('spot', id,'user')
                .then(function (cursor) {
                    cursor.each(function (err, item) {
                      externalSocketReference.emit('name',item);
// I tried referring directly to the 'socket' variable  as well.
                    });
                });
```

The only way it works(consistently) is if I add an eventListener on EventEmitter and then socket.emit() in the triggered event listener like so:
```js
db_realtime.tableWithUserFeed('spot', id,'user')
                .then(function (cursor) {
                    cursor.each(function (err, item) {
                        myOwnEventEmitter.emit('name',item);
                    });
//and then...
myOwnEventEmitter.on('name',(item)=>(socket.emit('name',item);))
```

_If anyone is aware of this issue or knows how this can possibly happen please let me know.. It is eating me up..._

**Comment by danielmewes** [comment]
@deontologician do you have any idea what could cause this?

**Comment by chris9753** [comment]
Yes, I have a theory... Basically when the socket reference is altered for instance when the id of the socket object changes because the connection is reset on the frontend it stops working;however it will work until the connection is reset... I know strange...  *Don't worry, I believe we landed on the moon...*

**Comment by danielmewes** [comment]
@chris9753 What do you mean by "the connection is reset on the frontend"? Is something resetting the RethinkDB connection? Or the socket object?

Are you getting any error by the way?

**Comment by chris9753** [comment]
@danielmewes socket.io connections disconnect and reconnect somtimes  and each time they have a different id. Typically, this behaviour shouldn't affect anything unless the reference to the socket is cached or a completely different reference entirely..... The rethinkdb connection is never reset and I received no errors. Thus, my theory is that because it stops working when i refresh the page(start a new socket.io connection) the  cursor.each sends it to clients that do not exist.. anymore..

**Comment by marshall007** [comment]
@chris9753 you'll just want to listen for `socket.on('disconnect', ...)` and cleanup any feeds you opened for that user.

**Comment by deontologician** [comment]
@chris9753's theory makes sense to me. Resumable changefeeds might make sense for this use case, where the frontend connection can be dropped and you want to pick up changes where they left off. The current strategy for this is to do as @marshall007 says and close the cursor when you get the disconnect message, then start a new changefeed when the client reconnects.

**Comment by chris9753** [comment]
Yes, or send it to an external Event Emitter inside the socket connection because it will always have the correct socket reference. This also eliminates any re-initialization logic after closing a feed.

**Comment by deontologician** [comment]
There's no good way to keep the rethinkdb cursors around between client connections currently just because most web servers are supposed to be stateless and you could get routed to another one when you reconnect. If you only have one web server you might get away with caching your cursors for some period of time in case the client reconnects.

**Comment by chris9753** [comment]
I was referring to my current solution can you foresee a problem with this pattern?
```db_realtime.tableWithUserFeed('spot', id,'user')
                .then(function (cursor) {
                    cursor.each(function (err, item) {
                        myOwnEventEmitter.emit('name',item);
                    });
//and then...
myOwnEventEmitter.on('name',(item)=>(socket.emit('name',item);))```

**Comment by chris9753** [comment]
haha, nvm, I see what you are saying...

**Comment by deontologician** [comment]
Sorry, my last comment wasn't really a response to yours, I was typing it at the same time and yours came in first

**Comment by chris9753** [comment]
No worries. =P Thx, for the insight guys!

**Comment by marshall007** [comment]
Alternatively, you can open up a changefeed on the entire table and just emit events to the relevant connected client when you receive a change. This is a more stateless approach that I've found easier to maintain, but obviously it can come at some performance cost.

```js
r.table('foos').changes().then(function (cursor) {
  cursor.each(function (row) {
    var socketId = socketIdForRow(row);
    // io.connected contains all connected clients
    var socket = io.connected[socketId];
    if (socket != null) {
      socket.emit('name', row);
    }
  })
})
```

**Comment by deontologician** [comment]
I'm going to close this for now since it doesn't seem to be a rethinkdb bug, but we can re-open it if it turns out it is. Also feel free to ask more questions here
