### ISSUE TITLE
bind to interface rather than ip address

### ISSUE THREAD

**Issue by mbroadst** [rethinkdb/rethinkdb#4911]
According to the documentation:

`bind`: Address of local interfaces to listen on when accepting connections. May be ‘all’ or an IP address, loopback addresses are enabled by default.

However, it doesn't seem possible to explicitly specify the _interfaces_ to bind to, rather only ip addresses. Is that possible? What if you want to isolate access to a certain interface which is configured via dhcp (and not all of the other potential addresses)?

**Comment by danielmewes** [comment]
It's not currently possible.

Are you actually running into a situation where the IP address is unknown / dynamic?

**Comment by mbroadst** [comment]
Yes we are unfortunately, but I think we can get around this with iptables. It occurred to me after posting this that this type of functionality would be pretty difficult to implement in rdb, and no other databases do this anyway :)
