### ISSUE TITLE
Backtrace addresses are sometimes not printed when release mode crashes.

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#4919]
See e.g. https://github.com/rethinkdb/rethinkdb/issues/4917 .

This is really bad because it makes it almost impossible to track down bugs based on user crashes.

**Comment by VeXocide** [comment]
Committed to `next` and `v2.1.x` via commits 618ce046a685023eeb33d4d9b94a5fe7c2a5f139 and 958be5c8865a966280b9ed2212060810579531d2 respectively, after an over-the-shoulder by @danielmewes.

**Comment by VeXocide** [comment]
We should investigate using `dladdr` and friends instead of the external program `addr2line` when generating backtraces.

**Comment by danielmewes** [comment]
I think it's fair to consider this fixed.
