### ISSUE TITLE
backfill jobs sometimes don't get removed

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4923]
Had some backfill jobs in the `jobs` table even though the only table was reporting all replicas to be ready, and there was no read/write activity.

**Comment by VeXocide** [comment]
In CR 3266 by @danielmewes.

**Comment by VeXocide** [comment]
Merged into `next` and `v2.1.x` via commits 5a06aa5b7fa4b4b70f3703137cc1314c779b4c74 and 6043b5a01a2e9f20a3ba6cd3e11eb5c6f08796c8 respectively.
