### ISSUE TITLE
golang driver 

### ISSUE THREAD

**Issue by gedw99** [rethinkdb/rethinkdb#4926]
https://github.com/dancannon/gorethink

it states it does not support the latest api. please clarify !!!

seriously ? no golang driver support. using the change feeds with goroutines is insanely powerful for machine learning.

**Comment by coffeemug** [comment]
From what I hear the `gorethink` driver is really good and is used quite heavily for realtime apps built on top of RethinkDB. If you know of something that isn't supported, please open an issue in the `gorethink` repo.

Closing for now, unless there is something specific I'm missing.

**Comment by mglukhovsky** [comment]
@gedw99: from their project page:

> Current version: v1.1.4 (RethinkDB v2.1)

It seems like it supports the latest version of RethinkDB -- unless I'm missing something.

**Comment by danielmewes** [comment]
@gedw99 Do you mean this note?
> Please note that this version of the driver only supports versions of RethinkDB using the v0.4 protocol (any versions of the driver older than RethinkDB 2.0 will not work).

The v0.4 protocol is actually the latest protocol. Basically this just means that the driver doesn't work with *old* versions of RethinkDB, but it works with all the current ones.

**Comment by gedw99** [comment]
All.

Thanks for clarification. I will move forward and conquer. :)
