### ISSUE TITLE
Can't query log table due to parser failures

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#4929]
Copying from the Google Group (reported by William Stein):

Something was written to the log somewhere that breaks the log table logic; querying the log table now always results in an error:

```
Problem with reading log file on server `dbstable`: cannot parse log
message (1) in:
r.db("rethinkdb").table("logs", {identifierFormat:
"uuid"}).orderBy({index: r.desc("id")}).limit(20).map(function(var_26)
{ return var_26.merge({server:
r.db("rethinkdb").table("server_config").get(var_26("server"))("name"),
server_id: var_26("server")}); })
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I think that if we can't parse a log message we should just skip it. There is absolutely no reason to throw and make the whole `logs` table unavailable.

/cc @VeXocide

**Comment by coffeemug** [comment]
In `clustering/administration/logs/log_writer.cc:120`:

```cpp
log_message_t parse_log_message(const std::string &s) THROWS_ONLY(log_read_exc_t) {
    const char *p = s.c_str();
    const char *start_timestamp = p;
    while (*p && *p != ' ') p++;
    if (!*p) throw log_read_exc_t("cannot parse log message (1)");
    ...
```

Not sure how a string with all whitespace made it into the log file, but it sounds like if `parse_log_message` throws we should just carry on our merry way without propagating this all the way up and breaking the whole query.

**Comment by VeXocide** [comment]
On it.

**Comment by VeXocide** [comment]
In CR 3267 by @danielmewes.

**Comment by mlucy** [comment]
I think skipping unparseably log messages is a bad idea.  In this particular case where there was a bunch of unexpected whitespace that's what you want, but if it's an important log message that we couldn't parse for some reason you still want to inform people that it exists.

I think we should instead return a `log_message_t` with `log_level_error`, the current time as the timestamp, and an error message saying something like "unparseable log message `%s`" with the literal message in the string.

We should also try to figure out how we wrote a line of all whitespace to the log file.  Do we have the log file in question?

**Comment by coffeemug** [comment]
> I think we should instead return a `log_message_t` with `log_level_error`, the current time as the timestamp, and an error message saying something like "unparseable log message `%s`" with the literal message in the string.

:+1: that sounds like a really good idea.

We don't have the log file, but maybe William could provide it.

**Comment by VeXocide** [comment]
Injecting a log message turned out to be rather tricky due to their timestamps being the primary key of the `rethinkdb.logs` table, thus having to be unique, as well as being used as the basis for changefeeds on the table. Instead we will log an actual error, at most once, which should show up next time it's queried.

In CR 3269 by @danielmewes.

**Comment by VeXocide** [comment]
Merged into `next` and `v2.1.x` via commits 68a386043e4d8b79582484b09fae8cc759d2ab7c and 45f2761a59558603082efd4caebebb32d991cbe0 respectively.

**Comment by williamstein** [comment]
> We don't have the log file, but maybe William could provide it.

Yep, I have them all.    I'll provide them soon.

**Comment by williamstein** [comment]
I've emailed the logs do Daniel, Michael, and Slava. (Didn't want to post them publicly.)  Thanks!

**Comment by danielmewes** [comment]
Thank you @williamstein! Got them.
