### ISSUE TITLE
Detect non-transitive connectivity and display an issue

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4936]
Occasionally users have run into cases of non-transitive connectivity without realizing it.
This often happens when the canonical-address isn't configured correctly, or if their servers are behind a firewall.

I believe servers already communicate which other servers they can see. We should detect inconsistencies in the connectivity data and raise an issue in the `current_issues` table if that's the case.

**Comment by danielmewes** [comment]
Note that often such clusters run seemingly without issues (as long as users connect to the "right" servers), but then when a server fails automatic failover doesn't happen etc.

**Comment by nighelles** [comment]
This is in review 3504,
Implemented in nighelles/4936

**Comment by nighelles** [comment]
This is in next.
