### ISSUE TITLE
@question where to consult your service pricing?

### ISSUE THREAD

**Issue by AlexLuya** [rethinkdb/rethinkdb#4939]
Hello,       
       I have filled the form in http://www.rethinkdb.com/services/,and result  page told me that your guys will contact me soon,but after 2 days,no any response to me  neither in phone nor in email box.Why?
     (Sorry to ask here,google group can't be used in China)

**Comment by ericrethinkdb** [comment]
@AlexLuya,  I have sent you an e-mail privately.  We apologize for the delay!
