### ISSUE TITLE
Response code 18 missing on 'writing drivers' page

### ISSUE THREAD

**Issue by pixelspark** [rethinkdb/rethinkdb#4944]
https://rethinkdb.com/docs/writing-drivers/ does not mention response code 18 (runtime error). It is however defined here: https://github.com/neumino/rethinkdbdash/blob/master/lib/protodef.js.

**Comment by mlucy** [comment]
Thanks for the report!  I moved this to our docs repo: https://github.com/rethinkdb/docs/issues/919 .

**Comment by pixelspark** [comment]
:+1:
