### ISSUE TITLE
No repo for Ubuntu 15.10 wily

### ISSUE THREAD

**Issue by internalfx** [rethinkdb/rethinkdb#4946]
Any idea when a wily build might show up?

Release is less than 2 weeks away.

**Comment by danielmewes** [comment]
:+1: We don't have an estimate yet, but will try to get it ready on time (or at least for the next release). 
Until then, the package for Ubuntu vivid might work, but I haven't tested it.

**Comment by AtnNn** [comment]
I've added wily-i386 and wily-amd64 to the buildbot.

**Comment by internalfx** [comment]
Thanks guys, I tried to force the vivid package. but I had problems with `libprotobuf9`.

Wily only offers `libprotobuf9v5`, didn't work when I tried it. Not an expert on packages....

**Comment by danielmewes** [comment]
@AtnNn Awesome! Is there anything else to do to get the repository working with the next upload (e.g. changing the scripts in rethinkdb-download repo)?

**Comment by AtnNn** [comment]
@danielmewes It should just work.

**Comment by felixis-1** [comment]
Ubuntu 15.10 got released today. But the standard installation procedure does not work. Any idea when it will become available?

**Comment by internalfx** [comment]
@felixis-1 got around the issue for now by running it with docker

**Comment by internalfx** [comment]
For others with this issue...

- [Install docker](https://docs.docker.com/installation/ubuntulinux/)
- Add yourself to docker group `sudo usermod -aG docker ubuntu`
- Reboot or logout/login
- `docker run -d -p 8080:8080 -p 28015:28015 -p 29015:29015 --name rethinkdb -v "WHERE-YOU-WANT-TO-PUT-YOUR-DATA:/data" rethinkdb:2.1`

**Comment by danielmewes** [comment]
@felixis-1 Thanks for the reminder. We'll try to get a repository up today.

**Comment by danielmewes** [comment]
The Ubuntu Wily repository is up with packages for RethinkDB 2.1.5-2.
The install instructions from http://rethinkdb.com/docs/install/ubuntu/ should now work.
