### ISSUE TITLE
Error: [request.last_included_term == ps().log.prev_term]

### ISSUE THREAD

**Issue by mbroadst** [rethinkdb/rethinkdb#4949]
Looks like we've run into another crash on a small cluster (three nodes), I've manually expanded the backtrace:

```
2015-10-13T11:34:37.047697588 96.109902s error: Error in ./src/clustering/generic/raft_core.tcc at line 552:
2015-10-13T11:34:37.047763158 96.109967s error: Guarantee failed: [request.last_included_term == ps().log.prev_term] The entry we shapshotted at was committed, so we shouldn't be receiving a different committed entry at the same index.
2015-10-13T11:34:37.047803579 96.110007s error: Backtrace:
2015-10-13T11:34:37.926402621 96.988611s error: Tue Oct 13 11:34:37 2015
1 [0xa0f920]: backtrace_t::backtrace_t() at ??:?
2 [0xa0fcb3]: format_backtrace(bool) at ??:?
3 [0xc440b5]: report_fatal_error(char const*, int, char const*, ...) at ??:?
4 [0xa5c871]: raft_member_t<table_raft_state_t>::on_install_snapshot_rpc(raft_rpc_request_t<table_raft_state_t>::install_snapshot_t const&, raft_rpc_reply_t::install_snapshot_t*) at ??:?
5 [0xa5c9c8]: raft_member_t<table_raft_state_t>::on_rpc(raft_rpc_request_t<table_raft_state_t> const&, raft_rpc_reply_t*) at ??:?
6 [0xa5cb91]: raft_networked_member_t<table_raft_state_t>::on_rpc(signal_t*, raft_rpc_request_t<table_raft_state_t> const&, mailbox_addr_t<void (raft_rpc_reply_t)> const&) at ??:?
7 [0xa652a4]: mailbox_t<void (raft_rpc_request_t<table_raft_state_t>, mailbox_addr_t<void (raft_rpc_reply_t)>)>::read_impl_t::read(read_stream_t*, signal_t*) at ??:?
8 [0x953f72]: /usr/bin/rethinkdb() [0x953f72] at 0x953f72 ()
9 [0x933748]: coro_t::run() at ??:?
2015-10-13T11:34:37.926632057 96.988836s error: Exiting.
```

**Comment by mbroadst** [comment]
This one is a persistent crash btw

**Comment by coffeemug** [comment]
cc @timmaxw 

Tim, do you have a theory on what could be going on here?

**Comment by VeXocide** [comment]
Over IRC @mbroadst provided me with the following information.

```
19:03 <mbroadst> (first of all it seems much easier to reproduce this on an isolated network that can't e.g. allow ntpdate to run and sync time)
19:03 <mbroadst> so set the physical machine to a 10s time skew from the other two
19:03 <mbroadst> that one is the primary replica for some tables
19:03 <mbroadst> join two other nodes to that primary
19:03 <mbroadst> <wait some indeterminant amount of time>
19:04 <mbroadst> <maybe do some other operation, like reconfigure a table - still investigating this part>
19:04 <mbroadst> then the crash happens 
19:04 <mbroadst> the maybe operation is not necessarily required
```

@timmaxw -- note the time skew here, could this impact anything?

**Comment by timmaxw** [comment]
Nothing pops out at me as the cause of this bug.

If the bug is in the core Raft implementation, then the clock skew is probably unrelated. The core Raft algorithm doesn't ever pass system clock timestamps back and forth across the network. But I wonder if what we're seeing is cross-talk between different Raft instances--perhaps different epochs of the same table. The system clock is used to assign epoch timestamps, so it's possible that the clock skew could affect that somehow.

The output of `r.db("rethinkdb").table("_debug_table_status")` might point to the cause. @VeXocide, are you working on reproducing it locally?

**Comment by mbroadst** [comment]
@timmaxw I've just uploaded the tarball of the data dir to you guys. Can't run `r.db("rethinkdb").table("_debug_table_status")` since the bug crashes the server on all subsequent runs unfortunately.

**Comment by VeXocide** [comment]
I'm closing this issue as I strongly suspect this was caused by the same issue that caused #4979. Since that was fixed I haven't been able to reproduce it using the fuzzer either. Were it to rear its ugly head again I'll reopen it.

**Comment by VeXocide** [comment]
I'm reopening this as well since @danielmewes just saw #4979 again on`next`.

**Comment by danielmewes** [comment]
This was likely fixed by the fix for https://github.com/rethinkdb/rethinkdb/issues/5289#issuecomment-176374215
