### ISSUE TITLE
r.asc('foo') returns 'foo'

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#4951]
It uses to throw an error in 2.0.

If `r.asc` is nested, I'll get the expected error
```
ASC may only be used as an argument to ORDER_BY.
```

**Comment by neumino** [comment]
Just to give a bit of context, I had a test in reqlite testing for the error using `r.asc('foo')`. I'm not sure anyone else will actually write this query.

**Comment by pritambaral** [comment]
Bug introduced in https://github.com/rethinkdb/rethinkdb/commit/4d0a80e56eac6a7d9baf15bae762b8304a4984f7#diff-5f5f60e255e349a06cc62ee7c7fa20d2R84, and tracked to `2.1.5` through https://github.com/rethinkdb/rethinkdb/commit/1cd2122d4adbaed71601dc278070a29c8d37771e#diff-5f5f60e255e349a06cc62ee7c7fa20d2R117

Readying PR

**Comment by coffeemug** [comment]
Thank you @pritambaral! (Also we should add a test on this to polyglot tests)

**Comment by coffeemug** [comment]
Also, /cc @Tryneus for completeness.
