### ISSUE TITLE
Undefined variable 'o' in Python encoder

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4955]
I'm not sure if this line is ever hit, but I'm pretty sure that the `o` in https://github.com/rethinkdb/rethinkdb/blob/next/drivers/python/rethinkdb/ast.py#L701 should be `obj`.

**Comment by grandquista** [comment]
It seems to never be hit in my usage. I'm updating my latest PR still.

**Comment by danielmewes** [comment]
Thanks @grandquista! I also didn't hit this in practice. Just noticed it when looking at the code.

(@Tryneus is currently out of office, but he'll be back next week to look at the PR. So we should be able to get it all in on time for 2.2)

**Comment by grandquista** [comment]
r.expr filters out any object of type that would trigger that line. I was looking at removing recursion from r.expr and that change would definitely trigger the line in some use cases. The line throws in either case. Fixing it just means the right error is thrown.
