### ISSUE TITLE
Error importing data upgrading from 2.1.3 to 2.1.5

### ISSUE THREAD

**Issue by csaintc** [rethinkdb/rethinkdb#4957]
When attempting to restore data from a 2.1.3 version of rethinkdb, it throws this error:
```
rethinkdb restore rethinkdb_dump.tar.gz
Unzipping archive file...
  Done (0 seconds)
Importing from directory...
ReQL error during 'tables check': Table `local.Group` is ambiguous; there are multiple tables with that name.
Error: rethinkdb-import failed
puter:~$ rethinkdb --version
rethinkdb 2.1.5+2~0trusty (GCC 4.8.2)
puter:~$
```

Everything restores fine on 2.1.3:
```
Unzipping archive file...
  Done (0 seconds)
Importing from directory...
[========================================] 100% 
3230 rows imported in 22 tables
  Done (5 seconds)
 krusty  ~/workspace/backups/google-rethinkdb-backups/google-rethinkdb-backups  docker exec -it rethinkdb /bin/bash
root@a5a1196afe32:/data# rethinkdb --version
rethinkdb 2.1.3~0jessie (GCC 4.9.1)
root@a5a1196afe32:/data# exit
exit
```

**Comment by csaintc** [comment]
I've managed to get past this hurdle:

The problem was that I had a 3 db shard, and when I attempted to restore, the shard created a bunch of duplicate database ( probably an issue with replication ), which confused and frightened rethinkdb.

The cluster was already established by the time I attempted the restore, so I'm unsure of why my cluster split-brained like that.

**Comment by danielmewes** [comment]
Hi @csaintc, sorry you had to run into this issue.
When you restored into the new cluster, were the tables created externally by some separate script, or did you just let `rethinkdb restore` take care of table creation?

I think `rethinkdb restore` should never generate table name conflicts. It sounds like there might be a bug or something else odd going on.

**Comment by csaintc** [comment]
@danielmewes Yeah, I just used restore.

What I did exactly was:

log into my staging environment which is running rethinkdb 2.1.3, dump / copy the data

log into my dev environment running 2.1.5, and attempt the restore.

**Comment by danielmewes** [comment]
We haven't seen this again as far as I know. It might have been something special about the setup.
If we encounter it again, we can re-open the issue.
