### ISSUE TITLE
Set default db for dashboard

### ISSUE THREAD

**Issue by Suvitruf** [rethinkdb/rethinkdb#4960]
For now we should every time specify db:

`r.db("MyDB").table("MyTable")`
  
Is it possible to set default db for Rethink Data Explorer?

**Comment by danielmewes** [comment]
Hi @Suvitruf, this is not possible at the moment.
We're planning to add this feature in one of the upcoming releases. See https://github.com/rethinkdb/rethinkdb/issues/2948 .
