### ISSUE TITLE
Handle openssl dependency in MacOS X 10.11

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4963]
In the latest version of MacOS X (10.11 or El Capitan) the OpenSSL library is present, but the headers are not, even with Xcode command-line tools installed. This is intentional, and is the next ratchet in Apple's slow depreciation of OpenSSL.

The main work-around is easy, just add `--fetch openssl` to the `./configure` invocation, but we need to strengthen our checks in that script to ensure that we pickup the lack of headers and complain about it during `./configure` rather than at compile time.

**Comment by larkost** [comment]
I accidentally `push`ed this to `next` rather than `publish`ing it to a new branch... whoops. However @VeXocide has now reviewed it, so we are not going revert the change.

The addition makes sure that we can compile with OpenSSL as given, and seems both to fail (with OpenSSL and no headers) and succeed (with `--fetch openssl` and with a valid OpenSSL install) as expected both on my machine and `newton`.

**Comment by danielmewes** [comment]
@larkost Can you also backport it to `v2.2.x` please?

**Comment by larkost** [comment]
@danielmewes: sure, done with dc0a1298
