### ISSUE TITLE
How to get the latest information?

### ISSUE THREAD

**Issue by DylanLyu** [rethinkdb/rethinkdb#4967]
Information Content:
{
"Name":  "Dylan" ,
"Password":  "456" ,
"Timsampe": 1445225320 ,
"Uid": 0 ,
"id":  "b251c17c-858b-4012-8829-6f461e000cbf"
} {
"Name":  "Dylan" ,
"Password":  "456" ,
"Timsampe": 1445225535 ,
"Uid": 0 ,
"id":  "df8e92c5-9a56-454e-91b0-a03f164a57b0"
}

i try Data Explorer SQL,but error
e: Cannot take the max of an empty stream.  (If you passed `max` a field name, it may be that no elements of the stream had that field.) in:
r.db("market").table("users").filter({Name: "Dylan", Password: "123"}).max("Timsampe")

i try r.db("market").table("users").filter({Name: "Dylan", Password: "456"}).max("Timsampe") is ok!

Any thoughts would cause a problem like this?
For not find the information.
My usage error ???
I just want to get updated information.
if the search is not find should be the return null not Instead of error.

**Comment by chrisvariety** [comment]
You should be able to use `default` to achieve this, something like:

`r.db("market").table("users").filter({Name: "Dylan", Password: "123"}).max("Timsampe").default(null)`

More info at https://rethinkdb.com/api/javascript/default/

**Comment by DylanLyu** [comment]
thx!To solve!
