### ISSUE TITLE
audit python driver with pylint

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4969]
We should probably run `pylint` on the Python driver, and audit the output of that to find changes we should make. This is something we should do periodically, but a first pass is probably going to be bad, and will involve deciding what linters we want to turn off.

**Comment by gabor-boros** [comment]
Currently codacy is checking the python driver with pylint, bandit and more so closing this issue. In case of any question please open an issue at rethinkdb/rethinkdb-python repo 😇
