### ISSUE TITLE
Crash when table fuzzing, Guarantee failed: [request.last_included_term == ps().log.prev_term]

### ISSUE THREAD

**Issue by Tryneus** [rethinkdb/rethinkdb#4975]
Ran into this crash on `v2.1.x` (a007331) when running the table fuzzer with `table_fuzzer.py --servers 7 --threads 48 --changefeeds --kill`.  I promptly deleted the log file and no longer have the backtrace.  Will keep trying to see if I can reproduce it.

The guarantee in question is `clustering/generic/raft_core.tcc:550`: `"The entry we shapshotted at was committed, so we shouldn't be receiving a different committed entry at the same index."`

**Comment by VeXocide** [comment]
This is a duplicate of #4949.
