### ISSUE TITLE
Web UI fails with "The request to retrieve data failed" if there's a table with a deleted DB

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4985]
![deleted db](https://cloud.githubusercontent.com/assets/505365/10675229/e1634c38-78b3-11e5-994c-32b196d34e1f.png)

The full ReQL error message is "Database `__deleted_database__` does not exist."

* Why is the error message not rendered?
* We need to handle this error gracefully.

To get a table with a deleted database for testing, it's currently enough to create a database + table, and then delete the DB's document from `db_config`.

**Comment by nighelles** [comment]
This is in review 3495, implemented in nighelles/4985

**Comment by nighelles** [comment]
This is in next.
