### ISSUE TITLE
Non-transitive connectivity from the python test framework when killing and restarting servers

### ISSUE THREAD

**Issue by Tryneus** [rethinkdb/rethinkdb#4987]
This came up when debugging `table_fuzzer.py` using the `--kill` command.  While initial startup of the cluster works fine, if we then kill all the servers and then start them all again, the newly started servers will not be given a `--join` option, and will be cut off from their peers, wandering endlessly.

**Comment by danielmewes** [comment]
Pinging @larkost

**Comment by larkost** [comment]
@danielmewes: I actually asked @Tryneus to post this one. I don't think it will be too difficult to do, but it will require a lock in the `start()` method of `Process()` (grr... bad name) objects in the `driver` (grrr... grr... really bad name) module. I think that I already know how that is going to work.

**Comment by larkost** [comment]
This has been merged into `next` with 7fb331fe.
