### ISSUE TITLE
Migration from 1.13 over 2.0.5 to 2.1 fails

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4991]
Reported by a user in https://groups.google.com/forum/#!topic/rethinkdb/cynZc-_Z-DE

I could reproduce the problem by following his steps. I additionally created two tables on 1.13, one with a single index and one without indexes.

**Comment by danielmewes** [comment]
Wow, actually this happens even without every creating any table!

**Comment by Tryneus** [comment]
Fix is up in review 3298.  Still no ideas on why this didn't happen before.

**Comment by Tryneus** [comment]
The fix has been approved and merged to `next` and `v2.1.x` in commits cb8f595 and b21ead6, respectively.  Will be in release 2.1.6.
