### ISSUE TITLE
Rethinkdb deployment via cloudformation

### ISSUE THREAD

**Issue by rajanshah** [rethinkdb/rethinkdb#4998]
This is somewhat unrelated to rethinkdb itself, but RethinkDB deployment to AWS question.

I am trying to deploy rethinkdb via custom chef cookbook on AWS. Is there anyway, one can assign canonical name to Rethinkdb EC2 instance up-front?

This will allow limited changes to downstream configuration files, which allow clients to connect to RethinkDB host.

**Comment by danielmewes** [comment]
Could you explain a little bit more what you mean by "canonical name"? Do
you mean a RethinkDB server name (like displayed in RethinkDB's
configuration tables and the web UI)? Or a DNS name that clients can use to
connect to it?

**Comment by danielmewes** [comment]
Haven't heard back from @rajanshah. Closing.
