### ISSUE TITLE
Remove generic parameter on Java connections

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#5002]
Copied from @eric-poitras 's comment: https://github.com/rethinkdb/rethinkdb/issues/3930#issuecomment-139841060

> it is useful for Connection to be a Generic type ? Java can be a bit strange in the way he handle generics and sometime it's just better to avoid it. Here a sample case of what I am talking about:

```java
public class SomeClass implements SomeApi {

    private final Db         db;
    private final Connection conn;

    @Inject
    public SomeClass( Db db, Connection conn ) {
        this.db = db;
        this.conn = conn;
    }

    @Override
    public List<Device> listDevices() throws ApiException {
        Cursor<Map<String, Object>> c = db.table( "test" ).run( conn );
    }
```

> The line: `Cursor<Map<String, Object>> c = db.table( "test" ).run( conn );` won't compile because I did not defined the variable conn as a generic type `Connection<?>` then java call the "run" method in JDK 1.4 style so it returns Object instead of `<T>`. (By the way, IntelliJ error highlighter don't event see this as a problem, it's javac that throws an error !).

I agree the connection parameter was a dumb idea on my part, it parameterizes over something no one ever cares about, and the subtype system should be fine to define other kinds of connection behaviors when necessary.

**Comment by bchavez** [comment]
+1 when I did the port of `Connection.java` I left the generic out also...

https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver/Net/Connection.cs#L12

**Comment by deontologician** [comment]
I've done this, it's in code review now
