### ISSUE TITLE
Remaining build system integration for the java driver

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#5004]
Currently the java driver is not fully integrated into our existing build infrastructure. I've created a makefile and maybe 3/4ths of what's needed, but this will probably require @AtnNn 's touch to make sure all of the t's are dotted and i's crossed.

Some issues I know of:
1. Dependencies are not handled (except for java library dependencies)
   - it assumes gradle 2.7+, java 8, python and mako are all installed on the system and in the path etc.
2. Make is not being utilized to skip builds of files that are already built
   - metajava.py does a make-like timestamp check, but it's a little flaky. I didn't use make because the files being included is pretty dynamic and I didn't want to hard code them all into the make file. There may be a better way to do this I'm not aware of.
   - this only means from template -> java file conversion with metajava.py. Gradle handles java compilation stuff just fine once the java files are output.
3. `make publish` and `make test` are not implemented (see also #5001 for deploying todos)

**Comment by larkost** [comment]
We already have a dependency on Python2.x, so that is an existing one. But I would not want to add Python3.x, since that is much rarer. Why is this Python3.x specific?

I have not yet formed an opinion on the rest of the dependencies.

**Comment by deontologician** [comment]
Sorry, I updated the issue. metajava.py isn't python3 specific, only `convert_tests.py` is (it needs to be able to distinguish between byte literals and string literals in the ast).

**Comment by adriantodt** [comment]
The Java driver now lives in https://github.com/rethinkdb/rethinkdb-java, and since the drivers got split from the main repo, this issue doesn't seems to be relevant anymore. This issue can be closed.
