### ISSUE TITLE
Implement profiles in the Java driver

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#5006]
Currently a Profile object is created when a response is formed, but nothing can be done with it, and it just stores the raw hashmap of the profile rather than doing anything useful with it.
1. The Profile object should be something useful and convenient for end users
2. The profile should be exposed in some way if it's present. Probably by changing runQuery to return some object that has both a result and a profile.

**Comment by adriantodt** [comment]
The Java driver now lives in https://github.com/rethinkdb/rethinkdb-java. I opened an issue so we can finally implement this into the driver. This issue can be closed.
