### ISSUE TITLE
Create a convenient way to do pathspecs in the java driver

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#5007]
Right now pathspecs are kind hairy due to Java's lack of nice hashmap and List literals:

in javascript: 

``` js
r.table('foo').filter({x: {y: {z: "bar"}}})
```

turns into the java query:

``` java
r.table("foo").filter(r.hashMap("x", r.hashMap("y", r.hashMap("z", "bar"))))
```

Since depth-first is more common in path-specs than breadth first, it might make sense to have a special `r.pathspec` convenience that creates the appropriate hashmap structure. It might look something like:

``` java
r.table("foo").filter(r.pathspec("x", "y", "z", "bar"))
```

I haven't really thought about branching pathspecs too much, maybe there's no syntax that would work well. It's something to think about.

**Comment by deontologician** [comment]
I've been looking over the new Java docs and I'm more convinced than ever this is necessary. Some of the simplest examples are downright terrifyingly verbose due to a lack of good pathspec syntax

**Comment by adriantodt** [comment]
The Java driver now lives in https://github.com/rethinkdb/rethinkdb-java. I opened an issue so we can finally implement this into the driver. This issue can be closed.
