### ISSUE TITLE
Implement Stream<T> for queries or cursors in the java driver

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#5008]
Not sure if this is a good idea, but it's something we might consider. The Stream interface is for specifying lazy operations on a stream. Many of the existing stream operations map to reql terms, or could be implemented on top of the Cursor object.

**Comment by danielmewes** [comment]
That's actually a neat API. Very close to ReQL.

**Comment by adriantodt** [comment]
I implemented this without even knowing that this issue existed. This is now implemented to one of the branches (https://github.com/rethinkdb/rethinkdb-java/pull/7) and replaced with reactive streams on another branch of the Java driver, which now lives in a separated repository (https://github.com/rethinkdb/rethinkdb-java). This issue can be closed.
