### ISSUE TITLE
Refactor Java driver ConnectionInstance class so that checkOpen is obviated

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#5009]
Right now we have lots of `checkOpen` calls in the Java driver ConnectionInstance class. This is a leftover from basically copying the python driver's implementation 1-1. A more java-esque way to do this would be to have a ConnectionInstanceBuilder that ensures you can't have a null socket inside a ConnectionInstance once it's created. The connection already destroys connectionInstances whenever it detects the socket is closed, so there's no real reason to have the ConnectionInstance be tolerant of missing sockets.

**Comment by danielmewes** [comment]
Can you post a code example of how the `ConnectionInstanceBuilder` API would work? Or would this all be internal to `Connection` and not exposed to the user at all?

**Comment by deontologician** [comment]
Yeah, this would be how the Connection creates a new ConnectionInstance, it wouldn't be a public api

**Comment by adriantodt** [comment]
This issue is not relevant anymore as ConnectionInstance doesn't seems to exist in v2.4.0. This issue can be closed.
