### ISSUE TITLE
Add pretty-printed output for toString on java driver AST classes

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#5012]
Right now the toString implementations are empty. We should do like the other drivers and implement some pretty printer so exceptions are formatted more nicely. This will probably also make backtraces ( #5005 ) more useful as well

**Comment by adriantodt** [comment]
The Java driver now lives in https://github.com/rethinkdb/rethinkdb-java. I opened an issue so we can finally implement this into the driver. This issue can be closed.
