### ISSUE TITLE
Make sure EventEmitter in the JS driver has a `done` event

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#5030]
Currently the EventEmitter cursor API in the JS RethinkDB driver doesn't seem to have a `done` event, so it's impossible to tell when the cursor is closed (according to @Tryneus).

We should add a `done` event that gets fired when the cursor is empty, and document it properly.

/cc @deontologician

**Comment by deontologician** [comment]
I think this is a dupe of #2577

**Comment by danielmewes** [comment]
That sounds right. Closing in favor of #2577.
