### ISSUE TITLE
interface.table_fuzzer shouldn't require unlimited core file size, or should set it itself

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5036]
When running `interface.table_fuzzer` through `test/run` I'm getting the following failure:
```
Traceback (most recent call last):
  File "/home/ssd3/daniel/rethinkdb/test/interface/table_fuzzer.py", line 19, in <module>
    assert resource.getrlimit(resource.RLIMIT_CORE)[0] == resource.RLIM_INFINITY
AssertionError
Command '$RETHINKDB/test/interface/table_fuzzer.py' returned non-zero exit status 1
```

My core file size limit is indeed set to 0, but I think the test should still run.

(pinging @Tryneus and @larkost )

**Comment by VeXocide** [comment]
I changed the assert to a warning via commit 74333d401066927d03c3fb1449410da8a6467fec which has been merged into `next`. We might want to have `run` perform this check?

**Comment by danielmewes** [comment]
Was addressed by https://github.com/rethinkdb/rethinkdb/commit/74333d401066927d03c3fb1449410da8a6467fec
