### ISSUE TITLE
Populate array of keys while joining

### ISSUE THREAD

**Issue by olasfar** [rethinkdb/rethinkdb#5050]
Hey guys,

I wasn't able to populate a list of keys while joining on an other table so I was wondering if my models are correct and if what I'm trying to do is possible with Thinky, here is my code:

`Group` model
```
  var Group = thinky.createModel('group', {
      users: [thinky.type.string()],
      place_id: thinky.type.string()
  });
```
`User` model
```
  var User = thinky.createModel('user', {
      name: thinky.type.string()
  });
```
`Place` model
```
  var Place = thinky.createModel('place', {
      name: thinky.type.string()
  });
  Place.hasMany(Group, "groups", "id", "place_id");
```

I'd like to fetch all the `groups` with user's name & place's name for a `place_id`

Here is what I've done:

```
Place.get(PLACE_ID).getJoin({groups: true}).then(function(g){console.log(g);})
```

How can I populate the user's name ? Using `_apply` ? How ?

Thank you in advance :)

**Comment by danielmewes** [comment]
You might want to ask this on the https://github.com/neumino/thinky repository, since Thinky is not maintained by RethinkDB.
Maybe @neumino can give you some hints.

**Comment by danielmewes** [comment]
Going to close this here, since it's outside the scope of this repository.

**Comment by olasfar** [comment]
Sure makes sense, I finally got the answer to my question. Thank you guys.
