### ISSUE TITLE
Make `include_initial` changefeeds use efficient new sharding logic.

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#5051]
Right now they're using the old-style unsharding because it's faster to implement for the release (so reading from a table with `include_initial` will be just as slow as in 2.1).  We should fix that when we get a chance.

**Comment by danielmewes** [comment]
This was fixed in f4ffd120e9b51d259c6d49cdd61a7a4643de15b5 as part of #5216 and will ship with RethinkDB 2.2.2.
