### ISSUE TITLE
test-runner appears to leak processes sometimes

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#5066]
Steps to reproduce:
* Run `./test-runner -j12` on Newton.
* Wait until you start to see "Starting..." lines, then hit Ctrl+c.
* Sometimes there are processes like this left behind that never seem to complete:
```
mlucy    23251  0.2  0.0  71516 23884 ?        S    00:40   0:00 python /home/ssd2/mlucy/rethinkdb/test/rql_test/connections/http_support/server.py --httpbin-port 0 --http-port 0 --ssl-port 0
mlucy    23344  0.1  0.0  71556 23888 ?        S    00:40   0:00 python /home/ssd2/mlucy/rethinkdb/test/rql_test/connections/http_support/server.py --httpbin-port 0 --http-port 0 --ssl-port 0
mlucy    23365  0.1  0.0  71388 23836 ?        S    00:40   0:00 python /home/ssd2/mlucy/rethinkdb/test/rql_test/connections/http_support/server.py --httpbin-port 0 --http-port 0 --ssl-port 0
```

This isn't a huge problem, but I've been running the tests a lot recently and I managed to exhausted my process ulimit just from leaked processes, which is how I noticed it.

**Comment by larkost** [comment]
This should be fixed in `next` with d90c90a3.
