### ISSUE TITLE
ReqlDriverError | Error: [Errno 36] Operation now in progress

### ISSUE THREAD

**Issue by keshavagrawal89** [rethinkdb/rethinkdb#5069]
Getting this error intermittently while fetching from rethinkdb. Weird observation but seen this while fetching data too fast from rethinkdb.

Note: I am using: https://github.com/hden/rethinkdb-pool for connection pooling. Can that be an issue? Any direction would help.

**Comment by danielmewes** [comment]
Thanks for the report @keshavagrawal89 .
I haven't seen this error before. @deontologician do you have any ideas?

One thing to make sure is that you don't call `pool.release` on a connection before you've read all data from a cursor. To be safe, you might might also want to call `close()` on the cursor (not on the connection) before releasing the connection back into the pool.

**Comment by danielmewes** [comment]
@keshavagrawal89 Have you been able to resolve this?

**Comment by keshavagrawal89** [comment]
@danielmewes Yes. You can close this bug. I called close at places where I was sure of data being read and the issue never came up. Sorry to respond so late.
