### ISSUE TITLE
crash on arm

### ISSUE THREAD

**Issue by deviantmk** [rethinkdb/rethinkdb#5087]
Happens a moment after i open the dashboard

Version: rethinkdb 2.2.0 (GCC 4.9.2)
error: Error in src/arch/runtime/thread_pool.cc at line 359:
error: Segmentation fault from reading the address 0x220067a9.
error: Backtrace:
addr2line: addr2line: 'rethinkdb': No such file
'rethinkdb': No such file
error: Sat Nov 14 05:13:49 2015
       
       1 [0x375c5c]: backtrace_t::backtrace_t() at 0x375c5c (rethinkdb)
       2 [0x375ee8]: format_backtrace(bool) at 0x375ee8 (rethinkdb)
       3 [0x5139e8]: report_fatal_error(char const*, int, char const*, ...) at 0x5139e8 (rethinkdb)
       4 [0x542be4]: linux_thread_pool_t::fatal_signal_handler(int, siginfo_t*, void*) at 0x542be4 (rethinkdb)
       5 [0xb6c0b250]: /lib/arm-linux-gnueabihf/libc.so.6(+0x25250) [0xb6c0b250] at 0xb6c0b250 (/lib/arm-linux-gnueabihf/libc.so.6)
       6 [0x596828]: ql::term_walker_t::walker_frame_t::walk(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::RAllocator>*, ql::backtrace_id_t) at 0x596828 (rethinkdb)
       7 [0x59721c]: ql::term_walker_t::walker_frame_t::walk(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::RAllocator>*, ql::backtrace_id_t) at 0x59721c (rethinkdb)
       8 [0x59721c]: ql::term_walker_t::walker_frame_t::walk(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::RAllocator>*, ql::backtrace_id_t) at 0x59721c (rethinkdb)
       9 [0x59721c]: ql::term_walker_t::walker_frame_t::walk(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::RAllocator>*, ql::backtrace_id_t) at 0x59721c (rethinkdb)
       10 [0x59721c]: ql::term_walker_t::walker_frame_t::walk(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::RAllocator>*, ql::backtrace_id_t) at 0x59721c (rethinkdb)
       11 [0x59721c]: ql::term_walker_t::walker_frame_t::walk(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::RAllocator>*, ql::backtrace_id_t) at 0x59721c (rethinkdb)
       12 [0x59721c]: ql::term_walker_t::walker_frame_t::walk(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::RAllocator>*, ql::backtrace_id_t) at 0x59721c (rethinkdb)
       13 [0x5975ec]: ql::term_walker_t::walker_frame_t::walk(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::RAllocator>*, ql::backtrace_id_t) at 0x5975ec (rethinkdb)
       14 [0x59721c]: ql::term_walker_t::walker_frame_t::walk(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::RAllocator>*, ql::backtrace_id_t) at 0x59721c (rethinkdb)
       15 [0x59721c]: ql::term_walker_t::walker_frame_t::walk(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::RAllocator>*, ql::backtrace_id_t) at 0x59721c (rethinkdb)
       16 [0x5975ec]: ql::term_walker_t::walker_frame_t::walk(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::RAllocator>*, ql::backtrace_id_t) at 0x5975ec (rethinkdb)
       17 [0x595fe2]: ql::preprocess_term_tree(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::RAllocator>*, rapidjson::RAllocator*, ql::backtrace_registry_t*) at 0x595fe2 (rethinkdb)
       18 [0x63706c]: ql::json_term_storage_t::preprocess() at 0x63706c (rethinkdb)
       19 [0x5468a8]: ql::query_cache_t::create(ql::query_params_t*, signal_t*) at 0x5468a8 (rethinkdb)
       20 [0x59fb76]: rdb_query_server_t::run_query(ql::query_params_t*, ql::response_t*, signal_t*) at 0x59fb76 (rethinkdb)
       21 [0x32180e]: query_server_t::handle(http_req_t const&, http_res_t*, signal_t*) at 0x32180e (rethinkdb)
       22 [0x6ccfa2]: routing_http_app_t::handle(http_req_t const&, http_res_t*, signal_t*) at 0x6ccfa2 (rethinkdb)
       23 [0x6ccfa2]: routing_http_app_t::handle(http_req_t const&, http_res_t*, signal_t*) at 0x6ccfa2 (rethinkdb)
       24 [0x6c99da]: http_server_t::handle_conn(scoped_ptr_t<linux_tcp_conn_descriptor_t> const&, auto_drainer_t::lock_t) at 0x6c99da (rethinkdb)
       25 [0x6ca014]: std::_Function_handler<void (scoped_ptr_t<linux_tcp_conn_descriptor_t>&), boost::_bi::bind_t<void, boost::_mfi::mf2<void, http_server_t, scoped_ptr_t<linux_tcp_conn_descriptor_t> const&, auto_drainer_t::lock_t>, boost::_bi::list3<boost::_bi::value<http_server_t*>, boost::arg<1>, boost::_bi::value<auto_drainer_t::lock_t> > > >::_M_invoke(std::_Any_data const&, scoped_ptr_t<linux_tcp_conn_descriptor_t>&) at 0x6ca014 (rethinkdb)
       26 [0x52a65a]: linux_nonthrowing_tcp_listener_t::handle(int) at 0x52a65a (rethinkdb)
       27 [0x542898]: coro_t::run() at 0x542898 (rethinkdb)
       28 [0x54285c]: coro_t::get_coro() at 0x54285c (rethinkdb)
error: Exiting.
Aborted

**Comment by leetal** [comment]
Possible duplicate. See discussion at #5093.

**Comment by danielmewes** [comment]
Yeah these look the same. Merging with #5093. Thanks for the report @deviantmk

**Comment by ChrisMondok** [comment]
I'm seeing this same behavior in rethinkdb 2.2.3-1 (GCC 5.3.0), despite the other bug being closed as fixed in 2.2.2. The error message "addr2line: addr2line: 'rethinkdb': No such file" appears in this issue, and in my output, but *not* in #5039.

I can open the dashboard, but as soon as I run any query or anything, it segfaults.

Do I open a new issue? Do I somehow reopen this one? Thanks!

Entire output is below.

```
Running on Linux 4.1.15-5-ARCH armv7l
Loading data from directory /home/chris/todone/rethinkdb_data
warn: Cache size does not leave much memory for server and query overhead (available memory: 859 MB).
warn: Cache size is very low and may impact performance.
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on addresses: 127.0.0.1, 10.0.0.10, ::1, fe80::7edd:90ff:fe6a:c9d0%3
Server ready, "tau_4vf" 881210fb-44c7-47a1-b5ab-ecc093e0b0b4
node server.js
Version: rethinkdb 2.2.3-1 (GCC 5.3.0)
error: Error in src/arch/runtime/thread_pool.cc at line 359:
error: Segmentation fault from reading the address 0x72800008.
error: Backtrace:
addr2line: addr2line: 'rethinkdb': No such file
'rethinkdb': No such file
error: Fri Jan 22 03:57:29 2016

       1 [0x66bb80]: backtrace_t::backtrace_t() at 0x66bb80 (rethinkdb)
       2 [0x66bf78]: format_backtrace[abi:cxx11](bool) at 0x66bf78 (rethinkdb)
       3 [0x32ec78]: report_fatal_error(char const*, int, char const*, ...) at 0x32ec78 (rethinkdb)
       4 [0x622840]: linux_thread_pool_t::fatal_signal_handler(int, siginfo_t*, void*) at 0x622840 (rethinkdb)
       5 [0x768c5a30]: __default_rt_sa_restorer+0 at 0x768c5a30 (/usr/lib/libc.so.6)
       6 [0x51e620]: boost::variant<profile::start_t, profile::split_t, profile::sample_t, profile::stop_t>* std::__uninitialized_copy<false>::__uninit_copy<__gnu_cxx::__normal_iterator<boost::variant<profile::start_t, profile::split_t, profile::sample_t, profile::stop_t> const*, std::vector<boost::variant<profile::start_t, profile::split_t, profile::sample_t, profile::stop_t>, std::allocator<boost::variant<profile::start_t, profile::split_t, profile::sample_t, profile::stop_t> > > >, boost::variant<profile::start_t, profile::split_t, profile::sample_t, profile::stop_t>*>(__gnu_cxx::__normal_iterator<boost::variant<profile::start_t, profile::split_t, profile::sample_t, profile::stop_t> const*, std::vector<boost::variant<profile::start_t, profile::split_t, profile::sample_t, profile::stop_t>, std::allocator<boost::variant<profile::start_t, profile::split_t, profile::sample_t, profile::stop_t> > > >, __gnu_cxx::__normal_iterator<boost::variant<profile::start_t, profile::split_t, profile::sample_t, profile::stop_t> const*, std::vector<boost::variant<profile::start_t, profile::split_t, profile::sample_t, profile::stop_t>, std::allocator<boost::variant<profile::start_t, profile::split_t, profile::sample_t, profile::stop_t> > > >, boost::variant<profile::start_t, profile::split_t, profile::sample_t, profile::stop_t>*) at 0x51e620 (rethinkdb)
       7 [0x827660]: read_response_t::read_response_t(read_response_t const&) at 0x827660 (rethinkdb)
       8 [0x825170]: rethinkdb() [0x825170] at 0x825170 ()
       9 [0x8296e0]: mailbox_t<void (boost::variant<read_response_t<cannot_perform_query_exc_t> >)>::read_impl_t::read(read_stream_t*, signal_t*) at 0x8296e0 (rethinkdb)
       10 [0x3a7764]: mailbox_manager_t::mailbox_read_coroutine(connectivity_cluster_t::connection_t*, auto_drainer_t::lock_t, threadnum_t, unsigned long long, std::vector<char, std::allocator<char> >*, long long, mailbox_manager_t::force_yield_t) at 0x3a7764 (rethinkdb)
       11 [0x3a7884]: rethinkdb() [0x3a7884] at 0x3a7884 ()
       12 [0x6274b8]: coro_t::run() at 0x6274b8 (rethinkdb)
error: Exiting.
```

**Comment by danielmewes** [comment]
@ChrisMondok This seems to be a different bug, judging from the backtrace. I opened https://github.com/rethinkdb/rethinkdb/issues/5322 for this.

**Comment by ChrisMondok** [comment]
Thanks!
