### ISSUE TITLE
Incorrect `is_deterministic` for UUID

### ISSUE THREAD

**Issue by VeXocide** [rethinkdb/rethinkdb#5092]
We currently return `deterministic::no` in `is_deterministic` for `r.uuid`, see https://github.com/rethinkdb/rethinkdb/blob/next/src/rdb_protocol/terms/uuid.cc#L39.

Unfortunately it's no longer this simple now that we support version 5 UUIDs such as `r.uuid("foo")`, these are based on a namespace and SHA-1 hash and are deterministic.

**Comment by thelinuxlich** [comment]
Just stumbled upon this trying to insert in batches with r.uuid(string) :( :(

**Comment by danielmewes** [comment]
We should obviously fix this. Looking at how `is_deterministic` works, it's probably going to be a very easy fix.

**Comment by danielmewes** [comment]
A fix is up in review 3345

**Comment by danielmewes** [comment]
Fixed in `next` cef5d65 and `v2.2.x` f1d53cd

**Comment by captainpete** [comment]
Yes!!
