### ISSUE TITLE
changes with  includeInitial: true orderBy not work?

### ISSUE THREAD

**Issue by nyrf** [rethinkdb/rethinkdb#5098]
`r.table('games').orderBy({index: r.desc('score')}).limit(3).changes({ includeInitial: true })` got

```
{
"new_val": {
"id":  "4c1e5a1f-faf5-4dd6-a917-bd4131f98c02" ,
"name":  "Game Last" ,
"score": 11
}
} {
"new_val": {
"id":  "e87da839-7ae6-4069-acee-733d5d4085f7" ,
"name":  "Game-2" ,
"score": 15
}
} {
"new_val": {
"id":  "cd2742ae-461f-4c1f-b767-25632238d2d9" ,
"name":  "Game-3" ,
"score": 18
}
}
```

**Comment by danielmewes** [comment]
It seems to be working for me. Is this result from the Data Explorer?
Note that the Data Explorer displays events on a change feed in reverse order, with the newest result on top and the oldest one at the bottom.

**Comment by nyrf** [comment]
@danielmewes Yes, i tried it from the Data Explorer, i'll try again, thanks.
