### ISSUE TITLE
rethinkdb restore error: ReQL error during 'create table': Connection is closed

### ISSUE THREAD

**Issue by subblue** [rethinkdb/rethinkdb#5104]
I have a RethinkDB deployment on compose.io with an SSH tunnel setup to connect to it.
I can do a ```rethinkdb dump``` of my remote database but when I try to restore back to the remote I get the following error for each table:

```ReQL error during 'create table': Connection is closed```

The tables in the remote installation actually get created, but no data is restored. 

I have localhost port 28016 mapping through to the remote deployment on port 28015 and the restore command I'm using is:

```rethinkdb restore backup.tar.gz -c localhost:28016 -i appdb -a $RDB_AUTH --force```

I'm actually trying to update the remote rethinkdb database with a dump from my local development installation. My local rdb is running v2.2.0 but the remote on compose.io is still v2.1.4 (the latest they currently support) if that makes any difference?

Thanks.

**Comment by danielmewes** [comment]
That's pretty strange.

Can you make sure that you have the latest version of the Python driver installed on your local machine (`sudo pip install --upgrade rethinkdb`)? The `rethinkdb restore` script is actually packaged with the Python driver.

You mention that it does still create the tables. If you leave the tables after the first run, do you get the same error again when you run `rethinkdb restore` a second time? If not, do you get a different error?

Could you also try the `--clients 1` option, just in case there's an issue with the high load during restore?

**Comment by subblue** [comment]
I tried what you suggested, but get the same errors each time.
However, if I use the ```--no-secondary-indexes``` option with the restore then it does work!

Perhaps there is a mismatch with dumps generated from v2.2 being restored into v2.1.2?

**Comment by danielmewes** [comment]
@subblue Oh that makes sense actually. Indexes exported from a more recent version such as 2.2.x are usually not compatible with older versions of RethinkDB (2.1.x and older). I didn't think about that.

Our error message seems to be pretty bad though. It looks like the server is terminating the connection rather than returning a useful error on the failed `indexCreate` query.

@Tryneus do you have an idea what's going on? Could it be that we're not handling the case where `indexCreate` receives a version that's too high?

**Comment by danielmewes** [comment]
I just ran into a similar case where I tried to import a RethinkDB 2.2 backup onto a RethinkDB 2.1.0 server.
The 2.1 server crashed as follows:
```
Version: rethinkdb 2.1.0+1~0precise (GCC 4.6.3)
error: Error in src/rdb_protocol/btree.cc at line 1272:
error: Unreachable code: 
error: Backtrace:
addr2line: 'rethinkdb': No such file
addr2line: 'rethinkdb': No such file
error: Wed Nov 25 18:29:33 2015
       
       1: format_backtrace(bool) at 0xb34803 (rethinkdb)
       2: report_fatal_error(char const*, int, char const*, ...) at 0xdc8904 (rethinkdb)
       3: deserialize_sindex_info(std::vector<char, std::allocator<char> > const&, sindex_disk_info_t*) at 0x86fb17 (rethinkdb)
       4: ql::sindex_config_from_string(datum_string_t const&, ql::rcheckable_t*) at 0x907647 (rethinkdb)
       5: ql::sindex_create_term_t::eval_impl(ql::scope_env_t*, ql::args_t*, ql::eval_flags_t) const at 0x90b87d (rethinkdb)
       6: ql::op_term_t::term_eval(ql::scope_env_t*, ql::eval_flags_t) const at 0x8851f1 (rethinkdb)
       7: ql::runtime_term_t::eval(ql::scope_env_t*, ql::eval_flags_t) const at 0x98e10b (rethinkdb)
       8: ql::query_cache_t::ref_t::run(ql::env_t*, Response*) at 0x7b6a68 (rethinkdb)
       9: ql::query_cache_t::ref_t::fill_response(Response*) at 0x7b8158 (rethinkdb)
       10: ql::run(ql::query_id_t&&, ql::protob_t<Query>, Response*, ql::query_cache_t*, signal_t*) at 0x98e59a (rethinkdb)
       11: rdb_query_server_t::run_query(ql::query_id_t&&, ql::protob_t<Query> const&, Response*, ql::query_cache_t*, signal_t*) at 0x8809b5 (rethinkdb)
       12: rethinkdb() [0xb2539c] at 0xb2539c ()
       13: std_function_callback_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >::coro_pool_callback(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, signal_t*) at 0xb28785 (rethinkdb)
       14: coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >::worker_run(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t) at 0xb28988 (rethinkdb)
       15: callable_action_instance_t<std::_Bind<std::_Mem_fn<void (coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >::*)(std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t)> (coro_pool_t<std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > > >*, std::_List_iterator<std::pair<ql::query_id_t, ql::protob_t<Query> > >, auto_drainer_t::lock_t)> >::run_action() at 0xb288f4 (rethinkdb)
       16: coro_t::run() at 0xa426fe (rethinkdb)
error: Exiting.
Trace/breakpoint trap (core dumped)
```

**Comment by nighelles** [comment]
This was in review 3475,
implemented in nighelles/sindex, and is now in next.
