### ISSUE TITLE
evaluate removing OpenSSL dependency

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5105]
With Apple further depreciating OpenSSL (#4963) there has been some discussion about removing OpenSSL as a dependency. There are a number of odd corners that we currently depend on OpenSSL that will have to be covered if we are going to do this, and some possibilities to do so:
- `src/client_protocol/server.cc` uses it to get a sha256 digest
  -  include a single-file sha256 implementation
  - `mbed TLS` (formerly `PolarSSL`) is an alternative
  - on MacOS ComonCrypto provides a drop-in replacement that has full OS support (see `COMMON_DIGEST_FOR_OPENSSL` in `/usr/include/CommonCrypto/CommonDigest.h `)
- The `s2` library that we use in `geo` support uses it for bing-number support. This is limited to a single file (`exactfloat.cc`).
  - we could try to pull the bignumb support out of OpenSSL and include those files in our project
  - it is possible that `mbed TLS` has support that we could use
  - `gmplib` might be used as a replacement for bignumb support
- When we build `libcurl` we link it against OpenSSL when not on MacOS (there we use `--darwin-ssl`)
  - `mbed TLS` is a good candidate here, but there is an outstanding question about whether it can use the root certs on MacOS.

**Comment by danielmewes** [comment]
This is no longer a real option, since we're now using OpenSSL much more heavily.
We can still replace it by another (core API compatible?) library at some point, but that's a separate discussion.
