### ISSUE TITLE
Make use of multi-key `getAll` in `eqJoin`

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5115]
`eqJoin` could be by an order of magnitude faster if we batched multiple lookups into a single multi-key `getAll`.

As an example: Consider the query described in https://github.com/rethinkdb/rethinkdb/issues/5109 . By rewriting the first `eqJoin` in that query into a `table2.getAll(r.args(table1.....coerceTo('array')))`, I could get the execution time of that part down from 35 ms to 4 ms.

**Comment by thelinuxlich** [comment]
I'm not understanding, how do you convert the eqJoin to getAll?

**Comment by marshall007** [comment]
@thelinuxlich I think it's a special case, as in the example cited, where the `.getAll` uses the same index as the subsequent `.eqJoin`.

**Comment by danielmewes** [comment]
The trick I used only works if one side of the join is small and you can afford loading it into an array. It works regardless of the indexes used. For example:
```js
r.table("small").eqJoin("joinKey", r.table("other"))
```
can be turned into
```js
r.table("small").coerceTo("array").do(function (left) {
    return r.table("other").getAll(r.args(left)).map(function (right) {"left": left, "right": right});
})
```

**Comment by marshall007** [comment]
@danielmewes by "small" do you mean less than the array size limit? Also, how would you even know which side is small(er) without reading both into memory first? Especially in cases where you're doing a `.getAll` on a secondary index, like in the example you mentioned. Are you guys persisting subtree counts to disk or something?

**Comment by danielmewes** [comment]
@marshall007 This was just what I used for testing how big the expected performance benefits would be. The actual implementation wouldn't look like that.

Currently `eqJoin` is implemented roughly like this:
`left.concatMap(other.getAll(r.row(joinKey)).map(...))`
As you can see, this does one `getAll` for each key that we want to join from the left table, and that is inefficient.

I suggest that we batch together a bunch of keys from the left table, and then issue a single `getAll`-like query against the other table for the batch. We already have logic in place to split up a stream into batches of reasonable size, so we would probably just use that. We don't need to know which table is smaller. It would always use the left table. If it's too large to fit into a single batch, it will simply use multiple batches.

**Comment by thelinuxlich** [comment]
Interesting

**Comment by marshall007** [comment]
@danielmewes thanks, that makes sense!

**Comment by danielmewes** [comment]
(Actually my rewrite is wrong, because we can't currently associate the left and right documents correctly... But it shows the idea.)

**Comment by nighelles** [comment]
An improvement is in review 3519.
Implemented in nighelles/5115

**Comment by danielmewes** [comment]
:clap:
What are the latest numbers for the speedup? :-)

**Comment by nighelles** [comment]
Looks like ~10X across the board. Haven't been able to reproduce the higher numbers I saw. :(

**Comment by thelinuxlich** [comment]
:100:

**Comment by nighelles** [comment]
This is in next.
