### ISSUE TITLE
Generated Java files are checked in

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#5117]
Running `make` currently modifies the following checked-in files:

* `drivers/java/proto_basic.json`
* `drivers/java/src/main/java/com/rethinkdb/gen/proto/QueryType.java`
* `drivers/java/src/main/java/com/rethinkdb/gen/proto/ResponseType.java`

**Comment by deontologician** [comment]
I think I just need to create a separate target for updating the driver vs. building it.

**Comment by deontologician** [comment]
Also, I need to update it
