### ISSUE TITLE
Any way to make `r.filter()` more efficient in this query ? 

### ISSUE THREAD

**Issue by alash3al** [rethinkdb/rethinkdb#5119]
i've asked a question on SO [Rethinkdb between with multiple keys](http://stackoverflow.com/questions/32922011/rethinkdb-between-with-multiple-keys), and i didn't find any way to that without using `r.filter()`, and now i need something like that, and to make use of `indexes`
is there any trick to do that ?

---

**This is the question content**

I've the following structrue :

    Item {
      id string,
      title string
      tags []string,
      time int,
      parent string
    }

What i want, `list all items with tags [tag1, tag2, ... etc] of parent "parent-1" and order by time`

So i did this

    r.db("db").table("tb").indexCreate("allByTime", function(row){
      return row("tags").map(function(tag){
        return [row("parent"), tag, row("time")]
      })
    })

It worked with a query like this 

    r.db("db").table("tb").between(["parent-1", "tag1", 0], ["parent-1", "tag1", <some-bigger-timestamp>], {index: "allByTime"}).orderBy(...)

But also i want something like this 

    r.db("db").table("tb").between(["parent-1", ["tag1", "tag2"], 0], ["parent-1", ["tag1", "tag2"], <some-bigger-timestamp>], {index: "allByTime"}).orderBy(...)

---
Any suggestions ?  
**NOTE ->** i don't want to use `r.filter(...)`
---
I've tried something like this

    r.union(<between-query-1>, <between-query-2>, ...)

is the above `r.union()` the only trick ?

**Comment by mlucy** [comment]
Yes, in this case I think the `union` of `between`s is the only way to do it if you want everything to be indexed.  Closing since this isn't a bug, but feel free to ask more questions here.
