### ISSUE TITLE
Two modules missing in package.json ?

### ISSUE THREAD

**Issue by dherault** [rethinkdb/rethinkdb#5120]
Hi,

I encontered this error on webpack:
```
ERROR in ./~/rethinkdb/net.js
Module not found: Error: Cannot resolve module 'net' in /root/oso/node_modules/rethinkdb
 @ ./~/rethinkdb/net.js 6:6-20

ERROR in ./~/rethinkdb/net.js
Module not found: Error: Cannot resolve module 'tls' in /root/oso/node_modules/rethinkdb
 @ ./~/rethinkdb/net.js 8:6-20
```
I did `npm remove rethinkdb && npm i rethinkdb` but still the same.

Eventually `npm i net tls` did the trick.

What am I missing ?

**Comment by chrisvariety** [comment]
`net` and `tls` are part of Node.js, and should not need to be installed via npm. I don't think the npm packages of the same name are the same as what is included in Node.

https://nodejs.org/api/tls.html

https://nodejs.org/api/net.html

Are you running in a Node.js-based environment?

**Comment by chrisvariety** [comment]
See also https://github.com/rethinkdb/rethinkdb/blob/next/drivers/javascript/net.coffee#L13-L26

**Comment by dherault** [comment]
I was in node 5, how strange. I'll rebuild my Dockerfile just to be sure. Thanks for the clue!

**Comment by RichardForrester** [comment]
I'm experiencing the same error. Running Node 5.2 (checked some different versions and makes no difference). I'm starting a new project. I think the error might have something to do with webpack-dev-server. If it is a rethinkdb issue please reopen. I'm checking with webpack now.

package.json:

    "dependencies": {
        "express": "^4.13.3",
        "history": "1.13.x",
        "immutable": "^3.7.5",
        "marked": "^0.3.5",
        "material-ui": "^0.13.4",
        "react": "^0.14.3",
        "react-dom": "^0.14.3",
        "react-redux": "^4.0.0",
        "react-router": "^1.0.2",
        "react-tap-event-plugin": "^0.2.1",
        "redux": "^3.0.4",
        "rethinkdb": "^2.2.0",
        "socket.io": "^1.3.7"
    },
    "devDependencies": {
        "babel-eslint": "^4.1.6",
        "babel-preset-es2015": "^6.3.13",
        "babel-preset-react": "^6.3.13",
        "babel-preset-stage-0": "^6.3.13",
        "eslint-plugin-react": "^3.11.3",
        "babel": "^6.3.13",
        "babel-core": "^6.3.15",
        "babel-loader": "^6.2.0",
        "chai": "^3.4.1",
        "chai-immutable": "^1.5.3",
        "eslint": "^1.10.3",
        "mocha": "^2.3.4",
        "react-hot-loader": "^1.3.0",
        "webpack": "^1.12.9",
        "webpack-dev-server": "^1.14.0"
    }

webpack.config.js:

    var path = require('path');
    var webpack = require('webpack');

    module.exports = {
      devtool: 'eval',
      entry: [
        'webpack-dev-server/client?http://localhost:3000',
        'webpack/hot/only-dev-server',
        './src/index'
      ],
      output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/static/'
      },
      plugins: [
        new webpack.HotModuleReplacementPlugin()
      ],
      module: {
        loaders: [{
          test: /\.js$/,
          loaders: ['react-hot', 'babel'],
          include: path.join(__dirname, 'src')
        }]
      }
    };

server.js: 

    var webpack = require('webpack'); 
    var WebpackDevServer = require('webpack-dev-server');
    var config = require('./webpack.config');

    new WebpackDevServer(webpack(config), {
        publicPath: config.output.publicPath,
        hot: true,
        historyApiFallback: true
    }).listen(3000, 'localhost', function (err, result) {
        if (err) {
            console.log(err);
        }

        console.log('Listening at localhost:3000');
    });

src/index.js:

    var r = require('rethinkdb')

Resulting error from running `node server.js`:

    ERROR in ./~/rethinkdb/net.js
    Module not found: Error: Cannot resolve module 'net' in [n]ode_modules/rethinkdb
     @ ./~/rethinkdb/net.js 6:6-20

    ERROR in ./~/rethinkdb/net.js
    Module not found: Error: Cannot resolve module 'tls' in [n]ode_modules/rethinkdb
     @ ./~/rethinkdb/net.js 8:6-20
    webpack: bundle is now VALID.

**Comment by RichardForrester** [comment]
Nevermind. This is definately not a RethinkDB issue. I tried loading redis and got the same errors. I'm thinking it must be a webpack config issue with react-hot-loader.

**Comment by danielmewes** [comment]
@dherault Please let us know if the issue persists. Maybe we have to change something for newer versions of Node.js?

**Comment by dsifford** [comment]
I'm having this issue as well. `net` and `tls` are not being recognized via webpack. (highly likely it is user error)

**Comment by chrisvariety** [comment]
@dsifford Webpack is (generally) for client side bundling of javascript. The rethinkdb npm package is for server-side (node) use only.

If you really want to use Webpack for server-side bundling, you'll have to follow a tutorial like http://jlongster.com/Backend-Apps-with-Webpack--Part-I -- but it can be pretty tricky.

**Comment by dsifford** [comment]
@chrisvariety I call to a db "getter" on the server-side from my client to gather data. The the function in the server uses the "r" method from rethinkdb. Because of that, webpack thinks I need it? 

I really don't understand how one would communicate with the server any other way.

**Comment by chrisvariety** [comment]
@dsifford Generally the client side uses AJAX (or another transport protocol) to communicate to a server-side endpoint -- AFAIK, you can't really make requests directly to Rethinkdb from the client side (unlike, say, Meteor)

**Comment by dsifford** [comment]
@chrisvariety Ah, I see.. Well shucks. I'll see if I can play around and get this to work. Thanks for the info

**Comment by deontologician** [comment]
@dsifford The big issue, even if you manage to get the project to compile for the browser, is that there are no security mechanisms in place to make it safe to expose the database directly to the internet. Anyone can just drop all of your tables, take your data etc. That's why the driver isn't written to accomodate that

**Comment by dsifford** [comment]
@deontologician Makes sense. Thanks for the clarification :blush:

**Comment by deontologician** [comment]
@dsifford Also, could I ask what your use case is? If you're trying to accomplish something and the driver isn't giving you the flexibility you want, there might be another way around it

**Comment by dsifford** [comment]
Just playing around at this point using react-router and redux, but I'm working on a collaborative markdown editor in which the index page is a generic splash page and then when the user clicks "create new" a unique instance is created at `index/editor/:uniqueid`. The markdown glob is then stored in rethinkdb (indexed using the same id). 

I have it wired up with socket.io right now so that after the user stops typing for three seconds, an autosave is triggered (but not sure I'll be able to do that after switching to an ajax-type model)..

**Comment by coffeemug** [comment]
Hey all, we have a new project designed to solve this problem. It's currently in a private repo (while it's in the early stages of development). If you're interested, let me know and I'll give you access.

**Comment by chrisvariety** [comment]
@coffeemug Count me in!!

**Comment by dsifford** [comment]
@coffeemug Ditto @chrisvariety

**Comment by coffeemug** [comment]
Ok, @chrisvariety @dsifford -- I invited you to the github project. Everything is WIP, but your feedback/contributions would be super-valuable!

**Comment by dsifford** [comment]
@coffeemug Greatly appreciated! Looking forward to checking it out :metal:

**Comment by letharion** [comment]
@coffeemug I ended up here by also naively trying to import the client into a client facing application. I'd also be interested in seeing what project you are working on and how it can help. :)

**Comment by coffeemug** [comment]
@letharion -- just invited you. Sorry for the delay, there is more activity around the project than we expected, so this slipped through the cracks. /cc @mglukhovsky

**Comment by shantp** [comment]
@coffeemug can I be invited?

**Comment by mglukhovsky** [comment]
@shantp: just sent you an email and invite.
