### ISSUE TITLE
Java protobuf compiler can't compile with new VALUES term

### ISSUE THREAD

**Issue by danielcompton** [rethinkdb/rethinkdb#5121]
The 2.2 release added the `VALUES` term type. When I try to compile ql2.proto from the 2.2 release under Java (through Leiningen on [this project](https://github.com/apa512/rethinkdb-protobuf/)), I get an error. It looks like there is a collision between the `VALUES` term and a static field called `VALUES` that is created for every protocol buffer message type.

```
$lein do clean, protobuf, javac
 >  /Users/Daniel/.lein/cache/lein-protobuf/protobuf-2.6.1/src/protoc ql2.proto --java_out=/Users/Daniel/Developer/clojure/rethinkdb-protobuf/target/protosrc -I. -I/Users/Daniel/Developer/clojure/rethinkdb-protobuf/target/proto -I/Users/Daniel/Developer/clojure/rethinkdb-protobuf/resources/proto
Compiling 1 source files to /Users/Daniel/Developer/clojure/rethinkdb-protobuf/target/classes
/Users/Daniel/Developer/clojure/rethinkdb-protobuf/target/protosrc/rethinkdb/Ql2.java:12601: error: variable VALUES is already defined in enum TermType
      private static final TermType[] VALUES = values();
                                      ^
/Users/Daniel/Developer/clojure/rethinkdb-protobuf/target/protosrc/rethinkdb/Ql2.java:12609: error: array required, but TermType found
        return VALUES[desc.getIndex()];
                     ^
2 errors
Compilation of Java sources(lein javac) failed.
```

The generated source that is throwing the error is below.

```java
    /**
     * Protobuf enum {@code rethinkdb.Term.TermType}
     */
    public enum TermType
        implements com.google.protobuf.ProtocolMessageEnum {
... snip
      /**
       * <code>VALUES = 186;</code>
       *
       * <pre>
       * Return an array containing the values of the object.
       * </pre>
       */
      VALUES(42, 186),
... snip a few thousand lines of code
      private static final TermType[] VALUES = values();

      public static TermType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
```

If I change the term to `VALUESX` then I'm able to compile it successfully.

I'm not sure if there's really anything that can be done about this, short of changing the ql2 definition? I'll change it for our usage and make a note in the code so others maintaining the code don't get caught out.

To reproduce this yourself, checkout [rethinkdb-protobuf](https://github.com/apa512/rethinkdb-protobuf/), copy the 2.2 QL2 over the existing one, and run `lein do clean, protobuf, javac`.

**Comment by danielmewes** [comment]
Some drivers (at least the Ruby driver) rely on the names in ql2.proto to define the commands that are available in the API. We could add an exception for `values` to the code. Unless this turns out to be a big problem for a lot of protobuf compilers, I'd prefer not to change it in the main `ql2.proto` file though.

**Comment by danielcompton** [comment]
It's probably fine, especially considering that long term plans are to move away from a Protobuf definition. 

One alternative term name would be vals, but this isn't as clear as values.

**Comment by danielmewes** [comment]
Ok let's not change it for now. We can revisit this in case more drivers have this issue.
