### ISSUE TITLE
2.2's SERVER_INFO response type reuses SUCCESS_FEED enum

### ISSUE THREAD

**Issue by danielcompton** [rethinkdb/rethinkdb#5124]
2.2 added the `SERVER_INFO` response type enum with value 5. However in previous versions of RethinkDB (prior to 2.0) the response type enum 5 was used for `SUCCESS_FEED`. When implementing support for the `SERVER_INFO` query type, I ran into this, as we had old code around which still supported `SUCCESS_FEED` responses. It's an easy fix, but others may run into this too.

It could be good in the future when removing a field or enum from the protobuf definition to [reserve](https://developers.google.com/protocol-buffers/docs/proto?hl=en#reserved) it to make sure that you don't reuse previously defined fields?

#3934

**Comment by danielmewes** [comment]
> It could be good in the future when removing a field or enum from the protobuf definition to reserve it to make sure that you don't reuse previously defined fields?

Good idea! Sorry for the inconvenience this time.

I'm closing this since there's nothing to do here at the moment. We'll try to keep this in mind the next time we remove an enum value (also pinging @mlucy, @encryptio, @VeXocide ).
