### ISSUE TITLE
Add server_info command to Java driver

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#5125]
It was merged to next after I finished working on the driver

**Comment by venantius** [comment]
Just so I understand - is this related to the `server()` command described [here](https://www.rethinkdb.com/api/java/server/)? As far as I can tell that function doesn't actually exist in source code anywhere.

**Comment by danielmewes** [comment]
@venantius Yes, that command.

Since we haven't added it to the Java driver yet, we should probably remove the documentation page until we get to it... I'll open a separate issue against our docs.

**Comment by venantius** [comment]
Thanks, that would be awesome. I found the disconnect between docs and source confusing, personally :)

**Comment by bchavez** [comment]
**Just a reminder for implementation**
Interestingly, in a parallel universe, if we provide a model for `Connection.Server()` we should declare `id` as a `string`. I found out today, in proxy mode, the server `id` isn't guaranteed to be a UUID. It can look like `proxy-a711d91a-c391-4161-9a00-51b754a2477f` in proxy mode. :scream_cat: :smiley_cat: 

A user of mine just hit this problem this morning 

https://github.com/bchavez/RethinkDb.Driver/issues/94
https://github.com/bchavez/RethinkDb.Driver/pull/95

:fallen_leaf: :leaves: [**Distance - Falling (ft Alys Be)**](https://www.youtube.com/watch?v=WIfwIv4wNCE)

**Comment by adriantodt** [comment]
The Java driver now lives in https://github.com/rethinkdb/rethinkdb-java. I opened an issue so we can finally implement this into the driver. This issue can be closed.
