### ISSUE TITLE
Geo functions can't be used inside of updates

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#5129]
@danielmewes, @encryptio -- based on our conversation yesterday I was under the impression that `r.table('test').update{|row| {a: r.geojson(row['a'])}}` (and other similar queries) should work because they're marked "deterministic on one server".

This is the behavior I'm actually seeing:
```
irb(main):1234:0> r.table('test').update{|row| {a: r.geojson(row['a'])}}.run
RethinkDB::RqlQueryLogicError: Could not prove argument deterministic.  Maybe you want to use the non_atomic flag?
```

Is that expected?  If so, what's the purpose of the "deterministic on one server" distinction?

**Comment by danielmewes** [comment]
The behavior you're seeing is expected and sounds correct. The purpose of "deterministic on one server" is to allow the use of geo terms in changefeeds, such as `.filter(r.row.intersects(g)).changes`.
