### ISSUE TITLE
Determinism checking in `geo.cc` is broken

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#5130]
The terms in `geo.cc` that redefine `is_deterministic` all redefine it to return a constant, without regard to their arguments.  For example, `point_term_t` has the line `deterministic_t is_deterministic() const { return deterministic_t::always; }`.  I think this is incorrect because it will return `deterministic_t::always` even for term trees like `r.point(r.table('test').get(0)['x'], 1)` which are clearly not deterministic.  You can see this being done correctly in `op_term_t::is_deterministic()` where we loop over the arguments and return non-deterministic if they're non-deterministic.

Probably the way we want to do this is that we want the `is_deterministic` implementations in `geo.cc` to call the `is_deterministic` implementation on their superclass, and then write them so that they can only ever produce a more conservative `deterministic_t` specification than the result of that call (like the current implementation of the poorly-named `all_are_deterministic` in `op.cc`).

Assigning to @encryptio since he mentioned on Friday he was the one who first implemented this.

**Comment by encryptio** [comment]
In CR 3380

**Comment by encryptio** [comment]
Fixed in `next` as of 02b642d and `v2.2.x` as of 2c053d9. Will be in 2.2.2 and 2.3.
