### ISSUE TITLE
attributes in old_val are kept

### ISSUE THREAD

**Issue by skinkie** [rethinkdb/rethinkdb#5134]
I am using RethinkDB as hashmap where I replace a feature based on id. When I replace an existing feature with a geometry I noticed that this feature is maintained from my previous object. The geometry has a secondary index. I am using the statement below to update. When specifying geometery = None explictly in my new document the geometry is removed.

Edit: I observe that this happens for all the attributes in my update. Not only geometry types. I consider this a serious issue.

r.table('vehicles').insert(obj2, durability = 'soft', conflict = 'update').run()

**Comment by larkost** [comment]
Unless I am missing something, you actually want `conflict="replace"`. The `update` setting only changes the values you give it, so in that case if you don't have a key for your geometric value, it should be kept.

I am going to close this issue under the assumption that this is the issue, but feel free to re-open it if I have it wrong.

**Comment by skinkie** [comment]
@larkost you are correct. I should have chosen replace, if I wanted to have that behavior.
