### ISSUE TITLE
Drop support for GCC 4.6

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#5136]
I propose increasing our minimum supported version of GCC to 4.8. It would allow us to upgrade v8 and to get access to more C++11 features. It would require changing the packaging process for distros such as Precise and would make it harder for some users to build RethinkDB from source.

Newer versions of v8 do not support GCC 4.6. A newer version of v8 would contain performance improvements, bug fixes and would simplify the windows port. See #5112.

I was able to build v8 4.7.30 with GCC 4.7, but couldn't find any documentation as to what version of GCC is required.

Node, which embeds v8 too, requires GCC 4.8 to build and uses clang to build itself on distributions that do not have GCC >= 4.8.

We already have a process in place to build RethinkDB on distributions that do not have GCC >= 4.6. I believe we currently use GCC 4.9. We could apply that process to distributions such as Ubuntu Precise which has GCC 4.6. We might also have to change the default GCC on newton.

See https://gcc.gnu.org/projects/cxx0x.html for the list of C++11 features supported in GCC.

**Comment by VeXocide** [comment]
Yes please!

**Comment by danielmewes** [comment]
@AtnNn Have you tried using the GCC 4.8 that's installed on `newton`?
Every time I tried to do that I had to preload a certain version of `libc` I think (or was it `libstdc++`?), because the one installed was too old. Maybe we just need to install a different GCC 4.8 build?

Some versions of GCC 4.7 have crashing bugs on our code base during compilation, so I'd definitely suggest switching directly to GCC 4.8 and skipping 4.7.

**Comment by AtnNn** [comment]
There was no GCC-4.8 installed on newton this morning, so installed one to `/opt/gcc-4.8.5` and created symlinks in `/usr/local/bin`.

It had no problem building RethinkDB. Running the resulting binary required the correct `libstdc++` which it was taught to find by setting the environment variable `LD_LIBRARY_PATH=/opt/gcc-4.8.5/lib64`.

It would be very easy to make those libraries available systme-wide. I didn't because it might cause the GCC 4.8 libraries to interfere with GCC 4.6. That is also why I haven't installed GCC 4.8 from the PPA at http://ppa.launchpad.net/ubuntu-toolchain-r/test.

**Comment by danielmewes** [comment]
This is done. The minimum required GCC version is not 4.7.4.
4.7.4 is confirmed working, and 4.7.2 is confirmed not working (it crashes). I didn't try 4.7.3.

As a consequence of this change, we are going to drop support for Debian Wheezy with RethinkDB 2.3.0.
