### ISSUE TITLE
Fix all warnings in java driver

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#5139]
Most of these have been unchecked casts etc, which are pretty necessary. But it would be nice if it compiled cleanly, and I should go through systematically and make sure all of the warnings are for things that are actually safe to do (or as safe as we can be given coercion from the database etc)

**Comment by adriantodt** [comment]
The Java driver now lives in https://github.com/rethinkdb/rethinkdb-java. Most warnings were fixed in the proposed PRs, as well as in the main branch. This issue can be closed.
