### ISSUE TITLE
Add parameters for `rethinkdb restore` to initialize sharding

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5140]
Currently `rethinkdb restore` and `rethinkdb import` always create tables with the default settings, which means that the tables will be neither sharded nor replicated.

I propose adding `--shards` and `--replicas` parameters to `rethinkdb import` and `rethinkdb restore`, which will be passed into any `table_create` call.

Note that you can only specify one set of shard/replica parameters per import process. If different settings are needed for different databases, users could run `rethinkdb import` multiple times for only a single database or table.

**Comment by marshall007** [comment]
@danielmewes I'm gonna work on this if that's alright. Is it acceptable if `--replicas` only accepts an integer argument or do we also need to support the server tag key/value pairs?

**Comment by danielmewes** [comment]
@marshall007 Amazing! :-)
> Is it acceptable if `--replicas` only accepts an integer argument or do we also need to support the server tag key/value pairs?

I think it is. That's what I had in mind.
