### ISSUE TITLE
Invalid Clustering Header on empty stream

### ISSUE THREAD

**Issue by JBodkin** [rethinkdb/rethinkdb#5145]
One of the health checks I've created for rethinkdb connects on the cluster port to ensure if the port is open. Each time the health check runs, rethinkdb creates an message saying "warn: Received invalid clustering header from [::ffff:172.17.0.1]:58139, closing connection -- something might be connecting to the wrong port."

I would like to suppress that message in this instance, is there any way to do this?

https://github.com/rethinkdb/rethinkdb/blob/3c2473f7e4a5866633c9eceda5aa304ca6accd65/src/rpc/connectivity/cluster.cc#L874

Health Check
```
/usr/lib/nagios/plugins/check_tcp -H 127.0.0.1 -p 29015
```

**Comment by larkost** [comment]
There is currently no way of suppressing any messages. However, without knowing anything about the details of your monitoring system, my first reaction is that it would probably be better to use a driver to open a connection (not much more costly then what you are already doing), and then send a trivial query (e.g.: `r.expr(1).run(conn)`). You can still distinguish failure-to-connect from failure-to-process based on the error class that comes back. From my quick read on creating `nagios` plugins that should not be too difficult to do, assuming you can install the proper driver on the `nagios` server.

I am going to close this issue, but make an additional comment in #4628 to make sure we cover this sort of case when we go to a more full-featured logger. Feel free to ask additional questions here if you want.

**Comment by danielmewes** [comment]
@JBodkin In theory the message should no longer appear if you make the health check send the correct cluster header "RethinkDB cluster\n". In a quick experiment I couldn't get this working though.

For me, using Nagios' `check_tcp` actually doesn't generate the warnings. I think it might be disconnecting before RethinkDB gets to the part where it verifies the header, but I'm not sure. It's probably timing dependent.
