### ISSUE TITLE
Endless searching when using .get() with string that's not in the database followed by vm lock up/crash

### ISSUE THREAD

**Issue by tomhatzer** [rethinkdb/rethinkdb#5148]
Hi everybody!

I've got quite a strange problem that's driving me crazy lately.

Information about the database (running inside a virtual machine):
rethinkdb 2.2.1 (updated just a few days ago)
2 tables:
   Table A with 1.1mio documents (each document has about 1-40kb)
   Table B with 5.7mio documents (each document has about 1kb)

Information about the OS:
OS Ubuntu 14.04.3
8GB RAM
256GB HDD

So, when I start a database query like
```
r.database("db1).table("tableA").get("EXISTS");
```
with a string that exists, it returns the document instantly.
BUT when I start a query like 
```
r.database("db1).table("tableA").get("DOES NOT EXIST");
```
then rethinkdb starts going crazy and searches in every single document for the string (1k-9k documents per second), and after a few hours it crashes and locks up the whole vm.

Another strange thing is, it doesn't write any logs to get to know what caused the hang and lock up.

Also .count() takes ages (15-30 minutes) to return a result for the simplest queries or stops in the middle of nowhere after a few minutes.

Is there any way that I can stop this from happening?

Thank you very much!

Best wishes
Tom

**Comment by danielmewes** [comment]
Hi Tom‎, can you reproduce this if you run the .get("no such key") query in the Data Explorer (web UI)?A 'get' should never cause more than one read, no matter whether the key exists or not. If this is reproducible, it's a bug. Is it possible that your application automatically retries the get if it returns `null`‎ or something like that?                                                                                                                                                                                                                                                                                                                                                                                     ‎

**Comment by tomhatzer** [comment]
Hello Daniel! Yes, I can reproduce this in the Data Explorer. It starts querying all the documents. Afterwards I have to restart rethinkdb (if I get to know it early, before it locks up the vm and I've got to restart the whole vm).

No, my app just prints a "Nothing found" if the return is null. :-/

**Comment by danielmewes** [comment]
A few more questions:
* Can you get the same behavior on `"tableB"` or only on `"tableA"`?
* Which version of RethinkDB did you upgrade from? Did the issue exist before the upgrade?
* Is there any chance that the reads you're observing are coming from a `count` query and not the 
`.get`? I assume the reads/s numbers are from the throughput graph in the web UI?
* Would you mind running a little experiment?
  1. Restart the server
  2. Go to the web UI and make sure that there are 0 reads/s
  3. Run only `r.database("db1").table("tableA").get("DOES NOT EXIST")` in the Data Explorer
  4. Check if you can now observe the high reads/s in the throughput graph
  5. If yes, go back to the Data Explorer and run `r.db('rethinkdb').table('jobs')`
  6. Post the output of that query here
* Can you observe a growth in RethinkDB's memory consumption when this happens? I wonder if an out of memory condition could be the reason for the VM locking up.

Regarding `count()` taking a long time: This might be normal. With a data set larger than the cache size, and with the data files being on a rotational HDD, traversing the whole table to count the number of documents can sometimes take a long time.
As a somewhat unfortunate edge case, if you run a `count()` in the Data Explorer, the Data Explorer  might time out after a few minutes. However the query will actually keep running in the background and put additional load on the server.

**Comment by danielmewes** [comment]
Haven't heard from @tomhatzer for a few months. Closing since we can't reproduce.

@tomhatzer Have you had a chance to look into the questions I posted in November? Are you still seeing this?
