### ISSUE TITLE
`rethinkdb restore` often fails with "Cannot perform write: primary replica for shard ["", +inf) not available"

### ISSUE THREAD

**Issue by danielcompton** [rethinkdb/rethinkdb#5154]
I'm wanting to restore a database onto my local Macbook Pro. I'm using RethinkDB 2.2.1 and the latest Python driver. 

Often when I run a restore I get an error:

```
$rethinkdb restore rethinkdb_dump_2015-11-26T19\:18\:58.tar.gz --hard-durability
Unzipping archive file...
  Done (0 seconds)
Importing from directory...
[                                        ]   0%
0 rows imported in 108 tables
ReQL error during 'import': Cannot perform write: primary replica for shard ["", +inf) not available
Errors occurred during import
Error: rethinkdb-import failed
```

I can see the tables being created on the server, and it appears like the restore driver isn't waiting for them to be ready before starting the restore which then causes the ReQL error. Running a second time with `--force` restores the documents successfully, (presumably) as the tables already exist.

Running with `--clients 4` perhaps makes it a little less likely to throw an error, but the problem is still there. Let me know if I can provide more information, there is nothing shown in the `rethinkdb` process logs.

**Comment by danielmewes** [comment]
Thanks for the report @danielcompton .

I wonder if this could be a server bug, since `table_create` should wait for a table to be ready before returning.

@Tryneus or @encryptio, could one of you double-check please that the `_import.py` script is probably waiting for `table_create` to return before it attempts to perform any operations on the table? (please add a note here when you start looking into it, so we don't duplicate the work)

**Comment by Tryneus** [comment]
Fix is up in review 3377.  This just adds a wait if the table already exists (`table_create` will already wait for readiness).  If the table takes more than 30 seconds to become ready, we will fail the import.

**Comment by Tryneus** [comment]
The fix has been approved and merged to `next` in commit 9128c3e, and cherry-picked into `v2.2.x` in commit c27e541.  Will be in the next python driver release.

Sorry you ran into this, @danielcompton.

**Comment by danielcompton** [comment]
No problem, thanks for the quick fix. Is the Python driver on the same release schedule as RethinkDB too?

**Comment by danielmewes** [comment]
@danielcompton We could release a new Python driver earlier, though I'd slightly prefer to wait for our 2.2.2 release and release it together with the server. I think the release is probably going to be in about a week.

**Comment by danielcompton** [comment]
No problem, I've got a try/catch to work around the problem in the meantime.

**Comment by DenisBY** [comment]
@danielcompton could you explain how you did it with try/catch?
I'm trying to catch and then retry on ` ReqlOpFailedError: Cannot perform write: The primary replica is currently changing from one replica to another ` but with no success
My code:
```
def retry_operation(operation, *args, **kwargs):
    def func(*args, **kwargs):
        attempts = 0
        while True:
            try:
                return operation(*args, **kwargs)
            except ReqlOpFailedError as req:
                sleep_interval = random.random() * min(MAX_SLEEP, MIN_SLEEP * 2 ** attempts)
                attempts = min(attempts + 1, ATTEMPTS_CAP)
                log.warn("Error: %s. Retrying in %f seconds", req, sleep_interval)
                time.sleep(sleep_interval)

    return func
```

**Comment by danielcompton** [comment]
@DenisBY I'm using the rethinkdb command line tool for this, not Python:

```sh
echo "Restoring backup to running server"
rethinkdb restore $(basename $RETHINKDB_BACKUP)

if [ $? -ne 0 ]; then
  echo "RethinkDB restore failed, trying again"
  rethinkdb restore $(basename $RETHINKDB_BACKUP) --force
fi
```

**Comment by DenisBY** [comment]
Thanks. It was problem in my code :).
