### ISSUE TITLE
optimize skip(0)

### ISSUE THREAD

**Issue by kwando** [rethinkdb/rethinkdb#5155]
I would expect that a query with ```skip(0)``` would be as fast as the same query without skip. I'm seeing an order of magnitude in differenence.

```ruby
r.order_by(index: reql.desc('date')).limit(input.per_page)
```
vs
```ruby
r.order_by(index: reql.desc('date')).skip(0).limit(input.per_page)
```

**Comment by danielmewes** [comment]
That's indeed very odd.
@mlucy Do you have an idea why the second one would be slower? Is this expected with the current implementation? (Maybe `skip`/`slice` somehow mess with the batch spec in a detrimental way?)

@kwando Could you try the following and see if it's fast or slow?
```js
r.order_by(index: reql.desc('date')).slice(0, input.per_page)
```

**Comment by mlucy** [comment]
This was caused by `slice` clobbering the already-reduced `max_els` in the batchspec provided by `limit` (and thus fetching too much data off of disk).  A fix is in CR 3374 by @danielmewes.

@danielmewes -- should we put this in 2.2.x do you think?  It's a simple fix.

**Comment by danielmewes** [comment]
@mlucy 2.2.x sounds good to me.

**Comment by kwando** [comment]
@danielmewes 
```
r.order_by(index: reql.desc('date')).slice(0, input.per_page)
```
is performing roughly the same as 
```
r.order_by(index: reql.desc('date')).limit(input.per_page)
```

**Comment by kwando** [comment]
using 2.2.1 from homebrew on OSX.

**Comment by mlucy** [comment]
This is in next and 2.2.x.

**Comment by danielmewes** [comment]
@kwando The optimization shipped with RethinkDB 2.2.2, which we released today. Homebrew might take a bit of extra time to update.

**Comment by kwando** [comment]
thank you all for your great work =)

btw #5155 seems to be about the same problem, sorry about creating a duplicate issue.

**Comment by danielmewes** [comment]
> btw #5155 seems to be about the same problem, sorry about creating a duplicate issue.

@kwando Is there another issue you meant? This one is #5155.

**Comment by kwando** [comment]
@danielmewes fackpalm, yeah there is... #4741 sorry about the confusion.
