### ISSUE TITLE
Investigate `SUCCESS_PARTIAL` arriving after `SUCCESS_SEQUENCE`

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#5159]
See https://github.com/neumino/rethinkdbdash/issues/190 .

**Comment by danielmewes** [comment]
Assigning @Tryneus

**Comment by Tryneus** [comment]
A fix for this has been approved in an OTS review by @mlucy and merged to `next` in commit 006f506, and cherry-picked into `v2.2.x` in commit c5a948a.  Will be in release 2.2.2.
