### ISSUE TITLE
Cosmetic issues in windows alpha1 build.

### ISSUE THREAD

**Issue by bckfnn** [rethinkdb/rethinkdb#5162]
Running with @AtnNn alpha1 windows preview.

Thanks for the preview. I'm running it on windows 10 and in addition to the "Problem with reading log file" issue that others have reported, I have found a few cosmetic issues:

* the uptime seems a bit off

![image](https://cloud.githubusercontent.com/assets/1541887/11512261/8d705c04-986d-11e5-9f38-db2c393e184b.png)
* the time line on all the graphs does not use my local 24hour time format (its is in the evening).

![image](https://cloud.githubusercontent.com/assets/1541887/11512374/15bfb852-986e-11e5-85a1-b5d5f473ae04.png)

**Comment by AtnNn** [comment]
Thanks for testing it and reporting. I can observe the same issues, I'll try to fix them.

**Comment by AtnNn** [comment]
I believe the time format issue is unrelated to windows. If you want it changed please open a separate issue. I believe the format used is this one: https://github.com/rethinkdb/rethinkdb/blob/next/admin/static/coffee/vis.coffee#L168

**Comment by AtnNn** [comment]
The other issues have been fixed in [alpha2](https://github.com/rethinkdb/rethinkdb/issues/1100#issuecomment-164890825).
