### ISSUE TITLE
Allow java Connection subclasses.

### ISSUE THREAD

**Issue by bckfnn** [rethinkdb/rethinkdb#5163]
The constructor in Connection.java is private, making it impossible to create our own implementations of Connection.

The usecase that I would like to experiment with is a non-blocking connection that uses the networking classes from vert.x.

Please either make the constructor public, or even better, use a Connection interface in ReqlAst.java which can be implemented in different ways.

**Comment by deontologician** [comment]
I made the Connection constructor public in 559ef59, and there are larger Connection refactorings coming in #5292 that will make it potentially easier to customize the Connection

**Comment by deontologician** [comment]
Also, thanks for the suggestion @bckfnn :)
