### ISSUE TITLE
Crash in windows alpha1

### ISSUE THREAD

**Issue by bckfnn** [rethinkdb/rethinkdb#5164]
On windows 10, restarting the server after creating a table, causes  a crash:

![image](https://cloud.githubusercontent.com/assets/1541887/11528389/aa9bfd1e-98e6-11e5-971e-30de1bcde42c.png)

Steps to reproduce:

* remove rethinkdb_data folder
* start RethinkDB-windows-alpha1.exe
* in the admin console on 8080 add a table called "table" in the "test" database.
* stop rethinkdb with Ctrl-C
* start RethinkDB-windows-alpha1.exe, the crash occurs after writing this log:
```
Running rethinkdb 2.0.1-dev-windows (debug) (MSC 190023026)...
Running on 6.2.9200 (Windows 8, Server 2012)
Loading data from directory C:\rethink\rethinkdb_data
warn: Failed to disable read-ahead on 'C:\vertx\ethics3\rethinkdb_data\metadata' (errno -1). You might see decreased read performance.
Our server ID is 65387f2e-c8a5-46c8-886b-3cc36f445f0e
Listening for intracluster connections on port 29015
warn: Failed to disable read-ahead on 'C:\rethink\rethinkdb_data\323089e3-fbec-4e1f-b818-59f597afb22e' (errno -1). You might see decreased read performance.
```

**Comment by danielmewes** [comment]
Thanks for the bug report @bckfnn .
Assigning @AtnNn

**Comment by AtnNn** [comment]
Thanks @bckfnn. I am in the process of rewriting the part of the code causing that error (the handling of aligned allocations).

**Comment by AtnNn** [comment]
I wasn't able to reproduce that crash, but I believe it might be fixed in [alpha2](https://github.com/rethinkdb/rethinkdb/issues/1100#issuecomment-164890825).

**Comment by AtnNn** [comment]
I still haven't been able to reproduce. Please re-open if this happens again in the latest version.
