### ISSUE TITLE
Exclusive access to rethinkdb_data folder on windows 10 using alpha1

### ISSUE THREAD

**Issue by bckfnn** [rethinkdb/rethinkdb#5165]
After starting RethinkDB-windows-alpha1.exe the windows 10 file explorer can not enter the rethinkdb_data subfolder:

![image](https://cloud.githubusercontent.com/assets/1541887/11528930/f90ae70a-98e9-11e5-906d-402ff170cbd1.png)

And if I stop rethinkdb, use file exporer to show files and folders in rethinkdb_data, and then try to start rethinkdb I get an error message:

```
Could not open directory 'rethinkdb_data': Broken pipe
```

It is IMHO a bit unusual for a windows program prevent other programs from even listing the content of the folder. Is that deliberate?

**Comment by danielmewes** [comment]
I agree that locking the whole folder is not great.

@AtnNn Can we change this without breaking RethinkDB's mechanism to detect other instances on the same data directory? Maybe we could lock `metadata` instead of the directory?

**Comment by AtnNn** [comment]
That behaviour is unintended and undesirable.

@danielmewes I'll see what I can do.

**Comment by AtnNn** [comment]
Fixed in 42b11ff.
