### ISSUE TITLE
TestingCommon and TestingFramework in the java driver are located in the wrong folder.

### ISSUE THREAD

**Issue by bckfnn** [rethinkdb/rethinkdb#5168]
While loading the java drive in my eclipse EDI I found that the TestingCommon.java and TestingFramework.java are located in the default package in the filesystem, but they both defines that they should reside in the "gen" package with the `package gen;`statement

Is there a reason for putting these source files in a different folder than the package statement specifies?

**Comment by deontologician** [comment]
The reason it's in a different directory than package is that it's not an autogenerated file, and the gen/ folders are only for autogenerated files (so you can blow them away and know they'll be regenerated). Unfortunately, this clashes with the canonical java folder scheme, and I decided it was more useful for the gen folder to be composed only of generated files than it was useful to have the packages and folders line up 100%.

It's possible there's a junit configuration option that would allow it to be moved out of the gen package, I didn't dig too deeply into it. If you manage to separate them cleanly, I'd definitely welcome a PR for it.

**Comment by adriantodt** [comment]
The Java driver now lives in https://github.com/rethinkdb/rethinkdb-java. `TestingCommon.java` and `TestingFramework.java` are located in the correct place: `package com.rethinkdb;`. This issue can be closed.
