### ISSUE TITLE
Detect if query is an  Object or a Sequence without a round trip.

### ISSUE THREAD

**Issue by rlancer** [rethinkdb/rethinkdb#5170]
_typeOf_ is great but it requires a round trip, I would love to be able to pass a ReQL expression to a function which can return if the query will result in an _Object_ or _Sequence_ without the need for a round trip. 

I have a series of utility functions throughout my application and I find myself having to write two versions of each function based on if the query will return an _Object_ or a _Sequence_.

**Comment by danielmewes** [comment]
Is this in JavaScript? Could you just look at the type of the `run` result to check if it's a cursor or not?

**Comment by rlancer** [comment]
Wouldn't calling run require a round trip?

**Comment by danielmewes** [comment]
@rlancer Yes, but you would also get the result of the query in the same request, so it wouldn't be an additional roundtrip like when first running with `.typeOf()`.

Or do you need to know if a given query returns an object or sequence, and then run a completely different query depending on what the answer is?

Determining whether a query is going to return a sequence or not without running it first is not trivial in general, and sometimes not possible. For example consider the query
```js
r.branch(r.random(2).eq(0), r.range(10000), "str")
```

This query will return a string in half of the cases, and a sequence in the other half. You can have similar (more realistic) queries where the type depends on the data in a particular table.

**Comment by rlancer** [comment]
Very true about not knowing the type till the query runs but would it be
possible to do some introspection of queries?

**Comment by danielmewes** [comment]
@rlancer It's technically possible. We don't currently support anything like this out of the box, but you could write some code yourself that analyses the query object that the driver generates before you call `run` on it.

**Comment by rlancer** [comment]
It does seems like its a driver function over a ReQL function. I'll look into that this weekend and report back my results.

**Comment by danielmewes** [comment]
> It does seems like its a driver function over a ReQL function. I'll look into that this weekend and report back my results.

:+1: Looking forward to any findings
