### ISSUE TITLE
Precompile source files needed for the windows build

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#5173]
The build infrastructure doesn't work very well on windows, and the parts that do require cygwin with many extra packages.

We already partially precompile the web assets as part of the source distribution. I would like to add `web_assets.cc`, `ql2.pb.h` and `ql2.pb.cc` to the precompiled files to reduce the amount of dependencies required to build on windows. `web_assets.cc` can replace the current individual web assets. The `ql2` files are tied to the version of protobuf they were generated with, so they are only useful if the same version of protobuf is used.

**Comment by danielmewes** [comment]
That sounds good.
This would only affect the source distribution right?

**Comment by AtnNn** [comment]
Yes, this would only affect the source distribution.

**Comment by AtnNn** [comment]
Merged into next (cb03f35)
