### ISSUE TITLE
Be smarter about when to display outdated index issue

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5175]
Currently we just compare the ReQL version of an index to the current version in order to decide whether to display an outdated index issue.

We should scan the index function and only raise the issue if the particular function was actually affected by the version change.

Since this requires adding and maintaining "last_changed_at_version" information to each term, I suggest doing something simpler that will still avoid needless index migration for most users:

* Check if the index function is a custom function, or a simple `function(x) {return x("fieldname");}`. If it is the latter, don't raise a migration issue.
* The exception would be ReQL version steps that are explicitly marked to always raise an outdated index issue. An example would be the jump from 1.15 to 1.16, where we changed the key serialization format to address certain bugs.

I think this is important because index migration is perceived as a significant burden against upgrading by many users, to the extend that I've heard from some users that they avoided upgrading just to not having to migrate indexes.

**Comment by nighelles** [comment]
This is in review 3447,
implemented in nighelles/5175
https://github.com/rethinkdb/rethinkdb/tree/nighelles/5175

**Comment by nighelles** [comment]
This is in next.
