### ISSUE TITLE
data explorer up arrow for history traversing

### ISSUE THREAD

**Issue by ftKnox** [rethinkdb/rethinkdb#5178]
Would be nice usability boost to be able to use the up arrow to traverse backwards through query history in the data explorer.

**Comment by deontologician** [comment]
:+1:

**Comment by marshall007** [comment]
This already works with `alt+↑/↓`.

**Comment by danielmewes** [comment]
We should think of ways to make the existing shortcuts easier to discover. I wasn't aware of the ALT+arrow one for example (thanks @marshall007 :) ).

Having just the up arrow traverse the history is not a good idea I think, because it clashes with editing multi-line queries.

**Comment by ftKnox** [comment]
@danielmewes you could just check that the cursor is at position 0 correct? seems like using alt does this check already.

**Comment by ftKnox** [comment]
i think the alt+up is fine, i just didn't know it existed.

**Comment by danielmewes** [comment]
I'm going to close this in favor of https://github.com/rethinkdb/rethinkdb/issues/671 , as it mostly seems to be a discoverability issue.
