### ISSUE TITLE
remove `ql` tests from `./test/run`

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5183]
From `./test/run` we have the `ql` tests, that just running a subset of the `./test/rql_test/test-runner` tests, specifically:
- `connections/connection.js`, `connections/promise.js`, and `connections/cursor.js`
- `connections/connection.py` and `connections/cursor.py`
- `connections/connection.rb`
- all of the `polyglot` tests as a single test per language

There are a few problems with this approach:
- there are a lot more `polyglot` tests then when this was devised, so timeouts on those tests are not uncommon
- we are missing the rest of the `connections` tests
- the error output through `./test/run` only outputs `stderr` to the console making quick troubleshooting difficult
- since all of the `polyglot` tests for a language are grouped together a single error is reported in a not-easy-to-decipher format

My opinion on this is that we should just remove the `ql` tests from `./test/run` as it seems that people are using `./test/rql_test/test-runner` enough that we are covered there. Alternately I should run all of the `connections` tests for each language as a single group, so we pick them all up.

Longer term this will be moot when we merge these two testing systems (#3442).

**Comment by larkost** [comment]
Oh.. and for clarity: I am looking to see if anyone objects to this. If not I will probably make the change next week.

**Comment by larkost** [comment]
I should also note that at least one person has started dropping tests into `./test/rql_test` directly, and those tests (even if they were properly put in a sub-folder) would not be picked up in this testing.

**Comment by danielmewes** [comment]
I usually run tests through `run`, but I'm not opposed to separating `run` and `test-runner` tests completely for the time being. It will definitely make things clearer, in that I'll know to run both in order to get full coverage.

**Comment by larkost** [comment]
This has been pushed into `next` with 903b45e3
