### ISSUE TITLE
Make optargs nicer in the java driver

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#5184]
Currently we just have a two argument chainable method for optargs:

``` java
between(3, 100).optArg("left_bound", "open").optArg("right_bound", "closed")
```

But we actually can do better than this since we have all of the optarg names and types listed in [global_info.json](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/global_info.json), I believe it would be possible to do something along the lines of:

``` java
between(3, 100, Optarg.of<>()
    .leftBound(Bound.OPEN)
    .rightBound(Bound.CLOSED))
```

Pros:
1. Optargs can be checked at compile time
2. Syntax is a bit better than chaining `.optArg` a bunch of times
3. Better syntax for lambdas provided to optargs.

Currently, we have no optargs that accept lambdas, but there are several proposals to add them (#3753, #3736 ) Right now, since the value in the optarg is dynamically typed, Java can't infer the lambda type, so we'd need to do things like:

``` java
.optArg("emit", (ReqlFunction2)((acc, b) -> stuff_here)).optArg("bar", 3)
```

compared to:

``` java
OptArg.of<>().foo((a, b) -> stuff_here).bar(3)
```

**Comment by danielmewes** [comment]
The contra argument for doing this is that we will need to maintain the list of supported optargs in the future.

I have a slight preference for keepings the optarg syntax the same it is now, and not introducing specific methods for the different optional arguments.

Lambda optargs are an interesting case. We could offer the proposed optarg syntax only for those arguments, and not for others. On the other hand that would be inconsistent.

Would you be ok with delaying this discussion until we introduce the first `lambda` optargs?

**Comment by deontologician** [comment]
I'm ok with delaying discussion, this would be a little bit of work as well so I don't think I can do it right away. I think in general the java community is in favor of stronger typing and this is a place I think it's tractable to provide stronger typing. The number of optargs is enumerable and they don't (currently) allow a reql term to dynamically evaluate their value

Personally, I think optargs are completely tractable to keep up to date. We have to add docs for each one anyway, so there's a reasonable time we could slap them into the json file and regenerate the java driver

**Comment by adriantodt** [comment]
Hey, the Java driver now has it's own repository (https://github.com/rethinkdb/rethinkdb-java), so I guess discussion should be moved there. I created an issue (https://github.com/rethinkdb/rethinkdb-java/issues/13) quoting this one. This issue can be closed.
