### ISSUE TITLE
Getting an update column's new value in a row in rethinkdb

### ISSUE THREAD

**Issue by vskr** [rethinkdb/rethinkdb#5185]
I am trying to get and update a column in a row in rethinkdb using a similar statement.

       User.get_table() \
                 .get(self.id) \
                 .update(return_changes = True, 
                    {'reward_amount' :r.row['reward_amount'].default(0)+amount}) \
                 .run(User.get_conn())
I am getting new value by passing return_changes=True, but is it possible to write a anonymous function that just returns new value as a int instead of array of old and new objects (which is what return_changes=True does)

**Comment by encryptio** [comment]
Sure; the `update` returns an object that's queriable with all the existing ReQL operators, so you could do:

```
   User.get_table() \
             .get(self.id) \
             .update(return_changes = True, 
                {'reward_amount' :r.row['reward_amount'].default(0)+amount}) \
             ["changes"]["new_val"]["reward_amount"] \
             .run(User.get_conn())
```

(Although that may need some slight whitespace tweaking to work with Python syntax; I'm not sure.)

Closing because this isn't a bug, but feel free to continue to ask questions here.
