### ISSUE TITLE
Windows 7 compatibility

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5194]
A lot of people still run Windows 7.

If it's not too hard, we should try to make the Windows port compatible with it.

It looks like we're at least using one function that's only available in Windows 8: `GetSystemTimePreciseAsFileTime` (see https://github.com/rethinkdb/rethinkdb/issues/1100#issuecomment-163558526 ).

**Comment by AtnNn** [comment]
@danielmewes To test this, we're going to need a copy of Windows 7. I believe the best way to do that would be to buy an MSDN subscription.

**Comment by AtnNn** [comment]
I set the `WINVER` and `_WIN32_WINNT` to target Windows Vista, but I haven't been able to test it on Windows 7 yet. See [alpha2](https://github.com/rethinkdb/rethinkdb/issues/1100#issuecomment-164890825)

**Comment by coffeemug** [comment]
I think we can just get a VM of Windows 7 here: https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/.

**Comment by kofalt** [comment]
You may want to have your legal guys take a quick look at the [license terms](http://modernievirt.blob.core.windows.net/vhd/release_notes_license_terms_1_5_15.pdf) linked from that download page, in particular page 5:

> You  may  install and use  the  software  on one  computer for  use  by  one  person at  a time ... You  may  use  the  software  for  testing  purposes  only ... You  may  not  use  the  software  for 
commercial purposes ... You may not use the software in a live operating environment.

> You  may  use  the  software  for  90  days  after  it  is  downloaded  to  the licensed computer. The software will stop running after 90 days...

It's not a big deal, but it is worth keeping in mind. In a previous corporate setting, we looked into using the test-IE VMs for build purposes - and ultimately decided to use them for browser testing but not for build & CI purposes, instead using MSDN for that.

Your Mileage May Vary, I Am Not A Lawyer, etc.

**Comment by AtnNn** [comment]
Another issue with the IE VM is that they only come with 32-bit Windows, no 64-bit.

**Comment by AtnNn** [comment]
I have a 32-bit windows build, I'm testing windows 7 compatibility now.

**Comment by AtnNn** [comment]
I removed two calls to `GetSystemTimePreciseAsFiletime` and now RethinkDB works on Windows 7.

**Comment by coffeemug** [comment]
:+1: :clap:

**Comment by juliankrispel** [comment]
@AtnNn is this fix released?

**Comment by juliankrispel** [comment]
@LukeBarry is trying to install rethinkdb on windows 7 32bit and can't seem to get it to work.

**Comment by danielmewes** [comment]
@juliankrispel Yes, this is fixed. However we don't provide 32 bit Windows binaries (only 64 bit).

You could build from source using the `windows_v2.3.3` branch (see https://github.com/rethinkdb/rethinkdb/blob/windows_v2.3.3/WINDOWS.md for instructions). However running on 32-bit Windows isn't well tested and not officially supported.

**Comment by codermapuche** [comment]
@danielmewes i need to use rethinkdb in windows xp 32bits, please, can you send me the unofficial binary precompiled for i use it at my own risk? i dont want download all the tools and compile myself, visual studio is an monster!

PD: Sorry for my bad english.
