### ISSUE TITLE
Only drop trivial changes if they don't cause the row to enter or exit the subscribed range

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#5205]
See http://stackoverflow.com/questions/34243969/rethinkdb-changefeeds-not-working-when-including-pluck .

It's debatable whether this is a bug or an API change, but I think it's sufficiently unintuitive behavior that we should call it a bug and fix it in a point release.

**Comment by danielmewes** [comment]
I agree that we should treat this as a bug. I'd expect an entry that enters or leaves the query range to show up as an insertion / deletion, no matter what its value in the changefeed stream is.

**Comment by mlucy** [comment]
In CR 3416 by @danielmewes .

**Comment by mlucy** [comment]
This is in next and 2.2.x.
