### ISSUE TITLE
Why can't I get out of waiting for primary state?

### ISSUE THREAD

**Issue by cggaurav** [rethinkdb/rethinkdb#5206]
![](http://d.pr/i/GDCW+)

**Comment by cggaurav** [comment]
The table reconfigure has started and doesn't finish. Is unsafe rollback the only way I get out of this state?

**Comment by danielmewes** [comment]
Thanks for reporting this @cggaurav. This seems to be a duplicate of https://github.com/rethinkdb/rethinkdb/issues/4706 . I'm going to write a reply there with some suggestions shortly.
