### ISSUE TITLE
{state:'ready'} sporadically not sent by changefeed until result of query changes.

### ISSUE THREAD

**Issue by williamstein** [rethinkdb/rethinkdb#5210]
If I set includeInitial:true and includeStates:true, and do a changefeed query, is it guaranteed -- when iterating through the values -- to get either an error or to see {state:'ready'} at some point?.    I'm looking at https://rethinkdb.com/api/javascript/changes/ .    I ask, because I assumed this in my now live production code, and it is failing randomly maybe 3-5% of the time.    

I just tried waiting 15 minutes, then modifying what the query would get, and then suddenly got the {state:'ready'}.     

So if the API doesn't guarantee {state:'ready'} without further changes, please clarify.  That would be odd, since it would make this useless.   Otherwise, I think there is a **very** serious bug that is sporadically hit in production.

NOTE: the queries I'm seeing this with are very simple -- just `.getAll(['one key']).pluck(some fields)`  -- nothing complicated at all.    (Literally, it is this: `db.table('projects').getAll(@project_id).pluck('project_id', 'host', 'state', 'storage', 'storage_request')`)

I'm using RethinkDB 2.2.1 on Ubuntu 15.04.

**Comment by danielmewes** [comment]
Hi @williamstein , it appears that you are running into https://github.com/rethinkdb/rethinkdb/issues/5157 . We're preparing to ship the point release right now. Should be out within the next 2-3 days.
