### ISSUE TITLE
long long time "waiting for primary"

### ISSUE THREAD

**Issue by airyland** [rethinkdb/rethinkdb#5219]
Can I know how much time I will wait or is it a wrong status?

![image](https://cloud.githubusercontent.com/assets/559179/11861049/18f7936e-a4b7-11e5-864c-3f6a0c9e4060.png)

**Comment by danielmewes** [comment]
Hi @airyland, thanks for the report.
We've often seen this when some servers in the cluster were unable to connect to others, for example due to firewalls or non-symmetric network tunnels.

Could you look at this comment https://github.com/rethinkdb/rethinkdb/issues/4706#issuecomment-164528069 and follow step 1 to obtain the connectivity information for each server in your cluster?

**Comment by airyland** [comment]
Sure.


````json
{
	"id": "045976c5-82ba-4f3d-9bc0-f60a4412adc1",
	"name": "mome_dz5",
	"network": {
		"canonical_addresses": [{
			"host": "127.0.0.1",
			"port": 29015
		}, {
			"host": "172.16.20.238",
			"port": 29015
		}, {
			"host": "43.*.*.*",
			"port": 29015
		}, {
			"host": "::1",
			"port": 29015
		}, {
			"host": "fe80::222:1cff:fe18:f3b3%2",
			"port": 29015
		}, {
			"host": "fe80::222:93ff:fe16:ff66%3",
			"port": 29015
		}],
		"cluster_port": 29015,
		"hostname": "mome",
		"http_admin_port": 8080,
		"reql_port": 28015,
		"time_connected": Wed Dec 16 2015 16: 07: 48 GMT + 00: 00
	},
	"process": {
		"argv": [
			"rethinkdb",
			"--server-tag",
			"mome",
			"--join",
			"43.241.221.8",
			"--bind",
			"all"
		],
		"cache_size_mb": 7186.3046875,
		"pid": 9012,
		"time_started": Wed Dec 16 2015 16: 07: 39 GMT + 00: 00,
		"version": "rethinkdb 2.2.1 (GCC 4.8.3)"
	}
} {
	"id": "cee4f54b-45cd-4bcb-8249-98b9b56d5534",
	"name": "iseekr_yu7",
	"network": {
		"canonical_addresses": [{
			"host": "127.0.0.1",
			"port": 8802
		}, {
			"host": "::1",
			"port": 8802
		}],
		"cluster_port": 8802,
		"hostname": "iseekr",
		"http_admin_port": 8803,
		"reql_port": 8801,
		"time_connected": Wed Dec 16 2015 12: 08: 04 GMT + 00: 00
	},
	"process": {
		"argv": [
			"rethinkdb",
			"--join",
			"127.0.0.1",
			"--driver-port",
			"8801",
			"--cluster-port",
			"8802",
			"--http-port",
			"8803"
		],
		"cache_size_mb": 1219.705078125,
		"pid": 21078,
		"time_started": Wed Dec 16 2015 07: 22: 37 GMT + 00: 00,
		"version": "rethinkdb 2.2.1~0trusty (GCC 4.8.2)"
	}
} {
	"id": "611d9fe8-c5b2-405d-a808-cab436c75675",
	"name": "iseekr_wji",
	"network": {
		"canonical_addresses": [{
			"host": "127.0.0.1",
			"port": 29015
		}, {
			"host": "172.16.8.111",
			"port": 29015
		}, {
			"host": "192.168.42.1",
			"port": 29015
		}, {
			"host": "43.*.*.*",
			"port": 29015
		}, {
			"host": "::1",
			"port": 29015
		}, {
			"host": "fe80::222:a2ff:fee3:c534%4",
			"port": 29015
		}, {
			"host": "fe80::222:abff:feec:b8df%2",
			"port": 29015
		}, {
			"host": "fe80::5484:7aff:fefe:9799%5",
			"port": 29015
		}, {
			"host": "fe80::581c:f3ff:fea5:767b%9",
			"port": 29015
		}],
		"cluster_port": 29015,
		"hostname": "iseekr",
		"http_admin_port": 8082,
		"reql_port": 28015,
		"time_connected": Fri Dec 11 2015 03: 16: 28 GMT + 00: 00
	},
	"process": {
		"argv": [
			"/usr/bin/rethinkdb",
			"--daemon",
			"--config-file",
			"/etc/rethinkdb/instances.d/instance1.conf",
			"--runuser",
			"rethinkdb",
			"--rungroup",
			"rethinkdb",
			"--pid-file",
			"/var/run/rethinkdb/instance1/pid_file",
			"--directory",
			"/var/lib/rethinkdb/instance1/data"
		],
		"cache_size_mb": 1545.267578125,
		"pid": 2810,
		"time_started": Fri Dec 11 2015 03: 16: 28 GMT + 00: 00,
		"version": "rethinkdb 2.2.1~0trusty (GCC 4.8.2)"
	}
````

**Comment by airyland** [comment]
I tried to shut down the server without "bind all" setting, and reconfigured the shards, now the cluster works find. Thx anyway.

**Comment by danielmewes** [comment]
@airyland Do all servers have `--bind all` now? If not, note that there's a chance that the issue might re-appear when servers fail.
In general, RethinkDB requires all servers to be able to connect to each other, in both directions.

**Comment by cggaurav** [comment]
I can confirm as well though I *think* we have symmetric network connections.
![](http://d.pr/i/WXyE+)
![](http://d.pr/i/Z9Mr+)

**Comment by danielmewes** [comment]
@cggaurav We have seen some issues with the reconnection logic lately (tracked in issue https://github.com/rethinkdb/rethinkdb/issues/2755 ). Maybe that's the cause for this (and possibly for some of the other issues you have reported previously as well?).
We have a patch that we will ship very soon in a new point release (RethinkDB 2.2.5).

Would you be willing to test a pre-release of 2.2.5 with that patch and see if it works properly for you? I just need to know which distribution+version you are running on your servers, so I can build the right package for you. If you're interested in testing the pre-release binary, please email me at daniel@rethinkdb.com .
