### ISSUE TITLE
Backfill jobs sometimes remain in `jobs` table after the backfill was aborted

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5223]
I've seen this on a handful of occasions, and @brandon-beacher also recently ran into this.

All tables had all their replicas fully ready, and yet some backfill jobs were still remaining in the `jobs` table. They weren't making any progress, and didn't appear to cause any load.

We should verify that interrupting a backfill properly cleans up everything.

**Comment by VeXocide** [comment]
Fixed in `next`, over the shoulder by @danielmewes.
