### ISSUE TITLE
ARM compiled version segfaults after interaction

### ISSUE THREAD

**Issue by cybertim** [rethinkdb/rethinkdb#5225]
I use an ARM build on my Cortex A9 ARM server.

Building of the new version 2.2.1 goes without any issues.

The server will start normal, but after any interaction (connect with a client, from the build in webclient or any other application) it will segfault.

[stacktrace on gist](https://gist.github.com/cybertim/c1117e98230bf4f507ef)

Had to fallback to 2.1.5.
If there is anything I can try with buildflags (or patches), just let me know I can test ARM builds right away.

**Comment by danielmewes** [comment]
Hi Tim, can you try building from the branch `v2.2.x` instead? It has a few
ARM-related fixes over 2.2.1 (especially
https://github.com/rethinkdb/rethinkdb/issues/5093).

- Daniel

**Comment by danielmewes** [comment]
I'm going to close this and assume that the more recent fixes in `v2.2.x` solved this. @cybertim please lt us know if this issue still persists with current versions.
