### ISSUE TITLE
Also mention per-table memory overhead in "Understanding RethinkDB memory requirements"

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5229]
We currently mention the overhead of 8 MB per table in http://rethinkdb.com/limitations/.

We should also mention it in http://rethinkdb.com/docs/memory-usage/

**Comment by thelinuxlich** [comment]
I thought this limitation had changed somehow after 2.1

**Comment by danielmewes** [comment]
@thelinuxlich The metadata overhead proportional to the total data size is now lower. We might indeed need to update that (I'll check the numbers and post the necessary updates here).

The constant per-table overhead is still essentially the same. I think it has gone down a bit in 2.2, but it's probably better to be conservative here.

**Comment by danielmewes** [comment]
Oops I just noticed I had opened this on the wrong tracker. Moving to https://github.com/rethinkdb/docs/issues/1010
