### ISSUE TITLE
Consider ShortID for alternative key generation scheme

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5231]
@thelinuxlich suggested https://github.com/dylang/shortid
The shorter IDs it generates are beneficial because they'll save space over our current UUIDs when used in primary keys, and they'll improve the performance of our btree.

The only issue might be to properly seed each node in the cluster, so that we don't get conflicts from different nodes.

Related to https://github.com/rethinkdb/rethinkdb/issues/117

**Comment by thelinuxlich** [comment]
A much better Go implementation was released: https://github.com/ventu-io/go-shortid

**Comment by thelinuxlich** [comment]
@srh we should close this and anything related should be added to #117
