### ISSUE TITLE
Added RethinkDB on Wikipedia's NoSQL page

### ISSUE THREAD

**Issue by vibl** [rethinkdb/rethinkdb#5236]
I just added RethinkDB on Wikipedia's NoSQL page. I also updated DB-Engines.com rankings on RethinkDB's page.

You might want to update other pages, lists and presentations on the web. Is there someone in charge of this? And a page with links to the places that need regular updating?

Vianney

**Comment by tatsujin1** [comment]
I also added some info to the RethinkDB entry in the list at https://en.wikipedia.org/wiki/Document-oriented_database#Implementations

**Comment by deontologician** [comment]
I think generally wikipedia editors frown on companies updating their own page. We've gotten deleted before for looking "too much like an advertisement" and the current page is pretty recent.

**Comment by deontologician** [comment]
The thinking is probably something along the lines of "if employees are the only ones updating the page, it's probably not too notable"

**Comment by danielmewes** [comment]
Like @deontologician said, we can't do much about this from our end. I think Wikipedia actually forbids companies from updating their own page. So we have to hope for users like you to edit the page.
Thanks @vibl and @tatsujin1 for your help on this!

**Comment by mglukhovsky** [comment]
If you need any data or help from us in updating the Wikipedia article, don't hesitate to ask!
