### ISSUE TITLE
question. Logging

### ISSUE THREAD

**Issue by joeblew99** [rethinkdb/rethinkdb#5240]
Its here:
https://github.com/elastic/beats/tree/master/filebeat
100% golang.
This is the replacement of i expect:
https://github.com/rethinkdb/logstash-input-rethinkdb.

SO i guess the question boils down to, does it make sense for rethink to support this new way of getting logs out of rethink and into Elastic ?

**Comment by deontologician** [comment]
It looks like this is very specifically for logs. Our logstash input and the (deprecated) river are more intended to be used to sync up elasticsearch with documents in RethinkDB so users can get the full-text search capabilities.

Are you looking to ingest the logs RethinkDB itself emits into Elasticsearch?

**Comment by joeblew99** [comment]
Thanks for the response. This is what i am needing:

1. Monitor rethink cluster logs. So log shipping of some form into Elastic
2. Full text search of data in Rethinkdb. So again Elastic.

Because Elastic can do both i was working my way through the best way to do it.

Any thoughts ?

**Comment by deontologician** [comment]
For 1. ingesting the log file in the `rethinkdb_data` directory, I would say something like filebeat would be a good choice (or the file output for logstash or something). You could use the logstash plugin to watch the `rethinkdb.logs` table, but it doesn't guarantee it will have the entire contents of the logfile, so it isn't a good idea if you need to index the entire log. (Also, that table is just a facade for reading the log file anyway, so it's just overhead that's probably not needed).

For 2, syncing the documents themselves, the logstash input is the best way. It better allows you to manipulate the documents (you could strip out all fields but text fields and the id for example), and it allows you to decouple your input from your output, which would be helpful if you end up wanting to shoot your documents somewhere else, like rabbitmq or something.

**Comment by joeblew99** [comment]
ok thanks for the tips.

i will try https://github.com/tsaikd/gogstash
Its a go version of logstash. LogStash is pretty bloated.
