### ISSUE TITLE
Pluck/filter not working on admin table initial vals in changefeeds

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#5241]
The query I ran is:

```js
r.db('rethinkdb').table('table_status')
    .filter({db: 'db1'})
    .pluck('db', 'name')
    .changes({include_initial: true, squash: true, include_states: true})
```

The initial values I get back ignore the filter (I get dbs other than 'db1'), and it does not do the pluck, I get the full document back. Once actual changes happen, the filter and pluck are respected.

I tried this on a normal table and it worked fine. I'm assuming other transformations have the same problem but I haven't checked that.

ping @mlucy: I remember us running across something like this before about changefeeds on admin tables being funky, but I can't find another issue about it. I found this issue initially in the ruby driver, but verified it in the data explorer

**Comment by mlucy** [comment]
@deontologician -- just to check, this is only on artificial tables?

**Comment by deontologician** [comment]
Right, it worked fine on a normal table

**Comment by mlucy** [comment]
This is in CR 3414 by @danielmewes .  I fixed a problem with the state documents on artificial `include_initial` streams with no initial values while I was in there.  I think we should ship this in a point release since it seems like a clear bug.

**Comment by danielmewes** [comment]
Yep I just moved it into 2.3-polish since it didn't seem critical, but since you have a fix now we should definitely backport it.

**Comment by mlucy** [comment]
This is in next and 2.2.x.
