### ISSUE TITLE
RethinkDB Dump and Restore on Mac OSX

### ISSUE THREAD

**Issue by JurgenJocubeit** [rethinkdb/rethinkdb#5244]
I've noticed that neither the Homebrew nor the Mac OS X native .pkg include `rethinkdb-dump` and `rethinkdb-restore` scripts. Can you please tell us how we can install the dependencies so we can backup and restore clusters/databases/tables on Mac OS X?

**Comment by JurgenJocubeit** [comment]
Ok so I worked out by using Homebrew I can install python and then pip the python rethinkdb driver. Any chance the native OS X .pkg will get these tools included?

**Comment by larkost** [comment]
I am going to mark this as duplicate, as we already have an issue for including the drivers in the OS X .pkg: #4507 (add drivers to server install package).

But I did want to mention that you don't have to instal Python through Homebrew. With a default instal of MacOS X (10.7+) all you need to do on the command line is: `sudo easy_install rethinkdb`, or if you prefer `pip` and have it installed: `sudo pip install rethinkdb`.

I should also mention that in that same bug I advocate to have the drivers always installed alongside the `rethinkdb` binary.
