### ISSUE TITLE
Stuck in endless 'Raft election timed out. Starting a new election for term 1407.'

### ISSUE THREAD

**Issue by samkelleher** [rethinkdb/rethinkdb#5245]
The cluster has 4 nodes and they seem to all be able to see each other as when I start or stop one of them (a slave used for replicas) they will disappear and reappear virtually instantly from the list of servers.

However the primary will just log out the above error constantly.

**Comment by samkelleher** [comment]
Although curiously if I attempt to replicate a table to one of the slaves I get:
```
The server returned the following error: The server(s) hosting table `test.table` are currently unreachable. The table's configuration was not changed.
```
The primary where the data is located is up and has the table, it sees the slaves, so do the slaves as I can browse the table data from them. I also see the log updating with entries from the primary.

**Comment by mglukhovsky** [comment]
@samkelleher: how are you creating the cluster? What environment are they running in?

Are you certain all the servers can reach each other via the network, without any intermittent interruptions?

**Comment by samkelleher** [comment]
That's okay @mglukhovsky! 😃

The environment is within Docker, 1 container marked as a master. 3 containers marked as 'slaves'. The slave containers are only different in that they have the --join argument on startup.

All 4 nodes are able to talk with any of the other members as using Docker links.

It's possible there was some sort of interuption, but I don't see how, since each node was able to access data etc.

This may be linked to the fact that one of the servers was missing before the new nodes were added. As I mentioned in #4806. So perhaps the failure is coming from the primary still trying to contact the dead server and killing the election in the process.

If that's the case then a new election can't take place once a server becomes missing before the cluster was created, which is a bit undesirable. I'm guessing it's best to run RethinkDB with either 1 or at least 3, but never 2.  I'll continue testing with 3 nodes and drop back with an update.

**Comment by larkost** [comment]
Just before seeing this issue I wrote up #5257 (Better report raft election timeouts), which if implemented would improve troubleshooting this.

**Comment by samkelleher** [comment]
In my case, a missing voting replica was missing before new shards were added. So no new election would take place. An emergency repair to remove the missing node resolved my situation.

I recommend advising in documentation that only 2 nodes should never run in a cluster. Either one, or at least 3.  Running 2 can get stuck like what happened to me.
