### ISSUE TITLE
Investigate test failure with order_by.limit changefeed

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5247]
I'm currently working on a fuzzing test for a few additional changefeed queries (currently available at https://github.com/rethinkdb/rethinkdb/blob/bc401bbba2853bb3159851aa2a40e0e943c6be80/test/rql_test/init_fuzz_various_queries.rb#L23 ). If I enable the query `$tbl.order_by(index: :id).limit(5)`, the test gets stuck.

Maybe the changefeed never becomes ready?

**Comment by danielmewes** [comment]
The test is at https://github.com/rethinkdb/rethinkdb/blob/bc401bbba2853bb3159851aa2a40e0e943c6be80/test/rql_test/init_fuzz_various_queries.rb#L23

**Comment by danielmewes** [comment]
The server also gets stuck in "Shutting down client connections..." during shutdown and must be killed.

**Comment by danielmewes** [comment]
The issue of `rethinkdb` not shutting down can seemingly be resolved by replacing line 2687 by
```c++
nap(50, env->interruptor);
```

However the test still hangs, so I suspect that something else is wrong.

**Comment by mlucy** [comment]
This appears to be caused by the `.orderby.limit` changefeed preventing one or more of the range changefeeds from becoming ready.  `.orderby.limit` changefeed messages consume timestamps from the same pool as the range changefeed messages, so there's probably somewhere where we're expecting sequential timestamps but not getting them.

**Comment by mlucy** [comment]
A fix for this is in CR 3408 by @danielmewes .

**Comment by danielmewes** [comment]
Moving this into the 2.2.3 release. Since we couldn't release last week because of some technical issues, we are going to retag and release 2.2.3 with two additional bug fixes instead.

**Comment by mlucy** [comment]
This is in next and 2.2.x.
