### ISSUE TITLE
compile source code rethinkdb face with Error: unsupported architecture: aarch64-redhat-linux

### ISSUE THREAD

**Issue by dong88885** [rethinkdb/rethinkdb#5249]
I download the rethinkdb source code with version 2.2.2 ,then upack it .
when execute "./configure --allow-fetch" ,an error occurs :
"
Error: unsupported architecture: aarch64-redhat-linux
"

the whole information as fallows:
=========================
[root@Centos rethinkdb-2.2.2]# ./configure --allow-fetch
* Reading arguments from 'configure.default'
* Prepending the following arguments: --fetch re2 --fetch gtest --fetch v8
* Detecting system configuration
Bash:                           4.2.46(1)-release
Use ccache:                     no
C++ Compiler:                   GCC 4.8.3 (/usr/bin/c++)
Host System:                    aarch64-redhat-linux
Build System:                   Linux 3.14.56 aarch64
Cross-compiling:                no
Host Operating System:          Linux
* Error: unsupported architecture: aarch64-redhat-linux
===============================================

**Comment by danielmewes** [comment]
I don't think we currently support 64 bit ARM (only 32 bit). I'm going to open a follow-up issue for porting RethinkDB to it.

**Comment by danielmewes** [comment]
@dong88885 See https://github.com/rethinkdb/rethinkdb/issues/5265

**Comment by ryanaverill** [comment]
+1
