### ISSUE TITLE
Database crashed on inserts with r.http

### ISSUE THREAD

**Issue by sagivf** [rethinkdb/rethinkdb#5252]
Seems like my Database is constantly crashing. I'll try to pin point when it happen, but perhaps the logs will mean something to you guys.

Basically I am doing a lot of inserts that include heavy use of the `r.http` module.
I make about 15 insert requests, with about 20 documents each. Each document is linked to about 5 different http request to enrich it's data.

![image](https://cloud.githubusercontent.com/assets/1857466/12114581/a1f8943c-b3b3-11e5-8563-315be9b10134.png)

**Comment by sagivf** [comment]
A am also getting this all the time

![image](https://cloud.githubusercontent.com/assets/1857466/12118244/0ab258ae-b3ce-11e5-9401-339545ccf933.png)

**Comment by danielmewes** [comment]
Thanks for the report @sagivf .

Which OS are you on, and which version of RethinkDB are you running? How did you install RethinkDB (e.g. from the APT repository, through homebrew, compiled from source etc.)?

Are your `r.http` queries using a public API that we could also use for testing this? If yes, what are the exact `r.http` queries you're running?

Assigning @Tryneus .

**Comment by pablokbs** [comment]
Hello, I work with Sagiv, the details are:

OS Version: Ubuntu 14.04.1 LTS
RethinkDB version: rethinkdb 2.1.3~0trusty (GCC 4.8.2)
Install method: APT repo (deb     "http://download.rethinkdb.com/apt" trusty main)

**Comment by sagivf** [comment]
I will add as much info as I can on the htto requests tomorrow - thanks.

**Comment by encryptio** [comment]
#4793 appears to have a nearly identical backtrace, and is given in text there. (I wasn't able to reproduce it when I saw it.)

**Comment by Tryneus** [comment]
Closing this in favor of #5256, which contains more information and a link to the review for the fix.
