### ISSUE TITLE
Support 64 bit ARM architecture

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5265]
Related to https://github.com/rethinkdb/rethinkdb/issues/5249

**Comment by dalanmiller** [comment]
Will also be good for future versions of Rasbian on the Raspberry Pi 3, currently the distro is still not 64 bit but the Raspberry Pi 3 processor is 64 bit.

**Comment by 360disrupt** [comment]
The processor is `64 bit` but the linux is `32 bit`. I had the same confusion with installing `nodejs` on the pi3, had to install the `armv7` version not the `arm64`.

**Comment by shahar3012** [comment]
Any progress on supporting 64-bit ARM architecture?
I have PINE64, so far I couldn't complete the build process.
I'm trying to build it on the PINE64, I'll update if it happened to succeed.

**Comment by AtnNn** [comment]
There hasn't been any progress.

You could try building and running a 32-bit rethinkdb.

If you are interested in porting rethinkdb to arm64, we can help. Come over to our #engineering slack channel or post to the rethinkdb-dev mailing list.

**Comment by vielmetti** [comment]
If anyone is interested in getting access to ARMv8 (arm64, aarch64) data center scale systems please let me know - Packet has a 96-core, ARMv8 type 2A server that I'm building all sorts of stuff on with generally good success.

**Comment by vielmetti** [comment]
In Slack, @srh mentions https://github.com/rethinkdb/rethinkdb/pull/1625 as a starting point should one want to port.

**Comment by gdeverlant** [comment]
Hi guys I did a little part of the work but I cannot do the ASM part at all... 

I hope that someone can complete the rest from now on :D

https://github.com/gdeverlant/rethinkdb/commits/next

**Comment by yangwao** [comment]
There is also scaleway.com supports aarch64 and I could help test it on my odroid c2.

**Comment by gdeverlant** [comment]
Notice!!!! It is not working yet

the ASM part is not done

**Comment by gdeverlant** [comment]
Following to that I have a clsuter of 12 arm32 and arm64 boards with total of 48 cores and 23 GB ram for testing purpose.

**Comment by robertjpayne** [comment]
@davidthomas426 would you have any interesting in doing the assembly for ARM64? Or have any ability to do it anyways? Sorry to drag you out of a very old PR!

**Comment by robertjpayne** [comment]
Well I took the plunge and actually managed to pull this off 👍 should be mergeable but would be great to have more people testing.

**Comment by gdeverlant** [comment]
Brother I would love to test this on my arm64 cluster!

Million thanx!

**Comment by gdeverlant** [comment]
This is what happens when I try to compile from your repo:

```
 ./configure --allow-fetch
* Detecting system configuration
Bash:                           4.3.30(1)-release
Use ccache:                     no
C++ Compiler:                   GCC 6.4.0 (/usr/bin/c++)
Host System:                    aarch64-linux-gnu
Build System:                   Linux 4.12.0-gx-117136-g44bd33f aarch64
Cross-compiling:                no
Host Operating System:          Linux
* Error: unsupported architecture: aarch64-linux-gnu

* Aborting configure
```

**Comment by lag-linaro** [comment]
It looks like this Issue should be closed, since it is now possible to build RethinkDB for ARM/ARM64.

**Comment by srh** [comment]
Good point!
