### ISSUE TITLE
Consider supporting Java 7

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5266]
We had some discussion about this in https://github.com/rethinkdb/rethinkdb/issues/3930 and it also came up again for building Android apps in https://github.com/rethinkdb/rethinkdb/issues/5253 .

If I remember correctly, @deontologician mentioned that this wouldn't be too hard.

However I'm not convinced yet that it's worth our time.

**Comment by poovarasanvasudevan** [comment]
any update on this?

**Comment by rusmichal** [comment]
bump

**Comment by adriantodt** [comment]
The Java driver now lives in https://github.com/rethinkdb/rethinkdb-java. Android 8.0 and Android Studio natively support Java 8, so open a ticket there instead if it doesn't work. This issue can be closed.
