### ISSUE TITLE
Add a hint to `emergency_repair` to `reconfigure` error

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5267]
If you try to `reconfigure` a table for which too many servers are currently missing, we return the following error: `The server(s) hosting table `test.t1` are currently unreachable. The table's configuration was not changed.`

We should add a note to the error message that suggests using `emergency_repair` if those servers are permanently missing. Maybe with the URL of the `reconfigure` API docs. 

This scenario happens quite often for people who run 2 server clusters, and the `emergency_repair` option is currently hard to discover. This has lead to people not knowing what to do in at least two cases already.

The message should also mention the servers that are missing if possible.

**Comment by danielmewes** [comment]
http://rethinkdb.com/api/javascript/reconfigure/#emergency-repair-mode

**Comment by nighelles** [comment]
In review 3449.
nighelles/5267

**Comment by nighelles** [comment]
This is in next.
