### ISSUE TITLE
new_val and old_val are the same

### ISSUE THREAD

**Issue by stellanhaglund** [rethinkdb/rethinkdb#5271]
Hi! I'm editing an object inside a table and listen to that table using changes

and use cursor.each()

but for the changed row I get this

<img width="405" alt="skarmavbild 2016-01-08 kl 12 29 48" src="https://cloud.githubusercontent.com/assets/2523054/12197063/07fb916a-b604-11e5-8896-9a7581f8ecdd.png">

I'm editing the verified key from false to true but it says true in both

I'm using version 2.2.1

**Comment by stellanhaglund** [comment]
Sorry it was completely my mistake I was handling the data wrong.

**Comment by danielmewes** [comment]
Happy to hear it's now working for you.
