### ISSUE TITLE
r.http "reattempts" param unrecognised

### ISSUE THREAD

**Issue by sagivf** [rethinkdb/rethinkdb#5275]
Very strange - 
The docs say you can use - "reattempts". 

Running it in the "dataexplorer" and with the Javascript driver I get 
`e: Unrecognized optional argument reattempts..`

oddly "attempts" works in the  "dataexplorer",
but trying in with the Javascript driver I get
`available options are reattemps <number>, redirects <number>, verify <boolean>, resultFormat: <string>, method: <string>, auth: <object>, params: <object>, header: <string>, data: <string>, page: <string/function>, pageLimit: <number>');`

Notice the missing *t* in reattemps (trying with the miss spelling doesn't work either)

**Comment by danielmewes** [comment]
Thanks for the issue report @sagivf. I think the correct argument is `"attempts"`, and the docs are wrong.

However I'm not sure why `"attempts"` is failing for you with the JavaScript driver. I can't find the miss-spelled term `reattemps` in our current code base, so I'm unsure where that's coming from. Maybe that message is generated by `libcurl` somehow? @Tryneus could you look into that please?

**Comment by sagivf** [comment]
@danielmewes - I checked again and the problem is in rethinkdbdash, I'll open I bug there.
Sorry for for the bother - still it's good to that the docs will get fixed...

**Comment by sagivf** [comment]
https://github.com/neumino/rethinkdbdash/issues/215

**Comment by danielmewes** [comment]
Ah, thanks for the update @sagivf .
I opened https://github.com/rethinkdb/docs/issues/997 for fixing our docs.
