### ISSUE TITLE
Java driver SSL support

### ISSUE THREAD

**Issue by pires** [rethinkdb/rethinkdb#5278]
I've looked into the code and the driver doesn't seem to support SSL. Can someone clarify on the current state of this?

I'm happy to contribute with a PR that adds SSL support but I'll for sure need to debate with someone. I'm on Slack #driver-dev.

**Comment by deontologician** [comment]
This is correct, SSL support doesn't exist in the driver currently. It's
intended to be added, but we hadn't done it quite yet. A PR would be very
welcome!

**Comment by pires** [comment]
I have been able to produce code that successfully connects to a secure (both TLS and auth key). I'll be working on improving it before opening a PR but I have a question: how am I supposed to make tests everyone can run for this given a secure server is needed?

**Comment by danielmewes** [comment]
@pires That's great news.
Pinging @larkost about the testing part. I don't think we have any infrastructure for testing this automatically at the moment though, so manual tests will need to suffice.

**Comment by larkost** [comment]
A couple of points to make:
- The RethinkDB server does not support SSL (or any encryption) at this point. We do have an issue to change this, but it has not been scheduled yet: #3158
- Our other drivers have SSL support, but it is in service of Compose.io. They have a system that sets up a SSL-enabled proxy that allows secure connections from the drivers to their service. I don't know that anyone else is using this.
- I do have some work on a setup for testing this, but have not completed it #4084. I t has fallen behind a number of other tasks.

**Comment by pires** [comment]
@larkost @danielmewes I'm testing with my compose.io account so good news since it works ;) I'm OK with providing the code and documentation on how to test it with compose.io.

PR will follow very soon.

**Comment by pires** [comment]
PR submitted.
