### ISSUE TITLE
Substantial Writes cause bottleneck on Mac OSX

### ISSUE THREAD

**Issue by ChrisCates** [rethinkdb/rethinkdb#5285]
Hey, so when I am doing ~25 writes a second.

The query profile for a 20k row table is:

![screen shot 2016-01-13 at 3 36 45 pm](https://cloud.githubusercontent.com/assets/1561091/12307159/93a10cf8-ba0b-11e5-8aaf-a65b4071ac40.png)

However, when I am not doing writes. The query is responsive and performant.

![screen shot 2016-01-13 at 3 38 16 pm](https://cloud.githubusercontent.com/assets/1561091/12307180/b1568746-ba0b-11e5-938e-f36262c893fd.png)

Any help on speeding up the performance on Mac OSX?

**Comment by ChrisCates** [comment]
Using Mac OSX Yosemite.

**Comment by ChrisCates** [comment]
The offending script:

```
var mysql      = require('mysql');
var r = require("rethinkdbdash")();
var async = require("async");

require("rethink-config")({
  "r": r,
  "database": "ilac",
  "tables": [
    "legacy"
   ],
});

var connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'root',
  password : 'root',
  database : 'ilac_legacy',
  port: 8889
});

connection.connect();

var count = 20447;
var page = 0;
var maxPages = 3500;

async.whilst(function() {
  return page < maxPages
}, function(whilst) {
  connection.query("SELECT * FROM `student_info` LIMIT 500 OFFSET " + (count + (page * 500)), function(err,rows,fields) {
    if (err) throw err;

    async.mapLimit(rows, 25, function(row, callback) {
      r.db("ilac").table("legacy").filter(row).then(function(result) {
        if (result.length == 0) {
          r.db("ilac").table("legacy").insert(row).then(function() {
            console.log("Row inserted #" + count);
            count++;
            callback(null);
          });
        } else {
          console.log("Row already exists #" + count);
          count++;
          callback(null);
        }
      })
    }, function(err) {
      page++;
      whilst(null);
    });
  })

})
```

**Comment by ChrisCates** [comment]
![screen shot 2016-01-13 at 3 41 20 pm](https://cloud.githubusercontent.com/assets/1561091/12307256/27b086d0-ba0c-11e5-87fd-3b6600219c7c.png)

It's doing 90k reads/sec. Now I know what I'm doing wrong... Gonna add a secondary index and only filter based on id.

**Comment by ChrisCates** [comment]
I added a secondary index, and, now it does 300/writes a second. r.db("ilac").table("legacy").getAll(row.myid, {index: 'myid'})

**Comment by danielmewes** [comment]
Oh so it was doing a full table scan for the `filter` for each write?
Is the `count` query faster now as well under writes?

**Comment by ChrisCates** [comment]
@danielmewes Yea! It's much better. Around 30-50ms for 120k documents.
