### ISSUE TITLE
Feature req: optimistic concurrency control

### ISSUE THREAD

**Issue by gebrits** [rethinkdb/rethinkdb#5286]
does RethinkDb support optimistic versioning?
If not, any plans on supporting this?

**Comment by danielmewes** [comment]
@gebrits Could you explain what you mean by optimistic versioning? I'm not familiar with the term.

**Comment by kwando** [comment]
I'm directly thinking about _Optimistic Locking_ when reading that, but I'm sure @gebrits knows what he means :smile:

**Comment by gebrits** [comment]
@danielmewes: I meant optimistic concurrency / locking, also sometimes known as CAS: check-and-set. 

The (optional) ability to send a versionId with an update request. The update only succeeds if the versionId send equals the current versionId of the document. If not a conflict is thrown. 

What happens in a case of conflict depends on the client. From, for example, the Elasticsearch docs: 

> What we do now depends on our application requirements. We could tell the user that somebody else has already made changes to the document, and to review the changes before trying to save them again. Alternatively, as in the case of the widget stock_count previously, we could retrieve the latest document and try to reapply the change.

https://www.elastic.co/guide/en/elasticsearch/guide/current/optimistic-concurrency-control.html

**Comment by gebrits** [comment]
@kwando missed your comment somehow. But indeed :)

**Comment by mlucy** [comment]
@gebrits -- you can do this yourself with `update` or `replace`.  If every document has a `version` field, you would write something like:

```
r.table('test').get(id).update(function(row) {
  return r.branch(row('version').eq(VERSION), {version: NEW_VERSION, ...}, r.error("ERROR"));
})
```

(Where `VERSION` and `NEW_VERSION` are UUIDs or something.)

**Comment by gebrits** [comment]
@mlucy: cool stuff!

**Comment by kureus** [comment]
Great that you can hand roll, but would it not be worth supporting optimistic concurrency control out of the box?
If you are going to update a document there are so many scenarios where you'd want to check if it had changed since you read it?

**Comment by danielmewes** [comment]
RethinkDB 2.4 will come with configurable "write hooks" that would allow you to automatically increment the version field with every update. https://github.com/rethinkdb/rethinkdb/issues/5813

That would simplify this.
