### ISSUE TITLE
Import script is not compatible with Python 2.6

### ISSUE THREAD

**Issue by Tryneus** [rethinkdb/rethinkdb#5294]
We're using a dict comprehension in `_import.py` that does not work in `python2.6`.

A fix has been approved and merged to `next` in commit 32c232f, and cherry-picked into `v2.2.x` in commit 6fb9616.

Opening this issue for tracking purposes.

**Comment by danielmewes** [comment]
I'll upload an updated Python driver...

**Comment by danielmewes** [comment]
A new version of the Python driver 2.2.0.post3 is now available on PIP.
