### ISSUE TITLE
Queue.java has a debug logging statement in serialize()

### ISSUE THREAD

**Issue by sceutre** [rethinkdb/rethinkdb#5306]
This hits my logs all the time when developing, and never replaces the %s so it's not even very useful.  I'd put it as a trace stmt and fix the %s to {}.  eg:
```
logger.trace("Serialized query: {}", Util.bufferToString(bb));
```

**Comment by danielmewes** [comment]
Thanks for reporting this @sceutre .

@deontologician could you look into this please?

**Comment by deontologician** [comment]
Ok, put up a PR. @sceutre could you take a look at tell me if that's the change you were looking for?

**Comment by sceutre** [comment]
Looks good to me, thanks.
