### ISSUE TITLE
Web-ui shows wrong max number of shards for cluster with more then 32 nodes

### ISSUE THREAD

**Issue by r-marques** [rethinkdb/rethinkdb#5311]
In the webui for version `2.2.3-1` in a cluster with 64 nodes the webui tells me that the maximum amounts of shards that I can create is 64, although the limit is 32.

![rethinkdb_shard_error](https://cloud.githubusercontent.com/assets/1793187/12505554/481ec868-c0e8-11e5-84af-c0ff5f2bc914.png)

**Comment by danielmewes** [comment]
Good catch. I think we should also bump the server-side limit to 64 while we're at it.
I'm not sure how well we scale to 64 shards, but I don't believe there's a strong technical reason to restrict it to 32 (@vexocide: Are you aware of any actual limitation? I think we have limited resolution for the distribution query, but apart from that?).

**Comment by r-marques** [comment]
From the writes performance test I have been doing with rethinkdb I can say that it scales beautifully until I have 32 nodes. Adding more nodes after that doesn't increase the write performance due to the shard limit and I eventually hit the IO limit on the nodes holding the primary replicas. Would love to test my cluster with a 64 shards

**Comment by nighelles** [comment]
This is in review 3492, implemented in nighelles/5311.

**Comment by nighelles** [comment]
This is in next.

**Comment by r-marques** [comment]
@nighelles Is the number of shards only hardcoded in the ui?

**Comment by deontologician** [comment]
@r-marques It's hardcoded in the database logic as well
