### ISSUE TITLE
TypeError: Cannot read property 'enqueue' of undefined

### ISSUE THREAD

**Issue by Suvitruf** [rethinkdb/rethinkdb#5312]
With simple select query:

      var query = pool.r.table(table).get(key);

I get error `TypeError: Cannot read property 'enqueue' of undefined`.

It happens on RethinkDB 2.2.3-1.

Same script works fine on older version of Rethink.

Same query in web admin console works.

Looks like problem in Java Driver. But I've tried to downgrade it to version that I use on another servsers (1.16.2). Anyway doesn't work neither with 1.16.2, nor 2.2.1.

**Comment by Suvitruf** [comment]
But I use nodejs v4.2.6 on this server. So, is problem 'cause driver doesn't support this version?

**Comment by Suvitruf** [comment]
I've downgraded nodejs to v4.2.2. Doesn't work anyway...

**Comment by Suvitruf** [comment]
Problem was 'cause of using old version of libs.

**Comment by danielmewes** [comment]
Happy to hear it's now working. Let us know if you run into any further issues.
