### ISSUE TITLE
`orderBy.limit.filter` has wrong behavior

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5325]
Client 1:
```js
r.table('test').orderBy({index: "id"}).limit(1).filter({v: true}).changes()
```

Client 2:
```js
r.table('test').insert({id: 2, v: true})
// Value appears on changefeed

r.table('test').insert({id: 1, v: false})
// Nothing appears on changefeed
// Would expect: {old_val: {id: 2, v: true}, new_val: null}
```

If this is hard to fix, we should probably just detect and disallow a filter after an `orderBy.limit` in a changefeed.

(mentioning @mlucy)

**Comment by mlucy** [comment]
Good catch.  I think we should just disallow `.orderBy.limit.filter`.

**Comment by danielmewes** [comment]
> I think we should just disallow `.orderBy.limit.filter`.

Agreed. Sounds good to me.

**Comment by nighelles** [comment]
In review 3474, branch nighelles/5325.

**Comment by nighelles** [comment]
This is in next.
