### ISSUE TITLE
Raspberrypi

### ISSUE THREAD

**Issue by joeblew99** [rethinkdb/rethinkdb#5326]
Any thoughts on supporting v2 raspberry pi.
The v2 is  is a different arm ISA version and much easier.

I currently run my middle tier code on raspberry pi with golang. It's very easy.

In terms of OS, I am currently using Ubunutu Core. It's 16.04 LTS.
Basically libs and or application for the next version of Ubuntu can be written as debs or the new Snaps.
Snaps can reference deps. Installing Snaps is crazy easy, as is writting them.

https://developer.ubuntu.com/en/snappy/build-apps/

Raspian is also another option as an OS. It's a bit different in terms of tooling. Bespoke you could say.

I prefer Ubuntu core and Snaps because then for servers, desktop and embedded writting and installing is 100% the same. So I am hoping that this fact leans you to packaging as Snaps :)

**Comment by danielmewes** [comment]
RethinkDB already works on the Raspberry PI 2.

Though in general our ARM support is experimental and there still appear to be some issues depending on the used compiler / build environment.

Have you seen http://rethinkdb.com/docs/install/raspbian/ ?

**Comment by joeblew99** [comment]
Have now. Thanks.
A Ubuntu core snappy would help me installs cycles alot. Maybe other here too ?

**Comment by danielmewes** [comment]
I opened a separate issue about Snappy packages: https://github.com/rethinkdb/rethinkdb/issues/5338
