### ISSUE TITLE
Allow connecting through SSL for `rethinkdb-backup`, `rethinkdb-restore`, `index-rebuild` etc.

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5330]
There should be command line options to connect to a RethinkDB server through SSL.

**Comment by danielmewes** [comment]
This is important especially for importing data into Compose clusters, like in this example https://www.compose.io/articles/3-csv-and-other-databases/

**Comment by danielmewes** [comment]
@nighelles Could you look into this?

We basically need an option for specifying a CA certificate file for these commands, and pass that to `connect`.

You can start a test server with a TLS-encrypted driver port on `next` by following the steps described here: https://github.com/rethinkdb/docs/issues/1057#issuecomment-200515848

**Comment by nighelles** [comment]
This is in review 3547, implemented in nighelles/5330

**Comment by nighelles** [comment]
This is in next.
