### ISSUE TITLE
Make cursors in Python driver print the first few elements.

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#5331]
I thought we had changed this a long time ago, but currently the Python driver has the following behavior:

```
In [3]: r.table('configs').run()
Out[3]: <rethinkdb.net.DefaultCursor at 0x7ff4d535ec50>
```

That's not very helpful behavior for interactive use.  I think we want to make the Python driver behave more like the Ruby driver here, which does this:

```
irb(main):017:0> r.table('configs').run
#<RethinkDB::Cursor:11519140 (enumerable): r.table("configs")
[{"InstanceType"=>"t2.micro",
  "NumServers"=>1,
  "Version"=>"7a0af72a-6720-4695-a08b-4cf1eaa18a45",
  "id"=>"mlucy"}]>
```

(Basically, when it prints a cursor it prints the first 10 elements of the cursor or however many elements the server has sent us, whichever is fewer.  If the cursor isn't exhausted, it prints a `...` to indicate that there's more in it.)

This is *drastically* nicer for interactive use than having to put `list(...)` around the cursor, especially if there's a lot of rows in the table and you just want to quickly see what it looks like rather than actually loading the whole thing into an array.

Putting this into 2.3 because @encryptio and I have actually been finding it really annoying when playing around in Python, but I wouldn't object too strongly if we bumped this to subsequent.

**Comment by nighelles** [comment]
You could do this by changing the __repr__ function in python, but that breaks from the python conventions for interactive mode, I think, as a custom __repr__ is meant to be interpretable.

If you do something like
`print r.table('configs').run()`
then you get the __str__ method, which is meant to be a user readable version.
Although looking into it just now, doing this right now causes an error.

**Comment by nighelles** [comment]
The error was from trying to slice a deque.

**Comment by nighelles** [comment]
In review 3456,
Implemented in nighelles/5331
https://github.com/rethinkdb/rethinkdb/tree/nighelles/5331

**Comment by nighelles** [comment]
This is in next.
