### ISSUE TITLE
Use RapidJSON instead of cjson

### ISSUE THREAD

**Issue by thedrow** [rethinkdb/rethinkdb#5337]
RapidJSON is a really fast JSON parser and supports SIMD optimizations which is a goal we discussed in #4903.
It should improve JSON parsing greatly on machines that support SIMD (which is 99% of them these days).

**Comment by thedrow** [comment]
It seems like we're using both. Any reason why?

**Comment by AtnNn** [comment]
RethinkDB already uses RapidJSON. CJSON is only used for backwards compatibility.

See the discussion here: https://github.com/rethinkdb/rethinkdb/issues/3844#issuecomment-98212020
