### ISSUE TITLE
Protocol Discrepancies Between Linux and Windows

### ISSUE THREAD

**Issue by bchavez** [rethinkdb/rethinkdb#5349]
Hi @AtnNn , first off: ***beautifu*l** work on the windows **alpha2** build. I'm finally able to stop shipping the C# unit tests over to **CircleCI** to have them run.

So, I gave `alpha2` a try and I noticed some protocol discrepancies between **Linux** servers and **Windows** servers running **RethinkDB**.

The C# driver [has the full battery of auto generated YAML tests](https://github.com/bchavez/RethinkDb.Driver/tree/master/Source/RethinkDb.Driver.Tests/Generated) just like the **Java** driver.

All unit tests are **green** against a **Linux** server. When the YAML tests are thrown against `alpha2` some unit tests are failing. Here's a particular example:
```
Test:
	datum/number.yaml, LineNum: 95
Expected ReQL:
	float(1234567890123456789012345678901234567890)
Expected C#/Java:
	float_(1234567890123456789012345678901234567890.0)
Run ReQL:
	r.expr(1234567890123456789012345678901234567890)
Run C#/Java:
	r.expr(1234567890123456789012345678901234567890.0)
RunOpts: []

Protocol In Context:
	JSON Send: Token: 12, JSON: [1,1.2345678901234568E+39,{}]
	JSON Recv: Token: 12, JSON: {"t":1,"r":[1.2345678901234567e39]}

PROBLEM:

Expected value to be between 1.23456789012346E+39 and 1.23456789012346E+39, but found 1.23456789012346E+39.
```

Looks more interesting when we pop up **Wireshark** protocol analyzer to see the actual wire-line transfer:

#### RethinkDB LINUX (PASSING)
![linux](https://cloud.githubusercontent.com/assets/478118/12772877/c3ad2230-c9ea-11e5-9c5d-1b43ba1ff21d.png)

#### RethinkDB Windows (FAILING)
![windows](https://cloud.githubusercontent.com/assets/478118/12772879/c744f6a2-c9ea-11e5-9a98-acfc776bb241.png)

This one is tricky. But... do you see it? :mag: **6 bytes** from the end of each the response: 

* **Linux**: `0x39`
* **WIndows**: `0x37`

The full list of failing tests and their protocol outputs are here:
https://ci.appveyor.com/project/bchavez/rethinkdb-driver/build/365/tests

Also, if you want to run these tests while I'm away from the computer, you can send a PR with the new `serverDownload` URL in the build script [`build.fsx`](https://github.com/bchavez/RethinkDb.Driver/blob/master/Builder/build.fsx). Then your PR/newURL will get built and tested at https://ci.appveyor.com/project/bchavez/rethinkdb-driver/build/tests

Again, as always, awesome work with windows! :+1: 

Thanks,
Brian

Test Setup
**Windows**: Windows Server 2012 R2
**Linux**: Ubuntu 14.04

**Comment by AtnNn** [comment]
Thanks for the detailed report, that helps a lot. I'll investigate and let you know what I find.

**Comment by AtnNn** [comment]
This looks like an error in parsing, storing or formatting floating point numbers, not a protocol error.

I was unable to reproduce. Against both the Windows and Linux version of RethinkDB, I get these results using the Python driver:

```
>>> r.expr(1234567890123456789012345678901234567890).to_json().run()
u'1.2345678901234569e39'
>>> repr(r.expr(1234567890123456789012345678901234567890).run())
'1.2345678901234568e+39'
```

**Comment by bchavez** [comment]
Hi @AtnNn these traces were pulled from network packets from Wireshark before reaching the client for parsing.

If you examine the network-level packets, you *should* see the discrepancies at the network packet level. As the result passes through the application layer on the client side the official drivers maybe shield these effects.

I guess the main issue is:
* Do we possibly want linux & windows servers returning possibly different values **at the network level** and have the drivers shield these differences between linux/windows?

Also, I'm not exactly sure how you are getting the date/time unit tests pass in the official drivers because what I'm finding with the Date/Time tests are off protocol? They have these "JUL" values in the iso8601 values.

```
Test:
	times/timezones.yaml, LineNum: 81
Expected ReQL:
	("2015-07-08T00:00:00-08:00")
Expected C#/Java:
	"2015-07-08T00:00:00-08:00"
Run ReQL:
	r.epoch_time(1436428422.339).in_timezone('-08:00').date().to_iso8601()
Run C#/Java:
	r.epochTime(1436428422.339).inTimezone("-08:00").date().toIso8601()
RunOpts: []

Protocol In Context:
	JSON Send: Token: 19, JSON: [1,[100,[[106,[[104,[[101,[1436428422.339]],"-08:00"]]]]]],{}]
	JSON Recv: Token: 19, JSON: {"t":1,"r":["2015-Jul-08 00:00:00"]}

PROBLEM:

Expected string to be 
"\"2015-07-08T00:00:00-08:00\"" with a length of 27, but 
"\"2015-Jul-08 00:00:00\"" has a length of 22.
```

**Comment by AtnNn** [comment]
I am also unable to reproduce the time related failures. With `rethinkdb-windows-alpha3`, I get:

```
>>> r.epoch_time(1436428422.339).in_timezone('-08:00').date().to_iso8601().run()
u'2015-07-08T00:00:00-08:00'
```

It's possible that the failures you see happen because RethinkDB is behaving differently in your environment. A quick look at the source seems to indicate that RethinkDB uses `%m` to format the month, which the boost documentation tells me is a two-digit representation. More investigation is required.

**Comment by bchavez** [comment]
Just updated to `alpha3` on the CI server, date/time unit tests are passing. Only failing test is the number one:

#### LINUX PASSING
```
JSON: [1,1.2345678901234568E+39,{}]
JSON: {"t":1,"r":[1.234567890123456__9__e39]}
```
#### WINDOWS FAILING
```
JSON: [1,1.2345678901234568E+39,{}]
JSON: {"t":1,"r":[1.234567890123456__7__e39]}
```
**__ __** added for emphasis.

Full battery of tests passing so far with windows version of RethinkDB server: https://ci.appveyor.com/project/bchavez/rethinkdb-driver/build/380/tests

**Comment by bchavez** [comment]
@AtnNn I was looking at the binary output for double-precision floating point... found this:

```
111010000011001001001000000111010111000000110111000000000~..: CLIENT
111010000011001001001000000111010111000000110111000000000~..: LINUX
111010000011001001001000000111010111000000110110111110000~..: WINDOWS
```

Might be a clue to what's happening with floating point in windows?

**Comment by larkost** [comment]
I am a bit late in commenting, but I think that this is just normal floating point storage issues. Because we are not doing anything to make sure that we have only a single flowing point implementation, we should expect small rounding errors like this. Usually I would expect it more in things that involve math (e.g.: multiplication), but this still looks like valid behavior to me.

I will probably just put an appropriate range allowance on these tests, since they are more precise than floating point actually allows.

**Comment by danielmewes** [comment]
Hmm the fact that just round-tripping through the JSON protocol introduces rounding errors is a bit weird though, isn't it?
We are setting `RAPIDJSON_PARSE_DEFAULT_FLAGS=kParseFullPrecisionFlag` in our `build.mk` make file. @AtnNn is that getting applied on Windows too or might we somehow not hit that definition with the Windows build system?

**Comment by danielmewes** [comment]
I just checked the generated `rethinkdb.vcxproj` on Windows and it doesn't contain the `RAPIDJSON_PARSE_DEFAULT_FLAGS` definition. That might be the issue.

**Comment by bchavez** [comment]
Hi @larkost ,

Are you referring to in-memory storage of floating point values?

If I recall correctly, the failing C# test is here
[**`DatumNumber.YamlTest` Line 165**](https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver.Tests/Generated/DatumNumber.cs#L167):
```
r.expr(1234567890123456789012345678901234567890.0)
```
I would probably feel more comfortable with rounding issues as a result of some kind of mathematical operation but I don't think there are any mathematical operations being performed on the floating point value when the test is using `r.expr()`. I feel a bit reluctant to pass this one off as a rounding issue tho. My main concern is the different wire-line responses I get from windows vs linux for the same `r.expr()` query.
```
SEND >>> 1.234567890123456_[8]_e39: CLIENT
RECV <<< 1.234567890123456_[9]_e39: Linux Server
RECV <<< 1.234567890123456_[7]_e39: Windows Server
0 10010000000 1101000001100100100100000011101011100000011011100000: CLIENT
0 10010000000 1101000001100100100100000011101011100000011011100000: Linux Server
0 10010000000 1101000001100100100100000011101011100000011011011111: Windows Server
```
I'd be more than happy to test any findings. Alternatively, you can hit up a PR that changes the [`serverDownload` URL](https://github.com/bchavez/RethinkDb.Driver/blob/master/Builder/build.fsx#L7). Any PR to the repo triggers the full battery of unit tests on AppVeyor in the **Tests** tab: https://ci.appveyor.com/project/bchavez/rethinkdb-driver

**Comment by danielmewes** [comment]
@bchavez I'll send you a `rethinkdb.exe` with the `RAPIDJSON_PARSE_DEFAULT_FLAGS=kParseFullPrecisionFlag` fix shortly. Thanks for helping us test this.

**Comment by danielmewes** [comment]
@bchavez You can download the build with the potential fix here: https://www.dropbox.com/s/a4vexv4zizf9w1a/rethinkdb-windows-5349.zip?dl=1

**Comment by bchavez** [comment]
@danielmewes Ah, yep. That seems to be it. https://ci.appveyor.com/project/bchavez/rethinkdb-driver/build/471/tests `DatumNumber` YAML tests are passing now both on AppVeyor and dev box with your precision flag set. :+1: Nice find!!! :)
