### ISSUE TITLE
Problems with gevent support in the python driver from next

### ISSUE THREAD

**Issue by nickmishustin** [rethinkdb/rethinkdb#5350]
I have installed python driver from `next` according to [instructions](https://github.com/rethinkdb/rethinkdb/issues/4433#issuecomment-172833164) . I tried Changefeed with gevent-socketio and it didn't work - `self.emit()` doesn't work when `r.table(...).changes().run()` called.
How I can make it work?

**Comment by nickmishustin** [comment]
My problem it related to the incorrent gevent-soketio using.
Sorry to trouble.

**Comment by danielmewes** [comment]
@nickmishustin Is it working now?
If it's still not working: Are you getting any error message? Do you have some example code to reproduce the problem?

**Comment by nickmishustin** [comment]
@danielmewes It's working now. It was my mistake.
