### ISSUE TITLE
`return_changes: 'always'` doesn't always return changes

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#5366]
Some errors that are caught before issuing the inserts to the shards don't actually populate the `changes` array properly.  For example, `r.table('test').insert({id: 'a'*500}).run(return_changes: 'always')` doesn't properly return a `{new_val: nil, old_val: nil}` change the way `r.table('test').insert({id: r.minval}).run(return_changes: 'always')` does.  We should change the code to include trivial changes for errors detected before reaching the shards.

**Comment by nighelles** [comment]
It looks like that error is getting caught in the driver before going into the insert logic.

**Comment by mlucy** [comment]
@nighelles -- I don't think the driver is smart enough to detect when primary keys are too long, is it?  The Ruby driver isn't, at least.

**Comment by nighelles** [comment]
Ah, I see what you're saying. In the js driver, 'a'*500 gives NaN.

**Comment by nighelles** [comment]
This is fixed in review 3587, implemented in nighelles/5366

**Comment by danielmewes** [comment]
Merged into next with 439213a and v2.3.x with 84007ed.
