### ISSUE TITLE
"between" command with multi-index

### ISSUE THREAD

**Issue by bgnorlov** [rethinkdb/rethinkdb#5370]
I have few records in table "projects" with multi-index "files"
```
{
"files": ["b" ,"c" ,"d"] ,
"user_id": 1,
"id":  "1a55e999-e30d-485a-b81a-93d90ced5c65"
}, {
"files": ["a" ,"b" ,"c"],
"user_id": 1,
"id":  "938572db-51c4-46a7-b704-5102b0a111e0"
}, {
"files": ["b" ,"c" ,"d"] ,
"user_id": 2,
"id":  "b1fd44d1-0543-4324-8c23-234dde78ebe7"
}, {
"files": ["c" ,"f" ,"e"] ,
"user_id": 2,
"id":  "b1a2cd50-9498-4d8e-b119-95dbb9a80f45"
}
```
I tried to select all records with "a" files using between command : r.db('test').table('project').between("a", "a", {index: 'files',leftBound: 'open', rightBound: 'open'}) but got empty array (I expect to get one file  {"files": ["a" ,"b" ,"c"],"user_id": 1,"id":  "938572db-51c4-46a7-b704-5102b0a111e0"} ). It's a bug or I missed something?

**Comment by bgnorlov** [comment]
I realised that I have been confused with "open", "closed" terminology so when I set to close all working properly. However, when I tried to chain between command ((table_slice.between(lowerKey, upperKey[, options]) → table_slice ) ) with another one - `
r.db('rocketslides').table('project').between("a", "a", {index: 'files',leftBound: 'closed', rightBound: 'closed'}).between(1, 1, {index: "user_id"})
`
I got this error `e: Cannot perform multiple BETWEENs on the same table in:
r.db("rocketslides").table("project").between("a", "a", {"index": "files", "leftBound": "closed", "rightBound": "closed"}).between(1, 1, {"index": "user_id"})
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by danielmewes** [comment]
@bgnorlov You can't mix multiple indexes on the same table. There are two options to accomplish filtering by two values at once:
1. Using an index for one criteria, and then use `filter` for the second one. `filter` is less efficient as it has to look at each document, but is more flexible. http://rethinkdb.com/api/javascript/filter/
2. Creating a compound index and using that with `between` or `getAll`. In your example case where you're actually only looking for a particular value, `getAll` would be easier to use than `between`: http://rethinkdb.com/api/javascript/get_all/
See www.rethinkdb.com/docs/secondary-indexes/javascript/#compound-indexes for more information on compound indexes.

**Comment by trungtin** [comment]
@danielmewes Could you help with my case:
Simplify, I have a Post with multiple Tags (limits at 3) and Scores. And user can query multiple tags at a time. If I use multi index, then I can use `get_all` to query, let say 10 posts with a list of user tags. Then how can I query those with highest Scores. If I use 3 separate compound index like this:
```
FirstTagIndex: [FirstTag, Points],
SecondTagIndex: [SecondTag, Points].
ThirdTagIndex: [ThirdTag, Points]
```
 then use `between` and `orderBy` and I can get top Scores post but I have to take `number of user selected tags` * `3 tags per post` queries each times, if somehow I can use `between` like `getAll` with multi index then I only have to query 3 time.

**Comment by danielmewes** [comment]
@trungtin I don't think there's any efficient way to fetch multiple tags with an index and at the same time do the ordering for the results with the highest score with an index.
If the result set is not too large, you could simply do an un-indexed `orderBy` after the `getAll`.

In the next release of RethinkDB (2.3.0), you could use the new ordered `union` to merge the ordered results for each tag: https://github.com/rethinkdb/rethinkdb/issues/5090
But this isn't supported in RethinkDB 2.2 yet.
