### ISSUE TITLE
JS Promises inconsistence

### ISSUE THREAD

**Issue by lolwhoami** [rethinkdb/rethinkdb#5379]
I'm able to use .then() and .error() when I want to get data, but when I want to write/update anything I still have to write it in callbacks style. That's strange.

**Comment by chrisvariety** [comment]
Both [connect](http://rethinkdb.com/api/javascript/connect/) and [run](http://rethinkdb.com/api/javascript/run/) return promises. What problems are you running into using promises when running writes/updates?

**Comment by lolwhoami** [comment]
My bad.
Now I tried this again with working code and it works fine.

Yesterday I was seeing something like
> r.table(...).get(...).update(...).run(...).then **is not a function**

Sorry.

**Comment by chrisvariety** [comment]
Glad you figured it out! You will definitely see `then is not a function` if you try to run any query without the `.run()`
