### ISSUE TITLE
Java driver connection/cursor handling simplification

### ISSUE THREAD

**Issue by pires** [rethinkdb/rethinkdb#5380]
As per @bchavez comments:

> So, after some additional review, I have a strong feeling the ResponsePump and awaiters stuff should really go into SocketWrapper like the .NET driver. I think there's too much state to "remember to clear" in Connection class if a connection is restarted... and it will be harder to get right as Connection code gets bigger in the future ... it also encourages usage of the awatiers dictionary at the Connection level, which shouldn't be accessed by anything else other than the response pump like this: pires#2
> 
> if ResponsePump and awatiers get encapsulated in SocketWrapper generally these problems go away like in the .NET driver when a new socket is created on reconnect.... Currently, the Java Connection a lil bit more complicated to get right the way it is setup now.... For example: how awaiters is being cleared at the Connection.close() level ... if we move ResponsePump and it's awaiters state in SocketWrapper these network "state" troubles go away because it's logically separated from the main connection class.
> 
> :heavy_check_mark: Connection is responsible for closing high-level Cursors. Then...
> :heavy_check_mark: SocketWrapper:ResponsePump is responsible for cleaning up it's own awaiters.
> 
> SocketWrapper and it's state wont ever be used again, and can safely be GC'ed. And avoids "forgot to clear" state issues.
> 
> Let me know what you think. If you think the name SocketWrapper is too low level, maybe we could rename it. Dunno.

I agree and this would be good to have.

**Comment by adriantodt** [comment]
I implemented this without even knowing that this issue existed. This is now implemented to one of the branches (https://github.com/rethinkdb/rethinkdb-java/pull/12) of the Java driver, which now lives in a separated repository (https://github.com/rethinkdb/rethinkdb-java). This issue can be closed.
