### ISSUE TITLE
On Windows, `--bind all` doesn't seem to work

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#5382]
When running RethinkDB with `--bind all` it lists `192.168.0.173`, my local IP, but connecting remotely doesn't work.

A workaround is to pass `--bind 192.168.0.173`.

**Comment by Wargog** [comment]
I'll try and confirm, I've been trying to get this to work on my machine as well

**Comment by Wargog** [comment]
Does the same thing on my development box too, binding directly to my private IP worked

**Comment by MedAnd** [comment]
:+1: 

I've documented similar findings on the google user group: https://groups.google.com/forum/#!topic/rethinkdb/89iX-qn7gbQ

**Comment by danielmewes** [comment]
@AtnNn fixed this.
