### ISSUE TITLE
Windows Preview 0 Crashes During Full Battery of Unit Tests

### ISSUE THREAD

**Issue by bchavez** [rethinkdb/rethinkdb#5386]
Hello,

I [just updated the server download testing URL](https://github.com/bchavez/RethinkDb.Driver/commit/68082874c4e74ec7f1052900fa6520e62bbb71b0) to use the official `preview 0` windows build from:

http://rethinkdb.com/docs/install/windows/

I tested this on local dev box and CI server. Each time, about half-way though the C# driver testing process, `rethinkdb.exe` crashes:

https://ci.appveyor.com/project/bchavez/rethinkdb-driver/build/381#L5329

(Line **5329** on the CI server's build/test log)

```
Version: rethinkdb 2.2.4-windows-alpha-4 (debug) (MSC 190023506)
error: Error in thread 12 in src\threading.cc at line 27:
error: Assertion failed: [home_thread() == get_thread_id()] home_thread(): 0, get_thread_id(): 12
error: Backtrace:
error: Wed Feb 10 12:39:27 2016

       1: 0x000000013F6A7B35 [The specified module could not be found.]
       2: 0x000000013F6A8161 [Attempt to access invalid address.]
       3: 0x000000013F6A753B [Attempt to access invalid address.]
       4: 0x0000000140514647 [Attempt to access invalid address.]
       5: 0x0000000140FFAD86 [Attempt to access invalid address.]
       6: 0x000000013F6611F8 [Attempt to access invalid address.]
       7: 0x000000013F660389 [Attempt to access invalid address.]
       8: 0x000000013F694622 [Attempt to access invalid address.]
       9: 0x000000013F69B475 [Attempt to access invalid address.]
       10: 0x000000013F6A7263 [Attempt to access invalid address.]
       11: 0x000000013F6A709A [Attempt to access invalid address.]
       12: BaseThreadInitThunk+13
       13: RtlUserThreadStart+33
error: Exiting.

R:\>
```

This did not happen with `alpha3`. Something seems to have changed.

Also, please don't forget, we have a [double-precision floating point protocol issue](https://github.com/rethinkdb/rethinkdb/issues/5349#issuecomment-180178033) to work out too. =)

**Comment by AtnNn** [comment]
@bchavez thanks for the report. Could you pinpoint more exactly what query causes the crash?

I'm going to decode the backtrace and investigate.

**Comment by bchavez** [comment]
Sure no problem @AtnNn , give me a few minutes to see if this is a reproduce this event on the same query.

**Comment by bchavez** [comment]
Okay, so it looks like I can get it to fail on this unit test in `Default`:

```
 //JavaQuery, default.yaml, #131
 /* ExpectedOriginal: [{}, {'a':1}] */
 var expected_ = r.array(r.hashMap(), r.hashMap("a", 1L));
 
 /* Original: arr.filter(lambda x:x['a'].eq(1), default=r.js('true')) */
var obtained = runOrCatch( arr.filter(x => x.bracket("a").eq(1L)).optArg("default", r.js("true")) , new {}, conn);
```
Let me know if you can reproduce.

**Comment by AtnNn** [comment]
Thanks @bchavez, I am able to reproduce.

**Comment by AtnNn** [comment]
Extprocs were sometimes performing IO on the wrong thread. Fixed in 880a61b.

**Comment by bchavez** [comment]
Is there a build I can test?

**Comment by AtnNn** [comment]
Here you go: http://circus.atnnn.com/ipfs/QmQaZiJNyAkWshdD3xRBmLYjvgoDpzm8QNYAStpo6SifDo/rethinkdb-windows-alpha-5.zip

**Comment by bchavez** [comment]
Awesome! Thank you so much @AtnNn , kicked off the test battery on `alpha5`: https://ci.appveyor.com/project/bchavez/rethinkdb-driver/build/386

I'll report back in about an hour after my night hike is done.

**Comment by AtnNn** [comment]
Thanks for running your tests again. Looking at the results it seems that this crash did not happen, but the issues reported in #5349 and #5389 did. I'm currently tracing the code one line at a time to figure those out.

**Comment by bchavez** [comment]
Hi @AtnNn , right-o, looks like the date/time issue is showing up again. Perhaps it's a `print` issue in `r.js`?

```
Test:
	times/time_arith.yaml, LineNum: 190
Expected ReQL:
	("2012-08-01T00:00:00+00:00")
Expected C#/Java:
	"2012-08-01T00:00:00+00:00"
Run ReQL:
	r.do(r.js("new Date('2012-08-01')")).to_iso8601()
Run C#/Java:
	r.do_(r.js("new Date('2012-08-01')")).toIso8601()
RunOpts: []

Protocol In Context:
	JSON Send: Token: 20, JSON: [1,[100,[[64,[[11,["new Date('2012-08-01')"]]]]]],{}]
	JSON Recv: Token: 20, JSON: {"t":1,"r":["2012-Aug-01 00:00:00"]}

PROBLEM:
Expected string to be 
"\"2012-08-01T00:00:00+00:00\"" with a length of 27, but 
"\"2012-Aug-01 00:00:00\"" has a length of 22.
```
We get back `Aug` instead of `08` when using `r.js(...)`.

**Comment by bchavez** [comment]
If you need Remote Desktop access on the CI server with build tools, let me know. You can ping me in IRC or slack.
