### ISSUE TITLE
ReqlQueryLogicError Error in time logic - Windows

### ISSUE THREAD

**Issue by snobear** [rethinkdb/rethinkdb#5389]
Hi,
I just fired up the Windows dev-preview-0 today and hitting this error when inserting a Date:

```
{name: "ReqlQueryLogicError", msg: "Error in time logic: Month number is out of range 1..12.",…}
```

I do _not_ hit this issue when I point to a Rethink instance 2.2.4 on Ubuntu (I followed [the exact steps here](https://www.rethinkdb.com/docs/paas/#deploying-on-aws) to fire up an instance on AWS ).

On the Windows side, I'm running Windows 10 and with rethink running locally.

**To reproduce**

Clone https://github.com/snobear/3ree and follow the steps for npm install, etc...  then load up localhost:3001 and enter something in the form. In Chrome dev tools you'll see the failed call in the Network tab. I use Gitbash on Windows 10. That repo is my fork of https://github.com/GordyD/3ree which I had to tweak to get the `npm start` command work to in Windows.

The relevant bits of code:

```
export function addEvent(event) {
  return connect()
  .then(conn => {
    event.created = new Date();
    event.text = xss(event.text);
    return r
    .table('pulses')
    .insert(event).run(conn)
    .then(response => {
      return Object.assign({}, event, {id: response.generated_keys[0]});
    });
  });
}
```

and the full error per Chrome:

```
error: {name: "ReqlQueryLogicError", msg: "Error in time logic: Month number is out of range 1..12.",…}
frames: [1, "created", 0]
message: "Error in time logic: Month number is out of range 1..12 in:↵r.table("pulses").insert({"text": "foo", "value": 50, "userId": "4542f270-d04e-11e5-a98d-0fa3e0bdd90a", "created": r.ISO8601("2016-02-11T02:06:01.718Z")})↵                                                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^   "
msg: "Error in time logic: Month number is out of range 1..12."
name: "ReqlQueryLogicError"
event: {text: "foo", value: 50, userId: "4542f270-d04e-11e5-a98d-0fa3e0bdd90a",…}
created: "2016-02-11T02:06:01.718Z"
text: "foo"
userId: "4542f270-d04e-11e5-a98d-0fa3e0bdd90a"
value: 50
```

Lemme know if you need more info.

**Comment by AtnNn** [comment]
Thanks for the report. The month is that timestamp is `02`, which is obviously correct.

**Comment by AtnNn** [comment]
This bug seems to caused by the order of static initialisation. In the alpha4 build, this line initialises `month_day_format` incorrectly:

```
const std::locale month_day_format = std::locale(std::locale::classic(), new input_timefmt_t("%Y-%m-%dT%H:%M:%s%ZP"));
```

**Comment by rsantosdev** [comment]
Same happens to me

**Comment by kaminskypavel** [comment]
+1 same here  

- [x] Win 10
- [x] rethinkdb 2.2.4-windows-alpha-4 (debug) (MSC 190023506)

**Comment by kaminskypavel** [comment]
Also why not posting older build for [Win](https://download.rethinkdb.com/windows/) as with https://download.rethinkdb.com/osx/?

**Comment by hobbit125** [comment]
+1 same here.  Win 10, 2.2.4-windows-alpha-4

**Comment by danielmewes** [comment]
@kaminskypavel You can find previous alpha builds in https://github.com/rethinkdb/rethinkdb/issues/1100#issuecomment-179568382 and upwards. Since the developer preview was our first official Windows release, there are no previous releases on `download.rethinkdb.com`. Once we release more versions, the old ones will remain on the download servers just as for the other systems.

**Comment by kaminskypavel** [comment]
thanks for the info, @danielmewes.
as a workaround I suggest the  2.2.4 docker image of rethink, works flawlessly.

**Comment by AtnNn** [comment]
I think cb007e1 fixes this. Could you test this new build?

http://circus.atnnn.com/ipfs/QmZkxXdHE9sRhNQ91Fh418wN927GdJ2QBVnQeZLDV3LX5j/rethinkdb-windows-alpha-6.zip

**Comment by snobear** [comment]
Yes, that appears to have fixed it for me!  (alpha 6, Windows 10)

**Comment by snobear** [comment]
@AtnNn is there a place I can access the latest Windows builds?  For now I'm using the 2.2.4 alpha 6 build you linked to above, but wasn't sure if there's been others since then.

On the public rethinkdb site, I still see the one from Feb 10 in https://download.rethinkdb.com/windows/.

**Comment by hackerunet** [comment]
Hello, I'm having exactly the same problem, can you please post a newer version or post a fix for the bug?
regards

**Comment by snobear** [comment]
There's a link to a patched version a few comments up.

**Comment by hackerunet** [comment]
yeah yeah, I already notice that and it worked like a charm. Thanks a lot!

**Comment by djeeg** [comment]
thanks, that's fixed it on Windows 8

**Comment by danielmewes** [comment]
I believe this is no longer an issue with the more recent Windows releases. Please re-open if this still occurs.
