### ISSUE TITLE
Intermittent NullPointerException in Java driver 2.2-beta-2 when reading from result stream

### ISSUE THREAD

**Issue by bittrance** [rethinkdb/rethinkdb#5397]
```
java.lang.NullPointerException: null
! at com.rethinkdb.net.Response.parseFrom(Response.java:36)
! at com.rethinkdb.net.ConnectionInstance.readResponse(ConnectionInstance.java:87)
! at com.rethinkdb.net.ConnectionInstance.readResponse(ConnectionInstance.java:61)
! at com.rethinkdb.net.Connection.runQuery(Connection.java:196)
! at com.rethinkdb.net.Connection.run(Connection.java:240)
! at com.rethinkdb.ast.ReqlAst.run(ReqlAst.java:66)
```

Driver is 2.2-beta-2.

I'm running the same query over and over, and it fails sometimes. Anectdotally, it seems to be failing more frequently when the result set is large, say 4 kb.

```
            events = r.table(Constants.TABLE_NAME)
                    .getAll(vin).optArg("index", Constants.KEY_VIN)
                    .filter(ev -> ev.getField(Constants.KEY_RECEIVED).during(
                            r.epochTime(finalFrom), r.epochTime(finalTo)))
                    .orderBy(Constants.KEY_RECEIVED)
                    .run(conn);
```

**Comment by bchavez** [comment]
Sounds like #5355

**Comment by bittrance** [comment]
Ah, there it is. The Github search engine failed me. I will try a build from master branch and verify in a day or two.

**Comment by bittrance** [comment]
Ah, there it is. The Github search engine failed me. I will try a build from master branch and verify in a day or two.

**Comment by bittrance** [comment]
Ah, there it is. The Github search engine failed me. I will try a build from master branch and verify in a day or two.

**Comment by danielmewes** [comment]
@bittrance Since #5255 isn't merged yet, you'll have to build from git://github.com/vomjom/rethinkdb.git branch java_driver_fix to test it.
