### ISSUE TITLE
Check that `r.now` does proper arity checking

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5405]
This came up in https://github.com/rethinkdb/rethinkdb/issues/5403

**Comment by Tryneus** [comment]
Fix is up in review 3484.

**Comment by Tryneus** [comment]
The fix has been approved and merged to `next` in commit c016269, and cherry-picked into `v2.2.x` in commit b99e213.  Will be in release 2.2.5.
