### ISSUE TITLE
Cannot build rethinkdb 2.2.4 on Darwin: v8 libtool error

### ISSUE THREAD

**Issue by wmertens** [rethinkdb/rethinkdb#5412]
I am trying to build rethinkdb from source with http://nixos.org/nix/ on OS X El Capitan. Nix creates a sandbox environment for the build, making available only the specified inputs.

The problem I have is that v8 doesn't build, `libtool` errors out on the use of `-static`:

```
...lders/g4/76q469c16sg48h2xcl17lm900000gn/T/nix-build-rethinkdb-2.2.4.drv-0/rethinkdb-2.2.4/build/external/v8_3.30.33.16/build/out/x64.release/obj.target/v8_base/src/ic/x64/ic-compiler-x64.o /private/var/folders/g4/76q469c16sg48h2xcl17lm900000gn/T/nix-build-rethinkdb-2.2.4.drv-0/rethinkdb-2.2.4/build/external/v8_3.30.33.16/build/out/x64.release/obj.target/v8_base/src/ic/x64/stub-cache-x64.o
Usage: /nix/store/n9s1gn8hrxgkz26kz5r5813pyw3c21ri-libtool-2.4.6/bin/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
libtool:   error: unrecognised option: '-static'
tools/gyp/v8_base.target.x64.release.mk:479: recipe for target '/private/var/folders/g4/76q469c16sg48h2xcl17lm900000gn/T/nix-build-rethinkdb-2.2.4.drv-0/rethinkdb-2.2.4/build/external/v8_3.30.33.16/build/out/x64.release/libv8_base.a' failed
make[3]: *** [/private/var/folders/g4/76q469c16sg48h2xcl17lm900000gn/T/nix-build-rethinkdb-2.2.4.drv-0/rethinkdb-2.2.4/build/external/v8_3.30.33.16/build/out/x64.release/libv8_base.a] Error 1
make[3]: Leaving directory '/private/var/folders/g4/76q469c16sg48h2xcl17lm900000gn/T/nix-build-rethinkdb-2.2.4.drv-0/rethinkdb-2.2.4/build/external/v8_3.30.33.16/build/out'
Makefile:286: recipe for target 'x64.release' failed
make[2]: *** [x64.release] Error 2
make[2]: Leaving directory '/private/var/folders/g4/76q469c16sg48h2xcl17lm900000gn/T/nix-build-rethinkdb-2.2.4.drv-0/rethinkdb-2.2.4/build/external/v8_3.30.33.16/build'
```

The build is basically just running the standard configure and make process, with some minor patching. [The build description is here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/nosql/rethinkdb/default.nix), anything not explicitly mentioned is the "default" build process.

Any pointers on how to fix?

How about using [one of the v8 packages already built in Nix](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/libraries/v8), and not linking statically?
Versions v3.16, v3.24 and v4.5 are available, and others could be added if needed. Nix has the advantage that it absolutely refers to dependent libraries, so there is never a problem with getting a different lib version than you were expecting.

**Comment by danielmewes** [comment]
Do you know which version of `libtool` Nix is linking into the sandbox?

I think the V8 build system assumes the XCode version, not the GNU one.

Wonder if there's a patch for the Nix v8 packages or if there's a different reason for why they don't encounter the issue.

Using an existing V8 is tricky because we also use the ICU header files from V8.

**Comment by wmertens** [comment]
Indeed, the libtool comes from gcc. I'll try using the XCode one.

As for the icu header files, if regular icu is not visible during build but v8 is, that should be the ones that are picked, right? Any way to check what is being used, something to grep in the resulting binaries perhaps?

**Comment by larkost** [comment]
`v8`'s way of including ICU is a bit complex, and they actually use a modified version that has the ICU table expanded. My understanding is that this later bit it to allow `v8` to use virtual memory much more efficiently if you have a lot of instances going (which is common). A couple of us here (I am only the most recent) have done battle with this setup a few times, and there are a lot of hoops to jump though.

Additionally we strongly prefer using the version of `v8` that we have. They have been changing the API regularly, so trying to cover system versions is a difficult moving target.

**Comment by srh** [comment]
Note that we'll be dropping our requirement of ICU in 2.4 and next. If I remember correctly we can link against a later version of v8, and the Windows build config uses that.  You might want to try dynamically linking with the v2.4.x or next branches now.  Feel free to reopen if you still see this.
