### ISSUE TITLE
offsetsOf returns wrong offset when orderBy is not applied.

### ISSUE THREAD

**Issue by ironhee** [rethinkdb/rethinkdb#5419]
```js
function idToOffset(query, pk) {
  const offset = query.offsetsOf(row => row('id').eq(pk)).nth(0);
  return offset;
}

const query = table.query();  // orderBy is not applied

const resource = await query.nth(10).run(connection);
const offset = await pkToOffset(query, resource.id).run(connection);

expect(offset).to.equal(10);  // sometimes, offset is not 10. (12, 13, 11...)
```

Like this situation.

```js
const query = table.query().orderBy('id'); 
```

When `orderBy` applied, Problem is removed. 
Is this intended?

**Comment by danielmewes** [comment]
‎This is expected. Without an `orderBy` the order of `r.table` is not guaranteed and depends on timing, sharding and other factors. If you add an `orderBy({index: "id"})`, that will be pretty efficient and enforce a deterministic ordering.

**Comment by ironhee** [comment]
Ok I understand. Thank you for detailed answer :D
