### ISSUE TITLE
Small parameter error on "Install RethinkDB on Windows" website

### ISSUE THREAD

**Issue by sceee** [rethinkdb/rethinkdb#5421]
Thank you so much for providing the Windows Developer Preview.

I just wanted to point out that there is an error on the website
http://rethinkdb.com/docs/install/windows/

The command
`rethinkdb.exe -n jarvis --j cluster.example.com`
uses two "minus" chars before the cluster wheras the command would be correct the following way:
`rethinkdb.exe -n jarvis --j cluster.example.com`

**Comment by danielmewes** [comment]
Thanks for the report @sceee. I've copied this to our separat issue tracker for documentation: https://github.com/rethinkdb/docs/issues/1025
