### ISSUE TITLE
Make RethinkDB error when compiling with Clang 3.2

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#5424]
There's a bug where brace initialization of structs with reference counted pointers sometimes causes the destructors of those reference counted pointers to not be called.  (Or at least that appears to be the behavior, and the same behavior doesn't happen in either GCC or newer version of clang.)

@AtnNn, do we have a standard way of refusing to compile with a particular version of a compiler?

**Comment by AtnNn** [comment]
@mlucy: the configure script can test for a lower bound on the version. we currently set `min_clang_version=0` here https://github.com/rethinkdb/rethinkdb/blob/next/configure#L14

**Comment by danielmewes** [comment]
We should do this for 2.3, not for 2.2.x I think. We also need to do https://github.com/rethinkdb/rethinkdb/issues/2230 first, because the version of Clang on OS X 10.7 is also affected (though I think it uses a different version numbering scheme?).

**Comment by AtnNn** [comment]
I think it would be better to test for this behaviour instead of for a specific compiler version. @mlucy Can you write a small self-contained test case?

**Comment by nighelles** [comment]
I added a clang_test.cc file in nighelles/5424.

**Comment by danielmewes** [comment]
@AtnNn Can you integrate that into the configure script? https://github.com/rethinkdb/rethinkdb/blob/29980dbefefc059cf0b1b81acd12837f235eb6f1/test/clang_test.cc

**Comment by nighelles** [comment]
@danielmewes Did we resolve this?

**Comment by danielmewes** [comment]
@nighelles No, we still need to integrate the test into `configure`. Can you see if you can figure out how that works?

**Comment by nighelles** [comment]
This is in review #3574.

**Comment by nighelles** [comment]
This is in next.
