### ISSUE TITLE
r.uuid(somestring)

### ISSUE THREAD

**Issue by wmira** [rethinkdb/rethinkdb#5425]
Is it  guaranteed that passing an argument will generate the same value every time if we pass the same string?

**Comment by kwando** [comment]
I think so, otherwise I'm in trouble.

**Comment by thelinuxlich** [comment]
Yes it is

**Comment by VeXocide** [comment]
Indeed, it will generate the same UUID given the same input.

I'll close this issue since it's not a bug, but please feel free to ask more questions here.
