### ISSUE TITLE
Figure out `jobs` table behavior in presence of proxy nodes

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5428]
Proxies never show up in the jobs table, since they don't have a server name (or maybe for other reasons as well).

This is an issue for queries that are run through a proxy. Those will be invisible in the `jobs` table.
In clusters that use proxies, this will usually be pretty much all queries.

The second point in https://github.com/rethinkdb/rethinkdb/issues/3647 would fix this for the most part, but is non-trivial.

We should think about whether there's a reasonable and simple fix for this.

Pinging @VeXocide

**Comment by analytik** [comment]
Our use case: we want to log all queries for bug hunting and potential performance improvements or analytics, and since RethinkDB servers don't provide this, it would be extra swell to be able to connect to servers and get a changefeed of all running queries.

**Comment by analytik** [comment]
Actually, maybe scratch my post above. It seems that running `r.db('rethinkdb').table('jobs').changes()` *hugely* increases network traffic between nodes.

If I run it on our production setup of 3 nodes + 1 proxy, the network usage on the proxy goes up from 0.5~1.0MB/s to ~3.5MB/s (not Mbps), and the usage on server nodes goes from about 2MB/s combined, to about 3~3.5MB/s combined.

All of our app servers connect through the proxy, so they don't even show in the changefeed. Is this related at all to anything in your original post? Should I file a new ticket for this, or is it a known behavior?

**Comment by danielmewes** [comment]
For the web UI we use gzip compression to the browser, which might reduce the network traffic compared to the node.js client (or any other client).

Are there a lot of queries and/or large queries (e.g. many inserts)? That might drive up the network traffic for reading the `jobs` table considerably. Though you say that all of your app servers connect through proxies, so I'm not sure what's causing the network traffic. Are you still getting some results from the changefeed? Or is the `jobs` table essentially empty?

The original post was specifically about the issue that queries run through proxies do not show up in the table.

**Comment by analytik** [comment]
Well, that's exactly what's puzzling me. The `jobs` changefeed returns a few queries per second if I don't filter them out, but they're basically the admin UI fetching a list of servers/tables/status, things like that. None of our business logic is there, no inserts or anything that would take more than a few kilobytes of easily compressible text.

Our cluster has about 4~20k reads per second, and 10~600 writes per second, but 90% are inserts or updates which are about 1kB in size. So I think even if all the insert queries were secretly being transferred between nodes, it would be a few hundred kB/s for the whole cluster.

I've tried it again today just to be sure - we've scaled to 5 nodes and 2 proxies, I've ran just `r.db('rethinkdb').table('jobs').changes()` at first from a web UI, then after a minute I quickly changed it to `r.db('rethinkdb').table('jobs').filter(doc => doc('type').ne('backfill')).changes()` so it wouldn't kill my browser, as it seems there are some 300'000 second old backfill jobs still claiming to be running (even when all shards on all nodes are up to date).

[Here is the screenshot](https://www.dropbox.com/s/6euw9mdyzymmy4a/Screenshot%202016-06-21%2013.27.56.png?dl=0) from Prometheus monitoring - on one node, the traffic went up from 1.1MB/s to 3.5MB/s. There are also other things running on those nodes, but the spike always correlates with me running the changefeed on jobs.

We're running RethinkDB 2.3.4~0jessie on a Debian Jessie x64 docker container running on a CoreOS cluster.

It's important for us to be able, in the future, to have a permanently running changefeed on all jobs to monitor slow queries - or, to be able to enable such logging in RethinkDB servers themselves. Alternatively, we'd need to hack our way through python and node.js drivers to log every query after it's executed.

**Comment by danielmewes** [comment]
@analytik I opened a new issue for that in https://github.com/rethinkdb/rethinkdb/issues/5876 , because it's really unrelated to this issue.

**Comment by danielmewes** [comment]
This might be easier to fix than expected. Moving to 2.4-polish (together with https://github.com/rethinkdb/rethinkdb/issues/5489 ).

**Comment by danielmewes** [comment]
Testing a small fix that will make queries run through proxies appear with a server name of `proxy-<proxy UUID>`. It will hopefully go into RethinkDB 2.4.

**Comment by danielmewes** [comment]
This is implemented in branch daniel_5428 and in code review 3754.

**Comment by danielmewes** [comment]
Implementation merged into `next` via 55b8dd6 . Will ship with RethinkDB 2.4.0.
