### ISSUE TITLE
empty data buffer on JavaScript cursor when it is closed

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5432]
If you call `close` on a Python or Ruby `cursor` object, and then try to read from it again you will get an error. However, on JavaScript it will continue to give you data out of the buffer until it is empty (and then error). We should probably do what we do on the Python one, and empty out the buffer immediately.

Note, this is related to #5056.

**Comment by danielmewes** [comment]
I have an implementation of this in `daniel_5432`.

**Comment by danielmewes** [comment]
@nighelles You merged this with your `eachAsync` changes right?

**Comment by hueniverse** [comment]
This should have probably been documented as a breaking change. It is described as a cleanup fix but it actually adds a new error which existing v2.2.0 is probably not expecting.

**Comment by danielmewes** [comment]
It looks like the new version throws a `ReqlDriverError` with the message "Cursor is closed.", while the old version might have thrown a different error, but in general had undefined behavior (it would sometimes return more rows and never throw an error, sometimes return a few results and then throw an error, and sometimes throw an error immediately).

The new behavior for the first time defines what the behavior for reading from a cursor after closing it is, so I'm not sure if this qualifies as a breaking change.

In general we should get better at pointing out changed error messages in our release notes though. We are currently not mentioning such changes anywhere.

**Comment by hueniverse** [comment]
The exception was new in the way I was using it and it broke a bunch of tests. The release was already a breaking release so there was no issues there, just that this change was billed as a minor fix when it actually changed significant behavior. It was the right change to make.
