### ISSUE TITLE
tornado example gives `Error: Stream is closed` when connect to remote server.

### ISSUE THREAD

**Issue by lucidfrontier45** [rethinkdb/rethinkdb#5445]
Hi all.

I followed the tornado rethinkdb example described in https://rethinkdb.com/blog/async-drivers/ .
It works OK so far as connecting to local rethinkdb.

When I changed to connect to remote rethinkdb, the following error occurred.

```py
Traceback (most recent call last):
  File "/home/du/.virtualenvs/iot-test/lib/python3.5/site-packages/tornado/ioloop.py", line 600, in _run_callback
    ret = callback()
  File "/home/du/.virtualenvs/iot-test/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/du/.virtualenvs/iot-test/lib/python3.5/site-packages/tornado/ioloop.py", line 615, in <lambda>
    self.add_future(ret, lambda f: f.result())
  File "/home/du/.virtualenvs/iot-test/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/du/.virtualenvs/iot-test/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/du/PycharmProjects/iot-test/async_rethink.py", line 13, in print_changes
    conn = yield conn_future
  File "/home/du/.virtualenvs/iot-test/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/du/.virtualenvs/iot-test/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/du/.virtualenvs/iot-test/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/du/.virtualenvs/iot-test/lib/python3.5/site-packages/rethinkdb/tornado_net/net_tornado.py", line 240, in reconnect
    res = yield ConnectionBase.reconnect(self, noreply_wait, timeout)
  File "/home/du/.virtualenvs/iot-test/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/du/.virtualenvs/iot-test/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/du/.virtualenvs/iot-test/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/du/.virtualenvs/iot-test/lib/python3.5/site-packages/rethinkdb/tornado_net/net_tornado.py", line 116, in connect
    (self._parent.host, self._parent.port, str(err)))
rethinkdb.errors.ReqlDriverError: Could not connect to isc-dev:28015. Error: Stream is closed
```

Am I missing something? My whole code is as follows.

```python
from pprint import pprint

import rethinkdb as r
from tornado import ioloop, gen

r.set_loop_type("tornado")


@gen.coroutine
def print_changes(conn_future):
    conn = yield conn_future
    feed = yield r.table("data").changes().run(conn)
    while (yield feed.fetch_next()):
        change = yield feed.next()
        pprint(change)


connection = r.connect() # OK
# connection = r.connect(host="isc-dev") <- error
current = ioloop.IOLoop.current()
current.add_callback(print_changes, connection)
current.start()
```

Thank you.

**Comment by danielmewes** [comment]
Hi @lucidfrontier45 . That's weird. Can you connect successfully in synchronous mode?
E.g.
```py
import rethinkdb as r
connection = r.connect(host="isc-dev")
print r.expr("Hello world").run(connection)
```

**Comment by lucidfrontier45** [comment]
@danielmewes

yes, synchronous mode is no problem.

**Comment by lucidfrontier45** [comment]
Async Connection to a proxy mode server in localhost is also OK.

client -> local rethinkdb : OK
client -> remote rethinkdb : NG
client -> local rethinkdb proxy -> remote rethinkdb : OK

My environment is as follows

local PC : ubuntu 15.10
remote server: centos 7.2
rethinkdb: 2.2.4~0jessie via docker
python driver: 2.2.0.post4

Note that remote server is in the same LAN as the local PC.

**Comment by danielmewes** [comment]
Thanks for trying that.

@Tryneus do you have any ideas? Anything @lucidfrontier45 could try to help us debug this?

**Comment by lucidfrontier45** [comment]
I also tried node.js version. It works fine with remote server.
The problem looks only related to Python.

```js
"use strict";

class RethinkApp {
    constructor() {
        this.sockets = new Set()
    }

    static _query() {
        return r.table("iot2")
            .changes().map(r.row("new_val"))
    }

    run(conn) {
        RethinkApp._query().run(conn).then(cur => {
            cur.each((err, row) => console.log(row))
        })
    }
}

let r = require("rethinkdb");

let app = new RethinkApp();

r.connect("isc-dev").then(conn => {
    app.run(conn)
}).error(err => {
    throw err
});
```

**Comment by lucidfrontier45** [comment]
I found the cause.

My remote server's hostname is registered in `/etc/hosts` by IPv6 address.
If I try IPv4 address, the connection succeeds.
So the problem is that Python driver's async connection is **not** IPv6 capable.

Python's sync connection and JS driver are IPv6 capable.

**Comment by VeXocide** [comment]
I just had a quick peek at the related code and hopefully just spotted the problem, compare https://github.com/rethinkdb/rethinkdb/blob/next/drivers/python/rethinkdb/net.py#L277 and https://github.com/rethinkdb/rethinkdb/blob/next/drivers/python/rethinkdb/tornado_net/net_tornado.py#L87.

Note that in the synchronous driver we use `socket.create_connection(...)` whilst in the Tornado driver we use `socket.socket(socket.AF_INET, ...)` which obviously means we don't support IPv6 there.

We likely have the same problem in the asyncio and gevent drivers, see https://github.com/rethinkdb/rethinkdb/blob/next/drivers/python/rethinkdb/asyncio_net/net_asyncio.py#L135 and https://github.com/rethinkdb/rethinkdb/blob/next/drivers/python/rethinkdb/gevent_net/net_gevent.py#L65 respectively.

@Tryneus -- the fix should be straightforward, could you please have a look since you have the setup required to test this?

**Comment by Tryneus** [comment]
Fix is up in review 3500.  This addresses `gevent`, `asyncio`, `tornado`, and to some degree `twisted`.

**Comment by Tryneus** [comment]
The fix has been approved and merged to `next` in commit 47a4815, and cherry-picked into `v2.2.x` in commit 1496801.

Thanks, @lucidfrontier45 for reporting this, and everyone for helping debug it.

**Comment by danielmewes** [comment]
I'll prepare a new Python driver release. Should be out by Monday.

**Comment by lucidfrontier45** [comment]
cool. thank you all.

**Comment by danielmewes** [comment]
The new driver is now available through Pypi. The new driver version is rethinkdb-2.2.0.post5
