### ISSUE TITLE
Java enum classes are not converted into strings

### ISSUE THREAD

**Issue by azabujuban** [rethinkdb/rethinkdb#5446]
I have a POJO with an enum field inside and that field is set to `null` by `toReqlAst`.

Looking in the driver code at  `Util#toReqlAst` there are checks for some types (`Map`, `Number`, `String`) and if the field is not of any of these types `toMap` is performed. But it doesn’t work for enum classes.

I’m thinking of adding a check for enum classes and if a field is an enum class call it’s `name()` method.

**Comment by azabujuban** [comment]
I have made the changes in #5447

**Comment by mcjp78** [comment]
If rethink db is still alive then bump!

**Comment by srh** [comment]
Anybody know if this is still a potential feature?  I chased a bunch of pull requests to a dead end, and don't know if anything made it in that adds this feature.

**Comment by adriantodt** [comment]
This issue can be safely closed, as lot of stuff was overwritten by Jackson serialization taking place.
