### ISSUE TITLE
Java disconnection leaks awaiting query requestors

### ISSUE THREAD

**Issue by pires** [rethinkdb/rethinkdb#5448]
As per @bchavez comments on #5439:

>@pires, there's a subtle bug in the code when processing exceptions this way.
>
>https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L139
>
>After the pump is finished processing a response cleanly, suppose the connection drops outside of the try{}catch{} statement. The pump isn't around to catch it. !isOpen is false. The while(true) loop breaks in Line 145. .close is never called. Hence, leaving all awaiting queries hanging.

**Comment by sceutre** [comment]
Imo, you should release a beta-6 driver for this bugfix.  Or at least remove beta-5.

**Comment by danielmewes** [comment]
Thanks for the reminder @sceutre .
We'll likely release a new version end of next week, since @deontologician is currently out of office.

Are you actually running into this @sceutre ?
I believe that this can only happen if the server unexpectedly drops a connection, or if there's an issue with the network connection. Am I wrong?

**Comment by sceutre** [comment]
Yes we were seeing it on our servers, it was leaking connections until the cluster ran out of open file descriptors and became unresponsive.  We never applied you change so I don't know exactly if it is the same issue, but downgrading to beta-4 fixes it for us.

Our use case for connections is to wrap them in a connection pool so we can distribute load to all servers in the cluster and handle node outages.  When the pool evicts a connection we shut it down with connection.close() and it's our guess this was never actually closing the connection.

**Comment by danielmewes** [comment]
@sceutre 
> When the pool evicts a connection we shut it down with connection.close() and it's our guess this was never actually closing the connection.

That actually sounds like it might be a different issue. I think when using `close()` to close the connection, it should have closed the socket even before this patch.

I can't find anything obviously wrong with the `close()` implementation.

@sceutre Would you be able to share your connection pool code and maybe the relevant parts of your application with us (my email address is daniel@rethinkdb.com )? I'd like to see if we can reproduce this locally, which would make investigating the issue much easier.
We can sign an NDA if necessary.

**Comment by sceutre** [comment]
Sure, I'll look into it.

**Comment by danielmewes** [comment]
@sceutre We have shipped a new version (2.2-beta-6) of the Java driver that has the fix @pires talked about. As mentioned before, I'm not sure if this is the same thing that you're experiencing. You might want to try it out though.

**Comment by sceutre** [comment]
I can confirm that 2.3 does not show the behaviour we were seeing.

**Comment by sceutre** [comment]
Fwiw, to completely close the door on this, we found last week that 2.3 was indeed exhibiting the issue, but the issue was our fault all along.  It turns out we were leaking  a connection (creating, using, not closing, and losing the reference) at a rate of one a minute.

**Comment by pires** [comment]
Thank you for letting us know @sceutre.
