### ISSUE TITLE
JavaScript `eachAsync` does not return a rejection for wrong number of arguments

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5454]
The following code does not work as expected at the moment:
```
try {
    r.db('foo').table('bar').run()
    .then(function(cur) { return cur.eachAsync(); })
    .catch(function(err) { console.log('I should get here'); });
} catch(err) {
    console.log('Rather I get here');
}
```
This should go to the promise `.catch` block. But because the code in [`util.coffee`](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/javascript/util.coffee#L19-L26) that does these checks is not aware of promises it throws an error rather than returning `Promise.reject(new err.ReqlDriverCompileError('blah'))`

**Comment by marshall007** [comment]
@larkost as it is, your example is basically equivalent to:

```js
Promise.resolve()
.then(function() {
  throw new err.ReqlDriverCompileError("...")
})
.catch(function(err) { console.log('I should get here'); });
```

Since you're in a `.then()` callback when the exception is thrown, I would expect this to already work as you've described it should. Are you certain it's not?

**Comment by deontologician** [comment]
From what I gathered from @coffeemug, "syntax" errors like this are intended to be actual exceptions instead of promise rejections. `.catch` should get both though, so I'm not exactly sure why it's not going to the handler.

**Comment by danielmewes** [comment]
Can `.catch` actually catch exceptions? That would surprise me. Isn't it just a function call on the promise?
If `eachAsync` indeed throws an exception directly, I would expect the behavior that @larkost describes, i.e. ending up in the "actual" `catch` with `console.log('Rather I get here');`

**Comment by deontologician** [comment]
According to the docs, it's supposed to catch exceptions thrown inside a `then` block coming before it:
http://bluebirdjs.com/docs/api/catch.html

It can catch them because the `.eachAsync()` call is wrapped in a closure, but it wouldn't be able to catch problems with arguments to `.table()` etc, since those aren't part of the promise chain.

**Comment by larkost** [comment]
I think I see the problem: we are not inside a `.then()` block when we error. I simplified slightly on the `mocha` code we have for testing. The `r.db('foo').table('bar').run()` part is inside a `beforeEach` block, and the cursor gets put into a variable. Then we start our chain on that, so essentially we are doing:

```
r.db('foo').table('bar').run()
then(function(cur) {
    try {
        cur.then(function(cur) { return cur.eachAsync(); })
        .catch(function(err) { console.log('I should get here'); });
    } catch(err) {
        console.log('Rather I get here');
    }
})
```
I suspect that larger setups are going to wind up using frameworks that may well expose us that way as well.

**Comment by larkost** [comment]
This is as solved as it is going to be at this point in the work for #5518.
