### ISSUE TITLE
JAVA: Queries work when debugging, but NOT while running

### ISSUE THREAD

**Issue by vinaysshenoy** [rethinkdb/rethinkdb#5457]
I'm using [Spark Java](http://sparkjava.com/) to build my web app. There's a very weird problem I'm facing when trying to query my data.

My database is running locally(Mac OS X). I'm using rethinkdb version `2.2.5` and JAVA driver version `2.2-beta-5`.

I have a table called **categories** and I'm making the call to fetch the categories as follows - 
```java
        RethinkDB r = RethinkDB.r;
        final Cursor categoriesCursor = r.table("categories").run(conn);
        final List<Category> categoryList = new ArrayList<>(categoriesCursor.bufferedSize());
        while (categoriesCursor.hasNext()) {
            categoryList.add(fromMap((Map<String, Object>) categoriesCursor.next()));
        }
        return categoryList;
```

When I **DEBUG** the app, it works fine and I get the list of documents. It works even if I don't have any breakpoints enabled. However, if I run it normally without debugging, the query fails with the following exception - 
```java
    com.rethinkdb.gen.exc.ReqlDriverError: Can't write query because response pump is not running.
	at com.rethinkdb.net.Connection.sendQuery(Connection.java:243)
	at com.rethinkdb.net.Connection.runQuery(Connection.java:275)
	at com.rethinkdb.net.Connection.run(Connection.java:338)
	at com.rethinkdb.net.Connection.run(Connection.java:327)
	at com.rethinkdb.ast.ReqlAst.run(ReqlAst.java:65)
	at in.momowala.backend.db.models.Category.fetchAll(Category.java:31)
	at in.momowala.backend.api.v1.ApiBinderV1.lambda$bind$0(ApiBinderV1.java:27)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
	at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
```

Any idea what the problem is and how I can fix it?

**Comment by bchavez** [comment]
Out of curiosity, are you using dependency injection on `conn`? What is `conn`'s lifetime / scope on every HTTP request? `Singleton`, `Per request`, or `Transient`? In other words is a new `conn` being created on every HTTP request?

Lastly, what happens if you `Thread.sleep()` for `1 second` just after calling `.connect()` and just before running the query `run` method? Any difference? IE:

```
Connection conn = r.connection().hostname("foo").port(1234);
Thread.sleep(1000);
r.table("foo")...query...run(conn);
```

**Comment by vinaysshenoy** [comment]
The problem is fixed now.

I had written a very barebones connection pool using a `Semaphore`. The connection `acquire` and `release` methods were unsynchronised. After I synchronised them, the connections seem to work properly.

```java
public class ConnectionPool {

    private static final Logger LOGGER = LoggerFactory.getLogger(ConnectionPool.class);

    private Semaphore semaphore;

    private List<Connection> availableConnections;

    private final int maxConnections;

    private final Configuration.DbConnectionConfig config;

    /**
     * Initialize a Connection Pool, with the number of connections and the configuration for those connections
     *
     * @param maxConnections The number of database connections to be held in the pool. A good number to set this to would be the
     *                       number of server threads
     * @param config         The Connection config
     */
    public ConnectionPool(int maxConnections, Configuration.DbConnectionConfig config) {
        this.maxConnections = maxConnections;
        this.config = config;
        initConnections();
        semaphore = new Semaphore(maxConnections, true);
    }

    private void initConnections() {

        availableConnections = new ArrayList<>(maxConnections);

        for (int i = 0; i < maxConnections; i++) {

            availableConnections.add(RethinkDB.r.connection()
                    .hostname(config.hostname)
                    .port(config.port)
                    .db(config.dbname)
                    .authKey(config.authKey)
                    .timeout(config.timeout)
                    .connect());
        }
    }

    public Connection acquireConnection() {

        synchronized (this) {
            try {
                semaphore.acquire();
                return availableConnections.remove(0);
            } catch (InterruptedException e) {
                LOGGER.error("Could not acquire connection", e);
                return null;
            }
        }
    }

    public void releaseConnection(Connection connection) {

        synchronized (this) {
            availableConnections.add(connection);
            semaphore.release();
        }
    }

}
```

**Comment by danielmewes** [comment]
Ah, thanks for the update @vinaysshenoy

**Comment by bchavez** [comment]
Hm. Interesting. A bit of mystery :8ball: to me how synchronizing `acquire` and `release` would resolve your original stack-trace that topped out at `sendQuery`. I had some suspicion after reviewing some connection pump logic but without further validation, `this.Yield("if it ain't broke, don't fix it")`. :smiley_cat:

**Comment by vinaysshenoy** [comment]
@bchavez Yup. One last question, off the top of your head, would you see any problem with the connection pool I've written. I don't close any connections once I'm done using them, just return them to the pool. Basically,
```java
Connection conn = pool.acquireConnection();
//Do task with conn
pool.releaseConnection(conn);
```

**Comment by bchavez** [comment]
@vinaysshenoy , per your request, here are some of my thoughts:

* The connection pool seems to be creating multiple connections to the same server. I'm not sure how useful this is. Connections themselves *should* be thread-safe. So, landing multiple queries on a single connection, in any order, from different threads should work just fine. The driver has internal locking to multiplex/serialize requests and demultiplex/deserialize responses over a single connection without disrupting other requests.

* Adding and removing connections from `List<Connection>` seems like a lot of work to me with unnecessary locking. From my experience, locking is slow and should be avoided if possible. Also, from a design and architecture standpoint, exposing methods like  `var conn = pool.acquire()` and `pool.release(conn)` delegates additional responsibility to the caller. The caller needs to always "remember" to put the connection "back into the pool" after using it. In a project with a very large code base, the pool could be drained if someone forgot a single line. :beetle: :warning: A `.next()` method and an underlying simple array with an atomically increasing integer `mod` array length would do just as good?

YMMV tho... I'm not an engineer at RethinkDB. @danielmewes or deontologician are the real deal w.r.t your Java issue.

**Comment by vinaysshenoy** [comment]
@bchavez Thanks for the input.

Actually, the RethinkDb driver [documentation](https://www.rethinkdb.com/docs/install-drivers/java/) (At the very end of the page) states that the connections are not thread-safe and recommends users to open a connection per thread or use a connection pool, so I wrote a pool like so.

Point 2 makes a lot of sense. As of now, I'm the only person working on the project and it's a small app so it works for now. I'll revisit the connection pool architecture in the future when the need arises.

Thanks for the advice.

**Comment by bchavez** [comment]
@vinaysshenoy , https://github.com/rethinkdb/rethinkdb/pull/5292

**Comment by vinaysshenoy** [comment]
This changes everything! Thanks!

**Comment by danielmewes** [comment]
Just a small addition: Opening multiple connections to the same server can still sometimes give slightly better performance, as the server can better utilize multiple cores for parsing requests from the different connections.

**Comment by vinaysshenoy** [comment]
@danielmewes Understood. Thanks for the info.
