### ISSUE TITLE
New handshake: JavaScript implementation

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5459]
Once we have the reference implementation in Python and the server code, we need to implement https://github.com/rethinkdb/rethinkdb/issues/5406 for the JS driver.

**Comment by danielmewes** [comment]
@nighelles can you work on this please?

(the following is virtually identical to what I wrote in https://github.com/rethinkdb/rethinkdb/issues/5461#issuecomment-202669667 )

The server-side implementation is currently available in branch vexocide/5406.

There is a reference implementation for the Python driver in this file: https://github.com/rethinkdb/rethinkdb/blob/vexocide/5406/drivers/python/rethinkdb/handshake.py

The handshake protocol is formally described here https://github.com/rethinkdb/rethinkdb/issues/5406#issuecomment-185980303 , with the authentication mechanism being described here http://tools.ietf.org/html/rfc5802 . It's probably going to be easiest to just follow the Python implementation.

For testing, you'll need to create a user account. This can be done by inserting into the `r.db('rethinkdb').table('users')` table. The document should look like this:
```js
{
  id: "username",
  password: "secret"
}
```

The `connect` method will need to accept two new options "user" and "password", which need to be provided together. If these options are not specified, the driver should try to connect with the username "admin" and an empty password. If the authentication fails, a `ReqlAuthError` should be thrown.
I think we should still support the `authKey` option for backwards compatibility with existing application code. If an `authKey` is specified, we assume a username of "admin" and use the `authKey` as the password for the "admin" user.

**Comment by nighelles** [comment]
This is in review 3561, implemented in nighelles/5459.

**Comment by nighelles** [comment]
This is in next.
