### ISSUE TITLE
Implement permissions on system tables

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5463]
Discussed this with @VeXocide and this is what we came up with:

* Read permissions on system tables will be assigned through the usual mechanism (i.e. the "rethinkdb" database is treated like any other database)
* Nobody can write to a system table, except for the `admin` user who can write to all system tables
* One exception from the rule: Users can update their own document in the `users` table, as long as they have read and write permissions on the `users` table as granted through the usual mechanism.

Note that operations such as `r.table(...).config().update(...)` or `r.table(...).reconfigure(...)` can still be performed by non-admin users, if the user has `config` permissions on the affected table.

**Comment by danielmewes** [comment]
I'd like to propose one exception from the rules above:
The `jobs` table should only be readable by the admin user for now.

The reason is that `jobs` exposes all sorts of queries that contain secret data (e.g. password of other users if they're currently changing theirs).
A common scenario is setting up a "read only" user with global read permissions. Such a user could escalate its privileges by reading passwords of other users from the `jobs` table.

If it's easy to do, we can think about filtering `jobs` output so users only see their own queries unless they are `admin`.
I think it would be ok to leave that refinement for later though.

**Comment by danielmewes** [comment]
Because we're a bit tight on time, let's do the simple thing for `jobs` for now and disallow reading from it alltogether for non-admin users. (@vexocide)

**Comment by VeXocide** [comment]
This is next.

**Comment by danielmewes** [comment]
@VeXocide merged this with https://github.com/rethinkdb/rethinkdb/commit/634a193f4c505a538ecae6d88ae6d4499eb7f646
