### ISSUE TITLE
Update import, export, restore, dump, index-rebuild scripts to work with user accounts

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5464]
While it can be useful to e.g. import data as a normal user (or export data with a read-only user), I suggest that we only allow logging in as the `admin` user at first to keep things as simple as possible.

That would mean that these scripts will need to accept a `password` argument of some sort, or ask for it interactively (probably both should be possible).
Passing in passwords as command line arguments is problematic on Linux because the password is going to be readable by all connected users (e.g. it will show up in `ps ax`). I've seen some tools who accept a file path instead that they read the password from.

I propose:
* If none of the below options is given, the scripts try to connect as the `admin` user without a password. If this fails, the script fails (i.e. we don't automatically fall back to `--password`).
* `--password | -p` Makes the script ask for the admin password interactively.
* `--password-file <file path>` Loads the admin password from the specified file.

**Comment by danielmewes** [comment]
We could add a `--user <user name>`  option to allow logging in as another user, but it opens up a bunch of questions about what to do if the user doesn't have permissions for some tables etc. So I think it's easier to stick with `admin` at first.

**Comment by danielmewes** [comment]
We can also remove the `--auth` option then.

**Comment by nighelles** [comment]
This is in review 3560, implemented in nighelles/5464

**Comment by nighelles** [comment]
This is in next.
