### ISSUE TITLE
Check how open changefeeds react to permission changes

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5465]
I imagine that they currently recheck the permissions whenever a new batch is requested. So if you open a changefeed on let's say table `t`, then someone removes your read permissions on `t`, you'll still get the next batch of changes from the changefeed, but it will be closed afterwards. I haven't tried this and could be wrong about this.

In any case we need to test this.

**Comment by danielmewes** [comment]
Turns out right now changefeeds remain open and usable indefinitely if the permissions are changed in the middle.

**Comment by danielmewes** [comment]
If it's easy to do, we should add some code that rechecks the permissions for example at the beginning of every batch.

**Comment by VeXocide** [comment]
43440cbc37a50f01ec54ce5a1d0f6c871d7ac718 on `vexocide/5406` implements this real tables, we'll implement it on artificial tables as part of #5463.

**Comment by danielmewes** [comment]
Since we won't allow non-admin access to artificial tables in 2.3, this is fixed.
