### ISSUE TITLE
Some removed top level terms still occur in Python driver code

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5466]
https://github.com/rethinkdb/rethinkdb/issues/4382 removed `r.wait`, `r.rebalance` and `r.reconfigure`.

The Python driver still defines `WaitTL`, `ReconfigureTL` and `RebalanceTL` types though (they are no longer used however).

E.g. https://github.com/rethinkdb/rethinkdb/blob/next/drivers/python/rethinkdb/ast.py#L1486

**Comment by nighelles** [comment]
In next, OTS by @danielmewes
