### ISSUE TITLE
Java Cursor as `Closeable`

### ISSUE THREAD

**Issue by n3integration** [rethinkdb/rethinkdb#5468]
Thank you for the recently released Java driver! A feature that may make a nice addition to the driver would be if the `com.rethinkdb.net.Cursor` instance could implement the `Closeable` interface. This would make it easier to use through Java's [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) idiom.

**Comment by deontologician** [comment]
Should simply involve adding the interface to the class since we already have a `void close()` method (I'm pretty sure).

**Comment by danielmewes** [comment]
:+1:

**Comment by deontologician** [comment]
PR up for this in #5471

**Comment by rocketraman** [comment]
I don't understand why #5471 fixes this. This issue is to mark the `Cursor` as `Closeable` whereas #5471 marks the `Connection` as `Closeable` (which is also good, but different). Is it because if the Connection is closed it is unnecessary to close cursors?

**Comment by danielmewes** [comment]
@rocketraman You're right. I think we mixed this up. Re-opening.

**Comment by deontologician** [comment]
whoops, yeah I'll fix this, thanks for catching it

**Comment by rocketraman** [comment]
This seems like something pretty simple to fix -- do you think it could get into the next point release?

**Comment by danielmewes** [comment]
@rocketraman Interested in opening a pull request? :-)
(we can obviously also fix this otherwise)

**Comment by rocketraman** [comment]
> @rocketraman Interested in opening a pull request? :-)

Yup, I can do that.

**Comment by danielmewes** [comment]
We just released a new Java driver version 2.3.3 with this fix.
