### ISSUE TITLE
support eachAsync for `r.expr([1,2,3])` in JavaScript

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5469]
`eachAsync` is not currently supported for the return of  `r.expr([1,2,3]).run(conn)`. This should probably be done in order to make all of our forms similar.

**Comment by danielmewes** [comment]
I just had a look at the code and `ArrayResult` inherits from `IterableResult` which is what `eachAsync` is defined on.
I wonder why it's not working.

**Comment by larkost** [comment]
Assigning to @nighelles, since he is working on merging @marshall007's pull request with this.

**Comment by nighelles** [comment]
This, along with the pull request from @marshall007, is in review 3545.

**Comment by nighelles** [comment]
This is in next.
