### ISSUE TITLE
[Rethindb]a rethinkdb server in a cluster has been dead suddenly, but i dont know why

### ISSUE THREAD

**Issue by xycjimmy** [rethinkdb/rethinkdb#5479]
This is the error information from the rethinkdb server:
Wed Mar 2 08:17:24 2016\n\n1 [0xa6ce20]: backtrace_t::backtrace_t() at 0xa6ce20 (rethinkdb)\n2 [0xa6d180]: format_backtrace(bool) at 0xa6d180 (rethinkdb)\n3 [0xaddba0]: report_fatal_error(char const*, int, char const*, ...) at 0xaddba0 (rethinkdb)\n4 [0xc007fe]: ql::changefeed::range_sub_t::apply_ops(ql::datum_t) at 0xc007fe (rethinkdb)\n5 [0xc0408c]: ql::changefeed::msg_visitor_t::operator()(ql::changefeed::msg_t::change_t const&) const::{lambda(ql::changefeed::range_sub_t*)#1}::operator()(ql::changefeed::range_sub_t*) const at 0xc0408c (rethinkdb)\n6 [0xbf4721]: void ql::changefeed::feed_t::each_sub_in_vec_cb<ql::changefeed::range_sub_t>(std::function<void (ql::changefeed::range_sub_t*)> const&, std::vector<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> >, std::allocator<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> > > > const&, std::vector<int, std::allocator<int> > const&, int) at 0xbf4721 (rethinkdb)\n7 [0xbf5dd6]: callable_action_instance_t<pmap_runner_one_arg_t<std::_Bind<std::_Mem_fn<void (ql::changefeed::feed_t::*)(std::function<void (ql::changefeed::range_sub_t*)> const&, std::vector<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> >, std::allocator<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> > > > const&, std::vector<int, std::allocator<int> > const&, int)> (ql::changefeed::feed_t*, std::reference_wrapper<std::function<void (ql::changefeed::range_sub_t*)> const>, std::reference_wrapper<std::vector<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> >, std::allocator<std::set<ql::changefeed::range_sub_t*, std::less<ql::changefeed::range_sub_t*>, std::allocator<ql::changefeed::range_sub_t*> > > > const>, std::reference_wrapper<std::vector<int, std::allocator<int> > const>, std::_Placeholder<1>)>, long> >::run_action() at 0xbf5dd6 (rethinkdb)\n8 [0xa40f18]: coro_t::run() at 0xa40f18 (rethinkdb)

Backtrace:

Guarantee failed: [env.has()]

the server has been running on the server for two days, but suddenly the first server has been dead, i cant get the process information of the first server, it is so weird, please tell me the reason if you know,or you can know how to avoid the error

**Comment by danielmewes** [comment]
Hi @xycjimmy, you're probably running into issue https://github.com/rethinkdb/rethinkdb/issues/5238 .
This issue was fixed in RethinkDB 2.2.3 and higher. I recommend upgrading to RethinkDB 2.2.4, which should resolve the problem.

Please let me know if you see the issue again after upgrading.
