### ISSUE TITLE
Pretty printer (for rethinkdb.jobs) inverts `map` arguments

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5480]
The pretty printer seems to not handle multi-stream `map` correctly.

If I run a query like this:

``` js
r.range(10).map(r.range(11), function(x, y) { r.js("while(true) {}") })
```

It shows up in `r.db('rethinkdb').table('jobs')` as follows:

``` js
r.range(10).map(function (var141, var142) {
                    return r.js("while(true) {}");
                },
                r.range(11))
```

Note that the function and the second stream arguments are swapped.

**Comment by AtnNn** [comment]
Should be fixed in #6245
