### ISSUE TITLE
[Q] Tables vs nested data

### ISSUE THREAD

**Issue by gngeorgiev** [rethinkdb/rethinkdb#5486]
I have a question, I am planning on using rethinkdb in large scale. Currently in mongo I have a lot of collections. E.g. think of it as ~5 collections per user. In rethinkdb should I go for tables or nest the data inside one collection as this is also possible. 

Think of it as if it is large scale, think about the read/write performance and also the realtime changes.

Thanks in advance

**Comment by thelinuxlich** [comment]
If the nested data could be thousands of items(or hundreds with fat objects), you should turn to extra tables until RethinkDB implements something like partial reads/writes

**Comment by danielmewes** [comment]
Closing this since there has been another answer in https://groups.google.com/forum/#!topic/rethinkdb/oMx3ZeA6MO8 .

The issue with a large number of tables is that they incur some memory overhead (about 8 MB RAM per table).
