### ISSUE TITLE
[Question of Java Client]: Should LocalDateTime be saved with time zone information?

### ISSUE THREAD

**Issue by QianJin2013** [rethinkdb/rethinkdb#5487]
I have a trivial question about Java Client Driver of RethinkDB.
I am working on [Support almost ALL types in/out. (e.x. Enum, OffsetDateTime, BigDecimal, double, Float... ) by QianJin2013 · Pull Request #5484 · rethinkdb/rethinkdb](https://github.com/rethinkdb/rethinkdb/pull/5484), it's too long, so i ask it here separately.

First, let me give some summary about Java's new Date Time type design:
--------Type-------------------------   ----have time zone----   ----RethinkDB save time zone----                       
`java.time.OffsetDateTime`:             YES                                 YES
`java.time.TimeZonedDateTime`:     YES                                 YES
`java.time.LocalDateTime`:               NO                                 YES           !!Not consistent
`java.time.LocalDate`:                       NO                                 NO
`java.time.LocalTime`:                      NO                                 NO

Then, i'd thought when rethink db's java client store above types to db, it follow above policy. But in fact NO.

When i store `OffsetDateTime` to db, it save data as following format:
```
    "offsetDateTimeProperty": {
        "$reql_type$": "TIME",
        "epoch_time": 1457175284.443,
        "timezone": "+09:00"
    },
```
This is perfect.

But when i store `LocalDateTime` to db, it will try to output time zone information:
The <a href="https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/ast/Util.java#L87">ast.Util.java:: toReqlAst  convert  `LocalDateTime` or `LocalTime` to OffsetDateTime.</a>
```
            ZoneId zid = ZoneId.systemDefault();
            DateTimeFormatter fmt2 = fmt.withZone(zid);
            return Iso8601.fromString(((LocalDateTime) val).format(fmt2));
```
This also sounds reasonable. So, having fixed the bug of .format() error with 
```
            ZonedDateTime zdt = ((LocalDateTime)val).atZone(ZoneId.systemDefault());
            return Iso8601.fromString(zdt.format(fmt));
```

The LocalDateTime will be output as following format (same as OffsetDateTime):
```
    "localDateTimeProperty": {
        "$reql_type$": "TIME",
        "epoch_time": 1457175284.444,
        "timezone": "+09:00"
    },
```

And for `LocalDate`, it stores as different format, without time zone information. (I do not know where did the conversion yet).
```
    "localDateProperty": {
        "chronology": {
            "calendarType": "iso8601",
            "id": "ISO"
        },
        "dayOfMonth": 5,
        "dayOfWeek": "SATURDAY",
        "dayOfYear": 65,
        "era": "CE",
        "leapYear": true,
        "month": "MARCH",
        "monthValue": 3,
        "year": 2016
    },
```

for `LocalTime`, it does no output time zone information.
```
    "localTimeProperty": {
        "hour": 19,
        "minute": 54,
        "nano": 444000000,
        "second": 44
    },
```

My questions are:
Is the policy of output time zone information consistent? seems confused, especially for LocalDateTime.
Actually, i do not even know why javaers save LocalDate/LocalDateTime/LocalTime in db.
(well, LocalTime seems be pure time, reasonable)

**Comment by danielmewes** [comment]
I hope I understand this correctly.

I think storing the timezone offset with `LocalDateTime` is the right thing to do. The data stored in the database has to represent the same time no matter what the locale of the Java client is. That is the current offset of the current locale should be encoded explicitly in the ReQL DataTime in terms of a timezone.

Also pinging @deontologician .

**Comment by danielmewes** [comment]
Imagine you have two clients A and B and both have different locales (e.g. they are running in different countries). If client A inserts a `LocalDateTime` object into RethinkDB, and client B then retrieves it from the database, the time should be adapted to describe the same actual time in the local time zone.

The alternative I guess would be to convert `LocalDateTime` objects to UTC and to always store them at `timezone: "+00:00"` in RethinkDB. Then they would need to be converted back to the local timezone when being read back (which we need to do in either case).

**Comment by QianJin2013** [comment]
I'd thought same, but you can see LocalDate is not saving with timestam, LocalTime either.

**Comment by QianJin2013** [comment]
Sorry for type miss, on the contrary, LocalDate, LocalTime is not being saved with time zone, why?

**Comment by deontologician** [comment]
I think this was just an oversight. I agree that if the Date object contains timezone offset data we should use it. Also, the java driver focused mainly on the Time api from Java 8, I don't know if any of these types are from older date apis in Java

**Comment by QianJin2013** [comment]
@danielmewes thans for your explain.
@deontologician These types are all Java 8 new types.

LocaDate is saved without timezone, but LocalDateTime saved WITH timezone. So one of them is wrong?

Currently it seems nobody use LocaDate yet, javaers use LocalDateTime in most case, so this is not a big problem.

If no one is interested on this trivial problem, i will close this issue.

**Comment by danielmewes** [comment]
Hmm `LocalDate` is a tricky edge case I think. The timezone doesn't have a lot of meaning if you only have a date without a time.

**Comment by QianJin2013** [comment]
lol, no wonder they are treated differently. I think you are right, `LocalDate` can be converted to absolute time without time.
OK, i am convinced. Thank you all.
