### ISSUE TITLE
RFE: Higher level date difference ReQL function

### ISSUE THREAD

**Issue by gitblit** [rethinkdb/rethinkdb#5488]
> r.time(2016, 1, 1, 'Z').sub(r.time(2015, 1, 1, 'Z'))

I'm really happy to have the date subtraction capability - because I need it.  :)  But it would be great if I could specify something like:

    r.diff(r.time(2016, 1, 1, 'Z'), r.time(2015, 1, 1, 'Z'), 'd')

to get the difference in days.  Right now I have to write this:

    r.floor(r.time(2016, 1, 1, 'Z').sub(r.time(2015, 1, 1, 'Z'))).div(86400))

Arguably, that is not horrible, but having a smart & flexible date difference function would be quite handy and easier to digest than specifying time constants in the query.

Our friends at ArangoDB offer a nice DATE_DIFF function.

> DATE_DIFF(date1, date2, unit, asFloat): Calculate the difference between two dates in given time  unit, optionally with decimal places. Returns a negative value if date1 is greater than / after date2.
>
> unit can be either of the following to specify the time unit to return the difference in (case- insensitive):
>
> y, year, years
> m, month, months
> w, week, weeks
> d, day, days
> h, hour, hours
> i, minute, minutes
> s, second, seconds
> f, millisecond, milliseconds

**Comment by ha1331** [comment]
thumbs up for everything related to easier and more convenient date/time functions. Past few months I've written 30+ queries that do some variation of r.now() to epochTime, do some math on that and use what comes to create a proper date time for the actual query. ReQL being so nice, it's not THAT bad of a task, but feel's like there might a proper opportunity for improvements.

**Comment by danielmewes** [comment]
Thanks for the proposal @gitblit . We've had some related discussions, but I think we haven't had anything quite like this proposal.

We'll discuss it for one of the upcoming releases.

**Comment by marshall007** [comment]
This is almost identical to my proposal in #4187.

**Comment by danielmewes** [comment]
@marshall007 Thanks for pointing to it. I missed that...

I'm going to close this as a duplicate then.

**Comment by gitblit** [comment]
Doh! I searched before reporting but evidently I failed. Looking forward to an implementation for #4187. :+1:
