### ISSUE TITLE
TimerTest.TestApproximateWaitTimes occasionally fails

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#549]
It failed 3 out of 10000 times:

```
src/unittest/timer_test.cc:21: Failure
Expected: (abs(diff - wait_array[i][j] * (1000LL * 1000LL))) < (2 * (1000LL * 1000LL)), actual: 2554311 vs 2000000
```

```
src/unittest/timer_test.cc:21: Failure
Expected: (abs(diff - wait_array[i][j] * (1000LL * 1000LL))) < (2 * (1000LL * 1000LL)), actual: 2109949 vs 2000000
```

```
src/unittest/timer_test.cc:21: Failure
Expected: (abs(diff - wait_array[i][j] * (1000LL * 1000LL))) < (2 * (1000LL * 1000LL)), actual: 5450565 vs 2000000
```

**Comment by larkost** [comment]
@gchpaco seems to have fixed this with #3610

**Comment by anatol** [comment]
I see the same error with 1.16.0 release

```
[----------] 1 test from TimerTest
[ RUN      ] TimerTest.TestApproximateWaitTimes
src/unittest/timer_test.cc:26: Failure
Expected: (llabs(diff - wait_array[i][j] * (1000LL * 1000LL))) < (std::max(diff / 4, static_cast<int64_t>(2 * (1000LL * 1000LL)))), actual: 2062616 vs 2000000
```

**Comment by danielmewes** [comment]
Thanks for reporting @anatol .
It seems like the test is still too strict. Re-opening

**Comment by AtnNn** [comment]
The test isn't too strict, it's broken: it compares relative time and absolute time.

**Comment by AtnNn** [comment]
It's not broken the way I thought, I'm just reading it wrong.

However, it has the weird behaviour of testing that `nap(1)` sleeps for 1±2ms but for `nap(40)` it expects approximately 40±10ms.

In @anatol's failure, `nap(1)` sleeps for 2.06ms and in https://github.com/rethinkdb/rethinkdb/issues/3610#issuecomment-70606716, there seems to always be a difference of less than 4ms.

**Comment by AtnNn** [comment]
I've removed the relative error tolerance of 25%, increased the absolute error tolerance from 2ms to 5ms and added a maximum of 2ms for the average error. In branch `atnnn/timertest`.

**Comment by anatol** [comment]
I am using a VM to create Arch packages and run its tests. This might explain why CPU scheduler jitter is so big.

**Comment by srh** [comment]
This fails on my rMBP reliably.  A whole bunch of 20ms, 30ms, 40ms waits miss their deadline by *just* over 5 ms.  (By between 5.0 and 5.2 ms.)  A much smaller number miss the deadline if I've got `perl -e 'for (1..1e15) { }` running in another terminal.  I even got the test to pass once!  So this is related to macOS power-savings behavior.

**Comment by srh** [comment]
We could delete the test.  But I'm going to close this issue because nobody wanted to do that, I recently found it useful, and there's no way to fix this problem -- it's the operating system's behavior.
