### ISSUE TITLE
Connecting a proxy raises a "The following servers are not fully connected" issue

### ISSUE THREAD

**Issue by encryptio** [rethinkdb/rethinkdb#5493]
Starting with no data, running these two concurrently:

```
rethinkdb -o 7
rethinkdb proxy -o 8 --join localhost:29022
```

Raises an issue on the web UI:

```
The following servers are not fully connected:

<storage node name>

Partial connectivity can cause tables to remain unavailable and queries to fail. Please check your network configuration if this issue persists for more than a few seconds.
```

The issue occurs on `next` as of at least d587a8a (but probably was introduced earlier.)

**Comment by danielmewes** [comment]
@nighelles could you look into this please?

**Comment by danielmewes** [comment]
On a side-note, it looks like the sub-heading is cut off? It reads "Some servers are only partially connected to the". Should it say "cluster" after that?

![incomplete connectivity](https://cloud.githubusercontent.com/assets/505365/13623813/1880b36a-e55e-11e5-84f6-b152a77c4922.png)

**Comment by nighelles** [comment]
@danielmewes I think it's a layout issue with a subtitle that's too long. I'll look into that also.

**Comment by nighelles** [comment]
I didn't see the layout problem on my side. What browser was this in?

**Comment by danielmewes** [comment]
Firefox 44.0.2

**Comment by nighelles** [comment]
This is in review 3524. Implemented in nighelles/5493.

**Comment by nighelles** [comment]
This is in next.

**Comment by RubenKelevra** [comment]
Thanks! :)

**Comment by csaintc** [comment]
I'm still seeing this issue in 2.3

**Comment by danielmewes** [comment]
@csaintc That probably means that one of the servers actually isn't connected to the proxy. You can check the `connected_to` field in `r.db('rethinkdb').table('server_status')` to see which servers are connected to which other server and proxy.

**Comment by donpdonp** [comment]
I'm seeing the same error in a proxy connected to a 2-server cluster.
"db2 is not fully connected"

the proxy is on a third machine and is started with proxy --join db1

the status shows that db2 is not connected to the proxy, but i have no idea why

here are some useful bits from the server_status report.
```
db2:
"connected_to": {
    "db1": true ,
    "proxy-dc7ecb48-ed96-4333-8e7c-5262a7cab2c6": false
}

    "rethinkdb" ,
    "--canonical-address" ,
    "10.9.8.117" ,
    "--join" ,
    "10.9.8.116" ,
    "--bind" ,
    "all"


db1:
"connected_to": {
    "db2": true ,
    "proxy-dc7ecb48-ed96-4333-8e7c-5262a7cab2c6": true
} , 

    "rethinkdb" ,
    "--canonical-address" ,
    "10.9.8.116" ,
    "--bind" ,
    "all"

```

**Comment by danielmewes** [comment]
@donpdonp Is the address of db2 reachable from the proxy, and was db2 running when you started the proxy? Does it work if you start the proxy with both `--join db1 --join db2`?

**Comment by donpdonp** [comment]
Restarting the proxy fixed the problem, thanks. Its possible db2 was not running when the proxy was started. I assumed the proxy would discover new nodes via its connection to db1. Also from the docs I saw --join [host] implying only one host can be specified, if --join can/should be used more than once, that'd be nice to note in the command line help.

**Comment by danielmewes** [comment]
@donpdonp Normally `db2` should have established a connection *to* the proxy the moment it started up and learned about the proxy from `db1`. Does your network configuration allow `db2` to connect to the proxy?

**Comment by subandroid** [comment]
What @donpdonp reported is still an issue and observed this in v2.3.5. It looks like when a new instance of RethinkDB is brought up, proxy have hard time connecting to the new instance or vice versa. As an experiment I've opened up all inbound ports in the box with the proxy from the box with the new RethinkDB and it is still not connecting. I will keep troubleshooting it but restart of the proxy always works.
