### ISSUE TITLE
`fold` emit_final function has wrong semantics

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5508]
I ran into this when trying out my example from https://github.com/rethinkdb/rethinkdb/issues/5507#issuecomment-195566372 .

It looks like the result of the `final_emit` function of `fold` is inserted into the output stream as a single element, rather than being split into multiple elements if it's an array. That is it doesn't appear to have the `concatMap` semantics.
However this only seems to be the case if there's also an `emit` function.

Example:
```js
r.expr(["a"]).fold(null, function() {return null;}, {emit: function() {return [0]}, finalEmit: function() {return [1, 2, 3]} })

// Results in:
[0, [1, 2, 3]]

// Expected:
[0, 1, 2, 3]
```

**Comment by nighelles** [comment]
This is in next.
