### ISSUE TITLE
Add optarg to `eachAsync` for managing concurrency

### ISSUE THREAD

**Issue by marshall007** [rethinkdb/rethinkdb#5509]
Now that we have `eachAsync` for automatically awaiting async operations before continuing to read from the cursor, it would be nice if the concurrency could be controlled. This would essentially be equivalent to [`Promise.map(..., { concurrency: <int> })`](http://bluebirdjs.com/docs/api/promise.map.html#map-option-concurrency) from bluebird.

While this can be done in user-code with relative ease, I think it's useful enough (namely in tuning the performance of bulk operations) to consider implementing.

```js
const concurrency = 10;
const pending = [];

cursor.eachAsync((job) => {
  Promise.resolve().then(() => {
    if (pending.length >= concurrency) {
      return Promise.any(pending);
    }
  }).then(() => {
    let p = asyncHandler(job).then(() =>
      pending.splice(pending.indexOf(p), 1);
    );
    pending.push(p);
  });
});
```

Proposal:

```js
cursor.eachAsync(asyncHandler, { concurrency: 10 });
```

**Comment by marshall007** [comment]
I have this working in marshall007/rethinkdb@37c7b32.

**Comment by danielmewes** [comment]
Sure :) Do you want to open a PR?

**Comment by marshall007** [comment]
@danielmewes sure, PR up!
