### ISSUE TITLE
Table size after delete()

### ISSUE THREAD

**Issue by deviantmk** [rethinkdb/rethinkdb#5511]
In a cluster with 3 replicas I had a ~GB of data, i did a delete on the table and was tottaly empty.

Resources
12% cache used 
75.0 MB disk used

I erased the table and created a new one with all the replicas again

Resources
1% cache used
32.0 MB disk used

Why is this extra space taken after running delete on the table?

**Comment by danielmewes** [comment]
This is normal. Even in a completely empty table, there will still be some metadata and index structures in the file. The way RethinkDB's storage format works, that metadata can be placed at any location within the file. If it was placed let's say around the 75 MB mark while the table was full, that would stop RethinkDB from being able to shrink the file below 75 MB until that piece of metadata is no longer used.
If you keep writing to the table, it will eventually get moved towards the beginning of the file and the space will be freed. This can however take a while.
