### ISSUE TITLE
ReqlQueryLogicError: Invalid LineString.  Are there antipodal or duplicate vertices?

### ISSUE THREAD

**Issue by gutenye** [rethinkdb/rethinkdb#5513]
Given

```
r.table("data").insert({route: r.line([0,0], [0,0], [1,1])})
```

Have one next-to duplicate point will throw this error, but GeoJSON LineString with duplicate points works in Google Maps and http://geojson.io, is it considered as a bug?

**Comment by danielmewes** [comment]
This is expected. Some implementations probably ignore duplicate vertices.

We are not currently doing this, though we're planning to filter out duplicates automatically in the future, see https://github.com/rethinkdb/rethinkdb/issues/4518 .

At the moment you'll need to filter the input geometry yourself.
