### ISSUE TITLE
Print proxy ID on startup

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5515]
Proxies use randomly assigned server IDs. Those can for example show up in the log messages of other servers (e.g. https://github.com/rethinkdb/rethinkdb/issues/5456#issuecomment-196419276 ).

For regular servers, we print "Server ready, "newton_ifn" cb189fa9-06d2-442d-8675-e88d67200067" on startup. However for proxies, we just print "Proxy ready."

I think we should include the server UUID there as well.

Assigning to @nighelles .
This will also make the server connectivity status more useful when proxies are present.

**Comment by larkost** [comment]
@nighelles: could you please still allow for distinguishing proxies from servers in the logs? Still using "Proxy ready", but adding the id would work for me.

[This line](https://github.com/rethinkdb/rethinkdb/blob/next/test/common/driver.py#L360) will also need to be checked to make sure it works for the new format.

**Comment by nighelles** [comment]
This is in next, OTS by @danielmewes
