### ISSUE TITLE
this should be a simple insert....What am I missing?

### ISSUE THREAD

**Issue by sirvon** [rethinkdb/rethinkdb#5521]
```python
>>> name = "myDB"
>>> conn = r.connect(host = sett.dev_data_rethinkdbHost(),
... port = sett.dev_data_rethinkdbPort(),
... auth_key = sett.dev_data_rethinkdbAuthKey(),
... ssl={'ca_certs': './cacerts'}, db = name)

>>>r.table('marketplaces').insert(r.http('https://raw.githubusercontent.com/sirvon/fourthScreen/
master/marketplaces_only_RETHINKDB.json')).run(conn)
```

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/ast.py", line 118, in run
    return c._start(self, **global_optargs)
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 589, in _start
    return self._instance.run_query(q, global_optargs.get('noreply', False))
  File "/usr/local/lib/python2.7/dist-packages/rethinkdb/net.py", line 451, in run_query
    raise res.make_error(query)
rethinkdb.errors.ReqlQueryLogicError: Cannot convert STRING to SEQUENCE in:
```

**Comment by Tryneus** [comment]
It looks like it is interpreting the result of the `r.http` call as a string rather than a JSON object - looking at the HTTP response, it isn't setting the Content-Type, so `r.http` does not try to convert it to anything.  You can specify the result type of the query by using `r.http(..., result_format='json')`.

**Comment by sirvon** [comment]
that worked marvelously...how did you look at the http response?

**Comment by Tryneus** [comment]
@sirvon - in Firefox I opened Developer Tools -> Network, then loaded the link.  I clicked the HTTP GET, then clicked the Raw Headers button to see what they were.

There has been some discussion about exposing the entire HTTP response in ReQL - it would actually be pretty easy - but the hard part is deciding how the interface should work (see #3371).
