### ISSUE TITLE
[Q] ReQL Updating object inside an embedded array emits create and delete changes

### ISSUE THREAD

**Issue by gngeorgiev** [rethinkdb/rethinkdb#5524]
Hey guys,

I am hitting the following problem: Suppose that I have the following structure:

```json
{
    "id": 1,
    "data": {
       "arr": [{"text":"item1"}]
    }
}
```

And the following query:
```javascript
r.db('test').table('test').get(1).update(function (item) {
    return {
        data: {
          arr: item('data')('arr').map(function (row) {
             return r.branch(
                  row('text').eq('item1'),
                  row.merge({updated:true}),
                  row
             )
          })
        }
    }
})
```

I am listening for changes in this specific array only, and when the item is updated both create and delete events are emitted. I really need to receive an update event, e.g. `old_val` is not null and `new_val` is not null.

Thanks in advance guys

**Comment by danielmewes** [comment]
Let's continue this discussion on the Google group: https://groups.google.com/forum/#!topic/rethinkdb/OWuW4N01frY

If this turns out to be a server bug, we will re-open this.
