### ISSUE TITLE
dump/restore to/from stdout/stdin

### ISSUE THREAD

**Issue by nh2** [rethinkdb/rethinkdb#5525]
It would make lots of sense if `rethinkdb-dump` could write to stdout and `rethinkdb-restore` could read from stdin, so that you can do something like

`ssh otherhost rethinkdb-dump --stdout | rethinkdb-restore -`

for importing a remote database without writing intermediate files (where you would have to worry about access permissions, deleting it afterwards - this way would allow to never be store the data on disk).

Do you agree?

**Comment by danielmewes** [comment]
Thanks for opening a proposal @nh2 .

I think this idea has come up before in another issue, but I can't find it (@Tryneus do you remember this?).

**Comment by encryptio** [comment]
#3838 is the previous issue

**Comment by nh2** [comment]
OK, happy to close this then as a duplicate, if we can extend the scope of the other issue to also contain exporting to stdout.

Or do you want to keep them separate, one for importing, one for exporting?

**Comment by nh2** [comment]
Note btw that while the importing problem can be worked around with bash substitution (quite hacky but it seems to work), this doesn't work for exporting:

```
$ rethinkdb-dump --file=>(cat > mydump)
Usage: rethinkdb dump [-c HOST:PORT] [-a AUTH_KEY] [-f FILE] [--clients NUM] [-e (DB | DB.TABLE)]...
Error: Output file already exists: /dev/fd/63
```

and there doesn't seem to be a flag to force the write.

**Comment by nh2** [comment]
> and there doesn't seem to be a flag to force the write.

No longer! https://github.com/rethinkdb/rethinkdb/pull/5526

**Comment by danielmewes** [comment]
Ah, thanks @encryptio.
Let's keep this open until your PR is merged.

**Comment by nh2** [comment]
> Let's keep this open until your PR is merged.

This would be the one for the dump-to-stdout feature: https://github.com/rethinkdb/rethinkdb/pull/5528

**Comment by nh2** [comment]
Note that my PR adds this feature, which already helps to implement the `ssh otherhost rethinkdb-dump --file=- | rethinkdb-restore - --force` workflow I had in mind.

But since `dump`/`restore` are still based on the `export`/`import` commands, which are directory based, it still writes temporary files, both for `dump` and `restore`.

There are situations when you don't want that for security reasons, e.g. if you want to use the `ssh otherhost rethinkdb-dump --file=- | rethinkdb-restore - --force` workflow to ensure the data is never written to (potentially unencrypted) disk anywhere, not even temporary files. This case is not covered by my PR.

I've filed a separate ticket (#5530) for that; it's more difficult because it would have to switch the `export`/`import` commands to support a streaming fashion.
