### ISSUE TITLE
Expose server/table stats over HTTP

### ISSUE THREAD

**Issue by lukaszkorecki** [rethinkdb/rethinkdb#5532]
It would be great to expose the server stats via HTTP, similarly to [Elasticsearch's stats](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html) or variety of information available in [RabbitMQ Admin plugin](https://www.rabbitmq.com/management.html).

We use collectd to gather system, service and application level stats.  With [curl_json](https://collectd.org/wiki/index.php/Plugin:cURL-JSON) plugin it's trivial to gather various statistics and push them to Graphite or InfluxDB. This way alerting becomes possible via solutions like Cabot.

Additionally one can inspect state of the cluster/server with curl, rather than using the web interface. 

Any pointers on how to make this happen would be appreciated - event though my C++ is **really rusty**  :wink:

**Comment by danielmewes** [comment]
Hi @lukaszkorecki , we're actually trying to get away from having specialized HTTP APIs on the server, as it adds additional code complexity.

It should be pretty easy to write a node.js or Python script that queries `r.db('rethinkdb').table('stats')` from the RethinkDB server and exposes it through an HTTP server.
Would that work for you?

Our long-term plan is to support "plugins" as described in https://github.com/rethinkdb/rethinkdb/issues/4785 , which among other things could expose HTTP APIs for various purposes and would run directly on the server.

**Comment by lukaszkorecki** [comment]
@danielmewes Plugin system looks really cool  that's what makes RabbitMQ or Elasticsearch shine and also keeps the core pretty small. 

(I'm not a fan of depending on node/npm but that's just my personal opinion ;-)

As for monitoring - at least with collectd - you can extend it with python (or anything really, through `exec` plugin) and push down query results to the collector. Of course that's still not as accessible as driver-less access to the db stats. So that will work for us.


I'll follow the plugin issue - some of the ideas there are really interesting.

Thanks!
