### ISSUE TITLE
We don't error when you coerce a non-Unicode binary blob to a string

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#5536]
Even if it results in a string that we would have rejected if you tried to specify it literally, like "\xFF".  It looks like we'll also happily store these invalid strings in documents, and even use them as primary keys.

**Comment by danielmewes** [comment]
Moving into 2.3. 2.3 isn't that far away, and fixing this can potentially break queries.

**Comment by nighelles** [comment]
I have a fix in nighelles/5536

**Comment by nighelles** [comment]
This is in next.
