### ISSUE TITLE
We should allow `-`s in db names, table names etc.

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#5537]
It seems like the rest of the world is moving to that in place of `_`, and it's pretty annoying.

(@danielmewes, is there any way we could schedule this for 2.4?)

**Comment by felixis-1** [comment]
+1.

Just to add, we have a number of applications where we store some metadata into RethinkDB and create databases and tables by naming them as the auto generated ID of these metadata records. This use case occurs too often for us. And just because of this restriction on `-` character, we need to do string manipulation all over the place. This will be a very nice modification for us.

**Comment by danielmewes** [comment]
Yeah, good idea.

**Comment by VeXocide** [comment]
In favour.

**Comment by oliverjanik** [comment]
Yes please,


My use case is generating table names on the fly based on sanitized input. That input however does contain `-` character often which is very common in urls and slugs.

**Comment by mlucy** [comment]
Actually, as long as we're here and changing this, why do we have any restrictions on db/table names?  Would people object to drastically expanding the set of allowed characters rather than just supporting `-`?

**Comment by marshall007** [comment]
I'm suspicious @mlucy is only saying that because he wants to use emoji for the system table names.

**Comment by danielmewes** [comment]
We should make sure that all db and table names are valid filenames, because our backup tools rely on that (see https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words ). @VeXocide also mentioned that we should disallow quotes and control characters.

**Comment by deontologician** [comment]
So all of unicode, minus `"'<>{}()[]\/*?%` ?

**Comment by VeXocide** [comment]
☃

**Comment by danielmewes** [comment]
I think maybe we should just add `-` and call it a day.

**Comment by oliverjanik** [comment]
Yeah, just whitelist few more commonly used chars that have low chance of colliding with filename restrictions in any OS and job done.

**Comment by mlucy** [comment]
It would be really annoying to have to go back and add more legal characters later.  I've personally wanted "."s and "/"s in table names before (when I wanted a table per website and a table per nested directory, respectively).

Personally I would vote for allowing any db/table name at all and having our backup tool do escaping.

If people think that's overkill, my second vote would be that anything you can type on a qwerty keyboard should be legal (and our backup tool should still do escaping -- not being able to have ":" or "/" in db/table names would be unfortunate).

If adding escaping to our backup tool is too much work, I would vote for just adding support for "-" and opening another issue to support any db/table name after the backup tool is changed.

**Comment by danielmewes** [comment]
> It would be really annoying to have to go back and add more legal characters later.

I don't think it would be *that* bad. :-)

While adding escaping to the backup tools isn't technically hard, I'm concerned about the required development and testing effort that we might better spend on other things at this time.

Note that the escaping isn't just about escaping shell arguments, but about mapping disallowed characters to allowed ones in a reversible way (e.g. we couldn't just put a `\` in front of illegal characters. Ignoring that `\` is an illegal character itself, we would generally need to completely get rid of the illegal characters in the string).

Apart from escaping, at least `rethinkdb import` also still uses period as a db.table delimiter in its command line option format (for `--table`). So further changes would be required.

> I would vote for just adding support for "-" and opening another issue to support any db/table name after the backup tool is changed.

I'm in favor of that.

**Comment by VeXocide** [comment]
I'm in favour of just adding support for `-` and opening another issue to support any database / table name later as well.

**Comment by larkost** [comment]
Specifically on `.` in file/database names: there are a number of places where we display tables names in `DB.TABLE` format. Allowing `.` in the names would make those places more confusing. At a minimum we would have to go over everything (including documentation) and scrub those. I would rather leave them as-is and continue to disallow `.`.

I am vaguely against allowing `/`, but don't have any solid reasoning there.

**Comment by coffeemug** [comment]
I also think we should add `-` and call it a day. I'm still attached to the idea of keeping database/table names as close to PL identifiers as possible. Making an exception for `-` seems reasonable because it's empirically useful to a lot of people, but the case for expanding the valid character set even further seems weaker to me.

**Comment by VeXocide** [comment]
@danielmewes noticed that we should check whether we use the `-` to determine whether a string is a name or potential UUID anywhere.

**Comment by danielmewes** [comment]
Marking settled for allowing `-` in table names. If we can make sure that we nowhere use `-` to differentiate between UUIDs and names, we should also allow it for other identifiers.

**Comment by nighelles** [comment]
This is in next.

**Comment by oliverjanik** [comment]
Has this landed in 2.3.5?

**Comment by AtnNn** [comment]
@oliverjanik No. It's in the 2.4 branch.
