### ISSUE TITLE
Provide way to run rethinkdb proxy node via init scripts

### ISSUE THREAD

**Issue by aaronorosen** [rethinkdb/rethinkdb#5539]
Currently, one must manually edit the init file for rethinkdb if they would like to start an additional instance to run as a proxy node. It would be nice if there was an option to specify this in config file in instances.d/<instance>.conf if the node should run as a proxy instead. This would make automating the install/setup process of rethinkdb easier.

**Comment by danielmewes** [comment]
Agreed. This is actually a duplicate of https://github.com/rethinkdb/rethinkdb/issues/5138.
