### ISSUE TITLE
Support python's "in" operator

### ISSUE THREAD

**Issue by tatsujin1** [rethinkdb/rethinkdb#5552]
compare:
`table.filter(r.row['field'].contains('ball'))`
with:
`table.filter('ball' in r.row['field'])`

It's basically syntactic sugar on the existing syntax, as it simply turns into: `r.row['field'].__contains__('ball')`.
But it looks nicer :)  and I guess it's more "pythonic". 

A slight downside is that when using a lambda parenthesis are required:
`table.filter( (lambda x: x == 1) in r.row['field'])`
and doesn't look as nice any longer...

**Comment by danielmewes** [comment]
I believe this isn't possible in our case. :-( See https://github.com/rethinkdb/rethinkdb/issues/3995 for the explanation.

**Comment by tatsujin1** [comment]
Oh I see, didn't know it did that... weird. 😠

**Comment by seanharr11** [comment]
Is it possible to implement this in the reverse direction?

`table.filter(r.row['book_title'] in ['The Eye of the World', 'A Memory of Light'] )`

It's a PITA to chain a bunch of ```or``` filters together to check if the field's value is in a list. And I don't see any documentation that would support this...

**Comment by tatsujin1** [comment]
I suppose that's also not possible for the same reason (see #3995).
