### ISSUE TITLE
Can i use index reliably immediately after a lot of bulk inserts?

### ISSUE THREAD

**Issue by QianJin2013** [rethinkdb/rethinkdb#5558]
I have encountered a rare case problem:
I insert about 100,000 records to a table `bookings`, using bulk insert method (passing row array),
immediately after insertion done,  i call verify function to check data integrity, it failed, but if i ran the check function again, it succeeded.

This is the asserted reql: 
```
assertEquals("should no any `driveId` which does not exist in `drives`", 0,
        (long) r.table(S.bookings).distinct().optArg(S.index, S.driveId)
                .filter(driveId -> r.not(r.table(S.drives).get(driveId)))
                .count()
                .run(db.c));
```

All indexes are correctly created and indexWait called when create index.

```
db.recreateTable(S.bookings, S.bookingId /*primary key*/);
db.createIndex(S.bookings, S.userId);
db.createIndex(S.bookings, S.driveId);
db.createIndex(S.bookings, S.driveIdAndStatus, new String[]{S.driveId, S.status});
db.createIndex(S.bookings, S.createdAt);
```

```
db.recreateTable(S.drives, S.driveId /*primary key*/);
db.createIndex(S.drives, S.userId);
db.createIndex(S.drives, S.createdAt);
```

```
bulk insert to bookings table....
```

My question is: Can i use index **reliably** immediately after a lot of data inserted to table?

**Comment by tatsujin1** [comment]
One point; are the inserts made using `noreply` ? If so, then no (depending on definition of "reliably").

As the data is being inserted in the background you can't retrieve it immediately. To make sure the data is written, call without `noreply` option (the `insert()` returns after completion), or use `noreplyWait()` after the inserts have been performed (waits until writes using `noreply` has been completed).

If you're not using `noreply` then you may have encountered a bug... But someone who actually knows things should probably step in here (i.e. not me).

**Comment by QianJin2013** [comment]
Thanks. I have not used noReply mode, i just use normal insert method.


The select use an new connection than insert.

They are just executed by junit one by one, i have confirmed insert is
first get executed.

I will try it again by using same connection.

Anyway, this is not easy to happen.

I have uploaded test source to
https://github.com/sjitech/rethinkdb_test_java

The error happened at
https://github.com/sjitech/rethinkdb_test_java/blob/master/src/test/java/PerformanceTests.java#L297

I suspect that index has not yet completly built for new inserted rows,
this is async.
While select does not know the status, so it could not use the excepted
index.


2016年3月24日木曜日、Tatsujin<notifications@github.com>さんは書きました:

**Comment by tatsujin1** [comment]
If it is asynchronous then I guess my point still applies; the write it's still in progress when you're trying to read it back.
I don't know anything about the java driver though, perhaps there is some way to wait for the write to compete.

**Comment by QianJin2013** [comment]
The writes did completed because  assertion of row count succeeded
in
https://github.com/sjitech/rethinkdb_test_java/blob/master/src/test/java/PerformanceTests.java#L240
```
assertEquals(C.bookingCount, db.getTableRowCount(S.bookings));
```


2016-03-25 0:16 GMT+09:00 Tatsujin <notifications@github.com>:

**Comment by tatsujin1** [comment]
Ah, interesting. That does sound inconsistent.

**Comment by QianJin2013** [comment]
I can not reproduce the problem yet.
 
I have added special test case https://github.com/sjitech/rethinkdb_test_java/blob/master/src/test/java/PerformanceTests2.java#L91

Then repeatedly tested the case.

So i think it's not rethinkdb's problem,  maybe my mistake, or maybe it's because junit execution order changes sometime, so the sub query table `drives`  are old data.

Let me close this question.

I want to get "OK" prove from rethinkdb's internal implementation.

**Comment by danielmewes** [comment]
@QianJin2013 If you want to post the `bulkInsert` I can take a look and see if I can spot anything wrong. Though it looks like it's working now?

In general indexes are consistent as soon as the write operation returns. Though you will get inconsistent results if you run the `count` while the write is still happening, or when using `noreply` writes as @tatsujin1 mentioned.

**Comment by danielmewes** [comment]
@QianJin2013 Never mind regarding `bulkInsert`. I just found it here https://github.com/sjitech/rethinkdb_test_java/blob/master/src/test/java/util/Database.java#L84 . The current version of it definitely looks fine.

**Comment by QianJin2013** [comment]
thank you, it's working. 
It just happened once, and another guy have strange "select after insert" problem (reason not clear), so i turned serious to this. 

Sorry bother you. 

I am looking at source of <a href="https://github.com/rethinkdb/rethinkdb/blob/next/src/rdb_protocol/real_table.cc#L87">real_table_t::read_all_with_sindexes</a>
to see what will happen if index is on building. 

I am trying to get a "OK" conclusion from theoretical.

Thanks to any knowledge about internal implementation.

**Comment by danielmewes** [comment]
If you try to use an index while it's building, the query will fail with an exception. It should never use an incomplete or inconsistent index.

**Comment by QianJin2013** [comment]
Good policy, simple and consistent.

Can i call indexWait then select ?

2016-03-25 3:07 GMT+09:00 Daniel Mewes <notifications@github.com>:

**Comment by danielmewes** [comment]
@QianJin2013 Yes if you call `indexWait` first that will make sure that the index finishes constructing.

If you want to combine both operations into one query, you can do something like this:
```java
r.table(...).indexWait().do(() -> { return yourCountQuery; })
```

**Comment by QianJin2013** [comment]
thank you

2016-03-25 3:52 GMT+09:00 Daniel Mewes <notifications@github.com>:
