### ISSUE TITLE
How to get data explorer work on a server

### ISSUE THREAD

**Issue by ankit92agrawal** [rethinkdb/rethinkdb#5559]
I am testing Rethinkdb on a cluster of 3 machines.I have no idea how to make use of something like data explorer in server machine.I tried to tunnel from my localhost to my machine on port 8080 in hope that I can query from my machine.Does rethinkdb has any shell for querying data or any other workaround.i cant get into code everytime I have to execute a query
Thanks

**Comment by danielmewes** [comment]
@ankit92agrawal Using a tunnel to port 8080 is usually the easiest option and should work. You can also check out http://www.rethinkdb.com/docs/security/ , which describes how to set up a reverse proxy for this.

There are multiple options for querying from the terminal. You can use `python` with the RethinkDB Python driver, or if you prefer JavaScript syntax, you can use one of the third-party CLI tools that are listed here http://www.rethinkdb.com/docs/third-party-admin-tools/
