### ISSUE TITLE
is there a reql converter for js <-> java <-> python ?

### ISSUE THREAD

**Issue by QianJin2013** [rethinkdb/rethinkdb#5560]
Normally i input reql in WebAdmin UI, check the result, then convert it to java.
So is there any conversion tool to do this?

**Comment by deontologician** [comment]
We don't have a js to X converter.

But you may be able to write one using a js parser like [esprima](http://esprima.org/). I wrote a [python to js/java/ruby converter](https://github.com/deontologician/multireql) that might give you a start on how to build one.

There's also issue #4171 for allowing different languages in the dataexplorer

**Comment by QianJin2013** [comment]
thank you! The python multi converter is Great.
