### ISSUE TITLE
C# driver causes the database server to terminate

### ISSUE THREAD

**Issue by NameOfTheDragon** [rethinkdb/rethinkdb#5565]
I have been experimenting with this C# driver and the Windows port of RethinkDB, I'm using build 2.2.4-windows-alpha-4.

When I run the unit tests for the driver, the database process terminates almost immediately. A client shouldn't be able to bring down the server...

The repro for the problem is to download the driver source code, open it in Visual Studio and run the unit tests. I have the database running on the same machine and in App.config I have set the host name to 127.0.0.1

**Comment by danielmewes** [comment]
Thanks for the bug report. Can you post the output of the RethinkDB server when this happens?

**Comment by bchavez** [comment]
Hi @NameOfTheDragon , there are some bad bugs in `alpha-4`. IIRC, this was fixed recently, see #5386 for details.

Currently, the C# driver is using [`alpha-6`](https://github.com/bchavez/RethinkDb.Driver/blob/master/Builder/build.fsx#L7) for testing (see [`build.fsx`](https://github.com/bchavez/RethinkDb.Driver/blob/master/Builder/build.fsx#L7)).

```
let serverDownload = 
"http://circus.atnnn.com/ipfs/QmZkxXdHE9sRhNQ91Fh418wN927GdJ2QBVnQeZLDV3LX5j/rethinkdb-windows-alpha-6.zip"
```

Using `alpha-6` should solve this issue and survive the full test battery. However, some tests will fail, namely:

* `DataumNumber`. Currently tracking #5349 for fix.
* `DatumMetaTable`. Should be fixed next time I re-generate the unit tests later next week.

Let me know if this helps.
-Brian

**Comment by NameOfTheDragon** [comment]
Brian, thanks for that. I didn't see any binaries for the DB server beyond alpha 4 and I'm not up for building from source code really. I'm getting all sorts of issues including queries failing because replicas lose contact with each other, etc. I will see if I can get a later build after easter.

**Comment by danielmewes** [comment]
@NameOfTheDragon You can download the mentioned alpha 6 here: http://circus.atnnn.com/ipfs/QmZkxXdHE9sRhNQ91Fh418wN927GdJ2QBVnQeZLDV3LX5j/rethinkdb-windows-alpha-6.zip

The current version for Windows is a "developer preview" and hence still has many bugs. We will release an official beta together with RethinkDB 2.3.0 in a few weeks.

**Comment by NameOfTheDragon** [comment]
I appreciate that it's an alpha build and I'm expecting bugs. I really want RethinkDB to work well on Windows and that's why I'm bashing on it. I assume the point of an alpha release is for people to find the bugs and report them, no?

That said, I'm closing this issue as Brian already mentioned that the issue is fixed in a subsequent build.

**Comment by danielmewes** [comment]
@NameOfTheDragon I didn't mean to come across as dismissive. I appreciate you taking to time to report this bug! Definitely helpful.
