### ISSUE TITLE
Modify metajava.py to generate customized .optArg signatures

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/rethinkdb#5569]
Right now every type of signature is emitted for every AstSubclass. Ideally, we'd only emit the signatures necessary for each ast class.

Example:

`term_info.json`

``` java
    "DISTINCT": {
        "include_in": [
            "T_TOP_LEVEL",
            "T_EXPR"
        ],
        "signatures": [["T_EXPR"]],
        "optargs": {
            "index": "T_STR"
        },
        "id": 42
    },
```

When this is run through `AstSubclass.java` to create `Distinct.java`, only the following signature would be generated for `.optArg`:

``` java
public Distinct optArg(String optname, String value) {
    OptArgs newOptargs = OptArgs.fromMap(optargs).with(optname, value);
    return new Distinct(args, newOptargs);
}
```

but would not generate `optArg` signatures where the value is a `ReqlFunction2`, `ReqlFunction3` etc.

This would reduce noise in the generated files, as well as reduce clutter in auto-complete dropdowns. Most of the signatures are known statically not to be useful, so it would be nice to be able to avoid generating them.

If we end up adding another optarg with a function signature later, we should consider doing this

**Comment by adriantodt** [comment]
![image](https://user-images.githubusercontent.com/6955035/74589397-cf299200-4fe3-11ea-9a13-9755dfe21480.png)
This issue can be closed, as this was freshly regenerated for the 2.4.0 release.
