### ISSUE TITLE
Method to get client port and address in Java driver

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5571]
Analogously to what was added in https://github.com/rethinkdb/rethinkdb/pull/4796 for the other drivers.

**Comment by nighelles** [comment]
This is in next, implemented in nighelles/5571.

**Comment by danielmewes** [comment]
@nighelles could you also backport to v2.3.x please?

**Comment by nighelles** [comment]
And in v2.3.x in 73fe18
