### ISSUE TITLE
web ui: shards table vertical axis labels wrong

### ISSUE THREAD

**Issue by haraldschilly** [rethinkdb/rethinkdb#5575]
in 2.5.5, with ~6M documents across 6 shards/3 replicas, I expect 3 million per shard, right? But it looks like this:

![rethinkdb-shards-scaling-v225](https://cloud.githubusercontent.com/assets/207405/14137598/bbaa3762-f668-11e5-83fe-2112b4dc2bd6.png)

I suspect, the "1M" should be "10M" and the "1000000" should be "1M".

**Comment by danielmewes** [comment]
Thanks for reporting this @haraldschilly . This is actually a duplicate of https://github.com/rethinkdb/rethinkdb/issues/4907 .

**Comment by danielmewes** [comment]
Oh with regard to this being 1M and not 3M: The shard shows the number of documents per shard, not considering the number of replicas. If you change the number of replicas, the shard sizes will remain the same. This is by design.
