### ISSUE TITLE
Swap warning too aggressive on MacOS X

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5578]
With #5235 we now provide a warning when swap is used, to try and help users distinguish RethinkDB performance problems from underlying issues. However this seems to be a bit too aggressive on MacOS and so is providing warning to me almost every time I spin up a local cluster. In addition to the WebGUI warnings, this is also causing problems in some tests that look that all issues have been resolved.

We should probably disable it for now on MacOS X.

**Comment by larkost** [comment]
If this is resolved, then the changes that I have made in the tests to filter this out should be removed. Look for this bug's number to find them in:
`test/scenarios/more_or_less_secondaries.py`

**Comment by nighelles** [comment]
This is in next.

**Comment by larkost** [comment]
We have decided to leave the filters in-place as these warnings could come up in testing and not be important in those tests.
