### ISSUE TITLE
Can't install on debian stretch

### ISSUE THREAD

**Issue by eatnut** [rethinkdb/rethinkdb#5585]
```
rethinkdb : Depends: libssl1.0.0 (>= 1.0.0) but it is not installable
```
Thank you for taking your time.

**Comment by danielmewes** [comment]
Thanks for the report.

It looks like stretch upgraded to libssl1.0.2. We probably need to update our build environment to make it build against a newer version of the library.
I'll do that for the upcoming RethinkDB 2.3.0.

For now you can probably build from source: http://rethinkdb.com/docs/install/debian/

**Comment by danielmewes** [comment]
I've made the required changed to our build servers. RethinkDB 2.3.0 will again work with Debian stretch.

**Comment by tannercollin** [comment]
I'm getting the following error now:

`rethinkdb : Depends: libprotobuf9v5 but it is not installable`

With this apt source:

`deb http://download.rethinkdb.com/apt stretch main`

Any idea why? Did Stretch change?

**Comment by marshall007** [comment]
@tannercollin see https://github.com/rethinkdb/rethinkdb/issues/6228#issuecomment-274235931
