### ISSUE TITLE
Reading table_status can be very slow during reconfigures of large tables

### ISSUE THREAD

**Issue by phil-hildebrand** [rethinkdb/rethinkdb#5586]
While using rethinkdb import to a 9 node cluster on a table with 150m rows during a reconfigure the web interface became unusable, presumably due to very long calls reading the rethinkdb.table_status table.

r.db('rethinkdb').table('table_status').count()  took 2min 5.61s., but did return the correct result of 16 tables.

The reconfigure was going from 9 shards/2 replicas -> 8 shards/2 replicas.  The interface became unusable 10-15 minutes after the import was killed.   1 replica is in the 'backfilling' state, all others are in the 'ready' state.

"status": {
"all_replicas_ready": false ,
"ready_for_outdated_reads": true ,
"ready_for_reads": true ,
"ready_for_writes": true
}

**Comment by phil-hildebrand** [comment]
For Reference:
RethinkDB Version: 2.2.6
Servers - VMWare (ubuntu), SSD, 62GB Ram, 4vCPU

**Comment by danielmewes** [comment]
The fix ended up being relatively uncomplicated, so I think we should also backport to v2.3.x (@nighelles).

**Comment by nighelles** [comment]
This fix is in next via b6c891, and v2.3.x via e33f62f
