### ISSUE TITLE
git/build problems with `next`

### ISSUE THREAD

**Issue by mbroadst** [rethinkdb/rethinkdb#5595]
Hey guys,
I'm putting a patch together to configure the cluster node reconnect timeout, and I've noticed two issues with `next`:

  * there are a number of files that seem to have issues with line endings, or at least that's my best guess. I have `core.autocrlf` enabled globally on my systems, and I'm running into this on linux and mac. Nothing I do can "reset" these files, they are just automatically modified. Here are the files:
```
	modified:   admin/static/fonts/copse_OFL.txt
	modified:   admin/static/fonts/open-sans_LICENSE.txt
	modified:   admin/static/js/date-en-US.js
	modified:   test/performance/comparisons/jquery.tablesorter.js
	modified:   test/rql_test/connections/http_support/jinja2/LICENSE.txt
	modified:   test/rql_test/connections/http_support/werkzeug/LICENSE.txt
```

  * the build seems broken on gcc 4.8.4 on ubuntu 14.10:
```
src/clustering/administration/auth/scram_authenticator.cc: In member function ‘virtual std::string auth::scram_authenticator_t::next_message(const string&)’:
src/clustering/administration/auth/scram_authenticator.cc:168:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1plus: all warnings being treated as errors
```

  the fix is trivial, adding a `return std::string()` to the end of that method, but should that have been caught by CI? maybe I've configured something incorrectly on my end.

Cheers!

**Comment by larkost** [comment]
The first part is probably because `.gitattributes` was added, and it does not play nice whence crossing over that limit. The solution is to `echo "" > ./.gitattributes`, then `git checkout` everything that is having this problem, then `git checkout .gitattributes` again to re-set it. I have filed #5597 to see if we can mitigate problems like this in the future.

I am going to being in @VeXocide on the second point.

**Comment by VeXocide** [comment]
@danielmewes fixed the second issue this morning, he ran into it as well.

**Comment by larkost** [comment]
@mbroadst: Can you try updating your repository? We think that second issue is already fixed.

**Comment by mbroadst** [comment]
@larkost @VeXocide  very strange, that error was from a compile 45min ago, but I now see that next has a commit from 4hours ago to fix the issue. Maybe there was a force push of old commits or something. Thanks, looks like this is no longer an issue.

WRT the .gitattributes, is that just going to be the solution for that from here on out? Your suggested tips fixed the issue, however the issue remains on a fresh checkout of the repo. Either way, looks like you've answered all the questions here, thanks

**Comment by larkost** [comment]
@mbroadst: we are going to figure out how to mitigate/fix the `.gitattributes` issue with #5597
