### ISSUE TITLE
Ruby driver getting "pbkdf2_hmac() function is unimplemented on this machine" on MacOS

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5600]
The system installed version of Ruby on MacOS is getting the following error during `./test/rql_test/test-runner connections/cursor.rb` on `next` (once another problem is worked around):
```
RethinkDB::ReqlDriverError: Error during handshake: #<NotImplementedError: pbkdf2_hmac() function is unimplemented on this machine>
    rethinkdb/build/drivers/ruby/lib/net.rb:959:in `rescue in do_handshake'
    rethinkdb/build/drivers/ruby/lib/net.rb:916:in `do_handshake'
    rethinkdb/build/drivers/ruby/lib/net.rb:978:in `start_listener'
    rethinkdb/build/drivers/ruby/lib/net.rb:687:in `connect'
    rethinkdb/build/drivers/ruby/lib/net.rb:497:in `initialize'
    rethinkdb/build/drivers/ruby/lib/func.rb:129:in `new'
    rethinkdb/build/drivers/ruby/lib/func.rb:129:in `connect'
    rethinkdb/test/rql_test/connections/cursor.rb:35:in `setup'
```

It looks like this has to do with the underlying OpenSSL library:
```
ruby -e 'require "openssl"; OpenSSL::PKCS5.pbkdf2_hmac'
-e:1:in `pbkdf2_hmac': pbkdf2_hmac() function is unimplemented on this machine (NotImplementedError)
```

This does not happen on linux, or on other custom-installed versions of Ruby on my machine that are linked against custom versions of OpenSSL.

**Comment by VeXocide** [comment]
There's a similar issue with older versions of Python, see https://github.com/rethinkdb/rethinkdb/blob/next/drivers/python/rethinkdb/handshake.py#L262 for a bare bones implementation of `pbkdf2_hmac`.

**Comment by VeXocide** [comment]
Note that `ruby -e 'require "openssl"; OpenSSL::HMAC'` seems to indicate that the HMAC functionality is available to base `pbkdf2_hmac` on.

**Comment by mlucy** [comment]
It looks like the default version of OpenSSL on OS X is just slightly too old.  There's a Ruby-only implementation of pbkdf2 available; I'll change it to fall back to that if the OpenSSL one is unavailable.

**Comment by mlucy** [comment]
It looks like the pbkdf2 gem doesn't quite work.  We should probably just implement it ourselves.

**Comment by mlucy** [comment]
A fix for this is in next, CR by @VeXocide .
