### ISSUE TITLE
javadriver ignores timeout?

### ISSUE THREAD

**Issue by iorlas1** [rethinkdb/rethinkdb#5603]
Noticed that in the javadriver the method DefaultCursor.getNext(Optional<Long>) ignores the timeout argument. I tried to make a change where the argument was passed to waitOnCursorItems() and to the awaitingContinue.get() method call. Worked fine for me. 

I checked out the code but failed to run the tests - guess there is some setup that I need - so I haven't contributed my solution. I can build the code just fine though.

Any hints on what needs to be done to run the tests, or if someone else wants to fix the problem for me that is just fine as well. 

--
Regards 
Magnus

**Comment by danielmewes** [comment]
Thanks for the bug report @iorlas1 .

A pull request would be most welcome. We can run the tests on our end. (You might want to take a quick look at our CLA as well: http://rethinkdb.com/community/cla/ .)
In general the Java drive tests require a running RethinkDB server on your local machine. Then you can run them through `gradle test` in the `drivers/java` directory.

Also pinging @deontologician .

**Comment by danielmewes** [comment]
Closed by https://github.com/rethinkdb/rethinkdb/pull/5618 . Will ship together with RethinkDB 2.3.1.
