### ISSUE TITLE
2.3 proxy and admin password issue

### ISSUE THREAD

**Issue by scottder** [rethinkdb/rethinkdb#5607]
If the cluster has an admin password set a proxy cannot connect because it doesn't have the admin PW set as well. 

`warn: Connection attempt from <IP>:29015 failed, reason: no admin password (The remote peer has an admin password configured, but we don't. Connecting to it could make the cluster insecure. You can run this server with the `--initial-password auto` option to allow joining the password-protected cluster.)`

--initial-password isn't available in proxy mode

**Comment by danielmewes** [comment]
Thanks for the report. I'm testing a fix right now...

**Comment by danielmewes** [comment]
Fix in branch daniel_5607, code review 3580

**Comment by danielmewes** [comment]
Fixed in next b56de83d6f72cf00e3465382df17e69a08327fb6 .
