### ISSUE TITLE
Make the Python and JS drivers cache the results of PBKDF2 to reduce latency.

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#5614]
We aren't including the server nonce in the PBKDF2 calculation, so we can cache the result of it to drastically speed up connection times when re-authenticating as the same user.  This is probably a good idea since some users may be on the old "one connection per query" model.  (This is already in review for Ruby.)

**Comment by danielmewes** [comment]
... and Java driver!

This is not critical for 2.3 (but a nice plus). We can update the drivers later.

(@nighelles, @deontologician, @VeXocide )

**Comment by nighelles** [comment]
This should be fixed for the javascript driver.

**Comment by danielmewes** [comment]
@deontologician implemented this for the Java driver in ad1d38fd16ebcd30509f4882f0c6114f1aaf906. I also cherry-picked the change into v2.3.x via ea074d3.

**Comment by nighelles** [comment]
This should be fixed for the python driver as well.

**Comment by nighelles** [comment]
That should be all the drivers.
