### ISSUE TITLE
sign the MacOS uninstaller

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5615]
Our MacOS uninstaller is an Applescript application, and up to MacOS X El Capitan (10.11) those did not require application signatures. It seems that that has changed, so we need to figure out how to sign it, and start doing so.

The work-around is simple: right-click on the scriptlet, and choose "Open". Depending on your Gatekeeper settings you will then have the option to run it at the warning box.

**Comment by larkost** [comment]
It looks like the answer is that we need to use `codesign` to sign the `.app` once we create it. I am working on this, but we are going to need another signing identity as the one we currently have installed on the builder is for installers only.

**Comment by larkost** [comment]
This is up for review in CR 3600, from branch `larkost/5615-sign-macos-uninstaller`.

**Comment by larkost** [comment]
This has been merged into `next` with 5ba40aae.

**Comment by danielmewes** [comment]
@larkost Did you cherry-pick this into `v2.3.x` as well?

**Comment by larkost** [comment]
Merged into `v2.3.x` with 6f1f1c18
