### ISSUE TITLE
move `interface` tests to `test-runner`

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5619]
On `the-shadow` I am having increasing problems getting good results. Part of this is aging hardware, but compounding that is the issue that parts of tests wind up living well past the test they started in with `./test/run`, so things build up to the point where no more valid testing can happen well before a round of tests can complete.

I would like to move more tests from `./test/run` to `test-runner`, as it does a much better job of reaping zombie processes, and the `interface` tests seem like a good candidate, since they are generally isolated in a single file each (well within `test-runner`'s current abilities). This would lighten the load on `./test/run` testing and get us better results.

Note that this is related to: #3442 Merge `./run` and `./test-runner`

**Comment by larkost** [comment]
This has been merged to `next` with 4be62cea.

**Comment by danielmewes** [comment]
:+1:

**Comment by larkost** [comment]
Merged into `v2.3.x` with 5f4fdcb8
