### ISSUE TITLE
2.3 Issues in help output for rethinkdb-dump examples

### ISSUE THREAD

**Issue by scottder** [rethinkdb/rethinkdb#5621]
The examples section still references the -a flag

> rethinkdb dump -c hades -e test.subscribers -a hunter2
>   Archive a specific table from a cluster running on host 'hades' which requires authorization.

**Comment by danielmewes** [comment]
Thanks for reporting this! It's now fixed in v2.3.x and will ship with the 2.3.0 Python driver release.
