### ISSUE TITLE
precise and utopic packages build with `-dirty` version

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5622]
This seems to be caused by `.gitattributes`. For the 2.3.0 packages, I manually changed the gen-config script to not add the -dirty tag but we have to find a permanent solution for this.

**Comment by larkost** [comment]
Linking this to the root cause bug: #5597

**Comment by danielmewes** [comment]
For now I fixed this by committing the changed line endings ( https://github.com/rethinkdb/rethinkdb/commit/da3d04aa03b81855a6610c6bb792433d6f4493df ).
