### ISSUE TITLE
Windows web_assets.cc cause compiler to run out of heap space

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5623]
Found a work-around for 2.3.0 to get the web_assets.cc smaller, but will need a permanent fix.

**Comment by AtnNn** [comment]
In my experience, msc sometimes fails when recompiling `web_assets.cc` alone, but not when compiling it along with other files.

It might be possible to use a resource file instead (https://msdn.microsoft.com/en-us/library/aa381054(v=vs.85).aspx)

**Comment by danielmewes** [comment]
It gave me this error https://msdn.microsoft.com/en-us/library/yz7kx3y2.aspx every time.

This seems to happen once the `web_assets.cc` grows over a certain size. The limit seems to be somewhere slightly below 10 MB. Though I'm not sure what exactly is the limiting factor (total size of string constants in the file? actual file size?).

**Comment by AtnNn** [comment]
We now use a resource file on Windows for the web assets.
