### ISSUE TITLE
`rethinkdb dump` etc. have bad error message if wrong password is used

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5624]
The easiest way to reproduce is taking a server with no password, and running
```
rethinkdb dump -c localhost:... -p
```
Enter some non-empty password, and it will fail like this:
```
ReQL error during 'version check': Could not connect to localhost:28038. Error: %d format: a number is required, not str
Error: rethinkdb-export failed
```

Note that it says "Could not connect to ...", but doesn't print the reason for the connection failure. Additionally it prints a second error when trying to parse the version (it should bail out before even trying to parse it if it can't connect).

**Comment by nighelles** [comment]
This should be fixed in next.
