### ISSUE TITLE
I already have a 'users' table where all my product's users are. What's going to happen when I update to RethinkDB 2.3?

### ISSUE THREAD

**Issue by jazoom** [rethinkdb/rethinkdb#5626]

**Comment by danielmewes** [comment]
The RethinkDB 2.3 `users` table is in the special `rethinkdb` system
database, so there won't be any conflict.

- Daniel

**Comment by jazoom** [comment]
Haha, yeah, I just realised that and came to comment before anyone else called out my silliness. It'll be a different "database". Thanks for the reply.
