### ISSUE TITLE
Support upsert with functions

### ISSUE THREAD

**Issue by tve** [rethinkdb/rethinkdb#5627]
I'm trying to "upsert" a row (i.e. insert if it doesn't exist and update if it does) with the twist that I need to increment a sequence number field. I tried insert() with conflict:update but i can make the add(1) work. Is there an alternate formulation or could insert be made to accept r.row?
Specifically:
```
r.db("test").table("t").insert(
  {foo:"bar", seq: r.row("seq").add(1).default(0)},
  {conflict:"update"})
```
produces:
```
e: r.row is not defined in this context in:
r.db("test").table("t").insert({"foo": "bar", "seq": r.row("seq").add(1).default(0)}, {"conflict": "update"})
                                                     ^^^^^                                                   
```

**Comment by danielmewes** [comment]
We actually just shipped the option for having a custom conflict-resolution function on `insert` with RethinkDB 2.3.0. You can now write this:

```JS
r.db("test").table("t").insert(
  {foo:"bar", seq: 0},
  {conflict: function(oldDoc, newDoc) {
       return oldDoc.merge(newDoc).merge({seq: oldDoc("seq").add(1)});
   }})
```

**Comment by webmutation** [comment]
When I try to run your code I get the following error message

e: The conflict function passed to `insert` should expect 3 arguments in:
r.db("test").table("t").insert({"foo": "bar", "seq": 0}, {"conflict": function(var_50, var_51) { return var_50.merge(var_51).merge({"seq": var_50("seq").add(1)}); }})

**Comment by marshall007** [comment]
@webmutation `<dest>.merge(<source>)` works by recursively merging properties from `source` into `dest`, overwriting any conflicting fields.

In your case, if you'd prefer to preserve the existing fields from `oldDoc` you can simply swap the two:

```js
return newDoc.merge(oldDoc, { armor: oldDoc("armor").add(1) });
```
