### ISSUE TITLE
Regression from 2.2.6 => 2.3.0 for eq_join with order_by

### ISSUE THREAD

**Issue by brianjpetersen** [rethinkdb/rethinkdb#5628]
I updated to version ```2.3.0``` from version ```2.2.6``` and am experiencing a regression in my testing that I haven't been able to attribute to any changes made internally.

Specifically, I have a table with a secondary compound index named ```by_which_then_what_then_when``` against the attributes ```[r.row['which'], r.row['what_id'], r.row['when']]```.  I have the following three documents inserted.

<img width="913" alt="screen shot 2016-04-07 at 3 48 05 pm" src="https://cloud.githubusercontent.com/assets/2500718/14364732/2f8d287c-fcd8-11e5-9356-fc5ef79da77b.png">

I perform a ```between``` query on this table, followed by an ```order_by``` using the secondary index ```by_which_then_what_then_when```.  This works as expected on both version ```2.2.6``` and ```2.3.0``` for both ascending and descending ordering.

<img width="915" alt="screen shot 2016-04-07 at 3 59 00 pm" src="https://cloud.githubusercontent.com/assets/2500718/14365082/cf1e3290-fcd9-11e5-8ee0-6f8662d8e12b.png">

<img width="906" alt="screen shot 2016-04-07 at 3 59 13 pm" src="https://cloud.githubusercontent.com/assets/2500718/14365085/d620a7da-fcd9-11e5-8139-2918486e4b03.png">

When I tack on an eq_join against another table in the database, I used to recover correct ordering (consistent with the ```order_by``` and the previous two screenshots) in ```2.2.6```.  However, in ```2.3.0```, the ordering appears to be lost.

<img width="918" alt="screen shot 2016-04-07 at 3 59 32 pm" src="https://cloud.githubusercontent.com/assets/2500718/14365086/db3cc578-fcd9-11e5-9eb9-2a5400844748.png">

<img width="916" alt="screen shot 2016-04-07 at 3 59 48 pm" src="https://cloud.githubusercontent.com/assets/2500718/14365095/e18f81b8-fcd9-11e5-9987-ce69a79136b7.png">

I've noted the problem using the Python driver as well.  I'm currently running a single instance of RethinkDB.  If helpful, and with an NDA in place, I can grant you access to the environment (although I suspect it should be replicable in other environments and with other data, I just haven't been able to verify that).

Here are some additional details.  

```
Python 3.5.1 |Anaconda 2.5.0 (64-bit)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
```
```python
>>> import rethinkdb
>>> rethinkdb.__version__
'2.3.0'
```
```
~/workspace/shoebox/testing $ rethinkdb -v
rethinkdb 2.3.0~0trusty (GCC 4.8.2)
```
```
~/workspace/shoebox/testing $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```

**Comment by brianjpetersen** [comment]
Apologies, I didn't read the release log closely enough.  For those who encounter this "regression," it is noted in the release notes.

> The eqJoin command no longer returns results in the order of its first input. You can pass in the new {ordered: true} option to restore the previous behavior.

https://github.com/rethinkdb/rethinkdb/releases/tag/v2.3.0

**Comment by danielmewes** [comment]
Sorry for the inconvenience.
We changed this because not keeping the ordering gives us a lot more potential for performance optimizations in `eqJoin`.

**Comment by geddski** [comment]
@danielmewes the `{ordered: true}` option seems to have no effect :/ Is there another way to get the order back?

**Comment by danielmewes** [comment]
@geddski Can you share the full query you're running?
If `{ordered: true}` doesn't make `eqJoin` keep the ordering from the left stream, that's a bug.

**Comment by danielmewes** [comment]
@geddski A work-around is using `concatMap` with a `getAll`.
Instead of `left.eqJoin(leftfield, rightTable, {index: "idx"})`, you can use:
```js
left.concatMap(function(l) { return rightTable.getAll(l(leftField), {index: "idx"}).map(function(r) { return {left: l, right: r}; } ); } )
```
