### ISSUE TITLE
In 2.3 Java driver RethinkDB.r.array() works differently with a passed in array

### ISSUE THREAD

**Issue by sceutre** [rethinkdb/rethinkdb#5631]
In the old Java driver if you could go:
`
  Object[] keys = { "a", "b" };
  r.array(keys); 
`
you'd get a list with two elements "a" and "b".  In the new driver you get a list with a single element, the array containing "a" and "b".  We were using this for example to generate the argument to table.getAll() which results in our searches not working.  A workaround is to just use Arrays.asList(keys) instead of r.array(keys).  

The change if it was intended is fine, but it'd be nice to call it out in the release notes as it's slightly mysterious when things just don't quite work.

**Comment by danielmewes** [comment]
Hi @sceutre . We changed the implementation in order to support lambdas inside of arrays, which is required for the new `interleave` option of the `union` term.

There might be a better way to implement this that maintains the old behavior that you mention.

**Comment by srh** [comment]
"wontfix" is more of a prediction than an opinion here -- I don't know the Java driver too well, but if `r.expr(keys)` doesn't do the thing you want then it sounds like a new command would be appropriate.
