### ISSUE TITLE
RethinkDB.com - Typo in code on Javascript cookbook page ?

### ISSUE THREAD

**Issue by jouerose** [rethinkdb/rethinkdb#5633]
Hello, 

on this page: https://rethinkdb.com/docs/cookbook/javascript/
Under this title: Filtering based on the presence of a value in an array
We have the following sentence: "Suppose we have a table users with documents of the following form"
which has "users" in plural form yet in the four other occurrences of the table "user" it is in singular form.
Is there a particular reason for this difference? thank you for your time.

**Comment by dineyw23** [comment]
I think you should open this issue in the RethinkDB docs' issue tracker,[ here.](https://github.com/rethinkdb/docs/issues)

**Comment by jouerose** [comment]
thanks @dineyw23 for the correction.
