### ISSUE TITLE
Logstash plugin causes a sanity check to fail

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#5644]
See https://github.com/rethinkdb/logstash-input-rethinkdb/issues/13 .

**Comment by mlucy** [comment]
It look like any time you try to subscribe to a changefeed on an artificial table with `squash: true` set we fail this check.

**Comment by mlucy** [comment]
It looks like the behavior prior to the change that introduced the crash was to treat `squash: true` and `squash: false` identically for artificial tables, with semantics that are most similar to `squash: true` for real tables, but with implementation details in the `changefeed` namespace identical to `squash: false`.  I think we should go back to that behavior.

**Comment by mlucy** [comment]
A fix for this is in CR 5644 by @VeXocide .

**Comment by mlucy** [comment]
This is in next and 2.3.x.

**Comment by mlucy** [comment]
@coffeemug -- We should probably do a point release for this and https://github.com/rethinkdb/rethinkdb/issues/5643 once that's in.  Does someone besides @danielmewes know how to do that?  Maybe @larkost ?

**Comment by coffeemug** [comment]
I'll talk to some ppl tomorrow and and also see if @AtnNn is available to help.

**Comment by danielmewes** [comment]
If you end up building this week, I recommend someone take a look at https://github.com/rethinkdb/rethinkdb/issues/5622 first. For 2.3.0, I literally waited until buildbot was done with the checkout step, and then went into its temporary directory and edited the scripts/gen_version.sh script to not add `-dirty` before it started compiling the server. You can do it again the same way of course, but at least need to be aware of it.
