### ISSUE TITLE
Server name is no longer random

### ISSUE THREAD

**Issue by VeXocide** [rethinkdb/rethinkdb#5655]
In 2.3 a random number generator is no longer being properly seeded, leading to non-random server names.

**Comment by adamkdean** [comment]
Does https://github.com/rethinkdb/rethinkdb/issues/5643#issuecomment-209125101 fix this?

**Comment by VeXocide** [comment]
@adamkdean -- unfortunately it's a completely separate issue, but I'm working on it.

**Comment by adamkdean** [comment]
Ok no problem, just wanted to check rather than assume.

Thanks for working on this, and the rest of Rethink, much appreciated!

**Comment by VeXocide** [comment]
In CR 3599 by @Tryneus

**Comment by VeXocide** [comment]
Merge into `next` and `v2.3.x` via commits f6bdc5e5f696ab90c1cf08da03fd719a628c3773 and 52e39c78b4838b3ae1a1884c2e54c2549dfb4a1b respectively.
