### ISSUE TITLE
cursor timeout

### ISSUE THREAD

**Issue by jjqq2013** [rethinkdb/rethinkdb#5656]
I know cursor timeout has been implemented, but is there anyone noticed it's not enough theoretically?

https://github.com/rethinkdb/rethinkdb/blob/9715c657c64189c52d8de7af56ddf37d18411fb0/drivers/java/src/main/java/com/rethinkdb/net/Cursor.java#L197

``` java
        T getNext(Optional<Long> timeout) throws TimeoutException {

            while( items.size() == 0){
                maybeSendContinue();
                waitOnCursorItems(timeout);   ////// confirm here 

                if( items.size() != 0){
                    break;
                }

                error.ifPresent(exc -> {
                    throw exc;
                });
            }

            Object value = Converter.convertPseudotypes(items.pop(), fmt);
            return Util.convertToPojo(value, pojoClass);
        }
```

Please note the `waitOnCursorItems(timeout)` maybe called several times theoretically, so the total consumed timeout is greater than specified.

But I can not produce this problem, i just think this should be fixed by decrease timeout once waited.

**Comment by danielmewes** [comment]
Thanks for your research @QianJin2013 .

**Comment by adriantodt** [comment]
This shoulb implemented to one of the branches (https://github.com/rethinkdb/rethinkdb-java/pull/12) of the Java driver, which now lives in a separated repository (https://github.com/rethinkdb/rethinkdb-java). This issue can be closed. Open a ticket on the new repository if the bug still exists on the new `com.rethinkdb.net.ResponseHandler`.
