### ISSUE TITLE
2.3.0 r.array(Object val0, Object...vals) cause unexpected problem

### ISSUE THREAD

**Issue by QianJin2013** [rethinkdb/rethinkdb#5657]
hi, java driver 2.3.0 modified  `r.array` definition, but caused problem when passing var args, i want to know why do the modification( sorry, i am not accusing, just need to know if there is any merit, i think this modification is unnecessary).

<a href="https://github.com/rethinkdb/rethinkdb/blob/95dfdb28a268f7fe68ab357596e6751baea99c27/drivers/java/src/main/java/com/rethinkdb/gen/model/TopLevel.java#L39">TopLevel.java#L39</a>

``
Old:
```
    public List array(Object... vals){
        return Arrays.asList(vals);
    }
```
New:
```
    public List array(Object val0, Object... vals){
        List res = new ArrayList();
        res.add(val0);
        res.addAll(Arrays.asList(vals));
        return res;
    }
```

The new definition has problem:
```
List SomeMethod(Object...objs) {
   return r.array(objs)
}
```
Calling SomeMethod("a","b") results an ArrayList which **always contains only 1 element** which is an Object[2], no matter how many arguments you passed to SomeMethod!

This will not works like previous version which will get ArrayList with 2 elements "a" and "b".

So,

Assume I have table(id, firstName, surName) which has a compoundIndex consists of [firstName, surName], and make a function `MyGetAllByCompoundIndex`, 
```
    GetAll MyGetAllByCompoundIndex(Object...compoundConditions) {
        return tbl.getAll(r.array(compoundConditions)).optArg("index", "someCompoundIndex");
    }
``` 
I know it's better to define two fixed parameters:
```
    GetAll MyGetAllByCompoundIndex(Object firstName, Object surName) { 
```
But for some reason it's already designed as variable arguments and it works fine before 2.3.0.

Assume i use the function like this:
```
   someReql.map(row -> r.hashMap("ary", MyGetAllByCompoundIndex( row.g("firstName"), row.g("surName")).coerceTo("array"))).run(con)`
```

Then this will not works.

**Comment by mlucy** [comment]
ping @deontologician

**Comment by danielmewes** [comment]
This is the same as https://github.com/rethinkdb/rethinkdb/issues/5631 .
To go into a bit more detail: The reason we fixed the first argument was because Java couldn't resolve the overload type between the lambda variant and the Object variant when pure varargs were used.

We will try to figure out a better solution.

**Comment by QianJin2013** [comment]
Thank you i got it.

2016年4月20日水曜日、Daniel Mewes<notifications@github.com>さんは書きました:
