### ISSUE TITLE
Typo on the website with the new user and password?

### ISSUE THREAD

**Issue by jwanglof** [rethinkdb/rethinkdb#5659]
I think I have found a typo on the website but not really sure if I'm doing something wrong or not. I have added a user with ID: `test_user` and password: `test_password` according to the docs: https://rethinkdb.com/docs/permissions-and-accounts/

The server is running fine and I can access the web interface, however, when I try to connect to it via the JavaScript RethinkDB driver with the following command:

    var r = require('rethinkdb');
    r.connect({host: 'localhost', port: 28015, db: 'database', user: 'test_user', password: 'test_password'})

I always get an `ReqlAuthError: Wrong password`-error.

However, if I change `user` to `username` it works fine. So the command that works is this: 

    r.connect({host: 'localhost', port: 28015, db: 'database', username: 'test_user', password: 'test_password'})

**Comment by NeilHanlon** [comment]
This is a _bit_ of an issue...

Every driver except javascript uses `user` as the username field for `r.connect()`. Javascript uses `username`

Ultimately it's a pretty easy code fix, but probably is going to require communication for people that have already updated and changed their code over.

**Comment by nighelles** [comment]
Hey, thanks for pointing this out. We're considering this a bug in the javascript driver, and it will be fixed to be consistent with the documentation and the other drivers.

**Comment by nighelles** [comment]
This is fixed in next.

**Comment by danielmewes** [comment]
@nighelles Can you backport the fix to `v2.3.x` please?

**Comment by danielmewes** [comment]
Actually since we've shipped this, we should probably support both variants for 2.3.x (and potentially longer, though we can probably remove it in 2.4).

@nighelles do you mind adding a `username` option back in that maps to `user` for backwards compatibility?

**Comment by nighelles** [comment]
@danielmewes , the current fix does currently support both versions to avoid breaking existing code.

**Comment by nighelles** [comment]
@danielmewes This is in 2.3.x

**Comment by danielmewes** [comment]
Cool, perfect :)

**Comment by kevintechie** [comment]
Can the NPM package be updated with the fix?

**Comment by danielmewes** [comment]
@kevintechie Yep, we should be releasing it later today.
