### ISSUE TITLE
Server status table not readable by non-admin users

### ISSUE THREAD

**Issue by dancannon** [rethinkdb/rethinkdb#5663]
In GoRethink we read the `server_status` table to get the list of available servers when connecting and also create a changefeed on this table to ensure that the client always has the complete up-to-date list of servers. 

However in 2.3 with the addition of users this no longer works for non-admin users as it appears that it is not possible to grant read permission to non-admin users on system tables such as `server_status`. For example:

```js
r.db("rethinkdb").table("users").grant("user", {read: true})
```
```
The `rethinkdb` database is special, you can't grant permissions on it in
```

I understand that system tables should be protected but should the status tables also be protected from reading?

**Comment by mlucy** [comment]
Granular permissions on systems tables seems like a reasonable thing to add support for.  I think @VeXocide commented once that it's a little bit hard for some reason?

It also seems like it might be reasonable to have some system tables default to being world-readable.

Tagging as a `ReQL_proposal` and putting into 2.4.

**Comment by VeXocide** [comment]
Indeed, we're hoping to do this for 2.4. It's a sufficiently large set of changes that we'll be unlikely to backport them to 2.3 though.

**Comment by danielmewes** [comment]
I just opened https://github.com/rethinkdb/rethinkdb/issues/5692 to address the general issue of extending permissions to system tables. Closing this as a duplicate.
