### ISSUE TITLE
[JavaScript Driver] Bug when I use custom user

### ISSUE THREAD

**Issue by thinklinux** [rethinkdb/rethinkdb#5669]
I added a new user to my database and for some reason I got `Wrong password` error. I looked at the repo and I saw this:

```javascript
@rawSocket.user = host["user"]
@rawSocket.password = host["password"]

# Default to admin user with no password if none is given.
if @rawSocket.user is undefined
    @rawSocket.user = "admin"
if @rawSocket.password is undefined
    @rawSocket.password = ""
```

Everything is fine here but when I looked over the compiled version in my node_modules folder I saw this:

```javascript
_this.rawSocket.username = host["username"];
_this.rawSocket.password = host["password"];
if (_this.rawSocket.username === void 0) {
  _this.rawSocket.username = "admin";
}
if (_this.rawSocket.password === void 0) {
  _this.rawSocket.password = "";
}
```

So I had to set `username` on the `connect` method not `user` to have this working. The npm package version is 2.3.0.

**Comment by nighelles** [comment]
Hey @thinklinux , thanks for reporting this. This seems like the same issue from #5659 . We're fixing the problem with the javascript driver, but in the meantime using `username` should work.

Let me know if you have any other issues or questions.
