### ISSUE TITLE
In admin CLI, tab completion midline has behavior oddities

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#567]
I have a table with an UUID `3b396ec6-ee3f-4e53-b7c3-96c8a89b066c`. In admin CLI:

```
set acks 3b_ 1
```

The cursor is denoted by underscore. If I hit TAB in this scenario, it does nothing.

```
set durability 3b_ --soft
```

The cursor is denoted by underscore. If I hit TAB in this scenario, it jumps the cursor to the end of the line.

Ideally, tab completion would just work as expected even if we aren't completing the last thing typed. The next best thing is to do nothing when the user hits TAB, but that has to be consistent.

Low priority, obviously.

**Comment by Tryneus** [comment]
Closing this - the admin CLI has been removed in 1.16.
