### ISSUE TITLE
RethinkDB ReqlDriverError Error during handshake

### ISSUE THREAD

**Issue by mhassaan** [rethinkdb/rethinkdb#5670]
hi guys I am trying to configure rethinkdb with my rails application along with postgresql . I have followed the procedure mentioned in the documentation  but i am getting this error when i try to add a record using rails console .

`RethinkDB::ReqlDriverError Error during handshake: #<Errno::ECONNRESET: Connection reset by peer>`
Ruby version is 2.2.4 and rethinkdb is 2.3.0. I have followed other posts too regarding this problem but i dont find any update. What am i missing ? Your help will be appreciated.

**Comment by larkost** [comment]
We are a little confused by this, since there should be good error messages even if you had mixed versions of server and client. One thought is that you might have your port numbers mixed up, and are trying to connect to, for instance, the cluster port? Is there anything in the server logs when you make this connection?

We just explicitly ran an experiment where we ran a 2.3.0 server and connected to it with a 2.2.6 version of the Ruby driver, and things worked correctly (as expected). Could you run the following commands, so that we can be sure what things look like?
`gem list rethinkdb` (on the client)
`rethinkdb --version` (on the server)

**Comment by mhassaan** [comment]
No i dont see any logs beacause when i try to require rethinkdb in rails console , it fails. When i request using webUI yes then i can see logs  But now i have upgraded my ruby version to 2.3.0 . 
`gem list rethinkdb` gives me `rethinkdb (2.3.0.0)` . And more over when i run this command
 `rethinkdb --version` i get `rethinkdb 1.4.1 (CLANG 4.1 ((tags/Apple/clang-421.11.66)))` . I am a bit confused about my version because i installed rethinkdb using homebrew and it gives me version `rethinkdb-2.1.5-2` . What am i doing wrong ? Is there any way to wipe out all the versions of rethinkdb on my machine and then test it again . Because i have the same connection issue when i try to test using python driver . Your help will be appreciated.

**Comment by larkost** [comment]
You can download the `.dmg` from our [website](https://rethinkdb.com/docs/install/osx/), and that has an uninstaller (note: there is a bug in it on older MacOS versions right now). That will clean out that old version, assuming you used a `.pkg` version. Personally I prefer the version from `.pkg` over homebrew, but that is mostly personal preference.

But it is likely that that old version of RethinkDB is what you have been running, and that is the cause.

**Comment by mglukhovsky** [comment]
@mhassaan: you can try `which rethinkdb` to see what binary it's choosing to run.

**Comment by mhassaan** [comment]
@larkost it works , i download .pkg version and uninstall the previous version. Then i ran the package to install the updated version. And now i query in rails console I dont see any connection out problem. I think that drivers available in older versions of rethinkdb are not feasible with current version. Moreover, @mglukhovsky @larkost If I am not wrong, currently there is no way to switch database in WebUI of rethinkDB, right ?

**Comment by danielmewes** [comment]
@mhassaan Older drivers work with newer versions, but not the other way around.
Indeed there is no way at the moment to change the default database in the web UI. You have to use `r.db` for accessing databases other than `test`.
