### ISSUE TITLE
Uninstall RethinkDB.app made on 10.10 crashes on 10.7

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5671]
We have recently moved from compiling our MacOS packages on a 10.7 machine to one running 10.10 (with settings to ensure compatibility with 10.7). This has worked out very well in most cases, but the resulting `Uninstall RethinkDB.app` crashes (SIGSEV) on 10.7 machines. Unfortunately, we only noticed this after we shipped the 2.3.0 package, so we have a bad version out in the wild.

After working on this a little it turns out that this appears to be a bug in 10.10 that Apple has fixed on 10.11. So this is more of a record-keeping message, since the solution is to move our builder to 10.11, which I am doing as I write this.

**Comment by larkost** [comment]
I will leave this open until we have shipped a new version that corrects this problem, presumably 2.3.1 which will probably be going out next week.

**Comment by danielmewes** [comment]
I'll close this because it makes keeping track of which changes are making it into 2.3.1 a bit easier for me.
