### ISSUE TITLE
Not being able to externally start a proxy node to connect to a Docker based 3 node cluster (received inconsistent routing)

### ISSUE THREAD

**Issue by alfredbaudisch** [rethinkdb/rethinkdb#5676]
I managed to run a 3 node cluster using Docker in my machine and I can do all operations in the web UI. All nodes communicate with each other correctly. Also with or without providing the -h hostname the result is the same.

### Create a 3 node cluster

    docker run -d -h localhost -p 8080:8080 -p 28015:28015 -p 29015:29015 -v /data:/data --name rethink-1 --net rethinknet rethinkdb  rethinkdb -d /data --bind all --canonical-address 172.18.0.2
    docker run -d -h localhost -p 8081:8080 -p 28016:28015 -p 29016:29015 -v /data1:/data --name rethink-2 --net rethinknet rethinkdb rethinkdb  -d /data --bind all --canonical-address 172.18.0.3 -j 172.18.0.2:29015
    docker run -d -h localhost -p 8082:8080 -p 28017:28015 -p 29017:29015 -v /data2:/data --name rethink-3 --net rethinknet rethinkdb rethinkdb  -d /data --bind all --canonical-address 172.18.0.4 -j 172.18.0.2:29015

The docker machine IP is `http://192.168.99.100/`.

### Starting a proxy node

I'm now trying to create a proxy outside of docker but I keep getting this message (or any other variation of it):
`error: Received inconsistent routing information (wrong address) from 192.168.99.100:29015 (expected_address = peer_address [192.168.99.100:29015], other_peer_addr = peer_address [172.18.0.2:29015]), closing connection.  Consider using the '--canonical-address' launch option.`

I have tried to initiated the proxy in the following ways:

- ./rethinkdb proxy --canonical-address localhost -j 192.168.99.100:29015 -o 1
- ./rethinkdb proxy --canonical-address localhost -j 192.168.99.100:29015 -j 192.168.99.100:29016 -j 192.168.99.100:29017 -o 1
- ./rethinkdb proxy -j 192.168.99.100:29015 -j 192.168.99.100:29016 -j 192.168.99.100:29017 -o 1
- ./rethinkdb proxy -j 192.168.99.100:29015 -j 192.168.99.100:29016 -j 192.168.99.100:29017 -o 1
- ./rethinkdb proxy -j 192.168.99.100:29015 -o 1

I also tried changing the port from 29*** in all of these commands to 28*** but then I got:
`warn: Received invalid clustering header from 192.168.99.100:28015, closing connection -- something might be connecting to the wrong port`

### Nodes with the docker-machine ip

Then I tried setting the canonical-address with the docker machine ip:

    docker run -d -p 8080:8080 -p 28015:28015 -p 29015:29015 -v /data:/data --name rethink-1 --net rethinknet rethinkdb  rethinkdb -d /data --bind all --canonical-address 192.168.99.100
    docker run -d -p 8081:8080 -p 28016:28015 -p 29016:29015 -v /data1:/data --name rethink-2 --net rethinknet rethinkdb rethinkdb  -d /data --bind all --canonical-address 192.168.99.100 -j 192.168.99.100:29015
    docker run -d -p 8082:8080 -p 28017:28015 -p 29017:29015 -v /data2:/data --name rethink-3 --net rethinknet rethinkdb rethinkdb  -d /data --bind all --canonical-address 192.168.99.100 -j 192.168.99.100:29015

But then the nodes didn't even join each other.

**Comment by alfredbaudisch** [comment]
I fixed it by myself.

1) Name and tag the servers

    docker run -d -h localhost -p 8080:8080 -p 28015:28015 -p 29015:29015 -v /data_rethink1:/data --name rethink-1 --net rethinknet rethinkdb  rethinkdb -n rethink1 -t rethink1 -d /data --bind all --canonical-address 172.18.0.2
    docker run -d -h localhost -p 8081:8080 -p 28016:28015 -p 29016:29015 -v /data_rethink2:/data --name rethink-2 --net rethinknet rethinkdb rethinkdb -n rethink2 -t rethink2 -d /data --bind all --canonical-address 172.18.0.3 -j 172.18.0.2:29015
    docker run -d -h localhost -p 8082:8080 -p 28017:28015 -p 29017:29015 -v /data_rethink3:/data --name rethink-3 --net rethinknet rethinkdb rethinkdb -n rethink3 -t rethink3 -d /data --bind all --canonical-address 172.18.0.4 -j 172.18.0.2:29015

2) Run the proxy node as a rethinkdb Docker image. Previously I was trying to start the proxy outside docker.

    docker run -d -h localhost -p 28020:28015 --name rethink-proxy --net rethinknet rethinkdb rethinkdb proxy --canonical-address 192.168.99.100 -j 172.18.0.2:29015 -j 172.18.0.3:29015 -j 172.18.0.4:29015 -o 3

Note that the intent of this is to run a cluster and a proxy in my local machine for development.

**Comment by danielmewes** [comment]
Thanks for documenting this @alfredbaudisch . Might be useful for others who have the same issue.
