### ISSUE TITLE
Better error messages for version mismatches

### ISSUE THREAD

**Issue by mikemaccana** [rethinkdb/rethinkdb#5678]
When attempting a `rethinkdb restore`

    ReQL error during 'version check': Could not connect to localhost:28015. Error: No JSON object could be decoded

The 'JSON' message is confusing, it makes it seem like the backup is corrupt. The action cause is the version mismatch. A better error would be:

    ReQL error during 'version check': rethinkdb version mismatch when connecting to localhost:28015. 

Or better yet:

    ReQL error during 'version check': rethinkdb version mismatch when connecting to localhost:28015. Dump is from rehtindb 2.3.0, this is version 2.2.5

**Comment by danielmewes** [comment]
This is similar to https://github.com/rethinkdb/rethinkdb/issues/5667, but for the Python driver.

I completely agree that we should catch this error and print a better message.
