### ISSUE TITLE
r.http https queries failing on MacOS 10.7 when built on 10.10+

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5681]
Starting with `v2.3.0` we are building on MacOS 10.10 or better. This gets us a much newer build toolchain, and we are building such that we should be compatible with MacOS 10.7. So far the only issue we have encountered with this is in the https support in `r.http`: for those results we are getting an error back every time:

```
e: Error in HTTP GET of `https://google.com`: SSL connect error.
header:
null
body:
null in:
r.http("https://google.com")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The same server binary running on latter versions of MacOS (e.g. 10.10 or 10.11) produce the correct results. This is not specific to any one site, and there is nothing in the server-side logs. At minimum we are probably missing an opportunity to give a better error message in these cases.

**Comment by larkost** [comment]
I have tried out the work in #5672 to see if that fixes the issue, but it does not appear to do so.

**Comment by larkost** [comment]
After trying a number of variants, including the latest version of `curl` it looks like we alway have this problem when building with our embedded version. So when built on 10.7 with `--static curl` (really `--static all`) we still get the issue. Building with the `--dynamic curl` flag on any version seems to work correctly. As far as I can tell we are correctly specifying `--with-darwinssl`, and the `curl` build logs seem to bear that out (only oddity is that curl is compiling using `gcc`).

With a little help from @VeXocide I got a slightly better error message:
```
Error in HTTP GET of `https://rethinkdb.com`: 35 Unknown SSL protocol error in connection to rethinkdb.com:-4960 SSL connect error.
```
I have thus-far been unable to determine what `-4960` is or where it is from (not in curl source code or documented in Apple's Security.framework documentation).

**Comment by larkost** [comment]
I found the error... and it is either `coreFoundationUnknownErr` or `errSecCoreFoundationUnknown` depending on where it actually comes from. This is coming out of `darwinssl_connect_step2` in `libcurl`, so there is potentially going to be a lot of digging to do to below this to figure out where either `curl` or the 10.7 `Security.framework` is going wrong.

My current view on this is that we probably should not fix this. We know that it does not work on 10.7, but does on 10.10. I will do the work of figuring out what version it does work on, but assuming that it works on something like 10.9 we should probably just say that we no longer support below that and call it a day. we are already most of the way there with the way there with issue #5424, where we disallow compiling with the native version of Clang on that version.

**Comment by larkost** [comment]
I setup the virtual machines today, and can confirm that the current binary works as expected on 10.9.5. So my vote is that we use this bug to add in the additional euro reporting, declare that we support from 10.9 up, and close this bug.

@danielmewes, this sound about right?

**Comment by danielmewes** [comment]
Could we check for this particular error number and emit a special message stating that `https` is not supported on OS X 10.8 and older?
That would be my only additional suggestion. Other than that not fixing the issue and dropping full support for OS X older than 10.9 sounds fine to me.

**Comment by VeXocide** [comment]
We can easily check and emit a special message if we're on OS X and `CURLE_SSL_CONNECT_ERROR` occurs.

**Comment by srh** [comment]
Closing.  People will have to upgrade.
