### ISSUE TITLE
Documentation for r.row (javascript) contains significant error and filter(...) should fail hard to reveal it

### ISSUE THREAD

**Issue by cefn** [rethinkdb/rethinkdb#5687]
I was trying to understand the operation of ```r.row``` by reference to [the javascript documentation](https://rethinkdb.com/api/javascript/row/). I was deeply confused by how this example offered in the documentation) could ever possibly work. 

```javascript
r.table('users').filter(r.row('embedded_doc')('child') > 5).run(conn, callback)
```
I investigated further (executable example below) and indeed it seems to be a straight-up error in a central part of the RethinkDB documentation.

The example should instead read...

```javascript
r.table('users').filter(r.row('embedded_doc')('child').gt(5)).run(conn, callback);
```

The example was clearly inconsistent with my mental model of ReQL. ReQL relies on late-bound and remote execution, only feasible within a new function scope, whereas this was evaluating the greater-than operator directly in the current javascript scope. 

If others try to make sense of ReQL by reference to this example, they are going to be very misled.

Sadly given the current behaviour of filter it doesn't throw an exception either (filter accepts boolean parameters, and hence javascript's type system hides the bug). Perhaps modifying filter to fail hard when passed a badly typed value like this should be a separate bug.

EXECUTABLE EXAMPLE SHOWING FAILURE

```javascript
var r = require("rethinkdb"),
    Promise = require("bluebird");

var dbName = "tmp3948";

r.connect({
        host:"localhost",
        port:28015
    })
    .then(function(conn){
        return Promise.resolve()
            .then(function(){
                return r.dbDrop(dbName).run(conn).catch(function(){
                    //do nothing - table didn't exist
                });
            })
            .then(function(){
                return r.dbCreate(dbName).run(conn);
            })
            .then(function(){
                return conn.use(dbName);
            })
            .then(function(){
                return r.tableCreate("users").run(conn);
            })
            .then(function(){
                var userRecord = {
                    embedded_doc:{
                        child:10,
                    },
                };
                return r.table("users").insert(userRecord).run(conn);
            })
            .then(function(){

                //this invocation (direct from the documentation at https://rethinkdb.com/api/javascript/row/ ) doesn't select the record and is flawed, but unfortunately doesn't throw an exception - could it?
                return r.table('users').filter(r.row('embedded_doc')('child') > 5).run(conn)

                //the invocation below works to select the record
                //return r.table('users').filter(r.row('embedded_doc')('child').gt(5)).run(conn);

            })
            .then(function(result){
                return result.toArray();
            })
            .then(function(arr){
                console.log(JSON.stringify(arr));
            });
    })
```

**Comment by danielmewes** [comment]
Thanks for the report @cefn, and sorry for the confusion. You are completely right of course, and the example should use `gt`. Unfortunately it's hard to detect such mistakes in the JavaScript driver (it's not really an issue of `filter`, but of how anonymous functions are processed within the driver).

I opened https://github.com/rethinkdb/docs/issues/1090 on the issue tracker for our documentation. We'll follow up over there.

**Comment by cefn** [comment]
The reason I was saying filter should throw an error; I believed that ```filter(true)``` and ```filter(false)``` were ALWAYS a bug as there is no circumstances under which they could ever actually be used.

**Comment by danielmewes** [comment]
@cefn I see, that's a fair point. There might still be valid use cases for a constant filter function, especially when filter criteria are assembled dynamically at runtime in the application (e.g. if a variable number of criteria need to be combined).
I added a note to https://github.com/rethinkdb/rethinkdb/issues/5602 describing your idea, which is probably the context in which we'd want to do this check.

**Comment by cefn** [comment]
I'm not sure I follow, since it strikes me that any case of filter(true) and filter(false) even where some complex conditional is being assessed, could be entirely substituted by an if clause and an assignment. 

If true, the query specification is the complex clause, if false, the query specification is the empty sequence.

There are in-principle edge cases where javascript dynamic typing might return either true or an Object, (hence implicitly using the different forms of overloading offered by filter), but these should probably not be encouraged by the API from a code-style point of view.

If you feel that query filtering really should be able to handle the boolean case, you could introduce a threatening looking error message to filter with a get-out, like asking authors to...
* wrap the boolean value in r.literal()
* force filter 'conditions' to return the explicit values r.true(), r.false() or r.boolean(condition)
* introduce a boolean-specific filter operation like allOrNone()

**Comment by danielmewes** [comment]
@cefn I was thinking of code like this, which I have seen many times: (pseudo code)
```
// user input: conditions: {field1: value1, field2: value2:, ...}
filter = r.expr(true);
for each (field, value) in conditions:
  filter = filter.and(r.row(field).eq(value));
result = r.table("t").filter(filter).run(conn);
```

This will perform a constant filter whenever `conditions` is empty. Requiring users to special-case this makes such code harder to write, and easier to break if they forget to test or think about the empty case.

**Comment by cefn** [comment]
Your pseudo-code example looks like quality code which actually guards from passing booleans directly into filter. 

I don't see any point in this where a javascript value where value===true or value===false is being used as an argument to the filter call, meaning that this code can still run even if guard behaviours are added to filter() which throw an exception when passed a primitive value directly (which I claim is always a mistake).

Sorry if I've missed something.

Perhaps you mean that r.expr(...) needs to accept locally evaluated javascript primitives, which is an explicit use case for r.expr(...) anyway, so this seems correct, but still allows you to throw an exception when someone passes an unguarded item which evaluates to a primitive without wrapping it in an expr, e.g. writing...
```javascript
r.table('users').filter(r.row('embedded_doc')('child') > 5).run(conn, callback)
```
...when they mean... 
```javascript
 r.table('users').filter(function(){
return r.row('embedded_doc')('child') > 5
}).run(conn, callback)
```
...actually as I write this, I'm asking myself if that's a valid filter function, or whether it re-introduces the same bug. As a newbie, having it die explicitly to tell me it's broken would be useful.

I am really new to rethinkdb, and haven't got a lot of time today for testing, but can't your example be written as follows with all the goodness of returning a constant filter...
```javascript
// user input: conditions: {field1: value1, field2: value2:, ...}
query = r.table("t");
for each (field, value) in conditions:
  query = query.filter(r.row(field).eq(value));
result = query.run(conn);
```

**Comment by cefn** [comment]
OK, I think I've figured out that r.expr() actually is never intended to handle an expression (as I understood from its name), but always performs the role of my suggested r.const(), so forget about that bit. 

However, as per the last post I am still struggling to find examples where locally-evaluated primitives should be passed in to filter() without an r.expr() wrap, and I personally would prefer a name like r.const() or r.value() since expr suggests expression evaluation (which is not intended, since in fact a locally evaluated javascript value is always expected to be passed).

**Comment by danielmewes** [comment]
@cefn My point was merely that if we made `filter` queries fail with an error if they are passed a function that returns a constant `true` or `false`, that would break certain useful code patterns. The one I described in pseudo-code is such an example.

The error would get triggered there if `conditions` is empty. The developer would have to write additional code to omit the `filter` in that case, or to add some `r.literal` wrapper around the `true` or something like that. So I think looking at whether the function is constant or not is not the right way to detect accidental use of the JavaScript operators. It would also be an incomplete check, as something like `filter(r.row('field').match("test").and(r.row('field') > 5))` would *not* result in a constant function (it would result in something like `function() { return r.row('field').match("test").and(true); }`).

As mentioned, it sounds like it could be a good heuristic though for detecting some common cases of operator use in the context of https://github.com/rethinkdb/rethinkdb/issues/5602 (i.e. providing a warning in the Data Explorer, rather than a full query error).

On a side note:
`r.expr` is called that way because it turns a native value into a "ReQL expression" by the way. If you pass any value from your client language into a ReQL term, this step is performed implicitly and you don't need `r.expr`. For example `r.add(1, 2)` will just work.
But if you want to start out with a value and then call a ReQL function on it, you need to use `r.expr` explicitly to convert the value into a ReQL expression object. For example `1.add(2)` wouldn't work, but you'd need to do `r.expr(1).add(2)` since `add` is a function that's only defined on ReQL expressions.
The RethinkDB server never sees the `r.expr`. From its point of view, *every* value is a ReQL expression, no matter whether `r.expr` was used on the client to generate it or whether it was implicitly transformed to a ReQL expression by passing it as an argument to one of the ReQL functions.
I hope that makes this clearer.
