### ISSUE TITLE
Allow secondary index for leftHand field of eqJoin

### ISSUE THREAD

**Issue by NeilHanlon** [rethinkdb/rethinkdb#5689]
This came up in slack:

```js
r.db('test').tableCreate('tableLeft')
r.db('test').tableCreate('tableRight')
r.db('test').table('tableLeft').insert({'key_one':'11', 'key_two':'22'}) 
r.db('test').table('tableRight').insert({'key_one':'11', 'key_two':'22'})  
r.db('test').table('tableLeft').indexCreate('table_key', [r.row('key_one'),r.row('key_two')])
r.db('test').table('tableRight').indexCreate('table_key', [r.row('key_one'),r.row('key_two')])
r.db('test').table('tableLeft').eqJoin('table_key', r.db('test').table('tableRight') , {index:'table_key'})
```

Doesn't work, as table_key is an index on both tables, not a key. The proposed solution is:

```js
r.table('tableLeft').eqJoin((row) => [row('key_one'), row('key_two')], r.table('tableRight'), {index: "table_key"});
```

However this solution probably isn't very good for performance.

Is there any reason an index can't be the left hand of a join? Is it unnecessarily complex to do this?

Just a suggestion :)

**Comment by barkerja** [comment]
```javascript
r.db('test').table('tableLeft').eqJoin(
  function(tableLeft) {
    return [tableLeft('key_one'), tableLeft('key_two')
  },
  r.db('test').table('tableRight'),
  { index: 'table_key' }
)
```

Apologies if my JS is a little off, but you need to use a function to construct the compound key.

**Comment by barkerja** [comment]
Or you can do something to the effect of:

```javascript
// First filter by specific values, then join other table
r.db('test').table('tableLeft').getAll(['a', 'b'], { index: 'table_key'}).eqJoin(
  function(tableLeft) {
    return [tableLeft('key_one'), tableLeft('key_two')
  },
  r.db('test').table('tableRight'),
  { index: 'table_key' }
)
```

**Comment by NeilHanlon** [comment]
`(row) => [...]` is a JS shortcut in ES7 (I think). It's an implicit return.

And yes--that's one way to do it, but if you're always going to join both tables together... then it's not an indexed operation on the left hand side.

**Comment by danielmewes** [comment]
Thanks for opening the issue here @NeilHanlon .

I think using the index on the left table wouldn't make any significant difference for performance. The only difference would be that we could theoretically extract the value of `(row) => [row('key_one'), row('key_two')]` from the index rather than re-evaluating that function for every row from the left table. However that's not always possible the way indexes are stored, and evaluating that function is very cheap anyway.

Or am I misunderstanding something? Is there another way in which we could utilize the index on the left table in addition to the one on the right table?

**Comment by NeilHanlon** [comment]
Thanks @danielmewes 

Yeah that makes sense. @barkerja and I talked for a bit on Slack earlier about the issue and basically determined that `join`ing on an index on the left hand side has no real effect since as he mentions above, you can `getAll` on the index and then join based on that data.

The issue was for @edwardsmarkf and to see if this was something reql needed or not.

Sounds like not. ;)

If we're all satisfied I'd say we can close this.

**Comment by danielmewes** [comment]
Closing as discussed. We can re-open the issue if we come up with anything that makes this worth revisiting.
