### ISSUE TITLE
Fix rethinkdb-dump on Python 3

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5694]
A similar issue as https://github.com/rethinkdb/rethinkdb/issues/5647 appears to exist for `rethinkdb dump`: https://github.com/rethinkdb/rethinkdb/issues/5505#issuecomment-211562672

Assigning to @larkost since you reviewed the equivalent fix for `rethinkdb restore` https://github.com/rethinkdb/rethinkdb/pull/5648 .

**Comment by NeilHanlon** [comment]
Since I worked on #5647 

What do you think about doing 

`is_fileobj = hasattr(options["out_file"], 'read')`

instead of making unnecessarily complex code to work with both Python 3 and Python 2? Since in Python 3, you'd have to do `isinstance(options["out_file"], io.IOBase)` --but that'd fail in Python 2.

I think it's still readable and gets the point across.

**Comment by danielmewes** [comment]
Pinging @larkost about that. My understanding of this is too shallow to tell whether that could have any disadvantages or not.

**Comment by larkost** [comment]
@NeilHanlon: ya, that is a good way to handle this. I have a version with that and some other changes (making it Python2.6 compatible) that I will have reviewed tomorrow morning.

**Comment by larkost** [comment]
Testing this is actually quite a pain, so the decision has been made to complete #5147 to make this a lot easier. I am working on that now, and will probably fold this into that.

**Comment by danielmewes** [comment]
I'm moving this out of 2.3.1 since it might take a few days longer as far as I understand.
We can easily ship a Python driver update separately after 2.3.1.

**Comment by larkost** [comment]
The work on this is probably complete, but I want to test more before declaring it done (mostly on non MacOS computers). This work is in branch `larkost/5147-python-driver-utils`. I anticipate it will be complete early next week.

**Comment by larkost** [comment]
This has been merged into `next` with df57248c after CR 3608 from branch `larkost/5147-python-driver-utils`.
