### ISSUE TITLE
`eqJoin` on changefeed causes infinite loop

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5696]
Running this query on an empty table `t1`:
```js
r.table('t1').changes().eqJoin('id', r.table('t1'))
```

causes the server to use 100% of one CPU core. The query never returns the initial cursor, and the server can no longer be shut down. It has to be killed with SIGKILL.

This bug was reported by ordishs on Slack.

**Comment by nighelles** [comment]
Could this be caused by trusting the batchspec from the input side?

**Comment by danielmewes** [comment]
@nighelles No I think we just need to handle empty batches in the eq_join_datum_stream_t.
I have a three-line fix that appears to work. Do you want it for code review or should I give it to @mlucy?

**Comment by nighelles** [comment]
I can review it, but I don't know how to get on code reviewer outside the office

**Comment by danielmewes** [comment]
The patch was merged into v2.3.x c98fe45 and next b70434f and will ship with RethinkDB 2.3.1.
