### ISSUE TITLE
Ubuntu 16.04 (Xenial Xerus) packages

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5697]
I mostly have this working... We should ship these with 2.3.1.

**Comment by danielmewes** [comment]
Packages will be available later this week starting with 2.3.1.

**Comment by smhg** [comment]
There aren't any xenial directories on http://download.rethinkdb.com/apt/ yet. Am I too early?
Thanks for your efforts!

**Comment by Wargog** [comment]
The releases were delayed until Monday, but the packages are ready for release

**Comment by mofax** [comment]
it's Monday :-(

**Comment by danielmewes** [comment]
@mofax Since RethinkDB HQ is located in UTC-7, Monday is a bit later here. :-D

The packages are uploading right now though, and will become available in about an hour.

**Comment by danielmewes** [comment]
@mofax @smhg The packages should now be available.

**Comment by smhg** [comment]
Thanks, apt-get just upgraded rethinkdb!

Got this warning though:
``
W: http://download.rethinkdb.com/apt/dists/xenial/Release.gpg: Signature by key 1614552E5765227AEC39EFCFA7E00EF33A8F2399 uses weak digest algorithm (SHA1)
``
But I'll open a new issue after investigation.
