### ISSUE TITLE
update the version on MacPorts

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5703]
We submit updates to the `brew` recipe for RethinkDB, but it looks like no one has been submitting updates to [MacPorts](https://www.macports.org/ports.php?by=name&substr=rethinkdb) (currently at 1.11.1). We should probably pick that up.

**Comment by danielmewes** [comment]
I would prefer not adding an extra step to our release process at the moment unless more people start asking for this.

**Comment by gabor-boros** [comment]
MacPorts has no RethinkDB package anymore. Closing.
