### ISSUE TITLE
`rethinkdb dump` potentially broken

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5705]
Opening an issue for book-keeping purposes.
@larkost mentioned that `rethinkdb dump` might be broken and create empty files even when there is data in the table(s).

In a quick test it seemed to work in the currently released 2.3.0 version, so this is hopefully just a regression since 2.3.0 (or maybe it's broken on some platforms?).

**Comment by larkost** [comment]
It might also something I have caused in working on #5147, I am trying to work my way through the process now to find out where it has broken down.

**Comment by larkost** [comment]
It was something I caused in development, and this was never checked in so I am closing this.
