### ISSUE TITLE
make gevent and twisted tests only run on valid Python versions

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5710]
`gevent` and `twisted` do not run on Python 3.0-3.1.x, so we should exclude those tests from those versions of the interpreters. Currently we only have the ability to choose specific versions (multiple), so need to introduce the ability to do something like:
`connections/twisted_connection.py2.7-,3.2+.test`
That is not the prettiest of names, but it wold get the job done, and we already support the comma in the middle, so this would only be adding the `+` and `-` to the equation.

**Comment by encryptio** [comment]
Here's a bikeshed color for you:

How about only adding `-` and using it for "inclusive range", meaning this test would have a `-py2.7,py3.2-` specifier? This removes the `+`, and IMO, reads better.

**Comment by larkost** [comment]
This was done under #4139, and that uses the `+` either in prefix or suffix to denote starting or ending ranges.
