### ISSUE TITLE
returnChanges and conflict=null throw an error on delete

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#5713]
This query fails one every two runs (it insert the document, then delete it and return an error)

```
r.db('test').table('test').insert(
  {id: 1},
  {
    conflict: function(x,y,z) { return null},
    returnChanges: true
  })
```

The error being:
```
e: Expected type OBJECT but found NULL in:
r.db("test").table("test").insert({"id": 1}, {"conflict": function(var_88, var_89, var_90) { return null; }, "returnChanges": true})
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by danielmewes** [comment]
Thanks for opening the issue here @neumino .

@nighelles, @neumino 
Is the issue that deleting a value by returning `null` from the insert conflict resolution function generally throws an error?

**Comment by nighelles** [comment]
It looks like that's the issue, I'm trying to track down what's causing the error to confirm.

**Comment by neumino** [comment]
From my tests the problem is returning the changes when I delete a document
using insert.

**Comment by nighelles** [comment]
A fix for this is in review 5713, implemented in nighelles/5713

**Comment by nighelles** [comment]
This is in next.
