### ISSUE TITLE
Building rethinkdb from git repo on OS X el capitan

### ISSUE THREAD

**Issue by javierso** [rethinkdb/rethinkdb#5714]
I am trying to build rethinkdb from the git repo on branch next on my somewhat new laptop with runs OS X el capitan. I keep getting the following error when trying to build external dependencies

[1/421] BUILD admin-deps_2.0.3
```
npm ERR! argv "/usr/local/Cellar/node/5.8.0/bin/node" "/usr/local/bin/npm" "--userconfig" "/Users/javier/dev/src/C++/rethinkdb/mk/support/config/npm.conf" "--cache" "/Users/javier/dev/src/C++/rethinkdb/external/npm_cache-1GtqZmG3" "--no-registry" "install" "/Users/javier/dev/src/C++/rethinkdb/external/admin-deps_2.0.3"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.6

npm ERR! registry URL is required
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.8.0/bin/node" "/usr/local/bin/npm" "--userconfig" "/Users/javier/dev/src/C++/rethinkdb/mk/support/config/npm.conf" "--cache" "/Users/javier/dev/src/C++/rethinkdb/external/npm_cache-1GtqZmG3" "--no-registry" "install" "/Users/javier/dev/src/C++/rethinkdb/external/admin-deps_2.0.3"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.6

npm ERR! registry URL is required
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/javier/dev/src/C++/rethinkdb/build/external/admin-deps_2.0.3/npm-debug.log

Full error log: ./build/external/admin-deps_2.0.3_install.log
make[1]: *** [build/external/admin-deps_2.0.3/bin/gulp] Error 1
make: *** [make] Error 2
```
It seems pretty clear to me that the issue reside on npm , but i am not sure how to proceed from here? Has anybody run into similar problem on OS X el capitan. BTW, Im running npm version 3.8.6

**Comment by danielmewes** [comment]
@javisan88 Can you try using `./configure --fetch npm --allow-fetch` and then run `make` again?

**Comment by javisan88** [comment]
daniel thanks for the help that did help. In addition to that I had to refer #5699 for linkage errors related to openssl dynamic libraries. However, does this mean the build relies on a particular version on npm and if so shouldn't fetching npm be part of the default behavior?

**Comment by danielmewes** [comment]
@javierso Not really a particular version, but support for newer versions of NPM is currently broken. That issue is tracked in https://github.com/rethinkdb/rethinkdb/issues/5230 and there's actually a pull request now to address the issue https://github.com/rethinkdb/rethinkdb/pull/5698 .
