### ISSUE TITLE
Crash causing corrupt database

### ISSUE THREAD

**Issue by jrote1** [rethinkdb/rethinkdb#5719]
I am getting the following message appear in command prompt which seems to be killing the rethinkdb server. `rethinkdb: Memory allocation failed. This usually means that we have run out of RAM. Aborting.`

The issue that is more worrying is that after this crash my data file has been corrupt. I get the following error when starting rethinkdb `error: This doesn't appear to be a RethinkDB data file.` 

As a side note is there anyway for me to recover this data from the file?

**Comment by danielmewes** [comment]
Thanks for the report @jrote1 and sorry you had to run into this. I'm surprised that an out-of-memory condition would corrupt the data file, so we should investigate this.

Can you send us a copy of the data directory (`rethinkdb_data` or a folder in `/var/lib/rethinkdb` by default)? If yes, I can give you access to our upload server so you can upload the data securely and without size limitations. We can also sign an NDA if the data is confidential.

The data would help is to investigate the type of the corruption, and potentially allow us to recover the data as well though I cannot promise that this is going to be possible.

What system are you running RethinkDB on? Operating system, hardware, disks, any virtualization?

**Comment by jrote1** [comment]
@danielmewes 

We are using windows so am aware that its not production ready to are not to concerned about the data loss. But thought this issue should definitely be fixed. There is confidential information so we would want to get an NDA signed before uploading the data.

With our use case we are seeing sustained writes of about 350 a second and this failure is quite consistent as it is the third time this has happened. 

We are running on:
Windows Server 2016
6GB RAM
4 Core 3.2GHz
Running VMWare ESXi

**Comment by danielmewes** [comment]
Thanks @jrote1, that's very helpful information.
This sounds like we're using a 32 bit offset somewhere in the Windows port and it overflows when the file grows over ~4 GB, thereby either truncating the file or overwriting the beginning of it.

I think we can investigate this without the data for now, though we might need it later.

**Comment by jrote1** [comment]
@danielmewes ok if you do need any data then let me know. Just out of curiosity is there normally a limit for database size?

**Comment by danielmewes** [comment]
@jrote1 Normally we use 64 bit integers for all file offsets, so the limit would be 8,192 PiB (pebibyte). 

The limiting factor will usually be the amount of available RAM, since you typically need about 1% of the total data size in RAM for some internal index structures with RethinkDB.

**Comment by nighelles** [comment]
This should be fixed in next.

**Comment by danielmewes** [comment]
@nighelles I think you closed the wrong issue

**Comment by danielmewes** [comment]
... @jrote1 We think we have found the bug btw and are testing a fix at the moment.

**Comment by danielmewes** [comment]
This is fixed by ab8349b388755ff26c3ffa8bca704dbc604443c8 .
The fix will be included in the upcoming 2.3.2-windows-beta release.

Thanks again for reporting this @jrote1 .

**Comment by jrote1** [comment]
@danielmewes Thanks for the quick fix I am looking forward to next release as this is a big issue for me
