### ISSUE TITLE
Table data deleted down to 7k documents but disk space still not reduced

### ISSUE THREAD

**Issue by ntquyen** [rethinkdb/rethinkdb#5726]
I'm using rethinkdb cluster version 2.2.5. One of my tables was containing millions of documents taking more than 100Gb of disk space. But after I deleted the data down to 7k documents, I don't see the disk space reduce, it is still taking more than 100Gb for that table. From the admin UI, the total disk used shows only 62 GB, much less than the actual table size stored on disk. Is that normal or am I missing some configuration?

**Comment by danielmewes** [comment]
This has come up on our Google groups mailing list a few times, e.g.:
https://groups.google.com/forum/#!topic/rethinkdb/jgJid-IlzEA
https://groups.google.com/forum/#!topic/rethinkdb/_i7ceE17ro0

I'm going to open an issue about adding a FAQ entry to our docs on this, as the question is coming up quite frequently at this point.
