### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/rethinkdb/RethinkDB : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by ganySri** [rethinkdb/rethinkdb#5730]
Getting this exception on trying to connect with JavaAPI 
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

Will it not work with JAVA 7.

**Comment by bchavez** [comment]
If I recall correctly, the minimum **Java** version is `Java 8 / 1.8`.

**Comment by deontologician** [comment]
Hey @ganySri, as @bchavez said, our minimum version is Java 8 right now. If you want to follow the Java 7 support issue, check out #5266 

I'm going to close this, but feel free to ask more questions here (or in #5266)
