### ISSUE TITLE
issues connecting with TLS from Python on MacOS

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5734]
I am getting an error when trying to connect to a server while using TLS:
```SSL handshake failed: EOF occurred in violation of protocol (_ssl.c:590)```

On the server side I am getting:
```warn: Driver connection TLS handshake failed: 336027900 - error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol```

This is coming up while working on #4815, so there could be something I am doing there, but some tests from the `next` driver seem to exclude this.

**Comment by larkost** [comment]
@danielmewes and I discovered that this is probably because we only allow `TLS1.2`, and the version of OpenSSL that is on MacOS (0.9.8zh) does not have support for that protocol (introduced in 1.0.1). This means that all of the languages on MacOS (e.g. Python and Ruby), and anything compiled against the built-in OpenSSL, will not work when connecting with TLS.

**Comment by larkost** [comment]
I think that the solution is that we are going to add a parameter to the server to allow for `TLS1.0` connections, which would enable connections from MacOS (and other systems with older OpenSSL libraries).

That will take care of making this possible, however I think we should also improve the error message that gets returned to the client to make this more understandable to users who run into it.

**Comment by danielmewes** [comment]
A new `--tls-min-protocol` option together with improved server log messages is in code review 3618, branch daniel_5734.

To make connecting from OpenSSL 0.9.8 work, the following recommended options should be passed to the server:
```
--tls-min-protocol TLSv1 --tls-ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:AES256-SHA
```

**Comment by danielmewes** [comment]
The new option is in v2.3.x adcedca and next 0932771.
