### ISSUE TITLE
Bug: rethinkdb.errors.ReqlDriverError: Could not connect to localhost:28015. Error: can't concat bytes to str

### ISSUE THREAD

**Issue by saadqc** [rethinkdb/rethinkdb#5742]
Python 3.3.x casting issue, net.py line 335. 
It throws error while concatenating bytes to string.

**Comment by nighelles** [comment]
Hey @saadqc ,

Can you tell me what you were doing when you saw this error? Is there a particular query you were trying to run?

**Comment by saadqc** [comment]
@nighelles Thank your for the quick response.

I am trying to pass tests of APScheduler. 

https://travis-ci.org/agronholm/apscheduler/jobs/127494324

it uses rethinkdb for testing. It works fine for all other python versions see https://travis-ci.org/agronholm/apscheduler/builds/127494322

but crashes on python 3.3.

As the line says, it just tries to create a connection string to connect rethink db server.

Hope that explains well.

**Comment by nighelles** [comment]
Ok, I merged your PR, but it looks like there were further issues with some of the logic in python 2.3.

These other issues should be fixed by 7b61ba in next.

**Comment by nighelles** [comment]
Cherry-picked into v2.3.x in 925c7c9 and ab4c167

**Comment by saadqc** [comment]
@nighelles Thank You!
