### ISSUE TITLE
apt warns about weak signature key

### ISSUE THREAD

**Issue by smhg** [rethinkdb/rethinkdb#5751]
When running `apt-get update` with apt versions 1.2.7 and above (Debian Unstable and Ubuntu 16.04), you get a warning if you're using the RethinkDB repo:

```bash
W: http://download.rethinkdb.com/apt/dists/xenial/Release.gpg: Signature by key 1614552E5765227AEC39EFCFA7E00EF33A8F2399 uses weak digest algorithm (SHA1)
```

The solution is mentioned at the bottom of this page:
https://wiki.debian.org/Teams/Apt/Sha1Removal
See section _Fixing **half-broken** repositories_.

**Comment by danielmewes** [comment]
Thanks for bringing this up @smhg . We'll look into it.

**Comment by danielmewes** [comment]
We're currently using freight to build our repositories. It looks like this is addressed in the more recent releases, so we just need to upgrade our internal tools. 

https://github.com/freight-team/freight/pull/22

**Comment by danielmewes** [comment]
I updates our freight installation. We're going to update our repositories for the RethinkDB 2.3.3 bug fix release, which should address this issue.

**Comment by smhg** [comment]
Apt didn't complain anymore for a while now. Thanks a lot!

**Comment by danielmewes** [comment]
We haven't uploaded the new repository metadata yet. I suspect it might only warn when the repository data changes. The better signed one should go online tomorrow though.
