### ISSUE TITLE
Minor change required in the message when single table is deleted

### ISSUE THREAD

**Issue by dineyw23** [rethinkdb/rethinkdb#5753]
When user deletes single table from database, message should have singular `table` but has `tables`. Needs changes in `admin/static/coffee/modals.coffee`. 

![minorerrorweb](https://cloud.githubusercontent.com/assets/10092343/15104217/d14c17f0-1569-11e6-91f3-9cde2d7d0a22.png)

When user adds a single table, the message is proper.

**Comment by danielmewes** [comment]
Thanks for reporting this @dineyw23 .
Since I was already looking at the file, I just went ahead and fixed it (change reviewed by @nighelles). This will ship with RethinkDB 2.3.3 or 2.4.0, whichever comes first.
