### ISSUE TITLE
Expose the Connection class from net.coffee (javascript driver)

### ISSUE THREAD

**Issue by gergelyke** [rethinkdb/rethinkdb#5758]
Hey,

we are building [Trace](https://trace.risingstack.com/), a Node.js monitoring platform.

For that, we'd like to instrument rethinkdb as well. We would need to access the Connection class from the `net` module. Is it something you would accept a PR for?

The change would be only this:

```javascript
// net.coffee

module.exports.Connection = Connection
```

```javascript
// rethinkdb.coffee

module.exports.net = net
```

Thanks,
Gergely

**Comment by deontologician** [comment]
Do you need the connection class itself? We have a connection factory method that's exposed (`r.connect`)

**Comment by gergelyke** [comment]
We can hook into that as well - that may be more complex to maintain down the road. The plan is to wrap the `_start` method of the `Connection` class.

If  you think there is a better way, I'd like to hear that :)

**Comment by danielmewes** [comment]
Could you monkey-patch the `_start` method after getting the `Connection` object from `r.connect`?

I'm not opposed to exposing the `Connection` class. Just wondering how much easier it actually makes the modification.

**Comment by gergelyke** [comment]
As a reference, you could take a look here:

The current mysql instrumentation looks this:
https://github.com/RisingStack/trace-nodejs/blob/master/lib/instrumentations/mysql.js#L49 - as we don't have access to the prototype, we had to it this way, and overwrite the connection factory. Currently, we would do something similar here as well.

On the other hand: https://github.com/RisingStack/trace-nodejs/blob/master/lib/instrumentations/mongodb.js - as mongodb exposes the prototype as well, it is really just wrapping that method, without have to modify the factory itself

**Comment by danielmewes** [comment]
Ok, unless anyone else has any concerns, I think we should do this.

@gergelyke Would you be willing to open a pull request with the necessary changes? (note that we have a Contributor License Agreement: http://rethinkdb.com/community/cla/ )

**Comment by gergelyke** [comment]
Great, thanks @danielmewes! 

Sure, happy to send one - so if I am right, I just have to fill it out, accept it, and that's it. Right?

**Comment by danielmewes** [comment]
@gergelyke
> Sure, happy to send one - so if I am right, I just have to fill it out, accept it, and that's it. Right?

Yep, that's all that's required as far as the CLA is concerned.

Thanks for contributing!

**Comment by danielmewes** [comment]
This was closed via https://github.com/rethinkdb/rethinkdb/pull/5759
