### ISSUE TITLE
Cpanel + Cloudlinux

### ISSUE THREAD

**Issue by jarodium** [rethinkdb/rethinkdb#5765]
Hello

I was wondering if anyone has ever tried to install RethinkDB in Cpanel with Cloudlinux ( CageFS ) addon. I believe this is possible but I would like to know if someone has already done this.

Thank you.

**Comment by danielmewes** [comment]
Hi @jarodium. The mailing list https://groups.google.com/forum/#!forum/rethinkdb or our Slack channel http://slack.rethinkdb.com would be a better place for this question.

Closing since it's not an issue we can work on.
