### ISSUE TITLE
Reading from RethinkDB fails due to unavailable primary replica for shard

### ISSUE THREAD

**Issue by aknuds1** [rethinkdb/rethinkdb#5766]
What's causing the following error? I'm running RethinkDB 2.3.0 in Google Container Engine/Docker, with a persistent volume mounted. The cluster consists of only one instance.

    Cannot perform read: primary replica for shard ["", +inf) not available in:
    r.table("users").get("aknudsen").merge(function(var_6) { return {"projects": r.table("projects").getAll("aknudsen", {"index": "owner"}).coerceTo("array")}; })

**Comment by aknuds1** [comment]
After upgrading the Docker container to RethinkDB 2.3.2, I have started getting this error instead:

``ReqlOpFailedError: Database `muzhack` is ambiguous; there are multiple databases with that name```

**Comment by danielmewes** [comment]
@aknuds1 Do you have access to the web UI? That will give you more information on what's wrong.

Alternatively you can take a look at `r.db('rethinkdb').table('current_issues')`.

For resolving the database name conflict, either go to the web UI and use the "rename" link in the issue that pops up at the top of the screen. Alternatively, check out `r.db('rethinkdb').table('db_config').filter({name: "muzhack"})`. This should give you the two conflicting databases. You can then run `r.db('rethinkdb').table('db_config').get(<id of one of them>).update({name: "muzhack_2"})` to rename one of them.

**Comment by danielmewes** [comment]
'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Arve KnudsenSent: Monday, May 16, 2016 8:50 AMTo: rethinkdb/rethinkdbReply To: rethinkdb/rethinkdbSubject: Re: [rethinkdb/rethinkdb] Reading from RethinkDB fails due to unavailable primary replica for shard (#5766)After upgrading the Docker container to RethinkDB 2.3.2, I have started getting this error instead:

ReqlOpFailedError: Database `muzhack` is ambiguous; there are multiple databases with that name`

—You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub

**Comment by aknuds1** [comment]
@danielmewes Yeah I am able to connect to the Web UI.

I renamed the conflicting databases (the muzhack database had two duplicates and test had 4). The remaining problem now is that my tables are without shards/replicas. What am I to do about this? I have no idea what's causing it even.

**Comment by danielmewes** [comment]
@aknuds1 That means that the server that was originally hosting those tables either isn't connected, or isn't there anymore.
How are you starting RethinkDB in GCE? Are you sure they are using the persistent volume correctly?

Duplicate databases (especially when it comes to the `test` database) are a strong indication that you somehow have multiple RethinkDB servers running that for some reason got connected to each other at some point.

**Comment by aknuds1** [comment]
@danielmewes Turns out there are two RethinkDB servers running, one of which is for serving the admin UI. It's a Kubernetes setup I just copied, so not sure what the intention is behind it. The normal RethinkDB server is using a persistent volume, whereas the admin server is just using ephemeral storage. Not sure how they are able to work with each other.

## The admin Kubernetes pod definition:

**Comment by danielmewes** [comment]
That's an odd setup. Where did you get this the Kubernetes setup from?

I suspect that the admin pod without persistent storage is responsible for your issues. I suspect that when you first created some of the tables, the replicas were placed on the admin pod (RethinkDB tries to evenly distribute replicas across all servers). Unfortunately it looks like that data might now be lost. :-(

**Comment by aknuds1** [comment]
Now I can't remember where I found the setup, but it was by a Kubernetes team member IIRC. I am wondering about the point of the admin pod myself. Am experimenting now with dropping it and instead pointing the admin service at the normal (non-admin) deployment.

**Comment by aknuds1** [comment]
It's no big deal though if the data is gone, since it's just a test setup.

**Comment by danielmewes** [comment]
Maybe the admin pod was supposed to run a `rethinkdb proxy` instance. That would have made more sense, but apparently it's not fully configured for actually doing that.

A RethinkDB proxy doesn't hold any data, so it's ok for it to use ephemeral storage. Running it as a regular server node on such storage is a recipe for disaster though.

**Comment by danielmewes** [comment]
I think dropping the separate admin deployment is the sanest option.

**Comment by aknuds1** [comment]
@danielmewes That's what I'm going with too :) No idea what was the purpose of it in the first place...

**Comment by aknuds1** [comment]
I guess we can close the issue now @danielmewes, as it was probably caused by the second server.
