### ISSUE TITLE
How can I solve "partial connectivity"?

### ISSUE THREAD

**Issue by jindragon** [rethinkdb/rethinkdb#5770]
I'm using 3 different physical machines.

At first machine, I entered "rethinkdb --bind all"
Other machines, I entered 
"rethinkdb —directory ~/mydirectory/ —join [server IP]:[port] —bind all

![image](https://cloud.githubusercontent.com/assets/16792324/15311120/8a63f2b6-1c32-11e6-8785-27df6469b7a8.png)

But they are not fully connected.
How can I fix it?

p.s. I'm using rethinkdb with BigchainDB.

**Comment by larkost** [comment]
Typically this is because there are firewalls between your servers that are preventing connections from being opened in both directions. Does that sound like the case in your setup? If not, can you share more information about who these machines are connected?

--
	Karl Kuehn
	Automation Engineer
	karl@rethinkdb.com

**Comment by artdude543** [comment]
I'm getting the same issue on a new cluster setup of which I did not have on my old cluster setup. I use Scaleway for the servers and have the master which has an external IP and the other machines use the internal DNS to connect to the master. The proxy then uses the main IP to connect.

On our old setup which worked fine with no issues. On the server stats the main server shows as connected to the proxy but the "sub" servers show as not connected to the proxy.

Not really sure how to fix this due to not having the issue before hand.

**Comment by danielmewes** [comment]
@artdude543 Note that this issue wasn't detected / displayed before RethinkDB 2.3. So the issue might have been there, but you wouldn't have noticed it under certain circumstances (though the proxies would still be unable to reach any primaries on the non-connected servers).

Are queries actually failing now?

In general the proxy needs to be able to connect to all servers in the cluster, not just one. If the Scaleway configuration exposes only a single IP and the other servers' IPs aren't accessible from the proxies, that setup cannot work. It might work in practice as long as all primary replicas are on the server that the proxies can reach, but queries run through the proxy will fail as soon as that's no longer the case (e.g. in case of a failover).

**Comment by artdude543** [comment]
As far as I know the queries were working but we had the error on the panel about the servers not being connected to each other.

I'm assuming I'll need to add external IP's to the other servers? I moved to Scalway to cut down on costs such as IP's but nothing major if it's needed. I thought using the internal network would be sufficient. Unless I'm missing something with the config on the proxy / cluster.

**Comment by artdude543** [comment]
Just tested and the proxy queries are passed through even tho the panel is complaining about connections.

If you wanted I could share screen or something to allow you to poke at it or see the setup easier? It's still a dev database so nothing really on it at the moment.

**Comment by danielmewes** [comment]
As mentioned things will work as long as the proxy is connected to the server that is a primary for all replicas. Once you shard the tables or an automatic failover happens queries run through the proxy will no longer work.

The RethinkDB cluster connectivity architecture just doesn't currently support setups like this. Every server and every proxy node must be able to connect directly to each other to establish full connectivity.

**Comment by danielmewes** [comment]
@jindragon Have you been able to resolve the issue?

**Comment by jindragon** [comment]
Sorry for not mentioning my result.
I noticed that I opened a port just one direction.
So on other machines, I opened port, both direction.
So I solved the problem!
Thank you man~ ^-'

**Comment by danielmewes** [comment]
Cool, I think in both cases RethinkDB is working as expected then.

@artdude543 we're happy to discuss alternative setups with you or check which configuration changes are necessary to get things up with Scaleway. This would fall into the range of our commercial support offerings though. Please contact us via http://rethinkdb.com/services/ or drop me an email to daniel@rethinkdb.com if you'd like to explore that option.
Alternatively someone might be able to give you some pointers in our Slack channel. You can easily sign up for it at http://slack.rethinkdb.com/ .
