### ISSUE TITLE
Upgrade CodeMirror

### ISSUE THREAD

**Issue by danielcompton** [rethinkdb/rethinkdb#5777]
Newer versions of CodeMirror include `field.setAttribute("spellcheck", "false");` on the Data Explorer input which disables OS X Safari autocorrect. If it's too much work to upgrade, I can put in a PR to just patch in that one call.

**Comment by danielmewes** [comment]
Good idea.

Just adding the one call would certainly be simpler and avoid regressions (PR welcome! :) ).
