### ISSUE TITLE
 What is this error? 

### ISSUE THREAD

**Issue by korolle** [rethinkdb/rethinkdb#5782]
Hello! I have Linux Ubuntu. I have an error during installation rethinkdb-2.3.2.

### This is the first method.
> source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
> wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
> sudo apt-get update (**MY ERROR**)
> sudo apt-get install rethinkdb

### Error

> Ош  http://downoload.rethinkdb.com rosa InRelease                              
> Ош  http://downoload.rethinkdb.com rosa Release.gpg   
>  Не удалось найти IP-адрес для «downoload.rethinkdb.com»
> Получено 316 Б за 40с (7 Б/c)
> Чтение списков пакетов… Готово
> W: Ошибка GPG: http://ppa.launchpad.net trusty Release: Следующие подписи не могут быть проверены, так как недоступен открытый ключ: NO_PUBKEY 135D945A11D62AD6
> W: Не удалось получить http://downoload.rethinkdb.com/apt/dists/rosa/InRelease  
> W: Не удалось получить http://download.rethinkdb.com/apt/dists/rosa/main/binary-amd64/Packages  404  Not Found
> W: Не удалось получить http://download.rethinkdb.com/apt/dists/rosa/main/binary-i386/Packages  404  Not Found
> W: Не удалось получить http://downoload.rethinkdb.com/apt/dists/rosa/Release.gpg  Не удалось найти IP-адрес для «downoload.rethinkdb.com»
> W: Некоторые индексные файлы не скачались. Они были проигнорированы или вместо них были использованы старые версии.

### This is the second method.

> wget https://download.rethinkdb.com/dist/rethinkdb-2.3.2.tgz
> tar xf rethinkdb-2.3.2.tgz
> cd rethinkdb-2.3.2
> ./configure --allow-fetch
> make (**MY ERROR**)
> sudo make install

### Error

> [1/425] CC build/release/obj/web_assets/web_assets.o
>     [2/425] CC build/release/obj/rdb_protocol/ql2.pb.o
>     [3/425] CC build/release/obj/http/http_parser.o
>     [4/425] CC build/release/obj/http/http.o
> In file included from src/http/http.cc:2:0:
> ./src/http/http.hpp:5:25: fatal error: openssl/ssl.h: Нет такого файла или каталога
>  #include <openssl/ssl.h>
>                          ^
> compilation terminated.
> make[1]: *** [build/release/obj/http/http.o] Error 1
> make: *** [make] Error 2

 _**What is the problem?
Why did the previous version worked without errors?
Help me please!!!!!**_

**Comment by danielmewes** [comment]
About the first one:
There seems to be a typo: In "Ош http://downoload.rethinkdb.com rosa Release.gpg" the downoload has an extra `o` in it, should be http://download.rethinkdb.com

About the second one (building from source): You might have to install libssl-dev or alternatively run run `./configure --fetch openssl --allow-fetch` and then try again.

**Comment by danielmewes** [comment]
Closing because this doesn't look like a bug. Let me know if the issue persists.
