### ISSUE TITLE
Node.js - How to run a script? (dataexplorer like)

### ISSUE THREAD

**Issue by Vadorequest** [rethinkdb/rethinkdb#5784]
I want to run a script the same way I would run it in the administration panel `dataexplorer` from node.js.

Is there a way to do that? I didn't found anything on the official documentation. Thanks.

**Comment by danielmewes** [comment]
I'm not sure if I fully understand what you're trying to do, but you can create a node.js script and use our normal JavaScript driver.

Something like this:

```js
var r = require('rethinkdb');
r.connect({host: 'localhost'})
 .then((c) => {
    var conn = c;
    return firstQuery.run(conn);
  })
  .then((firstQueryResult) => {
    // Do something with the first query result
    return secondQuery.run(conn);
  })
  .then((secondQueryResult) => {
    // Do something with the second query result
  });
```

Save this in `script.js` and then you can run it through `node script.js` (you might need to run `npm install rethinkdb` in the same directory first).

**Comment by Vadorequest** [comment]
I meant something else.

I have a script file called users.js for instance. (it's not really JS, but it's easier for syntaxic coloration)

```js
r.db('db_name').table('users').insert(
    // Array of users
);
```

Is there an easy way to take that file as it and run it through node.js? The whole script.
The same way the `dataexplorer` behave, actually.

**Comment by larkost** [comment]
@Vadorequest: what are you actually trying to accomplish? If you are trying to import data we do have an import script (`rethinkdb-import`) that you can already use that gets installed with the Python driver.

**Comment by danielmewes** [comment]
Oh I see. There's no way to do this out of the box.

You can implement a "run script" script that does something similar to what the Data Explorer does though:

1. Separate the script file into individual queries. This is the most complex part. You can find the Data Explorer's implementation of this step in the `separate_queries` function here: https://github.com/rethinkdb/rethinkdb/blob/next/admin/static/coffee/dataexplorer.coffee#L2773
2. Call `eval` on each of the individual queries to evaluate them to a query object
3. Call `.run` on each query object, waiting on the returned promise before you proceed with the next one.

**Comment by Vadorequest** [comment]
Well, I first started a "populate" feature that basically takes a hbs file and compile it into a js file. It allowed me to have such a template:

```hbs
r.db('{{rethinkDbName}}').table('assignments').insert(
    [
        {{#repeat 100}}
            {
                "$created_at": {{createdAt}},
                "$updated_at": {{updatedAt}},
                "id": "{{guid}}",
                "institution_id": "{{randomInstitutionId}}",
                "owner_id": "{{randomOwnerId}}",
                "thumbnail": "http://lorempixel.com/200/200/abstract/{{int 0 10}}/",
                "title": "{{lorem 8}}",
                "description": "{{lorem}}",
                "module_id": "{{randomModuleId}}",
                "book_id": "{{randomBookId}}",
                "groups": [
                    {{#repeat 1 2}}
                        "{{randomGroupsIds 'assignments'}}"
                    {{/repeat}}
                ],
                "users": [

                ],
                "metas": [

                ],
                "start_date": "{{startDate}}",
                "due_date": "{{dueDate}}"
            }
        {{/repeat}}
    ]
);
```

Then, once the file was compiled I got a ready-to-copy-and-paste file directly in the #dataexplorer. Really useful.

But now I'd like to take that same file and to run it programatically somehow. :)

**Comment by Vadorequest** [comment]
> 1. Separate the script file into individual queries

AFAIK RethinkDB doesn't allow several queries at once. I can only run one. Thus, all my script contain a single query already so I shouldn't have issue with that part :)

**Comment by danielmewes** [comment]
You can run multiple queries at the same time. Though if your script only has a single query that of course makes it much simpler.

**Comment by Vadorequest** [comment]
Maybe this feature was added in a new version but I was never able to run two queries at the same time in RethinkDB, maybe I forgot the ";" delimiter.

**Comment by Vadorequest** [comment]
@dalanmiller So, the idea would be do to something like that?

```js
var script = eval(r.db('my_db').table('assignments').insert([
  // data
]));

script.run();
```

I can't test right now, not at work.
Thanks.

**Comment by danielmewes** [comment]
@Vadorequest The Data Explorer only runs one query at a time, but in a client you can run multiple ones.

Something like this should work:
```js
var r = require('rethinkdb');

var script = eval('r.db('my_db').table('assignments').insert([
  // data
])');

r.connect({host: 'localhost'})
  .then(function(c) => {
    script.run(c)
      .then(function(res) {
        console.log("Result: " + JSON.stringify(res));
    });
  });
```

**Comment by Vadorequest** [comment]
Thank you Daniel, I'll try this ASAP :)

Do I need to close the connection? (I'm a newbie at RethinkDB)

2016-05-20 23:04 GMT+02:00 Daniel Mewes <notifications@github.com>:

> @Vadorequest <https://github.com/Vadorequest> The Data Explorer only runs
> one query at a time, but in a client you can run multiple ones.
>
> Something like this should work:
>
> var r = require('rethinkdb');
> var script = eval('r.db('my_db').table('assignments').insert([  // data])');
> r.connect({host: 'localhost'})
>   .then(function(c) => {
>     script.run(c)
>       .then(function(res) {
>         console.log("Result: " + JSON.stringify(res));
>     });
>   });
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/rethinkdb/rethinkdb/issues/5784#issuecomment-220717986>
>



-- 
Cordialement,

M. Ambroise Dhenain.

**Comment by Vadorequest** [comment]
Thank you @danielmewes ! Works like a charm :)

**Comment by danielmewes** [comment]
@Vadorequest Closing the connection at the end is a good idea.

**Comment by Vadorequest** [comment]
I just did a `process.exit(0)` at the end actually. Apparently this also closes the connection.
