### ISSUE TITLE
Issue with nested query and lack of good documentation 

### ISSUE THREAD

**Issue by carlskii** [rethinkdb/rethinkdb#5793]
Hi,

I'm struggling to get my head around a nested query. 

I have several docs that look like this: 

```json
{
	"blobs": [{
		"base64": "MIICPDCCAaUCEHC65B0Q2Sk0tjjKe",
		"data": {
			"Info:": {
				"length": 1024
			},
			"Serial Number": 123456,
			"Validity": {
				"begin": "20280801235959Z",
				"end": "19960129000000Z"
			},
			"Version": 0,
			"hash": "MIICPDCCAaUCEHC65B0Q2Sk0tjjKe",
			"item count:": 0,
			"meta1": {
				"a": "abc",
				"b": "bcd",
				"c": "cdf"
			},
			"meta2": {
				"a": "abc",
				"b": "bcd",
				"c": "cdf"
			}
		},
		"fingerprint": "123"
	}, {
		"base64": "MIICPDCCAaUCEHC65B0Q2Sk0tjjKe",
		"data": {
			"Info:": {
				"length": 1024
			},
			"Serial Number": 123456,
			"Validity": {
				"begin": "20280801235959Z",
				"end": "19960129000000Z"
			},
			"Version": 0,
			"hash": "MIICPDCCAaUCEHC65B0Q2Sk0tjjKe",
			"item count:": 0,
			"meta1": {
				"a": "abc",
				"b": "bcd",
				"c": "cdf"
			},
			"meta2": {
				"a": "abc",
				"b": "bcd",
				"c": "cdf"
			}
		},
		"fingerprint": "456"
	}, {
		"base64": "MIICPDCCAaUCEHC65B0Q2Sk0tjjKe",
		"data": {
			"Info:": {
				"length": 1024
			},
			"Serial Number": 123456,
			"Validity": {
				"begin": "20280801235959Z",
				"end": "19960129000000Z"
			},
			"Version": 0,
			"hash": "MIICPDCCAaUCEHC65B0Q2Sk0tjjKe",
			"item count:": 0,
			"meta1": {
				"a": "abc",
				"b": "bcd",
				"c": "cdf"
			},
			"meta2": {
				"a": "abc",
				"b": "bcd",
				"c": "cdf"
			}
		},
		"fingerprint": "789"
	}, {
		"base64": "MIICPDCCAaUCEHC65B0Q2Sk0tjjKe",
		"data": {
			"Info:": {
				"length": 1024
			},
			"Serial Number": 123456,
			"Validity": {
				"begin": "20280801235959Z",
				"end": "19960129000000Z"
			},
			"Version": 0,
			"hash": "MIICPDCCAaUCEHC65B0Q2Sk0tjjKe",
			"item count:": 0,
			"meta1": {
				"a": "abc",
				"b": "bcd",
				"c": "cdf"
			},
			"meta2": {
				"a": "abc",
				"b": "bcd",
				"c": "cdf"
			}
		},
		"fingerprint": "101112"
	}],
	"complete": false,
	"fast": true,
	"id": "33beabc8-9d5b-44f8-bc3b-d346387b1bc9",
	"items": [{
		"blobs": [
			"123",
			"457",
			"789",
			"10112"
		]
	}],
	"port": 443,
	"secure": true
}
```

I can easily query and match on `fingerprint` which then returns the documents that match. 

```javascript
r.db('db').table("test2").concatMap(function(doc) {
    return doc("blobs")
}).filter(function(carl) {
  return carl("fingerprint").match("123")
})
```
However, I need to match on more than one field and according to the docs I can do this.

```javascript
r.db('db').table("test2").concatMap(function(doc) {
    return doc("blobs")
}).filter(function(carl) {
  return carl("fingerprint").match("123").and(["meta1"]["b"]).match("bcd")
})
```
However, I get an error. 

```
e: Argument 1 to and may not be `undefined`.
```

Unfrotuantly, the docs seem a little light on good working examples for this sort of thing. Are rich examples anywhere ?

**Comment by deontologician** [comment]
The docs for this are at: https://rethinkdb.com/docs/nested-fields/javascript/

Basically, you'll want to skip 'match', that's for regexes. You want a query like:

```py
r.db('db').table('test2')('blobs').filter(carl =>
  carl('fingerprint').eq('123').and(
  carl('metal')('b').eq('bcd'))
) 
```

You can't use the bracket syntax `[]` in javascript reql, use `()` instead. And you don't need to explicitly use `.concatMap` here, since `('blobs')` does that for you under the hood

**Comment by deontologician** [comment]
And actually, now that I think about it, pathspecs are way easier for this:

```js
r.db('db').table('test2')('blobs').filter({ fingerprint: '123', metal: {b: 'bcd' }})
```

**Comment by carlskii** [comment]
Thanks for these examples and for clarifying where I was going wrong. To test these examples in the data explorer I assume I need some kind of callback/return statement ?

**Comment by carlskii** [comment]
Can I use the pathspec example from the data explorer ? 

Seem to get an error when I tried this.

`e: Expected type OBJECT but found ARRAY in:
r.db("db").table("test2")("blobs").filter({"fingerprint": "123", "meta1": {"b": "bcd"}})`

**Comment by deontologician** [comment]
In the python driver, you'd use `[]` brackets. Also I realized I misread your data structure. You will need to use concatmap to join up all of the arrays in 'blob':

```py
r.db('db').table('test2').concat_map(lambda b: b['blobs']).filter({'fingerprint': '123', 'metal': {'b': 'bcd'}})
```

**Comment by danielmewes** [comment]
@carlskii The `Expected type OBJECT but found ARRAY` error probably means that the `blobs` field contains an array value, so you can't filter over it like this.

I think the `concatMap` you had earlier is actually still necessary. 

In Python, you would do the same thing like this:
```py
r.db('db').table("test2").concat_map(lambda doc: doc["blobs"]).filter({"fingerprint": "123", "meta1": {"b": "bcd"}}).run(conn)
```

The pathspec syntax is exactly the same as you can see.

**Comment by carlskii** [comment]
Thanks. OK so this works

```javascript
r.db('db').table('test2').concat_map(lambda b: b['blobs']).filter({'fingerprint': '123'}).run()
```
it returns all the items with a fingerprint of 123, however the additional `and` is not working e.g.

```javascript
r.db('db').table("test2").concat_map(lambda doc: doc["blobs"]).filter({"fingerprint": "123", "meta1": {"b": "bcd"}}).run(conn)
```
Nothing gets returned if I include this.

**Comment by deontologician** [comment]
It's nested one level deeper: `{ "data": { "meta1": { "b" : "123" }}}`

**Comment by carlskii** [comment]
Got it - thanks so much for your help. So this is woking in Python now: 

```python
data2 = r.db('scanafi').table("test2").concat_map(lambda doc: doc["blobs"]).filter({ "fingerprint": "123", "data": { "meta1": { "b" : "bcd" }}}).run()
```
If I need the same in JS what do I need.

Sorry for the questions. Still getting my head around REQL.

**Comment by deontologician** [comment]
Only difference in javascript is that you'll translate all `[]` to `()` (so just that one around 'blob'), and then change the function syntax from `lambda x: ...` to `function(x){ return ... }` (make sure to return, that's important) If you have access to a newer version of node, you can use `x => ...` arrow functions.

When you call `.run(conn)` in javascript, you'll get a promise instead of it being synchronous like python

**Comment by carlskii** [comment]
Sorry to be a pain, but Is it possible to run this in the Data Explorer for testing. I can get this to work but can't get my full query to work. 

```javascript
r.db('db').table("test2").concatMap(function(row) { return row('blobs'); }).filter(function(blob) {
  return blob('fingerprint').eq('123');
})
```

This works, but I cant work out how pass the rest of the query `"data": { "meta1": { "b" : "bcd" }}` in to the query.

**Comment by deontologician** [comment]
Instead of passing a function to filter, just pass that pathspec object to filter
