### ISSUE TITLE
rethinkdb erroring out on count of index

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5794]
Written by @monkeyboy64, moved from https://github.com/rethinkdb/docs/issues/1129

--

I am trying to do this query: r.db("numetric").table("prostar__2cef1ff5_9a7e_4ddf_a405_04a2d0a26757").getAll(true, {index: "indexed"}).count()

on a table with ~13M records. There are only two values in the index, true or false.  Currently all the records have the value true so.

The query errors out with an unknown error.

There are three servers with 8 GB cache allocated to each. There are 3 shards/3 replicas on the table.

The records look like this:

{
    "ActualWeight": 6 ,
    "Amount": 0.65 ,
    "BatchId": null ,
    "CalculatedAmount": 0.51 ,
    "CarrierDescription":  "28" ,
    "CarrierOrderNumber":  "26" ,
    "CarrierType":  "25" ,
    "Category":  "14" ,
    "ClientName":  "2" ,
    "ClientOrderNumber":  "42" ,
    "Cost": 0.51 ,
    "CreatedDate":  "2015-01-05T14:50:46.967" ,
    "Description":  "16" ,
    "DetailName":  "38" ,
    "DetailValue":  "39" ,
    "DueDate":  "2015-01-05T14:50:46" ,
    "EndDate":  "2015-01-03T23:55:55" ,
    "InvoiceId": 314 ,
    "InvoiceLineCarrierId": 1453456 ,
    "InvoiceLineDetailId": null ,
    "InvoiceLineId": 2219085 ,
    "InvoiceNumetricId": 20 ,
    "InvoiceOrderId": 484423 ,
    "InvoiceStatus":  "3" ,
    "IsIntercept": null ,
    "IsPassThrough": false ,
    "IsReplacement": false ,
    "IssuedDate":  "2015-01-05T14:50:46.967" ,
    "LocationId": 1 ,
    "OrderClientName":  "40" ,
    "OrderNumber":  "22" ,
    "OrderOrderNumber":  "41" ,
    "OrderShipDate":  "2014-11-17T00:00:00" ,
    "OrderTrackingNumbers":  "44" ,
    "ProcessPeriod":  "11" ,
    "QBInvoiceRef":  "9" ,
    "Quantity": 1 ,
    "ShipDate":  "2014-12-22T00:00:00" ,
    "ShipToCountry":  "35" ,
    "ShipToPostalCode":  "36" ,
    "ShippingMethod":  "29" ,
    "StartDate":  "2014-12-28T00:00:00" ,
    "SubCategory":  "15" ,
    "TrackingNumber":  "30" ,
    "Weight": 6 ,
    "WorkOrderId": null ,
    "Zone":  "32" ,
    "__metadata": {
    "indexed": true ,
    "updated": "2015-01-05T14:50:46.967"
}

**Comment by danielmewes** [comment]
@monkeyboy64 Which version of RethinkDB are you using? Are you running the query in the Data Explorer or with a client?

If it's in the Data Explorer, I suspect that the query might time out. Older versions of RethinkDB had an issue that caused timeouts to be reported as "interrupted for an unknown reason". The timeout does not apply to other clients. Could you try running the query in a node.js script or in Python? If you have the latest version of the Python driver installed (`sudo pip install --upgrade rethinkdb`), you can run the query as follows:
```
$ python -m rethinkdb repl
The RethinkDB driver has been imported as `r`.
==========
>>> r.db("numetric").table("prostar__2cef1ff5_9a7e_4ddf_a405_04a2d0a26757").get_all(True, index="indexed").count().run()
```

**Comment by monkeyboy64** [comment]
I am using rethinkdb 2.2.4 on ubuntu.

When I run the query in python it takes a long time. After several minutes it still hasn't come back. While the query is running if I look at activity on the table it seems like it is reading through the entire table 7000 records at a time. I have an index, so it seems like it should just come back.

If I run r.db("numetric").table("prostar__2cef1ff5_9a7e_4ddf_a405_04a2d0a26757").count().run() instead the count will come back in 2 minutes.

**Comment by danielmewes** [comment]
@monkeyboy64 If you apply `count()` directly on a table there's an optimization that skips loading the full documents. However if you apply it after another operation (including indexed ones), RethinkDB actually loads every document.

Especially if your data is on a rotational disk or slow network storage and doesn't fully fit into cache, this can take a long time.

We have plans to make `count` be an essentially constant-time operation in the future https://github.com/rethinkdb/rethinkdb/issues/3949 , but currently it's just a reduction like any other (with the mentioned optimization in case you apply it to the whole table).

I think this is currently expected behavior. You might want to follow https://github.com/rethinkdb/rethinkdb/issues/3949 for future improvements to `count`.
