### ISSUE TITLE
Incorrect call signature for conn.close() in net_asyncio

### ISSUE THREAD

**Issue by skolsuper** [rethinkdb/rethinkdb#5795]
I am using rethinkdb Python driver version `2.3.0.post3` with asyncio and am getting the below exception thrown from `net_asyncio` whenever there is any problem connecting to the database.

It seems like the call signature for `conn.close` has changed but the Exception handlers here have not been updated to match.

```
TypeError: close() missing 2 required positional arguments: 'noreply_wait' and 'token'
  ...
  File "resync/connection.py", line 31, in get_conn
    conn = await r.connect(**self._config_dict)
  File "rethinkdb/asyncio_net/net_asyncio.py", line 283, in reconnect
    return (yield from self._instance.connect(timeout))
  File "rethinkdb/asyncio_net/net_asyncio.py", line 175, in connect
    yield self.close()
```

**Comment by danielmewes** [comment]
Thanks for reporting this. We'll look into it.

@Tryneus do you have an idea what's going on?

**Comment by danielmewes** [comment]
@larkost Did you fix this as part of making the asyncio tests pass?

**Comment by larkost** [comment]
Yes, that was one of the issues I found and fixed. The `close()` method now defaults all of its inputs. This is already in both `next` and `v2.3.x`. Sorry, I didn't remember this one.
