### ISSUE TITLE
Grappling with advanced nested queriew

### ISSUE THREAD

**Issue by carlskii** [rethinkdb/rethinkdb#5796]
In my quest to get to grips with REQL I'm trying to create my own more advanced version of this https://www.rethinkdb.com/docs/reql-data-exploration/ - This is was great start but the data set is just too simple to learn anything really useful from. Can I suggest creating something that resembles a more real world data-structure. 

RethinkDB is an amazing tool with huge potential, I have many ideas for things I would like to achieve using it. However, once you get past really basic use cases the lack of advanced query examples is a real stumbling block (at least for me) when comparing to the likes of CouchDB etc. I'm not a hardcore developer but can see some huge benefits for using RethinkDB for some of my data analysis and visualisation projects. 

I've read the docs here: https://rethinkdb.com/docs/nested-fields/javascript/

Is this really all there is on this subject ? 

And can't find anything on the `pathspec` syntax other than some references in GitHub issues.

Based on the following document structure and with the help of a previously #5793 logged question I can now perform a nested query using `pathspec` syntax. e.g.

```javascript
r.db('scanafi').table("test2").concatMap(function(doc) {
  return doc("blobs")
}).filter({ "fingerprint": "101112", "data": { "meta2": { "c" : "carlskii" }}})
```

However I now have two questions: 

1. Does the `pathspec` syntax enable wildcard or partial searching. e.g. `{ "fingerprint": "101112", "data": { "meta2": { "c" : "carl*" }}} or `{ "fingerprint": "10*", "data": { "meta2": { "c" : "carlskii" }}}` or should I be using the traditional syntax for this type of thing ? 

2. Based on my document structure I need to return both the `blobs` and the `items` into my results. How can I achieve that.

Again, I would like to re-iterate - An advanced query tutorial/cookbook containing nothing but query examples would be hugely beneficial to new users such as myself. 

Best Regards.

```json
{
	"blobs": [{
		"base64": "MIICPDCCAaUCEHC65B0Q2Sk0tjjKe",
		"data": {
			"Info:": {
				"length": 1024
			},
			"Serial Number": 123456,
			"Validity": {
				"begin": "20280801235959Z",
				"end": "19960129000000Z"
			},
			"Version": 0,
			"hash": "MIICPDCCAaUCEHC65B0Q2Sk0tjjKe",
			"item count:": 0,
			"meta1": {
				"a": "abc",
				"b": "bcd",
				"c": "cdf"
			},
			"meta2": {
				"a": "abc",
				"b": "bcd",
				"c": "cdf"
			}
		},
		"fingerprint": "123"
	}, {
		"base64": "MIICPDCCAaUCEHC65B0Q2Sk0tjjKe",
		"data": {
			"Info:": {
				"length": 1024
			},
			"Serial Number": 123456,
			"Validity": {
				"begin": "20280801235959Z",
				"end": "19960129000000Z"
			},
			"Version": 0,
			"hash": "MIICPDCCAaUCEHC65B0Q2Sk0tjjKe",
			"item count:": 0,
			"meta1": {
				"a": "abc",
				"b": "bcd",
				"c": "cdf"
			},
			"meta2": {
				"a": "abc",
				"b": "bcd",
				"c": "cdf"
			}
		},
		"fingerprint": "456"
	}, {
		"base64": "MIICPDCCAaUCEHC65B0Q2Sk0tjjKe",
		"data": {
			"Info:": {
				"length": 1024
			},
			"Serial Number": 123456,
			"Validity": {
				"begin": "20280801235959Z",
				"end": "19960129000000Z"
			},
			"Version": 0,
			"hash": "MIICPDCCAaUCEHC65B0Q2Sk0tjjKe",
			"item count:": 0,
			"meta1": {
				"a": "abc",
				"b": "bcd",
				"c": "cdf"
			},
			"meta2": {
				"a": "abc",
				"b": "bcd",
				"c": "cdf"
			}
		},
		"fingerprint": "789"
	}, {
		"base64": "MIICPDCCAaUCEHC65B0Q2Sk0tjjKe",
		"data": {
			"Info:": {
				"length": 1024
			},
			"Serial Number": 123456,
			"Validity": {
				"begin": "20280801235959Z",
				"end": "19960129000000Z"
			},
			"Version": 0,
			"hash": "MIICPDCCAaUCEHC65B0Q2Sk0tjjKe",
			"item count:": 0,
			"meta1": {
				"a": "abc",
				"b": "bcd",
				"c": "cdf"
			},
			"meta2": {
				"a": "abc",
				"b": "bcd",
				"c": "cdf"
			}
		},
		"fingerprint": "101112"
	}],
	"complete": false,
	"fast": true,
	"id": "33beabc8-9d5b-44f8-bc3b-d346387b1bc9",
	"items": [{
		"blobs": [
			"123",
			"457",
			"789",
			"10112"
		]
	}],
	"port": 443,
	"secure": true
}
```

**Comment by marshall007** [comment]
@carlskii I think this is roughly what you're looking for:

```js
r.db('scanafi').table("test2").merge({
  // only include blobs matching the pathspec
  blobs: r.row('blobs').filter({ "fingerprint": "101112", "data": { "meta2": { "c" : "carlskii" }}})
})
// filter items with no matching blobs
.filter(r.row('blobs').isEmpty().not())
```

Good luck with your advanced Data Explorer, sounds like a neat project!

**Comment by marshall007** [comment]
Oh, and in regards to wildcard matches, you'll have to use `.match()` for that instead of pathspaces. Which could look something like this:

```js
r.row('blobs').filter({ "fingerprint": "101112" })
  .filter((row) => row("data")("meta2")("c").match("carl*"))
```

**Comment by danielmewes** [comment]
@carlskii Have you seen http://www.rethinkdb.com/docs/cookbook/ ?

The "pathspec" syntax indeed seems to be under-documented. We'll see if we can add some information about them to the working with nested documents page.

**Comment by danielmewes** [comment]
I've opened https://github.com/rethinkdb/docs/issues/1130 to improve the documentation on pathspecs.

Are you on https://rethinkdb.slack.com? If not, you can sign up at http://slack.rethinkdb.com/ . The Slack channel or our mailing list at https://groups.google.com/forum/#!forum/rethinkdb are better places to ask questions. This issue tracker is primarily for feature suggestions and bugs.

**Comment by carlskii** [comment]
Thanks for the response. Look forward to the seeing docs. :) Great work on all you're doing.
