### ISSUE TITLE
Password protecting Rethinkdb v1.13

### ISSUE THREAD

**Issue by beatscode** [rethinkdb/rethinkdb#5797]
How is the auth password set on older versions of rethinkdb? Currently using versions 1.13/1.15 in production/development

**Comment by beatscode** [comment]
I just found the docs repository.

**Comment by danielmewes** [comment]
There have been a bunch of critical bug fixes including some fixes for data corruption issues since those releases by the way.
If you make regular backups and everything is stable you might not need to upgrade, but in general I'd recommend it.
