### ISSUE TITLE
Date Parsing Error

### ISSUE THREAD

**Issue by jonhartnett** [rethinkdb/rethinkdb#5801]
On Win 7 64-bit using the Python drivers, parsing of datetime objects fails if the epoch_time is less than 43200 seconds before 1970. This stackoverflow question details how to produce the error outside of rethink: [http://stackoverflow.com/questions/37494983/python-fromtimestamp-oserror](http://stackoverflow.com/questions/37494983/python-fromtimestamp-oserror)
The relevant code is convert_time in ReQLDecoder of ast.py. The issue is clearly an OS/Python problem, but this is a serious detriment for Win users. Perhaps explore other means of parsing dates?

**Comment by jonhartnett** [comment]
According to Python official docs, datetime.fromtimestamp: "It’s common for this to be restricted to years from 1970 through 2038.", meaning it never should have been used for dates in the first place.

**Comment by jonhartnett** [comment]
I have found a workaround for this issue. Instead of using fromtimestamp, we generate a unix epoch date:
`epoch = datetime.datetime(1970, 1, 1, tzinfo=RqlTzinfo(obj['timezone']))`
and then offset it by the epoch_time
`epoch += datetime.timedelta(0, 0, 0, obj['epoch_time'])`
and return that. Without timezone is the same minus the tzinfo param.

**Comment by danielmewes** [comment]
Ah that's a problem. Thanks for opening an issue!

**Comment by srh** [comment]
If some Python developer wants to make a PR for this before 2.4 that would be appreciated.
