### ISSUE TITLE
installation with apt-get not working

### ISSUE THREAD

**Issue by rokyed** [rethinkdb/rethinkdb#5803]
the apt-get cannot update "rethinkdb" because:
```
W: Failed to fetch http://download.rethinkdb.com/apt/dists/rebecca/main/binary-amd64/Packages  404  Not Found [IP: 104.28.25.125 80]

W: Failed to fetch http://download.rethinkdb.com/apt/dists/rebecca/main/binary-i386/Packages  404  Not Found [IP: 104.28.24.125 80]
```

P.S. I don't know if I am posting in the right place. But there we go, thanks. ( for myself I will compile the source code instead, but for others :smile_cat: )

Again thank you very much!

**Comment by danielmewes** [comment]
@rokyed We don't provide packages for Linux Mint.

You can try one of the Debian or Ubuntu repositories. Take a look at http://download.rethinkdb.com/apt/dists/ to see the supported distributions. Once you have found one that you think will work, you can edit `/etc/apt/sources.list.d/rethinkdb.list` and replace `rebecca` by the matching distribution.

**Comment by danielmewes** [comment]
Actually I just saw that http://rethinkdb.com/docs/install/mint/ has a matching source line for Mint 17, which might work with 17.1.

**Comment by rokyed** [comment]
thanks!! I managed to compile it flawlessly first time 🎆.
