### ISSUE TITLE
errors compiling against OpenSSL on MacOS

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5811]
I have been seeing an occasional error when compiling against the downloaded OpenSSL header files on MacOS (this is always using downloaded headers). Specifically:

```
In file included from src/arch/address.cc:19:
./src/arch/io/network.hpp:8:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
```

If I re-run `make` immediately afterwards with the same settings it works fine. It only appears to happen when I clean out the build products. My assumption is that we don't have a dependency quite right, and so `make` is sometimes scheduling that line before we have OpenSSL downloaded and setup right.

**Comment by danielmewes** [comment]
This might be the issue @AtnNn described here: https://github.com/rethinkdb/rethinkdb/issues/5776#issuecomment-220168597
`make build-openssl` is a possible work-around for the moment.
