### ISSUE TITLE
Proposal: Modifier functions

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5813]
__Intro__

Modifier functions are the first proposal out of two, which together will allow users to set up expiration / TTL (https://github.com/rethinkdb/rethinkdb/issues/746). I'll post the second part shortly.

A modifier function is a ReQL function that can be configured on a given table. A modifier function is applied to each write, and can:
* perform schema validation
* rewrite documents or add additional fields, for example a `lastModificationTs` field to implement expiration (TTL)
* implement security rules, such as insert-only tables. In the future, we can extend this concept to expose a user context with the user name and user groups to the modifier function.

__Specification__

The modifier function has the signature `(oldVal : object, newVal : object) -> object`. Each of the objects can also be `null`.

A modifier function has to be deterministic.

Whenever a write operation on the table inserts, deletes or modifies a given document, the modifier function will be called with the old value of the document (or `null` on inserts) and the new value of the document (or `null` on deletes). It then returns the value that should actually be inserted and/or replaced instead of `newVal`. It can also return `r.error(...)` to abort the write.

To simplify things, I think we should require the modifier function to return `null` exactly iff `newVal` is `null`. That way we make sure that it doesn't turn an insert/update into a deletion, and doesn't turn a deletion into an update, which could be confusing and might break some assumptions in our code.

__Configuration API__

Proposal for an API for setting a modifier function on a given table:
* `tbl.setModifier(function)` sets the modifier function or overwrites it if one already exists
* `tbl.setModifier(null)` deletes the modifier function
* `tbl.getModifier()` gets a string representation of the current modifier function, or `null`

The `setModifier` term requires `"config"` permissions on `tbl`.

This API could be more straight-forward if we had a ReQL query pseudo-type ( https://github.com/rethinkdb/rethinkdb/issues/3636 ), but I think that would become too much for 2.4. The current API therefore is loosely inspired by the secondary index API.

__Examples for modifier functions:__

```js
// Inject a `lastModified` timestamp
tbl.setModifier(function(oldVal, newVal) {
    return newVal.merge({lastModified: r.now}).default(null);
  })
```
(Note that `r.now` is the deterministic `r.now` that's filled in when the write query triggering this is compiled, not when the modifier is set. This might require some extra plumbing to work.)

```js
// Verify that the documents have certain fields.
tbl.setModifier(function(oldVal, newVal) {
    return r.branch(newVal.hasFields("field1", "field2"), newVal, r.error("Missing fields")).default(null);
  })
```

**Comment by deontologician** [comment]
> I think we should require the modifier function to return null exactly iff `newVal` is null

Or `r.error`

**Comment by danielmewes** [comment]
> Or `r.error`

Ah right. It can always throw or return errors.

**Comment by mlucy** [comment]
> A modifier function has to be deterministic.

Truly deterministic or per-node deterministic?  (I.e. can you use geo functions?)

Also, are we making an explicit exception for the current time?  If we're OK making an exception for the current time, why do we need the determinism constraint at all?

> `setModifier` and `getModifier`

The modifiers should presumably also live in an artificial table somewhere, so that people can e.g. subscribe to changes on them.  Maybe on `table_config` alongside the indexes?

Also, do we want to back up and restore modifiers when doing import/export the way we do with indexes?

> `tbl.setModifier(function(oldVal, newVal)`

The signature should maybe be `(id, oldVal, newVal)` for consistency with insert conflict functions.

> Note that r.now is the deterministic r.now that's filled in when the write query triggering this is compiled, not when the modifier is set. This might require some extra plumbing to work.

How are the semantics of `r.now` going to change exactly?  Are we going to move to `r.now` being a non-deterministic term that always evaluates to the current time?  Or is the proposal to special-case it inside of modifier functions?

I think it would be better if we could keep a consistent meaning for `r.now` everywhere -- it would be extremely confusing if it meant something different in normal functions vs. modifier functions vs. conflict resolution functions vs. secondary index functions vs. etc.

**Comment by mlucy** [comment]
Also, we might want to consider a name other than "modifier function".  It's not at all clear to me that I would want to use a modifier function for schema validation.  What do you think about a name like "write_hook" or "pre_write_hook" instead?

**Comment by danielmewes** [comment]
@mlucy We need full determinism because these functions will be executed on each replica while holding the lock on the leaf node. They have the same constraints as update functions.

> The modifiers should presumably also live in an artificial table somewhere, so that people can e.g. subscribe to changes on them. Maybe on table_config alongside the indexes?

Yea, that sounds good to me.

> Also, do we want to back up and restore modifiers when doing import/export the way we do with indexes?

Good point, I think yes. We just need to make sure that we only set them after we're done with the data insert.

> The signature should maybe be `(id, oldVal, newVal)` for consistency with insert conflict functions.

Makes sense.

About `r.now`: I think it's consistent, but with the one subtlety that the modifier function will be executed with the "`r.now` environment" of the query that causes the write, not the environment that existed when setting the modifier.
The only other place where we currently can store functions and where this is an issue is in secondary indexes. Our current behavior for secondary index functions is inconsistent to this, but our it also doesn't make sense and doesn't seem to be what people are expecting. We should probably just disallow `r.now` in secondary index functions as part of this, and the behavior would be consistent again afaikt.
You could describe it as: `r.now` in a query is evaluated based on an `r.now` value in a hidden query environment. The `r.now` value in the environment is set once when the query gets compiled.
With the exception of secondary index functions, I believe this is equivalent to our current behavior, even if this is not how it is implemented.

**Comment by deontologician** [comment]
What if the modifier function itself has to be deterministic, but you're allowed to return an object that has non-deterministic terms in it, which are evaluated at the time the modifier function completes without an error.

**Comment by danielmewes** [comment]
@deontologician That wouldn't work. The whole thing needs to be deterministic, because it will be executed independently on every replica. If each execution can lead to different results, then we'll get divergence between replicas.

As a secondary concern, the function should also be efficient since we will be holding a write lock on the leaf node and globally on all secondary indexes of the table while we're evaluating it.

**Comment by encryptio** [comment]
What about cases where you want a modifier function in the vast majority of cases (including new stuff that developers write) but want to skip it for just this one weird query? (e.g., table is append and delete only, but you want to rewrite all rows once with an `.update({"_notimportant_":true}); .update({"_notimportant_": r.literal()})`, and you'd like to keep your modifiers in place during that process.)

Should we have an optarg to `insert`/`update` to optionally skip the modifier functions? Do you need `config` permissions to use the optarg? Or is this too subtle and unknown territory to put into the first version?

**Comment by danielmewes** [comment]
@encryptio Interesting, I think that could be very useful.

I'm not quite sure what the permission requirements for the override should be.

If we allow everyone with write permissions to ignore the modifier, that would obviously rule out modifiers as a security feature. On the other hand they will be really limited for that purpose in the current proposal anyway, and their main use case is a different one.

Requiring `config` permissions for it would be safe, and might actually make sense since most cases I can think of where you would want to ignore the modifier are administrative operations.

**Comment by VeXocide** [comment]
I agree with @mlucy that this should be part of `tbl.config()` instead of having an explicit getter and setter.

**Comment by danielmewes** [comment]
> I agree with @mlucy that this should be part of tbl.config() instead of having an explicit getter and setter.

Yeah, but it doesn't work without a ReQL query data type unfortunately.

**Comment by tatsujin1** [comment]
Am I understanding it correctly that you're sneaking in an implementation to #3583 under the fence?  :)
If so, doubly awesome!

**Comment by danielmewes** [comment]
@tatsujin1 No, https://github.com/rethinkdb/rethinkdb/issues/3583 will not be addressed by the changes proposed here. `r.now` is still going to resolve to a single constant timestamp at the beginning of query execution.

**Comment by mlucy** [comment]
To clarify, I think there should be a setter and getter for the same reason `indexCreate` and `indexDrop` are terms, but you should also be able to interact with these things through the system tables.

**Comment by marshall007** [comment]
@danielmewes @mlucy if modifier functions are to backed up during import/export, I think `.getModifier()` is going to need to return an `.indexStatus()` style response rather than a string representation, correct? In the existing proposal, I don't see where else you would get the binary representation in order to recreate it (like we do with secondary indices).

**Comment by danielmewes** [comment]
@marshall007 Good point! We should probably return an object that has both the binary and the pretty-printed representation.

**Comment by danielmewes** [comment]
Updated proposal with the following changes:
* renamed to write hook
* the first argument to the write hook is now the document's ID
* added `ignore_write_hook` flag to ignore the hook on a per-query basis
* added specification of `getWriteHook` return format
* added note on `r.now` evaluation changes
* added note on backup tool changes
* added note on system table representation

__Specification__

The write hook function has the signature `(id: datum, oldVal : object, newVal : object) -> object`. Each of the objects can also be `null`.

A write hook function has to be deterministic.

Whenever a write operation on the table inserts, deletes or modifies a given document, the write hook function will be called with the primary key of the document, the old value of the document (or `null` on inserts) and the new value of the document (or `null` on deletes). It then returns the value that should actually be inserted and/or replaced instead of `newVal`. It can also return `r.error(...)` to abort the write.

For simplicity, the write hook function is allowed to return `null` exactly iff `newVal` is `null`. That way we make sure that it doesn't turn an insert/update into a deletion, and doesn't turn a deletion into an update, which could be confusing and might break some assumptions in our code.

__Configuration API__

Proposal for an API for setting a write function on a given table:
* `tbl.setWriteHook(function)` sets the modifier function or overwrites it if one already exists.
* `tbl.setWriteHook(binary)` variant for `rethinkdb restore` that accepts a binary representation of the function as obtained from `getWriteHook`
* `tbl.setWriteHook(null)` deletes the modifier function
* `tbl.getWriteHook()` returns either `null` or an object of the following form:
```js
{
  "function": binary,
  "query": "setWriteHook(function(_var1, _var2, _var3) { return ...; })" , 
}
  ```

The `setWriteHook` term requires `"config"` permissions on `tbl`.

__Override__
Any write query can override the write hook. The argument `ignoreWriteHook: true` can be passed to `insert`, `update`, `delete` and `replace` or globally to `run`. If specified, the write hook is not executed.

__Notes__
* The way `r.row` is evaluated will be changed slightly. `r.now`  in a query will be evaluated based on an `r.now` value in a hidden query environment. The `r.now` value in the environment is set once when the query gets compiled. We no longer replace `r.now` by a date-time constant during query compilation. We will allow `r.now` to appear in write hook functions, and will disallow it to appear in index function. For write hooks, the `r.now` environment value will be taken from the write query's environment.
* The rethinkdb backup tools should be adapted in two ways. First, they should store and restore the write hook function, similar to how they currently store and restore secondary indexes. Secondly, `rethinkdb restore` should use the `ignoreWriteHook` flag for its inserts. I'm not sure what the best default for `rethinkdb import` is. We can also make this configurable.
* The table's entry in `table_config` will get a new field `write_hook` with the same value as what `getWriteHook()` returns when called on the table. For simplicity I think we should make have this field be read-only.

**Comment by danielmewes** [comment]
@mlucy @coffeemug could you make a pass over the updated proposal please?

**Comment by encryptio** [comment]
To be explicit, your proposal allows `ignoreWriteHook` *without* `config` permissions?

**Comment by danielmewes** [comment]
> To be explicit, your proposal allows `ignoreWriteHook` *without* `config` permissions?

I was thinking yes, but on second thought it's probably better to require `config` permissions on the table for this.

**Comment by danielmewes** [comment]
Marking settled as described here https://github.com/rethinkdb/rethinkdb/issues/5813#issuecomment-227615749 with the addition that specifying `ignoreWriteHook` should required `config` permissions on the table.

**Comment by nighelles** [comment]
This is in review #3725.

**Comment by nighelles** [comment]
This is in next.
