### ISSUE TITLE
RethinkDB fatal error failed to delete via init script

### ISSUE THREAD

**Issue by aranw** [rethinkdb/rethinkdb#5826]
Just booted up a fresh server on AWS and trying to install and start RethinkDB via the init script. 

Server's running Ubuntu 14.04 and I've added a 40gb SSD and mounted it to `/data` it's formatted in ext4

I get the following stack trace when I use `service rethinkdb start`

Interestingly I can see it deleting and creating the `/data/rethinkdb` folder. Also when I use `rethinkdb --bind all` the server boots up fine if I do it from the `/data` directory. 

```
root@ip-172-31-40-242:/data# service rethinkdb start
rethinkdb: db2: Starting instance. (logging to `/data/rethinkdb/log_file')
Recursively removing directory /data/rethinkdb/tmp
Recursively removing directory /data/rethinkdb
In recursion: removing file '/data/rethinkdb/tmp'
In recursion: removing file '/data/rethinkdb/log_file'
In recursion: removing file '/data/rethinkdb'
Version: rethinkdb 2.3.3~0trusty (GCC 4.8.2)
error: Error in src/utils.cc at line 541:
error: Guarantee failed: [res == 0]  (errno 13 - Permission denied) Fatal error: failed to delete '/data/rethinkdb'.
error: Backtrace:
error: Fri Jun  3 17:18:48 2016

       1 [0xabae80]: backtrace_t::backtrace_t() at 0xabae80 (/usr/bin/rethinkdb)
       2 [0xabb213]: format_backtrace(bool) at 0xabb213 (/usr/bin/rethinkdb)
       3 [0xd3e64d]: report_fatal_error(char const*, int, char const*, ...) at 0xd3e64d (/usr/bin/rethinkdb)
       4 [0xaa9945]: remove_directory_helper(char const*, stat const*, int, FTW*) at 0xaa9945 (/usr/bin/rethinkdb)
       5 [0x7f3c99f41d52]: /lib/x86_64-linux-gnu/libc.so.6(+0xedd52) [0x7f3c99f41d52] at 0x7f3c99f41d52 (/lib/x86_64-linux-gnu/libc.so.6)
       6 [0x7f3c99f4230b]: /lib/x86_64-linux-gnu/libc.so.6(+0xee30b) [0x7f3c99f4230b] at 0x7f3c99f4230b (/lib/x86_64-linux-gnu/libc.so.6)
       7 [0xaaa9b4]: remove_directory_recursive(char const*) at 0xaaa9b4 (/usr/bin/rethinkdb)
       8 [0xc1ecad]: directory_lock_t::~directory_lock_t() at 0xc1ecad (/usr/bin/rethinkdb)
       9 [0xc169d0]: main_rethinkdb_porcelain(int, char**) at 0xc169d0 (/usr/bin/rethinkdb)
       10 [0x7347de]: main+0x1fe at 0x7347de (/usr/bin/rethinkdb)
       11 [0x7f3c99e75ec5]: __libc_start_main+0xf5 at 0x7f3c99e75ec5 (/lib/x86_64-linux-gnu/libc.so.6)
       12 [0x741122]: /usr/bin/rethinkdb() [0x741122] at 0x741122 ()
error: Exiting.
Trace/breakpoint trap (core dumped)
```

Nothing special about my config other than setting the directory and bind all

**Comment by danielmewes** [comment]
For other readers: We found that manually initializing the directory through `sudo -u rethinkdb rethinkdb create -d /data/rethinkdb` avoids the issue on startup.

There's some inconsistency here which we need to look into.

**Comment by thinklinux** [comment]
I have the same problem. Making a directory with the right user and group permissions didn't help.

**Comment by Ralithune** [comment]
I had this problem today too; my RethinkDB instance went down yesterday for some reason with the following kernel messages:
`Jul 16 14:02:19 localhost.localdomain kernel: traps: rethinkdb[9442] trap int3 ip:af7ede sp:7fbbb0a2a620 error:0
Jul 17 08:27:11 localhost.localdomain kernel: traps: rethinkdb[21811] trap int3 ip:b11155 sp:7ffda738d8c0 error:0
Jul 17 08:31:06 localhost.localdomain kernel: traps: rethinkdb[22147] trap int3 ip:af7ede sp:7fd880a92510 error:0`

And this stack trace:

`Jul 17 08:30:58 localhost.localdomain rethinkdb[22025]: rethinkdb: master: Starting instance. (logging to `/var/lo
Jul 17 08:30:58 localhost.localdomain systemd[1]: Started LSB: This starts a set of rethinkdb server instances..
Jul 17 08:57:18 localhost.localdomain systemd[1]: Stopping LSB: This starts a set of rethinkdb server instances...
Jul 17 08:57:18 localhost.localdomain systemd[1]: Starting LSB: This starts a set of rethinkdb server instances...
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: rethinkdb: master: Starting instance. (logging to `/var/lo
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: Recursively removing directory /var/lib/rethinkdb/jarvis/t
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: In recursion: removing file '/var/lib/rethinkdb/jarvis/tmp
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: In recursion: removing file '/var/lib/rethinkdb/jarvis/tmp
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: Version: rethinkdb 2.3.5 (GCC 4.8.5)
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: error: Error in src/utils.cc at line 548:
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: error: Guarantee failed: [res == 0]  (errno 13 - Permissio
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: error: Backtrace:
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: error: Mon Jul 17 08:57:18 2017
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: 1 [0xb20f80]: backtrace_t::backtrace_t() at ??:?
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: 2 [0xb212e0]: format_backtrace(bool) at ??:?
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: 3 [0xd6d683]: report_fatal_error(char const*, int, char co
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: 4 [0xb11154]: remove_directory_helper(char const*, stat co
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: 5 [0x7efddcf29be6]: /lib64/libc.so.6(+0xeabe6) [0x7efddcf2
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: 6 [0x7efddcf2a13b]: /lib64/libc.so.6(+0xeb13b) [0x7efddcf2
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: 7 [0xb12053]: remove_directory_recursive(char const*) at ?
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: 8 [0xb123da]: recreate_temporary_directory(base_path_t con
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: 9 [0xc58bf0]: main_rethinkdb_porcelain(int, char**) at ??:
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: 10 [0x7e361e]: main+0x1fe at ??:?
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: 11 [0x7efddce60b35]: __libc_start_main+0xf5 at 0x7efddce60
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: 12 [0x7ee505]: /usr/bin/rethinkdb() [0x7ee505] at 0x7ee505
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: error: Exiting.
Jul 17 08:57:18 localhost.localdomain systemd[1]: rethinkdb.service: control process exited, code=exited status=13
Jul 17 08:57:18 localhost.localdomain rethinkdb[22729]: /etc/rc.d/init.d/rethinkdb: line 115: 22842 Trace/breakpoi
Jul 17 08:57:18 localhost.localdomain systemd[1]: Failed to start LSB: This starts a set of rethinkdb server insta
Jul 17 08:57:18 localhost.localdomain systemd[1]: Unit rethinkdb.service entered failed state.
Jul 17 08:57:18 localhost.localdomain systemd[1]: rethinkdb.service failed.`

For whatever reason, running rethinkdb after commenting out "directory=/var/lib/rethinkdb/jarvis" in the config file worked, so I un-commented it (to put it back) and ran the following:
`cd /var/lib
chown -R rethinkdb rethinkdb
chgrp -R rethinkdb rethinkdb`

And that fixed it.
