### ISSUE TITLE
Returning top level attributes within nested queries 

### ISSUE THREAD

**Issue by carlskii** [rethinkdb/rethinkdb#5831]
Not quite sure the best way to explain this, but here goes.

When I run my rethink nested queries I need to include in my document output the values of items one level below my document root, called `title`. However, to get the required data I need to concatenate some of the nested elements and then perform the query. This means that the top level items don't get returned. 

Here's an example of my query:

```python
r.db('test').table("data")\
    .concat_map(lambda doc: doc["items"]) \
    .filter(lambda sa: sa["level1"]["level2"] == "foo") \
    .concat_map(lambda x: x["details"]["detail1"])\
    .filter(lambda x: x["data"]
    .match("^Hello")) \
    .run()
```

So this returns the documents that match `["level1"]["level2"]` with a value of `foo` & `["details"]["detail1"] ["data"] that begins with `Hello`. 

However, the problem is made somewhat more complex because `items` is an array which means I need to add the `title` to each of the 'items' in order to get what I need to be returned. 

So my question is, how can I include a top level attribute called `title` within my document `items` results. 

I think I should be using the `merge` function to restructure my output document, but I'm not completely sure how to build the extra part of the query.

**Comment by danielmewes** [comment]
Something like this maybe:
```py
r.db('test').table("data")\
    .concat_map(lambda doc: doc["items"]
      .filter(lambda sa: sa["level1"]["level2"] == "foo") \
      .concat_map(lambda x: x["details"]["detail1"])\
      .filter(lambda x: x["data"]
      .match("^Hello")) \
      .merge({"title": doc["title"]})
    )
    .run()
```

I basically just moved all the filtering steps inside the first concat_map, so that the `doc` variable is still available at the end. There are probably some other options for doing this as well.

**Comment by carlskii** [comment]
Thanks for this. This worked perfectly. Shame I wasted all day trying to work it out though. It would be really good to see some more advance examples in the docs or somewhere.
