### ISSUE TITLE
Building an ejabberd like chat system (with groups)

### ISSUE THREAD

**Issue by Rajan** [rethinkdb/rethinkdb#5832]
Is it possible to build ejabberd like chat system with groups using Rethinkdb?

Questions: Protocol being used by RethinkDB clients? I read it's TCP. How different is that compared to popular MQTT protocol for low battery consumption in the mobile devices. Are there benchmarks available comparing MQTT battery usage compared to say Swift client battery usage?

The sequence of messages received in the group chat is critical. How accurately does RethinkDB handle that given the network QoS may differ for the different set of users?

Latency comparison relative to ejabberd like systems?

**Comment by danielmewes** [comment]
Note that RethinkDB is not intended to be accessed directly by users of your application / chat system. RethinkDB's security model is insufficient for that usage scenario.

You might want to check out Horizon (http://www.horizon.io), which is intended for that scenario. It uses websockets underneath. Horizon is pretty new, and we haven't done any benchmarks of battery usage yet.
