### ISSUE TITLE
facing problem upgrade in 2.2.2 to 2.3.3

### ISSUE THREAD

**Issue by gmchaturvedi1** [rethinkdb/rethinkdb#5833]
Dear friennds,

i have installed rethinkdb and working in version 2.2.2. but now when i build the latest version as decribed in docs still old version is running .Because i am using currunt client driver so server is denying to accept connection. 

i have setup init stcript as suggested in docs . 

but when i start rethinkdb command from commandline my fresh installation work but on init it is working old one. 

kindly suggest me.

**Comment by danielmewes** [comment]
Did you build from source? Had you installed 2.2.2 the same way or did you use a package for it?

If you had installed RethinkDB 2.2.2 through a package before, you should uninstall that first (`sudo apt-get remove rethinkdb` if you're on Ubuntu or Debian).
Try running `sudo make install` in the 2.3.x source directory to install the new version. Then restart the server.

**Comment by danielmewes** [comment]
Until you get it working, you can also install the older 2.2 driver. Just follow the instructions here: https://www.compose.io/articles/compose-and-rethinkdb-23-drivers/
