### ISSUE TITLE
start/stop script

### ISSUE THREAD

**Issue by kodermax** [rethinkdb/rethinkdb#5834]
Do you have a startup/stop script for Centos?

**Comment by danielmewes** [comment]
Yes, the CentOS packages install a init script in /etc/init.d/rethinkdb. You can also find the script at https://github.com/rethinkdb/rethinkdb/blob/next/packaging/assets/init/rethinkdb .

You just have to place a configuration file in `/etc/rethinkdb/instances.d` to enable it. See http://rethinkdb.com/docs/start-on-startup/ for more details.

**Comment by kodermax** [comment]
Thanks
