### ISSUE TITLE
sudo /etc/init.d/rethinkdb restart

### ISSUE THREAD

**Issue by gmchaturvedi1** [rethinkdb/rethinkdb#5836]
i have norw working rethinkdb installation but init script not found in 
sudo /etc/init.d/rethinkdb restart

kindly suggest.

Regards
G M

**Comment by danielmewes** [comment]
How did you end up installing RethinkDB? You can grab the init script from https://raw.githubusercontent.com/rethinkdb/rethinkdb/next/packaging/assets/init/rethinkdb .

**Comment by gmchaturvedi1** [comment]
Thanks its done
