### ISSUE TITLE
Can't restore on Windows from a dump on Mac/Linux

### ISSUE THREAD

**Issue by frankdugan3** [rethinkdb/rethinkdb#5839]
Dumping and restoring has been fixed for Windows, provided that the `dump` occurs on Windows.

My issue is that I have a development template DB dumped from Mac/Linux that I would like to restore on Windows. Now I'm still having the old issue, ref: https://github.com/rethinkdb/rethinkdb/issues/5505 and https://github.com/rethinkdb/rethinkdb/issues/5399

I understand not wanting to change the default dump naming scheme for Mac/Linux to preserve any scripts that may depend on it.

Could there be a flag or naming option that uses a format friendly for all platforms? Even when I specify the filename and db with `-e` and `-f`, `dump` still nests a folder with the timestamp that breaks restore on Windows. There should be some solution that doesn't involve manually extracting, renaming, then recompressing the dump file.

**Comment by danielmewes** [comment]
Thanks for the issue report @frankdugan3 .

I'd like to think about this a little.

I think we could generally change the name of the folder that's inside the archive with RethinkDB 2.4. For 99% of users, this wouldn't break any scripts, because the `.tar.gz` file would still have the same name on Linux and OS X. Just the name of the folder that's packed up inside the archive would be different.

**Comment by frankdugan3** [comment]
Sounds good to me, thanks for looking into it.

**Comment by larkost** [comment]
Beyond changing the internal folder name to make it compatible everywhere (generically that sounds good to me), fixing #3755 would also get around this issue completely (even for older `export`s). That way we would never have to have the file on the filesystem at all.

The work I am doing on these scripts for #5147 should make this easier (but not make it done).

**Comment by larkost** [comment]
Just after commenting, it occurred to me that we could make the current method backwards compatible by specifically translating the non-Windows naming style and converting it as we are making the temporary files. That could be done with relatively little code in the driver as-is.

**Comment by larkost** [comment]
I have an initial version of a fix for this in branch `larkost/5839-windows-restore`.

**Comment by larkost** [comment]
This took a little longer than expected to test, as I found a number of issues in supporting both native Python on Windows, and Python running in Cygwin. I think those are all hammered out and in `next` with 9a11580f after review in CR 3689 from branch `larkost/5839-windows-restore`.

With these changes in place you can restore `dump`s made on linux using Pyton running on Windows. As an added bonus, if you are sending the data in through `stdin` on linux we now do not write that file onto disk before decompressing it (sadly still to disk).
