### ISSUE TITLE
Group by custom function and multi: true

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#5845]
This query
```javascript
r.table("foo").group("tags",{multi: true})
```
returns a different result than this query
```javascript
r.table("foo").group(row => row.pluck("tags"),{multi: true})
```

What should be the right way?

**Comment by danielmewes** [comment]
`pluck` still returns an object with the single `tags` field, so `multi` doesn't really work on that since it requires an array.

The correct version for the lambda syntax would be:
```js
r.table("foo").group(row => row("tags"),{multi: true})
```
