### ISSUE TITLE
Compression of object keys

### ISSUE THREAD

**Issue by foxx** [rethinkdb/rethinkdb#5848]
Am I correct in saying that object keys do not have any sort of compression or optimization?

For example, if I inserted `{'my_super_long_key_here': 'jessica'}` 5 times, would this result in 22 bytes being written to disk for every time that key is used? Or is there some sort of compression or pointer/ref used to prevent duplicates?

Possibly related to #1396.

**Comment by danielmewes** [comment]
You are correct that there is currently no such compression.

The issue you found #1396 is relevant, as well as the more specific https://github.com/rethinkdb/rethinkdb/issues/4397 .
