### ISSUE TITLE
Websocket "heartbeat" frequency

### ISSUE THREAD

**Issue by babakness** [rethinkdb/rethinkdb#5849]
How does one configure the "heartbeat" frequency of the realtime Websocket connection? Is this passed through to Horizon or is that a different setting?

**Comment by danielmewes** [comment]
RethinkDB doesn't have any websocket interface. I assume your question applies to Horizon (which has its own issue tracker https://github.com/rethinkdb/horizon/issues ).

Currently Horizon uses engine.io , which might have a setting to tweak the heartbeats. Horizon doesn't explicitly expose the option, so you'd need to modify the Horizon client and/or Horizon server code.

Be advised though that Horizon is going to switch away from engine.io . At that point there will be an option to control the frequency of hearbeats. See https://github.com/rethinkdb/horizon/issues/527

**Comment by babakness** [comment]
Ah, OK. This is what sparked the question (scaling)

https://www.built.io/blog/2014/11/websockets-on-aws-elb/

In the comments from link:

> This issues seems to be happening because of the Idle timeout for requests in Amazon’s ELB, which is by default, 60 seconds.
> 
> You can find ‘Connection Settings’ attribute under ‘Description’ tab for ELB in AWS console. It can be modified as needed.
> 
> You have also mentioned heartbeat mechanism is in place, in such case, you’d need to ensure heartbeat frequency is less than 60 seconds to avoid losing the WebSocket connection.
>
