### ISSUE TITLE
POJO conversion not working for List results

### ISSUE THREAD

**Issue by cluttered-code** [rethinkdb/rethinkdb#5859]
``` java
try (final Connection conn = r.connection().db(DB_NAME).connect()) {
    final List<Campus> results = r.table("campuses")
            .orderBy("name")
            .skip(0)
            .limit(25)
            .run(conn, Campus.class);

    results.get(0).getId();
}
```

On the last line I get the following error:
**java.lang.ClassCastException: java.util.HashMap cannot be cast to com.blah.foo.Campus**

**Comment by deontologician** [comment]
Hi @cluttered-code, what kind of data types do you have in the Campus documents?

**Comment by cluttered-code** [comment]
Strings and OffsetDateTimes. It works properly if I retrieve one item or if
I get a Cursor, just not with the List.

Cheers

**Comment by deontologician** [comment]
Hmm, now that I'm thinking about it, assigning it to a list seems like it shouldn't work statically. I may have forgotten us adding that feature though. Does this work:

```java
final List<Long> results = r.expr(r.array(1,2,3)).run(conn);
```

**Comment by cluttered-code** [comment]
That works, it also works with Strings and OffsetDateTimes properly. But when I use my POJO that contains Strings and OffsetDateTimes it doesn't work.

**Comment by adriantodt** [comment]
This is now implemented to one of the branches (https://github.com/rethinkdb/rethinkdb-java/pull/12) of the Java driver, which now lives in a separated repository (https://github.com/rethinkdb/rethinkdb-java). This issue can be closed.

**Comment by adriantodt** [comment]
This is now implemented to one of the branches (https://github.com/rethinkdb/rethinkdb-java/pull/12) of the Java driver, which now lives in a separated repository (https://github.com/rethinkdb/rethinkdb-java). This issue can be closed.
