### ISSUE TITLE
Changes: handling timeouts in RethinkDB/Dash

### ISSUE THREAD

**Issue by hgill** [rethinkdb/rethinkdb#5860]
This is a repost of https://github.com/neumino/rethinkdbdash/issues/261
More relevant here.

First off, not sure if this is a feature request or an issue or am I just missing something.

I have been able to set up change feeds successfully - so that RethinkDB informs the Nodejs server when changes happen to a table's documents and Nodejs in turn passes it on. But am stuck on trying to apply (Now-15minutes) on changefeeds. Think this can help make some powerful apps

Some usecases

E.g. 1:
I would like RethinkDB to tell my app server that my cached copy of data has become old enough and I should refresh it.

E.g. 2
I can store all front-end click-stream data in localStorage and when RethinkDB says that we should sync that data, 2 minutes have passed, then the server can ask frontend to send it.

E.g. 3
My Usecase:
I am building a crawler/rss feed parser with RethinkDB and Nodejs.
Now, I need to set up a time-bound refresh on the non-pubsubhubbub feeds I pull. So, if 15 minutes have passed since last refresh on any feeds in my table, go again.

lastUpdated timestamp in document. I would like to use it like this:

```
    r.db('test').table('test')
        .filter(doc=>{
            return doc('lastUpdated').lt(new Date()-15*60000);
        }).changes().run()
        .then(change=>{
             change.on('data',()=>{
                      //parsing logic
                      //This will run all day, with rethinkDB popping feeds to server as they become old
                      //- so for a 1000 feeds, 1 change initiated by RethinkDB every 900 ms. 
                      //Hope you get the idea
            })
        });
```

The above code doesn't work as I want it to (although it works as I expect it to)
Looks like the "new Date()" I provide is taken as the moment when the change feed was set up.

Or is there another way to do this that I am missing?

Else, Is it possible to add that functionality to RethinkDB/dash? Not sure if there are performance implications?

**Comment by danielmewes** [comment]
@hgill Check out https://github.com/rethinkdb/rethinkdb/issues/5823 .
While the functionality described in that issue doesn't directly allow you to open a changefeed that includes the current time, it will allow you to automatically flag documents that are older than 15 minutes by setting an "outdated" field on them (or similar). You can then create an index and open a changefeed on that field, which will give you the functionality you need.

There are some details to how you'd need to set this up that I'm happy to explain once we have agreed on a full API in #5823. Please feel free to ping me on this issue again when that is done so I don't forget.

This is also related to some of the things discussed in https://github.com/rethinkdb/rethinkdb/issues/3583 , though the original proposal in that issue had a more limited scope.

I'm going to close this as a duplicate as we've discussed related things in other issues and there's soon going to be a solution for doing what you need. Let me know if you feel like the existing issues don't sufficiently cover your use case.

**Comment by hgill** [comment]
Sure, Thanks, that'll work great.. Thanks for the detailed direction, it helps me make a polyfill mocking the operation rather than starting from scratch.
