### ISSUE TITLE
Feature request: add stats about rows retrieved to profiling info

### ISSUE THREAD

**Issue by tve** [rethinkdb/rethinkdb#5861]
When using mysql I find the "number of rows examined" shown in the slow query log or the similar "rows" shown in an explain statement very helpful. For example, when you see "10 million rows examined 10 returned" you know you have an indexing problem.

It would be awesome for rethinkdb's profile info to return info about how many rows/objects were retrieved from "table storage" during a query, and/or the number of bytes retrieved.

A concrete use-case that goes beyond the "I wonder why this query is slow" is that I am letting customers of my system perform powerful queries which have the notion of using an index and I need to establish some quota to force customers to think about their queries. I wanted to formulate those quotas in terms of number of objects retrieved/scanned since that is one of the major costs (I expect). I don't want to formulate the quotas in terms of execution time because that can vary wildly for the same query depending on HW configuration and other load on the system.

**Comment by danielmewes** [comment]
Thanks for opening a feature request about this @tve.

We'll see how hard this will be to add.

**Comment by GeoffreyPlitt** [comment]
+1!

**Comment by AtnNn** [comment]
8669

**Comment by GeoffreyPlitt** [comment]
@AtnNn There is no https://github.com/rethinkdb/rethinkdb/issues/8669, did you get the right number?
