### ISSUE TITLE
Rejected a connection from server X since one is open already.

### ISSUE THREAD

**Issue by ddombrow** [rethinkdb/rethinkdb#5862]
Getting error messages like the title constantly running in a cluster on AWS behind VPC.

Version is rethinkdb 2.3.2~0trusty

There does not appear to be an actual problem and all three servers are operating normally, each one throws this message about every 5 seconds about the other two servers in the cluster:

```Rejected a connection from server <server-id> since one is open already.```

Has been throwing these for hours.

**Comment by danielmewes** [comment]
Thanks for reporting this @ddombrow .
This sounds like https://github.com/rethinkdb/rethinkdb/issues/5456#issuecomment-212798522 We thought we had fixed it, but this is now the second reported case where the issue still appears to be happening. I'm going to re-open issue #5456 and close this as a duplicate.
