### ISSUE TITLE
Using RethinkDB to implement a persistent BehaviorSubject

### ISSUE THREAD

**Issue by tmds** [rethinkdb/rethinkdb#5863]
I am creating this issue to explain a use-case and get feedback on how well it matches with RethinkDB.

A BehaviorSubject in Reactive Extensions is:

> Represents a value that changes over time. Observers can subscribe to the subject to receive the last (or initial) value and all subsequent notifications.

There are two operations:
- next: which updates the current value
- subscribe: which fetches the latest value and updates

How to make it persistent by storing in RethinkDB?

You could have a table 'subscriptions' with documents that look like:
```
{
   key: "this.is.my.subscription.id"
   value: "this is my subscription value"
}
```

The above operations have these characteristics:
Every subscribe (query) ever performed on this table would always have a key to match a single document.
Every next (update) would never change the key of an existing document, but it can potentially change the value significantly (e.g. taking up more/less space).

Does RethinkDB lend it towards this use-case? Would the subscriptions table be a good approach?

**Comment by danielmewes** [comment]
> Does RethinkDB lend it towards this use-case? Would the subscriptions table be a good approach?

The approach looks reasonable to me. I recommend setting the `key` field as the primary key in the table (it's an option to `tableCreate`, see http://rethinkdb.com/api/javascript/table_create/ ). You can easily use changefeeds on a `get` query then to implement the `subscribe` functionality.

Size changes in the value aren't an issue. Note though that the complete value will be rewritten whenever it changes, so performance might suffer a bit if the values get very large and are updated frequently.
