### ISSUE TITLE
Duplicate primary key not thrown on all machines

### ISSUE THREAD

**Issue by drejc** [rethinkdb/rethinkdb#5866]
I have the following set up.

3 different machines run simultaneously listen to database changes on a table (this is a queue for tasks).
Once a record is inserted they all try to take this task and execute it, therefore I have created a new table that inserts a lock record setting the task id (as key) and the executor (the machine contending for the task) as additional data. 

Locally I have tested it out with 10 threads and 100 tasks on 2 nodes and everything works as expected. Only one executor gets one task.

But on production I can see that two executors get the same task, meaning the duplicate primary key is not thrown. Here are the logs I see ...

```
2016-06-17 08:21:46 [pool-9-thread-104] ubuntu-sb68 Task: a95246d5-502d-4de7-95b9-16c112c77817, locked for executor: WZLm8B7cjL
2016-06-17 08:21:45 [pool-9-thread-114] ubuntu-sb88 Task: a95246d5-502d-4de7-95b9-16c112c77817, locked for executor: Y65eeYfN0X
2016-06-17 08:21:45 [pool-9-thread-93] ubuntu-sb78 DB error response: DB error happened: deleted:0 inserted:0 unchanged:0 replaced:0 first_error:Duplicate primary key `id`: { "executor":	"Y65eeYfN0X", "id":	"a95246d5-502d-4de7-95b9-16c112c77817", "timestamp":	{ "$reql_type$":	"TIME", "epoch_time":	1466144505.658, "timezone":	"+00:00" } } { "executor":	"MF2ORuquFx", "id":	"a95246d5-502d-4de7-95b9-16c112c77817", "timestamp":	{ "$reql_type$":	"TIME", "epoch_time":	1466144505.659, "timezone":	"+00:00" } } errors:1 skipped:0 
2016-06-17 08:21:45 [pool-8-thread-1] ubuntu-sb88 Queue 'queue' new task: a95246d5-502d-4de7-95b9-16c112c77817 in state: queued, Y65eeYfN0X contending for task!
2016-06-17 08:21:45 [pool-8-thread-1] ubuntu-sb78 Queue 'queue' new task: a95246d5-502d-4de7-95b9-16c112c77817 in state: queued, MF2ORuquFx contending for task!
2016-06-17 08:21:45 [pool-8-thread-1] ubuntu-sb68 Queue 'queue' new task: a95246d5-502d-4de7-95b9-16c112c77817 in state: queued, WZLm8B7cjL contending for task! 
```

Let me explain how to read this ... so on the bottom we have 3 executors WZLm8B7cjL, MF2ORuquFx and Y65eeYfN0X, contending for the same task: a95246d5-502d-4de7-95b9-16c112c77817 

MF2ORuquFx recieves a duplicate primary key error (which is OK) so he is out of the game. Y65eeYfN0X does not. So task gets locked twice, which is not what should be happening.

What bugs me ... the error send to MF2ORuquFx, contains both errors ... for MF2ORuquFx and Y65eeYfN0X - he recieves both errors ... Y65eeYfN0X on the other hand gets none ... 

It seem to me ... that once the duplicate primary key error is consumed it is considered obsolete, so the third thread never gets informed.

I was trying to replicate this situation locally, but was unable to. It only happens in production with 3 separate machines running 3 RDB nodes, and 3 threads inserting a new record simultaneously.

We are currently running RethinkDB 2.3.2
Table config and write to table is set to: "durability":  "hard", "write_acks":  "majority"

Have I maybe found and bug, or is there some setting that I'm not aware of to fix this situation.

**Comment by danielmewes** [comment]
Which language are you using to implement this? Could you share the relevant parts of the code?
Are the threads sharing the same connection?

Does your code ever delete the "lock" documents again?

The `first_error` value that Y65eeYfN0X receives is definitely *very* weird. That value should never have more than one document in it, and here it seems to just have two documents right after each other.

This indeed looks like a worrysome bug. Possibly some sort of memory corruption? I would like to make sure that this is happening on the server though and not on the client.

**Comment by danielmewes** [comment]
Oh actually I was wrong about the message. It's format is as follows:
```C++
"Duplicate primary key `%s`:\n%s\n%s",
                     primary_key.c_str(), old_row.print().c_str(),
                     insert_row.print().c_str()
```

So the first document is the value currently in the table (in this case locked by Y65eeYfN0X), and the second value is the new document that the `insert` attempted to insert (here a lock for MF2ORuquFx). So that part is as expected.

**Comment by danielmewes** [comment]
This makes it less likely that this is a server bug. We should double-check the client code first.

**Comment by drejc** [comment]
We are using Java ... 
All three machine call the same insert statement ... at the same exact moment ... as the cursor kicks in at the same millisecond.

The code looks something like this ... 
(PS: we have our own rdb ORM wrapper which makes it easier to work with RDB, but nevertheless in the end it is a insert() call to the database).

So on a table we have a cursor listening for changes:

String executorId = generateRandomId();
for (Object change : cursor) {

   HashMap map = (HashMap) change;
   Object newValue = map.get("new_val");
 
  String taskId = // get fro newValue
   lock(taskId, executorId);
}

// the lock method inserts a new record into the table the taskId being the key
protected boolean lock(String executorId, String taskId) {

QueueTaskLock lock = rdb.get(QueueTaskLock.class, taskId);

		// we can lock task
		if (lock == null) {

			lock = new QueueTaskLock(taskId, executorId);
			try {
				rdb.create(lock);
			}
			catch (RdbException e) {
				// lock already in place ...
				if (RdbException.Error.DuplicatePrimaryKey.equals(e.error)) {
					log.debug("Executor: " + executorId + " denied lock of: " + taskId);
					return false;
				}

				log.debug("Exception thrown but not duplicate key: " + e.getMessage());
				return false;
		}

		// check if this task is locked by same executor
		return lock.isLockedBy(executorId);


As I have mentioned ... I could not replicate this locally ... was running 3-4 nodes and 10 threads in a unit test ... all worked fine.
In production however we have 3 machines / 3 nodes ... there it happens.

**Comment by danielmewes** [comment]
Does the lock entry ever get removed? Could it get removed too quickly, allowing another node to acquire the lock afterwards?

**Comment by drejc** [comment]
The lock does gets removed when the task is finished (this should take at least some seconds) ... will add some additional log messages to see the time when this happens. It might be that the task is quicker then expected - thanks for pointing that out.

**Comment by danielmewes** [comment]
@drejc Thanks for updating us on this!
