### ISSUE TITLE
unique field?

### ISSUE THREAD

**Issue by chovy** [rethinkdb/rethinkdb#5869]
Is it possible to have a unique field in a table `accounts` like `username` and `email`?

The only post I could find was from 3 years ago (https://stackoverflow.com/questions/17789123/how-to-create-unique-items-in-rethinkdb). Seems like a rudimentary thing as I'm starting a project with rethink because of its live change feeds. But if there's no way to get past creating a unique username then I don't know if this is the right db for me.

**Comment by chovy** [comment]
Its not a composite unique key. I only want one unique email to be registered in a table....same for username.

Is there any chance we can get a complete example with CRUD operations to the docs? I think a lot of people are going to run into this as I keep hearing about rethinkdb more. I know it would be extremely helpful for me to see a working example to manage these associations.

**Comment by danielmewes** [comment]
@chovy We have an issue about this in https://github.com/rethinkdb/docs/issues/500 . It has been open for a while and we haven't started working on this. I'll see if we can schedule the docs issue some time soon.
