### ISSUE TITLE
How to get property value in filter?

### ISSUE THREAD

**Issue by chrisabrams** [rethinkdb/rethinkdb#5881]
How do you get the value of a property in filter, such as below?

    .filter(function(doc) {
       console.log(doc('first_name'))
    })

I need to know the value of a property in filter to determine whether or not to return true/false.

Ive also tried `console.log(doc('first_name').coerceTo('string'))` but that didn’t work either.

The value returned is `var_3`, which is related to RethinkDB/REQL.

**Comment by deontologician** [comment]
It isn't possible to put a `console.log` into a ReQL function. What happens is `console.log(x)` gets evaluated and returns `undefined`, then your function becomes "takes any document and always returns undefined", and then the filter is run with that. So it looks like you're just using a javascript function, but really it can't run any javascript, it has to return a reql expression.

A good way to test if your filter is working correctly, is to turn it into a `.map`, run it to see what's going on and if it's doing what you expect, and then turn it back into a `.filter`

**Comment by danielmewes** [comment]
@chrisabrams If you want to learn more about how functions in ReQL work, I can recommend this old but still correct blog post: http://rethinkdb.com/blog/lambda-functions/

**Comment by chrisabrams** [comment]
Thanks @danielmewes that article is very helpful in understand what's going on.
