### ISSUE TITLE
Order of group results

### ISSUE THREAD

**Issue by chrisfosterelli** [rethinkdb/rethinkdb#5883]
In a `group` query, based on [the documentation](https://www.rethinkdb.com/api/javascript/group/) and my testing, it appears that the results are sorted by the `group` field of each document in the resulting array.

Is this guaranteed? I could not find anything in the documentation confirming this one way or the other.

**Comment by danielmewes** [comment]
I suspect that this is always the case in practice because we internally store the groups as an ordered map before converting the result into an array.

This is not an official guarantee though, and might change if we add support for streaming grouped results to the client in the future.

**Comment by chrisfosterelli** [comment]
Fair and makes sense, thanks @danielmewes!
