### ISSUE TITLE
Connecting existed rethinkDB with Rails App

### ISSUE THREAD

**Issue by p29892p** [rethinkdb/rethinkdb#5888]
When i created a new rails app and added required gems to connect rethinkDB. It automatically creating it's own named database in rethink server, but how can i connect already existed rethink database to Rails app?

**Comment by bsharpe** [comment]
check out http://nobrainer.io

**Comment by danielmewes** [comment]
I replied to this on Google groups: https://groups.google.com/forum/#!topic/rethinkdb/pdi2Xn6G5bk
