### ISSUE TITLE
Changefeed documentation: includeStates mentioned instead of includeTypes

### ISSUE THREAD

**Issue by rdunnington** [rethinkdb/rethinkdb#5907]
In the _Including result types_ subsection on the _Changefeeds in RethinkDB_ page, the documentation mentions:

> The `includeStates` optional argument adds a third field, `type`, to each result sent. The string values for `type` are largely self-explanatory:

I believe it should read:

> The `includeTypes` optional argument adds a third field, `type`, to each result sent. The string values for `type` are largely self-explanatory:

Looks like it has the same problem for all languages (javascript, python, ruby, and Java).

https://rethinkdb.com/docs/changefeeds/javascript/

**Comment by larkost** [comment]
Thanks for spotting this @rdunnington! I am moving it over to our docs repository where it can be taking care of: rethindb/docs#1151

**Comment by rdunnington** [comment]
You're welcome! :)

Reuben
