### ISSUE TITLE
.not() should be .not_() in Python documentation

### ISSUE THREAD

**Issue by coffenbacher** [rethinkdb/rethinkdb#5908]
Minor error but this cookbook example produces a syntax error:

```
SELECT * FROM users
WHERE name NOT IN ('Peter', 'John')
----
r.table("users").filter(lambda doc:
    r.expr(["Peter", "John"])
        .contains(doc["name"])
        .not()
)
```

https://www.rethinkdb.com/docs/sql-to-reql/python/

**Comment by larkost** [comment]
Thanks for pointing this out @coffenbacher, I am moving this issue over to our docs repository: rethinkdb/docs#1150
