### ISSUE TITLE
Python Twisted Driver Unexpected Timeout

### ISSUE THREAD

**Issue by jonhartnett** [rethinkdb/rethinkdb#5909]
When using the Twisted Drivers for Python, the connection to the database times out a small (but detrimental) percentage of the time, despite working perfectly the rest of the time. Both the server and the client are on one machine in my use case, so network related issues are not the culprit. Upon further digging, I discovered that this is due to the handshake never completing. Turns out in some cases the database server sends the authentication response in the same message as the protocol versioning.
For example 

```
b'{"max_protocol_version":0,...,"success":true}\x00{"authentication":"...","success":true}\x00'
```

instead of the usual

```
b'{"max_protocol_version":0,...,"success":true}\x00'
b'{"authentication":"...","success":true}\x00'
```

This invalidates the handshake because the driver (in net_twisted.DatabaseProtocol._handleHandshake) only processes the first block of data from each response. Luckily the solution is quite simple. Simply wrap the processing in a while loop and the issue disappears.

```
def _handleHandshake(self, data):
        try:
            self.buf += data
            while True: # wrap processing in 'while' to handle all messages
                end_index = self.buf.find(b'\0')
                if end_index != -1:
                    response = self.buf[:end_index]
                    self.buf = self.buf[end_index + 1:]
                    request = self.factory.handshake.next_message(response)

                    if request is None:
                        # We're now ready to work with real data.
                        self.state = DatabaseProtocol.READY
                        # We cancel the scheduled timeout.
                        self._timeout_defer.cancel()
                        # We callback our wait_for_handshake.
                        self.wait_for_handshake.callback(None)
                    elif request != "":
                        self.transport.write(request)
                else: # break when no more completed messages
                    break
        except Exception as e:
            self.wait_for_handshake.errback(e)
```

**Comment by danielmewes** [comment]
Thanks for the bug report and proposed fix @jonhartnett .

Pinging @Tryneus .

**Comment by srh** [comment]
Thanks, this'll make it into 2.4.
