### ISSUE TITLE
Add easy way to remotely establish version of nodes

### ISSUE THREAD

**Issue by codepope** [rethinkdb/rethinkdb#5920]
Have been trying to find any way of identifying what version a RethinkDB node is running. (Am thinking in terms of reporting tools connecting and getting versions for validating compliance... also thinking for double checking self). Can't find anything and suspect it might be useful either added to a cluster's tables or standalone.

**Comment by larkost** [comment]
This information is in the `rethinkdb.server_status` table. Here is a snippet you can use in the data explorer to get this:

`r.db('rethinkdb').table('server_status').pluck([{'process':{'version':true}}, 'id', 'name'])`

I am going to close this, as there does not seem to be a bug here. But feel free to ask more questions in this issue.

**Comment by codepope** [comment]
I note that, but that is returning not just version but build, platform and compiler (and process name). Yes, notabug though.
