### ISSUE TITLE
Bad error message when `eachAsync` row handler returns a promise which resolves to something besides undefined

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#5931]
If you write this:

```
cursor.eachAsync(() => new Promise((res) => {res(0)}));
```

You get the error:

```
Unhandled rejection ReqlDriverError: Row handler for eachAsync may only return a Promise or undefined.
```

---

The error message doesn't clearly communicate that in addition to the row handler returning a Promise or undefined, the Promise it returns has to resolve to undefined (or another Promise, presumably).  It took me a long time to figure out what was wrong.  (The behavior makes sense after thinking about it, though; returning a promise which resolves to something would require throwing that value away, which is sketchy.)

This is really easy to run into, because if you hit it if you try to issue a write for everything in the cursor:
```
cursor.eachAsync((c) => {
  return someWrite(c).run(conn);
})
```

**Comment by nighelles** [comment]
This is in next.
