### ISSUE TITLE
Database is deleted

### ISSUE THREAD

**Issue by thatsVishal** [rethinkdb/rethinkdb#5933]
Hey RethinkDB team,

**This is really a serious issue**. I am using rethinkdb database for my new project. I created a database it was working perfect, but suddenly the next day when i was trying to connect to database it gave me error  **Database `database_name` does not exist in:  r.db("database_name").table("table_name").get(id)** 

At a moment I thought I wrote wrong query so I went and checked the query through web interface and I was surprised to see the database that i created didn't exist.. The entire database was lost.. all the tables created and all the data in it is gone..!! I remember that I have never dropped the database, I have even checked the log but the log showed all the entries of the current day. I have no idea why this happened. Thank god that I found this before I put this into production.

**Comment by danielmewes** [comment]
@thatsVishal If you start `rethinkdb` on the command line and don't pass it any `-d` parameter to specify a different data directory, it creates a data directory called `rethinkdb_data` in the current path.

What you describe sounds consistent with starting RethinkDB in a different directory afterwards. Search your file system for `rethinkdb_data`, and you will probably find the old data files. Then you can pass the correct data path to `rethinkdb` through the `-d` parameter and your data should be accessible again.

**Comment by danielmewes** [comment]
(Keeping open until we get confirmation for the suspected cause)

**Comment by thatsVishal** [comment]
woah right..!! I had started it from another directory thats why it was showing the error.. when I started rethinkdb from the directory where I had created all my database and tables i.e. root directory I was able to find my database.. Thanks a lot.. and I appreciate your quick response for this :+1: you can close this issue..
