### ISSUE TITLE
buggy reading of "data distribution" at admin interface

### ISSUE THREAD

**Issue by ha1331** [rethinkdb/rethinkdb#5936]
Here be the example:
![datadistribution](https://cloud.githubusercontent.com/assets/8921895/16738311/d8462b34-479d-11e6-8d78-80c8325455e2.PNG)

**Comment by danielmewes** [comment]
Thanks for reporting it @ha1331 .

This is actually a duplicate of https://github.com/rethinkdb/rethinkdb/issues/4907 .
