### ISSUE TITLE
Async drivers' Tornado example

### ISSUE THREAD

**Issue by arnau** [rethinkdb/rethinkdb#5939]
Hi, this is a small Python syntax issue in https://rethinkdb.com/blog/async-drivers/

In the example

```python
import rethinkdb as r
from tornado import ioloop, gen

r.set_loop_type("tornado")

@gen.coroutine
def print_changes():
    conn = yield r.connect(host="localhost", port=28015)
    feed = yield r.table("table").changes().run(conn)
    while (yield feed.fetch_next())
        change = yield feed.next()
        print(change)

ioloop.IOLoop.current().add_callback(print_changes)
```

I would have expected line 10 (`while (yield feed.fetch_next())`) to end with a colon (`:`).

**Comment by danielmewes** [comment]
Thanks for the bug report @arnau . I moved it to our documentation issue tracker: https://github.com/rethinkdb/docs/issues/1157
