### ISSUE TITLE
Creating multi-index after inserting data results in 10x smaller database size

### ISSUE THREAD

**Issue by Calavoow** [rethinkdb/rethinkdb#5942]
When creating a database we usually create indices when setting up the database. But this resulted in some unusually large index sizes for multi-indexes. After playing around a bit it seems that first importing the data and then adding the indices results in a 10x smaller database file size compared to first creating indices and then inserting the data.

I have uploaded files with which I can reproduce this behaviour here: https://gist.github.com/Calavoow/c6d6b2d58635e003ffcc8ea7da1795fa
First generate items for the db with the generate script. Then set up the database without the index. Import the json with the command from the generate script. Then create an index with
```js
        r.db('multibloat').table("multibloat").indexCreate("byTagTitle", function( row ){
            return row('full_tags').map( function( tag ){
                return [row('view_id'), tag, row('title').downcase()];
            });
        }, {multi: true})
```
Compare the resulting database size to the one with the index created at setup time (remove the comment slashes from setup.js) and then the data imported.

I get the following difference. Index created before inserting data:
```
3.3G Jul 13 14:15 d2f699c2-fffd-4a7c-ade3-488d76ec9935
```
After:
```
646M Jul 13 14:14 71e0a88b-888f-4bad-a89f-5e2e46878d3f
```

Could be related to #5923

**Comment by danielmewes** [comment]
Thanks for reporting the issue and for providing a test script for reproduction.
I think this very likely has the same cause as https://github.com/rethinkdb/rethinkdb/issues/5923 . I'm merging this with the other issue.
