### ISSUE TITLE
improve documentation of update() to mention the fact that filter is not atomic

### ISSUE THREAD

**Issue by ha1331** [rethinkdb/rethinkdb#5951]
Had conversations with users at slack and noticed that the documentation of .update() does not mention anything about how filter/getAll/between could "see" different data that you update (because the document might have been changed after the reading of the table is done, but before the updating is done). There is an example on how to perform conditional update, but it doesn't explain why one would want to do that. I believe some users might think that filtering the documents for update quarantees that you only update the intended documents.  I am refering to what was discussed at #3992  , In my opinnion this is quite relevant information to know when one uses rethink.

**Comment by Calavoow** [comment]
Shouldn't this be posted under https://github.com/rethinkdb/docs?
