### ISSUE TITLE
CatThink example not working

### ISSUE THREAD

**Issue by lonnietc** [rethinkdb/rethinkdb#5956]
Greetings All,

Being new to RethinkDB, I am trying to get a feel for things by reading over the documentation as well as to run the RethinkDB examples (http://rethinkdb.com/docs/examples/)

On of the first examples that I have tried is the CatThink example (http://rethinkdb.com/blog/cats-of-instagram/).

I registered with Instagram and loaded up an instance of RethinkDB on my test server along with installing nodejs, but it seems that node will run the app.js, but it will not connect with Instagram.

Has anyone gotten this example to run recently, or is there another similar example that will demonstrate RethinkDB being able to externally connect to external API servers that I would download and try?

Any help would be greatly appreciated.

Cheers and have a great day,
Lonnie

**Comment by danielmewes** [comment]
Unfortunately that example no longer works as we recently learned, see https://github.com/rethinkdb/cats-of-instagram/issues/4

We just added a note to the CatThink README today, and are going to add another deprecation note to the blog post soon.
