### ISSUE TITLE
multiple proxy servers and load balancing with nginx problems

### ISSUE THREAD

**Issue by goors** [rethinkdb/rethinkdb#5963]
Hi,

i can not rely on just one proxy so I setup three proxy servers and one nginx load balancer. It turns out that, that setup has some problems. My node.js app is giving me this error:

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:893:11)
    at TCP.onread (net.js:555:26)
Program node server.js exited with code 1
```

I was not sure how to setup this load balancing with multiple proxies so I kind of asked and answer question here: http://stackoverflow.com/questions/38411303/how-to-use-nginx-load-balancing-with-rethinkdb-proxy

Funny thing is that this is working it is just after  requests to app goes up something everything stops and I am getting this types of errors.

I have tested connection with Python as well and everything work fine, it is just as requests goes up connection is reset.

I have no idea how to debug this and what to look for.
Maybe proxy is not designed to work like this.Anyway, any answer is more then welcome.

**Comment by goors** [comment]
It looks like my server max number of connections is wrong. I am sorry, this has nothing to do with rethinkdb.

**Comment by danielmewes** [comment]
No worries, glad you figured it out!

**Comment by assilabel** [comment]
hi !
 i have the same problem can you please explain me why it's happening in your case? and how did you fix it?
thanks :)

**Comment by goors** [comment]
I have put haproxy server in front of three proxy servers and that is how i solved this. i hope this helps you.
