### ISSUE TITLE
ASL 2.0 | MIT | BSD

### ISSUE THREAD

**Issue by sirinath** [rethinkdb/rethinkdb#5964]
It is possible to have the full stack under a more permissive license?

**Comment by danielmewes** [comment]
@sirinath That depends on what exactly you mean by more permissive. We offer commercial licensing in case you can't use AGPL software. If you're interested in commercial licensing options, please contact us via http://rethinkdb.com/services/ .

We're not planning to change the type of open source license at the moment.

**Comment by sirinath** [comment]
Is it possible to re open this in the light of the new development of the company behind RethinkDB shutting down.

**Comment by srh** [comment]
@sirinath There is discussion about this at https://rethinkdb.slack.com/messages/open-rethinkdb/ .
