### ISSUE TITLE
email is not saving correctly in database

### ISSUE THREAD

**Issue by gmchaturvedi1** [rethinkdb/rethinkdb#5976]
my command in explorer is as follow:

r.db('rojgaarwala').table('User').insert({'email':'raj@gmail.com'})

and saving output is :+1: 
{
"email": raj@gmail.com, »
"id":  "d6ee4424-db55-4abe-a233-ccf00a6ccda0"
}

kindly help me out on this.

**Comment by tatsujin1** [comment]
Uhm, it seems identical? What's the problem?

**Comment by gmchaturvedi1** [comment]
hi ,

my problem is solved .i am just equl the database email with req.email now it is working.

**Comment by VeXocide** [comment]
I'm closing the issue as the problem has been solved.
