### ISSUE TITLE
JS driver: `r.union` doesn't accept optarg

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5979]
We now have the `interleave` option for `union`. In the JavaScript driver, this option works when calling `union` as an infix operation (`seq1.union(seq2, {interleave: ...})`), but not when calling it with the prefix variant (`r.union(seq1, seq2, {interleave: ...})`).

**Comment by mlucy** [comment]
@danielmewes -- is this a duplicate of #5872 ?

**Comment by danielmewes** [comment]
It is, I completely forgot about that one. Thanks @mlucy
