### ISSUE TITLE
RethinkDB notify all user stored in a row

### ISSUE THREAD

**Issue by mkj-git** [rethinkdb/rethinkdb#5988]
I heard of RethinkDB. So started to explore it. I am looking for a particuler solution :

Whenever a new comment is posted, a notification should be sent to all other user who had commented on that post. A tradition solution is everytime a comment is posted, iterate through all user who commented and send them notification. But its a bit time consuming solution, cos evertime a new comment comes you have to iterate through all user.

The kind of solution I am finding (if possible through RethinkDB). I will maintain a record per post:

```
Table: PostComments
----------------------------
PostId=> user1, user2, user3.............userN
```

So if a new comment comes, i will just notify to "PostId" and as all "user" are there subscribed alreday, it should be notified automatically

**Comment by NicolasParada** [comment]
This isn't an issue. You should ask it on the chat https://rethinkdb.slack.com
