### ISSUE TITLE
OS X Instructions here: https://rethinkdb.com/docs/install/osx/

### ISSUE THREAD

**Issue by mintymac** [rethinkdb/rethinkdb#5995]
It's a small issue, but `curl` ships with Mac OS X.  So instead of using `wget` in the Mac OS X build instructions, it might be more consistent to use `curl -O https://download.rethinkdb.com/dist/rethinkdb-2.3.4.tgz` for instance.

**Comment by danielmewes** [comment]
Thanks for the suggestion. I moved your issue to the issue tracker on our documentation repository: https://github.com/rethinkdb/docs/issues/1163
