### ISSUE TITLE
I getting swap memory error and application server goes down 

### ISSUE THREAD

**Issue by tadesushilgithub** [rethinkdb/rethinkdb#6005]
Error: "Some rethinking data on this server has been placed into swap memory. This may impact performance". How to fix application server switch off after this. Having 16 GB RAM, 500 GB HDD, i5 processor.

**Comment by danielmewes** [comment]
I'm going to comment in https://github.com/rethinkdb/rethinkdb/issues/6003 , which is pretty much the same.
