### ISSUE TITLE
Verify & fix batching behavior for transformations on changefeeds

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#6007]
We found that at least `fold` and multi-stream `map` have bugs in how they handle batches when one of their inputs is a changefeed.

We should also check other terms that emit streams and can be applied on a changefeed (`concatMap`,  `filter` and maybe others).

@nighelles is currently working on this.

I think we should backport the fixes to `v2.3.x` as well.

**Comment by nighelles** [comment]
The issue we thought we had seen in map doesn't seem to be an issue. I'm looking into the other terms that can operate after a changefeed as well.

**Comment by danielmewes** [comment]
@nighelles Can you backport the fixes you did for the fold stream and the multi-map stream to `v2.3.x`, or is that tricky?

**Comment by nighelles** [comment]
This was fixed in next, and in v2.3.x in e2ab6b
