### ISSUE TITLE
On Windows: RethinkDB doesn't detect failure to bind port

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#6008]
I can start two RethinkDB server instances on Windows on the same TCP ports.

The second instance does not print any error, and pretends that it started listening, even though only the first instance receives incoming connections.

We are probably missing an error check somewhere.

**Comment by danielmewes** [comment]
@AtnNn Any ideas for this one?

**Comment by danielmewes** [comment]
A fix for this is in internal code review 3724 by @AtnNn .

**Comment by danielmewes** [comment]
Fixed in next via 438d384 . Still need to backport to the 2.3.x Windows branch.

**Comment by lbguilherme** [comment]
I think this was reopened by mistake.

**Comment by danielmewes** [comment]
I re-opened it so I don't forget to backport the fix to the 2.3.x branch.

**Comment by danielmewes** [comment]
Cherry-picked into v2.3.x-windows via 8f7ee62.
