### ISSUE TITLE
hidden memory leak when close Changefeeds cursor

### ISSUE THREAD

**Issue by QianJin2013** [rethinkdb/rethinkdb#6009]
hi, our team encountered a memory leak problem seems concerned with Cursor.close or connection.stop method, for Changefeeds cursor.

I am making a test case to prove it later. 

But now from static source analyze, i think there does have a problem. 
[drivers/java/src/main/java/com/rethinkdb/net/Cursor.java#L55](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Cursor.java#L55)
```
    public void close() {
        connection.removeFromCache(this.token);
        if (!error.isPresent()) {  /////here is the problem entry
            error = Optional.of(new NoSuchElementException());
            if (connection.isOpen()) {
                outstandingRequests += 1;
                connection.stop(this);     ////here is the problem 
            }
        }
    }
```

For a ChangeFeeds cursor, its error will not be set so can be called on next() method again.
Other type of cursor will be set error after got data to indicate it can not be used further more.

So, ChangeFeeds cursor will enter `!error.isPresent()` branch, finally call connection.stop(this) which in turn make a new cursor to send a close statement.
[drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L346](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L346)
```
    void stop(Cursor cursor) {
        // The server does reply to a stop request, though the response doesn't have a value.
        runQuery(Query.stop(cursor.token));
    }
 ```
The above code is strange. Previously it use `runQueryNoreply` which does not cause new cursor creation.

But the runQuery of course create new cursor.
[drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L283](https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Connection.java#L283)
```
Cursor cursor = Cursor.create(this, query, res, pojoClass);
```

So what is the problem? Calling close cause new cursor be added into cursorCache.
Repeatedly calling ChangeFeeds cursor query + close will cause memory leak.

**Comment by QianJin2013** [comment]
I have created a pull request for this issue.  Hope someone check it as soon as possible.

**Comment by danielmewes** [comment]
Thanks @QianJin2013 ! We'll try to get your fix in quickly.
