### ISSUE TITLE
Failed in less than 20s

### ISSUE THREAD

**Issue by floriannagel** [rethinkdb/rethinkdb#6013]
Hi folks, i startet a rethinkDB on GCE with Docker. And with every connection from NodeJS i get after 10Sec this Error:
```
Fail to create a new connection for the connection pool. Error:{"msg":"Failed to connect to  in less than 20s","message":"Failed to connect to in less than 20s.","isOperational":true}
```

What can i do?

**Comment by danielmewes** [comment]
Hi @floriannagel , are you using rethinkdbdash?

Can you try if you can successfully connect when using another driver, e.g. the Python driver?
That might give us a more helpful error message...

**Comment by floriannagel** [comment]
Python is saying this. The Web-Admin-Panel from my RethinkDB is visible and says, everything is all right :/

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/rethinkdb/net.py", line 656, in connect
    return conn.reconnect(timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/rethinkdb/net.py", line 567, in reconnect
    return self._instance.connect(timeout)
  File "/usr/local/lib/python2.7/site-packages/rethinkdb/net.py", line 425, in connect
    self._socket = SocketWrapper(self, timeout)
  File "/usr/local/lib/python2.7/site-packages/rethinkdb/net.py", line 328, in __init__
    raise ReqlTimeoutError(self.host, self.port)
rethinkdb.errors.ReqlTimeoutError: Could not connect to *, operation timed out.`

On the GCE Instance docker says: 
`839c1a2df9d9        rethinkdb           "rethinkdb --bind all"   42 hours ago        Up 42 hours         0.0.0.0:8080->8080/tcp, 0.0.0.0:28015->28015/tcp, 0.0.0.0:29015->29015/tcp   sharp_bohr`

**Comment by floriannagel** [comment]
Just a stupid GCE Firewall-Rule Error!! But thanks for your quick help
