### ISSUE TITLE
blob::stepsize() overflows when levels > 6

### ISSUE THREAD

**Issue by dekimir** [rethinkdb/rethinkdb#6015]
This leads to guarantee violations when appending large regions and could, theoretically, cause an infinite loop in `blob_t::append_region()`.

```
(lldb) p max_block_size_t::unsafe_make(4096)
(max_block_size_t) $62 = {
  block_size_t = (ser_bs_ = 4096)
}
(lldb) p blob::stepsize($62, 1)
(int64_t) $63 = 4084
(lldb) p blob::stepsize($62, 2)
(int64_t) $64 = 2082840
(lldb) p blob::stepsize($62, 3)
(int64_t) $65 = 1062248400
(lldb) p blob::stepsize($62, 4)
(int64_t) $66 = 541746684000
(lldb) p blob::stepsize($62, 5)
(int64_t) $67 = 276290808840000
(lldb) p blob::stepsize($62, 6)
(int64_t) $68 = 140908312508400000
(lldb) p blob::stepsize($62, 7)
(int64_t) $69 = -1923736915554206464
```

**Comment by danielmewes** [comment]
This isn't an issue. When you want to store data that is too large to have its size fit into a 64 bit integer you're going to have a whole set of other problems, and things will fail long long before you get anywhere near the blob code.

For one thing you can't address this much memory on a 64 bit computer. Even if you could, file access APIs in today's operating systems use 64 bit offsets, so you couldn't access a file like this either.

RethinkDB rejects queries that are larger than 128 MB. You can write queries that generate data that is larger than this, but those queries would run out of RAM way before you hit the limits of a 64 bit integer.
