### ISSUE TITLE
Ordering while selecting with indexes does not seem possible

### ISSUE THREAD

**Issue by niieani** [rethinkdb/rethinkdb#6016]
The structure of a row in my table is similar to this:

```js
{
  id: "...",
  access: [
    { user: "danielmewes", readOnly: false, grantedOn: Date },
    { user: "mlucy", readOnly: true, grantedOn: Date }
  ],
  data: "..."
}
```

What I'm after is: listing all the rows to which a given user has access to, ordered by `grantedOn` date in a performant way.
While I can create an expression-based multi-index to get all the documents which I can then query, say, whether `"danielmewes"` is listed as having access in the access object array:

```js
r.table('documents')
  .createIndex('user-with-access', doc => doc('access').map(acc => acc('user')))
```

It seems impossible to then order those documents in a performant way (with another index), because indexed `orderBy` must be done on a `Table` or a `TableSlice`.

Finding out which documents a person has access to is the easy (and fast) part:

```js
r.table('documents')
  .getAll(['danielmewes'], { index: 'user-with-access' })
```

With just 15000 documents in the database, passing a function that finds and returns the relevant record to an `orderBy` right after the above `getAll` takes a whole 8 seconds! (because it gets evaluated on every single record, because its not possible to use one index for ordering, while filtering out the irrelevant records with another)

Am I simply blindly missing a simple solution here, or is this really a current limitation of RethinkDB?

**Comment by danielmewes** [comment]
You can only use one index on a given table at a time. However you can use a compound index in this case to make it work:
```js
r.table('documents')
  .indexCreate('user-with-access_grantedOn', doc => doc('access').map(acc => [acc('user'), acc('grantedOn')]), {multi: true})
```

Note that each index key is now actually an array pair `[user, grantedOn]` rather than just `user`.

You can then query like this:
```js
r.table('documents')
  .between(['danielmewes', r.minval], ['danielmewes', r.maxval], { index: 'user-with-access_grantedOn' })
  .orderBy({index: 'user-with-access_grantedOn'})
```

**Comment by niieani** [comment]
Oh, I was actually looking through the docs but I didn't see anything about being able to use multi-indexes with `orderBy`. I'll try your suggestion though! Thanks.
