### ISSUE TITLE
Improve swapping detection (Linux)

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#6020]
This came out of an internal discussion on Slack:

@encryptio wrote: 

> there's also `majflt` ("The number of major faults the process has made which have required loading a memory page from disk.") in `/proc/[pid]/stat` but i'm pretty sure we don't want "any" major fault to raise issues, just if the number of major faults per minute exceeds some value (after a startup period where they may spike due to loading code from disk)

We think that we should change our swap detection code on Linux to use changes in `majflt`. The first value after one minute should be ignored (in case faults in the `rethinkdb` binary or other libraries are counted), and after that we should raise the issue if `majflt` increases by more than a certain number of faults per minute.

I think the limit should be maybe 200 FPS (faults per minute).

If we do this, we could also probably reduce the duration for which the swapping issue is displayed from the current 1 hour to maybe 10 minutes or so?

**Comment by nighelles** [comment]
Is there something derivable about 200, or is that just an arbitrary value?

**Comment by danielmewes** [comment]
@nighelles Arbitrary :-(

**Comment by danielmewes** [comment]
One criterion is that it has to be low enough that on a rotational disk with 10-20ms access time + other I/o load, we reliably detect heavy swap use. 200 page faults per second means 3.33 reads per second, which is probably lower than necessary with respect to this criterion.

**Comment by nighelles** [comment]
This is in review 3727.

**Comment by nighelles** [comment]
This is in next.
