### ISSUE TITLE
Java Driver – util question

### ISSUE THREAD

**Issue by dminkovsky** [rethinkdb/rethinkdb#6023]
https://github.com/rethinkdb/rethinkdb/blob/v2.3.4/drivers/java/src/main/java/com/rethinkdb/ast/Util.java#L76

and 

https://github.com/rethinkdb/rethinkdb/blob/v2.3.4/drivers/java/src/main/java/com/rethinkdb/ast/Util.java#L120

reset the remaining depth (vs subtracting 1). Just out of curiosity, I am wondering: why? 

Thank you!

**Comment by deontologician** [comment]
Probably an oversight

**Comment by dminkovsky** [comment]
Cool thanks.

**Comment by danielmewes** [comment]
Looks like this is a bug. Re-opening.

**Comment by adriantodt** [comment]
A fix was implemented to one of the branches of the Java driver, which now lives in a separated repository (https://github.com/rethinkdb/rethinkdb-java). This issue can be closed.
