### ISSUE TITLE
Intermittent errors with the data explorer on a AWS Compose Cluster 

### ISSUE THREAD

**Issue by Linicks** [rethinkdb/rethinkdb#6028]
All,
  While trying to test the geo location capabilities of RethinkDB, I setup a cluster with Compose deployed to AWS-EAST1.  I started going through the docs ( http://www.rethinkdb.com/docs/geo-support/javascript/) and created the two example locations.  Unsurprisingly, I wanted to query for records within a given distance, and tried the following query from the data explorer:

>var point = r.point(-122.422876,37.777128); //San Francisco
>r.db('geo_test').table('geo').getNearest(point, {index: 'location', maxDist: 300, unit: 'mi'})

A successful query was executed and I got back the SF location.  I then increased the maxDistance to 1000 to try and get San Diego, and got an error like this:

>[Exception... "The URI is malformed"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: https://amazon stuff:11321/cluster-min.js?v=2.3.4 :: ["/home/buildslave/buildslave/package-trusty/build/build/packages/js/net.js"]</</HttpConnection</r.prototype.write :: line 1483"  data: no]

If I changed the maxDistance  back to a lower number like 500 it would work.  I tried 1000 again, and ran the query several times in a row and got back errors, until it finally executed without the error described above.

In a discussion with Danielmewes on Slack, he thought it may be an issue with their admin proxy.
" Ah, wonder if it could have to do with the proxy they use for tunneling the web UI access."

My workstation is running Ubuntu 16.04, and I was using Firefox 47

Thanks! 
-- Nick

**Comment by danielmewes** [comment]
Thanks for opening the issue @Linicks .

This type of error definitely looks like something related to the HTTP communication, rather than to the particular query that you ran.

It might still be an issue in our code. Maybe it's actually constructing illegal URLs.

**Comment by danielmewes** [comment]
Do you have a chance to check if the same happens with a different browser (e.g. Chrome)?

**Comment by Linicks** [comment]
Hi Daniel,
  Chrome 52 will not currently allow me access to the admin site at all:

>"You cannot visit aws-us-east-1-portal9.dblayer.com right now because the website sent scrambled credentials that Google Chrome cannot process"

Ubuntu updated Firefox to V48 today, and I'm still able to advance to the admin site. So far, I haven't been able to re-create the error.  The only error that I've had is when I try too large of a maxDist value.  For example:

>var point = r.point(-122.422876,37.777128); r.db('geo_test').table('geo').getNearest(point, {index: 'location', maxDist: 7050, unit: 'mi'})

>e: The distance has become too large for continuing the indexed nearest traversal.  Consider specifying a smaller `max_dist` parameter.  (Radius must be smaller than a quarter of the circumference along the minor axis of the reference ellipsoid.  Got 11501765.127301588655m, but must be smaller than 9985163.1855612862855m.) in:
r.db("geo_test").table("geo").getNearest(r.point(-122.422876, 37.777128), {"index": "location", "maxDist": 7050, "unit": "mi"})

This error is very clear, and makes allot of sense.  Since I can't recreate the intermittent error I was having, it's probably best to mark this closed and get it off the books.

Thanks!
-- Nick

**Comment by danielmewes** [comment]
Hmm yeah might be hard to debug in that case. Thanks for trying.

We can re-open it if you or anyone else sees it again.
