### ISSUE TITLE
Insert with Function Error: Expected type DATUM but found FUNCTION

### ISSUE THREAD

**Issue by chacalle** [rethinkdb/rethinkdb#6045]
I'd like to insert documents with a resolution function like in #3753, for example I want to keep the document with a more recent timestamp. When passing a function with python or javascript I get the Error: Expected type DATUM but found FUNCTION. I tried the following in the data explorer as a test and am still getting the same error. Help in understanding this error would be appreciated. 
```
r.table('foo').insert(
  [{id: 0, a: 3}, {id: 1, a: 2}],
  {
    conflict: function(id, old_doc, new_doc){
    return r.branch(
      old_doc('a').lt(new_doc('a')),
      new_doc,
      old_doc
    )}
  })
```
Also documented here: http://stackoverflow.com/questions/37553022/rethinkdb-insert-and-conflict-resolution-function-syntax

**Comment by danielmewes** [comment]
Which version of RethinkDB are you running? The conflict function was added in RethinkDB 2.3.0, so if you're running an older version it will not work.

**Comment by chacalle** [comment]
Thank you, I updated to 2.3.4.
