### ISSUE TITLE
Add `--fast` option to `rethinkdb restore`

### ISSUE THREAD

**Issue by marshall007** [rethinkdb/rethinkdb#6060]
In cases where you don't care about downtime or are provisioning a brand new cluster, it would be nice to have an option that follows best practices for getting the data restored as quickly as possible. From my experience, this means:

1. create db and tables with appropriate shard/replica settings
1. restore data with `--no-secondary-indices`
1. restore secondary indices

Depending on the size of the machine, restoring onto a single shard/replica first and then updating the table config and letting it backfill to other nodes as a second step can sometimes be even faster. Some testing probably needs to be done to verify which is actually faster in the general case or if a heuristic can be applied to determine which method we should use.

In the future, I would like to see better throughput overall when restoring, perhaps with a dedicated, lower-level protocol for streaming data in and/or serializing straight to disk. For now, having a flag that at least performs these tasks in the optimal order seems like a good start.

Regardless, the current behavior of sharding + creating indices up front is definitely the slowest. It would be nice not having to remember all this and micromanage the restore process each time.

**Comment by larkost** [comment]
Assuming that the table does not already exist, and that you have not specified `--shards` or `--replicas` on the command line, we already only create a single shard. While that does have the potential for nasty surprises if someone is restoring to a computer that does not have enough space for the whole table, that is probably the best we are going to be able to do at this point. So we allow people to do the right thing, but still keep our logic simple.

On when to build indexes... After talking it over internally, we think that it is probably best to do post-construction by default and will be changing this. At one point in out codebase it was probably faster to do pre-construction, but with the exception of really large tables on spinning disks we expect post-construction to be generally faster and will switch that over.

So I am going to change that last bit in the near future, but I think that will be the only change we will take from this.

**Comment by marshall007** [comment]
> Assuming that the table does not already exist, and that you have not specified `--shards` or `--replicas` on the command line, we already only create a single shard.

@larkost right, to be clear, my comment on that portion only applies when you're trying to provision a multi-shard environment. I was simply saying that I've noticed it can be faster to restore onto a db with a single shard first before updating the config with the desired number of shards.

Not sure how we could determine in advance which method would be faster and your point about not having enough space on disk to support a single shard complicates that further. I think you're right that there's not a whole lot we could do there for now.

I would appreciate if someone could comment on exactly *why* restoring onto a cluster isn't always faster than a single node, though.

> So I am going to change that last bit in the near future, but I think that will be the only change we will take from this.

Sounds good, I assume that means this would become default behavior rather than being behind a flag?

**Comment by larkost** [comment]
This is now in `next` with 48c725bb, it makes the (re)creation of indexes happen after the data is imported. There is no way to change this behavior other than disabling index creation (`--no-secondary-indexes`) as we believe that it should be positive for almost all users.

**Comment by danielmewes** [comment]
> I would appreciate if someone could comment on exactly why restoring onto a cluster isn't always faster than a single node, though.

That's surprising to me too. If all replicas are on the local machine that `rethinkdb restore` is connecting to, that makes sense because it reduces the CPU and network overhead required for re-routing the writes to the appropriate node. However if you use a single shard in a cluster, RethinkDB will still pick a random server for the shard of each table. It will not necessarily be on the server that the `restore` script connects to. So I wouldn't expect this to provide any performance benefit.
