### ISSUE TITLE
[Question] Is ~30% peek CPU usage normal?

### ISSUE THREAD

**Issue by TigerHix** [rethinkdb/rethinkdb#6064]
Whenever there are operations like `orderBy` performed (with index enabled), the CPU usage went from 0.x% to 20% or even 30%. Is that considered normal? Is it advised to put RethinkDB on a separate machine?

**Comment by ha1331** [comment]
In case you didn't know, rethinkdb has pretty vibrant community at slack http://slack.rethinkdb.com/ at irc, freenode #rethinkdb and a mailing list https://groups.google.com/forum/#!forum/rethinkdb. You might get better answers there and also answering further questions might be easier.

as to your question, I suspect it's perfectly normal. Based on the information you provided, it's pretty hard to say anything definitive. Having database in separate machine should be a thing to consider with any database, not only with Rethinkdb.

**Comment by danielmewes** [comment]
If the data fits into RethinkDB's cache, and there's no other bottleneck (network, speed at which the client is reading the data), CPU usage should ideally get as high as 100% when running an operation like this. Anything less just means that CPU resources are left unutilized.
So 30% (or more) are definitely normal.
