### ISSUE TITLE
Rethinkdb slow to initialize (~45 seconds) if a configured DNS is unreachable

### ISSUE THREAD

**Issue by pavius** [rethinkdb/rethinkdb#6066]
On Ubuntu 16.04 w/rethinkdb 2.3.4 (checked 2.1.0 as well) rethinkdb will take 43 seconds to initialize if a DNS server is unresponsive or unreachable. 

I could not see any hint of this in the logs as they simply started logging at 43 seconds, but when running with `strace` noticed continuous timeouts connecting to an IP which was apparently a DNS which had become unreachable. 

A few things to note:
1. resolv.conf also had a working DNS configured to which rethinkdb connected fine (as per `strace`)
2. Running rethinkdb w/`--no-update-check` had no effect

Obviously our course of action is to deprovision this DNS server until it's back up - but it seems suboptimal that rethinkdb will take 45 seconds to initialize when at least one configured DNS is not available (especially given that no configuration was passed to mandate a DNS and, perhaps moreover, a working DNS was available).

**Comment by larkost** [comment]
This is very similar to the issue in #4600, so I am duping this against that. The only difference is that this is probably in the part where we are figuring out the hostname of the computer we are running against. Unfortunately the solution is going to be the same one as that one (hence the dup), which is to put a timer on our network setup, and then just report if it fails to work in a timely fashion. So you would at least have a logged line telling you that things were slow.
