### ISSUE TITLE
Python datetime not rounded like r.time()

### ISSUE THREAD

**Issue by daveisfera** [rethinkdb/rethinkdb#6069]
r.time() will round the number of milliseconds, but Python datetime does not do the same thing. This results in different results when using the same inputs through the different interfaces. It can also cause problems during floating point conversions when reading values and then writing them back (i.e. the timestamp can become X.ABC999 in the Python datetime when it should be X.ABD000 where C is D-1).

Here's a simple script to demonstrate the difference in behavior:

```
#!/usr/bin/env python3

import datetime

import pytz
import rethinkdb as r

conn = r.connect(host="localhost", db="test")

r.table_create("test_time").run(conn)
truth = datetime.datetime(2016, 1, 1, 0, 0, 0, 1000, pytz.utc)
r.table("test_time").insert({"time": truth}).run(conn)
r.table("test_time").insert({"time": datetime.datetime(2016, 1, 1, 0, 0, 0, 999, pytz.utc)}).run(conn)
r.table("test_time").insert({"time": r.time(2016, 1, 1, 0, 0, 0.000999, "Z")}).run(conn)
for row in r.table("test_time").run(conn):
    print(row["time"], row["time"] == truth)
```

**Comment by danielmewes** [comment]
Interesting.

I think the core issue is not so much that RethinkDB rounds times, and Python doesn't, but that RethinkDB doesn't *always* round the times when they are inserted

As you demonstrate, our conversion routine from Python datetime appears to just cut off anything below milliseconds, rather than rounding it properly.

I think we should consider this as a bug in the Python driver.

**Comment by daveisfera** [comment]
I did some digging in the Python driver after creating this issue and the actual culprit is the `ISO8601()` function. Python datetime is converted by passing the output of `.isoformat()` into `ISO8601()` and that's where the truncation happens.
Here's an example show the issue without the Python driver:
`r.expr(r.ISO8601('2016-01-01T00:00:00.000999+00'))`
`ISO8601()` should be fixed, but it would likely be more efficient to have the Python driver call `r.time()` so that the conversion to/from a string representation doesn't need to happen.

**Comment by srh** [comment]
Ah @daveisfera -- you caught #6272 before I did!

**Comment by srh** [comment]
PR #6574 fixes the server so that it rounds instead of truncating.  I didn't change the Python implementation.
