### ISSUE TITLE
Table reconfiguration from the UI acts funny

### ISSUE THREAD

**Issue by azabujuban** [rethinkdb/rethinkdb#6070]
On a three servers cluster, when changing the number of shards or replicas and clicking the `Apply Configuration` button immediately after changing the number reconfiguration isn't actually performed. However, if you only click the button a couple of seconds after changing either number it works fine.
![ok](https://cloud.githubusercontent.com/assets/445372/17914630/a8ec2b32-69de-11e6-95d8-2c8eb2c4213a.gif)
![bug](https://cloud.githubusercontent.com/assets/445372/17914649/e1b76904-69de-11e6-800f-c76bc259b2f3.gif)

**Comment by danielmewes** [comment]
Thanks for the report @azabujuban . This is a duplicate of https://github.com/rethinkdb/rethinkdb/issues/4858 .
