### ISSUE TITLE
java driver dropping bits

### ISSUE THREAD

**Issue by shengc** [rethinkdb/rethinkdb#6075]
I am using rethink 2.3.2 java driver to read back data ordered by a secondary index. This is the code I am using,

    r.db(db).table(table).orderBy().optArg("index", "tx").between(offset, r.maxVal()).optArg("left_bound", "open").run[Cursor[_]](connection)

I am using an `AtomicLong` to keep track of the `offset`, and whenever a read using the above line exhausts, I immediately initiate another read using the same line by setting the offset kept in the `AtomicLong`.

This worked well in a smaller scale of data, now we move to `UAT`, a lot more data comes in, and writes are more frequent, the code starts to exhibit weird behavior. For example, I have `tx = 401, 402, 403, 404, 405` in the rethink table, and the read gives me back `401`, `403`, `405`. This is not reproducible, something it happens, sometimes it does not. I test run two process using the same code simultaneously, one does not lose bits at all, the other loses bits from time to time. I also have an impression when `cursor.next()` cannot be called in time, the bits loss will usually come. My rethink db instance runs with only 1 node, so this bizarre behavior really surprises me. Is there anything I can try in my query, or something else ? Thanks!

**Comment by danielmewes** [comment]
Hi @shengc, are any writes happening to the table while the read is running? Could transactions be inserted or deleted concurrently?

Also to make sure I understand correctly: do entries get skipped within a *single* run of this query? Or do the skips happen only *between* runs, if you have to start another query with a new offset?

**Comment by shengc** [comment]
@danielmewes 

Thank you for following up. Yes writes happen during read, but guaranteed there are no deletes, only insertions happen, there are no updates either.

entries are skipped within a single run of the query, not in-between.

**Comment by danielmewes** [comment]
Are the skipped transactions ones that were just inserted by any chance?

Since RethinkDB doesn't provide consistency guarantees across multiple documents (or index ranges), it could certainly miss some of the inserts, but not others, if inserts happen while the cursor is open.

**Comment by danielmewes** [comment]
To work around this, you could check for skipped transactions, and update the `offset` to be the last transaction up to which no transaction has been skipped. Then the next time you run the query, it should give you the skipped documents.

**Comment by shengc** [comment]
I thought `optArg("index", "tx").between(offset, r.maxVal())` guarantees such a read only returns what is currently available in rethink, no? Also all insertions happen in a single thread executor, which means all insertions happen in a strict order (no concurrency), and an insertion only happens _after_ the immediately previous insertion returns. Do you mean miss of insertion can still happen for a read in this case ?

We cannot go back to replay the skipped transactions. Since our application strongly depends on all insertions replayed in an ordered manner, if one is skipped, the application will start to produce false positive alarm which is rather annoying.

**Comment by danielmewes** [comment]
> Do you mean miss of insertion can still happen for a read in this case ?

Yes, even on a single server RethinkDB internally shards the data in order to utilize multiple CPU cores. The read might already have passed over a given ID on one core, while it's still in front of it on another one. So an insert on the former core would be missed, while one on the latter core would still be included in the result.

I'm not saying to go back in replaying them. What I imagine is something like this:
```
while (true) {
  cursor = r.db(db).table(table).orderBy().optArg("index", "tx").between(offset, r.maxVal()).optArg("left_bound", "open").run[Cursor[_]](connection)
  for (el : cursor) {
    if (el.tx > offset + 1) {
      // Detected a skipped transaction. Run the query again. Next time the missing document will be
      // included.
      break;
    } else {
       handleTransaction(el);
    }
  }
}
```

**Comment by shengc** [comment]
Ok, I think your suggestion makes sense, will give it a try, thanks for the help. Another thing is in rethink, is there any strong guarantee like JVM's "happens-before" rules that promises the event order will be held from the perspective of all threads, in this case, all reads from different reads/clients.

**Comment by danielmewes** [comment]
> Another thing is in rethink, is there any strong guarantee like JVM's "happens-before" rules that promises the event order will be held from the perspective of all threads, in this case, all reads from different clients.

There is not. The only ordering guarantee that you have is that after a write has been acknowledged, any subsequent operation issued against the database will see the effect of that write.
However it might also see the effects of a write that has not been acknowledged yet. This also doesn't do anything for operations that have been started before a write was acknowledged, as is the case with the read cursor in your use case.
