### ISSUE TITLE
Java: `Cursor` implementing `Iterable` can be misleading

### ISSUE THREAD

**Issue by rocketraman** [rethinkdb/rethinkdb#6076]
The Java `Cursor` object implements both the `Iterator` and `Iterable` interfaces. However, a `Cursor` is not  `Iterable` for real -- it can only be traversed once and simply returns `this` in its `iterator()` implementation.

A real `Iterable` would allow the same cursor to be traversed multiple times by returning a new `Iterator` from `iterator()`. Since `Cursor` does not do this, exposing the `Iterable` interface is misleading.

Note that implementing `Iterable` allows the cursor to be used in a java for-each statement, which seems like a good thing, but programmers generally don't expect a for loop to be destructive i.e. it can only be executed on an object once. So I think this is an argument *against* implementing `Iterable` rather than "for" (pun intended!).

**Comment by danielmewes** [comment]
Good point!

@deontologician Do you know if there was a reason for implementing the `Iterable` interface on `Cursor`?
```java
public interface Iterable<T>
{
    Iterator<T> iterator();
}
```

**Comment by deontologician** [comment]
It was for the exact reason stated, you can otherwise not use it in a for-each loop. We could add a method `runIterable` which would return an Iterable for a forEach loop, and have `run` just return the iterator directly.

**Comment by rocketraman** [comment]
> We could add a method runIterable which would return an Iterable for a forEach loop, and have run just return the iterator directly.

Would `runIterable` return an `Iterable` that can be re-used i.e. iterated more than once? If not, then I don't see how this approach addresses the issue -- it would be the same confusion on a different object/method.

**Comment by danielmewes** [comment]
Ah, for-each loops require it, right, I missed that. 

I think the benefits of allowing `for (x : cursor)` are worth slightly violating the interface in this respect.

A second function `runIterable` would just be less intuitive. It would also still not be a real `Iterable`, since we have no way to have cursors that you can iterate multiple times (unless we store all results in memory, which defeats the purpose of a cursor).

**Comment by danielmewes** [comment]
Something we should probably do is ensure at runtime that `iterator()` only gets called once. On the second call, we should throw an exception.

**Comment by deontologician** [comment]
Well the iterable it returns would just execute the query against the db, and return the query. We could have the query be an Iterable, but there's no way to pass run parameters to it then

**Comment by danielmewes** [comment]
Hmm wait, throwing an exception might not work because it would change the API right?

**Comment by deontologician** [comment]
So basically, `runIterable` would return an Iterable that has the run parameters baked into it, and then when you iterate over it, it executes the request to the database, so it would be re-useable.

**Comment by danielmewes** [comment]
I see. That makes sense, but is still weird. If you get multiple iterators from the `Iterable` that `runIterable` generates, you might get different results each time.

**Comment by danielmewes** [comment]
Also, if `iterator()` will actually be the thing that runs the query, will we be able to throw an exception from there if executing the query fails? It seems to me that this will just add complication.

**Comment by deontologician** [comment]
I would guess getting different results each time isn't a terrible thing. And the exception throwing isn't any worse than we have right now, since it'll just throw an exception from `.run`

**Comment by danielmewes** [comment]
It looks like we'll add the check to `iterator()` so it fails on the second call, and otherwise keep our current API.

**Comment by rocketraman** [comment]
> It looks like we'll add the check to iterator() so it fails on the second call, and otherwise keep our current API.

That makes sense.
