### ISSUE TITLE
Python fails on applying birthday example on timestamps with timezone

### ISSUE THREAD

**Issue by skinkie** [rethinkdb/rethinkdb#6081]
I am trying the birthday example https://www.rethinkdb.com/api/python/date/ in Python. I figured out that the timezone of r.now() comparing to an existing timestamp with timezone fails. When explicitly initialising with the current date and the same timezone my code works.

> r.table('drivers').get(493170)['vehicles'].map(lambda vehicle: { vehicle['from_ts'].date() == r.time(2016, 8, 28, '+02:00').date() }).run(conn)
> [[False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [True], [True], [True], [True], [True], [True]]

But using now:

> r.table('drivers').get(493170)['vehicles'].map(lambda vehicle: { vehicle['from_ts'].date() == r.now().date() }).run(conn)
> [[False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False], [False]]

Should now be extended to support a timezone? Or shouldn't the comparison fail?

**Comment by danielmewes** [comment]
The current behavior makes sense insofar as that a `date()` actually describes a different time range in different time zones. August 28th in UTC+2 is not the same as August 28th in UTC (though they do intersect).

A more robust version of the example would be:
```
r.table("users").filter(lambda user:
    user["birthdate"].during(r.now().date(), r.now.date() + 24*60*60)
).run(conn)
```

**Comment by danielmewes** [comment]
Opened an issue to clarify this in the documentation: https://github.com/rethinkdb/docs/issues/1173

I think this is the correct behavior right now, due to how `date()` works (it just returns another datetime object, with the time set to 00:00:00).

**Comment by skinkie** [comment]
It isn't the correct behavior because comparing a given timestamp to 'today, in that timezone' would still be impossible.

**Comment by danielmewes** [comment]
Not sure if I understand what you mean, but you can do `r.now().inTimezone("+02:00").date()`. This will give you "today" in another timezone, whatever that day is (might be yesterday or tomorrow, depending on where you are).

**Comment by skinkie** [comment]
So I think _that_ would be the answer to my query, and helps me to solve it. I would suggest adding this to the documentation.
