### ISSUE TITLE
Cursor, extendInternal, NoSuchElementException

### ISSUE THREAD

**Issue by rpazuki** [rethinkdb/rethinkdb#6083]
I am wondering is this correct?

https://github.com/rethinkdb/rethinkdb/blob/next/drivers/java/src/main/java/com/rethinkdb/net/Cursor.java#L86

If it is an error that _response.isSequence()_ , why in line 85 there is an addAll?

I sometimes get this error from the same place:

`java.util.NoSuchElementException
        at com.rethinkdb.net.Cursor.extendInternal(Cursor.java:74)
        at com.rethinkdb.net.Cursor.extend(Cursor.java:64)
        at com.rethinkdb.net.ConnectionInstance.readResponse(ConnectionInstance.java:79)
        at com.rethinkdb.net.Connection.readResponse(Connection.java:130)
        at com.rethinkdb.net.Cursor$DefaultCursor.getNext(Cursor.java:172)
        at com.rethinkdb.net.Cursor.next(Cursor.java:110)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at com.rethinkdb.net.Cursor.toList(Cursor.java:130)
        at com.LandA.dataSets.rethinkDB$Query.timeSeries(rethinkDB.scala:136)
        at com.LandA.dataSets.rethinkDB$Query.timeSeries(rethinkDB.scala:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
`

Any Help?

**Comment by bchavez** [comment]
What version of the Java driver are you using? Do the numbers in your stacktrace ie:`(Cursor.java:110) at` correspond to source line numbers? If so, they're not matching up with the current source. :crying_cat_face: 

Maybe double check you're using the latest driver.

:walking: :zzz: [***"Every passing day seems all the same to the sleepwalker..."***](https://www.youtube.com/watch?v=R5IvcvdIxcQ)

**Comment by rpazuki** [comment]
Thanks for your reply.

I am using the release 2.3.3 from Maven repo. So, you are right, line numbers in stack trace are not exactly the same as latest code.
Is there any difference between 2.3.3 release and the current code? 2.3.3 is the latest on Maven.

Also, the Cursor is running in another thread than the main code. Does it make any difference? 

The query is the following. But the weird thing is the error is just sometimes happening. e.g. the following query throws the exception while if I change the second date to "2017-01-01T00:00:00.000Z", it works. 

I am pretty sure about the underlying dataset and I used your point by running the same code on a single thread. It is fine, but not on multithread one.

`r.table("event")`
 ` .getAll("STOPPED")`
` .optArg("index","subtype")`
 `.pluck("startDate","EndDate")`
` .filter{ row =>  row.g("startDate").ge("2016-01-01T00:00:00.000Z").and(row.g("EndDate").le("2016-08-01T00:00:00.000Z")) }`
`.run(conn)`


Cheers

**Comment by bchavez** [comment]
Hey @rpazuki , thanks for the reply. Are you ***really s.u.r.e*** you are using the latest [`v2.3.3`](http://search.maven.org/#search%7Cga%7C1%7Crethinkdb) of the **Java** driver? :no_mouth:

After giving it some additional thought, the stack trace you posted isn't making any sense.

* 1) `ConnectionInstance` was removed a [long time ago:here](https://github.com/rethinkdb/rethinkdb/commit/1a9d46ca4f9377b62edab244c33495dde2f17158) when the Java driver was made thread-safe.
```
com.rethinkdb.net.ConnectionInstance.readResponse(ConnectionInstance.java:79) a
```
* 2) AFAIK, it is impossble with the current Java driver to get from `Cursor.next()` to `Connection.readResponse()`. Some ***Back To The Future*** stuff going on right thrrr. :car::zap::fire: :smile_cat: 
````
com.rethinkdb.net.Connection.readResponse(Connection.java:130) at
com.rethinkdb.net.Cursor$DefaultCursor.getNext(Cursor.java:172) at
com.rethinkdb.net.Cursor.next(Cursor.java:110) at
```

*You gotta* be using an older version of the driver. Is there a way to clear your package cache somehow maybe?? 

Also, I pulled the latest [`sources.jar`](http://search.maven.org/remotecontent?filepath=com/rethinkdb/rethinkdb-driver/2.3.3/rethinkdb-driver-2.3.3-sources.jar) from Maven Central and the current `v2.3.3` release is pretty current with the [Java source here on GitHub](https://github.com/rethinkdb/rethinkdb/tree/next/drivers/java) (minus a recent minor commit). So, I'm still not sure how you can generate the stack trace you posted given the current release.

> ... and I used your point by running the same code on a single thread. It is fine, but not on multithread one.

**That** particular behavior makes sense if you are using a really old Java driver version when switching between `single-threaded` and `multi-threaded` usage. I would expect this particular threading behavior prior to **February 3, 2016** when the Java driver's `Connection` was not thread-safe. See https://github.com/rethinkdb/rethinkdb/pull/5292. The current Java version `v2.3.3` is thread-safe. If you are **really**, ***really***, using `v2.3.3` then `multi-threaded` usage should be fine.

If you are truly using the latest version, then I'm all out of ideas.

:headphones: :notes: [***Antiserum & Mayhem - Trippy***](https://www.youtube.com/watch?v=o95ZTp5fuF8)

**Comment by rpazuki** [comment]
Thanks a million @bchavez,  it is very illuminating. I will check it and let you know. 
I'm using the following sbt include and the stack trace is fully machine made :). So there is some problem traceable if this is the old version stack trace. 

`libraryDependencies += "com.rethinkdb" % "rethinkdb-driver" % "2.3.3"`

I should clear Maven's cache to see what happens next.

Cheers

**Comment by rpazuki** [comment]
Hey @bchavez. I checked the idea of an old release and you were absolutely right. 

There was a wrong class path somewhere in the code that caused the release 2.2.beta mistakenly being loaded to jvm. I removed that and it worked like a charm.

Thanks a million again for your help.

**Comment by bchavez** [comment]
No problem @rpazuki. I'm happy you found the problem. :sunglasses: 

:star: :guitar:  [***"Hey now, you're a rock star, get the show on, get paid..."***](https://www.youtube.com/watch?v=L_jWHffIx5E)

**Comment by danielmewes** [comment]
Thanks @bchavez ! :)
