### ISSUE TITLE
Migration to cluster version 2.4

### ISSUE THREAD

**Issue by nighelles** [rethinkdb/rethinkdb#6085]
Remember to write the migration to cluster version 2.4, and delete todo on line 351 of file.cc

**Comment by mbroadst** [comment]
I'm not seeing a TODO on line 351: https://github.com/rethinkdb/rethinkdb/blob/next/src/clustering/administration/persist/file.cc#L351

**Comment by chrisvariety** [comment]
@mbroadst probably this:  https://github.com/rethinkdb/rethinkdb/blob/767d72af9012d27e4f2f5db1da5fecda41057e8e/src/clustering/administration/persist/file.cc#L357-L358

**Comment by mbroadst** [comment]
@chrisvariety oh doh, I was looking for an actual guarantee - yeah looks like you're right

**Comment by danielmewes** [comment]
Implemented in https://github.com/rethinkdb/rethinkdb/pull/6230
