### ISSUE TITLE
Empty results querying for secondary index

### ISSUE THREAD

**Issue by ericholiveira** [rethinkdb/rethinkdb#6087]
Im using rethinkdb 2.3.4 , with 3 servers on replica set no sharding using a custom db (instead of the default 'test')

im trying to run the following query on data explorer on a secondary index:

r.db('MY_DB').table('MY_TABLE').getAll([SOME_INTEGER],{index:"MY_IDX"})

this query gives me an empty result, but i know this shouldnt be empty because im running to  r.db('MY_DB').table('MY_TABLE') looking the first result querying and using SOME_INTEGER as the value of MY_IDX for the first result.

I've created the index using the web interface. And the table MY_TABLE have documents in the following format:

{
... some properties,
"MY_IDX":SOME_INTEGER
}

What am i missing?

**Comment by danielmewes** [comment]
@ericholiveira Are you actually passing `SOME_INTEGER` to `getAll` in an array? That would make it an array key, which wouldn't match an integer in your table. Try removing the `[...]` if that's the case.

**Comment by ericholiveira** [comment]
thx @danielmewes 
Sorry.. my mistake i thought the array worked as "in" of mongodb... now it worked :)
