### ISSUE TITLE
AWS Lambda to ec2 Rethinkdb Timeout

### ISSUE THREAD

**Issue by warka0** [rethinkdb/rethinkdb#6088]
Hi everyone!

I'm having an issue with AWS Lambda who got timeout without explicit reason when trying to connect to an EC2 RethinkDB instance. 

I don't know if someone else get the error or having the same case. I didn't find something about it. 

`{ [ReqlTimeoutError: Could not connect to MY-ELASTIC-IP:28015, operation timed out.] name: 'ReqlTimeoutError', msg: 'Could not connect to MY-ELASTIC-IP:28015, operation timed out.', frames: undefined, message: 'Could not connect to MY-ELASTIC-IP:28015, operation timed out.' }`

The only way to fix this problem during a random duration is to re-upload the lambda function who failed until the next timeout... 

I hope to find a solution for this 😄

**Comment by chrisvariety** [comment]
I haven't actually tried connecting to RethinkDB via AWS Lambda, but I know there's a VPC song and dance you have to perform to be able to talk to EC2, for example: http://docs.aws.amazon.com/lambda/latest/dg/vpc.html

If your Elastic IP is accessible to the open web (not that I would recommend this) and you're trying to connect that way, I believe you would need a NAT Gateway: http://docs.aws.amazon.com/lambda/latest/dg/vpc.html#vpc-internet

If you've already done all that, based on your last sentence you may be holding onto a single connection too long? Are you re-connecting every time the Lambda function is invoked? I've never encountered a problem with Lambda that involved re-uploading the function to fix it.

It would definitely be helpful to post what you find back here so others can learn from it!

**Comment by warka0** [comment]
@chrisvariety In fact, the request are quick, i've test with privateip, elastic and DNS just for fun. And it failed after some handles. 

I'll do the VPC thing to watch if it's continue or nah.
I've a script who pool several hundred of request and it reproduce the timeout after some successful requests.

Thx for answering so quick! 👍

**Comment by warka0** [comment]
Alright!

I've update my lambdas function with the link you provide and it's working. No timeouts.
Thx for providing the documentation link, answering me and so quick! 😄

**Comment by chrisvariety** [comment]
Awesome! Hopefully other people will find this that are trying to get RethinkDB going on Lambda.

**Comment by warka0** [comment]
@chrisvariety Exactly, i hope this will be a part of the Google search of someone. 😃

**Comment by Diferno** [comment]
Hi, I'm facing the same problem and can't figure out how to configure the VPC so the lambda doesn't timeout :(

So far I've tried with the hosts public DNS, the public IP, opening the port 28015 to the world, to the Security group only.... nothing worked so far :-1: 

The role has the policies requested and tried to follow [this tutorial](http://docs.aws.amazon.com/lambda/latest/dg/vpc-rds-invoke-lambda-function.html) with no luck

**Comment by warka0** [comment]
Hi,

In fact, you need to update each lambda to be a part of the same VPC of your database instance by using this kind of line of command : 

`aws lambda update-function-configuration --function-name NAME-OF-THE-LAMBDA --vpc-config SubnetIds=subnet-SUBNET-DATABASE-ID-HERE,SecurityGroupIds=sg-GROUP-ID-HERE`

And that's all! After this line for each lambda who use the instance of RethinkDB, it's working!
At least, for me, so it probably for you too!

**Comment by Diferno** [comment]
Woot! thx for the quick reply!

I tried your command, but what it actually did was to override the configuration I already had made through the Lambda's console configuration tab. 
Don't know why or how, but in one try, it stablished the connection pool... and without changing anything, timeouts came again and owned the execution

I'm thinking of kicking Lambdas and moving towards a SQS-EC2 solution ...
