### ISSUE TITLE
One of the nodes in the cluster is out of connection.

### ISSUE THREAD

**Issue by CsterKuroi** [rethinkdb/rethinkdb#6092]
The following scenario:

1. A cluster with 60 nodes
2. 60 shards, 60 replicas
3. There is a node lost connection, would it affect other nodes? Need to restart it?

**Comment by danielmewes** [comment]
@CsterKuroi If all tables are configured to have 60 replicas, you can take up to 29 nodes offline and the tables will still be available (after a short moment during which RethinkDB performs the automatic failover).
There is no need to restart any of the remaining nodes.

Note that queries that are running at the moment where a node fails might get interrupted, and you'll have to restart changefeeds and some other queries once the auto-failover is complete.
