### ISSUE TITLE
How to del array element ?

### ISSUE THREAD

**Issue by 0x88l** [rethinkdb/rethinkdb#6096]
How to del  serial'elemnet of "abc" ?
data like this:
{
"serial": [
"abc" ,
"nba" ,
"fifa"
] ,
id: "123456"
}

**Comment by danielmewes** [comment]
@0x88l Note that questions like this are better placed in our mailing list https://groups.google.com/forum/#!forum/rethinkdb or on Slack (http://slack.rethinkdb.com for an invite, then https://rethinkdb.slack.com ). The GitHub tracker is for bug reports and feature suggestions.

To delete any "abc" entry from the array in this document, you would run something like this:
```js
r.table(...).get("123456").update({serial: r.row("serial").difference(["abc"])})
```

See the documentation of the `difference` term https://www.rethinkdb.com/api/javascript/difference/
