### ISSUE TITLE
Old id does not match new id

### ISSUE THREAD

**Issue by dan335** [rethinkdb/rethinkdb#6101]
I sometimes get a row that is type changed but the ids do not match.

```
{ 
  new_val: { 
    _id: 'c2cdf888-8187-4223-98fb-674d208d7063', 
    createdAt: Sun Sep 11 2016 01:00:56 GMT+0000 (UTC), 
    lastPostDate: Sun Sep 11 2016 01:00:56 GMT+0000 (UTC), 
    lastPostUserId: 'kKickRZjzg7JZFCGw', 
    lastPostUsername: 'Kevin35', 
    numPosts: 1, 
    title: 'Where did my Worker go?' 
  },old_val:  {
    _id: '5f79ee63-4a43-4772-b077-ccca45f6b547', 
    createdAt: Thu Sep 08 2016 22:41:30 GMT+0000 (UTC), 
    lastPostDate: Sat Sep 10 2016 16:35:54 GMT+0000 (UTC), 
    lastPostUserId: 'xZAuky6Mdt6N966pB', 
    lastPostUsername: 'DarklordMogrithe', 
    numPosts: 4, 
    title: 'Different City Names'
  }, 
  type: 'change' 
} 
```

I think it should have been an insert.

**Comment by marshall007** [comment]
@dan335 what query are you using on this changefeed? Does it include an `orderBy`? Also, are you sure you've configured `_id` as the primary key on this table?

**Comment by dan335** [comment]
It's one of these two queries.

```
r.table('forumtopics')
  .get(topicId)
  .changes({includeInitial:true, squash:true, includeTypes:true, includeOffsets:false, includeStates:false})
  .run(rConn, function(error, callback) {

  });
```

```
r.table('forumtopics')
  .orderBy({index: r.desc('lastPostDate')})
  .limit(limit)
  .changes({includeInitial:true, squash:true, includeTypes:true, includeOffsets:false, includeStates:false})
  .run(rConn, function(error, callback) {

  });
```

And here is creating the table with _id.

```
r.tableCreate('forumtopics', {primaryKey:'_id'});
```

**Comment by marshall007** [comment]
@dan335 you're definitely seeing this result from the second query then. Ordered changefeeds (i.e. `.orderBy(...).limit(...)`) are a little different than typical changefeeds because you get notified of _positional changes_ in addition to the changes on individual documents. In your example, you're being notified that the doc in `old_val`'s position in the feed has been replaced by  `new_val` (since it's `lastPostDate` is now earlier than the previous document).

**Comment by marshall007** [comment]
@dan335 it would probably be more clear to you what's happening if you try again using `includeOffsets: true`.

**Comment by dan335** [comment]
Seems strange.  I thought having includeOffsets be false means don't send updates on changes.  I'm ordering them on the client and don't need to know what order they're in.

Ok, thanks, guess this should be closed if that's how it should work.  Maybe make it clear in the docs?

**Comment by danielmewes** [comment]
It's not so much about ordering changes, but just that one document has left the top `limit` results, and another one has entered the top `limit` in its place. What their positions were/are is not directly reflected in the change notifications.

We could split a notification like this up into one removal of the form `{old_val: ..., new_val: null}`, followed by an addition of the form `{old_val: null, new_val: ...}`. However that would have the disadvantage that there are points when applying the changefeed stream during which you have fewer than `limit` elements in the result.

**Comment by dan335** [comment]
Yeah I would have assumed it would be a remove and added.  Then I would not have to check for if the id is not the same.  I see your point though.
