### ISSUE TITLE
The test runner and or the configure script do not check or install some test dependencies

### ISSUE THREAD

**Issue by tinco** [rethinkdb/rethinkdb#6106]
When running the test runner all ruby tests fail with the error message `can not require 'eventmachine'`. Running `gem install eventmachine` fixes this. I also get a failed test in some python code that looks like this:

```
  File "/home/tinco/Source/rethinkdb/test/rql_test/../common/http_support/server.py", line 183, in <module>
    __runServer(options.httpbinPort, options.httpPort, options.sslPort)
  File "/home/tinco/Source/rethinkdb/test/rql_test/../common/http_support/server.py", line 16, in __runServer
    import twisted.web
ImportError: No module named web
```

I suppose that's a similar issue, but with a python package. I'm not familiar enough with python to fix it.

**Comment by danielmewes** [comment]
Yeah I don't think we do any kind of explicit dependency checking in our tests right now. Might be a useful long-term addition.

Also mentioning @larkost

**Comment by srh** [comment]
FWIW installing the dependencies in the README's in the test directories worked for me.
