### ISSUE TITLE
Yum Dependency Error when upgrading Hadoop

### ISSUE THREAD

**Issue by x10ba** [rethinkdb/rethinkdb#6113]
Hi,
Not sure who owns the conflict, but thought I'd post here first since you've always been responsive.

System: centos 7
upgraded rethinkdb via yum
Horton Data Works upgrade to 2.5 via ambari/ yum gives this error:

I've also opened a ticket with the Hadoop folk, but I imagine (don't want to) I should un-install rethinkdb???

Thanks,
x10ba

date/time - Could not install packages. Error: Execution of '/usr/bin/yum -d 0 -e 0 check dependencies' returned 1. Error: check ['dependencies']
rethinkdb-2.3.5-29864.x86_64 has installed conflicts rethinkdb: rethinkdb-2.3.5-29864.x86_64

**Comment by x10ba** [comment]
Hi,
I just removed rethinkdb and Hadoop installed.
Really disappointed in rdb for not resolving this issue.
Goodbye forever rethinkdb it has been fun.
x10ba

**Comment by xvybihal** [comment]
Is there a SRPM of rethinkdb-2.3.5-29864 available?
