### ISSUE TITLE
Books on RethinkDB

### ISSUE THREAD

**Issue by packtpartner** [rethinkdb/rethinkdb#6115]
Packt has published  few books on RethinkDB '[Getting Started with RethinkDB](https://www.packtpub.com/big-data-and-business-intelligence/getting-started-rethinkdb)'
 We would love to see this book on the project site along with the cookbook.

@larkost can you help me with this?

**Comment by danielmewes** [comment]
Closing here because it's not an issue related to the RethinkDB server.

We don't currently have a section for books on our website, but it makes sense to add one.
