### ISSUE TITLE
Windows Binaries Are Corrupt

### ISSUE THREAD

**Issue by CemraJC** [rethinkdb/rethinkdb#6121]
After downloading windows binaries from [this link](https://download.rethinkdb.com/windows/rethinkdb-2.3.5.zip), any attempts to run the program result in the following message:

> cannot execute binary file: Exec format error

I am running Windows 7, trying to use version 2.3.5 of RethinkDB.
I get the same error in `MSYS` and `cmd.exe`

**Comment by bchavez** [comment]
Hello. The `2.3.5` windows binaries work fine on **Windows 7**.

* Try a different extraction utility: **WinZip**, **WinRAR**, or **7zip**.
* Try disabling anti-virus or other security software that may be interfering with the download.
* Try checking your machine for viruses and/or rootkits that may be interfering with the download.
* Lastly, check your hashes:
```
  File: rethinkdb.exe
CRC-32: 62d17d91
   MD4: 74597e11d6dfc9d55a0710c7a716bcb5
   MD5: a9fbfdf2662f51daa9b430c5e7f869c9
 SHA-1: 237b6559533b1934306551809002569cbf3ed01a
```

:door: :walking: [**Bassnectar - Chasing Heaven - Enter The Chamber**](https://www.youtube.com/watch?v=F18YksSPvkk)

![screen843](https://cloud.githubusercontent.com/assets/478118/18823137/051bb106-836c-11e6-9230-0fde85acb97e.png)

**Comment by CemraJC** [comment]
Hm. That's strange. See below:

![snipshot](https://cloud.githubusercontent.com/assets/9857188/18823421/3f46d7de-83fd-11e6-928b-cb1b174351cb.PNG)


Cool track btw :smile:

**Comment by bchavez** [comment]
Thanks. :+1: 

Hm. That's interesting. Are you using **Windows 7** **64-bit** or **32-bit**?

Hit up `C:\>systeminfo` and maybe dump some more info about `System Type` and `OS *` properties.

:cloud: :sunny: [**Bassnectar - Chasing Heaven - Into the Sun**](https://www.youtube.com/watch?v=a2BAia075lE)

**Comment by CemraJC** [comment]
Ah - of course! 

The PC I'm using is 32 bit... I'll see later if there's a problem with 64 bit computers, but I strongly doubt there will be. Closing this because I didn't read the install page properly :laughing: 

Sorry for wasting your time :confused:
