### ISSUE TITLE
Admin dashboard not working?

### ISSUE THREAD

**Issue by michaelpittino** [rethinkdb/rethinkdb#6129]
Hello, I installed rethinkdb 2.3.5-windows (MSC 190023506) and everything is working so far except for the web interface. It shows `Connected to <Unknown>` but I don't know why. It's also showing me some javascript errors.
Here is a screenshot: https://i.imgur.com/wEp39zA.png

**Comment by danielmewes** [comment]
@michaelpittino See https://github.com/rethinkdb/rethinkdb/issues/5426#issuecomment-247459503 for a work-around.
