### ISSUE TITLE
very slow reads with "majority" read mode

### ISSUE THREAD

**Issue by mollice** [rethinkdb/rethinkdb#6132]
Hello,

I am currently using RethinkDB in a three-shard cluster, with each shard having three replicas. My read mode is set to "majority" and, although it is clearly stated in  the documentation that this is the slowest mode I believe that for some reason it is too slow(in many cases 10 times slower than MongoDB in the same setup and with "majority" selected as the read concern level).

Can someone help me understand why this happens?
Thank you in advance

**Comment by AtnNn** [comment]
You may have better luck finding an answer:

* On stackoverflow: http://stackoverflow.com/tags/rethinkdb
* On slack: http://slack.rethinkdb.com/
* On the mailing list: https://groups.google.com/forum/#!forum/rethinkdb
