### ISSUE TITLE
GetNearest fast in development, slow in deployed cluster

### ISSUE THREAD

**Issue by keighl** [rethinkdb/rethinkdb#6134]
Hey team rethink. I'm having a peculiar issue where a `getNearest()` runs nice and fast on my local machine (~50ms), but very slow on a deployed cluster (~800ms). 

It's the same exact data. About 100 documents (each with a handful of nested data). A geo index on `coordinates`.

**Local machine**
Servers: 1
Version: 2.3.5
Cache: 1.1GB
Client connects directly

**Deployed cluster**
Servers: 3
Version: 2.3.5~0jessie
Cache(each): 1GB
Table replicas on all 3 nodes
Clients connect through a rethink proxy
Deployed via kubernetes

**Query:**

```js
r.db("xxx").table("places").getNearest(r.point(-73.97438, 40.7691017), {
	index: "coordinates",
	maxDist: 14,
	unit: "km",
})
```

Any insight as to what the difference in performance might be? Happy to give more information. 

Thank you all!

**Comment by AtnNn** [comment]
How are you measuring the time?

If you run the query in the data explorer, on your local machine and on the deployed cluster, what times are reported in the *profile* tab, for *round trip time* and the *server time*?

**Comment by keighl** [comment]
hey @AtnNn, thanks. i ended up tearing down the cluster and using a managed [compose.com](http://compose.com) instance. The query runs perfectly on the compose cluster. If I have some spare time, I'll try to reproduce.. but now I'm pretty sure it was user-error on the cluster setup (i.e. me)
