### ISSUE TITLE
Will RethinkDB continue to be open source and dev stay in this repo?

### ISSUE THREAD

**Issue by runvnc** [rethinkdb/rethinkdb#6136]
Hello, I use this and think its great. With news of the company shutting down some people think they should stop using it.

But that doesn't make sense to me since we have a strong open source dev community on this project.  So I plan to continue using RethinkDB, _unless_ somehow the project is retroactively being turned into closed source or something (is that even possible?).  

Nothing like that is going to happen right? People can continue working in this repo in the future?

Thanks.

**Comment by lholznagel** [comment]
In the blog entry they said it will be open source

**Comment by wiredprairie** [comment]
I'd also ask that the maintainers _consider_ changing the license from AGPL now that there isn't a commercial/corporate entity behind the product development. 

Change to Apache 2.0 for example.

**Comment by marshall007** [comment]
@runvnc the source code for RethinkDB and Horizon will remain open source. The docs will also continue to be available and hosted at rethinkdb.com for *at least* the next couple months as we transition (if we can't acquire the domain, we'll work something else out). The goal is to continue making everything accessible in much the same way it always has been.

**Comment by mglukhovsky** [comment]
We've got some news: RethinkDB is joining The Linux Foundation and is relicensed to ASLv2. You can read more here: https://github.com/rethinkdb/rethinkdb/issues/6137#issuecomment-277712805

We'll continue to host source code here and rethinkdb.com will stay running for the foreseeable future. 🌅
