### ISSUE TITLE
Use Collective Code Construction Contract (C4) for maintaining RethinkDB

### ISSUE THREAD

**Issue by wmertens** [rethinkdb/rethinkdb#6145]
C4 is a model for maintaining open source projects and has been used successfully for ZeroMQ and other projects. See https://rfc.zeromq.org/spec:42/C4/, a [blog post describing the success](http://hintjens.com/blog:93), and in particular this graph:

![Commits per week](http://hintjens.com/local--files/blog:93/graph.png)

Basically, any PR that follows C4 will be accepted. A new role, "Project Maintainers" verify that PRs conform to the spec and then merge them. 

> What is most fun is that ZeroMQ takes zero management these days. It is self-steering, self-feeding, and self-organizing. We have applied C4.1 to old projects like libzmq, and brand new ones. The results are the same. If the project does something useful, it takes off, and contributors join, and everyone enjoys themselves.
> 
> C4.1 is an exothermic process. It produces almost perfect software. ZeroMQ's oddities all date from before 2012, and are slowly disappearing. ZeroMQ master is almost always stable. It just does not break stable APIs or protocols. The mailing list is polite and happy. We do not argue.

**Comment by sirinath** [comment]
This is problematic as it is nearly impossible to change the license if the community desires to at a later point. I believe joining something like the ASF is the best option.

**Comment by Morgul** [comment]
@sirinath I guess I don't see the 'license lock in' problem. You can't retroactively change a version's license, but you can always relicense the code for future versions. The [Contributor's Agreement](https://rethinkdb.com/community/cla/) covers RethinkDB in this instance, RethinkDB has the copyright, and therefore can relicense as the project see fit.

I just don't see how relicensing the project is any more or less difficult under C4 than it currently is right now. (And I also don't see how C4 is reliant on any particular license scheme to make it all work, anyway.)

**Comment by AtnNn** [comment]
Thanks for suggesting C4. I haven't used it or studied it, but it contains some suggestions that could be helpful for maintaining RethinkDB.

Part of the appeal of RethinkDB for developers if the culture in which it was written. We've always tried to maintain a balance between pragmatism, correctness, simplicity, elegance and consistency, with a team of very smart, self-motivated and highly opinionated developers. We've reviewed every line of code and tried to test everything. @coffeemug wrote a few articles about this:

* http://www.defmacro.org/2013/06/03/engineering-commandments.html
* http://www.defmacro.org/2013/03/10/effective-handbook.html

I don't know how it would translate into shalls and shoulds, but it would be different from C4. As we transition to a more community-driven model, I hope that we keep the aspects of our current model that make RethinkDB great.

**Comment by wmertens** [comment]
Well, my intent was to raise awareness about the existence and success of
such models, so I'm happy that you saw it.
C4 was highly successful for zeromq, and I would say that your values
around rethinkdb are mirrored in zeromq, so at first glance it would seem
that C4 might be a good fit.

In any case, you can close this issue since my primary intent was achieved,
or you can keep it open to track further progress around this.

**Comment by srh** [comment]
This is too many rules to keep track of (not to mention we're Apache 2, at least for now...).  Right now we're deprived of contributors and my policy is basically accept PR's if they aren't broken or if there isn't something the contributor would agree is a bug.

**Comment by sirinath** [comment]
I home the ASL 2.0 will not change.

**Comment by v3ss0n** [comment]
. It won't change.

**Comment by srh** [comment]
I think there's a half-decent chance MPL might infiltrate a bit if we switch to Spidermonkey in place of V8.

**Comment by v3ss0n** [comment]
Spidermonkey? Any real advantages?

**Comment by srh** [comment]
The version of v8 we have is old and breaks on new compilers. And you need a huge infrastructure download to build the current version of v8.

**Comment by v3ss0n** [comment]
wow never thought of that , how about going new version of V8 ?
