### ISSUE TITLE
Error in time logic: Day of month is not valid for year.

### ISSUE THREAD

**Issue by jagan-veeraraghavan** [rethinkdb/rethinkdb#6146]
Server: RethinkDB 2.3.5
Query:  r.time(2016,7,31).inTimezone('+05:30') 
Error:  Error in time logic: Day of month is not valid for year. 

I checked the calendar and the date seems to be valid. Any idea why this would occur. ( I inserted a total of 7070 records out of which  7000 records were inserted  without issues but only 70 records with this date throws the above error)

I definitely know RethinkDB would get the date correct. But i am out of ideas on where to look for the issue. 
My Machine config 
Linux  3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**Comment by chrisvariety** [comment]
Time expects between 4 and 7 arguments: https://www.rethinkdb.com/api/javascript/time/

Perhaps you want `r.time(2016,7,31,'+05:30')` ? That seems to work for me on my machine running `2.3.4`

**Comment by jagan-veeraraghavan** [comment]
@chrisvariety I was lazy when reporting the bug, I did pass the hour,seconds, minutes args. But i copy-pasted the same code into RethinkDB data explorer, and it works. 

r.time(2016,7,31,13,10,10,'Z').inTimezone('+05:30')
Its still failing only in my NodeJS code.

**Comment by chrisvariety** [comment]
@jagan-veeraraghavan the query `r.time(2016,7,31,13,10,10,'Z').inTimezone('+05:30').run(conn, ...)` works fine in my node.js environment. There's probably something else going on causing the issue.

**Comment by jagan-veeraraghavan** [comment]
Ok Found out the issue. Javascript month being 0-11 range and RethinkDB month param expecting 1-12 range. That was the cause of error. So all those 7000 records that successfully passed are off by one month. Thanks for you help @chrisvariety
