### ISSUE TITLE
Enums

### ISSUE THREAD

**Issue by mcjp78** [rethinkdb/rethinkdb#6149]
Could someone add enum support? I think there is already a pr but no one is merging it

**Comment by mcjp78** [comment]
#5665

**Comment by mcjp78** [comment]
@AtnNn can you merge it

**Comment by AtnNn** [comment]
Do you have a link to the PR?

**Comment by mcjp78** [comment]
https://github.com/rethinkdb/rethinkdb/pull/5665 @AtnNn

**Comment by mcjp78** [comment]
and fixed!
