### ISSUE TITLE
Stylistic improvements to the Data Explorer Suggested

### ISSUE THREAD

**Issue by al3xandru** [rethinkdb/rethinkdb#615]
Some small suggestions for the Data Explorer suggester:
1. Make the API function blue (as is in autocompleter) and link it to the API page (link should open in new page)
2. For possible values of parameters use the same color as in the DE (red)
3. Add sort of a section title for the API description.
4. Change "Ex" to "Example" and make it have the style as the API description section.
5. Use a fixed font for the code snippets. Add a bit of spacing between the example description and the code snippet.
6. Present by default a single example. If there are more in the API docs, add either a "See more examples on API page" link or allow expanding the popup

![DataExplorerSuggester](https://f.cloud.github.com/assets/290841/344954/ba8e0268-9e10-11e2-985e-406fbe5a082f.png)

**Comment by srh** [comment]
The majority of these stylistic issues were addressed, and the next person to work on it might have a different opinion.  Closing.
