### ISSUE TITLE
RethinkDB Java driver "Expected type DATUM but found SELECTION" error

### ISSUE THREAD

**Issue by nthhtn** [rethinkdb/rethinkdb#6152]
I'm using RethinkDB driver for Java. I want to filter the rows without field `endedAt` in table `jam` like this:

    public List<Jam> getCurrent(){
    		Cursor cursor = r.table("jam")
    				.filter(row -> row.hasFields("endedAt")).not()
    				.run(conn);
    		List<Map<String,Object>> list=cursor.toList();
    		return list.stream().map(item->JamRepository.toJam(item)).collect(Collectors.toList());
    	}

And I've got this error `Expected type DATUM but found SELECTION Java`

I have another filter function in another class:

    public List<Speedlog> getByTime(long time){
    		Cursor cursor = r.table("speedlog")
    				.filter(row -> row.g("createdAt").eq(time))
    				.run(conn);
    		List<Map<String,Object>> list=cursor.toList();
    		return list.stream().map(item->SpeedlogRepository.toSpeedlog(item)).collect(Collectors.toList());
    	}

This function works properly

Could anyone please explain what makes the difference between these two? Why does `getCurrent` function get that error? What is its meaning and how to fix? Thank you

**Comment by bchavez** [comment]
I think you have a typo.
```
.filter(row -> row.hasFields("endedAt")).not()
.filter(row -> row.hasFields("endedAt").not())
```
We have an active & helpful slack channel where you can ask quesitons like this. :sunglasses:  https://rethinkdb.slack.com

:hourglass_flowing_sand: :mag: [***"But I still haven't found what I'm for..."***](https://www.youtube.com/watch?v=wdCJRybAtso)

**Comment by AtnNn** [comment]
Did that solution work for you? If you have any other questions please join us on stack, on stackoverflow or on the mailing list. https://www.rethinkdb.com/community/

**Comment by nthhtn** [comment]
Thank you very much, my bad, it perfectly works

2016-10-25 1:42 GMT+07:00 Etienne Laurin <notifications@github.com>:
