### ISSUE TITLE
How to get the current number of the rethinkdb connections?

### ISSUE THREAD

**Issue by lingbage** [rethinkdb/rethinkdb#6164]
I want to monitor the database status. How to get the current number of the rethinkdb connections?

**Comment by marshall007** [comment]
@lingbage you should be able to query the `jobs` table like so:

```js
r.db('rethinkdb').table('jobs')
  .filter({ type: 'query' })
  .count()
```

This will give you the number of active queries. I'm gonna close this since it's just a question, but feel free to continue discussion.
