### ISSUE TITLE
ESLint plugin

### ISSUE THREAD

**Issue by dferber90** [rethinkdb/rethinkdb#6165]
I'd like to experiment with creating an ESLint plugin for RethinkDB. I want it to warn whenever the query is invalid.

Any pointers on where to get started or ideas for additional rules (maybe performance hints)?

I've got the ESLint-part figured out. I talked to @mglukhovsky at ReactiveConf who mentioned there's a library which can take a query AST and produce the warnings. If this is the case then the plugin should be very straightforward and consist mainly of wiring everything up.

**Comment by marshall007** [comment]
@dferber90 this sounds like a great idea! In your mind, what would constitute an "invalid query"? Are you just talking about ensuring all the expressions are passed the correct number and type of parameters?

I'm not sure which library @mglukhovsky was referring to, but I know [`rethinkdbdash`](https://github.com/neumino/rethinkdbdash) does a lot of client-side query validation and produces meaningful errors, so that might be a good place to start.

**Comment by dferber90** [comment]
> In your mind, what would constitute an "invalid query"? 

Parts of a query return different types like `sequence`, `array` and so on. When running a command on the wrong type a warning would be nice. Something similiar seems to be implemented for suggestion feature of the admin interface of RethinkDb already.

Parameter validation is be possible as well, but comes with quite a bit of overhead when the API changes. The user has to specify his RethinkDb version and we need to maintain the rules for all versions. This is something I tried to do with `eslint-plugin-meteor` at first but gave up on because it offered too little benefit for how much work it was.

*I'm not too familiar with the RethinkDB lingo, so excuse me if I used the wrong names here.*

**Comment by AtnNn** [comment]
The [code for suggestions](https://github.com/rethinkdb/rethinkdb/blob/next/admin/static/coffee/dataexplorer.coffee#L2200) in the data explorer uses type information from `reql_docs.js` (available at http://localhost:8080/js/reql_docs.js if you have RethinkDB running). It looks like this:

```
reql_docs = {
  "api/javascript/add/": {
    "name": "add"
    "io": [
      ["number", "number"], 
      ["string", "string"], 
      ["time", "number"]
      ...
```

Where `io` is a list of pairs of the possible input and output types used by RethinkDB. For more information about these types, see https://rethinkdb.com/docs/data-types/ and https://github.com/rethinkdb/rethinkdb/blob/next/src/rdb_protocol/ql2.proto#L262-L281
