### ISSUE TITLE
Install not working on Linux Mint 18 (Sarah)

### ISSUE THREAD

**Issue by adadgio** [rethinkdb/rethinkdb#6166]
Is there a way to install Rehinkdb on Linux Mint 18 ?

The process described on the install tutorial is not working (package seems to be unavailable for linux mint 18).

https://www.rethinkdb.com/docs/install/mint/

Thank you.

**Comment by AtnNn** [comment]
Yes. Linux Mint 18 is based on Ubuntu Xenial, for which packages are available.

Does replacing `saucy` with `xenial` in the instructions work for you?

```
echo "deb http://download.rethinkdb.com/apt xenial main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
```

**Comment by adadgio** [comment]
Thank you! I lack knowledge on linux. Have a great day.

**Comment by AtnNn** [comment]
We'll be adding Linux Mint 18 to the docs. https://github.com/rethinkdb/docs/pull/1188
