### ISSUE TITLE
Cant connect to other replica sets

### ISSUE THREAD

**Issue by ericholiveira** [rethinkdb/rethinkdb#6174]
I've been using rethinkdb in production for a while, and it`s not the first time one of the servers crash, when this happens i usually just restart the process and everything works. But now one of my servers cant connect to the replica set and i keep seeing an error message on the html administrator. Also, as this server just cant become online again i cant connect a program to it...
Looking at the log i only see this message:

```2016-11-14T19:30:06.031741059 0.035625s notice: Running rethinkdb 2.3.4~0trusty (GCC 4.8.2)...
2016-11-14T19:30:06.034079625 0.037962s notice: Running on Linux 3.13.0-74-generic x86_64
2016-11-14T19:30:06.034109924 0.037991s notice: Loading data from directory /var/lib/rethinkdb/cluster_instance/data
2016-11-14T19:30:06.049263399 0.053147s info: Automatically using cache size of 3146 MB
2016-11-14T19:30:06.050975077 0.054856s notice: Listening for intracluster connections on port 29015
2016-11-14T19:30:06.051141745 0.055023s info: Attempting connection to 2 peers...```

The other 2 servers are running fine... and i already tried to telnet to those servers and everything is ok...
What else can i do to track the problem?

**Comment by AtnNn** [comment]
I'm sorry to hear you're running into issues.

Is your server configured with the correct and current address and port of the two remote peers? Is that port on the peers (default 29015) accessible from your instance? Does RethinkDB give you any other indication or error message as to why it might not be able to connect?

**Comment by ericholiveira** [comment]
Yes...the ips are correct... i can telnet on this port and a i receive a message like this?
```RethinkDB cluster
2.3.0```
 and  this is the only thig i can see in the logs

**Comment by AtnNn** [comment]
If you open the server's web UI dashboard, does it report any issues?

**Comment by ericholiveira** [comment]
Yes, it does.. but the only message tells me that one of the servers is unavailable

**Comment by zllovesuki** [comment]
Do you have a proxy node running somewhere? If one of instance crashed in the cluster, the proxy may not reconnect to that one, thus the web interface complaining about "disconnected server".

**Comment by ericholiveira** [comment]
No proxies... just direct connection on aws vpc... anyway... i think i can close the issue as i migrated the database...
