### ISSUE TITLE
Rethinkdb tables somehow got duplicated causing all services to go down

### ISSUE THREAD

**Issue by thomasmodeneis** [rethinkdb/rethinkdb#6179]
Hi,

I don't even know how to start.
This morning I got alert form service provider saying that something was f. with their service, and all of a sudden rethinkdb cluster went down.

All good, I went to check first the apps, rethinkdbdash is driver reporting `there are multiple databases with that name.` WHAT ??? 
` msg: 'Database `test` is ambiguous; there are multiple databases with that name.'`

I found this so weird, but I went to check on the databases....
It turns out that ALL tables are now duplicated, the cluster is completely corrupted and I've lost all my data! :|

Lucky me, I did a backup yesterday afternoon so I can restore, but I lost several requests, customers are waiting on the line, people are angry etc etc, all that kind of cool startup stuff :D

I'm really surprised and sad at the same time with this.

Possible related to:
https://github.com/rethinkdb/rethinkdb/issues/4898
and 
https://github.com/rethinkdb/rethinkdb/issues/5900

**Comment by chrisvariety** [comment]
Hi @thomasmodeneis 

Apologies this happened to you. We've seen this happen when two servers that were supposed to be separate rethinkdb instances joined each other (due to a server misconfiguration.) Are your running more than one rethinkdb instance that are supposed to be separate from each other? Or perhaps a production instance and a staging instance? The most likely scenario is that they joined each other, which can lead to this problem.

You should be able to rescue yourself out of this scenario without data loss. The following command will help you find one db named `test` and rename it to `test2`:

```
r.db('rethinkdb').table('db_config').filter({name: 'test'}).nth(0).update({name: 'test2'})
```

You can do a similar thing with the `table_config` table if you have multiple tables with the same name.

**Comment by thomasmodeneis** [comment]
Right, but now it returns me two tables.
What is the criteria you are using for renaming the very first row to test2 ?
You are supposing that the first one is the newest ?

Cheers.

**Comment by thomasmodeneis** [comment]
To reply your questions:
`Are your running more than one rethinkdb instance that are supposed to be separate from each other?`
I'm running a cluster of two instances. (I know thats not recommended, maybe the cause ? but thats what I can afford with my budget, 2x 16GB ram is minimum for me to have my databases started with the amount of data there is in it...its about >70GB)

`Or perhaps a production instance and a staging instance?`
staging is completely out of the equation as its running in a closed env with no access to outside world.

`The most likely scenario is that they joined each other, which can lead to this problem.`

That for sure never happened.

**Comment by thomasmodeneis** [comment]
Hi,

So I happen to understand the defect a bit better, this is what happened:

One of my devs started a proxy connecting to prod on the same server that pp1 was running.
This proxy was started with:
`rethinkdb proxy --join prod-01:29015 --port-offset 1`

So this caused the actual pp1 server to somehow connect to prod (via this proxy) and mess up the entire database.
When I connected to pp1 server yesterday I notice it was connected to prod, as there was 3 servers in the cluster (OMG), but when I check prod it was not connecting back to pp1 env.
 
I've double checked all the rethinkdb configurations and I can confirm it was not configured to join any other server, so the proxy getting into the way was weird.

I'm surprised by this behaviour, but at least now I know who is the culprit :)

Cheers.

**Comment by AtnNn** [comment]
Sorry you ran into this. It looks like a variant of issue #1905.

**Comment by thomasmodeneis** [comment]
It looks like a variant of that, however if you are going to close this you will have to update the existing one to say what happened on this ticket:
This ticket was the proxy that connected one pp1 server to the prod cluster; Having in mind that the pp1 server have never joined the prod cluster by configuration, the proxy did the bridge and screwed the scene.

It will be very nice if you could reflect this on the ticket that will remain open.
Cheers.
