### ISSUE TITLE
Ruby driver connections might become corrupted if we are interrupted after having `recv`d only half of a protobuf.

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#618]

**Comment by danielmewes** [comment]
@mlucy Do you know if this is still true?

**Comment by mlucy** [comment]
I do not.  I never explicitly did anything to fix it.

**Comment by Tryneus** [comment]
If the interruption results in an exception, it looks like we will close the connection and error out any queries.

**Comment by thelinuxlich** [comment]
@srh since the move from protobuf to json, do you think this is still an issue?
