### ISSUE TITLE
Order of statements in "or" matters, but shouldn't

### ISSUE THREAD

**Issue by coffenbacher** [rethinkdb/rethinkdb#6181]
Repro in python driver:

```
r.db_create('test').run(c)
r.db('test').table_create('example').run(c)
r.db('test').table('example').insert({'example_field': True}).run(c)
print r.db('test').table('example').filter(r.row['example_field'] | r.row['other_field']).count().run(c)
# 1
print r.db('test').table('example').filter(r.row['other_field'] | r.row['example_field']).count().run(c)
# 0
r.db_drop('test').run(c)
```

I'm not sure what's going on here.

Driver version: '2.3.0.post6'
Server version: rethinkdb 2.3.1~0jessie (GCC 4.9.2)

**Comment by AtnNn** [comment]
`filter` defaults non-existence errors to `false`, and `|` performs short-circuit evaluation. That leads to the behaviour you have very elegantly described.

You've stumbled upon an old issue. This is a duplicate of #1721. I think we all agree this behaviour isn't ideal, but there is no consensus on whether or how to fix it. See also the discussion in #1580, #1720 and #2030.

**Comment by coffenbacher** [comment]
It makes sense that the non-existence part of the expression evaluates to False. I guess I'm confused how (False | True) gets short-circuited to False, since unless I'm missing something you cannot ever short-circuit an OR to False. 

Is what's actually happening that the error bubbles out of the expression and is then evaluated to False?

Anyways, thanks for linking the relevant discussions, it seems that the general behavior has been covered in depth. Hopefully this issue can serve as a Google beacon for this particular manifestation of the behavior.

**Comment by AtnNn** [comment]
Yes. The error bubbles out of the expression and is then caught by `filter`, which treats it as False.
