### ISSUE TITLE
Update nested array (ref. example Updating nested fields)

### ISSUE THREAD

**Issue by tudorels** [rethinkdb/rethinkdb#6182]
Regarding the example from your site "Update nested fields", I want to know how can I update an array as notes. For example

```
{
  id: 10001,
  notes: [
    {
      data: r. time (2014,1, 1, ' Z '),
      from: "John Doe",
      subject: "My name is even more boring than Bob's"
    },
    {
      data: r. time (2014,2, 2, ' Z '),
      from: "Bob Smith Sr"
      subject: "Happy Second of February"
    }
  ]}
```

I want to update only subject on note from "John Doe". It is possible without altering other data in array?
Thank you!

**Comment by AtnNn** [comment]
Yes, it's possible. You can use `map` and `branch` together, or `changeAt` and `offsetsOf`.

If you have any more questions, please join us on Slack, Stackoverflow or on our mailing list: 

https://rethinkdb.com/community/

**Comment by tudorels** [comment]
In this case the example provided on your site is incomplete!

**Comment by chrisvariety** [comment]
@tudorels Not sure which page/section specifically you're referring to but please definitely open up an issue [on the docs repo](https://github.com/rethinkdb/docs) if something is wrong!

**Comment by tudorels** [comment]
Is not wrong, is incomplete. I can not find an example for the need I wrote above. The page is [https://rethinkdb.com/api/javascript/update/] to section "Updating nested fields". Thank you!

**Comment by AtnNn** [comment]
I've created https://github.com/rethinkdb/docs/issues/1189
