### ISSUE TITLE
Using between() and distinct()

### ISSUE THREAD

**Issue by jiteshtukadiya** [rethinkdb/rethinkdb#6184]
I am doing a query in rethink db,

    r.db('main').table('log').distinct({index: 'number'}).between(r.epochTime((new Date).setHours(0, 0, 0, 0)/1000), r.epochTime((new Date).setHours(23, 59, 59, 99)/1000), {index: 'createdAt'}).count()

`number` and `createdAt` are two secondary indexess. Doing this will generate the error as We are not allowed to use multiple secondary indexes in single query. I've tried to create compound index using this [link][1], but its different from my problem. Can anyone help me create compound index for above query ?

Thanks in advance.
Jitesh.

  [1]: http://stackoverflow.com/questions/19656785/how-do-i-intersect-multiple-secondary-index-queries

**Comment by jiteshtukadiya** [comment]
All I want is to get unique counts(based on number) for today(based on createdAt). If you have other suggestions, please suggest.

**Comment by zllovesuki** [comment]
1) How do the documents look like (e.g. data structure)?
2) Maybe you can use a secondary index like this one: https://www.rethinkdb.com/docs/secondary-indexes/javascript/, "Use a multi index and a mapping function to speed getAll/contains"

**Comment by jiteshtukadiya** [comment]
Thanks for the reply, 

My table looks ( not exactly ) something like this,

    [
        {
            "createdAt": Tue Nov 22 2016 05:55:00 GMT+00:00,
            "id": "627b133a-39fb-4bf6-99c5-d7d79962868d",
            "isActive": true,
            "isDelete": false,
            "keyword": "KEY",
            "msgType": "invalid",
            "number": "9876543211",
            "status": 0
        },
        {
            "createdAt": Tue Nov 29 2016 05:54:28 GMT+00:00,
            "id": "627b133a-39fb-4bf6-98c5-c7d79962868d",
            "isActive": true,
            "isDelete": false,
            "keyword": "KEY",
            "msgType": "invalid",
            "number": "9876543210",
            "status": 0
        },
        {
            "createdAt": Tue Nov 29 2016 05:55:20 GMT+00:00,
            "id": "627b133a-39fb-4bf6-99c5-c8d79962868d",
            "isActive": true,
            "isDelete": false,
            "keyword": "KEY",
            "msgType": "invalid",
            "number": "9876543212",
            "status": 0
        },
        {
            "createdAt": Tue Nov 29 2016 05:55:50 GMT+00:00,
            "id": "627b133a-39fb-4bf6-99c5-c7d799628680",
            "isActive": true,
            "isDelete": false,
            "keyword": "KEY",
            "msgType": "invalid",
            "number": "9876543210",
            "status": 0
        },
        {
            "createdAt": Tue Nov 29 2016 05:58:12 GMT+00:00,
            "id": "627b133a-39fb-4bf6-99c5-c7d79962868e",
            "isActive": true,
            "isDelete": false,
            "keyword": "KEY",
            "msgType": "invalid",
            "number": "9876543210",
            "status": 0
        }
    ]

Secondary indexes
- createdAt
- number

Now you can see there are five rows. But if you see there are 3 distinct(unique) row with respect to number, but for today( dated 29) the distinct (unique) count is 2 and that is what I want. I tried to use the following query but no luck with that.

    r.db('main').table('log').index_create('compound__index', [r.row['createdAt'], r.row['number']])

    r.db('main')
        .table('log')
        .between(r.epochTime((new Date).setHours(0, 0, 0, 0)/1000), r.epochTime((new Date).setHours(23, 59, 59, 99)/1000), {index: 'compound__index'})
        .distinct({index: 'compound__index'})

**Comment by marshall007** [comment]
@jiteshtukadiya you could try creating your compound index using `r.row['createdAt'].date()`, that way the first element of your compound index is not unique across multiple documents with the same `number` on a given day. This should result in your `distinct` working as you intended.

**Comment by jiteshtukadiya** [comment]
@marshall007 , You mean should I do like this ->

    r.db('main').table('log').index_create('compound__index', [r.row['createdAt'].date(), r.row['number']])

**Comment by marshall007** [comment]
@jiteshtukadiya yea, sorry. Emphasis was on the `.date()` part.

**Comment by mholt** [comment]
What was the query you ended up using, after creating the index? I'm not able to get any results when using the same compound index for both `between()` and `distinct()`. (JavaScript)
