### ISSUE TITLE
Not possible to modify the url in r.http

### ISSUE THREAD

**Issue by ebr00ks** [rethinkdb/rethinkdb#6186]
Variables passed to the anonymous containing a r.http request by map are not accessible inside the url parameter and there is no path equivalent to the params options. 

```
r.expr([111, 222]).map(function(i) {
  return r.http('https://app3.bposerver.com/path.php/dir/'+ i +'.txt', { params: { user: i } });
})
```

note _i_ is parsed in the url param as var_16. 
```
[
"{"path_info":{"dirname":"\/dir","basename":"var_16.txt","extension":"txt","filename":"var_16"},"get":{"user":"111"},"post":[]}" ,
"{"path_info":{"dirname":"\/dir","basename":"var_16.txt","extension":"txt","filename":"var_16"},"get":{"user":"222"},"post":[]}"
]
```

**Comment by AtnNn** [comment]
Native JavaScript operations like `+` do not work Inside ReQL queries when manipulating variables bound by the query.

Instead, you can use `add` like this:

```
r.expr('https://app3.bposerver.com/path.php/dir/').add(i).add('.txt')
```
