### ISSUE TITLE
Speed Test

### ISSUE THREAD

**Issue by minimok** [rethinkdb/rethinkdb#6188]
I've set up rethink on a Macbook Pro with 8 GB RAM and a 2.6 GHz processor.

I've run an insert test as follows:

`function insertRec(){
        r.table('tbl').insert(rec).then((res)=>{
             insertRec()
      })
}`

Achieving 10,000 writes takes 116 seconds! This is 88(ish) recs/sec....only marginally faster than I could write the data by hand:-) 

Presumably I'm doing something horribly wrong - care to point it out for me?

**Comment by chrisvariety** [comment]
You can batch insert an array which will be much faster: `r.table('tbl').insert([rec1, rec2, rec3])`

**Comment by minimok** [comment]
Thx - that may be the solution...I did this test to get an idea of how a site with 10K users is going to perform if backed by rethinkdb. Setting durability to soft does help somewhat...but I'll need to spin up a test to simulate a few 000s of clients all trying to write simultaneously. Love the api - but performance looks like an issue - I need to get my user onto and then off the node event loop in milliseconds rather than seconds.
