### ISSUE TITLE
getAll and Join index

### ISSUE THREAD

**Issue by wilywork** [rethinkdb/rethinkdb#6189]
Hi, my tables have index, 
I am not able to filter the two tables using the indexe.

```
r.db("dbase").table("areaDeAtuacao")
    .getAll(315130, {index:'idvendedor'})
    .eqJoin({index:'area_desc_ufsigla'}, r.db("dbase").table("cidades"), {index:'desc_ufsigla'}).zip()
```

**Comment by marshall007** [comment]
@wilywork RethinkDB doesn't currently support chaining expressions using multiple, different secondary indices. You'd have to do something along these lines instead:

```js
r.db("dbase").table("areaDeAtuacao")
    .eqJoin({index:'area_desc_ufsigla'}, r.db("dbase").table("cidades"), {index:'desc_ufsigla'}).zip()
    .filter({ idvendedor: 315130 })
```

Let us know if you have any other questions.
