### ISSUE TITLE
rethinkdb crash

### ISSUE THREAD

**Issue by aaronorosen** [rethinkdb/rethinkdb#6190]
I noticed rethinkdb not running this morning. I haven't seen it crash really before and has run for over a month no issues. I'm trying to do a little digging to understand why (and also to better understand future issues I might run into with rethinkdb) 
I'm running: 2.3.5~0trusty

The crash occurred on December 6th: 

Looking at the log file (<from directory>/log_file) the server did not log anything related to the crash. There was one log entry on Dec 12th - and then again on the 16th after I started the server up again: 

```
2016-12-02T19:05:48.048270307 2307900.290718s info: Table 55b5efe1-6cf3-4173-a184-070993c97a6d: Configuration is changing.
2016-12-06T16:33:26.642650398 0.151485s notice: Running rethinkdb 2.3.5~0trusty (GCC 4.8.2)...
```

dmesg does have the following I'm not sure if this is related but figured it could be: 

```
[  212.913872] perf samples too long (2525 > 2500), lowering kernel.perf_event_max_sample_rate to 50000
[  591.113066] perf samples too long (5027 > 5000), lowering kernel.perf_event_max_sample_rate to 25000
[ 6608.961394] perf samples too long (10006 > 10000), lowering kernel.perf_event_max_sample_rate to 12500
[149905.624008] perf samples too long (20119 > 20000), lowering kernel.perf_event_max_sample_rate to 6250
[1080621.220045] [sched_delayed] sched: RT throttling activated
[2599514.981304] Core dump to |/usr/share/apport/apport 16828 11 0 16828 pipe failed

```

There was also a crash file created in /var/crash http://codepad.org/gcI9SK8s

Anything else I should check? Or ideas why it crashed? 

(on another note it would be good if the rethinkdb init scripts auto started the server after it crashed)

**Comment by AtnNn** [comment]
I can't tell from the logs and crash file why the server died.

When a RethinkDB server crashes without writing anything to it's log file, it often means that it ran out of memory or disk space. But I don't see any indication of that in your dmesg log.

**Comment by aaronorosen** [comment]
Me either. I have seen the OOM error before in the dmesg logs (but not this time). Also server did not run out of space.  I'll report back if it crashes again and if I can dig up anything else. Thanks.

**Comment by aaronorosen** [comment]
closing since i haven't seen this happen again since.
