### ISSUE TITLE
All of a sudden, nodes are dying everyday

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#6192]
It's a cluster with 5 nodes, resources are plenty, dataset has millions of rows.

Long backtrace: https://gist.github.com/thelinuxlich/c4dc2d7eef109c36380d86fe27add6c2

**Comment by thomasmodeneis** [comment]
Hi @thelinuxlich is this still a issue for you ? 
I see that https://github.com/rethinkdb/rethinkdb/pull/6193 proposed for  2.3.x, 2.3.6 has something to do with this issue.

**Comment by thelinuxlich** [comment]
It's still a issue because I'm waiting for the new release

**Comment by thelinuxlich** [comment]
Unfortunately, none of the fixes of 2.3.6RC1 solved my problem. Nodes are disconnecting with a short message of heartbeat timeout constantly:

![rethink](https://user-images.githubusercontent.com/5043/27709905-39bb922a-5cf4-11e7-84e1-69dc34269b3f.png)

**Comment by thelinuxlich** [comment]
Before 2.3.6 I was seeing this error: https://gist.github.com/thelinuxlich/fc17ad35a43a9acebfe34fc50aef203c

**Comment by marshall007** [comment]
@thelinuxlich we were running into similar issues in our three node cluster lately. We were able to totally resolve it by adding two additional nodes to the cluster (probably a bit overkill) and adjusting the `oom_score` for all rethinkdb processes.

Do you know what's killing the process in your case? Is it OOM? Based on the logs you provided it appears that rethinkdb is getting killed by the kernel or something, not crashing on its own.

**Comment by thelinuxlich** [comment]
I am running a 5 node cluster and they aren't consuming even half the available memory yet(cache is 33%)

**Comment by marshall007** [comment]
@thelinuxlich sure, but some other user/process is sending the server a `SIGTERM`. You'll need to use `dtrace` or something to figure out what that is.

**Comment by thelinuxlich** [comment]
I will investigate, thanks for the tips

Em qui, 29 de jun de 2017 19:21, Marshall Cottrell <notifications@github.com>
escreveu:

**Comment by Extarys** [comment]
Please let us know what you find out!

**Comment by lucasjans** [comment]
@thelinuxlich did you discover anything here? we're having similar issues see #6468

**Comment by thelinuxlich** [comment]
Hi @lucasjans, sorry for not updating this issue. After updating to 2.3.6 the cluster is totally healthy.
