### ISSUE TITLE
High load to CPU

### ISSUE THREAD

**Issue by YaroslavLyzlov** [rethinkdb/rethinkdb#6196]
3 rethinkdb instances, 
1: 4 cores, 16 ram
2,3: 4 cores, 8 ram

5 tables
messages (3 shards, 3 replicas, 5 indexes, document 17 fields) - 1m~
files (3 shards, 3 replicas, 4 indexes, document 7 fields ) - 90k ~ (only metadata, no binary)
sessions (1 shard, 1 replica, 4 indexes, document 17 fields) - 100k~
tickets (3 shards, 3 replicas, 6 indexes, document 17 fields) - 20k~
auth (3 shards, 3 replicas, 1 index, document 15 fields) - 1k~ (auth records, often insert/update/remove)
At some point rethink begin die (all instances cpu 80-90%) and take a lot of memory and go to swap.
On rethinkdb monitoring max 30 write/s (standard load), read/s - 0 - 70000 (standard load)
For all updates and inserts i use durability: 'soft'
Tell me if you need more info
Thanks!

**Comment by YaroslavLyzlov** [comment]
up!
help, please :(

**Comment by Bennyelg** [comment]
Hey, 
When this problem started
Can you back it up with some images?
please provide ps -ef & top screen.
+ the read write screen. 
do you use durability hard on inserts?
I want to investigate it because I experience something similar after the 5th table. which I just added 4 days ago.

**Comment by YaroslavLyzlov** [comment]
Hi
cpu average: 60-80 % (all cores)
memory increase
read write is normal (10-60 w/s)
some inserts are starting to work very slowly (1 - 50 (!!!) seconds)
i use only soft inserts/updates (hard is slow for me)

Monday will try to make screenshots

**Comment by YaroslavLyzlov** [comment]
my theory: at some point rethink want all data from memory saves to hard drive and at this point use all cpu resources :(

**Comment by YaroslavLyzlov** [comment]
and in this moment VIRT memory in htop increases (1 min - 2gb)

**Comment by srh** [comment]
Closing because this is an old support request.  Let us know if you run into trouble again.
