### ISSUE TITLE
How to delete a paticular Object in an array in RethinkDB (e: Cannot nest writes or meta ops in stream operations.  Use FOR_EACH instead in:)

### ISSUE THREAD

**Issue by githubitsme** [rethinkdb/rethinkdb#6200]
I am little Bit Confused That how to delete an single Object in an array,What is the Exact query I have to use if i have to delete this Object

     {
            "name":  "Ram" ,
            "username":  "B97bf210-c4d2d-11e6-b783-07b5fev048705"
            }
from whoLikedIt Array
My data

            {
            "comments": [ ],
            "id":  "c242c74d-03d9-4963-9a22-4779facb8192" ,
           .....
            "views": 0 ,
            "whoLikedIt": [
            {
            "name":  "Vignesh Warar" ,
            "username":  "d97bf210-c42d-11e6-b783-07b5fe048705"
            },
    {
            "name":  "Ram" ,
            "username":  "B97bf210-c4d2d-11e6-b783-07b5fev048705"
            },
            
            
            ]
        .....
            }

My Try

    r.db('image').table('posts').get('c242c74d-03d9-4963-9a22-4779facb8192').update(
      {whoLikedIt:r.row('whoLikedIt').filter({username:"B97bf210-c4d2d-11e6-b783-07b5fev048705"}).delete()}
    )

Throws Me a error

    e: Cannot nest writes or meta ops in stream operations.  Use FOR_EACH instead in:

**Comment by chrisvariety** [comment]
This should work:

```js
r.db('image').table('posts').get('c242c74d-03d9-4963-9a22-4779facb8192').update(function(post) {
  return {
    whoLikedIt: post('whoLikedIt').filter(function(liked) {
      return liked('username').ne('B97bf210-c4d2d-11e6-b783-07b5fev048705')
    })
  };
})
```
