### ISSUE TITLE
Strange result decimal.

### ISSUE THREAD

**Issue by pongpanot-t** [rethinkdb/rethinkdb#6213]
I'm sorry. I'm not understand result of below.
r.expr(1.123).add(1.123).add(1.123)      //3.3689999999999998
r.expr(1.123).mul(3)         //3.3689999999999998

//Why result isn't 3.369

**Comment by srh** [comment]
Because numbers in RethinkDB use a binary representation: https://en.wikipedia.org/wiki/Double-precision_floating-point_format
