### ISSUE TITLE
Zlib.sh is pointing to wrong URL

### ISSUE THREAD

**Issue by mslaats** [rethinkdb/rethinkdb#6216]
File /mk/support/pkg/zlib.sh is pointing to zlib 1.2.8 and url http://www.zlib.net/zlib-1.2.8.tar.gz
But the old versions of zlib, including 1.2.8, are located at http://www.zlib.net/fossils/zlib-1.2.8.tar.gz

**Comment by srh** [comment]
Ooh, thank you.

**Comment by AtnNn** [comment]
Fixed in #6220
