### ISSUE TITLE
Consider using C++-style system headers (<cfoo> instead of <foo.h>)

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#6217]
C-style headers are possibly deprecated since C++11, and the use of `math.h` has caused portability issues in the past (#4049, #4437, #5450, #5635, #5926).

However there are some potential disadvantages, such as exports being placed in the `std` namespace.

Previously discussed in https://github.com/rethinkdb/rethinkdb/pull/6163#pullrequestreview-14416825

**Comment by srh** [comment]
Can we close this?  I've considered using them and concluded it's a bad idea.
