### ISSUE TITLE
Change license to a friendlier one?

### ISSUE THREAD

**Issue by mrkafk** [rethinkdb/rethinkdb#6221]
Where I work Affero GPL is under total ban, no questions asked. Would you consider changing the license to something friendlier like say Mozilla Public License which as far as I know has this nice property of working "file by file", that is, if you change a file, you only have to made this file public? Or perhaps even to something like Apache license?

**Comment by AtnNn** [comment]
There is some ongoing effort in that direction. See https://goo.gl/r8GGAK

**Comment by wishinghand** [comment]
@mrkafk 
I'm bad at reading licenses and figuring out the legalese- why is AGPL so disliked by companies?

**Comment by mrkafk** [comment]
@wishinghand The main reason is viral aspect of AGPL "infecting" software combined with triggering public disclosure of "combined work" on network service (sending data out of organisation). Anybody does anything even in dev mode that results in sending data out, strictly legally speaking you'd have to disclose entire solution. What makes it even worse is unclear and ambiguous language of the license that could result in court deciding this, other or another way what is scope of combined work, if disclosure triggers, etc. and it was not tested in courts either. There's no distinction between prod and dev uses, etc.

**Comment by v3ss0n** [comment]
the current team is working on it , mean while please try latest rethinkdb on  Next branch! Community and Ex-Devs are working hard to push 2.4 release. Hopefully legal stuff will get done within this year.

**Comment by uchuugaka** [comment]
Hope this comes to fruit with Apache, BSD or MIT style licensing. So many companies are unwilling to touch anything GPL. As an interesting example, such pressure came from the community to Perfect the Swift language based web server project. They eventually relented and moved to an Apache license. This increased their adoption significantly.

**Comment by v3ss0n** [comment]
see https://github.com/rethinkdb/rethinkdb/issues/6137#issuecomment-275968142
from word of ex-Founder , relicensing is not a choice anymore.
We have to close this issue.  @mrkafk  can you close it?

**Comment by rushmorem** [comment]
@v3ss0n I don't think @coffeemug has entirely dismissed the possibility of re-licensing. Please see https://github.com/rethinkdb/rethinkdb/issues/6137#issuecomment-276025096. I don't think it's time to close this issue yet. Since the community feels strongly about this, it's something that has to be fought for till it happens.

**Comment by Art-B** [comment]
Wouldn't it be better to just seek clarification on the AGPL? It would benefit more projects, and would cause no IP issues. The AGPL's heart is in a good place, it's just a matter of throwing lawyers at the technical details non?

**Comment by v3ss0n** [comment]
@Art-B  how we do to educate the mass ? That FUD is spread by Giants , how people will believe in a bunch of RethinkDB enthusiasts over those tech giants ?

**Comment by mglukhovsky** [comment]
We've got some news: RethinkDB is joining The Linux Foundation and is relicensed to ASLv2. You can read more here: #6137 

Looking forward to building RethinkDB's open-source future together. 🌅

**Comment by mrkafk** [comment]
@mglukhovsky Fanastic news!!! Thank you so much!

I will recommend RethinkDB to my company right away.

**Comment by mrkafk** [comment]
@Art-B Maybe Affero GPL has its heart in the right place, but it has its "brain" in all kinds of wrong places. AGPL is a serious legal risk for anybody using it. It's hard to say what kind of risk because to my best knowledge all the court cases involving open source licenses so far have been settled out of court, but it's legally risky nonetheless. To reiterate, we'd be fine even with plain GPLv2 or GPLv3. But not with Affero.

Nevertheless, what's really the point of *GPL? Forced sharing? If people do not want to share, they will not do it, with *GPL terms and conditions or without them. Much of the software under permissive licenses like MIT or ASL flourishes and has lots of contributors, just look at ASF stuff. Adding legal risks to that just stymies contribution and shared development, not helps it.
