### ISSUE TITLE
Surprising (broken?) r.or() behavior

### ISSUE THREAD

**Issue by oliverjanik** [rethinkdb/rethinkdb#6227]
Version:  2.3.5
OS: Ubuntu 16.04 LTS

Setup:
```js
r.db('test').table('cities').insert({ city: 'Sydney'})
```

Query A returns 1 result:
```js
r.db('test').table('cities').filter(function(i) {
  return r.or(i('city').eq('Sydney'), i('country').eq('AU'));
});
```

Query B returns 0 results:
```js
r.db('test').table('cities').filter(function(i) {
  return r.or(i('country').eq('AU'), i('city').eq('Sydney'));
});
```

This feels super wrong. I think it's the missing value that's causing this.

**Comment by srh** [comment]
`r.or` short-circuits, so that if the first argument evaluates to true, the second is not evaluated.  You could see this error, for example, by replacing `filter` with `map`.

Also, `filter` silently discards rows for which a missing field error happened.

**Comment by marshall007** [comment]
You can configure the behavior mentioned by @srh using the `default` optarg.

```js
.filter(..., { default: true }) // return docs with missing fields
.filter(..., { default: r.error() }) // propagate missing field errors
```

**Comment by oliverjanik** [comment]
@marshall007 Thank you for that. Default behaviour while logical violates the principle of least surprise. I think I'm going to do default: false on all my filters from now on. Just like SQL deals with nulls.

**Comment by marshall007** [comment]
@oliverjanik, just to be clear, `false` is the default and results in the behavior you outlined in"Query B".

**Comment by oliverjanik** [comment]
Are you saying that default applies to the entire row? That's useless then... 

I want the nested comparison to return false. kinda like this (undefined == 'AU' || 'Sydney' == 'Sydney') for that particular data point. Is that achievable?

**Comment by marshall007** [comment]
@oliverjanik correct, you'd have to do `i('country').eq('AU').default(false)` within the `filter`.
