### ISSUE TITLE
Can't install on debian stretch: Depends: libprotobuf9v5 but it is not installable

### ISSUE THREAD

**Issue by yglukhov** [rethinkdb/rethinkdb#6228]
```
The following packages have unmet dependencies:
 rethinkdb : Depends: libprotobuf9v5 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

[Travis build log trying to install RethinkDB](https://travis-ci.org/yglukhov/rethinkdb/builds/192018568)

**Comment by AtnNn** [comment]
It looks like the rethinkdb package was built with an older version of stretch that included an older version of protobuf. I'll try to build newer stretch packages.

**Comment by AtnNn** [comment]
I've added stretch to the nightly builds, but the build fails. I think #6205 might fix it.

http://thanos.atnnn.com/job/rethinkdb/daily-v2.3.x/stretch-amd64

**Comment by ekle** [comment]
any news on this ?

**Comment by srh** [comment]
There is no news right now.  It's on my list of things I care about, but the following have gotten my more immediate attention:
- releasing packages for backported fixes from http://github.com/srh/rethinkdb/tree/sam/delayed that improve soft durability performance
- getting rid of the v8 dependency, because that causes a lot of pain in building and newer platforms (v8 is failing on the newer gcc's, clang's and keeps needing patches)
- figuring out how to build the v2.3.x branch on macOS

You might be able to convince me that compiling on stretch is higher priority than the latter two.

**Comment by ekle** [comment]
maybe "getting rid of the v8 dependency" makes it easier to make the stretch build?
as stretch stable will release soon, and people(like me) are already testing if their stack works on it,
it would be a benefit to support it.

**Comment by srh** [comment]
If you look at https://github.com/srh/rethinkdb/tree/sam/rebased/bignum

You can see some progress I've made in getting stretch to build out of the box (with `./configure --allow-fetch`).  With libcurl4-openssl-dev and libssl-dev, I get a link-time warning that there might be a version mismatch.  If you remove both, or use `--fetch curl --fetch ssl --fetch crypto` you might have a compile work with plain `./configure --allow-fetch`.  I have no idea whether build-deb would work.

**Comment by Alkorin** [comment]
Any news about the Debian stretch package ?

It is still broken :(

```
The following packages have unmet dependencies:
 rethinkdb : Depends: libprotobuf9v5 but it is not installable
```

**Comment by TanakritBenz** [comment]
@Alkorin Check out #6375. You should be able to install RethinkDB on stretch using the jessie build. Not an ideal solution but it works.

**Comment by Alkorin** [comment]
And what about security updates? Installing packages by hand is not production proof ... :/

**Comment by ceriath** [comment]
a fix for this would be great, indeed

**Comment by Extarys** [comment]
Temp fix

```
wget http://mirrors.kernel.org/ubuntu/pool/main/p/protobuf/libprotobuf9v5_2.6.1-1.3_amd64.deb
sudo dpkg -i libprotobuf9v5_2.6.1-1.3_amd64.deb
```

**Comment by srh** [comment]
See https://github.com/rethinkdb/rethinkdb/issues/6375#issuecomment-332742675 for Stretch news.  Short version is: use CXX=clang++ on the configure line and install libssl1.0-dev.

**Comment by srh** [comment]
Closing this in favor of #6375.  Short version is: I'm in the midst of getting package-building working out of the box on stretch with `make build-deb DEB_RELEASE=stretch`.  The fix is already pushed in v2.3.x.

**Comment by B1gG** [comment]
Hi, this still unsolved right?
I am new with rethinkdb but I can't install it in debian,

**Comment by srh** [comment]
You can get a stretch package here: https://github.com/srh/rethinkdb/releases/tag/v2.3.6.srh.1

**Comment by graycatfromspace** [comment]
thanks alot @srh

**Comment by TheEquity** [comment]
Thanks a bunch @srh i didnt feel like switching to Ubuntu or anything 🤣

**Comment by officialpiyush** [comment]
Can't install this on debain :sweat:

**Comment by srh** [comment]
@officialpiyush You mean on Buster?

**Comment by srh** [comment]
I have uploaded Buster packages (for amd64) here: https://github.com/srh/rethinkdb/releases/tag/v2.3.6.srh.2

**Comment by srh** [comment]
Buster packages are on the official download server.
