### ISSUE TITLE
Section for External Resources

### ISSUE THREAD

**Issue by packtpartner** [rethinkdb/rethinkdb#6232]
Would it be possible to list external resources like books or videos in the Tutorial tab under "Learn more"?
For example, [Getting Started with RethinkDB](https://www.packtpub.com/big-data-and-business-intelligence/getting-started-rethinkdb) by Gianluca Tiepolo
[Mastering RethinkDB](https://www.packtpub.com/big-data-and-business-intelligence/mastering-rethinkdb) by Shahid Shaikh

**Comment by AtnNn** [comment]
The proper place for this request is the docs repo: https://github.com/rethinkdb/docs

I would love to see an independent review of the book before adding it to our list of resources.

**Comment by packtpartner** [comment]
@AtnNn I totally agree that you will need to review it before adding it to our resources. Can I send you a review copy?

**Comment by AtnNn** [comment]
Thanks, but I am not interested in reviewing those books myself.
