### ISSUE TITLE
fetching re2 fails in v2.3.x

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#6243]
It tries to fetch https://re2.googlecode.com/files/re2-20140111.tgz which doesn't exist anymore.

**Comment by v3ss0n** [comment]
it is fine at next branch , while building i got stuck at building rethinkdb admin. 
Not sure if its because of my config. Should i open a bug report?

**Comment by AtnNn** [comment]
@v3ss0n yes, please open an issue or ask on slack #hlep

This is normal. The re2 sources have already been added to the repo, there is no need to fetch them.
