### ISSUE TITLE
fetching zlib fails in 2.3.6 and next

### ISSUE THREAD

**Issue by mbroadst** [rethinkdb/rethinkdb#6244]
From the zlib website: "Due to the bug fixes, any installations of 1.2.9 or 1.2.10 should be immediately replaced with 1.2.11."

updated link: http://zlib.net/zlib-1.2.11.tar.gz

**Comment by AtnNn** [comment]
Fetching zlib works for me in the v2.3.x branch

**Comment by mbroadst** [comment]
@AtnNn yup, works for me as well. Must have been an isolated incident the other day :/

**Comment by AtnNn** [comment]
Note that it is still broken in next. See #6246

**Comment by mbroadst** [comment]
well that's _very_ strange, because I tested links for both what's in `next` as well as `atnnn/v2.3.6` today and they worked just fine
