### ISSUE TITLE
[Ruby] Can only iterate over a cursor once

### ISSUE THREAD

**Issue by Punknoodles** [rethinkdb/rethinkdb#6253]
Was messing with RethinkDB in irb, got this:
```
RethinkDB::ReqlRuntimeError: Can only iterate over a cursor once.
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rethinkdb-2.3.0.2/lib/net.rb:399:in `each'
        from (irb):20
        from C:/Ruby23/bin/irb.cmd:19:in `<main>'
```
The query I was trying was:
```
items = []
cursor = r.db('test').table('test').run
cursor.each{|doc| items.push(doc)}
```
I was trying to display all the items in the table. If anyone knows another way (with Ruby) to do this, please tell me.

**Comment by AtnNn** [comment]
I don't see anything wrong with your code. Are you still running into that error?

Another way to iterate over a cursor is `to_a`: https://www.rethinkdb.com/api/ruby/to_array/

**Comment by Punknoodles** [comment]
Yeah, I just started using to_a instead. Closing this.
