### ISSUE TITLE
Data got deleted.

### ISSUE THREAD

**Issue by phoenixvk** [rethinkdb/rethinkdb#6254]
Hi, I'm using rethinkdb in nodejs app. Data got deleted over night. Any one can guess the reason? I've just restart the server.

**Comment by srh** [comment]
All the data?  Just some of it?  Did the tables get deleted too?

**Comment by chrisvariety** [comment]
I think pasting the rethinkdb log would be good here. It's possible you restarted rethinkdb in a different directory, which by default will set up a new empty `rethinkdb_data` directory. But the log would help confirm that.

**Comment by AtnNn** [comment]
@phoenixvk Were you able to figure out where your data went or how it was deleted?

**Comment by phoenixvk** [comment]
My bad,I should have started the server from same directory where
rethink_data exists. That's all. Thank you.

**Comment by kvnvelasco** [comment]
If I were you i'd start it as a service to prevent this problem from occurring.

**Comment by phoenixvk** [comment]
How to start it as service? Is it same as using virtual environment?

*Vaibhav Kadam*
B.Tech.(Information Technology)
+91 9404241842
Optional Email - vaibhav.kadam45@live.com,
Vita, District- Sangli, State- Maharashtra,India.
