### ISSUE TITLE
Fail to download zlib-1.2.8 . (Attempt to compile on Raspberry Pi 3)

### ISSUE THREAD

**Issue by Sunnybayby** [rethinkdb/rethinkdb#6255]
```bash
mk/support/build.mk:51: recipe for target 'external/zlib_1.2.8' failed
```

In rethinkdb-2.3.5/mk/support/pkg/zlib.sh, you should replace 

```bash
src_url=http://zlib.net/zlib-$version.tar.gz
```

by

```bash
src_url=http://zlib.net/fossils/zlib-$version.tar.gz
```

Or update the link https://download.rethinkdb.com/dist/rethinkdb-2.3.5.tgz on website.

**Comment by bchavez** [comment]
related/duplicate: #6244 #6246

:busstop: :bus: ***["Fe, Fi, Fo, Fum... Well, I'll be darn here it comes... The Double Dutch Bus is on the street"](https://www.youtube.com/watch?v=fK9hK82r-AM)***

**Comment by Sunnybayby** [comment]
Thanks, not use to rely on github issues reports to look for answers (my bad). I spent 30min to correct it on my own... Stressful experience.
