### ISSUE TITLE
2.3.6 Release Candidate

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#6258]
# Checklist

- [x] All other issues in the milestone are closed (https://github.com/rethinkdb/rethinkdb/issues?utf8=✓&q=milestone:2.3.6%20)
- [x] Write release notes (https://github.com/rethinkdb/rethinkdb/blob/v2.3.x/NOTES.md)
- [x] Tag and push v2.3.6-0RC1
- [ ] Pass all tests (https://thanos.atnnn.com/jobset/rethinkdb/release-v2.3.6#tabs-jobs)
- Build packages
  - [x] Source (http://thanos.atnnn.com/build/4517/download/1/rethinkdb-2.3.6-0RC1-5-g4f0bd9.tgz)
  - Debian
    - [x] Jessie
    - [ ] Stretch
  - Ubuntu
    - [ ] Lucid
    - [ ] Precise
    - [x] Saucy
    - [x] Trusty
    - [x] Utopic
    - [x] Vivid
    - [x] Wily
    - [x] Xenial
    - [x] Yakkety
  - Centos
    - [ ] 6
    - [x] 7
  - [x] macOS dmg
  - [x] Windows
- [x] Make packages available for download and testing

My first impression is that the failing tests are either flaky or broken. I'll try to disable or fix them before the final release.

Although we have access to the old packaging scripts, we are missing information such as signing keys and build environments. I have slowly been reconstructing these.

**Comment by v3ss0n** [comment]
I will be testing tonight.

**Comment by AtnNn** [comment]
Debian and Ubuntu packages for the RC are available here https://thanos.atnnn.com/jobset/rethinkdb/release-v2.3.6#tabs-jobs

**Comment by v3ss0n** [comment]
http://thanos.atnnn.com/build/3762/download/1/rethinkdb-2.3.5-24-g80e5fa-dirty.tgz 
is not setting write permissions , just to keep track.

**Comment by AtnNn** [comment]
Thanks @v3ss0n, I'm testing fixes for both those issues right now.

**Comment by AtnNn** [comment]
New tarball with proper permissions: http://thanos.atnnn.com/build/4517/download/1/rethinkdb-2.3.6-0RC1-5-g4f0bd9.tgz

I haven't been able to reproduce the curl build issue. We might need to build it `--without-nghttp2`. Please open a separate issue if you run into that error again.

**Comment by AtnNn** [comment]
Packages are now available for download and testing: http://thanos.atnnn.com/downloads/rc/2.3.6/1/
