### ISSUE TITLE
Global optargs leak into write hook evaluation context

### ISSUE THREAD

**Issue by srh** [rethinkdb/rethinkdb#6261]
For example (in Python):

```
r.table('foo').set_write_hook(lambda id, x, y: y.merge({'z': y['a'].slice(0,1)})).run()
r.table('foo').insert({'name': 'Doc1', 'a': [0,1,2,3,4]}).run()
r.table('foo').insert({'name': 'Doc2', 'a': [0,1,2,3,4]}).run(left_bound='open')
list(r.table('foo').run())
```

And the output is as follows, note the 'z' field:
`{u'a': [0, 1, 2, 3, 4], u'z': [], u'id': u'8aa02a21-8cb8-46df-9ed2-96c32261e17e', u'name': u'Doc2'}, {u'a': [0, 1, 2, 3, 4], u'z': [0], u'id': u'7fb38212-399d-4843-83cf-9502f6c243eb', u'name': u'Doc1'}]`

Note that you need "config" permission to change a write hook on a table, and this behavior undermines that security permission.

Write hooks should either
(1) Run in an env_t under the global optargs environment that they were defined in, or
(2) Run in an env_t with no global optargs.  This is what secondary index functions do.

**Comment by AtnNn** [comment]
I think using the optargs they were defined in is best because RethinkDB has no restrictions on global optargs. We can do things like `r.circle([0,0],1).run(num_vertices=3)`.

**Comment by srh** [comment]
That's different than how secondary indexes work.

What I'd expect to be installed as a write hook is whatever you see inside of `setWriteHook(...)`.  Not that plus some invisible stuff somebody passed to `run`.  Imagine displaying the definition of an existing write hook to the user.  You have to show users the function itself, and then alongside it, the global optargs it runs under.

I would rather traverse the write hook function and mandate that global optargs do not affect the behavior of any of the commands it runs.

**Comment by marshall007** [comment]
I feel pretty strongly that we should go with (2), i.e. matching the behavior of secondary index functions.

**Comment by srh** [comment]
The implementation in #6396 does just that.

**Comment by srh** [comment]
Thus we can close this.
