### ISSUE TITLE
rethinkdb proxy in Ubuntu 16.04 (xenial) package is not listening for driver connections

### ISSUE THREAD

**Issue by atis--** [rethinkdb/rethinkdb#6265]
Created a Digital Ocean VM with Ubuntu 16.04.1 (xenial), install and run RethinkDB proxy as usual. The proxy runs, connects to the cluster, but it is not listening on driver port 28015!

Doing the same thing with Ubuntu 14.04.5 (trusty) works OK as expected, therefore the conclusion would be that there's something broken in the xenial RethinkDB package. Can someone confirm this? Seems like a serious issue...

**Comment by AtnNn** [comment]
What does `rethinkdb proxy` print out on stdout and stderr?

How are you testing that it is not listening on port 28025? What does `netstat -an | grep 28015` report?

**Comment by atis--** [comment]
Ha, sorry, I didn't realize that if the proxy fails to connect to the cluster (I had put in the wrong cluster port), that it will not listen for driver connections until the cluster connection succeeds. Sorry! (closing this).
