### ISSUE TITLE
rethinkdb:i386 (32-bit) on Linux 64-bit OS fails some YAML tests

### ISSUE THREAD

**Issue by bchavez** [rethinkdb/rethinkdb#6272]
This applies to a bug in RethinkDB 2.3.5 and 2.3.6 RC. Somewhat a low-priority issue since it's non-standard to run RethinkDB 32-bit binary on a Linux 64-bit OS.

I tested `rethinkdb` 32-bit binary on:
* rethinkdb:i386@2.3.5 & 2.3.6 RC on Ubuntu 14.04 64-bit OS.
* rethinkdb:i386@2.3.5 & 2.3.6 RC on Ubuntu 16.04 64-bit OS.

Note: Running RethinkDB 64-bit on a Ubuntu 64-bit OS, there are no failing tests and all YAML tests succeed.
Note: To install 32-bit RethinkDB binary on Ubuntu 64-bit OS I ran: `apt-get install rethinkdb:i386`.

# Failing Tests
I pointed the C# driver test suite to a 32-bit `rethinkdb` binary running on Ubuntu 14.04-64bit and 16.04-64bit and I have the same unit tests that fail the same way on 14.04-64bit and 16.04-64bit:

```
Test:
	geo/intersection_inclusion.yaml, LineNum: 50
Expected ReQL:
	true
Expected C#/Java:
	true
Run ReQL:
	r.line([1,1], [2,1]).intersects(r.point(1,1))
Run C#/Java:
	r.line(r.array(1L, 1L), r.array(2L, 1L)).intersects(r.point(1L, 1L))
RunOpts: []

Protocol In Context:
	TRACE JSON Send: Token: 24, JSON: [1,[163,[[160,[[2,[1,1]],[2,[2,1]]]],[159,[1,1]]]],{}]
	TRACE JSON Recv: Token: 24, JSON: {"t":1,"r":[false]}

PROBLEM:
Expected string to be "true" with a length of 4, but "false" has a length of 5.
```
---
```
Test:
	geo/operations.yaml, LineNum: 5
Expected ReQL:
	("89011.26253835332")
Expected C#/Java:
	"89011.26253835332"
Run ReQL:
	r.distance(r.point(-122, 37), r.point(-123, 37)).coerce_to('STRING')
Run C#/Java:
	r.distance(r.point(-122L, 37L), r.point(-123L, 37L)).coerceTo("STRING")
RunOpts: []

Protocol In Context:
	TRACE JSON Send: Token: 3, JSON: [1,[51,[[162,[[159,[-122,37]],[159,[-123,37]]]],"STRING"]],{}]
	TRACE JSON Recv: Token: 3, JSON: {"t":1,"r":["89011.2625383533"]}

PROBLEM:
Expected string to be 
"\"89011.26253835332\"" with a length of 19, but 
"\"89011.2625383533\"" has a length of 18.
```
---
```
Test:
	times/constructors.yaml, LineNum: 42
Expected ReQL:
	"1970-01-01T00:00:01.444+00:00"
Expected C#/Java:
	"1970-01-01T00:00:01.444+00:00"
Run ReQL:
	r.epoch_time(1.4444445).to_iso8601()
Run C#/Java:
	r.epochTime(1.4444445).toIso8601()
RunOpts: []

Protocol In Context:
	TRACE JSON Send: Token: 11, JSON: [1,[100,[[101,[1.4444445]]]],{}]
	TRACE JSON Recv: Token: 11, JSON: {"t":1,"r":["1970-01-01T00:00:01.443+00:00"]}

PROBLEM:
Expected date and time to be <1970-01-01 00:00:01.444>, but found <1970-01-01 00:00:01.443>.
````

:watch: :city_sunset: ***["I just can't wait... I just can't wait... for saturday night..."](https://www.youtube.com/watch?v=wOjGmpmvGz8#t=2m)***

**Comment by srh** [comment]
When building the i386 binary, do we tell the compiler to use SSE?  It could be that it's using x87 instructions and rounding.

**Comment by srh** [comment]
The time thing is some bug in toISO8601 serialization in the Boost time library.

**Comment by bchavez** [comment]
I don't know if this is related, but we kind-of had similar problem before:
https://github.com/rethinkdb/rethinkdb/issues/5349

Running a few more tests...

**Comment by srh** [comment]
The time thing is that we have `raw_sec` being 1.444 (really 1.4439999999...) coming into

```void add_seconds_to_ptime(ptime_t *t, double raw_sec) {
    int64_t sec = raw_sec;
    int64_t microsec = (raw_sec * 1000000.0) - (sec * 1000000);
```
and then rounding down to 1443999.999... after getting multiplied by a million.  Then we subtract 100000.0 from it, giving 443999.999... which gets truncated to an int64_t, producing 443999.

**Comment by srh** [comment]
(You could also use 1.444 instead of 1.4444445 and get the same result.)

You can exhibit the same behavior, with different numbers, on 64-bit RethinkDb, for example:

`r.epochTime(1.001).toISO8601()` => "1970-01-01T00:00:01.000+00:00"

You can make a list of these with

`r.range(1000000).map(function(x) { return {'a': x, 'b':r.ISO8601(r.epochTime(x.add(0.1).div(1000)).toISO8601()) }; }).filter(function(x) { return x('b').seconds().mul(1000).round().ne(x('a')); })`

**Comment by srh** [comment]
You know, maybe this isn't completely fixed.  We still have `r.expr(r.iso8601('2016-01-01T00:00:00.000999+00'))` truncating down to zero instead of rounding up to 1 millisecond.  A questionable behavior.

**Comment by srh** [comment]
The reason that happens on the server is because in sanitize::iso8601 we specifically just truncate the time.  No attempt at rounding whatsoever.  This seems crazy to me but I'm not going to change it.
