### ISSUE TITLE
What makes `ResourceWarning` happens when using Python `unittest`?

### ISSUE THREAD

**Issue by notalentgeek** [rethinkdb/rethinkdb#6274]
I am currently doing unit testing for my Python app. However, there are a lot `ResourceWarning`s when running the test, although the tests are all pass. The warning mostly comes from a function named `conn()` that does `r.connect()` with adjustable timeout based on internet connection and ping.

The definition I got from https://docs.python.org/3.2/library/warnings.html, does not make me understand on why the warning happens. So, how and why this warning happens?

```markdown
/usr/local/lib/python3.5/dist-packages/rethinkdb/net.py:555: ResourceWarning: unclosed <socket.socket fd=26, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 46410), raddr=('127.0.0.1', 28015)>
  self._json_decoder(), self._json_encoder(), self.host, self.port, user, password)
/usr/local/lib/python3.5/dist-packages/rethinkdb/handshake.py:198: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 46416), raddr=('127.0.0.1', 28015)>
  struct.unpack("32B", client_signature))))
```

**Comment by srh** [comment]
Most likely you aren't calling `.close()` on the connection returned by `r.connect()`.

**Comment by notalentgeek** [comment]
Probably it. I never use `.close()` and I just know it from you. I will fix it when I am back home :). Thanks!

**Comment by notalentgeek** [comment]
@srh , I do not get this.

What is the best practices. Do you...

1. Establish one connection and use it throughout the application run.
2. Establish one connection every time I want to query/update the database.

I tried the first one, but I want my application automatically re - try the connection in case there is no Internet connection. For example, in case there is no Internet connection, my application will loop indefinitely until the connection is back. And I was unable to find out how can I re - try connection with just one connection object.

So, at this point my application establish new connection object everytime I run query to the database. Is this a good practice? I just saw that there are `reconnect()` and `close()` as well, make me feel that I actually only need one connection object for per application run.

**Comment by srh** [comment]
I'm not a user, and I often see a lot of people clamoring for a connection pool.  Opening and closing a connection for every use with the database is fine -- using Python's `with` statement ideally, if you don't run into performance problems.  You should ask somebody else about how they deal with this, maybe on a help channel like RethinkDB's slack channel.

**Comment by notalentgeek** [comment]
Alright thanks!
