### ISSUE TITLE
Could not bind to http port: The address at localhost:8080 is reserved or already in use.

### ISSUE THREAD

**Issue by skumar1122** [rethinkdb/rethinkdb#6277]
Hi ,

I am trying to start rethinkdb and I am getting following error,

> Running rethinkdb 2.3.5 (CLANG 7.3.0 (clang-703.0.31))...
> Running on Darwin 15.6.0 x86_64
> Loading data from directory /Users/international/rethinkdb_data
> Listening for intracluster connections on port 29015
> Listening for client driver connections on port 28015
> error: Could not bind to http port: The address at localhost:8080 is reserved or already in use.
> 

I have checked my localhost:8080 is running Jenkins and i wanted that to be run and I wanted to start rethinkdb on diff port.

do you know is it possible to start rethinkdb on diff port ?

Thanks

**Comment by Hormold** [comment]
Use option http-port.
Example: --http-port 8081

Or in .conf edit variable http-port

http-port=8081

**Comment by skumar1122** [comment]
@Hormold 
Thank you
