### ISSUE TITLE
unwind arrays into individual documents in Aggregation 

### ISSUE THREAD

**Issue by valayDave** [rethinkdb/rethinkdb#6280]
Hey, 

So I currently have a use case where I am using Rethinkdb and its relations, But there is a problem I am facing . In the aggregation I am performing my Model Looks like the following : 

```
var model = {
    prices : [
        {
            name : '',
            amount : '', 
        },
    ]
}
```

The "prices" key is problematic as I am not able to group on the basis of the "name" key within the "prices" array.

Mongodb has a feature named $unwind in its aggregation framework. Does Rethinkdb support something similar? I have thoroughly checked the documentation and I got no help. Can someone Help ?

**Comment by marshall007** [comment]
@valayDave you should be able to create a secondary index on the `name` field and use it like so: 

```js
table.indexCreate('price_name', r.row('prices')('name'), { multi: true })

table.group({ index: 'price_name' })
```

If you don't wish to create an index, `group` also supports the `multi` optarg directly:

```js
table.group(r.row('prices')('name'), { multi: true })
```

I'm gonna close this issue for now, but feel free to continue discussion here if you have any further questions.
