### ISSUE TITLE
rethinkdb dump failing with 'utf8' codec can't decode byte invalid continuation byte

### ISSUE THREAD

**Issue by aaronorosen** [rethinkdb/rethinkdb#6281]
This command just starting failing on our rethinkdb database and I'm unable to export the database.

```
+ /usr/bin/rethinkdb dump -c localhost:28015 -f /home/arosen/backups/rethinkdb-backup-03-02-2017-19-03-13.tar.gz
NOTE: 'rethinkdb-dump' saves data and secondary indexes, but does *not* save
 cluster metadata.  You will need to recreate your cluster setup yourself after 
 you run 'rethinkdb-restore'.
Exporting to directory...
[======================================= ]  99% 
44799 rows exported from 33 tables, with 84 secondary indexes
'utf8' codec can't decode byte 0xf0 in position 7510666: invalid continuation byte
Errors occurred during export
Error: export failed

```

**Comment by AtnNn** [comment]
We talked on slack, it appears that you found a work-around and "deleted some data from [your] db to let [you] be able to back it up again".

If you can identify and share the data or documents that cause this error, I would love to reproduce and fix it.

If you encounter this error again, perhaps you could also try using the latest version of the driver and server. Or using a different version of Python.
