### ISSUE TITLE
GPG signatures for source validation

### ISSUE THREAD

**Issue by NicoHood** [rethinkdb/rethinkdb#6283]
As we all know, today more than ever before, it is crucial to be able to trust
our computing environments. One of the main difficulties that package
maintainers of Linux distributions face, is the difficulty to verify the
authenticity and the integrity of the source code.

The Arch Linux team would appreciate it if you would provide us GPG signatures
in order to verify easily and quickly your source code releases.

**Overview of the required tasks:**
* Create and/or use a 4096-bit RSA keypair for the file signing.
* Keep your key secret, use a strong unique passphrase for the key.
* Upload the public key to a key server and publish the full fingerprint.
* Sign every new git commit and tag.
* Create signed compressed (xz --best) release archives
* Upload a strong message digest (sha512) of the archive
* Configure https for your download server

[GPGit](https://github.com/NicoHood/gpgit) is meant to bring GPG to the masses.
It is not only a shell script that automates the process of creating new signed
git releases with GPG but also comes with this step-by-step readme guide for
learning how to use GPG.

**Additional Information:**
* https://github.com/NicoHood/gpgit
* https://help.github.com/categories/gpg/
* https://wiki.archlinux.org/index.php/GnuPG
* https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
* https://www.qubes-os.org/doc/verifying-signatures/
* https://lkml.org/lkml/2016/8/15/445
* https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https
* https://www.enigmail.net/index.php/en/

Thanks in advance.

**Comment by AtnNn** [comment]
Those are all great suggestions. I'll see what I can do.

Our Debian and macOS packages are already signed, but the signing key was owned by Hexagram 49, and it was lost when the company closed. Setting up a new signing process is one of the remaining tasks for the 2.3.6 release (#6258).

Our download server already supports https, but doesn't redirect to it automatically.

**Comment by NicoHood** [comment]
Hi, I am fetching the sources directly from github. I'd like to update the package and add support for the python driver as well. Would you mind manually signing the release for now? Possibly with gpgit?

I honestly don't want to distribute a package where I am unsure if it wasn't tampered while transmitting. Thanks!

**Comment by AtnNn** [comment]
Here's what I can do for you now. Anything more will have to wait.

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

af22fd40bf (tag: v2.2.6)
a679e9a460 (tag: v2.3.5)
80e5fa8408 (tag: v2.3.6-0RC1)
-----BEGIN PGP SIGNATURE-----

iF4EAREIAAYFAljLNYkACgkQuh9vUZP2LDtEFgD/YWyVywemLhVkcN/M/4XaCSNE
efn/ErR3mrIfZGE/+KkA/1vErRj4Nuc8fs4+Gf734E6Ok5xdTmaOUQacg5nA8lgL
=z8xm
-----END PGP SIGNATURE-----
```

**Comment by NicoHood** [comment]
I dont know how you created the output above, but it does not sign the source tarballs at all. Also the git commit IDs are the very short onces which is also not secure. I am looking forwards for properly signed source tarballs. Thanks for your effort :)

**Comment by NicoHood** [comment]
@AtnNn Any updates? The current rethinkdb python driver update is still awaiting gpg signatures check.

**Comment by AtnNn** [comment]
No progress yet on my part. I'm hoping to get access to our PyPI account soon.

We did discuss this issue [in our meeting yesterday](https://www.youtube.com/watch?v=Y4qvn_mK_kQ).

**Comment by AtnNn** [comment]
I've create a new signing key (CF9BDC6F03D1F02B) and uploaded it.

Here's what I've done for v2.3.6 RC2:

* Signed the git tag (https://github.com/rethinkdb/rethinkdb/releases/tag/v2.3.6-0RC2)
* Signed the list of sha512 hashes of all files part of the RC (https://thanos.atnnn.com/downloads/rc/2.3.6/2/)

If that works out, I'll do it for every future release.

* We're not going to require that every commit is signed.
* If you really want xz files, please create a new issue or send a PR to https://github.com/atnnn/rethinkdb-nix
* Our download server already supports https (but is not https-only)

Thanks @nicohood for pushing for a more secure process

**Comment by NicoHood** [comment]
Thanks for the effort with gpg signatures. The signed hash file is suboptimal, as we need to write additional wrappers to check the signature. It would be better to sign the files directly. However i think it is a good way to produce less files, I think that was your original intention. If not, please create single signatures, its easier to handle.

We still definitely need a source tarball of which we can build rethinkdb from source. If you can create such a tarball and sign it directly, that'd be nice. Building from git tags is not an option (for me), as there are several possible metadata attack on git. [more info](https://www.usenix.org/conference/usenixsecurity16/technical-sessions/presentation/torres-arias)

**Comment by AtnNn** [comment]
The release does include a source tarball.

What would your preferred format be for singing it? A detached signature in a `.sig` file?

**Comment by NicoHood** [comment]
A detached signature .asc or .sig doesnt really matter. Make sure to not sign the github release tarball and rather create your own using `git archive`. This ensures you include all files on your disk and dont trust github for the file creation. Otherwise the signature has no additional benefit.

.tar.xz is preferred (better compression)

Also see:
https://github.com/NicoHood/gpgit#4-create-a-signed-release-archive

**Comment by NicoHood** [comment]
Where can i find the source tarball signatures? I found the .tgz files but no signature for it.

**Comment by AtnNn** [comment]
I just uploaded http://download.rethinkdb.com/dist/rethinkdb-2.3.6.tgz.asc

**Comment by NicoHood** [comment]
@AtnNn Its working fine. Thanks a lot!
