### ISSUE TITLE
Stored Procedure Language

### ISSUE THREAD

**Issue by sirinath** [rethinkdb/rethinkdb#6285]
It is possible to have a stored procedure language which can be very fast. Ideally it should be strongly typed.

**Comment by AtnNn** [comment]
If support for stored procedures was added to RethinkDB, I can't imagine the language used would be anything other than ReQL itself.

Your suggestion is very general. Here are a few of the more specific proposals related to yours:
* For different kinds of stored procedures: #3740 #3636 #3171 #5813 #3963 #1863
* For ways of making ReQL more strict: #5494 #4210 #5879
* For making ReQL faster, most of the issues in the `performance` milestone

**Comment by YunusHaas** [comment]
This feature is useful for setting up advanced triggers.  Stored-ReQL could be used to create a very powerful event driven data system.  If Stored-ReQL worked then we could remove our cron jobs, and the data would decide when its ready.
