### ISSUE TITLE
RethinkDB returns incorrent results in Data Explorer with r.row

### ISSUE THREAD

**Issue by UzLA** [rethinkdb/rethinkdb#6289]
Environments tested in: RethinkDB 2.3.5 installed on Ubuntu Xenial, same tested on MacOS Sierra.

The below done on clean install with one record added to test database:
![rethinkdb_data](https://cloud.githubusercontent.com/assets/11695228/23693427/87f32894-03e5-11e7-9b21-a5da55bf1965.png)

Dashboard Data Explorer exact match query without r.row does find the record.

![rethinkdb_result_correct](https://cloud.githubusercontent.com/assets/11695228/23693503/cbafdb5e-03e5-11e7-9a5b-54b824d54318.png)

With Python3 it works with r.row:
```

>>> import rethinkdb
>>> conn = r.connect()
>>> r.db('test').table('test').filter(r.row['myfield1'] == 1).run(conn)
<rethinkdb.net.DefaultCursor object at 0x7f8a95839438 (done streaming):
 [{'myfield1': 1, 'myfield2': 'content', 'id': 'f26a33f4-5add-442e-93b6-5fb93e817fb8'}]>
>>> 
```

This means that data is set correctly.

However, Dashboard Data Explorer FAILS on filterScreenshot with r.row: That's the result with "No records found" rather then expected "1 row returned. Displaying rows 1-1":

Failure Screenshot]
![rethinkdb_result](https://cloud.githubusercontent.com/assets/11695228/23693412/72b3f2ec-03e5-11e7-860e-64c7f8772692.png)

**Comment by chrisvariety** [comment]
Hi @UzLA, this is because the web UI uses the Javascript style ReQL syntax, not the Python style.

This would be the same query in the Javascript style:

```
r.db('test').table('test').filter(r.row('myfield1').eq(1))
```

**Comment by UzLA** [comment]
Indeed! It works! Using Javascript style ReQL syntax solves the issue. Moreover, it is logical to use it in javascript driven environment (browser). Thanks a lot!
