### ISSUE TITLE
Failure in make ALLOW_WARNINGS=1 Raspberry Pi Install

### ISSUE THREAD

**Issue by buytore** [rethinkdb/rethinkdb#6292]
I'm receiving the following error when attempting to install rethinkdb on Raspberry Pi Model 3 B - Raspbian when following: "Install RethinkDB on Raspbian" 

Following install steps work great:
apt-get upgrade
apt-get update
apt-get dist-upgrade
apt-get autoremove
sudo apt-get install g++ protobuf-compiler libprotobuf-dev libboost-dev curl m4 wget libssl-dev
wget https://download.rethinkdb.com/dist/rethinkdb-2.3.5.tgz
tar xf rethinkdb-2.3.5.tgz
cd rethinkdb-2.3.5
./configure --with-system-malloc --allow-fetch
**make ALLOW_WARNINGS=1**

Goes through 399 of the 410 object loads and then on 400 I receive this:

   [399/410] CC build/release_system/obj/buffer_cache/eviction_bag.o
    [400/410] FETCH zlib_1.2.8
+ pkg_make_tmp_fetch_dir
++ mktemp -d /home/mpiuser/rethinkdb-2.3.5/external/zlib_1.2.8.fetch-XXXXXXXX
+ tmp_dir=/home/mpiuser/rethinkdb-2.3.5/external/zlib_1.2.8.fetch-IXIR12Sv
+ local archive=zlib-1.2.8.tar.gz
+ set +e
++ geturl http://zlib.net/zlib-1.2.8.tar.gz /home/mpiuser/rethinkdb-2.3.5/external/zlib_1.2.8.fetch-IXIR12Sv/zlib-1.2.8.tar.gz
++ [[ -n /usr/bin/curl ]]
++ /usr/bin/curl --silent -S --fail --location http://zlib.net/zlib-1.2.8.tar.gz -o /home/mpiuser/rethinkdb-2.3.5/external/zlib_1.2.8.fetch-IXIR12Sv/zlib-1.2.8.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
+ error_text=
+ local download_failed=22
+ [[ 22 -ne 0 ]]
+ [[ -n '' ]]
+ set -e
+ [[ 22 -ne 0 ]]
+ [[ ! -z '' ]]
+ error 'failed to download zlib from http://zlib.net/zlib-1.2.8.tar.gz'
+ echo 'mk/support/pkg/pkg.sh: zlib: failed to download zlib from http://zlib.net/zlib-1.2.8.tar.gz'
mk/support/pkg/pkg.sh: zlib: failed to download zlib from http://zlib.net/zlib-1.2.8.tar.gz
+ exit 1

Full error log: ./build/external/zlib_1.2.8_fetch.log
mk/support/build.mk:51: recipe for target 'external/zlib_1.2.8' failed
make[1]: *** [external/zlib_1.2.8] Error 1
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2

I've tried to go directly to the http://zlib.net/zlib-1.2.8.tar.gz n the browser and get 404. Then I removed the zlib-1.2.8.tar.gz in the browser and get to the site, which seems to be at version zlib-1.2.11.tar.gz and I'm gathering the older version is no longer available. Not a C guy so not sure how to change the script to load http://zlib.net/zlib-1.2.11.tar.gz but hopefully this helps a bit.

Thx,

Buytore

**Comment by cthayer** [comment]
I got this error building for edison.

Version 1.2.8 of zlib is actually at http://zlib.net/fossils/zlib-1.2.8.tar.gz

As a work around, you can edit `mk/support/pkg/zlib.sh` to change the url used during the build.

(this appears to be addressed in the latest rethinkdb source, but not in version 2.3.5)

**Comment by buytore** [comment]
Hey Craig,

Thx a ton for the info - that did the trick.

Mark
