### ISSUE TITLE
Laziness | Conditional or Depedent Triggers | Pull based queries

### ISSUE THREAD

**Issue by sirinath** [rethinkdb/rethinkdb#6297]
Having to handle each update may not be very optimal also. So it is possible to introduce laziness and conditional processing.

 - Get updated only when a more eager table is updated
 - More traditionally request the update
 - More fine grain ways to specify when to push the results
 - etc.

The problems to solve is:

 - do not consume cycles or bandwidth in sending data that will just be discarded
 - do not send data when the consumer cannot not or does not want to or need not process the data

**Comment by marshall007** [comment]
@sirinath I'm not quite clear on what you're looking for here, but changefeeds can already be initialized on a variety of sub-queries. Some examples:

```js
table.getAll(...).changes()
table.get(...).changes()
table.filter(...).changes()
```

You can even filter items from the changefeed itself. For example, a changefeed that only emits values with a players `score` increases might look like:

```js
r.table('players').changes().filter(
  r.row('new_val')('score').gt(r.row('old_val')('score'))
)
```

**Comment by AtnNn** [comment]
> * Get updated only when a more eager table is updated

You can for example `union` multiple change feeds and process them using `fold`

> * request the update

You can request updates over a cursor at will

> * More fine grain ways to specify when to push the results
> * do not consume cycles or bandwidth in sending data that will just be discarded
> * do not send data when the consumer cannot not or does not want to or need not process the data

What are you looking for that RethinkDB doesn't already have? You can use `filter` and all sorts of other operations both before and after a changefeed to specify when you want to be notified of a change.

RethinkDB can also squash changes for you if you aren't reading them fast enough.
