### ISSUE TITLE
Compliments to ReQL | Or extending ReQL to support SQL, GraphQL

### ISSUE THREAD

**Issue by sirinath** [rethinkdb/rethinkdb#6298]
Is it possible to extend ReQL or have SQL, GraphQL like support which can be translated to a form of extended ReQL. 

Sometimes you just need to mix paradigms. Having multiple DBs, and a technology zoo may not be the answer. RTDB has a very good paradigm and solution but when you require some plain old SQL like querying there should be some form of support.

**Comment by AtnNn** [comment]
There is already a discussion about GraphQL in #3711 and about plugins in #4785.
