### ISSUE TITLE
Build fails for rethinkdb 2.3.5 with 404 while attempting to download zlib

### ISSUE THREAD

**Issue by phonikg** [rethinkdb/rethinkdb#6312]
`make` fails when it receives a 404 while attempting to download: http://zlib.net/zlib-1.2.8.tar.gz

It seems as though only the most recent version of zlib is avail: from http://zlib.net/zlib-1.2.11.tar.gz

**Comment by simonbrowning** [comment]
+1

**Comment by srh** [comment]
This is fixed in v2.3.x.  But it's a problem that you can't just go back and build old releases like this.
