### ISSUE TITLE
Can we use V8 v4.7 on Linux.

### ISSUE THREAD

**Issue by asowani** [rethinkdb/rethinkdb#6315]
Hi,

File mk/support/pkg/v8.sh, lines 6-7 say that "4.7 has no source distribution, making it harder to build on Linux". I tried building RethinkDB with V8 v4,7 on Ubuntu 16.04/ppc64le and it seems to be working fine - all unit tests passed so far. Further testing is in progress - haven't hit any serious issue yet. I have introduced appropriate conditions in source code to pick V8 v4.7 if building on ppc64le.

So, I am wondering if it is okay to use V8 v4.7 on Linux if it works, or still there is a hard requirement to use 3.30 only? Any comments/advise about it?

Thanks,
Atul.

**Comment by srh** [comment]
That's nice to hear, but how did you do it?  Is it done in a way that can be conveniently integrated with RethinkDB's build system?

**Comment by asowani** [comment]
@srh Thanks! I have created PR for this today (https://github.com/rethinkdb/rethinkdb/pull/6317).

**Comment by gabor-boros** [comment]
@srh v8 is dropped in favor of quickjs, should we close this?
