### ISSUE TITLE
Table scanning when there is no query on the table

### ISSUE THREAD

**Issue by weilunzhong** [rethinkdb/rethinkdb#6323]
I have a table of around 4 million documents and it seems to have scheduled a scan from time to time thwn there no query running. The reading speed is around 1.5k/sec on the table dashboard and the secondary index is not available.
If i do this: 
`r.db("rethinkdb").table("jobs").filter({type: 'query'})`  
This is no query running on that table.

**Comment by srh** [comment]
If read queries are quick and you query the jobs table in between read queries, you'll get that result.  You would expect this if you're only reading 1500 documents a second -- that's a low number, so most of the time there is no query.  Let me know if you have more info that shows this explanation to be wrong.
