### ISSUE TITLE
Can't run cluster with tls

### ISSUE THREAD

**Issue by minaevmike** [rethinkdb/rethinkdb#6325]
Hi.
I am trying to run rethink cluster in tls mode and at connection i have such error
```
error: Cluster server connection TLS handshake failed: no certificate returned (OpenSSL error 336105650)
```
i am running rethink as docker container with such arguments
```
      --canonical-address <server_name>:<server_driver_port>
      --http-port <server_web_port>
      --http-tls-key /keys/server_name.pem
      --http-tls-cert /cert/server_name.pem
      --driver-tls-key /keys/server_name.pem
      --driver-tls-cert /cert/server_name.pem
      --cluster-tls-key /keys/server_name.pem
      --cluster-tls-cert /cert/server_name.pem
      --cluster-tls-ca /cert/ca_bundle.pem
      --tls-ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:AES256-SHA

```
What i am doing wrong?
Thank you for your help.

**UPDATE** I have untrasted intermediate certificate so for verifying it via openssl depth must be 1.

**Comment by srh** [comment]
It's a bit late, but this is not a help channel -- I recommend asking in the Slack #general or #help channels -- Go to http://slack.rethinkdb.com/ .  Also, I don't know how to help you, and there people might.

**Comment by alexxkn** [comment]
I tried 3 cases:
1. Run both nodes with selfsigned cert - it works
2. I made selfsigned CA, sign with it 2 certs - it works
3. I made selfsigned CA, sign with it intermediate CA, sign with this chain 2 certs - it doesn't

Opensll certificate checking passes correctly.
`$ openssl verify -CAfile ca-chain.cert.pem cert1.pem 
cert1.pem: OK
$ openssl verify -CAfile ca-chain.cert.pem cert2.pem 
cert2.pem: OK
`
As soon as more than one certificate appears in the file, the rethinkdb writes an error:
`error: Cluster server connection TLS handshake failed: no certificate returned (OpenSSL error 336105650)`
Without chain I of course get error `unknown ca`.

Please, reopen issue.
