### ISSUE TITLE
Is't live this project?

### ISSUE THREAD

**Issue by biapar** [rethinkdb/rethinkdb#6332]
Is't live this project?

**Comment by chrisvariety** [comment]
yes

**Comment by thinklinux** [comment]
Join on slack... follow things there ;)

**Comment by biapar** [comment]
Good...because I don't see any release from last year.

**Comment by v3ss0n** [comment]
it is still alive , but we need a lot of testers , contributors and companies who willing to support RethinkDB.
Please join us on : https://rethinkdb.slack.com/messages/C2KSYLS1Z/convo/C0CHR7KE0-1491662200.119742/

Please test rethinkdb RC1 for 2.3.6 : https://github.com/rethinkdb/rethinkdb/issues/6258

**Comment by AtnNn** [comment]
Watch our last meeting here: https://www.youtube.com/watch?v=Y4qvn_mK_kQ
