### ISSUE TITLE
Have you tried if RethinkDB is usable with Xamarin or Nativescript?

### ISSUE THREAD

**Issue by biapar** [rethinkdb/rethinkdb#6334]
I've to build a mobile app with Xamarin or Nativescript. Then, is RethinkDB is usable with Xamarin or Nativescript?

**Comment by v3ss0n** [comment]
RethinkDB is not designed for use as embedded database.
But it will be very interesting if you want to dive into source code , strip it down , and make a "light weight" version of it , that can be embedded into mobile applications.

If you mean as online application , yes , you can use rethinkdb/horizon to build a backend service so you can connect with your  NativeScript / Corodva / Any client side tech that supports JSON + HTTP .

**Comment by biapar** [comment]
Thank you for your reply. Sorry ( I know that Rethinkdb is not possible to use on mobile platform ), but I mean if it's possible to use RethinkRB as server side with Xamarin/Nativescript as client side.

**Comment by minaevmike** [comment]
as i see nativescript run js code. Rethink has very good js api. https://rethinkdb.com/api/javascript/

**Comment by v3ss0n** [comment]
@minaevmike  that still need to connect nativescript to connect to a remote server , even if rethinkdb allows it , it is very bad idea for client side to connect directly with Any Remote database .

**Comment by AtnNn** [comment]
The RethinkDB JavaScript driver requires Node.js so it would not work with Nativescript.

The .NET driver may work on Xamarin: https://github.com/bchavez/RethinkDb.Driver/issues/40

**Comment by biapar** [comment]
Good. I'll give a try .NET driver because I'm working on Xamarin.

**Comment by srh** [comment]
Closing this, because it's been 18 days without a response to the question.  If you need help I recommend asking on the slack channel -- go to http://slack.rethinkdb.com/
