### ISSUE TITLE
Memory leak, cursor.each() doesn't take callback, no back-pressure

### ISSUE THREAD

**Issue by GeoffreyPlitt** [rethinkdb/rethinkdb#6335]
For each of 500k records from a table, via a cursor, I need to call a Promise.

Each is documented to take a per-row callback like ```(err, row) => {}``` and a finally-done callback like ```() =>```. But this seems wrong, the per-row callback should have a ```done()``` callback itself, right?

I'm launching 500k Promises, but if they finish slower than the cursor is pumping records, the stack grows and grows and I get an out-of-memory exception.

I figured the cursor would allow back-pressure by only continuing to get new rows if the per-row callback finishes, but there is no signalling (back-pressure) from the per-row callback back to the cursor.

Am I missing something?

**Comment by GeoffreyPlitt** [comment]
I finally found this, which answers my question-- sorry, it was hard to find. https://rethinkdb.com/api/javascript/each_async/

**Comment by chrisvariety** [comment]
Good find! I didn't know about this myself and I've been at this for years now. Seems very useful

**Comment by marshall007** [comment]
@GeoffreyPlitt yep, I was running into the same problem which is why I implemented `.eachAsync()`. You may also want to consider using using [streams in rethinkdbdash](https://github.com/neumino/rethinkdbdash#readable-streams). Streams give you even more control over back-pressure.
