### ISSUE TITLE
undefined values are not handled correctly for filter operation

### ISSUE THREAD

**Issue by riteshsangwan** [rethinkdb/rethinkdb#6338]
This issue is related to #663.

The above issue is marked as closed and from the discussion there is no clear conclusion as to how `undefined` values will be handled not just in `insert` operation but also for `filter` operation hence I am opening a new issue.

- I have below code that fails when either `username` or `email` is `undefined`.

```
const users = yield User.filter(r.row('username').eq(username).or(r.row('email').eq(email)));
```

This will throw error

```
Cannot convert `undefined` with r.expr() in:\nr.table("users").filter(r.row("username").eq(undefined).or(r.row("email").eq(undefined)))
```

Logically since I have a users table where `email` or `username` cannot be `null/undefined` I would expect this query to return `0` results. This is what mongo returns since many of the developers actively work on mongo we would expect this to work the same way.

**What I would like is for this query to not throw error and return 0 results.**

I have been reading the docs and is not able to find the solution. How to get this done in rethink world.

- Consider below code

```
const users = yield User.filter({ username: undefined });
```

This will return all the users and completely ignore `undefined` value for username. This is logically not correct since ideally this should not return any results because there are no records where `username` is undefined.

**Additional Info**

`User` is a `thinky` model

```
const User = thinky.createModel('users', {
    id: type.string().uuid(4),
    fullName: type.string().required(),
    username: type.string().required(),
    email: type.string().email().required(),
    password: type.string().required(),
    firstName: type.string().alphanum().allowNull(true),
    lastName: type.string().alphanum().allowNull(true),
    bio: type.string().allowNull(true),
    // the timestamp this resource is created
    createdAt: type.number().integer().required(),
    // the timestamp this resource was last updated
    updatedAt: type.number().integer().required(),
  }, {
    enforce_extra: 'remove',
    enforce_type: 'strict',
  });
```

**Comment by srh** [comment]
ReQL doesn't have an undefined datatype, so this is something that would have to be handled by the driver.  The best solution here would be a driver that converts `undefined` to the null ReQL value.

In JavaScript it's easy enough to get the value `undefined` from a simple typo, so I doubt the official driver would silently accept the value and operate.  It would be bad for most users to overwrite data as a result of uninitialized variables or missing object properties.  Especially if they like to avoid using `undefined` as a value.

If you want to treat the undefined value as `null` you can pass it through a function you define such as `function atLeastNull(x) { return x === undefined ? null : x; }`.  Maybe a shorter name would be appropriate.

That might be annoying to use.  If so, a flag could be added to the driver, which, when enabled, tolerates `undefined` in ReQL queries (passing null to the server).

**Comment by AtnNn** [comment]
The issues you are having seem to be related to your use of [thinky](https://github.com/neumino/thinky) and [rethinkdbdash](https://github.com/neumino/rethinkdbdash), not RethinkDB itself.

The Javascript driver in this repo will always fail when given `undefined` values, with errors such as "Object field 'username' may not be undefined" and "Argument 1 to eq may not be `undefined`".

Thinky's behaviour of ignoring `undefined` fields is very common in JavaScript. Many built-in JavaScript operations do not distinguish between an undefined and a missing field, for example:

```
> empty = {}
> empty.user
undefined
```

**Comment by riteshsangwan** [comment]
@srh and @AtnNn Thanks for the info. Closing this in favour of https://github.com/neumino/thinky/issues/616.
