### ISSUE TITLE
com.rethinkdb.gen.exc.ReqlServerCompileError: Unrecognized optional argument `index`.

### ISSUE THREAD

**Issue by Kodehawa** [rethinkdb/rethinkdb#6339]
Am I doing something wrong? I get this by uhh... following [this](https://www.rethinkdb.com/docs/secondary-indexes/java/) manual aka [this](http://i.imgur.com/xcom0C5.png)

Why is it saying index is not a optarg?

**Comment by AtnNn** [comment]
I don't see any error in the documentation. What is the full query?

**Comment by Kodehawa** [comment]
http://i.imgur.com/4V2qj17.png This doesn't work at all, for example. If I remove the optArgs "index" declaration it works, but it doesn't *actually* query the index (aka it gives me "array size over 100000")

Am I doing something extremely wrong?

**Comment by Kodehawa** [comment]
Ok so, after tinkering around a little I discovered that `	.orderBy("index", r.desc("money"))` takes 2.1s to complete by itself, while getting the database itself takes only around 40ms.

**Comment by Kodehawa** [comment]
Final discovery, removing "index" completely made the query actually be *faster* (273ms) using the following query: http://i.imgur.com/UUt0Zez.png

The problem is that I *need* an index, and weren't index made to speed up those kind of things? :/

**Comment by Kodehawa** [comment]
Forget it. I just realized that optArg order matters (after what query you put it lol)

Can I ask you a favor and make a example with that? I had to figure that part by myself. But it's actually nice, after tinkering for around 1 hour I managed a way to make that query take any time from 1 to 8ms 🤔

**Comment by AtnNn** [comment]
The optional arguments should be attached to the command they modify. Not only should the `index` optional argument be attached to `orderBy` and not `table`, the `read_mode` argument should also not be attached to the `table` command, but passed to `run`.

There are already many example in the documentation:

https://www.rethinkdb.com/api/java/run/
https://www.rethinkdb.com/api/java/order_by/

**Comment by Kodehawa** [comment]
Uh, thanks you.
