### ISSUE TITLE
Filter by list of ids in RethinkDB java

### ISSUE THREAD

**Issue by amarjaljolie** [rethinkdb/rethinkdb#6348]
am using RethinkDB with java driver and i want to get rows by list of id's

until now i used :

.filter(row -> row.g("_id").eq("one")
but if i want to search where _id is equal to ["one","two", ...] (list of items)

iv seen an examples on how to do it in javascript and found this :-

    r.db("test2").table("table2").filter(
  function (doc) {
    return r.expr(["two","one"])
            .contains(doc("_id"))
  }
)
is there way to do it with java driver ?

thank you

**Comment by aaronorosen** [comment]
It sounds like what you might want to do is using a multi index instead? https://www.rethinkdb.com/docs/secondary-indexes/python/#multi-indexes

**Comment by amarjaljolie** [comment]
SELECT * FROM users
WHERE name IN ('Peter', 'John') 

this what i want to do as in the example i gave above in java script you dont have t create index for that .
as i dont want to end up having lot of indexes as it will slow down the queries 

as i said in java script i was able to so without the indexing in the above example .. now how to do the same in java ??

**Comment by AtnNn** [comment]
Closing in favour of http://stackoverflow.com/questions/43717320/filter-by-list-of-ids-in-rethinkdb-java
