### ISSUE TITLE
First example doesn't work

### ISSUE THREAD

**Issue by ElkeF** [rethinkdb/rethinkdb#6350]
Hi,

I just tried the very first example on you homepage and from this:
```
r.db('test').tableCreate('tv_shows')

r.table('tv_shows').insert([{ name: 'Star Trek TNG', episodes: 178 },
                            { name: 'Battlestar Galactica', episodes: 75 }])
```
I get:
SyntaxError: missing ; before statement

I guess, it's a really forward fix in either the code or the example.

**Comment by bchavez** [comment]
Hi.

Have you tried evaluating each query individually? Do they work when you execute each one individually? Or, did you evaluate them both at the same time? Are you using the Admin interface to execute these queries?

:watch: :city_sunset: ***["I just can't wait... I just can't wait... for saturday night..."](https://www.youtube.com/watch?v=wOjGmpmvGz8#t=2m)***

**Comment by AtnNn** [comment]
@ElkeF Those are two separate queries. They both work if you run them one after the other. You can try running them together, but you'll need to add a semicolon like the error suggests.
