### ISSUE TITLE
Administration interface not opening server on Windows in Firefox 53.0

### ISSUE THREAD

**Issue by dtaalbers** [rethinkdb/rethinkdb#6351]
When opening the administration UI interface in Firefox it does not show any available servers. 

**Steps to reproduce**
1) Download the `rethinkdb.exe` file (windows) and place it on your HD.
2) Navigate to the folder where you placed the file.
3) Start the server using the command `rethinkdb.exe`
4) Open the UI (http://localhost:8080 as default) in Firefox 53.0

I got the following error in the console preventing the servers to open in the UI

![screen shot 2017-05-05 at 12 11 18](https://cloud.githubusercontent.com/assets/6512556/25742222/c4209852-318e-11e7-955f-d723f4c0e2a4.png)

**Comment by bchavez** [comment]
Duplicate:
https://github.com/rethinkdb/rethinkdb/issues/6342
https://github.com/rethinkdb/rethinkdb/issues/6269

:sunny: :crescent_moon: ***["I've been counting down the days and the nights..."](https://www.youtube.com/watch?v=uMcYRk_o82M)***
