### ISSUE TITLE
batch insert much slower than one insert

### ISSUE THREAD

**Issue by amarjaljolie** [rethinkdb/rethinkdb#6355]
hi,
am using java driver
table has 65 documents and I want to update this documents 
one test I did ran with for loop on my list and added one by one .. this way:
1) db.table("table").insert(document);
and I was reading that if I use batch insert it will will be faster
so I wrapped my document in a list and I did this way
2) db.table("table").insert(documentsList).optArg("conflict", "replace");

documentsList now has 65 documents , but the problem is many times I get timeout for the connection and when it does succeeded it takes twice the time I took in no (1)
while as I understand number (2) it should be much faster 

anyone can help ?? 
thank you

**Comment by marshall007** [comment]
@amarjaljolie `table.update(document)` is not equivalent to `table.insert(documents, conflict: 'replace')`. The former updates every row in the table with the values in `document`, and will throw an error if the ID in `document` differs from that of any row it's trying to update.

**Comment by amarjaljolie** [comment]
i did another test with insert same thing no 1 is faster than adding all at once

**Comment by amarjaljolie** [comment]
and how does that explain why updating one by one is faster than adding all at once ... anyway i did test with insert same as no 2 and as i said i got adding my documents one by one with for loop is faster than adding all with batch insert

**Comment by srh** [comment]
I don't know how the Java driver works but based on the API documentation it seems like it would probably throw an exception the first time through the loop.  That would make it faster.

**Comment by amarjaljolie** [comment]
its not throwing exception as i said i did insert as well

**Comment by adriantodt** [comment]
The Java driver now lives in https://github.com/rethinkdb/rethinkdb-java. Please open a ticket there if it there's some weird behaviour going on.
