### ISSUE TITLE
Installation failure: The repository 'http://download.rethinkdb.com/apt zesty Release' does not have a Release file.

### ISSUE THREAD

**Issue by lukeify** [rethinkdb/rethinkdb#6359]
Attempting to follow the "With Binaries" instructions on the [official installation page for Ubuntu here](https://www.rethinkdb.com/docs/install/ubuntu/), while running x64 17.04 results in a number of warning and error messages. 

> Err:6 http://download.rethinkdb.com/apt zesty/main amd64 Packages                                                                
  404  Not Found
> W: The repository 'http://download.rethinkdb.com/apt zesty Release' does not have a Release file.
> N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: Failed to fetch http://download.rethinkdb.com/apt/dists/zesty/main/binary-amd64/Packages  404  Not Found
> E: Some index files failed to download. They have been ignored, or old ones used instead.

and thus

> sudo apt-get install rethinkdb 

results in:

> E: Unable to locate package rethinkdb

**Comment by AtnNn** [comment]
@lukeify We don't have packages for zesty out yet. I'll update this issue when we do.

**Comment by ijdickinson** [comment]
+1 for Zesty packages please

**Comment by stephen84s** [comment]
:+1:

**Comment by light24bulbs** [comment]
Still no zesty packages?

**Comment by iontom** [comment]
Any word yet?

**Comment by AtnNn** [comment]
The upcoming 2.3.6 release will have packages for zesty. See #6434
