### ISSUE TITLE
2.3.6 RC 2

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#6365]
For RC1 see https://github.com/rethinkdb/rethinkdb/issues/6258#issuecomment-280918135

The final 2.3.6 release should follow soon after RC2

# Checklist

- [x] All other issues in the milestone are closed (https://github.com/rethinkdb/rethinkdb/issues?utf8=✓&q=milestone:2.3.6%20)
- [x] Add missing items to release notes (https://github.com/rethinkdb/rethinkdb/blob/v2.3.x/NOTES.md)
- [x] Tag and push v2.3.6-0RC2
- [x] Pass tests (https://thanos.atnnn.com/jobset/rethinkdb/release-v2.3.6#tabs-jobs)
- [x] Build packages
  - [x] Source
  - Debian
    - [x] Jessie
    - [ ] Stretch
  - Ubuntu
    - [ ] Lucid
    - [ ] Precise
    - [x] Saucy
    - [x] Trusty
    - [x] Utopic
    - [x] Vivid
    - [x] Wily
    - [x] Xenial
    - [x] Yakkety
    - [x] Zesty
  - Centos
    - [x] 6
    - [x] 7
  - [x] macOS dmg
  - [x] Windows
- [x] Make packages available for download and testing

**Comment by v3ss0n** [comment]
Awesome , i will test tomorrow.

**Comment by Extarys** [comment]
I'm so glad some people still working on this. Adopted RethinkDB yesterday for my new project. It's awesome! Thanks for your work!

**Comment by AtnNn** [comment]
Packages are building. Source tarball: https://thanos.atnnn.com/build/7819/download/1/rethinkdb-2.3.6-0RC2.tgz

**Comment by AtnNn** [comment]
Packages for linux and windows are available:

https://thanos.atnnn.com/downloads/rc/2.3.6/2/

**Comment by AtnNn** [comment]
A package for OS X is now available too.

Please download and test this release, and report any bugs you find. We hope to release the final 2.3.6 on Monday.

https://thanos.atnnn.com/downloads/rc/2.3.6/2/
