### ISSUE TITLE
Commits in v2.3.x branch are absent in v2.4.x or next.

### ISSUE THREAD

**Issue by srh** [rethinkdb/rethinkdb#6367]
Commits such as c40d31dd139691632ad9f8ba34a70be31676ab96 or 4f0bd9165ba6139338aae118caf5c94e361c538d are in v2.3.x but there's no corresponding cherry-picked commit in v2.4.x or next.  How are we keeping track of what changes are supposed to go where?

**Comment by AtnNn** [comment]
I should have cherry-picked those two commits into `v2.4.x` and `next`. I've been keeping track of what goes where in the issue comments and in my head.

There are some commits in v2.3.x that shouldn't be cherry-picked, such as 5c97eb5 and 5b833de.

**Comment by AtnNn** [comment]
I looked at all the commits in v2.3.5..v2.3.6. The two commits you mention are the only ones that seemed to be missing. I have cherry-picked them into v2.4.x and next.
