### ISSUE TITLE
Is update.rethinkdb.com dead?

### ISSUE THREAD

**Issue by mikemaccana** [rethinkdb/rethinkdb#6368]
When starting the DB:

> warn: Problem when checking for new versions of RethinkDB: HTTP request to update.rethinkdb.com failed.

Update rethinkdb.com 404s. Is there a new URL now rethinkdb is a community project? Will there be? Thanks!

**Comment by AtnNn** [comment]
Does that warning persist?

The update server is still running and my local rethinkdb had no problem connecting to it just now. The fact that the `update.rethinkdb.com` index returns a 404 is a good sign. A 500 or connection timeout would indicate a failure somewhere.

**Comment by srh** [comment]
Closing for organizational reasons -- let us know if you still have a question!
