### ISSUE TITLE
Primary index, binary vs string performance.

### ISSUE THREAD

**Issue by WilcoBakker** [rethinkdb/rethinkdb#6371]
Hello devs of RethinkDB and fellow contributors,

I had a question regarding the performance of binary versus string.
Suppose I use UUID's in binary form as primary key instead of UUID's in string form.
Would this gain me any performance increasement (or decreasement) doing this?

If it did gain me any performance increasement, would it an idea of adding the option to set the default generated id type to binary instead of string?

Thanks,

Wilco

**Comment by srh** [comment]
The serialization format for the binary key "ABC" is `PBINARY:ABC`.  For the string "ABC" it's `SABC`.

So a binary UUID, which takes 16 bytes, will use 24 bytes of storage, in place of a string UUID which takes 37 bytes of storage.  (32 hexadecimals, 4 hyphens, 1 'S' prefix.)

(Just so you know, as an exception, the bytes 0 and 1 take 2 bytes (`\x01\x01` and `\x01\x02`) to represent in a binary key.)

Having the autogen key be a binary UUID would be an option.  Another option is a custom UUID datatype.  Another option is a special compressed representation when we recognize that a string value is a UUID.

**Comment by WilcoBakker** [comment]
@srh

thank you for you feedback.

I have made a proposal for this in issue #6372.
