### ISSUE TITLE
Debian stretch

### ISSUE THREAD

**Issue by bdschr** [rethinkdb/rethinkdb#6375]
Can you guys please fix the build for Debian to work with stretch.

Thanks.

**Comment by bdschr** [comment]
Nevermind got it working on debian stretch myself!

**Comment by srh** [comment]
Good to know.  Leaving this open because we still need to make this work out of the box.

**Comment by TanakritBenz** [comment]
Thanks @bdschr! I got it to work as well :)

For anyone who are trying to do this, here's how I did it:

- Install libprotobuf9 and libssl

1. `curl -O http://ftp.nl.debian.org/debian/pool/main/p/protobuf/libprotobuf9_2.6.1-1_amd64.deb`
2. `curl -O http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_amd64.deb`
3. `sudo dpkg -i libprotobuf9_2.6.1-1_amd64.deb`
4. `sudo apt-get install -f`
5. `sudo dpkg -i libssl1.0.0_1.0.1t-1+deb8u6_amd64.deb`
6. `sudo apt-get install -f` 

- Install RethinkDB

1. `export DISTRIB_CODENAME="jessie"`
2. `echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list`
3. `wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -`
4. `sudo apt-get update`
5. `sudo apt-get install rethinkdb`

**Comment by lenovouser** [comment]
@TanakritBenz there is a bit easier way. Change:

```diff
-deb http://download.rethinkdb.com/apt jessie main
+deb http://download.rethinkdb.com/apt stretch main
```

Install `libprotobuf9v5`:

```
wget http://archive.ubuntu.com/ubuntu/pool/main/p/protobuf/libprotobuf9v5_2.6.1-1.3_amd64.deb
dpkg -i libprotobuf9v5_2.6.1-1.3_amd64.deb
```

and that's it 😃 

```sh
apt install rethinkdb
```

works without any problems.

**Comment by hanleym** [comment]
@lenovouser your method results in 2.3.5 instead of 2.3.6.

**Comment by TanakritBenz** [comment]
@hanleym Mine is `2.3.6~0jessie (GCC 4.9.2)`. Maybe try to apt upgrade it?

**Comment by lenovouser** [comment]
@TanakritBenz he is right, [`rethinkdb.com/apt/stretch/Packages`](https://download.rethinkdb.com/apt/dists/stretch/main/binary-amd64/Packages) doesn't include `v2.3.6` yet. Seems like the maintainers haven't produced a release for it yet.

**Comment by ceriath** [comment]
any updates on this?

**Comment by srh** [comment]
I might get time to look into it soon.

**Comment by srh** [comment]
I have the build working on stretch and was able to make packages relatively easily using the branch https://github.com/srh/rethinkdb/tree/sam/23x/stretch

It includes the following significant changes relative to the v2.3.6 tag commit:
58c3a7c09b7060e605fad333745480f2661ecd8c - make BIGNUM functions in GEO code avoid removed SSL API's
486dcc53effcb6e70bb7586d307a5b8a0f126896 - make stretch Debian packaging depend on libssl1.0-dev, not libssl-dev.  Also assumes you need clang++

Notably, you have to `apt install libssl1.0-dev`, which will remove libssl-dev, so that you build and link against the right version.  The reason is, Stretch's libcurl uses version 1.0 of libssl.

To build a package, run

```
srh@pc2:~/rethinkdb$ ./configure --allow-fetch CXX=clang++
* Detecting system configuration
Bash:                           4.4.12(1)-release
Use ccache:                     no
C++ Compiler:                   CLANG 3.8.1 (clang++)
Host System:                    x86_64-pc-linux-gnu
Build System:                   Linux 4.9.0-3-amd64 x86_64
Cross-compiling:                no
Host Operating System:          Linux
Build Architecture:             x86_64
stdlib:                         -lstdc++
C++11:                          ok
Precompiled web assets:         no
Protobuf compiler:              /usr/bin/protoc
python:                         python 2.7.13
Node.js package manager:        external/node_0.12.2
coffee:                         external/coffee-script_1.10.0
Browserify:                     external/browserify_13.1.0
bluebird:                       external/bluebird_2.9.32
web UI dependencies:            external/admin-deps_2.0.3
wget:                           /usr/bin/wget
curl:                           /usr/bin/curl
Google Test:                    external/gtest_1.7.0
termcap:                        -ltermcap
boost_system:                   -lboost_system
protobuf:                       -lprotobuf
v8 javascript engine:           external/v8_3.30.33.16-patched2
RE2:                            external/re2_20140111
z:                              -lz
crypto:                         -lcrypto
ssl:                            -lssl
curl:                           -lcurl
malloc:                         jemalloc
jemalloc (static):              external/jemalloc_4.1.0
Test protobuf:                  ok
Test boost:                     ok
Test OpenSSL:                   ok
Installation prefix:            /usr/local
Configuration prefix:           /usr/local/etc
Runtime data prefix:            /usr/local/var
* Wrote configuration to config.mk
srh@pc2:~/rethinkdb$ make build-deb DEB_RELEASE=stretch
```

**Comment by L11R** [comment]
It's nice that we can build it. But why there is no any binaries in repo yet?

**Comment by srh** [comment]
Merged the sam/23x/stretch branch to v2.3.x as of 69f1099db571272e79c7fbf5cdd20edc328affe3 with #6563.  Will also cherry-pick the changes to v2.4.x and next.

**Comment by srh** [comment]
Alright, fixed and pushed in v2.3.x, v2.4.x, and next.  Also made the Ubuntu part of the conditional future-compatible... as long as Ubuntu has g++-5.

**Comment by srh** [comment]
Reopening.  Binaries for stretch ought to be shipped.

**Comment by srh** [comment]
I've built packages for amd64 stretch.  They're built off the commit f04cdf9f858f0f515ac3b49df5840180416df40e.  (So this strictly speaking has some bugfix patches made after 2.3.6.)

I don't have access to any RethinkDB-hosted repos so I've put the debs and .tar.xz on my website:

http://samuelhughes.com/misc/bin/rethinkdb_2.3.6+stretch~0stretch_amd64.deb
http://samuelhughes.com/misc/bin/rethinkdb-dbg_2.3.6+stretch~0stretch_amd64.deb
http://samuelhughes.com/misc/bin/rethinkdb_2.3.6+stretch~0stretch.tar.xz

Their respective sha-256 hashes.
97ade4d5092bafac3a456197486f29069c560f4eabf4fcf974bd80d38099b521
99239a33597860f83da09145743c8797d30a3f78a3a6967360f40b713cfa3234
1d8b7e8b8152893769700a64493e260369d6d6d0ffdd919acc83c35f47033883

**Comment by eeerrrttty** [comment]
In resume, what should i follow to get rethinkDB running in debian stretch ????

**Comment by srh** [comment]
What do you mean by "resume"?

**Comment by L11R** [comment]
@srh he meant "summarizing" this issue, I think. When we will get 2.3.6 in the official repo?

**Comment by srh** [comment]
I m asked for access to do that (today), we will see.

**Comment by krull** [comment]
+1 on this. I ran across this, and had to install the workaround @lenovouser pointed out above.

**Comment by TarSzator** [comment]
+1

It would be nice to get a debian stretch package for RethinkDB

**Comment by mgween** [comment]
Is there a simple solution to this yet? I'm afraid I don't understand any of the above mentioned methods.

**Comment by mgween** [comment]
When I try to build from the package provided by @srh above, I get this error:

```
[429/436] LD build/release_clang_system/rethinkdb
/home/pi/dsc/build/external/curl_7.40.0/lib/libcurl.a(libcurl_la-openssl.o): In function `ossl_connect_common':
openssl.c:(.text+0x26f4): undefined reference to `SSLv3_client_method'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
src/build.mk:334: recipe for target 'build/release_clang_system/rethinkdb' failed
make[1]: *** [build/release_clang_system/rethinkdb] Error 1
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2
```

**Comment by srh** [comment]
@mgween I think you should make sure you have the following apt packages:

```
apt install build-essential protobuf-compiler python \
    libprotobuf-dev libcurl4-openssl-dev libboost-all-dev \
    libncurses5-dev libjemalloc-dev wget m4 clang libssl1.0-dev
```

If you have some other libcurl version, or some other libssl version, such as libssl-dev, I think it won't work.

I just tried compiling (with the .tar.xz linked above) on an up to date Stretch machine and it succeeded.  Both using `--with-system-malloc` and not.

**Comment by nullpointusr** [comment]
Hello guys, 

Since Debian 8 is reaching end of life on 18 June 2018 and will stop making security updates, is there any ETA on having RethinkDB 2.3.6 or a new version running from repos on Debian 9 ?

Thanks in advance.

**Comment by lenovouser** [comment]
@nullpointusr as far as I know most of the contributors are moving to [RebirthDB](https://github.com/RebirthDB). Communication mostly runs over [spectrum.chat/rebirthdb](https://spectrum.chat/rebirthdb)

**Comment by gabor-boros** [comment]
As you may know, we are back. @srh correct me if I'm wrong but we have a build for Debian 9 too am I right? Can I close this issue?

**Comment by srh** [comment]
A 2.3.5 package is available.

Looking at https://github.com/rethinkdb/rethinkdb-download/tree/master/version/2.3.6/deb, it looks like the 2.3.6 deb packages for stretch were never made.  But some stretch files are present.  Maybe the package build system silently failed for the 2.3.6 release.  So this is something that ought to be addressed.

**Comment by srh** [comment]
I've uploaded a 2.3.7 package for Stretch to the download server.  The instructions at https://rethinkdb.com/docs/install/debian/ should work.  Closing.
