### ISSUE TITLE
Generating on-disk format files via a separate process

### ISSUE THREAD

**Issue by mtharrison** [rethinkdb/rethinkdb#6380]
I have a (maybe crazy) idea. I'm generating lots of sample data to use in an app with Rethink for performance testing aside from other things. I generate this data in Node.js and then use the Node.js rethinkdb package to populate the database. The resulting JSON if I do rethinkdb export is several Gb. The data population is very slow (takes about 30mins) and the bottleneck is the speed of writes via the driver. I would like to make this a lot faster if possible. 

My idea is that I could maybe make my data generation faster if I could directly generate the RethinkDB on-disk format from my data generation script and then simply start RethinkDB up pointed at this folder.

Is there any docs regarding the on-disk format or can anyone provide any pointers on how I can approach this?

**Comment by srh** [comment]
First:  Are you doing batched inserts?  Soft durability mode?  Okay.

If you're already doing that, the disk format is, well, rather gnarly if you want to generate it yourself.  You've got:

1. A journal of metadata blocks that point at the LBA table.
2. LBA entries that list (block_id, file_offset, replication_timestamp) triples
3. Blocks, with the on-disk format being a gnarly b-tree format -- there's the layout of internal node blocks, leaf node blocks, the serialization format for those values, the serialization format for keys.

**Comment by thelinuxlich** [comment]
By the way, slightly off-topic(or maybe not), is there a ratio between document size X number of documents per batch to achieve optimal performance?

**Comment by srh** [comment]
I would guess it's the larger the better, as long as you don't run out of memory.  An asymptotic trade-off though.

**Comment by mtharrison** [comment]
Thanks for the response and the info @srh. Yes we're doing batched inserts and also using soft durability but I still want it to be faster. Sounds like it could be challenging though 😄

**Comment by srh** [comment]
Are you using 2.3.5?  I'm making a release "2.3.5-extra" that will have some soft durability performance improvements which might benefit you.  Depends on workload.  Also, what platform are you running this on?  I'm cutting this release, like, today, so I'll start with yours.

**Comment by mtharrison** [comment]
Yes @srh I'm using 2.3.5. I'm MacOSX based. Great, I'll be happy to test that out when it's released.

**Comment by srh** [comment]
If you're on OS X you might get big performance improvements by moving to Linux (probably no longer true if you run APFS).  OS X has really bad disk performance.

Also that's a bit of a problem for me giving you a workable release because I can't get 2.3.x to build successfully on OS X right now.

**Comment by marshall007** [comment]
@mtharrison I've wanted the same thing in the past. It could do wonders for the performance of `rethinkdb dump/restore` just in general. Would be really sweet if we could refactor the disk de/serialization logic out into a shared library and build some standalone `disk-format <-> JSON` CLI tooling.

**Comment by srh** [comment]
@mtharrison @marshall007 You might want to check out http://github.com/srh/rethinkdb/tree/sam/delayed (which is what'll turn into "2.3.5-extra") and see how import times change.
