### ISSUE TITLE
Serverless Support

### ISSUE THREAD

**Issue by brpatel0202** [rethinkdb/rethinkdb#6382]
Kindly update rethinkdb to provide serverless architect like Fauna DB.

By providing this feature rethinkdb will dominate the real time database industry within few month.
And its right time to implement and provide such type of features.
It will make developers life dramatically easy also.

**Comment by riyadhzen** [comment]
Hi
I am really not that good with buzz words and I looked this fauna thing up but didn't get their point.
Can you elaborate more on the thing you are asking. Do you mean that rethinkdb should be a service where people only store their data and run queries on that data without having a server running.
Thank you.

**Comment by v3ss0n** [comment]
Too broad and no specific. 
Serveless nothing but a made up buzzword.

**Comment by AtnNn** [comment]
There already exists services that will host RethinkDB instances for you. Building a RethinkDB cloud hosting solution or a "serverless" RethinkDB is out of scope for this repo.

**Comment by marshall007** [comment]
@brpatel0202 just FYI, Compose is probably the most popular hosted solution for RethinkDB. I know a lot of users have had success with it: https://www.compose.com/rethinkdb.

**Comment by brpatel0202** [comment]
Kindly go through this...
[FaunaDB-Technical-Whitepaper.pdf](https://github.com/rethinkdb/rethinkdb/files/1090474/FaunaDB-Technical-Whitepaper.pdf)

**Comment by brpatel0202** [comment]
@AtnNn 
And kindly go through this also...and then please reply...is it possible or we going to do with rethinkDB?
https://serverless.com/blog/serverless-database-wish-list/

**Comment by anlexN** [comment]
@riyadhzen , i am interested in yours. i really want to a database like sqlite. could you give me recommonds?
