### ISSUE TITLE
Indexed .between() + .distinct() possibilities

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#6408]
A ReQL query with .between([....],[....],{index: "foo"}).distinct({index: "foo"}) works, but .between([....],[....],{index: "foo"}).filter(....).distinct({index: "foo"}) doesn't.

**Comment by marshall007** [comment]
@thelinuxlich you can do:

```js
table.between(..., { index: 'foo' })
.distinct({ index: 'foo' })
.concatMap((key) =>
  table.getAll(key, { index: 'foo' }).filter(...).isEmpty().branch([], key)
)
```

... which is still pretty performant, since I think the `concatMap` evaluates concurrently across shards. If you're looking to get the documents back instead of just keys, drop the `.isEmpty().branch([], key)` part.

**Comment by thelinuxlich** [comment]
Hmm, actually your suggestion seems to introduce additional overhead

**Comment by marshall007** [comment]
@thelinuxlich compared to what? `.between(...).filter(...).distinct(<func>)`?

**Comment by thelinuxlich** [comment]
Sure, because you're querying again

**Comment by marshall007** [comment]
@thelinuxlich I don't think that's necessarily true. Particularly for larger sets, you're definitely going to run into issues with the `.filter()` followed by an unindexed `.distinct()`. The `.concatMap()` solution, however, doesn't end up coercing the stream to an array.

**Comment by AtnNn** [comment]
Something like this is possible:

```
.between([....],[....],{index: "foo"}).filter(....)("foo").distinct()
```

The architecture of the query engine makes it impossible to perform indexed operations after a filter.

**Comment by marshall007** [comment]
Note that @AtnNn's suggestion is probably preferable in most cases, but is still subject to the array size limit. The example I posted above in https://github.com/rethinkdb/rethinkdb/issues/6408#issuecomment-310226332 operates on a stream and will work for arbitrarily large sets.
