### ISSUE TITLE
Optimize r.object by translating to another ReQL

### ISSUE THREAD

**Issue by thelinuxlich** [rethinkdb/rethinkdb#6409]
By translating r.object("foo","bar") into r([["foo","bar"]]).coerceTo("object") the performance really goes up

**Comment by marshall007** [comment]
@thelinuxlich in what context are you seeing a significant performance difference? The following two queries take approximately the same amount of time for me:

```js
table.map([ r.row('foo'), r.row('bar') ]).coerceTo('object')
```

```js
table.concatMap([ r.row('foo'), r.row('bar') ])
.coerceTo('array').do(fields => r.object(r.args(fields)))
```

**Comment by thelinuxlich** [comment]
I've seen queries with .fold() and .merge() getting a 40% performance boost with this, probably happens in other cases

**Comment by marshall007** [comment]
@thelinuxlich that probably has more to do with #3408 than `r.object` itself then. I'm gonna close this as a duplicate, but I'll reopen if you have a query demonstrating poor `r.object` performance in particular.
