### ISSUE TITLE
next release general info

### ISSUE THREAD

**Issue by Extarys** [rethinkdb/rethinkdb#6412]
Hey there!

I'm very happy with my new db system :D

I was wondering what are the changes we can expect in 2.4?
Any ETA?

Thanks!

**Comment by srh** [comment]
Hi.  The 2.3.6 release is basically done.

To see the changes in 2.4 you can look at https://github.com/rethinkdb/rethinkdb/compare/v2.3.x...v2.4.x#files_bucket  :-)

From what I'm aware, 2.4 has write hooks, and... maybe some other features.  I'm not too familiar myself.  You can see a list of issues in the milestone with https://github.com/rethinkdb/rethinkdb/issues?utf8=%E2%9C%93&q=is%3Aissue%20milestone%3A2.4

**Comment by Extarys** [comment]
Thanks ;)
