### ISSUE TITLE
Shortcut to get the generated_keys values on insert or update

### ISSUE THREAD

**Issue by Extarys** [rethinkdb/rethinkdb#6416]
I don't know if I'm the only one who would like a shortcut for this.

```
r.db("test").table("users").insert({new: "user"}).run().then(function(res) {
    return res.id; //or lastInsertIds, or insertedId
})
```

```
r.db("test").table("users").insert([{new: "user1"}, {new: "user2"}]).run().then(function(res) {
    res.id[0];
})
```
(I don't know if I'm explaining this good enough:)
Return the guid on update - sometimes we don't have the id of the document, so we update it with a filter, but if it returns the id we could store it for reference later. Sometimes we search using non-indexed field, in some cases we could store the id in another table along with other related data.
(Mainly in statistical scenarios)
```
var lastUpdateId;
r.db("test").table("players").filter({name: 'test'}).update({score: 4}).run().then(function(res) {
    lastUpdateId = res.lastUpdateId; // Or updatedId
})
r.db("test").table("updateScoreHistory").insert({idplayer: lastUpdateId, scoreModifier: 4}).run().then(function(res) {
    return "complete!";
})
```

**Comment by neumino** [comment]
I guess what you want is this?
```
r.db('test').table('test').insert({})('generated_keys').nth(0)
```

**Comment by gjuchault** [comment]
I think he just want the guid of the updated documents.
I would use `return_changes` so that you have `old_val` and `new_val`, both containing guid

https://www.rethinkdb.com/api/javascript/update/

**Comment by Extarys** [comment]
Thans for the `('generated_keys').nth(0)`, didn't know that, right now I'm using result[0]['generated_keys'][0] which is a pain!

This will make it a little bit better ;)
