### ISSUE TITLE
SyntaxError: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL

### ISSUE THREAD

**Issue by mission10138** [rethinkdb/rethinkdb#6417]
Just trying to connect, I get this invalid URL error and can't find an answer anywhere.
```
r.connect({
	host:'localhost',
	port:29015,
	db:'test',
	user:'user',
	password:''
})
```

If I add http:// before localhost I get "ReqlDriverError: XHR error, http status 0."

**Comment by neumino** [comment]
You probably want to connect to the port 28015. 29015 is the clustering port.

**Comment by AtnNn** [comment]
@mission10138 You seem to be trying to use the javascript driver in the browser. It is only meant to be used server-side, using nodejs

**Comment by amal-san** [comment]
How to use the javascript driver in the browser? :thinking:

**Comment by codermapuche** [comment]
@amal-san You need a share library between browser and node, like this: https://github.com/codermapuche/rethinkdb-client-side-js

**Comment by amal-san** [comment]
Thanks   :smile:

**Comment by beenotung** [comment]
@amal-san you may look into horizon, it's a general purpose middleware to allow accessing rethinkdb from client side, with ACL (access control list) support. It's not actively updated but it works as I recall

Documentation: https://horizon-io.surge.sh
Repo: https://github.com/rethinkdb/horizon
