### ISSUE TITLE
Add authentication to Admin Panel

### ISSUE THREAD

**Issue by bdschr** [rethinkdb/rethinkdb#6424]
Hello,

First I would like to applaud the developers of rethinkdb for their fantastic work. It's a good project, and along with MongoDB, it's on my list of favorite databases.

However, I do have a suggestion that in my opinion is important. Add authentication to the web panel. And make it easy for people to manage the users and permissions per database. You already have all of it functionality wise. It just needs to be integrated into the web admin.

Best regards,
bdschr

**Comment by RyoshiKayo** [comment]
You can just use the built in function of your webserver. For instance, in NGINX you make a `.htpasswd` file with the correct information then add `auth_basic` and `auth_basic_user_file` to a location. https://www.nginx.com/resources/admin-guide/restricting-access-auth-basic/

**Comment by AtnNn** [comment]
Thanks for the suggestion. We already have an issue open for this (#5947).

**Comment by bdschr** [comment]
@RyoshiKayo I know that. Bind it to localhost, make a reverse proxy on nginx and add basic auth to it. Or bind it to localhost and connect to it with a SSH tunnel. My point however is that besides it being not really user friendly; it doesn't feel secure.

**Comment by RyoshiKayo** [comment]
The webpanel is insecure by nature, you can run commands directly to the database/cluster. Im not trying to say it's a replacement for adding a built in way, just saying that NGINX already has this built in, and it covers everything on the location you set.
