### ISSUE TITLE
JSON Decode Error while working with rethinkdb

### ISSUE THREAD

**Issue by SirEdvin** [rethinkdb/rethinkdb#6426]
RethinkDB version: 2.3.5
Driver: python

Some times, I get strange response from rethinkdb: 

In res_buf: 

```
b'{"deleted":0,"errors":0,"inserted":0,"replaced":1,"skipped":0,"unchanged":0}]}$\x00\x00\x00\x00\x00\x00\x00Z\x00\x00\x00'
```
So, python fails with JSON Decode Error. 

You can see full error in [sentry](https://loany.sentry.kit-xxi.com.ua/share/issue/352e313730/).

**Comment by AtnNn** [comment]
Are you accessing the same RethinkDB connection simultaneously from multiple threads? That isn't supported.

**Comment by SirEdvin** [comment]
Ah, yes. Thanks, I will try to fix this from my side.
