### ISSUE TITLE
confusing with the path source when initialize the db

### ISSUE THREAD

**Issue by roysG** [rethinkdb/rethinkdb#6430]
I installed yesterday rethinkdb on my localhost, first of all i have to tell the experience to work with this db is amazing!

Steps to reproduce:

**In the beginning i started the server up normally:(logs)**

Roys-MacBook-Pro:~ rsabah$ rethinkdb --http-port 2020
Running rethinkdb 2.3.5 (CLANG 8.0.0 (clang-800.0.38))...
Running on Darwin 16.0.0 x86_64
Loading data from directory /Users/rsabah/rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 2020
Listening on cluster addresses: 127.0.0.1, ::1
Listening on driver addresses: 127.0.0.1, ::1
Listening on http addresses: 127.0.0.1, ::1
To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.
Server ready, "Roys_MacBook_Pro_local_ois" 1cdf286d-4fcf-4f40-808a-2c39ed32c20a

Removing file /Users/rsabah/rethinkdb_data/c8f39455-321f-42e9-b94b-4d1dd1c32bc4
Removing file /Users/rsabah/rethinkdb_data/3d5a94ed-a1bc-4b0a-b4be-a5345a978e01

----------------------

**Before i went sleep i shutdown the server (logs):**

^CServer got SIGINT from pid 351, uid 501; shutting down...
Shutting down client connections...
All client connections closed.
Shutting down storage engine... (This may take a while if you had a lot of unflushed data in the writeback cache.)
Storage engine shut down.

**When i wake up today morning, i started the server (logs):**

Roys-MacBook-Pro:xxx rsabah$ rethinkdb --http-port 2020
**Recursively removing directory /Users/rsabah/www/xxx/rethinkdb_data/tmp**
Initializing directory /Users/rsabah/www/xxx/rethinkdb_data
Running rethinkdb 2.3.5 (CLANG 8.0.0 (clang-800.0.38))...
Running on Darwin 16.0.0 x86_64
Loading data from directory /Users/rsabah/www/xxx/rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 2020
Listening on cluster addresses: 127.0.0.1, ::1
Listening on driver addresses: 127.0.0.1, ::1
Listening on http addresses: 127.0.0.1, ::1
To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.
Server ready, "Roys_MacBook_Pro_local_8b1" 6462e432-ae20-491e-9ec7-f8c23af50aa8

I think it happen because the line:
**Recursively removing directory /Users/rsabah/www/xxx/rethinkdb_data/tmp**

After that happen i also tried to stop the server start it again, enter some data to customers db, stop the server and start it again, this time the data was ok, but also the line 
"Recursive removing direcory.." and "Initializing directory..." were not there.

Any suggest to explain why this happened?
i am little scary now for using it on production, waiting for answer.
Thanks.

**Comment by AtnNn** [comment]
The deleted directory, `tmp`, only contains temporary files.

The source of your problem may be that you are not using the same data directory:

>```
> Loading data from directory /Users/rsabah/rethinkdb_data
>```
>```
>Loading data from directory /Users/rsabah/www/xxx/rethinkdb_data
>```

RethinkDB defaults to using `./rethinkdb_data` in the current working directory. You can select which data directory to use with the `-d` option.

**Comment by roysG** [comment]
@AtnNn , You right!
The data is not deleted, i accident init the rethink server from other path, sorry for that.
I also scroll in other bugs of this repository about the suddenly deletion data and i saw that other users encounter the problems.

Link1:
https://github.com/rethinkdb/rethinkdb/issues/3717

Link2:
https://github.com/rethinkdb/rethinkdb/issues/1339

Should i need to worry about that?

**Comment by roysG** [comment]
??
