### ISSUE TITLE
Release 2.3.6

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#6434]
We plan to release 2.3.6 on Monday if no new urgent issues are discovered in RC2 (#6365).

# Checklist

- [x] Write blog post
- [x] Update website
- [x] Add release date to release notes
- [x] Tag and push v2.3.6
- [x] Build packages
  - [x] Source
  - Debian
    - [x] Jessie
  - Ubuntu
    - [x] Saucy
    - [x] Trusty
    - [x] Utopic
    - [x] Vivid
    - [x] Wily
    - [x] Xenial
    - [x] Yakkety
    - [x] Zesty
  - Centos
    - [x] 6
    - [x] 7
  - macOS
    - [x] dmg
  - [x] Windows
- [x] Upload packages to download.rethinkdb.com
- [x] Update the update server with the new release number
- [ ] ~homebrew PR~ (I don't have OS X, someone else please do this)
- [ ] ~Update docker image~ (See https://github.com/rethinkdb/rethinkdb-dockerfiles)
- [x] Comment on fixed issues about new release
- [x] Post changelog to github releases page

**Comment by linuxjuggler** [comment]
any plan to have a package for ARM instead of building it each time from the source?

**Comment by AtnNn** [comment]
@linuxjuggler It should be possible, but not for 2.3.6. Please open an issue (or even better, a pull request) for packaging for a specific linux distribution and architecture.

**Comment by AtnNn** [comment]
The packages and blog post are up:

* https://download.rethinkdb.com
* https://rethinkdb.com/blog/2.3.6-release/

**Comment by AtnNn** [comment]
The update server has been updated.
