### ISSUE TITLE
Python Driver: ImportError: cannot import name ql2_pb2

### ISSUE THREAD

**Issue by NicoHood** [rethinkdb/rethinkdb#6452]
When running the driver (2.3.6) from python2 AND python3 i get the following error:

```py
>>> import rethinkdb as r
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/rethinkdb/__init__.py", line 4, in <module>
    from .ast import *
  File "/usr/lib/python2.7/site-packages/rethinkdb/ast.py", line 13, in <module>
    from . import ql2_pb2 as p
ImportError: cannot import name ql2_pb2
```

BTW: The pypi package is out of date and should be updated.

**Comment by NicoHood** [comment]
I noticed that an older package worked, but i cannot reproduce this. So I guess a dependency update on archlinux broke the python driver setup? Any ideas why?

**Comment by NicoHood** [comment]
I tried to install the python driver when i also recompiled rethinkdb. It seems to work properly then. So is it a requirement to compile rethinkdb first and then compile the driver?

Should I also compile the driver with make or with setuptools? It would be nice if you can help me packaging the driver properly.

I'd also like to publish teh ruby/java drivers, even though I cannot test them. Help appreciated.

**Comment by NicoHood** [comment]
So the solution seems to be:
```
./configure --allow-fetch
make
python setup.py install --root="${pkgdir}" --optimize=1
```

Is this the correct way to compile the python drivers? Is there any way to not use configure? I've used the defaults, as I dont compile rethinkdb itself with this setup, only the drivers.

**Comment by TTimo** [comment]
I'm running into this on Windows - any advice?

**Comment by srh** [comment]
I don't know much about Python environments -- I'd recommend asking at https://spectrum.chat/rethinkdb

**Comment by codeskyblue** [comment]
Just run `make prepare`

**Comment by adriantodt** [comment]
Just as a note, the Java driver is now being published and has it's own repository (https://github.com/rethinkdb/rethinkdb-java).

**Comment by gabor-boros** [comment]
FTR: closed as it was answered

(Run make prepare in the python driver repo -- rethinkdb/rethinkdb-python)
