### ISSUE TITLE
pool connection in ruby driver 

### ISSUE THREAD

**Issue by michelson** [rethinkdb/rethinkdb#6456]
Hello, how can I handle many connections on Ruby driver ?

we are opening new connection for every query, and then close the connection when the query is done, but we receive too many open files any way on our production systems, 
it seems there is no pool connection on ruby driver , how it's supposed to use Rethink connection in production apps ?

best regards

**Comment by michelson** [comment]
```ruby



  task :import_records => :environment do
    Model.where([...]).find_each do |model|
      model.store!
    end
  end

  # in some active record model
  def store!
    response = self.class.table
                         .insert(self.as_json)
                         .run(self.class.conn)
    self.class.conn.close([{:noreply_wait => true}])
    if response["errors"] != 0
      errors.add(:base, response["first_error"])
    end

    self
  end
```

**Comment by gabor-boros** [comment]
FTR: closed as it was answered
