### ISSUE TITLE
r.expr({}).merge([]) - Merging an array into an object

### ISSUE THREAD

**Issue by aleclarson** [rethinkdb/rethinkdb#6457]
I noticed it's possible to merge an array into an object:

```js
r.expr({ a: 1 }).merge([ {b: 2}, {c: 3} ])

// Result
[ {b: 2}, {c: 3} ]
```

It looks like the object is ignored entirely.

Is there a reason it works like this?

I would expect it to merge each object in the array into the first object:
```js
{ a: 1, b: 2, c: 3 }
```

**Comment by marshall007** [comment]
@aleclarson to achieve the behavior you described, you'd need to use `r.args()`:

```js
r.expr({ a: 1 }).merge(r.args([ {b: 2}, {c: 3} ]))
```
