### ISSUE TITLE
[Question] - rethinkdb for production

### ISSUE THREAD

**Issue by juvasquezg** [rethinkdb/rethinkdb#6466]
Hi,

Excuse me for my fears, I can use rethinkdb in production right now, is this project still being developed?

Thank you!!

**Comment by chrisvariety** [comment]
We use it in production for 100's of sites.

**Comment by thelinuxlich** [comment]
RethinkDB is the main database of web analytics system AIDAX since 2014

**Comment by aaronorosen** [comment]
I have also been using it for a while and haven't encountered any major issues.

**Comment by juvasquezg** [comment]
Thank you so much!!!
