### ISSUE TITLE
Sorting an array of literals

### ISSUE THREAD

**Issue by aleclarson** [rethinkdb/rethinkdb#6470]
Is there a method like `orderBy` that sorts using the value itself instead of one of its keys?

Or does RethinkDB expect you to sort those on your own server before inserting/updating?

A silly example:
```js
r.expr([ 3, 1, 2 ]).sort() // => [1, 2, 3]
r.expr([ 3, 1, 2 ]).sort(r.desc) // => [3, 2, 1]
```

**Comment by lbguilherme** [comment]
I usually do `r.expr([ 3, 1, 2 ]).orderBy(x => x)` and `r.expr([ 3, 1, 2 ]).orderBy(r.desc(x => x))`

**Comment by neumino** [comment]
You can also use `r.row` if you are using JavaScript
```
r.expr([3,20,1]).orderBy(r.desc(r.row))
```
