### ISSUE TITLE
rethink fails to compile on Ubuntu 17.04

### ISSUE THREAD

**Issue by mheins** [rethinkdb/rethinkdb#6471]
I'm trying to compile rethinkdb on Ubuntu17.04, there seems to be something wrong with how it's fetching from npm, error logs are as follows

Output from make:

 [1/453] BUILD bluebird_2.9.32
++ mktemp -d /home/mheins/rethinkdb/external/npm_cache-XXXXXXXX
+ cache_dir=/home/mheins/rethinkdb/external/npm_cache-lGcdQIpW
+ [[ Linux = Windows ]]
+ /usr/local/bin/npm --userconfig /home/mheins/rethinkdb/mk/support/config/npm.conf --cache /home/mheins/rethinkdb/external/npm_cache-lGcdQIpW install /home/mheins/rethinkdb/external/bluebird_2.9.32
npm WARN enoent ENOENT: no such file or directory, open '/home/mheins/rethinkdb/build/external/bluebird_2.9.32/package.json'
npm WARN bluebird_2.9.32 No description
npm WARN bluebird_2.9.32 No repository field.
npm WARN bluebird_2.9.32 No README data
npm WARN bluebird_2.9.32 No license field.

npm ERR! path /home/mheins/rethinkdb/build/external/bluebird_2.9.32/node_modules/.staging/bluebird-708b0848
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/mheins/rethinkdb/build/external/bluebird_2.9.32/node_modules/.staging/bluebird-708b0848' -> '/home/mheins/rethinkdb/external/bluebird_2.9.32/node_modules/bluebird'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mheins/rethinkdb/external/npm_cache-lGcdQIpW/_logs/2017-08-14T20_51_23_692Z-debug.log

Full error log: ./build/external/bluebird_2.9.32_install.log
mk/support/build.mk:148: recipe for target 'build/external/bluebird_2.9.32/install.witness' failed
make[1]: *** [build/external/bluebird_2.9.32/install.witness] Error 1
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2

Extended log from file:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   '--userconfig',
1 verbose cli   '/home/mheins/rethinkdb/mk/support/config/npm.conf',
1 verbose cli   '--cache',
1 verbose cli   '/home/mheins/rethinkdb/external/npm_cache-lGcdQIpW',
1 verbose cli   'install',
1 verbose cli   '/home/mheins/rethinkdb/external/bluebird_2.9.32' ]
2 info using npm@5.3.0
3 info using node@v8.3.0
4 verbose npm-session f9c7fa796d72d563
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly pacote directory manifest for undefined@file:/home/mheins/rethinkdb/external/bluebird_2.9.32 fetched in 7ms
8 silly install loadIdealTree
9 silly install cloneCurrentTreeToIdealTree
10 silly install loadShrinkwrap
11 silly install loadAllDepsIntoIdealTree
12 silly resolveWithNewModule packed-bluebird@2.9.32 checking installable status
13 silly currentTree bluebird_2.9.32
14 silly idealTree bluebird_2.9.32
14 silly idealTree `-- packed-bluebird@2.9.32
14 silly idealTree   `-- bluebird@2.9.32
15 silly install generateActionsToTake
16 silly diff-trees filtering actions: includeDev false includeProd true
17 silly diffTrees action count 2
18 silly diffTrees add bluebird@2.9.32
19 silly diffTrees add packed-bluebird@2.9.32
20 silly decomposeActions action count 12
21 silly decomposeActions preinstall bluebird@2.9.32
22 silly decomposeActions build bluebird@2.9.32
23 silly decomposeActions install bluebird@2.9.32
24 silly decomposeActions postinstall bluebird@2.9.32
25 silly decomposeActions finalize bluebird@2.9.32
26 silly decomposeActions refresh-package-json bluebird@2.9.32
27 silly decomposeActions preinstall packed-bluebird@2.9.32
28 silly decomposeActions build packed-bluebird@2.9.32
29 silly decomposeActions install packed-bluebird@2.9.32
30 silly decomposeActions postinstall packed-bluebird@2.9.32
31 silly decomposeActions finalize packed-bluebird@2.9.32
32 silly decomposeActions refresh-package-json packed-bluebird@2.9.32
33 silly install executeActions
34 silly doSerial global-install 12
35 verbose correctMkdir /home/mheins/rethinkdb/external/npm_cache-lGcdQIpW/_locks correctMkdir not in flight; initializing
36 verbose makeDirectory /home/mheins/rethinkdb/external/npm_cache-lGcdQIpW/_locks creation not in flight; initializing
37 silly makeDirectory /home/mheins/rethinkdb/external/npm_cache-lGcdQIpW/_locks uid: 1000 gid: 1000
38 verbose lock using /home/mheins/rethinkdb/external/npm_cache-lGcdQIpW/_locks/staging-e0a93db957eb7f7e.lock for /home/mheins/rethinkdb/build/external/bluebird_2.9.32/node_modules/.staging
39 silly doParallel extract 12
40 silly doReverseSerial unbuild 12
41 silly doSerial remove 12
42 silly doSerial move 12
43 silly doSerial finalize 12
44 silly finalize /home/mheins/rethinkdb/external/bluebird_2.9.32/node_modules/bluebird
45 verbose unlock done using /home/mheins/rethinkdb/external/npm_cache-lGcdQIpW/_locks/staging-e0a93db957eb7f7e.lock for /home/mheins/rethinkdb/build/external/bluebird_2.9.32/node_modules/.staging
46 warn enoent ENOENT: no such file or directory, open '/home/mheins/rethinkdb/build/external/bluebird_2.9.32/package.json'
47 verbose enoent This is related to npm not being able to find a file.
48 warn bluebird_2.9.32 No description
49 warn bluebird_2.9.32 No repository field.
50 warn bluebird_2.9.32 No README data
51 warn bluebird_2.9.32 No license field.
52 verbose stack Error: ENOENT: no such file or directory, rename '/home/mheins/rethinkdb/build/external/bluebird_2.9.32/node_modules/.staging/bluebird-708b0848' -> '/home/mheins/rethinkdb/external/bluebird_2.9.32/node_modules/bluebird'
53 verbose cwd /home/mheins/rethinkdb/build/external/bluebird_2.9.32
54 verbose Linux 4.10.0-32-generic
55 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "--userconfig" "/home/mheins/rethinkdb/mk/support/config/npm.conf" "--cache" "/home/mheins/rethinkdb/external/npm_cache-lGcdQIpW" "install" "/home/mheins/rethinkdb/external/bluebird_2.9.32"
56 verbose node v8.3.0
57 verbose npm  v5.3.0
58 error path /home/mheins/rethinkdb/build/external/bluebird_2.9.32/node_modules/.staging/bluebird-708b0848
59 error code ENOENT
60 error errno -2
61 error syscall rename
62 error enoent ENOENT: no such file or directory, rename '/home/mheins/rethinkdb/build/external/bluebird_2.9.32/node_modules/.staging/bluebird-708b0848' -> '/home/mheins/rethinkdb/external/bluebird_2.9.32/node_modules/bluebird'
63 error enoent This is related to npm not being able to find a file.
64 verbose exit [ -2, true ]

**Comment by mheins** [comment]
config as follows:

./configure --allow-fetch --prefix=/opt CXX=g++-5
* Detecting system configuration
Bash:                           4.4.7(1)-release
Use ccache:                     no
C++ Compiler:                   GCC 5.4.1 (g++-5)
Host System:                    x86_64-linux-gnu
Build System:                   Linux 4.10.0-32-generic x86_64
Cross-compiling:                no
Host Operating System:          Linux
Build Architecture:             x86_64
C++11:                          ok
Precompiled web assets:         no
Protobuf compiler:              /usr/bin/protoc
python:                         python 2.7.13
Node.js package manager:        /usr/local/bin/npm
coffee:                         coffee 1.12.7
Browserify:                     external/browserify_13.1.0
bluebird:                       external/bluebird_2.9.32
web UI dependencies:            external/admin-deps_2.0.4
wget:                           /usr/bin/wget
curl:                           /usr/bin/curl
Google Test:                    external/gtest_1.7.0
termcap:                        -ltermcap
boost_system:                   -lboost_system
protobuf:                       -lprotobuf
v8 javascript engine:           external/v8_3.30.33.16-patched
RE2:                            external/re2_2015-11-01
z:                              -lz
crypto:                         -lcrypto
ssl:                            -lssl
curl:                           external/curl_7.54.1
malloc:                         jemalloc
jemalloc (static):              external/jemalloc_4.5.0
Test protobuf:                  ok
Test boost:                     ok
Installation prefix:            /opt
Configuration prefix:           /opt/etc
Runtime data prefix:            /opt/var
* Wrote configuration to config.mk

**Comment by neok-m4700** [comment]
I'm hitting the exact same issue with node@8.4.0

Did you find a hotfix ?

**Comment by mheins** [comment]
I didn't find a solution to this problem, I ended up manually installing via the binaries instead (for some reason the package managers I tried failed to do this)

**Comment by robertjpayne** [comment]
What version are you trying to compile v2.3.6?

**Comment by micahscopes** [comment]
@robertjpayne I'm having this issue also on Arch Linux.  I'm trying to build v2.3.6-srh-extra so that I can change flush rates.

**Comment by srh** [comment]
@micahscopes I will make an Arch Linux VM and see what I can do.

For Ubuntu 17.04 Server, with nothing else installed, I found these instructions worked. It's possible this was on next, and not 2.3.6.

```
- apt install build-essential protobuf-compiler python \
    libprotobuf-dev libcurl4-openssl-dev libboost-all-dev \
    libncurses5-dev libjemalloc-dev wget m4 clang libssl1.0-dev
- ./configure --allow-fetch CXX=clang++
```

**Comment by srh** [comment]
I've pushed new commits via #6554 to fix the v2.3.x build.  (One of them, upgrading NodeJS, actually fixes the build.)

**Comment by srh** [comment]
@micahscopes Try to build the latest version from the new head of the sam/236delayed branch, https://github.com/srh/rethinkdb/commit/11f1f9a60981eafa1ecf9be05937f001dd28b3b6 .  Let me know if it doesn't build -- I tried installing Arch Linux but for some reason that is incredibly difficult, and I don't want to waste my time any further in that direction.

**Comment by micahscopes** [comment]
Will do!  Thank you so much!

p.s. Arch Linux is awesome, but the default installation instructions are
very DIY.  When I first installed Arch, I too was put off by installation,
but found [this](https://arch-anywhere.org/download/) alternate
installation tool called "Anarchy Installer" (Unfortunately, their
documentation isn't up right now, but the installer on that ISO is self
explanatory).  Anyway, I've never looked back.  The documentation is
incredible and the default configurations are usually very well done.  My
system is very stable, since Arch doesn't make imposing decisions whenever
I upgrade like Ubuntu does.  I've learned more in the last couple years
using Arch than I ever did with 8+ years of Ubuntu/Debian.

**Comment by srh** [comment]
I wound up going with a pre-built VM.  Using `./configure --allow-fetch CXX=clang++` to build, because GCC 7 won't build the old version of v8 we use.  For some reason building node and v8 are using only 1 core each (instead of passing down the -j16 parameter I'm using) so building is taking a while.

**Comment by srh** [comment]
Hey, I'm getting some weird ENOENT issues with bluebird and other npm packages now, but only on certain platforms.  Let me try and figure out what the problem is.

**Comment by srh** [comment]
Hey, I've fixed the build errors with the latest commit in v2.3.x, which downgrades node from 8.x to 6.11.0.  That's the version of node that 2.4.x and next had been upgraded to.

@micahscopes I've updated my sam/236delayed branch (2.3.6-srh-extra) with the fix: https://github.com/srh/rethinkdb/tree/sam/236delayed

**Comment by micahscopes** [comment]
@srh thank you so much!  This will prolong the life of my server's SSD 👍

**Comment by shankyrox** [comment]
I was running into this same error. I already had a later version of node installed on my Mac and I guess node version `6.11.0` was not getting used. There seems to be a change in behaviour of command `npm install <folder>` in later versions of npm leading to this issue. Doing a `npm pack` and `npm install <path_to_tgz_file>` fixed this issue for me for bluebird and other node dependencies : https://github.com/shankyrox/rethinkdb/commit/b053d63a96d2f2f0cc52ba1668311a631c5c026b

**Comment by srh** [comment]
@shankyrox You can also use `--fetch npm` on the configure line.

**Comment by srh** [comment]
I guess this issue is closeable.
