### ISSUE TITLE
Silent mode for rethinkdb dump

### ISSUE THREAD

**Issue by shadow7412** [rethinkdb/rethinkdb#6478]
I use rethink dump in a cron job. This means that any time a command has output, it sends me an email.

Could we please consider a `-s` or similar option that suppresses all output unless an error occurs?
I know I could redirect out to `/dev/null`, but if the command natively supported it then I wouldn't have to worry about it swallowing useful errors.

**Comment by lbguilherme** [comment]
It prints the "useless" output to STDOUT and the error output to STDERR. So, if you do `rethinkdb-dump ... > /dev/null`, it will only supress the useless output. If there is an error, it will be printed (and you should still receive an email)

**Comment by shadow7412** [comment]
While a good work-around, I would prefer to see *all* output when it errors, in case there are more details that help work out what is going on. I still think this would be useful feature - but I'll redirect stdout for now.

**Comment by marshall007** [comment]
Both `rethinkdb-dump` and `rethinkdb-restore` support the `--quiet` option, which suppresses writing everything but errors to stdout.

See #5378 and #5528.

**Comment by shadow7412** [comment]
Glad to hear it has this support. Should the documentation be updated to reflect this?
(I was using https://www.rethinkdb.com/docs/backup/)

**Comment by marshall007** [comment]
@shadow7412 yep, thanks. Note that it is available in the `--help` text though.

**Comment by shadow7412** [comment]
@marshall007 right you are. Not sure how I managed to miss that actually.
Thanks for raising the ticket.
