### ISSUE TITLE
Uninstall RethinkDB on Ubuntu

### ISSUE THREAD

**Issue by lautiamkok** [rethinkdb/rethinkdb#6480]
After [installing RethinkDB ](https://www.rethinkdb.com/docs/install/ubuntu/)and have it running on my localhost, it seems have messed up my server, e.g.:

```
    const Koa = require('koa')
    const app = new Koa()
    
    // Basic.
    app.use(async ctx => {
      console.log("Hello world!")
      ctx.body = 'Hello World'
    })
    
    app.listen(3000)
```
Now on my terminal, I get everything **twice**:

    Hello world!
    Hello world!

What is going on?

I want to try to uninstall RethinkDB but there is no guide or info about it from the [doc](https://rethinkdb.com/docs/)!

Could you guys please advice?

**Comment by marshall007** [comment]
@lautiamkok it depends on how you installed it, but if you installed a pre-built binary via `apt-get` it should just be `sudo apt-get remove rethinkdb`.

Note that installing RethinkDB is almost certainly not the cause of or at all related to the behavior you're seeing in your Node app.

**Comment by gabor-boros** [comment]
The way to uninstall RethinkDB package is provided above. For other installs, only the person who installed the binary knows what she/he did and that need to be "reverted".
