### ISSUE TITLE
2.3.6 docker image?

### ISSUE THREAD

**Issue by zhaoyao91** [rethinkdb/rethinkdb#6482]
why there isn't 2.3.6 docker image?

**Comment by ghiscoding** [comment]
FYI, you might want to see other open threads at [rethinkdb-dockerfiles #38](https://github.com/rethinkdb/rethinkdb-dockerfiles/issues/38) and [docker library #3332](https://github.com/docker-library/official-images/pull/3332).

**Comment by mterron** [comment]
Rethinkdb is in the Alpine repository for edge. You can check my [Dockerfile](https://github.com/mterron/rethinkdb/) to see how to install.

**Comment by tavurth** [comment]
It seems that it's been out for a while now, running the `rethinkdb 2.3.6`, pulled into `docker-compose` via the name `rethinkdb:latest`
