### ISSUE TITLE
add the 'bind=all' option

### ISSUE THREAD

**Issue by TheOnlyArtz** [rethinkdb/rethinkdb#6483]
Hello There, So today I've wanted to secure my cluster with a password and all of the sudden I could not get my cluster back online using `sudo service rethinkdb start`
Because it says `'bind=all' option to /etc/rethinkdb/instances.d/cluster_instance.conf`
And it's already set to all inside the cluster_instance
```bash
## Address of local interfaces to listen on when accepting connections
## May be 'all' or an IP address, loopback addresses are enabled by default
## Default: all local addresses
# bind=all
```

Please help, I will be so thankful!

**Comment by nobobo1234** [comment]
Maybe uncomment the `# bind=all` actually https://www.howtogeek.com/118389/how-to-comment-out-and-uncomment-lines-in-a-configuration-file/

**Comment by marshall007** [comment]
@TheOnlyArtz can you confirm that uncommenting the `bind` option in your config file resolves the issue?

**Comment by TheOnlyArtz** [comment]
Yes
