### ISSUE TITLE
Data Explorer fails unexpectedly on correct query

### ISSUE THREAD

**Issue by trickkiste** [rethinkdb/rethinkdb#6484]
This query:
```
r.db("db").table("table").filter(lambda x: x['MetaData']['name'].match('789'))
```

Will produce this error, even though the same query works fine in python:
```
JavaScript error:
SyntaxError: missing ) after argument list
```
![Screenrecording](http://g.recordit.co/qvro2z2Avs.gif)

Rethinkdb Docker Image 2.3.5

**Comment by chrisvariety** [comment]
The Data Explorer uses the javascript driver, and therefore expects queries written using the javascript driver's syntax:

```
r.db("db").table("table").filter(function(x) { return x('MetaData')('name').match('789'); })
```

**Comment by marshall007** [comment]
Thanks @chrisvariety!

**Comment by trickkiste** [comment]
Thank you so much. That helped!
