### ISSUE TITLE
Is there a way to listen to a special event when RethinkDB reconnects?

### ISSUE THREAD

**Issue by mariosouto** [rethinkdb/rethinkdb#6485]
I'm using a NodeJS application with a RethinkDB database.

When i start the server the application establish a connection with Rethink and it starts to listen to the changes in a table using RethinkDB feeds.

The problem is when RethinkDB goes down. Because of that the feed is interrupted, as the documentation of RethinkDB says, but when the DB is up again there's no way to reconnect to the feed. So changes are happening but i'm not just notice them because was lost somewhere.

What i was wondering, i wasn't able to find it in the docs, is if RethinkDB emits an event of some kind when it starts running again.

So my idea was to make my Node app to listen to that event and make the feed reconnect again as soon as it notice that event.

Is there an event of that kind that Rethink emits?

Sorry but i wasn't able to find it in the docs. Hope i was clear enough

Thanks!

**Comment by Extarys** [comment]
Depending on your needs, I know the rethinkdbdash for nodejs have a way to monitor the number of connections and have event handlers. Don't know if that helps.

**Comment by cur3n4** [comment]
In rethinkdbdash you can do:
`r.getPoolMaster().on('healthy', (healthy) => ...);`

**Comment by mariosouto** [comment]
@cur3n4 Thanks! I believe that `r.getPoolMaster().on('healthy', (healthy) => ...)` will work.
