### ISSUE TITLE
how to use r.getPoolMaster().on('healthy' with a rethinkdb-proxy

### ISSUE THREAD

**Issue by mariosouto** [rethinkdb/rethinkdb#6486]
Hi!

I'm using RethinkDB feeds with a NodeJS application in order to keep track on the changes in the database.

When RethinkDB goes down i use

```
r.getPoolMaster().on('healthy'
```

to keep track if RethinkDB is alive or not, and rejoin the feeds.

This works just fine. When RethinkDB goes down it emits a `healthy` event with the value of `false` and another one with the value of `true` when it goes up.

But now i need to use a RethinkDB-Proxy in front of my RethinkDB instance and i'm making my Node app connect to the Proxy. The problem is that when i use a Proxy and RethinkDB goes down, it's not emitting the `healthy` event or at least i don't get it bc i'm connected to the Proxy.

Is there a way to make the Proxy emit this event? Or to capture it from my instance? Or any other possible approach?

Hope i was clear enough

Thanks!

**Comment by marshall007** [comment]
@mariosouto I don't think `healthy` events are going to be emitted if you are able to connect to the proxy node. That said, this is a [rethinkdbdash](https://github.com/neumino/rethinkdbdash) related question, so you might have more luck opening up an issue over there and having @neumino take a look.

**Comment by mariosouto** [comment]
@marshall007 Thanks! I'll move this to rethinkdbdash then
