### ISSUE TITLE
Proposal - Permission management in Admin Panel

### ISSUE THREAD

**Issue by Extarys** [rethinkdb/rethinkdb#6496]
**Current behavior:**

The only way to manage users and databases permissions is by using the ReQL language in the Data Explorer section of the Admin Panel.

**Ideal behavior:**

Admins should be able to easily add, modify and delete users and users permissions to the server and to specific databases.

**Change to be made:**

The proposal is to create another page, called **administration** prehaps, where there is a list of current users with global and per-database permissions. This method would be ideal for someone who's seeking to change multiple users and/or permissions.

Also, on the **Tables** page, just next to the buttons to add tables and delete databases, we could add a **Manage permissions** option, which would open a modal to set the permissons. (Ideal scenario to quickly modify only a single database instead of going to another page.

**Comments:**

Before wasting my time on that I wanted to make sure it was going to be useful - for me it would be awesome because I always forget to configure those and it would be quicker for some users.

EDIT:

Nevermind, already working on it - I can't sleep.

How can I replace my local admin panel or use this one on another port?

**Comment by lbguilherme** [comment]
Take a look at this project: https://github.com/AtnNn/rethinkdb-webui

In the ideal world, the admin panel would be totally unrelated to the rethinkdb core itself, running as a separated instance, and communicating with ReQL. This project is a first step on this direction and you probably build on top of it.

Relevant: #3861 and #6344

**Comment by Extarys** [comment]
Like phpnyadmin. its sad. the fact that its included out of the box makes it easier a little. :P may I ask why?

**Comment by lbguilherme** [comment]
It would still be deployed and installed as a single product, would just be developed externally. This allows faster development (more people bringing new features and improvements, as you are) and also allows forks of it. End user experience shouldn't be impacted.

**Comment by Extarys** [comment]
Awesome thanks - I'll make the proposal on the other repo.

Shouldn't the webui beon rethinkdb/ instead of AtnNn? (Maybe I just don't understand but I don't really care it's curiosity.

**Comment by Extarys** [comment]
I'll close this since the web ui is managed on another repo.
