### ISSUE TITLE
Unable to download jemalloc when install rethinkdb

### ISSUE THREAD

**Issue by nellshamrell** [rethinkdb/rethinkdb#6499]
Rethinkdb tries to download jemalloc from canonware.com, which appears to be down at the moment.  I've opened [an issue on the jemalloc/jemalloc project as well](https://github.com/jemalloc/jemalloc/issues/1026).

**Comment by srh** [comment]
Agreed this needs to be fixed, a more reliable host should be used.

If you need to build I recommend replacing the canonware URL in mk/support/pkg/jemalloc.sh with https://github.com/jemalloc/jemalloc/releases/download/4.1.0/jemalloc-4.1.0.tar.bz2 .

Notably we use a github URL (for version 4.5.0) in the `next` and `v2.4.x` branches.

**Comment by srh** [comment]
I've got org membership back.  Merged the fix (setting the URL to Github) to v2.3.x as of 960125b.  Thank you for the report.
