### ISSUE TITLE
Cluster of x86/s390x nodes not working

### ISSUE THREAD

**Issue by utzb** [rethinkdb/rethinkdb#6500]
It seems the connectivity between nodes of different endianness does not work (errors about strings being longer than 4096 bytes).
Searching revealed it probably was never a considered use case -- https://github.com/rethinkdb/rethinkdb/issues/169#issuecomment-12296738

However, with support for s390x (one of the last big endian systems standing) in 2.4, considering endianness for mixed architecture clusters might be a more relevant case.

**Comment by marshall007** [comment]
See also https://github.com/rethinkdb/rethinkdb/issues/5504#issuecomment-195584389. Officially supporting mixed architecture clusters has never really been high priority. It does work under some scenarios, but those are undocumented and untested. It's unlikely we'll get around to this anytime soon.

I'm gonna close this in favor of the existing #239 and #240, but thanks for the additional detail.
