### ISSUE TITLE
[BUG] ReQL command: epochTime

### ISSUE THREAD

**Issue by codermapuche** [rethinkdb/rethinkdb#6505]
I found a bug in epochTime command.

Simple test, open adminsitrator console and run this:

```
var timestamp = Date.now(),
    date1= r.epochTime(r.expr(timestamp).div(1000)),
    date2= r.time(date1.year(), date1.month(), date1.day(), 'Z');

r.expr({
  timestamp: timestamp,
  date2raw : date2,
  date2iso : date2.toISO8601(),
  date2epoch : date2.toEpochTime() // this epoch is 18/01/1970
})
```

Testing over windows 7 with last version of rethinkdb.

**Comment by srh** [comment]
There's no bug exhibited -- toEpochTime returns a value in seconds, and you forgot to multiply it by 1000 to get back to a number of milliseconds.
