### ISSUE TITLE
Latest version for Debian stretch?

### ISSUE THREAD

**Issue by Extarys** [rethinkdb/rethinkdb#6507]
If the next release is in the corner, skip this, pleaseeee.

But, will Stretch get a 2.3.6 deb package?

**Comment by srh** [comment]
I think I've figured out how to make a (good) 2.3.6 deb package for stretch.  It might be done today.

**Comment by srh** [comment]
See https://github.com/rethinkdb/rethinkdb/issues/6375#issuecomment-332742675

Closing this issue because it's redundant.

**Comment by Extarys** [comment]
Thx
