### ISSUE TITLE
Icon question (Public relations)

### ISSUE THREAD

**Issue by Extarys** [rethinkdb/rethinkdb#6508]
If I eventually make money with one of my projects, a big portion of it go to the environment and the other big chunk go to the open source.

I was wonderingif I can use a RethinkDB logo to say that my project's backend use rethinkdb and that a portion of the profit would go to them while saying that we are not affiliated.

I do this with a lot of the open source stuff I'll be using (the small one since I doubt for example that, for example, oracle, need the money)

Would be nice also to make a Powered by RethinkDB at the bottom of the page for swag.

Any svg mascot/logo I can use?

**Comment by srh** [comment]
Please see https://www.linuxfoundation.org/trademark-usage/ .

There's an SVG at (quickly googles) http://instantlogosearch.com/rethinkdb -- it seems acceptable.  I don't know where you'd get SVG Thinker mascots though.

**Comment by Extarys** [comment]
Thansk for the Linux Foundation link , I'll send them an email ;)
