### ISSUE TITLE
Third-party administration tools slight update

### ISSUE THREAD

**Issue by Extarys** [rethinkdb/rethinkdb#6512]
**Proposal**
- Add [ReQL Pro](http://reqlpro.com/) to [Third-party administration tools](https://www.rethinkdb.com/docs/third-party-admin-tools/)

**Comment by lsabi** [comment]
The ReQL Pro link is not available anymore.

Do you have a new one to share?

**Comment by Extarys** [comment]
@lsabi hehe that was 3+ years ago, sadly I don't use Rethinkdb much anymore and didn't look for tools in a while. Check if other tools in the link above suits your needs.
