### ISSUE TITLE
sample causes crash

### ISSUE THREAD

**Issue by sabey** [rethinkdb/rethinkdb#6521]
not sure what to make of this, entering this into the data explorer causes a crash
r.db("db").table("table").sample(10000000000000)

OS: ubuntu 17.04 64bit
Kernel: 4.10.0-30-generic
Version: rethinkdb 2.3.5

I couldn't find any log information to post, nothing was found in the rethinkdb_data/log_file

**Comment by srh** [comment]
Thank you for the report.  It was fixed in 2.3.6. See #6148
