### ISSUE TITLE
Web interface is not open

### ISSUE THREAD

**Issue by rbajaniya** [rethinkdb/rethinkdb#6522]
### I have flowing this steps. ###

1. Run exe 
![rethink-issue-window](https://user-images.githubusercontent.com/25998887/31530799-6b1994b6-b000-11e7-9335-c8319ad0e756.PNG)

2.  Open browser
![rethink-issue](https://user-images.githubusercontent.com/25998887/31530783-584ff8d4-b000-11e7-939e-3907d071f301.png)

**Comment by chrisfosterelli** [comment]
Duplicate of #6476?

**Comment by sagivf** [comment]
See my comment - https://github.com/rethinkdb/rethinkdb/issues/6476#issuecomment-336948777

**Comment by gabor-boros** [comment]
Closed in favor of #6476
