### ISSUE TITLE
possible optional arguments detection bug

### ISSUE THREAD

**Issue by naomik** [rethinkdb/rethinkdb#6523]
source issue from stackoverflow: https://stackoverflow.com/q/46751787/633183

Using the rethinkdb data explorer

    r.db('exports').table('requests') 

fetches

    {
      "options": {
        "params": {
          "foo": "bof"
          "sort": "desc",
          "page": 6
        }
      } ,
      "url": "https://url1.tld/"
    } 

    {
      "options": {
        "auth": {
          "type":  "basic" ,
          "pass":  "dnkykngcntry1" ,
          "user":  "diddy"
        } ,
        "params": {
          "foo": "bar"
          "sort": "asc",
          "page": 3
        }
      } ,
      "url": "https://url2.test/"
    } 

    ...

---

Now i'd like to do this
  
    r.db('exports').table('responses').insert(
      r.db('exports').table('requests').map(req => ({
        requestId: req('id'),
        requestedAt: r.now(),
        response: r.http(req('url'), req('options'))
      }))
    )

Getting this error:

    e: Expected 1 argument (not including options) but found 2.

---

If I call the [`r.http`](https://www.rethinkdb.com/api/javascript/http/) function with the values from one of the `request` documents, everything works fine

    // http command syntax
    // r.http(url[, options]) → value
    // r.http(url[, options]) → stream

    r.http("https://url1.tld/", {
        "params": {
          "foo": "bof"
          "sort": "desc",
          "page": 6
        }
      })
    // <response text>

Why doesn't it work with `req('url')` and `req('options')` in the loop then?

**Comment by naomik** [comment]
A [helpful user](https://stackoverflow.com/a/46778546/633183) was able to help me narrow the bug down to this

```
// These two are your req('url') and req('options') equivalents respectively
const url = r.expr('https://postman-echo.com/get');
const options = r.expr({ params: { foo: 1, bar: 2 } });

r.http(url, options);
```

**produces the following error**

> e: Expected 1 argument (not including options) but found 2.

**Comment by srh** [comment]
This behavior was an intentional language design decision.

You can think of the optargs parameters as a bunch of extra function parameters whose presence is known at compile time.  Some client drivers might not even express, to the user, their availability via a single object parameter.  On the server, the optarg parameters get their names checked against a list of available optarg parameters at "compile time" before the query gets evaluated.  They could hypothetically get checked by the JavaScript driver before it sends the query to the server.  (Similarly, an SQL client could syntax-check the SQL if it wanted to.)

Note that some functions can have arity 1 or 2, plus an optional optargs dictionary.  Some can have arity 1..N, plus an optional optargs dictionary.  Allowing the optargs dictionary to be dynamically computed would make evaluation logic more complicated, with more edge case to worry about.

**Comment by naomik** [comment]
@srh, I started using rethinkdb less than 24 hours ago. Can you dumb this down for me a little bit? I want to understand better. Is there a better way to accomplish what I'm trying to do?

That helpful user mentioned `optargs` too here

```js
const unexpr = expr => Object.assign({}, expr.optargs);
r.http(url, unexpr(options));
```

This is sort of a corner case for my app, so I don't plan on using `unexpr` in many scenarios – I'm just wondering if there's anything I'm overlooking

**Comment by lbguilherme** [comment]
The options argument *must* be a literal value that doesn't come directly from data in the database. But note, it is quite easy to work around:

You can't do this:

    const url = r.expr('https://postman-echo.com/get');
    const options = r.expr({ params: { foo: 1, bar: 2 } });

    r.http(url, options);

But you can do this:

    const url = r.expr('https://postman-echo.com/get');
    const options = r.expr({ params: { foo: 1, bar: 2 } });

    r.http(url, {params: options("params")});

**Comment by srh** [comment]
That unexpr stuff can't be used anywhere you didn't literally use `r.expr`, in which case you could just pass the dictionary directly, so it is pretty useless.

**Comment by naomik** [comment]
@srh 

>As I mentioned in the Github issue it's an intentional design decision. The optional arguments of a function have to be provided "statically," and different client drivers in different languages might not represent the optional arguments using a single dictionary. **@srh/[stackoverflow.com/a/46794414/633183](https://stackoverflow.com/a/46794414/633183)**

this explanation helps a lot – thanks Sam
