### ISSUE TITLE
Replace a nested object via shallow merge?

### ISSUE THREAD

**Issue by aleclarson** [rethinkdb/rethinkdb#6526]
I want to replace a nested object with another object.

Is this the simplest way to express that?
```js
r.expr({ foo: {bar: 1}, eck: true })
 .merge({ foo: null }, { foo: {zim: 1} })

// Expected output: { foo: {zim: 1}, eck: true }
```

**Comment by srh** [comment]
Most people who could answer that are on the Slack general or help channels, see http://slack.rethinkdb.com
