### ISSUE TITLE
Make failed

### ISSUE THREAD

**Issue by victionn** [rethinkdb/rethinkdb#6527]
Make keeps failing on the line "CC build/release/obj/clustering/table_contract/contract_metadata.o"

This can be seen here: https://image.viction.co.uk/ExRVA

**Comment by srh** [comment]
Thank you for this report.  Please tell us what platform this happened on, what version of GCC, and exactly what version of RethinkDB you were compiling.

**Comment by cloudle** [comment]
I had the same problem today on Ubuntu 17.10 (Google Cloud Compute Engine)..
I first try this one https://www.rethinkdb.com/docs/install/ubuntu/:
```
source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
sudo apt-get update
sudo apt-get install rethinkdb
```

it just blaming couldn't find the `rethinkdb` package:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package rethinkdb
```

After that, I also try to compile from source (my Ubuntu 17.10 installation is brand new - and clean), it say Make failed too.. (I forgot to take the screen shot of the error, but just want to confirm that it did happend..)

Thanks for help ;)

**Comment by srh** [comment]
Hey @cloudle.  To compile on artful run

```
apt install build-essential protobuf-compiler python \
    libprotobuf-dev libcurl4-openssl-dev libboost-all-dev \
    libncurses5-dev libjemalloc-dev wget m4 clang libssl-dev
./configure --allow-fetch CXX=clang++
```

and then make.
