### ISSUE TITLE
FAQ refers to AGPL

### ISSUE THREAD

**Issue by dpen2000** [rethinkdb/rethinkdb#6533]
https://rethinkdb.com/faq/ still refers to AGPL licence under "How is RethinkDB licensed?"

**Comment by srh** [comment]
Thanks for noticing that.  I've submitted a PR at https://github.com/rethinkdb/docs/pull/1220

If nobody objects in a day or two, I'll merge it... and ask somebody to update the website, I guess.

**Comment by dpen2000** [comment]
Website still needs updating @srh
