### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by bloodknight2010** [rethinkdb/rethinkdb#6538]
I can't run rethinkdb in linux system. I got the following error.

`rethinkdb: symbol lookup error: rethinkdb: undefined symbol:_ZNK6google8protobuf7Message11GetTypeNameEv
`
Pls help me.

**Comment by srh** [comment]
Please give information about what distribution and what RethinkDB release you're running, how you installed it, and how you're running it.

**Comment by bloodknight2010** [comment]
Before upgrade the linux system I can run rethinkdb very well, Today I upgrade the system can't run got the  error.Rethinkdb version is 2.3.5.I use sabayon linux.

**Comment by srh** [comment]
It looks like your upgrade replaced a dynamically linked library to a newer version, which doesn't have the right symbol.  You'll need to rebuild or reinstall the RethinkDB package or binary, I guess.

**Comment by bloodknight2010** [comment]
I rebuild and reinstall Now its work Thanks

**Comment by bloodknight2010** [comment]
I rebuild and reinstall Now its work Thanks
