### ISSUE TITLE
Inserting a Hashmap<String,Object> causes an error

### ISSUE THREAD

**Issue by tarzan212** [rethinkdb/rethinkdb#6543]
Trying to insert a hashmap using the r.table.insert command for the java driver return me an error stating : 
com.rethinkdb.gen.exc.ReqlQueryLogicError: Cannot convert STRING to SEQUENCE

`     
        String userJson = gson.toJson(user);
        MapObject hashmap = gson.fromJson(userJson,new TypeToken<MapObject>(){}.getType());
        HashMap<String,Object> retour = r.table(DbScheme.USERS_COLLECTION).insert(hashmap.toString()).run(connection);
`

Am I missing something or do all the inserts have to use the r.hashmap() method, because in the last case, it wouldn't allow easy changes in the date .

**Comment by lbguilherme** [comment]
You are trying to insert a string into the table. You can only insert objects in it.
I don't know the exact syntax for the Java driver, but explaining for the JavaScript driver so you can have an idea:

```js
r.table("test").insert({a: 1, b: 2}).run(conn) // ok
r.table("test").insert("foo").run(conn) // error
r.table("test").insert("{a: 1, b: 2}").run(conn) // error
r.table("test").insert(JSON.stringify({a: 1, b: 2})).run(conn) // error
```

**Comment by tarzan212** [comment]
Thank you, got it, it would have been easier if we could just pass a String as a parameter since the hashMap tend to mix items. Not that it's bad in any point but it's "prettier" to have it organized.

**Comment by srh** [comment]
Closing since it's answered.

You can also convert a string to an object in ReQL (on the server) using `r.json(myString)`.
