### ISSUE TITLE
.randomify() - make the table's documents random (read before assuming)

### ISSUE THREAD

**Issue by PassTheMayo** [rethinkdb/rethinkdb#6547]
I can probably know what you are gonna say from the title, but this has nothing to do with `.sample()` or `r.random()`. I recently came across a problem that I had no solution for. I own a large list of Discord bots, but I have no way to random-ify the results (on an hourly basis). For example, the documents in the table are random, but an hour later, they are in another random order. I think that this could be accomplished with a new chaining function, called `.randomify()`. This will make the order of the documents in the table random. For example, if I wanted to make the order of the documents in table `bots` random, I could use the following method: `r.table("bots").randomify().run(r.conn, ...)`. If I wanted to get the results of the new order, I could use this:
```js
r.table("bots").randomify().run(r.conn, function (error, results) {
    if (error) ...
    // do something with the new order of 'results'
});
```
This would be **very** helpful to me, and possibly other people too. Thanks!

**Comment by ChrisTalman** [comment]
I agree that it would be useful to have this as native functionality.

It seems like this is about sort order, so if this were a native feature, it could be incorporated into [`orderBy()`](https://www.rethinkdb.com/api/javascript/order_by/) with the existing [`random()`](https://rethinkdb.com/api/javascript/random/). In other words:
```JavaScript
r.table('table').orderBy(r.random())
```

In the meantime, if you have not done so already and are looking for a functional solution today, you could try to [`merge()`](https://rethinkdb.com/api/javascript/#merge) a `random()` property, and then `orderBy()` that.

**Comment by srh** [comment]
That's right -- the recommended way to do a random shuffle is that.

If you want the order to change once an hour, you could use `r.uuid` on a combination of the document ID and current hour to deterministically produce a random ordering that changes every hour (while running the query more than once).

**Comment by PassTheMayo** [comment]
@ChrisTalman 🤔 
![image](https://user-images.githubusercontent.com/16949253/32927715-d6c5da7a-cb13-11e7-9965-c8e3c64f0317.png)

**Comment by lbguilherme** [comment]
This is actually how you do that:

`r.table("test").merge(() => ({sorkingKey: r.random()})).orderBy("sortingKey").without("sortingKey")`

Or:

`r.table("test").sample(100000)`

**Comment by ChrisTalman** [comment]
Apologies @PassTheMayo, I provided that code as an example of how this functionality _could_ be implemented natively for ReQL. I pointed towards an actual functional solution in my last sentence, which @lbguilherme has provided.

**Comment by PassTheMayo** [comment]
@ChrisTalman No worries, I understood how you got that example anyways. I had already found another great solution, too!
```js
r.table("test").merge(() => ({ orderKey: r.random() })).orderBy("orderKey").without("orderKey")...
```

**Comment by PassTheMayo** [comment]
I'm just gonna close this up after 10 days of recent activity. This appears that there was no specified order to the results anyway. Cheers!
