### ISSUE TITLE
Allow recursive .inserts() with the Data Explorer

### ISSUE THREAD

**Issue by PassTheMayo** [rethinkdb/rethinkdb#6548]
Hello. I have a problem with the Data Explorer on the admin panel. If you use a recursive function, and repetitively try to insert/get data from a table, then the panel will only execute the last repeated call for the query. I have made the following example:
```js
for (var i = 0; i < 25; i++) {
    r.table("test")
        .insert({
            id: i + 1,
            name: "Johnny Test",
            age: Math.floor(Math.random() * (50 - 12)) + 12,
            gender: Math.round(Math.random()) >= 0.5 ? "Male" : "Female"
        });
}
```
Using the code as I showed above, it only gave me the following output:
```json
[
    {
        "age": 13,
        "gender": "Male",
        "id": 25,
        "name": "Johnny Test"
    }
]
```
As you can see, it only used the last repeated call for the query. I would expect for their to be 25 documents within this table, but there isn't. Just by seeing the ID, `25` would be the last call within our `for` loop. I don't know if this is a bug, but I expected a different result to arise. Thanks.

**Comment by srh** [comment]
The way the data explorer works is that it evaluates the JavaScript expression or statements you write inside it.  Then it takes whatever that evaluates to and calls `.run(...)` on it.

For example, the for loop `for (var i = 0; i < 25; i++) { i; }` evaluates to 24.

You could instead construct an array of documents with a for loop, and pass that array to .insert, when constructing the query you want to send to the server.

**Comment by PassTheMayo** [comment]
Ah, ok. Thanks!
