### ISSUE TITLE
Docs: libquadmath is a missing dependency on build pages, etc.

### ISSUE THREAD

**Issue by adamierymenko** [rethinkdb/rethinkdb#6558]
The quadmath library seems required but isn't listed as a build dependency. It may come with some distros but has to be installed on CentOS at least.

**Comment by srh** [comment]
I never experienced this error.  Are you getting this on next, with CentOS 7?

I previously got things building, on CentOS 7, having used the following commands after installing CentOS from the minimal iso:

```
yum install mg git
yum install epel-release
yum update
yum install openssl-devel libcurl-devel wget tar m4 \
    git-core boost-static m4 gcc-c++ npm ncurses-devel \
    which make ncurses-static zlib-devel zlib-static \
    protobuf-devel protobuf-static jemalloc-devel
yum install bzip2 patch
./configure --allow-fetch
make -j16
```

**Comment by srh** [comment]
It also works without the first three lines and without protobuf-devel, protobuf-static, jemalloc-devel, with --dynamic jemalloc on the configure line, as described at https://rethinkdb.com/docs/install/centos/

Grepping the source directory on my Mac revealed that the boost external dependency is what looks for the quadmath library.  If you don't have boost-static installed, building will fetch boost as an external resource, and using that version is what results in the quadmath dependency problem.

**Comment by srh** [comment]
I'll note it seems to build fine without `boost-static`, fetching boost, on 2.3.6.  That fetches Boost 1.56.0, whereas `next` fetches Boost 1.60.0.  Also I can confirm that building with `libquadmath-devel`, and without `boost-static`, works on both next and 2.3.6.

**Comment by srh** [comment]
Updated the rethinkdb/docs repo with https://github.com/rethinkdb/docs/commit/ec20804716657513b32a90e3d1fb60937f08e48d to add bzip2 and patch.  (I don't have access to the website.)  My current understanding with respect to libquadmath is that the instructions are correct as-is.

**Comment by gabor-boros** [comment]
Closing this, especially that the rethinkdb/docs is deployed now upon any change
