### ISSUE TITLE
What is happen now?

### ISSUE THREAD

**Issue by jorgeluisrezende** [rethinkdb/rethinkdb#6560]
i saw a few posts that say about the rethinkdb is shutting down, i just want to know about the future of the project, what is happen now?

**Comment by lbguilherme** [comment]
See https://rethinkdb.com/blog/rethinkdb-joins-linux-foundation/ and https://rethinkdb.com/blog/2.3.6-release/

**Comment by jorgeluisrezende** [comment]
thank you :smile:
