### ISSUE TITLE
A Discord server?

### ISSUE THREAD

**Issue by PassTheMayo** [rethinkdb/rethinkdb#6567]
I know this may seem off-topic, but this felt like the best place to ask since people aren't very active on the Slack or IRC. Is there a Discord server anywhere? It's like Slack, but called Discord and a lot more improved. If there isn't, could you please create one? Thanks!

**Comment by thinklinux** [comment]
What's the point of creating a Discord when you already said that people are not very active on Slack or IRC these days. It's going to be one more channel with no active people.

**Comment by srh** [comment]
We considered it a year or so ago, part of the reason might have been this was before the Linux Foundation stuff. But we didn't want to lose all the people in the Slack channel and start from scratch.

**Comment by PassTheMayo** [comment]
@srh How about both? I'd like to see a RethinkDB discord server, and some people think Slack is confusing (like me, maybe just because I'm used to Discord). You don't have to delete the slack, maybe just have both?

**Comment by srh** [comment]
If you make a Discord server for RethinkDB, I'd be happy to join.  There isn't anybody in charge of who gets to make what communications channels.  I hope you do -- I'd prefer it if the community infrastructure was more decentralized, instead of everything being officiously run by some central entity.

**Comment by PassTheMayo** [comment]
@srh Ok, I'm done creating it. Here's the invite link: https://discord.gg/ZeEq5TE

**Comment by PassTheMayo** [comment]
@srh I was just wondering, is it possible to add the Discord link above to the website? Since it's a community-made driven community, I would doubt it's possible, but it was still worth a shot. Maybe it could be added somewhere in the footer?

![image](https://user-images.githubusercontent.com/16949253/34137917-bf13b05e-e432-11e7-9b4f-441a7a70456c.png)

By the way, I'm gonna close this issue because it has been solved.

**Comment by srh** [comment]
I'm pretty sure one could be made. I don't have access to the website but I do have access to the repo... somebody else would push to the website. A link would probably belong wherever Slack is linked.

**Comment by PassTheMayo** [comment]
@srh Do you know who has access to the website?

**Comment by PassTheMayo** [comment]
Bump @srh

**Comment by srh** [comment]
[This page](https://rethinkdb.com/community/) would be the one to update.  I don't know who has access but I could ask...

**Comment by PassTheMayo** [comment]
@srh The only way that I see that I can reach you guys is Twitter, but I don't have a Twitter and I don't want to create one. Could you maybe ask around?

**Comment by srh** [comment]
I asked on Slack.

**Comment by PassTheMayo** [comment]
Ok just reply when they reply.

**Comment by Extarys** [comment]
Huh, just found out the Discord server - empty.. RIP :smile:

**Comment by chovy** [comment]
is the slack channel still active?

**Comment by chovy** [comment]
there's still 61 people in #rethinkdb on irc.freenode.net

**Comment by krull** [comment]
+1 #rethinkdb @freenode

/old grumpy hax0r wannabee :)

**Comment by jasonkhanlar** [comment]
Would someone please make and organize an unofficial communtiy RethinkDB discord server?

You could also promote the server on these discord server search/stats websites:
<https://www.carbonitex.net/discord/servers>
<https://disboard.org/>
<http://discord.me/>
<https://discord.services/>
<http://discordlist.me/>
<https://discordbots.org/servers>
<https://discordhub.com/>
<https://discordpromote.com/>
<https://discord-server.com/>
<https://discordservers.com/>
<https://discordsl.com/>
<https://old.reddit.com/r/discordservers/>
<https://topg.org/discord/>

**Comment by srh** [comment]
@jasonkhanlar There is one.  It was made by @PassTheMayo as a result of this thread and is pretty active.  I think this is a valid link: https://discordapp.com/channels/392399453904044043/392399454356897792
