### ISSUE TITLE
Can you provide a binary for the RPI 3b?

### ISSUE THREAD

**Issue by NefixEstrada** [rethinkdb/rethinkdb#6569]
Hey there! I'm in love with RethinkDB. I have an issue though. I want to run a small server on my Raspberry Pi 3b using Raspbian. 

The thing is that it takes a lot to compile and it freezes the RPI completely. I use it for other things so I can't let it down for a copule of days. 

I was wondering if you could provide a compiled binary for it. Thanks in advance!

**Comment by srh** [comment]
Maybe making an arm64 binary using qemu(?) is how this works.  I've been meaning to figure that out so I'll see what I can do.

**Comment by vielmetti** [comment]
#5265 has some previous discussion.

**Comment by NefixEstrada** [comment]
I actually used ArchLinux ARM, they already provide the RethinkDB package compiled @vielmetti

**Comment by vielmetti** [comment]
Thanks @NefixEstrada - can we close this issue out, or are there still open issues?

**Comment by NefixEstrada** [comment]
Yeah, the issue can be closed, though it would be nice to add a package compiled for ARM
