### ISSUE TITLE
Lost ton of data due to Error of Missing Branch

### ISSUE THREAD

**Issue by YaBoyWonder** [rethinkdb/rethinkdb#6571]
error: Ignoring missing branch `1ba1c655-d81c-41a1-a9ac-ac4aad76efe5`. This probably means that there is a bug in RethinkDB. 

The thing is that I did not import or implement any new branches or tables, so the moment this came I lost all the data in one of my major db tables.

**Comment by PassTheMayo** [comment]
"Ignoring missing branch"

Using some common sense, it kinda looks like the table file was moved, but still in the RethinkDB registry for the tables that exist. Are you sure the table file didn't move?

**Comment by srh** [comment]
A "branch" refers to a node in the history of a table's configuration (what shards/servers it's allotted to).

What sort of cluster were you running the table on?  Did anything happen before this?  Servers disconnected or going down?  Could you share the log files?
