### ISSUE TITLE
How should I donate to RethinkDB?

### ISSUE THREAD

**Issue by lbguilherme** [rethinkdb/rethinkdb#6579]
I have a small company which uses RethinkDB for most projects and I think it is great. It does have some issues here and there which would make it even better, but it has been good enough for most of our needs. Thanks for all the hard work so far.

I understand it is hard to keep a project like this going with a source of money or a company behind it. And I feel I have the responsibility to help however I can.

It's not much but I want to make a monthly donation in the order of about $50 (yes, I know it is very few, but I hope I'm not alone. And I can't put more than that right now.). I couldn't find a donate link on the site and given the current governance I don't even know if it is possible at all. Something like https://salt.bountysource.com/ would be excellent.

Hopefully others would join this.

How should I donate to RethinkDB?

**Comment by sagivf** [comment]
@lbguilherme  You are not alone :)

https://www.rethinkdb.com/contribute/

**Comment by wanjochan** [comment]
when I tried to donate at https://funding.communitybridge.org/projects/rethinkdb
it always failed to add a card (pretty sure my card is uing...), any admin to check?

**Comment by gabor-boros** [comment]
http://donate.rethinkdb.com/
