### ISSUE TITLE
[Proposal] Developer docs.

### ISSUE THREAD

**Issue by DannehSC** [rethinkdb/rethinkdb#6586]
I know, this might sound like a stupid idea. But as a driver developer myself, I feel like Rethinkdb could use the docs so developers would have an idea of how to proceed. Like, some of the info could include:

Example: get

Example of the raw encoded query;
Detailed explanation of how the internals of how it works;
Other things.

It feels like a lot of writing a driver is guessing and trying to learn how other drivers do it. But it can be annoying trying to learn another language/environment to understand how you can incorporate what other drivers do into your own driver. So perhaps developer oriented documentation would be best for everyone.

**Comment by AtnNn** [comment]
@DannehSC There is some useful information on the retihnkdb-dev mailing list:

https://groups.google.com/forum/#!forum/rethinkdb-dev

The driver development docs are incomplete, but worth a read if you haven't seen them yet:

https://rethinkdb.com/docs/writing-drivers/

I don't know how up-to-date it is, but this tool is very useful:

https://github.com/neumino/rethinkdb-driver-development

**Comment by srh** [comment]
Ahhh, if I knew these links we might not have this issue. Sorry for being so useless @DannehSC.

**Comment by DannehSC** [comment]
Hey, you were helpful Srh, I just didn't know about the link in google groups nor the github driver dev repo.

**Comment by marioanticoli** [comment]
@DannehSC do you still feel this is an issue or can it be closed?
