### ISSUE TITLE
Connecting to RethinkDb on a Windows Server 2012

### ISSUE THREAD

**Issue by narendravenkata** [rethinkdb/rethinkdb#6589]
Hi I am using RethinkDb in my C#.NET application,I have my backend application running on app_server and i have rethinkdb installed and running on my db_server. can anyone let me know which inbound rules i should add on the firewall of db_server. When I run my application I am having error "System.Net.Sockets.SocketException
  Message=No connection could be made because the target machine actively refused it 10.1.1.51:28015"

when I run rethinkdb on my db_server it actually uses localhost i.e, 127.0.0.1. I am not sure how to connect to the database from another server.

**Comment by srh** [comment]
If you're binding to 127.0.0.1 on your db_server, you won't be able to connect from the outside.  That's the default behavior.  You'll want to start RethinkDB with `--bind all` if you want to connect to it from other servers.

**Comment by biapar** [comment]
Check the firewall rules, too.
