### ISSUE TITLE
make build-deb complains about node missing on next

### ISSUE THREAD

**Issue by srh** [rethinkdb/rethinkdb#6595]
If you run `make build-deb DEB_RELEASE=...` you'll get a complaint that node is missing.

This is almost certainly related to my recent changes making web_assets.cc precompiled, so that Node isn't an immediate build dependency.

Only affects the `next` branch (not 2.4.x).

**Comment by gabor-boros** [comment]
@srh since 2.5 will be created from 2.4 (if I understand correctly) upon a breaking change, this issue is not valid anymore as the `next` branch became the snapshot of that work done there and "abandoned", right?

**Comment by srh** [comment]
Right.  We'll have to avoid this issue if/when cherry-picking from next.  Closing.
