### ISSUE TITLE
Unsaved Data

### ISSUE THREAD

**Issue by YaBoyWonder** [rethinkdb/rethinkdb#6598]
I am recieving this error when some users are saving data, 

`Error: write ECANCELED
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)`

Does this mean the disk space is getting to low or does it have to do something with my tables?

**Comment by lbguilherme** [comment]
ECANCELED means that something canceled the network operation on the sending side (i.e. the driver). Doesn't look like anything related to the database itself. It's either a network issue or a driver issue. Please describe what are you using and how you are getting this error. More info.

**Comment by srh** [comment]
Probably not a RethinkDB bug. Wild guess: this happened on OS X.
