### ISSUE TITLE
Website update: Upcoming events and meetups

### ISSUE THREAD

**Issue by Extarys** [rethinkdb/rethinkdb#6599]
Someone should update the section 'Website update: Upcoming events and meetups' at https://rethinkdb.com/community/.
Clearly outdated hehe

Also, should update the section 'Latest news' on the index page when releasing. 2016 looks old and people might think the project is dead (no update = dead)

I could do it but the website doesn't seem to be on github.

**Comment by srh** [comment]
Thanks for mentioning that.  The slack invite page at slack.rethinkdb.com isn't working.  The channel's still there, but now no new people can join.  The last new person joined #general last Friday.

**Comment by techdragon** [comment]
I think this highlights the need to get the website into a more public control state. Community updates of a website via PR are an easy way for people to contribute activity that ensures newcomers are aware this project is alive and worth using.

**Comment by lavvy** [comment]
Yes. +1000 .
It's a great way to keep the freshness.

**Comment by Extarys** [comment]
How should we proceed to replicate the website to a repo? Who have the power to do this?

**Comment by thelinuxlich** [comment]
I would like to know that too

**Comment by gabor-boros** [comment]
The info is already removed as not relevant anymore
