### ISSUE TITLE
Backup command causes box memory consumption spike, swapping

### ISSUE THREAD

**Issue by GeoffreyPlitt** [rethinkdb/rethinkdb#6601]
We use ReThinkDB provided by Compose.io (3 VM nodes), and they do backups every hour through the  ```dump``` mechanism.

We see a huge spike in memory usage during the backups-- in fact it's so high that we enter swapping which wreaks havoc. Attached is a graph of 3 days of memory usage, and those 3 big spikes are backup jobs, not normal user activity or background processing we're intentionally doing, just backup jobs:
![screenshot 2018-01-22 15 58 07](https://user-images.githubusercontent.com/382821/35250752-208a7bfe-ff8d-11e7-984e-da6a84b7316a.png)

The docs at https://rethinkdb.com/docs/backup/ say: "Since the backup process uses client drivers, it takes advantage of RethinkDB’s concurrency. While it will use some cluster resources, it won’t lock out any clients, and it can be safely run on a live cluster."

We suspect the jump in RAM usage happens because every row fetched is run through cache-updating, causing the whole cache to cycle. But it's only a guess. maybe the backup mechanism need to avoid cache? Maybe it has a memory leak?

Is there an alternate backup technique you'd recommend, such as backing up purely by reading the disk files the server uses, to avoid the driver (and memory resources) entirely?

Happy to provide more info if needed.

**Comment by srh** [comment]
Backing up live disk files won't work unless your file system supports snapshots.  Using a snapshotting file system and copying snapshots of the disk files might be a good idea, for what it's worth.

Another option would be to pass a command line argument to the dump script that makes it run more slowly, to avoid eating temporary server resources.  If there isn't one available already, you could implement it yourself and (please) submit it upstream.  Maybe something that looks like `--rate-limit 3M` meaning 3 megabytes per second.   It's just Python code using the RethinkDB driver.

The implementation is at https://github.com/rethinkdb/rethinkdb/blob/next/drivers/python/rethinkdb/_dump.py and https://github.com/rethinkdb/rethinkdb/blob/next/drivers/python/rethinkdb/_export.py

**Comment by srh** [comment]
On a more general note it would be neat if you could annotate a query as a "one-time" query to tell the cache none of the data it loads off disk should be considered "hot".

**Comment by GeoffreyPlitt** [comment]
Gotcha, thanks!

**Comment by GeoffreyPlitt** [comment]
Closing in favor of #6608
