### ISSUE TITLE
could you please publish table that RethinkDB on Windows compare with linux, macos or others?

### ISSUE THREAD

**Issue by anlexN** [rethinkdb/rethinkdb#6605]

**Comment by lbguilherme** [comment]
What do you mean?

**Comment by anlexN** [comment]
their function diffrences. windows have and windows have no one. 
because you say:
![image](https://user-images.githubusercontent.com/8686739/35478365-568b3fe4-0416-11e8-880c-3980245e854d.png)

**Comment by lbguilherme** [comment]
not much tuning is was not as much optimized for speed. all features are there. It is not slow, just not as fast.

**Comment by biapar** [comment]
Which is the better s.o. for rethinkDB?

**Comment by srh** [comment]
I don't know what an s.o. is.

**Comment by biapar** [comment]
S.o. = system operative

**Comment by srh** [comment]
Linux for sure.

**Comment by srh** [comment]
Going to close. The answer is, no table, because there are no differences in feature set. Correct me if I'm wrong (in some very small detail).
