### ISSUE TITLE
Failed install on 17.10

### ISSUE THREAD

**Issue by the-noob** [rethinkdb/rethinkdb#6609]
Managed to fix this but adding the info here might help others hitting the same issue.

For me both the binaries and compiling failed on 17.10 (artful).
The [binaries](http://download.rethinkdb.com/apt/dists/) don't have a build for 17.10 but that can be 'fixed' by editing the generated `/etc/apt/sources.list.d/rethinkdb.list` with
```
deb http://download.rethinkdb.com/apt xenial main
```
This will still fail installation as it depends on `libprotobuf9v5` but only `libprotobuf10` is available on 17.10.
Can be also 'fixed' by manually downloading and installing [libprotobuf9v5](https://packages.ubuntu.com/xenial/amd64/libprotobuf9v5/download) from a mirror.

Now `sudo apt-get install rethinkdb` should work ok.

**Comment by roblav96** [comment]
@the-noob You da best =]

**Comment by I-Dont-Remember** [comment]
I also am running 17.10, I was able to install without running into `libprotobuf9v5` vs `10` issues by using `zesty` instead of `xenial`, they must have switched dependency between the two.

**Comment by zafhiel** [comment]
guys you tried with docker? https://hub.docker.com/_/rethinkdb/

**Comment by gabor-boros** [comment]
As of Ubuntu 17.10 reached end of life, I'm closing this issue
