### ISSUE TITLE
Error compiling src/client_protocol/server.cc under raspbian stretch lite.

### ISSUE THREAD

**Issue by jude** [rethinkdb/rethinkdb#6611]
I'm running into the error below trying to build rethinkdb on raspian stretch lite

The configure line I used was ` ./configure --with-system-malloc --allow-fetch`

I error I'm seeing is below

```
root@raspberrypi:~/rethinkdb/rethinkdb-2.3.6# make ALLOW_WARNINGS=1
    [1/286] CC build/release_system/obj/client_protocol/server.o
src/client_protocol/server.cc: In member function ‘size_t http_conn_cache_t::sha_hasher_t::operator()
   (const conn_key_t&) const’:
src/client_protocol/server.cc:177:16: error: aggregate ‘EVP_MD_CTX c’ has incomplete type and cannot be defined
     EVP_MD_CTX c;
                ^
src/build.mk:390: recipe for target 'build/release_system/obj/client_protocol/server.o' failed
make[1]: *** [build/release_system/obj/client_protocol/server.o] Error 1
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2
```

This error looks very similar to the error seen at https://github.com/rethinkdb/rethinkdb/pull/6159#issuecomment-307590215, and the response to that comment mentions trying --fetch options.  

Could you explain what --fetch options to try in a little more detail ?

**Comment by srh** [comment]
You should checkout the branch v2.3.x and build that. It has a fix which avoids this deprecated or unsupported interface.

**Comment by jude** [comment]
I didn't try checking out the 2.3.x branch, but what ended up working for me is uninstalling openssl on the pi, and then using './configure --with-system-malloc --allow-fetch CXX=clang++'.  It looks like this fetched openssl v1.0.t which doesn't have the error above, and which was good enough for now.  

Without the CXX=clang++, the build would get past the error above but then segfault near the end of build compiling the v8 code.  The clang++ build is also a lot faster than the g++ build, like 4x faster.

I will try building again with the stock openssl installed once 2.3.7 or 2.4.0 is released.   It would also be nice if there was an official Raspbian package !

**Comment by lavvy** [comment]
Yeah most apps now maintain and support arm version officially . it encourages more enthusiasts .

**Comment by ultimatecoder** [comment]
Sorry for commenting little off-topic.

@jude I am trying to build the RethinkDB under Rasbian os and R-PI-3 hardware from past few days. It is taking way too many hours. Never ended successfully. Do you know any way to get a pre-built package of RethinkDb for Raspbian hardware? Is it normal to take this much out of time to build the RethinkDB?

@srh Can't your team try to make package supporting R-PI-3? Thanks

**Comment by srh** [comment]
@ultimatecoder My team is you.

**Comment by ultimatecoder** [comment]
@srh Thanks for your reply. I will need assistance from an experienced fellow because I am too novice for packaging any software. At present, I am trying to make a successful build in R-PI-3 from past few days still unsuccessful. Will get some motivation once I am successful to make a source build first. Have a great day!

**Comment by tweeva** [comment]
If you still need it, I've built a rethinkdb-2.3.6 .deb package that seems to work on a RPI3B.
![image](https://user-images.githubusercontent.com/4503359/54475237-4b718f00-47ef-11e9-9be1-fafd2176d329.png)

**Comment by ultimatecoder** [comment]
@tweeva  I don't need it now. Thanks!
