### ISSUE TITLE
how to update value in object in array in object in array?

### ISSUE THREAD

**Issue by vectorselector** [rethinkdb/rethinkdb#6613]
if I have the following data structure:
```
{
  id:1234, 
  frames: [
    {frameId:1, item1:qq, item2:[ {itemId:1, key2:green}, {itemId:2, key2:purple} ] }, 
    {frameId:2, item1:yy, item2:[ {itemId:1, key2:orange}, {itemId:2, key2:yellow} ] }
  ]
}
```

and I want to update key2 of the array element where itemId is 2 in the frame where frameId =2

how on earth do I achieve this? I've literally spent a week re-reading the docs constantly and trying various combinations of:

`.update ({:frames => {r.branch({:frameId => 1})}[:item2] {r.branch({:itemId => 2})}[:key2] => newvalue})
`
or
```
      .update {
          r.branch({:frameId => 1}) 
          r.branch({:itemId => 2}
            {:key2 => newvalue}, {:non_atomic => true, :return_changes => true}
          )
      }
```

or even
```
      .update { |item|
          item.filter({:frameId => 1})
          .filter({:itemId => 2})
          .merge({:key2 => newvalue})
```

I have tried r.branching inside an update statement to 2 levels, but all I ever get is the field-value appended as in

```
{
  id:1234, 
  frames: [
    {frameId:1, item1:qq, item2:[ {itemId:1, key2:green}, {itemId:2, key2:purple} ] }, 
    {frameId:2, item1:yy, item2:[ {itemId:1, key2:orange}, {itemId:2, key2:yellow} ] }
  ],
  newField: newValue
}
```

I'm kind of going insane over this...well, more than usual

**Comment by vectorselector** [comment]
what i want is:

{
  id:1234, 
  frames: [
    {frameId:1, item1:qq, item2:[ {itemId:1, key2:green}, {itemId:2, key2:purple} ] }, 
    {frameId:2, item1:yy, item2:[ {itemId:1, key2:orange}, {itemId:2, key2:newvalue} ] }
  ]
}

**Comment by lbguilherme** [comment]
Ref: https://github.com/cubos/rethinkdb.cr/issues/13
