### ISSUE TITLE
Indexing nth document

### ISSUE THREAD

**Issue by enricobachiorrini** [rethinkdb/rethinkdb#6617]
Is there any way to index the nth document in a table?
For example, let's say I want to read the 3rd document only and print its values.
Thanks!

**Comment by srh** [comment]
Use .nth?

**Comment by enricobachiorrini** [comment]
This is my table "examples":
{
       'Name': 'John',
       'Team': 'Blue',
       'Score': '3'
   }
  {
       'Name': 'Mary',
       'Team': 'Red',
       'Score': '8'
   }
   {
       'Name': 'James',
       'Team': 'Yellow',
       'Score': '5'
   }

If I run:
```
cursor = r.table('examples').run()
for document in cursor:
    print(document)
```
This prints:
```
{'Name': 'James', 'Score': '5', 'Team': 'Yellow', 'id': '1f08d39e-08aa-493f-a324-03f4d4b9d489'}
{'Name': 'John', 'Score': '3', 'Team': 'Blue', 'id': 'd29beabe-5774-4c3f-af3f-2a24e198c68b'}
{'Name': 'Mary', 'Score': '8', 'Team': 'Red', 'id': 'db2a3aed-3fd1-4080-bb8c-7fb38a93dab6'}
```
Which is ok.

Then I would like to print the Name, Score and Team of the FIRST record only.
If I run:
```
cursor = r.db('test').table('examples').nth(0).run()
for document in cursor:
    print(document)
```
The result is:
```
Name
Score
Team
id
```

Finally, if I run:
```
cursor = r.db('test').table('examples').nth(0).run()
for document in cursor:
    print(document)
    print(document['Name'])
    print(document['Score'])
    print(document['Team'])
```
I get this as a result:
```
Name
Traceback (most recent call last):
  File "/Users/enrico/Desktop/untitled.py", line 12, in <module>
    print(document['Name'])
TypeError: string indices must be integers
```

I don't know what am I missing, I would like the script to print:
```
James
5
Yellow
```

Thanks in advance

**Comment by srh** [comment]
A query that uses nth doesn't return a cursor.  It returns a value.  You're iterating over the object keys.

**Comment by enricobachiorrini** [comment]
Thank you @srh.
What should I code to get this result? 
```
James
5
Yellow
```
I want the cursor to pick the first document, read all the keys, effectuate some operations with these keys, then switch to the second document and so on.

**Comment by srh** [comment]
You already have an example that iterates through the documents, the rest is a matter of Python programming.

**Comment by PassTheMayo** [comment]
@srh I think he wants to get the nth document on RethinkDB's side without Python having to iterate through them.

**Comment by PassTheMayo** [comment]
@enricobachiorrini There is no specific order for the documents returned from RDB, so don't try to get documents based on order. Use a proper unique ID system  and just use `.get()`.

**Comment by srh** [comment]
Gonna close as an old question.
