### ISSUE TITLE
Require is not defined Reference error

### ISSUE THREAD

**Issue by hunnain** [rethinkdb/rethinkdb#6620]
Hi Rethinkdb i have install rethinkdb in ubuntu 17.10 ,
iam using javascript i have install all dependencies of rethinkdb in my app and it is also coming in my node modules but when i write r = require('rethinkdb');
so the error come require is not defined reference error what may i do now i didnt using any server siding language. so please help me how i resolve this error.please please help me 

How can i attach rethinkdb with react.js

![screenshot from 2018-02-19 13-29-53](https://user-images.githubusercontent.com/24963356/36368499-602aab06-1579-11e8-91d6-027590653fe7.png)
![screenshot from 2018-02-19 13-31-11](https://user-images.githubusercontent.com/24963356/36368500-60589c82-1579-11e8-9833-1c7858bcd2da.png)
![screenshot from 2018-02-19 13-32-09](https://user-images.githubusercontent.com/24963356/36368502-60834b26-1579-11e8-9850-b59ec201042d.png)

**Comment by Hoishin** [comment]
I think it is rather a problem with React or Webpack.

**Comment by lbguilherme** [comment]
This package is for Node, not for the browser. You should never expose a database directly to browser access.

**Comment by hunnain** [comment]
Hi ibguiherme, 
Let suppose i want to use react so how can i use rethinkdb in react.js

**Comment by lbguilherme** [comment]
You create an API server with node (or any other language) to run on a remote server. Use express or something to create a REST api. And call that API from the browser.

**Comment by hunnain** [comment]
i didnt want to use node and express i want to use rethinkdb without node nad express only using react.js

**Comment by lbguilherme** [comment]
Ah, then just run it with electron and it will work. You were running with chrome..

**Comment by hunnain** [comment]
So i want to add in on Electron.js file.
So there is no possible way to use with react directly

**Comment by lbguilherme** [comment]
You can't use it in a browser.

**Comment by hunnain** [comment]
I have recently read  this person tutorial and they have attach rethink with react

https://github.com/mikemintz/react-rethinkdb
