### ISSUE TITLE
Unhandled rejection Error: Failed to construct 'WebSocket': The URL 'ws://localhost:28015undefined' is invalid.

### ISSUE THREAD

**Issue by hunnain** [rethinkdb/rethinkdb#6621]
Hi Rethinkdb,
Iam new in Rethinkdb and iam using rethinkdb with react.js i have install rethinkdb react driver from node "react-rethinkdb" then i want to connect with rethinkdb but iam getting error in connecting rethinkdb in console The error is 

Unhandled rejection Error: Failed to construct 'WebSocket': The URL 'ws://localhost:8080undefined' is invalid.
    at Socket.connect (http://localhost:3000/static/js/bundle.js:37968:11)
    at Object.connect (http://localhost:3000/static/js/bundle.js:38061:11)
    at new TcpConnection (http://localhost:3000/static/js/bundle.js:37591:29)
    at http://localhost:3000/static/js/bundle.js:37886:19
    at http://localhost:3000/static/js/bundle.js:37901:13
    at tryCatcher (http://localhost:3000/static/js/bundle.js:32857:24)
    at Promise._resolveFromResolver (http://localhost:3000/static/js/bundle.js:32551:32)
    at new Promise (http://localhost:3000/static/js/bundle.js:32141:38)
    at http://localhost:3000/static/js/bundle.js:37881:11
    at http://localhost:3000/static/js/bundle.js:38758:17
    at promisified (http://localhost:3000/static/js/bundle.js:36841:17)
    at connect (http://localhost:3000/static/js/bundle.js:32033:91)
    at http://localhost:3000/static/js/bundle.js:29572:15

![screenshot from 2018-02-20 14-53-21](https://user-images.githubusercontent.com/24963356/36417520-05afb9ac-164e-11e8-89da-0c10d18c016c.png)

![screenshot from 2018-02-20 14-44-16](https://user-images.githubusercontent.com/24963356/36417354-8915a1fe-164d-11e8-987a-1866491cccaf.png)
![screenshot from 2018-02-20 14-46-02](https://user-images.githubusercontent.com/24963356/36417361-8c9207a0-164d-11e8-93b6-3ae86964c884.png)

Please help me

**Comment by veracus** [comment]
`ws://localhost:8080undefined`

There probably shouldn't be an `undefined` there.

**Comment by sagivf** [comment]
I am not familiar with "react-rethinkdb" but I think your connecting to PORT 8080 which is used by the "admin-ui".

**Comment by hunnain** [comment]
Hi sagivf my rethinkdb server runing on port 8080 and i have also write port in react sagi help me i want to make a project on rethinkdb.

**Comment by hunnain** [comment]
Sagi i have also add 28015 port but same error coming.

**Comment by sagivf** [comment]
@hunnain I've looked into it. That port is your server socket port and your also missing the path (that's the undefined).

![image](https://user-images.githubusercontent.com/1857466/36666616-de5a4bba-1af3-11e8-82f6-382ab0da5e71.png)

Dig deeper into https://github.com/mikemintz/react-rethinkdb/tree/master/examples/tutorial
I think issues belong there.

Hope this help, good luck!

**Comment by hunnain** [comment]
Thanks Sagi
