### ISSUE TITLE
Python driver release? 

### ISSUE THREAD

**Issue by gcmurphy** [rethinkdb/rethinkdb#6627]
The last package available in pypi is https://pypi.python.org/pypi/rethinkdb/2.3.0.post6 (2016-08-29)

Would it possible to get a new release that includes some of the more recent changes to the driver? 

I'm specifically interested in [these](https://github.com/rethinkdb/rethinkdb/commit/dda2fea6326182350c7e845378efc6749c49ec13) asyncio changes.

**Comment by FilipeRamalho** [comment]
@Stylite 2.4.0 isn’t yet released, but I guess that pypi will get the newest right away as it is the most outdated, for now you can build from source

**Comment by Stylite** [comment]
@FilipeRamalho I'm waiting for the 2.4 driver on pypi as I would rather not have users build from source.

**Comment by markharley** [comment]
While we're waiting on the 2.4 release candidate, can we have the 2.3.6 drivers on PyPI? I need the same changes as referred to be @gcmurphy and would rather not have to bundle the driver along with my app

**Comment by dustyfresh** [comment]
If you find yourself looking at this issue be sure to check out this spectrum thread:

[https://spectrum.chat/rethinkdb/news/python-client-release~9f6f4a78-aac5-4e6d-8e27-574ba9fc4034](https://spectrum.chat/rethinkdb/news/python-client-release~9f6f4a78-aac5-4e6d-8e27-574ba9fc4034)

It seems that Pypi installs are currently busted.

**Comment by sontek** [comment]
Current version of RethinkDB driver on pypi is 2.4.1 so I believe this has been taken care of?

**Comment by gcmurphy** [comment]
Looks like this can be closed now.
