### ISSUE TITLE
Geolocation insert with Java API

### ISSUE THREAD

**Issue by tarzan212** [rethinkdb/rethinkdb#6628]
Hi all, I am using the Java driver and trying to insert a rethinkdb Point : 
` Point geoloc = RethinkDB.r.point(Float.parseFloat(message.getLocation().split(",")[0])
                    , Float.parseFloat(message.getLocation().split(",")[1]));`

I get the following result : 

> ,"geolocation":{"termType":"POINT","args":[{"termType":"DATUM","args":[],"optargs":{}},{"termType":"DATUM","args":[],"optargs":{}}],"optargs":{}},

I am not sure wether the java method call is incorectly done or if this is an API issue...

**Comment by adriantodt** [comment]
You're not inserting a RethinkDB point, just building a ReQL query and not running it with a connection. I'd recommend learning the basics of RethinkDB and ReQL. Open a issue on the Java driver repository (https://github.com/rethinkdb/rethinkdb-java) if you found any more problems. (This issue can be closed and locked)
