### ISSUE TITLE
Authenticate with rethinkdb

### ISSUE THREAD

**Issue by hunnain** [rethinkdb/rethinkdb#6629]
Hi Everyone,
Iam working in react,express and rethinkdb and i want to authenticate user email and password so how can i authenticate user email and password in rethinkdb please help me

**Comment by sagivf** [comment]
Authenticating your app is up to you on your server, you can use saas products like "Amazon Cognito" or your own custom authentication.

If you want to authenticate queries from you server to your rethink database have a look at - 
https://www.rethinkdb.com/docs/permissions-and-accounts/

**Comment by nigel-dewar** [comment]
@hunnain , @sagivf  is right, auth has nothing to do with rethinkdb.

**Comment by nigel-dewar** [comment]
I can provide a sample of how to do Auth with react or angular, express, rethinkdb, but Id rather put this as a tutorial so it can be re-found and this question not keep coming up. @srh , is there a way I can put up (up to date) tutorials on the official website

**Comment by v3ss0n** [comment]
It seems that none of the contributor have current access to Official website which is  under control by LinuxFoundation (proprietary?) and there is no license i think .

**Comment by nigel-dewar** [comment]
@v3ss0n okay dokay. What shall we do then?  Shall we setup a fresh site for now, or hit up whomever controls this for access

**Comment by v3ss0n** [comment]
i am asking srh if a new site is ok .

**Comment by srh** [comment]
Closing as a question. I don't think I (a random user) can invite people to the Slack.
