### ISSUE TITLE
Documentation about ReQL built format

### ISSUE THREAD

**Issue by jviotti** [rethinkdb/rethinkdb#6630]
Hey there! I'm playing with RethinkDB sources, and I noticed that queries get compiled to something like:

```js
[
  1,
  [
    15,
    [
      [
        14,
        [
          "test"
        ]
      ],
      "foo"
    ]
  ]
]
```

When running `.build()` on a query using the JS driver.

Do we have documentation about this built format, as I'd love to learn more about it? I've been studying https://github.com/rethinkdb/rethinkdb/blob/next/drivers/javascript/ast.coffee with not much success, and I think a higher level set of docs could help me a lot.

**Comment by srh** [comment]
We do, I'm on my phone so I can't find all of it, but there's a file in the source repo called ql2.proto which is a place to start. The protocol used to use protobufs and got converted to this weird JSON serialization because that was faster for many languages.

There is also https://rethinkdb.com/docs/writing-drivers/

**Comment by bchavez** [comment]
The [**C# driver**](https://github.com/bchavez/RethinkDb.Driver/tree/master/Source/RethinkDb.Driver) and [**Java driver**](https://github.com/rethinkdb/rethinkdb/tree/next/drivers/java/src/main/java/com/rethinkdb) are also great reference sources too. Both pass the full-battery ReQL test harness so it's all good.

Also, there is some scant documentation on how the C# driver is put together here:
https://github.com/bchavez/RethinkDb.Driver/wiki

![chrome_1234](https://user-images.githubusercontent.com/478118/36711407-01d6b544-1b38-11e8-968a-ad0c9490bcaf.png)

**Comment by jviotti** [comment]
Thanks a lot guys, this is really useful! I'll close the ticket as resolved :)
