### ISSUE TITLE
how can i retrive specific data from rethinkdb

### ISSUE THREAD

**Issue by hunnain** [rethinkdb/rethinkdb#6631]
hi everyone,
i want to retrive specif data like adminEmail and adminPassword and save into a variable like
`r.db('billing').table('billingadmin').run(connection, function(err, cursor) {
        if (err) throw err;
        cursor.toArray(function(err, result) {
            if (err) throw err;
            console.log(JSON.stringify(result, null, 2));
            var data = result
        console.log('Data',JSON.stringify(data))
        console.log('Data',console.log('Data',JSON.stringify(data.adminEmail)))
console.log('Data',JSON.stringify(data.adminPassword))
var myadminemail= JSON.stringify(data.adminEmail)
var myadminpassword = JSON.stringify(data.adminPassword)
        });`
im getting whole document i want only adminEmail and admin Password

if i wrong so please guide me 
please help me 
![ii](https://user-images.githubusercontent.com/24963356/36797923-1356dc38-1ccb-11e8-8eb7-65ba153eb0b6.png)

**Comment by srh** [comment]
Use pluck.

**Comment by hunnain** [comment]
What is pluck

**Comment by cur3n4** [comment]
This should help: https://rethinkdb.com/api/javascript/pluck/
