### ISSUE TITLE
Is there a way to protect sensitive data on RethinkDB on a server you don't trust?

### ISSUE THREAD

**Issue by adrianharabula** [rethinkdb/rethinkdb#6633]
Suppose there is a multi user web app which uses RethinkDB as a database.

Each user keeps personal data that should not be viewed/stored in plain-text.

How data/encryption should be handled in RethinkDB?

**Comment by marshall007** [comment]
RethinkDB supports network encryption, but not encryption of the data at rest. If you need to store encrypted data in a document, you would need to implement that within your application(s).

**Comment by Extarys** [comment]
Performance-wise, I believe encryption-at-rest should eventually be included. Decrypting could add a huge overhead if implemented inside the application. Also it would not support searching encrypted data as opposed to encryption-at-rest I suppose.

Of course it all depends on how it is implemented no matter if it's on the server or the app.

**Comment by srh** [comment]
You could run it on an encrypted volume.

**Comment by Extarys** [comment]
True, but it would require slightly more human interaction on server restart for example that a built-in encryption.

I'll find a way to manage, thanks! :)
