### ISSUE TITLE
Expected type TABLE but found TABLE_SLICE: SELECTION ON table (GROUP + ORDER)

### ISSUE THREAD

**Issue by abalad** [rethinkdb/rethinkdb#6635]
Does anyone know why this error when trying to sort and then group the data both actions with an index?

If removing the index from the grouping(CAR_ID) works, however, the query is too slow
```
r.db("BD")
  .table("tracker")
  .orderBy({index: r.desc('DT_EVENT')})
  .group({index:'CAR_ID'})
  .limit(1)
```

**Comment by srh** [comment]
You can't group by one index and order by another. Maybe you want a compound index.

**Comment by abalad** [comment]
And how would it be time to sort and group with this index? In the documentation does not explain how to perform the grouping and ordering using these  compound index.

**Comment by srh** [comment]
I'm not sure you can. What you're looking for is some index structure that lets you keep track of the largest value by car ID, right?  That's going to mean a compound index by (car_id, dt_event). Or, if every car has about the same distribution of events, just an index by dt_event. Then you have to find some way to write the query to take advantage of this structure.

**Comment by marshall007** [comment]
I believe something along these lines would work assuming you had a compound index on `[ CAR_ID, DT_EVENT ]`, but I'm not sure how much more performant it would be:

```js
r.db("BD")
  .table("tracker")
  .distinct({index: 'CAR_ID__DT_EVENT'})
  // group by CAR_ID
  .group(r.row(0))
  // should already be sorted cause of `distinct`,
  // so grab the last element (highest `DT_EVENT`)
  .nth(-1) 
  .ungroup()('reduction')
  .coerceTo('array')
  .do((keys) =>
    r.db("BD")
      .table("tracker")
      .getAll(keys, { index: 'CAR_ID__DT_EVENT' })
  )
```

A variant of the above query using `fold` or `reduce` instead of `group` might be even better. You'll need to experiment a little.

**Comment by abalad** [comment]
@marshall007 Thanks, I ended up trying to use this query, but the tracker table has more than 3 Million records, with this query the response was coming in around **2 to 3 seconds**.
I use this query in a Realtime application, this latency time is a bit high.

I ended up using the following syntax, as I needed only the last DT_EVENT record for each CAR_ID.I found a latency of **200 ~ 500ms.**

```javascript
let CARS = ['56396dbc-eb4f-44fe-b016-ba180d652860', 
            '4196dbc-eb4f-44fe-b016-ba180d515151s',...]

r.db("BD")
  .table("tracker")
  .filter((doc)=> r.expr(CARS).contains(doc("CAR_ID")) )
  .group("CAR_ID")
  .max("DT_EVENT")

```

**Comment by marshall007** [comment]
@abalad since you know the `CAR_ID`s ahead of time, you could use a `getAll` instead of a filter, which will probably help speed it up too:

```js
let CARS = ['56396dbc-eb4f-44fe-b016-ba180d652860', 
            '4196dbc-eb4f-44fe-b016-ba180d515151s',...]

r.db("BD")
  .table("tracker")
  .getAll(r.args(CARS), { index: 'CAR_ID' })
  .group("CAR_ID")
  .max("DT_EVENT")
```

Closing this issue, but let us know if you have any other questions.
