### ISSUE TITLE
NoClassDefFoundError: com/rethinkdb/RethinkDB

### ISSUE THREAD

**Issue by AstrealDev** [rethinkdb/rethinkdb#6637]
I'm new to using Maven but know a bit about setting up a `pom.xml` file. So, I just added one into my project looking like:
```xml
<project>
    <groupId>me.galaxycraft</groupId>
    <artifactId>galaxycraftpvp</artifactId>
    <modelVersion>4.0.0</modelVersion>
    <version>1.0.0</version>
    <dependencies>
        <dependency>
            <groupId>com.rethinkdb</groupId>
            <artifactId>rethinkdb-driver</artifactId>
            <version>2.3.3</version>
        </dependency>
    </dependencies>
</project>
```
I then built the project and tested and am getting this error: `NoClassDefFoundError: com/rethinkdb/RethinkDB`. Clearly something went wrong with me adding this dependency to my `pom.xml`. I then did some research and found I need to add a `.jar` file source to my project. Using IntelliJ I did this and added the `rethinkdb-driver-2.3.3` jar file under Libraries within the Project Structure. I once again tested and this didn't work as I got the same error.

I've hit a roadblock and need help figuring out how to correctly setup the RethinkDB Java Driver. Sorry if I'm being totally stupid and the answer is right in front of my eyes I've never used Maven before.

**Comment by adriantodt** [comment]
This is not a driver but Maven-related issue. You can try updating to version 2.4.0 to see if it's still not working, but still is a Maven-related issue. Open a issue on the Java driver repository (https://github.com/rethinkdb/rethinkdb-java) if you found any more problems, though I only know Gradle. (This issue can be closed and locked)
