### ISSUE TITLE
A question about the 'id' Attribute

### ISSUE THREAD

**Issue by olivierWWB** [rethinkdb/rethinkdb#6638]
When I create a new table, I want to set the 'id' be the primary key. But now it's value is like a long string. So can I make the 'id' value to be 0,1....100.... and it can be auto increment like mysql?

**Comment by sagivf** [comment]
@olivierWWB  you can use your own "id" field but there is no auto increment - you will have to manage that yourself in code. take into consideration that it might also affect you sharding strategy later on.
