### ISSUE TITLE
Curious about internal addition artefacts

### ISSUE THREAD

**Issue by Aedaeum** [rethinkdb/rethinkdb#6642]
The object below is representative of 3 other logic blocks that add fractions to an existing rating count. Every once in a while, I'll get a rating saved as `1.3000000004` even though there are no increments to that precision. Should I be wary of inaccuracies over time?

The only numbers added for this field are `0.2`, `0.6` and `1`. I would never expect to see any precision greater than 1 decimal.

```javascript
{
  msg: {
    rating: r.row('msg')('rating').add(0.2)
  }
}
```

**Comment by srh** [comment]
The numbers are represented with binary64 IEEE 754 (i.e. double precision floats), which is a base-2 format.  So you'll see rounding errors with any number of the reduced fractional form p/q where q is not a power of 2.
