### ISSUE TITLE
Rename fields idea

### ISSUE THREAD

**Issue by PassTheMayo** [rethinkdb/rethinkdb#6647]
Let's say you have a document with the following data:
```json
{
    "test_1": "Hello, there."
}
```

and that you wanted the output of the query to be returned as

```json
{
    "result": "Hello, there."
}
```

That's where my idea comes in place. You could use `r.table('data').rename('test_1', 'result')` to do that. If it's a `SEQUENCE`, it'll apply it to all documents, otherwise just do it on the current object.

**Comment by srh** [comment]
See #881.  Closing as duplicate.
