### ISSUE TITLE
RethinkDB does not install on Ubuntu 17.10 -- the repository does not have a Release file

### ISSUE THREAD

**Issue by ctsrc** [rethinkdb/rethinkdb#6648]
https://rethinkdb.com/docs/install/ubuntu/ says to do the following:

```
source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
sudo apt-get update
sudo apt-get install rethinkdb
```

However, when I get to `sudo apt-get update`, I get the following error:

```
Hit:1 http://no.archive.ubuntu.com/ubuntu artful InRelease
Get:2 http://no.archive.ubuntu.com/ubuntu artful-updates InRelease [81.7 kB]
Get:3 http://no.archive.ubuntu.com/ubuntu artful-backports InRelease [72.2 kB]
Hit:4 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu artful InRelease
Hit:5 http://ppa.launchpad.net/haraldhv/shotcut/ubuntu artful InRelease
Hit:6 https://download.docker.com/linux/ubuntu artful InRelease
Hit:7 http://ppa.launchpad.net/inkscape.dev/stable/ubuntu artful InRelease
Ign:8 http://download.rethinkdb.com/apt artful InRelease
Hit:9 http://ppa.launchpad.net/neovim-ppa/stable/ubuntu artful InRelease
Get:10 http://no.archive.ubuntu.com/ubuntu artful-updates/main amd64 DEP-11 Metadata [83.3 kB]
Hit:11 http://repo.steampowered.com/steam precise InRelease
Hit:12 http://ppa.launchpad.net/obsproject/obs-studio/ubuntu artful InRelease
Get:13 http://no.archive.ubuntu.com/ubuntu artful-updates/main DEP-11 64x64 Icons [54.1 kB]
Get:14 http://no.archive.ubuntu.com/ubuntu artful-updates/universe amd64 DEP-11 Metadata [65.2 kB]
Get:15 http://no.archive.ubuntu.com/ubuntu artful-updates/universe DEP-11 64x64 Icons [79.8 kB]
Get:16 http://no.archive.ubuntu.com/ubuntu artful-updates/multiverse amd64 DEP-11 Metadata [2,468 B]
Hit:17 http://ppa.launchpad.net/otto-kesselgulasch/gimp/ubuntu artful InRelease
Err:18 http://download.rethinkdb.com/apt artful Release
  404  Not Found
Get:19 http://no.archive.ubuntu.com/ubuntu artful-backports/universe amd64 DEP-11 Metadata [5,092 B]
Hit:20 http://ppa.launchpad.net/thomas-schiex/blender/ubuntu artful InRelease
Hit:21 http://security.ubuntu.com/ubuntu artful-security InRelease
Reading package lists... Done
E: The repository 'http://download.rethinkdb.com/apt artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

And therefore, `sudo apt-get install rethinkdb` fails:

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package rethinkdb
```

**Comment by Shinobu1337** [comment]
This is because there is no Artful release yet

**Comment by hunnain** [comment]
I have installed in Ubuntu 17.10

**Comment by hunnain** [comment]
I have face many error at last I have installed

**Comment by ZandercraftGames** [comment]
Yes, I have the same issue...
I really need it soon
Plz help

**Comment by ZandercraftGames** [comment]
Should I get a older version of ubuntu then?

**Comment by srh** [comment]
Follow the instructions at http://samuelhughes.com/rethinkdb/build_instructions.html

If you want a deb file, use `make build-deb UBUNTU_RELEASE=bionic` (or use artful if you want 17.10).  You might have to edit `mk/packaging.sh` to provide the proper behavior for bionic -- it looks good to me but I haven't tested it out.

You might need some extra packages to get a debian package built -- because I think it checks that the build dependencies specified in the package manifest are actually present, something like that.  So... it might not work the first run, but after you install the necessary packages (that it complains about in the output) it should work.

**Comment by ZandercraftGames** [comment]
If it will work... Should I just install ubuntu 16.04.4? Will that work?
ubuntu-16.04.4-preinstalled-server-armhf+raspi2.img.xz

**Comment by srh** [comment]
I put my bionic packages here: https://github.com/srh/rethinkdb/releases/tag/v2.3.6.srh.1
You can download the .deb and install it with `dpkg -i filename.deb`.

**Comment by srh** [comment]
Oh, you're on armhf.  I guess you can't install it.

**Comment by ZandercraftGames** [comment]
But would it work on 16.04 in any normal case?
Cause if it works on 16.04 in any case, it will work on armhf. Does normal rethinkdb work on 16.04?

**Comment by srh** [comment]
Yes. I don't know if there's an armhf package.

**Comment by ZandercraftGames** [comment]
Yeah... there isn't. I am using the source code and following the instructions for using it on armhf systems... It is labled as Installing on Raspberry Pi.

**Comment by syddel** [comment]
@srh - thank you so much for the pre-built .deb packages for Ubuntu (it was EXTREMELY difficult to find pre-build .deb packages, by the way). I followed your instructions and managed to install rethinkdb without any issues.

**Comment by Archer456** [comment]
@srh   
`cmd@TR:~/MyDownload$ sudo dpkg -i rethinkdb-dbg_2.3.6.srh.1.0bionic_amd64.deb 
正在选中未选择的软件包 rethinkdb-dbg。
(正在读取数据库 ... 系统当前共安装有 412934 个文件和目录。)
正准备解包 rethinkdb-dbg_2.3.6.srh.1.0bionic_amd64.deb  ...
正在解包 rethinkdb-dbg (2.3.6.srh.1~0bionic) ...
dpkg: 依赖关系问题使得 rethinkdb-dbg 的配置工作不能继续：
 rethinkdb-dbg 依赖于 rethinkdb (= 2.3.6.srh.1~0bionic)；然而：
  未安装软件包 rethinkdb。

dpkg: 处理软件包 rethinkdb-dbg (--install)时出错：
 依赖关系问题 - 仍未被配置
在处理时有错误发生：
 rethinkdb-dbg

cmd@TR:~/MyDownload$ sudo apt install -f
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
正在修复依赖关系... 完成
下列软件包将被【卸载】：
  rethinkdb-dbg
升级了 0 个软件包，新安装了 0 个软件包，要卸载 1 个软件包，有 0 个软件包未被升级。
有 1 个软件包没有被完全安装或卸载。
解压缩后将会空出 189 MB 的空间。
您希望继续执行吗？ [Y/n] y
(正在读取数据库 ... 系统当前共安装有 412938 个文件和目录。)
正在卸载 rethinkdb-dbg (2.3.6.srh.1~0bionic) ...

cmd@TR:~/MyDownload$ sudo dpkg -i rethinkdb-dbg_2.3.6.srh.1.0bionic_amd64.deb 
正在选中未选择的软件包 rethinkdb-dbg。
(正在读取数据库 ... 系统当前共安装有 412934 个文件和目录。)
正准备解包 rethinkdb-dbg_2.3.6.srh.1.0bionic_amd64.deb  ...
正在解包 rethinkdb-dbg (2.3.6.srh.1~0bionic) ...
dpkg: 依赖关系问题使得 rethinkdb-dbg 的配置工作不能继续：
 rethinkdb-dbg 依赖于 rethinkdb (= 2.3.6.srh.1~0bionic)；然而：
  未安装软件包 rethinkdb。

dpkg: 处理软件包 rethinkdb-dbg (--install)时出错：
 依赖关系问题 - 仍未被配置
在处理时有错误发生：
 rethinkdb-dbg
`

**Comment by maxchoid** [comment]
How do you go about making RethinkDB start up on the system automatically or having it run 24/7?

**Comment by hsafari** [comment]
Hello, Can someone please let me know how to install that bionic package.  I don't see such files ./configure  or make . Sorry, I am new in these stuff and probably dummy question

**Comment by srh** [comment]
Hi @hsafari. You'll want to run `sudo dpkg -i rethinkdb_2.3.6.srh.1.0bionic_amd64.deb` and possibly then `sudo apt-get install -f` afterwards.  Let us know if this doesn't actually work.

**Comment by hsafari** [comment]
Thank you Srh. It worked,  I was not familiar with installing these kind of deb files. Appreciate it.

**Comment by gabor-boros** [comment]
@srh Can we close this issue?
Side note: disco, eoan, bionic 2.3.7 versions are out on downloads.rethinkdb.com

**Comment by srh** [comment]
Packages are available for currently supported Ubuntus, including 16.04 and 18.04.

**Comment by kherwata** [comment]
to fix the problem you should go to the official website 
https://rethinkdb.com/docs/install/ then choose your os ... then install dependencies or use the commands in the page .. i hope you do your best to find the solution
