### ISSUE TITLE
How we use Rethinkdb in react native

### ISSUE THREAD

**Issue by hunnain** [rethinkdb/rethinkdb#6651]
Hi 
There anyone know.I want use rethinkdb in react-native so how can i use firstly i didnt have any backend server like node and express and flask.without server i want to use rethinkdb in react-native

**Comment by sagivf** [comment]
@hunnain react-native is like any other client. You need some sort of server(express, java, etc...). There are tutorials available (https://www.rethinkdb.com/docs/guide/javascript/).
I use node, if your stuck on something specific let me know.

**Comment by shanehsu** [comment]
You can also use the native part of `react-native` if you want, but that leaves the server wide open.

**Comment by gabor-boros** [comment]
Closed as it is already answered
