### ISSUE TITLE
net_tornado.py needs updating for tornado 5.0 support.

### ISSUE THREAD

**Issue by krull** [rethinkdb/rethinkdb#6655]
Hello!

I have created a [PR](https://github.com/rethinkdb/rethinkdb/pull/6654) for updating `net_tornado.py` python driver to promote compatibility to tornado v5.0.0 and above.

Per the release note:
> `io_loop` arguments to many Tornado functions have been removed. Use `IOLoop.current()` instead of passing `IOLoop` objects explicitly.

Creating an issue here to raise awareness.

**Comment by gabor-boros** [comment]
https://github.com/rethinkdb/rethinkdb/pull/6654
