### ISSUE TITLE
Http Error 403 studio/index.html on Windows 10

### ISSUE THREAD

**Issue by devtrix** [rethinkdb/rethinkdb#6657]
I just downloaded the windows executable.  I am starting rehinkdb.exe as admin in a folder e:\rethinkdb where the permissions exist.  I am trying to run the rethinkdb.exe as Administrator and, I get the following error in the browser
Access to 127.0.0.1 was denied
You don't have authorization to view this page.
HTTP ERROR 403

I see the following in the console
Someone asked for a nonwhitelisted file "/studio/index.html".  If this should be accessible, add it to the static web assets.

Please advise.

**Comment by srh** [comment]
The RethinkDB web UI listens on port 8080 by default.  Nothing should be trying to access /studio/index.html.
