### ISSUE TITLE
Installation fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by mholt** [rethinkdb/rethinkdb#6663]
After running these commands successfully:

```
source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
```

I get errors on these:

```
$ sudo apt-get update
Hit:1 http://mirrors.digitalocean.com/ubuntu bionic InRelease
Hit:2 http://mirrors.digitalocean.com/ubuntu bionic-updates InRelease                                        
Hit:3 http://mirrors.digitalocean.com/ubuntu bionic-backports InRelease                                      
Hit:4 https://repos.sonar.digitalocean.com/apt main InRelease                                                
Ign:5 http://download.rethinkdb.com/apt bionic InRelease                                                     
Err:6 http://download.rethinkdb.com/apt bionic Release                                                       
  404  Not Found [IP: 72.14.189.19 80]
Hit:7 http://security.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists... Done                     
E: The repository 'http://download.rethinkdb.com/apt bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

$ sudo apt-get install rethinkdb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package rethinkdb
```

I cannot seem to install RethinkDB on Ubuntu 18.04. ☹️ Can you give me any pointers as to what I'm doing wrong?

**Comment by srh** [comment]
There is no release for 18.04 uploaded to the official server. You can download a package for bionic from https://github.com/srh/rethinkdb/releases/tag/v2.3.6.srh.1

**Comment by mholt** [comment]
Ah... well, thanks for the link.

Any plans for an official release, do you know?

**Comment by n8behavior** [comment]
Guess that's a no...makes me think I should "rethink" using it :-1:

**Comment by chovy** [comment]
rethinkdb has been forked. there's a new effort which has strong support to rebrand it as rebirthdb.

**Comment by tarzan212** [comment]
Managed to install by configuring using the system malloc, on Ubuntu 18.04 bionic : 
`./configure --allow-fetch CXX=clang++ --with-system-malloc`
And not having any nodejs installed prior to the configuration since it will generate npm errors for whatever reasons ( didn't dig deep into this, simply removed my nodejs version).
The make should run fine.

**Comment by fluentart** [comment]
Busy compiling now, this tip of unlinking node seems to be working.
For others:

sudo unlink /usr/bin/node;
sudo unlink /usr/sbin/node;
sudo unlink /sbin/node;
sudo unlink /usr/local/bin/node;
sudo unlink /usr/bin/npm;
sudo unlink /usr/sbin/npm;
sudo unlink /sbin/npm;
sudo unlink /usr/local/bin/npm;

Then after use whichever is relevant for your location of the node/npm executables.

# Create symlinks to node && npm
sudo ln -s /opt/nodejs/bin/node /usr/bin/node;
sudo ln -s /opt/nodejs/bin/node /usr/sbin/node;
sudo ln -s /opt/nodejs/bin/node /sbin/node;
sudo ln -s /opt/nodejs/bin/node /usr/local/bin/node;
sudo ln -s /opt/nodejs/bin/npm /usr/bin/npm;
sudo ln -s /opt/nodejs/bin/npm /usr/sbin/npm;
sudo ln -s /opt/nodejs/bin/npm /sbin/npm;
sudo ln -s /opt/nodejs/bin/npm /usr/local/bin/npm;

**Comment by maxchoid** [comment]
@fluentart Is this the way to do it (latest comment)

**Comment by maxchoid** [comment]
How do you go about making RethinkDB start up on the system automatically or having it run 24/7?

**Comment by srh** [comment]
You could probably use `--fetch npm` instead of unlinking nodejs.  Unless you tried that.

**Comment by srh** [comment]
@zugende You can install the missing dependencies by running `apt-get install -f`.

You probably want to install rethinkdb_2.3.6.srh.1.0bionic_amd64.deb, not the -dbg version.

**Comment by TTimo** [comment]
@srh can you detail how you produced this package? And maybe produce one for v2.4.x as well?

For context, I have tried compiling v2.4.x on 18.04 and got stuck on the build failing during v8 compile. (It's the fetched v8 version, I wasn't able to get rethinkdb build system to use a packaged `libv8-dev` either).

That was just compiling from source, not even trying to produce a debian package. I would appreciate some pointers in that direction.

**Comment by srh** [comment]
@TTimo You can find a 2.4.x package at https://github.com/srh/rethinkdb/releases/ -- I'll keep the URL generic so people following the link find whatever's the latest.  I'd consider it a pre-pre-release.

For 18.04 I think I followed these instructions: http://samuelhughes.com/rethinkdb/build_instructions.html

If that doesn't work, you might have packages on your system that the build system tries to use, and might need to add explicit `--fetch` arguments to the configure line.

**Comment by TTimo** [comment]
Right on! Thanks for the various bits of information.

**Comment by jeffmikels** [comment]
Is there still no 18.04 release?

**Comment by TTimo** [comment]
fwiw I was able to install the 2.4.x package @srh made available at https://github.com/rethinkdb/rethinkdb/issues/6663#issuecomment-485142124 and it's been working fine ever since.

**Comment by matteo-bombelli** [comment]
for everyone that needs that, i've got no problem using rethibkdb on docker (even alpine versions)

**Comment by gabor-boros** [comment]
@srh Can we close it? I would

**Comment by srh** [comment]
There is an 18.04 release now. The instructions at https://rethinkdb.com/docs/install/ubuntu/ will get it for you.

**Comment by gelkin** [comment]
For some reason instructions from here https://rethinkdb.com/docs/install/ubuntu/ didn't work for me. You can choose and download from here: https://download.rethinkdb.com/#browse/browse
