### ISSUE TITLE
`patch -fp1` doesn't work on Alpine Linux

### ISSUE THREAD

**Issue by daveisfera** [rethinkdb/rethinkdb#6666]
RethinkDB 2.3.5 would build on Alpine Linux, but then [this change](https://github.com/rethinkdb/rethinkdb/commit/41e11c740b32493deefd668ab343fabb15d4b6b4#diff-2f99a770a02afe004be6e92b2cc92161R126) added `patch -fp1` and that isn't a valid command on Alpine Linux, so it fails to build.

**Comment by daveisfera** [comment]
Apparently, there's 2 spots with a change like that. This is a patch that gets it building on Alpine Linux again:
```
--- a/mk/support/pkg/v8.sh
+++ b/mk/support/pkg/v8.sh
@@ -6,7 +6,7 @@

 pkg_install-include () {
     pkg_copy_src_to_build
-    in_dir "$build_dir" patch -fp1 < "$pkg_dir"/patch/v8_2-HandleScope-protected.patch
+    in_dir "$build_dir" patch -p1 < "$pkg_dir"/patch/v8_2-HandleScope-protected.patch

     rm -rf "$install_dir/include"
     mkdir -p "$install_dir/include"
@@ -29,7 +29,7 @@

 pkg_install () {
     pkg_copy_src_to_build
-    in_dir "$build_dir" patch -fp1 < "$pkg_dir"/patch/v8_2-HandleScope-protected.patch
+    in_dir "$build_dir" patch -p1 < "$pkg_dir"/patch/v8_2-HandleScope-protected.patch
     sed -i.bak '/unittests/d;/cctest/d' "$build_dir/build/all.gyp" # don't build the tests
     mkdir -p "$install_dir/lib"
     if [[ "$OS" = Darwin ]]; then
```

**Comment by FilipeRamalho** [comment]
Could you make a PR so it can get merged and the issue solved ?

**Comment by srh** [comment]
-f is not in POSIX, and the result of removing does not result in prompts to the user? (And these prompts don't happen because the patch is legit?)  Sounds reasonable to drop the flag.

**Comment by srh** [comment]
This is fixed, congrats on getting issue number 6666.

**Comment by daveisfera** [comment]
For documentation, here's the commit:
https://github.com/rethinkdb/rethinkdb/commit/98fd78409095a25b04dcaf0eadd6719f381a7d7e
Thanks for the quick resolution.
