### ISSUE TITLE
Why does 'rethinkdb-dump' command executes 3 processes?

### ISSUE THREAD

**Issue by shbmira** [rethinkdb/rethinkdb#6669]
Hello, you all!

Sorry if this is duplicated, but I did not find a similar question here and your documentation does not explain it.

When I run following command, it spawns up other 2 processes for the same table, keeping open 3 connections to the rethinkdb server, even I'm passing `--clients 1` parameter:

```
rethinkdb dump -c myserver --clients 1 --temp-dir /mytempfolder -q --overwrite-file -e database.table -f /myfolder/database/table.tar.gz --password-file myserver-pw.txt
```

When I look into process list, I see:

```
root      2284  0.0  0.2 234060 21344 ?        S    12:20   0:03 /usr/bin/python2.7 /usr/local/bin/rethinkdb-dump -c myserver --clients 1 --temp-dir /mytempfolder -q --overwrite-file -e database.table -f /myfolder/database/table.tar.gz --password-file myserver-pw.txt
root      2294 38.4  0.7 272052 55628 ?        R    12:20  48:52 /usr/bin/python2.7 /usr/local/bin/rethinkdb-dump -c myserver --clients 1 --temp-dir /mytempfolder -q --overwrite-file -e database.table -f /myfolder/database/table.tar.gz --password-file myserver-pw.txt
root      2295 25.8  0.2 234076 16024 ?        S    12:20  32:50 /usr/bin/python2.7 /usr/local/bin/rethinkdb-dump -c myserver --clients 1 --temp-dir /mytempfolder -q --overwrite-file -e database.table -f /myfolder/database/table.tar.gz --password-file myserver-pw.txt
```

I did not really understand why this happen.

**Comment by srh** [comment]
I don't know either.  You can look at the source at https://github.com/rethinkdb/rethinkdb/blob/next/drivers/python/rethinkdb/_dump.py to see what it does.

**Comment by shbmira** [comment]
Yes, @srh!

I had already taken a look, but it was not too clear to me if it that implementation was a decision or someone followed requirements and naturally it culminated that way.

But thanks, anyway!
