### ISSUE TITLE
How to convert stamp epoch_time to real datatime format

### ISSUE THREAD

**Issue by bloodknight2010** [rethinkdb/rethinkdb#6672]
My query is `r.table('chat').order_by('stamp',index='stamp').slice(0,10).group('question_id').pluck('user','message','stamp').run()`
I got the following result

> {
    "ab7c4a3c-5f11-4068-a12a-513e91ed5539": [
        {
            "stamp": {
                "$date": 1486475943614
            }, 
            "message": "ေမးျမန္းႏိုင္ပါတယ္", 
            "user": "ေဒါက္တာဆုမြန္မြန္ထြန္း"
        }
    ], 
    "6c09458d-bbe1-4740-9342-dbecfc292845": [
        {
            "stamp": {
                "$date": 1486475988064
            }, 
            "message": "ဆုမြန္ပါ", 
            "user": "ေဒါက္တာဆုမြန္မြန္ထြန္း"
        }, 
        {
            "stamp": {
                "$date": 1486476004415
            }, 
            "message": "hi ma su mon", 
            "user": "Phyo Arkar"
        }, 
        {
            "stamp": {
                "$date": 1486476014335
            }, 
            "message": " သူငယ္ခ်င္းတို႔ ျမန္မာလိုဖတ္လို႔ၾကပီလား", 
            "user": "ေဒါက္တာဆုမြန္မြန္ထြန္း"
        }, 
        {
            "stamp": {
                "$date": 1486476028567
            }, 
            "message": "yes i fixed it all this morning", 
            "user": "Phyo Arkar"
        }, 
        {
            "stamp": {
                "$date": 1486476056193
            }, 
            "message": "my one ကေတာ့ both languages အဆင္ေျပေနတယ္ ဖတ္တာေကာ စာရိုက္တာေကာ😊", 
            "user": "ေဒါက္တာဆုမြန္မြန္ထြန္း"
        }, 
        {
            "stamp": {
                "$date": 1486476080722
            }, 
            "message": "Thanks , yes , all are forced to zawgyi font now\n", 
            "user": "Phyo Arkar"
        }, 
        {
            "stamp": {
                "$date": 1486476083473
            }, 
            "message": "# Closed", 
            "user": "Phyo Arkar"
        }
    ], 
    "0ce97a87-37ea-46fb-80c0-096b8508c7f5": [
        {
            "stamp": {
                "$date": 1486456868881
            }, 
            "message": null, 
            "user": "Wai Wai Hnin"
        }
    ], 
    "lobby": [
        {
            "stamp": {
                "$date": 1486456932930
            }, 
            "message": "Hi", 
            "user": "Wai Wai Hnin"
        }
    ]
}

I would like to select the real datetime result eg, I want to stamp must be "**Sun Nov 12 2017 08:24:59 GMT+00:00**"
How to create query?Pls help me.

**Comment by srh** [comment]
I don't think RethinkDB has a general time->string formatting function, it just has `toISO8601()`, but you could build such a string yourself manually by using dayOfWeek, month, day, year, hours, minutes, seconds, and timezone reql functions.  It's probably also annoying to format 8 into "08".  Do it client-side if you can.

**Comment by thelinuxlich** [comment]
The rebirthdb-js driver has a ISO8601 run option: https://github.com/RebirthDB/rebirthdb-js/pull/1
