### ISSUE TITLE
Using ReQL to filter based on properties of entry arrays

### ISSUE THREAD

**Issue by jviotti** [rethinkdb/rethinkdb#6677]
Hey there! 

I'm working on a prototype JSON Schema to ReQL translator Node.js module, and I found myself stuck at implementing the `items` JSON Schema operator. Let me give you an example:

```js
{
  type: 'object',
  required: [ 'foo' ],
  properties: {
    foo: {
      type: 'array',
      items: {
        type: 'string'
      }
    }
  }
}
```

The above JSON Schema will match for every entry that contains an array called `foo`, whose elements are all strings.

I couldn't find a way to express with ReQL. Here's what I imagine it could look like, but I hope you can point me in the right direction:

```js
r.db('test').table('test').filter(r.row('foo').typeOf().eq('ARRAY').and(r.row('foo').every((element) => element.typeOf().eq('STRING'))))
```

I guess the bit we're missing is the `.every()` operator. I don't know how to mimic that with the current operators ReQL supports. Maybe a `.reduce()` would be handy?

**Comment by ronzeidman** [comment]
You can use map=>reduce (or fold):
`row('foo').map(elem => elem.typeOf().eq('STRING')).reduce((l, r) => l.and(r))`

**Comment by jviotti** [comment]
Closing stale issues
