### ISSUE TITLE
Incorrect result with OR involving a disjunct with nested properties 

### ISSUE THREAD

**Issue by jviotti** [rethinkdb/rethinkdb#6680]
Take the following inserted object:

```js
{
  "active": true ,
  "data": {
    "email": "foo@bar.com" ,
    "roles": [ ]
  } ,
  "id":  "9a67da68-a312-4f0b-a43f-37fae7b8f8a4" ,
  "links": [ ],
  "name":  "The guest user" ,
  "slug":  "user-guest" ,
  "tags": [ ],
  "type":  "user"
}
```

And try to execute the following query:

```js
r.db('test').table('test').filter(
  r.row('slug').eq('user-guest').and(
    r.or(
      r.row('data')('target').typeOf().eq('STRING'),
      r.row('type').eq('user')
    )
  )
)
```

This basically filters the given table for objects whose `slug` is `user-guest` (which matches our example object), and also checks that either `data.target` is a string (which is false, since `target doesn't exist`) or `type` equals `user` (which is true). Given the disjunction is `true`, the overall conjunction is `true` and our example object should be returned.

However I get `No results were returned for this query` on `rethinkdb 2.3.6 (CLANG 9.0.0 (clang-900.0.37))` on macOS High Sierra 10.13.5. 

Interestingly enough, the query works if I swap the order of the disjuncts:

```js
r.db('test').table('test').filter(
  r.row('slug').eq('user-guest').and(
    r.or(
      r.row('type').eq('user'),
      r.row('data')('target').typeOf().eq('STRING')
    )
  )
)
```

Even more interesting is the fact that the query works if we don't try to assert something on a nested property. For example, this first disjunct is still false, but the query works as expected:

```js
r.db('test').table('test').filter(
  r.row('slug').eq('user-guest').and(
    r.or(
      r.row('data').typeOf().eq('STRING'),
      r.row('type').eq('user')
    )
  )
)
```

I'll try to dig more into it on my own, but I think at this point I could really use some help.

**Comment by jviotti** [comment]
Looks like RethinkDB stops considering disjuncts after a failing one that refers to a nested property. This one still fails:

```js
r.db('jellyfish').table('cards').filter(
  r.row('slug').eq('user-guest').and(
    r.or(
      r.row('data')('target').typeOf().eq('STRING'),
      true
    )
  )
)
```

**Comment by jviotti** [comment]
The overall conjunction doesn't affect this problem. We can reduce the problematic query to something like:

```js
r.db('jellyfish').table('cards').filter(
  r.or(
    r.row('data')('xxxxxxxxx').typeOf().eq('STRING'),
    true
  )  
)
```

**Comment by jviotti** [comment]
I also checked if `typeOf` has something to do with this problem. The following query still fails:

```js
r.db('jellyfish').table('cards').filter(
  r.row('data')('xxxxxxxxx').eq('foo').or(true)     
)
```

**Comment by jviotti** [comment]
For a second I thought that there might be a problem with the JS driver, but I can also reproduce this using the Python driver:

```py
cursor = r.db("test").table("test").filter((r.row['slug'] == 'user-guest') & r.or_(r.row["data"]["target"].type_of() == "STRING", r.row["type"] == "user")).run(conn)
```

**Comment by jviotti** [comment]
OK, I found a workaround. Apparently everything works if I set a default value to `false` on every disjunct that uses nested properties. For example:

```js
r.db('test').table('test').filter(
  r.row('slug').eq('user-guest').and(
    r.or(
      r.row('data')('target').typeOf().eq('STRING').default(false),
      r.row('type').eq('user')
    )
  )
)
```

I still think this should be fixed/improved though.

**Comment by gabor-boros** [comment]
@srh what is your opinion here?

**Comment by srh** [comment]
This is known behavior and the user figured it out -- `r.or` does short-circuiting evaluation, and you can't access a field that doesn't exist, and `.default` will catch that outcome and provide a value.
