### ISSUE TITLE
now() does not return the correct micro-seconds to allow recording linearized order

### ISSUE THREAD

**Issue by yjiangnan** [rethinkdb/rethinkdb#6681]
r.now().run()
returns:

    datetime.datetime(2018, 6, 18, 2, 11, 6, 354000, tzinfo=<rethinkdb.ast.RqlTzinfo...>)

It seems that rethinkdb tried to get the micro-seconds, but unfortunately they are all 0s. I also notice some functions in src/time.cc seem to have implemented high-precision time, but I am not sure how that can be queried. 

Is it possible to fix this problem? It is really important for some applications to know the precise time when the document is received/saved by the servers. I am trying to build a high-frequency insertion system where the order of insertion is important and should be archived. However, I cannot find an easy way to achieve this except for recording the time to high precision. Unfortunately, millisecond precision does not help that much. Alternatively, is it possible to cheaply get the id of the latest insertion to make a data structure like [{'id':1, 'last_id':0}, 'id':2, 'last_id':1}, 'id':3, 'last_id':2}...] when multiple servers attempt to retrieve the last id concurrently? This chained data structure would allow clients to easily know if they missed data after recovering from network problems. Rethinkdb internally have linearized operations, but I am not sure why that linear order is not recorded and allowed to be queried by users.

Thanks!

**Comment by srh** [comment]
RethinkDB can have an ordering to operations on a per-shard basis.

Time is rounded off to the millisecond because of some decision made when adding that API. Maybe because some client driver didn't like sub-millisecond precision. I see no reason not to support finer precision.

**Comment by gabor-boros** [comment]
@srh Should I close this issue?

**Comment by srh** [comment]
Sure.  Of course this doesn't mean a microsecond time precision or per-shard insertion order feature isn't permanently ruled out.
