### ISSUE TITLE
 rethinkdb apt repository not contains ubuntu18.04 bionic Release  versions

### ISSUE THREAD

**Issue by Archer456** [rethinkdb/rethinkdb#6682]
https://rethinkdb.com/docs/install/ubuntu/  
http://download.rethinkdb.com/apt  
hello,there is no  ubuntu18.04 bionic rethinkdb versions

`$ source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
deb http://download.rethinkdb.com/apt bionic main

$ wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
OK

$ sudo apt-get update

错误:8 http://download.rethinkdb.com/apt bionic Release                                 
  404  Not Found [IP: 72.14.189.19 80]
E: 仓库 “http://download.rethinkdb.com/apt bionic Release” 没有 Release 文件。
N: 无法安全地用该源进行更新，所以默认禁用该源。

`
so i can't install  rethinkdb in my ubuntu18.04 

`$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
`

**Comment by bchavez** [comment]
#6663 #6648

**Comment by Archer456** [comment]
@bchavez  3Q very much。  
I have download   rethinkdb_2.3.6.srh.1.0bionic_amd64.deb    this   form https://github.com/srh/rethinkdb/releases/tag/v2.3.6.srh.1   .
it works whell in my ubuntu18.04 .

**Comment by maxchoid** [comment]
How do you go about making RethinkDB start up on the system automatically or having it run 24/7?

**Comment by belal-mazlom** [comment]
I just resolved by edit rethinkdb.list in
`sudo nano /etc/apt/sources.list.d/rethinkdb.list`
and change from `artful` to `zesty` since artful not available
http://download.rethinkdb.com/apt/dist/

**Comment by jboneu** [comment]
Hello, does someone know, why is there is no ubuntu18.04 bionic rethinkdb versions?

Being rethinkdb such an amazing database for general use and for connecting realtime webs and apps to it?
If someone can help me understand why it has no further support in ubuntu please let me know.

**Comment by srh** [comment]
Website access (which is kind of resolved because we have DNS access), but also time.
