### ISSUE TITLE
Avoid brief period of unavailability

### ISSUE THREAD

**Issue by ChiragHindocha** [rethinkdb/rethinkdb#6683]
Hello,

I am evaluating rethinkdb to see if it fits my usecase. I have a 3 node cluster setup with a table that has 3 shards & 3 replicas per shard. I am inserting data into the table at 1 ms. i.e I am calling r.table().insert() every 1 ms. It works fine, but when one of the server in the cluster goes down, I get following error: 

> ReqlOpFailedError: Cannot perform write: The primary replica isn't connected to a quorum of replicas. The write was not performed

> 

or sometimes

> ReqlOpFailedError: Cannot perform write: The primary replica is not available. The write was not performed

I understand that rethinkdb is promoting one of the secondary replica to act as a primary & hence there's a brief period of unavailability. So I used 

`table.wait({ waitFor: 'ready_for_writes' })` and the error has gone because it waits for the table to be ready. But during this short duration, my writes gonna miss as I believe. When the server that was down, comes up again, again there's a short period of unavailability because the server is now promoting the old replica to again act as the primary replica, so it gives following error:

> The primary replica is currently changing from one replica to another. The write was not performed. This error should go away in a couple of seconds.

Again waiting for the table to be ready deals with the error, but what if I cannot afford to lose a write during this period? Are there any options I can deal with this? Please advise. Thanks

**Comment by srh** [comment]
You can retry writes until they succeed or fail with a different message. You could have the driver or server do that. But apparently there is a window of time where writes undergo a latency spike. Engineering work on clustering code in the DB could fix that.
