### ISSUE TITLE
Homebrew installation and documentation discrepancies

### ISSUE THREAD

**Issue by DarkStar1** [rethinkdb/rethinkdb#6687]
According to [this part of the official documentation](https://rethinkdb.com/docs/start-on-startup/#startup-with-launchd-os-x)

> If you install RethinkDB using Homebrew, a launchd configuration file will be installed for you in ~/Library/LaunchAgents/, although that file may need to be modified.

I just installed rethink (v2.3.6) using Homebrew on MacOs 10.13.4 and the launchd configuration file is missing at the directory location mentioned in the documentation.

Can someone verify this and advise how best to proceed ?

**Comment by srh** [comment]
The Homebrew install process involves some code or configuration you could look at, right?  I'd recommend looking at that and seeing what exactly it's doing.

**Comment by gabor-boros** [comment]
Because of the lack of activity, I'm closing this issue. 

**Note** Homebrew taps are not created until this issue is not resolved: https://github.com/rethinkdb/rethinkdb/issues/6789
