### ISSUE TITLE
How to create a Release to install Rethinkdb from Ubuntu 18.04LST?

### ISSUE THREAD

**Issue by miguelitolaparra** [rethinkdb/rethinkdb#6688]
Hi, I'm creating a project in a Platzi course, and I had to stop it because I could not install Rethinkdb with the instructions on the official page.
The error is that it can not find the Release file, and Platzi colleagues told me that the support of the community was lost.
Would you have the option to install Rethinkdb in Ubuntu 18.04 in some way and continue with the project?
Thank you.
I die the errors obtained

source /etc/lsb-release && echo "deb https://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
sudo apt-get update
sudo apt-get install rethinkdb

Err:7 https://download.rethinkdb.com/apt bionic Release                                                                      
  404  Not Found [IP: 72.14.189.19 443]
Obj:8 https://download.sublimetext.com apt/stable/ InRelease                                                       
Reading list of packages ... Done
E: The repository «https://download.rethinkdb.com/apt bionic Release» does not have a Publication file.
N: You can not update from a repository like this in a secure way and therefore it is disabled by default.
N: See the apt-secure (8) man page for details on creating repositories and configuring users.

**Comment by miguelitolaparra** [comment]
Thanks for your support.
I have already tried, before asking h sought solution in other answers previous to mine. and I can not find a way to make it work.
I'm a bit of a rookie and I tried all the options offered by https://github.com/srh/rethinkdb/releases/tag/v2.3.6.srh.1,
but I do not know what are the exact steps that I must follow.
I follow a course Node.js in Platzi and I've been using Rethinkdb in windows, but change to Lubuntu 18.04LTS because Windows does not give many options to be able to learn to program.
As I say, I do not know the exact steps that I must follow, so I can not install and I'm standing in Platzi's project, unable to move forward.
I was told in Platzi that Rethinkdb only has the support of the community for its maintenance.
When there is a simpler way to install, I can continue with the project.
With that I do not know how to make Rethinkdb work on my computer.
Again, thank you very much for your support.

**Comment by miguelitolaparra** [comment]
My architecture is x86, not x64

**Comment by srh** [comment]
You can use `dpkg -i` to install it.

**Comment by miguelitolaparra** [comment]
Agree. I already tested it and it gave architecture error. It has been implosible to see your answer until today. Tomorrow I'll try again and I'll tell you what the result was.
Thanks for your time and support.
Good job.

**Comment by miguelitolaparra** [comment]
Thanks mate, solve the problem with dpkg -i.
First, it did not work, until I became a super-user.
The problem is in a computer that I have with x86 architecture, this gives me architecture error.
Is there a solution for Lubuntu 18.04 from x86?
If you do not try to install an older version of Ubuntu and thus be able to use Rethinkdb.
Thanks for your support.
  What should I do to mark the issue as solved and that can help other users with the same problem?

**Comment by srh** [comment]
You could close the issue.  I'll do it, I guess.

If you want 32-bit x86 -- I'll build and upload an x86 package sometime this weekend.  If I don't, feel free to email me about it -- it just means I forgot.

**Comment by miguelitolaparra** [comment]
Thanks for your help and dedication. I'll be waiting where you send the x86 package to use it.
Thanks again.

**Comment by srh** [comment]
I tried installing Lubuntu 18.04 on a VirtualBox VM, but I'm getting hanging or glitched out graphics when I run the installer past the initial menu, depending on what my VM settings are.

I recommend building your own RethinkDB binary starting with the instructions at http://samuelhughes.com/rethinkdb/build_instructions.html .
