### ISSUE TITLE
question of scalability for new user

### ISSUE THREAD

**Issue by Outstep** [rethinkdb/rethinkdb#6691]
Hello,

I have been evaluating RethinkDB for possible use in a project that I am in the middle of developing. The project is a type of product-voting-recommendation system that can have millions of product records with perhaps thousands or more user recommendation entries on each product record. (i.e. a list of user names or hash values that liked/disliked or rated the product).

I really like what I have read about RethinkDB as it seems to be an AWESOME NoSQL database system, but I am a bit concerned to know if it could handle such large datasets?

Originally, I thought that a simple way might be to have just a RethinkDB table for each product but then it seems that in reading over limitations (https://rethinkdb.com/limitations/) that each table will require 10 MB and also that there is a "recommended" document limit of 16 MB.

Given this, I am would like to get a suggestion as to if RethinkDB is really a viable possible solution for this particular project.

Thanks in advance

**Comment by srh** [comment]
Hi @lonnieOST,

If the data fits in memory you'll be fine.  If it doesn't, you'll need an SSD for large documents.

If you store the recommendation entries on a separate table (why wouldn't you?), you have nothing to worry about.

**Comment by gabor-boros** [comment]
@srh We can close this as well I think.
