### ISSUE TITLE
Make Error (npm - bluebird)

### ISSUE THREAD

**Issue by YandiBanyuKarimaWaly** [rethinkdb/rethinkdb#6697]
System:
Ubuntu 17.10 (Artful)
Here's what I've done:

```
sudo apt install build-essential protobuf-compiler python \
    libprotobuf-dev libcurl4-openssl-dev libboost-all-dev \
    libncurses5-dev libjemalloc-dev wget m4 clang libssl-dev
```
`./configure --allow-fetch CXX=clang++`
`make`

Now, here's the error:
```
    [421/432] LD build/release_clang/rethinkdb
/usr/bin/ld: warning: libssl.so.1.0.0, needed by /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../x86_64-linux-gnu/libcurl.so, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../x86_64-linux-gnu/libcurl.so, may conflict with libcrypto.so.1.1
    [422/432] BUILD bluebird_2.9.32
++ mktemp -d /home/yandi/Downloads/Builds/RethinkDB/external/npm_cache-XXXXXXXX
+ cache_dir=/home/yandi/Downloads/Builds/RethinkDB/external/npm_cache-iFAwsTLJ
+ [[ Linux = Windows ]]
+ /usr/bin/npm --userconfig /home/yandi/Downloads/Builds/RethinkDB/mk/support/config/npm.conf --cache /home/yandi/Downloads/Builds/RethinkDB/external/npm_cache-iFAwsTLJ install /home/yandi/Downloads/Builds/RethinkDB/external/bluebird_2.9.32
npm WARN enoent ENOENT: no such file or directory, open '/home/yandi/Downloads/Builds/RethinkDB/build/external/bluebird_2.9.32/package.json'
npm WARN bluebird_2.9.32 No description
npm WARN bluebird_2.9.32 No repository field.
npm WARN bluebird_2.9.32 No README data
npm WARN bluebird_2.9.32 No license field.

npm ERR! path /home/yandi/Downloads/Builds/RethinkDB/build/external/bluebird_2.9.32/node_modules/.staging/bluebird-07b51728
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/yandi/Downloads/Builds/RethinkDB/build/external/bluebird_2.9.32/node_modules/.staging/bluebird-07b51728' -> '/home/yandi/Downloads/Builds/RethinkDB/external/bluebird_2.9.32/node_modules/bluebird'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yandi/Downloads/Builds/RethinkDB/external/npm_cache-iFAwsTLJ/_logs/2018-08-08T01_51_09_028Z-debug.log

Full error log: ./build/external/bluebird_2.9.32_install.log
mk/support/build.mk:148: recipe for target 'build/external/bluebird_2.9.32/install.witness' failed
make[1]: *** [build/external/bluebird_2.9.32/install.witness] Error 1
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2
```

**Comment by srh** [comment]
@YandiBanyuKarimaWaly  Ubuntu 17.10 is past its end of life, so you should upgrade.

Try passing `--fetch npm` to configure, instead of using your system npm.

**Comment by YandiBanyuKarimaWaly** [comment]
I already did, I'm so frustrated so in the end I decided to just upgrade the whole system, so, If anyone come here, I already solve the issue but I hope your answer might be useful to other

**Comment by srh** [comment]
Well, I updated http://samuelhughes.com/rethinkdb/build_instructions.html tell people to try `--fetch`, so there's that.

**Comment by jboneu** [comment]
Hi, everyone, I tried to run build instructions for 2.3.6, and received a different error in MakeFile line 52.
(I am building in ubuntu bionic )


`src/client_protocol/server.cc: In member function ‘size_t http_conn_cache_t::sha_hasher_t::operator()(const conn_key_t&) const’:
src/client_protocol/server.cc:177:16: error: aggregate ‘EVP_MD_CTX c’ has incomplete type and cannot be defined
     EVP_MD_CTX c;
                ^
src/build.mk:390: recipe for target 'build/release/obj/client_protocol/server.o' failed
make[4]: *** [build/release/obj/client_protocol/server.o] Error 1
Makefile:52: recipe for target 'make' failed
make[3]: *** [make] Error 2
debian/rules:20: recipe for target 'build' failed
make[2]: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
mk/packaging.mk:107: recipe for target 'build-deb' failed
make[1]: *** [build-deb] Error 2
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2`
