### ISSUE TITLE
Certificate expired today on https://rethinkdb.com/

### ISSUE THREAD

**Issue by logankoester** [rethinkdb/rethinkdb#6700]
![rethink](https://user-images.githubusercontent.com/19319/44256048-28b7d180-a232-11e8-835f-36435a51de23.png)

Reference: **[SSL Report: rethinkdb.com (72.14.189.19)](https://www.ssllabs.com/ssltest/analyze.html?d=rethinkdb.com&latest)**

**Comment by loeffel-io** [comment]
Fixed
