### ISSUE TITLE
Update README to redirect newcomers to RebirthDB

### ISSUE THREAD

**Issue by Extarys** [rethinkdb/rethinkdb#6704]
Updating the readme should be a good way to let current users and newcomers knows that RethinkDB is superseded by RebirthDB and that any current issues they are experiencing should be put on hold while RebirthDB releases the 2.4.0 version and then open a new issue on that repo if they still have a problem afterward.

This would avoid confusions and opening unnecessary issues.

**Comment by srh** [comment]
The Rebirthers are now merging back in with RethinkDB, it looks like -- so I think this no longer will need to be done.

**Comment by rodrigooler** [comment]
@Extarys, @thelinuxlich will be able to explain in more detail, but a fork is already foreseen between rethinkdB and rebirthDB.

**Comment by tomdread** [comment]
Does anybody know what happened to https://spectrum.chat/rebirthdb getting
a 404 on that now. I would love some news regarding Rebirthdb / Rethinkdb.

Regards
Tom

**Comment by thelinuxlich** [comment]
Hey, @tomdread our official communication channel is now https://spectrum.chat/rethinkdb

**Comment by rodrigooler** [comment]
@tomdread follows the thread related to the subject of the issue, https://spectrum.chat/rethinkdb?thread=0d28e226-c240-465b-b67c-1b1be2cdb58a

**Comment by Extarys** [comment]
Oh thanks! I'm very glad that this is happening!

I'll close as this is no more required.
