### ISSUE TITLE
Making an application level supervisor to vet table changes. (Document-dependant write permissions)

### ISSUE THREAD

**Issue by jordaorodolfo** [rethinkdb/rethinkdb#6705]
Hello, all! I'm very new to rethinkDB, so please pardon me if I want to do something that is either not idiomatic or simply impossible. Let me describe the real problem and then the problem that I encountered as a solution to the real problem.
### Real problem
Suppose that I have a table T with a good load of document T1, T2... Each document of this table has a field F which, as given by my business logic, may prevent some users from writing it. For instante, suppose that document T1 has a permissive field F, then every user U1, U2,... can save and read T1 without problems. Now, some users with elevated permissions changed F to its more restricted version, so that only U1, U5... can modify and save T1. All in all, I want to be able to restrict write with a condition based on the document that is being written, for certain users (they need not be the rethinkDB system ones, they may be a application-level table).
I saw no way to have this fine grained update/insertion, except possibly enforcing it at client side, which for a small-medium enterprise system as I am building, may not be enough.
### My Solutions
Since i found no way to do this document-dependent write permission natively, I figured out that I may A: restrict all users from writing to the db directly and make them issue inserts and updates to a backend server whose logic will determine if the save is allowed or not; or B: let them do all the saves but have a "supervisor" server which listens to all the dependent tables and simply discard the new values if the user is not allowed to make them. I know that option A would work, but it would give me more hard work than necessary. So...
### Problem of my solution
If I am going with the B route, i.e. making a supervisor, I would need to know which user is issuing a change in the watched table. Problem is, to my knowledge, rethinkDB does not give this information in a changefeed, not even to the admin user. I guess that's best for security reasons, right?
### Question
Thus there is my question: Is there some way to make conditional write permissions in rethinkDB, aside from the static CRUD-styled ones? If not, is there any way to get the user that is issuing a change I am the admin user? It can be a semi ad-hoc method on this last one.

Sorry if this is out of place and I am also willing to accept the answer "This should be asked on SO!!". Figured that asking it here may also help other people who may need these crazy permission enforcements for their own enterprise systems. Just for the sake of completeness, the actual stack is a common Java + SQL one, similar to my option A.

**Comment by srh** [comment]
In 2.4, which hasn't been released yet, there's a feature called write hooks, which lets you reject writes.  It wouldn't let you implement columnar permissions or fancier permissions though, because it doesn't pass user information to the write.  I suppose there's a way you could hack it with write hooks by creating a special password that the write hook knows about, and using some sort of one-way function (because I think the write hook source is publicly accessible to all users), and stripping out the password before writing.  But that's complicated and error-prone, and probably what you want is simply to pass user information to the write hook.

**Comment by thelinuxlich** [comment]
You could pass the user role to the write hook function and check a static dictionary inside the function, then strip the data of the role parameter

**Comment by jordaorodolfo** [comment]
thanks a lot, @srh and @thelinuxlich ! Yes, upon seing this lastest post in the rethinkDB blog I realise that I cloud cook up a hack using some sort of "auth Stamp" for any document, then listen to all tables and apply any authorization necessary, following the 'B' path of solution I proposed. It's shame that there is no well-developed official client for a pure browser enviroment, but only some community drivers admitedly on alpha stage... that would rock my socks. Probably this issue can be considered closed, as it was more of a newbie question than anything else.

**Comment by thelinuxlich** [comment]
There are nice projects for client-server integration, take a look at https://github.com/crrobinson14/vue-rethinkdb. for example
