### ISSUE TITLE
RethinkDB Development Status

### ISSUE THREAD

**Issue by lsabi** [rethinkdb/rethinkdb#6714]
Hello to everyone,

I've been with Rethinkdb for quite a long time (1-2 years).

Very few commits have been done in the past months and this makes me wonder about the current status of development. New users could be scared from this situation and existing users may move towards another database, due to uncertainty.

So my question is: is there a roadmap or a status of the development of the project? Not knowing the source code makes it difficult to understand which improvements have been done and if those improvements are only bug fixes or actual improvements for a newer version.

Thanks.

**Comment by srh** [comment]
Hi @lsabi.  Right now I am getting paid to build an improvement to the RethinkDB web UI which hopefully will be part of the 2.4 release.  And it looks like a 2.4 release will happen soon.  Most notably, this would provide write hooks.

**Comment by lsabi** [comment]
Hi @srh . That's great news! Looking forward testing the new release.

Thanks

**Comment by pdevine** [comment]
@lsabi any idea when the release will be coming?  Also, are there enough resources at this point to properly test any release before it goes out?

**Comment by lsabi** [comment]
@pdevine I'm not a developer of the project. It's risky to use a database whose development is idle, so I thought to ask for some news.

Though, I'm glad to see that there are also other people caring about this project.

**Comment by srh** [comment]
Hey @pdevine, I'm working on it :-]

**Comment by srh** [comment]
This is NOT a release, or even a release candidate, because who am I to designate these things?  But in a bit more of a hey-it's-a-free-country sort of way, here is a package for people that want to try out the future 2.4.x release on Ubuntu 18.04 ("Bionic").

https://github.com/srh/rethinkdb/releases/tag/v2.4.0-srh-special-1

I uploaded a Bionic package because @pashazz has been asking for that for a while.

If you ask me for another platform I might build it for you.

**Comment by pdevine** [comment]
@srh any chance for a Docker image?

**Comment by srh** [comment]
@pdevine Maybe that would be a good way for me to learn the basics of Docker usage... but I don't have a timetable for that right now.

**Comment by jboneu** [comment]
Thank you @srh for continuing with this amazing project. And @pashazz for insisting with the Bionic package, @srh please can we talk about this, and probably I can put some hours on making the docker image for enabling some simpler installation.
Otherwise let me know what other ways for helping ;)

**Comment by srh** [comment]
@jboneu There exists a repo https://github.com/rethinkdb/rethinkdb-dockerfiles so I guess that would be the place to start.

**Comment by jsieler** [comment]
Is there some progress on new version or some news?

**Comment by srh** [comment]
Some news coming shortly...

**Comment by v3ss0n** [comment]
Excited!!

**Comment by nicodmf** [comment]
@jboneu the official image in on dockerhub and works fine : https://hub.docker.com/_/rethinkdb/

**Comment by srh** [comment]
See my comment here: https://github.com/rethinkdb/rethinkdb/issues/6747#issuecomment-509846944

**Comment by gabor-boros** [comment]
As we release our [latest blog post](https://rethinkdb.com/blog/technical-update-keep-the-ball-rolling) about technical updates, I'm closing this issue. If you think I should not, let me know or open a new issue
