### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by audiodk** [rethinkdb/rethinkdb#6716]
I can not seem to get this to install on linux mint 19 or on debian 9.  Can someone point me in the direction to installing this on these systems?

**Comment by srh** [comment]
You can download a Debian 9 package from here: https://github.com/srh/rethinkdb/releases/tag/v2.3.6.srh.1

I haven't looked at what the source of Linux Mint 19 packages are but similarly, the package manager probably doesn't have a package for it.
