### ISSUE TITLE
Self built rethinkdb is not backupable

### ISSUE THREAD

**Issue by atassis** [rethinkdb/rethinkdb#6720]
Hello there. Trying to create the backup on selfbuilt rethinkdb. Receiving next error
```
rethinkdb-dump --password-file ./password.txt -c <HOST> 
NOTE: 'rethinkdb-dump' saves data and secondary indexes, but does *not* save
 cluster metadata.  You will need to recreate your cluster setup yourself after 
 you run 'rethinkdb-restore'.
Exporting to directory...
Error: Incompatible server version found, expected >= 1.16.0
Error: export failed
```
Here is the version output for our rethinkdb version
```
rethinkdb --version
rethinkdb 0.0-internal-unknown-fallback-fallback (CLANG 3.5.0 (tags/RELEASE_350/final))
```
Haven't found an info if we can set our own version for rethinkdb or rebuilding rethinkdb-dump script without checking the version of the DB.
How can we start collecting backups for our own version of Rethink?

**Comment by nha** [comment]
@atassis https://github.com/rethinkdb/rethinkdb-python/blob/086a7681a9e8efd42c15f78d33c94843f1bf9880/rethinkdb/utils_common.py#L127-L138

**Comment by srh** [comment]
@atassis Usually self-built RethinkDB's have some version string that starts with 2.3 or something like that.  Getting 0.0 is notable.  Are you building from a tarball, and not a git checkout? You can set your own version for RethinkDB, the option is PVERSION on some package building commands, but using `git tag` on the current commit would definitely work.

**Comment by atassis** [comment]
@srh I have cloned a repo locally, cherrypicked the commit to fix the changefeed bug, added a Dockerfile and build it.
All the steps made you can see in the next [repo](https://github.com/WASD-Team/rethinkdb/)

**Comment by atassis** [comment]
@nha thanks in advance! will try building our own utility

**Comment by gabor-boros** [comment]
Hey @atassis ,
Is there anything else we can help you with? If yes please reopen the issue or open a new one, otherwise, I'm closing this issue 🙏
