### ISSUE TITLE
AttributeError: module 'rethinkdb' has no attribute 'table'

### ISSUE THREAD

**Issue by richardjohnson23** [rethinkdb/rethinkdb#6722]
keys = r.table('keys').filter(r.row['owner'] == user['id']).run(get_db())
AttributeError: module 'rethinkdb' has no attribute 'table'

code:
def dashboard():
    user = session['user']
    is_admin = user['id'] in config['admins']
    keys = r.table('keys').filter(r.row['owner'] == user['id']).run(get_db())
    return render_template('dashboard.html', name=user['username'], keys=keys, admin=is_admin)

I imported the rethinkdb by "import rethinkdb as r"
I'm using Python 3.6.8, CentOS 6.9, rethinkdb 2.3.6 (GCC 4.8.2), the module was installed by "pip3.6 install rethinkdb".

**Comment by codeskyblue** [comment]
The last python-rethinkdb changes its usage. Bellow is the difference.

Old
```python
import rethinkdb as r
```

New

```python
from rethinkdb import RethinkDB; r = RethinkDB()
```

**Comment by richardjohnson23** [comment]
thanks, solved!
