### ISSUE TITLE
Error when running rethinkdb dump

### ISSUE THREAD

**Issue by zemuldo** [rethinkdb/rethinkdb#6724]
Hi I am trying to dump my data which sits in a 5 servers cluster each with rethinkdb 2.3.6.
I initially tried running  ```rethinkdb dump``` but got missing rethinkdb-dump command. I had to install rethinkdb via python-pip.
Now I am getting this and I dont know what this means
```
NOTE: 'rethinkdb-dump' saves data, secondary indexes, and write hooks, but does *not* save
            cluster metadata.  You will need to recreate your cluster setup yourself after
            you run 'rethinkdb-restore'.
  Exporting to temporary directory...
No handlers could be found for logger "rethinkdb.logger"
Error: export failed, 'module' object has no attribute 'get_context'
```

I have tried what this [issue](https://github.com/rethinkdb/rethinkdb/issues/2234) says and still nothing.

**Comment by srh** [comment]
Try https://spectrum.chat/rethinkdb for help.

**Comment by zemuldo** [comment]
@srh Thanks for noting that. I installed version 2.3.0 of the python driver and the dump worked.
