### ISSUE TITLE
Not Installing on Linux mint 19

### ISSUE THREAD

**Issue by hamidabdulmalik** [rethinkdb/rethinkdb#6728]
Hi. I have been trying to install rethinkdb on linux mint 19 for a couple of days now, but it has not worked. Can you please point me to the right direction or are there no builds for linux mint 19? On the RethinkDB install website, there seem to be no install directives for linux mint 19

**Comment by srh** [comment]
Linux Mint 19 is Ubuntu Bionic, right?  You can use the Bionic image from https://github.com/srh/rethinkdb/releases/tag/v2.3.6.srh.1 .

**Comment by gabor-boros** [comment]
I guess this issue can be closed, so I'm closing it. Feel free to reopen it.

**Comment by srh** [comment]
Just adding that the proper way to get a bionic install is now to use the instructions at https://rethinkdb.com/docs/install/ubuntu/ , because a 2.3.7 package was made for Bionic.
