### ISSUE TITLE
Using Failify for e2e testing of RethinkDB

### ISSUE THREAD

**Issue by arminbalalaie** [rethinkdb/rethinkdb#6729]
I am the author of Failify, a test framework for end-to-end testing of distributed systems. Failify can be used to deterministically inject failures during a normal test case execution. Currently, node failure, network partition, network delay, network packet loss, and clock drift is supported. For a few supported languages (right now, Java and Scala), it is possible to enforce a specific order between nodes in order to reproduce a specific time-sensitive scenario and inject failures before or after a specific method is called when a specific stack trace is present. You can find more information in https://failify.io.

Please let me know if you want to give it a try.

**Comment by srh** [comment]
Sounds cool.

**Comment by arminbalalaie** [comment]
Here is an example https://github.com/failify/example-rethinkdb. Please note that for simplicity purposes I am installing rethinkdb through apt in debian (check docker/Dockerfile). However, it is easily possible to add a compiled executable to a service through Failify's API (please check https://docs.failify.io for more information ). The main directory you want to take a look at is ``src/test/java/io/failify/examples/rethinkdb/`` and ``FailifyHelper.java`` and ``SampleTest.java`` files.

**Comment by arminbalalaie** [comment]
I updated the repo and added the build directory of a build on debian jessie for version 2.3.6 to demonstrate how the created artifacts in the build stage can be used in the Failify's test cases.

**Comment by gabor-boros** [comment]
@srh Should we take a closer look at this?

**Comment by srh** [comment]
That's not what I would do. Somebody running the product or considering using it might want to run something like this.  Last I checked, RethinkDB had been run with Jepsen, of course a long time ago.  I don't know what the state of the art is.

**Comment by gabor-boros** [comment]
Than how about closing this and reopen if needed?

**Comment by srh** [comment]
That depends on how you want to handle issues.

**Comment by gabor-boros** [comment]
Since the code is not updated in the past 3 years for failify and the domain is not available anymore either, it seems that time solved the question about the state of this issues. Closing.
