### ISSUE TITLE
Please provide more recent Ubuntu / Debian packages

### ISSUE THREAD

**Issue by jankeromnes** [rethinkdb/rethinkdb#6734]
https://rethinkdb.com/docs/install/ubuntu/#with-binaries says:

> We provide binaries for both 32-bit and 64-bit Ubuntu Precise and above (>= 12.04).

And tells you to do:

```bash
source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
```

However, the last update to http://download.rethinkdb.com/apt/pool/ was on `17-Jul-2017`, so these instructions currently break for:
- Ubuntu 17.10 Artful (already end-of-life)
- Ubuntu 18.04 Bionic LTS
- Ubuntu 18.10 Cosmic
- Ubuntu 19.04 Disco
- etc.

Please upload more recent Ubuntu / Debian packages to http://download.rethinkdb.com/apt/.

Also, maybe you could automatically build `.deb` files with each Release, for example with CircleCI?

**Comment by gabor-boros** [comment]
Hello @jankeromnes,
Bionic image is available now on the download server. We will publish disco package soon, so I’m closing this issue if you have no concerns

**Comment by jankeromnes** [comment]
Great news! Thanks a lot @gabor-boros
