### ISSUE TITLE
"n" element in response from server meaning?

### ISSUE THREAD

**Issue by natasanderson** [rethinkdb/rethinkdb#6740]
Hi,
I'm implementing my own driver against RethinkDB 2.3.6 the protocol version I'm using is V0.4
Everything seems to work fine, but I receive a response from the server with the following fields
"t","r","n"
And I cannot find any documentation in regards of the "n" field.

In the documentation https://www.rethinkdb.com/docs/writing-drivers/
all I found was this kind of response:

{
    t: 1,         // protodef.Response.ResponseType.SUCCESS_ATOM
    r: ["foo"]    // the response is the string 'foo"
} 

any help really appreciated.

thanks,
N.

**Comment by bchavez** [comment]
`n` is the response notes key:

https://github.com/rethinkdb/rethinkdb/blob/85e842dbe30579bafd5ddc6103d575a3ed277ee1/src/client_protocol/json.cc#L165-L173

https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver/Net/Response.cs

https://github.com/bchavez/RethinkDb.Driver/blob/edd0c122695275779c7f6b6d6ce894734dcd17d6/Source/RethinkDb.Driver/Generated/Proto/ResponseNote.cs

https://github.com/bchavez/RethinkDb.Driver/blob/edd0c122695275779c7f6b6d6ce894734dcd17d6/Source/Templates/Metadata/proto_basic.json#L53-L58

Relates to some extra cursor metadata about the response for the driver.

**Comment by gabor-boros** [comment]
Thank you @bchavez for answering this ☺️
