### ISSUE TITLE
Rethinkdb fails to compile on Arch Linux

### ISSUE THREAD

**Issue by Cairo2k18** [rethinkdb/rethinkdb#6744]
Every time I try to compile rethinkdb from source for arch linux (according to the docs) it always fails, I have spent hours upon hours trying to get it to work, and it just doesn't.

**Error**
[https://hastebin.com/oboqiziqun.cpp](https://hastebin.com/oboqiziqun.cpp)

**Comment by srh** [comment]
@Cairo2k18  Hastebin is down for me.  I fixed #6732 in the v2.3.x branch.  If that doesn't work, please let me know.
