### ISSUE TITLE
Error when run rethinkdb dump

### ISSUE THREAD

**Issue by Ippman** [rethinkdb/rethinkdb#6745]
When I use command rethinkdb-dump, it shows like below:

> NOTE: 'rethinkdb-dump' saves data, secondary indexes, and write hooks, but does *not* save
            cluster metadata.  You will need to recreate your cluster setup yourself after
            you run 'rethinkdb-restore'.
  Exporting to temporary directory...
No handlers could be found for logger "rethinkdb.logger"
Error: export failed, 'module' object has no attribute 'get_context'

My path:
> echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

When I run: python -m rethinkdb.dump
> /usr/bin/python: No module named rethinkdb.dump

Please help me

**Comment by srh** [comment]
What version, what platform, and how did you install rethinkdb?
