### ISSUE TITLE
Error compiling rethinkdb-2.3.6 on ARM (RazPi3B+) in .... client_protocol/server.o

### ISSUE THREAD

**Issue by zool2001** [rethinkdb/rethinkdb#6746]
I've tried all the suggested configure options which got me past most previous hiccups, but now consistently hitting this one:

Successful Configure Command:
./configure --with-system-malloc --allow-fetch --fetch protoc CXX=clang++

make error:
..............
    [114/424] CC build/release_clang_system/obj/client_protocol/server.o
In file included from src/client_protocol/server.cc:37:
In file included from ./src/rdb_protocol/env.hpp:21:
./src/rdb_protocol/datum_stream.hpp:839:16: warning: moving a local object in a
      return statement prevents copy elision [-Wpessimizing-move]
        return std::move(rget_items);
               ^
./src/rdb_protocol/datum_stream.hpp:839:16: note: remove std::move call here
        return std::move(rget_items);
               ^~~~~~~~~~          ~
src/client_protocol/server.cc:177:16: error: variable has incomplete type
      'EVP_MD_CTX' (aka 'evp_md_ctx_st')
    EVP_MD_CTX c;
               ^
/usr/local/include/openssl/ossl_typ.h:92:16: note: forward declaration of
      'evp_md_ctx_st'
typedef struct evp_md_ctx_st EVP_MD_CTX;
               ^
1 warning and 1 error generated.
src/build.mk:390: recipe for target 'build/release_clang_system/obj/client_protocol/server.o' failed
make[1]: *** [build/release_clang_system/obj/client_protocol/server.o] Error 1
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2
.........................................
Any suggestions?

**Comment by jsieler** [comment]
Can you please provide all steps you did? Which distro are you using?

PS: Join Discord if you want faster help https://discord.gg/dhTESz4

**Comment by srh** [comment]
This is probably fixed in v2.3.x branch.  There is already a discord server at https://discord.gg/ZeEq5TE

**Comment by gabor-boros** [comment]
@zool2001 Since I updated the installation instructions for 2.3.7 on the website for RPI and we had a similar resolved issue some days ago, I’m closing this issue. If you still can not progress even with the new instructions reach us out or reopen the issue. Thanks 🙏
