### ISSUE TITLE
unable to install rethinkdb on ubuntu 19.04

### ISSUE THREAD

**Issue by shaheerakr** [rethinkdb/rethinkdb#6748]
please provide the disco release for rethinkdb

**Comment by 4ley** [comment]
same here

**Comment by jsieler** [comment]
If you want you may join our Discord channel here so we might find a solutions together.
https://discord.gg/dhTESz4

**Comment by srh** [comment]
I have uploaded Disco deb files to the v2.3.6.srh.1 release:

https://github.com/srh/rethinkdb/releases/v2.3.6.srh.1

**Comment by shaheerakr** [comment]
thank you. any news on an official release?
