### ISSUE TITLE
Connect to existing database using it's IP Address {RethinkDB}{Python}

### ISSUE THREAD

**Issue by ayushiee** [rethinkdb/rethinkdb#6749]
I have just started using RethinkDB with Python and am trying to set up a connection to an already existing database at a remote location with information such as it's IP Address, user, database, password etc.
Please help me with the set up code.

**Comment by jsieler** [comment]
Where is your problem? Are you getting some kind of error or what?

**Comment by gabor-boros** [comment]
Hello @ayushiee,

I would suggest to take a look on https://github.com/rethinkdb/rethinkdb-python/blob/master/README.md#quickstart

Although this example only uses the host, you can define port, user, etc as described at https://rethinkdb.com/api/python/connect/
