### ISSUE TITLE
How to run rethinkdb server in background

### ISSUE THREAD

**Issue by bn600** [rethinkdb/rethinkdb#6753]
I'm using forever command to run rethink in the background but it's not working.
if I run  `rethinkdb` , it runs on the port 8080 but when I come out of it, the server stops
Can I get command to run rethinkdb in the background.

**Comment by gabor-boros** [comment]
Hello @bn600,

Thank you for your question. You could put `&` at the end of the command but that run will not live longer than your session.

I think you are looking for this https://rethinkdb.com/docs/start-on-startup/. This is about start on startup but you can disable auto start on OS level.

**Comment by srh** [comment]
nohup has always worked for me, but for anything serious you'll want to set it up to restart after a reboot.
