### ISSUE TITLE
Cannot navigate on Rethinkdb Home Page

### ISSUE THREAD

**Issue by namKolo** [rethinkdb/rethinkdb#6762]
Hi bros.

When I accessed to this url https://rethinkdb.com/api/javascript/, then I cannot navigate to any pages. Please help me take a look. Super thanks.

![image](https://user-images.githubusercontent.com/16164170/62855230-deb9dc80-bd1b-11e9-94e1-6130d36f72f9.png)

![image](https://user-images.githubusercontent.com/16164170/62855268-fbeeab00-bd1b-11e9-8484-4bf4b1ae9c27.png)

**Comment by gabor-boros** [comment]
@namKolo Thank you for reporting this issue! I just realized this too. I'll check this issue as soon as I can!

**Comment by gabor-boros** [comment]
Fixed by https://github.com/rethinkdb/www/pull/231

**Comment by namKolo** [comment]
@gabor-boros  Thanks bro. 👍
