### ISSUE TITLE
rethinkdb.errors.ReqlQueryLogicError: Primary key too long

### ISSUE THREAD

**Issue by codeliger** [rethinkdb/rethinkdb#6763]
I am getting this error when doing an get_all select statement

None of my primary keys are very long, why would I be getting this error?

```
    rethinkdb.errors.ReqlQueryLogicError: Primary key too long (max 127 characters): [
            "1AmQzdPWOnGje",
            "1AmjzdNGLmxQe",
            "1AmQzOowOYeKe",
            "1AmQzOJaxmwKe",
            "1AmQzdyaaZqje",
            "1AmQzdPlBJJje",
            "1DLEBADyNNWjJ",
            "1DLEBgVngvrQJ",
            "1DLEBDnODbqKJ",
            "1AmjzdPmwwdQe",
            "1AmjzdyaDdlQe",
            "1DLEBgPOmDpQJ"
    ] in:
    r.db('database').table('user').get_all(['1AmQzdPWOnGje', '1AmjzdNGLmxQe', '1AmQzOowOYeKe', '1AmQzOJaxmwKe', '1AmQzdyaaZqje', '1AmQzdPlBJJje', '1DLEBADyNNWjJ', '1DLEBgVngvrQJ', '1DLEBDnODbqKJ', '1AmjzdPmwwdQe', '1AmjzdyaDdlQe', '1DLEBgPOmDpQJ']).update(r.expr({'_deleted': True}))
```

**Comment by srh** [comment]
The ReQL command `get_all` takes each key parameter separately.  So you would need to write `.get_all('a', 'b', 'c', ..., 'z')`.  Or you might need to (or want to) use `r.args` and write `.get_all(r.args(['a', 'b', 'c', ..., 'z']))`.

I think one reason for this is that the API was designed with secondary index usage, with a single key, in mind.

Arrays can be primary key values.  Your error message is the result of treating the array as the primary key value.  When serialized to the internal primary key representation, it uses more than 127 bytes.
