### ISSUE TITLE
update.rethinkdb.com SSL certificate has expired

### ISSUE THREAD

**Issue by chrisvariety** [rethinkdb/rethinkdb#6764]
![image](https://user-images.githubusercontent.com/44855/63461666-19f89180-c427-11e9-8611-659c6ecca567.png)

https://update.rethinkdb.com/ is used by the RethinkDB server itself, so you'll see warnings like this in the server log: `warn: Problem when checking for new versions of RethinkDB: HTTP request to update.rethinkdb.com failed.`

Happy to help here any way I can, we use RethinkDB heavily !

**Comment by srh** [comment]
Thanks for the issue report.  This was also about to hit the download server (download.rethinkdb.com), but that got migrated to a new machine with a new certificate.  The same action might be appropriate for the update server.

Maybe update checking should be removed in a future version of RethinkDB.  I would guess the feature's real purpose was to gather usage statistics.

Before this gets fixed, you can run with the `--no-update-check` to keep your logs cleaner.

**Comment by srh** [comment]
People might hit #6719 more frequently because of this.  So that's a reason to get this fixed.

**Comment by gabor-boros** [comment]
@srh and @chrisvariety, I'll try to fix the issue as soon as I can, in worst case tomorrow late afternoon, but I'll keep you updated

**Comment by chrisvariety** [comment]
Thanks so much 🙏

**Comment by gabor-boros** [comment]
@chrisvariety, I did the necessary changes today early morning, so it should be ok now. Could you please check if you still get the error message?

**Comment by srh** [comment]
I don't get the error message any more.  Thanks @gabor-boros.
