### ISSUE TITLE
Need a help to design a database model for a complex scenario.

### ISSUE THREAD

**Issue by aaamitsingh** [rethinkdb/rethinkdb#6771]
Hi friends, I am new to this DB and I need your help to design the DB for the given scenario.

Scenario 1:
Multiple locations have multiple Company and the companies have many buildings/block, and many of them have multiple floors and the floors have many rooms and rooms have multiple zones and every zone have multiple seats and one laptop is allocated to each seat.

Scenario 2:
Multiple locations have multiple buildings, and the building has multiple floors and in every floors there is one or many companies and the company have many rooms and rooms have multiple zones and every zone have multiple seats and one laptop is allocated to each seat.

The database should store:
1. GPS value of the location,
2. building/block details to that location like the list of building, building's name, etc
3. floor details like list of there floors, floor number/name, floor plan images corresponding to that, etc
4. list of there rooms, room number/name and etc,
5. list of there zones, zones number/name and etc,
6. list of there seats, seat number/name and etc,
7. laptop details like laptop issue date, laptop configuration

Is there any single way to deal with both the scenario? Where I can allocate a laptop to a set and later I can fetch the complete laptop location by laptop id and I can see the list of laptop by zone, room, floor, building and company.

Any suggestions would be much appreciated!

**Comment by srh** [comment]
What database engine are you familiar with?  How would you do this in that?  What problems does RethinkDB pose for that solution, that you would need to work around?

**Comment by aaamitsingh** [comment]
HI @srh I'm bit familiar with MySQL. In MySQL I can do thin in this way:

Location:
LocationID(PK)
LocationName
Latitude
Longitude

Building:
BuildingID(PK)
LocationID(FK)
Building name
etc

Floors:
FloorID(PK)
BuildingID(FK)
FloorName
etc

FloorPlans:
FloorPlanID(PK)
FloorID(FK)
FloorPlanName
FloorPlanImage

Rooms:
RoomID(PK)
FloorID(FK)
RoomNumber
Latitude
Longitude
RoomSize
etc

Zones:
ZoneID(PK)
RoomID(FK)
ZoneNumber
etc

.......so on

I don't know how to this in RethinkDb. There is no problem with the rethink db I need help with better approach. And I'm going to use rethinkDb for the first time so can you help me?

**Comment by srh** [comment]
Well, you could do it that way in RethinkDB.  Unless the mutations you need to make would be inappropriate without transactions.  Or if your queries would be inefficient.

**Comment by aaamitsingh** [comment]
thanks
