### ISSUE TITLE
DigitalOcean RethinkDB Marketplace image update

### ISSUE THREAD

**Issue by gabor-boros** [rethinkdb/rethinkdb#6783]
Based on DigitalOcean's analytics and suggestions we would need to do the following action items:
- [x] Update the Getting started description on Marketplace
- [x] Update the image on the marketplace after syncing with @srh 
- [x] Mention the DigitalOcean 1-Click App on the website, documentations and in your community
- [x] Add referral URL for RethinkDB DO 1-click image on Marketplace
- [x] Have a blog post about v.2.4-beta DigitalOcean image

**Comment by srh** [comment]
What does this have to do with releasing 2.4?

**Comment by gabor-boros** [comment]
@srh basically this PR a public reminder for me what to do on DO marketplace when we are releasing v2.4.

**Comment by gabor-boros** [comment]
DO marketplace image for Fantasia 2.3.7 is out 🎉 Waiting for the release of 2.4.0 and I'll update that too.

**Comment by gabor-boros** [comment]
2.4.0 is in pending state and will be approved soon by DO
