### ISSUE TITLE
Question regarding recomputation of changefeeds on queries

### ISSUE THREAD

**Issue by sasasavic82** [rethinkdb/rethinkdb#6784]
In this article: https://rethinkdb.com/blog/realtime-web/

There is a snippet of code:

`r.table('gameplays').order_by(index=r.desc('score')).limit(5).changes().run(conn)`

With the below statement:

> Any time the database gets updated with a new gameplay, this query will inform the developer which items dropped off the leaderboard, and which new gameplays should be included. Internally, the database doesn’t merely rerun the query any time there is a change to the gameplays table – the changefeeds are recomputed incrementally and efficiently.

Is this statement true for **all queries**, or just a subset of queries?

If it is a subset of queries, which ones?

**Comment by srh** [comment]
All queries, I think.
