### ISSUE TITLE
Not a TIME pseudotype - retrieving data by timestamps?

### ISSUE THREAD

**Issue by lautiamkok** [rethinkdb/rethinkdb#6794]
I create timestamp using JavaScript's Date:

`    let timestamp = Date.now()`

So I would timestamps like this:

```
    1574651336667
    1574651408395
    1574651361751

```
When I want to retrieve the rows that were inserted on the 25th:

```
    r.table("users").filter(
        r.row("timestamp").day().eq(25)
    ).run(conn, callback)
```

But I get this error:

`Not a TIME pseudotype: `1574651336667` in:\nr.table(\"users\").filter(function(var_0) {`

what does it mean? 

What should I do to retrieve the data correctly with timestamp?

**Comment by srh** [comment]
Use the ReQL command that converts from epoch time to a time value, and be sure to be careful about time zones when checking the day.

**Comment by lautiamkok** [comment]
@srh 

The timestamps that I stored are:

```
1574651336667
1574651408395
1574651361751

```
But [epochTime](https://rethinkdb.com/api/javascript/epoch_time/) method only accepts timestamps in less digit as follows:

`531360000`

That is the problem

So the time value I get from the conversion is something like this below:

+051869-02-01T10:18:06.000Z

Unless there are other ways doing it, storing timestamp like this `531360000` does not seem standard.

**Comment by lautiamkok** [comment]
So the hack I do is:

`r.epochTime(doc('timestamp').div(1000))`

**Comment by srh** [comment]
That's the way to do it.
