### ISSUE TITLE
2.3.7 Changelog

### ISSUE THREAD

**Issue by Cherry** [rethinkdb/rethinkdb#6802]
Congrats on the 2.3.7 release - this is seriously awesome to see!

Is there a changelog available for this version? I don't see anything on the [Releases page](https://github.com/rethinkdb/rethinkdb/releases) or in the [NOTES.md](https://github.com/rethinkdb/rethinkdb/blob/next/NOTES.md) file.

**Comment by gabor-boros** [comment]
@srh do you have some?

**Comment by srh** [comment]
A few bugfixes slipped in, and there are fixes to get RethinkDB building on newer platforms.  Probably the most important change are fixes to keep RethinkDB compiling with newer OpenSSL versions.
