### ISSUE TITLE
Windows installer not downloadable

### ISSUE THREAD

**Issue by paavalan** [rethinkdb/rethinkdb#6814]
link getting 404 error
https://download.rethinkdb.com/windows/rethinkdb-2.4.0.zip

**Comment by srh** [comment]
Ah, there is no Windows installer.

**Comment by paavalan** [comment]
Oh ok. then any one fix the link url to previous version in this page https://rethinkdb.com/docs/install/windows/

**Comment by gabor-boros** [comment]
Issue created for this: https://github.com/rethinkdb/docs/issues/1258

**Comment by srh** [comment]
Just as some general info:  I was able to build 2.4 on Windows in the past.  Generally speaking, it is possible, if you follow the instructions, and work around any annoying problems when it fails.  It is just a bunch of work that I don't feel like doing right now.

**Comment by gabor-boros** [comment]
@srh I can confirm. I was almost able to build that too. The main problem is gclient in Cygwin, but after some investigation it can be worked around easily (clone their repo and add that to the PATH basically). Although it was almost successful, I have no time for that until end of January.

**Comment by mreinstein** [comment]
can we fix the link on the website at least? It looks very amateurish to have a link to a download the doesn't exist. Seems like a simple fix to at least remove the link for now.

**Comment by srh** [comment]
On the other hand, the broken link on the website has caused a lot of people to post issues complaining about it.  This will probably make getting a Windows build happen sooner.

**Comment by mreinstein** [comment]
> the broken link on the website has caused a lot of people to post issues complaining about it.

Perhaps a nice compromise would be to replace the broken link with a little text, stating " a windows build isn't available yet. go here if you'd like to request one" (which could point at rethink's github issues tracker.  Having a link that's been broken for months gives off some abandonware vibes.

**Comment by nlac** [comment]
For now, the server lists the available downloadable binaries: [https://download.rethinkdb.com/windows/](https://download.rethinkdb.com/windows/)

**Comment by srh** [comment]
I made a branch that removes JavaScript support (that is, `r.js` support) from RethinkDB and strips out v8 from the build system, based on v2.4.x.  That might work around those gclient issues.  So you might want to see if that can build on Windows. https://github.com/srh/rethinkdb/tree/srh/24x/no_js

**Comment by srh** [comment]
Some source file changes were also necessary to get it building.  I have uploaded an unofficial build at https://github.com/srh/rethinkdb/releases/tag/v2.4.0-srh-win-1 .

**Comment by arvind1kumar1** [comment]
get rethinkdb from 
https://github.com/rethinkdb/rethinkdb/tags

**Comment by Edodums** [comment]
So, Rethinkdb is no longer supported on Windows 😢 ?
I've "installed" it on docker but the docs don't guide you properly throughtout all the steps you have to do to make it

**Comment by clovergaze** [comment]
@Edodums Please refer to [this answer](https://groups.google.com/g/rethinkdb/c/KaR8JRGH66I) in the Google group if you need a working Windows version of RethinkDB.

**Comment by ramjibs** [comment]
> link getting 404 error
> https://download.rethinkdb.com/windows/rethinkdb-2.4.0.zip

you can download the windows version by changing the link to https://download.rethinkdb.com/repository/raw/windows/rethinkdb-2.3.6.zip

**Comment by mreinstein** [comment]
1 year later and we can't or won't fix a broken download link in the documentation. Talk about a perfect metaphor for the state of rethinkdb. 🤦

**Comment by gptshubham595** [comment]
You can check here all versions 2.4 sadly no
https://download.rethinkdb.com/#browse/search=keyword%3Dwindows:c770169c0b2e3ed83511d7b66af0a75c

**Comment by nbaua** [comment]
I am rethinking to use or not to use RethinkDB, can even deploy a build for windows and update the repository for the same.
@admin - I guess you should decline the windows as supported platform so that at least we are aware, that you've died in 2019 for real.

**Comment by srh** [comment]
I have heard that RethinkDB 2.4.2 runs fine on WSL 2.  That might be a good solution for Windows users going forward.

**Comment by srh** [comment]
I just noticed this -- windows support has been implemented in v2.4.x.  Amazing how #7083 got merged (by me) but still there are no binaries uploaded (by me).

**Comment by srh** [comment]
The Windows 2.4.3 build is being released a bit before the "official" 2.4.3 release -- it's up at

https://download.rethinkdb.com/repository/raw/windows/rethinkdb-2.4.3.zip .
