### ISSUE TITLE
404 https://rethinkdb.com/docs/java/

### ISSUE THREAD

**Issue by edwinhollen** [rethinkdb/rethinkdb#6818]
1. Navigate to https://rethinkdb.com/docs/install-drivers
2. Click "Java"
3. 404: https://rethinkdb.com/docs/java/

I think it should redirect here: 
https://rethinkdb.com/docs/install-drivers/java/

**Comment by srh** [comment]
Looks like https://rethinkdb.com/docs/install-drivers/ is the correct URL, and it's using a relative link (and you followed the one link to that page which omits the slash).  Closing because this should be in the rethinkdb/www repo, but don't bother making another ticket, because I'll push a fix.
