### ISSUE TITLE
Problems with buffered IO

### ISSUE THREAD

**Issue by sholladay** [rethinkdb/rethinkdb#6819]
RethinkDB 2.4 broke my app's tests, which read RethinkDB's stdout stream to wait for the "Server ready" text before attempting to connect to it.

This is apparently caused by a change to how RethinkDB buffers its console output.

via @srh on Slack:

> The difference can also be observed by running `rethinkdb | cat` on v2.3.x and v2.4.0.

> A write system call got replaced with an fwrite at commit/line https://github.com/rethinkdb/rethinkdb/commit/6455c907672#diff-ecd09eaab98f8bf01f631c194cd5c675R475 .  So it is performing buffered I/O to the console without flushing.  A call to fflush(write_stream) fixes this and should be added.

**Comment by srh** [comment]
For those wondering, this happened because glibc's `stdout` changes its buffering behavior depending on whether the stdout file descriptor is a TTY or not.

**Comment by gabor-boros** [comment]
@srh Isn't [this](00f0236f020f530da2fafe65a90a7a4330e15e69) commit resolves this issue?
