### ISSUE TITLE
windows install showing 404

### ISSUE THREAD

**Issue by seeyouin2x5x** [rethinkdb/rethinkdb#6821]
Hey guys the windows download link isn't working.
https://download.rethinkdb.com/windows/rethinkdb-2.4.0.zip

**Comment by gabor-boros** [comment]
Hello @seeyouin2x5x , I'm closing this issue because it is a duplicate of https://github.com/rethinkdb/rethinkdb/issues/6814. We will mitigate this issue as soon as we can
