### ISSUE TITLE
Unable to download 

### ISSUE THREAD

**Issue by iiRoceteLAWS** [rethinkdb/rethinkdb#6823]
I am unable to download the windows version.

**Comment by marianpekar** [comment]
Yes, download link at https://rethinkdb.com/docs/install/windows/ points to rethinkdb-2.4.0.zip which  doesn't exist.

You can either download 2.3.6 

https://download.rethinkdb.com/windows/rethinkdb-2.3.6.zip  

or compile from source.

**Comment by gabor-boros** [comment]
Hello @iiRoceteLAWS,
This is a known "issue". As far as I know some our community members helping us out to create the windows build.

The open issue (which will be updated) is https://github.com/rethinkdb/rethinkdb/issues/6814
