### ISSUE TITLE
Web GUI does not allow hyphens in table names.

### ISSUE THREAD

**Issue by RonnieSan** [rethinkdb/rethinkdb#6828]
When creating a new table with a hyphen in the name in the GUI, validation pops up saying:
"You can only use alphanumeric characters and underscores for a table's name."

**Comment by srh** [comment]
IIRC the history behind this is that at one point hyphens were not allowed.  I guess the web UI has its own copy of that logic, which is out of date.

**Comment by jcs224** [comment]
So, I guess this is fixed?

**Comment by srh** [comment]
It might need to be merged into `next`, I don't know.

**Comment by gabor-boros** [comment]
Yes it is fixed.

<img width="1003" alt="Screenshot 2022-05-03 at 11 29 17" src="https://user-images.githubusercontent.com/19173947/166431557-6d9c8a07-fc19-41bc-955c-4a1aec87ec60.png">
