### ISSUE TITLE
Rethindb v2.4 for Windows link not work

### ISSUE THREAD

**Issue by AhrimanSefid** [rethinkdb/rethinkdb#6835]
Hi
Rethindb v2.4 for Windows link not work
https://download.rethinkdb.com/windows/rethinkdb-2.4.0.zip
404 Not Found
nginx/1.14.0 (Ubuntu)

**Comment by modyamash** [comment]
yes the link is not working

**Comment by srh** [comment]
@AhrimanSefid Try my unofficial build at https://github.com/srh/rethinkdb/releases/tag/v2.4.0-srh-win-1

**Comment by lmdc45** [comment]
just wondering why 

> This release does not support the js ReQL command.

?

Thanks,

**Comment by gabor-boros** [comment]
duplicate of https://github.com/rethinkdb/rethinkdb/issues/6814
