### ISSUE TITLE
RethinkDB v2.4.0 for Windows not working

### ISSUE THREAD

**Issue by dps910** [rethinkdb/rethinkdb#6837]
Please change this to something else like "released soon" or something.

**Comment by AmilkarDev** [comment]
I downloaded the latest version for windows from here [https://download.rethinkdb.com/windows/](url)

I found the link in official github repository in [here](https://github.com/rethinkdb/rethinkdb-download)

**Comment by srh** [comment]
@dps910 and @AmilkarDev : Try my unofficial build at https://github.com/srh/rethinkdb/releases/tag/v2.4.0-srh-win-1

**Comment by davidroman0O** [comment]
Even the link on https://rethinkdb.com/docs/install/windows/ is dead ! :(

**Comment by gabor-boros** [comment]
Duplicate of https://github.com/rethinkdb/rethinkdb/issues/6814
