### ISSUE TITLE
Not working on android

### ISSUE THREAD

**Issue by lahiru04** [rethinkdb/rethinkdb#6838]
i tried this with android using java and i got following error

 com.rethinkdb.gen.exc.ReqlDriverError: java.security.spec.InvalidKeySpecException: Could not generate secret key

**Comment by adriantodt** [comment]
Can you please re-open the issue on https://github.com/rethinkdb/rethinkdb-java?
Specify your RethinkDB version and Android SDK version as well, please.

**Comment by adriantodt** [comment]
Is your Android SDK 26+? RethinkDB Handshake protocol requires PBKDF2WithHmacSHA256, which is implemented on API 26 according to https://developer.android.com/reference/javax/crypto/SecretKeyFactory

**Comment by adriantodt** [comment]
My final word about this: https://rethinkdb.com/docs/mobile-connections/

This issue can be closed.

**Comment by srh** [comment]
There are uses of Android besides end-user mobile phones.  Embedded devices, like in car head units.

**Comment by adriantodt** [comment]
> There are uses of Android besides end-user mobile phones. Embedded devices, like in car head units.

Embedded devices running Android also shouldn't be directly connecting, to be honest. Also, those devices also need to support API 26 or greater, which a lot of them don't.

I will gladly support PRs to the Java driver which targets compatibility with Android SDK 26, but I don't have an Android environiment set-up to test.

**Comment by srh** [comment]
Anybody interested in making a PR is free to do so in the https://github.com/rethinkdb/rethinkdb-java/ repo.  Closing.
