### ISSUE TITLE
CI/CD For RethinkDB

### ISSUE THREAD

**Issue by gabor-boros** [rethinkdb/rethinkdb#6840]
Simple CI/CD based on Circle CI to make sure we are running tests on changes.

**Comment by deleisha** [comment]
Does this means that we will have CI/CD running on circleCI ? If so, May I request the URL to check status. Tried searching online but did not get the URL.

**Comment by gabor-boros** [comment]
You are totally right. I'll need to adjust the README. Actually the configuration is set, but I forget to turn on the integration on CircleCi side. Shame, but at least it turned out. The link for the first run https://circleci.com/gh/rethinkdb/rethinkdb/1?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
