### ISSUE TITLE
Docker Image License

### ISSUE THREAD

**Issue by brecko** [rethinkdb/rethinkdb#6844]
Hi, I am thinking of using RethinkDB for a company product for which is hosted on-prem at our customer sites. The dockerhub license link for RethinkDB page goes to AGPLv3. Is this an oversite given the change in licensing to APL for RethinkDB?

If not, would you be able to let us know what is in the docker image that causes it to be Affero.

Thank you for any and all information provided.

**Comment by srh** [comment]
That is an oversight.  (I mean that as a statement about the world, not an official pronouncement.)  The images are built using the files at https://github.com/rethinkdb/rethinkdb-dockerfiles and you can take a look at what they contain.

**Comment by gabor-boros** [comment]
Since I fixed this issue I’m closing it

**Comment by srh** [comment]
Thanks @gabor-boros
