### ISSUE TITLE
Official .Net Driver for C# and F#

### ISSUE THREAD

**Issue by sirinath** [rethinkdb/rethinkdb#6848]
Can there be an official .net driver

**Comment by gabor-boros** [comment]
> Can there be an official .net driver

As far as I remember there is a C# driver.

**Comment by gabor-boros** [comment]
Here you can find most of the drivers: https://rethinkdb.com/docs/install-drivers/

I’m closing this issue since it is answered. If you have any questions please let us know. 😇

**Comment by sirinath** [comment]
One of the .Net drives is not updated. The other one has a restrictive license.
