### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by MIFD670** [rethinkdb/rethinkdb#6852]

**Comment by MIFD670** [comment]
While trying to download zip folder for Windows.

**Comment by ronen12333** [comment]
same

**Comment by McSneaky** [comment]
Duplicate of https://github.com/rethinkdb/rethinkdb/issues/6814

As last comment by srh in there you can see that he made unofficial build for Windows, you can test that out

**Comment by srh** [comment]
Thanks for the report and the answer.  Closing as duplicate.
