### ISSUE TITLE
Filter Function with default=true behaves strange

### ISSUE THREAD

**Issue by juli-p** [rethinkdb/rethinkdb#6853]
If I run a filter on a query with more than one field and the default option set to true every object that is missing one of the fields is returned even though the other fields do not meet the conditions.

`r.table('test').filter({ foo: 'bar', abc: true }, { default: true })`
also returns documents like
`{
   foo: 'notbar',
   ...
}`
if they do not have the field abc set.

In my opinion the default option should be applied to each field of the query individually rather than the whole query.

**Comment by srh** [comment]
You can get the behavior you want by chaining two filters together.

**Comment by gabor-boros** [comment]
@srh Since you answered this question shouldn't we close the issue due to lack of answer from the author?

**Comment by srh** [comment]
This is more of a reql proposal than a question, but a compatibility break like this is definitely not going to happen.
