### ISSUE TITLE
build fails on ubuntu because links to openssl have changed

### ISSUE THREAD

**Issue by buddudevelopers** [rethinkdb/rethinkdb#6854]
build fails because some links to dependencies were hard coded and they changed. In the file `/rethinkdb-2.4.0/mk/support/pkg/openssl.sh`

```
#These links are dead. So build fails
src_url="https://www.openssl.org/source/openssl-$version.tar.gz"
src_url_backup="ftp://ftp.openssl.org/source/openssl-$version.tar.gz"
```
```
#they have changed to 
src_url_backup="ftp://ftp.openssl.org/source/old/openssl-$version.tar.gz"
```

**Comment by rafaeltokyo** [comment]
can you send the your environment ?

**Comment by buddudevelopers** [comment]
ubuntu server 18.04.3 (LTS) x64 on digitalocean

**Comment by rafaeltokyo** [comment]
I simulated the environment here and managed to build normally, you use clang ?

**Comment by srh** [comment]
It's just the backup URL that's broken.  It's now

ftp://ftp.openssl.org/source/old/1.0.2/openssl-1.0.2l.tar.gz
