### ISSUE TITLE
Security Issue => All Database can delete

### ISSUE THREAD

**Issue by Pedroxam** [rethinkdb/rethinkdb#6857]
I maked a new script using rethinkdb, and i dont know why when i publish my new product on a market site, All database and table information can be deleted after some hour !
There is a big security hole and can access to users to delete all database and tabels !

And this problem will be appear when I moved from Windows to Linux.

This is not new problem, i see this many time in before. some users can easy erase database information !

its better to improve security !

Thanks !

**Comment by srh** [comment]
Please post steps to reproduce this issue in order to clarify what you're talking about.

**Comment by Pedroxam** [comment]
I just maked a simple script (user dashboard manager)  using nodejs and rethinkdb also websocket.
this script is very simple and no one can access to rethinkdb or any files in my host. 
users just can see info and edit. no one can delete anything from database and files, folders, i am complete sure about this. just admin can edit database after started rethinkdb --bind all in port 8080. also rethinkdb_data folder is protocted. just admin can edit database and folders from ssh.

I dont know how hackers can delete databases, tables, editing tables. sometimes tables names changed to acsii characters, (eg: &#027;).

just this. thanks

**Comment by srh** [comment]
Websocket has nothing to do with RethinkDB.  My guess is, the problem is with your application.  You should log all queries made to RethinkDB and use that information to identify how table names are getting altered.

**Comment by gabor-boros** [comment]
@Pedroxam In case you have the steps what @srh mentioned or you logged the queries (which would be a good practice), please report them as described here: https://rethinkdb.com/docs/vulnerabilities/.

Also, have you followed these instructions when you deployed your server to production? https://rethinkdb.com/docs/security/. Have you secured the driver port? In case you followed the instructions mentioned in the article, can you see anything correlating in the access logs of the Apache/Nginx/whatever reverse proxy's logs?

**Comment by Pedroxam** [comment]
HI, i checked every log access, apache log, but everything is normal, i don't see any securiy problem. also my server is from digitalocean and have high securiy. everyday i had to make table again :)

**Comment by Pedroxam** [comment]
My hard drive space is full. But I don't think that's why the tables is being erased.
