### ISSUE TITLE
Arch Linux

### ISSUE THREAD

**Issue by martijnmichel** [rethinkdb/rethinkdb#6858]
Currently there is no way (except for building from source) to install this on arch/manjaro because the AUR package is outdated.

**Comment by celogeek** [comment]
I'm working on fixing the build on Arch:

https://aur.archlinux.org/packages/rethinkdb/

**Comment by gabor-boros** [comment]
Closing this issue, as I can see, there is a fix already. Let me know if I should reopen

**Comment by srh** [comment]
See the commands and configure line in https://github.com/srh/rethinkdb-package-builder/tree/master/archlinux .
