### ISSUE TITLE
npm ERR! enoent ENOENT: no such file or directory

### ISSUE THREAD

**Issue by dipika21** [rethinkdb/rethinkdb#6866]
Hi,
I am running
`./configure --allow-fetch`
then `make` from code root directory 
facing below error:
`npm WARN enoent ENOENT: no such file or directory, open 'RethinkDB_RHEL_7.3/build/external/bluebird_2.9.32/package.json'
npm WARN bluebird_2.9.32 No description
npm WARN bluebird_2.9.32 No repository field.
npm WARN bluebird_2.9.32 No README data
npm WARN bluebird_2.9.32 No license field.

npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path RethinkDB_RHEL_7.3/build/external/bluebird_2.9.32/node_modules/.staging/bluebird-8b9865b5
npm ERR! dest RethinkDB_RHEL_7.3/external/bluebird_2.9.32/node_modules/bluebird
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, rename 'RethinkDB_RHEL_7.3/build/external/bluebird_2.9.32/node_modules/.staging/bluebird-8b9865b5' -> 'RethinkDB_RHEL_7.3/external/bluebird_2.9.32/node_modules/bluebird'
npm ERR! enoent This is related to npm not being able to find a file.`

**Comment by gabor-boros** [comment]
Hello @dipika21 ,

Since I can not see configure's output, what nodejs version do you have?

**Comment by dipika21** [comment]
node v 12.13.0
npm v 6.12.0

**Comment by gabor-boros** [comment]
Hello @dipika21 ,

Please try it with node 6.10. I know it’s old. It would be a great todo for us to bump.

**Comment by rafaeltokyo** [comment]
can you use nvm and install node 6.10.0, solve your problem.

**Comment by dipika21** [comment]
Thanks, "node v 6.10" solved above error.
