### ISSUE TITLE
Windows binary download link is broken

### ISSUE THREAD

**Issue by shomiron** [rethinkdb/rethinkdb#6881]
**Describe the bug**
The windows binary download link on the website yields a 404.

**To Reproduce**
1. TODO

**Expected behavior**

**Screenshots**

**System info**
 - OS: [e.g. macOS Mojave 10.14.3]
 - RethinkDB Version: [e.g. 2.4.0]

**Additional context**

**Comment by McSneaky** [comment]
There are several issues about it already :) Basically Windows build is missing
Meanwhile when and if it get's fixed @srh made **unofficial** build for Windows: https://github.com/srh/rethinkdb/releases/tag/v2.4.0-srh-win-1
