### ISSUE TITLE
Python 2 is EOL

### ISSUE THREAD

**Issue by nmeum** [rethinkdb/rethinkdb#6883]
Hello, I am currently working on [removing support for python 2 from the Alpine Linux distribution](https://gitlab.alpinelinux.org/alpine/aports/-/issues/11577) and rethinkdb is one of the few packages left which still requires python 2 as a compile-time dependency.

As I didn't manage to find any issue in your bug tracker reporting this, I wanted to inform you that python 2 is EOL and that it would be neat to upgrade to python 3 as soon as possible.

**Comment by velvetkeyboard** [comment]
Let me see if can help with that.

**Comment by gabor-boros** [comment]
Hello @nmeum,

We have an [issue](https://github.com/rethinkdb/rethinkdb-python/issues/168) for the Python client, but still in progress due to limited time.

I'll prioritize this issue to make sure we are not blocking Alpine in any terms. Please not that the project contains extremely lot of "complex" python files which complexity lies in that it's hard to validate it is working so it may take some time but I'll try to unblock you as soon as I can.

@velvetkeyboard every help is highly welcomed! 
FYI: @lsabi, we should jump on this first

**Comment by velvetkeyboard** [comment]
@gabor-boros Need some help to clarify which tests i should need to run to ensure full coverage.

**Comment by lsabi** [comment]
I guess it's all of them, although memcache and interface may be the less urgent as of now, at least, so I guess

**Comment by nmeum** [comment]
I tried to reproduce this bug, first wanted to upgrade our Alpine rethinkdb package to 2.4.0 as our currently packaged version (2.3.6) seems to still require python2 for the bundled node-gyp version (even with the referenced commit backported). While attempting to upgrade to 2.4.0 the building the bundeled nodejs fails to build with:

```
In file included from ../deps/v8/src/heap/objects-visiting.h:12,
                 from ../deps/v8/src/heap/object-stats.h:9,
                 from ../deps/v8/src/heap/heap.cc:27:
../deps/v8/src/objects-body-descriptors.h: In static member function 'static void v8::internal::FixedBodyDescriptor<start_offset, end_offset, size>::IterateBody(v8::internal::HeapObject*, int)':
../deps/v8/src/objects-body-descriptors.h:102:20: error: no matching function for call to 'v8::internal::FixedBodyDescriptor<start_offset, end_offset, size>::IterateBody(v8::internal::HeapObject*&)'
  102 |     IterateBody(obj);
      |                    ^
```

Is that a known issue? Full nodejs build log: [node_6.11.0_install.log](https://github.com/rethinkdb/rethinkdb/files/4751074/node_6.11.0_install.log)

**Comment by srh** [comment]
I hvae never seen that failure before.
