### ISSUE TITLE
Can't install RethinkDB on CentOS 7

### ISSUE THREAD

**Issue by mk-conn** [rethinkdb/rethinkdb#6893]
**Describe the bug**
Repository is not reachable => 404

**To Reproduce**
1. Open https://download.rethinkdb.com/repository/centos/7/x86_64/

**Expected behavior**
Repo would be available

**Screenshots**

<img width="875" alt="image" src="https://user-images.githubusercontent.com/5840922/86896239-fbb28780-c105-11ea-868c-ee8b39d63ed8.png">

**System info**
CentOS 7.8

**Comment by gabor-boros** [comment]
@mk-conn The repo is available and the package can be installed. If you check https://download.rethinkdb.com/repository/centos/7/x86_64/rethinkdb-2.4.0.x86_64.rpm that will download the latest rethinkdb package for centos7 for you. My question is that how did you get to this page?

If you would like to browse the package, please use Nexus' Browse UI: https://download.rethinkdb.com/#browse/browse:centos:7%2Fx86_64

**Comment by mk-conn** [comment]
Sorry for late response.. been sick than on vacation, now I had time to react: 

The url came from yum: 

base                                                                                                                                                                                                                   | 3.6 kB  00:00:00
centos-sclo-rh                                                                                                                                                                                                         | 3.0 kB  00:00:00
extras                                                                                                                                                                                                                 | 2.9 kB  00:00:00
google-chrome                                                                                                                                                                                                          | 1.3 kB  00:00:00
google-chrome-unstable                                                                                                                                                                                                                                                                                                                                                                       | 2.9 kB  00:00:00 !!!
puppet5                                                                                                                                                                                                                | 2.5 kB  00:00:00
puppet6                                                                                                                                                                                                                | 2.5 kB  00:00:00
puppetlabs-puppet5                                                                                                                                                                                                     | 2.5 kB  00:00:00
https://download.rethinkdb.com/centos/7/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.



 One of the configured repositories failed (RethinkDB),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=rethinkdb ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable rethinkdb
        or
            subscription-manager repos --disable=rethinkdb

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=rethinkdb.skip_if_unavailable=true

failure: repodata/repomd.xml from rethinkdb: [Errno 256] No more mirrors to try.
https://download.rethinkdb.com/centos/7/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

**Comment by srh** [comment]
Thank you for the details.  It looks like the docs have been updated.
