### ISSUE TITLE
Does RethinkDB redied?

### ISSUE THREAD

**Issue by manyopensource** [rethinkdb/rethinkdb#6894]
If so, I think I know why!

**Comment by gabor-boros** [comment]
No, just needed some rest a bit. But I'd be curious about the "why" part of the "question" 😇

**Comment by McSneaky** [comment]
Nope, if I remember correctly with previous "is it dead" issue, they started to look into changing the core of RethinkDB. 
Quite a lot of experimenting goes on currently :) There have been slightly more talks about it in Discord and Slack (also in issues in here somewhere)

**Comment by jondubois** [comment]
It's only dead in the mainstream corporate rhetoric. In the real world it's still very much alive. Great open source products don't die just because a bunch of suits say so.
