### ISSUE TITLE
Cannot download the file for windows

### ISSUE THREAD

**Issue by judicaelandria** [rethinkdb/rethinkdb#6896]
When I follow url to download the windows installation of rethinkdb, it says 404 error
[Download](https://download.rethinkdb.com/repository/raw/windows/rethinkdb-2.4.0.zip)

**Comment by McSneaky** [comment]
It's answered in here: https://github.com/rethinkdb/rethinkdb/issues/6892
And in here: https://github.com/rethinkdb/rethinkdb/issues/6837
And in here: https://github.com/rethinkdb/rethinkdb/issues/6835
And in here: https://github.com/rethinkdb/rethinkdb/issues/6814

Answer is still the same :slightly_smiling_face: 
> srh: 
> Some source file changes were also necessary to get it building. I have uploaded an unofficial build at https://github.com/srh/rethinkdb/releases/tag/v2.4.0-srh-win-1 .

**Comment by judicaelandria** [comment]
Oh Hey,
thank you, I will close this so
