### ISSUE TITLE
2.4.0 Debian Installation Broken

### ISSUE THREAD

**Issue by mcao** [rethinkdb/rethinkdb#6899]
**Describe the bug**
Trying to install a fresh copy of RethinkDB on Debian, and it seems that the repository is broken. Existing server also fails to check for updates.

**To Reproduce**
1. Follow instructions at https://rethinkdb.com/docs/install/debian/

**Expected behavior**
Server should install successfully / rebooted server should successfully check for updates and initialize.

**Screenshots**
https://i.imgur.com/MQDtWLi.png

**System info**
 - OS: Debian Wheezy
 - RethinkDB Version: 2.4.0

**Additional context**
Seems to be an issue on multiple distributions of Linux, but not sure.

**Comment by gabor-boros** [comment]
Hello @mcao,
It turned out that the link in the documentation is missing a word.

If you use `https://download.rethinkdb.com/repository/debian-$CODENAME $CODENAME main` instead of what the docs states (`deb https://download.rethinkdb.com/debian-$CODENAME $CODENAME main`), it will work.

I'll open a PR to fix the documentation issue soon.

Proof:

```
root@431cdd9a2dbd:/# apt-get update
Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Hit:4 http://deb.debian.org/debian stretch Release
Get:6 https://download.rethinkdb.com/repository/debian-stretch stretch InRelease [2063 B]
Get:7 https://download.rethinkdb.com/repository/debian-stretch stretch/main amd64 Packages [2612 B]
Fetched 4675 B in 1s (4313 B/s)
Reading package lists... Done
root@431cdd9a2dbd:/# apt-get install rethinkdb
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libcurl3 libgpm2 libncurses5 libprocps6 libprotobuf10 libssl1.0.2 procps psmisc
Suggested packages:
  gpm
The following NEW packages will be installed:
  libcurl3 libgpm2 libncurses5 libprocps6 libprotobuf10 libssl1.0.2 procps psmisc rethinkdb
0 upgraded, 9 newly installed, 0 to remove and 4 not upgraded.
Need to get 13.0 MB of archives.
After this operation, 46.4 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
```

**Comment by gabor-boros** [comment]
@mcao The issue should be fixed now, closing the issue. Let me know if you have any other issues.
