### ISSUE TITLE
Unable to import a 250mo csv to a dockerised rethinkDb

### ISSUE THREAD

**Issue by nicolas15000** [rethinkdb/rethinkdb#6901]
I have no clue how to import my 250mo file to a dockerised rethinkDB database.

How do I log in to the unbuntu docker machine ? Where do I place the 250 mo file ? There is no help anywhere.

 I am running windows 10 and the rethinkDb windows version is not even available .

Do I have to use telnet or ssh or something ?

When trying to ssh 192.168.99.100:32772 , it asks for a password .

Please help me.

**Comment by srh** [comment]
Following the link from Docker Hub, you can find the Dockerfile here: https://github.com/rethinkdb/rethinkdb-dockerfiles/blob/444f7754822cb3e96cb2b66042d8e87d2227be0b/buster/2.4.0/Dockerfile
