### ISSUE TITLE
Build error on Linux Mint 20

### ISSUE THREAD

**Issue by tripleo1** [rethinkdb/rethinkdb#6904]
**Describe the bug**
Build error

**To Reproduce**
./configure --allow-fetch CXX=clang++
make

**Expected behavior**
A successful build

**System info**
 - OS: [Linux Mint 20]
 - RethinkDB Version: [e.g. 2.4.0]
 - clang: 1:10.0-50~exp1 amd64

**Additional context**
I tried with gcc-8, 9 and 10 and always get an error

```
    [280/452] CC build/release_clang/obj/clustering/immediate_consistency/history.o
In file included from src/clustering/immediate_consistency/history.cc:2:
In file included from ./src/clustering/immediate_consistency/history.hpp:10:
In file included from ./src/region/region_map.hpp:11:
In file included from ./src/region/region.hpp:6:
./src/btree/keys.hpp:65:5: warning: definition of implicit copy assignment operator for 'store_key_t' is deprecated because it has a user-declared copy constructor [-Wdeprecated-copy]
    store_key_t(const store_key_t &_key) {
    ^
./src/btree/keys.hpp:122:19: note: in implicit copy assignment operator for 'store_key_t' first required here
            *this = store_key_t::max();
                  ^
In file included from src/clustering/immediate_consistency/history.cc:2:
./src/clustering/immediate_consistency/history.hpp:105:42: error: expected class name
class missing_branch_exc_t : public std::runtime_error {
                                         ^
./src/clustering/immediate_consistency/history.hpp:108:14: error: member initializer 'runtime_error' does not name a non-static data member or base class
        std::runtime_error("tried to look up a branch that is not in the history") { }
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 2 errors generated.
make[1]: *** [src/build.mk:379: build/release_clang/obj/clustering/immediate_consistency/history.o] Error 1
make: *** [Makefile:53: make] Error 2

```

**Comment by srh** [comment]
That's interesting and it seems like an include for <stdexcept> ought to be added to history.hpp.

**Comment by tripleo1** [comment]
Also need to add #include <cstddef> to src/crypto/random.hpp

Now it builds (a 37mb executable!)

**Comment by srh** [comment]
I was able to successfully build on Linux Mint 20 without any problems.  This was on a fresh install of Linux Mint 20.  I followed the instructions here: http://samuelhughes.com/rethinkdb/build_instructions.html (at the bottom of the page).

**Comment by srh** [comment]
I actually didn't install Linux Mint 20, I tried it on the installation image... I'll try it on an actual installation too now.

**Comment by srh** [comment]
This did not reproduce, but I pushed a change to v2.4.x here: 328ebfb8f694e15d01afa0341f0200dd45eac112 .
