### ISSUE TITLE
How to connect Rethinkdb from Pentaho Data Integration

### ISSUE THREAD

**Issue by DrashtiMashru** [rethinkdb/rethinkdb#6905]
I want to connect Rethinkdb from Pentaho Data Integration ETL tool... I tried to copy jar file of Rethinkdb in pentaho/mypath/pdi-ce-8.0/data-integration/lib folder.. but itis not displaying in connection type of pentaho data integration.

**Comment by srh** [comment]
Try a Pentaho forum.

**Comment by DrashtiMashru** [comment]
What is Custom driver class name and connection URL to connect Rethinkdb data? For version 2.3.6
