### ISSUE TITLE
Web UI broken in v2.4.x

### ISSUE THREAD

**Issue by srh** [rethinkdb/rethinkdb#6906]
The Web UI is broken in v2.4.x.  It was broken with commit 7789255b77929bc152a40ddc60248df13fc746f1.  The web UI fails to load because of a syntax error -- the server is serving a cluster-min.js file that has a nul character in it ("sho\0w_description" on line 11).

**Comment by lsabi** [comment]
I can't find any changes to that file in the commit. Could it be that it was generated via some automated stuff when building the project?

**Comment by srh** [comment]
The file that directly controls what gets sent to the client is src/gen/web_assets.cc.  The web ui infrastructure stuff is just used to generate that file.  Maybe the commit just applied the reversion to the file, instead of regenerating the file.

**Comment by lsabi** [comment]
Now I found the file, but I don't find the nul character.

Could it be due to that the splitted string? Maybe C++ added the extra char (just guessing what it could cause the error)
`return this.sho",
      65495) + std::string(
      "w_description()`

**Comment by srh** [comment]
I would guess that a merge resulted in 65495 being the wrong constant there, 1 more than the length of the string.

**Comment by srh** [comment]
Running `make generate` seems to fix the problem, so you might want to do that, check that the web UI works, and commit the result.

**Comment by gabor-boros** [comment]
Oh, I messed it up during cherry-picking I guess. Regenerate would help, in case @lsabi would like to do that I can help in that too or I can do it by end of Thursday (tomorrow I'll have a busy day)

**Comment by srh** [comment]
I pushed the fix.
