### ISSUE TITLE
v2.4.1 with assets gen with 2.4.0-8-g07da06-dirty

### ISSUE THREAD

**Issue by celogeek** [rethinkdb/rethinkdb#6910]
**Describe the bug**
The assets files are generated with version 2.4.0-8-g07da06-dirty

https://raw.githubusercontent.com/rethinkdb/rethinkdb/v2.4.1/src/gen/web_assets.cc

**To Reproduce**
1. Compile rethinkdb
2. Open web interface
3. RethinkUI indicate a new version is available but we already are on v2.4.1

**Expected behavior**
The assets should be gen with v2.4.1

**Screenshots**

**System info**
 - Arch Linux
 - RethinkDB Version: 2.4.1

**Additional context**

**Comment by srh** [comment]
Thanks for the report.  We'll have to add something to the release checklist.  2.4.0 didn't have the update checker, so its web UI version number existed solely to force the browser to refetch assets.  So it was okay, then, for it to just use the version that got automatically selected from some commit.

But it will have to be regenerated for future releases.

I have set the latest_version.txt back to 2.4.0 on download.rethinkdb.com.  The update checker was not even present for that version, so it won't hurt anybody to keep it at 2.4.0 for now.

**Comment by srh** [comment]
Also, the web assets especially shouldn't be generated with a "dirty" commit, which means there are extra uncommitted changes in the repo.

**Comment by srh** [comment]
I've updated the instructions at https://github.com/rethinkdb/rethinkdb/wiki/Releasing-a-new-version

We could remove this step if the web UI used `r.db('rethinkdb').table('server_status')` to retrieve the server version.

Anyway, I think this issue has been resolved.  Closing.

**Comment by celogeek** [comment]
Will you release a new version with this fixed?

**Comment by srh** [comment]
This is already fixed as of 2.4.1 because the download server has had its version downgraded to 2.4.0.  This is fine because 2.4.0 didn't have the update checker.

The next version should have a proper version in the web UI if the release process is followed.
