### ISSUE TITLE
Build from Source error on Raspberry4 Ubuntu 20.10 (Segmentation fault)

### ISSUE THREAD

**Issue by cyrixSpec** [rethinkdb/rethinkdb#6924]
Hi,
the used system is raspberry 4 with Ubuntu 20.10 64Bit. 
I followed the instructions from https://rethinkdb.com/docs/build.
In step 371/457 CC build/release/obj/rdb_protocol/query_cache.o the following message appears

Anyone an idea?

`  /usr/bin/c++ -pthread -ldl -o /home/cyrix/rethinkdb-2.4.1/build/external/v8_3.30.33.16-patched/build/out/arm64.release/mksnapshot -Wl,--start-group /home/cyrix/rethinkdb-2.4.1/build/external/v8_3.30.33.16-patched/build/out/arm64.release/obj.target/mksnapshot/src/mksnapshot.o /home/cyrix/rethinkdb-2.4.1/build/external/v8_3.30.33.16-patched/build/out/arm64.release/obj.target/tools/gyp/libv8_base.a /home/cyrix/rethinkdb-2.4.1/build/external/v8_3.30.33.16-patched/build/out/arm64.release/obj.target/tools/gyp/libv8_nosnapshot.a /home/cyrix/rethinkdb-2.4.1/build/external/v8_3.30.33.16-patched/build/out/arm64.release/obj.target/tools/gyp/libv8_libplatform.a /home/cyrix/rethinkdb-2.4.1/build/external/v8_3.30.33.16-patched/build/out/arm64.release/obj.target/third_party/icu/libicui18n.a /home/cyrix/rethinkdb-2.4.1/build/external/v8_3.30.33.16-patched/build/out/arm64.release/obj.target/third_party/icu/libicuuc.a /home/cyrix/rethinkdb-2.4.1/build/external/v8_3.30.33.16-patched/build/out/arm64.release/obj.target/tools/gyp/libv8_libbase.a /home/cyrix/rethinkdb-2.4.1/build/external/v8_3.30.33.16-patched/build/out/arm64.release/obj.target/third_party/icu/libicudata.a -Wl,--end-group -lrt
  LD_LIBRARY_PATH=/home/cyrix/rethinkdb-2.4.1/build/external/v8_3.30.33.16-patched/build/out/arm64.release/lib.host:/home/cyrix/rethinkdb-2.4.1/build/external/v8_3.30.33.16-patched/build/out/arm64.release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../tools/gyp; mkdir -p /home/cyrix/rethinkdb-2.4.1/build/external/v8_3.30.33.16-patched/build/out/arm64.release/obj.target/v8_snapshot/geni; "/home/cyrix/rethinkdb-2.4.1/build/external/v8_3.30.33.16-patched/build/out/arm64.release/mksnapshot" --log-snapshot-positions --logfile "/home/cyrix/rethinkdb-2.4.1/build/external/v8_3.30.33.16-patched/build/out/arm64.release/obj.target/v8_snapshot/geni/snapshot.log" --random-seed 314159265 "/home/cyrix/rethinkdb-2.4.1/build/external/v8_3.30.33.16-patched/build/out/arm64.release/obj.target/v8_snapshot/geni/snapshot.cc"
Segmentation fault (core dumped)
make[3]: *** [tools/gyp/v8_snapshot.target.arm64.release.mk:13: /home/cyrix/rethinkdb-2.4.1/build/external/v8_3.30.33.16-patched/build/out/arm64.release/obj.target/v8_snapshot/geni/snapshot.cc] Error 139
make[3]: Leaving directory '/home/cyrix/rethinkdb-2.4.1/build/external/v8_3.30.33.16-patched/build/out'
make[2]: *** [Makefile:286: arm64.release] Error 2
make[2]: Leaving directory '/home/cyrix/rethinkdb-2.4.1/build/external/v8_3.30.33.16-patched/build'`

**Comment by cyrixSpec** [comment]
worked after increasing swap

**Comment by prasanta97** [comment]
Hi @cyrixSpec! May I know how you did that because I am facing the same issue but the only difference is that I am using Ubuntu 21.04. Greatly appreciate your help if you list the steps taken to solve this issue. Thank you!
