### ISSUE TITLE
Conflict resolution: updating a nested object on rethinkdb doesn't update it

### ISSUE THREAD

**Issue by Kodehawa** [rethinkdb/rethinkdb#6925]
This is using the Java driver, latest version, on Ubuntu 16.04. No special logs.

The issue is that if I save doing "conflict": "update" (and I did this in prod, to learn the lesson...) and the object has objects within it (say {"hello":1, "hello-1": 2}) and you remove hello-1, it doesn't update the object within.

For a production example, I had a Player object, that in turns contains an Inventory object, which serializes to a HashMap (which should just be another object for rethinkdb), which has a json that looks like:
```
{
  "id": "..."
  (...)
  "inventory": "{1:20, 3:40, 5:10, 2:1}"
}
```

When we remove the 2:1 object, doing "conflict": "update" for conflict resolution, it *does NOT* remove it, at all. It works if, for example, I make 5:10 5:9 instead (9 objects of type 5 instead of 10 of type 5), but removing it just does not work at all, forcing us to use "conflict": "replace" for those cases :(

Offending changes on our codebase that made us realize this:
https://github.com/Mantaro/MantaroBot/commit/c3a009bc9ec9cda139fe288023218ea98fbeff54
https://github.com/Mantaro/MantaroBot/commit/12a54237837c961cbe1fc1e8a77a338d0904996c

EDIT: This is from a POJO, as clarification. In this case, at least on the java driver, is quite literally impossible to do r.literal() on a single nested object _-unless we do it for the whole document, which defeats the purpose of update :)-_ 

Thanks you.

EDIT 2: Well, might be worth it adding an option (option argument/optarg?) to do r.literal() on all nested fields?

**Comment by srh** [comment]
So, RethinkDB is behaving correctly.  I recommend making your suggestion or a PR in the Java driver repo: https://github.com/rethinkdb/rethinkdb-java .  That would be the appropriate place for the feature you suggest.

I'd guess you can make a function yourself that takes a POJO and applies r.literal around the top-level fields, and use that in your codebase.  But it might be a useful utility for the Java driver to have.

**Comment by Kodehawa** [comment]
Thanks. I'll do that then :)
