### ISSUE TITLE
Your founder is a sexist piece of trash. Remove him or delete your product.

### ISSUE THREAD

**Issue by ssmith-wombatweb** [rethinkdb/rethinkdb#6928]
https://twitter.com/spakhm/status/1333514691533025284

<img width="594" alt="Screen Shot 2020-11-30 at 2 16 04 PM" src="https://user-images.githubusercontent.com/11299714/100672315-99f1f480-3316-11eb-8942-4028d979a842.png">

**Comment by ssmith-wombatweb** [comment]
It appears he not longer works for you. I'd recommend distancing yourselves from him.

**Comment by clovergaze** [comment]
@ssmith-wombatweb Are you aware that this is an Open-Source project that is collaboratively developed by many people? One persons personal opinion about unrelated topics is not promoted or reflected by the project and to be seen as separate from this project.

If you do not like the association of a certain name with a product of any kind it is a perfectly valid option for you to not use that product.

**Comment by v3ss0n** [comment]
@ssmith-wombatweb  we hope you can see opensource software as software and  not as american politics.

**Comment by ssmith-wombatweb** [comment]
@v3ss0n No such thing as non political software. Both politics and software are made of human beings. Nothing is apolitical when politics are more than just policy decisions.

**Comment by Extarys** [comment]
Can we please lock this issue? No idea who to ping though. @clovergaze @gabor-boros  maybe?

@ssmith-wombatweb The founder left a good while ago and this issue have no reason to exists.
