### ISSUE TITLE
Incorrect redirection of "rethinkdb on freenode" link.

### ISSUE THREAD

**Issue by uwhaa** [rethinkdb/rethinkdb#6939]
**Describe the bug** 
After logging to the rethinkdb panel there are some links on the bottom of the page. One of them: "rethinkdb on freenode" redirects to an empty page.

**To Reproduce** 
Steps to reproduce the behaviour:
1. Enter portal
2. Click "rethinkdb on freenode" link on the bottom of the page.

**Expected behavior**
Redirect to correct page.

**Screenshots**
![rdb1](https://user-images.githubusercontent.com/62721926/104223324-c5065280-5443-11eb-87a3-335a4ca71c0f.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/62721926/104223395-dcddd680-5443-11eb-9035-1a4d6f755632.png)

-------------
Found by: wprzadka, pawelrys, uwhaa

**Comment by gabor-boros** [comment]
This should be https://webchat.freenode.net/#rethinkdb or irc://webchat.freenode.net/#rethinkdb, but not irc://chat.freenode.net/#rethinkdb for sure

**Comment by srh** [comment]
I've now updated old_admin branch to remove the Groups and Freenode links. ece0e7cbecbb57c539cc8557163581b5f7686836

Closing.
