### ISSUE TITLE
Forbidden access to ReQL data types page.

### ISSUE THREAD

**Issue by uwhaa** [rethinkdb/rethinkdb#6940]
**Describe the bug**
During typing of the command: "dbCreate('dbName').keys()" command description contains hyperlink to ReQL data types which returns HTTP Request 403.

**To Reproduce**
1. Run rethinkdb.exe
2. Click "Data Explorer" link on the top of the page.
3. Start typing "r.dbCreate('dbName').keys("
4. Click  **ReQL_data_types** hyperlink
5. Access to the page is forbidden

**Expected behavior**
Redirect to correct page.

**Screenshots**
![rdb](https://user-images.githubusercontent.com/62721926/104224561-72c63100-5445-11eb-8524-1ee822dafbfc.png)
![scr5](https://user-images.githubusercontent.com/62721926/104224535-67730580-5445-11eb-9481-82cb43e8b81e.png)

-------------
Found by: wprzadka, pawelrys, uwhaa

**Comment by srh** [comment]
Thanks for the report.

**Comment by gabor-boros** [comment]
The link is trying to redirect to `<HOST>/docs/data-types/#sorting-order` which is obviously not available.

**Comment by Pro-Coder04** [comment]
Hello
I'm interested in solving this issue
Could someone assign it to me

**Comment by gabor-boros** [comment]
@Pro-Coder04 Done. By the way, feel free to work on anything regardless of the assignee status (just leave a comment on the issue) 😇

**Comment by Pro-Coder04** [comment]
Since the link is redirecting to a location which doesn't exist we are getting Access denied.
We can maybe create a folder at that location. 
Can someone suggest me how to do that?
and where will I find the html source code for web UI?

**Comment by srh** [comment]
@Pro-Coder04 The admin UI is defined at https://github.com/rethinkdb/rethinkdb/tree/old_admin

**Comment by sg5506844** [comment]
Created PR #7112 . Updated the reql_docs link

**Comment by srh** [comment]
Closing as fixed.  Thanks @sg5506844 !
