### ISSUE TITLE
Conditional DELETE request 

### ISSUE THREAD

**Issue by HeikoMueller** [rethinkdb/rethinkdb#6942]
I have a table with id as primary key. If I want to delete records based on a second condition (e.g. a matching user_id with the current session user), I can either filter or make a get request twice. What is better performance-wise or is there another recommended  way to achieve this?

`const query = await r.table("stores")
        .filter({id: req.body.id, user_id: user.id})
        .delete()`

`const query = await r.table("stores")
        .get(req.body.id)
        .do(function(store) {
          return r.branch(
            r.eq(store("user_id"), user.id),
            r.table("stores").get(req.body.id).delete(),
            r.error('This store belongs to someone else.')
          )
        })`

**Comment by srh** [comment]
You should never be filtering if you have the object's primary key.

**Comment by HeikoMueller** [comment]
Thanks
