### ISSUE TITLE
Too many informations in message after failed authentication

### ISSUE THREAD

**Issue by wprzadka** [rethinkdb/rethinkdb#6944]
During authorization when client sends incorrect password it will receive 
`{"error":"Wrong password","error_code":12,"success":false}\x00`.
But when client sends wrong user name it will receive 
`{"error":"Unknown user","error_code":17,"success":false}\x00`.

I think that it's kind of useful information for someone who would like to try to find accounts in order to perform brute force attack on passwords of this accounts.

Setup details:
rethink from docker image - `rethinkdb:2.4.1`
I guess messages would look the same on other rethink versions

Found by: wprzadka, pawelrys, uwhaa

**Comment by srh** [comment]
Thank you for the report.  This behavior won't be changed.
