### ISSUE TITLE
Question: hard delete/vacuuming

### ISSUE THREAD

**Issue by mishawakerman** [rethinkdb/rethinkdb#6947]
Hello, we're conducting an audit of our data retention processes and I was hoping to confirm that RethinkDB will handle deletion from tables/indexes at some point after the document is `.delete()`d.

The only thing I could discover via Google was this comment [here](https://rethinkdb.com/docs/rethinkdb-vs-mongodb/):

> A custom log-structured storage engine with a concurrent, incremental on-disk garbage compactor takes advantage of different types of storage hardware.

Thanks in advance.

**Comment by srh** [comment]
@mishawakerman The data will remain in unused space in the database files until future writes or file truncation happen to overwrite it.  It is not retrievable by the application.

After that, depending on file system, it may, in the exact same sense, remain present on the hard drive, until future writes overwrite it.
