### ISSUE TITLE
Drop r.js support?  Use Duktape?

### ISSUE THREAD

**Issue by srh** [rethinkdb/rethinkdb#6960]
Here is a question for you.

Who is using `r.js`?

Integrating the v8 JavaScript engine is a pain.  Also, generally speaking, upgrading v8 to later versions does not "just work."

- With r.js removed, we could release a Windows version of the next RethinkDB version, just as there exists an unofficial release that removes r.js support: https://github.com/srh/rethinkdb/releases/tag/v2.4.0-srh-win-1
- Anybody using it could probably put that logic client-side (or refrain from upgrading).
- The Hirsute package, #6959, is getting held up because of v8 build errors
- The version of v8 we currently support is ancient.
- We're actually running v8 out of process anyway.

We could also replace v8 with Duktape.  See #6401 for an open PR.  That PR could be updated with the most recent Duktape version.

**Comment by MrBoombastic** [comment]
I don't use it. It's useless, especially when using Node.JS.

**Comment by yaneony** [comment]
We are also don't use it. 

Put 👍 if you also don't use it.

**Comment by marchaos** [comment]
Long time user of RethinkDB. We don't use it, any only found out that it existed from this issue 👀. I can see that it might be a pain for those that are using it to upgrade away from it, but don't think that anyone will miss it who isn't currently using it.

**Comment by hodgman** [comment]
Another non-user of the feature here.
We use Windows dev env and Linux server Env, would be very happy with up-to-date windows tools (or being able to easily make a build ourselves) that removal of it would provide.

I'm guessing it could be included but marked deprecated in the next version too? Or optionally enabled in unofficial builds?

**Comment by SamLebarbare** [comment]
Ok for Epsitec team, but we prefer QuickJS over DukTape
https://bellard.org/quickjs/

**Comment by marchaos** [comment]
@SamLebarbare - are you using r.js? Would you be ok if support was dropped altogether rather than switching to Duktape / quickjs.

**Comment by SamLebarbare** [comment]
This feature is not used in production our side, but it's sad to remove features that open possibilities, just because build process is messy...

**Comment by thelinuxlich** [comment]
+1 for duktape

**Comment by iambumblehead** [comment]
I'm using rethinkdb every day and have not heard of r.js. If you remove it, I won't notice.

**Comment by atassis** [comment]
Can't consider a good usecase for it, never used it in any project I met with ReDB under the hood

**Comment by Kodehawa** [comment]
Can't see why I'd use it, so I don't. If removing it lightens the load, all good.

**Comment by sothix** [comment]
It would be great to get an official windows build again and trim some fat along the way.

**Comment by lmdc45** [comment]
I use r.js as an easy way to set up custom filters on the db, just the same way it is displayed on https://rethinkdb.com/api/javascript/js however can probably be changed to something different if required

**Comment by srh** [comment]
@lmdc45 Thanks for the feedback.  I'm sure there are a lot of other people using r.js, then, who haven't replied.  So, right now my top choice is quickjs.

**Comment by srh** [comment]
A QuickJS **rough** work in progress is present in branch https://github.com/srh/rethinkdb/tree/sam/24x/quickjs

It's based off the Duktape branch, after rebasing it on v2.4.x, because that already does the nice stuff of getting rid of v8 and adds fetching of the rethinkdb-vendored repository.

By "rough" I mean quickjs is 10% in, and Duktape is 10% out.  You don't want to run it.  I'll clean up the branch's git history a bit, too. It doesn't support JS functions yet.  It doesn't handle errors well. You could run `r.js("1234")` or `r.js("\"hello\"")` and get the proper result.

Disturbingly, it crashes a JS worker process (but not RethinkDB) if you run `r.js("abca")` or `r.js("Math.sin(5)")`, and the stack trace is inside of quickjs code.  I don't think that's supposed to happen.

Just letting you know what's up.

**Comment by atassis** [comment]
@srh Cool. Can you suggest an ETA of deploying this to prod? Just interested in

**Comment by dotnetCarpenter** [comment]
@srh for a minute I thought that `r.js` was the entire [js driver for ReQL](https://rethinkdb.com/api/javascript/) but @lmdc45 pointed to [`r.js(jsString[, {timeout: <number>}]) → value`](https://rethinkdb.com/api/javascript/js).

We have been using RethinkDB for 6 years on our website and are creating a new façade instead of [thinky](https://github.com/neumino/thinky).

As long as you are talking about creating js expressions from strings, then no, we do not use it and won't. If I misunderstood and you want to remove the js driver, then we **definitely use it** and currently have no path to do without.

**Comment by srh** [comment]
@atassis I offer no ETA.  Currently the quickjs branch has a 99% feature-complete working replacement of the JS engine, which needs some basic cleanup and addressing of TODO comments, and probably Windows build system support.

@dotnetCarpenter Yes, this thread is not about the JS driver, it's about the server-side `r.js` command.

**Comment by srh** [comment]
I made PR #6978 for QuickJS integration.

I made a branch v2.5.x, based off of v2.4.x for this PR, but that doesn't mean the next version number is decided to be 2.5.0 or 2.4.2 yet.

**Comment by sholladay** [comment]
I don't use this feature, either. Anything to streamline development and make releases simpler is an important step for RethinkDB right now so I strongly support removing it.

**Comment by srh** [comment]
Merged #6978 which replaces v8 with QuickJS.
