### ISSUE TITLE
RethinkDB next release list

### ISSUE THREAD

**Issue by srh** [rethinkdb/rethinkdb#6975]
The purpose of this ticket is to start a list of features needed for the next release.  I'm not sure whether the next release should be numbered 2.4.2 or 2.5.0 (because of the v8 -> quickjs list).

Mandatory(?):

* ~Look at #6247~
* ~#7041~
* ~#7042~
* ~Get working with latest Clang versions: #7036~
* ~Address HTTP 2 issues with #6968~
* ~Replace v8 with QuickJS: #6960~
* Operating system support
  * ~The RethinkDB Hirsute (Ubuntu 21.04) build needs to work (by replacing v8 with QuickJS): #6959 - builds, packages work~
  * ~Ubuntu 21.10 (Impish) support~
  * ~Ubuntu 22.04 (Jammy) support~
  * ~Ubuntu 20.04 (Focal) support~
  * ~Ubuntu 18.04 (Bionic) support~
  * ~Ubuntu 16.04 (Xenial) support~
  * ~Debian 11 (Bullseye) support - #6989~
  * ~Debian 10 (Buster) support~
  * ~Debian 9 (Stretch) support~
  * ~CentOS 7 support~
  * ~RockyLinux, AlmaLinux support~
  * ~Alpine/Musl support~
  * Fedora support?
  * CentOS Stream 8 support?
  * CentOS Stream 9 support?
* Update website's build instructions to have `CXX=clang++` if still necessary
  * ~Fix warnings when building with g++ - #7020, #7018, #7016~
* ~Split off Admin UI and drivers: #6979~
  * ~Find a place for the old admin ui~
  * ~web_assets.cc generation needs to work on Debian Bullseye~
    * ~and Ubuntu Jammy~
* Add deprecation warning to dump command, and any others that call out to the Python driver.
* ~Verify ARM builds are basically working.~
* ~Verify source packages contain the vendored/ subrepo checkout.~
* ~Fix #6895~
* ~Ensure we don't build with incorrect state of vendored repo directory when it is already checked out~
* ~Address existing recent PR's:~
  * ~#6957~
  * ~#6970 - but under #6979 it may be appropriate for the admin repository~
  * ~#7017 - figure out proper python setup instructions w.r.t. Python 2 and Python 3~
  * ~#6949 - aarch64 flags in context_switching.cc - see also #6952~
* ~Update build system dependencies to later versions (even if not necessary)~
  * ~and revisit #6993~
* ~Update rethinkdb-package-builder to a new v2.4.2 support commit and dockerfile code~
  * ~make it explicitly fetch dependencies~
* ~scripts/build-rpm.sh must not use --fetch all -- have it dynamically link libcurl, openssl, libidn, and (because why not) zlib~
* ~Regenerate web_assets.cc with the 2.4.2 version number.~
* Make rethinkdb-package-builder provide a branch and instructions for pre-2.4.2 building.

Nice-to-haves:

* A Mac ARM build: #6932
* Linux ARM builds

Doubtful nice-to-haves:

* De-coffeescriptify the JS driver, replacing it with ugly coffee-scriptified JS
* ~Update rethinkdb-package-builder to use g++ instead of clang for 2.4.2 and later (but why bother?)~

Very Doubtful

* ~Extended LTS or Extended Security Maintenance Debian/Ubuntu~
  * ~Ubuntu 14.04 (Trusty) support - QuickJS build does **not** work - ESM ends April 2024~
  * ~Debian 8 (Jessie) support - QuickJS build does **not** work - ELTS ends June 2022~
* Get the Windows build working (after we remove v8, see https://github.com/srh/rethinkdb/releases/tag/v2.4.0-srh-win-1 , but it might take some nominal effort to have QuickJS building and linking on Windows) - #7008
  * Audit the c-smile/quickjspp code changes

Drivers?:

* Python
* JavaScript -> TypeScript client?

**Comment by atassis** [comment]
I think it is better to leave coffeescript as is, write new official admin client and then remove admin frontend completely

**Comment by atassis** [comment]
And what about making more releases, even with less changes?

**Comment by gabor-boros** [comment]
@srh we could add to the list a new version of the python client with some refractors type hints, dropped python 2 support, and some more that we worked on with @lsabi in the past couple of months.

Regarding the JS client, we could replace it with the TS one, but that's a separate discussion.

**Comment by lsabi** [comment]
In order to keep track of the completed tasks, we could use github's projects (or whatever it is called).

Otherwise, editing the first comment and updating what's done and what's not.

**Comment by srh** [comment]
Is the TS client drop-in compatible with the JS client?

**Comment by atassis** [comment]
No, it's API differs drastically. The only common thing are queries. Connection creation, query running, etc differs.

**Comment by v3ss0n** [comment]
> And what about making more releases, even with less changes?

That is a good idea , this will bring users back to RethinkDB. 


> I think it is better to leave coffeescript as is, write new official admin client and then remove admin frontend completely

I thought there was an attempt to develop seperate admin frontend.

**Comment by srh** [comment]
If the TypeScript client isn't compatible then we shouldn't replace the JS client with it.

**Comment by atassis** [comment]
@srh [this](https://github.com/rethinkdb/rethinkdb-admin) is coming into the house (no ETA either).

**Comment by refi64** [comment]
There's a [fork of QuickJS with Windows support](https://github com/c-smile/quickjspp) (and other functionality that can be disabled) that's used in Sciter, maybe that could be useful?

**Comment by 462548187** [comment]
When will it be released？

**Comment by 462548187** [comment]
> 如果 TypeScript 客户端不兼容，那么我们不应该用它替换 JS 客户端。

My Mac M1 is just waiting to be released for use.

**Comment by DenisBY** [comment]
Auto-rebalance. I.e. when a server is gone and replaced with a new one, DB/tables should be automatically rebalanced (re-sharded/re-replicated) to a new server. In our case, we use AWS EC2 Autoscaling to run servers and have to use custom scripts to rebalance DB/tables after instance replacing.

**Comment by v3ss0n** [comment]
is this a bot?

**Comment by srh** [comment]
I have allocated some time to get this completed and out.

**Comment by srh** [comment]
Moving Windows support to Nice-to-have.  I think it's doable, but it's below the line right now.

**Comment by srh** [comment]
If you have a platform (aside from Ubuntu or Debian) you want packages to be built for, it wouldn't hurt to comment here.

**Comment by srh** [comment]
Linux ARM builds are basically working on Ubuntu 20.04 and Bullseye.  I haven't tested others.

I'm considering moving them to "Mandatory", simply because they seem to be working out of the box.

**Comment by srh** [comment]
Decisions on updating package dependencies:

boost - Don't want to mess with datetime behavior, keep version unchanged.
curl - Update to latest, but packages will be dynamically linked with system libs.
gtest - would need cmake to build with latest version.  Stick with old version.
jemalloc - Update to latest.
libidn - Curl uses this.  Update to latest, but packages will be dynamically linked with system libs.
OpenSSL - Updated to 1.1.1m (latest old version).  Then updated to 1.3.0 (latest).  But packages will be dynamically linked with system libs.
protobuf - We have patches for Visual Studio.  No need to upgrade.
re2 - Don't want behavioral changes.  Don't upgrade.
zlib - Already on latest version.

So, openssl, libidn, jemalloc, and curl have been updated, but only jemalloc will affect release packages.  Currently in branch https://github.com/srh/rethinkdb/tree/srh/dependencies

I think we should change package build scripts, or all build scripts, to statically link re2 and boost, because differing versions could affect query language behavior.

**Comment by srh** [comment]
It looks like AlmaLinux and CentOS 7 will be able to have packages.  I _presume_ RockyLinux will too, I haven't gotten to that yet.

We need to change the RPM build script to dynamically link libcurl and openssl.

Actually, I'll make a ticket for that -- we should even make a 2.3.8 RPM release with dynamically linked libcurl/openssl.

**Comment by srh** [comment]
RockyLinux 8 works, CentOS 7 works, and Xenial and Trusty now work thanks to the changes made for CentOS 7.

**Comment by srh** [comment]
Moved "Mac ARM build" to mandatory.  ARM macbooks are the only good macbooks now.  It now compiles and runs (and generally works).  DMG building is the only thing that needs updating.

**Comment by srh** [comment]
Moved "Mac ARM build" back out.  It requires updates to stuff in packaging/osx, and the result is we're getting an empty dmg.  Maybe somebody who wants a Mac M1 dmg could make a PR.  Right now RethinkDB builds on Mac M1.

**Comment by srh** [comment]
Currently thinking about tagging the tip of v2.4.x v2.4.2.

**Comment by srh** [comment]
It's tagged; if there's a problem we'll have to do v2.4.3.  Kicking off builds now.

**Comment by atassis** [comment]
When new docker image gonna be supplied?

**Comment by srh** [comment]
Maybe tomorrow?  Keep pinging me so I don't forget about it.  I'd do it right now, but it's 9:32 PM here, and thus I'm likely to mess something up than earlier in the day.  I've never dealt with the rethinkdb-dockerfiles repo before.

**Comment by srh** [comment]
Or maybe somebody could make a PR :-)

https://github.com/rethinkdb/rethinkdb-dockerfiles

**Comment by atassis** [comment]
Not hurrying at all lol, that's fine, take your time:)
Will look at dockerfile repo later.
Thanks for your work @srh!

**Comment by gabor-boros** [comment]
@atassis the dockerfiles were updated yesterday (https://github.com/rethinkdb/rethinkdb-dockerfiles/pull/59) though docker hub not yet. I'm going to open a PR on their end soon. Though you can do too, if you would not like to wait. If I'm right it is about ~2 lines of change
