### ISSUE TITLE
Unable to Install rethinkDB on Linux machine with source code

### ISSUE THREAD

**Issue by ariesajaygarg** [rethinkdb/rethinkdb#6977]
I want to configure rethinkDB on Linux 7 (x86_64) and followed below steps but getting error out. Please advise.

0. I have downloaded tar file from https://rethinkdb.com/docs/install/centos/
1. wget https://download.rethinkdb.com/repository/raw/dist/rethinkdb-2.4.1.tgz
2. tar xf rethinkdb-2.4.1.tgz
3. ./configure --allow-fetch --dynamic jemalloc
4. then executed "make" command but got error due to connection
error" curl: (7) Failed connect to github.com:443; Connection timed out"
5. Then i have downloaded the file https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.bz2 and placced into "~external/.cache/protobuf-2.5.0.tar.bz2"
6. Then again executed make but its getting error out
"mk/support/pkg/pkg.sh: line 311: patch: command not found"

**Comment by srh** [comment]
You'll want to install these prerequisites.

```
yum install openssl-devel libcurl-devel wget tar m4 \
    git-core boost-static gcc-c++ npm ncurses-devel \
    which make ncurses-static zlib-devel zlib-static \
    protobuf-devel protobuf-static jemalloc-devel
yum install bzip2 patch
```
