### ISSUE TITLE
How many open connection at the same time?

### ISSUE THREAD

**Issue by oguzhancelikarslan** [rethinkdb/rethinkdb#6980]
I wonder that having only one machine(dedicated only for db) with 4 gb ram, with 120 gb ssd and 2 vcpu, how many active open connection my server can handle?

I know it is really hard to answer question without further information therefore just want to hear the average.

**Comment by Thiploll** [comment]
Hey,

You should probably consider some connection pooling, caching, and rate-limiting.
If you are seeking the limit then you are preparing your application to break.
For what it's worth, my rethinkdb proxy currently has 3700 active connections to it, which is a dedicated server with 8 cores 16 threads and 32GB of ram running ubuntu.
