### ISSUE TITLE
clang-format source code?

### ISSUE THREAD

**Issue by yesudeep** [rethinkdb/rethinkdb#6990]
Would it be possible to clang-format the source code?

Should be a trivial task but would help with our editors trying to include auto-formatted code when submitting patches.

**Comment by srh** [comment]
RethinkDB's C++ codebase follows very basic and general formatting rules that are readily apparent from the code you're editing, so you would have to gratuitously disregard basic common sense to suffer back-and-forth about formatting.

Like, we all have experienced the guy who comes into a project that uses `if (...) {` everywhere and starts doing `if(...){` .  Just don't be that guy and you're good.

If there was a PR with bad style, I think the appropriate thing to do would be for the project to accept it and fix the formatting if they (or "we") have a problem with it.  Beggers can't be choosers.

I am disinclined to add more "moving parts" to the project, such as automatic clang formatting.  For starters, that makes clang a dependency.  Second, its use would add a lot of changes that disrupt the git blame history.  It would also take more effort to review the PR's that change a lot of lines.

**Comment by srh** [comment]
I'm going to close this.  Cleaning up open issues on the front page...

I have merged #7090 to simplify the style document.  The only actual explicit formatting rule that remains is to always use braces and put spaces around control structure blocks.  The other rules weren't general rules but were overly specific carve-outs.  Unmentioned is four-space indentation or how to put spaces around commas.

RethinkDB doesn't actually have a super-precise formatting standard.

Note that the *important* parts of STYLE.md are not formatting rules.
