### ISSUE TITLE
Does this project support compiling on the windows platform? Or whether to support msvc compiler

### ISSUE THREAD

**Issue by qd1332543** [rethinkdb/rethinkdb#6992]

**Comment by srh** [comment]
See #6975.  Compiling on Windows right now is quite tricky and depends on specific old Visual Studio versions (or SDK versions) being installed.  Windows has always been in experimental state.  I recommend using Linux.

One issue is that v8 messes up the build.  See https://github.com/srh/rethinkdb/releases/tag/v2.4.0-srh-win-1 and you can see from the commit the changes that were made to get RethinkDb working with Windows.  But it still required specific instructions to be followed to get it compiling.

**Comment by srh** [comment]
I am going to close, because I think this is captured by #6975.
