### ISSUE TITLE
What to use for new project, any viable RethinkDB alternatives?

### ISSUE THREAD

**Issue by josipjelic** [rethinkdb/rethinkdb#6994]
Hi all, RDB is really awesome and feature I'm looking into for my next project is changefeeds. 
I understand MongoDB can also do them but, AFAIK, not based on any filter, you can only watch changes for the entire collection.

This really is a RethinkDB killer feature and I'm wondering if there is another DB that offers that type of watch on changes.

In today's world of reactive online experiences, what does everybody use?

**Comment by Bessonov** [comment]
I'm using [hasura](https://github.com/hasura/graphql-engine/). It's not a database, but it allows implementing a reactive approach. I the core, I'm attaching the graphql subscription to a view, which is based on auditing. But you can just subscribe to concrete tables with a query.
