### ISSUE TITLE
Can't install rethinkdb on Ubuntu 21.04

### ISSUE THREAD

**Issue by Sekru** [rethinkdb/rethinkdb#6998]
Hi, I'm trying to install rethinkdb on Ubuntu 21.04 via Ansible. I have this error: Failed to update apt cache: E:The repository 'https://download.rethinkdb.com/repository/ubuntu-hirsute hirsute Release' does not have a Release file.
I see that there is no ubuntu-hirsute.

**Comment by srh** [comment]
I'm working on it (literally).  I expect to be done before 22.04...

**Comment by srh** [comment]
It is confirmed this will generally be fixed in RethinkDB v2.4.2.  Currently the 21.04 and 21.10 packages build successfully in v2.4.x branch.

See #6975 for updates. Closing.
