### ISSUE TITLE
Error: unable to rund calng++ 

### ISSUE THREAD

**Issue by lulkebit** [rethinkdb/rethinkdb#7003]
Hello I want to install rethink db on my Raspberry Pi 3B. I folled the steps from the website but when I try to run the following line:

> ./configure --allow-fetch CXX=clang++

I get the following error message
`* Reading arguments from 'configure.default'
* Prepending the following arguments: --fetch re2 --fetch gtest --fetch v8 --fetch jemalloc --fetch npm --fetch coffee --fetch browserify
* Detecting system configuration
Bash:                           5.1.4(1)-release
Use ccache:                     no
C++ Compiler:                   error
* Error: unable to run clang++

* Aborting configure
`

**Comment by srh** [comment]
Do you have clang installed?
