### ISSUE TITLE
Python Client Driver is not compatible with python3.10

### ISSUE THREAD

**Issue by leoliu0** [rethinkdb/rethinkdb#7004]
OS: Arch Linux x86, rethinkdb 2.4.1
```python
from rethinkdb import r

r.connect('localhost', 28015).repl()

r.db('test').table_create('tv_shows').run()
```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_3837400/2671571060.py in <module>
      3 r.connect('localhost', 28015).repl()
      4 
----> 5 r.db('test').table_create('tv_shows').run()

~/.local/lib/python3.10/site-packages/rethinkdb/query.py in db(*args)
    141 
    142 def db(*args):
--> 143     return ast.DB(*args)
    144 
    145 

~/.local/lib/python3.10/site-packages/rethinkdb/ast.py in __init__(self, *args, **optargs)
    123     # Instantiate this AST node with the given pos and opt args
    124     def __init__(self, *args, **optargs):
--> 125         self._args = [expr(e) for e in args]
    126 
    127         self.optargs = {}

~/.local/lib/python3.10/site-packages/rethinkdb/ast.py in <listcomp>(.0)
    123     # Instantiate this AST node with the given pos and opt args
    124     def __init__(self, *args, **optargs):
--> 125         self._args = [expr(e) for e in args]
    126 
    127         self.optargs = {}

~/.local/lib/python3.10/site-packages/rethinkdb/ast.py in expr(val, nesting_depth)
     85     if isinstance(val, RqlQuery):
     86         return val
---> 87     elif isinstance(val, collections.Callable):
     88         return Func(val)
     89     elif isinstance(val, (datetime.datetime, datetime.date)):

AttributeError: module 'collections' has no attribute 'Callable'

**Comment by SomeHybrid** [comment]
Here's a fix.
Go to the rethinkdb client driver folder inside your python installation and access `ast.py`. After `import collections`, add `collections.Callable = collections.abc.Callable; collections.Mapping = collections.abc.Mapping`.

**Comment by SomeHybrid** [comment]
a probably better solution is to just download by source by doing `pip install git+https://github.com/rethinkdb/rethinkdb-python` as the fix has been implemented but hasn't been pushed to pypi yet

**Comment by lsabi** [comment]
We're working on supporting the latest version of python.

Though, this is an issue related to the driver, which has it's own repository. [https://github.com/rethinkdb/rethinkdb-python](https://github.com/rethinkdb/rethinkdb-python)
