### ISSUE TITLE
Two Node Instances on separate linux server

### ISSUE THREAD

**Issue by RenkimSupport** [rethinkdb/rethinkdb#7007]
Trying to setup a 2 node system on separate Linux servers using the config files. I have the server setup to auto-start so the examples using the command line wont apply.

**node1 config**
node1 config file:
bind=192.168.1.177
canonical-address=192.168.1.177

**Node2: Config**
bind=192.168.1.178
canonical-address=192.168.1.178
join=192.168.1.177:29015

This setup will not let node2 connect to node1. The only way for me to get this to work is adding the join in the node1 config:
join=192.168.1.178:29015

Is this the correct setup? and example of configs from each node would be appreciated.

**Comment by srh** [comment]
Closing; this is a question.
