### ISSUE TITLE
Push nightly source builds to the download service

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/rethinkdb#702]
When Jenkins builds a nightly tgz, we need to collect them in a folder on `dr-doom` and `rsync` them to the download service.

A counter-proposal is welcome (particularly since it's not clear how many builds we should keep before purging old builds) but right now a link is broken on our site since we have no way to provide nightly builds.

**Comment by AtnNn** [comment]
@mglukhovsky are you still interestd in having this? There hasn't been much demand for it and we have gotten pretty fast at releasing point releases.

**Comment by mglukhovsky** [comment]
I don't think there's a lot of demand for it, closing.
