### ISSUE TITLE
compile failed / debian amd64 bullseye (v11)

### ISSUE THREAD

**Issue by zadcha** [rethinkdb/rethinkdb#7033]
src/pprint/js_pprint.cc: In member function ‘void pprint::js_pretty_printer_t::to_js_datum(const ql::datum_t&)’:
src/pprint/js_pprint.cc:183:23: error: ‘trunc’ was not declared in this scope; did you mean ‘truncate’?
  183 |             push_text(trunc(d.as_num()) == d.as_num()
      |                       ^~~~~
      |                       truncate
src/pprint/js_pprint.cc:184:47: error: ‘lrint’ was not declared in this scope; did you mean ‘pprint’?
  184 |                              ? std::to_string(lrint(d.as_num()))
      |                                               ^~~~~
      |                                               pprint
src/pprint/js_pprint.cc: In member function ‘void pprint::js_pretty_printer_t::var_name(const ql::datum_t&)’:
src/pprint/js_pprint.cc:723:29: error: ‘lrint’ was not declared in this scope; did you mean ‘pprint’?
  723 |         push_text(print_var(lrint(d.as_num())));
      |                             ^~~~~
      |                             pprint
make[1]: *** [src/build.mk:344: build/release/obj/pprint/js_pprint.o] Error 1

**Comment by srh** [comment]
@zadcha What branch, what commit, what platform?

**Comment by zadcha** [comment]
it's on a intel (i5/i7) x86 64 bits with debian 11 (bullseye), fresh install
but i must confess i'm a new on the branch's concept, i was thinking naively
that following the README.md would do the stuff after gh repo clone
rethinkdb/rethinkdb, ./configure, make, etc.

what is the last branch/commit where rethinkdb is working ?

thx

**Comment by zadcha** [comment]
git branch --show-current
next

**Comment by srh** [comment]
Okay, please use branch v2.4.x.

**Comment by srh** [comment]
Closing.  v2.4.x is now the default branch of this repo.

**Comment by zadcha** [comment]
ok, compile successfully with the v2.4.x branch  (gh repo clone
rethinkdb/rethinkdb -- -b v2.4.x)
shouldn't you put the v2.4.x for the default branch instead of next ?
