### ISSUE TITLE
How can I use it in a platform like replit?

### ISSUE THREAD

**Issue by Tips-Tricks-Solutions** [rethinkdb/rethinkdb#7039]
I tried cloning this repo but not working

**Comment by srh** [comment]
I'm not familiar with Replit.  Is support for RethinkDB in Replit something we could specifically support somehow?

Generally, to build RethinkDB, you'd do something like

```
git checkout v2.4.x
./configure --allow-fetch
make fetch
make
```

And then `./build/release/rethinkdb` has a binary.

I separated out the `make fetch` step (which `make` would do) just to distinguish the part that connects to the network and downloads dependencies.

Another possibility is to try using a source distribution which has the dependencies pre-fetched.  https://rethinkdb.com/docs/build 
 You probably would need `CXX=clang++` on the configure line for v2.4.1.  (I have no idea if Replit offers choice of compilers, or any of this command line environment stuff.)

Please let me know if this helps or if this is off the mark.  If making RethinkDB work on Replit is possible, well, that would be nice to get working.  (Knowing nothing about Replit, I don't even know if it working on Replit is a concept that makes sense.)

**Comment by srh** [comment]
Closing this as a question, but if there's some path to changing this to support Replit somehow, please reopen and comment.
