### ISSUE TITLE
r.js vulnerability

### ISSUE THREAD

**Issue by HeikoMueller** [rethinkdb/rethinkdb#7046]
I start making use of r.js() in RethinkDB 2.4.1 recently and I am wondering if this function is more or less vulnerable to malicious user code inputs compared with the regular eval() function ? Does anyone know if r.js() can be considered to be safely sandboxed?

**Comment by srh** [comment]
@HeikoMueller You would surely not want to run untrusted user-supplied JavaScript with r.js.  In RethinkDB 2.4.1, it uses an old V8 version.  Specifically, V8 3.30.33.16.  In 2.4.2 it will use QuickJS, which may or may not be fit for running malicious code, but as it's not shipped in a web browser, it can be presumed not to be.

**Comment by srh** [comment]
Also, even if it were not able to escape the sandbox, you'd probably be vulnerable to a denial of service attack.

**Comment by HeikoMueller** [comment]
@srh Thanks for clarification!

**Comment by HeikoMueller** [comment]
@src Sorry for confusion, but wouldn't that apply also to functions such as r.expr(), r.ge() and basically to all other r functions in the API?

"r.js('Math.floor(3.4)')" and "r.expr(Math.floor(3.4))" both return 3, so I assume either of these use the same V8 engine. Also, if I run queries such as "r.expr(3).ge(Math.floor(3.4))", it includes a Javascript snippet. 

So, does this mean that the general rule is no uncontrolled user-supplied query to RethinkDB at all, in other words, any use case with dynamically generated queries is not in scope of RethinkDB?

**Comment by srh** [comment]
`r.expr(Math.floor(3.4))` constructs the query `r.expr(3)`.  `r.expr(3).ge(Math.floor(3.4))` constructs the query `r.expr(3).ge(3)`.  The `Math.floor(3.4)` expression is evaluated client-side the way the client-side programming language normally works.

**Comment by HeikoMueller** [comment]
Ah okay, cool. Makes sense, thanks!
