### ISSUE TITLE
Revisit #6192 "fix environment syntax"

### ISSUE THREAD

**Issue by srh** [rethinkdb/rethinkdb#7048]
PR #6192 was closed because we're changing the main branch of this repo to v2.4.x.

Revisit it after v2.4.2 is released (or whenever).

There are definitely some changes in the diff that we do *not* want (such as UtilsTest.TimeLocal no longer testing ::local).

**Comment by gabor-boros** [comment]
@srh I'm closing this issue. Actually, https://github.com/rethinkdb/rethinkdb/pull/7059 resolves the testing issues.
