### ISSUE TITLE
It should be possible to set `--initial-password` from a file

### ISSUE THREAD

**Issue by besworks** [rethinkdb/rethinkdb#7061]
The dump, restore, etc commands support reading the password from a file but there is no equivalent option when setting up a new server. Setting the initial password in plain text on the command line is insecure as it shows up when running `ps`.

This is the block of code responsible for getting the password string from the `--initial-password` option :

https://github.com/rethinkdb/rethinkdb/blob/c131f90ad55f8689059edc0be0f2026da2709ffc/src/clustering/administration/main/command_line.cc#L1474-L1475

Seems like this should probably be more like this :
```
optional<std::string> initial_password_filename = get_optional_option(opts, "--initial-password-file");

if (initial_password_filename) {
  fp_wrapper_t password_fp(initial_password_filename->c_str(), "r");
}

if (nullptr == password_fp.get()) {
  optional<std::string> initial_password_str = get_optional_option(opts, "--initial-password");
} else {
  optional<std::string> initial_password_str = password_fp.get();
}
```

Though I'm not entirely sure on the syntax. [`fp_wrapper_t`](https://github.com/rethinkdb/rethinkdb/blob/c131f90ad55f8689059edc0be0f2026da2709ffc/src/clustering/administration/main/command_line.cc#L837-L855) is defined in that same file and I just based this snippet roughly on how it was used.

**Comment by srh** [comment]
It might put the password in .bash_history too.

You can use `--config-file myconfig` with the file `myconfig` having the content `initial-password=hunter2`.

I'm going to close this.  A PR which updates the help output for `--initial-password` to suggest using `--config-file` would be accepted.

**Comment by besworks** [comment]
Thanks for the tip, that suits my purposes just fine. I didn't realize that you could do that because there is no mention of an `initial-password` option in the [config file doc](https://github.com/rethinkdb/docs/blob/master/5-deployment/config-file.md).
