### ISSUE TITLE
Publish 2.4.2 on GitHub

### ISSUE THREAD

**Issue by eloquence** [rethinkdb/rethinkdb#7063]
Congrats on getting a new point release out - I know it's been a struggle to keep this project going. I'm noticing that 2.4.2 is announced on https://rethinkdb.com/blog/2.4.2-release but there's no corresponding release object in https://github.com/rethinkdb/rethinkdb/releases  - is that intentional? If not perhaps someone with the adequate permissions can publish it on GitHub as well.

**Comment by gabor-boros** [comment]
Hey @eloquence,

It wasn't intentional, I believe. I'll take care of it.

**Comment by gabor-boros** [comment]
For the sake of completeness: https://github.com/rethinkdb/rethinkdb/releases/tag/v2.4.2

cc: @eloquence
