### ISSUE TITLE
Proposal: Remove .dmg packaging format

### ISSUE THREAD

**Issue by gabor-boros** [rethinkdb/rethinkdb#7069]
## Description

Let's remove the *.dmg packaging and installer. Most users on macOS uses `brew` for installing packages to mac which is somewhat a "defacto" way of installing tools on macOS. Also, the .dmg packaging is broken for M1 if I remember correctly.

We already have brew bottles that can be installed on mac: https://formulae.brew.sh/formula/rethinkdb#default (and that's 2.4.2 already). If we agree on that, we can cleanup the build system too.

What do you think?

cc: @srh

**Comment by srh** [comment]
I have no opinion on this matter.

**Comment by chrisvariety** [comment]
`.dmg` works great on M1, a lot of folks have moved away from brew, see e.g. https://wickedchicken.github.io/post/macos-nix-setup/

**Comment by gabor-boros** [comment]
@chrisvariety Say no more, you convinced me.
