### ISSUE TITLE
Request official s390x binary and docker image

### ISSUE THREAD

**Issue by kun-lu20** [rethinkdb/rethinkdb#7071]
Hi,

Since RethinkDB v2.4.2 uses QuickJS to run instead of an old version of V8, we now can use pretty much the same process to build RethinkDB binary on s390x as on x86_64 arch. I've built the binary and run Unit tests and Integration tests on s390x Ubuntu 20.04, the test results are the same as on x86_64. We would greatly appreciate it if community can provide official s390x binary and docker image.

If community agrees, we are glad to provide s390x VMs for building and testing. Please feel free to contact me regarding the VM requirements. Thanks!

**Comment by gabor-boros** [comment]
@kun-lu20 I think if we would have access to s390x machines (and RethinkDB builds on it), there is no obstacle to have s390x releases. All we need is Docker, Ruby and access to the VM. Though before making any commitments, I'd be curious about @srh's thoughts too. 

Ps: Sam, we could extend your packaging repo with s390x target if that's something you are up for. -- I can open a PR after having access to an s390x VM.

**Comment by kun-lu20** [comment]
@gabor-boros That's great. Please let me know the VM requirements when you're available, such as the number of VMs, vCPU/vMEM/Storage/OS. Thanks!

**Comment by gabor-boros** [comment]
@kun-lu20 I think a single VM with 4GB RAM, 2CPUs and a *nix OS that can run Docker containers will satisfy the requirements. Obviously, more CPUs will allow more parallel executions, though it doesn't really matter if the build takes 10h or 2h.

At the moment we are building packages for the following distros using Docker, though I assume some of these won't be available for s390x:

- bullseye
- jammy
- impish
- alma8
- rocky8
- centos7
- buster
- stretch
- jessie
- focal
- bionic
- xenial
- hirsute
- trusty

_Disclaimer: I never had the opportunity to use an s390x machine, so I may have false assumptions/expectations._

**Comment by kun-lu20** [comment]
@gabor-boros Thanks for the detailed info! For now s390x supports Ubuntu and Debian distributions in the above list.

I'll request a `4 vCPUs/4GB vMEM/100GB Storage/Ubuntu focal` s390x VM and get back to you as soon as possible.

**Comment by kun-lu20** [comment]
@gabor-boros I've sent you the latest Ts & Cs community can review and sign via email. Please take a look when you have some time. Thanks!

**Comment by gabor-boros** [comment]
@kun-lu20 I just signed and send it back to you. Please note that I'm signing it as an individual, not as a representative of any communities or companies -- as I have no authorization to do otherwise.

**Comment by srh** [comment]
Just beware that the Linux VM I used for building packages used about 250 GB when all the packages were generated; you'd need to remove docker images part of the way through the building process to fit within 100 GB.

**Comment by gabor-boros** [comment]
Nice warning! I was facing the same last time I built for arm. I'll cleanup the images between runs

**Comment by gabor-boros** [comment]
I just wanted to follow-up on this: I was able to successfully build packages for

- bullseye
- jammy
 - impish
 
 The following packages has no s390x-based docker image, so I cannot build for them:

- almalinux
- rockylinux
- centos7

The builds are still in progress, so I'll keep updating this comment as packages are building.

cc: @srh , @kun-lu20

**Comment by gabor-boros** [comment]
@kun-lu20 @srh here we go. The packages are built for the distros mentioned above, and I just uploaded them to the download server.

<img width="1263" alt="Screenshot 2022-05-19 at 7 54 51" src="https://user-images.githubusercontent.com/19173947/169220293-5cadce55-4918-4314-9545-1487c8a58e89.png">

Closing this issue 🎉  Thank you for the s390x server to build on, @kun-lu20!

**Comment by kun-lu20** [comment]
@gabor-boros You're welcome! Thanks for your speedy work on this!
