### ISSUE TITLE
Expose my local rethinkdb to internet 

### ISSUE THREAD

**Issue by KalybosPro** [rethinkdb/rethinkdb#7073]
Hi, please can't you help me to do this? I built an app with flutter and I used rethinkdb for back-end. Now I want to expose my local rethinkdb database to internet so that everyone can access to it using my app. I need your help, please.

**Comment by gabor-boros** [comment]
In addition to what @McSneaky wrote, please read these:

- https://rethinkdb.com/docs/mobile-connections/
- https://rethinkdb.com/docs/security/

Also, exposing your local machine's DB is risky from multiple perspectives. For example, although I'm not aware any vulnarabilities, you are risking that someone can access your computer through the DB.

Here is what I would do:

1. create a server on DigitalOcean (or somewhere else) and install rethinkdb
2. setup firewall rules to limit port access
3. setup a simple backend service that is "relaying" the queries or at least have a reverse proxy forwarding the admin site requests (so you can setup basic auth for the admin site)

**Comment by KalybosPro** [comment]
Okay thank you. I'm just a beginner for rethinkdb that's why. Of course, I would like to pay for a DigitalOcean droplet, but I don't have money now.

**Comment by KalybosPro** [comment]
Okay it must be the database. Because the app needs to load data from the database and display them on user interface. Okay thank for your help. So for the host, I should use my router IP address. Right?Sent from my Galaxy
-------- Original message --------From: McSneaky ***@***.***> Date: 02/06/2022  01:41  (GMT+00:00) To: rethinkdb/rethinkdb ***@***.***> Cc: KalybosPro ***@***.***>, Author ***@***.***> Subject: Re: [rethinkdb/rethinkdb] Expose my local rethinkdb to internet  (Issue #7073) 
You want random people on the internet be able to connect to your database directly? Or you want them to be able to connect to your backend?
Anyway, to allow direct DB access just open up ports in your firewall to allow driver connections on port 28015 and in case you are running cluster might need to open up 29015
