### ISSUE TITLE
AdminUI upgrade available eventhough using last version

### ISSUE THREAD

**Issue by MarianoRD** [rethinkdb/rethinkdb#7077]
## Server Info
Debian 11
5.10.0-15-amd64

### Test 1
```
rethinkdb 2.4.2~0buster (GCC 8.3.0)
```

### Test 2
```
rethinkdb 2.4.2-6-g2b55e8-dirty (x86_64-linux-gnu) (GCC 10.2.1)
Linux 5.10.0-15-amd64 x86_64
```
### AdminUI messsage

![Screenshot 2022-06-16 at 13-10-21 RethinkDB Administration Console](https://user-images.githubusercontent.com/10457534/174138415-ea091dbb-da61-4066-83ca-667ea636ceea.png)

## Expected result

The AdminUI shows the correct version and doesn't shows the message to upgrade since it's running latest version.

**Comment by srh** [comment]
Thank you for the report.  Marking as due of #7072.  I'm pinning that issue.
