### ISSUE TITLE
AttributeError: 'RethinkDB' object has no attribute 'Exchange'

### ISSUE THREAD

**Issue by Debojyoti7** [rethinkdb/rethinkdb#7106]
Im running rethink DB on windows . I have started rethinkDB server .  

import rethinkdb as rdb
r = rdb.RethinkDB()
r.connect('localhost', 28015).repl()

exchange = r.Exchange('exchange_name', db='database_name')

topic = exchange.topic('hi.there')

topic.publish("All subscribers to 'hi.there' will pick this up")

This is the publisher code . 

Im getting error "AttributeError: 'RethinkDB' object has no attribute 'Exchange'"

**Comment by srh** [comment]
That's because there is no `Exchange` command.  The Python driver's documentation is here: https://rethinkdb.com/api/python

My guess is, you are basing your code off of code that uses a different library than the standard RethinkDB client library, or which in some way modifies it.
