### ISSUE TITLE
Driver/cluster connection status

### ISSUE THREAD

**Issue by ptorrent** [rethinkdb/rethinkdb#7107]
Hello there,

Is there a way to know/see driver connections and cluster connections (ip source, etc...)

Thanks for your help !

**Comment by srh** [comment]
Cluster connections should be in the server_status system table.  I don't think driver connections are available in a structured format.  It's possible you might be able to parse it out of the `rethinkdb.logs` system table.  (I.e. parse each server's log history back to the most recent server startup message.)

https://rethinkdb.com/docs/system-tables/#other-tables

**Comment by srh** [comment]
Closing, reopen if you want to turn this into a feature request.

**Comment by ptorrent** [comment]
I think it would be nice to have the logs when a driver connects. This could be a good feature
