### ISSUE TITLE
Unable to install Rethinkdb 2.4.0 on Ubuntu 20

### ISSUE THREAD

**Issue by arpitjain305** [rethinkdb/rethinkdb#7108]
I was trying to install rethinkdb `2.4.0` on ubuntu 20, and I believe it depends on `libprotobuf10`. However, `libprotobuf10` is not available on ubuntu 20. Any way to resolve this?

**Comment by srh** [comment]
I recommend trying a help forum like the slack or discord, and post installation details.

**Comment by gabor-boros** [comment]
FTR: the commands to install the prebuilt `rethinkdb` package on Ubuntu 20 (Focal) can be found in the dockerfiles repo: https://github.com/rethinkdb/rethinkdb-dockerfiles/tree/master/focal

**Comment by srh** [comment]
Afaict RethinkDB 2.4.0 on Ubuntu 20.04 depends on libprotobuf17.
