### ISSUE TITLE
help bro my issue = warn: Problem when checking for new versions of RethinkDB: HTTP request to update.rethinkdb.com failed.

### ISSUE THREAD

**Issue by dionreddys** [rethinkdb/rethinkdb#7130]
when docker-compose up process issue in warning "warn: Problem when checking for new versions of RethinkDB: HTTP request to update.rethinkdb.com failed" help me 
<img width="963" alt="image" src="https://github.com/rethinkdb/rethinkdb/assets/32286107/8d8a93ec-a343-4e67-932f-a1502562342e">

**Comment by srh** [comment]
Run rethinkdb with `--no-update-check`.

See #6791 -- it got removed, and then added back again for the web UI, but the URL is different now.
