### ISSUE TITLE
Installation fails in Kubuntu 23.10

### ISSUE THREAD

**Issue by Leoccker** [rethinkdb/rethinkdb#7132]
Atingido:1 http://br.archive.ubuntu.com/ubuntu mantic InRelease
Atingido:2 http://br.archive.ubuntu.com/ubuntu mantic-updates InRelease                
Atingido:3 http://br.archive.ubuntu.com/ubuntu mantic-backports InRelease                                    
Ign:4 https://download.rethinkdb.com/repository/ubuntu-mantic mantic InRelease                               
Err:5 https://download.rethinkdb.com/repository/ubuntu-mantic mantic Release           
  404  Repository not found [IP: 167.172.11.96 443]
Atingido:6 http://security.ubuntu.com/ubuntu mantic-security InRelease
Lendo listas de pacotes... Pronto
E: The repository 'https://download.rethinkdb.com/repository/ubuntu-mantic mantic Release' does not have a Release file.
N: Atualizações a partir de tal repositório não podem ser feitas de forma segura e estão, portanto, desativadas por definição.
N: See apt-secure(8) manpage for repository creation and user configuration details.

How can i Fix it?

**Comment by srh** [comment]
Ah, there hasn't been a mantic package uploaded.

I have now added it to https://github.com/srh/rethinkdb-package-builder

I tried building v2.4.3 and ran into the missing stdint.h include from #7119.

I can either apply a patch upon checkout in the rethinkdb-package-builder script for mantic, or we could tag and release v2.4.4.

**Comment by srh** [comment]
@Leoccker I uploaded the 2.4.4 package for ubuntu 23.10.  Try it now.

(The other 2.4.4 packages are not up yet, only that one.)
