### ISSUE TITLE
Rethinkdb 2.4.4 release list

### ISSUE THREAD

**Issue by srh** [rethinkdb/rethinkdb#7139]
The current checklist for releasing RethinkDB 2.4.4 is below.  Currently, 2.4.4 is "out" and "announced", just as v2.4.3 was, but we still need to update the website and latest_version.txt file.

Code:
- [x] Regenerate web assets with 2.4.4 version number
- [x] Merge updated release notes (in branch `srh/v244notes`)
- [x] Check compilation on numerous platforms (before tagging)
- [x] Tag v2.4.4 release

Builds:
- [x] Linux amd64 builds
  - [x] sign RPMs
- [x] Linux ARM builds
  - [x] sign RPMs
- [x] Windows amd64 build
- [x] MacOS amd64 build
- [x] Source dist
- [x] upload everything
  - [x] and upload -latest.dmg and -latest.tgz MacOS and source dist files

More packages:
- [x] Docker files
  - [x] 2.4.3 Docker files - https://github.com/rethinkdb/rethinkdb-dockerfiles/pull/65
    - [x] official images PR merged
  - [x] 2.4.4 Docker files
    - [x] official images PR merged
- [x] Homebrew (@gabor-boros)

Website:
- [x] Update the website - https://github.com/rethinkdb/www/pull/341
- [x] Make the tag be a Github release page https://github.com/rethinkdb/rethinkdb/releases/tag/v2.4.4
- [x] Update the version number used by the upgrade checker

Additional builds:
- [x] s390x packages built (@gabor-boros)
- [x] s390x packages uploaded (@gabor-boros)

**Comment by srh** [comment]
Currently tagged https://github.com/rethinkdb/rethinkdb/releases/tag/v2.4.4

I am building amd64 packages now.

**Comment by srh** [comment]
The website is updated.  I'll see if I can get some Docker/Homebrew momentum myself, tomorrow, and see if I can help get that out, before updating the upgrade checker version number.

**Comment by srh** [comment]
I've made a 2.4.3 Docker files PR: https://github.com/rethinkdb/rethinkdb-dockerfiles/pull/65

Once that gets accepted, I'll make a 2.4.4 PR.  (I am waiting for the 2.4.3 review in case there are mistakes I don't want to repeat for 2.4.4.)

**Comment by srh** [comment]
I merged the 2.4.3 Docker Files PR.  Now baby-sitting https://github.com/docker-library/official-images/pull/15893 .

After that will be the 2.4.4 PRs.

**Comment by gabor-boros** [comment]
@srh I tagged myself for the s390x build. Do you need any other help from me? Happy to help, but I'm catching up with what was happening lately (in the past year or so).

**Comment by srh** [comment]
@gabor-boros Maybe the Homebrew update.  They have some contributing guidelines that say to make a PR using `brew`.  I'd like to at least be able to run the Homebrew recipe, and confirm that it's working, as well.

I will also have a 2.4.4 docker-library/official-images PR that might need another thumbs up.

**Comment by srh** [comment]
Looks like Homebrew got updated: https://github.com/Homebrew/homebrew-core/pull/157240

To minimize noise on their end, we can update the "next" branch in the homebrew file *after* we fork main off of v2.4.x.

**Comment by chenrui333** [comment]
> To minimize noise on their end, we can update the "next" branch in the homebrew file _after_ we fork main off of v2.4.x.

that makes sense 👍 (I am bit surprised that our audit did not pick the default branch issue up)

**Comment by gabor-boros** [comment]
FTR

- Built for bookworm
- Built for mantic
- Built for jammy
- Built for alma9
- Built for bullseye
- Built for lunar
- Built for focal
- Built for bionic
- Built for xenial
- NO s390x image base for alma8
- NO s390x image base for rocky8
- NO s390x image base for rocky9
- NO s390x image base for centos7
- NO s390x image base for buster
- NO s390x image base for trusty

I'll sign and upload the packages tomorrow
