### ISSUE TITLE
Automatically break up large arrays in the drivers

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#714]
Users often write code as follows (in semi-pseudocode):

```
records = []
for( i= 0; i < 1000000; i++) {
    records = append(records, document)
}

table.insert(records).run()
```

The problem with this code is that there is a huge bottleneck in the protobuf libraries and it causes terrible performance. We should internally break the records array up in the driver and convert it to a number of inserts at ~1k docs per insert.

**Comment by thelinuxlich** [comment]
@srh since the implementation of batch configuration is this still an issue?

**Comment by srh** [comment]
Agreed and breaking up the array in the drivers would be better addressed by some sort of "parameterized query / out-of-band uploading" feature (which also saves CPU time with all the AST manipulation in some drivers).
