### ISSUE TITLE
Cache miss rate measurements

### ISSUE THREAD

**Issue by AbhigyaWangoo** [rethinkdb/rethinkdb#7146]
Hello all, I was wondering whether there is a simple way to measure cache misses. I specifically want this rate to be num_storage_layer_seeks/num_operations. I've tried looking into the buffer_cache and btree operations, but haven't been able to figure out exactly how to get the number of RAM vs disk accesses.

**Comment by srh** [comment]
Hi @AbhigyaWangoo .  You might want to run `r.db('rethinkdb').table('_debug_stats')` and look at `serializer_block_reads` and such.

Note that a single read might involve multiple b-tree nodes cache missing, and large documents that aren't inlined will use 1 or more blocks outside the leaf node, and as far as I know there isn't any counter that tracks how many single-key reads or multi-key reads encountered 1 or more cache miss blocks.

**Comment by AbhigyaWangoo** [comment]
I'm inserting key-value pairs of size 1 KB, so I'm assuming that will typically fit onto one block. What exactly is the serializer block reads field?

**Comment by srh** [comment]
The serializer exposes a lookup table whose keys are block ids and values are data blocks from 512 B to 4K, with some ability to retain references to older copies of data.  Generally it accesses the disk (or OS filesystem cache, perhaps).  serializer_block_reads is the number of times this lookup table has been read from.

**Comment by AbhigyaWangoo** [comment]
Thank you, was able to collect the data I needed.
