### ISSUE TITLE
Connect rethinkdb directly from browser ?

### ISSUE THREAD

**Issue by anuragvohraec** [rethinkdb/rethinkdb#7149]
Hi All,

I know rethinkdb is not supposed to connect directly from browser, but for toy project it would really help.
I think the admin panel which is provided with the rethinkDB at `localhost:8080` do connect to rethinkdb directly from browser.
Is there any library/  part of code where I can have this functionality and get a client which runs only in broswer to connect with rethinkDB direclty just the same way the admin console does this thing in browser.

**Comment by srh** [comment]
Sure -- see the admin UI code and how it does requests over HTTP.

But the client can only be run by fully trusted, root-level administrative users who can be given the power to delete or modify everything in the database.
