### ISSUE TITLE
I could not install RethinkDB in Ubuntu 24.04

### ISSUE THREAD

**Issue by sherchhetri** [rethinkdb/rethinkdb#7151]
I could not install RethinkDB in Ubuntu 24.04.
Can you help me.
I have followed your instruction from here(https://rethinkdb.com/docs/install/ubuntu/)I am getting this error
W: Failed to fetch https://download.rethinkdb.com/repository/ubuntu-noble/dists/noble/InRelease  500  Server Error [IP: 167.172.11.96 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by RubberArchind** [comment]
i dont know what happened with the prebuild for Ubuntu 24 but if you in a hurry you might want to try build them from source, you can follow the instruction here [https://rethinkdb.com/docs/build](https://rethinkdb.com/docs/build)

**Comment by heejit** [comment]
you can use docker

**Comment by dotnetCarpenter** [comment]
It seems that download server is down. So apt won't work. https://download.rethinkdb.com/

**Comment by gabor-boros** [comment]
Download server is up and running now (again). Closing the issue.
