### ISSUE TITLE
Provide a working default init script

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#722]
On debian 6, when I tried to run

```
sudo /etc/init.d/rethinkdb start
```

I got the error

```
rethinkdb: No instances defined in /etc/rethinkdb/instanced.d/
rethinkdb: See http://www.rethinkdb.com/docs/guides/startup
```

While the page on http://www.rethinkdb.com/docs/guides/startup perfectly explains why I got this error, I would expect rethinkdb to ship a default config file in instances.d that works.

When I install Apache, I can directly run `/etc/init.d/apache start`. It will run a dumb server, but at least I know that it's working.
It would be nice to have the same behavior with RethinkDB.

**Comment by thelinuxlich** [comment]
@srh maybe close as dupe of #1156?
