### ISSUE TITLE
Use only one port.

### ISSUE THREAD

**Issue by srh** [rethinkdb/rethinkdb#768]
Having all these ports to keep track of, which completely random numbers like "28015", "29015", and "8080", is annoying.

We should just have one port.  The type of connection can be figured out by matching the first line against magic numbers, which for client connections and intracluster connections should be comprised of a fixed number of ascii characters followed by a CRLF.  Anything that doesn't look like that is assumed to be a web connection and in any case requests are then dispatched to the appropriate handler.

The ports for administrative, intracluster, and client connections could be changed from the default to be different, if the user wanted.  (edit: That is, different from one another, so that firewall rules can be put in place.)

With this we can also get rid of the awful "port offset."  Doing port offset arithmetic when writing command lines and doing development is annoying.  Port numbers are annoying to keep track of in production too, it would be much simpler if there was just one of them.

**Comment by danielmewes** [comment]
I don't think we should do this.
