### ISSUE TITLE
Harmonize server and driver error messages

### ISSUE THREAD

**Issue by wmrowan** [rethinkdb/rethinkdb#784]
There are some error cases handled by both the server and the drivers such as argument number checking. @coffeemug would like the error messages returned by the server to match those provided by the drivers (and for the drivers to match each other). Note that in some of these cases (argument number checking in Python) the error message is defined by the language. Would could try to standardize around this fixed point but get stuck if two or more languages define the error message in this case. Note also that some 3rd party driver languages might enforce this constraint without our even knowing.

Personally, I don't think this matters very much as long as error messages are consistent within a driver and within the server. Drivers that choose to implement features like argument number checking not natively available in the language will hide the server's error messages anyway.

**Comment by srh** [comment]
Meh!  Closing.  Naturally, differences in driver languages make this tricky and also potentially bloaty.
