### ISSUE TITLE
"Invalid data collector" error message provides too little information

### ISSUE THREAD

**Issue by wmrowan** [rethinkdb/rethinkdb#785]
When you supply something other than `r.count` or `r.sum(field)` or `r.avg(field)` the server returns the message "Invalid data collector" which doesn't provide the user with enough information to fix the error. Given that there are a finite number of acceptable values (rather than a type or set of types allowable) I think it should add something like "Data collector argument must be one of ...` and list the possible options.

**Comment by danielmewes** [comment]
This stuff doesn't exist anymore.
