### ISSUE TITLE
Listing indexes when master is down?

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#798]
I was doing some heavy-duty last minute testing, and I'm delighted to report that secondary indexes work under all sorts of odd conditions with masters failing and `use_outdated` turned on. Nice! (EDIT: not that I ever doubted ya'll)

However, runing `r.table('foo', use_outdated=True).index_list()` returns a "no master available" error (the master was indeed down). Is this expected behavior, or should one be able to list indexes when the master is down and `use_outdated` is turned on?

Ping @mlucy @jdoliner

**Comment by danielmewes** [comment]
This is working since at least 1.16
