### ISSUE TITLE
r.table doesn't autocomplete in the data explorer

### ISSUE THREAD

**Issue by jdoliner** [rethinkdb/rethinkdb#829]

**Comment by mypark** [comment]
hey guys - it's been a year or more on this issue - is this on the roadmap?

**Comment by danielmewes** [comment]
@mypark Sorry, not at the moment.

Do you care about selecting a different default DB in the data explorer or about the `r.table` auto completion (while using the default `test` database)?

**Comment by mypark** [comment]
selecting the default db is what I was looking for... kind of a minor thing but seems like it should be also be pretty easy as well..

**Comment by danielmewes** [comment]
Yeah. The problem was that we weren't sure what the UI should look like back in 2013. Since then we've added a settings panel to the Data Explorer.

I'm going to close this issue in favor of https://github.com/rethinkdb/rethinkdb/issues/2948 which has seen more recent activity.
