### ISSUE TITLE
Use chroot for testing on OS X

### ISSUE THREAD

**Issue by AtnNn** [rethinkdb/rethinkdb#837]
Many users were unable to install the 1.5.0 brew package. Our OS X test build did not fail because it is run on our development boxes.

Here is an article explaining how to create a test environment for OS X:

http://www.perkin.org.uk/posts/creating-chroots-for-fun-and-mysql-testing.html

```
# Create a sparse image to hold the chroot (which isn't really a directory)
hdiutil create -fs HFS+ -size 8g -type SPARSE -volname osx-chroot ${CHROOTDIR}
hdiutil attach -mountpoint ${CHROOTDIR} ${CHROOTDIR}.sparseimage
# Either attach a DVD image or the real thing
hdiutil attach -mountpoint /Volumes/osx-install /path/to/dvd
# Install packages
for pkg in BSD BaseSystem Essentials
do
  installer -verbose \
   -pkg /Volumes/osx-install/System/Installation/Packages/${pkg}.pkg \
   -target ${CHROOTDIR}
done
# Unmount
hdiutil detach ${CHROOTDIR}
hdiutil detach /Volumes/osx-install
```

**Comment by larkost** [comment]
If we want to test hombrew installation, then a better option would be to have a complete OS X image (.dmg), and mount it with a shadow file (`hdituil attach <dmg path> -readonly -shadow <file path>`. That way when you unmount it, only the shadow file has to be discarded.

The other option is to union mount an empty dmg on top of a volume, but that is only more convenient if you already have an installed physical partition. The dmg version is generally better.

**Comment by thelinuxlich** [comment]
@srh do you think this is still an issue?
