### ISSUE TITLE
Proposal: `ceil`, `floor`, `round`

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#866]
I think we should have the following:
```ruby
> r(1.2).floor.run
1
> r(1.2).ceil.run
2
> r(1.2).round.run
1
> r(1.5).round.run
2
```

(These are the names used in Ruby for these operations.)

**Comment by neumino** [comment]
Any change to schedule that for 2.0?
It doesn't seem too hard to do, and it's really frustrating when people run into that.

Defining an alias is not super nice `floor(x) = r.expr(x).do(function(y) { return y-r.mod(y, 1) })`

**Comment by Tryneus** [comment]
@neumino - for reference, you can't use that alias anyway, because the `mod` operator isn't defined on non-integers:

```py
> r.expr(102.5).do(lambda x: x.sub(x.mod(1)))
    'RqlRuntimeError: Number not an integer: 102.5'
```

**Comment by danielmewes** [comment]
Yeah, moving to 2.0-polish.
I think these functions look fine as proposed here.

We could later add optargs to `round` to allow rounding to a given number of digits, but that's strictly an extension for later.

**Comment by timmaxw** [comment]
We should consider making a single function `round()` with an optarg for rounding up/down/nearest.

**Comment by danielmewes** [comment]
I like `floor`/`ceil`/`round` as separate terms more I think. This is pretty common in other languages.

**Comment by gchpaco** [comment]
> I like `floor/ceil/round` as separate terms

:+1: Very few people understand rounding modes, or the difference between the rounding they learned in school and banker's rounding.

**Comment by mlucy** [comment]
Planning to mark this as settled on Monday with all three terms, and with both prefix/infix notation for all three.

**Comment by VeXocide** [comment]
In CR 2756 by @Tryneus

**Comment by VeXocide** [comment]
Merged into `next` via commit 1104380ee1d65ec3dfb66cf06a9749a874af96ac

@danielmewes -- should I commit merge this into `v2.0.x` as well?

**Comment by danielmewes** [comment]
@VeXocide No, just `next` is good. We shouldn't add new features after the freeze and RC.

**Comment by tycho01** [comment]
On x.mod() not working with floats:

`r.expr(102.5).do(lambda x: x.sub(x.mod(1))).run()`

It seems the % mod does:

`r.expr(102.5).do(lambda x: x - x % 1).run()`

For me this somehow did not always succeed in returning an integer value though... in my case I seemingly had to resort to the following ugly hack; also using the Python driver, and I could assume my value would be within 100:

`floor = lambda x: r.expr(list(xrange(100))).filter(lambda y: y <= x).max()`

**Comment by danielmewes** [comment]
@tycho01 `%` in a lambda function should be the same as `mod`. It surprises me that the second one sometimes worked for you.
In any case, the upcoming release will have a `floor` function which will help with this (so you can round the float to its nearest integer value before applying `mod`).

**Comment by tycho01** [comment]
@danielmewes: Perhaps there may be a difference between Python and Javascript as well here... in Javascript I cannot get either % or .mod() to work on non-integer values, as you stated. Interestingly though, they give me different errors in JS, but yeah, not much of interest if a floor() is already planned.

**Comment by danielmewes** [comment]
@tycho01 In JavaScript we cannot overload the `%` operator, so only `mod` works in general (regardless of whether it's applied to an integer or not). That explains the different error messages.
Sorry for the inconvenience. It will become easier soon.

**Comment by tycho01** [comment]
To others interested in a temporary workaround (I had to fight a bunch of errors trying to dynamically round a float for use in limit()), here is one for Javascript that works despite the issues with mod():

```javascript
var floor = function(y) {
	var MAX_VALUE = 2^53;
	return r.range(MAX_VALUE)
	.filter(function(x){
		return r.expr(x).le(y);
	})
	.nth(-1);
};
```

**Comment by haneefmubarak** [comment]
For those who currently want to just truncate a value (ie: round to zero), this currently works well (for me, so far, YMMV):

```js
// Instead of:
.floor()
// do:
.toJSON().split('.').nth(0).coerceTo("number")
```

For instance, if you play with the data from http://www.rethinkdb.com/docs/reql-data-exploration/ and you want to get the average number of votes for all of the movies as an integer:

```js
r.db("playground").table("movies").avg("votes").toJSON().split(".").nth(0).coerceTo("number")
// returns 283968
