### ISSUE TITLE
Add a way to treat column names case-insensitively

### ISSUE THREAD

**Issue by pixelspark** [rethinkdb/rethinkdb#891]
We are experimenting with using RethinkDB as the backend for a part of our application instead of MySQL. In the application, users can create analysis queries by dragging-and-dropping building blocks (which are then internally converted to SQL/ReQL queries). For user friendliness, we decided a long time ago that (like most RDBMses) we treat column names as case-insensitive. I like the fact that RethinkDB treats property names as case-sensitive, but it makes it difficult to use in an environment where this is not the case (pun intended ;)).

It would be nice (not just for us, but for all people migrating away from SQL) if there was a way to treat column names case-insensitively in ReQL. The most straightforward way to implement this would be by adding a flag 'caseSensitive' to the '()', pluck and without operators which tells the operation whether property names need to be treated case-sensitively (the default is true of course). 

If you do not want to mess the query language up too much (a lot of operators are affected by such a change), another option would be to add a way to lower (or upper) case all the property names, e.g.: r.table('x').lowercaseProperties().pluck('someproperty') would be equivalent to r.table('x').pluck('someProperty'). This is of course already possible using JS, but it would be much nicer (and I guess more efficient) if it became a core part of ReQL.

**Comment by thelinuxlich** [comment]
@srh this would break the way ReQL is being used for years, I don't think it is a good idea, maybe close it?

**Comment by srh** [comment]
Yep, closing.  You'll need to normalize your keys in application code.
