### ISSUE TITLE
insert() with a duplicate primary key

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#899]
jlongster on IRC bumped into this problem.

So now if we try to insert a duplicate primary key, we get back an object like that:

```
{
    "unchanged":0,
    "skipped":0,
    "replaced":0,
    "inserted":0,
    "first_error":"Duplicate primary key.\nFailed assertion: false\nAt: src/rdb_protocol/terms/error.cc:14",
    "errors":1,
    "deleted":0
}
```

This object is passed in the result of the callback with the javascript driver.
It should probably be passed in the error of the callback as soon as errors > 0.

@wmrowan any thoughts about that?

**Comment by thelinuxlich** [comment]
@srh I don't think people are unsatisfied with error handling, the api was settled and things moved on.
