### ISSUE TITLE
Javascript in source distribution files should be processed by closure (and merged into a bundle file)

### ISSUE THREAD

**Issue by anatol** [rethinkdb/rethinkdb#903]
Hi

I am looking at content of files at http://download.rethinkdb.com/dist and see that precompiled/web folders contain "pristine" javascript. Is there any reason not compile it with closure compiler before creating the distribution file?

If we want to force compile the files at user-side then users should install java. It is less not an ideal solution for Linux Arch/Gentoo users who compile project at their machines.

IMHO precompiled/web should be processed by closure compiler, so Arch will avoid build dependency on java.

PS on a related note. Currently main page serves 6 css files and more than a dozen of javascript. What about merging all javascript/css files into a bundle and serve it as a one file? Less HTTP requests - better load time is.

**Comment by deontologician** [comment]
This is effectively obsolete. We now use uglify in non-debug builds since #3660
