### ISSUE TITLE
Allow more characters in names in admin panel

### ISSUE THREAD

**Issue by morsik** [rethinkdb/rethinkdb#906]
Please allow more characters in admin panel names.

Server name: at least allow '-' and '.' characters.
Datacenter: Please allow space character, if it's impossible, maybe you could make 2 fields? ID (what currently name is with limited characters) and Display Name (full utf8?).

But maybe i misunderstood how this should work...

**Comment by srh** [comment]
Essentially a dupe of, and partially resolved by, #5537.
