### ISSUE TITLE
Sharding on non-primary field

### ISSUE THREAD

**Issue by Plasma** [rethinkdb/rethinkdb#911]
Hello,

I am not a user yet but investigating RethinkDB.

Sharing based on non-primary key would also be helpful so that relevant user data can be placed on a single shard instead of possibly spanning arbitrary shards and having no data locality.

This would improve scalability by reducing the number of shards queried when fetching specific user data.

**Comment by thelinuxlich** [comment]
Something for inspiration: http://redis.io/topics/cluster-spec#keys-hash-tags

**Comment by danielmewes** [comment]
Thanks for sharing @thelinuxlich. We should probably find a way to do this without relying on certain "magic" string formats. But the general idea of hash tags is interesting.

**Comment by thelinuxlich** [comment]
@srh I think the workaround with r.uuid would be enough for this
