### ISSUE TITLE
Make implicit constraints explicit in RQL layer

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/rethinkdb#927]
Having other people work on the RQL code has exposed a few implicit constraints that I never bothered to write down.  We should add comments and/or asserts for these, or change the interface to make them hard to mess up:
- Compile time happens when a `term_t` is constructed, and runtime happens when `eval` is called on it.  So evaluating arguments in the constructor goes poorly.
- If a term can push work to the shards it has to be in the first group of `term_forbids_writes`.
- Calling `arg(0)` more than once can re-evaluate the argument.  (This is arguably just bad interface design.)

I'll add more as I run into them.

**Comment by srh** [comment]
Addressed by b51d7cd168858c9a951a93ccdd776fcd01a0329d -- closing.
