### ISSUE TITLE
Don't piggy back off of C++ exceptions in ReQL

### ISSUE THREAD

**Issue by jdoliner** [rethinkdb/rethinkdb#950]
Right now we implement ReQL exceptions using C++ exceptions this seemed easy at the time but a few months down the road @mlucy and I talked about it and agreed it was actually becoming more trouble than it's worth and leading us to make some annoying compromises and it's not too hard to get rid of them.

**Comment by danielmewes** [comment]
Superseded by more specific issues such as https://github.com/rethinkdb/rethinkdb/issues/4412 and https://github.com/rethinkdb/rethinkdb/issues/4271
