### ISSUE TITLE
Error in case the user forgets to coerce to array

### ISSUE THREAD

**Issue by neumino** [rethinkdb/rethinkdb#969]
Query:

```
r.expr({value:r.db('cakemeter').table('stars').filter({'repo': 'rethinkdb'}).map(r.row('id'))})
```

Error:

```
RqlRuntimeError: Expected type DATUM but found SEQUENCE:
OPAQUE VALUE SEQUENCE in:
{value: r.db("cakemeter").table("stars").filter({repo: "rethinkdb"}).map(function(var_0) { return r.row("id"); })}
^^
```

Questions:
- Is the backtrace broken? (javascript driver)
- Is opaque sequence a term we want to keep?
  - If yes we should document it
  - If no, we should replace it.
- Can we make the message a little more friendly like with an extra "Did you forget to coerce to an array?"

Tagging in backlog.

**Comment by srh** [comment]
Closing since all that's left is miscellaneous discussion about whether streams should be allowed in data, nothing resolveable here.
