### ISSUE TITLE
Proposal: `r.unroll`

### ISSUE THREAD

**Issue by coffeemug** [rethinkdb/rethinkdb#981]
The rationale for this is that dealing with any kind of nested arrays quickly becomes challenging when the operations are anything other than trivial because of nested lambdas. Here's what I propose:

``` ruby
> r([{:a => 1, :b => [2, 3]}, {:a => 4, :b => [5, 6]}, ]).unroll(:b)
[{:a => 1, :b => 2},
 {:a => 1, :b => 3},
 {:a => 4, :b => 5},
 {:a => 4, :b => 6}]
```

This is sugar over `concatMap` and is essentially an equivalent of a SQL cross-product between tables, but for arrays. It's especially nice because people would be able to "unroll" an array, write their processing queries on a flat table, and then "roll it back up", possible via the proposal for `distinct` (#876#issuecomment-19242517).

I see two problems with this proposal:
- Rolling things back up with `distinct` is clunky because it takes the attributes to do distinct groups by, not the arguments _not_ to group by. An alternative would be to introduce `seq.rollup(:a)` which would be an equivalent to `seq.distinct(everything_but_:a_goes_here)`. Alternatively, `distinct` could take a flag: `seq.distinct(:a, :rollup => true)`
- In SQL, a cross-product operation like this allows for efficient implementation, whereas RethinkDB does not (e.g. when someone says `seq.unroll().filter().rollup()`, we'd end up doing a lot more work than we have to because we don't have an optimizer). We might find a different way to do this, or we might bite the performance cost until we can do an optimizer (or we can try and optimize it).

**Comment by thelinuxlich** [comment]
@srh maybe close this because .fold() can cover this case?

**Comment by srh** [comment]
Leaving open for same reason as pivot/unpivot.

**Comment by srh** [comment]
Or I'll just close and see if any kittens get harmed...
